ERIS CORE: StdioStream Class Reference
StdioStream Class Reference
StdioStream implements a minimal stdio stream.
#include <StdioStream.h>
Public Member Functions
StdioStream ()
__attribute__ ((always_inline)) int getc()
__attribute__ ((always_inline)) int putc(int c)
__attribute__ ((always_inline)) int putCRLF()
void clearerr ()
int fclose ()
int feof ()
int ferror ()
int fflush ()
int fgetc ()
char * fgets (char *str, size_t num, size_t *len=0)
bool fopen (const char *path, const char *mode)
int fputc (int c)
int fputs (const char *str)
size_t fread (void *ptr, size_t size, size_t count)
int fseek (int32_t offset, int origin)
int32_t ftell ()
size_t fwrite (const void *ptr, size_t size, size_t count)
size_t print (char c)
size_t print (const char *str)
size_t print (double val, uint8_t prec=2)
size_t print (float val, uint8_t prec=2)
template<typename T >
size_t print (T val)
int printDec (char n)
int printDec (double value, uint8_t prec)
int printDec (float value, uint8_t prec)
int printDec (int16_t n)
int printDec (int32_t n)
int printDec (signed char n)
int printDec (uint16_t n)
int printDec (uint32_t n)
int printDec (unsigned char n)
int printField (double value, char term, uint8_t prec=2)
int printField (float value, char term, uint8_t prec=2)
template<typename T >
int printField (T value, char term)
int printHex (uint32_t n)
int printHexln (uint32_t n)
size_t println ()
size_t println (double val, uint8_t prec=2)
size_t println (float val, uint8_t prec=2)
template<typename T >
size_t println (T val)
bool rewind ()
int ungetc (int c)
Private Member Functions
bool fillBuf ()
int fillGet ()
bool flushBuf ()
int flushPut (uint8_t c)
char * fmtSpace (uint8_t len)
int write (const void *buf, size_t count)
Private Attributes
uint8_t m_buf [STREAM_BUF_SIZE]
uint8_t * m_p = m_buf
uint8_t m_r = 0
uint8_t m_status = 0
uint8_t m_w
Static Private Attributes
static const uint8_t S_EOF = 0x10
static const uint8_t S_ERR = 0x20
static const uint8_t S_SRD = 0x01
static const uint8_t S_SRW = 0x04
static const uint8_t S_SWR = 0x02
Detailed Description
StdioStream implements a minimal stdio stream.
StdioStream does not support subdirectories or long file names.
Definition at line 112 of file StdioStream.h.
Constructor & Destructor Documentation
StdioStream()
StdioStream::StdioStream () inline
Constructor
Definition at line 117 of file StdioStream.h.
 {}
Member Function Documentation
__attribute__() [1/3]
StdioStream::__attribute__ ((always_inline)) inline
Get a byte from the stream.
getc and fgetc are equivalent but getc is in-line so it is faster but require more flash memory.
Returns
If the end-of-file indicator for the stream is set, or if the stream is at end-of-file, the end-of-file indicator for the stream is set and the fgetc function returns EOF. Otherwise, the fgetc function returns the next character from the input stream.
Definition at line 351 of file StdioStream.h.
              {
     return m_r-- == 0 ? fillGet() : *m_p++;
   }
References fillGet(), m_p, and m_r.
__attribute__() [2/3]
StdioStream::__attribute__ ((always_inline)) inline
Write a byte to a stream.
putc and fputc are equivalent but putc is in-line so it is faster but require more flash memory.
Parameters
[in] c the byte to be written (converted to an unsigned char).
Returns
Upon successful completion, fputc() returns the value it has written. Otherwise, it returns EOF and sets the error indicator for the stream.
Definition at line 367 of file StdioStream.h.
                   {
     return m_w-- == 0 ? flushPut(c) : *m_p++ = c;
   }
References flushPut(), m_p, and m_w.
__attribute__() [3/3]
StdioStream::__attribute__ ((always_inline)) inline
Write a CR/LF.
Returns
two, the number of bytes written, for success or -1 for failure.
Definition at line 376 of file StdioStream.h.
                 {
     if (m_w < 2) {
       if (!flushBuf()) {
         return -1;
       }
     }
     *m_p++ = '\r';
     *m_p++ = '\n';
     m_w -= 2;
     return 2;
   }
References flushBuf(), m_p, and m_w.
clearerr()
void StdioStream::clearerr () inline
Clear the stream's end-of-file and error indicators.
Definition at line 120 of file StdioStream.h.
                   {
     m_status &= ~(S_ERR | S_EOF);
   }
References m_status, S_EOF, and S_ERR.
fclose()
int StdioStream::fclose ()
Close a stream.
A successful call to the fclose function causes the stream to be flushed and the associated file to be closed. Any unwritten buffered data is written to the file; any unread buffered data is discarded. Whether or not the call succeeds, the stream is disassociated from the file.
Returns
zero if the stream was successfully closed, or EOF if any any errors are detected.
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 28 of file StdioStream.cpp.
{
   int rtn = 0;
   if (!m_status) {
     return EOF;
   }
   if (m_status & S_SWR) {
     if (!flushBuf()) {
       rtn = EOF;
     }
   }
   if (!StreamBaseFile::close()) {
     rtn = EOF;
   }
   m_r = 0;
   m_w = 0;
   m_status = 0;
   return rtn;
 }
References EOF, flushBuf(), m_r, m_status, m_w, and S_SWR.
feof()
int StdioStream::feof () inline
Test the stream's end-of-file indicator.
Returns
non-zero if and only if the end-of-file indicator is set.
Definition at line 140 of file StdioStream.h.
              {
     return (m_status & S_EOF) != 0;
   }
References m_status, and S_EOF.
ferror()
int StdioStream::ferror () inline
Test the stream's error indicator.
Returns
return non-zero if and only if the error indicator is set.
Definition at line 147 of file StdioStream.h.
                {
     return (m_status & S_ERR) != 0;
   }
References m_status, and S_ERR.
fflush()
int StdioStream::fflush ()
Flush the stream.
If stream is an output stream or an update stream in which the most recent operation was not input, any unwritten data is written to the file; otherwise the call is an error since any buffered input data would be lost.
Returns
sets the error indicator for the stream and returns EOF if an error occurs, otherwise it returns zero.
Definition at line 47 of file StdioStream.cpp.
{
   if ((m_status & (S_SWR | S_SRW)) && !(m_status & S_SRD)) {
     if (flushBuf() && StreamBaseFile::sync()) {
       return 0;
     }
   }
   return EOF;
 }
References EOF, flushBuf(), m_status, S_SRD, S_SRW, and S_SWR.
fgetc()
int StdioStream::fgetc () inline
Get a byte from the stream.
Returns
If the end-of-file indicator for the stream is set, or if the stream is at end-of-file, the end-of-file indicator for the stream is set and the fgetc function returns EOF. Otherwise, the fgetc function returns the next character from the input stream.
Definition at line 170 of file StdioStream.h.
               {
     return m_r-- == 0 ? fillGet() : *m_p++;
   }
References fillGet(), m_p, and m_r.
fgets()
char * StdioStream::fgets (char * str, size_t num, size_t * len = 0)
Get a string from a stream.
The fgets function reads at most one less than the number of characters specified by num from the stream into the array pointed to by str. No additional characters are read after a new-line character (which is retained) or after end-of-file. A null character is written immediately after the last character read into the array.
Parameters
[out] str Pointer to an array of where the string is copied.
[in] num Maximum number of characters including the null character.
[out] len If len is not null and fgets is successful, the length of the string is returned.
Returns
str if successful. If end-of-file is encountered and no characters have been read into the array, the contents of the array remain unchanged and a null pointer is returned. If a read error occurs during the operation, the array contents are indeterminate and a null pointer is returned.
Definition at line 56 of file StdioStream.cpp.
{
   char* s = str;
   size_t n;
   if (num-- == 0) {
     return 0;
   }
   while (num) {
     if ((n = m_r) == 0) {
       if (!fillBuf()) {
         if (s == str) {
           return 0;
         }
         break;
       }
       n = m_r;
     }
     if (n > num) {
       n = num;
     }
     uint8_t* end = reinterpret_cast<uint8_t*>(memchr(m_p, '\n', n));
     if (end != 0) {
       n = ++end - m_p;
       memcpy(s, m_p, n);
       m_r -= n;
       m_p = end;
       s += n;
       break;
     }
     memcpy(s, m_p, n);
     m_r -= n;
     m_p += n;
     s += n;
     num -= n;
   }
   *s = 0;
   if (len) {
     *len = s - str;
   }
   return str;
 }
References fillBuf(), m_p, and m_r.
fillBuf()
bool StdioStream::fillBuf () private
Definition at line 379 of file StdioStream.cpp.
{
   if (!(m_status &
         S_SRD)) {  // check for S_ERR and S_EOF ??/////////////////
     if (!(m_status & S_SRW)) {
       m_status |= S_ERR;
       return false;
     }
     if (m_status & S_SWR) {
       if (!flushBuf()) {
         return false;
       }
       m_status &= ~S_SWR;
       m_status |= S_SRD;
       m_w = 0;
     }
   }
   m_p = m_buf + UNGETC_BUF_SIZE;
   int nr = StreamBaseFile::read(m_p, sizeof(m_buf) - UNGETC_BUF_SIZE);
   if (nr <= 0) {
     m_status |= nr < 0 ? S_ERR : S_EOF;
     m_r = 0;
     return false;
   }
   m_r = nr;
   return true;
 }
References flushBuf(), m_buf, m_p, m_r, m_status, m_w, read, S_EOF, S_ERR, S_SRD, S_SRW, S_SWR, and UNGETC_BUF_SIZE.
Referenced by fgets(), fillGet(), and fread().
fillGet()
int StdioStream::fillGet () private
Definition at line 370 of file StdioStream.cpp.
{
   if (!fillBuf()) {
     return EOF;
   }
   m_r--;
   return *m_p++;
 }
References EOF, fillBuf(), m_p, and m_r.
Referenced by __attribute__(), and fgetc().
flushBuf()
bool StdioStream::flushBuf () private
Definition at line 407 of file StdioStream.cpp.
{
   if (!(m_status &
         S_SWR)) {  // check for S_ERR ??////////////////////////
     if (!(m_status & S_SRW)) {
       m_status |= S_ERR;
       return false;
     }
     m_status &= ~S_SRD;
     m_status |= S_SWR;
     m_r = 0;
     m_w = sizeof(m_buf);
     m_p = m_buf;
     return true;
   }
   uint8_t n = m_p - m_buf;
   m_p = m_buf;
   m_w = sizeof(m_buf);
   if (StreamBaseFile::write(m_buf, n) == n) {
     return true;
   }
   m_status |= S_ERR;
   return false;
 }
References m_buf, m_p, m_r, m_status, m_w, S_ERR, S_SRD, S_SRW, and S_SWR.
Referenced by __attribute__(), fclose(), fflush(), fillBuf(), flushPut(), fmtSpace(), fseek(), rewind(), and write().
flushPut()
int StdioStream::flushPut (uint8_t c) private
Definition at line 431 of file StdioStream.cpp.
{
   if (!flushBuf()) {
     return EOF;
   }
   m_w--;
   return *m_p++ = c;
 }
References EOF, flushBuf(), m_p, and m_w.
Referenced by __attribute__(), and fputc().
fmtSpace()
char * StdioStream::fmtSpace (uint8_t len) private
Definition at line 439 of file StdioStream.cpp.
{
   if (m_w < len) {
     if (!flushBuf() || m_w < len) {
       return 0;
     }
   }
   if (len > m_w) {
     return 0;
   }
   m_p += len;
   m_w -= len;
   return reinterpret_cast<char*>(m_p);
 }
References flushBuf(), m_p, and m_w.
fopen()
bool StdioStream::fopen (const char * path, const char * mode)
Open a stream.
Open a file and associates the stream with it.
Parameters
[in] path file to be opened.
[in] mode a string that indicates the open mode.
"r" or "rb" Open a file for reading. The file must exist.
"w" or "wb" Truncate an existing to zero length or create an empty file for writing.
"wx" or "wbx" Create a file for writing. Fails if the file already exists.
"a" or "ab" Append; open or create file for writing at end-of-file.
"r+" or "rb+" or "r+b" Open a file for update (reading and writing).
"w+" or "w+b" or "wb+" Truncate an existing to zero length or create a file for update.
"w+x" or "w+bx" or "wb+x" Create a file for update. Fails if the file already exists.
"a+" or "a+b" or "ab+" Append; open or create a file for update, writing at end-of-file.
The character 'b' shall have no effect, but is allowed for ISO C standard conformance.
Opening a file with append mode causes all subsequent writes to the file to be forced to the then current end-of-file, regardless of intervening calls to the fseek function.
When a file is opened with update mode, both input and output may be performed on the associated stream. However, output shall not be directly followed by input without an intervening call to the fflush function or to a file positioning function (fseek, or rewind), and input shall not be directly followed by output without an intervening call to a file positioning function, unless the input operation encounters end-of-file.
Returns
true for success or false for failure.
Definition at line 97 of file StdioStream.cpp.
{
   oflag_t oflag;
   uint8_t m;
   switch (*mode++) {
   case 'a':
     m = O_WRONLY;
     oflag = O_CREAT | O_APPEND;
     m_status = S_SWR;
     break;
   case 'r':
     m = O_RDONLY;
     oflag = 0;
     m_status = S_SRD;
     break;
   case 'w':
     m = O_WRONLY;
     oflag = O_CREAT | O_TRUNC;
     m_status = S_SWR;
     break;
   default:
     goto fail;
   }
   while (*mode) {
     switch (*mode++) {
     case '+':
       m_status = S_SRW;
       m = O_RDWR;
       break;
     case 'b':
       break;
     case 'x':
       oflag |= O_EXCL;
       break;
     default:
       goto fail;
     }
   }
   oflag |= m;
   if (!StreamBaseFile::open(path, oflag)) {
     goto fail;
   }
   m_r = 0;
   m_w = 0;
   m_p = m_buf;
   return true;
  fail:
   m_status = 0;
   return false;
 }
References m, m_buf, m_p, m_r, m_status, m_w, mode, O_APPEND, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, S_SRD, S_SRW, and S_SWR.
fputc()
int StdioStream::fputc (int c) inline
Write a byte to a stream.
Parameters
[in] c the byte to be written (converted to an unsigned char).
Returns
Upon successful completion, fputc() returns the value it has written. Otherwise, it returns EOF and sets the error indicator for the stream.
Definition at line 268 of file StdioStream.h.
                    {
     return m_w-- == 0 ? flushPut(c) : *m_p++ = c;
   }
References flushPut(), m_p, and m_w.
Referenced by printDec().
fputs()
int StdioStream::fputs (const char * str)
Write a string to a stream.
Parameters
[in] str a pointer to the string to be written.
Returns
for success, fputs() returns a non-negative number. Otherwise, it returns EOF and sets the error indicator for the stream.
Definition at line 154 of file StdioStream.cpp.
{
   size_t len = strlen(str);
   return fwrite(str, 1, len) == len ? len : EOF;
 }
References EOF, and fwrite().
Referenced by print().
fread()
size_t StdioStream::fread (void * ptr, size_t size, size_t count)
Binary input.
Reads an array of up to count elements, each one with a size of size bytes.
Parameters
[out] ptr pointer to area of at least (size*count) bytes where the data will be stored.
[in] size the size, in bytes, of each element to be read.
[in] count the number of elements to be read.
Returns
number of elements successfully read, which may be less than count if a read error or end-of-file is encountered. If size or count is zero, fread returns zero and the contents of the array and the state of the stream remain unchanged.
Definition at line 159 of file StdioStream.cpp.
{
   uint8_t* dst = reinterpret_cast<uint8_t*>(ptr);
   size_t total = size*count;
   if (total == 0) {
     return 0;
   }
   size_t need = total;
   while (need > m_r) {
     memcpy(dst, m_p, m_r);
     dst += m_r;
     m_p += m_r;
     need -= m_r;
     if (!fillBuf()) {
       return (total - need)/size;
     }
   }
   memcpy(dst, m_p, need);
   m_r -= need;
   m_p += need;
   return count;
 }
References count, fillBuf(), m_p, and m_r.
fseek()
int StdioStream::fseek (int32_t offset, int origin)
Set the file position for the stream.
Parameters
[in] offset number of offset from the origin.
[in] origin position used as reference for the offset. It is specified by one of the following constants.
SEEK_SET - Beginning of file.
SEEK_CUR - Current position of the file pointer.
SEEK_END - End of file.
Returns
zero for success. Otherwise, it returns non-zero and sets the error indicator for the stream.
Definition at line 181 of file StdioStream.cpp.
{
   int32_t pos;
   if (m_status & S_SWR) {
     if (!flushBuf()) {
       goto fail;
     }
   }
   switch (origin) {
   case SEEK_CUR:
     pos = ftell();
     if (pos < 0) {
       goto fail;
     }
     pos += offset;
     if (!StreamBaseFile::seekCur(pos)) {
       goto fail;
     }
     break;
   case SEEK_SET:
     if (!StreamBaseFile::seekSet(offset)) {
       goto fail;
     }
     break;
   case SEEK_END:
     if (!StreamBaseFile::seekEnd(offset)) {
       goto fail;
     }
     break;
   default:
     goto fail;
   }
   m_r = 0;
   m_p = m_buf;
   return 0;
  fail:
   return EOF;
 }
References EOF, flushBuf(), ftell(), m_buf, m_p, m_r, m_status, S_SWR, SEEK_CUR, SEEK_END, and SEEK_SET.
ftell()
int32_t StdioStream::ftell ()
Get the current position in a stream.
Returns
If successful, ftell return the current value of the position indicator. On failure, ftell returns 1L.
Definition at line 223 of file StdioStream.cpp.
{
   uint32_t pos = StreamBaseFile::curPosition();
   if (m_status & S_SRD) {
     if (m_r > pos) {
       return -1L;
     }
     pos -= m_r;
   } else if (m_status & S_SWR) {
     pos += m_p - m_buf;
   }
   return pos;
 }
References m_buf, m_p, m_r, m_status, S_SRD, and S_SWR.
Referenced by fseek().
fwrite()
size_t StdioStream::fwrite (const void * ptr, size_t size, size_t count)
Binary output.
Writes an array of up to count elements, each one with a size of size bytes.
Parameters
[in] ptr pointer to (size*count) bytes of data to be written.
[in] size the size, in bytes, of each element to be written.
[in] count the number of elements to be written.
Returns
number of elements successfully written. if this number is less than count, an error has occurred. If size or count is zero, fwrite returns zero.
Definition at line 236 of file StdioStream.cpp.
{
   return write(ptr, count*size) < 0 ? EOF : count;
 }
References count, EOF, and write().
Referenced by fputs().
print() [1/5]
size_t StdioStream::print (char c) inline
Write a character.
Parameters
[in] c the character to write.
Returns
the number of bytes written.
Definition at line 393 of file StdioStream.h.
{
     return putc(c) < 0 ? 0 : 1;
   }
Referenced by print(), and println().
print() [2/5]
size_t StdioStream::print (const char * str) inline
Write a string.
Parameters
[in] str the string to be written.
Returns
the number of bytes written.
Definition at line 403 of file StdioStream.h.
{
     int n = fputs(str);
     return n < 0 ? 0 : n;
   }
References fputs().
print() [3/5]
size_t StdioStream::print (double val, uint8_t prec = 2) inline
Print a floating point number.
Parameters
[in] prec Number of digits after decimal point.
[in] val the number to be printed.
Returns
the number of bytes written.
Definition at line 426 of file StdioStream.h.
{
     return print(static_cast<float>(val), prec);
   }
References print().
print() [4/5]
size_t StdioStream::print (float val, uint8_t prec = 2) inline
Print a floating point number.
Parameters
[in] prec Number of digits after decimal point.
[in] val the number to be printed.
Returns
the number of bytes written.
Definition at line 438 of file StdioStream.h.
{
     int n = printDec(val, prec);
     return n > 0 ? n : 0;
   }
References printDec().
print() [5/5]
template<typename T > size_t StdioStream::print (T val) inline
Print a number.
Parameters
[in] val the number to be printed.
Returns
the number of bytes written.
Definition at line 450 of file StdioStream.h.
                       {
     int n = printDec(val);
     return n > 0 ? n : 0;
   }
References printDec().
printDec() [1/9]
int StdioStream::printDec (char n) inline
Print a char as a number.
Parameters
[in] n number to be printed.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 504 of file StdioStream.h.
{
     if (CHAR_MIN == 0) {
       return printDec((unsigned char)n);
     } else {
       return printDec((signed char)n);
     }
   }
Referenced by print(), printDec(), printField(), and println().
printDec() [2/9]
int StdioStream::printDec (double value, uint8_t prec) inline
Print a double.
Parameters
[in] value The number to be printed.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 555 of file StdioStream.h.
{
     return printDec(static_cast<float>(value), prec);
   }
References printDec().
printDec() [3/9]
int StdioStream::printDec (float value, uint8_t prec)
Print a float.
Parameters
[in] value The number to be printed.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 273 of file StdioStream.cpp.
{
   char buf[24];
   char *ptr = fmtDouble(buf + sizeof(buf), value, prec, false);
   return write(ptr, buf + sizeof(buf) - ptr);
 }
References buf, fmtDouble(), and write().
printDec() [4/9]
int StdioStream::printDec (int16_t n)
Print a int16_t
Parameters
[in] n number to be printed.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 289 of file StdioStream.cpp.
{
   int s;
   uint8_t rtn = 0;
   if (n < 0) {
     if (fputc('-') < 0) {
       return -1;
     }
     n = -n;
     rtn++;
   }
   if ((s = printDec((uint16_t)n)) < 0) {
     return s;
   }
   return rtn;
 }
References fputc(), and printDec().
printDec() [5/9]
int StdioStream::printDec (int32_t n)
Print a signed 32-bit integer.
Parameters
[in] n number to be printed.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 312 of file StdioStream.cpp.
{
   uint8_t s = 0;
   if (n < 0) {
     if (fputc('-') < 0) {
       return -1;
     }
     n = -n;
     s = 1;
   }
   int rtn = printDec((uint32_t)n);
   return rtn > 0 ? rtn + s : -1;
 }
References fputc(), and printDec().
printDec() [6/9]
int StdioStream::printDec (signed char n)
print a signed 8-bit integer
Parameters
[in] n number to be printed.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 279 of file StdioStream.cpp.
{
   if (n < 0) {
     if (fputc('-') < 0) {
       return -1;
     }
     n = -n;
   }
   return printDec((unsigned char)n);
 }
References fputc(), and printDec().
printDec() [7/9]
int StdioStream::printDec (uint16_t n)
print a uint16_t.
Parameters
[in] n number to be printed.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 305 of file StdioStream.cpp.
{
   char buf[5];
   char *ptr = fmtBase10(buf + sizeof(buf), n);
   uint8_t len = buf + sizeof(buf) - ptr;
   return write(ptr, len);
 }
References buf, fmtBase10(), and write().
printDec() [8/9]
int StdioStream::printDec (uint32_t n)
Write an unsigned 32-bit number.
Parameters
[in] n number to be printed.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 325 of file StdioStream.cpp.
{
   char buf[10];
   char *ptr = fmtBase10(buf + sizeof(buf), n);
   uint8_t len = buf + sizeof(buf) - ptr;
   return write(ptr, len);
 }
References buf, fmtBase10(), and write().
printDec() [9/9]
int StdioStream::printDec (unsigned char n) inline
Print an unsigned 8-bit number.
Parameters
[in] n number to be print.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 522 of file StdioStream.h.
{
     return printDec((uint16_t)n);
   }
References printDec().
printField() [1/3]
int StdioStream::printField (double value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 572 of file StdioStream.h.
{
     return printField(static_cast<float>(value), term, prec) > 0;
   }
printField() [2/3]
int StdioStream::printField (float value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 582 of file StdioStream.h.
{
     int rtn = printDec(value, prec);
     return rtn < 0 || putc(term) < 0 ? -1 : rtn + 1;
   }
References printDec().
printField() [3/3]
template<typename T > int StdioStream::printField (T value, char term) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 593 of file StdioStream.h.
{
     int rtn = printDec(value);
     return rtn < 0 || putc(term) < 0 ? -1 : rtn + 1;
   }
References printDec().
printHex()
int StdioStream::printHex (uint32_t n)
Print HEX
Parameters
[in] n number to be printed as HEX.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 332 of file StdioStream.cpp.
{
   char buf[8];
   char *ptr = fmtHex(buf + sizeof(buf), n);
   uint8_t len = buf + sizeof(buf) - ptr;
   return write(ptr, len);
 }
References buf, fmtHex(), and write().
Referenced by printHexln().
printHexln()
int StdioStream::printHexln (uint32_t n) inline
Print HEX with CRLF
Parameters
[in] n number to be printed as HEX.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 610 of file StdioStream.h.
{
     int rtn = printHex(n);
     return  rtn < 0 || putCRLF() != 2 ? -1 : rtn + 2;
   }
References printHex().
println() [1/4]
size_t StdioStream::println () inline
Write a CR/LF.
Returns
two, the number of bytes written, for success or zero for failure.
Definition at line 459 of file StdioStream.h.
                    {
     return putCRLF() > 0 ? 2 : 0;
   }
Referenced by println().
println() [2/4]
size_t StdioStream::println (double val, uint8_t prec = 2) inline
Print a floating point number followed by CR/LF.
Parameters
[in] val the number to be printed.
[in] prec Number of digits after decimal point.
Returns
the number of bytes written.
Definition at line 471 of file StdioStream.h.
{
     return println(static_cast<float>(val), prec);
   }
References println().
println() [3/4]
size_t StdioStream::println (float val, uint8_t prec = 2) inline
Print a floating point number followed by CR/LF.
Parameters
[in] val the number to be printed.
[in] prec Number of digits after decimal point.
Returns
the number of bytes written.
Definition at line 483 of file StdioStream.h.
{
     int n = printDec(val, prec);
     return n > 0 && putCRLF() > 0 ? n + 2 : 0;
   }
References printDec().
println() [4/4]
template<typename T > size_t StdioStream::println (T val) inline
Print an item followed by CR/LF
Parameters
[in] val the item to be printed.
Returns
the number of bytes written.
Definition at line 495 of file StdioStream.h.
{
     int n = print(val);
     return putCRLF() > 0 ? n + 2 : 0;
   }
References print().
rewind()
bool StdioStream::rewind ()
Set position of a stream to the beginning.
The rewind function sets the file position to the beginning of the file. It is equivalent to fseek(0L, SEEK_SET) except that the error indicator for the stream is also cleared.
Returns
true for success or false for failure.
Definition at line 339 of file StdioStream.cpp.
{
   if (m_status & S_SWR) {
     if (!flushBuf()) {
       return false;
     }
   }
   StreamBaseFile::seekSet(0);
   m_r = 0;
   return true;
 }
References flushBuf(), m_r, m_status, and S_SWR.
ungetc()
int StdioStream::ungetc (int c)
Push a byte back into an input stream.
Parameters
[in] c the byte (converted to an unsigned char) to be pushed back.
One character of push-back is guaranteed. If the ungetc function is called too many times without an intervening read or file positioning operation on that stream, the operation may fail.
A successful intervening call to a file positioning function (fseek, fsetpos, or rewind) discards any pushed-back characters for the stream.
Returns
Upon successful completion, ungetc() returns the byte pushed back after conversion. Otherwise it returns EOF.
Definition at line 350 of file StdioStream.cpp.
{
   // error if EOF.
   if (c == EOF) {
     return EOF;
   }
   // error if not reading.
   if ((m_status & S_SRD) == 0) {
     return EOF;
   }
   // error if no space.
   if (m_p == m_buf) {
     return EOF;
   }
   m_r++;
   m_status &= ~S_EOF;
   return *--m_p = (uint8_t)c;
 }
References EOF, m_buf, m_p, m_r, m_status, S_EOF, and S_SRD.
write()
int StdioStream::write (const void * buf, size_t count) private
Definition at line 240 of file StdioStream.cpp.
{
   const uint8_t* src = static_cast<const uint8_t*>(buf);
   size_t todo = count;
   while (todo > m_w) {
     memcpy(m_p, src, m_w);
     m_p += m_w;
     src += m_w;
     todo -= m_w;
     if (!flushBuf()) {
       return EOF;
     }
   }
   memcpy(m_p, src, todo);
   m_p += todo;
   m_w -= todo;
   return count;
 }
References buf, count, EOF, flushBuf(), m_p, and m_w.
Referenced by fwrite(), printDec(), and printHex().
Member Data Documentation
m_buf
uint8_t StdioStream::m_buf[STREAM_BUF_SIZE] private
Definition at line 656 of file StdioStream.h.
Referenced by fillBuf(), flushBuf(), fopen(), fseek(), ftell(), and ungetc().
m_p
uint8_t* StdioStream::m_p = m_buf private
Definition at line 658 of file StdioStream.h.
Referenced by __attribute__(), fgetc(), fgets(), fillBuf(), fillGet(), flushBuf(), flushPut(), fmtSpace(), fopen(), fputc(), fread(), fseek(), ftell(), ungetc(), and write().
m_r
uint8_t StdioStream::m_r = 0 private
Definition at line 659 of file StdioStream.h.
Referenced by __attribute__(), fclose(), fgetc(), fgets(), fillBuf(), fillGet(), flushBuf(), fopen(), fread(), fseek(), ftell(), rewind(), and ungetc().
m_status
uint8_t StdioStream::m_status = 0 private
Definition at line 657 of file StdioStream.h.
Referenced by clearerr(), fclose(), feof(), ferror(), fflush(), fillBuf(), flushBuf(), fopen(), fseek(), ftell(), rewind(), and ungetc().
m_w
uint8_t StdioStream::m_w private
Definition at line 660 of file StdioStream.h.
Referenced by __attribute__(), fclose(), fillBuf(), flushBuf(), flushPut(), fmtSpace(), fopen(), fputc(), and write().
S_EOF
const uint8_t StdioStream::S_EOF = 0x10 static private
Definition at line 653 of file StdioStream.h.
Referenced by clearerr(), feof(), fillBuf(), and ungetc().
S_ERR
const uint8_t StdioStream::S_ERR = 0x20 static private
Definition at line 654 of file StdioStream.h.
Referenced by clearerr(), ferror(), fillBuf(), and flushBuf().
S_SRD
const uint8_t StdioStream::S_SRD = 0x01 static private
Definition at line 650 of file StdioStream.h.
Referenced by fflush(), fillBuf(), flushBuf(), fopen(), ftell(), and ungetc().
S_SRW
const uint8_t StdioStream::S_SRW = 0x04 static private
Definition at line 652 of file StdioStream.h.
Referenced by fflush(), fillBuf(), flushBuf(), and fopen().
S_SWR
const uint8_t StdioStream::S_SWR = 0x02 static private
Definition at line 651 of file StdioStream.h.
Referenced by fclose(), fflush(), fillBuf(), flushBuf(), fopen(), fseek(), ftell(), and rewind().
The documentation for this class was generated from the following files:
ERISCore/lib/SdFat-master/src/iostream/StdioStream.h
ERISCore/lib/SdFat-master/src/iostream/StdioStream.cpp