ERIS CORE: AppCQT::init
init()
void FLASHMEM AppCQT::init () inline protected
Definition at line 79 of file AppCQT.h.
{
       update_priority = 1; //set to high priority
       osc_bank_size = OSC_BANK_SIZE;
       char buffer[32]; //used to build the stream names
       sprintf(name, "AppCQT"); //set the applications name
       AudioNoInterrupts();
       for (int16_t i=0; i < osc_bank_size; i++){
         sprintf(buffer, "waveform:%d", i+1);
         //request the object from the audio director
         osc[i] = (erisAudioSynthWaveform*) (ad->getAudioStreamObjByName(buffer));
         //init the object to the default state
         osc[i]->begin(0.0, 0, WAVEFORM_SINE);
       }
       AudioInterrupts();
       //take care to downcast fetched objects to the correct type!
       fft = (erisAudioAnalyzeFFT1024*) (ad->getAudioStreamObjByName("fft1024:1"));
       fft2 = (erisAudioAnalyzeFFT1024*) (ad->getAudioStreamObjByName("fft1024:2"));
       fft2->toggleActiveRange(); //switch to low range
       //zero out the data variables
       memset(&fftRVal,0,sizeof(FFTReadRange));
       memset(&oscBank,0,sizeof(FFTReadRange)* OSC_BANK_SIZE);
       //init the data dictionary value(s)
       am->data->create(OCTAVE_DOWN_INTERVAL,(int32_t)0);
       //init the QCT bins by loading the frequency ranges for each music note using a look up table
       float flow;
       float fhigh;
       high_range = CQT_HIGHRANGE_SPLIT_AT_BIN;
       for (uint16_t i=0;i < NOTE_ARRAY_LENGTH;i++){
         flow = 0;
         fhigh = 0;
         if (i > 0 && i < NOTE_ARRAY_LENGTH){
           //calculate the high and low frequencys for the given note
           //this is done by splitting the frequency differences from the music note above and below
           flow = note_freq[i] - (note_freq[i] - note_freq[i-1])/2.0;
           fhigh = note_freq[i] + (note_freq[i+1] - note_freq[i])/2.0;
         }else{
           flow = 0;
           fhigh = 0;
         }
         //zero out the destination within the array
         memset(&fftHighRR[i],0,sizeof(FFTReadRange));
         memset(&fftLowRR[i],0,sizeof(FFTReadRange));
         //write the ranges to the bins, split between the high and low range fft
         if (i >= high_range){
           fftHighRR[i].cqtBin =i;
           fftLowRR[i].cqtBin =i;
           fftHighRR[i].startFrequency = flow;
           fftLowRR[i].startFrequency =0;
           fftHighRR[i].stopFrequency =fhigh;
           fftLowRR[i].stopFrequency =0;
         }
         else{
           fftHighRR[i].cqtBin =i;
           fftLowRR[i].cqtBin =i;
           fftHighRR[i].startFrequency =0;
           fftLowRR[i].startFrequency =flow;
           fftHighRR[i].stopFrequency =0;
           fftLowRR[i].stopFrequency =fhigh;
         }
        }
       rt_calls = 0;
       update_calls = 0;
       pll_p=0.0;
       pll_f=1.0;
       //enable the fft blocks
       fft_buffer_serial_transmit_elapsed = 0;
       fft_buffer_select_for_serial_transmit = 0;
       cqt_serial_transmit_elapsed = 0;
       is_active = true;
       am->data->create(FFT_AGE_THRESHOLD,(int32_t)6);
       AudioNoInterrupts();
       fft->enableFFT(true);
       fft2->enableFFT(true);
       AudioInterrupts();
     };
References AppBaseClass::ad, AppBaseClass::am, AudioSynthWaveform::begin(), cqt_serial_transmit_elapsed, SvcDataDictionary::create(), AppManager::data, erisAudioAnalyzeFFT1024::enableFFT(), fft, fft2, fft_buffer_select_for_serial_transmit, fft_buffer_serial_transmit_elapsed, AudioDirector::getAudioStreamObjByName(), high_range, is_active, AppBaseClass::name, note_freq, osc, osc_bank_size, pll_f, pll_p, rt_calls, erisAudioAnalyzeFFT1024::toggleActiveRange(), update_calls, and AppBaseClass::update_priority.
Referenced by AppCQT().