ERIS CORE: AppCQT::render
render()
void FLASHMEM AppCQT::render () inline protected virtual
render loop
Reimplemented from AppBaseClass.
Definition at line 162 of file AppCQT.h.
{
       if (!is_active) return;
       am->requestArmSetClock(CPU_BOOST_MAX_FREQ);
       update_calls++;
       #ifdef TX_PERIODIC_FFT
         if (fft_buffer_serial_transmit_elapsed > TX_PERIOD && Serial.availableForWrite() > 5900){
           if(sci->requestStartLZ4Message()){
             fft_buffer_serial_transmit_elapsed = 0;
             if(fft_buffer_select_for_serial_transmit < 2){
               sci->printf(F("S 512"));
               for(int i = 0; i < 512; i+=1){
                 //transmitt low range then high range
                 //if(Serial.availableForWrite() < 1000){delayMicroseconds(10000);}
                 if(fft_buffer_select_for_serial_transmit == 0) sci->printf(F(",%d"),(int)(100.0*fft2->output[i]));
                 if(fft_buffer_select_for_serial_transmit == 1) sci->printf(F(",%d"),(int)(100.0*fft->output[i]));
                 //if ((i % 127)==0) Serial.flush();
               }
               sci->println("");
             }
             fft_buffer_select_for_serial_transmit += 1;
             if(fft_buffer_select_for_serial_transmit >= 2)
             {
               fft_buffer_select_for_serial_transmit = 0;
               sci->println(F("S FIN")); // end of series data
             }
             sci->sendLZ4Message();
           }
         }
       #endif
       if (cqt_serial_transmit_elapsed > TX_CQT_PERIOD && Serial.availableForWrite() > 5900){
         if(sci->requestStartLZ4Message()){
           for (uint16_t i=0;i < osc_bank_size;i++){
             if (oscBank[i].cqtBin < high_range) sci->printf(F("CQT_L %d,%s,%.0f,%.0f,%.2f,%.3f,%.3f\n"),oscBank[i].cqtBin,note_name[oscBank[i].cqtBin],oscBank[i].peakFrequency,note_freq[oscBank[i].cqtBin],oscBank[i].phase,oscBank[i].avgValueFast,oscBank[i].avgValueSlow*1000.0,oscBank[i].transientValue*100.0);
             if (oscBank[i].cqtBin >= high_range) sci->printf(F("CQT_H %d,%s,%.0f,%.0f,%.2f,%.3f,%.3f\n"),oscBank[i].cqtBin,note_name[oscBank[i].cqtBin],oscBank[i].peakFrequency,note_freq[oscBank[i].cqtBin],oscBank[i].phase,oscBank[i].avgValueFast,oscBank[i].avgValueSlow*1000.0,oscBank[i].transientValue*100.0);
           }
           sci->printf(F("CQT_EOF\n"));
           sci->sendLZ4Message();
         }
         //Serial.flush();
         cqt_serial_transmit_elapsed = 0;
         am->requestArmSetClock(CPU_BASE_FREQ);
       }
       erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftLowRR,NOTE_ARRAY_LENGTH);
       erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftHighRR,NOTE_ARRAY_LENGTH);
       erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(oscBank,osc_bank_size);
       draw->fillRoundRect(x,y,w,h,3,CL(0x07,0x00,0x10));
       //draw the scale lines
       draw->setFont(Arial_8);
       draw->setTextColor(ILI9341_DARKGREY);
       for(uint8_t i=1;i < 18; i++){
         draw->drawLine(x,y +  (h - (log1p((0.1 * i))) * h),x+w,y + (h - (log1p((0.1 * i))) * h),ILI9341_DARKCYAN);
         if (has_pop){
           draw->setCursor(x + i * 17,y+ (h - (log1p((0.1 * i))) * h) - 9);
           if (i < 17) draw->print((log1p((0.1 * i))));
         }
       }
       //draw the cqt bins
       const float im = (w-1)/(float)(sizeof(note_freq)/sizeof(note_freq[0]));
       uint16_t nx;
       float signal;
       float amp;
       for (uint16_t i=0;i< sizeof(note_freq)/sizeof(note_freq[0])-1;i++){
         amp = fftHighRR[i].peakValue;//fft->read(&fftHighRR[i]);
         signal = (log1p((amp))) * h;
         if (signal>(h-1)) signal = h-1;
         if (signal<0) signal = 0;
         nx = (uint16_t)(im*fftHighRR[i].cqtBin);
         //draw->fillRoundRect(x+nx,y,2,(uint16_t)signal,1,ILI9341_ORANGE);
         draw->fillRoundRect(x+nx,y+h - (uint16_t)signal,2,(uint16_t)signal,1,ILI9341_CYAN);
         amp = fftLowRR[i].avgValueFast;//fft2->read(&fftLowRR[i]);
         signal = (log1p((amp))) * h;
         if (signal>(h-1)) signal = h-1;
         if (signal<0) signal = 0;
         nx = (uint16_t)(im*fftLowRR[i].cqtBin);
         draw->fillRoundRect(x+nx,y+h - (uint16_t)signal,2,(uint16_t)signal,1,ILI9341_MAGENTA);
       }
       //make a second pass but only draw the oscillators
       draw->setTextColor(ILI9341_GREENYELLOW);
       for (uint16_t i=0;i < osc_bank_size;i++){
         amp = oscBank[i].avgValueFast;//fft->read(&fftHighRR[i]);
         signal = (log1p((amp))) * h;
         if (signal<0) signal = 0;
         if (signal>(h-1)) signal = h-1;
         nx = (uint16_t)(im*oscBank[i].cqtBin);
         if ((y+h - (uint16_t)signal) < h && signal > 1) draw->fillRoundRect(x+nx,y+h - (uint16_t)signal,2,4,1,CL(0xFF,0xA0,(uint8_t)(300*oscBank[i].transientValue)));
         if ((y+h - (uint16_t)signal) < h && has_pop){
           draw->setCursor(x+nx - 5,y+h - (uint16_t)signal - 15);
           draw->print(note_name[oscBank[i].cqtBin]);
           draw->setCursor(x+nx - 5,y+h - (uint16_t)signal - 25);
           draw->printf("%.0f",oscBank[i].peakFrequency);
         }
       }
       //draw the border
       draw->drawRoundRect(x,y,w,h,4,ILI9341_MAGENTA);
       if (fftHighRR[0].peakValue > fftLowRR[0].peakValue) {
         fftRVal = fftHighRR[0];
         draw->setTextColor(ILI9341_DARKCYAN);
       } else{
         fftRVal = fftLowRR[0];
         draw->setTextColor(ILI9341_MAGENTA);
       }
     }; //called only when the app is active
References AppBaseClass::am, cqt_serial_transmit_elapsed, AppBaseClass::draw, fft, fft2, fft_buffer_select_for_serial_transmit, fft_buffer_serial_transmit_elapsed, AppBaseClass::h, AppBaseClass::has_pop, high_range, is_active, note_freq, note_name, osc_bank_size, AppManager::requestArmSetClock(), SvcSerialCommandInterface::requestStartLZ4Message(), AppBaseClass::sci, SvcSerialCommandInterface::sendLZ4Message(), erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(), update_calls, AppBaseClass::w, AppBaseClass::x, and AppBaseClass::y.