ERIS CORE: AppCQT::MessageHandler
MessageHandler()
void AppCQT::MessageHandler (AppBaseClass * sender, const char * message) inline protected virtual
Reimplemented from AppBaseClass.
Definition at line 437 of file appCQT.h.
{
     if(strcmp(message,ENABLE)==0){
       onFocus();
     }else if(strcmp(message,DISABLE)==0){
       onFocusLost();
     }
     if(sender->isName("SCI")){
       Serial.print(F("M appCQT::MessageHandler SCI param: "));
       Serial.println(message);
       //Serial.flush();
       if (strcmp(message,CQT_INFO)==0){
         //sort the bins to transmit them in order
         erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftLowRR,NOTE_ARRAY_LENGTH);
         erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftHighRR,NOTE_ARRAY_LENGTH);
         for (uint16_t i=1;i< NOTE_ARRAY_LENGTH - 1;i++){
           sci->startLZ4Message();
           sci->printf(F("M L %d,%f,%f,%d,%d,%d\t\t\t"),fftLowRR[i].cqtBin,fftLowRR[i].startFrequency,fftLowRR[i].stopFrequency,fftLowRR[i].startBin,fftLowRR[i].stopBin,fftLowRR[i].stopBin-fftLowRR[i].startBin);
           sci->printf(F("M H %d,%f,%f,%d,%d,%d\n"),fftHighRR[i].cqtBin,fftHighRR[i].startFrequency,fftHighRR[i].stopFrequency,fftHighRR[i].startBin,fftHighRR[i].stopBin,fftHighRR[i].stopBin-fftHighRR[i].startBin);
           sci->endLZ4Message();
         }
         //Serial.flush();
       }
     }
   }
References SvcSerialCommandInterface::endLZ4Message(), AppBaseClass::isName(), NOTE_ARRAY_LENGTH, onFocus(), onFocusLost(), AppBaseClass::sci, erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(), and SvcSerialCommandInterface::startLZ4Message().