ERIS CORE: AppCQT::updateOscillatorBank
updateOscillatorBank()
void FASTRUN AppCQT::updateOscillatorBank (bool low_range_switch) inline protected
Definition at line 329 of file appCQT.h.
{
       bool found;
       float peak_read=-1000;
       float peak;
       if(fft==NULL || fft2==NULL) return;
       //sort the FFTReadRange array by cqt bin number
       if (low_range_switch) {erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftLowRR,NOTE_ARRAY_LENGTH);}
       else erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftHighRR,NOTE_ARRAY_LENGTH);
       //read the fft ranges, which stores the results into the FFTReadRange array
       for (uint16_t i=0; i < NOTE_ARRAY_LENGTH; i++){
         if (low_range_switch) peak = fft2->read(&fftLowRR[i]);
         else peak = fft->read(&fftHighRR[i]);
         if (peak>peak_read){
             peak_read = peak;
         }
       }
       //update the oscillator bank with the current values
       for (uint16_t i=0; i < osc_bank_size; i++){
         if (oscBank[i].cqtBin >= high_range){
           if (low_range_switch==false){
             oscBank[i] = fftHighRR[oscBank[i].cqtBin];
           }
         }else if (low_range_switch==true){
           oscBank[i] = fftLowRR[oscBank[i].cqtBin];
         }
       }
       //sort the updated cqt bins by peakValue
       if (low_range_switch){erisAudioAnalyzeFFT1024::sort_fftrr_by_value(fftLowRR,NOTE_ARRAY_LENGTH);
       } else erisAudioAnalyzeFFT1024::sort_fftrr_by_value(fftHighRR,NOTE_ARRAY_LENGTH);
       //Add the new osc settings
       //low range
       if (low_range_switch){
         for(uint16_t i=0; i < osc_bank_size; i++){
           found = false;
           for (uint16_t j=0; j < osc_bank_size; j++){
             if (oscBank[j].cqtBin == fftLowRR[i].cqtBin){
               //oscBank[j] = fftLowRR[i];
               found = true;break;
             }
           }
           if(!found){
             for(int16_t k= osc_bank_size-1; k >= 0;k--){
               if ((oscBank[k].avgValueFast) < (fftLowRR[i].avgValueFast)){
                 //fftLowRR[i].phase = 0;
                 pll_p = 0.0;
                 pll_f = 1.0;
                 oscBank[k] = fftLowRR[i];
                 break;
               }
             }
           }
         }
       } else for(uint16_t i=0; i < osc_bank_size; i++){ //high range
           found = false;
           for (uint16_t j=0; j < osc_bank_size; j++){
             if (oscBank[j].cqtBin == fftHighRR[i].cqtBin){
               //oscBank[j] = fftHighRR[i];
               found = true;break;
             }
           }
           if(!found){
             for(int16_t k= osc_bank_size-1; k >= 0;k--){
               if ((oscBank[k].avgValueFast) < (fftHighRR[i].avgValueFast)){
                 //fftHighRR[i].phase = 0;
                 pll_p = 0.0;
                 pll_f = 1.0;
                 oscBank[k] = fftHighRR[i];
                 break;
               }
             }
         }
       }
       pll_p = 0.0;
       pll_f = 1.0;
       //sort the updated cqt bins by peakValue
       if (low_range_switch){erisAudioAnalyzeFFT1024::sort_fftrr_by_value(fftLowRR,NOTE_ARRAY_LENGTH);
       } else erisAudioAnalyzeFFT1024::sort_fftrr_by_value(fftHighRR,NOTE_ARRAY_LENGTH);
       //take the phase from the dominant frequency component
       float dominantPhase = 0;
       if (low_range_switch){
           dominantPhase = fftLowRR[0].phase;
       } else dominantPhase = fftHighRR[0].phase;;
       //actually update the oscillators -- IF the data is not TOO old
       //if (updateRT_call_period > am->data->read(FFT_AGE_THRESHOLD)) return;
       for(int16_t i=0; i < osc_bank_size; i++){
         float a,f;
         float64_t phase_aligner;
         if( ( (oscBank[i].cqtBin <= high_range) && (low_range_switch == true)) || ((oscBank[i].cqtBin > high_range) && (low_range_switch == false))){
           if (oscBank[i].peakFrequency > 30.0){
             f = oscBank[i].peakFrequency;
             a = sqrt(oscBank[i].avgValueFast)/OSC_BANK_SIZE;
             if(!isnan(a)){
               phase_aligner = ((dominantPhase - oscBank[i].phase)/dominantPhase);
               phase_aligner = (phase_aligner * (float64_t)osc[i]->getPhase()) + pll_p;
               if(!isnan(phase_aligner)) phase_aligner=0;
               f = (pll_f * f * octave_down[am->data->read(OCTAVE_DOWN_INTERVAL)]);
               if (f < 20) f = 20;
               if (f > 20000) f = 20000;
               if(osc[i] != NULL){
                 osc[i]->frequency(f);
                 osc[i]->amplitude(a);
                 osc[i]->phase(phase_aligner);
               }
             };
           }
         }
       }
       return;
     }
References AppBaseClass::am, AudioSynthWaveformhd::amplitude(), avgValueFast, cqtBin, AppManager::data, fft, fft2, fftHighRR, fftLowRR, AudioSynthWaveformhd::frequency(), high_range, octave_down, osc, osc_bank_size, oscBank, peakFrequency, AudioSynthWaveformhd::phase(), pll_f, pll_p, SvcDataDictionary::read(), erisAudioAnalyzeFFT1024::read(), erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(), and erisAudioAnalyzeFFT1024::sort_fftrr_by_value().
Referenced by update().