ERIS CORE: AppCQT::messageHandler
messageHandler()
void AppCQT::messageHandler (AppBaseClass * sender, const char * message) inline protected virtual
receiver method for inter-app string based communication
Parameters
uval
fval
Reimplemented from AppBaseClass.
Definition at line 447 of file appCQT.h.
{
     if(strcmp(message,ENABLE)==0){
       onFocus();//reusing the onFocus function to ENABLE processing
     }else if(strcmp(message,DISABLE)==0){
       onFocusLost();//reusing the onFocusLost function to DISABLE processing
     }
     if(sender->isName("SCI")){
       Serial.print(F("M appCQT::MessageHandler SCI param: "));
       Serial.println(message);
       if (strcmp(message,CQT_INFO)==0){
         //sort the bins to transmit them in order
         erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftLowRR,NOTE_ARRAY_LENGTH);
         erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(fftHighRR,NOTE_ARRAY_LENGTH);
         for (uint16_t i=1;i< NOTE_ARRAY_LENGTH - 1;i++){
           if(sci->requestStartLZ4Message()){
             sci->printf(F("M L %d,%f,%f,%d,%d,%d\t\t\t"),fftLowRR[i].cqtBin,fftLowRR[i].startFrequency,fftLowRR[i].stopFrequency,fftLowRR[i].startBin,fftLowRR[i].stopBin,fftLowRR[i].stopBin-fftLowRR[i].startBin);
             sci->printf(F("M H %d,%f,%f,%d,%d,%d\n"),fftHighRR[i].cqtBin,fftHighRR[i].startFrequency,fftHighRR[i].stopFrequency,fftHighRR[i].startBin,fftHighRR[i].stopBin,fftHighRR[i].stopBin-fftHighRR[i].startBin);
             sci->sendLZ4Message();
           }
         }
       }
     }
   }
References cqtBin, fftHighRR, fftLowRR, AppBaseClass::isName(), onFocus(), onFocusLost(), SvcSerialCommandInterface::requestStartLZ4Message(), AppBaseClass::sci, SvcSerialCommandInterface::sendLZ4Message(), erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(), startBin, startFrequency, stopBin, and stopFrequency.