ERIS CORE: AppCQT::update
update()
void FLASHMEM AppCQT::update () inline protected virtual
update loop
Reimplemented from AppBaseClass.
Definition at line 279 of file appCQT.h.
{
       if (!is_active) return;
       rt_calls++;
       //if (rt_calls < 10000) return;
       if (fft == NULL || fft2 == NULL) return;
       if (fft2->capture() && fft->capture()){
         //AudioNoInterrupts();
         fft2->analyze();
         fft->analyze();
         //AudioInterrupts();
         updateOscillatorBank(true);
         updateOscillatorBank(false);
         am->data->increment(CQT_UPDATE_COUNT);
       }
       //Serial.flush();
     }; //allways called even if app is not active
References AppBaseClass::am, erisAudioAnalyzeFFT1024::analyze(), erisAudioAnalyzeFFT1024::capture(), AppManager::data, fft, fft2, SvcDataDictionary::increment(), is_active, rt_calls, and updateOscillatorBank().