ERIS CORE: AppCQT::updateRT
updateRT()
void FLASHMEM AppCQT::updateRT () inline protected
Definition at line 267 of file appCQT.h.
{
       if (!isActive) return;
       rt_calls++;
       //if (rt_calls < 10000) return;
       if (fft2->capture() && fft->capture()){
         //AudioNoInterrupts();
         fft2->analyze();
         fft->analyze();
         //AudioInterrupts();
         updateOscillatorBank(true);
         updateOscillatorBank(false);
         am->data->increment(CQT_UPDATE_COUNT);
       }
       //Serial.flush();
     }; //allways called even if app is not active
References erisAudioAnalyzeFFT1024::analyze(), erisAudioAnalyzeFFT1024::capture(), fft, fft2, isActive, rt_calls, and updateOscillatorBank().