ERIS CORE: RingBuf< F, Size > Class Template Reference
RingBuf< F, Size > Class Template Reference
Ring buffer for data loggers.
#include <RingBuf.h>
Public Member Functions
RingBuf ()
void begin (F *file)
size_t bytesFree () const
size_t bytesFreeIsr () const
size_t bytesUsed () const
size_t bytesUsedIsr () const
size_t memcpyIn (const void *buf, size_t count)
size_t memcpyOut (void *buf, size_t count)
size_t printField (double value, char term, uint8_t prec=2)
size_t printField (float value, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type value, char term)
size_t readIn (size_t count)
bool sync ()
size_t write (const char *str)
size_t write (const uint8_t *buf, size_t count) override
size_t write (const void *buf, size_t count)
size_t write (uint8_t data) override
size_t writeOut (size_t count)
Private Member Functions
uint8_t __attribute__ ((aligned(4))) m_buf[Size]
size_t advance (size_t index, size_t n)
size_t minSize (size_t a, size_t b)
Private Attributes
volatile size_t m_count
F * m_file = nullptr
size_t m_head
size_t m_tail
Detailed Description
template<class F, size_t Size>
class RingBuf< F, Size >
Ring buffer for data loggers.
This ring buffer may be used in ISRs. bytesFreeIsr(), bytesUsedIsr(), memcopyIn(), and memcopyOut() are ISR callable. For ISR use call memcopyIn() in the ISR and use writeOut() in non-interrupt code to write data to a file. readIn() and memcopyOut can be use in a similar way to provide file data to an ISR.
Print into a RingBuf in an ISR should also work but has not been verified.
Definition at line 73 of file RingBuf.h.
Constructor & Destructor Documentation
RingBuf()
template<class F , size_t Size> RingBuf< F, Size >::RingBuf () inline
RingBuf Constructor.
Definition at line 78 of file RingBuf.h.
 {}
Member Function Documentation
__attribute__()
template<class F , size_t Size> uint8_t RingBuf< F, Size >::__attribute__ ((aligned(4))) private
advance()
template<class F , size_t Size> size_t RingBuf< F, Size >::advance (size_t index, size_t n) inline private
Definition at line 359 of file RingBuf.h.
{
     index += n;
     return index < Size ? index : index - Size;
   }
Referenced by RingBuf< F, Size >::memcpyIn(), RingBuf< F, Size >::memcpyOut(), RingBuf< F, Size >::readIn(), and RingBuf< F, Size >::writeOut().
begin()
template<class F , size_t Size> void RingBuf< F, Size >::begin (F * file) inline
Initialize RingBuf.
Parameters
[in] file Underlying file.
Definition at line 83 of file RingBuf.h.
                       {
     m_file = file;
     m_count = 0;
     m_head = 0;
     m_tail = 0;
     clearWriteError();
   }
References RingBuf< F, Size >::m_count, RingBuf< F, Size >::m_file, RingBuf< F, Size >::m_head, and RingBuf< F, Size >::m_tail.
bytesFree()
template<class F , size_t Size> size_t RingBuf< F, Size >::bytesFree () const inline
Returns
the RingBuf free space in bytes. Not ISR callable.
Definition at line 94 of file RingBuf.h.
{
     size_t count;
     noInterrupts();
     count = m_count;
     interrupts();
     return Size - count;
   }
References count, and RingBuf< F, Size >::m_count.
Referenced by RingBuf< F, Size >::readIn(), and RingBuf< F, Size >::write().
bytesFreeIsr()
template<class F , size_t Size> size_t RingBuf< F, Size >::bytesFreeIsr () const inline
Returns
the RingBuf free space in bytes. ISR callable.
Definition at line 104 of file RingBuf.h.
{
     return Size - m_count;
   }
References RingBuf< F, Size >::m_count.
bytesUsed()
template<class F , size_t Size> size_t RingBuf< F, Size >::bytesUsed () const inline
Returns
the RingBuf used space in bytes. Not ISR callable.
Definition at line 110 of file RingBuf.h.
{
     size_t count;
     noInterrupts();
     count = m_count;
     interrupts();
     return count;
   }
References count, and RingBuf< F, Size >::m_count.
Referenced by RingBuf< F, Size >::sync(), and RingBuf< F, Size >::writeOut().
bytesUsedIsr()
template<class F , size_t Size> size_t RingBuf< F, Size >::bytesUsedIsr () const inline
Returns
the RingBuf used space in bytes. ISR callable.
Definition at line 120 of file RingBuf.h.
{
     return m_count;
   }
References RingBuf< F, Size >::m_count.
memcpyIn()
template<class F , size_t Size> size_t RingBuf< F, Size >::memcpyIn (const void * buf, size_t count) inline
Copy data to the RingBuf from buf. The number of bytes copied may be less than count if count is greater than bytesFree.
This function may be used in an ISR with writeOut() in non-interrupt code.
Parameters
[in] buf Location of data to be copied.
[in] count number of bytes to be copied.
Returns
Number of bytes actually copied.
Definition at line 135 of file RingBuf.h.
{
     const uint8_t* src = (const uint8_t*)buf;
     size_t n = Size - m_count;
     if (count > n) {
       count = n;
     }
     size_t nread = 0;
     while (nread != count) {
         n = minSize(Size - m_head, count - nread);
         memcpyBuf(m_buf + m_head, src + nread, n);
         m_head = advance(m_head, n);
         nread += n;
     }
     m_count += nread;
     return nread;
   }
References RingBuf< F, Size >::advance(), buf, count, RingBuf< F, Size >::m_count, RingBuf< F, Size >::m_head, memcpyBuf(), and RingBuf< F, Size >::minSize().
Referenced by RingBuf< F, Size >::write().
memcpyOut()
template<class F , size_t Size> size_t RingBuf< F, Size >::memcpyOut (void * buf, size_t count) inline
Copy date from the RingBuf to buf. The number of bytes copied may be less than count if bytesUsed is less than count.
This function may be used in an ISR with readIn() in non-interrupt code.
Parameters
[out] buf Location to receive the data.
[in] count number of bytes to be copied.
Returns
Number of bytes actually copied.
Definition at line 163 of file RingBuf.h.
{
     uint8_t* dst = reinterpret_cast<uint8_t*>(buf);
     size_t nwrite = 0;
     size_t n = m_count;
     if (count > n) {
       count = n;
     }
     while (nwrite != count) {
       n = minSize(Size - m_tail, count - nwrite);
       memcpyBuf(dst + nwrite, m_buf + m_tail, n);
       m_tail = advance(m_tail, n);
       nwrite += n;
     }
     m_count -= nwrite;
     return nwrite;
   }
References RingBuf< F, Size >::advance(), buf, count, RingBuf< F, Size >::m_count, RingBuf< F, Size >::m_tail, memcpyBuf(), and RingBuf< F, Size >::minSize().
minSize()
template<class F , size_t Size> size_t RingBuf< F, Size >::minSize (size_t a, size_t b) inline private
Definition at line 364 of file RingBuf.h.
 {return a < b ? a : b;}
Referenced by RingBuf< F, Size >::memcpyIn(), RingBuf< F, Size >::memcpyOut(), RingBuf< F, Size >::readIn(), and RingBuf< F, Size >::writeOut().
printField() [1/3]
template<class F , size_t Size> size_t RingBuf< F, Size >::printField (double value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written.
Definition at line 185 of file RingBuf.h.
{
     char buf[24];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     str = fmtDouble(str, value, prec, false);
     return write(str, buf + sizeof(buf) - str);
   }
References buf, fmtDouble(), and RingBuf< F, Size >::write().
Referenced by RingBuf< F, Size >::printField().
printField() [2/3]
template<class F , size_t Size> size_t RingBuf< F, Size >::printField (float value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 203 of file RingBuf.h.
{
     return printField(static_cast<double>(value), term, prec);
   }
References RingBuf< F, Size >::printField().
printField() [3/3]
template<class F , size_t Size> template<typename Type > size_t RingBuf< F, Size >::printField (Type value, char term) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 212 of file RingBuf.h.
{
     char sign = 0;
     char buf[3*sizeof(Type) + 3];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     if (value < 0) {
       value = -value;
       sign = '-';
     }
     if (sizeof(Type) < 4) {
       str = fmtBase10(str, (uint16_t)value);
     } else {
       str = fmtBase10(str, (uint32_t)value);
     }
     if (sign) {
       *--str = sign;
     }
     return write((const uint8_t*)str, &buf[sizeof(buf)] - str);
   }
References buf, fmtBase10(), and RingBuf< F, Size >::write().
readIn()
template<class F , size_t Size> size_t RingBuf< F, Size >::readIn (size_t count) inline
Read data into the RingBuf from the underlying file. the number of bytes read may be less than count if bytesFree is less than count.
This function may be used in non-interrupt code with memcopyOut() in an ISR.
Parameters
[in] count number of bytes to be read.
Returns
Number of bytes actually read.
Definition at line 248 of file RingBuf.h.
{
     size_t nread = 0;
     size_t n = bytesFree();  // Protected from interrupts.
     if (count > n) {
       count = n;
     }
     while (nread != count) {
         n = minSize(Size - m_head, count - nread);
         if ((size_t)m_file->read(m_buf + m_head, n) != n) {
           return nread;
         }
         m_head = advance(m_head, n);
         nread += n;
     }
     noInterrupts();
     m_count += nread;
     interrupts();
     return nread;
   }
References RingBuf< F, Size >::advance(), RingBuf< F, Size >::bytesFree(), count, RingBuf< F, Size >::m_count, RingBuf< F, Size >::m_file, RingBuf< F, Size >::m_head, and RingBuf< F, Size >::minSize().
sync()
template<class F , size_t Size> bool RingBuf< F, Size >::sync () inline
Write all data in the RingBuf to the underlying file.
Returns
true for success.
Definition at line 271 of file RingBuf.h.
               {
     size_t n = bytesUsed();
     return writeOut(n) == n;
   }
References RingBuf< F, Size >::bytesUsed(), and RingBuf< F, Size >::writeOut().
write() [1/4]
template<class F , size_t Size> size_t RingBuf< F, Size >::write (const char * str) inline
Copy str to RingBuf.
Parameters
[in] str Location of data to be written.
Returns
Number of bytes actually written.
Definition at line 299 of file RingBuf.h.
{
     return Print::write(str);
   }
write() [2/4]
template<class F , size_t Size> size_t RingBuf< F, Size >::write (const uint8_t * buf, size_t count) inline override
Override virtual function in Print for efficiency.
Parameters
[in] buf Location of data to be written.
[in] count number of bytes to be written.
Returns
Number of bytes actually written.
Definition at line 309 of file RingBuf.h.
{
     return write((const void*)buf, count);
   }
References buf, count, and RingBuf< F, Size >::write().
write() [3/4]
template<class F , size_t Size> size_t RingBuf< F, Size >::write (const void * buf, size_t count) inline
Copy data to the RingBuf from buf.
The number of bytes copied may be less than count if count is greater than bytesFree. Use getWriteError() to check for print errors and clearWriteError() to clear error.
Parameters
[in] buf Location of data to be written.
[in] count number of bytes to be written.
Returns
Number of bytes actually written.
Definition at line 287 of file RingBuf.h.
{
     if (count > bytesFree()) {
       setWriteError();
     }
     return memcpyIn(buf, count);
   }
References buf, RingBuf< F, Size >::bytesFree(), count, and RingBuf< F, Size >::memcpyIn().
Referenced by RingBuf< F, Size >::printField(), and RingBuf< F, Size >::write().
write() [4/4]
template<class F , size_t Size> size_t RingBuf< F, Size >::write (uint8_t data) inline override
Required function for Print.
Parameters
[in] data Byte to be written.
Returns
Number of bytes actually written.
Definition at line 317 of file RingBuf.h.
{
     return write(&data, 1);
   }
References data, and RingBuf< F, Size >::write().
writeOut()
template<class F , size_t Size> size_t RingBuf< F, Size >::writeOut (size_t count) inline
Write data to file from RingBuf buffer.
Parameters
[in] count number of bytes to be written.
The number of bytes written may be less than count if bytesUsed is less than count or if an error occurs.
This function may be used in non-interrupt code with memcopyIn() in an ISR.
Returns
Number of bytes actually written.
Definition at line 332 of file RingBuf.h.
{
     size_t n = bytesUsed();  // Protected from interrupts;
      if (count > n) {
       count = n;
     }
     size_t nwrite = 0;
     while (nwrite != count) {
       n = minSize(Size - m_tail, count - nwrite);
       if (m_file->write(m_buf + m_tail, n) != n) {
         break;
       }
       m_tail = advance(m_tail, n);
       nwrite += n;
     }
     noInterrupts();
     m_count -= nwrite;
     interrupts();
     return nwrite;
   }
References RingBuf< F, Size >::advance(), RingBuf< F, Size >::bytesUsed(), count, RingBuf< F, Size >::m_count, RingBuf< F, Size >::m_file, RingBuf< F, Size >::m_tail, and RingBuf< F, Size >::minSize().
Referenced by RingBuf< F, Size >::sync().
Member Data Documentation
m_count
template<class F , size_t Size> volatile size_t RingBuf< F, Size >::m_count private
Definition at line 355 of file RingBuf.h.
Referenced by RingBuf< F, Size >::begin(), RingBuf< F, Size >::bytesFree(), RingBuf< F, Size >::bytesFreeIsr(), RingBuf< F, Size >::bytesUsed(), RingBuf< F, Size >::bytesUsedIsr(), RingBuf< F, Size >::memcpyIn(), RingBuf< F, Size >::memcpyOut(), RingBuf< F, Size >::readIn(), and RingBuf< F, Size >::writeOut().
m_file
template<class F , size_t Size> F* RingBuf< F, Size >::m_file = nullptr private
Definition at line 354 of file RingBuf.h.
Referenced by RingBuf< F, Size >::begin(), RingBuf< F, Size >::readIn(), and RingBuf< F, Size >::writeOut().
m_head
template<class F , size_t Size> size_t RingBuf< F, Size >::m_head private
Definition at line 356 of file RingBuf.h.
Referenced by RingBuf< F, Size >::begin(), RingBuf< F, Size >::memcpyIn(), and RingBuf< F, Size >::readIn().
m_tail
template<class F , size_t Size> size_t RingBuf< F, Size >::m_tail private
Definition at line 357 of file RingBuf.h.
Referenced by RingBuf< F, Size >::begin(), RingBuf< F, Size >::memcpyOut(), and RingBuf< F, Size >::writeOut().
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-master/src/RingBuf.h