ERIS CORE: AudioDirector::disconnect
disconnect() [1/3]
bool AudioDirector::disconnect (AudioStream * destination, int destinationInput)
Definition at line 397 of file AudioDirector.cpp.
{
   if (NULL==destination){
     Serial.println(F("M AudioDirector::disconnect: ERROR destination is NULL"));
     return false;
   }
   //find the connection within the pool
   uint16_t i;
   for(i=0; i < MAX_CONNECTIONS;i++){
     if (p_cord[i]->pDst == destination && p_cord[i]->dest_index == destinationInput){
       Serial.print(F("M AudioDirector::disconnect() found AudioConnection at index "));
       Serial.println(i);
       //disconnect the audio connection
       if(p_cord[i]->disconnect()) active_connections--;
       Serial.println(F("M AudioDirector::disconnect() disconnect complete"));
       //Serial.flush();
       return true;
     }
   }
   Serial.println(F("M AudioDirector::disconnect() Warning: AudioConnection not found"));
   Serial.println(destination->short_name);
   Serial.println(destination->instance);
   //Serial.flush();
   return false;
 }
References active_connections, AudioStream::instance, p_cord, and AudioStream::short_name.
Referenced by audioDirectorDisconnectCallback(), disconnect(), disconnectAll(), AppAudioToPolyphonic::messageHandler(), and SvcSerialCommandInterface::update().