ERIS CORE: AudioDirector::generateFunctionList
generateFunctionList()
void AudioDirector::generateFunctionList () protected
get the list of function types in the obj pool
Definition at line 240 of file AudioDirector.cpp.
{
   //init the count and the container
   category_count=0;
   for (uint16_t j = 0; j < MAX_AUDIO_FUNCTION_CATEGORIES; j++){
     functionsList[j] = 0;
   }
   for (uint16_t i = 0; i < obj_count; i++){           //for each object
     bool found;
     found = false;
     for (uint16_t j = 0; j < MAX_AUDIO_FUNCTION_CATEGORIES; j++){   //check if cat name is already in the list
       if (functionsList[j] != 0){ //dont test uninitialized string pointers
         if (strcmp(*functionsList[j],p_audiostream_obj_pool[i]->category)==0) found = true;
       }
     }
     if (found==false) functionsList[category_count++] = (char**)&p_audiostream_obj_pool[i]->category; //add to the list if not existing
     if (category_count==MAX_AUDIO_FUNCTION_CATEGORIES) return; //limit the result list to the size of the category buffer
   }
 }
References category_count, functionsList, obj_count, and p_audiostream_obj_pool.
Referenced by AudioDirector(), getFunctionCount(), and getFunctionListItem().