ERIS CORE: AudioDirector::AudioDirector
AudioDirector() [1/2]
FLASHMEM AudioDirector::AudioDirector ()
Definition at line 23 of file AudioDirector.cpp.
{
   sci = NULL;
   obj_count=0;
   active_connections = 0;
   category_count=0;
   query_result_count=0;
   printstats_select = 0;
   AudioMemory(MAX_AUDIO_MEMORY_BLOCKS);
   //init pointer arrays
   for (uint16_t i=0; i < MAX_AUDIO_TYPES_BY_FUNCTION_QUERY_RESULT; i++){
     query_result[i]=0;
   }
   for (uint16_t j = 0; j < MAX_AUDIO_FUNCTION_CATEGORIES; j++){
     functionsList[j] =0;
   }
   p_audiostream_input_port = new erisAudioInputI2S();
   p_heap_start = p_audiostream_input_port;
   addAudioStreamObj(p_audiostream_input_port);
   addAudioStreamObj(&p_audiostream_output_port);
   addAudioStreamObj(new erisAudioAnalyzeFFT1024);
   addAudioStreamObj(new erisAudioAnalyzeFFT1024);
   addAudioStreamObj(new erisAudioAnalyzeScope);
   //addAudioStreamObj(new erisAudioAnalyzeNoteFrequency);
   addAudioStreamObj(new erisAudioEffectFreeverb);
   addAudioStreamObj(new erisAudioSynthNoisePink);
   addAudioStreamObj(new erisAudioSynthToneSweep);
   addAudioStreamObj(new erisAudioSynthWaveformSineHires);
   addAudioStreamObj(new erisAudioSynthWaveformSineModulated);
   //generate audio component pool
   for (int i=0; i < 17; i++){
     //addAudioStreamObj(new erisAudioEffectEnvelope);
     //addAudioStreamObj(new erisAudioSynthWaveformModulated);
     addAudioStreamObj(new erisAudioSynthWaveform);
   }
   for (int i=0; i < 6; i++){
     addAudioStreamObj(new erisAudioMixer4);
     //addAudioStreamObj(new erisAudioFilterStateVariable);
     addAudioStreamObj(new erisAudioFilterBiquad);
     addAudioStreamObj(new erisAudioAmplifier);
   }
   addAudioStreamObj(new erisAudioMixer8);
   addAudioStreamObj(new erisAudioMixer8);
   addAudioStreamObj(new erisAudioMixer8);
   addAudioStreamObj(new erisAudioEffectDelay);
   Serial.print(F("M AudioDirector::AudioDirector() objects: "));
   Serial.println(obj_count);
   generateFunctionList();
   Serial.print(F("M AudioDirector::AudioDirector() object categories: "));
   Serial.println(category_count);
   for (uint16_t j = 0; j < category_count; j++)Serial.printf("M %s\n",*functionsList[j]);
   AudioStream* test = getAudioStreamObjByName("mixer:2");
   Serial.println(F("M AudioDirector::AudioDirector() getAudioStreamObjByName test: (should be mixer #2)"));
   Serial.print(test->short_name);
   Serial.print(F(":"));
   Serial.println(test->instance);
   Serial.println(F("M AudioDirector::AudioDirector() building AudioConnection pool"));
   for(uint16_t i=0; i < MAX_CONNECTIONS;i++){
     p_cord[i] = new AudioConnection(NULL, (unsigned char)0,NULL, (unsigned char)0);
   }
   p_heap_end = p_cord[MAX_CONNECTIONS-1] + (p_cord[MAX_CONNECTIONS-1] - p_cord[MAX_CONNECTIONS-2]);
   Serial.print(F("M AudioDirector::AudioDirector() Estimated Memory Useage: "));
   long s = (uint32_t)p_heap_start;
   long e = (uint32_t)p_heap_end;
   Serial.print(e-s);
   Serial.println(F(" Bytes"));
 };
References active_connections, addAudioStreamObj(), category_count, functionsList, generateFunctionList(), getAudioStreamObjByName(), AudioStream::instance, obj_count, p_audiostream_input_port, p_audiostream_output_port, p_cord, p_heap_end, p_heap_start, printstats_select, query_result, query_result_count, s, sci, and AudioStream::short_name.