ERIS CORE: AudioDirector::printStats
printStats()
void FLASHMEM AudioDirector::printStats ()
Definition at line 145 of file AudioDirector.cpp.
{
   if (sci==NULL) return;
   if (printstats_select == 0){
     if(sci->requestStartLZ4Message()){
       sci->print(F("STATS {\"AudioDirector\":{"));
       sci->print(F("\"AudioStreams\":{"));
       uint16_t from, to;
       from = printstats_block++ * 16; //block size
       to = printstats_block * 16;
       if (to >= obj_count){
         to = obj_count;
         printstats_select++;
         printstats_block = 0;
       }
       for(uint16_t i=from; i < to;i++){ //transmitt in blocks
         sci->print(F("\""));
         sci->print(p_audiostream_obj_pool[i]->short_name);sci->print(F(":"));
         sci->print(p_audiostream_obj_pool[i]->instance);
         sci->print(F("\":{\"cpu\":"));
         sci->print(p_audiostream_obj_pool[i]->processorUsage());
         sci->print(F(",\"cpu_max\":"));
         sci->print(p_audiostream_obj_pool[i]->processorUsageMax());
         sci->print(F(",\"category\":\""));
         sci->print(p_audiostream_obj_pool[i]->category);sci->print(F("\""));
         sci->print(F(",\"inputs\":"));
         sci->print(p_audiostream_obj_pool[i]->unum_inputs);
         sci->print(F(",\"outputs\":"));
         sci->print(p_audiostream_obj_pool[i]->unum_outputs);
         sci->print("}"); //close obj
         if ( i < (to -1)) sci->print(",");
       }
       sci->print(F("}}}"));
       sci->sendLZ4Message();
     }
   }else if (printstats_select == 1){
     if(sci->requestStartLZ4Message()){
       sci->print(F("STATS {\"AudioDirector\":{"));
       sci->print(F("\"AudioConnectionPool\":{"));
       sci->print(F("\"active_connections\":"));
       sci->print(active_connections);
       uint16_t from, to;
       from = printstats_block++ * 32;
       to = printstats_block * 32;
       if (to >= MAX_CONNECTIONS){
         to = MAX_CONNECTIONS;
         printstats_select++;
         printstats_block = 0;
       }
       for(uint16_t i=from; i < to;i++){ //transmitt in blocks
         sci->print(F(",\""));
         sci->print(i); //connection index used as a container
         sci->print(F("\":{"));
         sci->print(F("\"inUse\":"));
         sci->print(p_cord[i]->isConnected);
         if (p_cord[i]->isConnected == true){ //assigned connections
             sci->print(F(",\"srcType\":\""));
             sci->print(p_cord[i]->pSrc->short_name);
             sci->print(F("\",\"srcInstance\":"));
             sci->print(p_cord[i]->pSrc->instance);
             sci->print(F(",\"srcPort\":"));
             sci->print(p_cord[i]->src_index);
             sci->print(F(",\"destType\":\""));
             sci->print(p_cord[i]->pDst->short_name);
             sci->print(F("\",\"destInstance\":"));
             sci->print(p_cord[i]->pDst->instance);
             sci->print(F(",\"destPort\":"));
             sci->print(p_cord[i]->dest_index);
         }else{
             //unassigned connections
             sci->print(F(",\"srcType\":\""));
             sci->print(F("None"));
             sci->print(F("\",\"srcInstance\":\""));
             sci->print(F("None"));
             sci->print(F("\",\"srcPort\":\""));
             sci->print(F("None"));
             sci->print(F("\",\"destType\":\""));
             sci->print(F("None"));
             sci->print(F("\",\"destInstance\":\""));
             sci->print(F("None"));
             sci->print(F("\",\"destPort\":\""));
             sci->print(F("None\""));
         }
         sci->print(F("}")); //close the connection container
       }
       sci->println(F("}}}")); //close the connection container
       sci->sendLZ4Message();
     }
   }else if (printstats_select == 2){
     printstats_select = 0;
     //only check 'once in a great while' as the ADC serial link is relatively slow
     if( (random(100) > 80) && (!sci->throttle())){
       sci->print(F("STATS {"));
       ExtADCPrintStatus(sci);
       sci->println(F("}"));
       sci->send();
     }
   }
 }
References active_connections, ExtADCPrintStatus(), obj_count, p_audiostream_obj_pool, p_cord, printstats_block, printstats_select, SvcSerialCommandInterface::requestStartLZ4Message(), sci, SvcSerialCommandInterface::send(), SvcSerialCommandInterface::sendLZ4Message(), and SvcSerialCommandInterface::throttle().
Referenced by SvcSerialCommandInterface::update().