ERIS CORE: AudioDirector::getAudioStreamObjByName
getAudioStreamObjByName()
AudioStream * AudioDirector::getAudioStreamObjByName (const char * AudioStreamObjName)
Definition at line 311 of file AudioDirector.cpp.
{
   //string name needs to be deccompsed to type and instance
   char *pch;
   char *ptr;
   pch = strstr (AudioStreamObjName,":");
   uint8_t instance = (uint8_t)strtoul(pch+1,&ptr,10);//instance starts 1 char from ':' and is always base 10
   for (uint16_t i = 0; i < obj_count; i++){
     //test the index first, then the string
     if (instance == p_audiostream_obj_pool[i]->instance){
         if (0==strncmp(AudioStreamObjName,p_audiostream_obj_pool[i]->short_name,strlen(p_audiostream_obj_pool[i]->short_name))) return p_audiostream_obj_pool[i];
     }
   }
   //not found return null
   if(sci->requestStartLZ4Message()){
     sci->print(F("M AudioDirector::getAudioStreamObjByName Not Found: "));
     sci->println(AudioStreamObjName);
     sci->sendLZ4Message();
   }
   return 0;
 }
References obj_count, p_audiostream_obj_pool, SvcSerialCommandInterface::requestStartLZ4Message(), sci, and SvcSerialCommandInterface::sendLZ4Message().
Referenced by AppScope::AppScope(), AudioDirector(), AppAudioToPolyphonic::changeVoice(), connect(), disconnect(), AppCQT::init(), AppAudioToPolyphonic::initialize(), AppAudioToPolyphonic::messageHandler(), SvcErisAudioParameterController::messageHandler(), AppAudioToPolyphonic::onAnalog1(), AppAudioToPolyphonic::onAnalog2(), AppAudioToPolyphonic::onAnalog3(), AppAudioToPolyphonic::onAnalog4(), and AppAudioToPolyphonic::render().