ERIS CORE: AudioDirector Class Reference
AudioDirector Class Reference
#include <AudioDirector.h>
Public Member Functions
AudioDirector ()
AudioDirector (const AudioDirector &)=delete
bool addAudioStreamObj (AudioStream *obj)
bool connect (AudioStream *source, int sourceOutput, AudioStream *destination, int destinationInput)
bool connect (char *from, uint8_t from_port, char *to, uint8_t to_port)
bool connect (const char *connectionString)
int16_t connectionCount ()
bool disconnect (AudioStream *destination, int destinationInput)
bool disconnect (char *to, uint8_t to_port)
bool disconnect (const char *connectionString)
bool disconnectAll ()
AudioStream * getAudioStreamObjByName (const char *AudioStreamObjName)
bool getAudioStreamString (uint16_t streamIndex, char *streamStringBuffer)
bool getConnectionString (uint16_t connectionIndex, char *connectionStringBuffer)
void printStats ()
void setSCI (SvcSerialCommandInterface *serialCommandInterface)
Protected Member Functions
void generateCategoryList ()
void linkGroup ()
void ParseConnectString (const char *connectionString, ParsedConnection *p)
void unlinkAll ()
Protected Attributes
uint16_t activeConnections
erisAudioOutputI2S AudioStreamOutputPort
uint16_t categoryCount
char ** categoryList [MAX_CATEGORIES]
void * heapEnd
void * heapStart
uint16_t objCount
AudioStream * pAudioStreamInputPort
AudioStream * pAudioStreamObjPool [MAX_AUDIO_STREAM_OBJECTS]
AudioConnection * pCord [MAX_CONNECTIONS]
SvcSerialCommandInterface * sci
char * shortNameQueryResult [MAX_UNIQUE_NAMES_PER_CATEGORY]
uint16_t shortNameQueryResultCount
Detailed Description
Definition at line 32 of file AudioDirector.h.
Constructor & Destructor Documentation
AudioDirector() [1/2]
AudioDirector::AudioDirector ()
Definition at line 15 of file AudioDirector.cpp.
{
   sci = NULL;
   objCount=0;
   activeConnections = 0;
   categoryCount=0;
   shortNameQueryResultCount=0;
   AudioMemory(MAX_AUDIO_MEMORY_BLOCKS);
   //init pointer arrays
   for (uint16_t i=0; i < MAX_UNIQUE_NAMES_PER_CATEGORY; i++){
     shortNameQueryResult[i]=0;
   }
   for (uint16_t j = 0; j < MAX_CATEGORIES; j++){
     categoryList[j] = (char**)&nullStr;
   }
   pAudioStreamInputPort = new erisAudioInputI2S();
   heapStart = pAudioStreamInputPort;
   addAudioStreamObj(pAudioStreamInputPort);
   addAudioStreamObj(&AudioStreamOutputPort);
   addAudioStreamObj(new erisAudioAnalyzeFFT1024);
   addAudioStreamObj(new erisAudioAnalyzeFFT1024);
   addAudioStreamObj(new erisAudioAnalyzeScope);
   //addAudioStreamObj(new erisAudioAnalyzeNoteFrequency);
   addAudioStreamObj(new erisAudioEffectFreeverb);
   addAudioStreamObj(new erisAudioSynthNoisePink);
   //generate audio component pool
   for (int i=0; i < 17; i++){
     //addAudioStreamObj(new erisAudioEffectEnvelope);
     //addAudioStreamObj(new erisAudioSynthWaveformModulated);
     addAudioStreamObj(new erisAudioSynthWaveform);
   }
   for (int i=0; i < 6; i++){
     addAudioStreamObj(new erisAudioMixer4);
     //addAudioStreamObj(new erisAudioFilterStateVariable);
     addAudioStreamObj(new erisAudioFilterBiquad);
     addAudioStreamObj(new erisAudioAmplifier);
   }
   addAudioStreamObj(new erisAudioMixer8);
   addAudioStreamObj(new erisAudioMixer8);
   addAudioStreamObj(new erisAudioMixer8);
   addAudioStreamObj(new erisAudioEffectDelay);
   Serial.print(F("M AudioDirector::AudioDirector() objects: "));
   Serial.println(objCount);
   generateCategoryList();
   Serial.print(F("M AudioDirector::AudioDirector() object categories: "));
   Serial.println(categoryCount);
   for (uint16_t j = 0; j < categoryCount; j++)Serial.println(*categoryList[j]);
   AudioStream* test = getAudioStreamObjByName("mixer_2");
   Serial.println(F("M AudioDirector::AudioDirector() getAudioStreamObjByName test: (should be mixer #2)"));
   Serial.print(test->shortName);
   Serial.print(F("_"));
   Serial.println(test->instance);
   Serial.println(F("M AudioDirector::AudioDirector() building AudioConnection pool"));
   for(uint16_t i=0; i < MAX_CONNECTIONS;i++){
     pCord[i] = new AudioConnection(NULL, (unsigned char)0,NULL, (unsigned char)0);
   }
   heapEnd = pCord[MAX_CONNECTIONS-1] + (pCord[MAX_CONNECTIONS-1] - pCord[MAX_CONNECTIONS-2]);
   Serial.print(F("M AudioDirector::AudioDirector() Estimated Memory Useage: "));
   long s = (uint32_t)heapStart;
   long e = (uint32_t)heapEnd;
   Serial.print(e-s);
   Serial.println(F(" Bytes"));
   //Serial.flush();
 };
References activeConnections, addAudioStreamObj(), AudioMemory, AudioStreamOutputPort, categoryCount, categoryList, F, generateCategoryList(), getAudioStreamObjByName(), heapEnd, heapStart, AudioStream::instance, MAX_AUDIO_MEMORY_BLOCKS, MAX_CATEGORIES, MAX_CONNECTIONS, MAX_UNIQUE_NAMES_PER_CATEGORY, NULL, nullStr, objCount, pAudioStreamInputPort, pCord, s, sci, AudioStream::shortName, shortNameQueryResult, and shortNameQueryResultCount.
AudioDirector() [2/2]
AudioDirector::AudioDirector (const AudioDirector &) delete
Member Function Documentation
addAudioStreamObj()
bool AudioDirector::addAudioStreamObj (AudioStream * obj)
Definition at line 91 of file AudioDirector.cpp.
{
   uint8_t count = 0;
   if (obj !=0 && objCount < MAX_AUDIO_STREAM_OBJECTS){
     pAudioStreamObjPool[objCount++] = obj;
     Serial.print(F("M AudioDirector::addAudioStreamObj adding obj :"));
     Serial.print(obj->category);
     Serial.print(F("->"));
     Serial.print(obj->shortName);
     if (objCount > 0){
       for(uint16_t i=0; i < objCount;i++){
         if(strcmp(obj->shortName,pAudioStreamObjPool[i]->shortName)==0) count += 1;
       }
     } else{
       heapStart = (void *)obj;
     }
     obj->instance = count;
     Serial.print(F(" instance: "));
     Serial.print(obj->instance);
     Serial.print(F(" ptr: "));
     Serial.println((uint32_t)obj);
     heapEnd = (void *)obj;
     //Serial.flush();
     return true;
   }
   return false;
 };
References AudioStream::category, count, F, heapEnd, heapStart, AudioStream::instance, MAX_AUDIO_STREAM_OBJECTS, objCount, pAudioStreamObjPool, and AudioStream::shortName.
Referenced by AudioDirector().
connect() [1/3]
bool AudioDirector::connect (AudioStream * source, int sourceOutput, AudioStream * destination, int destinationInput)
Definition at line 264 of file AudioDirector.cpp.
{
   uint16_t i;
   if (NULL==source||NULL==destination) return false;
   //check if already existing
   for(i=0; i < MAX_CONNECTIONS;i++){
     if(source==pCord[i]->pSrc && destination==pCord[i]->pDst && sourceOutput==pCord[i]->src_index && destinationInput==pCord[i]->dest_index){
       //Serial.print(F("M AudioDirector::connect() found existing connection; reconnecting at index  "));
       //Serial.println(i);
       //Serial.flush();
       if(pCord[i]->reconnect()) activeConnections++;
       return true;
     }
   }
   //find a free connection from the pool
   for(i=0; i < MAX_CONNECTIONS;i++){
     //find any already existing but unused connections
     if (NULL!=pCord[i]){
       if (pCord[i]->isConnected == false){
         //Serial.printf(F("M \tAudioDirector::connect() connection index: %d\t"),i);
         //Serial.printf("%s_%d:%d -> %s_%d:%d  ",source->shortName,source->instance,sourceOutput,destination->shortName,destination->instance,destinationInput);
         //Serial.flush();
         if(pCord[i]->rewire(source, (unsigned char)sourceOutput,destination, (unsigned char)destinationInput)) activeConnections++;
         return true;
       }
     }
     if (NULL==pCord[i]){
       Serial.print(F("M AudioDirector::connect() making a new AudioConnection at index "));
       Serial.println(i);
       /*
       Serial.print(source->shortName);Serial.print(F(":"));
       Serial.print(sourceOutput);
       Serial.print(F(" -> "));
       Serial.print(destination->shortName);Serial.print(F(":"));
       Serial.println(destinationInput);
       */
       //Serial.flush();
       //need to rewire after creation as the reference based approach was bypassed
       //in favor of pointers in order to facilitate the extention of the audio connection base class
       pCord[i] = new AudioConnection(source, (unsigned char)sourceOutput,destination, (unsigned char)destinationInput);
       pCord[i]->rewire(source, (unsigned char)sourceOutput,destination, (unsigned char)destinationInput);
       return true;
     }
   }
   Serial.print(F("M AudioDirector::connect() Error: No free audio connection available"));
   return false; //no empty connection slots
 }
References activeConnections, F, MAX_CONNECTIONS, NULL, pCord, AudioConnection::rewire(), and source.
Referenced by connect(), AppAudioToPolyphonic::makeAudioConnections(), AppAudioToPolyphonic::MessageHandler(), and SvcSerialCommandInterface::updateRT().
connect() [2/3]
bool AudioDirector::connect (char * from, uint8_t from_port, char * to, uint8_t to_port)
Definition at line 312 of file AudioDirector.cpp.
{
   return connect(getAudioStreamObjByName((char* )from),from_port,getAudioStreamObjByName((char* )to),to_port);
 }
References connect(), and getAudioStreamObjByName().
connect() [3/3]
bool AudioDirector::connect (const char * connectionString)
Definition at line 356 of file AudioDirector.cpp.
{
   ParsedConnection p;
   ParseConnectString(connectionString,&p);
   connect(p.src,p.src_port,p.dst,p.dst_port);
   return false;
 }
References connect(), p, and ParseConnectString().
connectionCount()
int16_t AudioDirector::connectionCount () inline
Definition at line 46 of file AudioDirector.h.
 {return activeConnections;};
References activeConnections.
disconnect() [1/3]
bool AudioDirector::disconnect (AudioStream * destination, int destinationInput)
Definition at line 367 of file AudioDirector.cpp.
{
   if (NULL==destination){
     Serial.println(F("M AudioDirector::disconnect: ERROR destination is NULL"));
     return false;
   }
   //find the connection within the pool
   uint16_t i;
   for(i=0; i < MAX_CONNECTIONS;i++){
     if (pCord[i]->pDst == destination && pCord[i]->dest_index == destinationInput){
       Serial.print(F("M AudioDirector::disconnect() found AudioConnection at index "));
       Serial.println(i);
       //disconnect the audio connection
       if(pCord[i]->disconnect()) activeConnections--;
       Serial.println(F("M AudioDirector::disconnect() disconnect complete"));
       //Serial.flush();
       return true;
     }
   }
   Serial.println(F("M AudioDirector::disconnect() Warning: AudioConnection not found"));
   Serial.println(destination->shortName);
   Serial.println(destination->instance);
   //Serial.flush();
   return false;
 }
References activeConnections, F, AudioStream::instance, MAX_CONNECTIONS, NULL, pCord, and AudioStream::shortName.
Referenced by disconnect(), disconnectAll(), AppAudioToPolyphonic::MessageHandler(), and SvcSerialCommandInterface::updateRT().
disconnect() [2/3]
bool AudioDirector::disconnect (char * to, uint8_t to_port)
Definition at line 363 of file AudioDirector.cpp.
{
   return disconnect(getAudioStreamObjByName((char* )to),to_port);
 }
References disconnect(), and getAudioStreamObjByName().
disconnect() [3/3]
bool AudioDirector::disconnect (const char * connectionString)
Definition at line 392 of file AudioDirector.cpp.
{
   return false;
 };
disconnectAll()
bool AudioDirector::disconnectAll ()
Definition at line 396 of file AudioDirector.cpp.
{
   for(uint16_t i=0; i < MAX_CONNECTIONS; i++){
     if(pCord[i]->disconnect()) activeConnections--;
   }
   return false;
 };
References activeConnections, disconnect(), MAX_CONNECTIONS, and pCord.
Referenced by AppAudioToPolyphonic::makeAudioConnections().
generateCategoryList()
void AudioDirector::generateCategoryList () protected
Definition at line 193 of file AudioDirector.cpp.
{
   //called from the constructor
   bool found;
   categoryCount=0;
   for (uint16_t i = 0; i < objCount; i++){           //for each object
     found = false;
     for (uint16_t j = 0; j < MAX_CATEGORIES; j++){   //check if cat name is already in the list
       if (categoryList[j] != 0){ //dont test unitialized string pointers
         if (strcmp(*categoryList[j],pAudioStreamObjPool[i]->category)==0) found = true;
       }
     }
     if (found==false) categoryList[categoryCount++] = (char**)&pAudioStreamObjPool[i]->category; //add to the list if not existing
     if (categoryCount==MAX_CATEGORIES) return; //limit the result list to the size of the category buffer
   }
 }
References categoryCount, categoryList, MAX_CATEGORIES, objCount, and pAudioStreamObjPool.
Referenced by AudioDirector().
getAudioStreamObjByName()
AudioStream * AudioDirector::getAudioStreamObjByName (const char * AudioStreamObjName)
Definition at line 209 of file AudioDirector.cpp.
{
   //string name needs to be deccompsed to type and instance
   char *pch;
   char *ptr;
   pch = strstr (AudioStreamObjName,"_");
   uint8_t instance = (uint8_t)strtoul(pch+1,&ptr,10);//instance starts 1 char from '_' and is always base 10
   for (uint16_t i = 0; i < objCount; i++){
     //test the index first, then the string
     if (instance == pAudioStreamObjPool[i]->instance){
         if (0==strncmp(AudioStreamObjName,pAudioStreamObjPool[i]->shortName,strlen(pAudioStreamObjPool[i]->shortName))) return pAudioStreamObjPool[i];
     }
   }
   //not found return null
   Serial.print(F("M AudioDirector::getAudioStreamObjByName Not Found: "));
   Serial.println(AudioStreamObjName);
   return 0;
 }
References F, objCount, and pAudioStreamObjPool.
Referenced by AppScope::AppScope(), AudioDirector(), AppAudioToPolyphonic::changeVoice(), connect(), disconnect(), AppCQT::init(), AppAudioToPolyphonic::initMyAppExample(), AppAudioToPolyphonic::MessageHandler(), AppAudioToPolyphonic::onAnalog1(), AppAudioToPolyphonic::onAnalog2(), AppAudioToPolyphonic::onAnalog3(), AppAudioToPolyphonic::onAnalog4(), and AppAudioToPolyphonic::update().
getAudioStreamString()
bool AudioDirector::getAudioStreamString (uint16_t streamIndex, char * streamStringBuffer)
Definition at line 228 of file AudioDirector.cpp.
{
   if (streamIndex >= objCount){
     strcpy(streamStringBuffer,"");
     return false;
   }
   sprintf(streamStringBuffer,"%s %s_%d",pAudioStreamObjPool[streamIndex]->category,pAudioStreamObjPool[streamIndex]->shortName,pAudioStreamObjPool[streamIndex]->instance);
   return true;
 }
References objCount, and pAudioStreamObjPool.
getConnectionString()
bool AudioDirector::getConnectionString (uint16_t connectionIndex, char * connectionStringBuffer)
Definition at line 237 of file AudioDirector.cpp.
{
   //STUB
   uint16_t i;
   uint16_t count = 0;
   if (connectionIndex >= activeConnections){
     strcpy(connectionStringBuffer,"");
     return false;
   }
   for(i=0; i < MAX_CONNECTIONS;i++){
     if (pCord[i]->isConnected == true){
       if(count == connectionIndex){
         //build connection string into the buffer
         sprintf(connectionStringBuffer,"connect(%s_%d,%d,%s_%d,%d);",
           pCord[i]->pSrc->shortName,
           pCord[i]->pSrc->instance,
           pCord[i]->src_index,
           pCord[i]->pDst->shortName,
           pCord[i]->pDst->instance,
           pCord[i]->dest_index);
         if (connectionIndex < activeConnections) return true;
       }
       count++;
     }
   }
   strcpy(connectionStringBuffer,"");
   return false;
 }
References activeConnections, count, AudioConnection::dest_index, AudioStream::instance, MAX_CONNECTIONS, pCord, AudioConnection::pDst, AudioConnection::pSrc, AudioStream::shortName, and AudioConnection::src_index.
Referenced by SvcSerialCommandInterface::updateRT().
linkGroup()
void AudioDirector::linkGroup () protected
ParseConnectString()
void AudioDirector::ParseConnectString (const char * connectionString, ParsedConnection * p) protected
Definition at line 316 of file AudioDirector.cpp.
{
 //parse connectionString
   //format: "SRCTYPE(CHAR)_INSTANCE(INT) SRCPORT(INT) DESTTYPE(CHAR)_INSTANCE(INT) DESTPORT(INT)"
   //example: "MIXER_2 0 CHORUS_1 1"
   //the example above connects mixer instance 2 output 0 with chorus instance 1 input 1
   char buffer[MAX_CONNECTION_STRING_LENGTH];
   char *token;
   if(strlen(connectionString)>MAX_CONNECTION_STRING_LENGTH-1) return;
   memset(buffer, '\0', sizeof(buffer));
   memset(p->src, '\0', sizeof(p->src));
   memset(p->dst, '\0', sizeof(p->dst));
   strcpy(buffer,connectionString);
   token = strtok(buffer, " ");
   if(strlen(token)>MAX_NAME_LENGTH-1) return;
   strcpy(p->src,token);
   token = strtok(NULL, " ");
   if(strlen(token)>MAX_NAME_LENGTH-1) return;
   p->src_port = atoi(token);
   token = strtok(NULL, " ");
   if(strlen(token)>MAX_NAME_LENGTH-1) return;
   strcpy(p->dst,token);
   token = strtok(NULL, " ");
   p->dst_port = atoi(token);
   /*
   Serial.print(F("AudioDirector::ParseConnectString "));
   //Serial.println(connectionString);
   Serial.print(F("Source: "));Serial.print(p->src);Serial.print(F(" Port:"));Serial.print(p->src_port);
   Serial.print(F("\tDest: "));Serial.print(p->dst);Serial.print(F(" Port:"));Serial.println(p->dst_port);
   //Serial.flush();
   */
   return;
 }
References MAX_CONNECTION_STRING_LENGTH, MAX_NAME_LENGTH, NULL, p, and token.
Referenced by connect().
printStats()
void AudioDirector::printStats ()
Definition at line 119 of file AudioDirector.cpp.
{
   long s = (uint32_t)heapStart;
   long e = (uint32_t)heapEnd;
   if (sci==NULL) return;
   sci->startLZ4Message();
   sci->print(F("STATS {\"AudioDirector\":{"));
   //send audio object pool info
   sci->print(F("\"AudioStreamObjPool\":{"));
   for(uint16_t i=0; i < objCount;i++){
     sci->print(F("\""));
     sci->print(pAudioStreamObjPool[i]->shortName);sci->print(F("_"));
     sci->print(pAudioStreamObjPool[i]->instance);
     sci->print(F("\":{\"processorUsage\":"));
     sci->print(pAudioStreamObjPool[i]->processorUsage());
     sci->print(F(",\"processorUsageMax\":"));
     sci->print(pAudioStreamObjPool[i]->processorUsageMax());
     sci->print(F(",\"category\":\""));
     sci->print(pAudioStreamObjPool[i]->category);sci->print(F("\""));
     sci->print(F(",\"inputs\":"));
     sci->print(pAudioStreamObjPool[i]->unum_inputs);
     sci->print(F(",\"outputs\":"));
     sci->print(pAudioStreamObjPool[i]->unum_outputs);
     sci->print("}"); //close obj
     if ( i < (objCount -1)) sci->print(",");
   }
   sci->print("},");
   sci->endLZ4Message();
   //send connection pool info
   sci->startLZ4Message();
   sci->print(F("\"AudioConnectionPool\":{"));
   sci->print(F("\"activeConnections\":"));
   sci->print(activeConnections);
   //for each...
   for(uint16_t i=0; i < MAX_CONNECTIONS;i++){
     sci->print(F(",\""));
     sci->print(i); //connection index used as a container
     sci->print(F("\":{"));
     sci->print(F("\"isConnected\":"));
     sci->print(pCord[i]->isConnected);
     if (pCord[i]->isConnected == true){
         //assigned connections
         sci->print(F(",\"sourceName\":\""));
         sci->print(pCord[i]->pSrc->shortName);
         sci->print(F("\",\"sourceInstance\":"));
         sci->print(pCord[i]->pSrc->instance);
         sci->print(F(",\"sourcePort\":"));
         sci->print(pCord[i]->src_index);
         sci->print(F(",\"destName\":\""));
         sci->print(pCord[i]->pDst->shortName);
         sci->print(F("\",\"destInstance\":"));
         sci->print(pCord[i]->pDst->instance);
         sci->print(F(",\"destPort\":"));
         sci->print(pCord[i]->dest_index);
     }else{
         //unassigned connections
     }
     sci->print(F("}")); //close the connection container
   }
   sci->print(F("}")); // close the coonection pool container
   sci->endLZ4Message();
   //throw in some audio director stats
   sci->startLZ4Message();
   sci->print(F(",\"AudioStreamObjCount\":")); sci->print(objCount);
   sci->print(F(",\"memory\":"));
   sci->print(e-s);
   sci->println(F("}}"));
   sci->endLZ4Message();
   //sci->flush();
 }
References activeConnections, SvcSerialCommandInterface::endLZ4Message(), F, heapEnd, heapStart, MAX_CONNECTIONS, NULL, objCount, pAudioStreamObjPool, pCord, s, sci, and SvcSerialCommandInterface::startLZ4Message().
Referenced by SvcSerialCommandInterface::updateRT().
setSCI()
void AudioDirector::setSCI (SvcSerialCommandInterface * serialCommandInterface) inline
Definition at line 48 of file AudioDirector.h.
 {sci = serialCommandInterface;}
References sci.
Referenced by setup().
unlinkAll()
void AudioDirector::unlinkAll () protected
Member Data Documentation
activeConnections
uint16_t AudioDirector::activeConnections protected
Definition at line 60 of file AudioDirector.h.
Referenced by AudioDirector(), connect(), connectionCount(), disconnect(), disconnectAll(), getConnectionString(), and printStats().
AudioStreamOutputPort
erisAudioOutputI2S AudioDirector::AudioStreamOutputPort protected
Definition at line 56 of file AudioDirector.h.
Referenced by AudioDirector().
categoryCount
uint16_t AudioDirector::categoryCount protected
Definition at line 62 of file AudioDirector.h.
Referenced by AudioDirector(), and generateCategoryList().
categoryList
char** AudioDirector::categoryList[MAX_CATEGORIES] protected
Definition at line 64 of file AudioDirector.h.
Referenced by AudioDirector(), and generateCategoryList().
heapEnd
void* AudioDirector::heapEnd protected
Definition at line 53 of file AudioDirector.h.
Referenced by AudioDirector(), addAudioStreamObj(), and printStats().
heapStart
void* AudioDirector::heapStart protected
Definition at line 52 of file AudioDirector.h.
Referenced by AudioDirector(), addAudioStreamObj(), and printStats().
objCount
uint16_t AudioDirector::objCount protected
Definition at line 61 of file AudioDirector.h.
Referenced by AudioDirector(), addAudioStreamObj(), generateCategoryList(), getAudioStreamObjByName(), getAudioStreamString(), and printStats().
pAudioStreamInputPort
AudioStream* AudioDirector::pAudioStreamInputPort protected
Definition at line 55 of file AudioDirector.h.
Referenced by AudioDirector().
pAudioStreamObjPool
AudioStream* AudioDirector::pAudioStreamObjPool[MAX_AUDIO_STREAM_OBJECTS] protected
Definition at line 54 of file AudioDirector.h.
Referenced by addAudioStreamObj(), generateCategoryList(), getAudioStreamObjByName(), getAudioStreamString(), and printStats().
pCord
AudioConnection* AudioDirector::pCord[MAX_CONNECTIONS] protected
Definition at line 66 of file AudioDirector.h.
Referenced by AudioDirector(), connect(), disconnect(), disconnectAll(), getConnectionString(), and printStats().
sci
SvcSerialCommandInterface* AudioDirector::sci protected
Definition at line 51 of file AudioDirector.h.
Referenced by AudioDirector(), printStats(), and setSCI().
shortNameQueryResult
char* AudioDirector::shortNameQueryResult[MAX_UNIQUE_NAMES_PER_CATEGORY] protected
Definition at line 65 of file AudioDirector.h.
Referenced by AudioDirector().
shortNameQueryResultCount
uint16_t AudioDirector::shortNameQueryResultCount protected
Definition at line 63 of file AudioDirector.h.
Referenced by AudioDirector().
The documentation for this class was generated from the following files:
AudioDirector.h
AudioDirector.cpp