ERIS CORE: AudioDirector::connect
connect() [1/3]
bool AudioDirector::connect (AudioStream * source, int sourceOutput, AudioStream * destination, int destinationInput)
Definition at line 297 of file AudioDirector.cpp.
{
   uint16_t i;
   if (NULL==source||NULL==destination) return false;
   //check if already existing
   for(i=0; i < MAX_CONNECTIONS;i++){
     if(source==p_cord[i]->pSrc && destination==p_cord[i]->pDst && sourceOutput==p_cord[i]->src_index && destinationInput==p_cord[i]->dest_index){
       Serial.printf(F("M AudioDirector::connect() found existing connection; reconnecting at index %hu\n"),i);
       //Serial.println(i);
       //Serial.flush();
       if(p_cord[i]->reconnect()) active_connections++;
       return true;
     }
   }
   //find a free connection from the pool
   for(i=0; i < MAX_CONNECTIONS;i++){
     //find any already existing but unused connections
     if (NULL!=p_cord[i]){
       if (p_cord[i]->isConnected == false){
         Serial.printf(F("M AudioDirector::connect() connection index: %hu\n"),i);
         //Serial.printf("%s_%d:%d -> %s_%d:%d  ",source->shortName,source->instance,sourceOutput,destination->shortName,destination->instance,destinationInput);
         //Serial.flush();
         if(p_cord[i]->rewire(source, (unsigned char)sourceOutput,destination, (unsigned char)destinationInput)) active_connections++;
         return true;
       }
     }
     if (NULL==p_cord[i]){
       Serial.printf(F("M AudioDirector::connect() making a new AudioConnection at index %hu\n"),i);
       /*
       Serial.print(source->shortName);Serial.print(F(":"));
       Serial.print(sourceOutput);
       Serial.print(F(" -> "));
       Serial.print(destination->shortName);Serial.print(F(":"));
       Serial.println(destinationInput);
       */
       //Serial.flush();
       //need to rewire after creation as the reference based approach was bypassed
       //in favor of pointers in order to facilitate the extention of the audio connection base class
       p_cord[i] = new AudioConnection(source, (unsigned char)sourceOutput,destination, (unsigned char)destinationInput);
       p_cord[i]->rewire(source, (unsigned char)sourceOutput,destination, (unsigned char)destinationInput);
       return true;
     }
   }
   Serial.print(F("M AudioDirector::connect() Error: No free audio connection available"));
   return false; //no empty connection slots
 }
References active_connections, MAX_CONNECTIONS, p_cord, and AudioConnection::rewire().
Referenced by audioDirectorConnectCallback(), connect(), AppAudioToPolyphonic::makeAudioConnections(), AppAudioToPolyphonic::messageHandler(), and SvcSerialCommandInterface::update().