ERIS CORE: FmtNumber.cpp File Reference
FmtNumber.cpp File Reference
#include "FmtNumber.h"
Macros
#define divmod10_asm16(in32, mod8, tmp8)
#define divmod10_asm32(in32, mod8, tmp8)
#define USE_FMT_BASE10 1
Functions
char * fmtBase10 (char *str, uint16_t n)
char * fmtBase10 (char *str, uint32_t n)
char * fmtDouble (char *str, double num, uint8_t prec, bool altFmt)
char * fmtDouble (char *str, double value, uint8_t prec, bool altFmt, char expChar)
char * fmtHex (char *str, uint32_t n)
char * fmtSigned (char *str, int32_t num, uint8_t base, bool caps)
char * fmtUnsigned (char *str, uint32_t num, uint8_t base, bool caps)
float scale10 (float v, int8_t n)
float scanFloat (const char *str, const char **ptr)
Variables
static const float m [] = {1e-1, 1e-2, 1e-4, 1e-8, 1e-16, 1e-32}
static const size_t MAX_PREC = sizeof(powTen)/sizeof(powTen[0])
static const float p [] = {1e+1, 1e+2, 1e+4, 1e+8, 1e+16, 1e+32}
static const double powTen [] = {1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9}
static const double rnd []
Macro Definition Documentation
divmod10_asm16
#define divmod10_asm16 (in32, mod8, tmp8)
Value:
asm volatile(\
      " ldi %2,51     \n\t"     \
      " mul %A0,%2    \n\t"     \
      " clr %A0       \n\t"     \
      " add r0,%2     \n\t"     \
      " adc %A0,r1    \n\t"     \
      " mov %1,r0     \n\t"     \
      " mul %B0,%2    \n\t"     \
      " clr %B0       \n\t"     \
      " add %A0,r0    \n\t"     \
      " adc %B0,r1    \n\t"     \
      " clr r1        \n\t"     \
      " add %1,%A0    \n\t"     \
      " adc %A0,%B0   \n\t"     \
      " adc %B0,r1   \n\t"      \
      " add %1,%B0    \n\t"     \
      " adc %A0,r1   \n\t"      \
      " adc %B0,r1    \n\t"     \
      " lsr %B0       \n\t"     \
      " ror %A0       \n\t"     \
      " ror %1        \n\t"     \
      " ldi %2,10     \n\t"     \
      " mul %1,%2     \n\t"     \
      " mov %1,r1     \n\t"     \
      " clr r1        \n\t"     \
      :"+r"(in32), "=d"(mod8), "=d"(tmp8) : : "r0")
Definition at line 43 of file FmtNumber.cpp.
divmod10_asm32
#define divmod10_asm32 (in32, mod8, tmp8)
Definition at line 71 of file FmtNumber.cpp.
USE_FMT_BASE10
#define USE_FMT_BASE10 1
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 27 of file FmtNumber.cpp.
Function Documentation
fmtBase10() [1/2]
char* fmtBase10 (char * str, uint16_t n)
Definition at line 161 of file FmtNumber.cpp.
{
   while (n > 9) {
 #ifdef USE_STIMMER
     uint8_t tmp8, r;
     divmod10_asm16(n, r, tmp8);
 #else  // USE_STIMMER
     uint16_t t = n;
     n = (n >> 1) + (n >> 2);
     n = n + (n >> 4);
     n = n + (n >> 8);
     // n = n + (n >> 16);  // no code for 16-bit n
     n = n >> 3;
     uint8_t r = t - (((n << 2) + n) << 1);
     if (r > 9) {
       n++;
       r -= 10;
     }
 #endif  // USE_STIMMER
     *--str = r + '0';
   }
   *--str = n + '0';
   return str;
 }
References divmod10_asm16.
Referenced by fmtBase10(), fmtDouble(), fmtUnsigned(), fsFmtField(), StdioStream::printDec(), BufferedPrint< WriteClass, BUF_DIM >::printField(), ExFatFile::printField(), FatFile::printField(), RingBuf< F, Size >::printField(), and FatFile::printFileSize().
fmtBase10() [2/2]
char* fmtBase10 (char * str, uint32_t n)
Definition at line 186 of file FmtNumber.cpp.
{
   while (n > 0XFFFF) {
 #ifdef USE_STIMMER
     uint8_t tmp8, r;
     divmod10_asm32(n, r, tmp8);
 #else  //  USE_STIMMER
     uint32_t t = n;
     n = (n >> 1) + (n >> 2);
     n = n + (n >> 4);
     n = n + (n >> 8);
     n = n + (n >> 16);
     n = n >> 3;
     uint8_t r = t - (((n << 2) + n) << 1);
     if (r > 9) {
       n++;
       r -= 10;
     }
 #endif  // USE_STIMMER
     *--str = r + '0';
   }
   return fmtBase10(str, (uint16_t)n);
 }
References divmod10_asm32, and fmtBase10().
fmtDouble() [1/2]
char* fmtDouble (char * str, double num, uint8_t prec, bool altFmt)
Definition at line 247 of file FmtNumber.cpp.
{
   bool neg = num < 0;
   if (neg) {
     num = -num;
   }
   if (isnan(num)) {
     *--str = 'n';
     *--str = 'a';
     *--str = 'n';
     return str;
   }
   if (isinf(num)) {
     *--str = 'f';
     *--str = 'n';
     *--str = 'i';
     return str;
   }
   // last float < 2^32
   if (num > 4294967040.0) {
     *--str = 'f';
     *--str = 'v';
     *--str = 'o';
     return str;
   }
   if (prec > MAX_PREC) {
     prec = MAX_PREC;
   }
   num += rnd[prec];
   uint32_t ul = num;
   if (prec) {
     char* s = str - prec;
     uint32_t f = (num - ul)*powTen[prec - 1];
     str = fmtBase10(str, f);
     while (str > s) {
       *--str = '0';
     }
   }
   if (prec || altFmt) {
     *--str = '.';
   }
   str = fmtBase10(str, ul);
   if (neg) {
     *--str = '-';
   }
   return str;
 }
References fmtBase10(), MAX_PREC, powTen, rnd, and s.
Referenced by StdioStream::printDec(), BufferedPrint< WriteClass, BUF_DIM >::printField(), ExFatFile::printField(), FatFile::printField(), RingBuf< F, Size >::printField(), and vfprintf().
fmtDouble() [2/2]
char* fmtDouble (char * str, double value, uint8_t prec, bool altFmt, char expChar)
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] ptr Pointer to last char in buffer.
[in] prec Number of digits after decimal point.
[in] expChar Use exp format if non zero.
Returns
Pointer to first character of result.
Definition at line 302 of file FmtNumber.cpp.
{
   if (expChar != 'e' && expChar != 'E') {
     expChar = 0;
   }
   bool neg = value < 0;
   if (neg) {
     value = -value;
   }
   // check for nan inf ovf
   if (isnan(value)) {
     *--str = 'n';
     *--str = 'a';
     *--str = 'n';
     return str;
   }
   if (isinf(value)) {
     *--str = 'f';
     *--str = 'n';
     *--str = 'i';
     return str;
   }
   if (!expChar && value > 4294967040.0) {
     *--str = 'f';
     *--str = 'v';
     *--str = 'o';
     return str;
   }
   if (prec > 9) {
     prec = 9;
   }
   if (expChar) {
     int8_t exp = 0;
     bool expNeg = false;
     if (value) {
       if (value > 10.0L) {
         while (value > 1e16L) {
           value *= 1e-16L;
           exp += 16;
         }
         while (value > 1e4L) {
           value *= 1e-4L;
           exp += 4;
         }
         while (value > 10.0L) {
           value *= 0.1L;
           exp++;
         }
       } else if (value < 1.0L) {
          while (value < 1e-16L) {
           value *= 1e16L;
           exp -= 16;
         }
          while (value < 1e-4L) {
           value *= 1e4L;
           exp -= 4;
         }
         while (value < 1.0L) {
           value *= 10.0L;
           exp--;
         }
       }
       value += rnd[prec];
       if (value >= 10.0L) {
         value *= 0.1L;
         exp++;
       }
       expNeg = exp < 0;
       if (expNeg) {
         exp = -exp;
       }
     }
     str = fmtBase10(str, (uint16_t)exp);
     if (exp < 10) {
       *--str = '0';
     }
     *--str = expNeg ? '-' : '+';
     *--str = expChar;
   } else {
     // round value
     value += rnd[prec];
   }
   uint32_t whole = value;
   if (prec) {
     char* tmp = str - prec;
     uint32_t fraction = (value - whole)*powTen[prec - 1];
     str = fmtBase10(str, fraction);
     while (str > tmp) {
       *--str = '0';
     }
   }
   if (prec || altFmt)*--str = '.';
   str = fmtBase10(str, whole);
   if (neg) {
     *--str = '-';
   }
   return str;
 }
References fmtBase10(), powTen, and rnd.
fmtHex()
char* fmtHex (char * str, uint32_t n)
Definition at line 209 of file FmtNumber.cpp.
{
   do {
     uint8_t h = n & 0XF;
     *--str = h + (h < 10 ? '0' : 'A' - 10);
     n >>= 4;
   } while (n);
   return str;
 }
Referenced by StdioStream::printHex().
fmtSigned()
char* fmtSigned (char * str, int32_t num, uint8_t base, bool caps)
Definition at line 218 of file FmtNumber.cpp.
{
   bool neg = base == 10 && num < 0;
   if (neg) {
     num = -num;
   }
   str = fmtUnsigned(str, num, base, caps);
   if (neg) {
     *--str = '-';
   }
   return str;
 }
References fmtUnsigned().
Referenced by vmprintf().
fmtUnsigned()
char* fmtUnsigned (char * str, uint32_t num, uint8_t base, bool caps)
Definition at line 230 of file FmtNumber.cpp.
{
 #if USE_FMT_BASE10
   if (base == 10) return fmtBase10(str, (uint32_t)num);
 #endif  // USE_FMT_BASE10
   do {
     int c = num%base;
     *--str = c + (c < 10 ? '0' : caps ? 'A' - 10 : 'a' - 10);
   } while (num /= base);
   return str;
 }
References fmtBase10().
Referenced by fmtSigned(), vfprintf(), and vmprintf().
scale10()
float scale10 (float v, int8_t n)
Definition at line 414 of file FmtNumber.cpp.
{
   const float *s;
   if (n < 0) {
     n = -n;
     s = m;
   } else {
     s = p;
   }
   n &= 63;
   for (uint8_t i = 0; n; n >>= 1, i++) {
 #ifdef __AVR__
     if (n & 1) {
       v *= pgm_read_float(&s[i]);
     }
 #else  // __AVR__
     if (n & 1) {
       v *= s[i];
     }
 #endif  // __AVR__
   }
   return v;
 }
References m, p, and s.
Referenced by scanFloat().
scanFloat()
float scanFloat (const char * str, const char ** ptr)
Definition at line 437 of file FmtNumber.cpp.
{
   int16_t const EXP_LIMIT = 100;
   bool digit = false;
   bool dot = false;
   uint32_t fract = 0;
   int fracExp = 0;
   uint8_t nd = 0;
   bool neg;
   int c;
   float v;
   const char* successPtr = str;
   if (ptr) {
     *ptr = str;
   }
   while (isSpace((c = *str++))) {}
   neg = c == '-';
   if (c == '-' || c == '+') {
     c = *str++;
   }
   // Skip leading zeros
   while (c == '0') {
     c = *str++;
     digit = true;
   }
   for (;;) {
     if (isDigit(c)) {
       digit = true;
       if (nd < 9) {
         fract = 10*fract + c - '0';
         nd++;
         if (dot) {
           fracExp--;
         }
       } else {
         if (!dot) {
           fracExp++;
         }
       }
     } else if (c == '.') {
       if (dot) {
         goto fail;
       }
       dot = true;
     } else {
       if (!digit) {
         goto fail;
       }
       break;
     }
     successPtr = str;
     c = *str++;
   }
   if (c == 'e' || c == 'E') {
     int exp = 0;
     c = *str++;
     bool expNeg = c == '-';
     if (c == '-' || c == '+') {
       c = *str++;
     }
     while (isDigit(c)) {
       if (exp > EXP_LIMIT) {
         goto fail;
       }
       exp = 10*exp + c - '0';
       successPtr = str;
       c = *str++;
     }
     fracExp += expNeg ? -exp : exp;
   }
   if (ptr) {
     *ptr = successPtr;
   }
   v = scale10(static_cast<float>(fract), fracExp);
   return neg ? -v : v;
  fail:
   return 0;
 }
References EXP_LIMIT, isDigit(), isSpace(), and scale10().
Variable Documentation
m
const float m[] = {1e-1, 1e-2, 1e-4, 1e-8, 1e-16, 1e-32} static
Definition at line 409 of file FmtNumber.cpp.
Referenced by SharedSpiCard::erase(), ostream::fmtNum(), StdioStream::fopen(), ExFatFormatter::format(), istream::getNumber(), istream::getStr(), LZ4_NbCommonBytes(), ExFatFile::printFileSize(), println64(), and scale10().
MAX_PREC
const size_t MAX_PREC = sizeof(powTen)/sizeof(powTen[0]) static
Definition at line 245 of file FmtNumber.cpp.
Referenced by fmtDouble().
p
const float p[] = {1e+1, 1e+2, 1e+4, 1e+8, 1e+16, 1e+32} static
Definition at line 410 of file FmtNumber.cpp.
Referenced by scale10().
powTen
const double powTen[] = {1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9} static
Definition at line 242 of file FmtNumber.cpp.
Referenced by fmtDouble().
rnd
const double rnd[] static
Initial value:
=
  {5e-1, 5e-2, 5e-3, 5e-4, 5e-5, 5e-6, 5e-7, 5e-8, 5e-9, 5e-10}
Definition at line 243 of file FmtNumber.cpp.
Referenced by fmtDouble().