ERIS CORE: AppBaseClass::requestPopUp
requestPopUp()
void AppBaseClass::requestPopUp (bool exclusive = false) protected inherited
request popup from the AppManager
will be activated by the next render loop
applications in popup mode are guaranteed to be rendered last; preventing any overdraw
exclusive mode option blocks the render calls of all other apps by the AppManager usefull
for taking over full screen rendering while allowing the apps update loops to continue.
Parameters
exclusive
Definition at line 86 of file AppBaseClass.cpp.
{
     has_pop = true;
     AppManager::getInstance()->requestPopUp(this->id,exclusive);
     _updatePosition();
     return;
 }
References AppBaseClass::_updatePosition(), AppManager::getInstance(), AppBaseClass::has_pop, and AppManager::requestPopUp().
Referenced by AppCQT::onTouch(), AppScope::onTouch(), and AppWren::requestPopUp().