ERIS CORE: AppBaseClass::getFocus
getFocus()
void AppBaseClass::getFocus () inherited
Get focus from the AppManager.
Definition at line 71 of file AppBaseClass.cpp.
{
     has_focus = true;
     AppManager::getInstance()->getFocus(this->id);
     _updatePosition();
     return;
 }
References AppBaseClass::_updatePosition(), AppManager::getFocus(), AppManager::getInstance(), and AppBaseClass::has_focus.
Referenced by AppWren::getFocus(), and setup().