ERIS CORE: AppBaseClass::MessageHandler
MessageHandler()
virtual void AppBaseClass::MessageHandler (AppBaseClass * sender, const char * message) inline virtual
Reimplemented in AppWren, AppTemplate, AppCQT, and AppAudioToPolyphonic.
Definition at line 109 of file AppBaseClass.h.
 {};
Referenced by ControlSlider::onTouchDrag(), ControlSlider::onTouchRelease(), and ControlButton::onTouchRelease().