ERIS CORE: AppBaseClass::_updatePosition
_updatePosition()
void AppBaseClass::_updatePosition () protected inherited
Definition at line 56 of file AppBaseClass.cpp.
{
   if(has_focus || has_pop){
     w = width;
     h = height;
     x = origin_x;
     y = origin_y;
   }else{
     w = widget_width;
     h = widget_height;
     x = widget_origin_x;
     y = widget_origin_y;
   }
   return;
 }
References AppBaseClass::h, AppBaseClass::has_focus, AppBaseClass::has_pop, AppBaseClass::height, AppBaseClass::origin_x, AppBaseClass::origin_y, AppBaseClass::w, AppBaseClass::widget_height, AppBaseClass::widget_origin_x, AppBaseClass::widget_origin_y, AppBaseClass::widget_width, AppBaseClass::width, AppBaseClass::x, and AppBaseClass::y.
Referenced by AppBaseClass::getFocus(), AppBaseClass::releasePopUp(), AppBaseClass::requestPopUp(), AppBaseClass::returnFocus(), AppBaseClass::setDimension(), AppBaseClass::setPosition(), AppBaseClass::setWidgetDimension(), and AppBaseClass::setWidgetPosition().