ERIS CORE: AppBaseClass::isName
isName()
bool AppBaseClass::isName (const char * name_string) inline inherited
Definition at line 83 of file AppBaseClass.h.
{
       bool is;
       (0==strncmp(name,name_string,sizeof(name)))?is=true:is=false;
       return is;
     };
References is, and AppBaseClass::name.
Referenced by AppManager::getAppByName(), AppAIfES::messageHandler(), AppAudioToPolyphonic::messageHandler(), AppCQT::messageHandler(), AppTemplate::messageHandler(), AppWren::messageHandler(), and AppManager::sendMessage().