ERIS CORE: AppBaseClass::onFocus
onFocus()
virtual void AppBaseClass::onFocus () inline virtual inherited
Event handler called when the app gains focus.
Reimplemented in SvcErisAudioParameterController, AppWren, AppTemplate, AppAIfES, AppScope, AppCQT, and AppAudioToPolyphonic.
Definition at line 177 of file AppBaseClass.h.
 {};
Referenced by AppManager::getFocus(), AppManager::returnFocus(), and AppManager::update().