ERIS CORE: AppBaseClass::onFocusLost
onFocusLost()
virtual void AppBaseClass::onFocusLost () inline virtual inherited
Event handler called when the app loses focus.
Reimplemented in SvcMIDI, SvcErisAudioParameterController, ControlSlider, ControlButton, AppWren, AppTemplate, AppAIfES, AppScope, and AppCQT.
Definition at line 183 of file AppBaseClass.h.
 {};
Referenced by AppManager::getFocus(), AppManager::returnFocus(), and AppManager::update().