ERIS CORE: AppBaseClass::setWidgetPosition
setWidgetPosition()
void AppBaseClass::setWidgetPosition (int16_t new_origin_x, int16_t new_origin_y) inline inherited
Set the Widget Position object.
Parameters
new_origin_x
new_origin_y
Definition at line 136 of file AppBaseClass.h.
 {widget_origin_x=new_origin_x;widget_origin_y=new_origin_y;_updatePosition();}
References AppBaseClass::_updatePosition(), AppBaseClass::widget_origin_x, and AppBaseClass::widget_origin_y.
Referenced by AppAudioToPolyphonic::initalize(), and AppWren::setWidgetPosition().