ERIS CORE: wren_compiler.h File Reference
wren_compiler.h File Reference
#include "wren.h"
#include "wren_value.h"
Typedefs
typedef struct sCompiler Compiler
Functions
void wrenBindMethodCode (ObjClass *classObj, ObjFn *fn)
ObjFn * wrenCompile (WrenVM *vm, ObjModule *module, const char *source, bool isExpression, bool printErrors)
void wrenMarkCompiler (WrenVM *vm, Compiler *compiler)
Typedef Documentation
Compiler
typedef struct sCompiler Compiler
Definition at line 1 of file wren_compiler.h.
Function Documentation
wrenBindMethodCode()
void wrenBindMethodCode (ObjClass * classObj, ObjFn * fn)
Definition at line 3843 of file wren_compiler.c.
 {
   int ip = 0;
   for (;;)
   {
     Code instruction = (Code)fn->code.data[ip];
     switch (instruction)
     {
       case CODE_LOAD_FIELD:
       case CODE_STORE_FIELD:
       case CODE_LOAD_FIELD_THIS:
       case CODE_STORE_FIELD_THIS:
         // Shift this class's fields down past the inherited ones. We don't
         // check for overflow here because we'll see if the number of fields
         // overflows when the subclass is created.
         fn->code.data[ip + 1] += classObj->superclass->numFields;
         break;
       case CODE_SUPER_0:
       case CODE_SUPER_1:
       case CODE_SUPER_2:
       case CODE_SUPER_3:
       case CODE_SUPER_4:
       case CODE_SUPER_5:
       case CODE_SUPER_6:
       case CODE_SUPER_7:
       case CODE_SUPER_8:
       case CODE_SUPER_9:
       case CODE_SUPER_10:
       case CODE_SUPER_11:
       case CODE_SUPER_12:
       case CODE_SUPER_13:
       case CODE_SUPER_14:
       case CODE_SUPER_15:
       case CODE_SUPER_16:
       {
         // Fill in the constant slot with a reference to the superclass.
         int constant = (fn->code.data[ip + 3] << 8) | fn->code.data[ip + 4];
         fn->constants.data[constant] = OBJ_VAL(classObj->superclass);
         break;
       }
       case CODE_CLOSURE:
       {
         // Bind the nested closure too.
         int constant = (fn->code.data[ip + 1] << 8) | fn->code.data[ip + 2];
         wrenBindMethodCode(classObj, AS_FN(fn->constants.data[constant]));
         break;
       }
       case CODE_END:
         return;
       default:
         // Other instructions are unaffected, so just skip over them.
         break;
     }
     ip += 1 + getByteCountForArguments(fn->code.data, fn->constants.data, ip);
   }
 }
References AS_FN, fn, getByteCountForArguments(), sObjClass::numFields, OBJ_VAL, and sObjClass::superclass.
Referenced by bindMethod().
wrenCompile()
ObjFn* wrenCompile (WrenVM * vm, ObjModule * module, const char * source, bool isExpression, bool printErrors)
Definition at line 3762 of file wren_compiler.c.
 {
   // Skip the UTF-8 BOM if there is one.
   if (strncmp(source, "\xEF\xBB\xBF", 3) == 0) source += 3;
   Parser parser;
   parser.vm = vm;
   parser.module = module;
   parser.source = source;
   parser.tokenStart = source;
   parser.currentChar = source;
   parser.currentLine = 1;
   parser.numParens = 0;
   // Zero-init the current token. This will get copied to previous when
   // nextToken() is called below.
   parser.next.type = TOKEN_ERROR;
   parser.next.start = source;
   parser.next.length = 0;
   parser.next.line = 0;
   parser.next.value = UNDEFINED_VAL;
   parser.printErrors = printErrors;
   parser.hasError = false;
   // Read the first token into next
   nextToken(&parser);
   // Copy next -> current
   nextToken(&parser);
   int numExistingVariables = module->variables.count;
   Compiler compiler;
   initCompiler(&compiler, &parser, NULL, false);
   ignoreNewlines(&compiler);
   if (isExpression)
   {
     expression(&compiler);
     consume(&compiler, TOKEN_EOF, "Expect end of expression.");
   }
   else
   {
     while (!match(&compiler, TOKEN_EOF))
     {
       definition(&compiler);
       // If there is no newline, it must be the end of file on the same line.
       if (!matchLine(&compiler))
       {
         consume(&compiler, TOKEN_EOF, "Expect end of file.");
         break;
       }
     }
     emitOp(&compiler, CODE_END_MODULE);
   }
   emitOp(&compiler, CODE_RETURN);
   // See if there are any implicitly declared module-level variables that never
   // got an explicit definition. They will have values that are numbers
   // indicating the line where the variable was first used.
   for (int i = numExistingVariables; i < parser.module->variables.count; i++)
   {
     if (IS_NUM(parser.module->variables.data[i]))
     {
       // Synthesize a token for the original use site.
       parser.previous.type = TOKEN_NAME;
       parser.previous.start = parser.module->variableNames.data[i]->value;
       parser.previous.length = parser.module->variableNames.data[i]->length;
       parser.previous.line = (int)AS_NUM(parser.module->variables.data[i]);
       error(&compiler, "Variable is used but not defined.");
     }
   }
   return endCompiler(&compiler, "(script)", 8);
 }
References AS_NUM, consume(), definition(), emitOp(), endCompiler(), error(), expression(), ignoreNewlines(), initCompiler(), IS_NUM, match(), matchLine(), nextToken(), NULL, source, TOKEN_EOF, TOKEN_ERROR, TOKEN_NAME, UNDEFINED_VAL, and ObjModule::variables.
Referenced by compileInModule().
wrenMarkCompiler()
void wrenMarkCompiler (WrenVM * vm, Compiler * compiler)
Definition at line 3904 of file wren_compiler.c.
 {
   wrenGrayValue(vm, compiler->parser->current.value);
   wrenGrayValue(vm, compiler->parser->previous.value);
   wrenGrayValue(vm, compiler->parser->next.value);
   // Walk up the parent chain to mark the outer compilers too. The VM only
   // tracks the innermost one.
   do
   {
     wrenGrayObj(vm, (Obj*)compiler->fn);
     wrenGrayObj(vm, (Obj*)compiler->constants);
     wrenGrayObj(vm, (Obj*)compiler->attributes);
     if (compiler->enclosingClass != NULL)
     {
       wrenBlackenSymbolTable(vm, &compiler->enclosingClass->fields);
       if(compiler->enclosingClass->methodAttributes != NULL)
       {
         wrenGrayObj(vm, (Obj*)compiler->enclosingClass->methodAttributes);
       }
       if(compiler->enclosingClass->classAttributes != NULL)
       {
         wrenGrayObj(vm, (Obj*)compiler->enclosingClass->classAttributes);
       }
     }
     compiler = compiler->parent;
   }
   while (compiler != NULL);
 }
References NULL, wrenBlackenSymbolTable(), wrenGrayObj(), and wrenGrayValue().
Referenced by wrenCollectGarbage().