ERIS CORE: StreamBasic Class Reference
StreamBasic Class Reference abstract
#include <PrintBasic.h>
Public Member Functions
virtual int available ()=0
void clearWriteError ()
int getWriteError ()
virtual int peek ()=0
size_t print (char c)
size_t print (const __FlashStringHelper *str)
size_t print (const char *str)
size_t print (double n, uint8_t prec=2)
size_t print (int n, uint8_t base=10)
size_t print (long n, uint8_t base=10)
size_t print (signed char n, uint8_t base=10)
size_t print (unsigned char n, uint8_t base=10)
size_t print (unsigned int n, uint8_t base=10)
size_t print (unsigned long n, uint8_t base=10)
size_t println ()
size_t println (char c)
size_t println (const __FlashStringHelper *str)
size_t println (const char *str)
size_t println (double n, uint8_t prec=2)
size_t println (int n, uint8_t base=10)
size_t println (long n, uint8_t base=10)
size_t println (signed char n, uint8_t base=10)
size_t println (unsigned char n, uint8_t base=10)
size_t println (unsigned int n, uint8_t base=10)
size_t println (unsigned long n, uint8_t base=10)
virtual int read ()=0
size_t write (const char *buffer, size_t size)
size_t write (const char *str)
virtual size_t write (const uint8_t *buffer, size_t size)
virtual size_t write (uint8_t b)=0
Protected Member Functions
void setWriteError (int err=1)
Detailed Description
Definition at line 163 of file PrintBasic.h.
Member Function Documentation
available()
virtual int StreamBasic::available () pure virtual
clearWriteError()
void PrintBasic::clearWriteError () inline inherited
Definition at line 58 of file PrintBasic.h.
{
     setWriteError(0);
   }
References PrintBasic::setWriteError().
getWriteError()
int PrintBasic::getWriteError () inline inherited
Definition at line 61 of file PrintBasic.h.
                       {
     return m_error;
   }
peek()
virtual int StreamBasic::peek () pure virtual
print() [1/10]
size_t PrintBasic::print (char c) inline inherited
Definition at line 64 of file PrintBasic.h.
{
     return write(c);
   }
References PrintBasic::write().
Referenced by PrintBasic::print(), and PrintBasic::println().
print() [2/10]
size_t PrintBasic::print (const __FlashStringHelper * str) inline inherited
Definition at line 70 of file PrintBasic.h.
{
 #ifdef __AVR__
   PGM_P p = reinterpret_cast<PGM_P>(str);
   size_t n = 0;
   for (uint8_t c; (c = pgm_read_byte(p + n)) && write(c); n++) {}
   return n;
 #else  // __AVR__
   return print(reinterpret_cast<const char *>(str));
 #endif  // __AVR__
   }
print() [3/10]
size_t PrintBasic::print (const char * str) inline inherited
Definition at line 67 of file PrintBasic.h.
{
     return write(str);
   }
References PrintBasic::write().
print() [4/10]
size_t PrintBasic::print (double n, uint8_t prec = 2) inline inherited
Definition at line 87 of file PrintBasic.h.
{
     return printDouble(n, prec);
   }
print() [5/10]
size_t PrintBasic::print (int n, uint8_t base = 10) inline inherited
Definition at line 96 of file PrintBasic.h.
{
     return print((long)n, base);
   }
References PrintBasic::print().
print() [6/10]
size_t PrintBasic::print (long n, uint8_t base = 10) inherited
Copyright (c) 2011-2019 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 28 of file PrintBasic.cpp.
{
   if (n < 0 && base == 10) {
     return print('-') + printNum(-n, base);
   }
   return printNum(n, base);
 }
References PrintBasic::print().
print() [7/10]
size_t PrintBasic::print (signed char n, uint8_t base = 10) inline inherited
Definition at line 90 of file PrintBasic.h.
{
     return print((long)n, base);
   }
References PrintBasic::print().
print() [8/10]
size_t PrintBasic::print (unsigned char n, uint8_t base = 10) inline inherited
Definition at line 93 of file PrintBasic.h.
{
     return print((unsigned long)n, base);
   }
References PrintBasic::print().
print() [9/10]
size_t PrintBasic::print (unsigned int n, uint8_t base = 10) inline inherited
Definition at line 99 of file PrintBasic.h.
{
     return print((unsigned long)n, base);
   }
References PrintBasic::print().
print() [10/10]
size_t PrintBasic::print (unsigned long n, uint8_t base = 10) inline inherited
Definition at line 103 of file PrintBasic.h.
{
     return printNum(n, base);
   }
println() [1/11]
size_t PrintBasic::println () inline inherited
Definition at line 106 of file PrintBasic.h.
                    {
     return write("\r\n");
   }
References PrintBasic::write().
Referenced by PrintBasic::println().
println() [2/11]
size_t PrintBasic::println (char c) inline inherited
Definition at line 109 of file PrintBasic.h.
{
     return write(c) + println();
   }
References PrintBasic::println(), and PrintBasic::write().
println() [3/11]
size_t PrintBasic::println (const __FlashStringHelper * str) inline inherited
Definition at line 80 of file PrintBasic.h.
{
 #ifdef __AVR__
     return print(str) + println();
 #else  // __AVR__
     return println(reinterpret_cast<const char *>(str));
 #endif  // __AVR__
   }
References PrintBasic::print(), and PrintBasic::println().
println() [4/11]
size_t PrintBasic::println (const char * str) inline inherited
Definition at line 112 of file PrintBasic.h.
{
     return print(str) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [5/11]
size_t PrintBasic::println (double n, uint8_t prec = 2) inline inherited
Definition at line 115 of file PrintBasic.h.
{
     return print(n, prec) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [6/11]
size_t PrintBasic::println (int n, uint8_t base = 10) inline inherited
Definition at line 124 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [7/11]
size_t PrintBasic::println (long n, uint8_t base = 10) inline inherited
Definition at line 130 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [8/11]
size_t PrintBasic::println (signed char n, uint8_t base = 10) inline inherited
Definition at line 118 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [9/11]
size_t PrintBasic::println (unsigned char n, uint8_t base = 10) inline inherited
Definition at line 121 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [10/11]
size_t PrintBasic::println (unsigned int n, uint8_t base = 10) inline inherited
Definition at line 127 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [11/11]
size_t PrintBasic::println (unsigned long n, uint8_t base = 10) inline inherited
Definition at line 133 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
read()
virtual int StreamBasic::read () pure virtual
setWriteError()
void PrintBasic::setWriteError (int err = 1) inline protected inherited
Definition at line 153 of file PrintBasic.h.
{
     m_error = err;
   }
Referenced by PrintBasic::clearWriteError().
write() [1/4]
size_t PrintBasic::write (const char * buffer, size_t size) inline inherited
Definition at line 148 of file PrintBasic.h.
{
     return write((const uint8_t *)buffer, size);
   }
References PrintBasic::write().
write() [2/4]
size_t PrintBasic::write (const char * str) inline inherited
Definition at line 136 of file PrintBasic.h.
{
     return write(str, strlen(str));
   }
Referenced by PrintBasic::print(), PrintBasic::println(), and PrintBasic::write().
write() [3/4]
virtual size_t PrintBasic::write (const uint8_t * buffer, size_t size) inline virtual inherited
Definition at line 141 of file PrintBasic.h.
{
     size_t i;
     for (i = 0; i < size; i++) {
       if (!write(buffer[i])) break;
     }
     return i;
   }
References PrintBasic::write().
write() [4/4]
virtual size_t PrintBasic::write (uint8_t b) pure virtual inherited
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/common/PrintBasic.h