ERIS CORE: SoftSpiDriver< MisoPin, MosiPin, SckPin > Class Template Reference
SoftSpiDriver< MisoPin, MosiPin, SckPin > Class Template Reference
Class for external soft SPI.
#include <SdSpiSoftDriver.h>
Public Member Functions
void activate ()
void begin ()
void begin (SdSpiConfig spiConfig)
void deactivate ()
uint8_t receive ()
uint8_t receive (uint8_t *buf, size_t count)
void send (const uint8_t *buf, size_t count)
void send (uint8_t data)
void setSckSpeed (uint32_t maxSck)
Private Attributes
SoftSPI< MisoPin, MosiPin, SckPin, 0 > m_spi
Detailed Description
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin>
class SoftSpiDriver< MisoPin, MosiPin, SckPin >
Class for external soft SPI.
Definition at line 99 of file SdSpiSoftDriver.h.
Member Function Documentation
activate()
void SdSpiSoftDriver::activate () inline inherited
Activate SPI hardware.
Definition at line 39 of file SdSpiSoftDriver.h.
 {}
begin() [1/2]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin> void SoftSpiDriver< MisoPin, MosiPin, SckPin >::begin () inline virtual
Initialize the SPI bus.
Implements SdSpiSoftDriver.
Definition at line 102 of file SdSpiSoftDriver.h.
 {m_spi.begin();}
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::begin(), and SoftSpiDriver< MisoPin, MosiPin, SckPin >::m_spi.
begin() [2/2]
void SdSpiSoftDriver::begin (SdSpiConfig spiConfig) inline inherited
Initialize the SPI bus.
Parameters
[in] spiConfig SD card configuration.
Definition at line 46 of file SdSpiSoftDriver.h.
{
     (void)spiConfig;
     begin();
   }
References SdSpiSoftDriver::begin().
deactivate()
void SdSpiSoftDriver::deactivate () inline inherited
Deactivate SPI hardware.
Definition at line 51 of file SdSpiSoftDriver.h.
 {}
receive() [1/2]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin> uint8_t SoftSpiDriver< MisoPin, MosiPin, SckPin >::receive () inline virtual
Receive a byte.
Returns
The byte.
Implements SdSpiSoftDriver.
Definition at line 107 of file SdSpiSoftDriver.h.
 {return m_spi.receive();}
References SoftSpiDriver< MisoPin, MosiPin, SckPin >::m_spi.
receive() [2/2]
uint8_t SdSpiSoftDriver::receive (uint8_t * buf, size_t count) inline inherited
Receive multiple bytes.
Parameters
[out] buf Buffer to receive the data.
[in] count Number of bytes to receive.
Returns
Zero for no error or nonzero error code.
Definition at line 64 of file SdSpiSoftDriver.h.
{
     for (size_t i = 0; i < count; i++) {
       buf[i] = receive();
     }
     return 0;
   }
References buf, count, and SdSpiSoftDriver::receive().
send() [1/2]
void SdSpiSoftDriver::send (const uint8_t * buf, size_t count) inline inherited
Send multiple bytes.
Parameters
[in] buf Buffer for data to be sent.
[in] count Number of bytes to send.
Definition at line 80 of file SdSpiSoftDriver.h.
{
     for (size_t i = 0; i < count; i++) {
       send(buf[i]);
     }
   }
References buf, count, and SdSpiSoftDriver::send().
send() [2/2]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin> void SoftSpiDriver< MisoPin, MosiPin, SckPin >::send (uint8_t data) inline virtual
Send a byte.
Parameters
[in] data Byte to send
Implements SdSpiSoftDriver.
Definition at line 112 of file SdSpiSoftDriver.h.
 {m_spi.send(data);}
References data, and SoftSpiDriver< MisoPin, MosiPin, SckPin >::m_spi.
setSckSpeed()
void SdSpiSoftDriver::setSckSpeed (uint32_t maxSck) inline inherited
Save high speed SPISettings after SD initialization.
Parameters
[in] maxSck Maximum SCK frequency.
Definition at line 89 of file SdSpiSoftDriver.h.
{
     (void)maxSck;
   }
Member Data Documentation
m_spi
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin> SoftSPI<MisoPin, MosiPin, SckPin, 0> SoftSpiDriver< MisoPin, MosiPin, SckPin >::m_spi private
Definition at line 114 of file SdSpiSoftDriver.h.
Referenced by SoftSpiDriver< MisoPin, MosiPin, SckPin >::begin(), SoftSpiDriver< MisoPin, MosiPin, SckPin >::receive(), and SoftSpiDriver< MisoPin, MosiPin, SckPin >::send().
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/src/SpiDriver/SdSpiSoftDriver.h