ERIS CORE: PlasmaYellow Class Reference
PlasmaYellow Class Reference
#include <PlasmaYellow.h>
Public Member Functions
PlasmaYellow ()
uint_fast16_t bgColor (void)
virtual boolean forceTransitionNow (void)
void init (ILI9341_t3n tft)
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
virtual void reset (ILI9341_t3n tft)
String title ()
virtual boolean willForceTransition (void)
Detailed Description
Definition at line 15 of file PlasmaYellow.h.
Constructor & Destructor Documentation
PlasmaYellow()
PlasmaYellow::PlasmaYellow () inline
Definition at line 17 of file PlasmaYellow.h.
 : BaseAnimation() {};
Member Function Documentation
bgColor()
uint_fast16_t PlasmaYellow::bgColor (void) virtual
Reimplemented from BaseAnimation.
Definition at line 34 of file PlasmaYellow.h.
{
     return _bgColor;
 }
forceTransitionNow()
boolean BaseAnimation::forceTransitionNow (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 44 of file BaseAnimation.h.
{
     // Extend me
     return false;   // Default: SuperTFT will transition animations automatically
 }
init()
void PlasmaYellow::init (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
Definition at line 30 of file PlasmaYellow.h.
{
   _bgColor = tft.color565( 0xff, 0xff, 0 );
 }
References tft().
perFrame()
void PlasmaYellow::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseAnimation.
Definition at line 42 of file PlasmaYellow.h.
{
   int_fast16_t w = (int_fast16_t)tft.width();
   int_fast16_t h = (int_fast16_t)tft.height();
     _phase += frameParams.timeMult * PLASMA_YELLOW_SPEED;
     _ditherY = (_ditherY + 1) % PLASMA_YELLOW_DITHER;
     Point16 p0 = (Point16){
         (int_fast16_t)(w/2 + (sin(_phase*0.57f)*(w/2-PLASMA_YELLOW_MARGIN) )),
         (int_fast16_t)(h/2 + (sin(_phase*0.23f)*(h/2-PLASMA_YELLOW_MARGIN) ))
     };
     Point16 p1 = (Point16){
         (int_fast16_t)(w/2 + (cos(_phase*0.78f)*(w/2-PLASMA_YELLOW_MARGIN) )),
         (int_fast16_t)(h/2 + (cos(_phase*0.42f)*(h/2-PLASMA_YELLOW_MARGIN) ))
     };
     float audioPower = frameParams.audioMean;
     for( int_fast16_t x=0; x<w; x+=PLASMA_YELLOW_DITHER ) {
         for( int_fast16_t y=_ditherY; y<h; y+=PLASMA_YELLOW_DITHER ) {
             Point16 d0 = (Point16){ p0.x - x, p0.y - y };
             Point16 d1 = (Point16){ p1.x - x, p1.y - y };
             //uint_fast16_t distance = sqrt( d0.x*d0.x + d0.y*d0.y );// * sqrt( d1.x*d1.x + d1.y*d1.y );    // SLOW
             //uint_fast16_t distance = abs( d0.x*d0.y );    // pretty good
             uint_fast16_t distance = abs( d0.x*d0.y + d1.x*d1.y );
             uint_fast8_t bright = lerp8( (uint_fast16_t)(distance >> 5) & 0xff, 0xff, audioPower );
             if( bright > 0x7f ) bright = 0xff - bright;
             bright <<= 2;
             uint_fast16_t color = tft.color565( bright, bright, 0 );
             tft.drawFastHLine( x, y, PLASMA_YELLOW_DITHER, color );
         }
     }
 }
References FrameParams::audioMean, lerp8(), PLASMA_YELLOW_DITHER, PLASMA_YELLOW_MARGIN, PLASMA_YELLOW_SPEED, tft(), FrameParams::timeMult, x, Point16::x, y, and Point16::y.
reset()
void BaseAnimation::reset (ILI9341_t3n tft) virtual inherited
Reimplemented in TwistyText.
Definition at line 32 of file BaseAnimation.h.
{
     // Extend me
 }
title()
String PlasmaYellow::title () virtual
Reimplemented from BaseAnimation.
Definition at line 38 of file PlasmaYellow.h.
{
     return "PlasmaYellow";
 }
willForceTransition()
boolean BaseAnimation::willForceTransition (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 40 of file BaseAnimation.h.
{
     return false;   // Default: SuperTFT will transition animations automatically
 }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/PlasmaYellow.h