ERIS CORE: SdSpiSoftDriver Class Reference
SdSpiSoftDriver Class Reference abstract
Base class for external soft SPI.
#include <SdSpiSoftDriver.h>
Public Member Functions
void activate ()
virtual void begin ()=0
void begin (SdSpiConfig spiConfig)
void deactivate ()
virtual uint8_t receive ()=0
uint8_t receive (uint8_t *buf, size_t count)
void send (const uint8_t *buf, size_t count)
virtual void send (uint8_t data)=0
void setSckSpeed (uint32_t maxSck)
Detailed Description
Base class for external soft SPI.
Definition at line 36 of file SdSpiSoftDriver.h.
Member Function Documentation
activate()
void SdSpiSoftDriver::activate () inline
Activate SPI hardware.
Definition at line 39 of file SdSpiSoftDriver.h.
 {}
begin() [1/2]
virtual void SdSpiSoftDriver::begin () pure virtual
Initialize the SPI bus.
Implemented in SoftSpiDriver< MisoPin, MosiPin, SckPin >.
Referenced by begin().
begin() [2/2]
void SdSpiSoftDriver::begin (SdSpiConfig spiConfig) inline
Initialize the SPI bus.
Parameters
[in] spiConfig SD card configuration.
Definition at line 46 of file SdSpiSoftDriver.h.
{
     (void)spiConfig;
     begin();
   }
References begin().
deactivate()
void SdSpiSoftDriver::deactivate () inline
Deactivate SPI hardware.
Definition at line 51 of file SdSpiSoftDriver.h.
 {}
receive() [1/2]
virtual uint8_t SdSpiSoftDriver::receive () pure virtual
Receive a byte.
Returns
The byte.
Implemented in SoftSpiDriver< MisoPin, MosiPin, SckPin >.
Referenced by receive().
receive() [2/2]
uint8_t SdSpiSoftDriver::receive (uint8_t * buf, size_t count) inline
Receive multiple bytes.
Parameters
[out] buf Buffer to receive the data.
[in] count Number of bytes to receive.
Returns
Zero for no error or nonzero error code.
Definition at line 64 of file SdSpiSoftDriver.h.
{
     for (size_t i = 0; i < count; i++) {
       buf[i] = receive();
     }
     return 0;
   }
References buf, count, and receive().
send() [1/2]
void SdSpiSoftDriver::send (const uint8_t * buf, size_t count) inline
Send multiple bytes.
Parameters
[in] buf Buffer for data to be sent.
[in] count Number of bytes to send.
Definition at line 80 of file SdSpiSoftDriver.h.
{
     for (size_t i = 0; i < count; i++) {
       send(buf[i]);
     }
   }
References buf, count, and send().
send() [2/2]
virtual void SdSpiSoftDriver::send (uint8_t data) pure virtual
Send a byte.
Parameters
[in] data Byte to send
Implemented in SoftSpiDriver< MisoPin, MosiPin, SckPin >.
Referenced by send().
setSckSpeed()
void SdSpiSoftDriver::setSckSpeed (uint32_t maxSck) inline
Save high speed SPISettings after SD initialization.
Parameters
[in] maxSck Maximum SCK frequency.
Definition at line 89 of file SdSpiSoftDriver.h.
{
     (void)maxSck;
   }
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/src/SpiDriver/SdSpiSoftDriver.h