ERIS CORE: SvcSerialCommandInterface::streamHandler
streamHandler()
void FLASHMEM SvcSerialCommandInterface::streamHandler () protected
Definition at line 233 of file svcSerialCommandInterface.cpp.
{
     char bufferChr; //only need one char - 512 size is due to a potential bug in the teensy library identified by covintry static analysis
     char hexBuffer[8];
     uint16_t payload_len;
     uint16_t compressed_len,uncompressed_len;
     if(throttle()) return;
     if (streamPos == 0){
         Serial.println(F("FS_START"));
         periodicMessagesEnabled = false;
     }
     pSD->chdir(streamPath);
     if (pSD->exists(streamFile)){
         payload_len = 0;
         Serial.print(F("LZ4 "));
         empty();
         print("FS ");
         if(!file.open(streamFile, O_READ)){
             Serial.println(F("M GET_ERR FILE OPEN ERROR"));
             isStreamingFile = false;
             streamPos = 0;
             return;
         }
         file.seek(streamPos);
         //send the next chunked message until eof
         uint64_t i;
         i = file.available();
         if(i>0){
             //if i is zero then last chunk was eof
             if(i > SERIAL_FILESTREAM_PAYLOAD_SIZE) i = SERIAL_FILESTREAM_PAYLOAD_SIZE;
             for(;i > 0; i--){
                 payload_len += 1;
                 if (file.read(&bufferChr,1) < 0){
                     Serial.println(F("M GET_ERR FILE READ ERROR"));
                     isStreamingFile = false;
                     streamPos = 0;
                     file.close();
                     return;
                 }
                 sprintf(hexBuffer,"%02X,",(unsigned int)bufferChr);
                 print(hexBuffer);
             }
             if(indexTxBuffer > 0) txBuffer[--indexTxBuffer] = '\0'; //remove last comma
             streamPos = file.position();
             delay(20);
         }
         file.close();
         if (payload_len == 0){
             //no data to tx; @ eof
 #ifdef USE_EXTMEM
             //do nothing - one time malloc in the constructor
 #else
             char workingBuffer[SERIAL_WORKING_BUFFER_SIZE];
 #endif
             memset(workingBuffer,0,SERIAL_WORKING_BUFFER_SIZE);
             println();
             uncompressed_len = indexTxBuffer;
             compressed_len = LZ4_compress_fast(txBuffer,workingBuffer,indexTxBuffer,SERIAL_WORKING_BUFFER_SIZE,1);
             empty();
             encode_base64((unsigned char *)workingBuffer, strlen(workingBuffer), (unsigned char *)txBuffer);
             while(throttle()){
                 delay(10);
             }
             Serial.print(" ");
             Serial.print(uncompressed_len-2);
             Serial.print(" ");
             Serial.println(txBuffer);
             Serial.println(F("FS_END"));
             empty();
             delay(100);
             isStreamingFile = false;
             streamPos = 0;
 #ifdef USE_EXTMEM
             //do nothing - one time malloc in the constructor
 #else
             //do nothing - local var
 #endif
             return;
         }
         else if (payload_len < SERIAL_FILESTREAM_PAYLOAD_SIZE) {
             delayMicroseconds(20);
             println();
 #ifdef USE_EXTMEM
             //do nothing - one time malloc in the constructor
 #else
             char workingBuffer[SERIAL_WORKING_BUFFER_SIZE];
 #endif
             memset(workingBuffer,0,SERIAL_WORKING_BUFFER_SIZE);
             uncompressed_len = indexTxBuffer;
             compressed_len = LZ4_compress_fast(txBuffer,workingBuffer,indexTxBuffer,SERIAL_WORKING_BUFFER_SIZE,1);
             empty();
             encode_base64((unsigned char *)workingBuffer, compressed_len, (unsigned char *)txBuffer);
             while(throttle()){
                 delay(10);
             }
             Serial.print(uncompressed_len);
             Serial.print(" ");
             Serial.println(txBuffer);
             empty();
             Serial.println(F("FS_END"));
             empty();
             isStreamingFile = false;
             streamPos = 0;
             delayMicroseconds(3000);
             periodicMessagesEnabled = true;
 #ifdef USE_EXTMEM
             //do nothing - one time malloc in the constructor
 #else
             //do nothing-- local var
 #endif
             return;
         } else{
             //send file chunk
             println();
 #ifdef USE_EXTMEM
             //do nothing - one time malloc in the constructor
 #else
             char wb[SERIAL_WORKING_BUFFER_SIZE];
 #endif
             memset(workingBuffer,0,SERIAL_WORKING_BUFFER_SIZE);
             uncompressed_len = indexTxBuffer;
             compressed_len = LZ4_compress_fast(txBuffer,workingBuffer,indexTxBuffer,SERIAL_WORKING_BUFFER_SIZE,1);
             empty();
             encode_base64((unsigned char *)workingBuffer, compressed_len, (unsigned char *)txBuffer);
             Serial.print(uncompressed_len);
             Serial.print(" ");
             Serial.println(txBuffer);
             empty();
 #ifdef USE_EXTMEM
             //do nothing - one time malloc in the constructor
 #else
             //do nothing - local var
 #endif
             return;
         }
     }
     else{
         Serial.print(F("M GET_ERR FILE NOT FOUND "));
         Serial.println(streamFile);
         isStreamingFile = false;
         streamPos = 0;
         return;
     }
 };
References empty(), file, indexTxBuffer, isStreamingFile, periodicMessagesEnabled, pSD, SERIAL_FILESTREAM_PAYLOAD_SIZE, SERIAL_WORKING_BUFFER_SIZE, streamFile, streamPath, streamPos, throttle(), txBuffer, and workingBuffer.
Referenced by updateRT().