ERIS CORE: FsFile Class Reference
FsFile Class Reference
FsBaseFile file with Arduino Stream.
#include <FsFile.h>
Public Member Functions
const char * __attribute__ ((error("use getName(name, size)"))) name()
int available ()
int available () const
uint64_t available64 () const
void clearWriteError ()
void clearWriteError ()
bool close ()
bool contiguousRange (uint32_t *bgnSector, uint32_t *endSector)
uint64_t curPosition () const
uint32_t dirIndex () const
bool exists (const char *path)
void fgetpos (fspos_t *pos) const
int fgets (char *str, int num, char *delim=nullptr)
uint64_t fileSize () const
uint32_t firstSector () const
void flush ()
void fsetpos (const fspos_t *pos)
bool getAccessDateTime (uint16_t *pdate, uint16_t *ptime)
bool getCreateDateTime (uint16_t *pdate, uint16_t *ptime)
uint8_t getError () const
bool getModifyDateTime (uint16_t *pdate, uint16_t *ptime)
size_t getName (char *name, size_t len)
int getWriteError ()
bool getWriteError () const
bool isBusy ()
bool isContiguous () const
bool isDir () const
bool isDirectory ()
bool isDirectory () const
bool isFile () const
bool isHidden () const
bool isOpen () const
bool isReadable () const
bool isReadOnly () const
bool isSubDir () const
bool isWritable () const
bool ls (print_t *pr)
bool ls (print_t *pr, uint8_t flags)
bool mkdir (FsBaseFile *dir, const char *path, bool pFlag=true)
const char * name () const
bool open (const char *path, oflag_t oflag=O_RDONLY)
bool open (FsBaseFile *dir, const char *path, oflag_t oflag=O_RDONLY)
bool open (FsBaseFile *dir, uint32_t index, oflag_t oflag)
bool open (FsVolume *vol, const char *path, oflag_t oflag)
bool openNext (FsBaseFile *dir, oflag_t oflag=O_RDONLY)
FsFile openNextFile (oflag_t oflag=O_RDONLY)
bool openRoot (FsVolume *vol)
operator bool () const
int peek ()
uint64_t position ()
uint64_t position () const
bool preAllocate (uint64_t length)
size_t print (char c)
size_t print (const __FlashStringHelper *str)
size_t print (const char *str)
size_t print (double n, uint8_t prec=2)
size_t print (int n, uint8_t base=10)
size_t print (long n, uint8_t base=10)
size_t print (signed char n, uint8_t base=10)
size_t print (unsigned char n, uint8_t base=10)
size_t print (unsigned int n, uint8_t base=10)
size_t print (unsigned long n, uint8_t base=10)
size_t printAccessDateTime (print_t *pr)
size_t printCreateDateTime (print_t *pr)
size_t printField (double value, char term, uint8_t prec=2)
size_t printField (float value, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type value, char term)
size_t printFileSize (print_t *pr)
size_t println ()
size_t println (char c)
size_t println (const __FlashStringHelper *str)
size_t println (const char *str)
size_t println (double n, uint8_t prec=2)
size_t println (int n, uint8_t base=10)
size_t println (long n, uint8_t base=10)
size_t println (signed char n, uint8_t base=10)
size_t println (unsigned char n, uint8_t base=10)
size_t println (unsigned int n, uint8_t base=10)
size_t println (unsigned long n, uint8_t base=10)
size_t printModifyDateTime (print_t *pr)
size_t printName (print_t *pr)
int read ()
int read (void *buf, size_t count)
bool remove ()
bool remove (const char *path)
bool rename (const char *newPath)
bool rename (FsBaseFile *dirFile, const char *newPath)
void rewind ()
void rewindDirectory ()
bool rmdir ()
bool seek (uint64_t pos)
bool seekCur (int64_t offset)
bool seekEnd (int64_t offset=0)
bool seekSet (uint64_t pos)
uint64_t size ()
uint64_t size () const
bool sync ()
bool timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
bool truncate ()
bool truncate (uint64_t length)
size_t write (const char *buffer, size_t size)
size_t write (const char *str)
size_t write (const uint8_t *buffer, size_t size)
size_t write (const void *buf, size_t count)
size_t write (uint8_t b)
Protected Member Functions
void setWriteError (int err=1)
Private Member Functions
size_t printDouble (double n, uint8_t prec)
size_t printNum (unsigned long n, uint8_t base)
Private Attributes
int m_error
FatFile * m_fFile = nullptr
newalign_t m_fileMem [FS_ALIGN_DIM(ExFatFile, FatFile)]
ExFatFile * m_xFile = nullptr
Detailed Description
FsBaseFile file with Arduino Stream.
Definition at line 796 of file FsFile.h.
Member Function Documentation
__attribute__()
const char* StreamFile< FsBaseFile , uint64_t >::__attribute__ ((error("use getName(name, size)"))) inherited
No longer implemented due to Long File Names.
Use getName(char* name, size_t size).
Returns
a pointer to replacement suggestion.
available() [1/2]
int StreamFile< FsBaseFile , uint64_t >::available (void) inline inherited
Returns
number of bytes available from the current position to EOF or INT_MAX if more than INT_MAX bytes are available.
Definition at line 75 of file ArduinoFiles.h.
                   {
     return BaseFile::available();
   }
available() [2/2]
int FsBaseFile::available (void) const inline inherited
Returns
number of bytes available from the current position to EOF or INT_MAX if more than INT_MAX bytes are available.
Definition at line 72 of file FsFile.h.
{
     return m_fFile ? m_fFile->available() :
            m_xFile ? m_xFile->available() : 0;
   }
References ExFatFile::available(), FatFile::available(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
available64()
uint64_t FsBaseFile::available64 () const inline inherited
Returns
The number of bytes available from the current position to EOF for normal files. Zero is returned for directory files.
Definition at line 79 of file FsFile.h.
{
     return m_fFile ? m_fFile->available32() :
            m_xFile ? m_xFile->available64() : 0;
   }
References FatFile::available32(), ExFatFile::available64(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
clearWriteError() [1/2]
void PrintBasic::clearWriteError () inline inherited
Definition at line 57 of file PrintBasic.h.
{
     setWriteError(0);
   }
References PrintBasic::setWriteError().
clearWriteError() [2/2]
void FsBaseFile::clearWriteError () inline inherited
Clear writeError.
Definition at line 84 of file FsFile.h.
{
     if (m_fFile) m_fFile->clearWriteError();
     if (m_xFile) m_xFile->clearWriteError();
   }
References ExFatFile::clearWriteError(), FatFile::clearWriteError(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
close()
bool FsBaseFile::close () inherited
Close a file and force cached data and directory information to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 52 of file FsFile.cpp.
{
   if (m_fFile && m_fFile->close()) {
     m_fFile = nullptr;
     return true;
   }
   if (m_xFile && m_xFile->close()) {
     m_xFile = nullptr;
     return true;
   }
   return false;
 }
References ExFatFile::close(), FatFile::close(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
Referenced by Surface::Surface(), FsBaseFile::~FsBaseFile(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDAnimationFullScreen(), ILI9341_t3_ERIS::bltSDFullScreen(), FsBaseFile::mkdir(), FsBaseFile::open(), FsBaseFile::openNext(), FsBaseFile::openRoot(), FsBaseFile::operator=(), and SvcSerialCommandInterface::streamHandler().
contiguousRange()
bool FsBaseFile::contiguousRange (uint32_t * bgnSector, uint32_t * endSector) inline inherited
Check for contiguous file and return its raw sector range.
Parameters
[out] bgnSector the first sector address for the file.
[out] endSector the last sector address for the file.
Set contiguous flag for FAT16/FAT32 files. Parameters may be nullptr.
Returns
true for success or false for failure.
Definition at line 104 of file FsFile.h.
{
     return m_fFile ? m_fFile->contiguousRange(bgnSector, endSector) :
            m_xFile ? m_xFile->contiguousRange(bgnSector, endSector) : false;
   }
References ExFatFile::contiguousRange(), FatFile::contiguousRange(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
curPosition()
uint64_t FsBaseFile::curPosition () const inline inherited
Returns
The current position for a file or directory.
Definition at line 109 of file FsFile.h.
{
     return m_fFile ? m_fFile->curPosition() :
            m_xFile ? m_xFile->curPosition() : 0;
   }
References ExFatFile::curPosition(), FatFile::curPosition(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
dirIndex()
uint32_t FsBaseFile::dirIndex () const inline inherited
Returns
Directory entry index.
Definition at line 114 of file FsFile.h.
{
     return m_fFile ? m_fFile->dirIndex() :
            m_xFile ? m_xFile->dirIndex() : 0;
   }
References ExFatFile::dirIndex(), FatFile::dirIndex(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
exists()
bool FsBaseFile::exists (const char * path) inline inherited
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
The calling instance must be an open directory file.
dirFile.exists("TOFIND.TXT") searches for "TOFIND.TXT" in the directory dirFile.
Returns
true if the file exists else false.
Definition at line 129 of file FsFile.h.
{
     return m_fFile ? m_fFile->exists(path) :
            m_xFile ? m_xFile->exists(path) : false;
   }
References ExFatFile::exists(), FatFile::exists(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
fgetpos()
void FsBaseFile::fgetpos (fspos_t * pos) const inline inherited
get position for streams
Parameters
[out] pos struct to receive position
Definition at line 136 of file FsFile.h.
{
     if (m_fFile) m_fFile->fgetpos(pos);
     if (m_xFile) m_xFile->fgetpos(pos);
   }
References ExFatFile::fgetpos(), FatFile::fgetpos(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
fgets()
int FsBaseFile::fgets (char * str, int num, char * delim = nullptr) inline inherited
Get a string from a file.
fgets() reads bytes from a file into the array pointed to by str, until num - 1 bytes are read, or a delimiter is read and transferred to str, or end-of-file is encountered. The string is then terminated with a null byte.
fgets() deletes CR, '\r', from the string. This insures only a '\n' terminates the string for Windows text files which use CRLF for newline.
Parameters
[out] str Pointer to the array where the string is stored.
[in] num Maximum number of characters to be read (including the final null byte). Usually the length of the array str is used.
[in] delim Optional set of delimiters. The default is "\n".
Returns
For success fgets() returns the length of the string in str. If no data is read, fgets() returns zero for EOF or -1 if an error occurred.
Definition at line 160 of file FsFile.h.
{
     return m_fFile ? m_fFile->fgets(str, num, delim) :
            m_xFile ? m_xFile->fgets(str, num, delim) : -1;
   }
References ExFatFile::fgets(), FatFile::fgets(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
Referenced by Surface::Surface(), and ILI9341_t3_ERIS::bltSD().
fileSize()
uint64_t FsBaseFile::fileSize () const inline inherited
Returns
The total number of bytes in a file.
Definition at line 165 of file FsFile.h.
{
     return m_fFile ? m_fFile->fileSize() :
            m_xFile ? m_xFile->fileSize() : 0;
   }
References ExFatFile::fileSize(), FatFile::fileSize(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
firstSector()
uint32_t FsBaseFile::firstSector () const inline inherited
Returns
Address of first sector or zero for empty file.
Definition at line 170 of file FsFile.h.
{
     return m_fFile ? m_fFile->firstSector() :
            m_xFile ? m_xFile->firstSector() : 0;
   }
References ExFatFile::firstSector(), FatFile::firstSector(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
flush()
void StreamFile< FsBaseFile , uint64_t >::flush () inline inherited
Ensure that any bytes written to the file are saved to the SD card.
Definition at line 79 of file ArduinoFiles.h.
                {
     BaseFile::sync();
   }
fsetpos()
void FsBaseFile::fsetpos (const fspos_t * pos) inline inherited
set position for streams
Parameters
[in] pos struct with value for new position
Definition at line 179 of file FsFile.h.
{
     if (m_fFile) m_fFile->fsetpos(pos);
     if (m_xFile) m_xFile->fsetpos(pos);
   }
References ExFatFile::fsetpos(), FatFile::fsetpos(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
getAccessDateTime()
bool FsBaseFile::getAccessDateTime (uint16_t * pdate, uint16_t * ptime) inline inherited
Get a file's access date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 190 of file FsFile.h.
{
     return m_fFile ? m_fFile->getAccessDateTime(pdate, ptime) :
            m_xFile ? m_xFile->getAccessDateTime(pdate, ptime) : false;
   }
References ExFatFile::getAccessDateTime(), FatFile::getAccessDateTime(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
getCreateDateTime()
bool FsBaseFile::getCreateDateTime (uint16_t * pdate, uint16_t * ptime) inline inherited
Get a file's create date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 201 of file FsFile.h.
{
     return m_fFile ? m_fFile->getCreateDateTime(pdate, ptime) :
            m_xFile ? m_xFile->getCreateDateTime(pdate, ptime) : false;
   }
References ExFatFile::getCreateDateTime(), FatFile::getCreateDateTime(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
getError()
uint8_t FsBaseFile::getError () const inline inherited
Returns
All error bits.
Definition at line 206 of file FsFile.h.
{
     return m_fFile ? m_fFile->getError() :
            m_xFile ? m_xFile->getError() : 0XFF;
   }
References ExFatFile::getError(), FatFile::getError(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
getModifyDateTime()
bool FsBaseFile::getModifyDateTime (uint16_t * pdate, uint16_t * ptime) inline inherited
Get a file's Modify date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 217 of file FsFile.h.
{
     return m_fFile ? m_fFile->getModifyDateTime(pdate, ptime) :
            m_xFile ? m_xFile->getModifyDateTime(pdate, ptime) : false;
   }
References ExFatFile::getModifyDateTime(), FatFile::getModifyDateTime(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
getName()
size_t FsBaseFile::getName (char * name, size_t len) inline inherited
Get a file's name followed by a zero byte.
Parameters
[out] name An array of characters for the file's name.
[in] len The size of the array in bytes. The array must be at least 13 bytes long. The file's name will be truncated if the file's name is too long.
Returns
The length of the returned string.
Definition at line 230 of file FsFile.h.
{
     *name = 0;
     return m_fFile ? m_fFile->getName(name, len) :
            m_xFile ? m_xFile->getName(name, len) : 0;
   }
References ExFatFile::getName(), FatFile::getName(), FsBaseFile::m_fFile, FsBaseFile::m_xFile, and name.
getWriteError() [1/2]
int PrintBasic::getWriteError () inline inherited
Definition at line 60 of file PrintBasic.h.
                       {
     return m_error;
   }
References PrintBasic::m_error.
getWriteError() [2/2]
bool FsBaseFile::getWriteError () const inline inherited
Returns
value of writeError
Definition at line 237 of file FsFile.h.
{
     return m_fFile ? m_fFile->getWriteError() :
            m_xFile ? m_xFile->getWriteError() : true;
   }
References ExFatFile::getWriteError(), FatFile::getWriteError(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isBusy()
bool FsBaseFile::isBusy () inline inherited
Check for BlockDevice busy.
Returns
true if busy else false.
Definition at line 246 of file FsFile.h.
                 {
     return m_fFile ? m_fFile->isBusy() :
            m_xFile ? m_xFile->isBusy() : true;
   }
References ExFatFile::isBusy(), FatFile::isBusy(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isContiguous()
bool FsBaseFile::isContiguous () const inline inherited
Returns
True if the file is contiguous.
Definition at line 251 of file FsFile.h.
{
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
     return m_fFile ? m_fFile->isContiguous() :
            m_xFile ? m_xFile->isContiguous() : false;
 #else  // USE_FAT_FILE_FLAG_CONTIGUOUS
     return m_xFile ? m_xFile->isContiguous() : false;
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
   }
References ExFatFile::isContiguous(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isDir()
bool FsBaseFile::isDir () const inline inherited
Returns
True if this is a directory else false.
Definition at line 260 of file FsFile.h.
                      {
     return m_fFile ? m_fFile->isDir() :
            m_xFile ? m_xFile->isDir() : false;
   }
References ExFatFile::isDir(), FatFile::isDir(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
Referenced by FsBaseFile::isDirectory().
isDirectory() [1/2]
bool StreamFile< FsBaseFile , uint64_t >::isDirectory () inline inherited
This function reports if the current file is a directory or not.
Returns
true if the file is a directory.
Definition at line 85 of file ArduinoFiles.h.
                      {
     return BaseFile::isDir();
   }
isDirectory() [2/2]
bool FsBaseFile::isDirectory () const inline inherited
This function reports if the current file is a directory or not.
Returns
true if the file is a directory.
Definition at line 267 of file FsFile.h.
 {return isDir();}
References FsBaseFile::isDir().
isFile()
bool FsBaseFile::isFile () const inline inherited
Returns
True if this is a normal file.
Definition at line 269 of file FsFile.h.
                       {
     return m_fFile ? m_fFile->isFile() :
            m_xFile ? m_xFile->isFile() : false;
   }
References ExFatFile::isFile(), FatFile::isFile(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isHidden()
bool FsBaseFile::isHidden () const inline inherited
Returns
True if this is a hidden file else false.
Definition at line 274 of file FsFile.h.
{
     return m_fFile ? m_fFile->isHidden() :
            m_xFile ? m_xFile->isHidden() : false;
   }
References ExFatFile::isHidden(), FatFile::isHidden(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isOpen()
bool FsBaseFile::isOpen () const inline inherited
Returns
True if this is an open file/directory else false.
Definition at line 279 of file FsFile.h.
 {return m_fFile || m_xFile;}
References FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
Referenced by FsBaseFile::operator bool().
isReadable()
bool FsBaseFile::isReadable () const inline inherited
Returns
True file is readable.
Definition at line 281 of file FsFile.h.
{
     return m_fFile ? m_fFile->isReadable() :
            m_xFile ? m_xFile->isReadable() : false;
     }
References ExFatFile::isReadable(), FatFile::isReadable(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isReadOnly()
bool FsBaseFile::isReadOnly () const inline inherited
Returns
True if file is read-only
Definition at line 286 of file FsFile.h.
{
     return m_fFile ? m_fFile->isReadOnly() :
            m_xFile ? m_xFile->isReadOnly() : false;
   }
References ExFatFile::isReadOnly(), FatFile::isReadOnly(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isSubDir()
bool FsBaseFile::isSubDir () const inline inherited
Returns
True if this is a subdirectory file else false.
Definition at line 291 of file FsFile.h.
{
     return m_fFile ? m_fFile->isSubDir() :
            m_xFile ? m_xFile->isSubDir() : false;
   }
References ExFatFile::isSubDir(), FatFile::isSubDir(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
isWritable()
bool FsBaseFile::isWritable () const inline inherited
Returns
True file is writable.
Definition at line 296 of file FsFile.h.
{
     return m_fFile ? m_fFile->isWritable() :
            m_xFile ? m_xFile->isWritable() : false;
   }
References ExFatFile::isWritable(), FatFile::isWritable(), FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
ls() [1/2]
bool FsBaseFile::ls (print_t * pr) inline inherited
List directory contents.
Parameters
[in] pr Print object.
Returns
true for success or false for failure.
Definition at line 325 of file FsFile.h.
{
     return m_fFile ? m_fFile->ls(pr) :
            m_xFile ? m_xFile->ls(pr) : false;
   }
Referenced by FsVolume::ls().
ls() [2/2]
bool FsBaseFile::ls (print_t * pr, uint8_t flags) inline inherited
List directory contents.
Parameters
[in] pr Print object.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 342 of file FsFile.h.
{
     return m_fFile ? m_fFile->ls(pr, flags) :
            m_xFile ? m_xFile->ls(pr, flags) : false;
   }
mkdir()
bool FsBaseFile::mkdir (FsBaseFile * dir, const char * path, bool pFlag = true) inherited
Make a new directory.
Parameters
[in] dir An open FatFile instance for the directory that will contain the new directory.
[in] path A path with a valid 8.3 DOS name for the new directory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 64 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->mkdir(dir->m_fFile, path, pFlag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->mkdir(dir->m_xFile, path, pFlag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References FsBaseFile::close(), FsBaseFile::m_fFile, FsBaseFile::m_fileMem, FsBaseFile::m_xFile, ExFatFile::mkdir(), and FatFile::mkdir().
name()
const char* StreamFile< FsBaseFile , uint64_t >::name () const inline inherited
Definition at line 96 of file ArduinoFiles.h.
 {return "use getName()";}
open() [1/4]
bool FsBaseFile::open (const char * path, oflag_t oflag = O_RDONLY) inline inherited
Open a file or directory by name.
Parameters
[in] path A path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of open flags.
Returns
true for success or false for failure.
Definition at line 443 of file FsFile.h.
{
     return FsVolume::m_cwv && open(FsVolume::m_cwv, path, oflag);
   }
References FsVolume::m_cwv.
open() [2/4]
bool FsBaseFile::open (FsBaseFile * dir, const char * path, oflag_t oflag = O_RDONLY) inherited
Open a file or directory by name.
Parameters
[in] dir An open file instance for the directory containing the file to be opened.
[in] path A path with a valid 8.3 DOS name for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list
O_RDONLY - Open for reading only..
O_READ - Same as O_RDONLY.
O_WRONLY - Open for writing only.
O_WRITE - Same as O_WRONLY.
O_RDWR - Open for reading and writing.
O_APPEND - If set, the file offset shall be set to the end of the file prior to each write.
O_AT_END - Set the initial position at the end of the file.
O_CREAT - If the file exists, this flag has no effect except as noted under O_EXCL below. Otherwise, the file shall be created
O_EXCL - If O_CREAT and O_EXCL are set, open() shall fail if the file exists.
O_TRUNC - If the file exists and is a regular file, and the file is successfully opened and is not read only, its length shall be truncated to 0.
WARNING: A given file must not be opened by more than one file object or file corruption may occur.
Note
Directory files must be opened read only. Write and truncation is not allowed for directory files.
Returns
true for success or false for failure.
Definition at line 103 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->open(dir->m_fFile, path, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->open(dir->m_xFile, path, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References FsBaseFile::close(), FsBaseFile::m_fFile, FsBaseFile::m_fileMem, FsBaseFile::m_xFile, ExFatFile::open(), and FatFile::open().
Referenced by FsBaseFile::FsBaseFile(), Surface::Surface(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDAnimationFullScreen(), ILI9341_t3_ERIS::bltSDFullScreen(), FsVolume::ls(), FsVolume::open(), and SvcSerialCommandInterface::streamHandler().
open() [3/4]
bool FsBaseFile::open (FsBaseFile * dir, uint32_t index, oflag_t oflag) inherited
Open a file by index.
Parameters
[in] dir An open FsFile instance for the directory.
[in] index The index of the directory entry for the file to be opened. The value for index is (directory file position)/32.
[in] oflag bitwise-inclusive OR of open flags. See see FsFile::open(FsFile*, const char*, uint8_t).
See open() by path for definition of flags.
Returns
true for success or false for failure.
Definition at line 121 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->open(dir->m_fFile, index, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->open(dir->m_xFile, index, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References FsBaseFile::close(), FsBaseFile::m_fFile, FsBaseFile::m_fileMem, FsBaseFile::m_xFile, ExFatFile::open(), and FatFile::open().
open() [4/4]
bool FsBaseFile::open (FsVolume * vol, const char * path, oflag_t oflag) inherited
Open a file or directory by name.
Parameters
[in] vol Volume where the file is located.
[in] path A path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of open flags.
Returns
true for success or false for failure.
Definition at line 82 of file FsFile.cpp.
{
   if (!vol) {
     return false;
   }
   close();
   if (vol->m_fVol) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile && m_fFile->open(vol->m_fVol, path, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (vol->m_xVol) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile && m_xFile->open(vol->m_xVol, path, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References FsBaseFile::close(), FsBaseFile::m_fFile, FsBaseFile::m_fileMem, FsVolume::m_fVol, FsBaseFile::m_xFile, FsVolume::m_xVol, ExFatFile::open(), and FatFile::open().
openNext()
bool FsBaseFile::openNext (FsBaseFile * dir, oflag_t oflag = O_RDONLY) inherited
Opens the next file or folder in a directory.
Parameters
[in] dir directory containing files.
[in] oflag open flags.
Returns
a file object.
Definition at line 139 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->openNext(dir->m_fFile, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->openNext(dir->m_xFile, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References FsBaseFile::close(), FsBaseFile::m_fFile, FsBaseFile::m_fileMem, FsBaseFile::m_xFile, ExFatFile::openNext(), and FatFile::openNext().
Referenced by openNextFile().
openNextFile()
FsFile FsFile::openNextFile (oflag_t oflag = O_RDONLY) inline
Opens the next file or folder in a directory.
Parameters
[in] oflag open flags.
Returns
a FatStream object.
Definition at line 803 of file FsFile.h.
{
     FsFile tmpFile;
     tmpFile.openNext(this, oflag);
     return tmpFile;
   }
References FsBaseFile::openNext().
openRoot()
bool FsBaseFile::openRoot (FsVolume * vol) inherited
Open a volume's root directory.
Parameters
[in] vol The SdFs volume containing the root directory to be opened.
Returns
true for success or false for failure.
Definition at line 157 of file FsFile.cpp.
{
   if (!vol) {
     return false;
   }
   close();
   if (vol->m_fVol) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile && m_fFile->openRoot(vol->m_fVol)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (vol->m_xVol) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile && m_xFile->openRoot(vol->m_xVol)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References FsBaseFile::close(), FsBaseFile::m_fFile, FsBaseFile::m_fileMem, FsVolume::m_fVol, FsBaseFile::m_xFile, FsVolume::m_xVol, ExFatFile::openRoot(), and FatFile::openRoot().
operator bool()
FsBaseFile::operator bool () const inline inherited
The parenthesis operator.
Returns
true if a file is open.
Definition at line 68 of file FsFile.h.
 {return isOpen();}
References FsBaseFile::isOpen().
peek()
int StreamFile< FsBaseFile , uint64_t >::peek () inline inherited
Return the next available byte without consuming it.
Returns
The byte if no error and not at eof else -1;
Definition at line 101 of file ArduinoFiles.h.
              {
     return BaseFile::peek();
   }
position() [1/2]
uint64_t StreamFile< FsBaseFile , uint64_t >::position () inline inherited
Returns
the current file position.
Definition at line 105 of file ArduinoFiles.h.
                      {
     return BaseFile::curPosition();
   }
position() [2/2]
uint64_t FsBaseFile::position () const inline inherited
Returns
the current file position.
Definition at line 460 of file FsFile.h.
 {return curPosition();}
preAllocate()
bool FsBaseFile::preAllocate (uint64_t length) inline inherited
Allocate contiguous clusters to an empty file.
The file must be empty with no clusters allocated.
The file will contain uninitialized data for FAT16/FAT32 files. exFAT files will have zero validLength and dataLength will equal the requested length.
Parameters
[in] length size of the file in bytes.
Returns
true for success or false for failure.
Definition at line 480 of file FsFile.h.
{
     return m_fFile ? length < (1ULL << 32) && m_fFile->preAllocate(length) :
            m_xFile ? m_xFile->preAllocate(length) : false;
   }
print() [1/10]
size_t PrintBasic::print (char c) inline inherited
Definition at line 63 of file PrintBasic.h.
{
     return write(c);
   }
References PrintBasic::write().
Referenced by ExFatPartition::checkUpcase(), ExFatPartition::dmpCluster(), SdBase< Vol >::errorHalt(), SdBase< Vol >::errorPrint(), PrintBasic::print(), ExFatPartition::printDir(), printDirBitmap(), printDirFile(), printDirLabel(), printDirName(), printDirStream(), printDirUpcase(), PrintBasic::printDouble(), printExFatBoot(), ExFatPartition::printFat(), printFatDir(), SdBase< Vol >::printFatType(), printHex(), PrintBasic::println(), printMbr(), SdBase< Vol >::printSdError(), printSdErrorSymbol(), printSdErrorText(), ExFatPartition::printUpcase(), and ExFatPartition::printVolInfo().
print() [2/10]
size_t PrintBasic::print (const __FlashStringHelper * str) inline inherited
Definition at line 69 of file PrintBasic.h.
{
 #ifdef __AVR__
   PGM_P p = reinterpret_cast<PGM_P>(str);
   size_t n = 0;
   for (uint8_t c; (c = pgm_read_byte(p + n)) && write(c); n++) {}
   return n;
 #else  // __AVR__
   return print(reinterpret_cast<const char *>(str));
 #endif  // __AVR__
   }
References p, pgm_read_byte, PrintBasic::print(), and PrintBasic::write().
print() [3/10]
size_t PrintBasic::print (const char * str) inline inherited
Definition at line 66 of file PrintBasic.h.
{
     return write(str);
   }
References PrintBasic::write().
print() [4/10]
size_t PrintBasic::print (double n, uint8_t prec = 2) inline inherited
Definition at line 86 of file PrintBasic.h.
{
     return printDouble(n, prec);
   }
References PrintBasic::printDouble().
print() [5/10]
size_t PrintBasic::print (int n, uint8_t base = 10) inline inherited
Definition at line 95 of file PrintBasic.h.
{
     return print((long)n, base);
   }
References PrintBasic::print().
print() [6/10]
size_t PrintBasic::print (long n, uint8_t base = 10) inherited
Copyright (c) 2011-2020 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 28 of file PrintBasic.cpp.
{
   if (n < 0 && base == 10) {
     return print('-') + printNum(-n, base);
   }
   return printNum(n, base);
 }
References PrintBasic::print(), and PrintBasic::printNum().
print() [7/10]
size_t PrintBasic::print (signed char n, uint8_t base = 10) inline inherited
Definition at line 89 of file PrintBasic.h.
{
     return print((long)n, base);
   }
References PrintBasic::print().
print() [8/10]
size_t PrintBasic::print (unsigned char n, uint8_t base = 10) inline inherited
Definition at line 92 of file PrintBasic.h.
{
     return print((unsigned long)n, base);
   }
References PrintBasic::print().
print() [9/10]
size_t PrintBasic::print (unsigned int n, uint8_t base = 10) inline inherited
Definition at line 98 of file PrintBasic.h.
{
     return print((unsigned long)n, base);
   }
References PrintBasic::print().
print() [10/10]
size_t PrintBasic::print (unsigned long n, uint8_t base = 10) inline inherited
Definition at line 102 of file PrintBasic.h.
{
     return printNum(n, base);
   }
References PrintBasic::printNum().
printAccessDateTime()
size_t FsBaseFile::printAccessDateTime (print_t * pr) inline inherited
Print a file's access date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 490 of file FsFile.h.
{
     return m_fFile ? m_fFile->printAccessDateTime(pr) :
            m_xFile ? m_xFile->printAccessDateTime(pr) : 0;
   }
printCreateDateTime()
size_t FsBaseFile::printCreateDateTime (print_t * pr) inline inherited
Print a file's creation date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 500 of file FsFile.h.
{
     return m_fFile ? m_fFile->printCreateDateTime(pr) :
            m_xFile ? m_xFile->printCreateDateTime(pr) : 0;
   }
printDouble()
size_t PrintBasic::printDouble (double n, uint8_t prec) private inherited
Definition at line 49 of file PrintBasic.cpp.
{
   // Max printable 32-bit floating point number. AVR uses 32-bit double.
   const double maxfp = static_cast<double>(0XFFFFFF00UL);
   size_t rtn = 0;
   if (isnan(n)) {
     return write("NaN");
   }
   if (n < 0) {
     n = -n;
     rtn += print('-');
   }
   if (isinf(n)) {
     return rtn + write("Inf");
   }
   if (n > maxfp) {
     return rtn + write("Ovf");
   }
   double round = 0.5;
   for (uint8_t i  = 0; i < prec; ++i) {
     round *= 0.1;
   }
   n += round;
   uint32_t whole = (uint32_t)n;
   rtn += print(whole);
   if (prec) {
     rtn += print('.');
     double fraction = n - static_cast<double>(whole);
     for (uint8_t i = 0; i < prec; i++) {
       fraction *= 10.0;
       uint8_t digit = fraction;
       rtn += print(digit);
       fraction -= digit;
     }
   }
   return rtn;
 }
References PrintBasic::print(), and PrintBasic::write().
Referenced by PrintBasic::print().
printField() [1/3]
size_t FsBaseFile::printField (double value, char term, uint8_t prec = 2) inline inherited
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 510 of file FsFile.h.
{
     return m_fFile ? m_fFile->printField(value, term, prec) :
            m_xFile ? m_xFile->printField(value, term, prec) : 0;
   }
printField() [2/3]
size_t FsBaseFile::printField (float value, char term, uint8_t prec = 2) inline inherited
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 520 of file FsFile.h.
{
      return printField(static_cast<double>(value), term, prec);
   }
printField() [3/3]
template<typename Type > size_t FsBaseFile::printField (Type value, char term) inline inherited
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 529 of file FsFile.h.
{
     return m_fFile ? m_fFile->printField(value, term) :
            m_xFile ? m_xFile->printField(value, term) : 0;
   }
printFileSize()
size_t FsBaseFile::printFileSize (print_t * pr) inline inherited
Print a file's size.
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed is returned for success and zero is returned for failure.
Definition at line 540 of file FsFile.h.
{
     return m_fFile ? m_fFile->printFileSize(pr) :
            m_xFile ? m_xFile->printFileSize(pr) : 0;
   }
println() [1/11]
size_t PrintBasic::println () inline inherited
Definition at line 105 of file PrintBasic.h.
                    {
     return write("\r\n");
   }
References PrintBasic::write().
Referenced by PrintBasic::println().
println() [2/11]
size_t PrintBasic::println (char c) inline inherited
Definition at line 108 of file PrintBasic.h.
{
     return write(c) + println();
   }
References PrintBasic::println(), and PrintBasic::write().
println() [3/11]
size_t PrintBasic::println (const __FlashStringHelper * str) inline inherited
Definition at line 79 of file PrintBasic.h.
{
 #ifdef __AVR__
     return print(str) + println();
 #else  // __AVR__
     return println(reinterpret_cast<const char *>(str));
 #endif  // __AVR__
   }
References PrintBasic::print(), and PrintBasic::println().
Referenced by ExFatPartition::checkUpcase(), ExFatPartition::dmpBitmap(), ExFatPartition::dmpCluster(), dmpDirData(), FatPartition::dmpDirSector(), ExFatPartition::dmpFat(), FatPartition::dmpFat(), FatPartition::dmpRootDir(), ExFatPartition::dmpSector(), FatPartition::dmpSector(), SdBase< Vol >::errorHalt(), SdBase< Vol >::errorPrint(), SdBase< Vol >::initErrorHalt(), printDateTime(), ExFatPartition::printDir(), printDirBitmap(), printDirFile(), printDirLabel(), printDirName(), printDirStream(), printDirUpcase(), printExFatBoot(), ExFatPartition::printFat(), printFatDir(), printHex64(), printHexLn(), println64(), printMbr(), SdBase< Vol >::printSdError(), ExFatPartition::printUpcase(), and ExFatPartition::printVolInfo().
println() [4/11]
size_t PrintBasic::println (const char * str) inline inherited
Definition at line 111 of file PrintBasic.h.
{
     return print(str) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [5/11]
size_t PrintBasic::println (double n, uint8_t prec = 2) inline inherited
Definition at line 114 of file PrintBasic.h.
{
     return print(n, prec) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [6/11]
size_t PrintBasic::println (int n, uint8_t base = 10) inline inherited
Definition at line 123 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [7/11]
size_t PrintBasic::println (long n, uint8_t base = 10) inline inherited
Definition at line 129 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [8/11]
size_t PrintBasic::println (signed char n, uint8_t base = 10) inline inherited
Definition at line 117 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [9/11]
size_t PrintBasic::println (unsigned char n, uint8_t base = 10) inline inherited
Definition at line 120 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [10/11]
size_t PrintBasic::println (unsigned int n, uint8_t base = 10) inline inherited
Definition at line 126 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [11/11]
size_t PrintBasic::println (unsigned long n, uint8_t base = 10) inline inherited
Definition at line 132 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
printModifyDateTime()
size_t FsBaseFile::printModifyDateTime (print_t * pr) inline inherited
Print a file's modify date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 550 of file FsFile.h.
{
     return m_fFile ? m_fFile->printModifyDateTime(pr) :
            m_xFile ? m_xFile->printModifyDateTime(pr) : 0;
   }
printName()
size_t FsBaseFile::printName (print_t * pr) inline inherited
Print a file's name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 560 of file FsFile.h.
{
     return m_fFile ? m_fFile->printName(pr) :
            m_xFile ? m_xFile->printName(pr) : 0;
   }
printNum()
size_t PrintBasic::printNum (unsigned long n, uint8_t base) private inherited
Definition at line 34 of file PrintBasic.cpp.
{
   const uint8_t DIM = 8*sizeof(long);
   char buf[DIM];
   char *str = &buf[DIM];
   if (base < 2) return 0;
   do {
     char c = n%base;
     n /= base;
     *--str = c + (c < 10 ? '0' : 'A' - 10);
   } while (n);
   return write(str, &buf[DIM] - str);
 }
References buf, and PrintBasic::write().
Referenced by PrintBasic::print().
read() [1/2]
int StreamFile< FsBaseFile , uint64_t >::read () inline inherited
Read the next byte from a file.
Returns
For success return the next byte in the file as an int. If an error occurs or end of file is reached return -1.
Definition at line 113 of file ArduinoFiles.h.
              {
     return BaseFile::read();
   }
read() [2/2]
int FsBaseFile::read (void * buf, size_t count) inline inherited
Read data from a file starting at the current position.
Parameters
[out] buf Pointer to the location that will receive the data.
[in] count Maximum number of bytes to read.
Returns
For success read() returns the number of bytes read. A value less than count, including zero, will be returned if end of file is reached. If an error occurs, read() returns -1. Possible errors include read() called before a file has been opened, corrupt file system or an I/O error occurred.
Definition at line 586 of file FsFile.h.
{
     return m_fFile ? m_fFile->read(buf, count) :
            m_xFile ? m_xFile->read(buf, count) : -1;
   }
References buf, and count.
remove() [1/2]
bool FsBaseFile::remove () inherited
Remove a file.
The directory entry and all data for the file are deleted.
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 178 of file FsFile.cpp.
{
   if (m_fFile) {
     if (m_fFile->remove()) {
       m_fFile = nullptr;
       return true;
     }
   } else if (m_xFile) {
     if (m_xFile->remove()) {
       m_xFile = nullptr;
       return true;
     }
   }
   return false;
 }
References FsBaseFile::m_fFile, FsBaseFile::m_xFile, ExFatFile::remove(), and FatFile::remove().
remove() [2/2]
bool FsBaseFile::remove (const char * path) inline inherited
Remove a file.
The directory entry and all data for the file are deleted.
Parameters
[in] path Path for the file to be removed.
Example use: dirFile.remove(filenameToRemove);
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 615 of file FsFile.h.
{
     return m_fFile ? m_fFile->remove(path) :
            m_xFile ? m_xFile->remove(path) : false;
   }
rename() [1/2]
bool FsBaseFile::rename (const char * newPath) inline inherited
Rename a file or subdirectory.
Parameters
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 625 of file FsFile.h.
{
     return m_fFile ? m_fFile->rename(newPath) :
            m_xFile ? m_xFile->rename(newPath) : false;
   }
rename() [2/2]
bool FsBaseFile::rename (FsBaseFile * dirFile, const char * newPath) inline inherited
Rename a file or subdirectory.
Parameters
[in] dirFile Directory for the new path.
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 636 of file FsFile.h.
{
     return m_fFile ? m_fFile->rename(dirFile->m_fFile, newPath) :
            m_xFile ? m_xFile->rename(dirFile->m_xFile, newPath) : false;
   }
References FsBaseFile::m_fFile, and FsBaseFile::m_xFile.
rewind()
void FsBaseFile::rewind () inline inherited
Set the file's current position to zero.
Definition at line 641 of file FsFile.h.
                 {
     if (m_fFile) m_fFile->rewind();
     if (m_xFile) m_xFile->rewind();
   }
rewindDirectory()
void StreamFile< FsBaseFile , uint64_t >::rewindDirectory () inline inherited
Rewind a file if it is a directory
Definition at line 117 of file ArduinoFiles.h.
{
     if (BaseFile::isDir()) {
       BaseFile::rewind();
     }
   }
rmdir()
bool FsBaseFile::rmdir () inherited
Remove a directory file.
The directory file will be removed only if it is empty and is not the root directory. rmdir() follows DOS and Windows and ignores the read-only attribute for the directory.
Note
This function should not be used to delete the 8.3 version of a directory that has a long name. For example if a directory has the long name "New folder" you should not delete the 8.3 name "NEWFOL~1".
Returns
true for success or false for failure.
Definition at line 193 of file FsFile.cpp.
{
   if (m_fFile) {
     if (m_fFile->rmdir()) {
       m_fFile = nullptr;
       return true;
     }
   } else if (m_xFile) {
     if (m_xFile->rmdir()) {
       m_xFile = nullptr;
       return true;
     }
   }
   return false;
 }
References FsBaseFile::m_fFile, FsBaseFile::m_xFile, ExFatFile::rmdir(), and FatFile::rmdir().
seek()
bool StreamFile< FsBaseFile , uint64_t >::seek (uint64_t pos) inline inherited
Seek to a new position in the file, which must be between 0 and the size of the file (inclusive).
Parameters
[in] pos the new file position.
Returns
true for success or false for failure.
Definition at line 129 of file ArduinoFiles.h.
{
     return BaseFile::seekSet(pos);
   }
seekCur()
bool FsBaseFile::seekCur (int64_t offset) inline inherited
Set the files position to current position + pos. See seekSet().
Parameters
[in] offset The new position in bytes from the current position.
Returns
true for success or false for failure.
Definition at line 673 of file FsFile.h.
{
     return seekSet(curPosition() + offset);
   }
Referenced by ILI9341_t3_ERIS::bltSD().
seekEnd()
bool FsBaseFile::seekEnd (int64_t offset = 0) inline inherited
Set the files position to end-of-file + offset. See seekSet(). Can't be used for directory files since file size is not defined.
Parameters
[in] offset The new position in bytes from end-of-file.
Returns
true for success or false for failure.
Definition at line 681 of file FsFile.h.
{
     return seekSet(fileSize() + offset);
   }
seekSet()
bool FsBaseFile::seekSet (uint64_t pos) inline inherited
Sets a file's position.
Parameters
[in] pos The new position in bytes from the beginning of the file.
Returns
true for success or false for failure.
Definition at line 690 of file FsFile.h.
{
     return m_fFile ? pos < (1ULL << 32) && m_fFile->seekSet(pos) :
            m_xFile ? m_xFile->seekSet(pos) : false;
   }
Referenced by ILI9341_t3_ERIS::bltSDAnimationFullScreen(), and ILI9341_t3_ERIS::bltSDFullScreen().
setWriteError()
void PrintBasic::setWriteError (int err = 1) inline protected inherited
Definition at line 152 of file PrintBasic.h.
{
     m_error = err;
   }
References PrintBasic::m_error.
Referenced by PrintBasic::clearWriteError().
size() [1/2]
uint64_t StreamFile< FsBaseFile , uint64_t >::size () inline inherited
Returns
the file's size.
Definition at line 133 of file ArduinoFiles.h.
                  {
     return BaseFile::fileSize();
   }
size() [2/2]
uint64_t FsBaseFile::size () const inline inherited
Returns
the file's size.
Definition at line 695 of file FsFile.h.
 {return fileSize();}
sync()
bool FsBaseFile::sync () inline inherited
The sync() call causes all modified data and directory fields to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 701 of file FsFile.h.
               {
     return m_fFile ? m_fFile->sync() :
            m_xFile ? m_xFile->sync() : false;
   }
Referenced by FsBaseFile::flush().
timestamp()
bool FsBaseFile::timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second) inline inherited
Set a file's timestamps in its directory entry.
Parameters
[in] flags Values for flags are constructed by a bitwise-inclusive OR of flags from the following list
T_ACCESS - Set the file's last access date and time.
T_CREATE - Set the file's creation date and time.
T_WRITE - Set the file's last write/modification date and time.
Parameters
[in] year Valid range 1980 - 2107 inclusive.
[in] month Valid range 1 - 12 inclusive.
[in] day Valid range 1 - 31 inclusive.
[in] hour Valid range 0 - 23 inclusive.
[in] minute Valid range 0 - 59 inclusive.
[in] second Valid range 0 - 59 inclusive
Note
It is possible to set an invalid date since there is no check for the number of days in a month.
Modify and access timestamps may be overwritten if a date time callback function has been set by dateTimeCallback().
Returns
true for success or false for failure.
Definition at line 737 of file FsFile.h.
{
     return m_fFile ?
            m_fFile->timestamp(flags, year, month, day, hour, minute, second) :
            m_xFile ?
            m_xFile->timestamp(flags, year, month, day, hour, minute, second) :
            false;
   }
References second.
truncate() [1/2]
bool FsBaseFile::truncate () inline inherited
Truncate a file to the current position.
Returns
true for success or false for failure.
Definition at line 749 of file FsFile.h.
                   {
     return m_fFile ? m_fFile->truncate() :
            m_xFile ? m_xFile->truncate() : false;
   }
truncate() [2/2]
bool FsBaseFile::truncate (uint64_t length) inline inherited
Truncate a file to a specified length. The current file position will be set to end of file.
Parameters
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 760 of file FsFile.h.
{
     return m_fFile ? length < (1ULL << 32) && m_fFile->truncate(length) :
            m_xFile ? m_xFile->truncate(length) : false;
   }
write() [1/5]
size_t PrintBasic::write (const char * buffer, size_t size) inline inherited
Definition at line 147 of file PrintBasic.h.
{
     return write((const uint8_t*)buffer, size);
   }
References PrintBasic::write().
write() [2/5]
size_t PrintBasic::write (const char * str) inline inherited
Definition at line 135 of file PrintBasic.h.
{
     return write(str, strlen(str));
   }
Referenced by ExFatPartition::checkUpcase(), dmpDirData(), ExFatPartition::dmpFat(), FatPartition::dmpFat(), FatFile::dmpFile(), ExFatPartition::dmpSector(), FatPartition::dmpSector(), fsPrintDate(), fsPrintDateTime(), fsPrintTime(), fsPrintTimeZone(), ExFatFile::ls(), FatFile::ls(), PrintBasic::print(), printDirLabel(), PrintBasic::printDouble(), printExFatBoot(), ExFatPartition::printFat(), printFatDir(), ExFatFile::printFileSize(), FatFile::printFileSize(), printHex(), PrintBasic::println(), printMbr(), ExFatFile::printName7(), FatFile::printName7(), ExFatFile::printName8(), FatFile::printName8(), PrintBasic::printNum(), FatFile::printSFN(), ExFatPartition::printUpcase(), and PrintBasic::write().
write() [3/5]
size_t StreamFile< FsBaseFile , uint64_t >::write (const uint8_t * buffer, size_t size) inline virtual inherited
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buffer Pointer to the location of the data to be written.
[in] size Number of bytes to write.
Returns
For success write() returns the number of bytes written, always size.
Reimplemented from PrintBasic.
Definition at line 156 of file ArduinoFiles.h.
{
     return BaseFile::write(buffer, size);
   }
write() [4/5]
size_t FsBaseFile::write (const void * buf, size_t count) inline inherited
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buf Pointer to the location of the data to be written.
[in] count Number of bytes to write.
Returns
For success write() returns the number of bytes written, always nbyte. If an error occurs, write() returns zero and writeError is set.
Definition at line 782 of file FsFile.h.
{
     return m_fFile ? m_fFile->write(buf, count) :
            m_xFile ? m_xFile->write(buf, count) : 0;
   }
References buf, and count.
write() [5/5]
size_t StreamFile< FsBaseFile , uint64_t >::write (uint8_t b) inline virtual inherited
Write a byte to a file. Required by the Arduino Print class.
Parameters
[in] b the byte to be written. Use getWriteError to check for errors.
Returns
1 for success and 0 for failure.
Implements PrintBasic.
Definition at line 141 of file ArduinoFiles.h.
{
     return BaseFile::write(b);
   }
Member Data Documentation
m_error
int PrintBasic::m_error private inherited
Definition at line 159 of file PrintBasic.h.
Referenced by PrintBasic::getWriteError(), and PrintBasic::setWriteError().
m_fFile
FatFile* FsBaseFile::m_fFile = nullptr private inherited
Definition at line 789 of file FsFile.h.
Referenced by FsBaseFile::FsBaseFile(), FsBaseFile::available(), FsBaseFile::available64(), FsBaseFile::clearWriteError(), FsBaseFile::close(), FsBaseFile::contiguousRange(), FsBaseFile::curPosition(), FsBaseFile::dirIndex(), FsBaseFile::exists(), FsBaseFile::fgetpos(), FsBaseFile::fgets(), FsBaseFile::fileSize(), FsBaseFile::firstSector(), FsBaseFile::fsetpos(), FsBaseFile::getAccessDateTime(), FsBaseFile::getCreateDateTime(), FsBaseFile::getError(), FsBaseFile::getModifyDateTime(), FsBaseFile::getName(), FsBaseFile::getWriteError(), FsBaseFile::isBusy(), FsBaseFile::isContiguous(), FsBaseFile::isDir(), FsBaseFile::isFile(), FsBaseFile::isHidden(), FsBaseFile::isOpen(), FsBaseFile::isReadable(), FsBaseFile::isReadOnly(), FsBaseFile::isSubDir(), FsBaseFile::isWritable(), FsBaseFile::mkdir(), FsBaseFile::open(), FsBaseFile::openNext(), FsBaseFile::openRoot(), FsBaseFile::operator=(), FsBaseFile::remove(), FsBaseFile::rename(), and FsBaseFile::rmdir().
m_fileMem
newalign_t FsBaseFile::m_fileMem[FS_ALIGN_DIM(ExFatFile, FatFile)] private inherited
Definition at line 788 of file FsFile.h.
Referenced by FsBaseFile::FsBaseFile(), FsBaseFile::mkdir(), FsBaseFile::open(), FsBaseFile::openNext(), FsBaseFile::openRoot(), and FsBaseFile::operator=().
m_xFile
ExFatFile* FsBaseFile::m_xFile = nullptr private inherited
Definition at line 790 of file FsFile.h.
Referenced by FsBaseFile::FsBaseFile(), FsBaseFile::available(), FsBaseFile::available64(), FsBaseFile::clearWriteError(), FsBaseFile::close(), FsBaseFile::contiguousRange(), FsBaseFile::curPosition(), FsBaseFile::dirIndex(), FsBaseFile::exists(), FsBaseFile::fgetpos(), FsBaseFile::fgets(), FsBaseFile::fileSize(), FsBaseFile::firstSector(), FsBaseFile::fsetpos(), FsBaseFile::getAccessDateTime(), FsBaseFile::getCreateDateTime(), FsBaseFile::getError(), FsBaseFile::getModifyDateTime(), FsBaseFile::getName(), FsBaseFile::getWriteError(), FsBaseFile::isBusy(), FsBaseFile::isContiguous(), FsBaseFile::isDir(), FsBaseFile::isFile(), FsBaseFile::isHidden(), FsBaseFile::isOpen(), FsBaseFile::isReadable(), FsBaseFile::isReadOnly(), FsBaseFile::isSubDir(), FsBaseFile::isWritable(), FsBaseFile::mkdir(), FsBaseFile::open(), FsBaseFile::openNext(), FsBaseFile::openRoot(), FsBaseFile::operator=(), FsBaseFile::remove(), FsBaseFile::rename(), and FsBaseFile::rmdir().
The documentation for this class was generated from the following file:
FsFile.h