ERIS CORE: SvcMIDI::publish
publish()
void SvcMIDI::publish (const char * message)
public interface for the midi callback functions to publish messages to subscribers through thier message handlers
Parameters
message
Definition at line 169 of file SvcMIDI.cpp.
{
     for(uint16_t i = 0; i < MAX_MIDI_MESSAGE_APP_SUBSCRIPTIONS; i ++){
         if (subscriptions[i] == 0) return;
         am->sendMessage(this,am->getApp(subscriptions[i])->name,message);
         am->data->increment("MIDI_MSGS_PUB");
     }
 }
References AppBaseClass::am, AppManager::data, AppManager::getApp(), SvcDataDictionary::increment(), AppBaseClass::name, AppManager::sendMessage(), and subscriptions.
Referenced by handleControlChangeCallback(), handleNoteOffCallback(), handleNoteOnCallback(), and handleProgramChangeCallback().