ERIS CORE: SvcMIDI::midiInit
midiInit()
void SvcMIDI::midiInit () protected
Definition at line 110 of file SvcMIDI.cpp.
                       {
     //start midi
     #ifndef USE_USB_MIDI
     usbMIDI.begin(MIDI_CHANNEL_OMNI); //MIDI_LISTEN_CHANNEL - default listen on channel 7 (set to MIDI_CHANNEL_OMNI to receive all)
     usbMIDI.setHandlePitchBend(handlePitchBendCallback);
     usbMIDI.setHandleError(handleErrorCallback);
     #endif
     usbMIDI.setHandleNoteOff(handleNoteOffCallback);
     usbMIDI.setHandleNoteOn(handleNoteOnCallback);
     usbMIDI.setHandleAfterTouchPoly(handleAfterTouchPolyCallback);
     usbMIDI.setHandleControlChange(handleControlChangeCallback);
     usbMIDI.setHandleProgramChange(handleProgramChangeCallback);
     usbMIDI.setHandleAfterTouchChannel(handleAfterTouchChannelCallback);
     #ifdef USE_USB_MIDI
     usbMIDI.setHandlePitchChange(handlePitchBendCallback);
     usbMIDI.setHandleSongPosition(handleSongPositionCallback);
     #endif
     usbMIDI.setHandleSystemExclusive(handleSystemExclusiveCallback);
     usbMIDI.setHandleTimeCodeQuarterFrame(handleTimeCodeQuarterFrameCallback);
     usbMIDI.setHandleSongSelect(handleSongSelectCallback);
     usbMIDI.setHandleTuneRequest(handleTuneRequestCallback);
     usbMIDI.setHandleClock(handleClockCallback);
     usbMIDI.setHandleStart(handleStartCallback);
     //usbMIDI.setHandleTick(handleTickCallback);
     usbMIDI.setHandleContinue(handleHandleContinue);
     usbMIDI.setHandleStop(handleStopCallback);
     usbMIDI.setHandleActiveSensing(handleActiveSensingCallback);
     usbMIDI.setHandleSystemReset(handleSystemResetCallback);
     //usbMIDI.turnThruOff();
     last_midi_clock_rxtime = 0;
     last_quarter_note_time = micros();
     last_eighth_note_time = micros();
     midi_clock_counter = 0;
     tempo = 90;
     quarter_note_tick = false;
     quarter_note_count = 0;
     eighth_note_count = 0;
     sixteenth_note_count = 0;
     last_arp_note_count = 0;
     midi_note = 0;
     last_midi_note = 1;
     //end global var init
     midi_init = true;
     usbMIDI.begin();
 };
References eighth_note_count, handleActiveSensingCallback(), handleAfterTouchChannelCallback(), handleAfterTouchPolyCallback(), handleClockCallback(), handleControlChangeCallback(), handleErrorCallback(), handleHandleContinue(), handleNoteOffCallback(), handleNoteOnCallback(), handlePitchBendCallback(), handleProgramChangeCallback(), handleSongPositionCallback(), handleSongSelectCallback(), handleStartCallback(), handleStopCallback(), handleSystemExclusiveCallback(), handleSystemResetCallback(), handleTimeCodeQuarterFrameCallback(), handleTuneRequestCallback(), last_arp_note_count, last_eighth_note_time, last_midi_clock_rxtime, last_midi_note, last_quarter_note_time, midi_clock_counter, midi_init, midi_note, quarter_note_count, quarter_note_tick, sixteenth_note_count, and tempo.
Referenced by render().