ERIS CORE: ControlButton::render
render()
void FLASHMEM ControlButton::render () inline override protected virtual
render loop
Reimplemented from AppBaseClass.
Definition at line 74 of file ControlButton.h.
{
         is_dirty = true;
         if(is_pressed==false && show_active == true && time_active > SHOW_ACTIVE_TIME_MILLISEC){
                 show_active = false;
                 is_dirty = true;
                 time_active = 0;
         }
         if (!is_dirty) return;
         if(using_image){
             if(!img_loaded){
                 //allocate space
                 img_cache = new Surface(am->p_fast_img_cache_surface, &am->sd, img_path, img_filename);
                 if(!img_cache){
                     Serial.println(F("M ERROR img_cache out of mem"));
                     Serial.flush();
                     delete(img_cache);
                     return;
                 }else{
                     draw->bltSDB(img_cache->getSurfaceBufferP(), img_cache->getWidth(), img_cache->getHeight(), img_path, img_filename, 0, 0, BLT_COPY); //load img into cache
                     img_loaded = true;
                     return;
                 }
             } else{
                 draw->bltSurface2Surface(am->p_display_surface,x,y,img_cache,0,0,img_cache->getWidth(),img_cache->getHeight(),BLT_COPY);
             }
         }else{
             draw->fillRoundRect(x,y,w,h/2+3,3,am->data->read("UI_BUTTON_FILL_COLOR"));
             draw->fillRoundRect(x,y+h/2,w,h/2,3,am->data->read("UI_BUTTON_SHADE_COLOR"));
         }
         if (show_active){
             draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_ACTIVE_BORDER_COLOR")); //ILI9341_GREENYELLOW
         } else{
             draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_INACTIVE_BORDER_COLOR"));//ILI9341_MAGENTA
         }
         if(!using_image){
             draw->setTextColor(am->data->read("UI_BUTTON_TEXT_COLOR"));
             draw->setCursor(x+(w/2),y+(h/2),true);
             draw->setFont(Arial_9);
             draw->print(text);
         }
         is_dirty = false;
     };
References AppBaseClass::am, Arial_9, BLT_COPY, ILI9341_t3_ERIS::bltSDB(), ILI9341_t3_ERIS::bltSurface2Surface(), AppManager::data, AppBaseClass::draw, Surface::getHeight(), Surface::getSurfaceBufferP(), Surface::getWidth(), AppBaseClass::h, img_cache, img_filename, img_loaded, img_path, is_dirty, is_pressed, AppManager::p_display_surface, AppManager::p_fast_img_cache_surface, SvcDataDictionary::read(), AppManager::sd, show_active, text, time_active, using_image, AppBaseClass::w, AppBaseClass::x, and AppBaseClass::y.