ERIS CORE: ControlButton::setImage
setImage()
void ControlButton::setImage (const char * path, const char * filename) inline
Definition at line 44 of file ControlButton.h.
{
         setPath(path);
         setFile(filename);
         if(img_loaded) delete(img_cache);
         img_loaded = false;
     }
References img_cache, img_loaded, setFile(), and setPath().
Referenced by AppAudioToPolyphonic::initalize().