ERIS CORE: D:/brian/Dev/Eris/ERISCore/src/main.cpp File Reference
main.cpp File Reference
#include <Arduino.h>
#include <SdCard/SdioCard.h>
#include <SdFatConfig.h>
#include <SdFat-beta.h>
#include "HSI.h"
#include "SPI.h"
#include "appTemplate.h"
#include "appExample.h"
#include "appReprogram.h"
#include "appSerialCommandInterface.h"
#include "PCM1863.h"
Macros
#define BUILTIN_SDCARD 254
Functions
void loop (void)
void FLASHMEM setup ()
Variables
MyAppExample app
AppReprogram * appReprogram
AppSerialCommandInterface appSCI
uint16_t inc
elapsedMicros loop_cycle_time
Macro Definition Documentation
BUILTIN_SDCARD
#define BUILTIN_SDCARD 254
Definition at line 2 of file main.cpp.
Function Documentation
loop()
void loop (void)
Definition at line 75 of file main.cpp.
                 {
   //The appManager will...
   //call the handlers of the active app for any triggered events,
   //calls update for the active app
   //calls updateRT for all apps
   loop_cycle_time = 0;
   AppManager::getInstance()->update();
 }
References AppManager::getInstance(), loop_cycle_time, and AppManager::update().
setup()
void FLASHMEM setup ()
Definition at line 20 of file main.cpp.
                       {
   //always run this first to ensure programming mode can be entered through the hmi
   //as access to the physical reset button may be restricted in an integrated application.
   //
   //power on/reset bootrequest check
   pinMode(TAP_INPUT, INPUT);
   pinMode(SW_D, INPUT);
   delay(500);
   Serial.begin(3000000);//baud rate is ignored by the library as it's fixed at max USB speed
   if (digitalRead(TAP_INPUT) == LOW && digitalRead(SW_D) == LOW){
             Serial.println("setup: Power on reset request to enter programming mode in 5 seconds.");
             delay(5000);
             __asm__ volatile ("bkpt #251"); //enter the bootloader
             while(1);
   }
   //while(!Serial); //DEBUG - wait for serial connection
   //reset the i2c bus and config the external ADC
   Serial.println(F("Setup: Initalizing"));
   Serial.println(F("Setup: Configuring Audio Hardware"));
   I2CReset();
   ExtADCConfig();
   //I2CBusScan();
   touch.setCalibrationInputs(452,374,3830,3800); //inital cal values; app manager will monitor and update
   touch.setRotation(3);
   Serial.println(F("Setup: Loading Applications"));
   //app = new MyAppExample;    //note: The AppBaseClass constructor self registers with the app manager
   appReprogram = new AppReprogram();
   AppManager::getInstance()->switchAppFocus(app.getId()); //focus is requested by obj id
   // set the connection goup
   ad.activateConnectionGroup(0);
   Serial.println(F("Setup: Configuring the sw audio block connections"));
   Serial.println(F("Setup: Init Complete"));
   Serial.print(F("Ext ADC Operating State (15:RUNNING): "));
   Serial.println(ExtADCReadReg(114));
   Serial.print(F("Ext ADC Sample Freq: "));
   Serial.println(ExtADCReadReg(115));
   Serial.print(F("Ext ADC BCLK Ratio: "));
   Serial.println((ExtADCReadReg(116) >> 4) & 0x7);
   Serial.print(F("Ext ADC SCLK Ratio: "));
   Serial.println(ExtADCReadReg(116) & 0x7);
   Serial.print(F("Ext ADC CLK Error Status (0:OK): "));
   Serial.println(ExtADCReadReg(117));
   Serial.print(F("Ext ADC Voltage Status (7:OK): "));
   Serial.println(ExtADCReadReg(120));
   for (int i =0; i < 12;i++){
     Serial.print(F("Ext ADC CONF REG VALUE"));
     Serial.print(i);
     Serial.print(F(": "));
     Serial.println(ExtADCReadReg(i),HEX);
   }
 }
References AudioDirector::activateConnectionGroup(), ad, app, appReprogram, ExtADCConfig(), ExtADCReadReg(), F, AppBaseClass::getId(), AppManager::getInstance(), HEX, I2CReset(), INPUT, LOW, Touch::setCalibrationInputs(), SW_D, AppManager::switchAppFocus(), TAP_INPUT, and touch().
Referenced by userSetup().
Variable Documentation
app
MyAppExample app
Definition at line 15 of file main.cpp.
Referenced by AppManager::RegisterApp(), and setup().
appReprogram
AppReprogram* appReprogram
Definition at line 17 of file main.cpp.
Referenced by setup().
appSCI
AppSerialCommandInterface appSCI
Definition at line 16 of file main.cpp.
inc
uint16_t inc
Definition at line 14 of file main.cpp.
loop_cycle_time
elapsedMicros loop_cycle_time
Definition at line 74 of file main.cpp.
Referenced by loop().