ERIS CORE: Fast Pin I/O
Fast Pin I/O
Classes
class DigitalPin< PinNumber >
Fast digital port I/O.
Macros
#define fastPinConfig(pin, mode, level) {fastPinMode(pin, mode); fastDigitalWrite(pin, level);}
Functions
bool fastDigitalRead (uint8_t pin)
void fastDigitalToggle (uint8_t pin)
void fastDigitalWrite (uint8_t pin, bool value)
void fastPinMode (uint8_t pin, uint8_t mode)
Detailed Description
Fast Digital I/O functions and template class.
Macro Definition Documentation
fastPinConfig
#define fastPinConfig (pin, mode, level) {fastPinMode(pin, mode); fastDigitalWrite(pin, level);}
set pin configuration
Parameters
[in] pin Arduino pin number
[in] mode mode INPUT or OUTPUT.
[in] level If mode is output, set level high/low. If mode is input, enable or disable the pin's 20K pullup.
Definition at line 289 of file DigitalPin.h.
Function Documentation
fastDigitalRead()
bool fastDigitalRead (uint8_t pin) inline
Definition at line 269 of file DigitalPin.h.
{
   return digitalRead(pin);
 }
Referenced by DigitalPin< PinNumber >::__attribute__(), and fastDigitalToggle().
fastDigitalToggle()
void fastDigitalToggle (uint8_t pin) inline
Definition at line 274 of file DigitalPin.h.
{
   fastDigitalWrite(pin, !fastDigitalRead(pin));
 }
References fastDigitalRead(), and fastDigitalWrite().
Referenced by DigitalPin< PinNumber >::__attribute__().
fastDigitalWrite()
void fastDigitalWrite (uint8_t pin, bool value) inline
Definition at line 265 of file DigitalPin.h.
{
   digitalWrite(pin, value);
 }
Referenced by DigitalPin< PinNumber >::__attribute__(), and fastDigitalToggle().
fastPinMode()
void fastPinMode (uint8_t pin, uint8_t mode) inline
Definition at line 278 of file DigitalPin.h.
{
   pinMode(pin, mode);
 }
References mode.
Referenced by DigitalPin< PinNumber >::__attribute__().