ERIS CORE: AppWren::dynamicSurfaceManager
dynamicSurfaceManager()
bool FLASHMEM AppWren::dynamicSurfaceManager () protected
responsible for managing the surface buffer memory allocation
Returns
true
false
Definition at line 705 of file AppWren.cpp.
{
   if(!surface_cache){
     surface_mempool = wrenFastRam;
     if (has_pop || has_focus){
       surface_cache = new Surface((uint16_t *)draw->getFrameAddress(),width,height);
       memset((uint16_t *)draw->getFrameAddress(),200,sizeof(uint16_t)*WREN_FRAME_BUFFER_SIZE);
     }else{
       surface_cache = new Surface(surface_mempool, widget_width, widget_height);
       memset(surface_mempool,0,sizeof(uint16_t)*widget_width*widget_height);
     }
   }else{
     //check for state changes and adjust the buffer accordingly
     if (has_pop || has_focus){
       if( (width != surface_cache->getWidth()) || (height != surface_cache->getHeight()) ){
         delete(surface_cache);
         surface_cache = new Surface(surface_mempool, width, height);
         memset(surface_mempool,0,sizeof(uint16_t)*width*height);
       }
     }else{
       if( (widget_width != surface_cache->getWidth()) || (widget_height != surface_cache->getHeight()) ){
         delete(surface_cache);
         surface_cache = new Surface(surface_mempool, widget_width, widget_height);
         memset(surface_mempool,0,sizeof(uint16_t)*widget_width*widget_height);
       }
     }
   }
   if (surface_cache==NULL)return false;
   //wrenCollectGarbage(vm);
   return true;
 }
References AppBaseClass::draw, ILI9341_t3_ERIS::getFrameAddress(), Surface::getHeight(), Surface::getWidth(), AppBaseClass::has_focus, AppBaseClass::has_pop, AppBaseClass::height, surface_cache, surface_mempool, AppBaseClass::widget_height, AppBaseClass::widget_width, and AppBaseClass::width.
Referenced by bltSD2Surface(), bltSurface2FrameBuffer(), drawFill(), drawLine(), render(), and setPixel().