ERIS CORE: AppWren::bltSD2Surface
bltSD2Surface()
void AppWren::bltSD2Surface (const char * path, const char * filename, int16_t x, int16_t y, bltAlphaType alpha_type) inline
block tramsfer from SD to surface
Parameters
path
filename
x
y
Definition at line 275 of file AppWren.h.
{
         dynamicSurfaceManager();
         uint16_t *sb = surface_cache->getSurfaceBufferP();
         draw->bltSDB(sb,surface_cache->getWidth(),surface_cache->getHeight(),path,filename,x,y,alpha_type);
     }
References ILI9341_t3_ERIS::bltSDB(), AppBaseClass::draw, dynamicSurfaceManager(), filename, Surface::getHeight(), Surface::getSurfaceBufferP(), Surface::getWidth(), surface_cache, AppBaseClass::x, and AppBaseClass::y.
Referenced by loadImageSurfaceCallback().