ERIS CORE: AppWren::messageHandler
messageHandler()
void FLASHMEM AppWren::messageHandler (AppBaseClass * sender, const char * message) virtual
handles messages from other sw components
Parameters
sender
message
Reimplemented from AppBaseClass.
Definition at line 1271 of file AppWren.cpp.
{
     if(sender->isName("SCI")){
         if(0 == strncmp(message,"WREN_SCRIPT_EXECUTE",strlen("WREN_SCRIPT_EXECUTE"))) {
             Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_COMPILE -> compileOnly = false"));
             compile_only = false;
             return;
         }else if(0 == strncmp(message,"WREN_SCRIPT_COMPILE",strlen("WREN_SCRIPT_COMPILE"))) {
             Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_EXECUTE -> compileOnly = true"));
             compile_only = true;
             return;
         }else if(0 == strncmp(message,"WREN_SCRIPT_SAVE",strlen("WREN_SCRIPT_SAVE"))){
             char cmd[128];
             int total_read;
             total_read = sscanf(message, "%127s %23s\n" , cmd, wren_module_name);
             if (total_read==2){
               strcat(wren_module_name,".wren");
               Serial.print(F("M AppWren::MessageHandler: WREN_SCRIPT_SAVE as: "));
               Serial.println(wren_module_name);
               save_module = true;
             }
             return;
         }else{ //if the message payload is not a command then assume its the data
             if(save_module){
               FsFile file;
               sd->chdir("/wren");
               sd->remove(wren_module_name);
               file = sd->open(wren_module_name, O_WRONLY|O_CREAT);
               file.write(message,strlen(message));
               file.close();
               save_module = false;
               Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_SAVE complete"));
             }else if(compile_only){
               Serial.println(F("M AppWren::MessageHandler: Compiling the received script"));
               return;
             }else{ //execute the script
                 Serial.println(F("M ************************************************************************"));
                 Serial.println(F("M AppWren::MessageHandler: Restarting the VM"));
                 if(!has_focus){
                   //cycling the focus triggers the parent app to recover any system changes made by the VM
                   getFocus();
                   returnFocus();
                 }else{
                   returnFocus();
                 }
                 restartVM();
                 Serial.println(F("M AppWren::MessageHandler: Loading the received script"));
                 if(!loadScript(message)){
                     enable_call_forwarding = false;
                     restartVM();
                 } else enable_call_forwarding = true;
                 Serial.println(F("M AppWren::MessageHandler: request complete"));
                 Serial.println(F("M ************************************************************************"));
                 return;
             }
         }
     } else{
       //All other messages from senders other than the SCI will be forwarded to the VM
       //Serial is dedicated to serial comms with the VM for stdio/stderr
       wrenEnsureSlots(vm, 3);
       wrenSetSlotHandle(vm, 0, h_slot0);//App
       wrenSetSlotString(vm, 1, sender->name);//sender
       wrenSetSlotString(vm, 2, message);//message
       isWrenResultOK(wrenCall(vm,h_messageHandler));
     }
 }
References compile_only, enable_call_forwarding, getFocus(), h_messageHandler, h_slot0, AppBaseClass::has_focus, AppBaseClass::isName(), isWrenResultOK(), loadScript(), AppBaseClass::name, restartVM(), returnFocus(), save_module, AppBaseClass::sd, vm, and wren_module_name.