ERIS CORE: AppWren::bltRAMDrive2Surface
bltRAMDrive2Surface()
void AppWren::bltRAMDrive2Surface (const char * path, const char * filename, int16_t x, int16_t y, bltMode blt_mode) inline
block tramsfer from ram drive file to surface
Parameters
path
filename
x
y
Definition at line 313 of file AppWren.h.
{
         dynamicSurfaceManager();
         AudioNoInterrupts();
         uint16_t *sb = surface_cache->getSurfaceBufferP();
         File file = wren_file_system.open(filename,O_RDONLY);
         if(file.available()>0){
             draw->bltRAMFileB(sb,surface_cache->getWidth(),surface_cache->getHeight(),&file,x,y,blt_mode);
             file.close();
         }
         AudioInterrupts();
     }
References ILI9341_t3_ERIS::bltRAMFileB(), AppBaseClass::draw, dynamicSurfaceManager(), Surface::getHeight(), Surface::getSurfaceBufferP(), Surface::getWidth(), surface_cache, wren_file_system, AppBaseClass::x, and AppBaseClass::y.
Referenced by loadImageSurfaceCallback().