ERIS CORE: AppWren::shutdownVM
shutdownVM()
void AppWren::shutdownVM () inline
shutdown the VM
Definition at line 95 of file AppWren.h.
                      {
         if(has_pop){
             am->releasePopUp();
             has_pop = false;
         }
         releaseWrenHandles();
         wrenFreeVM(vm);
         if(surface_cache){
             //delete(surface_cache);
             //surface_cache = NULL;
         }
     }
References AppBaseClass::am, AppBaseClass::has_pop, AppManager::releasePopUp(), releaseWrenHandles(), surface_cache, and vm.
Referenced by restartVM().