ERIS CORE: AppWren::startVM
startVM()
void FLASHMEM AppWren::startVM ()
start the VM
Definition at line 615 of file AppWren.cpp.
{
     Serial.println(F("\nM AppWren::startVM()"));
     WrenConfiguration config;
     wrenInitConfiguration(&config);
     config.writeFn = &writeFn;
     config.errorFn = &errorFn;
 #ifdef USE_EXTMEM
     config.initialHeapSize = WREN_VM_HEAP_SIZE;//WREN_VM_HEAP_SIZE;
     config.minHeapSize = 32000;
     config.heapGrowthPercent = 5;
     //config.reallocateFn = &wrenFastMemoryAllocator;
 #else
     config.initialHeapSize = WREN_VM_HEAP_SIZE * 2;//WREN_VM_HEAP_SIZE;
     config.minHeapSize = WREN_VM_HEAP_SIZE;
     config.heapGrowthPercent = 10;
 #endif
     config.bindForeignMethodFn = &bindForeignMethod;
     config.loadModuleFn = &loadModule;
     vm = wrenNewVM(&config);
 }
References bindForeignMethod(), errorFn(), loadModule(), vm, WREN_VM_HEAP_SIZE, and writeFn().
Referenced by restartVM(), and vmConstructor().