ERIS CORE: AppWren::update
update()
void AppWren::update () override protected virtual
Reimplemented from AppBaseClass.
Definition at line 702 of file AppWren.cpp.
                      {
         if (h_update==0){ //if no script loaded
             return;
         } else{
           if(reboot_request){
             reboot_request = false;
             //handle the reboot request from the running wren script
             restartVM();
             loadScript(loadModuleSource(wren_module_name));
             freeModuleSource();
             return;
           }
           wrenEnsureSlots(vm, 1);
           wrenSetSlotHandle(vm, 0, h_slot0);//App
           if (!isWrenResultOK(wrenCall(vm,h_update))){
           }else{
               if(isPressed==false && show_active == true && time_active > SHOW_ACTIVE_TIME_MILLISEC){
                       show_active = false;
                       time_active = 0;
               }
               if(usingImage){
                   if(!surface_cache){
                       //surface_cache = new Surface(am->fastImgCacheSurfaceP, widget_width, widget_height);
                       if(!dynamicSurfaceManager()){
                           Serial.println(F("M AppWren::update() VM ERROR: Surface not available"));
                           return;
                       }else Serial.println(F("M AppWren::update() Surface created"));
                   } else{
                     if(has_pop || has_focus){
                       //do nothing
                     }else{
                       draw->bltMem(am->displaySurfaceP,surface_cache,x,y,AT_NONE);
                     }
                   }
               }else{
                   draw->fillRoundRect(x,y,w,h/2+3,3,am->data->read("UI_BUTTON_FILL_COLOR"));
                   draw->fillRoundRect(x,y+h/2,w,h/2,3,am->data->read("UI_BUTTON_SHADE_COLOR"));
               }
               if(has_pop || has_focus){
                 //do nothing
               }else{
                 if (show_active){
                     draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_ACTIVE_BORDER_COLOR"));
                 } else{
                     draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_INACTIVE_BORDER_COLOR"));
                 }
                 if(!usingImage){
                     draw->setTextColor(am->data->read("UI_BUTTON_TEXT_COLOR"));
                     draw->setCursor(x+(w/2),y+(h/2),true);
                     draw->setFont(Arial_9);
                     //draw->print(text);
                 }
               }
           }
         }
         if(tempmonGetTemp()>63.0) set_arm_clock(400000000);//thermal guard (safer but not failsafe)
         wrenCollectGarbage(vm);
     };    //called only when the app is active
References AppBaseClass::am, Arial_9, AT_NONE, ILI9341_t3_ERIS::bltMem(), AppBaseClass::draw, dynamicSurfaceManager(), freeModuleSource(), AppBaseClass::h, h_slot0, h_update, AppBaseClass::has_focus, AppBaseClass::has_pop, isPressed, isWrenResultOK(), loadModuleSource(), loadScript(), reboot_request, restartVM(), set_arm_clock(), show_active, SHOW_ACTIVE_TIME_MILLISEC, surface_cache, time_active, usingImage, vm, AppBaseClass::w, wren_module_name, AppBaseClass::x, and AppBaseClass::y.