ERIS CORE: AppWren::MessageHandler
MessageHandler()
void FLASHMEM AppWren::MessageHandler (AppBaseClass * sender, const char * message) virtual
Reimplemented from AppBaseClass.
Definition at line 566 of file AppWren.cpp.
{
     if(sender->isName("SCI")){
         if(0 == strncmp(message,"WREN_SCRIPT_EXECUTE",strlen("WREN_SCRIPT_EXECUTE"))) {
             Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_COMPILE -> compileOnly = false"));
             compileOnly = false;
             return;
         }else if(0 == strncmp(message,"WREN_SCRIPT_COMPILE",strlen("WREN_SCRIPT_COMPILE"))) {
             Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_EXECUTE -> compileOnly = true"));
             compileOnly = true;
             return;
         }else if(0 == strncmp(message,"WREN_SCRIPT_SAVE",strlen("WREN_SCRIPT_SAVE"))){
             char cmd[128];
             int total_read;
             total_read = sscanf(message, "%s %s\n" , cmd, save_module_as);
             if (total_read==2){
               //save the file
               //strcpy(file_name,"/wren/");
               strcat(save_module_as,".wren");
               //strcat(file_name,save_module_as);
               //strcpy(save_module_as,file_name);
               Serial.print(F("M AppWren::MessageHandler: WREN_SCRIPT_SAVE as: "));
               Serial.println(save_module_as);
               save_module = true;
             }
             return;
         }else{ //if the message payload is not a command then assume its the data
             if(save_module){
               set_arm_clock(600000000);
               FsFile file;
               sd->chdir("/wren");
               sd->remove(save_module_as);
               sd->remove("temp.wren");
               sd->remove("test.wren");
               sd->remove("test2.wren");
               sd->remove(save_module_as);
               file = sd->open(save_module_as, O_WRONLY|O_CREAT);
               file.write(message,strlen(message));
               //file.write("//DEBUG\n\n",strlen("//DEBUG\n\n"));
               file.close();
               save_module = false;
               Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_SAVE complete"));
             }else if(compileOnly){
               Serial.println(F("M AppWren::MessageHandler: Compiling the received script"));
               return;
             }else{ //execute the script
                 Serial.println(F("M AppWren::MessageHandler: Restarting the VM"));
                 if(!has_focus){
                   //cycling the focus triggers the parent app to recover any system changes made by the VM
                   getFocus();
                   returnFocus();
                 }else{
                   returnFocus();
                 }
                 restartVM();
                 Serial.println(F("M AppWren::MessageHandler: Loading the received script"));
                 loadScript(message);
                 Serial.println(F("M AppWren::MessageHandler: cache the wren handles"));
                 getWrenHandles();
                 wrenEnsureSlots(vm, 1);
                 wrenSetSlotHandle(vm, 0, h_slot0);//App
                 Serial.println(F("M AppWren::MessageHandler: request complete"));
                 return;
             }
         }
     } else{
       //All other messages from senders other than the SCI will be forwarded to the VM
       //SerialUSB1 is dedicated to serial comms with the VM for stdio/stderr
       wrenEnsureSlots(vm, 3);
       wrenSetSlotHandle(vm, 0, h_slot0);//App
       wrenSetSlotString(vm, 1, sender->name);//sender
       wrenSetSlotString(vm, 2, message);//message
       isWrenResultOK(wrenCall(vm,h_messageHandler));
     }
 }
References compileOnly, getFocus(), getWrenHandles(), h_messageHandler, h_slot0, AppBaseClass::has_focus, AppBaseClass::isName(), isWrenResultOK(), loadScript(), AppBaseClass::name, restartVM(), returnFocus(), save_module, save_module_as, AppBaseClass::sd, set_arm_clock(), and vm.