ERIS CORE: AppWren::render
render()
void FLASHMEM AppWren::render () override protected virtual
class specific update implementation
Reimplemented from AppBaseClass.
Definition at line 1572 of file AppWren.cpp.
{
         if (enable_call_forwarding == false){ //if no script loaded
             return;
         } else{
           dynamicSurfaceManager();
           if(reboot_request){
             reboot_request = false;
             //handle the reboot request from the running wren script
             restartVM();
             if(!loadScript(loadModuleSource(wren_module_name))){
                 enable_call_forwarding = false;
                 restartVM();
             } else enable_call_forwarding = true;
             freeModuleSource();
             return;
           }
           wrenEnsureSlots(vm, 4);
           wrenSetSlotHandle(vm, 0, h_slot0);//App
           if (!isWrenResultOK(wrenCall(vm,h_render))){
             releaseWrenHandles();
           }else{
               if(is_pressed==false && show_active == true && time_active > SHOW_ACTIVE_TIME_MILLISEC){
                       show_active = false;
                       time_active = 0;
               }
               if(using_image){
                   if(!surface_cache){
                       //surface_cache = new Surface(am->p_fast_img_cache_surface, widget_width, widget_height);
                       if(!dynamicSurfaceManager()){
                           Serial.println(F("M AppWren::render() VM ERROR: Surface not available"));
                           return;
                       }else Serial.println(F("M AppWren::render() Surface created"));
                   } else{
                     if(has_pop || has_focus){
                       //do nothing
                     }else{
                       draw->bltSurface2Surface(am->p_display_surface,x,y,surface_cache,0,0,surface_cache->getWidth(),surface_cache->getHeight(),BLT_COPY);
                     }
                   }
               }else{
                   draw->fillRoundRect(x,y,w,h/2+3,3,am->data->read("UI_BUTTON_FILL_COLOR"));
                   draw->fillRoundRect(x,y+h/2,w,h/2,3,am->data->read("UI_BUTTON_SHADE_COLOR"));
               }
               if(has_pop || has_focus){
                 //do nothing
               }else{
                 if (show_active){
                     draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_ACTIVE_BORDER_COLOR"));
                 } else{
                     draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_INACTIVE_BORDER_COLOR"));
                 }
                 if(!using_image){
                     draw->setTextColor(am->data->read("UI_BUTTON_TEXT_COLOR"));
                     draw->setCursor(x+(w/2),y+(h/2),true);
                     draw->setFont(Arial_9);
                     //draw->print(text);
                 }
               }
           }
         }
         am->data->update("VM_BYTES_ALLOCATED",(int32_t)wrenCollectGarbage(vm));
         draw->disablePixelOP();//disable pixel op and the end of the render cycle
     };    //called only when the app is active
References AppBaseClass::am, Arial_9, BLT_COPY, ILI9341_t3_ERIS::bltSurface2Surface(), AppManager::data, ILI9341_t3_ERIS::disablePixelOP(), AppBaseClass::draw, dynamicSurfaceManager(), enable_call_forwarding, freeModuleSource(), Surface::getHeight(), Surface::getWidth(), AppBaseClass::h, h_render, h_slot0, AppBaseClass::has_focus, AppBaseClass::has_pop, is_pressed, isWrenResultOK(), loadModuleSource(), loadScript(), AppManager::p_display_surface, SvcDataDictionary::read(), reboot_request, releaseWrenHandles(), restartVM(), show_active, surface_cache, time_active, SvcDataDictionary::update(), using_image, vm, AppBaseClass::w, wren_module_name, AppBaseClass::x, and AppBaseClass::y.