ERIS CORE: AppWren::bltSurface2FrameBuffer
bltSurface2FrameBuffer()
void AppWren::bltSurface2FrameBuffer (int16_t from_x, int16_t from_y, int16_t width, int16_t height, int16_t to_x, int16_t to_y, bltMode alpha_type) inline
Definition at line 300 of file AppWren.h.
{
         dynamicSurfaceManager();
         uint16_t *sb = surface_cache->getSurfaceBufferP();
         Surface source((uint16_t*)(sb + from_x + (from_y * surface_cache->getWidth())),width,height);
         Surface dest(draw->getFrameBuffer(),SCREEN_WIDTH,SCREEN_HEIGHT);
         //bltSurface2Surface(Surface *dest, Surface *source,int16_t pos_x,int16_t pos_y,bltMode alpha_type)
         draw->bltSurface2Surface(&dest,to_x,to_y,&source,0,0,source.getWidth(),source.getHeight(),alpha_type);
     }
References ILI9341_t3_ERIS::bltSurface2Surface(), AppBaseClass::draw, dynamicSurfaceManager(), Surface::getHeight(), Surface::getSurfaceBufferP(), Surface::getWidth(), AppBaseClass::height, surface_cache, and AppBaseClass::width.
Referenced by bltCallback().