ERIS CORE: AppWren::getPixel
getPixel()
uint16_t AppWren::getPixel (int16_t x, int16_t y) inline
Definition at line 237 of file AppWren.h.
{
         if (draw){
             if (has_pop){
                 //return draw->readPixel(x,y);
                 return ILI9341_YELLOW;//draw->ILI9341_t3n::readPixel(x,y);
             }else{
                 if (!surface_cache) return ILI9341_MAGENTA;
                 if (x >= surface_cache->getWidth()) return ILI9341_MAGENTA;
                 if (y >= surface_cache->getHeight()) return ILI9341_MAGENTA;
                 if (x < 0 || y < 0) return ILI9341_MAGENTA;
                 return draw->readSurfacePixel(surface_cache,x,y);
             }
         }
         return 0;
     }
References AppBaseClass::draw, Surface::getHeight(), Surface::getWidth(), AppBaseClass::has_pop, ILI9341_t3_ERIS::readSurfacePixel(), surface_cache, AppBaseClass::x, and AppBaseClass::y.
Referenced by getPixelCallback().