ERIS CORE: AppWren::drawFill
drawFill()
void AppWren::drawFill (int16_t r, int16_t g, int16_t b) inline
fills the render target (either a surface or the framebuffer depending on)
Parameters
r
g
b
Definition at line 500 of file AppWren.h.
{
         dynamicSurfaceManager();
         if (draw){
             if (has_pop){
                 draw->fillScreen(CL(r,g,b));
             } else{
                 if (!surface_cache) return;
                 draw->fillSurface(surface_cache,CL(r,g,b),BLT_COPY);
             }
         }
         return;
     }
References BLT_COPY, AppBaseClass::draw, dynamicSurfaceManager(), ILI9341_t3_ERIS::fillSurface(), AppBaseClass::has_pop, and surface_cache.
Referenced by drawFillCallback().