ERIS CORE: AppWren::loadModuleSource
loadModuleSource()
const char *FLASHMEM AppWren::loadModuleSource (const char * name)
receiver for the wren c callback function getSourceForModule
Parameters
name
Returns
const char*
Definition at line 1333 of file AppWren.cpp.
{
   char file_name[128];
   FsFile file;
   int16_t file_size; //max file size 32K
   safer_strncpy(file_name,name,sizeof(file_name));
   strcat(file_name,".wren");
   sd->chdir("/wren");
   file = sd->open(file_name, O_RDONLY);
   file_size = file.available() + 1;
 #ifdef USE_EXTMEM
   module_load_buffer = (char*)extmem_malloc(file_size);
 #else
   module_load_buffer = (char*)malloc(file_size);
 #endif
   if (module_load_buffer == NULL){
     Serial.println(F("M AppWren::loadModuleSource ERROR: Not Enough Memory"));
     return NULL;
   }
   memset(module_load_buffer,0,file_size);
   file.read(module_load_buffer,file_size);
   file.close();
   return module_load_buffer;
 }
References module_load_buffer, AppBaseClass::name, safer_strncpy(), and AppBaseClass::sd.
Referenced by getSourceForModule(), and render().