ERIS CORE: AppWren::vmConstructor
vmConstructor()
void AppWren::vmConstructor ()
start, load and configure the handles of the VM
Definition at line 540 of file AppWren.cpp.
{
     Serial.println(F("M AppWren: Starting the VM"));
     startVM();
     loadScript(g_wrenScript);
     getWrenHandles();
     wrenEnsureSlots(vm, 1);
     wrenSetSlotHandle(vm, 0, h_slot0);//App
     isWrenResultOK(wrenCall(vm,h_updateRT));
 }
References getWrenHandles(), h_slot0, h_updateRT, isWrenResultOK(), loadScript(), startVM(), and vm.
Referenced by AppWren().