ERIS CORE: AppWren::loadScript
loadScript()
void AppWren::loadScript (const char * script) inline
load a script into the running VM
Parameters
script
Definition at line 86 of file AppWren.h.
{
         const char* module = "main";
         Serial.printf("M AppWren:loadScript: Loading script (size: %d bytes)\n",strlen(script));
         if (isWrenResultOK(wrenInterpret(vm, module, script))){
             Serial.println(F("M AppWren::loadScript: OK"));
             getWrenHandles();
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
         }
     }
References getWrenHandles(), h_slot0, isWrenResultOK(), and vm.
Referenced by MessageHandler(), update(), and vmConstructor().