ERIS CORE: AppWren::releaseWrenHandles
releaseWrenHandles()
void AppWren::releaseWrenHandles () protected
release any/all Wren embedded call handles
Definition at line 1651 of file AppWren.cpp.
{
   Serial.printf(F("M AppWren::releaseWrenHandles\n"));
   //release any existing handles
   if (h_slot0!=NULL) {wrenReleaseHandle(vm, h_slot0); h_slot0=NULL;}
   if (h_render!=NULL) {wrenReleaseHandle(vm, h_render); h_render=NULL;}
   if (h_update!=NULL) {wrenReleaseHandle(vm, h_update); h_update=NULL;}
   if (h_onFocus!=NULL) {wrenReleaseHandle(vm, h_onFocus); h_onFocus=NULL;}
   if (h_onFocusLost!=NULL) {wrenReleaseHandle(vm, h_onFocusLost); h_onFocusLost=NULL;}
   if (h_onTouch!=NULL) {wrenReleaseHandle(vm, h_onTouch); h_onTouch=NULL;}
   if (h_onTouchDrag!=NULL) {wrenReleaseHandle(vm, h_onTouchDrag); h_onTouchDrag=NULL;}
   if (h_onTouchRelease!=NULL) {wrenReleaseHandle(vm, h_onTouchRelease); h_onTouchRelease=NULL;}
   if (h_onAnalog1!=NULL) {wrenReleaseHandle(vm, h_onAnalog1); h_onAnalog1=NULL;}
   if (h_onAnalog2!=NULL) {wrenReleaseHandle(vm, h_onAnalog2); h_onAnalog2=NULL;}
   if (h_onAnalog3!=NULL) {wrenReleaseHandle(vm, h_onAnalog3); h_onAnalog3=NULL;}
   if (h_onAnalog4!=NULL) {wrenReleaseHandle(vm, h_onAnalog4); h_onAnalog4=NULL;}
   if (h_messageHandler!=NULL) {wrenReleaseHandle(vm, h_messageHandler); h_messageHandler=NULL;}
   enable_call_forwarding = false;
 }
References enable_call_forwarding, h_messageHandler, h_onAnalog1, h_onAnalog2, h_onAnalog3, h_onAnalog4, h_onFocus, h_onFocusLost, h_onTouch, h_onTouchDrag, h_onTouchRelease, h_render, h_slot0, h_update, and vm.
Referenced by onAnalog1(), onAnalog2(), onAnalog3(), onAnalog4(), onFocus(), onFocusLost(), onTouch(), onTouchDrag(), onTouchRelease(), render(), shutdownVM(), and update().