ERIS CORE: AppWren::isWrenResultOK
isWrenResultOK()
bool AppWren::isWrenResultOK (WrenInterpretResult res) inline protected
Definition at line 508 of file AppWren.h.
{
         switch (res){
             case WREN_RESULT_COMPILE_ERROR:
                 if(sci->requestStartLZ4Message()){
                     sci->printf(F("M AppWren::isWrenResultOK WREN_RESULT_COMPILE_ERROR\n"));
                     sci->printf(F("VM WREN_ERR Compilation Failed\n"));
                     sci->sendLZ4Message();
                 }
                 return false;
             case WREN_RESULT_RUNTIME_ERROR:
                 if(sci->requestStartLZ4Message()){
                     sci->printf(F("M AppWren::isWrenResultOK WREN_RESULT_RUNTIME_ERROR\n"));
                     sci->printf(F("VM WREN_WRN [Implementation Warning] call forwarding will be disabled until next script load.\n"));
                     sci->sendLZ4Message();
                 }
                 return false;
             case WREN_RESULT_SUCCESS:
                 return true;
             default:
                 if(sci->requestStartLZ4Message()){
                     sci->printf(F("M AppWren::isWrenResultOK UNDEFINED RESULT!\n"));
                     sci->sendLZ4Message();
                 }
                 return false; //should never execute
         }
     }
References SvcSerialCommandInterface::requestStartLZ4Message(), AppBaseClass::sci, and SvcSerialCommandInterface::sendLZ4Message().
Referenced by loadScript(), messageHandler(), onAnalog1(), onAnalog2(), onAnalog3(), onAnalog4(), onFocus(), onFocusLost(), onTouch(), onTouchDrag(), onTouchRelease(), render(), update(), and vmConstructor().