ERIS CORE: AppWren::enablePixelOP
enablePixelOP()
void AppWren::enablePixelOP (uint16_t param, pixelOPMode operation)
wren callback interface to enable pixel operations
forwards the call to ILI9341_t3_ERIS which has a matching interface
Parameters
param
operation
Definition at line 1623 of file AppWren.cpp.
{
     am->data->update("DEBUG_PIXOP",(int32_t)operation);
     draw->enablePixelOP(param,operation);
 };
References AppBaseClass::am, AppManager::data, AppBaseClass::draw, ILI9341_t3_ERIS::enablePixelOP(), and SvcDataDictionary::update().
Referenced by drawEnablePixelOp().