ERIS CORE: AppWren::vmConstructor
vmConstructor()
void AppWren::vmConstructor (const char * initial_script)
start, load and configure the handles of the VM
Definition at line 605 of file AppWren.cpp.
{
     startVM();
     loadScript(initial_script);
     getWrenHandles();
     wrenEnsureSlots(vm, 1);
     wrenSetSlotHandle(vm, 0, h_slot0);//App
     isWrenResultOK(wrenCall(vm,h_update));
 }
References getWrenHandles(), h_slot0, h_update, isWrenResultOK(), loadScript(), startVM(), and vm.
Referenced by AppWren().