ERIS CORE: AppWren::drawLine
drawLine()
void AppWren::drawLine (int16_t start_x, int16_t start_y, int16_t end_x, int16_t end_y, int16_t r, int16_t g, int16_t b) inline
draws a line on the render target
Parameters
start_x
start_y
end_x
end_y
r
g
b
Definition at line 349 of file AppWren.h.
{
         if ((start_x == end_x) && (start_y == end_y)){
             if (draw){
                 if (has_pop){
                     draw->ILI9341_t3n::drawPixel(start_x,start_y,CL((uint16_t)r,(uint16_t)g,(uint16_t)b));
                 } else{
                     dynamicSurfaceManager();
                     if (!surface_cache) return;
                     if (start_x >= surface_cache->getWidth()) start_x = surface_cache->getWidth()-1;
                     if (start_y >= surface_cache->getHeight()) start_y = surface_cache->getHeight()-1;
                     if (start_x < 0 ) start_x = 0;
                     if (start_y < 0 ) start_y = 0;
                     if (end_x >= surface_cache->getWidth()) end_x = surface_cache->getWidth()-1;
                     if (end_y >= surface_cache->getHeight()) end_y = surface_cache->getHeight()-1;
                     if (end_x < 0 ) end_x = 0;
                     if (end_y < 0 ) end_y = 0;
                     draw->drawPixel(surface_cache,start_x,start_y,CL(r,g,b));
                 }
             }
             return;
         }else if (draw){
             if (has_pop){
                 draw->ILI9341_t3n::drawLine(start_x, start_y, end_x, end_y, CL(r,g,b));
             }else{
                 dynamicSurfaceManager();
                 if (!surface_cache) return;
                 if (start_x >= surface_cache->getWidth()) start_x = surface_cache->getWidth()-1;
                 if (start_y >= surface_cache->getHeight()) start_y = surface_cache->getHeight()-1;
                 if (start_x < 0 ) start_x = 0;
                 if (start_y < 0 ) start_y = 0;
                 if (end_x >= surface_cache->getWidth()) end_x = surface_cache->getWidth()-1;
                 if (end_y >= surface_cache->getHeight()) end_y = surface_cache->getHeight()-1;
                 if (end_x < 0 ) end_x = 0;
                 if (end_y < 0 ) end_y = 0;
                 draw->drawSurfaceLine(surface_cache, start_x, start_y, end_x, end_y, CL(r,g,b));
             }
             return;
         }
     }
References draw(), ILI9341_t3_ERIS::drawPixel(), ILI9341_t3_ERIS::drawSurfaceLine(), dynamicSurfaceManager(), Surface::getHeight(), Surface::getWidth(), and surface_cache.
Referenced by drawLineCallback().