ERIS CORE: AppWren Class Reference
AppWren Class Reference
Wren is a scripting language. This class is a proxy which mirrors the AppBaseClass into wren.
#include <AppWren.h>
Public Member Functions
AppWren ()
~AppWren ()
void compileScript (const char *script)
void getFocus ()
uint16_t getId ()
bool isName (const char *name_string)
void loadScript (const char *script)
void MessageHandler (AppBaseClass *sender, const char *message)
void RegisterApp (AppBaseClass *app)
void setDimension (int16_t new_width, int16_t new_height)
void setName (const char *name_string)
void setParent (AppBaseClass *parent)
void setPosition (int16_t newOriginX, int16_t newOriginY)
void setWidgetDimension (int16_t new_width, int16_t new_height)
void setWidgetPosition (int16_t newOriginX, int16_t newOriginY)
void vmConstructor ()
Public Attributes
int16_t h
int16_t height
char name [MAX_NAME_LENGTH]
int16_t origin_x
int16_t origin_y
int16_t w
int16_t widget_height
int16_t widget_origin_x
int16_t widget_origin_y
int16_t widget_width
int16_t width
int16_t x
int16_t y
Protected Member Functions
void getWrenHandles ()
bool isWrenResultOK (WrenInterpretResult res)
void onAnalog1 (uint16_t uval, float fval) override
void onAnalog2 (uint16_t uval, float fval) override
void onAnalog3 (uint16_t uval, float fval) override
void onAnalog4 (uint16_t uval, float fval) override
void onFocus () override
void onFocusLost () override
void onTouch (uint16_t t_x, uint16_t t_y) override
void onTouchDrag (uint16_t t_x, uint16_t t_y) override
void onTouchRelease (uint16_t t_x, uint16_t t_y) override
void releasePopUp ()
void releaseWrenHandles ()
void requestPopUp (bool exclusive=false)
void restartVM ()
void returnFocus ()
void selfRegister ()
void setRTPriority (uint16_t level)
void startVM ()
void update () override
void updateRT () override
Protected Attributes
AudioDirector * ad
AppManager * am
bool compileOnly
uint16_t cycle_time
uint16_t cycle_time_max
ILI9341_t3_ERIS * draw
bool has_focus
bool has_pop
uint16_t id
AppBaseClass * nextAppicationNode
AppBaseClass * parentNode
AppBaseClass * previousAppicationNode
SvcSerialCommandInterface * sci
SdFs * sd
bool touch_state
elapsedMicros update_call_period
uint16_t update_call_period_max
uint16_t update_loop_time
uint16_t update_loop_time_max
elapsedMicros updateRT_call_period
uint16_t updateRT_call_period_max
uint16_t updateRT_loop_time
uint16_t updateRT_loop_time_max
uint16_t updateRT_priority
Private Member Functions
void _updatePosition ()
Private Attributes
WrenHandle * h_messageHandler
WrenHandle * h_onAnalog1
WrenHandle * h_onAnalog2
WrenHandle * h_onAnalog3
WrenHandle * h_onAnalog4
WrenHandle * h_onFocus
WrenHandle * h_onFocusLost
WrenHandle * h_onTouch
WrenHandle * h_onTouchDrag
WrenHandle * h_onTouchRelease
WrenHandle * h_slot0
WrenHandle * h_update
WrenHandle * h_updateRT
WrenVM * vm
Detailed Description
Wren is a scripting language. This class is a proxy which mirrors the AppBaseClass into wren.
The use case is to allow scripting of apps Why? with this applications can be dynamically loaded and executed Need another reason? script storage moves from the precious and limited microcontroller flash to the SD card which gives effectivly limitless program storage space. Beware: The available heap defines the upper boundary of VM size
Definition at line 26 of file AppWren.h.
Constructor & Destructor Documentation
AppWren()
AppWren::AppWren () inline
Definition at line 28 of file AppWren.h.
              :AppBaseClass(){
         strcpy(name,"AppWren");
         h_slot0 = 0;
         vm = 0;
         h_update = 0;
         h_updateRT = 0;
         h_onFocus = 0;
         h_onFocusLost = 0;
         h_onTouch = 0;
         h_onTouchDrag = 0;
         h_onTouchRelease = 0;
         h_onAnalog1 = 0;
         h_onAnalog2 = 0;
         h_onAnalog3 = 0;
         h_onAnalog4 = 0;
         h_messageHandler = 0;
         compileOnly = false;
         vmConstructor();
     };
References compileOnly, h_messageHandler, h_onAnalog1, h_onAnalog2, h_onAnalog3, h_onAnalog4, h_onFocus, h_onFocusLost, h_onTouch, h_onTouchDrag, h_onTouchRelease, h_slot0, h_update, h_updateRT, AppBaseClass::name, vm, and vmConstructor().
~AppWren()
AppWren::~AppWren () inline
Definition at line 47 of file AppWren.h.
               {
         wrenFreeVM(vm);
     };
References vm, and wrenFreeVM().
Member Function Documentation
_updatePosition()
void AppBaseClass::_updatePosition () private inherited
Definition at line 55 of file AppBaseClass.cpp.
{
   if(has_focus || has_pop){
     w = width;
     h = height;
     x = origin_x;
     y = origin_y;
   }else{
     w = widget_width;
     h = widget_height;
     x = widget_origin_x;
     y = widget_origin_y;
   }
   return;
 }
References AppBaseClass::h, AppBaseClass::has_focus, AppBaseClass::has_pop, AppBaseClass::height, AppBaseClass::origin_x, AppBaseClass::origin_y, AppBaseClass::w, AppBaseClass::widget_height, AppBaseClass::widget_origin_x, AppBaseClass::widget_origin_y, AppBaseClass::widget_width, AppBaseClass::width, AppBaseClass::x, and AppBaseClass::y.
Referenced by AppBaseClass::getFocus(), AppBaseClass::releasePopUp(), AppBaseClass::requestPopUp(), AppBaseClass::returnFocus(), AppBaseClass::setDimension(), AppBaseClass::setPosition(), AppBaseClass::setWidgetDimension(), and AppBaseClass::setWidgetPosition().
compileScript()
void AppWren::compileScript (const char * script) inline
Definition at line 53 of file AppWren.h.
{
     }
getFocus()
void AppBaseClass::getFocus () inherited
Definition at line 70 of file AppBaseClass.cpp.
{
     has_focus = true;
     AppManager::getInstance()->getFocus(this->id);
     _updatePosition();
     return;
 }
References AppBaseClass::_updatePosition(), and AppBaseClass::has_focus.
Referenced by setup().
getId()
uint16_t AppBaseClass::getId () inline inherited
Definition at line 80 of file AppBaseClass.h.
 {return id;};
References AppBaseClass::id.
getWrenHandles()
void AppWren::getWrenHandles () inline protected
Definition at line 92 of file AppWren.h.
{
         wrenEnsureSlots(vm, 1);
         wrenGetVariable(vm, "main", "ErisApp", 0);
         //get the handles
         h_slot0 = wrenGetSlotHandle(vm, 0);
         h_update = wrenMakeCallHandle(vm, "update()");
         h_updateRT = wrenMakeCallHandle(vm, "updateRT()");
         /*
         h_onFocus = wrenMakeCallHandle(vm, "onFocus()");
         h_onFocusLost = wrenMakeCallHandle(vm, "onFocusLost()");
         h_onTouch = wrenMakeCallHandle(vm, "onTouch()");
         h_onTouchDrag = wrenMakeCallHandle(vm, "onTouchDrag()");
         h_onTouchRelease = wrenMakeCallHandle(vm, "onTouchRelease()");
         h_onAnalog1 = wrenMakeCallHandle(vm, "onAnalog1()");
         h_onAnalog2 = wrenMakeCallHandle(vm, "onAnalog2()");
         h_onAnalog3 = wrenMakeCallHandle(vm, "onAnalog3()");
         h_onAnalog4 = wrenMakeCallHandle(vm, "onAnalog4()");
         h_messageHandler = wrenMakeCallHandle(vm, "messageHandler()");
         */
     }
References h_slot0, h_update, h_updateRT, vm, wrenEnsureSlots(), wrenGetSlotHandle(), wrenGetVariable(), and wrenMakeCallHandle().
Referenced by MessageHandler(), and vmConstructor().
isName()
bool AppBaseClass::isName (const char * name_string) inline inherited
Definition at line 81 of file AppBaseClass.h.
{
       bool is;
       (0==strncmp(name,name_string,sizeof(name)))?is=true:is=false;
       return is;
     };
References is, and AppBaseClass::name.
Referenced by AppAudioToPolyphonic::MessageHandler(), AppCQT::MessageHandler(), AppTemplate::MessageHandler(), and MessageHandler().
isWrenResultOK()
bool AppWren::isWrenResultOK (WrenInterpretResult res) inline protected
Definition at line 113 of file AppWren.h.
{
         switch (res){
         case WREN_RESULT_COMPILE_ERROR:
             { Serial.printf("M WREN: Compile Error!\n"); } return false;
         case WREN_RESULT_RUNTIME_ERROR:
             //{ Serial.printf("M WREN: Runtime Error!\n"); }
             return false;
         case WREN_RESULT_SUCCESS:
             return true;
         default:
             return false; //should never execute
         }
     }
References WREN_RESULT_COMPILE_ERROR, WREN_RESULT_RUNTIME_ERROR, and WREN_RESULT_SUCCESS.
Referenced by loadScript(), onAnalog1(), onAnalog2(), onAnalog3(), onAnalog4(), onFocus(), onFocusLost(), onTouch(), onTouchDrag(), onTouchRelease(), update(), updateRT(), and vmConstructor().
loadScript()
void AppWren::loadScript (const char * script) inline
Definition at line 58 of file AppWren.h.
{
         const char* module = "main";
         Serial.println(F("M AppWren: Loading script into the VM"));
         isWrenResultOK(wrenInterpret(vm, module, script));
     }
References F, isWrenResultOK(), vm, and wrenInterpret().
Referenced by MessageHandler(), and vmConstructor().
MessageHandler()
void AppWren::MessageHandler (AppBaseClass * sender, const char * message) virtual
Reimplemented from AppBaseClass.
Definition at line 66 of file AppWren.cpp.
{
     if(sender->isName("SCI")){
         if(strcmp(message,"WREN_SCRIPT_COMPILE")) {
             Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_COMPILE -> compileOnly = true"));
             compileOnly = true;
             return;
         }else if(strcmp(message,"WREN_SCRIPT_EXECUTE")) {
             Serial.println(F("M AppWren::MessageHandler: WREN_SCRIPT_EXECUTE -> compileOnly = false"));
             compileOnly = false;
             return;
         }else{ //if the message payload is not a command then assume its the data
             if(compileOnly){
               Serial.println(F("M AppWren::MessageHandler: Compiling the received script"));
               return;
             }else{ //execute the script
                 Serial.println(F("M AppWren::MessageHandler: Restarting the VM"));
                 restartVM();
                 Serial.println(F("M AppWren::MessageHandler: Loading the received script"));
                 loadScript(message);
                 Serial.println(F("M AppWren::MessageHandler: cache the wren handles"));
                 getWrenHandles();
                 wrenSetSlotHandle(vm, 0, h_slot0);//App
                 Serial.println(F("M AppWren::MessageHandler: request complete"));
             }
         }
     }
 }
References compileOnly, F, getWrenHandles(), h_slot0, AppBaseClass::isName(), loadScript(), restartVM(), vm, and wrenSetSlotHandle().
onAnalog1()
void AppWren::onAnalog1 (uint16_t uval, float fval) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 210 of file AppWren.h.
{
         if (h_onAnalog1==0){
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onAnalog1))){
             };
         }
     };
References h_onAnalog1, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onAnalog2()
void AppWren::onAnalog2 (uint16_t uval, float fval) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 221 of file AppWren.h.
{
         if (h_onAnalog2==0){
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onAnalog2))){
             };
         }
     };
References h_onAnalog2, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onAnalog3()
void AppWren::onAnalog3 (uint16_t uval, float fval) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 232 of file AppWren.h.
{
         if (h_onAnalog3==0){
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onAnalog3))){
             };
         }
     };
References h_onAnalog3, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onAnalog4()
void AppWren::onAnalog4 (uint16_t uval, float fval) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 243 of file AppWren.h.
{
         if (h_onAnalog4==0){
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onAnalog4))){
             };
         }
     };
References h_onAnalog4, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onFocus()
void AppWren::onFocus () inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 152 of file AppWren.h.
{
         if (h_onFocus==0){ //if no script loaded
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onFocus))){
             };
         }
     };   //called when given focus
References h_onFocus, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onFocusLost()
void AppWren::onFocusLost () inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 163 of file AppWren.h.
{
         if (h_onFocusLost==0){ //if no script loaded
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onFocusLost))){
             };
         }
     }; //called when focus is taken
References h_onFocusLost, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onTouch()
void AppWren::onTouch (uint16_t t_x, uint16_t t_y) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 174 of file AppWren.h.
{
         //check if touch point is within the application bounding box
         if (t_x > x && t_x < (x + w) && t_y > y && t_y < (y + h)){
             if (h_onTouch==0){ //if no script loaded
                 return;
             } else{
                 wrenEnsureSlots(vm, 1);
                 wrenSetSlotHandle(vm, 0, h_slot0);//App
                 if (isWrenResultOK(wrenCall(vm,h_onTouch))){
                 };
             }
         }
     };
References AppBaseClass::h, h_onTouch, h_slot0, isWrenResultOK(), vm, AppBaseClass::w, wrenCall(), wrenEnsureSlots(), wrenSetSlotHandle(), AppBaseClass::x, and AppBaseClass::y.
onTouchDrag()
void AppWren::onTouchDrag (uint16_t t_x, uint16_t t_y) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 188 of file AppWren.h.
{
         if (h_onTouchDrag==0){ //if no script loaded
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onTouchDrag))){
             };
         }
     };
References h_onTouchDrag, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
onTouchRelease()
void AppWren::onTouchRelease (uint16_t t_x, uint16_t t_y) inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 199 of file AppWren.h.
{
         if (h_onTouchRelease==0){ //if no script loaded
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_onTouchRelease))){
             };
         }
     };
References h_onTouchRelease, h_slot0, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
RegisterApp()
void AppBaseClass::RegisterApp (AppBaseClass * app) inherited
releasePopUp()
void AppBaseClass::releasePopUp () protected inherited
Definition at line 92 of file AppBaseClass.cpp.
{
   if(!has_pop) return;
   has_pop = false;
   AppManager::getInstance()->releasePopUp();
     _updatePosition();
     return;
 }
References AppBaseClass::_updatePosition(), and AppBaseClass::has_pop.
Referenced by AppCQT::onTouch(), and AppScope::onTouch().
releaseWrenHandles()
void AppWren::releaseWrenHandles () inline protected
Definition at line 75 of file AppWren.h.
{
         //release any existing handles
         if (h_slot0!=NULL) wrenReleaseHandle(vm, h_slot0);
         if (h_update!=NULL) wrenReleaseHandle(vm, h_update);
         if (h_updateRT!=NULL) wrenReleaseHandle(vm, h_updateRT);
         if (h_onFocus!=NULL) wrenReleaseHandle(vm, h_onFocus);
         if (h_onFocusLost!=NULL) wrenReleaseHandle(vm, h_onFocusLost);
         if (h_onTouch!=NULL) wrenReleaseHandle(vm, h_onTouch);
         if (h_onTouchDrag!=NULL) wrenReleaseHandle(vm, h_onTouchDrag);
         if (h_onTouchRelease!=NULL) wrenReleaseHandle(vm, h_onTouchRelease);
         if (h_onAnalog1!=NULL) wrenReleaseHandle(vm, h_onAnalog1);
         if (h_onAnalog2!=NULL) wrenReleaseHandle(vm, h_onAnalog2);
         if (h_onAnalog3!=NULL) wrenReleaseHandle(vm, h_onAnalog3);
         if (h_onAnalog4!=NULL) wrenReleaseHandle(vm, h_onAnalog4);
         if (h_messageHandler!=NULL) wrenReleaseHandle(vm, h_messageHandler);
     }
References h_messageHandler, h_onAnalog1, h_onAnalog2, h_onAnalog3, h_onAnalog4, h_onFocus, h_onFocusLost, h_onTouch, h_onTouchDrag, h_onTouchRelease, h_slot0, h_update, h_updateRT, NULL, vm, and wrenReleaseHandle().
Referenced by restartVM().
requestPopUp()
void AppBaseClass::requestPopUp (bool exclusive = false) protected inherited
Definition at line 85 of file AppBaseClass.cpp.
{
     has_pop = true;
     AppManager::getInstance()->requestPopUp(this->id,exclusive);
     _updatePosition();
     return;
 }
References AppBaseClass::_updatePosition(), and AppBaseClass::has_pop.
Referenced by AppCQT::onTouch(), and AppScope::onTouch().
restartVM()
void AppWren::restartVM () inline protected
Definition at line 67 of file AppWren.h.
                     {
         releaseWrenHandles();
         wrenFreeVM(vm);
         startVM();
     }
References releaseWrenHandles(), startVM(), vm, and wrenFreeVM().
Referenced by MessageHandler().
returnFocus()
void AppBaseClass::returnFocus () protected inherited
Definition at line 77 of file AppBaseClass.cpp.
{
   if(!has_focus) return;
   has_focus = false;
   AppManager::getInstance()->returnFocus();
   _updatePosition();
   return;
 }
References AppBaseClass::_updatePosition(), and AppBaseClass::has_focus.
selfRegister()
void AppBaseClass::selfRegister () protected inherited
Definition at line 53 of file AppBaseClass.cpp.
 {AppManager::getInstance()->RegisterApp(this); }//self register on construction
Referenced by AppBaseClass::AppBaseClass().
setDimension()
void AppBaseClass::setDimension (int16_t new_width, int16_t new_height) inline inherited
Definition at line 93 of file AppBaseClass.h.
 {width=new_width;height=new_height;_updatePosition();}
References AppBaseClass::_updatePosition(), AppBaseClass::height, and AppBaseClass::width.
Referenced by AppAudioToPolyphonic::initMyAppExample().
setName()
void AppBaseClass::setName (const char * name_string) inline inherited
Definition at line 86 of file AppBaseClass.h.
{
       if (strlen(name_string) < MAX_NAME_LENGTH - 1){strcpy(name,name_string);
       } else strncpy(name,name_string,MAX_NAME_LENGTH - 1);
     }
References MAX_NAME_LENGTH, and AppBaseClass::name.
Referenced by AppAudioToPolyphonic::initMyAppExample().
setParent()
void AppBaseClass::setParent (AppBaseClass * parent) inline inherited
Definition at line 91 of file AppBaseClass.h.
 {parentNode = parent;};
References AppBaseClass::parentNode.
Referenced by ControlButton::ControlButton(), ControlSlider::ControlSlider(), and AppAudioToPolyphonic::initMyAppExample().
setPosition()
void AppBaseClass::setPosition (int16_t newOriginX, int16_t newOriginY) inline inherited
Definition at line 92 of file AppBaseClass.h.
 {origin_x=newOriginX;origin_y=newOriginY;_updatePosition();}
References AppBaseClass::_updatePosition(), AppBaseClass::origin_x, and AppBaseClass::origin_y.
Referenced by AppAudioToPolyphonic::initMyAppExample().
setRTPriority()
void AppBaseClass::setRTPriority (uint16_t level) protected inherited
Definition at line 101 of file AppBaseClass.cpp.
{
     updateRT_priority = level;
     return;
 }
References AppBaseClass::updateRT_priority.
setWidgetDimension()
void AppBaseClass::setWidgetDimension (int16_t new_width, int16_t new_height) inline inherited
Definition at line 95 of file AppBaseClass.h.
 {widget_width=new_width;widget_height=new_height;_updatePosition();}
References AppBaseClass::_updatePosition(), AppBaseClass::widget_height, and AppBaseClass::widget_width.
Referenced by AppAudioToPolyphonic::initMyAppExample().
setWidgetPosition()
void AppBaseClass::setWidgetPosition (int16_t newOriginX, int16_t newOriginY) inline inherited
Definition at line 94 of file AppBaseClass.h.
 {widget_origin_x=newOriginX;widget_origin_y=newOriginY;_updatePosition();}
References AppBaseClass::_updatePosition(), AppBaseClass::widget_origin_x, and AppBaseClass::widget_origin_y.
Referenced by AppAudioToPolyphonic::initMyAppExample().
startVM()
void AppWren::startVM () protected
Definition at line 55 of file AppWren.cpp.
                      {
     WrenConfiguration config;
     wrenInitConfiguration(&config);
     config.writeFn = &writeFn;
     config.errorFn = &errorFn;
     config.initialHeapSize = 16000;
     config.minHeapSize = 16000;
     config.heapGrowthPercent = 50;
     vm = wrenNewVM(&config);
 }
References config, errorFn(), vm, wrenInitConfiguration(), wrenNewVM(), and writeFn().
Referenced by restartVM(), and vmConstructor().
update()
void AppWren::update () inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 128 of file AppWren.h.
{
         if (h_update==0){ //if no script loaded
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_update))){
             };
         }
         wrenCollectGarbage(vm);
     };    //called only when the app is active
References h_slot0, h_update, isWrenResultOK(), vm, wrenCall(), wrenCollectGarbage(), wrenEnsureSlots(), and wrenSetSlotHandle().
updateRT()
void AppWren::updateRT () inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 141 of file AppWren.h.
{
         if (h_updateRT==0){ //if no script loaded
             return;
         } else{
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
             if (isWrenResultOK(wrenCall(vm,h_updateRT))){
             };
         }
     }; //allways called even if app is not active
References h_slot0, h_updateRT, isWrenResultOK(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
vmConstructor()
void AppWren::vmConstructor ()
Definition at line 45 of file AppWren.cpp.
{
     Serial.println(F("M AppWren: Starting the VM"));
     startVM();
     loadScript(g_wrenScript);
     getWrenHandles();
     wrenEnsureSlots(vm, 1);
     wrenSetSlotHandle(vm, 0, h_slot0);//App
     isWrenResultOK(wrenCall(vm,h_updateRT));
 }
References F, getWrenHandles(), h_slot0, h_updateRT, isWrenResultOK(), loadScript(), startVM(), vm, wrenCall(), wrenEnsureSlots(), and wrenSetSlotHandle().
Referenced by AppWren().
Member Data Documentation
ad
AudioDirector* AppBaseClass::ad protected inherited
Definition at line 41 of file AppBaseClass.h.
Referenced by AppScope::AppScope(), AppAudioToPolyphonic::changeVoice(), AppCQT::init(), AppAudioToPolyphonic::initMyAppExample(), AppAudioToPolyphonic::makeAudioConnections(), AppAudioToPolyphonic::MessageHandler(), AppAudioToPolyphonic::onAnalog1(), AppAudioToPolyphonic::onAnalog2(), AppAudioToPolyphonic::onAnalog3(), AppAudioToPolyphonic::onAnalog4(), AppAudioToPolyphonic::update(), and SvcSerialCommandInterface::updateRT().
am
AppManager* AppBaseClass::am protected inherited
Definition at line 42 of file AppBaseClass.h.
Referenced by AppCQT::init(), AppAudioToPolyphonic::initMyAppExample(), AppAudioToPolyphonic::onFocus(), AppAudioToPolyphonic::update(), AppScope::update(), ControlButton::update(), ControlSlider::update(), AppCQT::updateOscillatorBank(), AppCQT::updateRT(), AppScope::updateRT(), and SvcSerialCommandInterface::updateRT().
compileOnly
bool AppWren::compileOnly protected
Definition at line 255 of file AppWren.h.
Referenced by AppWren(), and MessageHandler().
cycle_time
uint16_t AppBaseClass::cycle_time protected inherited
Definition at line 61 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
cycle_time_max
uint16_t AppBaseClass::cycle_time_max protected inherited
Definition at line 62 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
draw
ILI9341_t3_ERIS* AppBaseClass::draw protected inherited
Definition at line 45 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppCQT::update(), AppScope::update(), ControlButton::update(), and ControlSlider::update().
h
int16_t AppBaseClass::h inherited
Definition at line 76 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), AppAudioToPolyphonic::onTouch(), AppCQT::onTouch(), AppScope::onTouch(), ControlSlider::onTouch(), AppTemplate::onTouch(), onTouch(), ControlButton::onTouch(), ControlSlider::onTouchRelease(), ControlButton::onTouchRelease(), AppCQT::update(), AppScope::update(), ControlButton::update(), and ControlSlider::update().
h_messageHandler
WrenHandle* AppWren::h_messageHandler private
Definition at line 270 of file AppWren.h.
Referenced by AppWren(), and releaseWrenHandles().
h_onAnalog1
WrenHandle* AppWren::h_onAnalog1 private
Definition at line 266 of file AppWren.h.
Referenced by AppWren(), onAnalog1(), and releaseWrenHandles().
h_onAnalog2
WrenHandle* AppWren::h_onAnalog2 private
Definition at line 267 of file AppWren.h.
Referenced by AppWren(), onAnalog2(), and releaseWrenHandles().
h_onAnalog3
WrenHandle* AppWren::h_onAnalog3 private
Definition at line 268 of file AppWren.h.
Referenced by AppWren(), onAnalog3(), and releaseWrenHandles().
h_onAnalog4
WrenHandle* AppWren::h_onAnalog4 private
Definition at line 269 of file AppWren.h.
Referenced by AppWren(), onAnalog4(), and releaseWrenHandles().
h_onFocus
WrenHandle* AppWren::h_onFocus private
Definition at line 261 of file AppWren.h.
Referenced by AppWren(), onFocus(), and releaseWrenHandles().
h_onFocusLost
WrenHandle* AppWren::h_onFocusLost private
Definition at line 262 of file AppWren.h.
Referenced by AppWren(), onFocusLost(), and releaseWrenHandles().
h_onTouch
WrenHandle* AppWren::h_onTouch private
Definition at line 263 of file AppWren.h.
Referenced by AppWren(), onTouch(), and releaseWrenHandles().
h_onTouchDrag
WrenHandle* AppWren::h_onTouchDrag private
Definition at line 264 of file AppWren.h.
Referenced by AppWren(), onTouchDrag(), and releaseWrenHandles().
h_onTouchRelease
WrenHandle* AppWren::h_onTouchRelease private
Definition at line 265 of file AppWren.h.
Referenced by AppWren(), onTouchRelease(), and releaseWrenHandles().
h_slot0
WrenHandle* AppWren::h_slot0 private
Definition at line 258 of file AppWren.h.
Referenced by AppWren(), getWrenHandles(), MessageHandler(), onAnalog1(), onAnalog2(), onAnalog3(), onAnalog4(), onFocus(), onFocusLost(), onTouch(), onTouchDrag(), onTouchRelease(), releaseWrenHandles(), update(), updateRT(), and vmConstructor().
h_update
WrenHandle* AppWren::h_update private
Definition at line 259 of file AppWren.h.
Referenced by AppWren(), getWrenHandles(), releaseWrenHandles(), and update().
h_updateRT
WrenHandle* AppWren::h_updateRT private
Definition at line 260 of file AppWren.h.
Referenced by AppWren(), getWrenHandles(), releaseWrenHandles(), updateRT(), and vmConstructor().
has_focus
bool AppBaseClass::has_focus protected inherited
Definition at line 111 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), AppBaseClass::getFocus(), and AppBaseClass::returnFocus().
has_pop
bool AppBaseClass::has_pop protected inherited
Definition at line 112 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), AppCQT::onTouch(), AppScope::onTouch(), AppBaseClass::releasePopUp(), AppBaseClass::requestPopUp(), and AppCQT::update().
height
int16_t AppBaseClass::height inherited
Definition at line 71 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setDimension().
id
uint16_t AppBaseClass::id protected inherited
Definition at line 50 of file AppBaseClass.h.
Referenced by AppBaseClass::getId().
name
char AppBaseClass::name[MAX_NAME_LENGTH] inherited
Definition at line 77 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppReprogram::AppReprogram(), AppScope::AppScope(), AppWren(), ControlButton::ControlButton(), ControlSlider::ControlSlider(), SvcSerialCommandInterface::SvcSerialCommandInterface(), cpplint._ClassInfo::CheckEnd(), cpplint._NamespaceInfo::CheckEnd(), AppCQT::init(), AppAudioToPolyphonic::initMyAppExample(), AppBaseClass::isName(), and AppBaseClass::setName().
nextAppicationNode
AppBaseClass* AppBaseClass::nextAppicationNode protected inherited
Definition at line 48 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
origin_x
int16_t AppBaseClass::origin_x inherited
Definition at line 68 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setPosition().
origin_y
int16_t AppBaseClass::origin_y inherited
Definition at line 69 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setPosition().
parentNode
AppBaseClass* AppBaseClass::parentNode protected inherited
Definition at line 46 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), ControlSlider::onTouchDrag(), ControlSlider::onTouchRelease(), ControlButton::onTouchRelease(), and AppBaseClass::setParent().
previousAppicationNode
AppBaseClass* AppBaseClass::previousAppicationNode protected inherited
Definition at line 47 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
sci
SvcSerialCommandInterface* AppBaseClass::sci protected inherited
Definition at line 43 of file AppBaseClass.h.
Referenced by AppCQT::MessageHandler(), and AppCQT::update().
sd
SdFs* AppBaseClass::sd protected inherited
Definition at line 44 of file AppBaseClass.h.
Referenced by SvcSerialCommandInterface::updateRT().
touch_state
bool AppBaseClass::touch_state protected inherited
Definition at line 49 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
update_call_period
elapsedMicros AppBaseClass::update_call_period protected inherited
Definition at line 63 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
update_call_period_max
uint16_t AppBaseClass::update_call_period_max protected inherited
Definition at line 64 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
update_loop_time
uint16_t AppBaseClass::update_loop_time protected inherited
Definition at line 57 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
update_loop_time_max
uint16_t AppBaseClass::update_loop_time_max protected inherited
Definition at line 58 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
updateRT_call_period
elapsedMicros AppBaseClass::updateRT_call_period protected inherited
Definition at line 65 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
updateRT_call_period_max
uint16_t AppBaseClass::updateRT_call_period_max protected inherited
Definition at line 66 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
updateRT_loop_time
uint16_t AppBaseClass::updateRT_loop_time protected inherited
Definition at line 59 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
updateRT_loop_time_max
uint16_t AppBaseClass::updateRT_loop_time_max protected inherited
Definition at line 60 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass().
updateRT_priority
uint16_t AppBaseClass::updateRT_priority protected inherited
Definition at line 56 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::setRTPriority(), AppBaseClass::updateRT(), AppCQT::updateRT(), and AppReprogram::updateRT().
vm
WrenVM* AppWren::vm private
Definition at line 257 of file AppWren.h.
Referenced by AppWren(), ~AppWren(), getWrenHandles(), loadScript(), MessageHandler(), onAnalog1(), onAnalog2(), onAnalog3(), onAnalog4(), onFocus(), onFocusLost(), onTouch(), onTouchDrag(), onTouchRelease(), releaseWrenHandles(), restartVM(), startVM(), update(), updateRT(), and vmConstructor().
w
int16_t AppBaseClass::w inherited
Definition at line 76 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), AppAudioToPolyphonic::changeVoice(), AppAudioToPolyphonic::onTouch(), AppCQT::onTouch(), AppScope::onTouch(), ControlSlider::onTouch(), AppTemplate::onTouch(), onTouch(), ControlButton::onTouch(), ControlSlider::onTouchRelease(), ControlButton::onTouchRelease(), AppCQT::update(), AppScope::update(), ControlButton::update(), and ControlSlider::update().
widget_height
int16_t AppBaseClass::widget_height inherited
Definition at line 75 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setWidgetDimension().
widget_origin_x
int16_t AppBaseClass::widget_origin_x inherited
Definition at line 72 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setWidgetPosition().
widget_origin_y
int16_t AppBaseClass::widget_origin_y inherited
Definition at line 73 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setWidgetPosition().
widget_width
int16_t AppBaseClass::widget_width inherited
Definition at line 74 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setWidgetDimension().
width
int16_t AppBaseClass::width inherited
Definition at line 70 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), and AppBaseClass::setDimension().
x
int16_t AppBaseClass::x inherited
Definition at line 76 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), AppAudioToPolyphonic::onTouch(), AppCQT::onTouch(), AppScope::onTouch(), ControlSlider::onTouch(), AppTemplate::onTouch(), onTouch(), ControlButton::onTouch(), ControlSlider::onTouchRelease(), ControlButton::onTouchRelease(), AppCQT::update(), AppScope::update(), ControlButton::update(), and ControlSlider::update().
y
int16_t AppBaseClass::y inherited
Definition at line 76 of file AppBaseClass.h.
Referenced by AppBaseClass::AppBaseClass(), AppBaseClass::_updatePosition(), AppAudioToPolyphonic::onTouch(), AppCQT::onTouch(), AppScope::onTouch(), ControlSlider::onTouch(), AppTemplate::onTouch(), onTouch(), ControlButton::onTouch(), ControlSlider::onTouchRelease(), ControlButton::onTouchRelease(), AppCQT::update(), AppScope::update(), ControlButton::update(), and ControlSlider::update().
The documentation for this class was generated from the following files:
AppWren.h
AppWren.cpp