ERIS CORE: AppWren::bltSurface2FrameBuffer
bltSurface2FrameBuffer()
void AppWren::bltSurface2FrameBuffer (int16_t from_x, int16_t from_y, int16_t width, int16_t height, int16_t to_x, int16_t to_y, bltAlphaType alpha_type) inline
Definition at line 282 of file AppWren.h.
{
         dynamicSurfaceManager();
         uint16_t *sb = surface_cache->getSurfaceBufferP();
         Surface source((uint16_t*)(sb + from_x + (from_y * surface_cache->getWidth())),width,height);
         Surface dest(draw->getFrameBuffer(),320,240);
         //bltMem(Surface *dest, Surface *source,int16_t pos_x,int16_t pos_y,bltAlphaType alpha_type)
         draw->bltMem(&dest,&source,to_x,to_y,AT_NONE);
     }
References AT_NONE, ILI9341_t3_ERIS::bltMem(), draw(), dynamicSurfaceManager(), Surface::getSurfaceBufferP(), Surface::getWidth(), and surface_cache.
Referenced by bltCallback().