ERIS CORE: AppWren::loadScript
loadScript()
bool AppWren::loadScript (const char * script) inline
runs the script in the VM
Parameters
script
Returns
true wrenInterpret result is ok
false wrenInterpret result is not ok
Definition at line 140 of file AppWren.h.
{
         const char* module = "main";
         bool res;
         res = isWrenResultOK(wrenInterpret(vm, module, script));
         if(res){
             getWrenHandles();
             wrenEnsureSlots(vm, 1);
             wrenSetSlotHandle(vm, 0, h_slot0);//App
         }
         if(sci->requestStartLZ4Message()){
             sci->printf("M AppWren:loadScript: Loading script (size: %d bytes)\n",strlen(script));
             if (res){
                 sci->println(F("M AppWren::loadScript: OK"));
             }else sci->println(F("M AppWren::loadScript: NOT OK"));
             sci->sendLZ4Message();
         }
         return res;
     }
References getWrenHandles(), h_slot0, isWrenResultOK(), SvcSerialCommandInterface::requestStartLZ4Message(), AppBaseClass::sci, SvcSerialCommandInterface::sendLZ4Message(), and vm.
Referenced by messageHandler(), render(), and vmConstructor().