ERIS CORE: ILI9341_t3_ERIS::bltMem
bltMem()
void FLASHMEM ILI9341_t3_ERIS::bltMem (Surface * dest, Surface * source, int16_t x, int16_t y, bltAlphaType alpha_type)
Definition at line 99 of file ILI9341_t3_ERIS.cpp.
{
   bool toggle = false;
   int16_t source_x,source_y, dest_x,dest_y;
   uint32_t read_index,write_index;
   uint16_t *srcBuffer;
   uint16_t *dstBuffer;
   srcBuffer = source->getSurfaceBufferP();
   dstBuffer = dest->getSurfaceBufferP();
   //check for null
   if (!srcBuffer) return;
   if (!dstBuffer) return;
   //check for off surface blt attempt
   if ((pos_x > dest->getWidth()) || (0 > (dest->getWidth() + pos_x))) return;
   if ((pos_y > dest->getHeight()) || (0 > (dest->getHeight() + pos_y))) return;
   //for each pixel in the source buffer, write to the dest buffer if the x,y coords are within bounds
   for (source_y=0; source_y < source->getHeight();source_y +=1){
     for (source_x=0; source_x < source->getWidth();source_x +=1){
       //translate the source coords to the destination coords
       dest_x = pos_x + source_x;
       dest_y = pos_y + source_y;
       write_index = (dest_y * dest->getWidth()) + dest_x;
       read_index = (source_y * source->getWidth()) + source_x;
       if(dest_x < 320 && dest_x >= 0 && dest_y < 240 && dest_y >= 0){
         //if in bounds then ok to write
         if (AT_NONE == alpha_type){
           dstBuffer[write_index] = srcBuffer[read_index];
         }else if(AT_HATCHXOR){
           if (toggle) dstBuffer[write_index] = srcBuffer[read_index];
           toggle ^= true;
         }else if(AT_TRANS){
           //TODO: unpack both source and dest, average the rgb values, repack and store in dest
         }
       }
     }
   }
 }
References AT_HATCHXOR, AT_NONE, AT_TRANS, Surface::getHeight(), Surface::getSurfaceBufferP(), and Surface::getWidth().
Referenced by AppWren::update(), and ControlButton::update().