ERIS CORE: ILI9341_t3_ERIS::bltSD
bltSD() [2/2]
void FLASHMEM ILI9341_t3_ERIS::bltSD (uint16_t * dest_buffer, uint16_t dest_buffer_width, const char * path, const char * filename, int16_t x, int16_t y, bltAlphaType alpha_type)
Definition at line 199 of file ILI9341_t3_ERIS.cpp.
{
   int16_t iy; // x & y index
   int16_t w;int16_t h; //width & height
   int16_t mx;        //left clip x offset
   int16_t nx;        //right clip x offset
   unsigned long ifb; //frame buffer index
   //uint16_t dwbf[320];//file read pixel row input buffer
   uint16_t dw;       //pixel data
   char str[16];      //char buffer
   char *c;           //char pointer
   bool toggle = false;
   //pSD->chdir();
   if (!pSD->chdir(path)){ //change file path
     Serial.print(F("M ILI9341_t3_ERIS::bltSD Path not found: "));
     Serial.println(path);
     return;
   }
   file.open(filename, O_READ);        //open image to read
   if (file.available() == 0){ //file not found
     Serial.print(F("M ILI9341_t3_ERIS::bltSD File Not Found: "));
     Serial.println(filename);
     //pSD->ls();
     return;
   }
   file.fgets(str,sizeof(str)); //read the header data
   file.fgets(str,sizeof(str)); //to get the image dimensions
   strtok(str," ");             //convert dimension text to numbers
   w = atol(str);
   c = strtok(NULL, " ");
   h = atol(c);
   //clip in y dimension (top)
   if (y<0) { //throw away rows which are off screen
     for (iy = 0; iy < -1L * y; iy += 1L){ //for each off screen row
       file.seekCur(w*2L);
       h -= 1; //reduce bitmap hight by 1 row
     }
     y = 0; //set y pos to 0 for the remaining portion of the bitmap
   }
   for (iy = y; iy < y + h; iy += 1){ //for each row
     toggle ^= true;
     if (iy < 240L) //clip in y dimension (bottom) - simply don't draw anything
     {
       mx = 0; nx = 0;
       if (x < 0L){file.seekCur(x * -2L);mx = -1L * x;} //clip in x dimension (left) - skip offscreen data
       ifb = (iy * dest_buffer_width) + x + mx; //32bit index
       if (x + w > dest_buffer_width){nx = x + w - dest_buffer_width;}//clip in x dimension (right) - truncate copy to screen bounds
       for (uint16_t z = 0; z < (w - mx - nx); z += 1){
         file.read(&dw,2);
         toggle ^= true;
         //if alpha is enabled mask any colors close to black
         if (alpha_type == AT_NONE){dest_buffer[ifb + z] = dw;}
         else if (alpha_type == AT_TRANS && (dw & 0xE79C) != 0){dest_buffer[ifb + z] = dw;}
         else if (alpha_type == AT_HATCHBLK){
           if ((dw & 0xE79C) != 0) dest_buffer[ifb + z] = dw;
           else if (toggle) dest_buffer[ifb + z] = 0; //pFB[i] ^= pFB[i];
         }
         else if (alpha_type == AT_HATCHXOR){
           if ((dw & 0xE79C) != 0) dest_buffer[ifb + z] = dw;
           else if (toggle) dest_buffer[ifb + z] = dest_buffer[ifb + z]^dest_buffer[ifb + z];
         }
       }
       if (x + w > dest_buffer_width){file.seekCur( (x + w - dest_buffer_width) * 2);} //clip in x dimension (right) - skip unused data
     }
     else{
       //since y index is now off screen close the file and return
       file.close();
       return;
     }
   }
   file.close();
 }
References AT_HATCHBLK, AT_HATCHXOR, AT_NONE, AT_TRANS, file, and pSD.
Referenced by bltSD(), loadImageCallback(), and ControlButton::update().