ERIS CORE: FsDateTime.h File Reference
FsDateTime.h File Reference
#include <stdint.h>
#include "CompileDateTime.h"
#include "SysCall.h"
Namespaces
FsDateTime
Macros
#define FAT_DATE(y, m, d) FS_DATE(y, m, d)
#define FAT_TIME(h, m, s) FS_TIME(h, m, s)
Functions
void FsDateTime::clearCallback ()
static uint16_t FS_DATE (uint16_t year, uint8_t month, uint8_t day)
static uint8_t FS_DAY (uint16_t fatDate)
static uint8_t FS_HOUR (uint16_t fatTime)
static uint8_t FS_MINUTE (uint16_t fatTime)
static uint8_t FS_MONTH (uint16_t fatDate)
static uint8_t FS_SECOND (uint16_t fatTime)
static uint16_t FS_TIME (uint8_t hour, uint8_t minute, uint8_t second)
static uint16_t FS_YEAR (uint16_t fatDate)
char * fsFmtDate (char *str, uint16_t date)
char * fsFmtTime (char *str, uint16_t time)
char * fsFmtTime (char *str, uint16_t time, uint8_t sec100)
char * fsFmtTimeZone (char *str, int8_t tz)
size_t fsPrintDate (print_t *pr, uint16_t date)
size_t fsPrintDateTime (print_t *pr, uint16_t date, uint16_t time)
size_t fsPrintDateTime (print_t *pr, uint32_t dateTime)
size_t fsPrintDateTime (print_t *pr, uint32_t dateTime, uint8_t s100, int8_t tz)
size_t fsPrintTime (print_t *pr, uint16_t time)
size_t fsPrintTime (print_t *pr, uint16_t time, uint8_t sec100)
size_t fsPrintTimeZone (print_t *pr, int8_t tz)
void FsDateTime::setCallback (void(*dateTime)(uint16_t *date, uint16_t *time))
void FsDateTime::setCallback (void(*dateTime)(uint16_t *date, uint16_t *time, uint8_t *ms10))
Macro Definition Documentation
FAT_DATE
#define FAT_DATE (y, m, d) FS_DATE(y, m, d)
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. Backward compatible definition.
Definition at line 32 of file FsDateTime.h.
FAT_TIME
#define FAT_TIME (h, m, s) FS_TIME(h, m, s)
Backward compatible definition.
Definition at line 35 of file FsDateTime.h.
Function Documentation
FS_DATE()
static uint16_t FS_DATE (uint16_t year, uint8_t month, uint8_t day) inline static
date field for directory entry
Parameters
[in] year [1980,2107]
[in] month [1,12]
[in] day [1,31]
Returns
Packed date for directory entry.
Definition at line 116 of file FsDateTime.h.
{
   year -= 1980;
   return year > 127 || month > 12 || day > 31 ? 0 :
          year << 9 | month << 5 | day;
 }
Referenced by ExFatFile::timestamp(), and FatFile::timestamp().
FS_DAY()
static uint8_t FS_DAY (uint16_t fatDate) inline static
day part of FAT directory date field
Parameters
[in] fatDate Date in packed dir format.
Returns
Extracted day [1,31]
Definition at line 142 of file FsDateTime.h.
{
   return fatDate & 0X1F;
 }
FS_HOUR()
static uint8_t FS_HOUR (uint16_t fatTime) inline static
hour part of FAT directory time field
Parameters
[in] fatTime Time in packed dir format.
Returns
Extracted hour [0,23]
Definition at line 161 of file FsDateTime.h.
{
   return fatTime >> 11;
 }
FS_MINUTE()
static uint8_t FS_MINUTE (uint16_t fatTime) inline static
minute part of FAT directory time field
Parameters
[in] fatTime Time in packed dir format.
Returns
Extracted minute [0,59]
Definition at line 169 of file FsDateTime.h.
{
   return (fatTime >> 5) & 0X3F;
 }
FS_MONTH()
static uint8_t FS_MONTH (uint16_t fatDate) inline static
month part of FAT directory date field
Parameters
[in] fatDate Date in packed dir format.
Returns
Extracted month [1,12]
Definition at line 134 of file FsDateTime.h.
{
   return (fatDate >> 5) & 0XF;
 }
FS_SECOND()
static uint8_t FS_SECOND (uint16_t fatTime) inline static
second part of FAT directory time field N
Note
second/2 is stored in packed time.
Parameters
[in] fatTime Time in packed dir format.
Returns
Extracted second [0,58]
Definition at line 179 of file FsDateTime.h.
{
   return 2*(fatTime & 0X1F);
 }
FS_TIME()
static uint16_t FS_TIME (uint8_t hour, uint8_t minute, uint8_t second) inline static
time field for directory entry
Parameters
[in] hour [0,23]
[in] minute [0,59]
[in] second [0,59]
Returns
Packed time for directory entry.
Definition at line 152 of file FsDateTime.h.
{
   return hour > 23 || minute > 59 || second > 59 ? 0 :
          hour << 11 | minute << 5 | second >> 1;
 }
References second.
Referenced by ExFatFile::timestamp(), and FatFile::timestamp().
FS_YEAR()
static uint16_t FS_YEAR (uint16_t fatDate) inline static
year part of FAT directory date field
Parameters
[in] fatDate Date in packed dir format.
Returns
Extracted year [1980,2107]
Definition at line 126 of file FsDateTime.h.
{
   return 1980 + (fatDate >> 9);
 }
fsFmtDate()
char* fsFmtDate (char * str, uint16_t date)
Definition at line 62 of file FsDateTime.cpp.
{
   str = fsFmtField(str, date & 31, 0);
   date >>= 5;
   str = fsFmtField(str, date & 15, '-');
   date >>= 4;
   return fsFmtField(str, 1980 + date, '-');
 }
References fsFmtField().
Referenced by fsPrintDate(), and fsPrintDateTime().
fsFmtTime() [1/2]
char* fsFmtTime (char * str, uint16_t time)
Definition at line 70 of file FsDateTime.cpp.
{
   time >>= 5;
   str = fsFmtField(str, time & 63, 0);
   return fsFmtField(str, time >> 6, ':');
 }
References fsFmtField().
Referenced by fsFmtTime(), fsPrintDateTime(), and fsPrintTime().
fsFmtTime() [2/2]
char* fsFmtTime (char * str, uint16_t time, uint8_t sec100)
Definition at line 76 of file FsDateTime.cpp.
{
   str = fsFmtField(str, 2*(time & 31) + (sec100 < 100 ? 0 : 1), 0);
   *--str = ':';
   return fsFmtTime(str, time);
 }
References fsFmtField(), and fsFmtTime().
fsFmtTimeZone()
char* fsFmtTimeZone (char * str, int8_t tz)
Definition at line 82 of file FsDateTime.cpp.
{
   char sign;
   if (tz & 0X80) {
     if (tz & 0X40) {
       sign = '-';
       tz = -tz;
     } else {
       sign = '+';
       tz &= 0X7F;
     }
     if (tz) {
       str = fsFmtField(str, 15*(tz%4), 0);
       str = fsFmtField(str, tz/4, ':');
       *--str = sign;
     }
     *--str = 'C';
     *--str = 'T';
     *--str = 'U';
   }
   return str;
 }
References fsFmtField().
Referenced by fsPrintDateTime(), and fsPrintTimeZone().
fsPrintDate()
size_t fsPrintDate (print_t * pr, uint16_t date)
Definition at line 104 of file FsDateTime.cpp.
{
   // Allow YYYY-MM-DD
   char buf[sizeof("YYYY-MM-DD") -1];
   char* str = buf + sizeof(buf);
   if (date) {
     str = fsFmtDate(str, date);
   } else {
      do {
       *--str = ' ';
     } while (str > buf);
   }
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtDate(), and PrintBasic::write().
Referenced by FatFile::printAccessDate().
fsPrintDateTime() [1/3]
size_t fsPrintDateTime (print_t * pr, uint16_t date, uint16_t time)
Definition at line 118 of file FsDateTime.cpp.
{
   // Allow YYYY-MM-DD hh:mm
   char buf[sizeof("YYYY-MM-DD hh:mm") -1];
   char* str = buf + sizeof(buf);
   if (date) {
     str = fsFmtTime(str, time);
     *--str = ' ';
     str = fsFmtDate(str, date);
   } else {
     do {
       *--str = ' ';
     } while (str > buf);
   }
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtDate(), fsFmtTime(), and PrintBasic::write().
Referenced by fsPrintDateTime(), ExFatFile::printAccessDateTime(), ExFatFile::printCreateDateTime(), FatFile::printCreateDateTime(), printDateTime(), ExFatFile::printModifyDateTime(), and FatFile::printModifyDateTime().
fsPrintDateTime() [2/3]
size_t fsPrintDateTime (print_t * pr, uint32_t dateTime)
Definition at line 134 of file FsDateTime.cpp.
{
   return fsPrintDateTime(pr, dateTime >> 16, dateTime & 0XFFFF);
 }
References fsPrintDateTime().
fsPrintDateTime() [3/3]
size_t fsPrintDateTime (print_t * pr, uint32_t dateTime, uint8_t s100, int8_t tz)
Definition at line 138 of file FsDateTime.cpp.
{
   // Allow YYYY-MM-DD hh:mm:ss UTC+hh:mm
   char buf[sizeof("YYYY-MM-DD hh:mm:ss UTC+hh:mm") -1];
   char* str = buf + sizeof(buf);
   if (tz) {
     str = fsFmtTimeZone(str, tz);
     *--str = ' ';
   }
   str = fsFmtTime(str, (uint16_t)dateTime, s100);
   *--str = ' ';
   str = fsFmtDate(str, (uint16_t)(dateTime >> 16));
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtDate(), fsFmtTime(), fsFmtTimeZone(), and PrintBasic::write().
fsPrintTime() [1/2]
size_t fsPrintTime (print_t * pr, uint16_t time)
Definition at line 153 of file FsDateTime.cpp.
{
   // Allow hh:mm
   char buf[sizeof("hh:mm") -1];
   char* str = buf + sizeof(buf);
   str = fsFmtTime(str, time);
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtTime(), and PrintBasic::write().
fsPrintTime() [2/2]
size_t fsPrintTime (print_t * pr, uint16_t time, uint8_t sec100)
Definition at line 161 of file FsDateTime.cpp.
{
   // Allow hh:mm:ss
   char buf[sizeof("hh:mm:ss") -1];
   char* str = buf + sizeof(buf);
   str = fsFmtTime(str, time, sec100);
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtTime(), and PrintBasic::write().
fsPrintTimeZone()
size_t fsPrintTimeZone (print_t * pr, int8_t tz)
Definition at line 169 of file FsDateTime.cpp.
{
   // Allow UTC+hh:mm
   char buf[sizeof("UTC+hh:mm") -1];
   char* str = buf + sizeof(buf);
   str = fsFmtTimeZone(str, tz);
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtTimeZone(), and PrintBasic::write().