ERIS CORE: AudioMixer8::update
update()
void AudioMixer8::update (void) virtual
Implements AudioStream.
Reimplemented in erisAudioMixer8.
Definition at line 49 of file eris_mixer_ext.cpp.
 {
     audio_block_t *in, *out=NULL;
     unsigned int channel;
     for (channel=0; channel < 8; channel++) {
         if (!out) {
             out = receiveWritable(channel);
             if (out) {
                 int32_t mult = multiplier[channel];
                 if (mult != 65536) applyGain2(out->data, mult);
             }
         } else {
             in = receiveReadOnly(channel);
             if (in) {
                 applyGainThenAdd2(out->data, in->data, multiplier[channel]);
                 release(in);
             }
         }
     }
     if (out) {
         transmit(out);
         release(out);
     }
 }
References applyGain2(), applyGainThenAdd2(), audio_block_struct::data, multiplier, AudioStream::receiveReadOnly(), AudioStream::receiveWritable(), AudioStream::release(), and AudioStream::transmit().
Referenced by erisAudioMixer8::update().