ERIS CORE: wren_compiler.c File Reference
wren_compiler.c File Reference
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "wren_common.h"
#include "wren_compiler.h"
#include "wren_vm.h"
#include "wren_opcodes.h"
Macros
#define ERROR_MESSAGE_SIZE (80 + MAX_VARIABLE_NAME + 15)
#define INFIX(prec, fn) { NULL, fn, NULL, prec, NULL }
#define INFIX_OPERATOR(prec, name) { NULL, infixOp, infixSignature, prec, name }
#define MAX_CONSTANTS (1 << 16)
#define MAX_INTERPOLATION_NESTING 8
#define MAX_JUMP (1 << 16)
#define MAX_LOCALS 256
#define MAX_UPVALUES 256
#define OPCODE(_, effect) effect,
#define OPERATOR(name) { unaryOp, infixOp, mixedSignature, PREC_TERM, name }
#define PREFIX(fn) { fn, NULL, NULL, PREC_NONE, NULL }
#define PREFIX_OPERATOR(name) { unaryOp, NULL, unarySignature, PREC_NONE, name }
#define UNUSED { NULL, NULL, NULL, PREC_NONE, NULL }
Typedefs
typedef void(* GrammarFn) (Compiler *, bool canAssign)
typedef struct sLoop Loop
typedef void(* SignatureFn) (Compiler *compiler, Signature *signature)
Enumerations
enum Precedence {
PREC_NONE , PREC_LOWEST , PREC_ASSIGNMENT , PREC_CONDITIONAL ,
PREC_LOGICAL_OR , PREC_LOGICAL_AND , PREC_EQUALITY , PREC_IS ,
PREC_COMPARISON , PREC_BITWISE_OR , PREC_BITWISE_XOR , PREC_BITWISE_AND ,
PREC_BITWISE_SHIFT , PREC_RANGE , PREC_TERM , PREC_FACTOR ,
PREC_UNARY , PREC_CALL , PREC_PRIMARY
}
enum Scope { SCOPE_LOCAL , SCOPE_UPVALUE , SCOPE_MODULE }
enum SignatureType {
SIG_METHOD , SIG_GETTER , SIG_SETTER , SIG_SUBSCRIPT ,
SIG_SUBSCRIPT_SETTER , SIG_INITIALIZER
}
enum TokenType {
TOKEN_LEFT_PAREN , TOKEN_RIGHT_PAREN , TOKEN_LEFT_BRACKET , TOKEN_RIGHT_BRACKET ,
TOKEN_LEFT_BRACE , TOKEN_RIGHT_BRACE , TOKEN_COLON , TOKEN_DOT ,
TOKEN_DOTDOT , TOKEN_DOTDOTDOT , TOKEN_COMMA , TOKEN_STAR ,
TOKEN_SLASH , TOKEN_PERCENT , TOKEN_HASH , TOKEN_PLUS ,
TOKEN_MINUS , TOKEN_LTLT , TOKEN_GTGT , TOKEN_PIPE ,
TOKEN_PIPEPIPE , TOKEN_CARET , TOKEN_AMP , TOKEN_AMPAMP ,
TOKEN_BANG , TOKEN_TILDE , TOKEN_QUESTION , TOKEN_EQ ,
TOKEN_LT , TOKEN_GT , TOKEN_LTEQ , TOKEN_GTEQ ,
TOKEN_EQEQ , TOKEN_BANGEQ , TOKEN_BREAK , TOKEN_CONTINUE ,
TOKEN_CLASS , TOKEN_CONSTRUCT , TOKEN_ELSE , TOKEN_FALSE ,
TOKEN_FOR , TOKEN_FOREIGN , TOKEN_IF , TOKEN_IMPORT ,
TOKEN_AS , TOKEN_IN , TOKEN_IS , TOKEN_NULL ,
TOKEN_RETURN , TOKEN_STATIC , TOKEN_SUPER , TOKEN_THIS ,
TOKEN_TRUE , TOKEN_VAR , TOKEN_WHILE , TOKEN_FIELD ,
TOKEN_STATIC_FIELD , TOKEN_NAME , TOKEN_NUMBER , TOKEN_STRING ,
TOKEN_INTERPOLATION , TOKEN_LINE , TOKEN_ERROR , TOKEN_EOF
}
Functions
static int addConstant (Compiler *compiler, Value constant)
static int addLocal (Compiler *compiler, const char *name, int length)
static void addToAttributeGroup (Compiler *compiler, Value group, Value key, Value value)
static int addUpvalue (Compiler *compiler, bool isLocal, int index)
static void allowLineBeforeDot (Compiler *compiler)
static void and_ (Compiler *compiler, bool canAssign)
static void bareName (Compiler *compiler, bool canAssign, Variable variable)
static void boolean (Compiler *compiler, bool canAssign)
static void call (Compiler *compiler, bool canAssign)
static void callMethod (Compiler *compiler, int numArgs, const char *name, int length)
static void callSignature (Compiler *compiler, Code instruction, Signature *signature)
static void classDefinition (Compiler *compiler, bool isForeign)
static void conditional (Compiler *compiler, bool canAssign)
void constructorSignature (Compiler *compiler, Signature *signature)
static void consume (Compiler *compiler, TokenType expected, const char *errorMessage)
static void consumeLine (Compiler *compiler, const char *errorMessage)
static Value consumeLiteral (Compiler *compiler, const char *message)
static void copyAttributes (Compiler *compiler, ObjMap *into)
static void copyMethodAttributes (Compiler *compiler, bool isForeign, bool isStatic, const char *fullSignature, int32_t length)
static void createConstructor (Compiler *compiler, Signature *signature, int initializerSymbol)
static int declareMethod (Compiler *compiler, Signature *signature, const char *name, int length)
static int declareNamedVariable (Compiler *compiler)
static int declareVariable (Compiler *compiler, Token *token)
static void defineMethod (Compiler *compiler, Variable classVariable, bool isStatic, int methodSymbol)
static void defineVariable (Compiler *compiler, int symbol)
static void definition (Compiler *compiler)
static void disallowAttributes (Compiler *compiler)
static int discardLocals (Compiler *compiler, int depth)
static void emitAttributeMethods (Compiler *compiler, ObjMap *attributes)
static void emitAttributes (Compiler *compiler, ObjMap *attributes)
static int emitByte (Compiler *compiler, int byte)
static int emitByteArg (Compiler *compiler, Code instruction, int arg)
static void emitClassAttributes (Compiler *compiler, ClassInfo *classInfo)
static void emitConstant (Compiler *compiler, Value value)
static int emitJump (Compiler *compiler, Code instruction)
static void emitOp (Compiler *compiler, Code instruction)
static void emitShort (Compiler *compiler, int arg)
static void emitShortArg (Compiler *compiler, Code instruction, int arg)
static ObjFn * endCompiler (Compiler *compiler, const char *debugName, int debugNameLength)
static void endLoop (Compiler *compiler)
static void error (Compiler *compiler, const char *format,...)
static void expression (Compiler *compiler)
static void field (Compiler *compiler, bool canAssign)
static int findUpvalue (Compiler *compiler, const char *name, int length)
static void finishArgumentList (Compiler *compiler, Signature *signature)
static bool finishBlock (Compiler *compiler)
static void finishBody (Compiler *compiler)
static void finishParameterList (Compiler *compiler, Signature *signature)
static void forStatement (Compiler *compiler)
static int getByteCountForArguments (const uint8_t *bytecode, const Value *constants, int ip)
static ClassInfo * getEnclosingClass (Compiler *compiler)
static Compiler * getEnclosingClassCompiler (Compiler *compiler)
static GrammarRule * getRule (TokenType type)
static void grouping (Compiler *compiler, bool canAssign)
static void ifStatement (Compiler *compiler)
static void ignoreNewlines (Compiler *compiler)
static void import (Compiler *compiler)
void infixOp (Compiler *compiler, bool canAssign)
void infixSignature (Compiler *compiler, Signature *signature)
static void initCompiler (Compiler *compiler, Parser *parser, Compiler *parent, bool isMethod)
static bool isDigit (char c)
static bool isName (char c)
static void lexError (Parser *parser, const char *format,...)
static void list (Compiler *compiler, bool canAssign)
static void literal (Compiler *compiler, bool canAssign)
static void loadCoreVariable (Compiler *compiler, const char *name)
static void loadLocal (Compiler *compiler, int slot)
static void loadThis (Compiler *compiler)
static void loadVariable (Compiler *compiler, Variable variable)
static void loopBody (Compiler *compiler)
static void makeNumber (Parser *parser, bool isHex)
static void makeToken (Parser *parser, TokenType type)
static void map (Compiler *compiler, bool canAssign)
static bool match (Compiler *compiler, TokenType expected)
static bool matchAttribute (Compiler *compiler)
static bool matchChar (Parser *parser, char c)
static bool matchLine (Compiler *compiler)
static bool maybeSetter (Compiler *compiler, Signature *signature)
static bool method (Compiler *compiler, Variable classVariable)
static void methodCall (Compiler *compiler, Code instruction, Signature *signature)
static int methodSymbol (Compiler *compiler, const char *name, int length)
void mixedSignature (Compiler *compiler, Signature *signature)
static void name (Compiler *compiler, bool canAssign)
static void namedCall (Compiler *compiler, bool canAssign, Code instruction)
void namedSignature (Compiler *compiler, Signature *signature)
static char nextChar (Parser *parser)
static void nextToken (Parser *parser)
static void null (Compiler *compiler, bool canAssign)
static void or_ (Compiler *compiler, bool canAssign)
static void parameterList (Compiler *compiler, Signature *signature)
static void parsePrecedence (Compiler *compiler, Precedence precedence)
static void patchJump (Compiler *compiler, int offset)
static TokenType peek (Compiler *compiler)
static char peekChar (Parser *parser)
static TokenType peekNext (Compiler *compiler)
static char peekNextChar (Parser *parser)
static void popScope (Compiler *compiler)
static void printError (Parser *parser, int line, const char *label, const char *format, va_list args)
static void pushScope (Compiler *compiler)
static int readHexDigit (Parser *parser)
static int readHexEscape (Parser *parser, int digits, const char *description)
static void readHexNumber (Parser *parser)
static void readName (Parser *parser, TokenType type, char firstChar)
static void readNumber (Parser *parser)
static void readRawString (Parser *parser)
static void readString (Parser *parser)
static void readUnicodeEscape (Parser *parser, ByteBuffer *string, int length)
static int resolveLocal (Compiler *compiler, const char *name, int length)
static Variable resolveName (Compiler *compiler, const char *name, int length)
static Variable resolveNonmodule (Compiler *compiler, const char *name, int length)
static Signature signatureFromToken (Compiler *compiler, SignatureType type)
static void signatureParameterList (char name[MAX_METHOD_SIGNATURE], int *length, int numParams, char leftBracket, char rightBracket)
static int signatureSymbol (Compiler *compiler, Signature *signature)
static void signatureToString (Signature *signature, char name[MAX_METHOD_SIGNATURE], int *length)
static void skipBlockComment (Parser *parser)
static void skipLineComment (Parser *parser)
static void startLoop (Compiler *compiler, Loop *loop)
static void statement (Compiler *compiler)
static void staticField (Compiler *compiler, bool canAssign)
static void stringInterpolation (Compiler *compiler, bool canAssign)
static void subscript (Compiler *compiler, bool canAssign)
void subscriptSignature (Compiler *compiler, Signature *signature)
static void super_ (Compiler *compiler, bool canAssign)
static void testExitLoop (Compiler *compiler)
static void this_ (Compiler *compiler, bool canAssign)
static void twoCharToken (Parser *parser, char c, TokenType two, TokenType one)
static void unaryOp (Compiler *compiler, bool canAssign)
void unarySignature (Compiler *compiler, Signature *signature)
static void validateNumParameters (Compiler *compiler, int numArgs)
static void variableDefinition (Compiler *compiler)
static void whileStatement (Compiler *compiler)
void wrenBindMethodCode (ObjClass *classObj, ObjFn *fn)
ObjFn * wrenCompile (WrenVM *vm, ObjModule *module, const char *source, bool isExpression, bool printErrors)
void wrenMarkCompiler (WrenVM *vm, Compiler *compiler)
Variables
static Keyword keywords []
GrammarRule rules []
static const int stackEffects []
Macro Definition Documentation
ERROR_MESSAGE_SIZE
#define ERROR_MESSAGE_SIZE (80 + MAX_VARIABLE_NAME + 15)
Definition at line 51 of file wren_compiler.c.
INFIX
#define INFIX (prec, fn) { NULL, fn, NULL, prec, NULL }
Definition at line 2744 of file wren_compiler.c.
INFIX_OPERATOR
#define INFIX_OPERATOR (prec, name) { NULL, infixOp, infixSignature, prec, name }
Definition at line 2745 of file wren_compiler.c.
MAX_CONSTANTS
#define MAX_CONSTANTS (1 << 16)
Definition at line 34 of file wren_compiler.c.
MAX_INTERPOLATION_NESTING
#define MAX_INTERPOLATION_NESTING 8
Definition at line 44 of file wren_compiler.c.
MAX_JUMP
#define MAX_JUMP (1 << 16)
Definition at line 38 of file wren_compiler.c.
MAX_LOCALS
#define MAX_LOCALS 256
Definition at line 25 of file wren_compiler.c.
MAX_UPVALUES
#define MAX_UPVALUES 256
Definition at line 29 of file wren_compiler.c.
OPCODE
#define OPCODE (_, effect) effect,
OPERATOR
#define OPERATOR (name) { unaryOp, infixOp, mixedSignature, PREC_TERM, name }
Definition at line 2747 of file wren_compiler.c.
PREFIX
#define PREFIX (fn) { fn, NULL, NULL, PREC_NONE, NULL }
Definition at line 2743 of file wren_compiler.c.
PREFIX_OPERATOR
#define PREFIX_OPERATOR (name) { unaryOp, NULL, unarySignature, PREC_NONE, name }
Definition at line 2746 of file wren_compiler.c.
UNUSED
#define UNUSED { NULL, NULL, NULL, PREC_NONE, NULL }
Definition at line 2742 of file wren_compiler.c.
Typedef Documentation
GrammarFn
typedef void(* GrammarFn) (Compiler *, bool canAssign)
Definition at line 1734 of file wren_compiler.c.
Loop
typedef struct sLoop Loop
SignatureFn
typedef void(* SignatureFn) (Compiler *compiler, Signature *signature)
Definition at line 1736 of file wren_compiler.c.
Enumeration Type Documentation
Precedence
enum Precedence
Enumerator
PREC_NONE
PREC_LOWEST
PREC_ASSIGNMENT
PREC_CONDITIONAL
PREC_LOGICAL_OR
PREC_LOGICAL_AND
PREC_EQUALITY
PREC_IS
PREC_COMPARISON
PREC_BITWISE_OR
PREC_BITWISE_XOR
PREC_BITWISE_AND
PREC_BITWISE_SHIFT
PREC_RANGE
PREC_TERM
PREC_FACTOR
PREC_UNARY
PREC_CALL
PREC_PRIMARY
Definition at line 1711 of file wren_compiler.c.
 {
   PREC_NONE,
   PREC_LOWEST,
   PREC_ASSIGNMENT,    // =
   PREC_CONDITIONAL,   // ?:
   PREC_LOGICAL_OR,    // ||
   PREC_LOGICAL_AND,   // &&
   PREC_EQUALITY,      // == !=
   PREC_IS,            // is
   PREC_COMPARISON,    // < > <= >=
   PREC_BITWISE_OR,    // |
   PREC_BITWISE_XOR,   // ^
   PREC_BITWISE_AND,   // &
   PREC_BITWISE_SHIFT, // << >>
   PREC_RANGE,         // .. ...
   PREC_TERM,          // + -
   PREC_FACTOR,        // * / %
   PREC_UNARY,         // unary - ! ~
   PREC_CALL,          // . () []
   PREC_PRIMARY
 } Precedence;
Scope
enum Scope
Enumerator
SCOPE_LOCAL
SCOPE_UPVALUE
SCOPE_MODULE
Definition at line 381 of file wren_compiler.c.
 {
   // A local variable in the current function.
   SCOPE_LOCAL,
   // A local variable declared in an enclosing function.
   SCOPE_UPVALUE,
   // A top-level module variable.
   SCOPE_MODULE
 } Scope;
SignatureType
enum SignatureType
Enumerator
SIG_METHOD
SIG_GETTER
SIG_SETTER
SIG_SUBSCRIPT
SIG_SUBSCRIPT_SETTER
SIG_INITIALIZER
Definition at line 259 of file wren_compiler.c.
 {
   // A name followed by a (possibly empty) parenthesized parameter list. Also
   // used for binary operators.
   SIG_METHOD,
   // Just a name. Also used for unary operators.
   SIG_GETTER,
   // A name followed by "=".
   SIG_SETTER,
   // A square bracketed parameter list.
   SIG_SUBSCRIPT,
   // A square bracketed parameter list followed by "=".
   SIG_SUBSCRIPT_SETTER,
   // A constructor initializer function. This has a distinct signature to
   // prevent it from being invoked directly outside of the constructor on the
   // metaclass.
   SIG_INITIALIZER
 } SignatureType;
TokenType
enum TokenType
Enumerator
TOKEN_LEFT_PAREN
TOKEN_RIGHT_PAREN
TOKEN_LEFT_BRACKET
TOKEN_RIGHT_BRACKET
TOKEN_LEFT_BRACE
TOKEN_RIGHT_BRACE
TOKEN_COLON
TOKEN_DOT
TOKEN_DOTDOT
TOKEN_DOTDOTDOT
TOKEN_COMMA
TOKEN_STAR
TOKEN_SLASH
TOKEN_PERCENT
TOKEN_HASH
TOKEN_PLUS
TOKEN_MINUS
TOKEN_LTLT
TOKEN_GTGT
TOKEN_PIPE
TOKEN_PIPEPIPE
TOKEN_CARET
TOKEN_AMP
TOKEN_AMPAMP
TOKEN_BANG
TOKEN_TILDE
TOKEN_QUESTION
TOKEN_EQ
TOKEN_LT
TOKEN_GT
TOKEN_LTEQ
TOKEN_GTEQ
TOKEN_EQEQ
TOKEN_BANGEQ
TOKEN_BREAK
TOKEN_CONTINUE
TOKEN_CLASS
TOKEN_CONSTRUCT
TOKEN_ELSE
TOKEN_FALSE
TOKEN_FOR
TOKEN_FOREIGN
TOKEN_IF
TOKEN_IMPORT
TOKEN_AS
TOKEN_IN
TOKEN_IS
TOKEN_NULL
TOKEN_RETURN
TOKEN_STATIC
TOKEN_SUPER
TOKEN_THIS
TOKEN_TRUE
TOKEN_VAR
TOKEN_WHILE
TOKEN_FIELD
TOKEN_STATIC_FIELD
TOKEN_NAME
TOKEN_NUMBER
TOKEN_STRING
TOKEN_INTERPOLATION
TOKEN_LINE
TOKEN_ERROR
TOKEN_EOF
Definition at line 53 of file wren_compiler.c.
 {
   TOKEN_LEFT_PAREN,
   TOKEN_RIGHT_PAREN,
   TOKEN_LEFT_BRACKET,
   TOKEN_RIGHT_BRACKET,
   TOKEN_LEFT_BRACE,
   TOKEN_RIGHT_BRACE,
   TOKEN_COLON,
   TOKEN_DOT,
   TOKEN_DOTDOT,
   TOKEN_DOTDOTDOT,
   TOKEN_COMMA,
   TOKEN_STAR,
   TOKEN_SLASH,
   TOKEN_PERCENT,
   TOKEN_HASH,
   TOKEN_PLUS,
   TOKEN_MINUS,
   TOKEN_LTLT,
   TOKEN_GTGT,
   TOKEN_PIPE,
   TOKEN_PIPEPIPE,
   TOKEN_CARET,
   TOKEN_AMP,
   TOKEN_AMPAMP,
   TOKEN_BANG,
   TOKEN_TILDE,
   TOKEN_QUESTION,
   TOKEN_EQ,
   TOKEN_LT,
   TOKEN_GT,
   TOKEN_LTEQ,
   TOKEN_GTEQ,
   TOKEN_EQEQ,
   TOKEN_BANGEQ,
   TOKEN_BREAK,
   TOKEN_CONTINUE,
   TOKEN_CLASS,
   TOKEN_CONSTRUCT,
   TOKEN_ELSE,
   TOKEN_FALSE,
   TOKEN_FOR,
   TOKEN_FOREIGN,
   TOKEN_IF,
   TOKEN_IMPORT,
   TOKEN_AS,
   TOKEN_IN,
   TOKEN_IS,
   TOKEN_NULL,
   TOKEN_RETURN,
   TOKEN_STATIC,
   TOKEN_SUPER,
   TOKEN_THIS,
   TOKEN_TRUE,
   TOKEN_VAR,
   TOKEN_WHILE,
   TOKEN_FIELD,
   TOKEN_STATIC_FIELD,
   TOKEN_NAME,
   TOKEN_NUMBER,
   // A string literal without any interpolation, or the last section of a
   // string following the last interpolated expression.
   TOKEN_STRING,
   // A portion of a string literal preceding an interpolated expression. This
   // string:
   //
   //     "a %(b) c %(d) e"
   //
   // is tokenized to:
   //
   //     TOKEN_INTERPOLATION "a "
   //     TOKEN_NAME          b
   //     TOKEN_INTERPOLATION " c "
   //     TOKEN_NAME          d
   //     TOKEN_STRING        " e"
   TOKEN_INTERPOLATION,
   TOKEN_LINE,
   TOKEN_ERROR,
   TOKEN_EOF
 } TokenType;
Function Documentation
addConstant()
static int addConstant (Compiler * compiler, Value constant) static
Definition at line 496 of file wren_compiler.c.
 {
   if (compiler->parser->hasError) return -1;
   // See if we already have a constant for the value. If so, reuse it.
   if (compiler->constants != NULL)
   {
     Value existing = wrenMapGet(compiler->constants, constant);
     if (IS_NUM(existing)) return (int)AS_NUM(existing);
   }
   // It's a new constant.
   if (compiler->fn->constants.count < MAX_CONSTANTS)
   {
     if (IS_OBJ(constant)) wrenPushRoot(compiler->parser->vm, AS_OBJ(constant));
     wrenValueBufferWrite(compiler->parser->vm, &compiler->fn->constants,
                          constant);
     if (IS_OBJ(constant)) wrenPopRoot(compiler->parser->vm);
     if (compiler->constants == NULL)
     {
       compiler->constants = wrenNewMap(compiler->parser->vm);
     }
     wrenMapSet(compiler->parser->vm, compiler->constants, constant,
                NUM_VAL(compiler->fn->constants.count - 1));
   }
   else
   {
     error(compiler, "A function may only contain %d unique constants.",
           MAX_CONSTANTS);
   }
   return compiler->fn->constants.count - 1;
 }
References AS_NUM, AS_OBJ, error(), IS_NUM, IS_OBJ, MAX_CONSTANTS, NULL, NUM_VAL, wrenMapGet(), wrenMapSet(), wrenNewMap(), wrenPopRoot(), and wrenPushRoot().
Referenced by callSignature(), emitConstant(), endCompiler(), and import().
addLocal()
static int addLocal (Compiler * compiler, const char * name, int length) static
Definition at line 1381 of file wren_compiler.c.
 {
   Local* local = &compiler->locals[compiler->numLocals];
   local->name = name;
   local->length = length;
   local->depth = compiler->scopeDepth;
   local->isUpvalue = false;
   return compiler->numLocals++;
 }
References name().
Referenced by declareVariable(), and forStatement().
addToAttributeGroup()
static void addToAttributeGroup (Compiler * compiler, Value group, Value key, Value value) static
Definition at line 3952 of file wren_compiler.c.
 {
   WrenVM* vm = compiler->parser->vm;
   if(IS_OBJ(group)) wrenPushRoot(vm, AS_OBJ(group));
   if(IS_OBJ(key))   wrenPushRoot(vm, AS_OBJ(key));
   if(IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   Value groupMapValue = wrenMapGet(compiler->attributes, group);
   if(IS_UNDEFINED(groupMapValue))
   {
     groupMapValue = OBJ_VAL(wrenNewMap(vm));
     wrenMapSet(vm, compiler->attributes, group, groupMapValue);
   }
   //we store them as a map per so we can maintain duplicate keys
   //group = { key:[value, ...], }
   ObjMap* groupMap = AS_MAP(groupMapValue);
   //var keyItems = group[key]
   //if(!keyItems) keyItems = group[key] = []
   Value keyItemsValue = wrenMapGet(groupMap, key);
   if(IS_UNDEFINED(keyItemsValue))
   {
     keyItemsValue = OBJ_VAL(wrenNewList(vm, 0));
     wrenMapSet(vm, groupMap, key, keyItemsValue);
   }
   //keyItems.add(value)
   ObjList* keyItems = AS_LIST(keyItemsValue);
   wrenValueBufferWrite(vm, &keyItems->elements, value);
   if(IS_OBJ(group)) wrenPopRoot(vm);
   if(IS_OBJ(key))   wrenPopRoot(vm);
   if(IS_OBJ(value)) wrenPopRoot(vm);
 }
References AS_LIST, AS_MAP, AS_OBJ, ObjList::elements, IS_OBJ, IS_UNDEFINED, OBJ_VAL, wrenMapGet(), wrenMapSet(), wrenNewList(), wrenNewMap(), wrenPopRoot(), and wrenPushRoot().
Referenced by matchAttribute().
addUpvalue()
static int addUpvalue (Compiler * compiler, bool isLocal, int index) static
Definition at line 1551 of file wren_compiler.c.
 {
   // Look for an existing one.
   for (int i = 0; i < compiler->fn->numUpvalues; i++)
   {
     CompilerUpvalue* upvalue = &compiler->upvalues[i];
     if (upvalue->index == index && upvalue->isLocal == isLocal) return i;
   }
   // If we got here, it's a new upvalue.
   compiler->upvalues[compiler->fn->numUpvalues].isLocal = isLocal;
   compiler->upvalues[compiler->fn->numUpvalues].index = index;
   return compiler->fn->numUpvalues++;
 }
Referenced by findUpvalue().
allowLineBeforeDot()
static void allowLineBeforeDot (Compiler * compiler) static
Definition at line 1303 of file wren_compiler.c.
{
   if (peek(compiler) == TOKEN_LINE && peekNext(compiler) == TOKEN_DOT) {
     nextToken(compiler->parser);
   }
 }
References nextToken(), peek(), peekNext(), TOKEN_DOT, and TOKEN_LINE.
Referenced by bareName(), field(), namedCall(), and subscript().
and_()
static void and_ (Compiler * compiler, bool canAssign) static
Definition at line 2536 of file wren_compiler.c.
 {
   ignoreNewlines(compiler);
   // Skip the right argument if the left is false.
   int jump = emitJump(compiler, CODE_AND);
   parsePrecedence(compiler, PREC_LOGICAL_AND);
   patchJump(compiler, jump);
 }
References emitJump(), ignoreNewlines(), parsePrecedence(), patchJump(), and PREC_LOGICAL_AND.
bareName()
static void bareName (Compiler * compiler, bool canAssign, Variable variable) static
Definition at line 2301 of file wren_compiler.c.
 {
   // If there's an "=" after a bare name, it's a variable assignment.
   if (canAssign && match(compiler, TOKEN_EQ))
   {
     // Compile the right-hand side.
     expression(compiler);
     // Emit the store instruction.
     switch (variable.scope)
     {
       case SCOPE_LOCAL:
         emitByteArg(compiler, CODE_STORE_LOCAL, variable.index);
         break;
       case SCOPE_UPVALUE:
         emitByteArg(compiler, CODE_STORE_UPVALUE, variable.index);
         break;
       case SCOPE_MODULE:
         emitShortArg(compiler, CODE_STORE_MODULE_VAR, variable.index);
         break;
       default:
         UNREACHABLE();
     }
     return;
   }
   // Emit the load instruction.
   loadVariable(compiler, variable);
   allowLineBeforeDot(compiler);
 }
References allowLineBeforeDot(), emitByteArg(), emitShortArg(), expression(), loadVariable(), match(), SCOPE_LOCAL, SCOPE_MODULE, SCOPE_UPVALUE, TOKEN_EQ, and UNREACHABLE.
Referenced by name(), and staticField().
boolean()
static void boolean (Compiler * compiler, bool canAssign) static
Definition at line 2215 of file wren_compiler.c.
 {
   emitOp(compiler,
       compiler->parser->previous.type == TOKEN_FALSE ? CODE_FALSE : CODE_TRUE);
 }
References emitOp(), and TOKEN_FALSE.
call()
static void call (Compiler * compiler, bool canAssign) static
Definition at line 2529 of file wren_compiler.c.
 {
   ignoreNewlines(compiler);
   consume(compiler, TOKEN_NAME, "Expect method name after '.'.");
   namedCall(compiler, canAssign, CODE_CALL_0);
 }
References consume(), ignoreNewlines(), namedCall(), and TOKEN_NAME.
callMethod()
static void callMethod (Compiler * compiler, int numArgs, const char * name, int length) static
Definition at line 1995 of file wren_compiler.c.
 {
   int symbol = methodSymbol(compiler, name, length);
   emitShortArg(compiler, (Code)(CODE_CALL_0 + numArgs), symbol);
 }
References emitShortArg(), methodSymbol(), and name().
Referenced by emitAttributeMethods(), emitAttributes(), emitClassAttributes(), forStatement(), list(), map(), stringInterpolation(), and unaryOp().
callSignature()
static void callSignature (Compiler * compiler, Code instruction, Signature * signature) static
Definition at line 1974 of file wren_compiler.c.
 {
   int symbol = signatureSymbol(compiler, signature);
   emitShortArg(compiler, (Code)(instruction + signature->arity), symbol);
   if (instruction == CODE_SUPER_0)
   {
     // Super calls need to be statically bound to the class's superclass. This
     // ensures we call the right method even when a method containing a super
     // call is inherited by another subclass.
     //
     // We bind it at class definition time by storing a reference to the
     // superclass in a constant. So, here, we create a slot in the constant
     // table and store NULL in it. When the method is bound, we'll look up the
     // superclass then and store it in the constant slot.
     emitShort(compiler, addConstant(compiler, NULL_VAL));
   }
 }
References addConstant(), emitShort(), emitShortArg(), NULL_VAL, and signatureSymbol().
Referenced by infixOp(), methodCall(), namedCall(), and subscript().
classDefinition()
static void classDefinition (Compiler * compiler, bool isForeign) static
Definition at line 3514 of file wren_compiler.c.
 {
   // Create a variable to store the class in.
   Variable classVariable;
   classVariable.scope = compiler->scopeDepth == -1 ? SCOPE_MODULE : SCOPE_LOCAL;
   classVariable.index = declareNamedVariable(compiler);
   // Create shared class name value
   Value classNameString = wrenNewStringLength(compiler->parser->vm,
       compiler->parser->previous.start, compiler->parser->previous.length);
   // Create class name string to track method duplicates
   ObjString* className = AS_STRING(classNameString);
   // Make a string constant for the name.
   emitConstant(compiler, classNameString);
   // Load the superclass (if there is one).
   if (match(compiler, TOKEN_IS))
   {
     parsePrecedence(compiler, PREC_CALL);
   }
   else
   {
     // Implicitly inherit from Object.
     loadCoreVariable(compiler, "Object");
   }
   // Store a placeholder for the number of fields argument. We don't know the
   // count until we've compiled all the methods to see which fields are used.
   int numFieldsInstruction = -1;
   if (isForeign)
   {
     emitOp(compiler, CODE_FOREIGN_CLASS);
   }
   else
   {
     numFieldsInstruction = emitByteArg(compiler, CODE_CLASS, 255);
   }
   // Store it in its name.
   defineVariable(compiler, classVariable.index);
   // Push a local variable scope. Static fields in a class body are hoisted out
   // into local variables declared in this scope. Methods that use them will
   // have upvalues referencing them.
   pushScope(compiler);
   ClassInfo classInfo;
   classInfo.isForeign = isForeign;
   classInfo.name = className;
   // Allocate attribute maps if necessary.
   // A method will allocate the methods one if needed
   classInfo.classAttributes = compiler->attributes->count > 0
         ? wrenNewMap(compiler->parser->vm)
         : NULL;
   classInfo.methodAttributes = NULL;
   // Copy any existing attributes into the class
   copyAttributes(compiler, classInfo.classAttributes);
   // Set up a symbol table for the class's fields. We'll initially compile
   // them to slots starting at zero. When the method is bound to the class, the
   // bytecode will be adjusted by [wrenBindMethod] to take inherited fields
   // into account.
   wrenSymbolTableInit(&classInfo.fields);
   // Set up symbol buffers to track duplicate static and instance methods.
   wrenIntBufferInit(&classInfo.methods);
   wrenIntBufferInit(&classInfo.staticMethods);
   compiler->enclosingClass = &classInfo;
   // Compile the method definitions.
   consume(compiler, TOKEN_LEFT_BRACE, "Expect '{' after class declaration.");
   matchLine(compiler);
   while (!match(compiler, TOKEN_RIGHT_BRACE))
   {
     if (!method(compiler, classVariable)) break;
     // Don't require a newline after the last definition.
     if (match(compiler, TOKEN_RIGHT_BRACE)) break;
     consumeLine(compiler, "Expect newline after definition in class.");
   }
   // If any attributes are present,
   // instantiate a ClassAttributes instance for the class
   // and send it over to CODE_END_CLASS
   bool hasAttr = classInfo.classAttributes != NULL ||
                  classInfo.methodAttributes != NULL;
   if(hasAttr) {
     emitClassAttributes(compiler, &classInfo);
     loadVariable(compiler, classVariable);
     // At the moment, we don't have other uses for CODE_END_CLASS,
     // so we put it inside this condition. Later, we can always
     // emit it and use it as needed.
     emitOp(compiler, CODE_END_CLASS);
   }
   // Update the class with the number of fields.
   if (!isForeign)
   {
     compiler->fn->code.data[numFieldsInstruction] =
         (uint8_t)classInfo.fields.count;
   }
   // Clear symbol tables for tracking field and method names.
   wrenSymbolTableClear(compiler->parser->vm, &classInfo.fields);
   wrenIntBufferClear(compiler->parser->vm, &classInfo.methods);
   wrenIntBufferClear(compiler->parser->vm, &classInfo.staticMethods);
   compiler->enclosingClass = NULL;
   popScope(compiler);
 }
References AS_STRING, consume(), consumeLine(), copyAttributes(), declareNamedVariable(), defineVariable(), emitByteArg(), emitClassAttributes(), emitConstant(), emitOp(), loadCoreVariable(), loadVariable(), match(), matchLine(), method(), NULL, parsePrecedence(), popScope(), PREC_CALL, pushScope(), SCOPE_LOCAL, SCOPE_MODULE, TOKEN_IS, TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE, wrenNewMap(), wrenNewStringLength(), wrenSymbolTableClear(), and wrenSymbolTableInit().
Referenced by definition().
conditional()
static void conditional (Compiler * compiler, bool canAssign) static
Definition at line 2556 of file wren_compiler.c.
 {
   // Ignore newline after '?'.
   ignoreNewlines(compiler);
   // Jump to the else branch if the condition is false.
   int ifJump = emitJump(compiler, CODE_JUMP_IF);
   // Compile the then branch.
   parsePrecedence(compiler, PREC_CONDITIONAL);
   consume(compiler, TOKEN_COLON,
           "Expect ':' after then branch of conditional operator.");
   ignoreNewlines(compiler);
   // Jump over the else branch when the if branch is taken.
   int elseJump = emitJump(compiler, CODE_JUMP);
   // Compile the else branch.
   patchJump(compiler, ifJump);
   parsePrecedence(compiler, PREC_ASSIGNMENT);
   // Patch the jump over the else.
   patchJump(compiler, elseJump);
 }
References consume(), emitJump(), ignoreNewlines(), parsePrecedence(), patchJump(), PREC_ASSIGNMENT, PREC_CONDITIONAL, and TOKEN_COLON.
constructorSignature()
void constructorSignature (Compiler * compiler, Signature * signature)
Definition at line 2713 of file wren_compiler.c.
 {
   consume(compiler, TOKEN_NAME, "Expect constructor name after 'construct'.");
   // Capture the name.
   *signature = signatureFromToken(compiler, SIG_INITIALIZER);
   if (match(compiler, TOKEN_EQ))
   {
     error(compiler, "A constructor cannot be a setter.");
   }
   if (!match(compiler, TOKEN_LEFT_PAREN))
   {
     error(compiler, "A constructor cannot be a getter.");
     return;
   }
   // Allow an empty parameter list.
   if (match(compiler, TOKEN_RIGHT_PAREN)) return;
   finishParameterList(compiler, signature);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after parameters.");
 }
References consume(), error(), finishParameterList(), match(), SIG_INITIALIZER, signatureFromToken(), TOKEN_EQ, TOKEN_LEFT_PAREN, TOKEN_NAME, and TOKEN_RIGHT_PAREN.
consume()
static void consume (Compiler * compiler, TokenType expected, const char * errorMessage) static
Definition at line 1266 of file wren_compiler.c.
 {
   nextToken(compiler->parser);
   if (compiler->parser->previous.type != expected)
   {
     error(compiler, errorMessage);
     // If the next token is the one we want, assume the current one is just a
     // spurious error and discard it to minimize the number of cascaded errors.
     if (compiler->parser->current.type == expected) nextToken(compiler->parser);
   }
 }
References error(), and nextToken().
Referenced by call(), classDefinition(), conditional(), constructorSignature(), consumeLine(), declareNamedVariable(), definition(), finishBlock(), forStatement(), grouping(), ifStatement(), import(), infixSignature(), list(), map(), matchAttribute(), maybeSetter(), method(), methodCall(), mixedSignature(), parameterList(), stringInterpolation(), subscript(), subscriptSignature(), super_(), variableDefinition(), whileStatement(), and wrenCompile().
consumeLine()
static void consumeLine (Compiler * compiler, const char * errorMessage) static
Definition at line 1297 of file wren_compiler.c.
 {
   consume(compiler, TOKEN_LINE, errorMessage);
   ignoreNewlines(compiler);
 }
References consume(), ignoreNewlines(), and TOKEN_LINE.
Referenced by classDefinition(), finishBlock(), and matchAttribute().
consumeLiteral()
static Value consumeLiteral (Compiler * compiler, const char * message) static
Definition at line 3344 of file wren_compiler.c.
 {
   if(match(compiler, TOKEN_FALSE))  return FALSE_VAL;
   if(match(compiler, TOKEN_TRUE))   return TRUE_VAL;
   if(match(compiler, TOKEN_NUMBER)) return compiler->parser->previous.value;
   if(match(compiler, TOKEN_STRING)) return compiler->parser->previous.value;
   if(match(compiler, TOKEN_NAME))   return compiler->parser->previous.value;
   error(compiler, message);
   nextToken(compiler->parser);
   return NULL_VAL;
 }
References error(), FALSE_VAL, match(), nextToken(), NULL_VAL, TOKEN_FALSE, TOKEN_NAME, TOKEN_NUMBER, TOKEN_STRING, TOKEN_TRUE, and TRUE_VAL.
Referenced by matchAttribute().
copyAttributes()
static void copyAttributes (Compiler * compiler, ObjMap * into) static
Definition at line 4076 of file wren_compiler.c.
 {
   compiler->numAttributes = 0;
   if(compiler->attributes->count == 0) return;
   if(into == NULL) return;
   WrenVM* vm = compiler->parser->vm;
   // Note we copy the actual values as is since we'll take ownership
   // and clear the original map
   for(uint32_t attrIdx = 0; attrIdx < compiler->attributes->capacity; attrIdx++)
   {
     const MapEntry* attrEntry = &compiler->attributes->entries[attrIdx];
     if(IS_UNDEFINED(attrEntry->key)) continue;
     wrenMapSet(vm, into, attrEntry->key, attrEntry->value);
   }
   wrenMapClear(vm, compiler->attributes);
 }
References IS_UNDEFINED, MapEntry::key, NULL, MapEntry::value, wrenMapClear(), and wrenMapSet().
Referenced by classDefinition(), and copyMethodAttributes().
copyMethodAttributes()
static void copyMethodAttributes (Compiler * compiler, bool isForeign, bool isStatic, const char * fullSignature, int32_t length) static
Definition at line 4100 of file wren_compiler.c.
 {
   compiler->numAttributes = 0;
   if(compiler->attributes->count == 0) return;
   WrenVM* vm = compiler->parser->vm;
   // Make a map for this method to copy into
   ObjMap* methodAttr = wrenNewMap(vm);
   wrenPushRoot(vm, (Obj*)methodAttr);
   copyAttributes(compiler, methodAttr);
   // Include 'foreign static ' in front as needed
   int32_t fullLength = length;
   if(isForeign) fullLength += 8;
   if(isStatic) fullLength += 7;
   char fullSignatureWithPrefix[MAX_METHOD_SIGNATURE + 8 + 7];
   const char* foreignPrefix = isForeign ? "foreign " : "";
   const char* staticPrefix = isStatic ? "static " : "";
   sprintf(fullSignatureWithPrefix, "%s%s%.*s", foreignPrefix, staticPrefix,
                                                length, fullSignature);
   fullSignatureWithPrefix[fullLength] = '\0';
   if(compiler->enclosingClass->methodAttributes == NULL) {
     compiler->enclosingClass->methodAttributes = wrenNewMap(vm);
   }
   // Store the method attributes in the class map
   Value key = wrenNewStringLength(vm, fullSignatureWithPrefix, fullLength);
   wrenMapSet(vm, compiler->enclosingClass->methodAttributes, key, OBJ_VAL(methodAttr));
   wrenPopRoot(vm);
 }
References copyAttributes(), MAX_METHOD_SIGNATURE, NULL, OBJ_VAL, wrenMapSet(), wrenNewMap(), wrenNewStringLength(), wrenPopRoot(), and wrenPushRoot().
Referenced by method().
createConstructor()
static void createConstructor (Compiler * compiler, Signature * signature, int initializerSymbol) static
Definition at line 3279 of file wren_compiler.c.
 {
   Compiler methodCompiler;
   initCompiler(&methodCompiler, compiler->parser, compiler, true);
   // Allocate the instance.
   emitOp(&methodCompiler, compiler->enclosingClass->isForeign
        ? CODE_FOREIGN_CONSTRUCT : CODE_CONSTRUCT);
   // Run its initializer.
   emitShortArg(&methodCompiler, (Code)(CODE_CALL_0 + signature->arity),
                initializerSymbol);
   // Return the instance.
   emitOp(&methodCompiler, CODE_RETURN);
   endCompiler(&methodCompiler, "", 0);
 }
References emitOp(), emitShortArg(), endCompiler(), and initCompiler().
Referenced by method().
declareMethod()
static int declareMethod (Compiler * compiler, Signature * signature, const char * name, int length) static
Definition at line 3320 of file wren_compiler.c.
 {
   int symbol = signatureSymbol(compiler, signature);
   // See if the class has already declared method with this signature.
   ClassInfo* classInfo = compiler->enclosingClass;
   IntBuffer* methods = classInfo->inStatic
       ? &classInfo->staticMethods : &classInfo->methods;
   for (int i = 0; i < methods->count; i++)
   {
     if (methods->data[i] == symbol)
     {
       const char* staticPrefix = classInfo->inStatic ? "static " : "";
       error(compiler, "Class %s already defines a %smethod '%s'.",
             &compiler->enclosingClass->name->value, staticPrefix, name);
       break;
     }
   }
   wrenIntBufferWrite(compiler->parser->vm, methods, symbol);
   return symbol;
 }
References error(), name(), and signatureSymbol().
Referenced by method().
declareNamedVariable()
static int declareNamedVariable (Compiler * compiler) static
Definition at line 1460 of file wren_compiler.c.
 {
   consume(compiler, TOKEN_NAME, "Expect variable name.");
   return declareVariable(compiler, NULL);
 }
References consume(), declareVariable(), NULL, and TOKEN_NAME.
Referenced by classDefinition(), finishParameterList(), import(), infixSignature(), maybeSetter(), and mixedSignature().
declareVariable()
static int declareVariable (Compiler * compiler, Token * token) static
Definition at line 1394 of file wren_compiler.c.
 {
   if (token == NULL) token = &compiler->parser->previous;
   if (token->length > MAX_VARIABLE_NAME)
   {
     error(compiler, "Variable name cannot be longer than %d characters.",
           MAX_VARIABLE_NAME);
   }
   // Top-level module scope.
   if (compiler->scopeDepth == -1)
   {
     int line = -1;
     int symbol = wrenDefineVariable(compiler->parser->vm,
                                     compiler->parser->module,
                                     token->start, token->length,
                                     NULL_VAL, &line);
     if (symbol == -1)
     {
       error(compiler, "Module variable is already defined.");
     }
     else if (symbol == -2)
     {
       error(compiler, "Too many module variables defined.");
     }
     else if (symbol == -3)
     {
       error(compiler,
         "Variable '%.*s' referenced before this definition (first use at line %d).",
         token->length, token->start, line);
     }
     return symbol;
   }
   // See if there is already a variable with this name declared in the current
   // scope. (Outer scopes are OK: those get shadowed.)
   for (int i = compiler->numLocals - 1; i >= 0; i--)
   {
     Local* local = &compiler->locals[i];
     // Once we escape this scope and hit an outer one, we can stop.
     if (local->depth < compiler->scopeDepth) break;
     if (local->length == token->length &&
         memcmp(local->name, token->start, token->length) == 0)
     {
       error(compiler, "Variable is already declared in this scope.");
       return i;
     }
   }
   if (compiler->numLocals == MAX_LOCALS)
   {
     error(compiler, "Cannot declare more than %d variables in one scope.",
           MAX_LOCALS);
     return -1;
   }
   return addLocal(compiler, token->start, token->length);
 }
References addLocal(), error(), MAX_LOCALS, MAX_VARIABLE_NAME, NULL, NULL_VAL, token, and wrenDefineVariable().
Referenced by declareNamedVariable(), import(), staticField(), and variableDefinition().
defineMethod()
static void defineMethod (Compiler * compiler, Variable classVariable, bool isStatic, int methodSymbol) static
Definition at line 3301 of file wren_compiler.c.
 {
   // Load the class. We have to do this for each method because we can't
   // keep the class on top of the stack. If there are static fields, they
   // will be locals above the initial variable slot for the class on the
   // stack. To skip past those, we just load the class each time right before
   // defining a method.
   loadVariable(compiler, classVariable);
   // Define the method.
   Code instruction = isStatic ? CODE_METHOD_STATIC : CODE_METHOD_INSTANCE;
   emitShortArg(compiler, instruction, methodSymbol);
 }
References emitShortArg(), loadVariable(), and methodSymbol().
Referenced by method().
defineVariable()
static void defineVariable (Compiler * compiler, int symbol) static
Definition at line 1467 of file wren_compiler.c.
 {
   // Store the variable. If it's a local, the result of the initializer is
   // in the correct slot on the stack already so we're done.
   if (compiler->scopeDepth >= 0) return;
   // It's a module-level variable, so store the value in the module slot and
   // then discard the temporary for the initializer.
   emitShortArg(compiler, CODE_STORE_MODULE_VAR, symbol);
   emitOp(compiler, CODE_POP);
 }
References emitOp(), and emitShortArg().
Referenced by classDefinition(), import(), staticField(), and variableDefinition().
definition()
void definition (Compiler * compiler) static
Definition at line 3727 of file wren_compiler.c.
 {
   if(matchAttribute(compiler)) {
     definition(compiler);
     return;
   }
   if (match(compiler, TOKEN_CLASS))
   {
     classDefinition(compiler, false);
     return;
   }
   else if (match(compiler, TOKEN_FOREIGN))
   {
     consume(compiler, TOKEN_CLASS, "Expect 'class' after 'foreign'.");
     classDefinition(compiler, true);
     return;
   }
   disallowAttributes(compiler);
   if (match(compiler, TOKEN_IMPORT))
   {
     import(compiler);
   }
   else if (match(compiler, TOKEN_VAR))
   {
     variableDefinition(compiler);
   }
   else
   {
     statement(compiler);
   }
 }
References classDefinition(), consume(), disallowAttributes(), match(), matchAttribute(), statement(), TOKEN_CLASS, TOKEN_FOREIGN, TOKEN_IMPORT, TOKEN_VAR, and variableDefinition().
Referenced by finishBlock(), and wrenCompile().
disallowAttributes()
static void disallowAttributes (Compiler * compiler) static
Definition at line 3941 of file wren_compiler.c.
 {
   if (compiler->numAttributes > 0)
   {
     error(compiler, "Attributes can only specified before a class or a method");
     wrenMapClear(compiler->parser->vm, compiler->attributes);
     compiler->numAttributes = 0;
   }
 }
References error(), and wrenMapClear().
Referenced by definition().
discardLocals()
static int discardLocals (Compiler * compiler, int depth) static
Definition at line 1492 of file wren_compiler.c.
 {
   ASSERT(compiler->scopeDepth > -1, "Cannot exit top-level scope.");
   int local = compiler->numLocals - 1;
   while (local >= 0 && compiler->locals[local].depth >= depth)
   {
     // If the local was closed over, make sure the upvalue gets closed when it
     // goes out of scope on the stack. We use emitByte() and not emitOp() here
     // because we don't want to track that stack effect of these pops since the
     // variables are still in scope after the break.
     if (compiler->locals[local].isUpvalue)
     {
       emitByte(compiler, CODE_CLOSE_UPVALUE);
     }
     else
     {
       emitByte(compiler, CODE_POP);
     }
     local--;
   }
   return compiler->numLocals - local - 1;
 }
References ASSERT, and emitByte().
Referenced by popScope(), and statement().
emitAttributeMethods()
static void emitAttributeMethods (Compiler * compiler, ObjMap * attributes) static
Definition at line 4040 of file wren_compiler.c.
 {
     // Instantiate a new map for the attributes
   loadCoreVariable(compiler, "Map");
   callMethod(compiler, 0, "new()", 5);
   for(uint32_t methodIdx = 0; methodIdx < attributes->capacity; methodIdx++)
   {
     const MapEntry* methodEntry = &attributes->entries[methodIdx];
     if(IS_UNDEFINED(methodEntry->key)) continue;
     emitConstant(compiler, methodEntry->key);
     ObjMap* attributeMap = AS_MAP(methodEntry->value);
     emitAttributes(compiler, attributeMap);
     callMethod(compiler, 2, "addCore_(_,_)", 13);
   }
 }
References AS_MAP, callMethod(), ObjMap::capacity, emitAttributes(), emitConstant(), ObjMap::entries, IS_UNDEFINED, MapEntry::key, loadCoreVariable(), and MapEntry::value.
Referenced by emitClassAttributes().
emitAttributes()
static void emitAttributes (Compiler * compiler, ObjMap * attributes) static
Definition at line 3992 of file wren_compiler.c.
 {
   // Instantiate a new map for the attributes
   loadCoreVariable(compiler, "Map");
   callMethod(compiler, 0, "new()", 5);
   // The attributes are stored as group = { key:[value, value, ...] }
   // so our first level is the group map
   for(uint32_t groupIdx = 0; groupIdx < attributes->capacity; groupIdx++)
   {
     const MapEntry* groupEntry = &attributes->entries[groupIdx];
     if(IS_UNDEFINED(groupEntry->key)) continue;
     //group key
     emitConstant(compiler, groupEntry->key);
     //group value is gonna be a map
     loadCoreVariable(compiler, "Map");
     callMethod(compiler, 0, "new()", 5);
     ObjMap* groupItems = AS_MAP(groupEntry->value);
     for(uint32_t itemIdx = 0; itemIdx < groupItems->capacity; itemIdx++)
     {
       const MapEntry* itemEntry = &groupItems->entries[itemIdx];
       if(IS_UNDEFINED(itemEntry->key)) continue;
       emitConstant(compiler, itemEntry->key);
       // Attribute key value, key = []
       loadCoreVariable(compiler, "List");
       callMethod(compiler, 0, "new()", 5);
       // Add the items to the key list
       ObjList* items = AS_LIST(itemEntry->value);
       for(int itemIdx = 0; itemIdx < items->elements.count; ++itemIdx)
       {
         emitConstant(compiler, items->elements.data[itemIdx]);
         callMethod(compiler, 1, "addCore_(_)", 11);
       }
       // Add the list to the map
       callMethod(compiler, 2, "addCore_(_,_)", 13);
     }
     // Add the key/value to the map
     callMethod(compiler, 2, "addCore_(_,_)", 13);
   }
 }
References AS_LIST, AS_MAP, callMethod(), ObjMap::capacity, ObjList::elements, emitConstant(), ObjMap::entries, IS_UNDEFINED, MapEntry::key, loadCoreVariable(), and MapEntry::value.
Referenced by emitAttributeMethods(), and emitClassAttributes().
emitByte()
static int emitByte (Compiler * compiler, int byte) static
Definition at line 1312 of file wren_compiler.c.
 {
   wrenByteBufferWrite(compiler->parser->vm, &compiler->fn->code, (uint8_t)byte);
   // Assume the instruction is associated with the most recently consumed token.
   wrenIntBufferWrite(compiler->parser->vm, &compiler->fn->debug->sourceLines,
                      compiler->parser->previous.line);
   return compiler->fn->code.count - 1;
 }
Referenced by discardLocals(), emitByteArg(), emitJump(), emitOp(), emitShort(), and endCompiler().
emitByteArg()
static int emitByteArg (Compiler * compiler, Code instruction, int arg) static
Definition at line 1345 of file wren_compiler.c.
 {
   emitOp(compiler, instruction);
   return emitByte(compiler, arg);
 }
References emitByte(), and emitOp().
Referenced by bareName(), classDefinition(), field(), forStatement(), loadLocal(), and loadVariable().
emitClassAttributes()
static void emitClassAttributes (Compiler * compiler, ClassInfo * classInfo) static
Definition at line 4059 of file wren_compiler.c.
 {
   loadCoreVariable(compiler, "ClassAttributes");
   classInfo->classAttributes
     ? emitAttributes(compiler, classInfo->classAttributes)
     : null(compiler, false);
   classInfo->methodAttributes
     ? emitAttributeMethods(compiler, classInfo->methodAttributes)
     : null(compiler, false);
   callMethod(compiler, 2, "new(_,_)", 8);
 }
References callMethod(), emitAttributeMethods(), emitAttributes(), and loadCoreVariable().
Referenced by classDefinition().
emitConstant()
static void emitConstant (Compiler * compiler, Value value) static
Definition at line 1371 of file wren_compiler.c.
 {
   int constant = addConstant(compiler, value);
   // Compile the code to load the constant.
   emitShortArg(compiler, CODE_CONSTANT, constant);
 }
References addConstant(), and emitShortArg().
Referenced by classDefinition(), emitAttributeMethods(), emitAttributes(), literal(), and method().
emitJump()
static int emitJump (Compiler * compiler, Code instruction) static
Definition at line 1362 of file wren_compiler.c.
 {
   emitOp(compiler, instruction);
   emitByte(compiler, 0xff);
   return emitByte(compiler, 0xff) - 1;
 }
References emitByte(), and emitOp().
Referenced by and_(), conditional(), ifStatement(), or_(), statement(), and testExitLoop().
emitOp()
static void emitOp (Compiler * compiler, Code instruction) static
Definition at line 1324 of file wren_compiler.c.
 {
   emitByte(compiler, instruction);
   // Keep track of the stack's high water mark.
   compiler->numSlots += stackEffects[instruction];
   if (compiler->numSlots > compiler->fn->maxSlots)
   {
     compiler->fn->maxSlots = compiler->numSlots;
   }
 }
References emitByte(), and stackEffects.
Referenced by boolean(), classDefinition(), createConstructor(), defineVariable(), emitByteArg(), emitJump(), emitShortArg(), endCompiler(), finishBody(), import(), loadLocal(), null(), statement(), staticField(), and wrenCompile().
emitShort()
static void emitShort (Compiler * compiler, int arg) static
Definition at line 1337 of file wren_compiler.c.
 {
   emitByte(compiler, (arg >> 8) & 0xff);
   emitByte(compiler, arg & 0xff);
 }
References emitByte().
Referenced by callSignature(), and emitShortArg().
emitShortArg()
static void emitShortArg (Compiler * compiler, Code instruction, int arg) static
Definition at line 1353 of file wren_compiler.c.
 {
   emitOp(compiler, instruction);
   emitShort(compiler, arg);
 }
References emitOp(), and emitShort().
Referenced by bareName(), callMethod(), callSignature(), createConstructor(), defineMethod(), defineVariable(), emitConstant(), endCompiler(), endLoop(), import(), loadCoreVariable(), loadVariable(), and statement().
endCompiler()
static ObjFn* endCompiler (Compiler * compiler, const char * debugName, int debugNameLength) static
Definition at line 1661 of file wren_compiler.c.
 {
   // If we hit an error, don't finish the function since it's borked anyway.
   if (compiler->parser->hasError)
   {
     compiler->parser->vm->compiler = compiler->parent;
     return NULL;
   }
   // Mark the end of the bytecode. Since it may contain multiple early returns,
   // we can't rely on CODE_RETURN to tell us we're at the end.
   emitOp(compiler, CODE_END);
   wrenFunctionBindName(compiler->parser->vm, compiler->fn,
                        debugName, debugNameLength);
   // In the function that contains this one, load the resulting function object.
   if (compiler->parent != NULL)
   {
     int constant = addConstant(compiler->parent, OBJ_VAL(compiler->fn));
     // Wrap the function in a closure. We do this even if it has no upvalues so
     // that the VM can uniformly assume all called objects are closures. This
     // makes creating a function a little slower, but makes invoking them
     // faster. Given that functions are invoked more often than they are
     // created, this is a win.
     emitShortArg(compiler->parent, CODE_CLOSURE, constant);
     // Emit arguments for each upvalue to know whether to capture a local or
     // an upvalue.
     for (int i = 0; i < compiler->fn->numUpvalues; i++)
     {
       emitByte(compiler->parent, compiler->upvalues[i].isLocal ? 1 : 0);
       emitByte(compiler->parent, compiler->upvalues[i].index);
     }
   }
   // Pop this compiler off the stack.
   compiler->parser->vm->compiler = compiler->parent;
   #if WREN_DEBUG_DUMP_COMPILED_CODE
     wrenDumpCode(compiler->parser->vm, compiler->fn);
   #endif
   return compiler->fn;
 }
References addConstant(), emitByte(), emitOp(), emitShortArg(), NULL, OBJ_VAL, wrenDumpCode(), and wrenFunctionBindName().
Referenced by createConstructor(), method(), methodCall(), and wrenCompile().
endLoop()
static void endLoop (Compiler * compiler) static
Definition at line 2994 of file wren_compiler.c.
 {
   // We don't check for overflow here since the forward jump over the loop body
   // will report an error for the same problem.
   int loopOffset = compiler->fn->code.count - compiler->loop->start + 2;
   emitShortArg(compiler, CODE_LOOP, loopOffset);
   patchJump(compiler, compiler->loop->exitJump);
   // Find any break placeholder instructions (which will be CODE_END in the
   // bytecode) and replace them with real jumps.
   int i = compiler->loop->body;
   while (i < compiler->fn->code.count)
   {
     if (compiler->fn->code.data[i] == CODE_END)
     {
       compiler->fn->code.data[i] = CODE_JUMP;
       patchJump(compiler, i + 1);
       i += 3;
     }
     else
     {
       // Skip this instruction and its arguments.
       i += 1 + getByteCountForArguments(compiler->fn->code.data,
                                compiler->fn->constants.data, i);
     }
   }
   compiler->loop = compiler->loop->enclosing;
 }
References emitShortArg(), fn, getByteCountForArguments(), and patchJump().
Referenced by forStatement(), and whileStatement().
error()
static void error (Compiler * compiler, const char * format, ...) static
Definition at line 459 of file wren_compiler.c.
 {
   Token* token = &compiler->parser->previous;
   // If the parse error was caused by an error token, the lexer has already
   // reported it.
   if (token->type == TOKEN_ERROR) return;
   va_list args;
   va_start(args, format);
   if (token->type == TOKEN_LINE)
   {
     printError(compiler->parser, token->line, "Error at newline", format, args);
   }
   else if (token->type == TOKEN_EOF)
   {
     printError(compiler->parser, token->line,
                "Error at end of file", format, args);
   }
   else
   {
     // Make sure we don't exceed the buffer with a very long token.
     char label[10 + MAX_VARIABLE_NAME + 4 + 1];
     if (token->length <= MAX_VARIABLE_NAME)
     {
       sprintf(label, "Error at '%.*s'", token->length, token->start);
     }
     else
     {
       sprintf(label, "Error at '%.*s...'", MAX_VARIABLE_NAME, token->start);
     }
     printError(compiler->parser, token->line, label, format, args);
   }
   va_end(args);
 }
References MAX_VARIABLE_NAME, printError(), token, TOKEN_EOF, TOKEN_ERROR, and TOKEN_LINE.
Referenced by addConstant(), constructorSignature(), consume(), consumeLiteral(), declareMethod(), declareVariable(), disallowAttributes(), field(), forStatement(), matchAttribute(), method(), methodCall(), name(), parsePrecedence(), patchJump(), signatureFromToken(), statement(), staticField(), super_(), this_(), validateNumParameters(), and wrenCompile().
expression()
void expression (Compiler * compiler) static
Definition at line 2855 of file wren_compiler.c.
 {
   parsePrecedence(compiler, PREC_LOWEST);
 }
References parsePrecedence(), and PREC_LOWEST.
Referenced by bareName(), field(), finishArgumentList(), finishBlock(), forStatement(), grouping(), ifStatement(), list(), map(), namedCall(), statement(), stringInterpolation(), subscript(), variableDefinition(), whileStatement(), and wrenCompile().
field()
static void field (Compiler * compiler, bool canAssign) static
Definition at line 2242 of file wren_compiler.c.
 {
   // Initialize it with a fake value so we can keep parsing and minimize the
   // number of cascaded errors.
   int field = MAX_FIELDS;
   ClassInfo* enclosingClass = getEnclosingClass(compiler);
   if (enclosingClass == NULL)
   {
     error(compiler, "Cannot reference a field outside of a class definition.");
   }
   else if (enclosingClass->isForeign)
   {
     error(compiler, "Cannot define fields in a foreign class.");
   }
   else if (enclosingClass->inStatic)
   {
     error(compiler, "Cannot use an instance field in a static method.");
   }
   else
   {
     // Look up the field, or implicitly define it.
     field = wrenSymbolTableEnsure(compiler->parser->vm, &enclosingClass->fields,
         compiler->parser->previous.start,
         compiler->parser->previous.length);
     if (field >= MAX_FIELDS)
     {
       error(compiler, "A class can only have %d fields.", MAX_FIELDS);
     }
   }
   // If there's an "=" after a field name, it's an assignment.
   bool isLoad = true;
   if (canAssign && match(compiler, TOKEN_EQ))
   {
     // Compile the right-hand side.
     expression(compiler);
     isLoad = false;
   }
   // If we're directly inside a method, use a more optimal instruction.
   if (compiler->parent != NULL &&
       compiler->parent->enclosingClass == enclosingClass)
   {
     emitByteArg(compiler, isLoad ? CODE_LOAD_FIELD_THIS : CODE_STORE_FIELD_THIS,
                 field);
   }
   else
   {
     loadThis(compiler);
     emitByteArg(compiler, isLoad ? CODE_LOAD_FIELD : CODE_STORE_FIELD, field);
   }
   allowLineBeforeDot(compiler);
 }
References allowLineBeforeDot(), emitByteArg(), error(), expression(), getEnclosingClass(), loadThis(), match(), MAX_FIELDS, NULL, TOKEN_EQ, and wrenSymbolTableEnsure().
Referenced by runInterpreter().
findUpvalue()
static int findUpvalue (Compiler * compiler, const char * name, int length) static
Definition at line 1577 of file wren_compiler.c.
 {
   // If we are at the top level, we didn't find it.
   if (compiler->parent == NULL) return -1;
   // If we hit the method boundary (and the name isn't a static field), then
   // stop looking for it. We'll instead treat it as a self send.
   if (name[0] != '_' && compiler->parent->enclosingClass != NULL) return -1;
   // See if it's a local variable in the immediately enclosing function.
   int local = resolveLocal(compiler->parent, name, length);
   if (local != -1)
   {
     // Mark the local as an upvalue so we know to close it when it goes out of
     // scope.
     compiler->parent->locals[local].isUpvalue = true;
     return addUpvalue(compiler, true, local);
   }
   // See if it's an upvalue in the immediately enclosing function. In other
   // words, if it's a local variable in a non-immediately enclosing function.
   // This "flattens" closures automatically: it adds upvalues to all of the
   // intermediate functions to get from the function where a local is declared
   // all the way into the possibly deeply nested function that is closing over
   // it.
   int upvalue = findUpvalue(compiler->parent, name, length);
   if (upvalue != -1)
   {
     return addUpvalue(compiler, false, upvalue);
   }
   // If we got here, we walked all the way up the parent chain and couldn't
   // find it.
   return -1;
 }
References addUpvalue(), name(), NULL, and resolveLocal().
Referenced by resolveNonmodule().
finishArgumentList()
static void finishArgumentList (Compiler * compiler, Signature * signature) static
Definition at line 1959 of file wren_compiler.c.
 {
   do
   {
     ignoreNewlines(compiler);
     validateNumParameters(compiler, ++signature->arity);
     expression(compiler);
   }
   while (match(compiler, TOKEN_COMMA));
   // Allow a newline before the closing delimiter.
   ignoreNewlines(compiler);
 }
References expression(), ignoreNewlines(), match(), TOKEN_COMMA, and validateNumParameters().
Referenced by methodCall(), and subscript().
finishBlock()
static bool finishBlock (Compiler * compiler) static
Definition at line 1771 of file wren_compiler.c.
 {
   // Empty blocks do nothing.
   if (match(compiler, TOKEN_RIGHT_BRACE)) return false;
   // If there's no line after the "{", it's a single-expression body.
   if (!matchLine(compiler))
   {
     expression(compiler);
     consume(compiler, TOKEN_RIGHT_BRACE, "Expect '}' at end of block.");
     return true;
   }
   // Empty blocks (with just a newline inside) do nothing.
   if (match(compiler, TOKEN_RIGHT_BRACE)) return false;
   // Compile the definition list.
   do
   {
     definition(compiler);
     consumeLine(compiler, "Expect newline after statement.");
   }
   while (peek(compiler) != TOKEN_RIGHT_BRACE && peek(compiler) != TOKEN_EOF);
   consume(compiler, TOKEN_RIGHT_BRACE, "Expect '}' at end of block.");
   return false;
 }
References consume(), consumeLine(), definition(), expression(), match(), matchLine(), peek(), TOKEN_EOF, and TOKEN_RIGHT_BRACE.
Referenced by finishBody(), and statement().
finishBody()
static void finishBody (Compiler * compiler) static
Definition at line 1803 of file wren_compiler.c.
 {
   bool isExpressionBody = finishBlock(compiler);
   if (compiler->isInitializer)
   {
     // If the initializer body evaluates to a value, discard it.
     if (isExpressionBody) emitOp(compiler, CODE_POP);
     // The receiver is always stored in the first local slot.
     emitOp(compiler, CODE_LOAD_LOCAL_0);
   }
   else if (!isExpressionBody)
   {
     // Implicitly return null in statement bodies.
     emitOp(compiler, CODE_NULL);
   }
   emitOp(compiler, CODE_RETURN);
 }
References emitOp(), and finishBlock().
Referenced by method(), and methodCall().
finishParameterList()
static void finishParameterList (Compiler * compiler, Signature * signature) static
Definition at line 1839 of file wren_compiler.c.
 {
   do
   {
     ignoreNewlines(compiler);
     validateNumParameters(compiler, ++signature->arity);
     // Define a local variable in the method for the parameter.
     declareNamedVariable(compiler);
   }
   while (match(compiler, TOKEN_COMMA));
 }
References declareNamedVariable(), ignoreNewlines(), match(), TOKEN_COMMA, and validateNumParameters().
Referenced by constructorSignature(), methodCall(), parameterList(), and subscriptSignature().
forStatement()
static void forStatement (Compiler * compiler) static
Definition at line 3025 of file wren_compiler.c.
 {
   // A for statement like:
   //
   //     for (i in sequence.expression) {
   //       System.print(i)
   //     }
   //
   // Is compiled to bytecode almost as if the source looked like this:
   //
   //     {
   //       var seq_ = sequence.expression
   //       var iter_
   //       while (iter_ = seq_.iterate(iter_)) {
   //         var i = seq_.iteratorValue(iter_)
   //         System.print(i)
   //       }
   //     }
   //
   // It's not exactly this, because the synthetic variables `seq_` and `iter_`
   // actually get names that aren't valid Wren identfiers, but that's the basic
   // idea.
   //
   // The important parts are:
   // - The sequence expression is only evaluated once.
   // - The .iterate() method is used to advance the iterator and determine if
   //   it should exit the loop.
   // - The .iteratorValue() method is used to get the value at the current
   //   iterator position.
   // Create a scope for the hidden local variables used for the iterator.
   pushScope(compiler);
   consume(compiler, TOKEN_LEFT_PAREN, "Expect '(' after 'for'.");
   consume(compiler, TOKEN_NAME, "Expect for loop variable name.");
   // Remember the name of the loop variable.
   const char* name = compiler->parser->previous.start;
   int length = compiler->parser->previous.length;
   consume(compiler, TOKEN_IN, "Expect 'in' after loop variable.");
   ignoreNewlines(compiler);
   // Evaluate the sequence expression and store it in a hidden local variable.
   // The space in the variable name ensures it won't collide with a user-defined
   // variable.
   expression(compiler);
   // Verify that there is space to hidden local variables.
   // Note that we expect only two addLocal calls next to each other in the
   // following code.
   if (compiler->numLocals + 2 > MAX_LOCALS)
   {
     error(compiler, "Cannot declare more than %d variables in one scope. (Not enough space for for-loops internal variables)",
           MAX_LOCALS);
     return;
   }
   int seqSlot = addLocal(compiler, "seq ", 4);
   // Create another hidden local for the iterator object.
   null(compiler, false);
   int iterSlot = addLocal(compiler, "iter ", 5);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after loop expression.");
   Loop loop;
   startLoop(compiler, &loop);
   // Advance the iterator by calling the ".iterate" method on the sequence.
   loadLocal(compiler, seqSlot);
   loadLocal(compiler, iterSlot);
   // Update and test the iterator.
   callMethod(compiler, 1, "iterate(_)", 10);
   emitByteArg(compiler, CODE_STORE_LOCAL, iterSlot);
   testExitLoop(compiler);
   // Get the current value in the sequence by calling ".iteratorValue".
   loadLocal(compiler, seqSlot);
   loadLocal(compiler, iterSlot);
   callMethod(compiler, 1, "iteratorValue(_)", 16);
   // Bind the loop variable in its own scope. This ensures we get a fresh
   // variable each iteration so that closures for it don't all see the same one.
   pushScope(compiler);
   addLocal(compiler, name, length);
   loopBody(compiler);
   // Loop variable.
   popScope(compiler);
   endLoop(compiler);
   // Hidden variables.
   popScope(compiler);
 }
References addLocal(), callMethod(), consume(), emitByteArg(), endLoop(), error(), expression(), ignoreNewlines(), loadLocal(), loop(), loopBody(), MAX_LOCALS, name(), popScope(), pushScope(), startLoop(), testExitLoop(), TOKEN_IN, TOKEN_LEFT_PAREN, TOKEN_NAME, and TOKEN_RIGHT_PAREN.
Referenced by statement().
getByteCountForArguments()
static int getByteCountForArguments (const uint8_t * bytecode, const Value * constants, int ip) static
Definition at line 2862 of file wren_compiler.c.
 {
   Code instruction = (Code)bytecode[ip];
   switch (instruction)
   {
     case CODE_NULL:
     case CODE_FALSE:
     case CODE_TRUE:
     case CODE_POP:
     case CODE_CLOSE_UPVALUE:
     case CODE_RETURN:
     case CODE_END:
     case CODE_LOAD_LOCAL_0:
     case CODE_LOAD_LOCAL_1:
     case CODE_LOAD_LOCAL_2:
     case CODE_LOAD_LOCAL_3:
     case CODE_LOAD_LOCAL_4:
     case CODE_LOAD_LOCAL_5:
     case CODE_LOAD_LOCAL_6:
     case CODE_LOAD_LOCAL_7:
     case CODE_LOAD_LOCAL_8:
     case CODE_CONSTRUCT:
     case CODE_FOREIGN_CONSTRUCT:
     case CODE_FOREIGN_CLASS:
     case CODE_END_MODULE:
     case CODE_END_CLASS:
       return 0;
     case CODE_LOAD_LOCAL:
     case CODE_STORE_LOCAL:
     case CODE_LOAD_UPVALUE:
     case CODE_STORE_UPVALUE:
     case CODE_LOAD_FIELD_THIS:
     case CODE_STORE_FIELD_THIS:
     case CODE_LOAD_FIELD:
     case CODE_STORE_FIELD:
     case CODE_CLASS:
       return 1;
     case CODE_CONSTANT:
     case CODE_LOAD_MODULE_VAR:
     case CODE_STORE_MODULE_VAR:
     case CODE_CALL_0:
     case CODE_CALL_1:
     case CODE_CALL_2:
     case CODE_CALL_3:
     case CODE_CALL_4:
     case CODE_CALL_5:
     case CODE_CALL_6:
     case CODE_CALL_7:
     case CODE_CALL_8:
     case CODE_CALL_9:
     case CODE_CALL_10:
     case CODE_CALL_11:
     case CODE_CALL_12:
     case CODE_CALL_13:
     case CODE_CALL_14:
     case CODE_CALL_15:
     case CODE_CALL_16:
     case CODE_JUMP:
     case CODE_LOOP:
     case CODE_JUMP_IF:
     case CODE_AND:
     case CODE_OR:
     case CODE_METHOD_INSTANCE:
     case CODE_METHOD_STATIC:
     case CODE_IMPORT_MODULE:
     case CODE_IMPORT_VARIABLE:
       return 2;
     case CODE_SUPER_0:
     case CODE_SUPER_1:
     case CODE_SUPER_2:
     case CODE_SUPER_3:
     case CODE_SUPER_4:
     case CODE_SUPER_5:
     case CODE_SUPER_6:
     case CODE_SUPER_7:
     case CODE_SUPER_8:
     case CODE_SUPER_9:
     case CODE_SUPER_10:
     case CODE_SUPER_11:
     case CODE_SUPER_12:
     case CODE_SUPER_13:
     case CODE_SUPER_14:
     case CODE_SUPER_15:
     case CODE_SUPER_16:
       return 4;
     case CODE_CLOSURE:
     {
       int constant = (bytecode[ip + 1] << 8) | bytecode[ip + 2];
       ObjFn* loadedFn = AS_FN(constants[constant]);
       // There are two bytes for the constant, then two for each upvalue.
       return 2 + (loadedFn->numUpvalues * 2);
     }
   }
   UNREACHABLE();
   return 0;
 }
References AS_FN, ObjFn::numUpvalues, and UNREACHABLE.
Referenced by endLoop(), and wrenBindMethodCode().
getEnclosingClass()
static ClassInfo* getEnclosingClass (Compiler * compiler) static
Definition at line 2236 of file wren_compiler.c.
 {
   compiler = getEnclosingClassCompiler(compiler);
   return compiler == NULL ? NULL : compiler->enclosingClass;
 }
References getEnclosingClassCompiler(), and NULL.
Referenced by field(), name(), super_(), and this_().
getEnclosingClassCompiler()
static Compiler* getEnclosingClassCompiler (Compiler * compiler) static
Definition at line 2223 of file wren_compiler.c.
 {
   while (compiler != NULL)
   {
     if (compiler->enclosingClass != NULL) return compiler;
     compiler = compiler->parent;
   }
   return NULL;
 }
References NULL.
Referenced by getEnclosingClass(), and staticField().
getRule()
static GrammarRule * getRule (TokenType type) static
Definition at line 2818 of file wren_compiler.c.
 {
   return &rules[type];
 }
References rules.
Referenced by infixOp(), and unaryOp().
grouping()
static void grouping (Compiler * compiler, bool canAssign) static
Definition at line 2139 of file wren_compiler.c.
 {
   expression(compiler);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after expression.");
 }
References consume(), expression(), and TOKEN_RIGHT_PAREN.
ifStatement()
static void ifStatement (Compiler * compiler) static
Definition at line 3123 of file wren_compiler.c.
 {
   // Compile the condition.
   consume(compiler, TOKEN_LEFT_PAREN, "Expect '(' after 'if'.");
   expression(compiler);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after if condition.");
   // Jump to the else branch if the condition is false.
   int ifJump = emitJump(compiler, CODE_JUMP_IF);
   // Compile the then branch.
   statement(compiler);
   // Compile the else branch if there is one.
   if (match(compiler, TOKEN_ELSE))
   {
     // Jump over the else branch when the if branch is taken.
     int elseJump = emitJump(compiler, CODE_JUMP);
     patchJump(compiler, ifJump);
     statement(compiler);
     // Patch the jump over the else.
     patchJump(compiler, elseJump);
   }
   else
   {
     patchJump(compiler, ifJump);
   }
 }
References consume(), emitJump(), expression(), match(), patchJump(), statement(), TOKEN_ELSE, TOKEN_LEFT_PAREN, and TOKEN_RIGHT_PAREN.
Referenced by statement().
ignoreNewlines()
static void ignoreNewlines (Compiler * compiler) static
Definition at line 1290 of file wren_compiler.c.
 {
   matchLine(compiler);
 }
References matchLine().
Referenced by and_(), call(), conditional(), consumeLine(), finishArgumentList(), finishParameterList(), forStatement(), import(), infixOp(), list(), map(), matchAttribute(), methodCall(), namedCall(), or_(), parameterList(), stringInterpolation(), unaryOp(), variableDefinition(), and wrenCompile().
import()
static void import (Compiler * compiler) static
Definition at line 3643 of file wren_compiler.c.
 {
   ignoreNewlines(compiler);
   consume(compiler, TOKEN_STRING, "Expect a string after 'import'.");
   int moduleConstant = addConstant(compiler, compiler->parser->previous.value);
   // Load the module.
   emitShortArg(compiler, CODE_IMPORT_MODULE, moduleConstant);
   // Discard the unused result value from calling the module body's closure.
   emitOp(compiler, CODE_POP);
   // The for clause is optional.
   if (!match(compiler, TOKEN_FOR)) return;
   // Compile the comma-separated list of variables to import.
   do
   {
     ignoreNewlines(compiler);
     consume(compiler, TOKEN_NAME, "Expect variable name.");
     // We need to hold onto the source variable,
     // in order to reference it in the import later
     Token sourceVariableToken = compiler->parser->previous;
     // Define a string constant for the original variable name.
     int sourceVariableConstant = addConstant(compiler,
           wrenNewStringLength(compiler->parser->vm,
                         sourceVariableToken.start,
                         sourceVariableToken.length));
     // Store the symbol we care about for the variable
     int slot = -1;
     if(match(compiler, TOKEN_AS))
     {
       //import "module" for Source as Dest
       //Use 'Dest' as the name by declaring a new variable for it.
       //This parses a name after the 'as' and defines it.
       slot = declareNamedVariable(compiler);
     }
     else
     {
       //import "module" for Source
       //Uses 'Source' as the name directly
       slot = declareVariable(compiler, &sourceVariableToken);
     }
     // Load the variable from the other module.
     emitShortArg(compiler, CODE_IMPORT_VARIABLE, sourceVariableConstant);
     // Store the result in the variable here.
     defineVariable(compiler, slot);
   } while (match(compiler, TOKEN_COMMA));
 }
References addConstant(), consume(), declareNamedVariable(), declareVariable(), defineVariable(), emitOp(), emitShortArg(), ignoreNewlines(), match(), TOKEN_AS, TOKEN_COMMA, TOKEN_FOR, TOKEN_NAME, TOKEN_STRING, and wrenNewStringLength().
infixOp()
void infixOp (Compiler * compiler, bool canAssign)
Definition at line 2583 of file wren_compiler.c.
 {
   GrammarRule* rule = getRule(compiler->parser->previous.type);
   // An infix operator cannot end an expression.
   ignoreNewlines(compiler);
   // Compile the right-hand side.
   parsePrecedence(compiler, (Precedence)(rule->precedence + 1));
   // Call the operator method on the left-hand side.
   Signature signature = { rule->name, (int)strlen(rule->name), SIG_METHOD, 1 };
   callSignature(compiler, CODE_CALL_0, &signature);
 }
References callSignature(), getRule(), ignoreNewlines(), parsePrecedence(), and SIG_METHOD.
infixSignature()
void infixSignature (Compiler * compiler, Signature * signature)
Definition at line 2599 of file wren_compiler.c.
 {
   // Add the RHS parameter.
   signature->type = SIG_METHOD;
   signature->arity = 1;
   // Parse the parameter name.
   consume(compiler, TOKEN_LEFT_PAREN, "Expect '(' after operator name.");
   declareNamedVariable(compiler);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after parameter name.");
 }
References consume(), declareNamedVariable(), SIG_METHOD, TOKEN_LEFT_PAREN, and TOKEN_RIGHT_PAREN.
initCompiler()
static void initCompiler (Compiler * compiler, Parser * parser, Compiler * parent, bool isMethod) static
Definition at line 532 of file wren_compiler.c.
 {
   compiler->parser = parser;
   compiler->parent = parent;
   compiler->loop = NULL;
   compiler->enclosingClass = NULL;
   compiler->isInitializer = false;
   // Initialize these to NULL before allocating in case a GC gets triggered in
   // the middle of initializing the compiler.
   compiler->fn = NULL;
   compiler->constants = NULL;
   compiler->attributes = NULL;
   parser->vm->compiler = compiler;
   // Declare a local slot for either the closure or method receiver so that we
   // don't try to reuse that slot for a user-defined local variable. For
   // methods, we name it "this", so that we can resolve references to that like
   // a normal variable. For functions, they have no explicit "this", so we use
   // an empty name. That way references to "this" inside a function walks up
   // the parent chain to find a method enclosing the function whose "this" we
   // can close over.
   compiler->numLocals = 1;
   compiler->numSlots = compiler->numLocals;
   if (isMethod)
   {
     compiler->locals[0].name = "this";
     compiler->locals[0].length = 4;
   }
   else
   {
     compiler->locals[0].name = NULL;
     compiler->locals[0].length = 0;
   }
   compiler->locals[0].depth = -1;
   compiler->locals[0].isUpvalue = false;
   if (parent == NULL)
   {
     // Compiling top-level code, so the initial scope is module-level.
     compiler->scopeDepth = -1;
   }
   else
   {
     // The initial scope for functions and methods is local scope.
     compiler->scopeDepth = 0;
   }
   compiler->numAttributes = 0;
   compiler->attributes = wrenNewMap(parser->vm);
   compiler->fn = wrenNewFunction(parser->vm, parser->module,
                                  compiler->numLocals);
 }
References NULL, wrenNewFunction(), and wrenNewMap().
Referenced by createConstructor(), method(), methodCall(), and wrenCompile().
isDigit()
static bool isDigit (char c) static
Definition at line 633 of file wren_compiler.c.
 {
   return c >= '0' && c <= '9';
 }
Referenced by nextToken(), readName(), and readNumber().
isName()
static bool isName (char c) static
Definition at line 627 of file wren_compiler.c.
 {
   return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_';
 }
Referenced by nextToken(), and readName().
lexError()
static void lexError (Parser * parser, const char * format, ...) static
Definition at line 443 of file wren_compiler.c.
 {
   va_list args;
   va_start(args, format);
   printError(parser, parser->currentLine, "Error", format, args);
   va_end(args);
 }
References printError().
Referenced by makeNumber(), nextToken(), readHexEscape(), readNumber(), readRawString(), readString(), and skipBlockComment().
list()
static void list (Compiler * compiler, bool canAssign) static
Definition at line 2146 of file wren_compiler.c.
 {
   // Instantiate a new list.
   loadCoreVariable(compiler, "List");
   callMethod(compiler, 0, "new()", 5);
   // Compile the list elements. Each one compiles to a ".add()" call.
   do
   {
     ignoreNewlines(compiler);
     // Stop if we hit the end of the list.
     if (peek(compiler) == TOKEN_RIGHT_BRACKET) break;
     // The element.
     expression(compiler);
     callMethod(compiler, 1, "addCore_(_)", 11);
   } while (match(compiler, TOKEN_COMMA));
   // Allow newlines before the closing ']'.
   ignoreNewlines(compiler);
   consume(compiler, TOKEN_RIGHT_BRACKET, "Expect ']' after list elements.");
 }
References callMethod(), consume(), expression(), ignoreNewlines(), loadCoreVariable(), match(), peek(), TOKEN_COMMA, and TOKEN_RIGHT_BRACKET.
Referenced by blackenList(), cpplint::CheckEmptyBlockBody(), DEF_PRIMITIVE(), wrenInsertInList(), wrenListIndexOf(), wrenListInsert(), wrenListRemoveAt(), wrenNewList(), and wrenSetListElement().
literal()
static void literal (Compiler * compiler, bool canAssign) static
Definition at line 2421 of file wren_compiler.c.
 {
   emitConstant(compiler, compiler->parser->previous.value);
 }
References emitConstant().
Referenced by stringInterpolation().
loadCoreVariable()
static void loadCoreVariable (Compiler * compiler, const char * name) static
Definition at line 2130 of file wren_compiler.c.
 {
   int symbol = wrenSymbolTableFind(&compiler->parser->module->variableNames,
                                    name, strlen(name));
   ASSERT(symbol != -1, "Should have already defined core name.");
   emitShortArg(compiler, CODE_LOAD_MODULE_VAR, symbol);
 }
References ASSERT, emitShortArg(), name(), and wrenSymbolTableFind().
Referenced by classDefinition(), emitAttributeMethods(), emitAttributes(), emitClassAttributes(), list(), map(), and stringInterpolation().
loadLocal()
static void loadLocal (Compiler * compiler, int slot) static
Definition at line 1647 of file wren_compiler.c.
 {
   if (slot <= 8)
   {
     emitOp(compiler, (Code)(CODE_LOAD_LOCAL_0 + slot));
     return;
   }
   emitByteArg(compiler, CODE_LOAD_LOCAL, slot);
 }
References emitByteArg(), and emitOp().
Referenced by forStatement(), and loadVariable().
loadThis()
static void loadThis (Compiler * compiler) static
Definition at line 2124 of file wren_compiler.c.
 {
   loadVariable(compiler, resolveNonmodule(compiler, "this", 4));
 }
References loadVariable(), and resolveNonmodule().
Referenced by field(), name(), super_(), and this_().
loadVariable()
static void loadVariable (Compiler * compiler, Variable variable) static
Definition at line 2104 of file wren_compiler.c.
 {
   switch (variable.scope)
   {
     case SCOPE_LOCAL:
       loadLocal(compiler, variable.index);
       break;
     case SCOPE_UPVALUE:
       emitByteArg(compiler, CODE_LOAD_UPVALUE, variable.index);
       break;
     case SCOPE_MODULE:
       emitShortArg(compiler, CODE_LOAD_MODULE_VAR, variable.index);
       break;
     default:
       UNREACHABLE();
   }
 }
References emitByteArg(), emitShortArg(), loadLocal(), SCOPE_LOCAL, SCOPE_MODULE, SCOPE_UPVALUE, and UNREACHABLE.
Referenced by bareName(), classDefinition(), defineMethod(), and loadThis().
loopBody()
static void loopBody (Compiler * compiler) static
Definition at line 2986 of file wren_compiler.c.
 {
   compiler->loop->body = compiler->fn->code.count;
   statement(compiler);
 }
References statement().
Referenced by forStatement(), and whileStatement().
makeNumber()
static void makeNumber (Parser * parser, bool isHex) static
Definition at line 747 of file wren_compiler.c.
 {
   errno = 0;
   if (isHex)
   {
     parser->next.value = NUM_VAL((double)strtoll(parser->tokenStart, NULL, 16));
   }
   else
   {
     parser->next.value = NUM_VAL(strtod(parser->tokenStart, NULL));
   }
   if (errno == ERANGE)
   {
     lexError(parser, "Number literal was too large (%d).", sizeof(long int));
     parser->next.value = NUM_VAL(0);
   }
   // We don't check that the entire token is consumed after calling strtoll()
   // or strtod() because we've already scanned it ourselves and know it's valid.
   makeToken(parser, TOKEN_NUMBER);
 }
References lexError(), makeToken(), NULL, NUM_VAL, and TOKEN_NUMBER.
Referenced by readHexNumber(), and readNumber().
makeToken()
static void makeToken (Parser * parser, TokenType type) static
Definition at line 671 of file wren_compiler.c.
 {
   parser->next.type = type;
   parser->next.start = parser->tokenStart;
   parser->next.length = (int)(parser->currentChar - parser->tokenStart);
   parser->next.line = parser->currentLine;
   // Make line tokens appear on the line containing the "\n".
   if (type == TOKEN_LINE) parser->next.line--;
 }
References TOKEN_LINE.
Referenced by makeNumber(), nextToken(), readName(), readRawString(), readString(), and twoCharToken().
map()
static void map (Compiler * compiler, bool canAssign) static
Definition at line 2171 of file wren_compiler.c.
 {
   // Instantiate a new map.
   loadCoreVariable(compiler, "Map");
   callMethod(compiler, 0, "new()", 5);
   // Compile the map elements. Each one is compiled to just invoke the
   // subscript setter on the map.
   do
   {
     ignoreNewlines(compiler);
     // Stop if we hit the end of the map.
     if (peek(compiler) == TOKEN_RIGHT_BRACE) break;
     // The key.
     parsePrecedence(compiler, PREC_UNARY);
     consume(compiler, TOKEN_COLON, "Expect ':' after map key.");
     ignoreNewlines(compiler);
     // The value.
     expression(compiler);
     callMethod(compiler, 2, "addCore_(_,_)", 13);
   } while (match(compiler, TOKEN_COMMA));
   // Allow newlines before the closing '}'.
   ignoreNewlines(compiler);
   consume(compiler, TOKEN_RIGHT_BRACE, "Expect '}' after map entries.");
 }
References callMethod(), consume(), expression(), ignoreNewlines(), loadCoreVariable(), match(), parsePrecedence(), peek(), PREC_UNARY, TOKEN_COLON, TOKEN_COMMA, and TOKEN_RIGHT_BRACE.
Referenced by blackenMap(), DEF_PRIMITIVE(), resizeMap(), wrenGetMapContainsKey(), wrenGetMapCount(), wrenGetMapValue(), wrenMapClear(), wrenMapGet(), wrenMapRemoveKey(), wrenMapSet(), wrenNewMap(), wrenRemoveMapValue(), and wrenSetMapValue().
match()
static bool match (Compiler * compiler, TokenType expected) static
Definition at line 1257 of file wren_compiler.c.
 {
   if (peek(compiler) != expected) return false;
   nextToken(compiler->parser);
   return true;
 }
References nextToken(), and peek().
Referenced by bareName(), classDefinition(), constructorSignature(), consumeLiteral(), definition(), field(), finishArgumentList(), finishBlock(), finishParameterList(), ifStatement(), import(), list(), LZ4_compress_generic_validated(), LZ4_decompress_generic(), map(), cpplint::Match(), matchAttribute(), matchLine(), maybeSetter(), method(), methodCall(), mixedSignature(), namedCall(), parameterList(), statement(), stringInterpolation(), subscript(), super_(), variableDefinition(), and wrenCompile().
matchAttribute()
static bool matchAttribute (Compiler * compiler) static
Definition at line 3357 of file wren_compiler.c.
{
   if(match(compiler, TOKEN_HASH))
   {
     compiler->numAttributes++;
     bool runtimeAccess = match(compiler, TOKEN_BANG);
     if(match(compiler, TOKEN_NAME))
     {
       Value group = compiler->parser->previous.value;
       TokenType ahead = peek(compiler);
       if(ahead == TOKEN_EQ || ahead == TOKEN_LINE)
       {
         Value key = group;
         Value value = NULL_VAL;
         if(match(compiler, TOKEN_EQ))
         {
           value = consumeLiteral(compiler, "Expect a Bool, Num, String or Identifier literal for an attribute value.");
         }
         if(runtimeAccess) addToAttributeGroup(compiler, NULL_VAL, key, value);
       }
       else if(match(compiler, TOKEN_LEFT_PAREN))
       {
         ignoreNewlines(compiler);
         if(match(compiler, TOKEN_RIGHT_PAREN))
         {
           error(compiler, "Expected attributes in group, group cannot be empty.");
         }
         else
         {
           while(peek(compiler) != TOKEN_RIGHT_PAREN)
           {
             consume(compiler, TOKEN_NAME, "Expect name for attribute key.");
             Value key = compiler->parser->previous.value;
             Value value = NULL_VAL;
             if(match(compiler, TOKEN_EQ))
             {
               value = consumeLiteral(compiler, "Expect a Bool, Num, String or Identifier literal for an attribute value.");
             }
             if(runtimeAccess) addToAttributeGroup(compiler, group, key, value);
             ignoreNewlines(compiler);
             if(!match(compiler, TOKEN_COMMA)) break;
             ignoreNewlines(compiler);
           }
           ignoreNewlines(compiler);
           consume(compiler, TOKEN_RIGHT_PAREN,
             "Expected ')' after grouped attributes.");
         }
       }
       else
       {
         error(compiler, "Expect an equal, newline or grouping after an attribute key.");
       }
     }
     else
     {
       error(compiler, "Expect an attribute definition after #.");
     }
     consumeLine(compiler, "Expect newline after attribute.");
     return true;
   }
   return false;
 }
References addToAttributeGroup(), consume(), consumeLine(), consumeLiteral(), error(), ignoreNewlines(), match(), NULL_VAL, peek(), TOKEN_BANG, TOKEN_COMMA, TOKEN_EQ, TOKEN_HASH, TOKEN_LEFT_PAREN, TOKEN_LINE, TOKEN_NAME, and TOKEN_RIGHT_PAREN.
Referenced by definition(), and method().
matchChar()
static bool matchChar (Parser * parser, char c) static
Definition at line 662 of file wren_compiler.c.
 {
   if (peekChar(parser) != c) return false;
   nextChar(parser);
   return true;
 }
References nextChar(), and peekChar().
Referenced by nextToken(), readNumber(), and twoCharToken().
matchLine()
static bool matchLine (Compiler * compiler) static
Definition at line 1281 of file wren_compiler.c.
 {
   if (!match(compiler, TOKEN_LINE)) return false;
   while (match(compiler, TOKEN_LINE));
   return true;
 }
References match(), and TOKEN_LINE.
Referenced by classDefinition(), finishBlock(), ignoreNewlines(), and wrenCompile().
maybeSetter()
static bool maybeSetter (Compiler * compiler, Signature * signature) static
Definition at line 2640 of file wren_compiler.c.
 {
   // See if it's a setter.
   if (!match(compiler, TOKEN_EQ)) return false;
   // It's a setter.
   if (signature->type == SIG_SUBSCRIPT)
   {
     signature->type = SIG_SUBSCRIPT_SETTER;
   }
   else
   {
     signature->type = SIG_SETTER;
   }
   // Parse the value parameter.
   consume(compiler, TOKEN_LEFT_PAREN, "Expect '(' after '='.");
   declareNamedVariable(compiler);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after parameter name.");
   signature->arity++;
   return true;
 }
References consume(), declareNamedVariable(), match(), SIG_SETTER, SIG_SUBSCRIPT, SIG_SUBSCRIPT_SETTER, TOKEN_EQ, TOKEN_LEFT_PAREN, and TOKEN_RIGHT_PAREN.
Referenced by namedSignature(), and subscriptSignature().
method()
static bool method (Compiler * compiler, Variable classVariable) static
Definition at line 3427 of file wren_compiler.c.
 {
   // Parse any attributes before the method and store them
   if(matchAttribute(compiler)) {
     return method(compiler, classVariable);
   }
   // TODO: What about foreign constructors?
   bool isForeign = match(compiler, TOKEN_FOREIGN);
   bool isStatic = match(compiler, TOKEN_STATIC);
   compiler->enclosingClass->inStatic = isStatic;
   SignatureFn signatureFn = rules[compiler->parser->current.type].method;
   nextToken(compiler->parser);
   if (signatureFn == NULL)
   {
     error(compiler, "Expect method definition.");
     return false;
   }
   // Build the method signature.
   Signature signature = signatureFromToken(compiler, SIG_GETTER);
   compiler->enclosingClass->signature = &signature;
   Compiler methodCompiler;
   initCompiler(&methodCompiler, compiler->parser, compiler, true);
   // Compile the method signature.
   signatureFn(&methodCompiler, &signature);
   methodCompiler.isInitializer = signature.type == SIG_INITIALIZER;
   if (isStatic && signature.type == SIG_INITIALIZER)
   {
     error(compiler, "A constructor cannot be static.");
   }
   // Include the full signature in debug messages in stack traces.
   char fullSignature[MAX_METHOD_SIGNATURE];
   int length;
   signatureToString(&signature, fullSignature, &length);
   // Copy any attributes the compiler collected into the enclosing class
   copyMethodAttributes(compiler, isForeign, isStatic, fullSignature, length);
   // Check for duplicate methods. Doesn't matter that it's already been
   // defined, error will discard bytecode anyway.
   // Check if the method table already contains this symbol
   int methodSymbol = declareMethod(compiler, &signature, fullSignature, length);
   if (isForeign)
   {
     // Define a constant for the signature.
     emitConstant(compiler, wrenNewStringLength(compiler->parser->vm,
                                                fullSignature, length));
     // We don't need the function we started compiling in the parameter list
     // any more.
     methodCompiler.parser->vm->compiler = methodCompiler.parent;
   }
   else
   {
     consume(compiler, TOKEN_LEFT_BRACE, "Expect '{' to begin method body.");
     finishBody(&methodCompiler);
     endCompiler(&methodCompiler, fullSignature, length);
   }
   // Define the method. For a constructor, this defines the instance
   // initializer method.
   defineMethod(compiler, classVariable, isStatic, methodSymbol);
   if (signature.type == SIG_INITIALIZER)
   {
     // Also define a matching constructor method on the metaclass.
     signature.type = SIG_METHOD;
     int constructorSymbol = signatureSymbol(compiler, &signature);
     createConstructor(compiler, &signature, methodSymbol);
     defineMethod(compiler, classVariable, true, constructorSymbol);
   }
   return true;
 }
References consume(), copyMethodAttributes(), createConstructor(), declareMethod(), defineMethod(), emitConstant(), endCompiler(), error(), finishBody(), initCompiler(), match(), matchAttribute(), MAX_METHOD_SIGNATURE, methodSymbol(), nextToken(), NULL, rules, SIG_GETTER, SIG_INITIALIZER, SIG_METHOD, signatureFromToken(), signatureSymbol(), signatureToString(), TOKEN_FOREIGN, TOKEN_LEFT_BRACE, TOKEN_STATIC, and wrenNewStringLength().
Referenced by bindForeignClass(), bindMethod(), classDefinition(), createForeign(), findForeignMethod(), runInterpreter(), wrenBindMethod(), wrenCall(), wrenFinalizeForeign(), and wrenMakeCallHandle().
methodCall()
static void methodCall (Compiler * compiler, Code instruction, Signature * signature) static
Definition at line 2004 of file wren_compiler.c.
 {
   // Make a new signature that contains the updated arity and type based on
   // the arguments we find.
   Signature called = { signature->name, signature->length, SIG_GETTER, 0 };
   // Parse the argument list, if any.
   if (match(compiler, TOKEN_LEFT_PAREN))
   {
     called.type = SIG_METHOD;
     // Allow new line before an empty argument list
     ignoreNewlines(compiler);
     // Allow empty an argument list.
     if (peek(compiler) != TOKEN_RIGHT_PAREN)
     {
       finishArgumentList(compiler, &called);
     }
     consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after arguments.");
   }
   // Parse the block argument, if any.
   if (match(compiler, TOKEN_LEFT_BRACE))
   {
     // Include the block argument in the arity.
     called.type = SIG_METHOD;
     called.arity++;
     Compiler fnCompiler;
     initCompiler(&fnCompiler, compiler->parser, compiler, false);
     // Make a dummy signature to track the arity.
     Signature fnSignature = { "", 0, SIG_METHOD, 0 };
     // Parse the parameter list, if any.
     if (match(compiler, TOKEN_PIPE))
     {
       finishParameterList(&fnCompiler, &fnSignature);
       consume(compiler, TOKEN_PIPE, "Expect '|' after function parameters.");
     }
     fnCompiler.fn->arity = fnSignature.arity;
     finishBody(&fnCompiler);
     // Name the function based on the method its passed to.
     char blockName[MAX_METHOD_SIGNATURE + 15];
     int blockLength;
     signatureToString(&called, blockName, &blockLength);
     memmove(blockName + blockLength, " block argument", 16);
     endCompiler(&fnCompiler, blockName, blockLength + 15);
   }
   // TODO: Allow Grace-style mixfix methods?
   // If this is a super() call for an initializer, make sure we got an actual
   // argument list.
   if (signature->type == SIG_INITIALIZER)
   {
     if (called.type != SIG_METHOD)
     {
       error(compiler, "A superclass constructor must have an argument list.");
     }
     called.type = SIG_INITIALIZER;
   }
   callSignature(compiler, instruction, &called);
 }
References callSignature(), consume(), endCompiler(), error(), finishArgumentList(), finishBody(), finishParameterList(), ignoreNewlines(), initCompiler(), match(), MAX_METHOD_SIGNATURE, peek(), SIG_GETTER, SIG_INITIALIZER, SIG_METHOD, signatureToString(), TOKEN_LEFT_BRACE, TOKEN_LEFT_PAREN, TOKEN_PIPE, and TOKEN_RIGHT_PAREN.
Referenced by namedCall(), and super_().
methodSymbol()
static int methodSymbol (Compiler * compiler, const char * name, int length) static
Definition at line 1853 of file wren_compiler.c.
 {
   return wrenSymbolTableEnsure(compiler->parser->vm,
       &compiler->parser->vm->methodNames, name, length);
 }
References name(), and wrenSymbolTableEnsure().
Referenced by callMethod(), defineMethod(), method(), and signatureSymbol().
mixedSignature()
void mixedSignature (Compiler * compiler, Signature * signature)
Definition at line 2620 of file wren_compiler.c.
 {
   signature->type = SIG_GETTER;
   // If there is a parameter, it's an infix operator, otherwise it's unary.
   if (match(compiler, TOKEN_LEFT_PAREN))
   {
     // Add the RHS parameter.
     signature->type = SIG_METHOD;
     signature->arity = 1;
     // Parse the parameter name.
     declareNamedVariable(compiler);
     consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after parameter name.");
   }
 }
References consume(), declareNamedVariable(), match(), SIG_GETTER, SIG_METHOD, TOKEN_LEFT_PAREN, and TOKEN_RIGHT_PAREN.
name()
static void name (Compiler * compiler, bool canAssign) static
Definition at line 2364 of file wren_compiler.c.
 {
   // Look for the name in the scope chain up to the nearest enclosing method.
   Token* token = &compiler->parser->previous;
   Variable variable = resolveNonmodule(compiler, token->start, token->length);
   if (variable.index != -1)
   {
     bareName(compiler, canAssign, variable);
     return;
   }
   // TODO: The fact that we return above here if the variable is known and parse
   // an optional argument list below if not means that the grammar is not
   // context-free. A line of code in a method like "someName(foo)" is a parse
   // error if "someName" is a defined variable in the surrounding scope and not
   // if it isn't. Fix this. One option is to have "someName(foo)" always
   // resolve to a self-call if there is an argument list, but that makes
   // getters a little confusing.
   // If we're inside a method and the name is lowercase, treat it as a method
   // on this.
   if (wrenIsLocalName(token->start) && getEnclosingClass(compiler) != NULL)
   {
     loadThis(compiler);
     namedCall(compiler, canAssign, CODE_CALL_0);
     return;
   }
   // Otherwise, look for a module-level variable with the name.
   variable.scope = SCOPE_MODULE;
   variable.index = wrenSymbolTableFind(&compiler->parser->module->variableNames,
                                        token->start, token->length);
   if (variable.index == -1)
   {
     // Implicitly define a module-level variable in
     // the hopes that we get a real definition later.
     variable.index = wrenDeclareVariable(compiler->parser->vm,
                                          compiler->parser->module,
                                          token->start, token->length,
                                          token->line);
     if (variable.index == -2)
     {
       error(compiler, "Too many module variables defined.");
     }
   }
   bareName(compiler, canAssign, variable);
 }
References bareName(), error(), getEnclosingClass(), loadThis(), namedCall(), NULL, resolveNonmodule(), SCOPE_MODULE, token, wrenDeclareVariable(), wrenIsLocalName(), and wrenSymbolTableFind().
Referenced by addLocal(), callMethod(), declareMethod(), findUpvalue(), forStatement(), loadCoreVariable(), methodSymbol(), resolveLocal(), resolveName(), resolveNonmodule(), signatureParameterList(), signatureSymbol(), and signatureToString().
namedCall()
static void namedCall (Compiler * compiler, bool canAssign, Code instruction) static
Definition at line 2079 of file wren_compiler.c.
 {
   // Get the token for the method name.
   Signature signature = signatureFromToken(compiler, SIG_GETTER);
   if (canAssign && match(compiler, TOKEN_EQ))
   {
     ignoreNewlines(compiler);
     // Build the setter signature.
     signature.type = SIG_SETTER;
     signature.arity = 1;
     // Compile the assigned value.
     expression(compiler);
     callSignature(compiler, instruction, &signature);
   }
   else
   {
     methodCall(compiler, instruction, &signature);
     allowLineBeforeDot(compiler);
   }
 }
References allowLineBeforeDot(), callSignature(), expression(), ignoreNewlines(), match(), methodCall(), SIG_GETTER, SIG_SETTER, signatureFromToken(), and TOKEN_EQ.
Referenced by call(), name(), and super_().
namedSignature()
void namedSignature (Compiler * compiler, Signature * signature)
Definition at line 2701 of file wren_compiler.c.
 {
   signature->type = SIG_GETTER;
   // If it's a setter, it can't also have a parameter list.
   if (maybeSetter(compiler, signature)) return;
   // Regular named method with an optional parameter list.
   parameterList(compiler, signature);
 }
References maybeSetter(), parameterList(), and SIG_GETTER.
nextChar()
static char nextChar (Parser * parser) static
Definition at line 653 of file wren_compiler.c.
 {
   char c = peekChar(parser);
   parser->currentChar++;
   if (c == '\n') parser->currentLine++;
   return c;
 }
References peekChar().
Referenced by matchChar(), nextToken(), readHexDigit(), readHexNumber(), readName(), readNumber(), readRawString(), readString(), skipBlockComment(), and skipLineComment().
nextToken()
static void nextToken (Parser * parser) static
Definition at line 1051 of file wren_compiler.c.
 {
   parser->previous = parser->current;
   parser->current = parser->next;
   // If we are out of tokens, don't try to tokenize any more. We *do* still
   // copy the TOKEN_EOF to previous so that code that expects it to be consumed
   // will still work.
   if (parser->next.type == TOKEN_EOF) return;
   if (parser->current.type == TOKEN_EOF) return;
   while (peekChar(parser) != '\0')
   {
     parser->tokenStart = parser->currentChar;
     char c = nextChar(parser);
     switch (c)
     {
       case '(':
         // If we are inside an interpolated expression, count the unmatched "(".
         if (parser->numParens > 0) parser->parens[parser->numParens - 1]++;
         makeToken(parser, TOKEN_LEFT_PAREN);
         return;
       case ')':
         // If we are inside an interpolated expression, count the ")".
         if (parser->numParens > 0 &&
             --parser->parens[parser->numParens - 1] == 0)
         {
           // This is the final ")", so the interpolation expression has ended.
           // This ")" now begins the next section of the template string.
           parser->numParens--;
           readString(parser);
           return;
         }
         makeToken(parser, TOKEN_RIGHT_PAREN);
         return;
       case '[': makeToken(parser, TOKEN_LEFT_BRACKET); return;
       case ']': makeToken(parser, TOKEN_RIGHT_BRACKET); return;
       case '{': makeToken(parser, TOKEN_LEFT_BRACE); return;
       case '}': makeToken(parser, TOKEN_RIGHT_BRACE); return;
       case ':': makeToken(parser, TOKEN_COLON); return;
       case ',': makeToken(parser, TOKEN_COMMA); return;
       case '*': makeToken(parser, TOKEN_STAR); return;
       case '%': makeToken(parser, TOKEN_PERCENT); return;
       case '#': {
         // Ignore shebang on the first line.
         if (parser->currentLine == 1 && peekChar(parser) == '!' && peekNextChar(parser) == '/')
         {
           skipLineComment(parser);
           break;
         }
         // Otherwise we treat it as a token
         makeToken(parser, TOKEN_HASH);
         return;
       }
       case '^': makeToken(parser, TOKEN_CARET); return;
       case '+': makeToken(parser, TOKEN_PLUS); return;
       case '-': makeToken(parser, TOKEN_MINUS); return;
       case '~': makeToken(parser, TOKEN_TILDE); return;
       case '?': makeToken(parser, TOKEN_QUESTION); return;
       case '|': twoCharToken(parser, '|', TOKEN_PIPEPIPE, TOKEN_PIPE); return;
       case '&': twoCharToken(parser, '&', TOKEN_AMPAMP, TOKEN_AMP); return;
       case '=': twoCharToken(parser, '=', TOKEN_EQEQ, TOKEN_EQ); return;
       case '!': twoCharToken(parser, '=', TOKEN_BANGEQ, TOKEN_BANG); return;
       case '.':
         if (matchChar(parser, '.'))
         {
           twoCharToken(parser, '.', TOKEN_DOTDOTDOT, TOKEN_DOTDOT);
           return;
         }
         makeToken(parser, TOKEN_DOT);
         return;
       case '/':
         if (matchChar(parser, '/'))
         {
           skipLineComment(parser);
           break;
         }
         if (matchChar(parser, '*'))
         {
           skipBlockComment(parser);
           break;
         }
         makeToken(parser, TOKEN_SLASH);
         return;
       case '<':
         if (matchChar(parser, '<'))
         {
           makeToken(parser, TOKEN_LTLT);
         }
         else
         {
           twoCharToken(parser, '=', TOKEN_LTEQ, TOKEN_LT);
         }
         return;
       case '>':
         if (matchChar(parser, '>'))
         {
           makeToken(parser, TOKEN_GTGT);
         }
         else
         {
           twoCharToken(parser, '=', TOKEN_GTEQ, TOKEN_GT);
         }
         return;
       case '\n':
         makeToken(parser, TOKEN_LINE);
         return;
       case ' ':
       case '\r':
       case '\t':
         // Skip forward until we run out of whitespace.
         while (peekChar(parser) == ' ' ||
                peekChar(parser) == '\r' ||
                peekChar(parser) == '\t')
         {
           nextChar(parser);
         }
         break;
       case '"': {
         if(peekChar(parser) == '"' && peekNextChar(parser)  == '"') {
           readRawString(parser);
           return;
         }
         readString(parser); return;
       }
       case '_':
         readName(parser,
                  peekChar(parser) == '_' ? TOKEN_STATIC_FIELD : TOKEN_FIELD, c);
         return;
       case '0':
         if (peekChar(parser) == 'x')
         {
           readHexNumber(parser);
           return;
         }
         readNumber(parser);
         return;
       default:
         if (isName(c))
         {
           readName(parser, TOKEN_NAME, c);
         }
         else if (isDigit(c))
         {
           readNumber(parser);
         }
         else
         {
           if (c >= 32 && c <= 126)
           {
             lexError(parser, "Invalid character '%c'.", c);
           }
           else
           {
             // Don't show non-ASCII values since we didn't UTF-8 decode the
             // bytes. Since there are no non-ASCII byte values that are
             // meaningful code units in Wren, the lexer works on raw bytes,
             // even though the source code and console output are UTF-8.
             lexError(parser, "Invalid byte 0x%x.", (uint8_t)c);
           }
           parser->next.type = TOKEN_ERROR;
           parser->next.length = 0;
         }
         return;
     }
   }
   // If we get here, we're out of source, so just make EOF tokens.
   parser->tokenStart = parser->currentChar;
   makeToken(parser, TOKEN_EOF);
 }
References isDigit(), isName(), lexError(), makeToken(), matchChar(), nextChar(), peekChar(), peekNextChar(), readHexNumber(), readName(), readNumber(), readRawString(), readString(), skipBlockComment(), skipLineComment(), TOKEN_AMP, TOKEN_AMPAMP, TOKEN_BANG, TOKEN_BANGEQ, TOKEN_CARET, TOKEN_COLON, TOKEN_COMMA, TOKEN_DOT, TOKEN_DOTDOT, TOKEN_DOTDOTDOT, TOKEN_EOF, TOKEN_EQ, TOKEN_EQEQ, TOKEN_ERROR, TOKEN_FIELD, TOKEN_GT, TOKEN_GTEQ, TOKEN_GTGT, TOKEN_HASH, TOKEN_LEFT_BRACE, TOKEN_LEFT_BRACKET, TOKEN_LEFT_PAREN, TOKEN_LINE, TOKEN_LT, TOKEN_LTEQ, TOKEN_LTLT, TOKEN_MINUS, TOKEN_NAME, TOKEN_PERCENT, TOKEN_PIPE, TOKEN_PIPEPIPE, TOKEN_PLUS, TOKEN_QUESTION, TOKEN_RIGHT_BRACE, TOKEN_RIGHT_BRACKET, TOKEN_RIGHT_PAREN, TOKEN_SLASH, TOKEN_STAR, TOKEN_STATIC_FIELD, TOKEN_TILDE, and twoCharToken().
Referenced by allowLineBeforeDot(), consume(), consumeLiteral(), match(), method(), parsePrecedence(), and wrenCompile().
null()
static void null (Compiler * compiler, bool canAssign) static
Definition at line 2415 of file wren_compiler.c.
 {
   emitOp(compiler, CODE_NULL);
 }
References emitOp().
or_()
static void or_ (Compiler * compiler, bool canAssign) static
Definition at line 2546 of file wren_compiler.c.
 {
   ignoreNewlines(compiler);
   // Skip the right argument if the left is true.
   int jump = emitJump(compiler, CODE_OR);
   parsePrecedence(compiler, PREC_LOGICAL_OR);
   patchJump(compiler, jump);
 }
References emitJump(), ignoreNewlines(), parsePrecedence(), patchJump(), and PREC_LOGICAL_OR.
parameterList()
static void parameterList (Compiler * compiler, Signature * signature) static
Definition at line 2683 of file wren_compiler.c.
 {
   // The parameter list is optional.
   if (!match(compiler, TOKEN_LEFT_PAREN)) return;
   signature->type = SIG_METHOD;
   // Allow new line before an empty argument list
   ignoreNewlines(compiler);
   // Allow an empty parameter list.
   if (match(compiler, TOKEN_RIGHT_PAREN)) return;
   finishParameterList(compiler, signature);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after parameters.");
 }
References consume(), finishParameterList(), ignoreNewlines(), match(), SIG_METHOD, TOKEN_LEFT_PAREN, and TOKEN_RIGHT_PAREN.
Referenced by namedSignature().
parsePrecedence()
void parsePrecedence (Compiler * compiler, Precedence precedence) static
Definition at line 2824 of file wren_compiler.c.
 {
   nextToken(compiler->parser);
   GrammarFn prefix = rules[compiler->parser->previous.type].prefix;
   if (prefix == NULL)
   {
     error(compiler, "Expected expression.");
     return;
   }
   // Track if the precendence of the surrounding expression is low enough to
   // allow an assignment inside this one. We can't compile an assignment like
   // a normal expression because it requires us to handle the LHS specially --
   // it needs to be an lvalue, not an rvalue. So, for each of the kinds of
   // expressions that are valid lvalues -- names, subscripts, fields, etc. --
   // we pass in whether or not it appears in a context loose enough to allow
   // "=". If so, it will parse the "=" itself and handle it appropriately.
   bool canAssign = precedence <= PREC_CONDITIONAL;
   prefix(compiler, canAssign);
   while (precedence <= rules[compiler->parser->current.type].precedence)
   {
     nextToken(compiler->parser);
     GrammarFn infix = rules[compiler->parser->previous.type].infix;
     infix(compiler, canAssign);
   }
 }
References error(), nextToken(), NULL, PREC_CONDITIONAL, prefix(), and rules.
Referenced by and_(), classDefinition(), conditional(), expression(), infixOp(), map(), or_(), and unaryOp().
patchJump()
static void patchJump (Compiler * compiler, int offset) static
Definition at line 1756 of file wren_compiler.c.
 {
   // -2 to adjust for the bytecode for the jump offset itself.
   int jump = compiler->fn->code.count - offset - 2;
   if (jump > MAX_JUMP) error(compiler, "Too much code to jump over.");
   compiler->fn->code.data[offset] = (jump >> 8) & 0xff;
   compiler->fn->code.data[offset + 1] = jump & 0xff;
 }
References error(), and MAX_JUMP.
Referenced by and_(), conditional(), endLoop(), ifStatement(), and or_().
peek()
static TokenType peek (Compiler * compiler) static
Definition at line 1244 of file wren_compiler.c.
 {
   return compiler->parser->current.type;
 }
Referenced by allowLineBeforeDot(), finishBlock(), list(), map(), match(), matchAttribute(), methodCall(), StreamFile< BaseFile, PosType >::peek(), and statement().
peekChar()
static char peekChar (Parser * parser) static
Definition at line 639 of file wren_compiler.c.
 {
   return *parser->currentChar;
 }
Referenced by matchChar(), nextChar(), nextToken(), peekNextChar(), readHexEscape(), readName(), readNumber(), readRawString(), skipBlockComment(), and skipLineComment().
peekNext()
static TokenType peekNext (Compiler * compiler) static
Definition at line 1250 of file wren_compiler.c.
 {
   return compiler->parser->next.type;
 }
Referenced by allowLineBeforeDot().
peekNextChar()
static char peekNextChar (Parser * parser) static
Definition at line 645 of file wren_compiler.c.
 {
   // If we're at the end of the source, don't read past it.
   if (peekChar(parser) == '\0') return '\0';
   return *(parser->currentChar + 1);
 }
References peekChar().
Referenced by nextToken(), readNumber(), readRawString(), and skipBlockComment().
popScope()
static void popScope (Compiler * compiler) static
Definition at line 1522 of file wren_compiler.c.
 {
   int popped = discardLocals(compiler, compiler->scopeDepth);
   compiler->numLocals -= popped;
   compiler->numSlots -= popped;
   compiler->scopeDepth--;
 }
References discardLocals().
Referenced by classDefinition(), forStatement(), and statement().
printError()
static void printError (Parser * parser, int line, const char * label, const char * format, va_list args) static
Definition at line 420 of file wren_compiler.c.
 {
   parser->hasError = true;
   if (!parser->printErrors) return;
   // Only report errors if there is a WrenErrorFn to handle them.
   if (parser->vm->config.errorFn == NULL) return;
   // Format the label and message.
   char message[ERROR_MESSAGE_SIZE];
   int length = sprintf(message, "%s: ", label);
   length += vsprintf(message + length, format, args);
   ASSERT(length < ERROR_MESSAGE_SIZE, "Error should not exceed buffer.");
   ObjString* module = parser->module->name;
   const char* module_name = module ? module->value : "<unknown>";
   parser->vm->config.errorFn(parser->vm, WREN_ERROR_COMPILE,
                              module_name, line, message);
 }
References ASSERT, ERROR_MESSAGE_SIZE, NULL, sObjString::value, and WREN_ERROR_COMPILE.
Referenced by error(), and lexError().
pushScope()
static void pushScope (Compiler * compiler) static
Definition at line 1480 of file wren_compiler.c.
 {
   compiler->scopeDepth++;
 }
Referenced by classDefinition(), forStatement(), and statement().
readHexDigit()
static int readHexDigit (Parser * parser) static
Definition at line 733 of file wren_compiler.c.
 {
   char c = nextChar(parser);
   if (c >= '0' && c <= '9') return c - '0';
   if (c >= 'a' && c <= 'f') return c - 'a' + 10;
   if (c >= 'A' && c <= 'F') return c - 'A' + 10;
   // Don't consume it if it isn't expected. Keeps us from reading past the end
   // of an unterminated string.
   parser->currentChar--;
   return -1;
 }
References nextChar().
Referenced by readHexEscape(), and readHexNumber().
readHexEscape()
static int readHexEscape (Parser * parser, int digits, const char * description) static
Definition at line 850 of file wren_compiler.c.
 {
   int value = 0;
   for (int i = 0; i < digits; i++)
   {
     if (peekChar(parser) == '"' || peekChar(parser) == '\0')
     {
       lexError(parser, "Incomplete %s escape sequence.", description);
       // Don't consume it if it isn't expected. Keeps us from reading past the
       // end of an unterminated string.
       parser->currentChar--;
       break;
     }
     int digit = readHexDigit(parser);
     if (digit == -1)
     {
       lexError(parser, "Invalid %s escape sequence.", description);
       break;
     }
     value = (value * 16) | digit;
   }
   return value;
 }
References lexError(), peekChar(), and readHexDigit().
Referenced by readString(), and readUnicodeEscape().
readHexNumber()
static void readHexNumber (Parser * parser) static
Definition at line 773 of file wren_compiler.c.
 {
   // Skip past the `x` used to denote a hexadecimal literal.
   nextChar(parser);
   // Iterate over all the valid hexadecimal digits found.
   while (readHexDigit(parser) != -1) continue;
   makeNumber(parser, true);
 }
References makeNumber(), nextChar(), and readHexDigit().
Referenced by nextToken().
readName()
static void readName (Parser * parser, TokenType type, char firstChar) static
Definition at line 818 of file wren_compiler.c.
 {
   ByteBuffer string;
   wrenByteBufferInit(&string);
   wrenByteBufferWrite(parser->vm, &string, firstChar);
   while (isName(peekChar(parser)) || isDigit(peekChar(parser)))
   {
     char c = nextChar(parser);
     wrenByteBufferWrite(parser->vm, &string, c);
   }
   // Update the type if it's a keyword.
   size_t length = parser->currentChar - parser->tokenStart;
   for (int i = 0; keywords[i].identifier != NULL; i++)
   {
     if (length == keywords[i].length &&
         memcmp(parser->tokenStart, keywords[i].identifier, length) == 0)
     {
       type = keywords[i].tokenType;
       break;
     }
   }
   parser->next.value = wrenNewStringLength(parser->vm,
                                             (char*)string.data, string.count);
   wrenByteBufferClear(parser->vm, &string);
   makeToken(parser, type);
 }
References isDigit(), isName(), keywords, makeToken(), nextChar(), NULL, peekChar(), and wrenNewStringLength().
Referenced by nextToken().
readNumber()
static void readNumber (Parser * parser) static
Definition at line 785 of file wren_compiler.c.
 {
   while (isDigit(peekChar(parser))) nextChar(parser);
   // See if it has a floating point. Make sure there is a digit after the "."
   // so we don't get confused by method calls on number literals.
   if (peekChar(parser) == '.' && isDigit(peekNextChar(parser)))
   {
     nextChar(parser);
     while (isDigit(peekChar(parser))) nextChar(parser);
   }
   // See if the number is in scientific notation.
   if (matchChar(parser, 'e') || matchChar(parser, 'E'))
   {
     // Allow a single positive/negative exponent symbol.
     if(!matchChar(parser, '+'))
     {
       matchChar(parser, '-');
     }
     if (!isDigit(peekChar(parser)))
     {
       lexError(parser, "Unterminated scientific notation.");
     }
     while (isDigit(peekChar(parser))) nextChar(parser);
   }
   makeNumber(parser, false);
 }
References isDigit(), lexError(), makeNumber(), matchChar(), nextChar(), peekChar(), and peekNextChar().
Referenced by nextToken().
readRawString()
static void readRawString (Parser * parser) static
Definition at line 892 of file wren_compiler.c.
 {
   ByteBuffer string;
   wrenByteBufferInit(&string);
   TokenType type = TOKEN_STRING;
   //consume the second and third "
   nextChar(parser);
   nextChar(parser);
   int skipStart = 0;
   int firstNewline = -1;
   int skipEnd = -1;
   int lastNewline = -1;
   for (;;)
   {
     char c = nextChar(parser);
     char c1 = peekChar(parser);
     char c2 = peekNextChar(parser);
     if (c == '\r') continue;
     if (c == '\n') {
       lastNewline = string.count;
       skipEnd = lastNewline;
       firstNewline = firstNewline == -1 ? string.count : firstNewline;
     }
     if (c == '"' && c1 == '"' && c2 == '"') break;
     bool isWhitespace = c == ' ' || c == '\t';
     skipEnd = c == '\n' || isWhitespace ? skipEnd : -1;
     // If we haven't seen a newline or other character yet,
     // and still seeing whitespace, count the characters
     // as skippable till we know otherwise
     bool skippable = skipStart != -1 && isWhitespace && firstNewline == -1;
     skipStart = skippable ? string.count + 1 : skipStart;
     // We've counted leading whitespace till we hit something else,
     // but it's not a newline, so we reset skipStart since we need these characters
     if (firstNewline == -1 && !isWhitespace && c != '\n') skipStart = -1;
     if (c == '\0' || c1 == '\0' || c2 == '\0')
     {
       lexError(parser, "Unterminated raw string.");
       // Don't consume it if it isn't expected. Keeps us from reading past the
       // end of an unterminated string.
       parser->currentChar--;
       break;
     }
     wrenByteBufferWrite(parser->vm, &string, c);
   }
   //consume the second and third "
   nextChar(parser);
   nextChar(parser);
   int offset = 0;
   int count = string.count;
   if(firstNewline != -1 && skipStart == firstNewline) offset = firstNewline + 1;
   if(lastNewline != -1 && skipEnd == lastNewline) count = lastNewline;
   count -= (offset > count) ? count : offset;
   parser->next.value = wrenNewStringLength(parser->vm,
                          ((char*)string.data) + offset, count);
   wrenByteBufferClear(parser->vm, &string);
   makeToken(parser, type);
 }
References count, lexError(), makeToken(), nextChar(), peekChar(), peekNextChar(), TOKEN_STRING, and wrenNewStringLength().
Referenced by nextToken().
readString()
static void readString (Parser * parser) static
Definition at line 970 of file wren_compiler.c.
 {
   ByteBuffer string;
   TokenType type = TOKEN_STRING;
   wrenByteBufferInit(&string);
   for (;;)
   {
     char c = nextChar(parser);
     if (c == '"') break;
     if (c == '\r') continue;
     if (c == '\0')
     {
       lexError(parser, "Unterminated string.");
       // Don't consume it if it isn't expected. Keeps us from reading past the
       // end of an unterminated string.
       parser->currentChar--;
       break;
     }
     if (c == '%')
     {
       if (parser->numParens < MAX_INTERPOLATION_NESTING)
       {
         // TODO: Allow format string.
         if (nextChar(parser) != '(') lexError(parser, "Expect '(' after '%%'.");
         parser->parens[parser->numParens++] = 1;
         type = TOKEN_INTERPOLATION;
         break;
       }
       lexError(parser, "Interpolation may only nest %d levels deep.",
                MAX_INTERPOLATION_NESTING);
     }
     if (c == '\\')
     {
       switch (nextChar(parser))
       {
         case '"':  wrenByteBufferWrite(parser->vm, &string, '"'); break;
         case '\\': wrenByteBufferWrite(parser->vm, &string, '\\'); break;
         case '%':  wrenByteBufferWrite(parser->vm, &string, '%'); break;
         case '0':  wrenByteBufferWrite(parser->vm, &string, '\0'); break;
         case 'a':  wrenByteBufferWrite(parser->vm, &string, '\a'); break;
         case 'b':  wrenByteBufferWrite(parser->vm, &string, '\b'); break;
         case 'e':  wrenByteBufferWrite(parser->vm, &string, '\33'); break;
         case 'f':  wrenByteBufferWrite(parser->vm, &string, '\f'); break;
         case 'n':  wrenByteBufferWrite(parser->vm, &string, '\n'); break;
         case 'r':  wrenByteBufferWrite(parser->vm, &string, '\r'); break;
         case 't':  wrenByteBufferWrite(parser->vm, &string, '\t'); break;
         case 'u':  readUnicodeEscape(parser, &string, 4); break;
         case 'U':  readUnicodeEscape(parser, &string, 8); break;
         case 'v':  wrenByteBufferWrite(parser->vm, &string, '\v'); break;
         case 'x':
           wrenByteBufferWrite(parser->vm, &string,
                               (uint8_t)readHexEscape(parser, 2, "byte"));
           break;
         default:
           lexError(parser, "Invalid escape character '%c'.",
                    *(parser->currentChar - 1));
           break;
       }
     }
     else
     {
       wrenByteBufferWrite(parser->vm, &string, c);
     }
   }
   parser->next.value = wrenNewStringLength(parser->vm,
                                               (char*)string.data, string.count);
   wrenByteBufferClear(parser->vm, &string);
   makeToken(parser, type);
 }
References lexError(), makeToken(), MAX_INTERPOLATION_NESTING, nextChar(), readHexEscape(), readUnicodeEscape(), TOKEN_INTERPOLATION, TOKEN_STRING, and wrenNewStringLength().
Referenced by nextToken().
readUnicodeEscape()
static void readUnicodeEscape (Parser * parser, ByteBuffer * string, int length) static
Definition at line 879 of file wren_compiler.c.
 {
   int value = readHexEscape(parser, length, "Unicode");
   // Grow the buffer enough for the encoded result.
   int numBytes = wrenUtf8EncodeNumBytes(value);
   if (numBytes != 0)
   {
     wrenByteBufferFill(parser->vm, string, 0, numBytes);
     wrenUtf8Encode(value, string->data + string->count - numBytes);
   }
 }
References readHexEscape(), wrenUtf8Encode(), and wrenUtf8EncodeNumBytes().
Referenced by readString().
resolveLocal()
static int resolveLocal (Compiler * compiler, const char * name, int length) static
Definition at line 1532 of file wren_compiler.c.
 {
   // Look it up in the local scopes. Look in reverse order so that the most
   // nested variable is found first and shadows outer ones.
   for (int i = compiler->numLocals - 1; i >= 0; i--)
   {
     if (compiler->locals[i].length == length &&
         memcmp(name, compiler->locals[i].name, length) == 0)
     {
       return i;
     }
   }
   return -1;
 }
References name().
Referenced by findUpvalue(), resolveNonmodule(), and staticField().
resolveName()
static Variable resolveName (Compiler * compiler, const char * name, int length) static
Definition at line 1636 of file wren_compiler.c.
 {
   Variable variable = resolveNonmodule(compiler, name, length);
   if (variable.index != -1) return variable;
   variable.scope = SCOPE_MODULE;
   variable.index = wrenSymbolTableFind(&compiler->parser->module->variableNames,
                                        name, length);
   return variable;
 }
References name(), resolveNonmodule(), SCOPE_MODULE, and wrenSymbolTableFind().
Referenced by staticField().
resolveNonmodule()
static Variable resolveNonmodule (Compiler * compiler, const char * name, int length) static
Definition at line 1618 of file wren_compiler.c.
 {
   // Look it up in the local scopes.
   Variable variable;
   variable.scope = SCOPE_LOCAL;
   variable.index = resolveLocal(compiler, name, length);
   if (variable.index != -1) return variable;
   // Tt's not a local, so guess that it's an upvalue.
   variable.scope = SCOPE_UPVALUE;
   variable.index = findUpvalue(compiler, name, length);
   return variable;
 }
References findUpvalue(), name(), resolveLocal(), SCOPE_LOCAL, and SCOPE_UPVALUE.
Referenced by loadThis(), name(), and resolveName().
signatureFromToken()
static Signature signatureFromToken (Compiler * compiler, SignatureType type) static
Definition at line 1936 of file wren_compiler.c.
 {
   Signature signature;
   // Get the token for the method name.
   Token* token = &compiler->parser->previous;
   signature.name = token->start;
   signature.length = token->length;
   signature.type = type;
   signature.arity = 0;
   if (signature.length > MAX_METHOD_NAME)
   {
     error(compiler, "Method names cannot be longer than %d characters.",
           MAX_METHOD_NAME);
     signature.length = MAX_METHOD_NAME;
   }
   return signature;
 }
References error(), MAX_METHOD_NAME, and token.
Referenced by constructorSignature(), method(), and namedCall().
signatureParameterList()
static void signatureParameterList (char name[MAX_METHOD_SIGNATURE], int * length, int numParams, char leftBracket, char rightBracket) static
Definition at line 1861 of file wren_compiler.c.
 {
   name[(*length)++] = leftBracket;
   // This function may be called with too many parameters. When that happens,
   // a compile error has already been reported, but we need to make sure we
   // don't overflow the string too, hence the MAX_PARAMETERS check.
   for (int i = 0; i < numParams && i < MAX_PARAMETERS; i++)
   {
     if (i > 0) name[(*length)++] = ',';
     name[(*length)++] = '_';
   }
   name[(*length)++] = rightBracket;
 }
References MAX_PARAMETERS, and name().
Referenced by signatureToString().
signatureSymbol()
static int signatureSymbol (Compiler * compiler, Signature * signature) static
Definition at line 1925 of file wren_compiler.c.
 {
   // Build the full name from the signature.
   char name[MAX_METHOD_SIGNATURE];
   int length;
   signatureToString(signature, name, &length);
   return methodSymbol(compiler, name, length);
 }
References MAX_METHOD_SIGNATURE, methodSymbol(), name(), and signatureToString().
Referenced by callSignature(), declareMethod(), and method().
signatureToString()
static void signatureToString (Signature * signature, char name[MAX_METHOD_SIGNATURE], int * length) static
Definition at line 1879 of file wren_compiler.c.
 {
   *length = 0;
   // Build the full name from the signature.
   memcpy(name + *length, signature->name, signature->length);
   *length += signature->length;
   switch (signature->type)
   {
     case SIG_METHOD:
       signatureParameterList(name, length, signature->arity, '(', ')');
       break;
     case SIG_GETTER:
       // The signature is just the name.
       break;
     case SIG_SETTER:
       name[(*length)++] = '=';
       signatureParameterList(name, length, 1, '(', ')');
       break;
     case SIG_SUBSCRIPT:
       signatureParameterList(name, length, signature->arity, '[', ']');
       break;
     case SIG_SUBSCRIPT_SETTER:
       signatureParameterList(name, length, signature->arity - 1, '[', ']');
       name[(*length)++] = '=';
       signatureParameterList(name, length, 1, '(', ')');
       break;
     case SIG_INITIALIZER:
       memcpy(name, "init ", 5);
       memcpy(name + 5, signature->name, signature->length);
       *length = 5 + signature->length;
       signatureParameterList(name, length, signature->arity, '(', ')');
       break;
   }
   name[*length] = '\0';
 }
References name(), SIG_GETTER, SIG_INITIALIZER, SIG_METHOD, SIG_SETTER, SIG_SUBSCRIPT, SIG_SUBSCRIPT_SETTER, and signatureParameterList().
Referenced by method(), methodCall(), and signatureSymbol().
skipBlockComment()
static void skipBlockComment (Parser * parser) static
Definition at line 699 of file wren_compiler.c.
 {
   int nesting = 1;
   while (nesting > 0)
   {
     if (peekChar(parser) == '\0')
     {
       lexError(parser, "Unterminated block comment.");
       return;
     }
     if (peekChar(parser) == '/' && peekNextChar(parser) == '*')
     {
       nextChar(parser);
       nextChar(parser);
       nesting++;
       continue;
     }
     if (peekChar(parser) == '*' && peekNextChar(parser) == '/')
     {
       nextChar(parser);
       nextChar(parser);
       nesting--;
       continue;
     }
     // Regular comment character.
     nextChar(parser);
   }
 }
References lexError(), nextChar(), peekChar(), and peekNextChar().
Referenced by nextToken().
skipLineComment()
static void skipLineComment (Parser * parser) static
Definition at line 690 of file wren_compiler.c.
 {
   while (peekChar(parser) != '\n' && peekChar(parser) != '\0')
   {
     nextChar(parser);
   }
 }
References nextChar(), and peekChar().
Referenced by nextToken().
startLoop()
static void startLoop (Compiler * compiler, Loop * loop) static
Definition at line 2968 of file wren_compiler.c.
 {
   loop->enclosing = compiler->loop;
   loop->start = compiler->fn->code.count - 1;
   loop->scopeDepth = compiler->scopeDepth;
   compiler->loop = loop;
 }
References loop().
Referenced by forStatement(), and whileStatement().
statement()
void statement (Compiler * compiler) static
Definition at line 3175 of file wren_compiler.c.
 {
   if (match(compiler, TOKEN_BREAK))
   {
     if (compiler->loop == NULL)
     {
       error(compiler, "Cannot use 'break' outside of a loop.");
       return;
     }
     // Since we will be jumping out of the scope, make sure any locals in it
     // are discarded first.
     discardLocals(compiler, compiler->loop->scopeDepth + 1);
     // Emit a placeholder instruction for the jump to the end of the body. When
     // we're done compiling the loop body and know where the end is, we'll
     // replace these with `CODE_JUMP` instructions with appropriate offsets.
     // We use `CODE_END` here because that can't occur in the middle of
     // bytecode.
     emitJump(compiler, CODE_END);
   }
   else if (match(compiler, TOKEN_CONTINUE))
   {
     if (compiler->loop == NULL)
     {
         error(compiler, "Cannot use 'continue' outside of a loop.");
         return;
     }
     // Since we will be jumping out of the scope, make sure any locals in it
     // are discarded first.
     discardLocals(compiler, compiler->loop->scopeDepth + 1);
     // emit a jump back to the top of the loop
     int loopOffset = compiler->fn->code.count - compiler->loop->start + 2;
     emitShortArg(compiler, CODE_LOOP, loopOffset);
   }
   else if (match(compiler, TOKEN_FOR))
   {
     forStatement(compiler);
   }
   else if (match(compiler, TOKEN_IF))
   {
     ifStatement(compiler);
   }
   else if (match(compiler, TOKEN_RETURN))
   {
     // Compile the return value.
     if (peek(compiler) == TOKEN_LINE)
     {
       // If there's no expression after return, initializers should
       // return 'this' and regular methods should return null
       Code result = compiler->isInitializer ? CODE_LOAD_LOCAL_0 : CODE_NULL;
       emitOp(compiler, result);
     }
     else
     {
       if (compiler->isInitializer)
       {
         error(compiler, "A constructor cannot return a value.");
       }
       expression(compiler);
     }
     emitOp(compiler, CODE_RETURN);
   }
   else if (match(compiler, TOKEN_WHILE))
   {
     whileStatement(compiler);
   }
   else if (match(compiler, TOKEN_LEFT_BRACE))
   {
     // Block statement.
     pushScope(compiler);
     if (finishBlock(compiler))
     {
       // Block was an expression, so discard it.
       emitOp(compiler, CODE_POP);
     }
     popScope(compiler);
   }
   else
   {
     // Expression statement.
     expression(compiler);
     emitOp(compiler, CODE_POP);
   }
 }
References discardLocals(), emitJump(), emitOp(), emitShortArg(), error(), expression(), finishBlock(), forStatement(), ifStatement(), match(), NULL, peek(), popScope(), pushScope(), TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_FOR, TOKEN_IF, TOKEN_LEFT_BRACE, TOKEN_LINE, TOKEN_RETURN, TOKEN_WHILE, and whileStatement().
Referenced by definition(), ifStatement(), and loopBody().
staticField()
static void staticField (Compiler * compiler, bool canAssign) static
Definition at line 2333 of file wren_compiler.c.
 {
   Compiler* classCompiler = getEnclosingClassCompiler(compiler);
   if (classCompiler == NULL)
   {
     error(compiler, "Cannot use a static field outside of a class definition.");
     return;
   }
   // Look up the name in the scope chain.
   Token* token = &compiler->parser->previous;
   // If this is the first time we've seen this static field, implicitly
   // define it as a variable in the scope surrounding the class definition.
   if (resolveLocal(classCompiler, token->start, token->length) == -1)
   {
     int symbol = declareVariable(classCompiler, NULL);
     // Implicitly initialize it to null.
     emitOp(classCompiler, CODE_NULL);
     defineVariable(classCompiler, symbol);
   }
   // It definitely exists now, so resolve it properly. This is different from
   // the above resolveLocal() call because we may have already closed over it
   // as an upvalue.
   Variable variable = resolveName(compiler, token->start, token->length);
   bareName(compiler, canAssign, variable);
 }
References bareName(), declareVariable(), defineVariable(), emitOp(), error(), getEnclosingClassCompiler(), NULL, resolveLocal(), resolveName(), and token.
stringInterpolation()
static void stringInterpolation (Compiler * compiler, bool canAssign) static
Definition at line 2436 of file wren_compiler.c.
 {
   // Instantiate a new list.
   loadCoreVariable(compiler, "List");
   callMethod(compiler, 0, "new()", 5);
   do
   {
     // The opening string part.
     literal(compiler, false);
     callMethod(compiler, 1, "addCore_(_)", 11);
     // The interpolated expression.
     ignoreNewlines(compiler);
     expression(compiler);
     callMethod(compiler, 1, "addCore_(_)", 11);
     ignoreNewlines(compiler);
   } while (match(compiler, TOKEN_INTERPOLATION));
   // The trailing string part.
   consume(compiler, TOKEN_STRING, "Expect end of string interpolation.");
   literal(compiler, false);
   callMethod(compiler, 1, "addCore_(_)", 11);
   // The list of interpolated parts.
   callMethod(compiler, 0, "join()", 6);
 }
References callMethod(), consume(), expression(), ignoreNewlines(), literal(), loadCoreVariable(), match(), TOKEN_INTERPOLATION, and TOKEN_STRING.
subscript()
static void subscript (Compiler * compiler, bool canAssign) static
Definition at line 2507 of file wren_compiler.c.
 {
   Signature signature = { "", 0, SIG_SUBSCRIPT, 0 };
   // Parse the argument list.
   finishArgumentList(compiler, &signature);
   consume(compiler, TOKEN_RIGHT_BRACKET, "Expect ']' after arguments.");
   allowLineBeforeDot(compiler);
   if (canAssign && match(compiler, TOKEN_EQ))
   {
     signature.type = SIG_SUBSCRIPT_SETTER;
     // Compile the assigned value.
     validateNumParameters(compiler, ++signature.arity);
     expression(compiler);
   }
   callSignature(compiler, CODE_CALL_0, &signature);
 }
References allowLineBeforeDot(), callSignature(), consume(), expression(), finishArgumentList(), match(), SIG_SUBSCRIPT, SIG_SUBSCRIPT_SETTER, TOKEN_EQ, TOKEN_RIGHT_BRACKET, and validateNumParameters().
subscriptSignature()
void subscriptSignature (Compiler * compiler, Signature * signature)
Definition at line 2666 of file wren_compiler.c.
 {
   signature->type = SIG_SUBSCRIPT;
   // The signature currently has "[" as its name since that was the token that
   // matched it. Clear that out.
   signature->length = 0;
   // Parse the parameters inside the subscript.
   finishParameterList(compiler, signature);
   consume(compiler, TOKEN_RIGHT_BRACKET, "Expect ']' after parameters.");
   maybeSetter(compiler, signature);
 }
References consume(), finishParameterList(), maybeSetter(), SIG_SUBSCRIPT, and TOKEN_RIGHT_BRACKET.
super_()
static void super_ (Compiler * compiler, bool canAssign) static
Definition at line 2465 of file wren_compiler.c.
 {
   ClassInfo* enclosingClass = getEnclosingClass(compiler);
   if (enclosingClass == NULL)
   {
     error(compiler, "Cannot use 'super' outside of a method.");
   }
   loadThis(compiler);
   // TODO: Super operator calls.
   // TODO: There's no syntax for invoking a superclass constructor with a
   // different name from the enclosing one. Figure that out.
   // See if it's a named super call, or an unnamed one.
   if (match(compiler, TOKEN_DOT))
   {
     // Compile the superclass call.
     consume(compiler, TOKEN_NAME, "Expect method name after 'super.'.");
     namedCall(compiler, canAssign, CODE_SUPER_0);
   }
   else if (enclosingClass != NULL)
   {
     // No explicit name, so use the name of the enclosing method. Make sure we
     // check that enclosingClass isn't NULL first. We've already reported the
     // error, but we don't want to crash here.
     methodCall(compiler, CODE_SUPER_0, enclosingClass->signature);
   }
 }
References consume(), error(), getEnclosingClass(), loadThis(), match(), methodCall(), namedCall(), NULL, TOKEN_DOT, and TOKEN_NAME.
testExitLoop()
static void testExitLoop (Compiler * compiler) static
Definition at line 2979 of file wren_compiler.c.
 {
   compiler->loop->exitJump = emitJump(compiler, CODE_JUMP_IF);
 }
References emitJump().
Referenced by forStatement(), and whileStatement().
this_()
static void this_ (Compiler * compiler, bool canAssign) static
Definition at line 2495 of file wren_compiler.c.
 {
   if (getEnclosingClass(compiler) == NULL)
   {
     error(compiler, "Cannot use 'this' outside of a method.");
     return;
   }
   loadThis(compiler);
 }
References error(), getEnclosingClass(), loadThis(), and NULL.
twoCharToken()
static void twoCharToken (Parser * parser, char c, TokenType two, TokenType one) static
Definition at line 684 of file wren_compiler.c.
 {
   makeToken(parser, matchChar(parser, c) ? two : one);
 }
References makeToken(), and matchChar().
Referenced by nextToken().
unaryOp()
static void unaryOp (Compiler * compiler, bool canAssign) static
Definition at line 2202 of file wren_compiler.c.
 {
   GrammarRule* rule = getRule(compiler->parser->previous.type);
   ignoreNewlines(compiler);
   // Compile the argument.
   parsePrecedence(compiler, (Precedence)(PREC_UNARY + 1));
   // Call the operator method on the left-hand side.
   callMethod(compiler, 0, rule->name, 1);
 }
References callMethod(), getRule(), ignoreNewlines(), parsePrecedence(), and PREC_UNARY.
unarySignature()
void unarySignature (Compiler * compiler, Signature * signature)
Definition at line 2612 of file wren_compiler.c.
 {
   // Do nothing. The name is already complete.
   signature->type = SIG_GETTER;
 }
References SIG_GETTER.
validateNumParameters()
static void validateNumParameters (Compiler * compiler, int numArgs) static
Definition at line 1826 of file wren_compiler.c.
 {
   if (numArgs == MAX_PARAMETERS + 1)
   {
     // Only show an error at exactly max + 1 so that we can keep parsing the
     // parameters and minimize cascaded errors.
     error(compiler, "Methods cannot have more than %d parameters.",
           MAX_PARAMETERS);
   }
 }
References error(), and MAX_PARAMETERS.
Referenced by finishArgumentList(), finishParameterList(), and subscript().
variableDefinition()
static void variableDefinition (Compiler * compiler) static
Definition at line 3700 of file wren_compiler.c.
 {
   // Grab its name, but don't declare it yet. A (local) variable shouldn't be
   // in scope in its own initializer.
   consume(compiler, TOKEN_NAME, "Expect variable name.");
   Token nameToken = compiler->parser->previous;
   // Compile the initializer.
   if (match(compiler, TOKEN_EQ))
   {
     ignoreNewlines(compiler);
     expression(compiler);
   }
   else
   {
     // Default initialize it to null.
     null(compiler, false);
   }
   // Now put it in scope.
   int symbol = declareVariable(compiler, &nameToken);
   defineVariable(compiler, symbol);
 }
References consume(), declareVariable(), defineVariable(), expression(), ignoreNewlines(), match(), TOKEN_EQ, and TOKEN_NAME.
Referenced by definition().
whileStatement()
static void whileStatement (Compiler * compiler) static
Definition at line 3154 of file wren_compiler.c.
 {
   Loop loop;
   startLoop(compiler, &loop);
   // Compile the condition.
   consume(compiler, TOKEN_LEFT_PAREN, "Expect '(' after 'while'.");
   expression(compiler);
   consume(compiler, TOKEN_RIGHT_PAREN, "Expect ')' after while condition.");
   testExitLoop(compiler);
   loopBody(compiler);
   endLoop(compiler);
 }
References consume(), endLoop(), expression(), loop(), loopBody(), startLoop(), testExitLoop(), TOKEN_LEFT_PAREN, and TOKEN_RIGHT_PAREN.
Referenced by statement().
wrenBindMethodCode()
void wrenBindMethodCode (ObjClass * classObj, ObjFn * fn)
Definition at line 3843 of file wren_compiler.c.
 {
   int ip = 0;
   for (;;)
   {
     Code instruction = (Code)fn->code.data[ip];
     switch (instruction)
     {
       case CODE_LOAD_FIELD:
       case CODE_STORE_FIELD:
       case CODE_LOAD_FIELD_THIS:
       case CODE_STORE_FIELD_THIS:
         // Shift this class's fields down past the inherited ones. We don't
         // check for overflow here because we'll see if the number of fields
         // overflows when the subclass is created.
         fn->code.data[ip + 1] += classObj->superclass->numFields;
         break;
       case CODE_SUPER_0:
       case CODE_SUPER_1:
       case CODE_SUPER_2:
       case CODE_SUPER_3:
       case CODE_SUPER_4:
       case CODE_SUPER_5:
       case CODE_SUPER_6:
       case CODE_SUPER_7:
       case CODE_SUPER_8:
       case CODE_SUPER_9:
       case CODE_SUPER_10:
       case CODE_SUPER_11:
       case CODE_SUPER_12:
       case CODE_SUPER_13:
       case CODE_SUPER_14:
       case CODE_SUPER_15:
       case CODE_SUPER_16:
       {
         // Fill in the constant slot with a reference to the superclass.
         int constant = (fn->code.data[ip + 3] << 8) | fn->code.data[ip + 4];
         fn->constants.data[constant] = OBJ_VAL(classObj->superclass);
         break;
       }
       case CODE_CLOSURE:
       {
         // Bind the nested closure too.
         int constant = (fn->code.data[ip + 1] << 8) | fn->code.data[ip + 2];
         wrenBindMethodCode(classObj, AS_FN(fn->constants.data[constant]));
         break;
       }
       case CODE_END:
         return;
       default:
         // Other instructions are unaffected, so just skip over them.
         break;
     }
     ip += 1 + getByteCountForArguments(fn->code.data, fn->constants.data, ip);
   }
 }
References AS_FN, fn, getByteCountForArguments(), sObjClass::numFields, OBJ_VAL, and sObjClass::superclass.
Referenced by bindMethod().
wrenCompile()
ObjFn* wrenCompile (WrenVM * vm, ObjModule * module, const char * source, bool isExpression, bool printErrors)
Definition at line 3762 of file wren_compiler.c.
 {
   // Skip the UTF-8 BOM if there is one.
   if (strncmp(source, "\xEF\xBB\xBF", 3) == 0) source += 3;
   Parser parser;
   parser.vm = vm;
   parser.module = module;
   parser.source = source;
   parser.tokenStart = source;
   parser.currentChar = source;
   parser.currentLine = 1;
   parser.numParens = 0;
   // Zero-init the current token. This will get copied to previous when
   // nextToken() is called below.
   parser.next.type = TOKEN_ERROR;
   parser.next.start = source;
   parser.next.length = 0;
   parser.next.line = 0;
   parser.next.value = UNDEFINED_VAL;
   parser.printErrors = printErrors;
   parser.hasError = false;
   // Read the first token into next
   nextToken(&parser);
   // Copy next -> current
   nextToken(&parser);
   int numExistingVariables = module->variables.count;
   Compiler compiler;
   initCompiler(&compiler, &parser, NULL, false);
   ignoreNewlines(&compiler);
   if (isExpression)
   {
     expression(&compiler);
     consume(&compiler, TOKEN_EOF, "Expect end of expression.");
   }
   else
   {
     while (!match(&compiler, TOKEN_EOF))
     {
       definition(&compiler);
       // If there is no newline, it must be the end of file on the same line.
       if (!matchLine(&compiler))
       {
         consume(&compiler, TOKEN_EOF, "Expect end of file.");
         break;
       }
     }
     emitOp(&compiler, CODE_END_MODULE);
   }
   emitOp(&compiler, CODE_RETURN);
   // See if there are any implicitly declared module-level variables that never
   // got an explicit definition. They will have values that are numbers
   // indicating the line where the variable was first used.
   for (int i = numExistingVariables; i < parser.module->variables.count; i++)
   {
     if (IS_NUM(parser.module->variables.data[i]))
     {
       // Synthesize a token for the original use site.
       parser.previous.type = TOKEN_NAME;
       parser.previous.start = parser.module->variableNames.data[i]->value;
       parser.previous.length = parser.module->variableNames.data[i]->length;
       parser.previous.line = (int)AS_NUM(parser.module->variables.data[i]);
       error(&compiler, "Variable is used but not defined.");
     }
   }
   return endCompiler(&compiler, "(script)", 8);
 }
References AS_NUM, consume(), definition(), emitOp(), endCompiler(), error(), expression(), ignoreNewlines(), initCompiler(), IS_NUM, match(), matchLine(), nextToken(), NULL, source, TOKEN_EOF, TOKEN_ERROR, TOKEN_NAME, UNDEFINED_VAL, and ObjModule::variables.
Referenced by compileInModule().
wrenMarkCompiler()
void wrenMarkCompiler (WrenVM * vm, Compiler * compiler)
Definition at line 3904 of file wren_compiler.c.
 {
   wrenGrayValue(vm, compiler->parser->current.value);
   wrenGrayValue(vm, compiler->parser->previous.value);
   wrenGrayValue(vm, compiler->parser->next.value);
   // Walk up the parent chain to mark the outer compilers too. The VM only
   // tracks the innermost one.
   do
   {
     wrenGrayObj(vm, (Obj*)compiler->fn);
     wrenGrayObj(vm, (Obj*)compiler->constants);
     wrenGrayObj(vm, (Obj*)compiler->attributes);
     if (compiler->enclosingClass != NULL)
     {
       wrenBlackenSymbolTable(vm, &compiler->enclosingClass->fields);
       if(compiler->enclosingClass->methodAttributes != NULL)
       {
         wrenGrayObj(vm, (Obj*)compiler->enclosingClass->methodAttributes);
       }
       if(compiler->enclosingClass->classAttributes != NULL)
       {
         wrenGrayObj(vm, (Obj*)compiler->enclosingClass->classAttributes);
       }
     }
     compiler = compiler->parent;
   }
   while (compiler != NULL);
 }
References NULL, wrenBlackenSymbolTable(), wrenGrayObj(), and wrenGrayValue().
Referenced by wrenCollectGarbage().
Variable Documentation
keywords
Keyword keywords[] static
Initial value:
=
{
  {"break",     5, TOKEN_BREAK},
  {"continue",  8, TOKEN_CONTINUE},
  {"class",     5, TOKEN_CLASS},
  {"construct", 9, TOKEN_CONSTRUCT},
  {"else",      4, TOKEN_ELSE},
  {"false",     5, TOKEN_FALSE},
  {"for",       3, TOKEN_FOR},
  {"foreign",   7, TOKEN_FOREIGN},
  {"if",        2, TOKEN_IF},
  {"import",    6, TOKEN_IMPORT},
  {"as",        2, TOKEN_AS},
  {"in",        2, TOKEN_IN},
  {"is",        2, TOKEN_IS},
  {"null",      4, TOKEN_NULL},
  {"return",    6, TOKEN_RETURN},
  {"static",    6, TOKEN_STATIC},
  {"super",     5, TOKEN_SUPER},
  {"this",      4, TOKEN_THIS},
  {"true",      4, TOKEN_TRUE},
  {"var",       3, TOKEN_VAR},
  {"while",     5, TOKEN_WHILE},
  {NULL,        0, TOKEN_EOF}
}
Definition at line 600 of file wren_compiler.c.
Referenced by readName().
rules
GrammarRule rules[]
Definition at line 2749 of file wren_compiler.c.
Referenced by getRule(), method(), and parsePrecedence().
stackEffects
const int stackEffects[] static
Initial value:
= {
#define OPCODE(_, effect)
}
Definition at line 414 of file wren_compiler.c.
Referenced by emitOp().