ERIS CORE: wren_vm.c File Reference
wren_vm.c File Reference
#include <stdarg.h>
#include <string.h>
#include "wren.h"
#include "wren_common.h"
#include "wren_compiler.h"
#include "wren_core.h"
#include "wren_debug.h"
#include "wren_primitive.h"
#include "wren_vm.h"
#include "wren_opt_meta.h"
#include "wren_opt_random.h"
#include "wren_opcodes.h"
Macros
#define CASE_CODE(name) code_##name
#define DEBUG_TRACE_INSTRUCTIONS() do { } while (false)
#define DISPATCH()
#define DROP() (fiber->stackTop--)
#define INTERPRET_LOOP DISPATCH();
#define LOAD_FRAME()
#define OPCODE(name, _) &&code_##name,
#define PEEK() (*(fiber->stackTop - 1))
#define PEEK2() (*(fiber->stackTop - 2))
#define POP() (*(--fiber->stackTop))
#define PUSH(value) (*fiber->stackTop++ = value)
#define READ_BYTE() (*ip++)
#define READ_SHORT() (ip += 2, (uint16_t)((ip[-2] << 8) | ip[-1]))
#define RUNTIME_ERROR()
#define STORE_FRAME() frame->ip = ip
Functions
static void bindForeignClass (WrenVM *vm, ObjClass *classObj, ObjModule *module)
static void bindMethod (WrenVM *vm, int methodType, int symbol, ObjModule *module, ObjClass *classObj, Value methodValue)
static void callForeign (WrenVM *vm, ObjFiber *fiber, WrenForeignMethodFn foreign, int numArgs)
static ObjUpvalue * captureUpvalue (WrenVM *vm, ObjFiber *fiber, Value *local)
static bool checkArity (WrenVM *vm, Value value, int numArgs)
static void closeUpvalues (ObjFiber *fiber, Value *last)
static ObjClosure * compileInModule (WrenVM *vm, Value name, const char *source, bool isExpression, bool printErrors)
static void createClass (WrenVM *vm, int numFields, ObjModule *module)
static void createForeign (WrenVM *vm, ObjFiber *fiber, Value *stack)
static void * defaultReallocate (void *ptr, size_t newSize, void *_)
static void endClass (WrenVM *vm)
static WrenForeignMethodFn findForeignMethod (WrenVM *vm, const char *moduleName, const char *className, bool isStatic, const char *signature)
static ObjModule * getModule (WrenVM *vm, Value name)
static Value getModuleVariable (WrenVM *vm, ObjModule *module, Value variableName)
static Value importModule (WrenVM *vm, Value name)
static void methodNotFound (WrenVM *vm, ObjClass *classObj, int symbol)
static Value resolveModule (WrenVM *vm, Value name)
static WrenInterpretResult runInterpreter (WrenVM *vm, register ObjFiber *fiber)
static void runtimeError (WrenVM *vm)
static void setSlot (WrenVM *vm, int slot, Value value)
static void validateApiSlot (WrenVM *vm, int slot)
static Value validateSuperclass (WrenVM *vm, Value name, Value superclassValue, int numFields)
void wrenAbortFiber (WrenVM *vm, int slot)
WrenInterpretResult wrenCall (WrenVM *vm, WrenHandle *method)
void wrenCollectGarbage (WrenVM *vm)
ObjClosure * wrenCompileSource (WrenVM *vm, const char *module, const char *source, bool isExpression, bool printErrors)
int wrenDeclareVariable (WrenVM *vm, ObjModule *module, const char *name, size_t length, int line)
int wrenDefineVariable (WrenVM *vm, ObjModule *module, const char *name, size_t length, Value value, int *line)
void wrenEnsureSlots (WrenVM *vm, int numSlots)
void wrenFinalizeForeign (WrenVM *vm, ObjForeign *foreign)
Value wrenFindVariable (WrenVM *vm, ObjModule *module, const char *name)
void wrenFreeVM (WrenVM *vm)
int wrenGetListCount (WrenVM *vm, int slot)
void wrenGetListElement (WrenVM *vm, int listSlot, int index, int elementSlot)
bool wrenGetMapContainsKey (WrenVM *vm, int mapSlot, int keySlot)
int wrenGetMapCount (WrenVM *vm, int slot)
void wrenGetMapValue (WrenVM *vm, int mapSlot, int keySlot, int valueSlot)
Value wrenGetModuleVariable (WrenVM *vm, Value moduleName, Value variableName)
bool wrenGetSlotBool (WrenVM *vm, int slot)
const char * wrenGetSlotBytes (WrenVM *vm, int slot, int *length)
int wrenGetSlotCount (WrenVM *vm)
double wrenGetSlotDouble (WrenVM *vm, int slot)
void * wrenGetSlotForeign (WrenVM *vm, int slot)
WrenHandle * wrenGetSlotHandle (WrenVM *vm, int slot)
const char * wrenGetSlotString (WrenVM *vm, int slot)
WrenType wrenGetSlotType (WrenVM *vm, int slot)
void * wrenGetUserData (WrenVM *vm)
void wrenGetVariable (WrenVM *vm, const char *module, const char *name, int slot)
int wrenGetVersionNumber ()
bool wrenHasModule (WrenVM *vm, const char *module)
bool wrenHasVariable (WrenVM *vm, const char *module, const char *name)
void wrenInitConfiguration (WrenConfiguration *config)
void wrenInsertInList (WrenVM *vm, int listSlot, int index, int elementSlot)
WrenInterpretResult wrenInterpret (WrenVM *vm, const char *module, const char *source)
WrenHandle * wrenMakeCallHandle (WrenVM *vm, const char *signature)
WrenHandle * wrenMakeHandle (WrenVM *vm, Value value)
WrenVM * wrenNewVM (WrenConfiguration *config)
void wrenPopRoot (WrenVM *vm)
void wrenPushRoot (WrenVM *vm, Obj *obj)
void * wrenReallocate (WrenVM *vm, void *memory, size_t oldSize, size_t newSize)
void wrenReleaseHandle (WrenVM *vm, WrenHandle *handle)
void wrenRemoveMapValue (WrenVM *vm, int mapSlot, int keySlot, int removedValueSlot)
void wrenSetListElement (WrenVM *vm, int listSlot, int index, int elementSlot)
void wrenSetMapValue (WrenVM *vm, int mapSlot, int keySlot, int valueSlot)
void wrenSetSlotBool (WrenVM *vm, int slot, bool value)
void wrenSetSlotBytes (WrenVM *vm, int slot, const char *bytes, size_t length)
void wrenSetSlotDouble (WrenVM *vm, int slot, double value)
void wrenSetSlotHandle (WrenVM *vm, int slot, WrenHandle *handle)
void * wrenSetSlotNewForeign (WrenVM *vm, int slot, int classSlot, size_t size)
void wrenSetSlotNewList (WrenVM *vm, int slot)
void wrenSetSlotNewMap (WrenVM *vm, int slot)
void wrenSetSlotNull (WrenVM *vm, int slot)
void wrenSetSlotString (WrenVM *vm, int slot, const char *text)
void wrenSetUserData (WrenVM *vm, void *userData)
Macro Definition Documentation
CASE_CODE
#define CASE_CODE (name) code_##name
DEBUG_TRACE_INSTRUCTIONS
#define DEBUG_TRACE_INSTRUCTIONS () do { } while (false)
DISPATCH
#define DISPATCH ()
Value:
      do                                                                       \
      {                                                                        \
        DEBUG_TRACE_INSTRUCTIONS();                                            \
        goto *dispatchTable[instruction = (Code)READ_BYTE()];                  \
      } while (false)
DROP
#define DROP () (fiber->stackTop--)
INTERPRET_LOOP
#define INTERPRET_LOOP DISPATCH();
LOAD_FRAME
#define LOAD_FRAME ()
Value:
      do                                                                       \
      {                                                                        \
        frame = &fiber->frames[fiber->numFrames - 1];                          \
        stackStart = frame->stackStart;                                        \
        ip = frame->ip;                                                        \
        fn = frame->closure->fn;                                               \
      } while (false)
OPCODE
#define OPCODE (name, _) &&code_##name,
PEEK
#define PEEK () (*(fiber->stackTop - 1))
PEEK2
#define PEEK2 () (*(fiber->stackTop - 2))
POP
#define POP () (*(--fiber->stackTop))
PUSH
#define PUSH (value) (*fiber->stackTop++ = value)
READ_BYTE
#define READ_BYTE () (*ip++)
READ_SHORT
#define READ_SHORT () (ip += 2, (uint16_t)((ip[-2] << 8) | ip[-1]))
RUNTIME_ERROR
#define RUNTIME_ERROR ()
Value:
      do                                                                       \
      {                                                                        \
        STORE_FRAME();                                                         \
        runtimeError(vm);                                                      \
        if (vm->fiber == NULL) return WREN_RESULT_RUNTIME_ERROR;               \
        fiber = vm->fiber;                                                     \
        LOAD_FRAME();                                                          \
        DISPATCH();                                                            \
      } while (false)
STORE_FRAME
#define STORE_FRAME () frame->ip = ip
Function Documentation
bindForeignClass()
static void bindForeignClass (WrenVM * vm, ObjClass * classObj, ObjModule * module) static
Definition at line 562 of file wren_vm.c.
 {
   WrenForeignClassMethods methods;
   methods.allocate = NULL;
   methods.finalize = NULL;
   // Check the optional built-in module first so the host can override it.
   if (vm->config.bindForeignClassFn != NULL)
   {
     methods = vm->config.bindForeignClassFn(vm, module->name->value,
                                             classObj->name->value);
   }
   // If the host didn't provide it, see if it's a built in optional module.
   if (methods.allocate == NULL && methods.finalize == NULL)
   {
 #if WREN_OPT_RANDOM
     if (strcmp(module->name->value, "random") == 0)
     {
       methods = wrenRandomBindForeignClass(vm, module->name->value,
                                            classObj->name->value);
     }
 #endif
   }
   Method method;
   method.type = METHOD_FOREIGN;
   // Add the symbol even if there is no allocator so we can ensure that the
   // symbol itself is always in the symbol table.
   int symbol = wrenSymbolTableEnsure(vm, &vm->methodNames, "<allocate>", 10);
   if (methods.allocate != NULL)
   {
     method.as.foreign = methods.allocate;
     wrenBindMethod(vm, classObj, symbol, method);
   }
   // Add the symbol even if there is no finalizer so we can ensure that the
   // symbol itself is always in the symbol table.
   symbol = wrenSymbolTableEnsure(vm, &vm->methodNames, "<finalize>", 10);
   if (methods.finalize != NULL)
   {
     method.as.foreign = (WrenForeignMethodFn)methods.finalize;
     wrenBindMethod(vm, classObj, symbol, method);
   }
 }
References WrenForeignClassMethods::allocate, WrenConfiguration::bindForeignClassFn, WrenVM::config, WrenForeignClassMethods::finalize, method(), METHOD_FOREIGN, WrenVM::methodNames, ObjModule::name, sObjClass::name, NULL, sObjString::value, wrenBindMethod(), wrenRandomBindForeignClass(), and wrenSymbolTableEnsure().
Referenced by createClass().
bindMethod()
static void bindMethod (WrenVM * vm, int methodType, int symbol, ObjModule * module, ObjClass * classObj, Value methodValue) static
Definition at line 348 of file wren_vm.c.
 {
   const char* className = classObj->name->value;
   if (methodType == CODE_METHOD_STATIC) classObj = classObj->obj.classObj;
   Method method;
   if (IS_STRING(methodValue))
   {
     const char* name = AS_CSTRING(methodValue);
     method.type = METHOD_FOREIGN;
     method.as.foreign = findForeignMethod(vm, module->name->value,
                                           className,
                                           methodType == CODE_METHOD_STATIC,
                                           name);
     if (method.as.foreign == NULL)
     {
       vm->fiber->error = wrenStringFormat(vm,
           "Could not find foreign method '@' for class $ in module '$'.",
           methodValue, classObj->name->value, module->name->value);
       return;
     }
   }
   else
   {
     method.as.closure = AS_CLOSURE(methodValue);
     method.type = METHOD_BLOCK;
     // Patch up the bytecode now that we know the superclass.
     wrenBindMethodCode(classObj, method.as.closure->fn);
   }
   wrenBindMethod(vm, classObj, symbol, method);
 }
References AS_CLOSURE, AS_CSTRING, sObj::classObj, sObjFiber::error, WrenVM::fiber, findForeignMethod(), IS_STRING, method(), METHOD_BLOCK, METHOD_FOREIGN, name, ObjModule::name, sObjClass::name, NULL, sObjClass::obj, sObjString::value, wrenBindMethod(), wrenBindMethodCode(), and wrenStringFormat().
Referenced by runInterpreter().
callForeign()
static void callForeign (WrenVM * vm, ObjFiber * fiber, WrenForeignMethodFn foreign, int numArgs) static
Definition at line 384 of file wren_vm.c.
 {
   ASSERT(vm->apiStack == NULL, "Cannot already be in foreign call.");
   vm->apiStack = fiber->stackTop - numArgs;
   foreign(vm);
   // Discard the stack slots for the arguments and temporaries but leave one
   // for the result.
   fiber->stackTop = vm->apiStack + 1;
   vm->apiStack = NULL;
 }
References WrenVM::apiStack, ASSERT, fiber, and NULL.
Referenced by runInterpreter().
captureUpvalue()
static ObjUpvalue* captureUpvalue (WrenVM * vm, ObjFiber * fiber, Value * local) static
Definition at line 244 of file wren_vm.c.
 {
   // If there are no open upvalues at all, we must need a new one.
   if (fiber->openUpvalues == NULL)
   {
     fiber->openUpvalues = wrenNewUpvalue(vm, local);
     return fiber->openUpvalues;
   }
   ObjUpvalue* prevUpvalue = NULL;
   ObjUpvalue* upvalue = fiber->openUpvalues;
   // Walk towards the bottom of the stack until we find a previously existing
   // upvalue or pass where it should be.
   while (upvalue != NULL && upvalue->value > local)
   {
     prevUpvalue = upvalue;
     upvalue = upvalue->next;
   }
   // Found an existing upvalue for this local.
   if (upvalue != NULL && upvalue->value == local) return upvalue;
   // We've walked past this local on the stack, so there must not be an
   // upvalue for it already. Make a new one and link it in in the right
   // place to keep the list sorted.
   ObjUpvalue* createdUpvalue = wrenNewUpvalue(vm, local);
   if (prevUpvalue == NULL)
   {
     // The new one is the first one in the list.
     fiber->openUpvalues = createdUpvalue;
   }
   else
   {
     prevUpvalue->next = createdUpvalue;
   }
   createdUpvalue->next = upvalue;
   return createdUpvalue;
 }
References fiber, sObjUpvalue::next, NULL, sObjUpvalue::value, and wrenNewUpvalue().
Referenced by runInterpreter().
checkArity()
static bool checkArity (WrenVM * vm, Value value, int numArgs) inline static
Definition at line 809 of file wren_vm.c.
 {
   ASSERT(IS_CLOSURE(value), "Receiver must be a closure.");
   ObjFn* fn = AS_CLOSURE(value)->fn;
   // We only care about missing arguments, not extras. The "- 1" is because
   // numArgs includes the receiver, the function itself, which we don't want to
   // count.
   if (numArgs - 1 >= fn->arity) return true;
   vm->fiber->error = CONST_STRING(vm, "Function expects more arguments.");
   return false;
 }
References AS_CLOSURE, ASSERT, CONST_STRING, sObjFiber::error, WrenVM::fiber, fn, and IS_CLOSURE.
Referenced by runInterpreter().
closeUpvalues()
static void closeUpvalues (ObjFiber * fiber, Value * last) static
Definition at line 287 of file wren_vm.c.
 {
   while (fiber->openUpvalues != NULL &&
          fiber->openUpvalues->value >= last)
   {
     ObjUpvalue* upvalue = fiber->openUpvalues;
     // Move the value into the upvalue itself and point the upvalue to it.
     upvalue->closed = *upvalue->value;
     upvalue->value = &upvalue->closed;
     // Remove it from the open upvalue list.
     fiber->openUpvalues = upvalue->next;
   }
 }
References sObjUpvalue::closed, fiber, sObjUpvalue::next, NULL, and sObjUpvalue::value.
Referenced by runInterpreter().
compileInModule()
static ObjClosure* compileInModule (WrenVM * vm, Value name, const char * source, bool isExpression, bool printErrors) static
Definition at line 453 of file wren_vm.c.
 {
   // See if the module has already been loaded.
   ObjModule* module = getModule(vm, name);
   if (module == NULL)
   {
     module = wrenNewModule(vm, AS_STRING(name));
     // It's possible for the wrenMapSet below to resize the modules map,
     // and trigger a GC while doing so. When this happens it will collect
     // the module we've just created. Once in the map it is safe.
     wrenPushRoot(vm, (Obj*)module);
     // Store it in the VM's module registry so we don't load the same module
     // multiple times.
     wrenMapSet(vm, vm->modules, name, OBJ_VAL(module));
     wrenPopRoot(vm);
     // Implicitly import the core module.
     ObjModule* coreModule = getModule(vm, NULL_VAL);
     for (int i = 0; i < coreModule->variables.count; i++)
     {
       wrenDefineVariable(vm, module,
                          coreModule->variableNames.data[i]->value,
                          coreModule->variableNames.data[i]->length,
                          coreModule->variables.data[i], NULL);
     }
   }
   ObjFn* fn = wrenCompile(vm, module, source, isExpression, printErrors);
   if (fn == NULL)
   {
     // TODO: Should we still store the module even if it didn't compile?
     return NULL;
   }
   // Functions are always wrapped in closures.
   wrenPushRoot(vm, (Obj*)fn);
   ObjClosure* closure = wrenNewClosure(vm, fn);
   wrenPopRoot(vm); // fn.
   return closure;
 }
References AS_STRING, fn, getModule(), WrenVM::modules, name, NULL, NULL_VAL, OBJ_VAL, source, ObjModule::variableNames, ObjModule::variables, wrenCompile(), wrenDefineVariable(), wrenMapSet(), wrenNewClosure(), wrenNewModule(), wrenPopRoot(), and wrenPushRoot().
Referenced by importModule(), and wrenCompileSource().
createClass()
static void createClass (WrenVM * vm, int numFields, ObjModule * module) static
Definition at line 638 of file wren_vm.c.
 {
   // Pull the name and superclass off the stack.
   Value name = vm->fiber->stackTop[-2];
   Value superclass = vm->fiber->stackTop[-1];
   // We have two values on the stack and we are going to leave one, so discard
   // the other slot.
   vm->fiber->stackTop--;
   vm->fiber->error = validateSuperclass(vm, name, superclass, numFields);
   if (wrenHasError(vm->fiber)) return;
   ObjClass* classObj = wrenNewClass(vm, AS_CLASS(superclass), numFields,
                                     AS_STRING(name));
   vm->fiber->stackTop[-1] = OBJ_VAL(classObj);
   if (numFields == -1) bindForeignClass(vm, classObj, module);
 }
References AS_CLASS, AS_STRING, bindForeignClass(), sObjFiber::error, WrenVM::fiber, name, OBJ_VAL, sObjFiber::stackTop, validateSuperclass(), wrenHasError(), and wrenNewClass().
Referenced by runInterpreter().
createForeign()
static void createForeign (WrenVM * vm, ObjFiber * fiber, Value * stack) static
Definition at line 658 of file wren_vm.c.
 {
   ObjClass* classObj = AS_CLASS(stack[0]);
   ASSERT(classObj->numFields == -1, "Class must be a foreign class.");
   // TODO: Don't look up every time.
   int symbol = wrenSymbolTableFind(&vm->methodNames, "<allocate>", 10);
   ASSERT(symbol != -1, "Should have defined <allocate> symbol.");
   ASSERT(classObj->methods.count > symbol, "Class should have allocator.");
   Method* method = &classObj->methods.data[symbol];
   ASSERT(method->type == METHOD_FOREIGN, "Allocator should be foreign.");
   // Pass the constructor arguments to the allocator as well.
   ASSERT(vm->apiStack == NULL, "Cannot already be in foreign call.");
   vm->apiStack = stack;
   method->as.foreign(vm);
   vm->apiStack = NULL;
 }
References WrenVM::apiStack, AS_CLASS, ASSERT, method(), METHOD_FOREIGN, WrenVM::methodNames, sObjClass::methods, NULL, sObjClass::numFields, and wrenSymbolTableFind().
Referenced by runInterpreter().
defaultReallocate()
static void* defaultReallocate (void * ptr, size_t newSize, void * _) static
Definition at line 28 of file wren_vm.c.
 {
   if (newSize == 0)
   {
     free(ptr);
     return NULL;
   }
   return realloc(ptr, newSize);
 }
References NULL.
Referenced by wrenInitConfiguration(), and wrenNewVM().
endClass()
static void endClass (WrenVM * vm) static
Definition at line 618 of file wren_vm.c.
 {
   // Pull the attributes and class off the stack
   Value attributes = vm->fiber->stackTop[-2];
   Value classValue = vm->fiber->stackTop[-1];
   // Remove the stack items
   vm->fiber->stackTop -= 2;
   ObjClass* classObj = AS_CLASS(classValue);
     classObj->attributes = attributes;
 }
References AS_CLASS, sObjClass::attributes, WrenVM::fiber, and sObjFiber::stackTop.
Referenced by runInterpreter().
findForeignMethod()
static WrenForeignMethodFn findForeignMethod (WrenVM * vm, const char * moduleName, const char * className, bool isStatic, const char * signature) static
Definition at line 307 of file wren_vm.c.
 {
   WrenForeignMethodFn method = NULL;
   if (vm->config.bindForeignMethodFn != NULL)
   {
     method = vm->config.bindForeignMethodFn(vm, moduleName, className, isStatic,
                                             signature);
   }
   // If the host didn't provide it, see if it's an optional one.
   if (method == NULL)
   {
 #if WREN_OPT_META
     if (strcmp(moduleName, "meta") == 0)
     {
       method = wrenMetaBindForeignMethod(vm, className, isStatic, signature);
     }
 #endif
 #if WREN_OPT_RANDOM
     if (strcmp(moduleName, "random") == 0)
     {
       method = wrenRandomBindForeignMethod(vm, className, isStatic, signature);
     }
 #endif
   }
   return method;
 }
References WrenConfiguration::bindForeignMethodFn, WrenVM::config, method(), NULL, wrenMetaBindForeignMethod(), and wrenRandomBindForeignMethod().
Referenced by bindMethod().
getModule()
static ObjModule* getModule (WrenVM * vm, Value name) static
Definition at line 447 of file wren_vm.c.
 {
   Value moduleValue = wrenMapGet(vm->modules, name);
   return !IS_UNDEFINED(moduleValue) ? AS_MODULE(moduleValue) : NULL;
 }
References AS_MODULE, IS_UNDEFINED, WrenVM::modules, name, NULL, and wrenMapGet().
Referenced by compileInModule(), wrenGetModuleVariable(), wrenGetVariable(), wrenHasModule(), and wrenHasVariable().
getModuleVariable()
static Value getModuleVariable (WrenVM * vm, ObjModule * module, Value variableName) static
Definition at line 789 of file wren_vm.c.
 {
   ObjString* variable = AS_STRING(variableName);
   uint32_t variableEntry = wrenSymbolTableFind(&module->variableNames,
                                                variable->value,
                                                variable->length);
   // It's a runtime error if the imported variable does not exist.
   if (variableEntry != UINT32_MAX)
   {
     return module->variables.data[variableEntry];
   }
   vm->fiber->error = wrenStringFormat(vm,
       "Could not find a variable named '@' in module '@'.",
       variableName, OBJ_VAL(module->name));
   return NULL_VAL;
 }
References AS_STRING, sObjFiber::error, WrenVM::fiber, sObjString::length, ObjModule::name, NULL_VAL, OBJ_VAL, sObjString::value, ObjModule::variableNames, ObjModule::variables, wrenStringFormat(), and wrenSymbolTableFind().
Referenced by runInterpreter(), and wrenGetModuleVariable().
importModule()
static Value importModule (WrenVM * vm, Value name) static
Definition at line 731 of file wren_vm.c.
 {
   name = resolveModule(vm, name);
   // If the module is already loaded, we don't need to do anything.
   Value existing = wrenMapGet(vm->modules, name);
   if (!IS_UNDEFINED(existing)) return existing;
   wrenPushRoot(vm, AS_OBJ(name));
   WrenLoadModuleResult result = {0};
   const char* source = NULL;
   // Let the host try to provide the module.
   if (vm->config.loadModuleFn != NULL)
   {
     result = vm->config.loadModuleFn(vm, AS_CSTRING(name));
   }
   // If the host didn't provide it, see if it's a built in optional module.
   if (result.source == NULL)
   {
     result.onComplete = NULL;
     ObjString* nameString = AS_STRING(name);
 #if WREN_OPT_META
     if (strcmp(nameString->value, "meta") == 0) result.source = wrenMetaSource();
 #endif
 #if WREN_OPT_RANDOM
     if (strcmp(nameString->value, "random") == 0) result.source = wrenRandomSource();
 #endif
   }
   if (result.source == NULL)
   {
     vm->fiber->error = wrenStringFormat(vm, "Could not load module '@'.", name);
     wrenPopRoot(vm); // name.
     return NULL_VAL;
   }
   ObjClosure* moduleClosure = compileInModule(vm, name, result.source, false, true);
   // Now that we're done, give the result back in case there's cleanup to do.
   if(result.onComplete) result.onComplete(vm, AS_CSTRING(name), result);
   if (moduleClosure == NULL)
   {
     vm->fiber->error = wrenStringFormat(vm,
                                         "Could not compile module '@'.", name);
     wrenPopRoot(vm); // name.
     return NULL_VAL;
   }
   wrenPopRoot(vm); // name.
   // Return the closure that executes the module.
   return OBJ_VAL(moduleClosure);
 }
References AS_CSTRING, AS_OBJ, AS_STRING, compileInModule(), WrenVM::config, sObjFiber::error, WrenVM::fiber, IS_UNDEFINED, WrenConfiguration::loadModuleFn, WrenVM::modules, name, NULL, NULL_VAL, OBJ_VAL, WrenLoadModuleResult::onComplete, resolveModule(), source, WrenLoadModuleResult::source, sObjString::value, wrenMapGet(), wrenMetaSource(), wrenPopRoot(), wrenPushRoot(), wrenRandomSource(), and wrenStringFormat().
Referenced by runInterpreter().
methodNotFound()
static void methodNotFound (WrenVM * vm, ObjClass * classObj, int symbol) static
Definition at line 438 of file wren_vm.c.
 {
   vm->fiber->error = wrenStringFormat(vm, "@ does not implement '$'.",
       OBJ_VAL(classObj->name), vm->methodNames.data[symbol]->value);
 }
References sObjFiber::error, WrenVM::fiber, WrenVM::methodNames, sObjClass::name, OBJ_VAL, and wrenStringFormat().
Referenced by runInterpreter().
resolveModule()
static Value resolveModule (WrenVM * vm, Value name) static
Definition at line 703 of file wren_vm.c.
 {
   // If the host doesn't care to resolve, leave the name alone.
   if (vm->config.resolveModuleFn == NULL) return name;
   ObjFiber* fiber = vm->fiber;
   ObjFn* fn = fiber->frames[fiber->numFrames - 1].closure->fn;
   ObjString* importer = fn->module->name;
   const char* resolved = vm->config.resolveModuleFn(vm, importer->value,
                                                     AS_CSTRING(name));
   if (resolved == NULL)
   {
     vm->fiber->error = wrenStringFormat(vm,
         "Could not resolve module '@' imported from '@'.",
         name, OBJ_VAL(importer));
     return NULL_VAL;
   }
   // If they resolved to the exact same string, we don't need to copy it.
   if (resolved == AS_CSTRING(name)) return name;
   // Copy the string into a Wren String object.
   name = wrenNewString(vm, resolved);
   DEALLOCATE(vm, (char*)resolved);
   return name;
 }
References AS_CSTRING, WrenVM::config, DEALLOCATE, sObjFiber::error, fiber, WrenVM::fiber, fn, name, NULL, NULL_VAL, OBJ_VAL, WrenConfiguration::resolveModuleFn, sObjString::value, wrenNewString(), and wrenStringFormat().
Referenced by importModule().
runInterpreter()
static WrenInterpretResult runInterpreter (WrenVM * vm, register ObjFiber * fiber) static
Definition at line 826 of file wren_vm.c.
 {
   // Remember the current fiber so we can find it if a GC happens.
   vm->fiber = fiber;
   fiber->state = FIBER_ROOT;
   // Hoist these into local variables. They are accessed frequently in the loop
   // but assigned less frequently. Keeping them in locals and updating them when
   // a call frame has been pushed or popped gives a large speed boost.
   register CallFrame* frame;
   register Value* stackStart;
   register uint8_t* ip;
   register ObjFn* fn;
   // These macros are designed to only be invoked within this function.
   #define PUSH(value)  (*fiber->stackTop++ = value)
   #define POP()        (*(--fiber->stackTop))
   #define DROP()       (fiber->stackTop--)
   #define PEEK()       (*(fiber->stackTop - 1))
   #define PEEK2()      (*(fiber->stackTop - 2))
   #define READ_BYTE()  (*ip++)
   #define READ_SHORT() (ip += 2, (uint16_t)((ip[-2] << 8) | ip[-1]))
   // Use this before a CallFrame is pushed to store the local variables back
   // into the current one.
   #define STORE_FRAME() frame->ip = ip
   // Use this after a CallFrame has been pushed or popped to refresh the local
   // variables.
   #define LOAD_FRAME()                                                         \
       do                                                                       \
       {                                                                        \
         frame = &fiber->frames[fiber->numFrames - 1];                          \
         stackStart = frame->stackStart;                                        \
         ip = frame->ip;                                                        \
         fn = frame->closure->fn;                                               \
       } while (false)
   // Terminates the current fiber with error string [error]. If another calling
   // fiber is willing to catch the error, transfers control to it, otherwise
   // exits the interpreter.
   #define RUNTIME_ERROR()                                                      \
       do                                                                       \
       {                                                                        \
         STORE_FRAME();                                                         \
         runtimeError(vm);                                                      \
         if (vm->fiber == NULL) return WREN_RESULT_RUNTIME_ERROR;               \
         fiber = vm->fiber;                                                     \
         LOAD_FRAME();                                                          \
         DISPATCH();                                                            \
       } while (false)
   #if WREN_DEBUG_TRACE_INSTRUCTIONS
     // Prints the stack and instruction before each instruction is executed.
     #define DEBUG_TRACE_INSTRUCTIONS()                                         \
         do                                                                     \
         {                                                                      \
           wrenDumpStack(fiber);                                                \
           wrenDumpInstruction(vm, fn, (int)(ip - fn->code.data));              \
         } while (false)
   #else
     #define DEBUG_TRACE_INSTRUCTIONS() do { } while (false)
   #endif
   #if WREN_COMPUTED_GOTO
   static void* dispatchTable[] = {
     #define OPCODE(name, _) &&code_##name,
     #include "wren_opcodes.h"
     #undef OPCODE
   };
   #define INTERPRET_LOOP    DISPATCH();
   #define CASE_CODE(name)   code_##name
   #define DISPATCH()                                                           \
       do                                                                       \
       {                                                                        \
         DEBUG_TRACE_INSTRUCTIONS();                                            \
         goto *dispatchTable[instruction = (Code)READ_BYTE()];                  \
       } while (false)
   #else
   #define INTERPRET_LOOP                                                       \
       loop:                                                                    \
         DEBUG_TRACE_INSTRUCTIONS();                                            \
         switch (instruction = (Code)READ_BYTE())
   #define CASE_CODE(name)  case CODE_##name
   #define DISPATCH()       goto loop
   #endif
   LOAD_FRAME();
   Code instruction;
   INTERPRET_LOOP
   {
     CASE_CODE(LOAD_LOCAL_0):
     CASE_CODE(LOAD_LOCAL_1):
     CASE_CODE(LOAD_LOCAL_2):
     CASE_CODE(LOAD_LOCAL_3):
     CASE_CODE(LOAD_LOCAL_4):
     CASE_CODE(LOAD_LOCAL_5):
     CASE_CODE(LOAD_LOCAL_6):
     CASE_CODE(LOAD_LOCAL_7):
     CASE_CODE(LOAD_LOCAL_8):
       PUSH(stackStart[instruction - CODE_LOAD_LOCAL_0]);
       DISPATCH();
     CASE_CODE(LOAD_LOCAL):
       PUSH(stackStart[READ_BYTE()]);
       DISPATCH();
     CASE_CODE(LOAD_FIELD_THIS):
     {
       uint8_t field = READ_BYTE();
       Value receiver = stackStart[0];
       ASSERT(IS_INSTANCE(receiver), "Receiver should be instance.");
       ObjInstance* instance = AS_INSTANCE(receiver);
       ASSERT(field < instance->obj.classObj->numFields, "Out of bounds field.");
       PUSH(instance->fields[field]);
       DISPATCH();
     }
     CASE_CODE(POP):   DROP(); DISPATCH();
     CASE_CODE(NULL):  PUSH(NULL_VAL); DISPATCH();
     CASE_CODE(FALSE): PUSH(FALSE_VAL); DISPATCH();
     CASE_CODE(TRUE):  PUSH(TRUE_VAL); DISPATCH();
     CASE_CODE(STORE_LOCAL):
       stackStart[READ_BYTE()] = PEEK();
       DISPATCH();
     CASE_CODE(CONSTANT):
       PUSH(fn->constants.data[READ_SHORT()]);
       DISPATCH();
     {
       // The opcodes for doing method and superclass calls share a lot of code.
       // However, doing an if() test in the middle of the instruction sequence
       // to handle the bit that is special to super calls makes the non-super
       // call path noticeably slower.
       //
       // Instead, we do this old school using an explicit goto to share code for
       // everything at the tail end of the call-handling code that is the same
       // between normal and superclass calls.
       int numArgs;
       int symbol;
       Value* args;
       ObjClass* classObj;
       Method* method;
     CASE_CODE(CALL_0):
     CASE_CODE(CALL_1):
     CASE_CODE(CALL_2):
     CASE_CODE(CALL_3):
     CASE_CODE(CALL_4):
     CASE_CODE(CALL_5):
     CASE_CODE(CALL_6):
     CASE_CODE(CALL_7):
     CASE_CODE(CALL_8):
     CASE_CODE(CALL_9):
     CASE_CODE(CALL_10):
     CASE_CODE(CALL_11):
     CASE_CODE(CALL_12):
     CASE_CODE(CALL_13):
     CASE_CODE(CALL_14):
     CASE_CODE(CALL_15):
     CASE_CODE(CALL_16):
       // Add one for the implicit receiver argument.
       numArgs = instruction - CODE_CALL_0 + 1;
       symbol = READ_SHORT();
       // The receiver is the first argument.
       args = fiber->stackTop - numArgs;
       classObj = wrenGetClassInline(vm, args[0]);
       goto completeCall;
     CASE_CODE(SUPER_0):
     CASE_CODE(SUPER_1):
     CASE_CODE(SUPER_2):
     CASE_CODE(SUPER_3):
     CASE_CODE(SUPER_4):
     CASE_CODE(SUPER_5):
     CASE_CODE(SUPER_6):
     CASE_CODE(SUPER_7):
     CASE_CODE(SUPER_8):
     CASE_CODE(SUPER_9):
     CASE_CODE(SUPER_10):
     CASE_CODE(SUPER_11):
     CASE_CODE(SUPER_12):
     CASE_CODE(SUPER_13):
     CASE_CODE(SUPER_14):
     CASE_CODE(SUPER_15):
     CASE_CODE(SUPER_16):
       // Add one for the implicit receiver argument.
       numArgs = instruction - CODE_SUPER_0 + 1;
       symbol = READ_SHORT();
       // The receiver is the first argument.
       args = fiber->stackTop - numArgs;
       // The superclass is stored in a constant.
       classObj = AS_CLASS(fn->constants.data[READ_SHORT()]);
       goto completeCall;
     completeCall:
       // If the class's method table doesn't include the symbol, bail.
       if (symbol >= classObj->methods.count ||
           (method = &classObj->methods.data[symbol])->type == METHOD_NONE)
       {
         methodNotFound(vm, classObj, symbol);
         RUNTIME_ERROR();
       }
       switch (method->type)
       {
         case METHOD_PRIMITIVE:
           if (method->as.primitive(vm, args))
           {
             // The result is now in the first arg slot. Discard the other
             // stack slots.
             fiber->stackTop -= numArgs - 1;
           } else {
             // An error, fiber switch, or call frame change occurred.
             STORE_FRAME();
             // If we don't have a fiber to switch to, stop interpreting.
             fiber = vm->fiber;
             if (fiber == NULL) return WREN_RESULT_SUCCESS;
             if (wrenHasError(fiber)) RUNTIME_ERROR();
             LOAD_FRAME();
           }
           break;
         case METHOD_FUNCTION_CALL:
           if (!checkArity(vm, args[0], numArgs)) {
             RUNTIME_ERROR();
             break;
           }
           STORE_FRAME();
           method->as.primitive(vm, args);
           LOAD_FRAME();
           break;
         case METHOD_FOREIGN:
           callForeign(vm, fiber, method->as.foreign, numArgs);
           if (wrenHasError(fiber)) RUNTIME_ERROR();
           break;
         case METHOD_BLOCK:
           STORE_FRAME();
           wrenCallFunction(vm, fiber, (ObjClosure*)method->as.closure, numArgs);
           LOAD_FRAME();
           break;
         case METHOD_NONE:
           UNREACHABLE();
           break;
       }
       DISPATCH();
     }
     CASE_CODE(LOAD_UPVALUE):
     {
       ObjUpvalue** upvalues = frame->closure->upvalues;
       PUSH(*upvalues[READ_BYTE()]->value);
       DISPATCH();
     }
     CASE_CODE(STORE_UPVALUE):
     {
       ObjUpvalue** upvalues = frame->closure->upvalues;
       *upvalues[READ_BYTE()]->value = PEEK();
       DISPATCH();
     }
     CASE_CODE(LOAD_MODULE_VAR):
       PUSH(fn->module->variables.data[READ_SHORT()]);
       DISPATCH();
     CASE_CODE(STORE_MODULE_VAR):
       fn->module->variables.data[READ_SHORT()] = PEEK();
       DISPATCH();
     CASE_CODE(STORE_FIELD_THIS):
     {
       uint8_t field = READ_BYTE();
       Value receiver = stackStart[0];
       ASSERT(IS_INSTANCE(receiver), "Receiver should be instance.");
       ObjInstance* instance = AS_INSTANCE(receiver);
       ASSERT(field < instance->obj.classObj->numFields, "Out of bounds field.");
       instance->fields[field] = PEEK();
       DISPATCH();
     }
     CASE_CODE(LOAD_FIELD):
     {
       uint8_t field = READ_BYTE();
       Value receiver = POP();
       ASSERT(IS_INSTANCE(receiver), "Receiver should be instance.");
       ObjInstance* instance = AS_INSTANCE(receiver);
       ASSERT(field < instance->obj.classObj->numFields, "Out of bounds field.");
       PUSH(instance->fields[field]);
       DISPATCH();
     }
     CASE_CODE(STORE_FIELD):
     {
       uint8_t field = READ_BYTE();
       Value receiver = POP();
       ASSERT(IS_INSTANCE(receiver), "Receiver should be instance.");
       ObjInstance* instance = AS_INSTANCE(receiver);
       ASSERT(field < instance->obj.classObj->numFields, "Out of bounds field.");
       instance->fields[field] = PEEK();
       DISPATCH();
     }
     CASE_CODE(JUMP):
     {
       uint16_t offset = READ_SHORT();
       ip += offset;
       DISPATCH();
     }
     CASE_CODE(LOOP):
     {
       // Jump back to the top of the loop.
       uint16_t offset = READ_SHORT();
       ip -= offset;
       DISPATCH();
     }
     CASE_CODE(JUMP_IF):
     {
       uint16_t offset = READ_SHORT();
       Value condition = POP();
       if (wrenIsFalsyValue(condition)) ip += offset;
       DISPATCH();
     }
     CASE_CODE(AND):
     {
       uint16_t offset = READ_SHORT();
       Value condition = PEEK();
       if (wrenIsFalsyValue(condition))
       {
         // Short-circuit the right hand side.
         ip += offset;
       }
       else
       {
         // Discard the condition and evaluate the right hand side.
         DROP();
       }
       DISPATCH();
     }
     CASE_CODE(OR):
     {
       uint16_t offset = READ_SHORT();
       Value condition = PEEK();
       if (wrenIsFalsyValue(condition))
       {
         // Discard the condition and evaluate the right hand side.
         DROP();
       }
       else
       {
         // Short-circuit the right hand side.
         ip += offset;
       }
       DISPATCH();
     }
     CASE_CODE(CLOSE_UPVALUE):
       // Close the upvalue for the local if we have one.
       closeUpvalues(fiber, fiber->stackTop - 1);
       DROP();
       DISPATCH();
     CASE_CODE(RETURN):
     {
       Value result = POP();
       fiber->numFrames--;
       // Close any upvalues still in scope.
       closeUpvalues(fiber, stackStart);
       // If the fiber is complete, end it.
       if (fiber->numFrames == 0)
       {
         // See if there's another fiber to return to. If not, we're done.
         if (fiber->caller == NULL)
         {
           // Store the final result value at the beginning of the stack so the
           // C API can get it.
           fiber->stack[0] = result;
           fiber->stackTop = fiber->stack + 1;
           return WREN_RESULT_SUCCESS;
         }
         ObjFiber* resumingFiber = fiber->caller;
         fiber->caller = NULL;
         fiber = resumingFiber;
         vm->fiber = resumingFiber;
         // Store the result in the resuming fiber.
         fiber->stackTop[-1] = result;
       }
       else
       {
         // Store the result of the block in the first slot, which is where the
         // caller expects it.
         stackStart[0] = result;
         // Discard the stack slots for the call frame (leaving one slot for the
         // result).
         fiber->stackTop = frame->stackStart + 1;
       }
       LOAD_FRAME();
       DISPATCH();
     }
     CASE_CODE(CONSTRUCT):
       ASSERT(IS_CLASS(stackStart[0]), "'this' should be a class.");
       stackStart[0] = wrenNewInstance(vm, AS_CLASS(stackStart[0]));
       DISPATCH();
     CASE_CODE(FOREIGN_CONSTRUCT):
       ASSERT(IS_CLASS(stackStart[0]), "'this' should be a class.");
       createForeign(vm, fiber, stackStart);
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       DISPATCH();
     CASE_CODE(CLOSURE):
     {
       // Create the closure and push it on the stack before creating upvalues
       // so that it doesn't get collected.
       ObjFn* function = AS_FN(fn->constants.data[READ_SHORT()]);
       ObjClosure* closure = wrenNewClosure(vm, function);
       PUSH(OBJ_VAL(closure));
       // Capture upvalues, if any.
       for (int i = 0; i < function->numUpvalues; i++)
       {
         uint8_t isLocal = READ_BYTE();
         uint8_t index = READ_BYTE();
         if (isLocal)
         {
           // Make an new upvalue to close over the parent's local variable.
           closure->upvalues[i] = captureUpvalue(vm, fiber,
                                                 frame->stackStart + index);
         }
         else
         {
           // Use the same upvalue as the current call frame.
           closure->upvalues[i] = frame->closure->upvalues[index];
         }
       }
       DISPATCH();
     }
     CASE_CODE(END_CLASS):
     {
       endClass(vm);
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       DISPATCH();
     }
     CASE_CODE(CLASS):
     {
       createClass(vm, READ_BYTE(), NULL);
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       DISPATCH();
     }
     CASE_CODE(FOREIGN_CLASS):
     {
       createClass(vm, -1, fn->module);
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       DISPATCH();
     }
     CASE_CODE(METHOD_INSTANCE):
     CASE_CODE(METHOD_STATIC):
     {
       uint16_t symbol = READ_SHORT();
       ObjClass* classObj = AS_CLASS(PEEK());
       Value method = PEEK2();
       bindMethod(vm, instruction, symbol, fn->module, classObj, method);
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       DROP();
       DROP();
       DISPATCH();
     }
     CASE_CODE(END_MODULE):
     {
       vm->lastModule = fn->module;
       PUSH(NULL_VAL);
       DISPATCH();
     }
     CASE_CODE(IMPORT_MODULE):
     {
       // Make a slot on the stack for the module's fiber to place the return
       // value. It will be popped after this fiber is resumed. Store the
       // imported module's closure in the slot in case a GC happens when
       // invoking the closure.
       PUSH(importModule(vm, fn->constants.data[READ_SHORT()]));
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       // If we get a closure, call it to execute the module body.
       if (IS_CLOSURE(PEEK()))
       {
         STORE_FRAME();
         ObjClosure* closure = AS_CLOSURE(PEEK());
         wrenCallFunction(vm, fiber, closure, 1);
         LOAD_FRAME();
       }
       else
       {
         // The module has already been loaded. Remember it so we can import
         // variables from it if needed.
         vm->lastModule = AS_MODULE(PEEK());
       }
       DISPATCH();
     }
     CASE_CODE(IMPORT_VARIABLE):
     {
       Value variable = fn->constants.data[READ_SHORT()];
       ASSERT(vm->lastModule != NULL, "Should have already imported module.");
       Value result = getModuleVariable(vm, vm->lastModule, variable);
       if (wrenHasError(fiber)) RUNTIME_ERROR();
       PUSH(result);
       DISPATCH();
     }
     CASE_CODE(END):
       // A CODE_END should always be preceded by a CODE_RETURN. If we get here,
       // the compiler generated wrong code.
       UNREACHABLE();
   }
   // We should only exit this function from an explicit return from CODE_RETURN
   // or a runtime error.
   UNREACHABLE();
   return WREN_RESULT_RUNTIME_ERROR;
   #undef READ_BYTE
   #undef READ_SHORT
 }
References AS_CLASS, AS_CLOSURE, AS_FN, AS_INSTANCE, AS_MODULE, ASSERT, bindMethod(), callForeign(), captureUpvalue(), CASE_CODE, checkArity(), closeUpvalues(), CallFrame::closure, createClass(), createForeign(), DISPATCH, DROP, endClass(), FALSE_VAL, fiber, WrenVM::fiber, FIBER_ROOT, field(), ObjInstance::fields, fn, getModuleVariable(), importModule(), INTERPRET_LOOP, IS_CLASS, IS_CLOSURE, IS_INSTANCE, WrenVM::lastModule, LOAD_FRAME, method(), METHOD_BLOCK, METHOD_FOREIGN, METHOD_FUNCTION_CALL, METHOD_NONE, METHOD_PRIMITIVE, methodNotFound(), sObjClass::methods, NULL, NULL_VAL, OBJ_VAL, PEEK, PEEK2, POP, PUSH, READ_BYTE, READ_SHORT, RUNTIME_ERROR, CallFrame::stackStart, STORE_FRAME, TRUE_VAL, UNREACHABLE, ObjClosure::upvalues, sObjUpvalue::value, WREN_RESULT_RUNTIME_ERROR, WREN_RESULT_SUCCESS, wrenCallFunction(), wrenGetClassInline(), wrenHasError(), wrenIsFalsyValue(), wrenNewClosure(), and wrenNewInstance().
Referenced by wrenCall(), and wrenInterpret().
runtimeError()
static void runtimeError (WrenVM * vm) static
Definition at line 403 of file wren_vm.c.
 {
   ASSERT(wrenHasError(vm->fiber), "Should only call this after an error.");
   ObjFiber* current = vm->fiber;
   Value error = current->error;
   while (current != NULL)
   {
     // Every fiber along the call chain gets aborted with the same error.
     current->error = error;
     // If the caller ran this fiber using "try", give it the error and stop.
     if (current->state == FIBER_TRY)
     {
       // Make the caller's try method return the error message.
       current->caller->stackTop[-1] = vm->fiber->error;
       vm->fiber = current->caller;
       return;
     }
     // Otherwise, unhook the caller since we will never resume and return to it.
     ObjFiber* caller = current->caller;
     current->caller = NULL;
     current = caller;
   }
   // If we got here, nothing caught the error, so show the stack trace.
   wrenDebugPrintStackTrace(vm);
   vm->fiber = NULL;
   vm->apiStack = NULL;
 }
References WrenVM::apiStack, ASSERT, sObjFiber::caller, error, sObjFiber::error, WrenVM::fiber, FIBER_TRY, NULL, sObjFiber::stackTop, sObjFiber::state, wrenDebugPrintStackTrace(), and wrenHasError().
setSlot()
static void setSlot (WrenVM * vm, int slot, Value value) static
Definition at line 1726 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   vm->apiStack[slot] = value;
 }
References WrenVM::apiStack, and validateApiSlot().
Referenced by wrenGetVariable(), wrenRemoveMapValue(), wrenSetSlotBool(), wrenSetSlotBytes(), wrenSetSlotDouble(), wrenSetSlotHandle(), wrenSetSlotNewList(), wrenSetSlotNewMap(), wrenSetSlotNull(), and wrenSetSlotString().
validateApiSlot()
static void validateApiSlot (WrenVM * vm, int slot) static
Definition at line 1655 of file wren_vm.c.
 {
   ASSERT(slot >= 0, "Slot cannot be negative.");
   ASSERT(slot < wrenGetSlotCount(vm), "Not that many slots.");
 }
References ASSERT, and wrenGetSlotCount().
Referenced by setSlot(), wrenAbortFiber(), wrenGetListCount(), wrenGetListElement(), wrenGetMapContainsKey(), wrenGetMapCount(), wrenGetMapValue(), wrenGetSlotBool(), wrenGetSlotBytes(), wrenGetSlotDouble(), wrenGetSlotForeign(), wrenGetSlotHandle(), wrenGetSlotString(), wrenGetSlotType(), wrenInsertInList(), wrenRemoveMapValue(), wrenSetListElement(), wrenSetMapValue(), and wrenSetSlotNewForeign().
validateSuperclass()
static Value validateSuperclass (WrenVM * vm, Value name, Value superclassValue, int numFields) static
Definition at line 507 of file wren_vm.c.
 {
   // Make sure the superclass is a class.
   if (!IS_CLASS(superclassValue))
   {
     return wrenStringFormat(vm,
         "Class '@' cannot inherit from a non-class object.",
         name);
   }
   // Make sure it doesn't inherit from a sealed built-in type. Primitive methods
   // on these classes assume the instance is one of the other Obj___ types and
   // will fail horribly if it's actually an ObjInstance.
   ObjClass* superclass = AS_CLASS(superclassValue);
   if (superclass == vm->classClass ||
       superclass == vm->fiberClass ||
       superclass == vm->fnClass || // Includes OBJ_CLOSURE.
       superclass == vm->listClass ||
       superclass == vm->mapClass ||
       superclass == vm->rangeClass ||
       superclass == vm->stringClass ||
       superclass == vm->boolClass ||
       superclass == vm->nullClass ||
       superclass == vm->numClass)
   {
     return wrenStringFormat(vm,
         "Class '@' cannot inherit from built-in class '@'.",
         name, OBJ_VAL(superclass->name));
   }
   if (superclass->numFields == -1)
   {
     return wrenStringFormat(vm,
         "Class '@' cannot inherit from foreign class '@'.",
         name, OBJ_VAL(superclass->name));
   }
   if (numFields == -1 && superclass->numFields > 0)
   {
     return wrenStringFormat(vm,
         "Foreign class '@' may not inherit from a class with fields.",
         name);
   }
   if (superclass->numFields + numFields > MAX_FIELDS)
   {
     return wrenStringFormat(vm,
         "Class '@' may not have more than 255 fields, including inherited "
         "ones.", name);
   }
   return NULL_VAL;
 }
References AS_CLASS, WrenVM::boolClass, WrenVM::classClass, WrenVM::fiberClass, WrenVM::fnClass, IS_CLASS, WrenVM::listClass, WrenVM::mapClass, MAX_FIELDS, name, sObjClass::name, NULL_VAL, WrenVM::nullClass, WrenVM::numClass, sObjClass::numFields, OBJ_VAL, WrenVM::rangeClass, WrenVM::stringClass, and wrenStringFormat().
Referenced by createClass().
wrenAbortFiber()
void wrenAbortFiber (WrenVM * vm, int slot)
Definition at line 1979 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   vm->fiber->error = vm->apiStack[slot];
 }
References WrenVM::apiStack, sObjFiber::error, WrenVM::fiber, and validateApiSlot().
wrenCall()
WrenInterpretResult wrenCall (WrenVM * vm, WrenHandle * method)
Definition at line 1442 of file wren_vm.c.
 {
   ASSERT(method != NULL, "Method cannot be NULL.");
   ASSERT(IS_CLOSURE(method->value), "Method must be a method handle.");
   ASSERT(vm->fiber != NULL, "Must set up arguments for call first.");
   ASSERT(vm->apiStack != NULL, "Must set up arguments for call first.");
   ASSERT(vm->fiber->numFrames == 0, "Can not call from a foreign method.");
   ObjClosure* closure = AS_CLOSURE(method->value);
   ASSERT(vm->fiber->stackTop - vm->fiber->stack >= closure->fn->arity,
          "Stack must have enough arguments for method.");
   // Clear the API stack. Now that wrenCall() has control, we no longer need
   // it. We use this being non-null to tell if re-entrant calls to foreign
   // methods are happening, so it's important to clear it out now so that you
   // can call foreign methods from within calls to wrenCall().
   vm->apiStack = NULL;
   // Discard any extra temporary slots. We take for granted that the stub
   // function has exactly one slot for each argument.
   vm->fiber->stackTop = &vm->fiber->stack[closure->fn->maxSlots];
   wrenCallFunction(vm, vm->fiber, closure, 0);
   WrenInterpretResult result = runInterpreter(vm, vm->fiber);
   // If the call didn't abort, then set up the API stack to point to the
   // beginning of the stack so the host can access the call's return value.
   if (vm->fiber != NULL) vm->apiStack = vm->fiber->stack;
   return result;
 }
References WrenVM::apiStack, ObjFn::arity, AS_CLOSURE, ASSERT, WrenVM::fiber, ObjClosure::fn, IS_CLOSURE, ObjFn::maxSlots, method(), NULL, sObjFiber::numFrames, runInterpreter(), sObjFiber::stack, sObjFiber::stackTop, and wrenCallFunction().
Referenced by AppWren::onAnalog1(), AppWren::onAnalog2(), AppWren::onAnalog3(), AppWren::onAnalog4(), AppWren::onFocus(), AppWren::onFocusLost(), AppWren::onTouch(), AppWren::onTouchDrag(), AppWren::onTouchRelease(), AppWren::update(), AppWren::updateRT(), and AppWren::vmConstructor().
wrenCollectGarbage()
void wrenCollectGarbage (WrenVM * vm)
Definition at line 125 of file wren_vm.c.
 {
 #if WREN_DEBUG_TRACE_MEMORY || WREN_DEBUG_TRACE_GC
   printf("-- gc --\n");
   size_t before = vm->bytesAllocated;
   double startTime = (double)clock() / CLOCKS_PER_SEC;
 #endif
   // Mark all reachable objects.
   // Reset this. As we mark objects, their size will be counted again so that
   // we can track how much memory is in use without needing to know the size
   // of each *freed* object.
   //
   // This is important because when freeing an unmarked object, we don't always
   // know how much memory it is using. For example, when freeing an instance,
   // we need to know its class to know how big it is, but its class may have
   // already been freed.
   vm->bytesAllocated = 0;
   wrenGrayObj(vm, (Obj*)vm->modules);
   // Temporary roots.
   for (int i = 0; i < vm->numTempRoots; i++)
   {
     wrenGrayObj(vm, vm->tempRoots[i]);
   }
   // The current fiber.
   wrenGrayObj(vm, (Obj*)vm->fiber);
   // The handles.
   for (WrenHandle* handle = vm->handles;
        handle != NULL;
        handle = handle->next)
   {
     wrenGrayValue(vm, handle->value);
   }
   // Any object the compiler is using (if there is one).
   if (vm->compiler != NULL) wrenMarkCompiler(vm, vm->compiler);
   // Method names.
   wrenBlackenSymbolTable(vm, &vm->methodNames);
   // Now that we have grayed the roots, do a depth-first search over all of the
   // reachable objects.
   wrenBlackenObjects(vm);
   // Collect the white objects.
   Obj** obj = &vm->first;
   while (*obj != NULL)
   {
     if (!((*obj)->isDark))
     {
       // This object wasn't reached, so remove it from the list and free it.
       Obj* unreached = *obj;
       *obj = unreached->next;
       wrenFreeObj(vm, unreached);
     }
     else
     {
       // This object was reached, so unmark it (for the next GC) and move on to
       // the next.
       (*obj)->isDark = false;
       obj = &(*obj)->next;
     }
   }
   // Calculate the next gc point, this is the current allocation plus
   // a configured percentage of the current allocation.
   vm->nextGC = vm->bytesAllocated + ((vm->bytesAllocated * vm->config.heapGrowthPercent) / 100);
   if (vm->nextGC < vm->config.minHeapSize) vm->nextGC = vm->config.minHeapSize;
 #if WREN_DEBUG_TRACE_MEMORY || WREN_DEBUG_TRACE_GC
   double elapsed = ((double)clock() / CLOCKS_PER_SEC) - startTime;
   // Explicit cast because size_t has different sizes on 32-bit and 64-bit and
   // we need a consistent type for the format string.
   printf("GC %lu before, %lu after (%lu collected), next at %lu. Took %.3fms.\n",
          (unsigned long)before,
          (unsigned long)vm->bytesAllocated,
          (unsigned long)(before - vm->bytesAllocated),
          (unsigned long)vm->nextGC,
          elapsed*1000.0);
 #endif
 }
References WrenVM::bytesAllocated, WrenVM::compiler, WrenVM::config, WrenVM::fiber, WrenVM::first, WrenVM::handles, WrenConfiguration::heapGrowthPercent, WrenVM::methodNames, WrenConfiguration::minHeapSize, WrenVM::modules, sObj::next, WrenVM::nextGC, NULL, WrenVM::numTempRoots, WrenVM::tempRoots, wrenBlackenObjects(), wrenBlackenSymbolTable(), wrenFreeObj(), wrenGrayObj(), wrenGrayValue(), and wrenMarkCompiler().
Referenced by DEF_PRIMITIVE(), AppWren::update(), and wrenReallocate().
wrenCompileSource()
ObjClosure* wrenCompileSource (WrenVM * vm, const char * module, const char * source, bool isExpression, bool printErrors)
Definition at line 1527 of file wren_vm.c.
 {
   Value nameValue = NULL_VAL;
   if (module != NULL)
   {
     nameValue = wrenNewString(vm, module);
     wrenPushRoot(vm, AS_OBJ(nameValue));
   }
   ObjClosure* closure = compileInModule(vm, nameValue, source,
                                         isExpression, printErrors);
   if (module != NULL) wrenPopRoot(vm); // nameValue.
   return closure;
 }
References AS_OBJ, compileInModule(), NULL, NULL_VAL, source, wrenNewString(), wrenPopRoot(), and wrenPushRoot().
Referenced by metaCompile(), and wrenInterpret().
wrenDeclareVariable()
int wrenDeclareVariable (WrenVM * vm, ObjModule * module, const char * name, size_t length, int line)
Definition at line 1563 of file wren_vm.c.
 {
   if (module->variables.count == MAX_MODULE_VARS) return -2;
   // Implicitly defined variables get a "value" that is the line where the
   // variable is first used. We'll use that later to report an error on the
   // right line.
   wrenValueBufferWrite(vm, &module->variables, NUM_VAL(line));
   return wrenSymbolTableAdd(vm, &module->variableNames, name, length);
 }
References MAX_MODULE_VARS, name, NUM_VAL, ObjModule::variableNames, ObjModule::variables, and wrenSymbolTableAdd().
Referenced by name().
wrenDefineVariable()
int wrenDefineVariable (WrenVM * vm, ObjModule * module, const char * name, size_t length, Value value, int * line)
Definition at line 1575 of file wren_vm.c.
 {
   if (module->variables.count == MAX_MODULE_VARS) return -2;
   if (IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   // See if the variable is already explicitly or implicitly declared.
   int symbol = wrenSymbolTableFind(&module->variableNames, name, length);
   if (symbol == -1)
   {
     // Brand new variable.
     symbol = wrenSymbolTableAdd(vm, &module->variableNames, name, length);
     wrenValueBufferWrite(vm, &module->variables, value);
   }
   else if (IS_NUM(module->variables.data[symbol]))
   {
     // An implicitly declared variable's value will always be a number.
     // Now we have a real definition.
     if(line) *line = (int)AS_NUM(module->variables.data[symbol]);
     module->variables.data[symbol] = value;
     // If this was a localname we want to error if it was
     // referenced before this definition.
     if (wrenIsLocalName(name)) symbol = -3;
   }
   else
   {
     // Already explicitly declared.
     symbol = -1;
   }
   if (IS_OBJ(value)) wrenPopRoot(vm);
   return symbol;
 }
References AS_NUM, AS_OBJ, IS_NUM, IS_OBJ, MAX_MODULE_VARS, name, ObjModule::variableNames, ObjModule::variables, wrenIsLocalName(), wrenPopRoot(), wrenPushRoot(), wrenSymbolTableAdd(), and wrenSymbolTableFind().
Referenced by compileInModule(), declareVariable(), and defineClass().
wrenEnsureSlots()
void wrenEnsureSlots (WrenVM * vm, int numSlots)
Definition at line 1635 of file wren_vm.c.
 {
   // If we don't have a fiber accessible, create one for the API to use.
   if (vm->apiStack == NULL)
   {
     vm->fiber = wrenNewFiber(vm, NULL);
     vm->apiStack = vm->fiber->stack;
   }
   int currentSize = (int)(vm->fiber->stackTop - vm->apiStack);
   if (currentSize >= numSlots) return;
   // Grow the stack if needed.
   int needed = (int)(vm->apiStack - vm->fiber->stack) + numSlots;
   wrenEnsureStack(vm, vm->fiber, needed);
   vm->fiber->stackTop = vm->apiStack + numSlots;
 }
References WrenVM::apiStack, WrenVM::fiber, NULL, sObjFiber::stack, sObjFiber::stackTop, wrenEnsureStack(), and wrenNewFiber().
Referenced by AppWren::getWrenHandles(), metaGetModuleVariables(), AppWren::onAnalog1(), AppWren::onAnalog2(), AppWren::onAnalog3(), AppWren::onAnalog4(), AppWren::onFocus(), AppWren::onFocusLost(), AppWren::onTouch(), AppWren::onTouchDrag(), AppWren::onTouchRelease(), AppWren::update(), AppWren::updateRT(), and AppWren::vmConstructor().
wrenFinalizeForeign()
void wrenFinalizeForeign (WrenVM * vm, ObjForeign * foreign)
Definition at line 680 of file wren_vm.c.
 {
   // TODO: Don't look up every time.
   int symbol = wrenSymbolTableFind(&vm->methodNames, "<finalize>", 10);
   ASSERT(symbol != -1, "Should have defined <finalize> symbol.");
   // If there are no finalizers, don't finalize it.
   if (symbol == -1) return;
   // If the class doesn't have a finalizer, bail out.
   ObjClass* classObj = foreign->obj.classObj;
   if (symbol >= classObj->methods.count) return;
   Method* method = &classObj->methods.data[symbol];
   if (method->type == METHOD_NONE) return;
   ASSERT(method->type == METHOD_FOREIGN, "Finalizer should be foreign.");
   WrenFinalizerFn finalizer = (WrenFinalizerFn)method->as.foreign;
   finalizer(foreign->data);
 }
References ASSERT, sObj::classObj, ObjForeign::data, method(), METHOD_FOREIGN, METHOD_NONE, WrenVM::methodNames, sObjClass::methods, ObjForeign::obj, and wrenSymbolTableFind().
Referenced by wrenFreeObj().
wrenFindVariable()
Value wrenFindVariable (WrenVM * vm, ObjModule * module, const char * name)
Definition at line 1557 of file wren_vm.c.
 {
   int symbol = wrenSymbolTableFind(&module->variableNames, name, strlen(name));
   return module->variables.data[symbol];
 }
References name, ObjModule::variableNames, ObjModule::variables, and wrenSymbolTableFind().
Referenced by wrenInitializeCore().
wrenFreeVM()
void wrenFreeVM (WrenVM * vm)
Definition at line 99 of file wren_vm.c.
 {
   ASSERT(vm->methodNames.count > 0, "VM appears to have already been freed.");
   // Free all of the GC objects.
   Obj* obj = vm->first;
   while (obj != NULL)
   {
     Obj* next = obj->next;
     wrenFreeObj(vm, obj);
     obj = next;
   }
   // Free up the GC gray set.
   vm->gray = (Obj**)vm->config.reallocateFn(vm->gray, 0, vm->config.userData);
   // Tell the user if they didn't free any handles. We don't want to just free
   // them here because the host app may still have pointers to them that they
   // may try to use. Better to tell them about the bug early.
   ASSERT(vm->handles == NULL, "All handles have not been released.");
   wrenSymbolTableClear(vm, &vm->methodNames);
   DEALLOCATE(vm, vm);
 }
References ASSERT, WrenVM::config, DEALLOCATE, WrenVM::first, WrenVM::gray, WrenVM::handles, WrenVM::methodNames, sObj::next, NULL, WrenConfiguration::reallocateFn, WrenConfiguration::userData, wrenFreeObj(), and wrenSymbolTableClear().
Referenced by AppWren::~AppWren(), main(), and AppWren::restartVM().
wrenGetListCount()
int wrenGetListCount (WrenVM * vm, int slot)
Definition at line 1792 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_LIST(vm->apiStack[slot]), "Slot must hold a list.");
   ValueBuffer elements = AS_LIST(vm->apiStack[slot])->elements;
   return elements.count;
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, and validateApiSlot().
wrenGetListElement()
void wrenGetListElement (WrenVM * vm, int listSlot, int index, int elementSlot)
Definition at line 1801 of file wren_vm.c.
 {
   validateApiSlot(vm, listSlot);
   validateApiSlot(vm, elementSlot);
   ASSERT(IS_LIST(vm->apiStack[listSlot]), "Slot must hold a list.");
   ValueBuffer elements = AS_LIST(vm->apiStack[listSlot])->elements;
   uint32_t usedIndex = wrenValidateIndex(elements.count, index);
   ASSERT(usedIndex != UINT32_MAX, "Index out of bounds.");
   vm->apiStack[elementSlot] = elements.data[usedIndex];
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, validateApiSlot(), and wrenValidateIndex().
wrenGetMapContainsKey()
bool wrenGetMapContainsKey (WrenVM * vm, int mapSlot, int keySlot)
Definition at line 1855 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Slot must hold a map.");
   Value key = vm->apiStack[keySlot];
   ASSERT(wrenMapIsValidKey(key), "Key must be a value type");
   if (!validateKey(vm, key)) return false;
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   Value value = wrenMapGet(map, key);
   return !IS_UNDEFINED(value);
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, IS_UNDEFINED, map(), validateApiSlot(), validateKey(), wrenMapGet(), and wrenMapIsValidKey().
wrenGetMapCount()
int wrenGetMapCount (WrenVM * vm, int slot)
Definition at line 1846 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_MAP(vm->apiStack[slot]), "Slot must hold a map.");
   ObjMap* map = AS_MAP(vm->apiStack[slot]);
   return map->count;
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, map(), and validateApiSlot().
wrenGetMapValue()
void wrenGetMapValue (WrenVM * vm, int mapSlot, int keySlot, int valueSlot)
Definition at line 1871 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   validateApiSlot(vm, valueSlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Slot must hold a map.");
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   Value value = wrenMapGet(map, vm->apiStack[keySlot]);
   if (IS_UNDEFINED(value)) {
     value = NULL_VAL;
   }
   vm->apiStack[valueSlot] = value;
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, IS_UNDEFINED, map(), NULL_VAL, validateApiSlot(), and wrenMapGet().
wrenGetModuleVariable()
Value wrenGetModuleVariable (WrenVM * vm, Value moduleName, Value variableName)
Definition at line 1544 of file wren_vm.c.
 {
   ObjModule* module = getModule(vm, moduleName);
   if (module == NULL)
   {
     vm->fiber->error = wrenStringFormat(vm, "Module '@' is not loaded.",
                                         moduleName);
     return NULL_VAL;
   }
   return getModuleVariable(vm, module, variableName);
 }
References sObjFiber::error, WrenVM::fiber, getModule(), getModuleVariable(), NULL, NULL_VAL, and wrenStringFormat().
wrenGetSlotBool()
bool wrenGetSlotBool (WrenVM * vm, int slot)
Definition at line 1676 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_BOOL(vm->apiStack[slot]), "Slot must hold a bool.");
   return AS_BOOL(vm->apiStack[slot]);
 }
References WrenVM::apiStack, AS_BOOL, ASSERT, IS_BOOL, and validateApiSlot().
Referenced by metaCompile().
wrenGetSlotBytes()
const char* wrenGetSlotBytes (WrenVM * vm, int slot, int * length)
Definition at line 1684 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_STRING(vm->apiStack[slot]), "Slot must hold a string.");
   ObjString* string = AS_STRING(vm->apiStack[slot]);
   *length = string->length;
   return string->value;
 }
References WrenVM::apiStack, AS_STRING, ASSERT, IS_STRING, and validateApiSlot().
wrenGetSlotCount()
int wrenGetSlotCount (WrenVM * vm)
Definition at line 1628 of file wren_vm.c.
 {
   if (vm->apiStack == NULL) return 0;
   return (int)(vm->fiber->stackTop - vm->apiStack);
 }
References WrenVM::apiStack, WrenVM::fiber, NULL, and sObjFiber::stackTop.
Referenced by validateApiSlot().
wrenGetSlotDouble()
double wrenGetSlotDouble (WrenVM * vm, int slot)
Definition at line 1694 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_NUM(vm->apiStack[slot]), "Slot must hold a number.");
   return AS_NUM(vm->apiStack[slot]);
 }
References WrenVM::apiStack, AS_NUM, ASSERT, IS_NUM, and validateApiSlot().
Referenced by randomSeed1(), and randomSeed16().
wrenGetSlotForeign()
void* wrenGetSlotForeign (WrenVM * vm, int slot)
Definition at line 1702 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_FOREIGN(vm->apiStack[slot]),
          "Slot must hold a foreign instance.");
   return AS_FOREIGN(vm->apiStack[slot])->data;
 }
References WrenVM::apiStack, AS_FOREIGN, ASSERT, IS_FOREIGN, and validateApiSlot().
Referenced by randomFloat(), randomInt0(), randomSeed0(), randomSeed1(), and randomSeed16().
wrenGetSlotHandle()
WrenHandle* wrenGetSlotHandle (WrenVM * vm, int slot)
Definition at line 1719 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   return wrenMakeHandle(vm, vm->apiStack[slot]);
 }
References WrenVM::apiStack, validateApiSlot(), and wrenMakeHandle().
Referenced by AppWren::getWrenHandles().
wrenGetSlotString()
const char* wrenGetSlotString (WrenVM * vm, int slot)
Definition at line 1711 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_STRING(vm->apiStack[slot]), "Slot must hold a string.");
   return AS_CSTRING(vm->apiStack[slot]);
 }
References WrenVM::apiStack, AS_CSTRING, ASSERT, IS_STRING, and validateApiSlot().
Referenced by metaCompile().
wrenGetSlotType()
WrenType wrenGetSlotType (WrenVM * vm, int slot)
Definition at line 1662 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   if (IS_BOOL(vm->apiStack[slot])) return WREN_TYPE_BOOL;
   if (IS_NUM(vm->apiStack[slot])) return WREN_TYPE_NUM;
   if (IS_FOREIGN(vm->apiStack[slot])) return WREN_TYPE_FOREIGN;
   if (IS_LIST(vm->apiStack[slot])) return WREN_TYPE_LIST;
   if (IS_MAP(vm->apiStack[slot])) return WREN_TYPE_MAP;
   if (IS_NULL(vm->apiStack[slot])) return WREN_TYPE_NULL;
   if (IS_STRING(vm->apiStack[slot])) return WREN_TYPE_STRING;
   return WREN_TYPE_UNKNOWN;
 }
References WrenVM::apiStack, IS_BOOL, IS_FOREIGN, IS_LIST, IS_MAP, IS_NULL, IS_NUM, IS_STRING, validateApiSlot(), WREN_TYPE_BOOL, WREN_TYPE_FOREIGN, WREN_TYPE_LIST, WREN_TYPE_MAP, WREN_TYPE_NULL, WREN_TYPE_NUM, WREN_TYPE_STRING, and WREN_TYPE_UNKNOWN.
wrenGetUserData()
void* wrenGetUserData (WrenVM * vm)
Definition at line 1985 of file wren_vm.c.
 {
     return vm->config.userData;
 }
References WrenVM::config, and WrenConfiguration::userData.
wrenGetVariable()
void wrenGetVariable (WrenVM * vm, const char * module, const char * name, int slot)
Definition at line 1924 of file wren_vm.c.
 {
   ASSERT(module != NULL, "Module cannot be NULL.");
   ASSERT(name != NULL, "Variable name cannot be NULL.");
   Value moduleName = wrenStringFormat(vm, "$", module);
   wrenPushRoot(vm, AS_OBJ(moduleName));
   ObjModule* moduleObj = getModule(vm, moduleName);
   ASSERT(moduleObj != NULL, "Could not find module.");
   wrenPopRoot(vm); // moduleName.
   int variableSlot = wrenSymbolTableFind(&moduleObj->variableNames,
                                          name, strlen(name));
   ASSERT(variableSlot != -1, "Could not find variable.");
   setSlot(vm, slot, moduleObj->variables.data[variableSlot]);
 }
References AS_OBJ, ASSERT, getModule(), name, NULL, setSlot(), ObjModule::variableNames, ObjModule::variables, wrenPopRoot(), wrenPushRoot(), wrenStringFormat(), and wrenSymbolTableFind().
Referenced by AppWren::getWrenHandles().
wrenGetVersionNumber()
int wrenGetVersionNumber ()
Definition at line 39 of file wren_vm.c.
 {
   return WREN_VERSION_NUMBER;
 }
References WREN_VERSION_NUMBER.
wrenHasModule()
bool wrenHasModule (WrenVM * vm, const char * module)
Definition at line 1965 of file wren_vm.c.
 {
   ASSERT(module != NULL, "Module cannot be NULL.");
   Value moduleName = wrenStringFormat(vm, "$", module);
   wrenPushRoot(vm, AS_OBJ(moduleName));
   ObjModule* moduleObj = getModule(vm, moduleName);
   wrenPopRoot(vm); // moduleName.
   return moduleObj != NULL;
 }
References AS_OBJ, ASSERT, getModule(), NULL, wrenPopRoot(), wrenPushRoot(), and wrenStringFormat().
wrenHasVariable()
bool wrenHasVariable (WrenVM * vm, const char * module, const char * name)
Definition at line 1945 of file wren_vm.c.
 {
   ASSERT(module != NULL, "Module cannot be NULL.");
   ASSERT(name != NULL, "Variable name cannot be NULL.");
   Value moduleName = wrenStringFormat(vm, "$", module);
   wrenPushRoot(vm, AS_OBJ(moduleName));
   //We don't use wrenHasModule since we want to use the module object.
   ObjModule* moduleObj = getModule(vm, moduleName);
   ASSERT(moduleObj != NULL, "Could not find module.");
   wrenPopRoot(vm); // moduleName.
   int variableSlot = wrenSymbolTableFind(&moduleObj->variableNames,
     name, strlen(name));
   return variableSlot != -1;
 }
References AS_OBJ, ASSERT, getModule(), name, NULL, ObjModule::variableNames, wrenPopRoot(), wrenPushRoot(), wrenStringFormat(), and wrenSymbolTableFind().
wrenInitConfiguration()
void wrenInitConfiguration (WrenConfiguration * config)
Definition at line 44 of file wren_vm.c.
 {
   config->reallocateFn = defaultReallocate;
   config->resolveModuleFn = NULL;
   config->loadModuleFn = NULL;
   config->bindForeignMethodFn = NULL;
   config->bindForeignClassFn = NULL;
   config->writeFn = NULL;
   config->errorFn = NULL;
   config->initialHeapSize = 1024 * 1024 * 10;
   config->minHeapSize = 1024 * 1024;
   config->heapGrowthPercent = 50;
   config->userData = NULL;
 }
References config, defaultReallocate(), and NULL.
Referenced by main(), AppWren::startVM(), and wrenNewVM().
wrenInsertInList()
void wrenInsertInList (WrenVM * vm, int listSlot, int index, int elementSlot)
Definition at line 1829 of file wren_vm.c.
 {
   validateApiSlot(vm, listSlot);
   validateApiSlot(vm, elementSlot);
   ASSERT(IS_LIST(vm->apiStack[listSlot]), "Must insert into a list.");
   ObjList* list = AS_LIST(vm->apiStack[listSlot]);
   // Negative indices count from the end.
   // We don't use wrenValidateIndex here because insert allows 1 past the end.
   if (index < 0) index = list->elements.count + 1 + index;
   ASSERT(index <= list->elements.count, "Index out of bounds.");
   wrenListInsert(vm, list, vm->apiStack[elementSlot], index);
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, list(), validateApiSlot(), and wrenListInsert().
wrenInterpret()
WrenInterpretResult wrenInterpret (WrenVM * vm, const char * module, const char * source)
Definition at line 1513 of file wren_vm.c.
 {
   ObjClosure* closure = wrenCompileSource(vm, module, source, false, true);
   if (closure == NULL) return WREN_RESULT_COMPILE_ERROR;
   wrenPushRoot(vm, (Obj*)closure);
   ObjFiber* fiber = wrenNewFiber(vm, closure);
   wrenPopRoot(vm); // closure.
   vm->apiStack = NULL;
   return runInterpreter(vm, fiber);
 }
References WrenVM::apiStack, fiber, NULL, runInterpreter(), source, WREN_RESULT_COMPILE_ERROR, wrenCompileSource(), wrenNewFiber(), wrenPopRoot(), and wrenPushRoot().
Referenced by AppWren::loadScript(), main(), and wrenInitializeCore().
wrenMakeCallHandle()
WrenHandle* wrenMakeCallHandle (WrenVM * vm, const char * signature)
Definition at line 1392 of file wren_vm.c.
 {
   ASSERT(signature != NULL, "Signature cannot be NULL.");
   int signatureLength = (int)strlen(signature);
   ASSERT(signatureLength > 0, "Signature cannot be empty.");
   // Count the number parameters the method expects.
   int numParams = 0;
   if (signature[signatureLength - 1] == ')')
   {
     for (int i = signatureLength - 1; i > 0 && signature[i] != '('; i--)
     {
       if (signature[i] == '_') numParams++;
     }
   }
   // Count subscript arguments.
   if (signature[0] == '[')
   {
     for (int i = 0; i < signatureLength && signature[i] != ']'; i++)
     {
       if (signature[i] == '_') numParams++;
     }
   }
   // Add the signatue to the method table.
   int method =  wrenSymbolTableEnsure(vm, &vm->methodNames,
                                       signature, signatureLength);
   // Create a little stub function that assumes the arguments are on the stack
   // and calls the method.
   ObjFn* fn = wrenNewFunction(vm, NULL, numParams + 1);
   // Wrap the function in a closure and then in a handle. Do this here so it
   // doesn't get collected as we fill it in.
   WrenHandle* value = wrenMakeHandle(vm, OBJ_VAL(fn));
   value->value = OBJ_VAL(wrenNewClosure(vm, fn));
   wrenByteBufferWrite(vm, &fn->code, (uint8_t)(CODE_CALL_0 + numParams));
   wrenByteBufferWrite(vm, &fn->code, (method >> 8) & 0xff);
   wrenByteBufferWrite(vm, &fn->code, method & 0xff);
   wrenByteBufferWrite(vm, &fn->code, CODE_RETURN);
   wrenByteBufferWrite(vm, &fn->code, CODE_END);
   wrenIntBufferFill(vm, &fn->debug->sourceLines, 0, 5);
   wrenFunctionBindName(vm, fn, signature, signatureLength);
   return value;
 }
References ASSERT, fn, method(), WrenVM::methodNames, NULL, OBJ_VAL, WrenHandle::value, wrenFunctionBindName(), wrenMakeHandle(), wrenNewClosure(), wrenNewFunction(), and wrenSymbolTableEnsure().
Referenced by AppWren::getWrenHandles().
wrenMakeHandle()
WrenHandle* wrenMakeHandle (WrenVM * vm, Value value)
Definition at line 1475 of file wren_vm.c.
 {
   if (IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   // Make a handle for it.
   WrenHandle* handle = ALLOCATE(vm, WrenHandle);
   handle->value = value;
   if (IS_OBJ(value)) wrenPopRoot(vm);
   // Add it to the front of the linked list of handles.
   if (vm->handles != NULL) vm->handles->prev = handle;
   handle->prev = NULL;
   handle->next = vm->handles;
   vm->handles = handle;
   return handle;
 }
References ALLOCATE, AS_OBJ, WrenVM::handles, IS_OBJ, WrenHandle::next, NULL, WrenHandle::prev, WrenHandle::value, wrenPopRoot(), and wrenPushRoot().
Referenced by wrenGetSlotHandle(), and wrenMakeCallHandle().
wrenNewVM()
WrenVM* wrenNewVM (WrenConfiguration * config)
Definition at line 59 of file wren_vm.c.
 {
   WrenReallocateFn reallocate = defaultReallocate;
   void* userData = NULL;
   if (config != NULL) {
     userData = config->userData;
     reallocate = config->reallocateFn ? config->reallocateFn : defaultReallocate;
   }
   WrenVM* vm = (WrenVM*)reallocate(NULL, sizeof(*vm), userData);
   memset(vm, 0, sizeof(WrenVM));
   // Copy the configuration if given one.
   if (config != NULL)
   {
     memcpy(&vm->config, config, sizeof(WrenConfiguration));
     // We choose to set this after copying,
     // rather than modifying the user config pointer
     vm->config.reallocateFn = reallocate;
   }
   else
   {
     wrenInitConfiguration(&vm->config);
   }
   // TODO: Should we allocate and free this during a GC?
   vm->grayCount = 0;
   // TODO: Tune this.
   vm->grayCapacity = 4;
   vm->gray = (Obj**)reallocate(NULL, vm->grayCapacity * sizeof(Obj*), userData);
   vm->nextGC = vm->config.initialHeapSize;
   wrenSymbolTableInit(&vm->methodNames);
   vm->modules = wrenNewMap(vm);
   wrenInitializeCore(vm);
   return vm;
 }
References config, WrenVM::config, defaultReallocate(), WrenVM::gray, WrenVM::grayCapacity, WrenVM::grayCount, WrenConfiguration::initialHeapSize, WrenVM::methodNames, WrenVM::modules, WrenVM::nextGC, NULL, WrenConfiguration::reallocateFn, wrenInitConfiguration(), wrenInitializeCore(), wrenNewMap(), and wrenSymbolTableInit().
Referenced by main(), and AppWren::startVM().
wrenPopRoot()
void wrenPopRoot (WrenVM * vm)
Definition at line 1622 of file wren_vm.c.
 {
   ASSERT(vm->numTempRoots > 0, "No temporary roots to release.");
   vm->numTempRoots--;
 }
References ASSERT, and WrenVM::numTempRoots.
Referenced by addConstant(), addToAttributeGroup(), compileInModule(), copyMethodAttributes(), DEF_PRIMITIVE(), defineClass(), importModule(), wrenCompileSource(), wrenDefineVariable(), wrenGetVariable(), wrenHasModule(), wrenHasVariable(), wrenInitializeCore(), wrenInterpret(), wrenListInsert(), wrenListRemoveAt(), wrenMakeHandle(), wrenMapRemoveKey(), wrenNewClass(), wrenNewModule(), wrenNewSingleClass(), and wrenSymbolTableAdd().
wrenPushRoot()
void wrenPushRoot (WrenVM * vm, Obj * obj)
Definition at line 1614 of file wren_vm.c.
 {
   ASSERT(obj != NULL, "Can't root NULL.");
   ASSERT(vm->numTempRoots < WREN_MAX_TEMP_ROOTS, "Too many temporary roots.");
   vm->tempRoots[vm->numTempRoots++] = obj;
 }
References ASSERT, NULL, WrenVM::numTempRoots, WrenVM::tempRoots, and WREN_MAX_TEMP_ROOTS.
Referenced by addConstant(), addToAttributeGroup(), compileInModule(), copyMethodAttributes(), DEF_PRIMITIVE(), defineClass(), importModule(), wrenCompileSource(), wrenDefineVariable(), wrenGetVariable(), wrenHasModule(), wrenHasVariable(), wrenInitializeCore(), wrenInterpret(), wrenListInsert(), wrenListRemoveAt(), wrenMakeHandle(), wrenMapRemoveKey(), wrenNewClass(), wrenNewModule(), wrenNewSingleClass(), and wrenSymbolTableAdd().
wrenReallocate()
void* wrenReallocate (WrenVM * vm, void * memory, size_t oldSize, size_t newSize)
Definition at line 213 of file wren_vm.c.
 {
 #if WREN_DEBUG_TRACE_MEMORY
   // Explicit cast because size_t has different sizes on 32-bit and 64-bit and
   // we need a consistent type for the format string.
   printf("reallocate %p %lu -> %lu\n",
          memory, (unsigned long)oldSize, (unsigned long)newSize);
 #endif
   // If new bytes are being allocated, add them to the total count. If objects
   // are being completely deallocated, we don't track that (since we don't
   // track the original size). Instead, that will be handled while marking
   // during the next GC.
   vm->bytesAllocated += newSize - oldSize;
 #if WREN_DEBUG_GC_STRESS
   // Since collecting calls this function to free things, make sure we don't
   // recurse.
   if (newSize > 0) wrenCollectGarbage(vm);
 #else
   if (newSize > 0 && vm->bytesAllocated > vm->nextGC) wrenCollectGarbage(vm);
 #endif
   return vm->config.reallocateFn(memory, newSize, vm->config.userData);
 }
References WrenVM::bytesAllocated, WrenVM::config, WrenVM::nextGC, WrenConfiguration::reallocateFn, WrenConfiguration::userData, and wrenCollectGarbage().
Referenced by wrenCallFunction(), wrenEnsureStack(), and wrenListRemoveAt().
wrenReleaseHandle()
void wrenReleaseHandle (WrenVM * vm, WrenHandle * handle)
Definition at line 1494 of file wren_vm.c.
 {
   ASSERT(handle != NULL, "Handle cannot be NULL.");
   // Update the VM's head pointer if we're releasing the first handle.
   if (vm->handles == handle) vm->handles = handle->next;
   // Unlink it from the list.
   if (handle->prev != NULL) handle->prev->next = handle->next;
   if (handle->next != NULL) handle->next->prev = handle->prev;
   // Clear it out. This isn't strictly necessary since we're going to free it,
   // but it makes for easier debugging.
   handle->prev = NULL;
   handle->next = NULL;
   handle->value = NULL_VAL;
   DEALLOCATE(vm, handle);
 }
References ASSERT, DEALLOCATE, WrenVM::handles, WrenHandle::next, NULL, NULL_VAL, WrenHandle::prev, and WrenHandle::value.
Referenced by AppWren::releaseWrenHandles().
wrenRemoveMapValue()
void wrenRemoveMapValue (WrenVM * vm, int mapSlot, int keySlot, int removedValueSlot)
Definition at line 1907 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Slot must hold a map.");
   Value key = vm->apiStack[keySlot];
   if (!validateKey(vm, key)) {
     return;
   }
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   Value removed = wrenMapRemoveKey(vm, map, key);
   setSlot(vm, removedValueSlot, removed);
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, map(), setSlot(), validateApiSlot(), validateKey(), and wrenMapRemoveKey().
wrenSetListElement()
void wrenSetListElement (WrenVM * vm, int listSlot, int index, int elementSlot)
Definition at line 1815 of file wren_vm.c.
 {
   validateApiSlot(vm, listSlot);
   validateApiSlot(vm, elementSlot);
   ASSERT(IS_LIST(vm->apiStack[listSlot]), "Slot must hold a list.");
   ObjList* list = AS_LIST(vm->apiStack[listSlot]);
   uint32_t usedIndex = wrenValidateIndex(list->elements.count, index);
   ASSERT(usedIndex != UINT32_MAX, "Index out of bounds.");
   list->elements.data[usedIndex] = vm->apiStack[elementSlot];
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, list(), validateApiSlot(), and wrenValidateIndex().
wrenSetMapValue()
void wrenSetMapValue (WrenVM * vm, int mapSlot, int keySlot, int valueSlot)
Definition at line 1887 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   validateApiSlot(vm, valueSlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Must insert into a map.");
   Value key = vm->apiStack[keySlot];
   ASSERT(wrenMapIsValidKey(key), "Key must be a value type");
   if (!validateKey(vm, key)) {
     return;
   }
   Value value = vm->apiStack[valueSlot];
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   wrenMapSet(vm, map, key, value);
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, map(), validateApiSlot(), validateKey(), wrenMapIsValidKey(), and wrenMapSet().
wrenSetSlotBool()
void wrenSetSlotBool (WrenVM * vm, int slot, bool value)
Definition at line 1732 of file wren_vm.c.
 {
   setSlot(vm, slot, BOOL_VAL(value));
 }
References BOOL_VAL, and setSlot().
wrenSetSlotBytes()
void wrenSetSlotBytes (WrenVM * vm, int slot, const char * bytes, size_t length)
Definition at line 1737 of file wren_vm.c.
 {
   ASSERT(bytes != NULL, "Byte array cannot be NULL.");
   setSlot(vm, slot, wrenNewStringLength(vm, bytes, length));
 }
References ASSERT, NULL, setSlot(), and wrenNewStringLength().
wrenSetSlotDouble()
void wrenSetSlotDouble (WrenVM * vm, int slot, double value)
Definition at line 1743 of file wren_vm.c.
 {
   setSlot(vm, slot, NUM_VAL(value));
 }
References NUM_VAL, and setSlot().
Referenced by randomFloat(), and randomInt0().
wrenSetSlotHandle()
void wrenSetSlotHandle (WrenVM * vm, int slot, WrenHandle * handle)
Definition at line 1785 of file wren_vm.c.
 {
   ASSERT(handle != NULL, "Handle cannot be NULL.");
   setSlot(vm, slot, handle->value);
 }
References ASSERT, NULL, setSlot(), and WrenHandle::value.
Referenced by AppWren::onAnalog1(), AppWren::onAnalog2(), AppWren::onAnalog3(), AppWren::onAnalog4(), AppWren::onFocus(), AppWren::onFocusLost(), AppWren::onTouch(), AppWren::onTouchDrag(), AppWren::onTouchRelease(), AppWren::update(), AppWren::updateRT(), and AppWren::vmConstructor().
wrenSetSlotNewForeign()
void* wrenSetSlotNewForeign (WrenVM * vm, int slot, int classSlot, size_t size)
Definition at line 1748 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   validateApiSlot(vm, classSlot);
   ASSERT(IS_CLASS(vm->apiStack[classSlot]), "Slot must hold a class.");
   ObjClass* classObj = AS_CLASS(vm->apiStack[classSlot]);
   ASSERT(classObj->numFields == -1, "Class must be a foreign class.");
   ObjForeign* foreign = wrenNewForeign(vm, classObj, size);
   vm->apiStack[slot] = OBJ_VAL(foreign);
   return (void*)foreign->data;
 }
References WrenVM::apiStack, AS_CLASS, ASSERT, ObjForeign::data, IS_CLASS, sObjClass::numFields, OBJ_VAL, validateApiSlot(), and wrenNewForeign().
Referenced by randomAllocate().
wrenSetSlotNewList()
void wrenSetSlotNewList (WrenVM * vm, int slot)
Definition at line 1763 of file wren_vm.c.
 {
   setSlot(vm, slot, OBJ_VAL(wrenNewList(vm, 0)));
 }
References OBJ_VAL, setSlot(), and wrenNewList().
wrenSetSlotNewMap()
void wrenSetSlotNewMap (WrenVM * vm, int slot)
Definition at line 1768 of file wren_vm.c.
 {
   setSlot(vm, slot, OBJ_VAL(wrenNewMap(vm)));
 }
References OBJ_VAL, setSlot(), and wrenNewMap().
wrenSetSlotNull()
void wrenSetSlotNull (WrenVM * vm, int slot)
Definition at line 1773 of file wren_vm.c.
 {
   setSlot(vm, slot, NULL_VAL);
 }
References NULL_VAL, and setSlot().
wrenSetSlotString()
void wrenSetSlotString (WrenVM * vm, int slot, const char * text)
Definition at line 1778 of file wren_vm.c.
 {
   ASSERT(text != NULL, "String cannot be NULL.");
   setSlot(vm, slot, wrenNewString(vm, text));
 }
References ASSERT, NULL, setSlot(), and wrenNewString().
wrenSetUserData()
void wrenSetUserData (WrenVM * vm, void * userData)
Definition at line 1990 of file wren_vm.c.
 {
     vm->config.userData = userData;
 }
References WrenVM::config, and WrenConfiguration::userData.