ERIS CORE: SdSpiArduinoDriver Class Reference
SdSpiArduinoDriver Class Reference
Optimized SPI class for access to SD and SDHC flash memory cards.
#include <SdSpiArduinoDriver.h>
Public Member Functions
void activate ()
void begin (SdSpiConfig spiConfig)
void deactivate ()
void end ()
uint8_t receive ()
uint8_t receive (uint8_t *buf, size_t count)
void send (const uint8_t *buf, size_t count)
void send (uint8_t data)
void setSckSpeed (uint32_t maxSck)
Private Attributes
SPIClass * m_spi
SPISettings m_spiSettings
Detailed Description
Optimized SPI class for access to SD and SDHC flash memory cards.
Definition at line 39 of file SdSpiArduinoDriver.h.
Member Function Documentation
activate()
void SdSpiArduinoDriver::activate () inline
Activate SPI hardware.
Definition at line 35 of file SdSpiAvr.h.
{
   SPI.beginTransaction(m_spiSettings);
 }
References m_spiSettings.
Referenced by SharedSpiCard::spiActivate().
begin()
void SdSpiArduinoDriver::begin (SdSpiConfig spiConfig) inline
Initialize the SPI bus.
Parameters
[in] spiConfig SD card configuration.
Definition at line 30 of file SdSpiAvr.h.
{
   (void)spiConfig;
   SPI.begin();
 }
Referenced by SharedSpiCard::spiBegin().
deactivate()
void SdSpiArduinoDriver::deactivate () inline
Deactivate SPI hardware.
Definition at line 39 of file SdSpiAvr.h.
{
   SPI.endTransaction();
 }
Referenced by SharedSpiCard::spiDeactivate().
end()
void SdSpiArduinoDriver::end ()
End use of SPI driver after begin() call.
receive() [1/2]
uint8_t SdSpiArduinoDriver::receive () inline
Receive a byte.
Returns
The byte.
Definition at line 43 of file SdSpiAvr.h.
{
   return SPI.transfer(0XFF);
 }
Referenced by SharedSpiCard::spiReceive().
receive() [2/2]
uint8_t SdSpiArduinoDriver::receive (uint8_t * buf, size_t count) inline
Receive multiple bytes.
Parameters
[out] buf Buffer to receive the data.
[in] count Number of bytes to receive.
Returns
Zero for no error or nonzero error code.
Definition at line 47 of file SdSpiAvr.h.
{
   if (count == 0) {
     return 0;
   }
 #ifdef SPSR
   SPDR = 0XFF;
   while (--count) {
     // nops optimize loop for 16MHz CPU 8 MHz SPI
     nop;
     nop;
     while (!(SPSR & _BV(SPIF))) {}
     uint8_t in = SPDR;
     SPDR = 0XFF;
     *buf++ = in;
   }
   while (!(SPSR & _BV(SPIF))) {}
   *buf = SPDR;
 #elif defined(SPI_RXCIF_bm)
   SPI0.DATA = 0XFF;
   while (--count) {
     // nops optimize loop for ATmega4809 16MHz CPU 8 MHz SPI
     nop;
     nop;
     nop;
     nop;
     while (!(SPI0.INTFLAGS & SPI_RXCIF_bm)) {}
     uint8_t in = SPI0.DATA;
     SPI0.DATA = 0XFF;
     *buf++ = in;
   }
   while (!(SPI0.INTFLAGS & SPI_RXCIF_bm)) {}
   *buf = SPI0.DATA;
 #else  // SPSR
 #error Unsupported AVR CPU - edit SdFatConfig.h to use standard SPI library.
 #endif  // SPSR
   return 0;
 }
References buf, count, and nop.
send() [1/2]
void SdSpiArduinoDriver::send (const uint8_t * buf, size_t count) inline
Send multiple bytes.
Parameters
[in] buf Buffer for data to be sent.
[in] count Number of bytes to send.
Definition at line 89 of file SdSpiAvr.h.
{
   if (count == 0) {
     return;
   }
 #ifdef SPSR
   SPDR = *buf++;
   while (--count) {
     uint8_t b = *buf++;
     // nops optimize loop for 16MHz CPU 8 MHz SPI
     nop;
     nop;
     while (!(SPSR & (1 << SPIF))) {}
     SPDR = b;
   }
   while (!(SPSR & (1 << SPIF))) {}
 #elif defined(SPI_RXCIF_bm)
   SPI0.DATA = *buf++;
   while (--count) {
     uint8_t b = *buf++;
     // nops optimize loop for ATmega4809 16MHz CPU 8 MHz SPI
     nop;
     nop;
     nop;
     while (!(SPI0.INTFLAGS & SPI_RXCIF_bm)) {}
     SPI0.DATA = b;
   }
   while (!(SPI0.INTFLAGS & SPI_RXCIF_bm)) {}
 #else  // SPSR
 #error Unsupported AVR CPU - edit SdFatConfig.h to use standard SPI library.
 #endif  // SPSR
 }
References buf, count, and nop.
send() [2/2]
void SdSpiArduinoDriver::send (uint8_t data) inline
Send a byte.
Parameters
[in] data Byte to send
Definition at line 85 of file SdSpiAvr.h.
{
   SPI.transfer(data);
 }
References data.
Referenced by SharedSpiCard::spiSend().
setSckSpeed()
void SdSpiArduinoDriver::setSckSpeed (uint32_t maxSck) inline
Save high speed SPISettings after SD initialization.
Parameters
[in] maxSck Maximum SCK frequency.
Definition at line 80 of file SdSpiArduinoDriver.h.
{
     m_spiSettings = SPISettings(maxSck, MSBFIRST, SPI_MODE0);
   }
Referenced by SharedSpiCard::spiSetSckSpeed().
Member Data Documentation
m_spi
SPIClass* SdSpiArduinoDriver::m_spi private
Definition at line 85 of file SdSpiArduinoDriver.h.
m_spiSettings
SPISettings SdSpiArduinoDriver::m_spiSettings private
Definition at line 86 of file SdSpiArduinoDriver.h.
Referenced by activate().
The documentation for this class was generated from the following files:
ERISCore/lib/SdFat-master/src/SpiDriver/SdSpiArduinoDriver.h
ERISCore/lib/SdFat-master/src/SpiDriver/SdSpiAvr.h
ERISCore/lib/SdFat-master/src/SpiDriver/SdSpiLibDriver.h