ERIS CORE: AudioSynthWaveformhd::begin
begin() [1/2]
void AudioSynthWaveformhd::begin (float t_amp, float t_freq, short t_type) inline inherited
Definition at line 107 of file eris_synth_waveform.h.
{
         amplitude(t_amp);
         frequency(t_freq);
         phase_offset = 0;
         begin (t_type);
     }
References AudioSynthWaveformhd::amplitude(), AudioSynthWaveformhd::begin(), AudioSynthWaveformhd::frequency(), and AudioSynthWaveformhd::phase_offset.