ERIS CORE: FatCache Class Reference
FatCache Class Reference
Sector cache.
#include <FatPartition.h>
Public Member Functions
cache_t * buffer ()
void dirty ()
void init (FatPartition *vol)
void invalidate ()
bool isDirty ()
cache_t * read (uint32_t sector, uint8_t option)
uint32_t sector ()
bool sync ()
Static Public Attributes
static const uint8_t CACHE_FOR_READ = 0
static const uint8_t CACHE_FOR_WRITE = CACHE_STATUS_DIRTY
static const uint8_t CACHE_OPTION_NO_READ = 4
static const uint8_t CACHE_RESERVE_FOR_WRITE = CACHE_STATUS_DIRTY | CACHE_OPTION_NO_READ
static const uint8_t CACHE_STATUS_DIRTY = 1
static const uint8_t CACHE_STATUS_MASK = CACHE_STATUS_DIRTY | CACHE_STATUS_MIRROR_FAT
static const uint8_t CACHE_STATUS_MIRROR_FAT = 2
Detailed Description
Sector cache.
Definition at line 68 of file FatPartition.h.
Member Function Documentation
buffer()
cache_t* FatCache::buffer () inline
Returns
Cache sector address.
Definition at line 87 of file FatPartition.h.
                     {
     return &m_buffer;
   }
dirty()
void FatCache::dirty () inline
Set current sector dirty.
Definition at line 91 of file FatPartition.h.
                {
     m_status |= CACHE_STATUS_DIRTY;
   }
References CACHE_STATUS_DIRTY.
init()
void FatCache::init (FatPartition * vol) inline
Initialize the cache.
Parameters
[in] vol FatPartition that owns this FatCache.
Definition at line 97 of file FatPartition.h.
{
     m_part = vol;
     invalidate();
   }
References invalidate().
Referenced by FatPartition::init().
invalidate()
void FatCache::invalidate () inline
Invalidate current cache sector.
Definition at line 102 of file FatPartition.h.
                     {
     m_status = 0;
     m_lbn = 0XFFFFFFFF;
   }
Referenced by init().
isDirty()
bool FatCache::isDirty () inline
Returns
dirty status
Definition at line 107 of file FatPartition.h.
                  {
     return m_status & CACHE_STATUS_DIRTY;
   }
References CACHE_STATUS_DIRTY.
read()
cache_t * FatCache::read (uint32_t sector, uint8_t option)
Read a sector into the cache.
Parameters
[in] sector Sector to read.
[in] option mode for cached sector.
Returns
Address of cached sector.
Definition at line 31 of file FatPartition.cpp.
{
   if (m_lbn != sector) {
     if (!sync()) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!(option & CACHE_OPTION_NO_READ)) {
       if (!m_part->readSector(sector, m_buffer.data)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_status = 0;
     m_lbn = sector;
   }
   m_status |= option & CACHE_STATUS_MASK;
   return &m_buffer;
 fail:
   return nullptr;
 }
References CACHE_OPTION_NO_READ, CACHE_STATUS_MASK, cache_t::data, DBG_FAIL_MACRO, sector(), and sync().
sector()
uint32_t FatCache::sector () inline
Returns
Logical sector number for cached sector.
Definition at line 111 of file FatPartition.h.
                     {
     return m_lbn;
   }
Referenced by read(), and sync().
sync()
bool FatCache::sync ()
Write current sector if dirty.
Returns
true for success or false for failure.
Definition at line 54 of file FatPartition.cpp.
                     {
   if (m_status & CACHE_STATUS_DIRTY) {
     if (!m_part->writeSector(m_lbn, m_buffer.data)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // mirror second FAT
     if (m_status & CACHE_STATUS_MIRROR_FAT) {
       uint32_t sector = m_lbn + m_part->sectorsPerFat();
       if (!m_part->writeSector(sector, m_buffer.data)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_status &= ~CACHE_STATUS_DIRTY;
   }
   return true;
 fail:
   return false;
 }
References CACHE_STATUS_DIRTY, CACHE_STATUS_MIRROR_FAT, cache_t::data, DBG_FAIL_MACRO, sector(), and FatPartition::sectorsPerFat().
Referenced by read().
Member Data Documentation
CACHE_FOR_READ
const uint8_t FatCache::CACHE_FOR_READ = 0 static
Cache sector for read.
Definition at line 80 of file FatPartition.h.
Referenced by FatFile::dirEntry(), FatPartition::dmpFat(), FatPartition::freeClusterCount(), FatFile::getSFN(), FatPartition::init(), FatFile::read(), and FatFile::rename().
CACHE_FOR_WRITE
const uint8_t FatCache::CACHE_FOR_WRITE = CACHE_STATUS_DIRTY static
Cache sector for write.
Definition at line 82 of file FatPartition.h.
Referenced by FatFile::remove(), FatFile::rename(), FatFile::sync(), FatFile::timestamp(), and FatFile::write().
CACHE_OPTION_NO_READ
const uint8_t FatCache::CACHE_OPTION_NO_READ = 4 static
Sync existing sector but do not read new sector.
Definition at line 78 of file FatPartition.h.
Referenced by read().
CACHE_RESERVE_FOR_WRITE
const uint8_t FatCache::CACHE_RESERVE_FOR_WRITE = CACHE_STATUS_DIRTY | CACHE_OPTION_NO_READ static
Reserve cache sector for write - do not read from sector device.
Definition at line 84 of file FatPartition.h.
Referenced by FatFile::write().
CACHE_STATUS_DIRTY
const uint8_t FatCache::CACHE_STATUS_DIRTY = 1 static
Cached sector is dirty
Definition at line 71 of file FatPartition.h.
Referenced by dirty(), isDirty(), and sync().
CACHE_STATUS_MASK
const uint8_t FatCache::CACHE_STATUS_MASK = CACHE_STATUS_DIRTY | CACHE_STATUS_MIRROR_FAT static
Cache sector status bits
Definition at line 75 of file FatPartition.h.
Referenced by read().
CACHE_STATUS_MIRROR_FAT
const uint8_t FatCache::CACHE_STATUS_MIRROR_FAT = 2 static
Cashed sector is FAT entry and must be mirrored in second FAT.
Definition at line 73 of file FatPartition.h.
Referenced by sync().
The documentation for this class was generated from the following files:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/FatLib/FatPartition.h
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/FatLib/FatPartition.cpp