ERIS CORE: FsUtf Namespace Reference
FsUtf Namespace Reference
Functions
char * cpToMb (uint32_t cp, char *str, char *end)
uint16_t highSurrogate (uint32_t cp)
bool isHighSurrogate (uint16_t c)
bool isLowSurrogate (uint16_t c)
bool isSurrogate (uint16_t c)
bool isValidCp (uint32_t cp)
uint16_t lowSurrogate (uint32_t cp)
const char * mbToCp (const char *str, const char *end, uint32_t *rtn)
const char * mbToU16 (const char *str, const char *end, uint16_t *hs, uint16_t *ls)
uint32_t u16ToCp (uint16_t hs, uint16_t ls)
Detailed Description
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Function Documentation
cpToMb()
char * FsUtf::cpToMb (uint32_t cp, char * str, char * end)
Encodes a 32 bit code point as a UTF-8 sequence.
Parameters
[in] cp code point to encode.
[out] str location for UTF-8 sequence.
[in] end location following last character of str.
Returns
location one beyond last encoded character.
Definition at line 28 of file FsUtf.cpp.
{
     size_t n = end - str;
     if (cp < 0X80) {
       if (n < 1) goto fail;
       *(str++) = static_cast<uint8_t>(cp);
     } else if (cp < 0X800) {
       if (n < 2) goto fail;
       *(str++) = static_cast<uint8_t>((cp >> 6)          | 0XC0);
       *(str++) = static_cast<uint8_t>((cp & 0X3F)        | 0X80);
     } else if (cp < 0X10000) {
       if (n < 3) goto fail;
       *(str++) = static_cast<uint8_t>((cp >> 12)         | 0XE0);
       *(str++) = static_cast<uint8_t>(((cp >> 6) & 0X3F) | 0X80);
       *(str++) = static_cast<uint8_t>((cp & 0X3F)        | 0X80);
     } else {
        if (n < 4) goto fail;
       *(str++) = static_cast<uint8_t>((cp >> 18)         | 0XF0);
       *(str++) = static_cast<uint8_t>(((cp >> 12) & 0X3F)| 0X80);
       *(str++) = static_cast<uint8_t>(((cp >> 6) & 0X3F) | 0X80);
       *(str++) = static_cast<uint8_t>((cp & 0X3F)        | 0X80);
     }
     return str;
    fail:
     return nullptr;
   }
Referenced by ExFatFile::getName8(), FatFile::getName8(), ExFatFile::printName8(), and FatFile::printName8().
highSurrogate()
uint16_t FsUtf::highSurrogate (uint32_t cp) inline
High surrogate for a code point.
Parameters
cp code point.
Returns
high surrogate.
Definition at line 38 of file FsUtf.h.
{
     return (cp >> 10) + (0XD800 - (0X10000 >> 10));
   }
Referenced by mbToU16().
isHighSurrogate()
bool FsUtf::isHighSurrogate (uint16_t c) inline
Check for UTF-16 high surrogate.
Parameters
[in] c UTF-16 unit..
Returns
true if c is a high surrogate else false.
Definition at line 66 of file FsUtf.h.
{
     return 0XD800 <= c && c <= 0XDBFF;
   }
Referenced by ExFatFile::getName8(), FatFile::getName8(), ExFatFile::printName8(), and FatFile::printName8().
isLowSurrogate()
bool FsUtf::isLowSurrogate (uint16_t c) inline
Check for UTF-16 low surrogate.
Parameters
[in] c UTF-16 unit..
Returns
true if c is a low surrogate else false.
Definition at line 73 of file FsUtf.h.
{
     return 0XDC00 <= c && c <= 0XDFFF;
   }
Referenced by ExFatFile::getName8(), FatFile::getName8(), ExFatFile::printName8(), and FatFile::printName8().
isSurrogate()
bool FsUtf::isSurrogate (uint16_t c) inline
Check for UTF-16 surrogate.
Parameters
[in] c UTF-16 unit.
Returns
true if c is a surrogate else false.
Definition at line 59 of file FsUtf.h.
{
     return 0XD800 <= c && c <= 0XDFFF;
   }
Referenced by ExFatFile::getName8(), FatFile::getName8(), ExFatFile::printName8(), and FatFile::printName8().
isValidCp()
bool FsUtf::isValidCp (uint32_t cp) inline
Check for a valid code point.
Parameters
[in] cp code point.
Returns
true if valid else false.
Definition at line 52 of file FsUtf.h.
{
     return cp <= 0x10FFFF && (cp < 0XD800 || cp > 0XDFFF);
   }
Referenced by mbToCp().
lowSurrogate()
uint16_t FsUtf::lowSurrogate (uint32_t cp) inline
Low surrogate for a code point.
Parameters
cp code point.
Returns
low surrogate.
Definition at line 45 of file FsUtf.h.
{
     return (cp & 0X3FF) + 0XDC00;
   }
Referenced by mbToU16().
mbToCp()
const char * FsUtf::mbToCp (const char * str, const char * end, uint32_t * rtn)
Get next code point from a UTF-8 sequence.
Parameters
[in] str location for UTF-8 sequence.
[in] end location following last character of str. May be nullptr if str is zero terminated.
[out] rtn location for the code point.
Returns
location of next UTF-8 character in str of nullptr for error.
Definition at line 56 of file FsUtf.cpp.
{
     size_t n;
     uint32_t cp;
     if (str >= end) {
       return nullptr;
     }
     uint8_t ch = str[0];
     if ((ch & 0X80) == 0) {
       *rtn = ch;
       return str + 1;
     }
     if ((ch & 0XE0) == 0XC0) {
       cp = ch & 0X1F;
       n = 2;
     } else if ((ch & 0XF0) == 0XE0) {
       cp = ch & 0X0F;
       n = 3;
     } else if ((ch & 0XF8) == 0XF0) {
       cp = ch & 0X07;
       n = 4;
     } else {
       return nullptr;
     }
     if ((str + n) > end) {
       return nullptr;
     }
     for (size_t i = 1; i < n; i++) {
       ch = str[i];
       if ((ch & 0XC0) != 0X80) {
         return nullptr;
       }
       cp <<= 6;
       cp |= ch & 0X3F;
     }
     // Don't allow over long as ASCII.
     if (cp < 0X80 || !isValidCp(cp)) {
       return nullptr;
     }
     *rtn = cp;
     return str + n;
   }
References isValidCp().
Referenced by mbToU16().
mbToU16()
const char * FsUtf::mbToU16 (const char * str, const char * end, uint16_t * hs, uint16_t * ls)
Get next code point from a UTF-8 sequence as UTF-16.
Parameters
[in] str location for UTF-8 sequence.
[in] end location following last character of str.
[out] hs location for the code point or high surrogate.
[out] ls location for zero or high surrogate.
Returns
location of next UTF-8 character in str of nullptr for error.
Definition at line 98 of file FsUtf.cpp.
{
     uint32_t cp;
     const char* ptr = mbToCp(str, end, &cp);
     if (!ptr) {
       return nullptr;
     }
     if (cp <= 0XFFFF) {
       *hs = cp;
       *ls = 0;
     } else {
       *hs = highSurrogate(cp);
       *ls = lowSurrogate(cp);
     }
     return ptr;
   }
References highSurrogate(), lowSurrogate(), and mbToCp().
u16ToCp()
uint32_t FsUtf::u16ToCp (uint16_t hs, uint16_t ls) inline
Convert UFT-16 surrogate pair to code point.
Parameters
[in] hs high surrogate.
[in] ls low surrogate.
Returns
code point.
Definition at line 81 of file FsUtf.h.
{
     return 0X10000 + (((hs & 0X3FF) << 10) | (ls & 0X3FF));
   }
Referenced by ExFatFile::getName8(), FatFile::getName8(), ExFatFile::printName8(), and FatFile::printName8().