ERIS CORE: Sphere3D Class Reference
Sphere3D Class Reference
#include <Sphere3D.h>
Public Member Functions
Sphere3D ()
uint_fast16_t bgColor (void)
virtual boolean forceTransitionNow (void)
void init (ILI9341_t3n tft)
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
virtual void reset (ILI9341_t3n tft)
String title ()
virtual boolean willForceTransition (void)
Detailed Description
Definition at line 19 of file Sphere3D.h.
Constructor & Destructor Documentation
Sphere3D()
Sphere3D::Sphere3D () inline
Definition at line 21 of file Sphere3D.h.
 : BaseAnimation() {};
Member Function Documentation
bgColor()
uint_fast16_t Sphere3D::bgColor (void) virtual
Reimplemented from BaseAnimation.
Definition at line 50 of file Sphere3D.h.
{
     return _bgColor;
 }
forceTransitionNow()
boolean BaseAnimation::forceTransitionNow (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 44 of file BaseAnimation.h.
{
     // Extend me
     return false;   // Default: SuperTFT will transition animations automatically
 }
init()
void Sphere3D::init (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
Definition at line 39 of file Sphere3D.h.
{
   uint_fast16_t w = tft.width();
   uint_fast16_t h = tft.height();
   //_bgColor = tft.color565( 0, 0x44, 0x44 ); // Only looks good in low light :P
   _bgColor = tft.color565( 0, 0, 0 );
   Point16 sphereTopOnScreen = xyz2screen( 0, -1.0f, SPHERE_DISTANCE, (w>>1), (h>>1) );
   _baseCircSize = (h/2) - sphereTopOnScreen.y + 1;
 }
References SPHERE_DISTANCE, tft(), xyz2screen(), and Point16::y.
perFrame()
void Sphere3D::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseAnimation.
Definition at line 76 of file Sphere3D.h.
{
   uint_fast16_t w = (uint_fast16_t)tft.width();
   uint_fast16_t h = (uint_fast16_t)tft.height();
     uint_fast16_t w_2 = (w>>1);
     uint_fast16_t h_2 = (h>>1);
     float oldPhase = _rotatePhase;
   _rotatePhase += frameParams.timeMult * SPHERE_3D_ROTATE_SPEED;
     _sparkle = max( (frameParams.audioPeak >> 1), _sparkle * (1.0f-(frameParams.timeMult*0.02f)) );
     uint_fast16_t erase = _bgColor;
     float x, y, z, sinLat;
   float oldTilt = -sin( oldPhase * SPHERE_3D_TILT_SPEED ) * SPHERE_3D_TILT_AMOUNT;
   float oldCosTilt = cos( oldTilt );
   float oldSinTilt = sin( oldTilt );
   float tilt = -sin( _rotatePhase * SPHERE_3D_TILT_SPEED ) * SPHERE_3D_TILT_AMOUNT;
   float cosTilt = cos( tilt );
   float sinTilt = sin( tilt );
     // Rotating sphere yo
     for( float lon=0.0f; lon<(M_PI*0.5f); lon+=(M_PI*0.125f) ) {    // longitude (around). Only 1/4 of sphere circumference.
         for( float lat=(M_PI*0.0625f); lat<(M_PI*0.5f); lat+=(M_PI*0.125f) ) {  // latitude (up & down). Only 1/2 of sphere height.
             // Erase the old line here
             x = cos( oldPhase + lon );
             z = sin( oldPhase + lon );
             y = cos( lat );
             sinLat = sin( lat );
             x *= sinLat;
             z *= sinLat;
             // We can swap & negate x,y,z to draw at least 8 lines without recomputing cos & sin values etc
             _drawLine( tft, oldCosTilt, oldSinTilt, x, y, z, w_2, h_2, erase );
             _drawLine( tft, oldCosTilt, oldSinTilt, -x, y, -z, w_2, h_2, erase );
             _drawLine( tft, oldCosTilt, oldSinTilt, -z, y, x, w_2, h_2, erase );
             _drawLine( tft, oldCosTilt, oldSinTilt, z, y, -x, w_2, h_2, erase );
             // Draw the other hemisphere
             _drawLine( tft, oldCosTilt, oldSinTilt, x, -y, z, w_2, h_2, erase );
             _drawLine( tft, oldCosTilt, oldSinTilt, -x, -y, -z, w_2, h_2, erase );
             _drawLine( tft, oldCosTilt, oldSinTilt, -z, -y, x, w_2, h_2, erase );
             _drawLine( tft, oldCosTilt, oldSinTilt, z, -y, -x, w_2, h_2, erase );
             // Now, draw the new lines
       uint_fast16_t color = tft.color565(
         random( _sparkle>>1, _sparkle ),
         random( _sparkle>>1, _sparkle ),
         0xff
       );
             x = cos( _rotatePhase + lon );
             z = sin( _rotatePhase + lon );
             // Now we need the y (up & down), then normalize x & z to create a normalized 3D vector (length == 1.0)
             y = cos( lat );
             sinLat = sin( lat );
             x *= sinLat;
             z *= sinLat;
             // We can swap & negate x,y,z to draw at least 8 lines without recomputing cos & sin values etc
             _drawLine( tft, cosTilt, sinTilt, x, y, z, w_2, h_2, color );
             _drawLine( tft, cosTilt, sinTilt, -x, y, -z, w_2, h_2, color );
             _drawLine( tft, cosTilt, sinTilt, -z, y, x, w_2, h_2, color );
             _drawLine( tft, cosTilt, sinTilt, z, y, -x, w_2, h_2, color );
             // Draw the other hemisphere
             _drawLine( tft, cosTilt, sinTilt, x, -y, z, w_2, h_2, color );
             _drawLine( tft, cosTilt, sinTilt, -x, -y, -z, w_2, h_2, color );
             _drawLine( tft, cosTilt, sinTilt, -z, -y, x, w_2, h_2, color );
             _drawLine( tft, cosTilt, sinTilt, z, -y, -x, w_2, h_2, color );
         }
     }
     const uint_fast8_t RADIATION_PX = 12;
   _circStep += random(1,4);
   if( _circStep > RADIATION_PX ) _circStep -= RADIATION_PX;
     float brightAmt = ((frameParams.audioMean + 1.0f) * 0.5f);  // 0.5...1
     uint_fast8_t bright = (0xff/RADIATION_PX) * brightAmt;
     uint_fast16_t radiationColor = tft.color565( 0, random((RADIATION_PX-_circStep)*(bright>>1)), random((RADIATION_PX-_circStep)*bright) ) | _bgColor;
   tft.drawCircle( w_2, h_2, _baseCircSize + _circStep, radiationColor );
 }
References FrameParams::audioMean, FrameParams::audioPeak, erase, SPHERE_3D_ROTATE_SPEED, SPHERE_3D_TILT_AMOUNT, SPHERE_3D_TILT_SPEED, tft(), FrameParams::timeMult, x, and y.
reset()
void BaseAnimation::reset (ILI9341_t3n tft) virtual inherited
Reimplemented in TwistyText.
Definition at line 32 of file BaseAnimation.h.
{
     // Extend me
 }
title()
String Sphere3D::title () virtual
Reimplemented from BaseAnimation.
Definition at line 54 of file Sphere3D.h.
{
     return "Sphere3D";
 }
willForceTransition()
boolean BaseAnimation::willForceTransition (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 40 of file BaseAnimation.h.
{
     return false;   // Default: SuperTFT will transition animations automatically
 }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/Sphere3D.h