ERIS CORE: FsCache Class Reference
FsCache Class Reference
Sector cache.
#include <FsCache.h>
Public Member Functions
uint8_t * cacheBuffer ()
bool cacheSafeRead (uint32_t sector, uint8_t *dst)
bool cacheSafeRead (uint32_t sector, uint8_t *dst, size_t count)
bool cacheSafeWrite (uint32_t sector, const uint8_t *src)
bool cacheSafeWrite (uint32_t sector, const uint8_t *src, size_t count)
uint8_t * clear ()
void dirty ()
void init (BlockDevice *blockDev)
void invalidate ()
bool isCached (uint32_t sector) const
bool isCached (uint32_t sector, size_t count)
bool isDirty ()
uint8_t * prepare (uint32_t sector, uint8_t option)
uint32_t sector ()
void setMirrorOffset (uint32_t offset)
bool sync ()
Static Public Attributes
static const uint8_t CACHE_FOR_READ = 0
static const uint8_t CACHE_FOR_WRITE = CACHE_STATUS_DIRTY
static const uint8_t CACHE_OPTION_NO_READ = 4
static const uint8_t CACHE_RESERVE_FOR_WRITE
static const uint8_t CACHE_STATUS_DIRTY = 1
static const uint8_t CACHE_STATUS_MASK
static const uint8_t CACHE_STATUS_MIRROR_FAT = 2
Private Attributes
BlockDevice * m_blockDev
uint8_t m_buffer [512]
uint32_t m_mirrorOffset
uint32_t m_sector
uint8_t m_status
Detailed Description
Sector cache.
Definition at line 37 of file FsCache.h.
Member Function Documentation
cacheBuffer()
uint8_t* FsCache::cacheBuffer () inline
Returns
Cache buffer address.
Definition at line 57 of file FsCache.h.
{
     return m_buffer;
   }
References m_buffer.
Referenced by FatPartition::cacheAddress().
cacheSafeRead() [1/2]
bool FsCache::cacheSafeRead (uint32_t sector, uint8_t * dst) inline
Cache safe read of a sector.
Parameters
[in] sector Logical sector to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 67 of file FsCache.h.
{
     if (isCached(sector)) {
       memcpy(dst, m_buffer, 512);
       return true;
     }
     return m_blockDev->readSector(sector, dst);
   }
References dst, isCached(), m_blockDev, m_buffer, SharedSpiCard::readSector(), and sector().
Referenced by ExFatPartition::cacheSafeRead().
cacheSafeRead() [2/2]
bool FsCache::cacheSafeRead (uint32_t sector, uint8_t * dst, size_t count) inline
Cache safe read of multiple sectors.
Parameters
[in] sector Logical sector to be read.
[in] count Number of sectors to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 82 of file FsCache.h.
{
     if (isCached(sector, count) && !sync()) {
       return false;
     }
     return m_blockDev->readSectors(sector, dst, count);
   }
References count, dst, isCached(), m_blockDev, SharedSpiCard::readSectors(), sector(), and sync().
cacheSafeWrite() [1/2]
bool FsCache::cacheSafeWrite (uint32_t sector, const uint8_t * src) inline
Cache safe write of a sectors.
Parameters
[in] sector Logical sector to be written.
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 95 of file FsCache.h.
{
     if (isCached(sector)) {
       invalidate();
     }
     return m_blockDev->writeSector(sector, src);
   }
References invalidate(), isCached(), m_blockDev, sector(), and SharedSpiCard::writeSector().
Referenced by ExFatPartition::cacheSafeWrite().
cacheSafeWrite() [2/2]
bool FsCache::cacheSafeWrite (uint32_t sector, const uint8_t * src, size_t count) inline
Cache safe write of multiple sectors.
Parameters
[in] sector Logical sector to be written.
[in] src Pointer to the location of the data to be written.
[in] count Number of sectors to be written.
Returns
true for success or false for failure.
Definition at line 109 of file FsCache.h.
{
      if (isCached(sector, count)) {
       invalidate();
     }
     return m_blockDev->writeSectors(sector, src, count);
   }
References count, invalidate(), isCached(), m_blockDev, sector(), and SharedSpiCard::writeSectors().
clear()
uint8_t* FsCache::clear () inline
Returns
Clear the cache and returns a pointer to the cache.
Definition at line 116 of file FsCache.h.
                    {
     if (isDirty() && !sync()) {
       return nullptr;
     }
     invalidate();
     return m_buffer;
   }
References invalidate(), isDirty(), m_buffer, and sync().
Referenced by ExFatPartition::cacheClear().
dirty()
void FsCache::dirty () inline
Set current sector dirty.
Definition at line 124 of file FsCache.h.
                {
     m_status |= CACHE_STATUS_DIRTY;
   }
References CACHE_STATUS_DIRTY, and m_status.
Referenced by FatPartition::cacheDirty(), and ExFatPartition::dataCacheDirty().
init()
void FsCache::init (BlockDevice * blockDev) inline
Initialize the cache.
Parameters
[in] blockDev Block device for this cache.
Definition at line 130 of file FsCache.h.
{
     m_blockDev = blockDev;
     invalidate();
   }
References invalidate(), and m_blockDev.
Referenced by ExFatPartition::cacheInit(), and FatPartition::init().
invalidate()
void FsCache::invalidate () inline
Invalidate current cache sector.
Definition at line 135 of file FsCache.h.
                     {
     m_status = 0;
     m_sector = 0XFFFFFFFF;
   }
References m_sector, and m_status.
Referenced by FatPartition::cacheInvalidate(), cacheSafeWrite(), clear(), ExFatPartition::dataCacheInvalidate(), and init().
isCached() [1/2]
bool FsCache::isCached (uint32_t sector) const inline
Check if a sector is in the cache.
Parameters
[in] sector Sector to checked.
Returns
true if the sector is cached.
Definition at line 143 of file FsCache.h.
 {return sector == m_sector;}
References m_sector, and sector().
Referenced by cacheSafeRead(), and cacheSafeWrite().
isCached() [2/2]
bool FsCache::isCached (uint32_t sector, size_t count) inline
Check if the cache contains a sector from a range.
Parameters
[in] sector Start sector of the range.
[in] count Number of sectors in the range.
Returns
true if a sector in the range is cached.
Definition at line 149 of file FsCache.h.
{
     return sector <= m_sector && m_sector < (sector + count);
   }
References count, m_sector, and sector().
isDirty()
bool FsCache::isDirty () inline
Returns
dirty status
Definition at line 153 of file FsCache.h.
                  {
     return m_status & CACHE_STATUS_DIRTY;
   }
References CACHE_STATUS_DIRTY, and m_status.
Referenced by clear().
prepare()
uint8_t * FsCache::prepare (uint32_t sector, uint8_t option)
Prepare cache to access sector.
Parameters
[in] sector Sector to read.
[in] option mode for cached sector.
Returns
Address of cached sector.
Definition at line 29 of file FsCache.cpp.
{
   if (!m_blockDev) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (m_sector != sector) {
     if (!sync()) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!(option & CACHE_OPTION_NO_READ)) {
       if (!m_blockDev->readSector(sector, m_buffer)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_status = 0;
     m_sector = sector;
   }
   m_status |= option & CACHE_STATUS_MASK;
   return m_buffer;
  fail:
   return nullptr;
 }
References CACHE_OPTION_NO_READ, CACHE_STATUS_MASK, DBG_FAIL_MACRO, m_blockDev, m_buffer, m_sector, m_status, SharedSpiCard::readSector(), sector(), and sync().
Referenced by ExFatPartition::bitmapCachePrepare(), FatPartition::cachePrepare(), ExFatPartition::dataCachePrepare(), and FatPartition::dataCachePrepare().
sector()
uint32_t FsCache::sector () inline
Returns
Logical sector number for cached sector.
Definition at line 157 of file FsCache.h.
                     {
     return m_sector;
   }
References m_sector.
Referenced by cacheSafeRead(), cacheSafeWrite(), FatPartition::cacheSectorNumber(), ExFatPartition::dataCacheSector(), isCached(), prepare(), and sync().
setMirrorOffset()
void FsCache::setMirrorOffset (uint32_t offset) inline
Set the offset to the second FAT for mirroring.
Parameters
[in] offset Sector offset to second FAT.
Definition at line 163 of file FsCache.h.
{
     m_mirrorOffset = offset;
   }
References m_mirrorOffset.
Referenced by FatPartition::init().
sync()
bool FsCache::sync ()
Write current sector if dirty.
Returns
true for success or false for failure.
Definition at line 55 of file FsCache.cpp.
                    {
   if (m_status & CACHE_STATUS_DIRTY) {
     if (!m_blockDev->writeSector(m_sector, m_buffer)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // mirror second FAT
     if (m_status & CACHE_STATUS_MIRROR_FAT) {
       uint32_t sector = m_sector + m_mirrorOffset;
       if (!m_blockDev->writeSector(sector, m_buffer)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_status &= ~CACHE_STATUS_DIRTY;
   }
   return true;
  fail:
   return false;
 }
References CACHE_STATUS_DIRTY, CACHE_STATUS_MIRROR_FAT, DBG_FAIL_MACRO, m_blockDev, m_buffer, m_mirrorOffset, m_sector, m_status, sector(), and SharedSpiCard::writeSector().
Referenced by cacheSafeRead(), ExFatPartition::cacheSync(), FatPartition::cacheSync(), FatPartition::cacheSyncData(), clear(), ExFatPartition::dataCacheSync(), and prepare().
Member Data Documentation
CACHE_FOR_READ
const uint8_t FsCache::CACHE_FOR_READ = 0 static
Cache sector for read.
Definition at line 49 of file FsCache.h.
Referenced by ExFatPartition::bitmapFind(), ExFatPartition::checkUpcase(), FatFile::dirEntry(), ExFatPartition::dmpFat(), FatPartition::dmpFat(), ExFatPartition::dmpSector(), ExFatPartition::fatGet(), FatPartition::fatGet(), ExFatPartition::freeClusterCount(), FatPartition::freeClusterCount(), ExFatFile::getAccessDateTime(), ExFatFile::getCreateDateTime(), ExFatFile::getModifyDateTime(), ExFatFile::getName7(), ExFatFile::getName8(), FatFile::getSFN(), ExFatPartition::init(), FatPartition::init(), ExFatPartition::printDir(), ExFatFile::printName7(), ExFatFile::printName8(), ExFatPartition::printUpcase(), ExFatPartition::printVolInfo(), ExFatFile::read(), FatFile::read(), FatFile::rename(), ExFatFile::syncDir(), and ExFatFile::timestamp().
CACHE_FOR_WRITE
const uint8_t FsCache::CACHE_FOR_WRITE = CACHE_STATUS_DIRTY static
Cache sector for write.
Definition at line 51 of file FsCache.h.
Referenced by ExFatPartition::bitmapModify(), ExFatPartition::fatPut(), FatPartition::fatPut(), FatFile::mkdir(), ExFatFile::openPrivate(), ExFatFile::remove(), FatFile::remove(), FatFile::rename(), FatFile::sync(), ExFatFile::syncDir(), ExFatFile::timestamp(), FatFile::timestamp(), ExFatFile::write(), and FatFile::write().
CACHE_OPTION_NO_READ
const uint8_t FsCache::CACHE_OPTION_NO_READ = 4 static
Sync existing sector but do not read new sector.
Definition at line 47 of file FsCache.h.
Referenced by prepare().
CACHE_RESERVE_FOR_WRITE
const uint8_t FsCache::CACHE_RESERVE_FOR_WRITE static
Initial value:
=
    CACHE_STATUS_DIRTY | CACHE_OPTION_NO_READ
Reserve cache sector for write - do not read from sector device.
Definition at line 53 of file FsCache.h.
Referenced by ExFatFile::addDirCluster(), FatFile::addDirCluster(), ExFatFile::write(), and FatFile::write().
CACHE_STATUS_DIRTY
const uint8_t FsCache::CACHE_STATUS_DIRTY = 1 static
Cached sector is dirty
Definition at line 40 of file FsCache.h.
Referenced by dirty(), isDirty(), and sync().
CACHE_STATUS_MASK
const uint8_t FsCache::CACHE_STATUS_MASK static
Initial value:
=
    CACHE_STATUS_DIRTY | CACHE_STATUS_MIRROR_FAT
Cache sector status bits
Definition at line 44 of file FsCache.h.
Referenced by prepare().
CACHE_STATUS_MIRROR_FAT
const uint8_t FsCache::CACHE_STATUS_MIRROR_FAT = 2 static
Cashed sector is FAT entry and must be mirrored in second FAT.
Definition at line 42 of file FsCache.h.
Referenced by FatPartition::fatCachePrepare(), and sync().
m_blockDev
BlockDevice* FsCache::m_blockDev private
Definition at line 179 of file FsCache.h.
Referenced by cacheSafeRead(), cacheSafeWrite(), init(), prepare(), and sync().
m_buffer
uint8_t FsCache::m_buffer[512] private
Definition at line 182 of file FsCache.h.
Referenced by cacheBuffer(), cacheSafeRead(), clear(), prepare(), and sync().
m_mirrorOffset
uint32_t FsCache::m_mirrorOffset private
Definition at line 180 of file FsCache.h.
Referenced by setMirrorOffset(), and sync().
m_sector
uint32_t FsCache::m_sector private
Definition at line 181 of file FsCache.h.
Referenced by invalidate(), isCached(), prepare(), sector(), and sync().
m_status
uint8_t FsCache::m_status private
Definition at line 178 of file FsCache.h.
Referenced by dirty(), invalidate(), isDirty(), prepare(), and sync().
The documentation for this class was generated from the following files:
FsCache.h
FsCache.cpp