ERIS CORE: D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/upcase.cpp File Reference
upcase.cpp File Reference
#include "upcase.h"
Classes
struct map16
struct pair16
Macros
#define readTable16(sym) (sym)
#define readTable8(sym) (sym)
#define TABLE_MEM
Typedefs
typedef struct map16 map16_t
typedef struct pair16 pair16_t
Functions
bool exFatCmpName (const DirName_t *unicode, const char *name, size_t offset, size_t n)
bool exFatCmpName (const DirName_t *unicode, const ExChar16_t *name, size_t offset, size_t n)
uint16_t exFatHashName (const char *name, size_t n, uint16_t hash)
uint16_t exFatHashName (const ExChar16_t *name, size_t n, uint16_t hash)
uint16_t toUpcase (uint16_t chr)
uint32_t upcaseChecksum (uint16_t uc, uint32_t sum)
Variables
const size_t LOOKUP_DIM = sizeof(lookupTable)/sizeof(pair16_t)
const size_t MAP_DIM = sizeof(mapTable)/sizeof(map16_t)
Macro Definition Documentation
readTable16
#define readTable16 (sym) (sym)
Definition at line 35 of file upcase.cpp.
readTable8
#define readTable8 (sym) (sym)
Definition at line 34 of file upcase.cpp.
TABLE_MEM
#define TABLE_MEM
Copyright (c) 2011-2019 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 33 of file upcase.cpp.
Typedef Documentation
map16_t
typedef struct map16 map16_t
Definition at line 1 of file upcase.cpp.
pair16_t
typedef struct pair16 pair16_t
Definition at line 1 of file upcase.cpp.
Function Documentation
exFatCmpName() [1/2]
bool exFatCmpName (const DirName_t * unicode, const char * name, size_t offset, size_t n)
Copyright (c) 2011-2019 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 262 of file upcase.cpp.
{
   uint16_t u;
   for (size_t i = 0; i < n; i++) {
     u = getLe16(unicode->unicode + 2*i);
     if (u >= 0x7F  || toUpper(name[i + offset]) != toUpper(u)) {
       return false;
     }
   }
   return true;
 }
References getLe16(), and DirName_t::unicode.
exFatCmpName() [2/2]
bool exFatCmpName (const DirName_t * unicode, const ExChar16_t * name, size_t offset, size_t n)
Definition at line 234 of file upcase.cpp.
{
   uint16_t u;
   for (size_t i = 0; i < n; i++) {
     u = getLe16(unicode->unicode + 2*i);
     if (toUpcase(name[i + offset]) != toUpcase(u)) {
       return false;
     }
   }
   return true;
 }
References getLe16(), toUpcase(), and DirName_t::unicode.
exFatHashName() [1/2]
uint16_t exFatHashName (const char * name, size_t n, uint16_t hash)
Definition at line 250 of file upcase.cpp.
{
   for (size_t i = 0; i < n; i++) {
     uint8_t c = name[i];
     if ('a' <= c && c <= 'z') {
       c -= 'a' - 'A';
     }
     hash = ((hash << 15) | (hash >> 1)) + c;
     hash = ((hash << 15) | (hash >> 1));
   }
   return hash;
 }
exFatHashName() [2/2]
uint16_t exFatHashName (const ExChar16_t * name, size_t n, uint16_t hash)
Definition at line 188 of file upcase.cpp.
{
   for (size_t i = 0; i < n; i++) {
     uint16_t c = toUpcase(name[i]);
     hash = ((hash << 15) | (hash >> 1)) + (c & 0XFF);
     hash = ((hash << 15) | (hash >> 1)) + (c >> 8);
   }
   return hash;
 }
References toUpcase().
toUpcase()
uint16_t toUpcase (uint16_t chr)
Definition at line 212 of file upcase.cpp.
{
   uint16_t i, first;
   // Optimize for simple ASCII.
   if (chr < 127) {
     return chr - ('a' <= chr && chr <= 'z' ? 'a' - 'A' : 0);
   }
   i = searchPair16(reinterpret_cast<const pair16_t*>(mapTable), MAP_DIM, chr);
   first = readTable16(mapTable[i].base);
   if (first <= chr && (chr - first)  < readTable8(mapTable[i].count)) {
     int8_t off = readTable8(mapTable[i].off);
     if (off == 1) {
       return chr - ((chr - first) & 1);
     }
     return chr + (off ? off : -0x1C60);
   }
   i = searchPair16(lookupTable, LOOKUP_DIM, chr);
   if (readTable16(lookupTable[i].key) == chr) {
     return readTable16(lookupTable[i].val);
   }
   return chr;
 }
Referenced by ExFatPartition::checkUpcase(), exFatCmpName(), and exFatHashName().
upcaseChecksum()
uint32_t upcaseChecksum (uint16_t uc, uint32_t sum)
Definition at line 274 of file upcase.cpp.
{
   sum = (sum << 31) + (sum >> 1) + (uc & 0XFF);
   sum = (sum << 31) + (sum >> 1) + (uc >> 8);
   return sum;
 }
Variable Documentation
LOOKUP_DIM
const size_t LOOKUP_DIM = sizeof(lookupTable)/sizeof(pair16_t)
Definition at line 185 of file upcase.cpp.
MAP_DIM
const size_t MAP_DIM = sizeof(mapTable)/sizeof(map16_t)
Definition at line 106 of file upcase.cpp.