ERIS CORE: LZ4_compress_destSize_extState
LZ4_compress_destSize_extState()
static int LZ4_compress_destSize_extState (LZ4_stream_t * state, const char * src, char * dst, int * srcSizePtr, int targetDstSize) static
Definition at line 1394 of file lz4.c.
 {
     void* const s = LZ4_initStream(state, sizeof (*state));
     assert(s != NULL); (void)s;
     if (targetDstSize >= LZ4_compressBound(*srcSizePtr)) {  /* compression success is guaranteed */
         return LZ4_compress_fast_extState(state, src, dst, *srcSizePtr, targetDstSize, 1);
     } else {
         if (*srcSizePtr < LZ4_64Klimit) {
             return LZ4_compress_generic(&state->internal_donotuse, src, dst, *srcSizePtr, srcSizePtr, targetDstSize, fillOutput, byU16, noDict, noDictIssue, 1);
         } else {
             tableType_t const addrMode = ((sizeof(void*)==4) && ((uptrval)src > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
             return LZ4_compress_generic(&state->internal_donotuse, src, dst, *srcSizePtr, srcSizePtr, targetDstSize, fillOutput, addrMode, noDict, noDictIssue, 1);
     }   }
 }
References assert, byPtr, byU16, byU32, dst, fillOutput, LZ4_stream_u::internal_donotuse, LZ4_64Klimit, LZ4_compress_fast_extState(), LZ4_compress_generic(), LZ4_compressBound(), LZ4_initStream(), noDict, noDictIssue, and s.
Referenced by LZ4_compress_destSize().