ERIS CORE: LZ4_compress_generic
LZ4_compress_generic()
LZ4_FORCE_INLINE int LZ4_compress_generic (LZ4_stream_t_internal *const cctx, const char *const src, char *const dst, const int srcSize, int * inputConsumed, const int dstCapacity, const limitedOutput_directive outputDirective, const tableType_t tableType, const dict_directive dictDirective, const dictIssue_directive dictIssue, const int acceleration)
LZ4_compress_generic() : inlined, to ensure branches are decided at compilation time; takes care of src == (NULL, 0) and forward the rest to LZ4_compress_generic_validated
Definition at line 1258 of file lz4.c.
 {
     DEBUGLOG(5, "LZ4_compress_generic: srcSize=%i, dstCapacity=%i",
                 srcSize, dstCapacity);
     if ((U32)srcSize > (U32)LZ4_MAX_INPUT_SIZE) { return 0; }  /* Unsupported srcSize, too large (or negative) */
     if (srcSize == 0) {   /* src == NULL supported if srcSize == 0 */
         if (outputDirective != notLimited && dstCapacity <= 0) return 0;  /* no output, can't write anything */
         DEBUGLOG(5, "Generating an empty block");
         assert(outputDirective == notLimited || dstCapacity >= 1);
         assert(dst != NULL);
         dst[0] = 0;
         if (outputDirective == fillOutput) {
             assert (inputConsumed != NULL);
             *inputConsumed = 0;
         }
         return 1;
     }
     assert(src != NULL);
     return LZ4_compress_generic_validated(cctx, src, dst, srcSize,
                 inputConsumed, /* only written into if outputDirective == fillOutput */
                 dstCapacity, outputDirective,
                 tableType, dictDirective, dictIssue, acceleration);
 }
References assert, DEBUGLOG, dst, fillOutput, LZ4_compress_generic_validated(), LZ4_MAX_INPUT_SIZE, notLimited, and srcSize.
Referenced by LZ4_compress_destSize_extState(), LZ4_compress_fast_continue(), LZ4_compress_fast_extState(), LZ4_compress_fast_extState_fastReset(), and LZ4_compress_forceExtDict().