ERIS CORE: LZ4_initStream
LZ4_initStream()
LZ4_stream_t* LZ4_initStream (void * buffer, size_t size)
LZ4_initStream() : v1.9.0+ An LZ4_stream_t structure must be initialized at least once. This is automatically done when invoking LZ4_createStream(), but it's not when the structure is simply declared on stack (for example).
Use LZ4_initStream() to properly initialize a newly declared LZ4_stream_t. It can also initialize any arbitrary buffer of sufficient size, and will
Returns
a pointer of proper type upon initialization.
Note : initialization fails if size and alignment conditions are not respected. In which case, the function will
Returns
NULL. Note2: An LZ4_stream_t structure guarantees correct alignment and size. Note3: Before v1.9.0, use LZ4_resetStream() instead
Definition at line 1455 of file lz4.c.
 {
     DEBUGLOG(5, "LZ4_initStream");
     if (buffer == NULL) { return NULL; }
     if (size < sizeof(LZ4_stream_t)) { return NULL; }
     if (!LZ4_isAligned(buffer, LZ4_stream_t_alignment())) return NULL;
     MEM_INIT(buffer, 0, sizeof(LZ4_stream_t_internal));
     return (LZ4_stream_t*)buffer;
 }
References DEBUGLOG, LZ4_isAligned(), LZ4_stream_t_alignment(), and MEM_INIT.
Referenced by LZ4_compress_destSize_extState(), LZ4_compress_fast_extState(), and LZ4_createStream().