ERIS CORE: LZ4_hashPosition
LZ4_hashPosition()
LZ4_FORCE_INLINE U32 LZ4_hashPosition (const void *const p, tableType_t const tableType)
Definition at line 726 of file lz4.c.
 {
     if ((sizeof(reg_t)==8) && (tableType != byU16)) return LZ4_hash5(LZ4_read_ARCH(p), tableType);
     return LZ4_hash4(LZ4_read32(p), tableType);
 }
References byU16, LZ4_hash4(), LZ4_hash5(), LZ4_read32(), LZ4_read_ARCH(), and p.
Referenced by LZ4_compress_generic_validated(), LZ4_getPosition(), and LZ4_putPosition().