ERIS CORE: LZ4_writeLE16
LZ4_writeLE16()
static void LZ4_writeLE16 (void * memPtr, U16 value) static
Definition at line 395 of file lz4.c.
 {
     if (LZ4_isLittleEndian()) {
         LZ4_write16(memPtr, value);
     } else {
         BYTE* p = (BYTE*)memPtr;
         p[0] = (BYTE) value;
         p[1] = (BYTE)(value>>8);
     }
 }
References LZ4_isLittleEndian(), LZ4_write16(), and p.
Referenced by LZ4_compress_generic_validated().