ERIS CORE: LZ4_readLE16
LZ4_readLE16()
static U16 LZ4_readLE16 (const void * memPtr) static
Definition at line 385 of file lz4.c.
 {
     if (LZ4_isLittleEndian()) {
         return LZ4_read16(memPtr);
     } else {
         const BYTE* p = (const BYTE*)memPtr;
         return (U16)((U16)p[0] + (p[1]<<8));
     }
 }
References LZ4_isLittleEndian(), LZ4_read16(), and p.
Referenced by LZ4_decompress_generic().