ERIS CORE: LZ4_count
LZ4_count()
LZ4_FORCE_INLINE unsigned LZ4_count (const BYTE * pIn, const BYTE * pMatch, const BYTE * pInLimit)
Definition at line 611 of file lz4.c.
 {
     const BYTE* const pStart = pIn;
     if (likely(pIn < pInLimit-(STEPSIZE-1))) {
         reg_t const diff = LZ4_read_ARCH(pMatch) ^ LZ4_read_ARCH(pIn);
         if (!diff) {
             pIn+=STEPSIZE; pMatch+=STEPSIZE;
         } else {
             return LZ4_NbCommonBytes(diff);
     }   }
     while (likely(pIn < pInLimit-(STEPSIZE-1))) {
         reg_t const diff = LZ4_read_ARCH(pMatch) ^ LZ4_read_ARCH(pIn);
         if (!diff) { pIn+=STEPSIZE; pMatch+=STEPSIZE; continue; }
         pIn += LZ4_NbCommonBytes(diff);
         return (unsigned)(pIn - pStart);
     }
     if ((STEPSIZE==8) && (pIn<(pInLimit-3)) && (LZ4_read32(pMatch) == LZ4_read32(pIn))) { pIn+=4; pMatch+=4; }
     if ((pIn<(pInLimit-1)) && (LZ4_read16(pMatch) == LZ4_read16(pIn))) { pIn+=2; pMatch+=2; }
     if ((pIn<pInLimit) && (*pMatch == *pIn)) pIn++;
     return (unsigned)(pIn - pStart);
 }
References likely, LZ4_NbCommonBytes(), LZ4_read16(), LZ4_read32(), LZ4_read_ARCH(), and STEPSIZE.
Referenced by LZ4_compress_generic_validated().