ERIS CORE: LZ4_putPosition
LZ4_putPosition()
LZ4_FORCE_INLINE void LZ4_putPosition (const BYTE * p, void * tableBase, tableType_t tableType, const BYTE * srcBase)
Definition at line 769 of file lz4.c.
 {
     U32 const h = LZ4_hashPosition(p, tableType);
     LZ4_putPositionOnHash(p, h, tableBase, tableType, srcBase);
 }
References LZ4_hashPosition(), LZ4_putPositionOnHash(), and p.
Referenced by LZ4_compress_generic_validated(), and LZ4_loadDict().