ERIS CORE: LZ4_decompress_safe
LZ4_decompress_safe()
LZ4_FORCE_O2 int LZ4_decompress_safe (const char * src, char * dst, int compressedSize, int dstCapacity)
LZ4_decompress_safe() : compressedSize : is the exact complete size of the compressed block. dstCapacity : is the size of destination buffer (which must be already allocated), presumed an upper bound of decompressed size.
Returns
: the number of bytes decompressed into destination buffer (necessarily <= dstCapacity) If destination buffer is not large enough, decoding will stop and output an error code (negative value). If the source stream is detected malformed, the function will stop decoding and return a negative result. Note 1 : This function is protected against malicious data packets : it will never writes outside 'dst' buffer, nor read outside 'source' buffer, even if the compressed block is maliciously modified to order the decoder to do these actions. In such case, the decoder stops immediately, and considers the compressed block malformed. Note 2 : compressedSize and dstCapacity must be provided to the function, the compressed block does not contain them. The implementation is free to send / store / derive this information in whichever way is most beneficial. If there is a need for a different format which bundles together both compressed data and its metadata, consider looking at lz4frame.h instead.
Definition at line 2192 of file lz4.c.
 {
     return LZ4_decompress_generic(source, dest, compressedSize, maxDecompressedSize,
                                   endOnInputSize, decode_full_block, noDict,
                                   (BYTE*)dest, NULL, 0);
 }
References compressedSize, decode_full_block, dest, endOnInputSize, LZ4_decompress_generic(), noDict, and source.
Referenced by LZ4_decompress_safe_continue(), LZ4_decompress_safe_usingDict(), and LZ4_uncompress_unknownOutputSize().