ERIS CORE: wren_opt_random.h File Reference
wren_opt_random.h File Reference
#include "wren_common.h"
#include "wren.h"
Functions
WrenForeignClassMethods wrenRandomBindForeignClass (WrenVM *vm, const char *module, const char *className)
WrenForeignMethodFn wrenRandomBindForeignMethod (WrenVM *vm, const char *className, bool isStatic, const char *signature)
const char * wrenRandomSource ()
Function Documentation
wrenRandomBindForeignClass()
WrenForeignClassMethods wrenRandomBindForeignClass (WrenVM * vm, const char * module, const char * className)
Definition at line 110 of file wren_opt_random.c.
 {
   ASSERT(strcmp(className, "Random") == 0, "Should be in Random class.");
   WrenForeignClassMethods methods;
   methods.allocate = randomAllocate;
   methods.finalize = NULL;
   return methods;
 }
References WrenForeignClassMethods::allocate, ASSERT, WrenForeignClassMethods::finalize, NULL, and randomAllocate().
Referenced by bindForeignClass().
wrenRandomBindForeignMethod()
WrenForeignMethodFn wrenRandomBindForeignMethod (WrenVM * vm, const char * className, bool isStatic, const char * signature)
Definition at line 121 of file wren_opt_random.c.
 {
   ASSERT(strcmp(className, "Random") == 0, "Should be in Random class.");
   if (strcmp(signature, "<allocate>") == 0) return randomAllocate;
   if (strcmp(signature, "seed_()") == 0) return randomSeed0;
   if (strcmp(signature, "seed_(_)") == 0) return randomSeed1;
   if (strcmp(signature, "seed_(_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_)") == 0)
   {
     return randomSeed16;
   }
   if (strcmp(signature, "float()") == 0) return randomFloat;
   if (strcmp(signature, "int()") == 0) return randomInt0;
   ASSERT(false, "Unknown method.");
   return NULL;
 }
References ASSERT, NULL, randomAllocate(), randomFloat(), randomInt0(), randomSeed0(), randomSeed1(), and randomSeed16().
Referenced by findForeignMethod().
wrenRandomSource()
const char* wrenRandomSource ()
Definition at line 105 of file wren_opt_random.c.
 {
   return randomModuleSource;
 }
Referenced by importModule().