ERIS CORE: ios.h File Reference
ios.h File Reference
ios_base and ios classes
#include "../FsLib/FsLib.h"
Classes
class ios
Error and state information for all streams.
class ios_base
Base class for all streams.
Typedefs
typedef fspos_t pos_t
Functions
ios_base & boolalpha (ios_base &str)
ios_base & dec (ios_base &str)
ios_base & hex (ios_base &str)
ios_base & internal (ios_base &str)
ios_base & left (ios_base &str)
ios_base & noboolalpha (ios_base &str)
ios_base & noshowbase (ios_base &str)
ios_base & noshowpoint (ios_base &str)
ios_base & noshowpos (ios_base &str)
ios_base & noskipws (ios_base &str)
ios_base & nouppercase (ios_base &str)
ios_base & oct (ios_base &str)
ios_base & right (ios_base &str)
ios_base & showbase (ios_base &str)
ios_base & showpoint (ios_base &str)
ios_base & showpos (ios_base &str)
ios_base & skipws (ios_base &str)
ios_base & uppercase (ios_base &str)
Detailed Description
ios_base and ios classes
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file ios.h.
Typedef Documentation
pos_t
typedef fspos_t pos_t
For internal use in c++ streams
Definition at line 34 of file ios.h.
Function Documentation
boolalpha()
ios_base& boolalpha (ios_base & str) inline
function for boolalpha manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 244 of file ios.h.
{
   str.setf(ios_base::boolalpha);
   return str;
 }
References ios_base::boolalpha, and ios_base::setf().
dec()
ios_base& dec (ios_base & str) inline
function for dec manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 252 of file ios.h.
{
   str.setf(ios_base::dec, ios_base::basefield);
   return str;
 }
References ios_base::basefield, ios_base::dec, and ios_base::setf().
hex()
ios_base& hex (ios_base & str) inline
function for hex manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 260 of file ios.h.
{
   str.setf(ios_base::hex, ios_base::basefield);
   return str;
 }
References ios_base::basefield, ios_base::hex, and ios_base::setf().
Referenced by ios_base::flagsToBase(), and ostream::putNum().
internal()
ios_base& internal (ios_base & str) inline
function for internal manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 268 of file ios.h.
{
   str.setf(ios_base::internal, ios_base::adjustfield);
   return str;
 }
References ios_base::adjustfield, ios_base::internal, and ios_base::setf().
left()
ios_base& left (ios_base & str) inline
function for left manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 276 of file ios.h.
{
   str.setf(ios_base::left, ios_base::adjustfield);
   return str;
 }
References ios_base::adjustfield, ios_base::left, and ios_base::setf().
Referenced by searchPair16().
noboolalpha()
ios_base& noboolalpha (ios_base & str) inline
function for noboolalpha manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 284 of file ios.h.
{
   str.unsetf(ios_base::boolalpha);
   return str;
 }
References ios_base::boolalpha, and ios_base::unsetf().
noshowbase()
ios_base& noshowbase (ios_base & str) inline
function for noshowbase manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 292 of file ios.h.
{
   str.unsetf(ios_base::showbase);
   return str;
 }
References ios_base::showbase, and ios_base::unsetf().
noshowpoint()
ios_base& noshowpoint (ios_base & str) inline
function for noshowpoint manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 300 of file ios.h.
{
   str.unsetf(ios_base::showpoint);
   return str;
 }
References ios_base::showpoint, and ios_base::unsetf().
noshowpos()
ios_base& noshowpos (ios_base & str) inline
function for noshowpos manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 308 of file ios.h.
{
   str.unsetf(ios_base::showpos);
   return str;
 }
References ios_base::showpos, and ios_base::unsetf().
noskipws()
ios_base& noskipws (ios_base & str) inline
function for noskipws manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 316 of file ios.h.
{
   str.unsetf(ios_base::skipws);
   return str;
 }
References ios_base::skipws, and ios_base::unsetf().
nouppercase()
ios_base& nouppercase (ios_base & str) inline
function for nouppercase manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 324 of file ios.h.
{
   str.unsetf(ios_base::uppercase);
   return str;
 }
References ios_base::unsetf(), and ios_base::uppercase.
oct()
ios_base& oct (ios_base & str) inline
function for oct manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 332 of file ios.h.
{
   str.setf(ios_base::oct, ios_base::basefield);
   return str;
 }
References ios_base::basefield, ios_base::oct, and ios_base::setf().
Referenced by ios_base::flagsToBase().
right()
ios_base& right (ios_base & str) inline
function for right manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 340 of file ios.h.
{
   str.setf(ios_base::right, ios_base::adjustfield);
   return str;
 }
References ios_base::adjustfield, ios_base::right, and ios_base::setf().
Referenced by searchPair16().
showbase()
ios_base& showbase (ios_base & str) inline
function for showbase manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 348 of file ios.h.
{
   str.setf(ios_base::showbase);
   return str;
 }
References ios_base::setf(), and ios_base::showbase.
Referenced by ostream::putNum().
showpoint()
ios_base& showpoint (ios_base & str) inline
function for showpoint manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 364 of file ios.h.
{
   str.setf(ios_base::showpoint);
   return str;
 }
References ios_base::setf(), and ios_base::showpoint.
showpos()
ios_base& showpos (ios_base & str) inline
function for showpos manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 356 of file ios.h.
{
   str.setf(ios_base::showpos);
   return str;
 }
References ios_base::setf(), and ios_base::showpos.
Referenced by ostream::putNum().
skipws()
ios_base& skipws (ios_base & str) inline
function for skipws manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 372 of file ios.h.
{
   str.setf(ios_base::skipws);
   return str;
 }
References ios_base::setf(), and ios_base::skipws.
uppercase()
ios_base& uppercase (ios_base & str) inline
function for uppercase manipulator
Parameters
[in] str The stream
Returns
The stream
Definition at line 380 of file ios.h.
{
   str.setf(ios_base::uppercase);
   return str;
 }
References ios_base::setf(), and ios_base::uppercase.
Referenced by ostream::fmtNum(), and ostream::putNum().