ERIS CORE: FsBaseFile Class Reference
FsBaseFile Class Reference
FsBaseFile class.
#include <FsFile.h>
Public Member Functions
FsBaseFile ()
FsBaseFile (const FsBaseFile &from)
~FsBaseFile ()
int available ()
void clearWriteError ()
bool close ()
uint64_t curPosition ()
uint32_t dirIndex ()
bool exists (const char *path)
void fgetpos (fspos_t *pos)
int fgets (char *str, int num, char *delim=nullptr)
uint64_t fileSize ()
void flush ()
void fsetpos (const fspos_t *pos)
uint8_t getError ()
size_t getName (char *name, size_t len)
bool getWriteError ()
bool isDir ()
bool isDirectory ()
bool isHidden ()
bool isOpen ()
bool isSubDir ()
bool ls (print_t *pr)
bool ls (print_t *pr, uint8_t flags)
bool mkdir (FsBaseFile *dir, const char *path, bool pFlag=true)
const char * name () const
bool open (const char *path, oflag_t oflag=O_RDONLY)
bool open (FsBaseFile *dir, const char *path, oflag_t oflag=O_RDONLY)
bool open (FsBaseFile *dir, uint32_t index, oflag_t oflag)
bool open (FsVolume *vol, const char *path, oflag_t oflag)
bool openNext (FsBaseFile *dir, oflag_t oflag=O_RDONLY)
operator bool ()
FsBaseFile & operator= (const FsBaseFile &from)
int peek ()
uint64_t position ()
bool preAllocate (uint64_t length)
size_t printAccessDateTime (print_t *pr)
size_t printCreateDateTime (print_t *pr)
size_t printField (double value, char term, uint8_t prec=2)
size_t printField (float value, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type value, char term)
size_t printFileSize (print_t *pr)
size_t printModifyDateTime (print_t *pr)
size_t printName (print_t *pr)
int read ()
int read (void *buf, size_t count)
bool remove ()
bool remove (const char *path)
bool rename (const char *newPath)
bool rename (FsBaseFile *dirFile, const char *newPath)
void rewind ()
void rewindDirectory ()
bool rmdir ()
bool seek (uint64_t pos)
bool seekCur (int64_t offset)
bool seekEnd (int64_t offset=0)
bool seekSet (uint64_t pos)
uint64_t size ()
bool sync ()
bool timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
bool truncate ()
bool truncate (uint64_t length)
size_t write (const void *buf, size_t count)
size_t write (uint8_t b)
Detailed Description
FsBaseFile class.
Definition at line 38 of file FsFile.h.
Constructor & Destructor Documentation
FsBaseFile() [1/2]
FsBaseFile::FsBaseFile () inline
Definition at line 40 of file FsFile.h.
 : m_fFile(nullptr), m_xFile(nullptr) {}
~FsBaseFile()
FsBaseFile::~FsBaseFile () inline
Definition at line 42 of file FsFile.h.
 {close();}
References close().
FsBaseFile() [2/2]
FsBaseFile::FsBaseFile (const FsBaseFile & from)
Copy constructor.
Parameters
[in] from Object used to initialize this instance.
Copyright (c) 2011-2019 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 27 of file FsFile.cpp.
{
   m_fFile = nullptr;
   m_xFile = nullptr;
   if (from.m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     *m_fFile = *from.m_fFile;
   } else if (from.m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     *m_xFile = *from.m_xFile;
   }
 }
Member Function Documentation
available()
int FsBaseFile::available (void) inline
Returns
number of bytes available from the current position to EOF or INT_MAX if more than INT_MAX bytes are available.
Definition at line 61 of file FsFile.h.
                   {
     return m_fFile ? m_fFile->available() :
            m_xFile ? m_xFile->available() : 0;
   }
References ExFatFile::available(), and FatFile::available().
clearWriteError()
void FsBaseFile::clearWriteError () inline
Set writeError to zero
Definition at line 67 of file FsFile.h.
{
     if (m_fFile) m_fFile->clearWriteError();
     if (m_xFile) m_xFile->clearWriteError();
   }
References ExFatFile::clearWriteError(), and FatFile::clearWriteError().
close()
bool FsBaseFile::close ()
Close a file and force cached data and directory information to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 52 of file FsFile.cpp.
{
   if (m_fFile && m_fFile->close()) {
     m_fFile = nullptr;
     return true;
   }
   if (m_xFile && m_xFile->close()) {
     m_xFile = nullptr;
     return true;
   }
   return false;
 }
References ExFatFile::close(), and FatFile::close().
Referenced by ~FsBaseFile(), ILI9341_t3_ERIS::begin(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), mkdir(), open(), openNext(), operator=(), and AppSerialCommandInterface::streamHandler().
curPosition()
uint64_t FsBaseFile::curPosition () inline
Returns
The current position for a file or directory.
Definition at line 78 of file FsFile.h.
{
     return m_fFile ? m_fFile->curPosition() :
            m_xFile ? m_xFile->curPosition() : 0;
   }
References ExFatFile::curPosition(), and FatFile::curPosition().
dirIndex()
uint32_t FsBaseFile::dirIndex () inline
Returns
Directory entry index.
Definition at line 83 of file FsFile.h.
                       {
     return m_fFile ? m_fFile->dirIndex() :
            m_xFile ? m_xFile->dirIndex() : 0;
   }
References ExFatFile::dirIndex(), and FatFile::dirIndex().
exists()
bool FsBaseFile::exists (const char * path) inline
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
The calling instance must be an open directory file.
dirFile.exists("TOFIND.TXT") searches for "TOFIND.TXT" in the directory dirFile.
Returns
true if the file exists else false.
Definition at line 98 of file FsFile.h.
{
     return m_fFile ? m_fFile->exists(path) :
            m_xFile ? m_xFile->exists(path) : false;
   }
References FatFile::exists(), and ExFatFile::exists().
fgetpos()
void FsBaseFile::fgetpos (fspos_t * pos) inline
get position for streams
Parameters
[out] pos struct to receive position
Definition at line 105 of file FsFile.h.
{
     if (m_fFile) m_fFile->fgetpos(pos);
     if (m_xFile) m_xFile->fgetpos(pos);
   }
References ExFatFile::fgetpos(), and FatFile::fgetpos().
fgets()
int FsBaseFile::fgets (char * str, int num, char * delim = nullptr) inline
Get a string from a file.
fgets() reads bytes from a file into the array pointed to by str, until num - 1 bytes are read, or a delimiter is read and transferred to str, or end-of-file is encountered. The string is then terminated with a null byte.
fgets() deletes CR, '\r', from the string. This insures only a '\n' terminates the string for Windows text files which use CRLF for newline.
Parameters
[out] str Pointer to the array where the string is stored.
[in] num Maximum number of characters to be read (including the final null byte). Usually the length of the array str is used.
[in] delim Optional set of delimiters. The default is "\n".
Returns
For success fgets() returns the length of the string in str. If no data is read, fgets() returns zero for EOF or -1 if an error occurred.
Definition at line 129 of file FsFile.h.
{
     return m_fFile ? m_fFile->fgets(str, num, delim) :
            m_xFile ? m_xFile->fgets(str, num, delim) : -1;
   }
References ExFatFile::fgets(), and FatFile::fgets().
Referenced by ILI9341_t3_ERIS::begin(), and ILI9341_t3_ERIS::bltSD().
fileSize()
uint64_t FsBaseFile::fileSize () inline
Returns
The total number of bytes in a file.
Definition at line 134 of file FsFile.h.
                       {
     return m_fFile ? m_fFile->fileSize() :
            m_xFile ? m_xFile->fileSize() : 0;
   }
References ExFatFile::fileSize(), and FatFile::fileSize().
flush()
void FsBaseFile::flush () inline
Ensure that any bytes written to the file are saved to the SD card.
Definition at line 139 of file FsFile.h.
 {sync();}
References sync().
fsetpos()
void FsBaseFile::fsetpos (const fspos_t * pos) inline
set position for streams
Parameters
[in] pos struct with value for new position
Definition at line 143 of file FsFile.h.
{
     if (m_fFile) m_fFile->fsetpos(pos);
     if (m_xFile) m_xFile->fsetpos(pos);
   }
References ExFatFile::fsetpos(), and FatFile::fsetpos().
getError()
uint8_t FsBaseFile::getError () inline
Returns
All error bits.
Definition at line 148 of file FsFile.h.
                      {
     return m_fFile ? m_fFile->getError() :
            m_xFile ? m_xFile->getError() : 0XFF;
   }
References ExFatFile::getError(), and FatFile::getError().
getName()
size_t FsBaseFile::getName (char * name, size_t len) inline
Get a file's name followed by a zero byte.
Parameters
[out] name An array of characters for the file's name.
[in] len The size of the array in bytes. The array must be at least 13 bytes long. The file's name will be truncated if the file's name is too long.
Returns
The length of the returned string.
Definition at line 161 of file FsFile.h.
{
     *name = 0;
     return m_fFile ? m_fFile->getName(name, len) :
            m_xFile ? m_xFile->getName(name, len) : 0;
   }
References FatFile::getName(), ExFatFile::getName(), and name().
getWriteError()
bool FsBaseFile::getWriteError () inline
Returns
value of writeError
Definition at line 168 of file FsFile.h.
{
     return m_fFile ? m_fFile->getWriteError() :
            m_xFile ? m_xFile->getWriteError() : true;
   }
References ExFatFile::getWriteError(), and FatFile::getWriteError().
isDir()
bool FsBaseFile::isDir () inline
Returns
True if this is a directory else false.
Definition at line 173 of file FsFile.h.
                {
     return m_fFile ? m_fFile->isDir() :
            m_xFile ? m_xFile->isDir() : false;
   }
References ExFatFile::isDir(), and FatFile::isDir().
Referenced by isDirectory().
isDirectory()
bool FsBaseFile::isDirectory () inline
This function reports if the current file is a directory or not.
Returns
true if the file is a directory.
Definition at line 180 of file FsFile.h.
 {return isDir();}
References isDir().
isHidden()
bool FsBaseFile::isHidden () inline
Returns
True if this is a hidden file else false.
Definition at line 182 of file FsFile.h.
                   {
     return m_fFile ? m_fFile->isHidden() :
            m_xFile ? m_xFile->isHidden() : false;
   }
References ExFatFile::isHidden(), and FatFile::isHidden().
isOpen()
bool FsBaseFile::isOpen () inline
Returns
True if this is an open file/directory else false.
Definition at line 187 of file FsFile.h.
 {return m_fFile || m_xFile;}
Referenced by operator bool().
isSubDir()
bool FsBaseFile::isSubDir () inline
Returns
True if this is a subdirectory file else false.
Definition at line 189 of file FsFile.h.
                   {
     return m_fFile ? m_fFile->isSubDir() :
            m_xFile ? m_xFile->isSubDir() : false;
   }
References ExFatFile::isSubDir(), and FatFile::isSubDir().
ls() [1/2]
bool FsBaseFile::ls (print_t * pr) inline
List directory contents.
Parameters
[in] pr Print object.
Returns
true for success or false for failure.
Definition at line 218 of file FsFile.h.
{
     return m_fFile ? m_fFile->ls(pr) :
            m_xFile ? m_xFile->ls(pr) : false;
   }
Referenced by FsVolume::ls().
ls() [2/2]
bool FsBaseFile::ls (print_t * pr, uint8_t flags) inline
List directory contents.
Parameters
[in] pr Print object.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 235 of file FsFile.h.
{
     return m_fFile ? m_fFile->ls(pr, flags) :
            m_xFile ? m_xFile->ls(pr, flags) : false;
   }
mkdir()
bool FsBaseFile::mkdir (FsBaseFile * dir, const char * path, bool pFlag = true)
Make a new directory.
Parameters
[in] dir An open FatFile instance for the directory that will contain the new directory.
[in] path A path with a valid 8.3 DOS name for the new directory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 64 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->mkdir(dir->m_fFile, path, pFlag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->mkdir(dir->m_xFile, path, pFlag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References close(), ExFatFile::mkdir(), and FatFile::mkdir().
name()
const char* FsBaseFile::name () const inline
No longer implemented due to Long File Names.
Use getName(char* name, size_t size).
Returns
a pointer to replacement suggestion.
Definition at line 256 of file FsFile.h.
{
     return "use getName()";
   }
Referenced by cpplint._ClassInfo::CheckEnd(), cpplint._NamespaceInfo::CheckEnd(), and getName().
open() [1/4]
bool FsBaseFile::open (const char * path, oflag_t oflag = O_RDONLY) inline
Open a file or directory by name.
Parameters
[in] path A path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of open flags.
Returns
true for success or false for failure.
Definition at line 336 of file FsFile.h.
{
     return FsVolume::m_cwv && open(FsVolume::m_cwv, path, oflag);
   }
open() [2/4]
bool FsBaseFile::open (FsBaseFile * dir, const char * path, oflag_t oflag = O_RDONLY)
Open a file or directory by name.
Parameters
[in] dir An open file instance for the directory containing the file to be opened.
[in] path A path with a valid 8.3 DOS name for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list
O_RDONLY - Open for reading only..
O_READ - Same as O_RDONLY.
O_WRONLY - Open for writing only.
O_WRITE - Same as O_WRONLY.
O_RDWR - Open for reading and writing.
O_APPEND - If set, the file offset shall be set to the end of the file prior to each write.
O_AT_END - Set the initial position at the end of the file.
O_CREAT - If the file exists, this flag has no effect except as noted under O_EXCL below. Otherwise, the file shall be created
O_EXCL - If O_CREAT and O_EXCL are set, open() shall fail if the file exists.
O_TRUNC - If the file exists and is a regular file, and the file is successfully opened and is not read only, its length shall be truncated to 0.
WARNING: A given file must not be opened by more than one file object or file corruption may occur.
Note
Directory files must be opened read only. Write and truncation is not allowed for directory files.
Returns
true for success or false for failure.
Definition at line 104 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->open(dir->m_fFile, path, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->open(dir->m_xFile, path, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References close(), ExFatFile::open(), and FatFile::open().
Referenced by ILI9341_t3_ERIS::begin(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), FsVolume::ls(), FsVolume::open(), and AppSerialCommandInterface::streamHandler().
open() [3/4]
bool FsBaseFile::open (FsBaseFile * dir, uint32_t index, oflag_t oflag)
Open a file by index.
Parameters
[in] dir An open FsFile instance for the directory.
[in] index The index of the directory entry for the file to be opened. The value for index is (directory file position)/32.
[in] oflag bitwise-inclusive OR of open flags. See see FsFile::open(FsFile*, const char*, uint8_t).
See open() by path for definition of flags.
Returns
true for success or false for failure.
Definition at line 122 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->open(dir->m_fFile, index, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->open(dir->m_xFile, index, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References close(), index, ExFatFile::open(), and FatFile::open().
open() [4/4]
bool FsBaseFile::open (FsVolume * vol, const char * path, oflag_t oflag)
Open a file or directory by name.
Parameters
[in] vol Volume where the file is located.
[in] path A path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of open flags.
Returns
true for success or false for failure.
Definition at line 82 of file FsFile.cpp.
{
   if (!vol) {
     return false;
   }
   close();
   if (vol->m_fVol) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile && m_fFile->open(vol->m_fVol, path, oflag)) {
       return true;
     }
     m_fFile = nullptr;
     return false;
   } else if (vol->m_xVol) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile && m_xFile->open(vol->m_xVol, path, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References close(), ExFatFile::open(), and FatFile::open().
openNext()
bool FsBaseFile::openNext (FsBaseFile * dir, oflag_t oflag = O_RDONLY)
Opens the next file or folder in a directory.
Parameters
[in] dir directory containing files.
[in] oflag open flags.
Returns
a file object.
Definition at line 140 of file FsFile.cpp.
{
   close();
   if (dir->m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     if (m_fFile->openNext(dir->m_fFile, oflag)) {
       return true;
     }
     m_fFile = nullptr;
   } else if (dir->m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     if (m_xFile->openNext(dir->m_xFile, oflag)) {
       return true;
     }
     m_xFile = nullptr;
   }
   return false;
 }
References close(), ExFatFile::openNext(), and FatFile::openNext().
Referenced by FsFile::openNextFile().
operator bool()
FsBaseFile::operator bool () inline
The parenthesis operator.
Returns
true if a file is open.
Definition at line 57 of file FsFile.h.
 {return isOpen();}
References isOpen().
operator=()
FsBaseFile & FsBaseFile::operator= (const FsBaseFile & from)
Copy assignment operator
Parameters
[in] from Object used to initialize this instance.
Returns
assigned object.
Definition at line 39 of file FsFile.cpp.
{
   if (this == &from) return *this;
   close();
   if (from.m_fFile) {
     m_fFile = new (m_fileMem) FatFile;
     *m_fFile = *from.m_fFile;
   } else if (from.m_xFile) {
     m_xFile = new (m_fileMem) ExFatFile;
     *m_xFile = *from.m_xFile;
   }
   return *this;
 }
References close().
peek()
int FsBaseFile::peek () inline
Return the next available byte without consuming it.
Returns
The byte if no error and not at eof else -1;
Definition at line 349 of file FsFile.h.
              {
     return m_fFile ? m_fFile->peek() :
            m_xFile ? m_xFile->peek() : -1;
   }
position()
uint64_t FsBaseFile::position () inline
Returns
the current file position.
Definition at line 420 of file FsFile.h.
 {return curPosition();}
preAllocate()
bool FsBaseFile::preAllocate (uint64_t length) inline
Allocate contiguous clusters to an empty file.
The file must be empty with no clusters allocated.
The file will contain uninitialized data for FAT16/FAT32 files. exFAT files will have zero validLength and dataLength will equal the requested length.
Parameters
[in] length size of the file in bytes.
Returns
true for success or false for failure.
Definition at line 415 of file FsFile.h.
{
     return m_fFile ? length < (1ULL << 32) && m_fFile->preAllocate(length) :
            m_xFile ? m_xFile->preAllocate(length) : false;
   }
printAccessDateTime()
size_t FsBaseFile::printAccessDateTime (print_t * pr) inline
Print a file's access date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 359 of file FsFile.h.
{
     return m_fFile ? m_fFile->printAccessDateTime(pr) :
            m_xFile ? m_xFile->printAccessDateTime(pr) : 0;
   }
printCreateDateTime()
size_t FsBaseFile::printCreateDateTime (print_t * pr) inline
Print a file's creation date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 369 of file FsFile.h.
{
     return m_fFile ? m_fFile->printCreateDateTime(pr) :
            m_xFile ? m_xFile->printCreateDateTime(pr) : 0;
   }
printField() [1/3]
size_t FsBaseFile::printField (double value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 427 of file FsFile.h.
{
     return m_fFile ? m_fFile->printField(value, term, prec) :
            m_xFile ? m_xFile->printField(value, term, prec) : 0;
   }
References value.
printField() [2/3]
size_t FsBaseFile::printField (float value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 437 of file FsFile.h.
{
      return printField(static_cast<double>(value), term, prec);
   }
References value.
printField() [3/3]
template<typename Type > size_t FsBaseFile::printField (Type value, char term) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 446 of file FsFile.h.
{
     return m_fFile ? m_fFile->printField(value, term) :
            m_xFile ? m_xFile->printField(value, term) : 0;
   }
References value.
printFileSize()
size_t FsBaseFile::printFileSize (print_t * pr) inline
Print a file's size.
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed is returned for success and zero is returned for failure.
Definition at line 400 of file FsFile.h.
{
     return m_fFile ? m_fFile->printFileSize(pr) :
            m_xFile ? m_xFile->printFileSize(pr) : 0;
   }
printModifyDateTime()
size_t FsBaseFile::printModifyDateTime (print_t * pr) inline
Print a file's modify date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 379 of file FsFile.h.
{
     return m_fFile ? m_fFile->printModifyDateTime(pr) :
            m_xFile ? m_xFile->printModifyDateTime(pr) : 0;
   }
printName()
size_t FsBaseFile::printName (print_t * pr) inline
Print a file's name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 389 of file FsFile.h.
{
     return m_fFile ? m_fFile->printName(pr) :
            m_xFile ? m_xFile->printName(pr) : 0;
   }
read() [1/2]
int FsBaseFile::read () inline
Read the next byte from a file.
Returns
For success return the next byte in the file as an int. If an error occurs or end of file is reached return -1.
Definition at line 455 of file FsFile.h.
              {
     uint8_t b;
     return read(&b, 1) == 1 ? b : -1;
   }
References read.
read() [2/2]
int FsBaseFile::read (void * buf, size_t count) inline
Read data from a file starting at the current position.
Parameters
[out] buf Pointer to the location that will receive the data.
[in] count Maximum number of bytes to read.
Returns
For success read() returns the number of bytes read. A value less than count, including zero, will be returned if end of file is reached. If an error occurs, read() returns -1. Possible errors include read() called before a file has been opened, corrupt file system or an I/O error occurred.
Definition at line 472 of file FsFile.h.
{
     return m_fFile ? m_fFile->read(buf, count) :
            m_xFile ? m_xFile->read(buf, count) : -1;
   }
References count.
remove() [1/2]
bool FsBaseFile::remove ()
Remove a file.
The directory entry and all data for the file are deleted.
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 158 of file FsFile.cpp.
{
   if (m_fFile) {
     if (m_fFile->remove()) {
       m_fFile = nullptr;
       return true;
     }
   } else if (m_xFile) {
     if (m_xFile->remove()) {
       m_xFile = nullptr;
       return true;
     }
   }
   return false;
 }
References ExFatFile::remove(), and FatFile::remove().
remove() [2/2]
bool FsBaseFile::remove (const char * path) inline
Remove a file.
The directory entry and all data for the file are deleted.
Parameters
[in] path Path for the file to be removed.
Example use: dirFile.remove(filenameToRemove);
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 501 of file FsFile.h.
{
     return m_fFile ? m_fFile->remove(path) :
            m_xFile ? m_xFile->remove(path) : false;
   }
rename() [1/2]
bool FsBaseFile::rename (const char * newPath) inline
Rename a file or subdirectory.
Parameters
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 511 of file FsFile.h.
{
     return m_fFile ? m_fFile->rename(newPath) :
            m_xFile ? m_xFile->rename(newPath) : false;
   }
rename() [2/2]
bool FsBaseFile::rename (FsBaseFile * dirFile, const char * newPath) inline
Rename a file or subdirectory.
Parameters
[in] dirFile Directory for the new path.
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 522 of file FsFile.h.
{
     return m_fFile ? m_fFile->rename(dirFile->m_fFile, newPath) :
            m_xFile ? m_xFile->rename(dirFile->m_xFile, newPath) : false;
   }
rewind()
void FsBaseFile::rewind () inline
Set the file's current position to zero.
Definition at line 527 of file FsFile.h.
                 {
     if (m_fFile) m_fFile->rewind();
     if (m_xFile) m_xFile->rewind();
   }
rewindDirectory()
void FsBaseFile::rewindDirectory () inline
Rewind a file if it is a directory
Definition at line 532 of file FsFile.h.
{
     if (isDir()) rewind();
   }
rmdir()
bool FsBaseFile::rmdir ()
Remove a directory file.
The directory file will be removed only if it is empty and is not the root directory. rmdir() follows DOS and Windows and ignores the read-only attribute for the directory.
Note
This function should not be used to delete the 8.3 version of a directory that has a long name. For example if a directory has the long name "New folder" you should not delete the 8.3 name "NEWFOL~1".
Returns
true for success or false for failure.
Definition at line 173 of file FsFile.cpp.
{
   if (m_fFile) {
     if (m_fFile->rmdir()) {
       m_fFile = nullptr;
       return true;
     }
   } else if (m_xFile) {
     if (m_xFile->rmdir()) {
       m_xFile = nullptr;
       return true;
     }
   }
   return false;
 }
References ExFatFile::rmdir(), and FatFile::rmdir().
seek()
bool FsBaseFile::seek (uint64_t pos) inline
Seek to a new position in the file, which must be between 0 and the size of the file (inclusive).
Parameters
[in] pos the new file position.
Returns
true for success or false for failure.
Definition at line 554 of file FsFile.h.
 {return seekSet(pos);}
seekCur()
bool FsBaseFile::seekCur (int64_t offset) inline
Set the files position to current position + pos. See seekSet().
Parameters
[in] offset The new position in bytes from the current position.
Returns
true for success or false for failure.
Definition at line 559 of file FsFile.h.
{
     return seekSet(curPosition() + offset);
   }
Referenced by ILI9341_t3_ERIS::bltSD().
seekEnd()
bool FsBaseFile::seekEnd (int64_t offset = 0) inline
Set the files position to end-of-file + offset. See seekSet(). Can't be used for directory files since file size is not defined.
Parameters
[in] offset The new position in bytes from end-of-file.
Returns
true for success or false for failure.
Definition at line 567 of file FsFile.h.
{
     return seekSet(fileSize() + offset);
   }
seekSet()
bool FsBaseFile::seekSet (uint64_t pos) inline
Sets a file's position.
Parameters
[in] pos The new position in bytes from the beginning of the file.
Returns
true for success or false for failure.
Definition at line 576 of file FsFile.h.
{
     return m_fFile ? pos < (1ULL << 32) && m_fFile->seekSet(pos) :
            m_xFile ? m_xFile->seekSet(pos) : false;
   }
Referenced by ILI9341_t3_ERIS::bltSDFullScreen().
size()
uint64_t FsBaseFile::size () inline
Returns
the file's size.
Definition at line 581 of file FsFile.h.
 {return fileSize();}
sync()
bool FsBaseFile::sync () inline
The sync() call causes all modified data and directory fields to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 587 of file FsFile.h.
               {
     return m_fFile ? m_fFile->sync() :
            m_xFile ? m_xFile->sync() : false;
   }
Referenced by flush().
timestamp()
bool FsBaseFile::timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second) inline
Set a file's timestamps in its directory entry.
Parameters
[in] flags Values for flags are constructed by a bitwise-inclusive OR of flags from the following list
T_ACCESS - Set the file's last access date.
T_CREATE - Set the file's creation date and time.
T_WRITE - Set the file's last write/modification date and time.
Parameters
[in] year Valid range 1980 - 2107 inclusive.
[in] month Valid range 1 - 12 inclusive.
[in] day Valid range 1 - 31 inclusive.
[in] hour Valid range 0 - 23 inclusive.
[in] minute Valid range 0 - 59 inclusive.
[in] second Valid range 0 - 59 inclusive
Note
It is possible to set an invalid date since there is no check for the number of days in a month.
Modify and access timestamps may be overwritten if a date time callback function has been set by dateTimeCallback().
Returns
true for success or false for failure.
Definition at line 623 of file FsFile.h.
{
     return m_fFile ?
            m_fFile->timestamp(flags, year, month, day, hour, minute, second) :
            m_xFile ?
            m_xFile->timestamp(flags, year, month, day, hour, minute, second) :
            false;
   }
truncate() [1/2]
bool FsBaseFile::truncate () inline
Truncate a file to the current position.
Returns
true for success or false for failure.
Definition at line 636 of file FsFile.h.
                   {
     return m_fFile ? m_fFile->truncate() :
            m_xFile ? m_xFile->truncate() : false;
   }
truncate() [2/2]
bool FsBaseFile::truncate (uint64_t length) inline
Truncate a file to a specified length. The current file position will be set to end of file.
Parameters
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 647 of file FsFile.h.
{
     return m_fFile ? length < (1ULL << 32) && m_fFile->truncate(length) :
            m_xFile ? m_xFile->truncate(length) : false;
   }
write() [1/2]
size_t FsBaseFile::write (const void * buf, size_t count) inline
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buf Pointer to the location of the data to be written.
[in] count Number of bytes to write.
Returns
For success write() returns the number of bytes written, always nbyte. If an error occurs, write() returns -1. Possible errors include write() is called before a file has been opened, write is called for a read-only file, device is full, a corrupt file system or an I/O error.
Definition at line 672 of file FsFile.h.
{
     return m_fFile ? m_fFile->write(buf, count) :
            m_xFile ? m_xFile->write(buf, count) : 0;
   }
References count.
write() [2/2]
size_t FsBaseFile::write (uint8_t b) inline
Write a byte to a file. Required by the Arduino Print class.
Parameters
[in] b the byte to be written. Use getWriteError to check for errors.
Returns
1 for success and 0 for failure.
Definition at line 656 of file FsFile.h.
 {return write(&b, 1);}
References write().
Referenced by write().
The documentation for this class was generated from the following files:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/FsLib/FsFile.h
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/FsLib/FsFile.cpp