ERIS CORE: BufferedPrint< WriteClass, BUF_DIM > Class Template Reference
BufferedPrint< WriteClass, BUF_DIM > Class Template Reference
Fast buffered print template.
#include <BufferedPrint.h>
Public Member Functions
BufferedPrint ()
BufferedPrint (WriteClass *wr)
void begin (WriteClass *wr)
void flush ()
size_t print (double d, uint8_t prec=2)
size_t print (float f, uint8_t prec=2)
template<typename Type >
size_t print (Type v)
size_t printField (char c, char term)
size_t printField (const __FlashStringHelper *fsh, char term)
size_t printField (const char *str, char term)
size_t printField (double d, char term, uint8_t prec=2)
size_t printField (float f, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type n, char term)
size_t println ()
size_t println (double d, uint8_t prec=2)
size_t println (float f, uint8_t prec)
template<typename Type >
size_t println (Type v)
bool sync ()
size_t write (const void *src, size_t n)
Private Attributes
uint8_t m_buf [BUF_DIM< 24 ? 24 :BUF_DIM]
uint8_t m_in
WriteClass * m_wr
Detailed Description
template<typename WriteClass, uint8_t BUF_DIM>
class BufferedPrint< WriteClass, BUF_DIM >
Fast buffered print template.
Definition at line 37 of file BufferedPrint.h.
Constructor & Destructor Documentation
BufferedPrint() [1/2]
template<typename WriteClass , uint8_t BUF_DIM> BufferedPrint< WriteClass, BUF_DIM >::BufferedPrint () inline
Definition at line 39 of file BufferedPrint.h.
 : m_wr(nullptr), m_in(0) {}
BufferedPrint() [2/2]
template<typename WriteClass , uint8_t BUF_DIM> BufferedPrint< WriteClass, BUF_DIM >::BufferedPrint (WriteClass * wr) inline explicit
BufferedPrint constructor.
Parameters
[in] wr Print destination.
Definition at line 43 of file BufferedPrint.h.
 : m_wr(wr), m_in(0) {}
Member Function Documentation
begin()
template<typename WriteClass , uint8_t BUF_DIM> void BufferedPrint< WriteClass, BUF_DIM >::begin (WriteClass * wr) inline
Initialize the BuffedPrint class.
Parameters
[in] wr Print destination.
Definition at line 47 of file BufferedPrint.h.
{
     m_wr = wr;
     m_in = 0;
   }
References BufferedPrint< WriteClass, BUF_DIM >::m_in, and BufferedPrint< WriteClass, BUF_DIM >::m_wr.
flush()
template<typename WriteClass , uint8_t BUF_DIM> void BufferedPrint< WriteClass, BUF_DIM >::flush () inline
Flush the buffer - same as sync() with no status return.
Definition at line 52 of file BufferedPrint.h.
 {sync();}
References BufferedPrint< WriteClass, BUF_DIM >::sync().
print() [1/3]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::print (double d, uint8_t prec = 2) inline
Print a double.
Parameters
[in] d The number to be printed.
[in] prec Number of digits after decimal point.
Returns
true for success or false if an error occurs.
Definition at line 187 of file BufferedPrint.h.
{
     return printField(d, 0, prec);
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
print() [2/3]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::print (float f, uint8_t prec = 2) inline
Print a float.
Parameters
[in] f The number to be printed.
[in] prec Number of digits after decimal point.
Returns
true for success or false if an error occurs.
Definition at line 203 of file BufferedPrint.h.
{
     return printField(static_cast<double>(f), 0, prec);
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
print() [3/3]
template<typename WriteClass , uint8_t BUF_DIM> template<typename Type > size_t BufferedPrint< WriteClass, BUF_DIM >::print (Type v) inline
Print character, string, or number.
Parameters
[in] v item to print.
Returns
true for success or false if an error occurs.
Definition at line 219 of file BufferedPrint.h.
{
     return printField(v, 0);
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
printField() [1/6]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::printField (char c, char term) inline
Print a character followed by a field terminator.
Parameters
[in] c character to print.
[in] term The field terminator. Use '\n' for CR LF.
Returns
true for success or false if an error occurs.
Definition at line 58 of file BufferedPrint.h.
{
     char buf[3];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     *--str = c;
     return write(str, buf + sizeof(buf) - str);
   }
References buf, and BufferedPrint< WriteClass, BUF_DIM >::write().
Referenced by BufferedPrint< WriteClass, BUF_DIM >::print(), BufferedPrint< WriteClass, BUF_DIM >::printField(), and BufferedPrint< WriteClass, BUF_DIM >::println().
printField() [2/6]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::printField (const __FlashStringHelper * fsh, char term) inline
Print a string stored in AVR flash followed by a field terminator.
Parameters
[in] fsh string to print.
[in] term The field terminator. Use '\n' for CR LF.
Returns
true for success or false if an error occurs.
Definition at line 75 of file BufferedPrint.h.
{
 #ifdef __AVR__
     size_t rtn = 0;
     PGM_P p = reinterpret_cast<PGM_P>(fsh);
     char c;
     while ((c = pgm_read_byte(p++))) {
       if (!write(&c, 1)) {
         return 0;
       }
       rtn++;
     }
     if (term) {
       char buf[2];
       char* str = buf + sizeof(buf);
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
       rtn += write(str, buf + sizeof(buf) - str);
     }
     return rtn;
 #else  // __AVR__
     return printField(reinterpret_cast<const char *>(fsh), term);
 #endif  // __AVR__
   }
References buf, p, pgm_read_byte, BufferedPrint< WriteClass, BUF_DIM >::printField(), and BufferedPrint< WriteClass, BUF_DIM >::write().
printField() [3/6]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::printField (const char * str, char term) inline
Print a string followed by a field terminator.
Parameters
[in] str string to print.
[in] term The field terminator. Use '\n' for CR LF.
Returns
true for success or false if an error occurs.
Definition at line 105 of file BufferedPrint.h.
{
     size_t rtn = write(str, strlen(str));
     if (term) {
       char buf[2];
       char* ptr = buf + sizeof(buf);
       *--ptr = term;
       if (term == '\n') {
         *--ptr = '\r';
       }
       rtn += write(ptr, buf + sizeof(buf) - ptr);
     }
     return rtn;
   }
References buf, and BufferedPrint< WriteClass, BUF_DIM >::write().
printField() [4/6]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::printField (double d, char term, uint8_t prec = 2) inline
Print a double followed by a field terminator.
Parameters
[in] d The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
true for success or false if an error occurs.
Definition at line 124 of file BufferedPrint.h.
{
     char buf[24];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     str = fmtDouble(str, d, prec, false);
     return write(str, buf + sizeof(buf) - str);
   }
References buf, fmtDouble(), and BufferedPrint< WriteClass, BUF_DIM >::write().
printField() [5/6]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::printField (float f, char term, uint8_t prec = 2) inline
Print a float followed by a field terminator.
Parameters
[in] f The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
true for success or false if an error occurs.
Definition at line 142 of file BufferedPrint.h.
{
     return printField(static_cast<double>(f), term, prec);
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
printField() [6/6]
template<typename WriteClass , uint8_t BUF_DIM> template<typename Type > size_t BufferedPrint< WriteClass, BUF_DIM >::printField (Type n, char term) inline
Print an integer value for 8, 16, and 32 bit signed and unsigned types.
Parameters
[in] n The value to print.
[in] term The field terminator. Use '\n' for CR LF.
Returns
true for success or false if an error occurs.
Definition at line 151 of file BufferedPrint.h.
{
     const uint8_t DIM = sizeof(Type) <= 2 ? 8 : 13;
     char buf[DIM];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     Type p = n < 0 ? -n : n;
     if (sizeof(Type) <= 2) {
       str = fmtBase10(str, (uint16_t)p);
     } else {
       str = fmtBase10(str, (uint32_t)p);
     }
     if (n < 0) {
       *--str = '-';
     }
     return write(str, buf + sizeof(buf) - str);
   }
References buf, fmtBase10(), p, and BufferedPrint< WriteClass, BUF_DIM >::write().
println() [1/4]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::println () inline
Print CR LF.
Returns
true for success or false if an error occurs.
Definition at line 176 of file BufferedPrint.h.
                    {
     char buf[2];
     buf[0] = '\r';
     buf[1] = '\n';
     return write(buf, 2);
   }
References buf, and BufferedPrint< WriteClass, BUF_DIM >::write().
println() [2/4]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::println (double d, uint8_t prec = 2) inline
Print a double followed by CR LF.
Parameters
[in] d The number to be printed.
[in] prec Number of digits after decimal point.
Returns
true for success or false if an error occurs.
Definition at line 195 of file BufferedPrint.h.
{
     return printField(d, '\n', prec);
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
println() [3/4]
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::println (float f, uint8_t prec) inline
Print a float followed by CR LF.
Parameters
[in] f The number to be printed.
[in] prec Number of digits after decimal point.
Returns
true for success or false if an error occurs.
Definition at line 211 of file BufferedPrint.h.
{
     return printField(static_cast<double>(f), '\n', prec);
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
println() [4/4]
template<typename WriteClass , uint8_t BUF_DIM> template<typename Type > size_t BufferedPrint< WriteClass, BUF_DIM >::println (Type v) inline
Print character, string, or number followed by CR LF.
Parameters
[in] v item to print.
Returns
true for success or false if an error occurs.
Definition at line 227 of file BufferedPrint.h.
{
     return printField(v, '\n');
   }
References BufferedPrint< WriteClass, BUF_DIM >::printField().
sync()
template<typename WriteClass , uint8_t BUF_DIM> bool BufferedPrint< WriteClass, BUF_DIM >::sync () inline
Flush the buffer.
Returns
true for success or false if an error occurs.
Definition at line 234 of file BufferedPrint.h.
               {
     if (!m_wr || m_wr->write(m_buf, m_in) != m_in) {
       return false;
     }
     m_in = 0;
     return true;
   }
References BufferedPrint< WriteClass, BUF_DIM >::m_buf, BufferedPrint< WriteClass, BUF_DIM >::m_in, and BufferedPrint< WriteClass, BUF_DIM >::m_wr.
Referenced by BufferedPrint< WriteClass, BUF_DIM >::flush(), and BufferedPrint< WriteClass, BUF_DIM >::write().
write()
template<typename WriteClass , uint8_t BUF_DIM> size_t BufferedPrint< WriteClass, BUF_DIM >::write (const void * src, size_t n) inline
Write data to an open file.
Parameters
[in] src Pointer to the location of the data to be written.
[in] n Number of bytes to write.
Returns
For success write() returns the number of bytes written, always n.
Definition at line 249 of file BufferedPrint.h.
{
     if ((m_in + n) > sizeof(m_buf)) {
       if (!sync()) {
         return 0;
       }
       if (n >= sizeof(m_buf)) {
         return n == m_wr->write((const uint8_t*)src, n) ? n : 0;
       }
     }
     memcpy(m_buf + m_in, src, n);
     m_in += n;
     return n;
   }
References BufferedPrint< WriteClass, BUF_DIM >::m_buf, BufferedPrint< WriteClass, BUF_DIM >::m_in, BufferedPrint< WriteClass, BUF_DIM >::m_wr, and BufferedPrint< WriteClass, BUF_DIM >::sync().
Referenced by BufferedPrint< WriteClass, BUF_DIM >::printField(), and BufferedPrint< WriteClass, BUF_DIM >::println().
Member Data Documentation
m_buf
template<typename WriteClass , uint8_t BUF_DIM> uint8_t BufferedPrint< WriteClass, BUF_DIM >::m_buf[BUF_DIM< 24 ? 24 :BUF_DIM] private
Definition at line 267 of file BufferedPrint.h.
Referenced by BufferedPrint< WriteClass, BUF_DIM >::sync(), and BufferedPrint< WriteClass, BUF_DIM >::write().
m_in
template<typename WriteClass , uint8_t BUF_DIM> uint8_t BufferedPrint< WriteClass, BUF_DIM >::m_in private
Definition at line 265 of file BufferedPrint.h.
Referenced by BufferedPrint< WriteClass, BUF_DIM >::begin(), BufferedPrint< WriteClass, BUF_DIM >::sync(), and BufferedPrint< WriteClass, BUF_DIM >::write().
m_wr
template<typename WriteClass , uint8_t BUF_DIM> WriteClass* BufferedPrint< WriteClass, BUF_DIM >::m_wr private
Definition at line 264 of file BufferedPrint.h.
Referenced by BufferedPrint< WriteClass, BUF_DIM >::begin(), BufferedPrint< WriteClass, BUF_DIM >::sync(), and BufferedPrint< WriteClass, BUF_DIM >::write().
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/src/BufferedPrint.h