ERIS CORE: ExFatPartition Class Reference
ExFatPartition Class Reference
Access exFat partitions on raw file devices.
#include <ExFatPartition.h>
Public Member Functions
ExFatPartition ()
uint32_t blocksPerCluster () __attribute__((deprecated))
uint32_t bytesPerCluster ()
uint8_t bytesPerClusterShift ()
uint16_t bytesPerSector ()
uint8_t bytesPerSectorShift ()
uint8_t * cacheClear ()
void checkUpcase (print_t *pr)
uint32_t clusterCount ()
uint32_t clusterHeapStartSector ()
void dmpBitmap (print_t *pr)
void dmpCluster (print_t *pr, uint32_t cluster, uint32_t offset, uint32_t count)
void dmpFat (print_t *pr, uint32_t start, uint32_t count)
void dmpSector (print_t *pr, uint32_t sector)
uint32_t fatLength ()
uint32_t fatStartSector ()
uint8_t fatType () const
uint32_t freeClusterCount ()
bool init (BlockDevice *dev, uint8_t part)
bool printDir (print_t *pr, ExFatFile *file)
void printFat (print_t *pr)
void printUpcase (print_t *pr)
bool printVolInfo (print_t *pr)
uint32_t rootDirectoryCluster ()
uint32_t rootLength ()
uint32_t sectorsPerCluster ()
uint8_t sectorsPerClusterShift ()
Friends
class ExFatFile
Detailed Description
Access exFat partitions on raw file devices.
Definition at line 118 of file ExFatPartition.h.
Constructor & Destructor Documentation
ExFatPartition()
ExFatPartition::ExFatPartition () inline
Definition at line 120 of file ExFatPartition.h.
 : m_fatType(0) {}
Member Function Documentation
blocksPerCluster()
uint32_t ExFatPartition::blocksPerCluster () inline
Definition at line 168 of file ExFatPartition.h.
 {return sectorsPerCluster();} //NOLINT
References sectorsPerCluster().
bytesPerCluster()
uint32_t ExFatPartition::bytesPerCluster () inline
Returns
the number of bytes in a cluster.
Definition at line 122 of file ExFatPartition.h.
 {return m_bytesPerCluster;}
Referenced by FsVolume::bytesPerCluster().
bytesPerClusterShift()
uint8_t ExFatPartition::bytesPerClusterShift () inline
Returns
the power of two for bytesPerCluster.
Definition at line 124 of file ExFatPartition.h.
{
     return m_bytesPerSectorShift + m_sectorsPerClusterShift;
   }
Referenced by ExFatFile::preAllocate(), ExFatFile::remove(), rootLength(), ExFatFile::seekSet(), ExFatFile::truncate(), and ExFatFile::write().
bytesPerSector()
uint16_t ExFatPartition::bytesPerSector () inline
Returns
the number of bytes in a sector.
Definition at line 128 of file ExFatPartition.h.
 {return m_bytesPerSector;}
Referenced by ExFatFile::read(), and ExFatFile::write().
bytesPerSectorShift()
uint8_t ExFatPartition::bytesPerSectorShift () inline
Returns
the power of two for bytesPerSector.
Definition at line 130 of file ExFatPartition.h.
 {return m_bytesPerSectorShift;}
Referenced by ExFatFile::read(), and ExFatFile::write().
cacheClear()
uint8_t* ExFatPartition::cacheClear () inline
Clear the cache and returns a pointer to the cache. Not for normal apps.
Returns
A pointer to the cache buffer or zero if an error occurs.
Definition at line 135 of file ExFatPartition.h.
{
     return m_dataCache.clear();
   }
References FsCache::clear().
Referenced by SdExFat::format().
checkUpcase()
void ExFatPartition::checkUpcase (print_t * pr)
Definition at line 363 of file ExFatDbg.cpp.
{
   bool skip = false;
   uint16_t u = 0;
   uint8_t* upcase = nullptr;
   uint32_t size = 0;
   uint32_t sector = clusterStartSector(m_rootDirectoryCluster);
   uint8_t* cache = dataCacheGet(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read root failed"));
     return;
   }
   DirUpcase_t* dir = reinterpret_cast<DirUpcase_t*>(cache);
   pr->println(F("\nChecking upcase table"));
   for (size_t i = 0; i < 16; i++) {
     if (dir[i].type == EXFAT_TYPE_UPCASE) {
       sector = clusterStartSector(getLe32(dir[i].firstCluster));
       size = getLe64(dir[i].size);
       break;
     }
   }
   if (!size) {
     pr->println(F("upcase not found"));
     return;
   }
   for (size_t i = 0; i < size/2; i++) {
     if ((i%256) == 0) {
       upcase = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
       if (!upcase) {
         pr->println(F("read upcase failed"));
         return;
       }
     }
     uint16_t v = getLe16(&upcase[2*(i & 0XFF)]);
     if (skip) {
       pr->print("skip ");
       pr->print(u);
       pr->write(' ');
       pr->println(v);
     }
     if (v == 0XFFFF) {
       skip = true;
     } else if (skip) {
       for (uint16_t k = 0; k < v; k++) {
         uint16_t x = toUpcase(u + k);
         if (x != (u + k)) {
           printHex(pr, (uint16_t)(u+k));
           pr->write(',');
           printHex(pr, x);
           pr->println("<<<<<<<<<<<<<<<<<<<<");
         }
       }
       u += v;
       skip = false;
     } else {
       uint16_t x = toUpcase(u);
       if (v != x) {
         printHex(pr, u);
         pr->write(',');
         printHex(pr, x);
         pr->write(',');
         printHex(pr, v);
         pr->println();
       }
       u++;
     }
   }
   pr->println(F("Done checkUpcase"));
 }
References FsCache::CACHE_FOR_READ, EXFAT_TYPE_UPCASE, F, getLe16(), getLe32(), getLe64(), toUpcase(), and x.
clusterCount()
uint32_t ExFatPartition::clusterCount () inline
Returns
the cluster count for the partition.
Definition at line 139 of file ExFatPartition.h.
 {return m_clusterCount;}
Referenced by FsVolume::clusterCount().
clusterHeapStartSector()
uint32_t ExFatPartition::clusterHeapStartSector () inline
Returns
the cluster heap start sector.
Definition at line 141 of file ExFatPartition.h.
 {return m_clusterHeapStartSector;}
Referenced by FsVolume::dataStartSector().
dmpBitmap()
void ExFatPartition::dmpBitmap (print_t * pr)
Definition at line 188 of file ExFatDbg.cpp.
{
   pr->println(F("bitmap:"));
   dmpSector(pr, m_clusterHeapStartSector);
 }
References dmpSector(), and F.
dmpCluster()
void ExFatPartition::dmpCluster (print_t * pr, uint32_t cluster, uint32_t offset, uint32_t count)
Definition at line 159 of file ExFatDbg.cpp.
{
   uint32_t sector = clusterStartSector(cluster) + offset;
   for (uint32_t i = 0; i < count; i++) {
     pr->print(F("\nSector: "));
     pr->println(sector + i, HEX);
     dmpSector(pr, sector + i);
   }
 }
References count, dmpSector(), F, and HEX.
dmpFat()
void ExFatPartition::dmpFat (print_t * pr, uint32_t start, uint32_t count)
Definition at line 203 of file ExFatDbg.cpp.
{
   uint32_t sector = m_fatStartSector + start;
   uint32_t cluster = 128*start;
   pr->println(F("FAT:"));
   for (uint32_t i = 0; i < count; i++) {
     uint8_t* cache = dataCacheGet(sector + i, FsCache::CACHE_FOR_READ);
     if (!cache) {
       pr->println(F("cache read failed"));
       return;
     }
     uint32_t* fat = reinterpret_cast<uint32_t*>(cache);
     for (size_t k = 0; k < 128; k++) {
       if (0 == cluster%8) {
         if (k) {
           pr->println();
         }
         printHex(pr, cluster);
       }
       cluster++;
       pr->write(' ');
       printHex(pr, fat[k]);
     }
     pr->println();
   }
 }
References FsCache::CACHE_FOR_READ, count, and F.
dmpSector()
void ExFatPartition::dmpSector (print_t * pr, uint32_t sector)
Definition at line 169 of file ExFatDbg.cpp.
{
   uint8_t* cache = dataCacheGet(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("dmpSector failed"));
     return;
   }
   for (uint16_t i = 0; i < 512; i++) {
     if (i%32 == 0) {
       if (i) {
         pr->println();
       }
       printHex(pr, i);
     }
     pr->write(' ');
     printHex(pr, cache[i]);
   }
   pr->println();
 }
References FsCache::CACHE_FOR_READ, and F.
Referenced by dmpBitmap(), and dmpCluster().
fatLength()
uint32_t ExFatPartition::fatLength () inline
Returns
the FAT length in sectors
Definition at line 143 of file ExFatPartition.h.
 {return m_fatLength;}
fatStartSector()
uint32_t ExFatPartition::fatStartSector () inline
Returns
the FAT start sector number.
Definition at line 145 of file ExFatPartition.h.
 {return m_fatStartSector;}
Referenced by FsVolume::fatStartSector().
fatType()
uint8_t ExFatPartition::fatType () const inline
Returns
Type FAT_TYPE_EXFAT for exFAT partition or zero for error.
Definition at line 147 of file ExFatPartition.h.
 {return m_fatType;}
freeClusterCount()
uint32_t ExFatPartition::freeClusterCount ()
Returns
the free cluster count.
Definition at line 344 of file ExFatPartition.cpp.
{
   uint32_t nc = 0;
   uint32_t sector = m_clusterHeapStartSector;
   uint32_t usedCount = 0;
   uint8_t* cache;
   while (true) {
     cache = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
     if (!cache) {
       return 0;
     }
     for (size_t i = 0; i < m_bytesPerSector; i++) {
       if (cache[i] == 0XFF) {
         usedCount+= 8;
       } else if (cache[i]) {
         for (uint8_t mask = 1; mask ; mask <<=1) {
           if ((mask & cache[i])) {
             usedCount++;
           }
         }
       }
       nc += 8;
       if (nc >= m_clusterCount) {
         return m_clusterCount - usedCount;
       }
     }
   }
 }
References FsCache::CACHE_FOR_READ.
Referenced by FsVolume::freeClusterCount().
init()
bool ExFatPartition::init (BlockDevice * dev, uint8_t part)
Initialize a exFAT partition.
Parameters
[in] dev The blockDevice for the partition.
[in] part The partition to be used. Legal values for part are 1-4 to use the corresponding partition on a device formatted with a MBR, Master Boot Record, or zero if the device is formatted as a super floppy with the FAT boot sector in sector zero.
Returns
true for success or false for failure.
Definition at line 75 of file ExFatPartition.cpp.
{
   uint32_t volStart = 0;
   uint8_t *cache;
   pbs_t* pbs;
   BpbExFat_t* bpb;
   MbrSector_t* mbr;
   MbrPart_t* mp;
   m_fatType = 0;
   m_blockDev = dev;
   cacheInit(m_blockDev);
   cache = dataCacheGet(0, FsCache::CACHE_FOR_READ);
   if (part > 4 || !cache) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (part >= 1) {
     mbr = reinterpret_cast<MbrSector_t*>(cache);
     mp = &mbr->part[part - 1];
     if ((mp->boot != 0 && mp->boot != 0X80) || mp->type == 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     volStart = getLe32(mp->relativeSectors);
     cache = dataCacheGet(volStart, FsCache::CACHE_FOR_READ);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   pbs = reinterpret_cast<pbs_t*>(cache);
   if (strncmp(pbs->oemName, "EXFAT", 5)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   bpb = reinterpret_cast<BpbExFat_t*>(pbs->bpb);
   if (bpb->bytesPerSectorShift != m_bytesPerSectorShift) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_fatStartSector = volStart + getLe32(bpb->fatOffset);
   m_fatLength = getLe32(bpb->fatLength);
   m_clusterHeapStartSector = volStart + getLe32(bpb->clusterHeapOffset);
   m_clusterCount = getLe32(bpb->clusterCount);
   m_rootDirectoryCluster = getLe32(bpb->rootDirectoryCluster);
   m_sectorsPerClusterShift = bpb->sectorsPerClusterShift;
   m_bytesPerCluster = 1UL << (m_bytesPerSectorShift + m_sectorsPerClusterShift);
   m_clusterMask = m_bytesPerCluster - 1;
   // Set m_bitmapStart to first free cluster.
   m_bitmapStart = 0;
   bitmapFind(0, 1);
   m_fatType = FAT_TYPE_EXFAT;
   return true;
  fail:
   return false;
 }
References mbrPartition::boot, partitionBootSector::bpb, biosParameterBlockExFat::bytesPerSectorShift, FsCache::CACHE_FOR_READ, biosParameterBlockExFat::clusterCount, biosParameterBlockExFat::clusterHeapOffset, DBG_FAIL_MACRO, FAT_TYPE_EXFAT, biosParameterBlockExFat::fatLength, biosParameterBlockExFat::fatOffset, getLe32(), partitionBootSector::oemName, masterBootRecordSector::part, mbrPartition::relativeSectors, biosParameterBlockExFat::rootDirectoryCluster, biosParameterBlockExFat::sectorsPerClusterShift, and mbrPartition::type.
Referenced by ExFatVolume::begin().
printDir()
bool ExFatPartition::printDir (print_t * pr, ExFatFile * file)
Definition at line 433 of file ExFatDbg.cpp.
{
   DirGeneric_t* dir = nullptr;
   DirFile_t* dirFile;
   DirStream_t* dirStream;
   DirName_t* dirName;
   uint16_t calcHash = 0;
   uint16_t nameHash = 0;
   uint16_t setChecksum = 0;
   uint16_t calcChecksum = 0;;
   uint8_t  nameLength = 0;
   uint8_t  setCount = 0;
   uint8_t  nUnicode;
 #define RAW_ROOT
 #ifndef RAW_ROOT
   while (1) {
     uint8_t buf[32];
     if (file->read(buf, 32) != 32) {
       break;
     }
     dir = reinterpret_cast<DirGeneric_t*>(buf);
 #else  // RAW_ROOT
   (void)file;
   uint32_t nDir = 1UL << (m_sectorsPerClusterShift + 4);
   uint32_t sector = clusterStartSector(m_rootDirectoryCluster);
   for (uint32_t iDir = 0; iDir < nDir; iDir++) {
     size_t i = iDir%16;
     if (i == 0) {
       uint8_t* cache = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
       if (!cache) {
         return false;
       }
       dir = reinterpret_cast<DirGeneric_t*>(cache);
     } else {
       dir++;
     }
 #endif  // RAW_ROOT
     if (dir->type == 0) {
       break;
     }
     pr->println();
     switch (dir->type) {
       case EXFAT_TYPE_BITMAP:
         printDirBitmap(pr, reinterpret_cast<DirBitmap_t*>(dir));
         break;
       case EXFAT_TYPE_UPCASE:
         printDirUpcase(pr, reinterpret_cast<DirUpcase_t*>(dir));
         break;
       case EXFAT_TYPE_LABEL:
         printDirLabel(pr, reinterpret_cast<DirLabel_t*>(dir));
         break;
       case EXFAT_TYPE_FILE:
         dirFile = reinterpret_cast<DirFile_t*>(dir);
         printDirFile(pr, dirFile);
         setCount = dirFile->setCount;
         setChecksum = getLe16(dirFile->setChecksum);
         calcChecksum = exFatDirChecksum(dir, 0);
         break;
       case EXFAT_TYPE_STREAM:
         dirStream = reinterpret_cast<DirStream_t*>(dir);
         printDirStream(pr, dirStream);
         nameLength = dirStream->nameLength;
         nameHash = getLe16(dirStream->nameHash);
         calcChecksum = exFatDirChecksum(dir, calcChecksum);
         setCount--;
         calcHash = 0;
         break;
        case EXFAT_TYPE_NAME:
         dirName = reinterpret_cast<DirName_t*>(dir);
         printDirName(pr, dirName);
         calcChecksum = exFatDirChecksum(dir, calcChecksum);
         nUnicode = nameLength > 15 ? 15 : nameLength;
         calcHash = exFatHashName(reinterpret_cast<ExChar16_t*>
                                 (dirName->unicode), nUnicode, calcHash);
         nameLength -= nUnicode;
         setCount--;
         if (nameLength == 0  || setCount == 0) {
           pr->print(F("setChecksum: 0x"));
           pr->print(setChecksum, HEX);
           if (setChecksum != calcChecksum) {
             pr->print(F(" != calcChecksum: 0x"));
           } else {
             pr->print(F(" == calcChecksum: 0x"));
           }
           pr->println(calcChecksum, HEX);
           pr->print(F("nameHash: 0x"));
           pr->print(nameHash, HEX);
           if (nameHash != calcHash) {
             pr->print(F(" != calcHash: 0x"));
           } else {
             pr->print(F(" == calcHash: 0x"));
           }
           pr->println(calcHash, HEX);
         }
         break;
       default:
         if (dir->type & 0x80) {
           pr->print(F("Unknown dirType: 0x"));
         } else {
           pr->print(F("Unused dirType: 0x"));
         }
         pr->println(dir->type, HEX);
         dmpDirData(pr, dir);
         break;
     }
   }
   pr->println(F("Done"));
   return true;
 }
References FsCache::CACHE_FOR_READ, EXFAT_TYPE_BITMAP, ExFatFile::read(), and DirGeneric_t::type.
printFat()
void ExFatPartition::printFat (print_t * pr)
Definition at line 229 of file ExFatDbg.cpp.
{
   uint32_t next;
   int8_t status;
   pr->println(F("FAT:"));
   for (uint32_t cluster = 0; cluster < 16; cluster++) {
     status = fatGet(cluster, &next);
     pr->print(cluster, HEX);
     pr->write(' ');
     if (status == 0) {
       next = EXFAT_EOC;
     }
     pr->println(next, HEX);
   }
 }
References EXFAT_EOC, F, HEX, and status.
printUpcase()
void ExFatPartition::printUpcase (print_t * pr)
Definition at line 550 of file ExFatDbg.cpp.
{
   uint8_t* upcase = nullptr;
   uint32_t sector;
   uint32_t size = 0;
   uint32_t checksum = 0;
   DirUpcase_t* dir;
   sector = clusterStartSector(m_rootDirectoryCluster);
   upcase = dataCacheGet(sector, FsCache::CACHE_FOR_READ);
   dir = reinterpret_cast<DirUpcase_t*>(upcase);
   if (!dir) {
     pr->println(F("read root dir failed"));
     return;
   }
   for (size_t i = 0; i < 16; i++) {
     if (dir[i].type == EXFAT_TYPE_UPCASE) {
       sector = clusterStartSector(getLe32(dir[i].firstCluster));
       size = getLe64(dir[i].size);
       break;
     }
   }
   if (!size) {
     pr->println(F("upcase not found"));
     return;
   }
   for (uint16_t i = 0; i < size/2; i++) {
     if ((i%256) == 0) {
       upcase = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
       if (!upcase) {
         pr->println(F("read upcase failed"));
         return;
       }
     }
     if (i%16 == 0) {
       pr->println();
       printHex(pr, i);
     }
     pr->write(' ');
     uint16_t uc = getLe16(&upcase[2*(i & 0XFF)]);
     printHex(pr, uc);
     checksum = upcaseChecksum(uc, checksum);
   }
   pr->println();
   pr->print(F("checksum: "));
   printHex(pr, checksum);
   pr->println();
 }
References FsCache::CACHE_FOR_READ, EXFAT_TYPE_UPCASE, F, getLe32(), and getLe64().
printVolInfo()
bool ExFatPartition::printVolInfo (print_t * pr)
Definition at line 244 of file ExFatDbg.cpp.
{
   uint8_t* cache = dataCacheGet(0, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read mbr failed"));
     return false;
   }
   MbrSector_t* mbr = reinterpret_cast<MbrSector_t*>(cache);
   printMbr(pr, mbr);
   uint32_t volStart = getLe32(mbr->part->relativeSectors);
   uint32_t volSize = getLe32(mbr->part->totalSectors);
   if (volSize == 0) {
     pr->print(F("bad partition size"));
     return false;
   }
   cache = dataCacheGet(volStart, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read pbs failed"));
     return false;
   }
   printExFatBoot(pr, reinterpret_cast<pbs_t*>(cache));
   return true;
 }
References FsCache::CACHE_FOR_READ, and F.
rootDirectoryCluster()
uint32_t ExFatPartition::rootDirectoryCluster () inline
Returns
the root directory start cluster number.
Definition at line 161 of file ExFatPartition.h.
 {return m_rootDirectoryCluster;}
Referenced by ExFatFile::read(), and ExFatFile::seekSet().
rootLength()
uint32_t ExFatPartition::rootLength ()
Returns
the root directory length.
Definition at line 373 of file ExFatPartition.cpp.
{
   uint32_t nc = chainSize(m_rootDirectoryCluster);
   return nc << bytesPerClusterShift();
 }
References bytesPerClusterShift().
sectorsPerCluster()
uint32_t ExFatPartition::sectorsPerCluster () inline
Returns
the number of sectors in a cluster.
Definition at line 165 of file ExFatPartition.h.
 {return 1UL << m_sectorsPerClusterShift;}
Referenced by blocksPerCluster(), ExFatFile::read(), FsVolume::sectorsPerCluster(), and ExFatFile::write().
sectorsPerClusterShift()
uint8_t ExFatPartition::sectorsPerClusterShift () inline
Returns
the power of two for sectors per cluster.
Definition at line 171 of file ExFatPartition.h.
 {return m_sectorsPerClusterShift;}
Friends And Related Function Documentation
ExFatFile
friend class ExFatFile friend
ExFatFile allowed access to private members.
Definition at line 188 of file ExFatPartition.h.
The documentation for this class was generated from the following files:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/ExFatPartition.h
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/ExFatDbg.cpp
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/ExFatPartition.cpp