ERIS CORE: SvcSerialCommandInterface::messageHandler_LS
messageHandler_LS()
void FLASHMEM SvcSerialCommandInterface::messageHandler_LS () protected
Definition at line 570 of file SvcSerialCommandInterface.cpp.
{
     bool first;
     int total_read;
     char cmd[128], param[128],param2[128];
     total_read = sscanf(received_chars, "%127s %127s %127s" , cmd, param,param2);
     if (total_read < 2){
         //send the root directory
         //delay(100);
         empty();
         println(F("DIR"));
         print(F("LS . ["));
 #ifdef USE_EXTMEM
         //do nothing - one time malloc in the constructor
 #else
         workingBuffer = (char*)malloc(SERIAL_WORKING_BUFFER_SIZE);
 #endif
         strcpy(p_working_buffer,tx_Buffer);
         empty();
         Serial.print(p_working_buffer);
         sd->chdir();
         tx_buffer_overflow_flag = false;
         sd->ls(this);
         memset(p_working_buffer,0,SERIAL_WORKING_BUFFER_SIZE);
         strcpy(p_working_buffer,tx_Buffer);
         empty();
         first = true;
         token = strtok(p_working_buffer, &newline);
         while( token != NULL ) {
             if (first && !tx_buffer_overflow_flag) Serial.print(F("\""));
             else Serial.print(F(",\""));
             Serial.print(token);
             Serial.print(F("\""));
             token = strtok(NULL, &newline);
             first = false;
         }
         Serial.println(F("]"));
         Serial.println(F("DIR_EOF"));
 #ifdef USE_EXTMEM
         //do nothing - one time malloc in the constructor
 #else
         free(workingBuffer);
 #endif
         //delay(200);
     } else{
         //send the requested path
         replacechar(param,':',' '); //replace space token used to tx the path
         empty();
         print(F("M "));
         println(param);
         println(F("DIR"));
         send();
         sd->chdir();
         replacechar(param,' ',':'); //replace any spaces in the transmitted path to ':'
         sprintf(multipart_header, "LS %s [", param);
         Serial.print(multipart_header);
         replacechar(param,':',' '); // put the spaces back in time for the ls command
         sd->ls(this,param,false);
         first = true;
         token = strtok(tx_Buffer, &newline);
         while( token != NULL && index_tx_buffer > 1) {
             if (first && !tx_buffer_overflow_flag) Serial.print(F("\""));
             else Serial.print(F(",\""));
             replacechar(token,'\r',0);
             Serial.print(token);
             Serial.print(F("\""));
             token = strtok(NULL, &newline);
             first = false;
             while(throttle()){
                 delay(50);
             }
         }
         Serial.println(F("]"));
         Serial.println(F("DIR_EOF"));
     }
 }
References empty(), index_tx_buffer, multipart_header, newline, p_working_buffer, received_chars, replacechar(), AppBaseClass::sd, send(), throttle(), token, tx_Buffer, and tx_buffer_overflow_flag.
Referenced by update().