ERIS CORE: SvcSerialCommandInterface::empty
empty()
void SvcSerialCommandInterface::empty () inline
zero out the transmit buffer and reset the write index
Definition at line 89 of file SvcSerialCommandInterface.h.
                 {
       memset(tx_Buffer,0,SERIAL_OUTPUT_BUFFER_SIZE);
       index_tx_buffer = 0;
     }
References index_tx_buffer, and tx_Buffer.
Referenced by messageHandler_LS(), sendLZ4Message(), startLZ4Message(), and streamTransmitHandler().