ERIS CORE: SvcSerialCommandInterface::throttle
throttle()
bool SvcSerialCommandInterface::throttle ()
returns true if the available serial buffer falls below SERIAL_THROTTLE_BUFFER_REMAINING_THRESHOLD if the buffer falls below SERIAL_THROTTLE_CHECK_CONNECTION_BUFFER_THRESHOLD delay for a small period of time if another check finds the buffer isn't moving then flush the buffer. returns false otherwise
Returns
true
false
Definition at line 170 of file SvcSerialCommandInterface.cpp.
{
     uint16_t avail;
     avail = Serial.availableForWrite();
     if(avail < SERIAL_THROTTLE_CHECK_CONNECTION_BUFFER_THRESHOLD){
         uint16_t delta_avail;
         uint16_t msec_delay_counter = 0;
         //serial tx buffer not available
         do{
             delay(2);
             msec_delay_counter += 2;
             delta_avail = Serial.availableForWrite();
             if (delta_avail > SERIAL_THROTTLE_CHECK_CONNECTION_BUFFER_THRESHOLD) break;
         } while (msec_delay_counter < SERIAL_THROTTLE_CHECK_CONNECTION_MAX_DELAY);
         if(avail == delta_avail){
             Serial.flush();
             Serial.println(F("M WRN flush"));
         } else{
             //Serial.println(F("M WRN throttling"));//use this for debug only!
             am->data->increment("SERIAL_THROTTLE_EVENTS");
         }
     }
     if(avail < SERIAL_THROTTLE_BUFFER_THRESHOLD) return true;
     return false;
 }
References AppBaseClass::am, AppManager::data, and SvcDataDictionary::increment().
Referenced by flush(), messageHandler_GET_RAM2(), messageHandler_LS(), send(), sendLZ4Message(), txOverflowHandler(), and update().