ERIS CORE: SvcSerialCommandInterface::update
update()
void FASTRUN SvcSerialCommandInterface::update (void) override protected virtual
update loop
Reimplemented from AppBaseClass.
Definition at line 311 of file SvcSerialCommandInterface.cpp.
{
     char endMarker = '\n';
     boolean newRxMsg = false;
     char bufferChr;
     if(is_capturing_bulk_data){
         Serial.println(F("M SvcSerialCommandInterface::updateRT isCapturingBulkData"));
         char* f;
         do{
             do{
                 p_capture_buffer[index_capture_buffer] = Serial.read();
                 if(p_capture_buffer[index_capture_buffer] != 0xFF) index_capture_buffer++;
             }while (Serial.available() && index_capture_buffer < SERIAL_RX_CAPTURE_BUFFER_SIZE-1);//in case were asking for the streaming data faster than it's being sent
             if(index_capture_buffer == SERIAL_RX_CAPTURE_BUFFER_SIZE-1){
                 Serial.println(F("M SvcSerialCommandInterface::updateRT Wren Script ERROR: Input buffer full"));
                 Serial.flush();
                 is_capturing_bulk_data = false;
                 index_capture_buffer = 0;
             }
             f = strstr(p_capture_buffer,"WREN_SCRIPT_END");
             if (f > 0){
                 Serial.println(F("M SvcSerialCommandInterface::updateRT Wren Script Received"));
                 memset(f,0,strlen("WREN_SCRIPT_END"));//remove the EOF marker
                 //stream complete
                 is_capturing_bulk_data = false;
             }
         }while(is_capturing_bulk_data);
     }else if (is_streaming_file){
         streamHandler();
     }else if (Serial.available() > 0 && false == newRxMsg ) {
         bufferChr = Serial.read();
         received_chars[index_rx_buffer++] = bufferChr;
         if(index_rx_buffer >= (SERIAL_RX_BUFFER_SIZE-16)){
             //input overflow - clear serial input and reset the index
             index_rx_buffer = 0;
             Serial.clear();
             Serial.clearReadError();
             return;
         }
         if (bufferChr == endMarker){
             received_chars[--index_rx_buffer] = '\0'; //remove the end marker and null terminate the string
             index_rx_buffer = 0; //reset the input write index
             newRxMsg = true;
         }
         if (newRxMsg){
             char cmd[128], param[128],param2[128];
             int total_read;
             total_read = sscanf(received_chars, "%127s %127s" , cmd, param);
             if (strncmp(cmd, "LS",sizeof(cmd)) == 0){
                 bool first;
                 if (total_read < 2){
                     //send the root directory
                     //delay(100);
                     empty();
                     println(F("DIR"));
                     print(F("LS . ["));
 #ifdef USE_EXTMEM
                     //do nothing - one time malloc in the constructor
 #else
                     workingBuffer = (char*)malloc(SERIAL_WORKING_BUFFER_SIZE);
 #endif
                     strcpy(p_working_buffer,tx_Buffer);
                     empty();
                     Serial.print(p_working_buffer);
                     sd->chdir();
                     tx_buffer_overflow_flag = false;
                     sd->ls(this);
                     memset(p_working_buffer,0,SERIAL_WORKING_BUFFER_SIZE);
                     strcpy(p_working_buffer,tx_Buffer);
                     empty();
                     first = true;
                     token = strtok(p_working_buffer, &newline);
                     while( token != NULL ) {
                         if (first && !tx_buffer_overflow_flag) Serial.print(F("\""));
                         else Serial.print(F(",\""));
                         Serial.print(token);
                         Serial.print(F("\""));
                         token = strtok(NULL, &newline);
                         first = false;
                     }
                     Serial.println(F("]"));
                     Serial.println(F("DIR_EOF"));
 #ifdef USE_EXTMEM
                     //do nothing - one time malloc in the constructor
 #else
                     free(workingBuffer);
 #endif
                     //delay(200);
                 } else{
                     //send the requested path
                     replacechar(param,':',' '); //replace space token used to tx the path
                     empty();
                     print(F("M "));
                     println(param);
                     println(F("DIR"));
                     send();
                     sd->chdir();
                     replacechar(param,' ',':'); //replace any spaces in the transmitted path to ':'
                     sprintf(multipart_header, "LS %s [", param);
                     Serial.print(multipart_header);
                     replacechar(param,':',' '); // put the spaces back in time for the ls command
                     sd->ls(this,param,false);
                     first = true;
                     token = strtok(tx_Buffer, &newline);
                     while( token != NULL && index_tx_buffer > 1) {
                         if (first && !tx_buffer_overflow_flag) Serial.print(F("\""));
                         else Serial.print(F(",\""));
                         replacechar(token,'\r',0);
                         Serial.print(token);
                         Serial.print(F("\""));
                         token = strtok(NULL, &newline);
                         first = false;
                         while(throttle()){
                             delay(50);
                         }
                     }
                     Serial.println(F("]"));
                     Serial.println(F("DIR_EOF"));
                 }
             }else if (strncmp(cmd, "GET",sizeof(cmd)) == 0){
                 total_read = sscanf(received_chars, "%127s %127s %127s" , cmd, param,param2);
                 if (total_read < 3){
                     Serial.print(F("M GET_ERR WRONG PARAM COUNT"));
                     Serial.println(param);
                 } else{
                     //file streaming request ok
                     //init the transfer
                     Serial.print(F("M GET_OK "));
                     Serial.print(param);
                     Serial.print(" ");
                     Serial.println(param2);
                     strcpy(stream_path,param);
                     strcpy(stream_file,param2);
                     Serial.println(F("FS_START"));
                     is_streaming_file = true;
                     is_periodic_messages_enabled = false;
                     stream_pos = 0;
                 }
             }else if (strncmp(cmd, "ACON",sizeof(cmd)) == 0){ //audio connections
                 uint16_t i;
                 char csBuffer[128];
                 i = 0;
                 Serial.println(F("M ACON START"));
                 while(ad->getConnectionString(i,csBuffer)){
                     i += 1;
                     Serial.print("M ");
                     Serial.println(csBuffer);
                 }
                 Serial.println(F("M ACON END"));
             }else if (strncmp(cmd, "CONNECT",sizeof(cmd)) == 0){
                 int source_port;
                 int dest_port;
                 total_read = sscanf(received_chars, "%127s %127s %d %127s %d" , cmd, param,&source_port,param2,&dest_port);
                 if (total_read < 3){
                     Serial.print(F("M CONNECT WRONG PARAM COUNT "));
                     Serial.println(received_chars);
                 } else{
                     ad->connect(param,source_port,param2,dest_port);
                 }
             }else if (strncmp(cmd, "DISCONNECT",sizeof(cmd)) == 0){
                 int dest_port;
                 total_read = sscanf(received_chars, "%127s %127s %d" , cmd, param,&dest_port);
                 if (total_read < 2){
                     Serial.print(F("M DISCONNECT WRONG PARAM COUNT "));
                     Serial.println(received_chars);
                 } else{
                     if (ad->disconnect(param,dest_port)){
                         Serial.printf(F("M DISCONNECTED %s %d\n"),param,dest_port);
                     }else{
                         Serial.printf(F("M FAILED DISCONNECT OF %s %d\n"),param,dest_port);
                     }
                 }
             }else if (strncmp(cmd, "AA",sizeof(cmd)) == 0){         //active app message
                 if (total_read > 1) am->getActiveApp()->messageHandler(this,param);
             }else if (strncmp(cmd, "APC",sizeof(cmd)) == 0){
                 //forward the message to the SvcErisAudioParameterController
                 am->getAppByName("APC")->messageHandler(this,received_chars + 4);
             }else if (strncmp(cmd, "STATS",sizeof(cmd)) == 0){
                 ad->printStats();
                 while(throttle()){delay(2);}
                 am->printStats();
             }else if (strncmp(cmd, "CQT_CFG",sizeof(cmd)) == 0){
                 am->sendMessage(this,"AppCQT","CQT_INFO");
             }else if (strncmp(cmd, "GET_DD",sizeof(cmd)) == 0){
                 am->data->printDictionary(this);
             }else if (strncmp(cmd, "GET_WREN_SCRIPT",sizeof(cmd)) == 0){
                 if(!requestStartLZ4Message()) return;
                 println("#WREN_START!");
                 println(g_wrenScript);
                 println("#WREN_EOF!");
                 sendLZ4Message();
             }else if (strncmp(cmd, "WREN_SCRIPT_START",sizeof(cmd)) == 0){
                 is_capturing_bulk_data = true;
 #ifndef USE_EXTMEM
                 char* tmp;
                 tmp = (char*)realloc(captureBuffer,SERIAL_RX_CAPTURE_BUFFER_SIZE);
                 if(tmp==NULL){
                     //realloc failed; release the pointer and try again
                     free(captureBuffer);
                     captureBuffer = (char*)malloc(SERIAL_RX_CAPTURE_BUFFER_SIZE);
                 } else captureBuffer = tmp;
 #endif
                 if(p_capture_buffer!=NULL){
                     memset(p_capture_buffer,0,SERIAL_RX_CAPTURE_BUFFER_SIZE);
                     index_capture_buffer = 0;
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer allocated and initalized"));
                 } else{
                     is_capturing_bulk_data = false;
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: ERROR: realloc(SERIAL_RX_CAPTURE_BUFFER_SIZE) failed"));
                     Serial.flush();
                 }
             }else if (strncmp(cmd, "WREN_SCRIPT_COMPILE",sizeof(cmd)) == 0){
                 if(p_capture_buffer != NULL){
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: script compile request"));
                     am->sendMessage(this,"AppWren","WREN_SCRIPT_COMPILE");
                     am->sendMessage(this,"AppWren",p_capture_buffer);
 #ifndef USE_EXTMEM
                     captureBuffer = (char*)realloc(captureBuffer,0);
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer released"));
 #endif
                 } else Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer is NULL"));
             }else if (strncmp(cmd, "WREN_SCRIPT_EXECUTE",sizeof(cmd)) == 0){
                 if(p_capture_buffer != NULL){
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: script execute request"));
                     am->sendMessage(this,"AppWren","WREN_SCRIPT_EXECUTE");
                     am->sendMessage(this,"AppWren",p_capture_buffer);
 #ifndef USE_EXTMEM
                     captureBuffer = (char*)realloc(captureBuffer,0);
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer released"));
 #endif
                 } else Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer is NULL"));
             }else if (strncmp(cmd, "WREN_SCRIPT_SAVE",sizeof(cmd)) == 0){
                 if(p_capture_buffer != NULL){
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: script save request"));
                     am->sendMessage(this,"AppWren",received_chars);//"WREN_SCRIPT_SAVE [modulename]");
                     am->sendMessage(this,"AppWren",p_capture_buffer);
 #ifndef USE_EXTMEM
                     captureBuffer = (char*)realloc(captureBuffer,0);
                     Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer released"));
 #endif
                 } else Serial.println(F("M SvcSerialCommandInterface::updateRT: captureBuffer is NULL"));
             }else if (strncmp(cmd, "UPDATE_DD",sizeof(cmd)) == 0){
                 int32_t val;
                 float32_t fval;
                 total_read = sscanf(received_chars, "%127s %127s %d" , cmd, param,(int*)&val);
                 if (total_read < 3){
                     total_read = sscanf(received_chars, "%127s %127s %f" , cmd, param,(float32_t*)&fval);
                     if (total_read < 3){
                         Serial.print(F("M WRONG PARAM COUNT"));
                         Serial.println(total_read);
                     } else am->data->update(param,fval);
                 }else if(!am->data->update(param,val)){
                     total_read = sscanf(received_chars, "%127s %127s %f" , cmd, param,(float32_t*)&fval);
                     am->data->update(param,fval);
                 }
             }else if (strncmp(cmd, "HELO",sizeof(cmd)) == 0){
                 if(requestStartLZ4Message()){
                     println(gWelcomeMessage);
                     sendLZ4Message();
                 }
             }else if (strncmp(cmd, "GET_RAM",sizeof(cmd)) == 0){
                 char* mp;
                 long num;
                 num = strtol(param,NULL,10);
                 mp = (char*)num;
                 Serial.printf("M GET_RAM {\"addr\":\"%08X\",\"data\":\"%02X\"}\n",num,(uint8_t)*mp);
             }else if (strncmp(cmd, "GET_RAM2",sizeof(cmd)) == 0){
                 char* mp = 0;
                 char c;
 #ifdef USE_EXTMEM
                 char tmp[1000];
                 //tmp = (char*)extmem_malloc(1000);
 #else
                 char* tmp;
                 tmp = (char*)malloc(1000);
 #endif
                 while(throttle()){delay(100);}
                 if(!requestStartLZ4Message()) return;
                 strcpy(tmp,"");
                 printf(F("RAM {\"RAM2\":{\"addr\":\"%08X\",\"chunk\":\""),0x20000000);
                 //RAM2 always ends at 0x20280000
                 for(uint32_t i = 0x20000000; i < 0x20280000; i+=1){
                     if (i == 0x20010000) i = 0x20200000;
                     mp = (char*)i;
                     c = *mp;
                     c = (c & 0xFF);
                     if(i%32==0 && i != 0x20000000){
                         print(F("\",\"decode\":\""));
                         print(tmp);
                         println(F("\"}}"));
                         sendLZ4Message();
                         strcpy(tmp,"");
                         while(throttle()){delay(50);}
                         if(i%1024==0){
                             float32_t pct;
                             pct = 100.0 * ((float)(i-0x20000000)/(float)(0x20280000-0x20000000));
                             Serial.printf(F("CLS\nM GET_RAM2 %08X %.0f pct "),i,pct);
                             for(uint16_t div = 0; div < (uint16_t)pct; div += 5){
                                 Serial.printf("*");
                             }
                             Serial.println("");
                         }
                         startLZ4Message();
                         printf(F("RAM {\"RAM2\":{\"addr\":\"%08X\",\"chunk\":\""),i);
                     }
                     printf("%02X ",(uint8_t)c);
                     const char* escape = "\\";
                     if (c=='"'){
                         strncat(tmp, escape, 1);
                         strncat(tmp, &c, 1);
                     }else if (c=='\''){
                         strncat(tmp, escape, 1);
                         strncat(tmp, &c, 1);
                     }else if (isprint((int)c)){
                         strncat(tmp, &c, 1);
                     }else if (iscntrl((int)c)){
                         c = '.';
                         strncat(tmp, &c, 1);
                     }else{
                         c = '?';
                         strncat(tmp, &c, 1);
                     }
                 }
                 println("\n");
                 println(F("RAM END"));
                 sendLZ4Message();
 #ifdef USE_EXTMEM
                 //do nothing - local var
 #else
                 free(tmp);
 #endif
             }else if (strncmp(cmd, "GET_RAM1",sizeof(cmd)) == 0){
                 char* mp = 0;
                 char c;
 #ifdef USE_EXTMEM
                 char tmp[1000];
                 //tmp = (char*)extmem_malloc(1000);
 #else
                 char* tmp;
                 tmp = (char*)malloc(1000);
 #endif
                 while(throttle()){delay(100);}
                 if(!requestStartLZ4Message()) return;
                 strcpy(tmp,"");
                 printf(F("RAM {\"RAM1\":{\"addr\":\"%08X\",\"chunk\":\""),0x000000);
                 for(uint32_t i = 0x00070000; i < 0x0007F000; i+=1){
                     //if (i == 0x20010000) i = 0x20200000;
                     mp = (char*)i;
                     c = *mp;
                     c = (c & 0xFF);
                     if(i%32==0 && i != 0x00070000){
                         print(F("\",\"decode\":\""));
                         print(tmp);
                         println(F("\"}}"));
                         sendLZ4Message();
                         strcpy(tmp,"");
                         while(throttle()){delay(150);}
                         if(i%1024==0){
                             float32_t pct;
                             pct = 100.0 * ((float)(i-0x00070000)/(float)(0x0007F000));
                             Serial.printf(F("CLS\nM GET_RAM1 %08X %.0f pct "),i,pct);
                             for(uint16_t div = 0; div < (uint16_t)pct; div += 5){
                                 Serial.printf("*");
                             }
                             Serial.println("");
                         }
                         startLZ4Message();
                         printf(F("RAM {\"RAM1\":{\"addr\":\"%08X\",\"chunk\":\""),i);
                     }
                     printf("%02X ",(uint8_t)c);
                     const char* escape = "\\";
                     if (c=='"'){
                         strncat(tmp, escape, 1);
                         strncat(tmp, &c, 1);
                     }else if (c=='\''){
                         strncat(tmp, escape, 1);
                         strncat(tmp, &c, 1);
                     }else if (isprint((int)c)){
                         strncat(tmp, &c, 1);
                     }else if (iscntrl((int)c)){
                         c = '.';
                         strncat(tmp, &c, 1);
                     }else{
                         c = '?';
                         strncat(tmp, &c, 1);
                     }
                 }
                 println("\n");
                 println(F("RAM END"));
                 sendLZ4Message();
 #ifdef USE_EXTMEM
                 //do nothing - local var
 #else
                 free(tmp);
 #endif
             }else if (strncmp(cmd, "AUDIO_NO_INTERRUPTS",sizeof(cmd)) == 0){
                 AudioNoInterrupts();
             }else if (strncmp(cmd, "AUDIO_INTERRUPTS",sizeof(cmd)) == 0){
                 AudioInterrupts();
             }
             //END
             newRxMsg = false;
         }
     }
     et_since_poll = 0;
     //tx periodic messages
     #ifdef SERIAL_AUTO_TRANSMIT_DATA_PERIODICALLY
     if(is_periodic_messages_enabled){
         if (et_since_periodic_stats_tx > SERIAL_AUTO_TRANSMIT_STATS_PERIOD && !throttle()){
             et_since_periodic_stats_tx = 0;
             AppManager::getInstance()->printStats();
             ad->printStats();
         }else if (et_since_periodic_data_dict_tx > SERIAL_AUTO_TRANSMIT_DATA_DICT_PERIOD && !throttle()){
             et_since_periodic_data_dict_tx = 0;
             et_since_periodic_stats_tx = 0;
             AppManager::getInstance()->data->printDictionary(this);
         }
     }
     #endif
 }
References AppBaseClass::ad, AppBaseClass::am, AudioDirector::connect(), AppManager::data, AudioDirector::disconnect(), empty(), et_since_periodic_data_dict_tx, et_since_periodic_stats_tx, et_since_poll, AppManager::getActiveApp(), AppManager::getAppByName(), AudioDirector::getConnectionString(), AppManager::getInstance(), gWelcomeMessage, index_capture_buffer, index_rx_buffer, index_tx_buffer, is_capturing_bulk_data, is_periodic_messages_enabled, is_streaming_file, AppBaseClass::messageHandler(), multipart_header, newline, p_capture_buffer, p_working_buffer, SvcDataDictionary::printDictionary(), AppManager::printStats(), AudioDirector::printStats(), received_chars, replacechar(), requestStartLZ4Message(), AppBaseClass::sd, send(), sendLZ4Message(), AppManager::sendMessage(), startLZ4Message(), stream_file, stream_path, stream_pos, streamHandler(), throttle(), token, tx_Buffer, tx_buffer_overflow_flag, SvcDataDictionary::update(), and val.