ERIS CORE: SvcSerialCommandInterface::sendLZ4Message
sendLZ4Message()
void FASTRUN SvcSerialCommandInterface::sendLZ4Message ()
Calling this function signals the end of a compressed message.
The txBuffer contents are lz4 compressed, base64 encoded and finally sent.
The serial message format is "LZ4 [UNCOMPRESSED_SIZE] [BASE64 encoded LZ4 compressed message]".
Definition at line 115 of file svcSerialCommandInterface.cpp.
{
     uint16_t compressed_len,uncompressed_len;
     while(throttle()){
         delay(5);
     };
 #ifdef USE_EXTMEM
     //do nothing - one time malloc in the constructor
 #else
     char workingBuffer[SERIAL_WORKING_BUFFER_SIZE];
 #endif
     am->requestArmSetClock(CPU_BOOST_MAX_FREQ);
     memset(p_working_buffer,0,SERIAL_WORKING_BUFFER_SIZE);
     uncompressed_len = index_tx_buffer;
     compressed_len = LZ4_compress_fast(p_tx_Buffer,p_working_buffer,index_tx_buffer,SERIAL_WORKING_BUFFER_SIZE,1);
     empty();
     encode_base64((unsigned char *)p_working_buffer, compressed_len, (unsigned char *)p_tx_Buffer);
     Serial.print("LZ4 ");
     Serial.print(uncompressed_len);
     Serial.print(" ");
     Serial.println(p_tx_Buffer);
     am->requestArmSetClock(CPU_BASE_FREQ);
 #ifdef USE_EXTMEM
     //do nothing - one time malloc in the constructor
 #else
     //do nothing - local var
 #endif
 }
References AppBaseClass::am, empty(), index_tx_buffer, p_tx_Buffer, p_working_buffer, AppManager::requestArmSetClock(), and throttle().
Referenced by AudioDirector::getAudioStreamObjByName(), AppWren::isWrenResultOK(), AppWren::loadScript(), AppCQT::messageHandler(), SvcErisAudioParameterController::messageHandler(), messageHandler_GET_RAM1(), messageHandler_GET_RAM2(), SvcDataDictionary::printDictionary(), AppManager::printStats(), AudioDirector::printStats(), AppWren::rebootRequest(), AppCQT::render(), streamTransmitHandler(), update(), and writeFn().