ERIS CORE: SvcSerialCommandInterface::sendLZ4Message
sendLZ4Message()
void SvcSerialCommandInterface::sendLZ4Message ()
Calling this function signals the end of a compressed message.
The txBuffer contents are lz4 compressed, base64 encoded and finaly sent.
The serial message format is "LZ4 [UNCOMPRESSED_SIZE] [BASE64 encoded LZ4 compressed message]".
Definition at line 115 of file SvcSerialCommandInterface.cpp.
{
     uint16_t compressed_len,uncompressed_len;
 #ifdef USE_EXTMEM
     //do nothing - one time malloc in the constructor
 #else
     char workingBuffer[SERIAL_WORKING_BUFFER_SIZE];
 #endif
     memset(p_working_buffer,0,SERIAL_WORKING_BUFFER_SIZE);
     uncompressed_len = index_tx_buffer;
     compressed_len = LZ4_compress_fast(tx_Buffer,p_working_buffer,index_tx_buffer,SERIAL_WORKING_BUFFER_SIZE,1);
     empty();
     encode_base64((unsigned char *)p_working_buffer, compressed_len, (unsigned char *)tx_Buffer);
     while(throttle()){
         delay(5);
     };
     Serial.print(" ");
     Serial.print(uncompressed_len);
     Serial.print(" ");
     Serial.println(tx_Buffer);
     //empty();
     //while(throttle()){
     //    delay(50);
     //};
 #ifdef USE_EXTMEM
     //do nothing - one time malloc in the constructor
 #else
     //do nothing - local var
 #endif
 }
References empty(), index_tx_buffer, p_working_buffer, throttle(), and tx_Buffer.
Referenced by AppCQT::messageHandler(), SvcDataDictionary::printDictionary(), AppManager::printStats(), AudioDirector::printStats(), AppCQT::render(), streamHandler(), update(), and writeFn().