ERIS CORE: SvcSerialCommandInterface::send
send()
void SvcSerialCommandInterface::send ()
immediately transmit then clear the txBuffer
Definition at line 150 of file SvcSerialCommandInterface.cpp.
{
     while(throttle()){
         delay(50);
     }
     if (strlen(tx_Buffer) > 0 ) Serial.print(tx_Buffer);
     memset(tx_Buffer,0,SERIAL_OUTPUT_BUFFER_SIZE);
     index_tx_buffer = 0;
     tx_buffer_overflow_flag = false;
 }
References index_tx_buffer, throttle(), tx_Buffer, and tx_buffer_overflow_flag.
Referenced by SvcErisAudioParameterController::messageHandler(), and messageHandler_LS().