ERIS CORE: SvcSerialCommandInterface::txOverflowHandler
txOverflowHandler()
void FASTRUN SvcSerialCommandInterface::txOverflowHandler () protected
Definition at line 195 of file SvcSerialCommandInterface.cpp.
{
     char* s;
     s = strrchr(tx_Buffer,'\r');//find last new line
     s[0] = 0;
     token = strtok(tx_Buffer, &newline);
     while( token != NULL ) {
         while(throttle()){
             delay(50);
         }
         if (tx_buffer_overflow_flag==false){
             //txBufferOverflowFlag=true;
             Serial.print(F("\""));
         }else{
             Serial.print(F(",\""));
         }
         //replaceAll(token,'\r',0);
         Serial.print(token);
         Serial.print(F("\""));
         token = strtok(NULL, &newline);
     }
     //close the tag
     Serial.println("]");
     //start the next part of the multipart message
     Serial.print(&multipart_header[0]);
     s = strrchr(tx_Buffer,'\r');//find last new line
     //s = strrchr(s,'\r');//find last new line
     s+=2;
     Serial.printf("VM %s %s\n",&multipart_header[0],s);
     //Serial.flush();
     index_tx_buffer = strlen(s);
     safer_strncpy(tx_Buffer,s,sizeof(tx_Buffer));
     //Serial.printf("VM remainder %s",txBuffer);
 }
References index_tx_buffer, multipart_header, newline, s, safer_strncpy(), throttle(), token, tx_Buffer, and tx_buffer_overflow_flag.
Referenced by write().