ERIS CORE: SvcSerialCommandInterface::messageHandler_GET_RAM2
messageHandler_GET_RAM2()
void FLASHMEM SvcSerialCommandInterface::messageHandler_GET_RAM2 () protected
Definition at line 401 of file SvcSerialCommandInterface.cpp.
{
     char* mp = 0;
     char c;
 #ifdef USE_EXTMEM
     char tmp[1000];
     //tmp = (char*)extmem_malloc(1000);
 #else
     char* tmp;
     tmp = (char*)malloc(1000);
 #endif
     while(throttle()){delay(100);}
     if(!requestStartLZ4Message()) return;
     strcpy(tmp,"");
     printf(F("RAM {\"RAM2\":{\"addr\":\"%08X\",\"chunk\":\""),0x20000000);
     //RAM2 always ends at 0x20280000
     for(uint32_t i = 0x20000000; i < 0x20280000; i+=1){
         if (i == 0x20010000) i = 0x20200000;
         mp = (char*)i;
         c = *mp;
         c = (c & 0xFF);
         if(i%32==0 && i != 0x20000000){
             print(F("\",\"decode\":\""));
             print(tmp);
             println(F("\"}}"));
             sendLZ4Message();
             strcpy(tmp,"");
             while(throttle()){delay(50);}
             if(i%1024==0){
                 float32_t pct;
                 pct = 100.0 * ((float)(i-0x20000000)/(float)(0x20280000-0x20000000));
                 Serial.printf(F("CLS\nM GET_RAM2 %08X %.0f pct "),i,pct);
                 for(uint16_t div = 0; div < (uint16_t)pct; div += 5){
                     Serial.printf("*");
                 }
                 Serial.println("");
             }
             startLZ4Message();
             printf(F("RAM {\"RAM2\":{\"addr\":\"%08X\",\"chunk\":\""),i);
         }
         printf("%02X ",(uint8_t)c);
         const char* escape = "\\";
         if (c=='"'){
             strncat(tmp, escape, 1);
             strncat(tmp, &c, 1);
         }else if (c=='\''){
             strncat(tmp, escape, 1);
             strncat(tmp, &c, 1);
         }else if (isprint((int)c)){
             strncat(tmp, &c, 1);
         }else if (iscntrl((int)c)){
             c = '.';
             strncat(tmp, &c, 1);
         }else{
             c = '?';
             strncat(tmp, &c, 1);
         }
     }
     println("\n");
     println(F("RAM END"));
     sendLZ4Message();
 #ifdef USE_EXTMEM
     //do nothing - local var
 #else
     free(tmp);
 #endif
 }
References requestStartLZ4Message(), sendLZ4Message(), startLZ4Message(), and throttle().
Referenced by update().