ERIS CORE: SvcSerialCommandInterface::endLZ4Message
endLZ4Message()
void SvcSerialCommandInterface::endLZ4Message ()
Calling this function signals the end of a compressed message. The current txBuffer is lz4 compressed before being base64 encoded and sent. The sent message format is "LZ4 [UNCOMPRESSED_SIZE] [BASE64 encoded LZ4 compressed message]".
Definition at line 123 of file svcSerialCommandInterface.cpp.
{
     uint16_t compressed_len,uncompressed_len;
 #ifdef USE_EXTMEM
     //do nothing - one time malloc in the constructor
 #else
     char workingBuffer[SERIAL_WORKING_BUFFER_SIZE];
 #endif
     memset(workingBuffer,0,SERIAL_WORKING_BUFFER_SIZE);
     uncompressed_len = indexTxBuffer;
     compressed_len = LZ4_compress_fast(txBuffer,workingBuffer,indexTxBuffer,SERIAL_WORKING_BUFFER_SIZE,1);
     empty();
     encode_base64((unsigned char *)workingBuffer, compressed_len, (unsigned char *)txBuffer);
     while(throttle()){
         delay(50);
     };
     Serial.print(" ");
     Serial.print(uncompressed_len);
     Serial.print(" ");
     Serial.println(txBuffer);
     empty();
     while(throttle()){
         delayMicroseconds(500);
     };
 #ifdef USE_EXTMEM
     //do nothing - one time malloc in the constructor
 #else
     //do nothing - local var
 #endif
 }
References empty(), indexTxBuffer, SERIAL_WORKING_BUFFER_SIZE, throttle(), txBuffer, and workingBuffer.
Referenced by AppCQT::MessageHandler(), SvcDataDictionary::printDictionary(), AudioDirector::printStats(), AppCQT::update(), and updateRT().