ERIS CORE: SvcSerialCommandInterface::streamTransmitHandler
streamTransmitHandler()
void FLASHMEM SvcSerialCommandInterface::streamTransmitHandler () protected
Definition at line 256 of file svcSerialCommandInterface.cpp.
{
     char bufferChr; //only need one char - 512 size is due to a potential bug in the teensy library identified by covintry static analysis
     char hexBuffer[8];
     uint16_t payload_len;
     //if(Serial.availableForWrite() < 6000) return;
     if(throttle()) return;
     p_SD->chdir(p_stream_path);
     if (p_SD->exists(p_stream_file)){
         payload_len = 0;
         if(!file.open(p_stream_file, O_READ)){
             Serial.println(F("M GET_ERR FILE OPEN ERROR"));
             is_streaming_file = false;
             is_periodic_messages_enabled = true;
             stream_pos = 0;
             return;
         }
         startLZ4Message();
         print("FS ");
         file.seek(stream_pos);
         //send the next chunked message until eof
         uint64_t i;
         i = file.available();
         if(i>0){
             //if i is zero then last chunk was eof
             if(i > SERIAL_FILESTREAM_PAYLOAD_SIZE) i = SERIAL_FILESTREAM_PAYLOAD_SIZE;
             for(;i > 0; i--){
                 payload_len += 1;
                 if (file.read(&bufferChr,1) < 0){
                     Serial.println(F("\nM GET_ERR FILE READ ERROR"));
                     is_streaming_file = false;
                     is_periodic_messages_enabled = true;
                     stream_pos = 0;
                     file.close();
                     return;
                 }
                 sprintf(hexBuffer,"%02X,",(unsigned int)bufferChr);
                 print(hexBuffer);
             }
             if(index_tx_buffer > 0) p_tx_Buffer[--index_tx_buffer] = '\0'; //remove last comma
             stream_pos = file.position();
             println("");
         }
         file.close();
         if (payload_len == 0){
             //no data to tx; @ eof
             sendLZ4Message();
             Serial.println("FS_END");
             is_streaming_file = false;
             is_periodic_messages_enabled = true;
             stream_pos = 0;
             delayMicroseconds(3000);
             return;
         }
         else if (payload_len < SERIAL_FILESTREAM_PAYLOAD_SIZE) {
             sendLZ4Message();
             Serial.println("FS_END");
             empty();
             is_streaming_file = false;
             is_periodic_messages_enabled = true;
             stream_pos = 0;
             delayMicroseconds(3000);
             return;
         } else{
             //send file chunk
             sendLZ4Message();
             return;
         }
     }
     else{
         Serial.print(F("M GET_ERR FILE NOT FOUND "));
         Serial.println(p_stream_file);
         is_streaming_file = false;
         stream_pos = 0;
         return;
     }
 };
References empty(), file, index_tx_buffer, is_periodic_messages_enabled, is_streaming_file, p_SD, p_stream_file, p_stream_path, p_tx_Buffer, sendLZ4Message(), startLZ4Message(), stream_pos, and throttle().
Referenced by update().