ERIS CORE: SvcSerialCommandInterface::requestStartLZ4Message
requestStartLZ4Message()
bool SvcSerialCommandInterface::requestStartLZ4Message () inline
request to start a lz4 compressed message
starts the message and returns true if available returns false if busy
Returns
true
false
Definition at line 102 of file SvcSerialCommandInterface.h.
{
       if(is_streaming_file) return false;
       startLZ4Message();
       return true;
     }
References is_streaming_file, and startLZ4Message().
Referenced by AppCQT::messageHandler(), SvcDataDictionary::printDictionary(), AppManager::printStats(), AudioDirector::printStats(), AppCQT::render(), update(), and writeFn().