ERIS CORE: SvcSerialCommandInterface::txOverflowHandler
txOverflowHandler()
void SvcSerialCommandInterface::txOverflowHandler () protected
Definition at line 197 of file SvcSerialCommandInterface.cpp.
{
     char* s;
     s = strrchr(txBuffer,'\r');//find last new line
     s[0] = 0;
     token = strtok(txBuffer, &newline);
     while( token != NULL ) {
         while(throttle()){
             delay(50);
         }
         if (txBufferOverflowFlag==false){
             //txBufferOverflowFlag=true;
             Serial.print(F("\""));
         }else{
             Serial.print(F(",\""));
         }
         //replaceAll(token,'\r',0);
         Serial.print(token);
         Serial.print(F("\""));
         token = strtok(NULL, &newline);
     }
     //close the tag
     Serial.println("]");
     //start the next part of the multipart message
     Serial.print(&multiPartHeader[0]);
     s = strrchr(txBuffer,'\r');//find last new line
     //s = strrchr(s,'\r');//find last new line
     s+=2;
     SerialUSB1.printf("VM %s %s\n",&multiPartHeader[0],s);
     //SerialUSB1.flush();
     indexTxBuffer = strlen(s);
     safer_strncpy(txBuffer,s,sizeof(txBuffer));
     //SerialUSB1.printf("VM remainder %s",txBuffer);
 }
References indexTxBuffer, multiPartHeader, newline, s, safer_strncpy(), throttle(), token, txBuffer, and txBufferOverflowFlag.
Referenced by write().