ERIS CORE: ExFile Class Reference
ExFile Class Reference
exFAT file with Arduino Stream.
#include <ExFatFile.h>
Public Member Functions
int available ()
uint64_t available64 ()
void clearError ()
void clearWriteError ()
bool close ()
uint64_t curPosition () const
uint64_t dataLength ()
uint32_t dirIndex ()
bool exists (const ExChar_t *path)
void fgetpos (fspos_t *pos)
int fgets (char *str, int num, char *delim=nullptr)
uint64_t fileSize ()
void flush ()
void fsetpos (const fspos_t *pos)
uint8_t getError ()
size_t getName (ExChar_t *name, size_t size)
bool getWriteError ()
bool isContiguous () const
bool isDir () const
bool isDirectory ()
bool isFile () const
bool isHidden () const
bool isOpen () const
bool isReadable () const
bool isReadOnly () const
bool isRoot () const
bool isSubDir () const
bool isWritable () const
bool ls (print_t *pr)
bool ls (print_t *pr, uint8_t flags, uint8_t indent=0)
bool mkdir (ExFatFile *parent, const ExChar_t *path, bool pFlag=true)
const char * name () const
bool open (const ExChar_t *path, int oflag=O_RDONLY)
bool open (ExFatFile *dirFile, const ExChar_t *path, oflag_t oflag)
bool open (ExFatFile *dirFile, uint32_t index, oflag_t oflag)
bool open (ExFatVolume *vol, const ExChar_t *path, int oflag)
bool openNext (ExFatFile *dirFile, oflag_t oflag=O_RDONLY)
ExFile openNextFile (oflag_t oflag=O_RDONLY)
bool openRoot (ExFatVolume *vol)
operator bool ()
int peek ()
uint64_t position ()
bool preAllocate (uint64_t length)
size_t printAccessDateTime (print_t *pr)
size_t printCreateDateTime (print_t *pr)
size_t printField (double value, char term, uint8_t prec=2)
size_t printField (float value, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type value, char term)
size_t printFileSize (print_t *pr)
size_t printModifyDateTime (print_t *pr)
size_t printName (print_t *pr)
int read ()
int read (void *buf, size_t count)
bool remove ()
bool remove (const ExChar_t *path)
bool rename (const ExChar_t *newPath)
bool rename (ExFatFile *dirFile, const ExChar_t *newPath)
void rewind ()
void rewindDirectory ()
bool rmdir ()
bool seek (uint64_t pos)
bool seekCur (int64_t offset)
bool seekEnd (int64_t offset=0)
bool seekSet (uint64_t pos)
uint64_t size ()
bool sync ()
bool timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
bool truncate ()
bool truncate (uint64_t length)
uint64_t validLength ()
size_t write (const char *str)
size_t write (const uint8_t *buffer, size_t size)
size_t write (const void *buf, size_t count)
size_t write (uint8_t b)
Detailed Description
exFAT file with Arduino Stream.
Definition at line 749 of file ExFatFile.h.
Member Function Documentation
available()
int StreamFile< ExFatFile , uint64_t >::available (void) inline inherited
Returns
number of bytes available from the current position to EOF or INT_MAX if more than INT_MAX bytes are available.
Definition at line 75 of file ArduinoFiles.h.
                   {
     return BaseFile::available();
   }
available64()
uint64_t ExFatFile::available64 () inline inherited
Returns
The number of bytes available from the current position to EOF for normal files. Zero is returned for directory files.
Definition at line 115 of file ExFatFile.h.
{
     return isFile() ? fileSize() - curPosition() : 0;
   }
References ExFatFile::curPosition(), ExFatFile::fileSize(), and ExFatFile::isFile().
Referenced by ExFatFile::available().
clearError()
void ExFatFile::clearError () inline inherited
Clear all error bits.
Definition at line 200 of file ExFatFile.h.
                     {
     m_error = 0;
   }
clearWriteError()
void ExFatFile::clearWriteError () inline inherited
Set writeError to zero
Definition at line 204 of file ExFatFile.h.
{
     m_error &= ~WRITE_ERROR;
   }
Referenced by FsBaseFile::clearWriteError().
close()
bool ExFatFile::close () inherited
Close a file and force cached data and directory information to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 31 of file ExFatFile.cpp.
                       {
   bool rtn = sync();
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   return rtn;
 }
References ExFatFile::sync().
Referenced by ExFatVolume::chdir(), FsBaseFile::close(), ExFatFile::ls(), ExFatFile::mkdir(), and ExFatFile::open().
curPosition()
uint64_t ExFatFile::curPosition () const inline inherited
Returns
The current position for a file or directory.
Definition at line 137 of file ExFatFile.h.
 {return m_curPosition;}
Referenced by ExFatFile::available64(), FsBaseFile::curPosition(), ExFatFile::openNext(), and ExFatFile::peek().
dataLength()
uint64_t ExFatFile::dataLength () inline inherited
Returns
Total data length for file.
Definition at line 140 of file ExFatFile.h.
 {return m_dataLength;}
dirIndex()
uint32_t ExFatFile::dirIndex () inline inherited
Returns
Directory entry index.
Definition at line 142 of file ExFatFile.h.
 {return m_dirPos.position/32;}
References DirPos_t::position.
Referenced by FsBaseFile::dirIndex(), and ExFatFile::open().
exists()
bool ExFatFile::exists (const ExChar_t * path) inline inherited
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
The calling instance must be an open directory file.
dirFile.exists("TOFIND.TXT") searches for "TOFIND.TXT" in the directory dirFile.
Returns
true if the file exists else false.
Definition at line 154 of file ExFatFile.h.
{
     ExFatFile file;
     return file.open(this, path, O_RDONLY);
   }
References O_RDONLY, and ExFatFile::open().
Referenced by FsBaseFile::exists().
fgetpos()
void ExFatFile::fgetpos (fspos_t * pos) inherited
get position for streams
Parameters
[out] pos struct to receive position
Definition at line 38 of file ExFatFile.cpp.
{
   pos->position = m_curPosition;
   pos->cluster = m_curCluster;
 }
References fspos_t::cluster, and fspos_t::position.
Referenced by FsBaseFile::fgetpos().
fgets()
int ExFatFile::fgets (char * str, int num, char * delim = nullptr) inherited
Get a string from a file.
fgets() reads bytes from a file into the array pointed to by str, until num - 1 bytes are read, or a delimiter is read and transferred to str, or end-of-file is encountered. The string is then terminated with a null byte.
fgets() deletes CR, '\r', from the string. This insures only a '\n' terminates the string for Windows text files which use CRLF for newline.
Parameters
[out] str Pointer to the array where the string is stored.
[in] num Maximum number of characters to be read (including the final null byte). Usually the length of the array str is used.
[in] delim Optional set of delimiters. The default is "\n".
Returns
For success fgets() returns the length of the string in str. If no data is read, fgets() returns zero for EOF or -1 if an error occurred.
Definition at line 43 of file ExFatFile.cpp.
{
   char ch;
   int n = 0;
   int r = -1;
   while ((n + 1) < num && (r = read(&ch, 1)) == 1) {
     // delete CR
     if (ch == '\r') {
       continue;
     }
     str[n++] = ch;
     if (!delim) {
       if (ch == '\n') {
         break;
       }
     } else {
       if (strchr(delim, ch)) {
         break;
       }
     }
   }
   if (r < 0) {
     // read error
     return -1;
   }
   str[n] = '\0';
   return n;
 }
References ExFatFile::read().
Referenced by FsBaseFile::fgets().
fileSize()
uint64_t ExFatFile::fileSize () inline inherited
Returns
The total number of bytes in a file.
Definition at line 184 of file ExFatFile.h.
 {return m_validLength;}
Referenced by ExFatFile::available64(), and FsBaseFile::fileSize().
flush()
void StreamFile< ExFatFile , uint64_t >::flush () inline inherited
Ensure that any bytes written to the file are saved to the SD card.
Definition at line 79 of file ArduinoFiles.h.
                {
     BaseFile::sync();
   }
fsetpos()
void ExFatFile::fsetpos (const fspos_t * pos) inherited
set position for streams
Parameters
[in] pos struct with value for new position
Definition at line 71 of file ExFatFile.cpp.
{
   m_curPosition = pos->position;
   m_curCluster = pos->cluster;
 }
References fspos_t::cluster, and fspos_t::position.
Referenced by FsBaseFile::fsetpos().
getError()
uint8_t ExFatFile::getError () inline inherited
Returns
All error bits.
Definition at line 208 of file ExFatFile.h.
                      {
     return isOpen() ? m_error : 0XFF;
   }
References ExFatFile::isOpen().
Referenced by FsBaseFile::getError(), and ExFatFile::ls().
getName()
size_t ExFatFile::getName (ExChar_t * name, size_t size) inherited
Get a file's name followed by a zero byte.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in characters.
Returns
the name length.
Definition at line 76 of file ExFatFile.cpp.
{
   DirName_t* dn;
   DirPos_t pos = m_dirPos;
   size_t n = 0;
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   for (uint8_t is = 1; is < m_setCount; is++) {
     if (m_vol->dirSeek(&pos, is == 1 ? 64: 32) != 1) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     dn = reinterpret_cast<DirName_t*>
          (m_vol->dirCache(&pos, FsCache::CACHE_FOR_READ));
     if (!dn || dn->type != EXFAT_TYPE_NAME) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (uint8_t in = 0; in < 15; in++) {
       if ((n + 1) >= length) {
         goto done;
       }
       uint16_t c = getLe16(dn->unicode + 2*in);
       name[n++] = sizeof(ExChar_t) > 1 || c < 0X7F ? c : '?';
     }
   }
  done:
   name[n] = 0;
   return n;
  fail:
   *name = 0;
   return 0;
 }
References FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, EXFAT_TYPE_NAME, getLe16(), ExFatFile::isOpen(), DirName_t::type, and DirName_t::unicode.
Referenced by FsBaseFile::getName().
getWriteError()
bool ExFatFile::getWriteError () inline inherited
Returns
value of writeError
Definition at line 212 of file ExFatFile.h.
{
     return isOpen() ? m_error & WRITE_ERROR : true;
   }
References ExFatFile::isOpen().
Referenced by FsBaseFile::getWriteError().
isContiguous()
bool ExFatFile::isContiguous () const inline inherited
Returns
True if the file is contiguous.
Definition at line 216 of file ExFatFile.h.
 {return m_flags & FILE_FLAG_CONTIGUOUS;}
Referenced by ExFatFile::read(), ExFatFile::remove(), ExFatFile::seekSet(), ExFatFile::truncate(), and ExFatFile::write().
isDir()
bool ExFatFile::isDir () const inline inherited
Returns
True if this is a directory.
Definition at line 218 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_DIR;}
Referenced by ExFatVolume::chdir(), FsBaseFile::isDir(), ExFatFile::ls(), ExFatFile::mkdir(), ExFatFile::open(), ExFatFile::openNext(), and ExFatFile::read().
isDirectory()
bool StreamFile< ExFatFile , uint64_t >::isDirectory () inline inherited
This function reports if the current file is a directory or not.
Returns
true if the file is a directory.
Definition at line 85 of file ArduinoFiles.h.
                      {
     return BaseFile::isDir();
   }
isFile()
bool ExFatFile::isFile () const inline inherited
Returns
True if this is a normal file.
Definition at line 220 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_FILE;}
Referenced by ExFatFile::available64(), ExFatFile::read(), ExFatFile::rename(), ExFatFile::seekEnd(), ExFatFile::seekSet(), and ExFatFile::timestamp().
isHidden()
bool ExFatFile::isHidden () const inline inherited
Returns
True if this is a hidden.
Definition at line 222 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_HIDDEN;}
Referenced by FsBaseFile::isHidden(), and ExFatFile::ls().
isOpen()
bool ExFatFile::isOpen () const inline inherited
Returns
true if the file is open.
Definition at line 224 of file ExFatFile.h.
 {return m_attributes;}
Referenced by ExFatFile::getError(), ExFatFile::getName(), ExFatFile::getWriteError(), ExFatFile::mkdir(), ExFatFile::open(), ExFatFile::openNext(), ExFatFile::openRoot(), ExFatFile::operator bool(), ExFatFile::printName(), ExFatFile::seekSet(), and ExFatFile::sync().
isReadable()
bool ExFatFile::isReadable () const inline inherited
Returns
True file is writable.
Definition at line 232 of file ExFatFile.h.
 {return m_flags & FILE_FLAG_READ;}
Referenced by ExFatFile::read().
isReadOnly()
bool ExFatFile::isReadOnly () const inline inherited
Returns
True if file is read-only
Definition at line 226 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_READ_ONLY;}
isRoot()
bool ExFatFile::isRoot () const inline inherited
Returns
True if this is the root directory.
Definition at line 230 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_ROOT;}
Referenced by ExFatFile::read(), and ExFatFile::seekSet().
isSubDir()
bool ExFatFile::isSubDir () const inline inherited
Returns
True if this is a subdirectory.
Definition at line 228 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_SUBDIR;}
Referenced by FsBaseFile::isSubDir(), ExFatFile::rename(), and ExFatFile::rmdir().
isWritable()
bool ExFatFile::isWritable () const inline inherited
Returns
True file is writable.
Definition at line 234 of file ExFatFile.h.
 {return m_flags & FILE_FLAG_WRITE;}
Referenced by ExFatFile::preAllocate(), ExFatFile::remove(), ExFatFile::truncate(), and ExFatFile::write().
ls() [1/2]
bool ExFatFile::ls (print_t * pr) inherited
List directory contents.
Parameters
[in] pr Print stream for list.
Returns
true for success or false for failure.
Definition at line 84 of file ExFatFilePrint.cpp.
{
   ExFatFile file;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   while (file.openNext(this, O_RDONLY)) {
     if (!file.isHidden()) {
       file.printName(pr);
       if (file.isDir()) {
         pr->write('/');
       }
       pr->write('\r');
       pr->write('\n');
     }
     file.close();
   }
   if (getError()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References ExFatFile::close(), DBG_FAIL_MACRO, ExFatFile::getError(), ExFatFile::isDir(), ExFatFile::isHidden(), O_RDONLY, ExFatFile::openNext(), ExFatFile::printName(), and ExFatFile::rewind().
Referenced by ExFatFile::ls(), and ExFatVolume::ls().
ls() [2/2]
bool ExFatFile::ls (print_t * pr, uint8_t flags, uint8_t indent = 0) inherited
List directory contents.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Parameters
[in] indent Amount of space before file name. Used for recursive list to indicate subdirectory level.
Returns
true for success or false for failure.
Definition at line 112 of file ExFatFilePrint.cpp.
{
   ExFatFile file;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   while (file.openNext(this, O_RDONLY)) {
     // indent for dir level
     if (!file.isHidden() || (flags & LS_A)) {
       for (uint8_t i = 0; i < indent; i++) {
         pr->write(' ');
       }
       if (flags & LS_DATE) {
         file.printModifyDateTime(pr);
         pr->write(' ');
       }
       if (flags & LS_SIZE) {
         file.printFileSize(pr);
         pr->write(' ');
       }
       file.printName(pr);
       if (file.isDir()) {
         pr->write('/');
       }
       pr->write('\r');
       pr->write('\n');
       if ((flags & LS_R) && file.isDir()) {
         file.ls(pr, flags, indent + 2);
       }
     }
     file.close();
   }
   if (getError()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References ExFatFile::close(), DBG_FAIL_MACRO, ExFatFile::getError(), ExFatFile::isDir(), ExFatFile::isHidden(), ExFatFile::ls(), LS_A, LS_DATE, LS_R, LS_SIZE, O_RDONLY, ExFatFile::openNext(), ExFatFile::printFileSize(), ExFatFile::printModifyDateTime(), ExFatFile::printName(), and ExFatFile::rewind().
mkdir()
bool ExFatFile::mkdir (ExFatFile * parent, const ExChar_t * path, bool pFlag = true) inherited
Make a new directory.
Parameters
[in] parent An open directory file that will contain the new directory.
[in] path A path with a valid name for the new directory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 160 of file ExFatFileWrite.cpp.
{
   ExName_t fname;
   ExFatFile tmpDir;
   if (isOpen() || !parent->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isDirSeparator(*path)) {
     while (isDirSeparator(*path)) {
       path++;
     }
     if (!tmpDir.openRoot(parent->m_vol)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     parent = &tmpDir;
   }
   while (1) {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!*path) {
       break;
     }
     if (!open(parent, &fname, O_RDONLY)) {
       if (!pFlag || !mkdir(parent, &fname)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     tmpDir = *this;
     parent = &tmpDir;
     close();
   }
   return mkdir(parent, &fname);
 fail:
   return false;
 }
References ExFatFile::close(), DBG_FAIL_MACRO, ExFatFile::isDir(), isDirSeparator, ExFatFile::isOpen(), O_RDONLY, ExFatFile::open(), and ExFatFile::openRoot().
Referenced by ExFatVolume::mkdir(), and FsBaseFile::mkdir().
name()
const char* StreamFile< ExFatFile , uint64_t >::name () const inline inherited
No longer implemented due to Long File Names.
Use getName(char* name, size_t size).
Returns
a pointer to replacement suggestion.
Definition at line 93 of file ArduinoFiles.h.
{
     return "use getName()";
   }
open() [1/4]
bool ExFatFile::open (const ExChar_t * path, int oflag = O_RDONLY) inherited
Open a file in the current working directory.
Parameters
[in] path A path with a valid name for a file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see ExFatFile::open(ExFatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 112 of file ExFatFile.cpp.
{
   return open(ExFatVolume::cwv(), path, oflag);
 }
References ExFatVolume::cwv(), and ExFatFile::open().
open() [2/4]
bool ExFatFile::open (ExFatFile * dirFile, const ExChar_t * path, oflag_t oflag) inherited
Open a file or directory by name.
Parameters
[in] dirFile An open directory containing the file to be opened.
[in] path The path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list. Only one of O_RDONLY, O_READ, O_WRONLY, O_WRITE, or O_RDWR is allowed.
O_RDONLY - Open for reading.
O_READ - Same as O_RDONLY.
O_WRONLY - Open for writing.
O_WRITE - Same as O_WRONLY.
O_RDWR - Open for reading and writing.
O_APPEND - If set, the file offset shall be set to the end of the file prior to each write.
O_AT_END - Set the initial position at the end of the file.
O_CREAT - If the file exists, this flag has no effect except as noted under O_EXCL below. Otherwise, the file shall be created
O_EXCL - If O_CREAT and O_EXCL are set, open() shall fail if the file exists.
O_TRUNC - If the file exists and is a regular file, and the file is successfully opened and is not read only, its length shall be truncated to 0.
WARNING: A given file must not be opened by more than one file object or file corruption may occur.
Note
Directory files must be opened read only. Write and truncation is not allowed for directory files.
Returns
true for success or false for failure.
Definition at line 120 of file ExFatFile.cpp.
{
   ExFatFile tmpDir;
   ExName_t fname;
   // error if already open
   if (isOpen() || !dirFile->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isDirSeparator(*path)) {
     while (isDirSeparator(*path)) {
       path++;
     }
     if (*path == 0) {
       return openRoot(dirFile->m_vol);
     }
     if (!tmpDir.openRoot(dirFile->m_vol)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     dirFile = &tmpDir;
   }
   while (1) {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (*path == 0) {
       break;
     }
     if (!open(dirFile, &fname, O_RDONLY)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     tmpDir = *this;
     dirFile = &tmpDir;
     close();
   }
   return open(dirFile, &fname, oflag);
 fail:
   return false;
 }
References ExFatFile::close(), DBG_FAIL_MACRO, ExFatFile::isDir(), isDirSeparator, ExFatFile::isOpen(), O_RDONLY, and ExFatFile::openRoot().
Referenced by ExFatVolume::chdir(), ExFatFile::exists(), ExFatVolume::exists(), ExFatVolume::ls(), ExFatFile::mkdir(), ExFatFile::open(), ExFatVolume::open(), FsBaseFile::open(), ExFatFile::remove(), ExFatVolume::remove(), ExFatVolume::rename(), ExFatFile::rename(), ExFatVolume::rmdir(), and ExFatVolume::truncate().
open() [3/4]
bool ExFatFile::open (ExFatFile * dirFile, uint32_t index, oflag_t oflag) inherited
Open a file by index.
Parameters
[in] dirFile An open ExFatFile instance for the directory.
[in] index The index of the directory entry for the file to be opened. The value for index is (directory file position)/32.
[in] oflag bitwise-inclusive OR of open flags. See see ExFatFile::open(ExFatFile*, const ExChar_t*, uint8_t).
See open() by path for definition of flags.
Returns
true for success or false for failure.
Definition at line 163 of file ExFatFile.cpp.
{
   if (dirFile->seekSet(32*index) && openNext(dirFile, oflag)) {
     if (dirIndex() == index) {
       return true;
     }
     close();
     DBG_FAIL_MACRO;
   }
   return false;
 }
References ExFatFile::close(), DBG_FAIL_MACRO, ExFatFile::dirIndex(), index, ExFatFile::openNext(), and ExFatFile::seekSet().
open() [4/4]
bool ExFatFile::open (ExFatVolume * vol, const ExChar_t * path, int oflag) inherited
Open a file in the volume working directory.
Parameters
[in] vol Volume where the file is located.
[in] path with a valid name for a file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see open(ExFatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 116 of file ExFatFile.cpp.
{
   return vol && open(vol->vwd(), path, oflag);
 }
References ExFatFile::open().
openNext()
bool ExFatFile::openNext (ExFatFile * dirFile, oflag_t oflag = O_RDONLY) inherited
Open the next file or subdirectory in a directory.
Parameters
[in] dirFile An open instance for the directory containing the file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see open(ExFatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 174 of file ExFatFile.cpp.
{
   if (isOpen() || !dir->isDir() || (dir->curPosition() & 0X1F)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return openRootFile(dir, nullptr, 0, oflag);
  fail:
   return false;
 }
References ExFatFile::curPosition(), DBG_FAIL_MACRO, ExFatFile::isDir(), and ExFatFile::isOpen().
Referenced by ExFatFile::ls(), ExFatFile::open(), FsBaseFile::openNext(), and openNextFile().
openNextFile()
ExFile ExFile::openNextFile (oflag_t oflag = O_RDONLY) inline
Opens the next file or folder in a directory.
Parameters
[in] oflag open flags.
Returns
a FatStream object.
Definition at line 756 of file ExFatFile.h.
{
     ExFile tmpFile;
     tmpFile.openNext(this, oflag);
     return tmpFile;
   }
References ExFatFile::openNext().
openRoot()
bool ExFatFile::openRoot (ExFatVolume * vol) inherited
Open a volume's root directory.
Parameters
[in] vol The FAT volume containing the root directory to be opened.
Returns
true for success or false for failure.
Definition at line 442 of file ExFatFile.cpp.
{
   if (isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   memset(this, 0, sizeof(ExFatFile));
   m_attributes = FILE_ATTR_ROOT;
   m_vol = vol;
   m_flags = FILE_FLAG_READ;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, and ExFatFile::isOpen().
Referenced by ExFatVolume::chdir(), ExFatFile::mkdir(), and ExFatFile::open().
operator bool()
ExFatFile::operator bool () inline inherited
The parenthesis operator.
Returns
true if a file is open.
Definition at line 109 of file ExFatFile.h.
                   {
     return isOpen();
   }
References ExFatFile::isOpen().
peek()
int StreamFile< ExFatFile , uint64_t >::peek () inline inherited
Return the next available byte without consuming it.
Returns
The byte if no error and not at eof else -1;
Definition at line 100 of file ArduinoFiles.h.
              {
     return BaseFile::peek();
   }
position()
uint64_t StreamFile< ExFatFile , uint64_t >::position () inline inherited
Returns
the current file position.
Definition at line 104 of file ArduinoFiles.h.
                      {
     return BaseFile::curPosition();
   }
preAllocate()
bool ExFatFile::preAllocate (uint64_t length) inherited
Allocate contiguous clusters to an empty file.
The file must be empty with no clusters allocated.
The file will have zero validLength and dataLength will equal the requested length.
Parameters
[in] length size of allocated space in bytes.
Returns
true for success or false for failure.
Definition at line 232 of file ExFatFileWrite.cpp.
{
   uint32_t find;
   uint32_t need;
   if (!length || !isWritable() || m_firstCluster) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   need = 1 + ((length - 1) >> m_vol->bytesPerClusterShift());
   find = m_vol->bitmapFind(0, need);
   if (find < 2) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!m_vol->bitmapModify(find, need, 1)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_dataLength = length;
   m_firstCluster = find;
   m_flags |= FILE_FLAG_DIR_DIRTY | FILE_FLAG_CONTIGUOUS;
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References ExFatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, ExFatFile::isWritable(), and ExFatFile::sync().
printAccessDateTime()
size_t ExFatFile::printAccessDateTime (print_t * pr) inherited
Print a file's access date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 48 of file ExFatFilePrint.cpp.
{
   DirFile_t* df = reinterpret_cast<DirFile_t*>
                  (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_READ));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return fsPrintDateTime(pr, getLe32(df->accessTime));
 fail:
   return 0;
 }
References DirFile_t::accessTime, FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, fsPrintDateTime(), and getLe32().
printCreateDateTime()
size_t ExFatFile::printCreateDateTime (print_t * pr) inherited
Print a file's creation date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 60 of file ExFatFilePrint.cpp.
{
   DirFile_t* df = reinterpret_cast<DirFile_t*>
                  (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_READ));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return fsPrintDateTime(pr, getLe32(df->createTime));
 fail:
   return 0;
 }
References FsCache::CACHE_FOR_READ, DirFile_t::createTime, DBG_FAIL_MACRO, fsPrintDateTime(), and getLe32().
printField() [1/3]
size_t ExFatFile::printField (double value, char term, uint8_t prec = 2) inline inherited
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 390 of file ExFatFile.h.
{
     char buf[24];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     str = fmtDouble(str, value, prec, false);
     return write(str, buf + sizeof(buf) - str);
   }
References fmtDouble(), value, and ExFatFile::write().
Referenced by ExFatFile::printField().
printField() [2/3]
size_t ExFatFile::printField (float value, char term, uint8_t prec = 2) inline inherited
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 408 of file ExFatFile.h.
{
     return printField(static_cast<double>(value), term, prec);
   }
References ExFatFile::printField(), and value.
printField() [3/3]
template<typename Type > size_t ExFatFile::printField (Type value, char term) inline inherited
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 417 of file ExFatFile.h.
{
     char sign = 0;
     char buf[3*sizeof(Type) + 3];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     if (value < 0) {
       value = -value;
       sign = '-';
     }
     if (sizeof(Type) < 4) {
       str = fmtBase10(str, (uint16_t)value);
     } else {
       str = fmtBase10(str, (uint32_t)value);
     }
     if (sign) {
       *--str = sign;
     }
     return write(str, &buf[sizeof(buf)] - str);
   }
References fmtBase10(), value, and ExFatFile::write().
printFileSize()
size_t ExFatFile::printFileSize (print_t * pr) inherited
Print a file's size in bytes.
Parameters
[in] pr Prtin stream for the output.
Returns
The number of bytes printed.
Definition at line 31 of file ExFatFilePrint.cpp.
{
   uint64_t n = m_validLength;
   char buf[21];
   char *str = &buf[sizeof(buf) - 1];
   char *bgn = str - 12;
   *str = '\0';
   do {
     uint64_t m = n;
     n /= 10;
     *--str = m - 10*n + '0';
   } while (n);
   while (str > bgn) {
     *--str = ' ';
   }
   return pr->write(str);
 }
Referenced by ExFatFile::ls().
printModifyDateTime()
size_t ExFatFile::printModifyDateTime (print_t * pr) inherited
Print a file's modify date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 72 of file ExFatFilePrint.cpp.
{
   DirFile_t* df = reinterpret_cast<DirFile_t*>
                  (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_READ));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return fsPrintDateTime(pr, getLe32(df->modifyTime));
 fail:
   return 0;
 }
References FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, fsPrintDateTime(), getLe32(), and DirFile_t::modifyTime.
Referenced by ExFatFile::ls().
printName()
size_t ExFatFile::printName (print_t * pr) inherited
Print a file's name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 507 of file ExFatFile.cpp.
{
   DirName_t* dn;
   DirPos_t pos = m_dirPos;
   size_t n = 0;
   uint8_t in;
   uint8_t buf[15];
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   for (uint8_t is = 1; is < m_setCount; is++) {
     if (m_vol->dirSeek(&pos, is == 1 ? 64: 32) != 1) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     dn = reinterpret_cast<DirName_t*>
          (m_vol->dirCache(&pos, FsCache::CACHE_FOR_READ));
     if (!dn || dn->type != EXFAT_TYPE_NAME) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (in = 0; in < 15; in++) {
       uint16_t c = getLe16(dn->unicode + 2*in);
       if (!c) {
         break;;
       }
       buf[in] = c < 0X7f ? c : '?';
       n++;
     }
     pr->write(buf, in);
   }
   return n;
  fail:
   return 0;
 }
References FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, EXFAT_TYPE_NAME, getLe16(), ExFatFile::isOpen(), DirName_t::type, and DirName_t::unicode.
Referenced by ExFatFile::ls().
read() [1/2]
int StreamFile< ExFatFile , uint64_t >::read () inline inherited
Read the next byte from a file.
Returns
For success return the next byte in the file as an int. If an error occurs or end of file is reached return -1.
Definition at line 112 of file ArduinoFiles.h.
              {
     return BaseFile::read();
   }
read() [2/2]
int ExFatFile::read (void * buf, size_t count) inherited
Read data from a file starting at the current position.
Parameters
[out] buf Pointer to the location that will receive the data.
[in] count Maximum number of bytes to read.
Returns
For success read() returns the number of bytes read. A value less than nbyte, including zero, will be returned if end of file is reached. If an error occurs, read() returns -1.
Definition at line 544 of file ExFatFile.cpp.
{
   uint8_t* dst = reinterpret_cast<uint8_t*>(buf);
   int8_t fg;
   size_t toRead = count;
   size_t n;
   uint8_t* cache;
   uint16_t sectorOffset;
   uint32_t sector;
   uint32_t clusterOffset;
   if (!isReadable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isContiguous() || isFile()) {
     if ((m_curPosition + count) > m_validLength) {
       count = toRead = m_validLength - m_curPosition;
     }
   }
   while (toRead) {
     clusterOffset = m_curPosition & m_vol->clusterMask();
     sectorOffset = clusterOffset & m_vol->sectorMask();
     if (clusterOffset == 0) {
       if (m_curPosition == 0) {
         m_curCluster = isRoot()
                        ? m_vol->rootDirectoryCluster() : m_firstCluster;
       } else if (isContiguous()) {
         m_curCluster++;
       } else {
         fg = m_vol->fatGet(m_curCluster, &m_curCluster);
         if (fg < 0) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         if (fg == 0) {
           // EOF if directory.
           if (isDir()) {
             break;
           }
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
     }
     sector = m_vol->clusterStartSector(m_curCluster) +
              (clusterOffset >> m_vol->bytesPerSectorShift());
     if (sectorOffset != 0 || toRead < m_vol->bytesPerSector()
                           || sector == m_vol->dataCacheSector()) {
       n = m_vol->bytesPerSector() - sectorOffset;
       if (n > toRead) {
         n = toRead;
       }
       // read sector to cache and copy data to caller
       cache = m_vol->dataCacheGet(sector, FsCache::CACHE_FOR_READ);
       if (!cache) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       uint8_t* src = cache + sectorOffset;
       memcpy(dst, src, n);
 #if USE_MULTI_SECTOR_IO
     } else if (toRead >= 2*m_vol->bytesPerSector()) {
       uint32_t ns = toRead >> m_vol->bytesPerSectorShift();
       // Limit writes to current cluster.
       uint32_t maxNs = m_vol->sectorsPerCluster()
                        - (clusterOffset >> m_vol->bytesPerSectorShift());
       if (ns > maxNs) {
         ns = maxNs;
       }
       n = ns << m_vol->bytesPerSectorShift();
       // Check for cache sector in read range.
       if (sector <= m_vol->dataCacheSector()
           && m_vol->dataCacheSector() < (sector + ns)) {
         // Flush cache if cache sector is in the range.
         if (!m_vol->dataCacheSync()) {
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
       if (!m_vol->readSectors(sector, dst, ns)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
 #endif  // USE_MULTI_SECTOR_IO
     } else {
       // read single sector
       n = m_vol->bytesPerSector();
       if (!m_vol->readSector(sector, dst)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     dst += n;
     m_curPosition += n;
     toRead -= n;
   }
   return count - toRead;
 fail:
   m_error |= READ_ERROR;
   return -1;
 }
References ExFatPartition::bytesPerSector(), ExFatPartition::bytesPerSectorShift(), FsCache::CACHE_FOR_READ, count, DBG_FAIL_MACRO, ExFatFile::isContiguous(), ExFatFile::isDir(), ExFatFile::isFile(), ExFatFile::isReadable(), ExFatFile::isRoot(), ExFatPartition::rootDirectoryCluster(), and ExFatPartition::sectorsPerCluster().
remove() [1/2]
bool ExFatFile::remove () inherited
Remove a file.
The directory entry and all data for the file are deleted.
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 262 of file ExFatFileWrite.cpp.
{
   DirPos_t pos = m_dirPos;
   uint8_t* cache;
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Free any clusters.
   if (m_firstCluster) {
     if (isContiguous()) {
       uint32_t nc = 1 + ((m_dataLength - 1) >> m_vol->bytesPerClusterShift());
       if (!m_vol->bitmapModify(m_firstCluster, nc, 0)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     } else {
       if (!m_vol->freeChain(m_firstCluster)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   }
   for (uint8_t i = 0; i <= m_setCount; i++) {
     if (i && m_vol->dirSeek(&pos, 32) != 1) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     cache = m_vol->dirCache(&pos, FsCache::CACHE_FOR_WRITE);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // Mark entry not used.
     cache[0] &= 0x7F;
   }
   // Set this file closed.
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   // Write entry to device.
   return m_vol->cacheSync();
  fail:
   return false;
 }
References ExFatPartition::bytesPerClusterShift(), FsCache::CACHE_FOR_WRITE, DBG_FAIL_MACRO, ExFatFile::isContiguous(), and ExFatFile::isWritable().
Referenced by FsBaseFile::remove(), ExFatFile::remove(), ExFatVolume::remove(), ExFatFile::rename(), and ExFatFile::rmdir().
remove() [2/2]
bool ExFatFile::remove (const ExChar_t * path) inherited
Remove a file.
The directory entry and all data for the file are deleted.
Parameters
[in] path Path for the file to be removed.
Example use: dirFile.remove(filenameToRemove);
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 647 of file ExFatFile.cpp.
{
   ExFatFile file;
   if (!file.open(this, path, O_WRONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return file.remove();
 fail:
   return false;
 }
References DBG_FAIL_MACRO, O_WRONLY, ExFatFile::open(), and ExFatFile::remove().
rename() [1/2]
bool ExFatFile::rename (const ExChar_t * newPath) inherited
Rename a file or subdirectory.
Parameters
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 309 of file ExFatFileWrite.cpp.
{
   return rename(m_vol->vwd(), newPath);
 }
Referenced by ExFatVolume::rename().
rename() [2/2]
bool ExFatFile::rename (ExFatFile * dirFile, const ExChar_t * newPath) inherited
Rename a file or subdirectory.
Parameters
[in] dirFile Directory for the new path.
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 313 of file ExFatFileWrite.cpp.
{
   ExFatFile file;
   ExFatFile oldFile;
   // Must be an open file or subdirectory.
   if (!(isFile() || isSubDir())) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Can't move file to new volume.
   if (m_vol != dirFile->m_vol) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!file.open(dirFile, newPath, O_CREAT | O_EXCL | O_WRONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   oldFile = *this;
   m_dirPos = file.m_dirPos;
   m_setCount = file.m_setCount;
   m_flags |= FILE_FLAG_DIR_DIRTY;
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Remove old directory entry;
   oldFile.m_firstCluster = 0;
   oldFile.m_flags = FILE_FLAG_WRITE;
   oldFile.m_attributes = FILE_ATTR_FILE;
   return oldFile.remove();
 fail:
   return false;
 }
References DBG_FAIL_MACRO, ExFatFile::isFile(), ExFatFile::isSubDir(), O_CREAT, O_EXCL, O_WRONLY, ExFatFile::open(), ExFatFile::remove(), and ExFatFile::sync().
rewind()
void ExFatFile::rewind () inline inherited
Set the file's current position to zero.
Definition at line 539 of file ExFatFile.h.
                 {
     seekSet(0);
   }
References ExFatFile::seekSet().
Referenced by ExFatFile::ls(), and ExFatFile::rmdir().
rewindDirectory()
void StreamFile< ExFatFile , uint64_t >::rewindDirectory () inline inherited
Rewind a file if it is a directory
Definition at line 116 of file ArduinoFiles.h.
{
     if (BaseFile::isDir()) {
       BaseFile::rewind();
     }
   }
rmdir()
bool ExFatFile::rmdir () inherited
Remove a directory file.
The directory file will be removed only if it is empty and is not the root directory. rmdir() follows DOS and Windows and ignores the read-only attribute for the directory.
Note
This function should not be used to delete the 8.3 version of a directory that has a long name. For example if a directory has the long name "New folder" you should not delete the 8.3 name "NEWFOL~1".
Returns
true for success or false for failure.
Definition at line 349 of file ExFatFileWrite.cpp.
                       {
   int n;
   uint8_t dir[32];
   // must be open subdirectory
   if (!isSubDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   // make sure directory is empty
   while (1) {
     n = read(dir, 32);
     if (n == 0) {
       break;
     }
     if (n != 32 || dir[0] & 0X80) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (dir[0] == 0) {
       break;
     }
   }
   // convert empty directory to normal file for remove
   m_attributes = FILE_ATTR_FILE;
   m_flags |= FILE_FLAG_WRITE;
   return remove();
 fail:
   return false;
 }
References DBG_FAIL_MACRO, ExFatFile::isSubDir(), ExFatFile::read(), ExFatFile::remove(), and ExFatFile::rewind().
Referenced by FsBaseFile::rmdir(), and ExFatVolume::rmdir().
seek()
bool StreamFile< ExFatFile , uint64_t >::seek (uint64_t pos) inline inherited
Seek to a new position in the file, which must be between 0 and the size of the file (inclusive).
Parameters
[in] pos the new file position.
Returns
true for success or false for failure.
Definition at line 128 of file ArduinoFiles.h.
{
     return BaseFile::seekSet(pos);
   }
seekCur()
bool ExFatFile::seekCur (int64_t offset) inline inherited
Set the files position to current position + pos. See seekSet().
Parameters
[in] offset The new position in bytes from the current position.
Returns
true for success or false for failure.
Definition at line 559 of file ExFatFile.h.
{
     return seekSet(m_curPosition + offset);
   }
References ExFatFile::seekSet().
seekEnd()
bool ExFatFile::seekEnd (int64_t offset = 0) inline inherited
Set the files position to end-of-file + offset. See seekSet(). Can't be used for directory files since file size is not defined.
Parameters
[in] offset The new position in bytes from end-of-file.
Returns
true for success or false for failure.
Definition at line 567 of file ExFatFile.h.
{
     return isFile() ? seekSet(m_validLength + offset) : false;
   }
References ExFatFile::isFile(), and ExFatFile::seekSet().
seekSet()
bool ExFatFile::seekSet (uint64_t pos) inherited
Sets a file's position.
Parameters
[in] pos The new position in bytes from the beginning of the file.
Returns
true for success or false for failure.
Definition at line 659 of file ExFatFile.cpp.
{
   uint32_t nCur;
   uint32_t nNew;
   uint32_t tmp = m_curCluster;
   // error if file not open
   if (!isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Optimize O_APPEND writes.
   if (pos == m_curPosition) {
     return true;
   }
   if (pos == 0) {
     // set position to start of file
     m_curCluster = 0;
     goto done;
   }
   if (isFile()) {
     if (pos > m_validLength) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   // calculate cluster index for new position
   nNew = (pos - 1) >> m_vol->bytesPerClusterShift();
   if (isContiguous()) {
     m_curCluster = m_firstCluster + nNew;
     goto done;
   }
   // calculate cluster index for current position
   nCur = (m_curPosition - 1) >> m_vol->bytesPerClusterShift();
   if (nNew < nCur || m_curPosition == 0) {
     // must follow chain from first cluster
     m_curCluster = isRoot() ? m_vol->rootDirectoryCluster() : m_firstCluster;
   } else {
     // advance from curPosition
     nNew -= nCur;
   }
   while (nNew--) {
     if (m_vol->fatGet(m_curCluster, &m_curCluster) <= 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
 done:
   m_curPosition = pos;
   return true;
 fail:
   m_curCluster = tmp;
   return false;
 }
References ExFatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, ExFatFile::isContiguous(), ExFatFile::isFile(), ExFatFile::isOpen(), ExFatFile::isRoot(), and ExFatPartition::rootDirectoryCluster().
Referenced by ExFatFile::open(), ExFatFile::rewind(), ExFatFile::seekCur(), ExFatFile::seekEnd(), ExFatFile::truncate(), and ExFatFile::write().
size()
uint64_t StreamFile< ExFatFile , uint64_t >::size () inline inherited
Returns
the file's size.
Definition at line 132 of file ArduinoFiles.h.
                  {
     return BaseFile::fileSize();
   }
sync()
bool ExFatFile::sync () inherited
The sync() call causes all modified data and directory fields to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 382 of file ExFatFileWrite.cpp.
                      {
   if (!isOpen()) {
     return true;
   }
   if (m_flags & FILE_FLAG_DIR_DIRTY) {
     // clear directory dirty
     m_flags &= ~FILE_FLAG_DIR_DIRTY;
     return syncDir();
   }
   if (!m_vol->cacheSync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   m_error |= WRITE_ERROR;
   return false;
 }
References DBG_FAIL_MACRO, and ExFatFile::isOpen().
Referenced by ExFatFile::close(), ExFatFile::flush(), ExFatFile::preAllocate(), ExFatFile::rename(), ExFatFile::timestamp(), and ExFatFile::truncate().
timestamp()
bool ExFatFile::timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second) inherited
Truncate a file at the current file position.
Returns
true for success or false for failure. Set a file's timestamps in its directory entry.
Parameters
[in] flags Values for flags are constructed by a bitwise-inclusive OR of flags from the following list
T_ACCESS - Set the file's last access date.
T_CREATE - Set the file's creation date and time.
T_WRITE - Set the file's last write/modification date and time.
Parameters
[in] year Valid range 1980 - 2107 inclusive.
[in] month Valid range 1 - 12 inclusive.
[in] day Valid range 1 - 31 inclusive.
[in] hour Valid range 0 - 23 inclusive.
[in] minute Valid range 0 - 59 inclusive.
[in] second Valid range 0 - 59 inclusive
Note
It is possible to set an invalid date since there is no check for the number of days in a month.
Modify and access timestamps may be overwritten if a date time callback function has been set by dateTimeCallback().
Returns
true for success or false for failure.
Definition at line 481 of file ExFatFileWrite.cpp.
{
   DirFile_t* df;
   uint8_t* cache;
   uint16_t checksum = 0;
   uint8_t setCount = 0;
   uint16_t date;
   uint16_t time;
   uint8_t ms10;
   DirPos_t pos;
   if (!isFile()
       || year < 1980
       || year > 2107
       || month < 1
       || month > 12
       || day < 1
       || day > 31
       || hour > 23
       || minute > 59
       || second > 59) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // update directory entry
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   date = FS_DATE(year, month, day);
   time = FS_TIME(hour, minute, second);
   ms10 = second & 1 ? 100 : 0;
   pos = m_dirPos;
   for (uint8_t i = 0;; i++) {
     cache = m_vol->dirCache(&pos, FsCache::CACHE_FOR_READ);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     switch (cache[0]) {
       case EXFAT_TYPE_FILE:
         df = reinterpret_cast<DirFile_t*>(cache);
         setCount = df->setCount;
         setLe16(df->attributes, m_attributes & FILE_ATTR_COPY);
         m_vol->dataCacheDirty();
         if (flags & T_ACCESS) {
           setLe16(df->accessTime, time);
           setLe16(df->accessDate, date);
         }
         if (flags & T_CREATE) {
           df->createTimeMs = ms10;
           setLe16(df->createTime, time);
           setLe16(df->createDate, date);
         }
         if (flags & T_WRITE) {
           df->modifyTimeMs = ms10;
           setLe16(df->modifyTime, time);
           setLe16(df->modifyDate, date);
         }
         break;
       case EXFAT_TYPE_STREAM:
         break;
       case EXFAT_TYPE_NAME:
         break;
       default:
         DBG_FAIL_MACRO;
         goto fail;
         break;
     }
     checksum = exFatDirChecksum(cache, checksum);
     if (i == setCount) break;
     if (m_vol->dirSeek(&pos, 32) != 1) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   df = reinterpret_cast<DirFile_t *>
        (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_WRITE));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   setLe16(df->setChecksum, checksum);
   if (!m_vol->cacheSync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, ExFatFile::isFile(), and ExFatFile::sync().
truncate() [1/2]
bool ExFatFile::truncate () inherited
Truncate a file at the current file position. will be maintained if it is less than or equal to length otherwise it will be set to end of file.
Returns
true for success or false for failure.
Definition at line 579 of file ExFatFileWrite.cpp.
{
   uint32_t toFree;
   // error if not a normal file or read-only
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (m_firstCluster == 0) {
       return true;
   }
   if (isContiguous()) {
     uint32_t nc = 1 + ((m_dataLength - 1) >> m_vol->bytesPerClusterShift());
     if (m_curCluster) {
       toFree = m_curCluster + 1;
       nc -= 1 + m_curCluster - m_firstCluster;
     } else {
       toFree = m_firstCluster;
       m_firstCluster = 0;
     }
     if (nc && !m_vol->bitmapModify(toFree, nc, 0)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } else {
     // need to free chain
     if (m_curCluster) {
       toFree = 0;
       int8_t fg = m_vol->fatGet(m_curCluster, &toFree);
       if (fg < 0) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       if (fg) {
         // current cluster is end of chain
         if (!m_vol->fatPut(m_curCluster, EXFAT_EOC)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
     } else {
       toFree = m_firstCluster;
       m_firstCluster = 0;
     }
     if (toFree) {
       if (!m_vol->freeChain(toFree)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   }
   m_dataLength = m_curPosition;
   m_validLength = m_curPosition;
   m_flags |= FILE_FLAG_DIR_DIRTY;
   return sync();
  fail:
   return false;
 }
References ExFatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, EXFAT_EOC, ExFatFile::isContiguous(), ExFatFile::isWritable(), and ExFatFile::sync().
Referenced by ExFatVolume::truncate(), and ExFatFile::truncate().
truncate() [2/2]
bool ExFatFile::truncate (uint64_t length) inline inherited
Truncate a file to a specified length. The current file position will be set to end of file.
Parameters
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 635 of file ExFatFile.h.
{
     return seekSet(length) && truncate();
   }
References ExFatFile::seekSet(), and ExFatFile::truncate().
validLength()
uint64_t ExFatFile::validLength () inline inherited
Returns
The valid number of bytes in a file.
Definition at line 640 of file ExFatFile.h.
 {return m_validLength;}
write() [1/4]
size_t ExFatFile::write (const char * str) inline inherited
Write a string to a file. Used by the Arduino Print class.
Parameters
[in] str Pointer to the string. Use getWriteError to check for errors.
Returns
count of characters written for success or -1 for failure.
Definition at line 646 of file ExFatFile.h.
{
     return write(str, strlen(str));
   }
Referenced by ExFatFile::printField().
write() [2/4]
size_t StreamFile< ExFatFile , uint64_t >::write (const uint8_t * buffer, size_t size) inline inherited
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buffer Pointer to the location of the data to be written.
[in] size Number of bytes to write.
Returns
For success write() returns the number of bytes written, always size.
Definition at line 155 of file ArduinoFiles.h.
{
     return BaseFile::write(buffer, size);
   }
write() [3/4]
size_t ExFatFile::write (const void * buf, size_t count) inherited
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buf Pointer to the location of the data to be written.
[in] count Number of bytes to write.
Returns
For success write() returns the number of bytes written, always count.
Definition at line 638 of file ExFatFileWrite.cpp.
{
   // convert void* to uint8_t*  -  must be before goto statements
   const uint8_t* src = reinterpret_cast<const uint8_t*>(buf);
   uint8_t* cache;
   uint8_t cacheOption;
   uint16_t sectorOffset;
   uint32_t sector;
   uint32_t clusterOffset;
   // number of bytes left to write  -  must be before goto statements
   size_t toWrite = nbyte;
   size_t n;
   // error if not an open file or is read-only
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // seek to end of file if append flag
   if ((m_flags & FILE_FLAG_APPEND)) {
     if (!seekSet(m_validLength)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   while (toWrite) {
     clusterOffset = m_curPosition & m_vol->clusterMask();
     sectorOffset = clusterOffset & m_vol->sectorMask();
     if (clusterOffset == 0) {
       // start of new cluster
       if (m_curCluster != 0) {
         int fg;
         if (isContiguous()) {
           uint32_t lc = m_firstCluster;
           lc += (m_dataLength - 1) >> m_vol->bytesPerClusterShift();
           if (m_curCluster < lc) {
             m_curCluster++;
             fg = 1;
           } else {
             fg = 0;
           }
         } else {
           fg = m_vol->fatGet(m_curCluster, &m_curCluster);
           if (fg < 0) {
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
         if (fg == 0) {
           // add cluster if at end of chain
           if (!addCluster()) {
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
       } else {
         if (m_firstCluster == 0) {
           // allocate first cluster of file
           if (!addCluster()) {
             DBG_FAIL_MACRO;
             goto fail;
           }
           m_firstCluster = m_curCluster;
         } else {
           m_curCluster = m_firstCluster;
         }
       }
     }
     // sector for data write
     sector = m_vol->clusterStartSector(m_curCluster) +
              (clusterOffset >> m_vol->bytesPerSectorShift());
     if (sectorOffset != 0 || toWrite < m_vol->bytesPerSector()) {
       // partial sector - must use cache
       // max space in sector
       n = m_vol->bytesPerSector() - sectorOffset;
       // lesser of space and amount to write
       if (n > toWrite) {
         n = toWrite;
       }
       if (sectorOffset == 0 && m_curPosition >= m_validLength) {
         // start of new sector don't need to read into cache
         cacheOption = FsCache::CACHE_RESERVE_FOR_WRITE;
       } else {
         // rewrite part of sector
         cacheOption = FsCache::CACHE_FOR_WRITE;
       }
       cache = m_vol->dataCacheGet(sector, cacheOption);
       if (!cache) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       uint8_t* dst = cache + sectorOffset;
       memcpy(dst, src, n);
       if (m_vol->bytesPerSector() == (n + sectorOffset)) {
         // Force write if sector is full - improves large writes.
         if (!m_vol->dataCacheSync()) {
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
 #if USE_MULTI_SECTOR_IO
     } else if (toWrite >= 2*m_vol->bytesPerSector()) {
       // use multiple sector write command
       uint32_t ns = toWrite >> m_vol->bytesPerSectorShift();
       // Limit writes to current cluster.
       uint32_t maxNs = m_vol->sectorsPerCluster()
                        - (clusterOffset >> m_vol->bytesPerSectorShift());
       if (ns > maxNs) {
         ns = maxNs;
       }
       n = ns << m_vol->bytesPerSectorShift();
       // Check for cache sector in write range.
       if (sector <= m_vol->dataCacheSector()
           && m_vol->dataCacheSector() < (sector + ns)) {
         // Invalidate cache if cache sector is in the range.
         m_vol->dataCacheInvalidate();
       }
       if (!m_vol->writeSectors(sector, src, ns)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
 #endif  // USE_MULTI_SECTOR_IO
     } else {
       // use single sector write command
       n = m_vol->bytesPerSector();
       if (m_vol->dataCacheSector() == sector) {
         m_vol->dataCacheInvalidate();
       }
       if (!m_vol->writeSector(sector, src)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_curPosition += n;
     src += n;
     toWrite -= n;
     if (m_curPosition > m_validLength) {
       m_flags |= FILE_FLAG_DIR_DIRTY;
       m_validLength = m_curPosition;
     }
   }
   if (m_curPosition > m_dataLength) {
     m_dataLength = m_curPosition;
     // update fileSize and insure sync will update dir entr
     m_flags |= FILE_FLAG_DIR_DIRTY;
   } else if (FsDateTime::callback) {
     // insure sync will update modified date and time
     m_flags |= FILE_FLAG_DIR_DIRTY;
   }
   return nbyte;
 fail:
   // return for write error
   m_error |= WRITE_ERROR;
   return -1;
 }
References ExFatPartition::bytesPerClusterShift(), ExFatPartition::bytesPerSector(), ExFatPartition::bytesPerSectorShift(), FsCache::CACHE_FOR_WRITE, FsCache::CACHE_RESERVE_FOR_WRITE, FsDateTime::callback, DBG_FAIL_MACRO, ExFatFile::isContiguous(), ExFatFile::isWritable(), ExFatPartition::sectorsPerCluster(), and ExFatFile::seekSet().
write() [4/4]
size_t StreamFile< ExFatFile , uint64_t >::write (uint8_t b) inline inherited
Write a byte to a file. Required by the Arduino Print class.
Parameters
[in] b the byte to be written. Use getWriteError to check for errors.
Returns
1 for success and 0 for failure.
Definition at line 140 of file ArduinoFiles.h.
{
     return BaseFile::write(b);
   }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/ExFatFile.h