ERIS CORE: erisAudioAnalyzeFFT1024::enableFFT
enableFFT()
void erisAudioAnalyzeFFT1024::enableFFT (bool enable_state) inline
Definition at line 124 of file eris_analyze_fft1024.h.
{
         reset();
         enabled = enable_state;
     }
References enabled, and reset().
Referenced by AppCQT::init(), AppCQT::onFocus(), and AppCQT::onFocusLost().