ERIS CORE: erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin
sort_fftrr_by_cqt_bin()
static void erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin (FFTReadRange * a, size_t n) inline static
Definition at line 319 of file eris_analyze_fft1024.h.
{
         //helper function used to sort FFTReadRange arrays (used for CQT)
         qsort(a, n, sizeof(*a), compare_fftrr_cqt_bin);
     }
References compare_fftrr_cqt_bin().
Referenced by AppCQT::messageHandler(), AppCQT::render(), and AppCQT::updateOscillatorBank().