ERIS CORE: erisAudioAnalyzeFFT1024::analyze
analyze()
void erisAudioAnalyzeFFT1024::analyze (void)
Definition at line 143 of file eris_analyze_fft1024.cpp.
 {
     float p;
     if (is_analyzed) return;
     //(NVIC_DISABLE_IRQ(IRQ_SOFTWARE));
     apply_window_to_fft_buffer_f32((float32_t*)tmp_buffer, window_f32);
     arm_fill_f32(0,(float32_t*)&tmp_buffer[1024],1024);
     arm_cfft_radix4_f32(&fft_inst, (float32_t*)tmp_buffer);
     //extract the polar phase from the interleaved real and imag
     for(int16_t i=0;i < 1024;i+=2){
         p = normalized_atan2(tmp_buffer[i],tmp_buffer[i+1]);
         if (!std::isfinite(p)) p = 0;
         phase[i/2] = 360.0 * (p/4.0);
     }
     // Process the data through the Complex Magnitude Module for calculating the magnitude at each bin
     arm_cmplx_mag_f32((float32_t*)tmp_buffer, (float32_t*)output, 1024);
     //(NVIC_ENABLE_IRQ(IRQ_SOFTWARE));
     //spectralFilter();
     outputflag = false; //current frame is analyzed and ready to use
     is_analyzed = true;
     return;
 }
References apply_window_to_fft_buffer_f32(), fft_inst, is_analyzed, normalized_atan2(), outputflag, p, and window_f32.
Referenced by AppCQT::update().