ERIS CORE: erisAudioAnalyzeFFT1024::update
update()
void erisAudioAnalyzeFFT1024::update (void) virtual
Implements AudioStream.
Definition at line 178 of file eris_analyze_fft1024.cpp.
 {
     audio_block_t *block;
     block = receiveReadOnly();
     if (!block) return;
     //FAT Audio - add the ability to turn FFT on or OFF to save CPU
     if (!enabled){
         release(block);
         return;
     };
     uint16_t ofs;
     //calcuate active subsampling step and offset
     if (ssr == SS_LOWFREQ){
         MEM_STEP = subsample_lowfreqrange;
         subsample_by = (int)subsample_lowfreqrange;
     }
     else if (ssr == SS_HIGHFREQ){
         MEM_STEP = subsample_highfreqrange;
         subsample_by = (int)subsample_highfreqrange;
     }
     BLOCKS_PER_FFT = ((1024 / AUDIO_BLOCK_SAMPLES) * subsample_by);
     BLOCK_REFRESH_SIZE = BLOCKS_PER_FFT/16;
     if (ssr == SS_LOWFREQ) BLOCK_REFRESH_SIZE = BLOCKS_PER_FFT/8;//((subsample_lowfreqrange/subsample_highfreqrange) * 2);//BLOCK_REFRESH_SIZE/(subsample_lowfreqrange/2);//BLOCKS_PER_FFT/4;
     ofs = (AUDIO_BLOCK_SAMPLES/subsample_by) * (sample_block);
     if (sample_block < BLOCKS_PER_FFT -1){
         copy_to_fft_buffer(buffer+ofs, block->data,subsample_by);
         release(block);
         sample_block++;
     } else{
         copy_to_fft_buffer(buffer+ofs, block->data,subsample_by);
         release(block);
         #ifdef ENABLE_F32_FFT
         //copy buffer while casting to float and scale to the range -1 to 1
         //(NVIC_DISABLE_IRQ(IRQ_SOFTWARE));
         if(outputflag == false && is_analyzed){
             for (int16_t i=0; i < 1024; i++){
                 tmp_buffer[i] = ((float32_t)buffer[i] / (float32_t)32768.0);
                 //if (SS_LOWFREQ) tmp_buffer[i] *= subsample_lowfreqrange/(float32_t)subsample_highfreqrange; //scale match the low range
                 if (!std::isfinite(tmp_buffer[i])) tmp_buffer[i] = 0.0;
             }
             outputflag = true;
         }
         //(NVIC_ENABLE_IRQ(IRQ_SOFTWARE));
         #else
         memcpy(tmp_buffer,buffer,2048 * sizeof(int16_t));
         apply_window_to_fft_buffer(tmp_buffer, window);
         arm_cfft_radix4_q15(&fft_inst, tmp_buffer);
         outputflag = false; //output flag is false while updating the fft results
         for (int i=0; i < 512; i++) {
             uint32_t tmp = *((uint32_t *)tmp_buffer + i); // real & imag
             uint32_t magsq = multiply_16tx16t_add_16bx16b(tmp, tmp);
             output[i] = sqrt_uint32_approx(magsq);
             output_packed[i] = tmp;//normalized_atan2((float)real,(float)imag)*180/PI;//atan2(imag,real)*180/PI;
         }
         #endif
         if (sample_block!= 0){
             sample_block = BLOCKS_PER_FFT - BLOCK_REFRESH_SIZE;
             ofs = (AUDIO_BLOCK_SAMPLES/subsample_by) * sample_block;
             //fft overlap - restore tmp cpy of last half to first half
             memmove(buffer,&buffer[(AUDIO_BLOCK_SAMPLES/subsample_by)*BLOCK_REFRESH_SIZE], (AUDIO_BLOCK_SAMPLES/subsample_by) * (BLOCKS_PER_FFT - BLOCK_REFRESH_SIZE) * sizeof(int16_t));
         }
     }
 }
References apply_window_to_fft_buffer(), BLOCK_REFRESH_SIZE, BLOCKS_PER_FFT, copy_to_fft_buffer(), audio_block_struct::data, enabled, fft_inst, is_analyzed, MEM_STEP, outputflag, AudioStream::receiveReadOnly(), AudioStream::release(), sample_block, SS_HIGHFREQ, SS_LOWFREQ, ssr, subsample_by, subsample_highfreqrange, subsample_lowfreqrange, and window.