ERIS CORE: obufstream Class Reference
obufstream Class Reference
format a char string
#include <bufstream.h>
Public Types
typedef unsigned int fmtflags
typedef unsigned char iostate
typedef int64_t off_type
typedef uint8_t openmode
typedef uint64_t pos_type
enum seekdir { beg , cur , end }
typedef uint64_t streamsize
Public Member Functions
obufstream ()
obufstream (char *buf, size_t size)
bool bad () const
char * buf ()
void clear (iostate state=goodbit)
bool eof () const
bool fail () const
char fill ()
char fill (char c)
fmtflags flags () const
fmtflags flags (fmtflags fl)
ostream & flush ()
bool good () const
void init (char *buf, size_t size)
size_t length ()
operator bool () const
operator const void * () const
bool operator! () const
ostream & operator<< (bool arg)
ostream & operator<< (char arg)
ostream & operator<< (const __FlashStringHelper *arg)
ostream & operator<< (const char *arg)
ostream & operator<< (const signed char *arg)
ostream & operator<< (const unsigned char *arg)
ostream & operator<< (const void *arg)
ostream & operator<< (double arg)
ostream & operator<< (float arg)
ostream & operator<< (int arg)
ostream & operator<< (ios_base &(*pf)(ios_base &str))
ostream & operator<< (long arg)
ostream & operator<< (long long arg)
ostream & operator<< (ostream &(*pf)(ostream &str))
ostream & operator<< (short arg)
ostream & operator<< (signed char arg)
ostream & operator<< (unsigned char arg)
ostream & operator<< (unsigned int arg)
ostream & operator<< (unsigned long arg)
ostream & operator<< (unsigned long long arg)
ostream & operator<< (unsigned short arg)
int precision () const
int precision (unsigned int n)
ostream & put (char ch)
iostate rdstate () const
ostream & seekp (off_type off, seekdir way)
ostream & seekp (pos_type pos)
fmtflags setf (fmtflags fl)
fmtflags setf (fmtflags fl, fmtflags mask)
void setstate (iostate state)
pos_type tellp ()
void unsetf (fmtflags fl)
unsigned width ()
unsigned width (unsigned n)
Static Public Attributes
static const fmtflags adjustfield = left | right | internal
static const openmode app = 0X4
static const openmode ate = 0X8
static const iostate badbit = 0X01
static const fmtflags basefield = dec | hex | oct
static const openmode binary = 0X10
static const fmtflags boolalpha = 0x0100
static const fmtflags dec = 0x0008
static const iostate eofbit = 0x02
static const iostate failbit = 0X04
static const iostate goodbit = 0x00
static const fmtflags hex = 0x0010
static const openmode in = 0X20
static const fmtflags internal = 0x0004
static const fmtflags left = 0x0001
static const fmtflags oct = 0x0020
static const openmode out = 0X40
static const fmtflags right = 0x0002
static const fmtflags showbase = 0x0200
static const fmtflags showpoint = 0x0400
static const fmtflags showpos = 0x0800
static const fmtflags skipws = 0x1000
static const openmode trunc = 0X80
static const fmtflags uppercase = 0x4000
Protected Member Functions
uint8_t flagsToBase ()
Private Member Functions
void do_fill (unsigned len)
void fill_not_left (unsigned len)
template<typename T >
char * fmtNum (T n, char *ptr, uint8_t base)
void putBool (bool b)
void putChar (char c)
void putDouble (double n)
void putNum (int32_t n)
void putNum (int64_t n)
template<typename T >
void putNum (T n, bool neg)
void putNum (uint32_t n)
void putNum (uint64_t n)
void putPgm (const char *str)
void putStr (const char *str)
Private Attributes
char * m_buf = nullptr
char m_fill
fmtflags m_fmtflags
size_t m_in = 0
iostate m_iostate = 0
unsigned char m_precision
size_t m_size = 0
unsigned int m_width
Detailed Description
format a char string
Definition at line 101 of file bufstream.h.
Member Typedef Documentation
fmtflags
typedef unsigned int ios_base::fmtflags inherited
type for format flags
Definition at line 94 of file ios.h.
iostate
typedef unsigned char ios_base::iostate inherited
typedef for iostate bitmask
Definition at line 53 of file ios.h.
off_type
typedef int64_t ios_base::off_type inherited
type for relative seek offset
Definition at line 82 of file ios.h.
openmode
typedef uint8_t ios_base::openmode inherited
typedef for iostream open mode
Definition at line 129 of file ios.h.
pos_type
typedef uint64_t ios_base::pos_type inherited
type for absolute seek position
Definition at line 80 of file ios.h.
streamsize
typedef uint64_t ios_base::streamsize inherited
unsigned size that can represent maximum file size. (violates spec - should be signed)
Definition at line 78 of file ios.h.
Member Enumeration Documentation
seekdir
enum ios_base::seekdir inherited
enumerated type for the direction of relative seeks
Enumerator
beg
seek relative to the beginning of the stream
cur
seek relative to the current stream position
end
seek relative to the end of the stream
Definition at line 85 of file ios.h.
                {
     beg,
     cur,
     end
   };
Constructor & Destructor Documentation
obufstream() [1/2]
obufstream::obufstream () inline
constructor
Definition at line 104 of file bufstream.h.
 {}
obufstream() [2/2]
obufstream::obufstream (char * buf, size_t size) inline
Constructor
Parameters
[in] buf buffer for formatted string
[in] size buffer size
Definition at line 109 of file bufstream.h.
{
     init(buf, size);
   }
References buf(), and init().
Member Function Documentation
bad()
bool ios::bad () const inline inherited
Returns
true if bad bit is set else false.
Definition at line 427 of file ios.h.
                    {
     return m_iostate & badbit;
   }
References ios_base::badbit, and ios::m_iostate.
Referenced by istream::peek().
buf()
char* obufstream::buf () inline
Returns
a pointer to the buffer
Definition at line 123 of file bufstream.h.
               {
     return m_buf;
   }
References m_buf.
Referenced by obufstream(), and init().
clear()
void ios::clear (iostate state = goodbit) inline inherited
Clear iostate bits.
Parameters
[in] state The flags you want to set after clearing all flags.
Definition at line 434 of file ios.h.
{
     m_iostate = state;
   }
References ios::m_iostate.
Referenced by ibufstream::init(), and StreamBaseClass::open().
do_fill()
void ostream::do_fill (unsigned len) private inherited
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 31 of file ostream.cpp.
{
   for (; len < width(); len++) {
     putch(fill());
   }
   width(0);
 }
References ios_base::fill(), and ios_base::width().
Referenced by ostream::fill_not_left(), ostream::putChar(), ostream::putDouble(), ostream::putPgm(), and ostream::putStr().
eof()
bool ios::eof () const inline inherited
Returns
true if end of file has been reached else false.
Warning: An empty file returns false before the first read.
Moral: eof() is only useful in combination with fail(), to find out whether EOF was the cause for failure
Definition at line 419 of file ios.h.
                    {
     return m_iostate & eofbit;
   }
References ios_base::eofbit, and ios::m_iostate.
fail()
bool ios::fail () const inline inherited
Returns
true if any iostate bit other than eof are set else false.
Definition at line 423 of file ios.h.
                     {
     return m_iostate & (failbit | badbit);
   }
References ios_base::badbit, ios_base::failbit, and ios::m_iostate.
Referenced by istream::getDouble(), StreamBaseClass::open(), ios::operator bool(), ios::operator const void *(), and ios::operator!().
fill() [1/2]
char ios_base::fill () inline inherited
Returns
fill character
Definition at line 148 of file ios.h.
               {
     return m_fill;
   }
Referenced by ostream::do_fill(), operator<<(), and operator>>().
fill() [2/2]
char ios_base::fill (char c) inline inherited
Set fill character
Parameters
[in] c new fill character
Returns
old fill character
Definition at line 155 of file ios.h.
                     {
     char r = m_fill;
     m_fill = c;
     return r;
   }
fill_not_left()
void ostream::fill_not_left (unsigned len) private inherited
Definition at line 38 of file ostream.cpp.
{
   if ((flags() & adjustfield) != left) {
     do_fill(len);
   }
 }
References ios_base::adjustfield, ostream::do_fill(), ios_base::flags(), and ios_base::left.
Referenced by ostream::putChar(), ostream::putDouble(), ostream::putPgm(), and ostream::putStr().
flags() [1/2]
fmtflags ios_base::flags () const inline inherited
Returns
format flags
Definition at line 161 of file ios.h.
{
     return m_fmtflags;
   }
Referenced by ostream::fill_not_left(), istream::getBool(), istream::getNumber(), ostream::putBool(), ostream::putDouble(), and istream::readSkip().
flags() [2/2]
fmtflags ios_base::flags (fmtflags fl) inline inherited
set format flags
Parameters
[in] fl new flag
Returns
old flags
Definition at line 168 of file ios.h.
{
     fmtflags tmp = m_fmtflags;
     m_fmtflags = fl;
     return tmp;
   }
flagsToBase()
uint8_t ios_base::flagsToBase () inline protected inherited
Returns
current number base
Definition at line 228 of file ios.h.
{
     uint8_t f = flags() & basefield;
     return f == oct ? 8 : f != hex ? 10 : 16;
   }
References hex(), and oct().
Referenced by ostream::putNum().
flush()
ostream& ostream::flush () inline inherited
Flushes the buffer associated with this stream. The flush function calls the sync function of the associated file.
Returns
A reference to the ostream object.
Definition at line 237 of file ostream.h.
                    {
     if (!sync()) {
       setstate(badbit);
     }
     return *this;
   }
Referenced by endl(), and flush().
fmtNum()
template<typename T > char* ostream::fmtNum (T n, char * ptr, uint8_t base) inline private inherited
Definition at line 301 of file ostream.h.
{
     char a = flags() & uppercase ? 'A' - 10 : 'a' - 10;
     do {
       T m = n;
       n /= base;
       char c = m - base * n;
       *--ptr = c < 10 ? c + '0' : c + a;
     } while (n);
     return ptr;
   }
References m, and uppercase().
Referenced by ostream::putDouble().
good()
bool ios::good () const inline inherited
Returns
True if no iostate flags are set else false.
Definition at line 409 of file ios.h.
                     {
     return m_iostate == goodbit;
   }
References ios_base::goodbit, and ios::m_iostate.
init()
void obufstream::init (char * buf, size_t size) inline
Initialize an obufstream
Parameters
[in] buf buffer for formatted string
[in] size buffer size
Definition at line 116 of file bufstream.h.
{
     m_buf = buf;
     buf[0] = '\0';
     m_size = size;
     m_in = 0;
   }
References buf(), m_buf, m_in, and m_size.
Referenced by obufstream().
length()
size_t obufstream::length () inline
Returns
the length of the formatted string
Definition at line 127 of file bufstream.h.
                   {
     return m_in;
   }
References m_in.
operator bool()
ios::operator bool () const inline explicit inherited
Returns
false if fail() else true.
Definition at line 403 of file ios.h.
 {return !fail();}
References ios::fail().
operator const void *()
ios::operator const void * () const inline inherited
Returns
null pointer if fail() is true.
Definition at line 395 of file ios.h.
{
     return !fail() ? reinterpret_cast<const void*>(this) : nullptr;
   }
References ios::fail().
operator!()
bool ios::operator! () const inline inherited
Returns
true if fail() else false.
Definition at line 399 of file ios.h.
{
     return fail();
   }
References ios::fail().
operator<<() [1/21]
ostream& ostream::operator<< (bool arg) inline inherited
Output bool
Parameters
[in] arg value to output
Returns
the stream
Definition at line 60 of file ostream.h.
{
     putBool(arg);
     return *this;
   }
References ostream::putBool().
operator<<() [2/21]
ostream& ostream::operator<< (char arg) inline inherited
Output character
Parameters
[in] arg character to output
Returns
the stream
Definition at line 102 of file ostream.h.
{
     putChar(arg);
     return *this;
   }
operator<<() [3/21]
ostream& ostream::operator<< (const __FlashStringHelper * arg) inline inherited
Output a string from flash using the Arduino F() macro.
Parameters
[in] arg pointing to flash string
Returns
the stream
Definition at line 214 of file ostream.h.
{
     putPgm(reinterpret_cast<const char*>(arg));
     return *this;
   }
operator<<() [4/21]
ostream& ostream::operator<< (const char * arg) inline inherited
Output string
Parameters
[in] arg string to output
Returns
the stream
Definition at line 68 of file ostream.h.
{
     putStr(arg);
     return *this;
   }
References ostream::putStr().
operator<<() [5/21]
ostream& ostream::operator<< (const signed char * arg) inline inherited
Output string
Parameters
[in] arg string to output
Returns
the stream
Definition at line 76 of file ostream.h.
{
     putStr((const char*)arg);
     return *this;
   }
References ostream::putStr().
operator<<() [6/21]
ostream& ostream::operator<< (const unsigned char * arg) inline inherited
Output string
Parameters
[in] arg string to output
Returns
the stream
Definition at line 84 of file ostream.h.
{
     putStr((const char*)arg);
     return *this;
   }
References ostream::putStr().
operator<<() [7/21]
ostream& ostream::operator<< (const void * arg) inline inherited
Output pointer
Parameters
[in] arg value to output
Returns
the stream
Definition at line 206 of file ostream.h.
{
     putNum(reinterpret_cast<uint32_t>(arg));
     return *this;
   }
operator<<() [8/21]
ostream& ostream::operator<< (double arg) inline inherited
Output double
Parameters
[in] arg value to output
Returns
the stream
Definition at line 126 of file ostream.h.
{
     putDouble(arg);
     return *this;
   }
operator<<() [9/21]
ostream& ostream::operator<< (float arg) inline inherited
Output float
Parameters
[in] arg value to output
Returns
the stream
Definition at line 134 of file ostream.h.
{
     putDouble(arg);
     return *this;
   }
operator<<() [10/21]
ostream& ostream::operator<< (int arg) inline inherited
Output signed int
Parameters
[in] arg value to output
Returns
the stream
Definition at line 158 of file ostream.h.
{
     putNum((int32_t)arg);
     return *this;
   }
operator<<() [11/21]
ostream& ostream::operator<< (ios_base &(*)(ios_base &str) pf) inline inherited
call manipulator
Parameters
[in] pf function to call
Returns
the stream
Definition at line 52 of file ostream.h.
{
     pf(*this);
     return *this;
   }
operator<<() [12/21]
ostream& ostream::operator<< (long arg) inline inherited
Output signed long
Parameters
[in] arg value to output
Returns
the stream
Definition at line 174 of file ostream.h.
                                  {  // NOLINT
     putNum((int32_t)arg);
     return *this;
   }
operator<<() [13/21]
ostream& ostream::operator<< (long long arg) inline inherited
Output signed long long
Parameters
[in] arg value to output
Returns
the stream
Definition at line 190 of file ostream.h.
                                       {  // NOLINT
     putNum((int64_t)arg);
     return *this;
   }
operator<<() [14/21]
ostream& ostream::operator<< (ostream &(*)(ostream &str) pf) inline inherited
call manipulator
Parameters
[in] pf function to call
Returns
the stream
Definition at line 45 of file ostream.h.
{
     return pf(*this);
   }
operator<<() [15/21]
ostream& ostream::operator<< (short arg) inline inherited
Output signed short
Parameters
[in] arg value to output
Returns
the stream
Definition at line 142 of file ostream.h.
                                   {  // NOLINT
     putNum((int32_t)arg);
     return *this;
   }
operator<<() [16/21]
ostream& ostream::operator<< (signed char arg) inline inherited
Output character
Parameters
[in] arg character to output
Returns
the stream
Definition at line 110 of file ostream.h.
{
     putChar(static_cast<char>(arg));
     return *this;
   }
operator<<() [17/21]
ostream& ostream::operator<< (unsigned char arg) inline inherited
Output character
Parameters
[in] arg character to output
Returns
the stream
Definition at line 118 of file ostream.h.
{
     putChar(static_cast<char>(arg));
     return *this;
   }
operator<<() [18/21]
ostream& ostream::operator<< (unsigned int arg) inline inherited
Output unsigned int
Parameters
[in] arg value to output
Returns
the stream
Definition at line 166 of file ostream.h.
{
     putNum((uint32_t)arg);
     return *this;
   }
operator<<() [19/21]
ostream& ostream::operator<< (unsigned long arg) inline inherited
Output unsigned long
Parameters
[in] arg value to output
Returns
the stream
Definition at line 182 of file ostream.h.
                                           {  // NOLINT
     putNum((uint32_t)arg);
     return *this;
   }
operator<<() [20/21]
ostream& ostream::operator<< (unsigned long long arg) inline inherited
Output unsigned long long
Parameters
[in] arg value to output
Returns
the stream
Definition at line 198 of file ostream.h.
                                                {  // NOLINT
     putNum((uint64_t)arg);
     return *this;
   }
operator<<() [21/21]
ostream& ostream::operator<< (unsigned short arg) inline inherited
Output unsigned short
Parameters
[in] arg value to output
Returns
the stream
Definition at line 150 of file ostream.h.
                                            {  // NOLINT
     putNum((uint32_t)arg);
     return *this;
   }
precision() [1/2]
int ios_base::precision () const inline inherited
Returns
precision
Definition at line 174 of file ios.h.
{
     return m_precision;
   }
Referenced by operator<<(), operator>>(), and ostream::putDouble().
precision() [2/2]
int ios_base::precision (unsigned int n) inline inherited
set precision
Parameters
[in] n new precision
Returns
old precision
Definition at line 181 of file ios.h.
{
     int r = m_precision;
     m_precision = n;
     return r;
   }
put()
ostream& ostream::put (char ch) inline inherited
Puts a character in a stream.
The unformatted output function inserts the element ch. It returns *this.
Parameters
[in] ch The character
Returns
A reference to the ostream object.
Definition at line 227 of file ostream.h.
{
     putch(ch);
     return *this;
   }
Referenced by endl().
putBool()
void ostream::putBool (bool b) private inherited
Definition at line 44 of file ostream.cpp.
{
   if (flags() & boolalpha) {
     if (b) {
       putPgm(PSTR("true"));
     } else {
       putPgm(PSTR("false"));
     }
   } else {
     putChar(b ? '1' : '0');
   }
 }
References ios_base::boolalpha, ios_base::flags(), PSTR, ostream::putChar(), and ostream::putPgm().
Referenced by ostream::operator<<().
putChar()
void ostream::putChar (char c) private inherited
Definition at line 56 of file ostream.cpp.
{
   fill_not_left(1);
   putch(c);
   do_fill(1);
 }
References ostream::do_fill(), and ostream::fill_not_left().
Referenced by ostream::putBool().
putDouble()
void ostream::putDouble (double n) private inherited
Definition at line 62 of file ostream.cpp.
{
   uint8_t nd = precision();
   double round = 0.5;
   char sign;
   char buf[13];  // room for sign, 10 digits, '.', and zero byte
   char *ptr = buf + sizeof(buf) - 1;
   char *str = ptr;
   // terminate string
   *ptr = '\0';
   // get sign and make nonnegative
   if (n < 0.0) {
     sign = '-';
     n = -n;
   } else {
     sign = flags() & showpos ? '+' : '\0';
   }
   // check for larger than uint32_t
   if (n > 4.0E9) {
     putPgm(PSTR("BIG FLT"));
     return;
   }
   // round up and separate int and fraction parts
   for (uint8_t i = 0; i < nd; ++i) {
     round *= 0.1;
   }
   n += round;
   uint32_t intPart = n;
   double fractionPart = n - intPart;
   // format intPart and decimal point
   if (nd || (flags() & showpoint)) {
     *--str = '.';
   }
   str = fmtNum(intPart, str, 10);
   // calculate length for fill
   uint8_t len = sign ? 1 : 0;
   len += nd + ptr - str;
   // extract adjust field
   fmtflags adj = flags() & adjustfield;
   if (adj == internal) {
     if (sign) {
       putch(sign);
     }
     do_fill(len);
   } else {
     // do fill for right
     fill_not_left(len);
     if (sign) {
       *--str = sign;
     }
   }
   putstr(str);
   // output fraction
   while (nd-- > 0) {
     fractionPart *= 10.0;
     int digit = static_cast<int>(fractionPart);
     putch(digit + '0');
     fractionPart -= digit;
   }
   // do fill if not done above
   do_fill(len);
 }
References ios_base::adjustfield, buf, ostream::do_fill(), ostream::fill_not_left(), ios_base::flags(), ostream::fmtNum(), ios_base::precision(), PSTR, ostream::putPgm(), ios_base::showpoint, and ios_base::showpos.
putNum() [1/5]
void ostream::putNum (int32_t n) private inherited
Definition at line 128 of file ostream.cpp.
{
   bool neg = n < 0 && flagsToBase() == 10;
   putNum((uint32_t)(neg ? -n : n), neg);
 }
References ios_base::flagsToBase().
Referenced by ostream::putNum().
putNum() [2/5]
void ostream::putNum (int64_t n) private inherited
Definition at line 133 of file ostream.cpp.
{
   bool neg = n < 0 && flagsToBase() == 10;
   putNum((uint64_t)(neg ? -n : n), neg);
 }
References ios_base::flagsToBase(), and ostream::putNum().
putNum() [3/5]
template<typename T > void ostream::putNum (T n, bool neg) inline private inherited
Definition at line 313 of file ostream.h.
{
     char buf[(8*sizeof(T) + 2)/3 + 2];
     char* ptr = buf + sizeof(buf) - 1;
     char* num;
     char* str;
     uint8_t base = flagsToBase();
     *ptr = '\0';
     str = num = fmtNum(n, ptr, base);
     if (base == 10) {
       if (neg) {
         *--str = '-';
       } else if (flags() & showpos) {
         *--str = '+';
       }
     } else if (flags() & showbase) {
       if (flags() & hex) {
         *--str = flags() & uppercase ? 'X' : 'x';
       }
       *--str = '0';
     }
     uint8_t len = ptr - str;
     fmtflags adj = flags() & adjustfield;
     if (adj == internal) {
       while (str < num) {
         putch(*str++);
       }
       do_fill(len);
     } else {
       // do fill for right
       fill_not_left(len);
     }
     putstr(str);
     do_fill(len);
   }
References buf, hex(), showbase(), showpos(), and uppercase().
putNum() [4/5]
void ostream::putNum (uint32_t n) inline private inherited
Definition at line 295 of file ostream.h.
 {putNum(n, false);}
References ostream::putNum().
Referenced by ostream::putNum().
putNum() [5/5]
void ostream::putNum (uint64_t n) inline private inherited
Definition at line 296 of file ostream.h.
 {putNum(n, false);}
References ostream::putNum().
Referenced by ostream::putNum().
putPgm()
void ostream::putPgm (const char * str) private inherited
Definition at line 138 of file ostream.cpp.
{
   int n;
   for (n = 0; pgm_read_byte(&str[n]); n++) {}
   fill_not_left(n);
   for (uint8_t c; (c = pgm_read_byte(str)); str++) {
     putch(c);
   }
   do_fill(n);
 }
References ostream::do_fill(), ostream::fill_not_left(), and pgm_read_byte.
Referenced by ostream::putBool(), and ostream::putDouble().
putStr()
void ostream::putStr (const char * str) private inherited
Definition at line 148 of file ostream.cpp.
{
   unsigned n = strlen(str);
   fill_not_left(n);
   putstr(str);
   do_fill(n);
 }
References ostream::do_fill(), and ostream::fill_not_left().
Referenced by ostream::operator<<().
rdstate()
iostate ios::rdstate () const inline inherited
Returns
The iostate flags for this file.
Definition at line 405 of file ios.h.
{
     return m_iostate;
   }
References ios::m_iostate.
seekp() [1/2]
ostream& ostream::seekp (off_type off, seekdir way) inline inherited
Set the stream position.
Parameters
[in] off An offset to move the write pointer relative to way. off is a signed 32-bit int so the offset is limited to +- 2GB.
[in] way One of ios::beg, ios::cur, or ios::end.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 268 of file ostream.h.
{
     if (!seekoff(off, way)) {
       setstate(failbit);
     }
     return *this;
   }
seekp() [2/2]
ostream& ostream::seekp (pos_type pos) inline inherited
Set the stream position
Parameters
[in] pos The absolute position in which to move the write pointer.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 254 of file ostream.h.
{
     if (!seekpos(pos)) {
       setstate(failbit);
     }
     return *this;
   }
setf() [1/2]
fmtflags ios_base::setf (fmtflags fl) inline inherited
set format flags
Parameters
[in] fl new flags to be or'ed in
Returns
old flags
Definition at line 190 of file ios.h.
{
     fmtflags r = m_fmtflags;
     m_fmtflags |= fl;
     return r;
   }
Referenced by boolalpha(), dec(), hex(), internal(), left(), oct(), right(), showbase(), showpoint(), showpos(), skipws(), and uppercase().
setf() [2/2]
fmtflags ios_base::setf (fmtflags fl, fmtflags mask) inline inherited
modify format flags
Parameters
[in] mask flags to be removed
[in] fl flags to be set after mask bits have been cleared
Returns
old flags
Definition at line 200 of file ios.h.
{
     fmtflags r = m_fmtflags;
     m_fmtflags &= ~mask;
     m_fmtflags |= fl;
     return r;
   }
setstate()
void ios::setstate (iostate state) inline inherited
Set iostate bits.
Parameters
[in] state Bitts to set.
Definition at line 441 of file ios.h.
{
     m_iostate |= state;
   }
References ios::m_iostate.
Referenced by istream::get(), istream::getBool(), StreamBaseClass::getch(), istream::getChar(), istream::getDouble(), istream::getline(), istream::getStr(), StreamBaseClass::open(), istream::peek(), StreamBaseClass::putch(), StreamBaseClass::putstr(), ArduinoInStream::readline(), and istream::seekg().
tellp()
pos_type ostream::tellp () inline inherited
Returns
the stream position
Definition at line 246 of file ostream.h.
                    {
     return tellpos();
   }
unsetf()
void ios_base::unsetf (fmtflags fl) inline inherited
clear format flags
Parameters
[in] fl flags to be cleared
Definition at line 209 of file ios.h.
{
     m_fmtflags &= ~fl;
   }
Referenced by noboolalpha(), noshowbase(), noshowpoint(), noshowpos(), noskipws(), and nouppercase().
width() [1/2]
unsigned ios_base::width () inline inherited
Returns
width
Definition at line 213 of file ios.h.
                    {
     return m_width;
   }
Referenced by ostream::do_fill(), istream::getStr(), operator<<(), and operator>>().
width() [2/2]
unsigned ios_base::width (unsigned n) inline inherited
set width
Parameters
[in] n new width
Returns
old width
Definition at line 220 of file ios.h.
{
     unsigned r = m_width;
     m_width = n;
     return r;
   }
Member Data Documentation
adjustfield
const fmtflags ios_base::adjustfield = left | right | internal static inherited
mask for adjustfield
Definition at line 123 of file ios.h.
Referenced by ostream::fill_not_left(), internal(), left(), ostream::putDouble(), and right().
app
const openmode ios_base::app = 0X4 static inherited
seek to end before each write
Definition at line 133 of file ios.h.
Referenced by StreamBaseClass::open().
ate
const openmode ios_base::ate = 0X8 static inherited
open and seek to end immediately after opening
Definition at line 135 of file ios.h.
Referenced by StreamBaseClass::open().
badbit
const iostate ios_base::badbit = 0X01 static inherited
iostate bad bit for a nonrecoverable error.
Definition at line 58 of file ios.h.
Referenced by ios::bad(), ios::fail(), StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
basefield
const fmtflags ios_base::basefield = dec | hex | oct static inherited
mask for basefield
Definition at line 125 of file ios.h.
Referenced by dec(), istream::getNumber(), hex(), and oct().
binary
const openmode ios_base::binary = 0X10 static inherited
perform input and output in binary mode (as opposed to text mode)
Definition at line 137 of file ios.h.
Referenced by StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
boolalpha
const fmtflags ios_base::boolalpha = 0x0100 static inherited
use strings true/false for bool
Definition at line 110 of file ios.h.
Referenced by boolalpha(), istream::getBool(), noboolalpha(), and ostream::putBool().
dec
const fmtflags ios_base::dec = 0x0008 static inherited
base 10 flag
Definition at line 102 of file ios.h.
Referenced by dec().
eofbit
const iostate ios_base::eofbit = 0x02 static inherited
iostate bit for end of file reached
Definition at line 60 of file ios.h.
Referenced by ios::eof(), StreamBaseClass::getch(), and istream::peek().
failbit
const iostate ios_base::failbit = 0X04 static inherited
iostate fail bit for nonfatal error
Definition at line 62 of file ios.h.
Referenced by ios::fail(), istream::get(), istream::getBool(), istream::getChar(), istream::getDouble(), istream::getline(), istream::getStr(), StreamBaseClass::open(), ArduinoInStream::readline(), and istream::seekg().
goodbit
const iostate ios_base::goodbit = 0x00 static inherited
iostate for no flags
Definition at line 56 of file ios.h.
Referenced by ios::good().
hex
const fmtflags ios_base::hex = 0x0010 static inherited
base 16 flag
Definition at line 104 of file ios.h.
Referenced by istream::getNumber(), and hex().
in
const openmode ios_base::in = 0X20 static inherited
open for input
Definition at line 139 of file ios.h.
Referenced by StreamBaseClass::open().
internal
const fmtflags ios_base::internal = 0x0004 static inherited
fill between sign/base prefix and number
Definition at line 100 of file ios.h.
Referenced by internal().
left
const fmtflags ios_base::left = 0x0001 static inherited
left adjust fields
Definition at line 96 of file ios.h.
Referenced by ostream::fill_not_left(), and left().
m_buf
char* obufstream::m_buf = nullptr private
Definition at line 167 of file bufstream.h.
Referenced by buf(), and init().
m_fill
char ios_base::m_fill private inherited
Definition at line 234 of file ios.h.
m_fmtflags
fmtflags ios_base::m_fmtflags private inherited
Definition at line 235 of file ios.h.
m_in
size_t obufstream::m_in = 0 private
Definition at line 169 of file bufstream.h.
Referenced by init(), and length().
m_iostate
iostate ios::m_iostate = 0 private inherited
Definition at line 446 of file ios.h.
Referenced by ios::bad(), ios::clear(), ios::eof(), ios::fail(), ios::good(), ios::rdstate(), and ios::setstate().
m_precision
unsigned char ios_base::m_precision private inherited
Definition at line 236 of file ios.h.
m_size
size_t obufstream::m_size = 0 private
Definition at line 168 of file bufstream.h.
Referenced by init().
m_width
unsigned int ios_base::m_width private inherited
Definition at line 237 of file ios.h.
oct
const fmtflags ios_base::oct = 0x0020 static inherited
base 8 flag
Definition at line 106 of file ios.h.
Referenced by istream::getNumber(), and oct().
out
const openmode ios_base::out = 0X40 static inherited
open for output
Definition at line 141 of file ios.h.
Referenced by StreamBaseClass::open().
right
const fmtflags ios_base::right = 0x0002 static inherited
right adjust fields
Definition at line 98 of file ios.h.
Referenced by right().
showbase
const fmtflags ios_base::showbase = 0x0200 static inherited
use prefix 0X for hex and 0 for oct
Definition at line 112 of file ios.h.
Referenced by noshowbase(), and showbase().
showpoint
const fmtflags ios_base::showpoint = 0x0400 static inherited
always show '.' for floating numbers
Definition at line 114 of file ios.h.
Referenced by noshowpoint(), ostream::putDouble(), and showpoint().
showpos
const fmtflags ios_base::showpos = 0x0800 static inherited
show + sign for nonnegative numbers
Definition at line 116 of file ios.h.
Referenced by noshowpos(), ostream::putDouble(), and showpos().
skipws
const fmtflags ios_base::skipws = 0x1000 static inherited
skip initial white space
Definition at line 118 of file ios.h.
Referenced by noskipws(), istream::readSkip(), and skipws().
trunc
const openmode ios_base::trunc = 0X80 static inherited
truncate an existing stream when opening
Definition at line 143 of file ios.h.
Referenced by StreamBaseClass::open().
uppercase
const fmtflags ios_base::uppercase = 0x4000 static inherited
use uppercase letters in number representations
Definition at line 121 of file ios.h.
Referenced by nouppercase(), and uppercase().
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-master/src/iostream/bufstream.h