ERIS CORE: SysCall Class Reference
SysCall Class Reference
SysCall - Class to wrap system calls.
#include <SysCall.h>
Static Public Member Functions
static void halt ()
static void yield ()
Detailed Description
SysCall - Class to wrap system calls.
Definition at line 46 of file SysCall.h.
Member Function Documentation
halt()
static void SysCall::halt () inline static
Halt execution of this thread.
Definition at line 49 of file SysCall.h.
                      {
     while (1) {
       yield();
     }
   }
References yield().
Referenced by SdBase< Vol >::errorHalt(), and SdBase< Vol >::initErrorHalt().
yield()
void SysCall::yield () inline static
Yield to other threads.
Definition at line 94 of file SysCall.h.
 {}
Referenced by halt(), and ArduinoInStream::readline().
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/src/common/SysCall.h