ERIS CORE: StreamFile< BaseFile, PosType > Class Template Reference
StreamFile< BaseFile, PosType > Class Template Reference
StreamFile class.
#include <ArduinoFiles.h>
Public Member Functions
StreamFile ()
int available ()
void flush ()
bool isDirectory ()
const char * name () const
int peek ()
PosType position ()
int read ()
void rewindDirectory ()
bool seek (PosType pos)
PosType size ()
size_t write (const uint8_t *buffer, size_t size)
size_t write (uint8_t b)
Detailed Description
template<class BaseFile, typename PosType>
class StreamFile< BaseFile, PosType >
StreamFile class.
Definition at line 63 of file ArduinoFiles.h.
Constructor & Destructor Documentation
StreamFile()
template<class BaseFile , typename PosType > StreamFile< BaseFile, PosType >::StreamFile () inline
Definition at line 70 of file ArduinoFiles.h.
 {}
Member Function Documentation
available()
template<class BaseFile , typename PosType > int StreamFile< BaseFile, PosType >::available (void) inline
Returns
number of bytes available from the current position to EOF or INT_MAX if more than INT_MAX bytes are available.
Definition at line 75 of file ArduinoFiles.h.
                   {
     return BaseFile::available();
   }
Referenced by ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), and AppSerialCommandInterface::streamHandler().
flush()
template<class BaseFile , typename PosType > void StreamFile< BaseFile, PosType >::flush () inline
Ensure that any bytes written to the file are saved to the SD card.
Definition at line 79 of file ArduinoFiles.h.
                {
     BaseFile::sync();
   }
isDirectory()
template<class BaseFile , typename PosType > bool StreamFile< BaseFile, PosType >::isDirectory () inline
This function reports if the current file is a directory or not.
Returns
true if the file is a directory.
Definition at line 85 of file ArduinoFiles.h.
                      {
     return BaseFile::isDir();
   }
name()
template<class BaseFile , typename PosType > const char* StreamFile< BaseFile, PosType >::name () const inline
No longer implemented due to Long File Names.
Use getName(char* name, size_t size).
Returns
a pointer to replacement suggestion.
Definition at line 93 of file ArduinoFiles.h.
{
     return "use getName()";
   }
Referenced by cpplint._ClassInfo::CheckEnd(), and cpplint._NamespaceInfo::CheckEnd().
peek()
template<class BaseFile , typename PosType > int StreamFile< BaseFile, PosType >::peek () inline
Return the next available byte without consuming it.
Returns
The byte if no error and not at eof else -1;
Definition at line 100 of file ArduinoFiles.h.
              {
     return BaseFile::peek();
   }
position()
template<class BaseFile , typename PosType > PosType StreamFile< BaseFile, PosType >::position () inline
Returns
the current file position.
Definition at line 104 of file ArduinoFiles.h.
                      {
     return BaseFile::curPosition();
   }
Referenced by AppSerialCommandInterface::streamHandler().
read()
template<class BaseFile , typename PosType > int StreamFile< BaseFile, PosType >::read () inline
Read the next byte from a file.
Returns
For success return the next byte in the file as an int. If an error occurs or end of file is reached return -1.
Definition at line 112 of file ArduinoFiles.h.
              {
     return BaseFile::read();
   }
References read.
Referenced by ILI9341_t3_ERIS::begin(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), and AppSerialCommandInterface::streamHandler().
rewindDirectory()
template<class BaseFile , typename PosType > void StreamFile< BaseFile, PosType >::rewindDirectory () inline
Rewind a file if it is a directory
Definition at line 116 of file ArduinoFiles.h.
{
     if (BaseFile::isDir()) {
       BaseFile::rewind();
     }
   }
seek()
template<class BaseFile , typename PosType > bool StreamFile< BaseFile, PosType >::seek (PosType pos) inline
Seek to a new position in the file, which must be between 0 and the size of the file (inclusive).
Parameters
[in] pos the new file position.
Returns
true for success or false for failure.
Definition at line 128 of file ArduinoFiles.h.
{
     return BaseFile::seekSet(pos);
   }
Referenced by AppSerialCommandInterface::streamHandler().
size()
template<class BaseFile , typename PosType > PosType StreamFile< BaseFile, PosType >::size () inline
Returns
the file's size.
Definition at line 132 of file ArduinoFiles.h.
                  {
     return BaseFile::fileSize();
   }
Referenced by StreamFile< BaseFile, PosType >::write().
write() [1/2]
template<class BaseFile , typename PosType > size_t StreamFile< BaseFile, PosType >::write (const uint8_t * buffer, size_t size) inline
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buffer Pointer to the location of the data to be written.
[in] size Number of bytes to write.
Returns
For success write() returns the number of bytes written, always size.
Definition at line 155 of file ArduinoFiles.h.
{
     return BaseFile::write(buffer, size);
   }
References StreamFile< BaseFile, PosType >::size().
write() [2/2]
template<class BaseFile , typename PosType > size_t StreamFile< BaseFile, PosType >::write (uint8_t b) inline
Write a byte to a file. Required by the Arduino Print class.
Parameters
[in] b the byte to be written. Use getWriteError to check for errors.
Returns
1 for success and 0 for failure.
Definition at line 140 of file ArduinoFiles.h.
{
     return BaseFile::write(b);
   }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/common/ArduinoFiles.h