ERIS CORE: ExFatDbg.cpp File Reference
ExFatDbg.cpp File Reference
#include "ExFatVolume.h"
#include "../common/upcase.h"
#include "ExFatLib.h"
Macros
#define RAW_ROOT
Functions
static void dmpDirData (print_t *pr, DirGeneric_t *dir)
static uint16_t exFatDirChecksum (const void *dir, uint16_t checksum)
static uint16_t hashDir (DirName_t *dir, uint16_t hash)
static void printDateTime (print_t *pr, uint32_t timeDate, uint8_t ms, int8_t tz)
static void printDirBitmap (print_t *pr, DirBitmap_t *dir)
static void printDirFile (print_t *pr, DirFile_t *dir)
static void printDirLabel (print_t *pr, DirLabel_t *dir)
static void printDirName (print_t *pr, DirName_t *dir)
static void printDirStream (print_t *pr, DirStream_t *dir)
static void printDirUpcase (print_t *pr, DirUpcase_t *dir)
static void printExFatBoot (print_t *pr, pbs_t *pbs)
static void printHex (print_t *pr, uint16_t val)
static void printHex (print_t *pr, uint32_t val)
static void printHex (print_t *pr, uint8_t h)
static void printHex64 (print_t *pr, uint64_t n)
static void println64 (print_t *pr, uint64_t n)
static void printMbr (print_t *pr, MbrSector_t *mbr)
Macro Definition Documentation
RAW_ROOT
#define RAW_ROOT
Function Documentation
dmpDirData()
static void dmpDirData (print_t * pr, DirGeneric_t * dir) static
Definition at line 36 of file ExFatDbg.cpp.
{
   for (uint8_t k = 0; k < 31; k++) {
     if (k) {
       pr->write(' ');
     }
     printHex(pr, dir->data[k]);
   }
   pr->println();
 }
References DirGeneric_t::data, printHex(), PrintBasic::println(), and PrintBasic::write().
Referenced by ExFatPartition::printDir().
exFatDirChecksum()
static uint16_t exFatDirChecksum (const void * dir, uint16_t checksum) static
Definition at line 46 of file ExFatDbg.cpp.
{
   const uint8_t* data = reinterpret_cast<const uint8_t*>(dir);
   bool skip = data[0] == EXFAT_TYPE_FILE;
   for (size_t i = 0; i < 32; i += (i == 1 && skip ? 3 : 1)) {
     checksum = ((checksum << 15) | (checksum >> 1)) + data[i];
   }
   return checksum;
 }
References data, and EXFAT_TYPE_FILE.
Referenced by ExFatPartition::printDir().
hashDir()
static uint16_t hashDir (DirName_t * dir, uint16_t hash) static
Definition at line 56 of file ExFatDbg.cpp.
{
   for (uint8_t i = 0; i < 30; i += 2) {
     uint16_t u = getLe16(dir->unicode + i);
     if (!u) {
       break;
     }
   uint16_t c = toUpcase(u);
   hash = ((hash << 15) | (hash >> 1)) + (c & 0XFF);
   hash = ((hash << 15) | (hash >> 1)) + (c >> 8);
   }
   return hash;
 }
References getLe16(), toUpcase(), and DirName_t::unicode.
Referenced by ExFatPartition::printDir().
printDateTime()
static void printDateTime (print_t * pr, uint32_t timeDate, uint8_t ms, int8_t tz) static
Definition at line 69 of file ExFatDbg.cpp.
{
   fsPrintDateTime(pr, timeDate, ms, tz);
   pr->println();
 }
References fsPrintDateTime(), and PrintBasic::println().
Referenced by printDirFile().
printDirBitmap()
static void printDirBitmap (print_t * pr, DirBitmap_t * dir) static
Definition at line 75 of file ExFatDbg.cpp.
{
   pr->print(F("dirBitmap: 0x"));
   pr->println(dir->type, HEX);
   pr->print(F("flags: 0x"));
   pr->println(dir->flags, HEX);
   pr->print(F("firstCluster: "));
   pr->println(getLe32(dir->firstCluster));
   pr->print(F("size: "));
   println64(pr, getLe64(dir->size));
 }
References F, DirBitmap_t::firstCluster, DirBitmap_t::flags, getLe32(), getLe64(), HEX, PrintBasic::print(), PrintBasic::println(), println64(), DirBitmap_t::size, and DirBitmap_t::type.
Referenced by ExFatPartition::printDir().
printDirFile()
static void printDirFile (print_t * pr, DirFile_t * dir) static
Definition at line 86 of file ExFatDbg.cpp.
{
   pr->print(F("dirFile: 0x"));
   pr->println(dir->type, HEX);
   pr->print(F("setCount: "));
   pr->println(dir->setCount);
   pr->print(F("setChecksum: 0x"));
   pr->println(getLe16(dir->setChecksum), HEX);
   pr->print(F("attributes: 0x"));
   pr->println(getLe16(dir->attributes), HEX);
   pr->print(F("createTime: "));
   printDateTime(pr, getLe32(dir->createTime),
                 dir->createTimeMs, dir->createTimezone);
   pr->print(F("modifyTime: "));
   printDateTime(pr, getLe32(dir->modifyTime),
                 dir->modifyTimeMs, dir->modifyTimezone);
   pr->print(F("accessTime: "));
   printDateTime(pr, getLe32(dir->accessTime), 0, dir->accessTimezone);
 }
References DirFile_t::accessTime, DirFile_t::accessTimezone, DirFile_t::attributes, DirFile_t::createTime, DirFile_t::createTimeMs, DirFile_t::createTimezone, F, getLe16(), getLe32(), HEX, DirFile_t::modifyTime, DirFile_t::modifyTimeMs, DirFile_t::modifyTimezone, PrintBasic::print(), printDateTime(), PrintBasic::println(), DirFile_t::setChecksum, DirFile_t::setCount, and DirFile_t::type.
Referenced by ExFatPartition::printDir().
printDirLabel()
static void printDirLabel (print_t * pr, DirLabel_t * dir) static
Definition at line 105 of file ExFatDbg.cpp.
{
   pr->print(F("dirLabel: 0x"));
   pr->println(dir->type, HEX);
   pr->print(F("labelLength: "));
   pr->println(dir->labelLength);
   pr->print(F("unicode: "));
   for (size_t i = 0; i < dir->labelLength; i++) {
     pr->write(dir->unicode[2*i]);
   }
   pr->println();
 }
References F, HEX, DirLabel_t::labelLength, PrintBasic::print(), PrintBasic::println(), DirLabel_t::type, DirLabel_t::unicode, and PrintBasic::write().
Referenced by ExFatPartition::printDir().
printDirName()
static void printDirName (print_t * pr, DirName_t * dir) static
Definition at line 117 of file ExFatDbg.cpp.
{
   pr->print(F("dirName: 0x"));
   pr->println(dir->type, HEX);
   pr->print(F("unicode: "));
   for (size_t i = 0; i < 30; i += 2) {
     uint16_t c = getLe16(dir->unicode + i);
     if (c == 0) break;
     if (c < 128) {
       pr->print(static_cast<char>(c));
     } else {
       pr->print("0x");
       pr->print(c, HEX);
     }
     pr->print(' ');
   }
   pr->println();
 }
References F, getLe16(), HEX, PrintBasic::print(), PrintBasic::println(), DirName_t::type, and DirName_t::unicode.
Referenced by ExFatPartition::printDir().
printDirStream()
static void printDirStream (print_t * pr, DirStream_t * dir) static
Definition at line 135 of file ExFatDbg.cpp.
{
   pr->print(F("dirStream: 0x"));
   pr->println(dir->type, HEX);
   pr->print(F("flags: 0x"));
   pr->println(dir->flags, HEX);
   pr->print(F("nameLength: "));
   pr->println(dir->nameLength);
   pr->print(F("nameHash: 0x"));
   pr->println(getLe16(dir->nameHash), HEX);
   pr->print(F("validLength: "));
   println64(pr, getLe64(dir->validLength));
   pr->print(F("firstCluster: "));
   pr->println(getLe32(dir->firstCluster));
   pr->print(F("dataLength: "));
   println64(pr, getLe64(dir->dataLength));
 }
References DirStream_t::dataLength, F, DirStream_t::firstCluster, DirStream_t::flags, getLe16(), getLe32(), getLe64(), HEX, DirStream_t::nameHash, DirStream_t::nameLength, PrintBasic::print(), PrintBasic::println(), println64(), DirStream_t::type, and DirStream_t::validLength.
Referenced by ExFatPartition::printDir().
printDirUpcase()
static void printDirUpcase (print_t * pr, DirUpcase_t * dir) static
Definition at line 152 of file ExFatDbg.cpp.
{
   pr->print(F("dirUpcase: 0x"));
   pr->println(dir->type, HEX);
     pr->print(F("checksum: 0x"));
   pr->println(getLe32(dir->checksum), HEX);
   pr->print(F("firstCluster: "));
   pr->println(getLe32(dir->firstCluster));
   pr->print(F("size: "));
   println64(pr, getLe64(dir->size));
 }
References DirUpcase_t::checksum, F, DirUpcase_t::firstCluster, getLe32(), getLe64(), HEX, PrintBasic::print(), PrintBasic::println(), println64(), DirUpcase_t::size, and DirUpcase_t::type.
Referenced by ExFatPartition::printDir().
printExFatBoot()
static void printExFatBoot (print_t * pr, pbs_t * pbs) static
Definition at line 163 of file ExFatDbg.cpp.
{
   BpbExFat_t* ebs = reinterpret_cast<BpbExFat_t*>(pbs->bpb);
   pr->print(F("bpbSig: 0x"));
   pr->println(getLe16(pbs->signature), HEX);
   pr->print(F("FileSystemName: "));
   pr->write(reinterpret_cast<uint8_t*>(pbs->oemName), 8);
   pr->println();
   for (size_t i = 0; i < sizeof(ebs->mustBeZero); i++) {
     if (ebs->mustBeZero[i]) {
       pr->println(F("mustBeZero error"));
       break;
     }
   }
   pr->print(F("PartitionOffset: 0x"));
   printHex64(pr, getLe64(ebs->partitionOffset));
   pr->print(F("VolumeLength: "));
   println64(pr, getLe64(ebs->volumeLength));
   pr->print(F("FatOffset: 0x"));
   pr->println(getLe32(ebs->fatOffset), HEX);
   pr->print(F("FatLength: "));
   pr->println(getLe32(ebs->fatLength));
   pr->print(F("ClusterHeapOffset: 0x"));
   pr->println(getLe32(ebs->clusterHeapOffset), HEX);
   pr->print(F("ClusterCount: "));
   pr->println(getLe32(ebs->clusterCount));
   pr->print(F("RootDirectoryCluster: "));
   pr->println(getLe32(ebs->rootDirectoryCluster));
   pr->print(F("VolumeSerialNumber: 0x"));
   pr->println(getLe32(ebs->volumeSerialNumber), HEX);
   pr->print(F("FileSystemRevision: 0x"));
   pr->println(getLe32(ebs->fileSystemRevision), HEX);
   pr->print(F("VolumeFlags: 0x"));
   pr->println(getLe16(ebs->volumeFlags) , HEX);
   pr->print(F("BytesPerSectorShift: "));
   pr->println(ebs->bytesPerSectorShift);
   pr->print(F("SectorsPerClusterShift: "));
   pr->println(ebs->sectorsPerClusterShift);
   pr->print(F("NumberOfFats: "));
   pr->println(ebs->numberOfFats);
   pr->print(F("DriveSelect: 0x"));
   pr->println(ebs->driveSelect, HEX);
   pr->print(F("PercentInUse: "));
   pr->println(ebs->percentInUse);
 }
References partitionBootSector::bpb, biosParameterBlockExFat::bytesPerSectorShift, biosParameterBlockExFat::clusterCount, biosParameterBlockExFat::clusterHeapOffset, biosParameterBlockExFat::driveSelect, F, biosParameterBlockExFat::fatLength, biosParameterBlockExFat::fatOffset, biosParameterBlockExFat::fileSystemRevision, getLe16(), getLe32(), getLe64(), HEX, biosParameterBlockExFat::mustBeZero, biosParameterBlockExFat::numberOfFats, partitionBootSector::oemName, biosParameterBlockExFat::partitionOffset, biosParameterBlockExFat::percentInUse, PrintBasic::print(), printHex64(), PrintBasic::println(), println64(), biosParameterBlockExFat::rootDirectoryCluster, biosParameterBlockExFat::sectorsPerClusterShift, partitionBootSector::signature, biosParameterBlockExFat::volumeFlags, biosParameterBlockExFat::volumeLength, biosParameterBlockExFat::volumeSerialNumber, and PrintBasic::write().
Referenced by ExFatPartition::printVolInfo().
printHex() [1/3]
static void printHex (print_t * pr, uint16_t val) static
Definition at line 215 of file ExFatDbg.cpp.
{
   bool space = true;
   for (uint8_t i = 0; i < 4; i++) {
     uint8_t h = (val >> (12 - 4*i)) & 15;
     if (h || i == 3) {
       space = false;
     }
     if (space) {
       pr->write(' ');
     } else {
       pr->print(h, HEX);
     }
   }
 }
References HEX, PrintBasic::print(), and PrintBasic::write().
printHex() [2/3]
static void printHex (print_t * pr, uint32_t val) static
Definition at line 230 of file ExFatDbg.cpp.
{
   bool space = true;
   for (uint8_t i = 0; i < 8; i++) {
     uint8_t h = (val >> (28 - 4*i)) & 15;
     if (h || i == 7) {
       space = false;
     }
     if (space) {
       pr->write(' ');
     } else {
       pr->print(h, HEX);
     }
   }
 }
References HEX, PrintBasic::print(), and PrintBasic::write().
printHex() [3/3]
static void printHex (print_t * pr, uint8_t h) static
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 208 of file ExFatDbg.cpp.
{
   if (h < 16) {
     pr->write('0');
   }
   pr->print(h, HEX);
 }
References HEX, PrintBasic::print(), and PrintBasic::write().
Referenced by ExFatPartition::checkUpcase(), dmpDirData(), ExFatPartition::dmpFat(), ExFatPartition::dmpSector(), printMbr(), and ExFatPartition::printUpcase().
printHex64()
static void printHex64 (print_t * pr, uint64_t n) static
Definition at line 245 of file ExFatDbg.cpp.
{
   char buf[17];
   char *str = &buf[sizeof(buf) - 1];
   *str = '\0';
   do {
     uint8_t h = n & 15;
     *--str = h < 10 ? h + '0' : h + 'A' - 10;
     n >>= 4;
   } while (n);
   pr->println(str);
 }
References buf, and PrintBasic::println().
Referenced by printExFatBoot().
println64()
static void println64 (print_t * pr, uint64_t n) static
Definition at line 257 of file ExFatDbg.cpp.
{
   char buf[21];
   char *str = &buf[sizeof(buf) - 1];
   *str = '\0';
   do {
     uint64_t m = n;
     n /= 10;
     *--str = m - 10*n + '0';
   } while (n);
   pr->println(str);
 }
References buf, m, and PrintBasic::println().
Referenced by printDirBitmap(), printDirStream(), printDirUpcase(), and printExFatBoot().
printMbr()
static void printMbr (print_t * pr, MbrSector_t * mbr) static
Definition at line 269 of file ExFatDbg.cpp.
{
   pr->print(F("mbrSig: 0x"));
   pr->println(getLe16(mbr->signature), HEX);
   for (int i = 0; i < 4; i++) {
     printHex(pr, mbr->part[i].boot);
     pr->write(' ');
     for (int k = 0; k < 3; k++) {
       printHex(pr, mbr->part[i].beginCHS[k]);
       pr->write(' ');
     }
     printHex(pr, mbr->part[i].type);
     pr->write(' ');
     for (int k = 0; k < 3; k++) {
       printHex(pr, mbr->part[i].endCHS[k]);
       pr->write(' ');
     }
     pr->print(getLe32(mbr->part[i].relativeSectors), HEX);
     pr->print(' ');
     pr->println(getLe32(mbr->part[i].totalSectors), HEX);
   }
 }
References mbrPartition::beginCHS, mbrPartition::boot, mbrPartition::endCHS, F, getLe16(), getLe32(), HEX, masterBootRecordSector::part, PrintBasic::print(), printHex(), PrintBasic::println(), mbrPartition::relativeSectors, masterBootRecordSector::signature, mbrPartition::totalSectors, mbrPartition::type, and PrintBasic::write().
Referenced by ExFatPartition::printVolInfo().