ERIS CORE: wren_vm.h File Reference
wren_vm.h File Reference
#include "wren_common.h"
#include "wren_compiler.h"
#include "wren_value.h"
#include "wren_utils.h"
#include "wren_opcodes.h"
Classes
struct WrenHandle
struct WrenVM
Macros
#define OPCODE(name, _) CODE_##name,
#define WREN_MAX_TEMP_ROOTS 8
Enumerations
enum Code
Functions
static void wrenCallFunction (WrenVM *vm, ObjFiber *fiber, ObjClosure *closure, int numArgs)
ObjClosure * wrenCompileSource (WrenVM *vm, const char *module, const char *source, bool isExpression, bool printErrors)
int wrenDeclareVariable (WrenVM *vm, ObjModule *module, const char *name, size_t length, int line)
int wrenDefineVariable (WrenVM *vm, ObjModule *module, const char *name, size_t length, Value value, int *line)
void wrenFinalizeForeign (WrenVM *vm, ObjForeign *foreign)
Value wrenFindVariable (WrenVM *vm, ObjModule *module, const char *name)
static ObjClass * wrenGetClassInline (WrenVM *vm, Value value)
Value wrenGetModuleVariable (WrenVM *vm, Value moduleName, Value variableName)
static bool wrenIsFalsyValue (Value value)
static bool wrenIsLocalName (const char *name)
WrenHandle * wrenMakeHandle (WrenVM *vm, Value value)
void wrenPopRoot (WrenVM *vm)
void wrenPushRoot (WrenVM *vm, Obj *obj)
void * wrenReallocate (WrenVM *vm, void *memory, size_t oldSize, size_t newSize)
Macro Definition Documentation
OPCODE
#define OPCODE (name, _) CODE_##name,
Definition at line 15 of file wren_vm.h.
WREN_MAX_TEMP_ROOTS
#define WREN_MAX_TEMP_ROOTS 8
Definition at line 11 of file wren_vm.h.
Enumeration Type Documentation
Code
enum Code
Definition at line 13 of file wren_vm.h.
 {
   #define OPCODE(name, _) CODE_##name,
   #include "wren_opcodes.h"
   #undef OPCODE
 } Code;
Function Documentation
wrenCallFunction()
static void wrenCallFunction (WrenVM * vm, ObjFiber * fiber, ObjClosure * closure, int numArgs) inline static
Definition at line 178 of file wren_vm.h.
 {
   // Grow the call frame array if needed.
   if (fiber->numFrames + 1 > fiber->frameCapacity)
   {
     int max = fiber->frameCapacity * 2;
     fiber->frames = (CallFrame*)wrenReallocate(vm, fiber->frames,
         sizeof(CallFrame) * fiber->frameCapacity, sizeof(CallFrame) * max);
     fiber->frameCapacity = max;
   }
   // Grow the stack if needed.
   int stackSize = (int)(fiber->stackTop - fiber->stack);
   int needed = stackSize + closure->fn->maxSlots;
   wrenEnsureStack(vm, fiber, needed);
   wrenAppendCallFrame(vm, fiber, closure, fiber->stackTop - numArgs);
 }
References fiber, ObjClosure::fn, ObjFn::maxSlots, wrenAppendCallFrame(), wrenEnsureStack(), and wrenReallocate().
Referenced by call_fn(), runInterpreter(), and wrenCall().
wrenCompileSource()
ObjClosure* wrenCompileSource (WrenVM * vm, const char * module, const char * source, bool isExpression, bool printErrors)
Definition at line 1527 of file wren_vm.c.
 {
   Value nameValue = NULL_VAL;
   if (module != NULL)
   {
     nameValue = wrenNewString(vm, module);
     wrenPushRoot(vm, AS_OBJ(nameValue));
   }
   ObjClosure* closure = compileInModule(vm, nameValue, source,
                                         isExpression, printErrors);
   if (module != NULL) wrenPopRoot(vm); // nameValue.
   return closure;
 }
References AS_OBJ, compileInModule(), NULL, NULL_VAL, source, wrenNewString(), wrenPopRoot(), and wrenPushRoot().
Referenced by metaCompile(), and wrenInterpret().
wrenDeclareVariable()
int wrenDeclareVariable (WrenVM * vm, ObjModule * module, const char * name, size_t length, int line)
Definition at line 1563 of file wren_vm.c.
 {
   if (module->variables.count == MAX_MODULE_VARS) return -2;
   // Implicitly defined variables get a "value" that is the line where the
   // variable is first used. We'll use that later to report an error on the
   // right line.
   wrenValueBufferWrite(vm, &module->variables, NUM_VAL(line));
   return wrenSymbolTableAdd(vm, &module->variableNames, name, length);
 }
References MAX_MODULE_VARS, name, NUM_VAL, ObjModule::variableNames, ObjModule::variables, and wrenSymbolTableAdd().
Referenced by name().
wrenDefineVariable()
int wrenDefineVariable (WrenVM * vm, ObjModule * module, const char * name, size_t length, Value value, int * line)
Definition at line 1575 of file wren_vm.c.
 {
   if (module->variables.count == MAX_MODULE_VARS) return -2;
   if (IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   // See if the variable is already explicitly or implicitly declared.
   int symbol = wrenSymbolTableFind(&module->variableNames, name, length);
   if (symbol == -1)
   {
     // Brand new variable.
     symbol = wrenSymbolTableAdd(vm, &module->variableNames, name, length);
     wrenValueBufferWrite(vm, &module->variables, value);
   }
   else if (IS_NUM(module->variables.data[symbol]))
   {
     // An implicitly declared variable's value will always be a number.
     // Now we have a real definition.
     if(line) *line = (int)AS_NUM(module->variables.data[symbol]);
     module->variables.data[symbol] = value;
     // If this was a localname we want to error if it was
     // referenced before this definition.
     if (wrenIsLocalName(name)) symbol = -3;
   }
   else
   {
     // Already explicitly declared.
     symbol = -1;
   }
   if (IS_OBJ(value)) wrenPopRoot(vm);
   return symbol;
 }
References AS_NUM, AS_OBJ, IS_NUM, IS_OBJ, MAX_MODULE_VARS, name, ObjModule::variableNames, ObjModule::variables, wrenIsLocalName(), wrenPopRoot(), wrenPushRoot(), wrenSymbolTableAdd(), and wrenSymbolTableFind().
Referenced by compileInModule(), declareVariable(), and defineClass().
wrenFinalizeForeign()
void wrenFinalizeForeign (WrenVM * vm, ObjForeign * foreign)
Definition at line 680 of file wren_vm.c.
 {
   // TODO: Don't look up every time.
   int symbol = wrenSymbolTableFind(&vm->methodNames, "<finalize>", 10);
   ASSERT(symbol != -1, "Should have defined <finalize> symbol.");
   // If there are no finalizers, don't finalize it.
   if (symbol == -1) return;
   // If the class doesn't have a finalizer, bail out.
   ObjClass* classObj = foreign->obj.classObj;
   if (symbol >= classObj->methods.count) return;
   Method* method = &classObj->methods.data[symbol];
   if (method->type == METHOD_NONE) return;
   ASSERT(method->type == METHOD_FOREIGN, "Finalizer should be foreign.");
   WrenFinalizerFn finalizer = (WrenFinalizerFn)method->as.foreign;
   finalizer(foreign->data);
 }
References ASSERT, sObj::classObj, ObjForeign::data, method(), METHOD_FOREIGN, METHOD_NONE, WrenVM::methodNames, sObjClass::methods, ObjForeign::obj, and wrenSymbolTableFind().
Referenced by wrenFreeObj().
wrenFindVariable()
Value wrenFindVariable (WrenVM * vm, ObjModule * module, const char * name)
Definition at line 1557 of file wren_vm.c.
 {
   int symbol = wrenSymbolTableFind(&module->variableNames, name, strlen(name));
   return module->variables.data[symbol];
 }
References name, ObjModule::variableNames, ObjModule::variables, and wrenSymbolTableFind().
Referenced by wrenInitializeCore().
wrenGetClassInline()
static ObjClass* wrenGetClassInline (WrenVM * vm, Value value) inline static
Definition at line 209 of file wren_vm.h.
 {
   if (IS_NUM(value)) return vm->numClass;
   if (IS_OBJ(value)) return AS_OBJ(value)->classObj;
 #if WREN_NAN_TAGGING
   switch (GET_TAG(value))
   {
     case TAG_FALSE:     return vm->boolClass; break;
     case TAG_NAN:       return vm->numClass; break;
     case TAG_NULL:      return vm->nullClass; break;
     case TAG_TRUE:      return vm->boolClass; break;
     case TAG_UNDEFINED: UNREACHABLE();
   }
 #else
   switch (value.type)
   {
     case VAL_FALSE:     return vm->boolClass;
     case VAL_NULL:      return vm->nullClass;
     case VAL_NUM:       return vm->numClass;
     case VAL_TRUE:      return vm->boolClass;
     case VAL_OBJ:       return AS_OBJ(value)->classObj;
     case VAL_UNDEFINED: UNREACHABLE();
   }
 #endif
   UNREACHABLE();
   return NULL;
 }
References AS_OBJ, WrenVM::boolClass, GET_TAG, IS_NUM, IS_OBJ, NULL, WrenVM::nullClass, WrenVM::numClass, TAG_FALSE, TAG_NAN, TAG_NULL, TAG_TRUE, TAG_UNDEFINED, and UNREACHABLE.
Referenced by runInterpreter(), and wrenGetClass().
wrenGetModuleVariable()
Value wrenGetModuleVariable (WrenVM * vm, Value moduleName, Value variableName)
Definition at line 1544 of file wren_vm.c.
 {
   ObjModule* module = getModule(vm, moduleName);
   if (module == NULL)
   {
     vm->fiber->error = wrenStringFormat(vm, "Module '@' is not loaded.",
                                         moduleName);
     return NULL_VAL;
   }
   return getModuleVariable(vm, module, variableName);
 }
References sObjFiber::error, WrenVM::fiber, getModule(), getModuleVariable(), NULL, NULL_VAL, and wrenStringFormat().
wrenIsFalsyValue()
static bool wrenIsFalsyValue (Value value) inline static
Definition at line 246 of file wren_vm.h.
 {
   return IS_FALSE(value) || IS_NULL(value);
 }
References IS_FALSE, and IS_NULL.
Referenced by runInterpreter().
wrenIsLocalName()
static bool wrenIsLocalName (const char * name) inline static
Definition at line 241 of file wren_vm.h.
 {
   return name[0] >= 'a' && name[0] <= 'z';
 }
References name.
Referenced by name(), and wrenDefineVariable().
wrenMakeHandle()
WrenHandle* wrenMakeHandle (WrenVM * vm, Value value)
Definition at line 1475 of file wren_vm.c.
 {
   if (IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   // Make a handle for it.
   WrenHandle* handle = ALLOCATE(vm, WrenHandle);
   handle->value = value;
   if (IS_OBJ(value)) wrenPopRoot(vm);
   // Add it to the front of the linked list of handles.
   if (vm->handles != NULL) vm->handles->prev = handle;
   handle->prev = NULL;
   handle->next = vm->handles;
   vm->handles = handle;
   return handle;
 }
References ALLOCATE, AS_OBJ, WrenVM::handles, IS_OBJ, WrenHandle::next, NULL, WrenHandle::prev, WrenHandle::value, wrenPopRoot(), and wrenPushRoot().
Referenced by wrenGetSlotHandle(), and wrenMakeCallHandle().
wrenPopRoot()
void wrenPopRoot (WrenVM * vm)
Definition at line 1622 of file wren_vm.c.
 {
   ASSERT(vm->numTempRoots > 0, "No temporary roots to release.");
   vm->numTempRoots--;
 }
References ASSERT, and WrenVM::numTempRoots.
Referenced by addConstant(), addToAttributeGroup(), compileInModule(), copyMethodAttributes(), DEF_PRIMITIVE(), defineClass(), importModule(), wrenCompileSource(), wrenDefineVariable(), wrenGetVariable(), wrenHasModule(), wrenHasVariable(), wrenInitializeCore(), wrenInterpret(), wrenListInsert(), wrenListRemoveAt(), wrenMakeHandle(), wrenMapRemoveKey(), wrenNewClass(), wrenNewModule(), wrenNewSingleClass(), and wrenSymbolTableAdd().
wrenPushRoot()
void wrenPushRoot (WrenVM * vm, Obj * obj)
Definition at line 1614 of file wren_vm.c.
 {
   ASSERT(obj != NULL, "Can't root NULL.");
   ASSERT(vm->numTempRoots < WREN_MAX_TEMP_ROOTS, "Too many temporary roots.");
   vm->tempRoots[vm->numTempRoots++] = obj;
 }
References ASSERT, NULL, WrenVM::numTempRoots, WrenVM::tempRoots, and WREN_MAX_TEMP_ROOTS.
Referenced by addConstant(), addToAttributeGroup(), compileInModule(), copyMethodAttributes(), DEF_PRIMITIVE(), defineClass(), importModule(), wrenCompileSource(), wrenDefineVariable(), wrenGetVariable(), wrenHasModule(), wrenHasVariable(), wrenInitializeCore(), wrenInterpret(), wrenListInsert(), wrenListRemoveAt(), wrenMakeHandle(), wrenMapRemoveKey(), wrenNewClass(), wrenNewModule(), wrenNewSingleClass(), and wrenSymbolTableAdd().
wrenReallocate()
void* wrenReallocate (WrenVM * vm, void * memory, size_t oldSize, size_t newSize)
Definition at line 213 of file wren_vm.c.
 {
 #if WREN_DEBUG_TRACE_MEMORY
   // Explicit cast because size_t has different sizes on 32-bit and 64-bit and
   // we need a consistent type for the format string.
   printf("reallocate %p %lu -> %lu\n",
          memory, (unsigned long)oldSize, (unsigned long)newSize);
 #endif
   // If new bytes are being allocated, add them to the total count. If objects
   // are being completely deallocated, we don't track that (since we don't
   // track the original size). Instead, that will be handled while marking
   // during the next GC.
   vm->bytesAllocated += newSize - oldSize;
 #if WREN_DEBUG_GC_STRESS
   // Since collecting calls this function to free things, make sure we don't
   // recurse.
   if (newSize > 0) wrenCollectGarbage(vm);
 #else
   if (newSize > 0 && vm->bytesAllocated > vm->nextGC) wrenCollectGarbage(vm);
 #endif
   return vm->config.reallocateFn(memory, newSize, vm->config.userData);
 }
References WrenVM::bytesAllocated, WrenVM::config, WrenVM::nextGC, WrenConfiguration::reallocateFn, WrenConfiguration::userData, and wrenCollectGarbage().
Referenced by wrenCallFunction(), wrenEnsureStack(), and wrenListRemoveAt().