ERIS CORE: ExFatVolume Class Reference
ExFatVolume Class Reference
exFAT volume.
#include <ExFatVolume.h>
Public Member Functions
ExFatVolume ()
bool begin (BlockDevice *dev, bool setCwv=true, uint8_t part=1)
uint32_t blocksPerCluster () __attribute__((deprecated))
uint32_t bytesPerCluster ()
uint8_t bytesPerClusterShift ()
uint16_t bytesPerSector ()
uint8_t bytesPerSectorShift ()
uint8_t * cacheClear ()
bool chdir ()
bool chdir (const ExChar_t *path)
bool chdir (const String &path)
void checkUpcase (print_t *pr)
void chvol ()
uint32_t clusterCount ()
uint32_t clusterHeapStartSector ()
void dmpBitmap (print_t *pr)
void dmpCluster (print_t *pr, uint32_t cluster, uint32_t offset, uint32_t count)
void dmpFat (print_t *pr, uint32_t start, uint32_t count)
void dmpSector (print_t *pr, uint32_t sector)
bool exists (const ExChar_t *path)
bool exists (const String &path)
uint32_t fatLength ()
uint32_t fatStartSector ()
uint8_t fatType () const
uint32_t freeClusterCount ()
bool init (BlockDevice *dev, uint8_t part)
bool ls ()
bool ls (const ExChar_t *path, uint8_t flags=0)
bool ls (print_t *pr, const ExChar_t *path, uint8_t flags)
bool ls (print_t *pr, uint8_t flags=0)
bool ls (uint8_t flags)
bool mkdir (const ExChar_t *path, bool pFlag=true)
bool mkdir (const String &path, bool pFlag=true)
ExFile open (const ExChar_t *path, oflag_t oflag=O_RDONLY)
ExFile open (const String &path, oflag_t oflag=O_RDONLY)
bool printDir (print_t *pr, ExFatFile *file)
void printFat (print_t *pr)
void printUpcase (print_t *pr)
bool printVolInfo (print_t *pr)
bool remove (const ExChar_t *path)
bool remove (const String &path)
bool rename (const ExChar_t *oldPath, const ExChar_t *newPath)
bool rename (const String &oldPath, const String &newPath)
bool rmdir (const ExChar_t *path)
bool rmdir (const String &path)
uint32_t rootDirectoryCluster ()
uint32_t rootLength ()
uint32_t sectorsPerCluster ()
uint8_t sectorsPerClusterShift ()
bool truncate (const ExChar_t *path, uint64_t length)
bool truncate (const String &path, uint64_t length)
Static Public Member Functions
static ExFatVolume * cwv ()
Detailed Description
exFAT volume.
Copyright (c) 2011-2019 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 34 of file ExFatVolume.h.
Constructor & Destructor Documentation
ExFatVolume()
ExFatVolume::ExFatVolume () inline
Definition at line 36 of file ExFatVolume.h.
                 {
   }
Member Function Documentation
begin()
bool ExFatVolume::begin (BlockDevice * dev, bool setCwv = true, uint8_t part = 1) inline
Initialize an FatVolume object.
Parameters
[in] dev Device block driver.
[in] setCwv Set current working volume if true.
[in] part partition to initialize.
Returns
true for success or false for failure.
Definition at line 45 of file ExFatVolume.h.
{
     if (!init(dev, part)) {
       return false;
     }
     if (!chdir()) {
       return false;
     }
     if (setCwv) {
       m_cwv = this;
     }
     return true;
   }
References chdir(), and ExFatPartition::init().
Referenced by FsVolume::begin().
blocksPerCluster()
uint32_t ExFatPartition::blocksPerCluster () inline inherited
Definition at line 168 of file ExFatPartition.h.
 {return sectorsPerCluster();} //NOLINT
References ExFatPartition::sectorsPerCluster().
bytesPerCluster()
uint32_t ExFatPartition::bytesPerCluster () inline inherited
Returns
the number of bytes in a cluster.
Definition at line 122 of file ExFatPartition.h.
 {return m_bytesPerCluster;}
Referenced by FsVolume::bytesPerCluster().
bytesPerClusterShift()
uint8_t ExFatPartition::bytesPerClusterShift () inline inherited
Returns
the power of two for bytesPerCluster.
Definition at line 124 of file ExFatPartition.h.
{
     return m_bytesPerSectorShift + m_sectorsPerClusterShift;
   }
Referenced by ExFatFile::preAllocate(), ExFatFile::remove(), ExFatPartition::rootLength(), ExFatFile::seekSet(), ExFatFile::truncate(), and ExFatFile::write().
bytesPerSector()
uint16_t ExFatPartition::bytesPerSector () inline inherited
Returns
the number of bytes in a sector.
Definition at line 128 of file ExFatPartition.h.
 {return m_bytesPerSector;}
Referenced by ExFatFile::read(), and ExFatFile::write().
bytesPerSectorShift()
uint8_t ExFatPartition::bytesPerSectorShift () inline inherited
Returns
the power of two for bytesPerSector.
Definition at line 130 of file ExFatPartition.h.
 {return m_bytesPerSectorShift;}
Referenced by ExFatFile::read(), and ExFatFile::write().
cacheClear()
uint8_t* ExFatPartition::cacheClear () inline inherited
Clear the cache and returns a pointer to the cache. Not for normal apps.
Returns
A pointer to the cache buffer or zero if an error occurs.
Definition at line 135 of file ExFatPartition.h.
{
     return m_dataCache.clear();
   }
References FsCache::clear().
Referenced by SdExFat::format().
chdir() [1/3]
bool ExFatVolume::chdir () inline
Set volume working directory to root.
Returns
true for success or false for failure.
Definition at line 61 of file ExFatVolume.h.
                {
     m_vwd.close();
     return m_vwd.openRoot(this);
   }
References ExFatFile::close(), and ExFatFile::openRoot().
Referenced by begin(), and chdir().
chdir() [2/3]
bool ExFatVolume::chdir (const ExChar_t * path)
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 28 of file ExFatVolume.cpp.
{
   ExFatFile dir;
   if (!dir.open(vwd(), path, O_RDONLY)) {
     goto fail;
   }
   if (!dir.isDir()) {
     goto fail;
   }
   m_vwd = dir;
   return true;
 fail:
   return false;
 }
References ExFatFile::isDir(), O_RDONLY, and ExFatFile::open().
chdir() [3/3]
bool ExFatVolume::chdir (const String & path) inline
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 251 of file ExFatVolume.h.
{
     return chdir(path.c_str());
   }
References chdir().
checkUpcase()
void ExFatPartition::checkUpcase (print_t * pr) inherited
Definition at line 363 of file ExFatDbg.cpp.
{
   bool skip = false;
   uint16_t u = 0;
   uint8_t* upcase = nullptr;
   uint32_t size = 0;
   uint32_t sector = clusterStartSector(m_rootDirectoryCluster);
   uint8_t* cache = dataCacheGet(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read root failed"));
     return;
   }
   DirUpcase_t* dir = reinterpret_cast<DirUpcase_t*>(cache);
   pr->println(F("\nChecking upcase table"));
   for (size_t i = 0; i < 16; i++) {
     if (dir[i].type == EXFAT_TYPE_UPCASE) {
       sector = clusterStartSector(getLe32(dir[i].firstCluster));
       size = getLe64(dir[i].size);
       break;
     }
   }
   if (!size) {
     pr->println(F("upcase not found"));
     return;
   }
   for (size_t i = 0; i < size/2; i++) {
     if ((i%256) == 0) {
       upcase = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
       if (!upcase) {
         pr->println(F("read upcase failed"));
         return;
       }
     }
     uint16_t v = getLe16(&upcase[2*(i & 0XFF)]);
     if (skip) {
       pr->print("skip ");
       pr->print(u);
       pr->write(' ');
       pr->println(v);
     }
     if (v == 0XFFFF) {
       skip = true;
     } else if (skip) {
       for (uint16_t k = 0; k < v; k++) {
         uint16_t x = toUpcase(u + k);
         if (x != (u + k)) {
           printHex(pr, (uint16_t)(u+k));
           pr->write(',');
           printHex(pr, x);
           pr->println("<<<<<<<<<<<<<<<<<<<<");
         }
       }
       u += v;
       skip = false;
     } else {
       uint16_t x = toUpcase(u);
       if (v != x) {
         printHex(pr, u);
         pr->write(',');
         printHex(pr, x);
         pr->write(',');
         printHex(pr, v);
         pr->println();
       }
       u++;
     }
   }
   pr->println(F("Done checkUpcase"));
 }
References FsCache::CACHE_FOR_READ, EXFAT_TYPE_UPCASE, F, getLe16(), getLe32(), getLe64(), toUpcase(), and x.
chvol()
void ExFatVolume::chvol () inline
Change global working volume to this volume.
Definition at line 74 of file ExFatVolume.h.
 {m_cwv = this;}
clusterCount()
uint32_t ExFatPartition::clusterCount () inline inherited
Returns
the cluster count for the partition.
Definition at line 139 of file ExFatPartition.h.
 {return m_clusterCount;}
Referenced by FsVolume::clusterCount().
clusterHeapStartSector()
uint32_t ExFatPartition::clusterHeapStartSector () inline inherited
Returns
the cluster heap start sector.
Definition at line 141 of file ExFatPartition.h.
 {return m_clusterHeapStartSector;}
Referenced by FsVolume::dataStartSector().
cwv()
static ExFatVolume* ExFatVolume::cwv () inline static
Returns
current working volume.
Definition at line 72 of file ExFatVolume.h.
 {return m_cwv;}
Referenced by ExFatFile::open().
dmpBitmap()
void ExFatPartition::dmpBitmap (print_t * pr) inherited
Definition at line 188 of file ExFatDbg.cpp.
{
   pr->println(F("bitmap:"));
   dmpSector(pr, m_clusterHeapStartSector);
 }
References ExFatPartition::dmpSector(), and F.
dmpCluster()
void ExFatPartition::dmpCluster (print_t * pr, uint32_t cluster, uint32_t offset, uint32_t count) inherited
Definition at line 159 of file ExFatDbg.cpp.
{
   uint32_t sector = clusterStartSector(cluster) + offset;
   for (uint32_t i = 0; i < count; i++) {
     pr->print(F("\nSector: "));
     pr->println(sector + i, HEX);
     dmpSector(pr, sector + i);
   }
 }
References count, ExFatPartition::dmpSector(), F, and HEX.
dmpFat()
void ExFatPartition::dmpFat (print_t * pr, uint32_t start, uint32_t count) inherited
Definition at line 203 of file ExFatDbg.cpp.
{
   uint32_t sector = m_fatStartSector + start;
   uint32_t cluster = 128*start;
   pr->println(F("FAT:"));
   for (uint32_t i = 0; i < count; i++) {
     uint8_t* cache = dataCacheGet(sector + i, FsCache::CACHE_FOR_READ);
     if (!cache) {
       pr->println(F("cache read failed"));
       return;
     }
     uint32_t* fat = reinterpret_cast<uint32_t*>(cache);
     for (size_t k = 0; k < 128; k++) {
       if (0 == cluster%8) {
         if (k) {
           pr->println();
         }
         printHex(pr, cluster);
       }
       cluster++;
       pr->write(' ');
       printHex(pr, fat[k]);
     }
     pr->println();
   }
 }
References FsCache::CACHE_FOR_READ, count, and F.
dmpSector()
void ExFatPartition::dmpSector (print_t * pr, uint32_t sector) inherited
Definition at line 169 of file ExFatDbg.cpp.
{
   uint8_t* cache = dataCacheGet(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("dmpSector failed"));
     return;
   }
   for (uint16_t i = 0; i < 512; i++) {
     if (i%32 == 0) {
       if (i) {
         pr->println();
       }
       printHex(pr, i);
     }
     pr->write(' ');
     printHex(pr, cache[i]);
   }
   pr->println();
 }
References FsCache::CACHE_FOR_READ, and F.
Referenced by ExFatPartition::dmpBitmap(), and ExFatPartition::dmpCluster().
exists() [1/2]
bool ExFatVolume::exists (const ExChar_t * path) inline
Test for the existence of a file.
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 83 of file ExFatVolume.h.
{
     ExFatFile tmp;
     return tmp.open(this, path, O_RDONLY);
   }
References O_RDONLY, and ExFatFile::open().
Referenced by exists().
exists() [2/2]
bool ExFatVolume::exists (const String & path) inline
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 260 of file ExFatVolume.h.
{
     return exists(path.c_str());
   }
References exists().
fatLength()
uint32_t ExFatPartition::fatLength () inline inherited
Returns
the FAT length in sectors
Definition at line 143 of file ExFatPartition.h.
 {return m_fatLength;}
fatStartSector()
uint32_t ExFatPartition::fatStartSector () inline inherited
Returns
the FAT start sector number.
Definition at line 145 of file ExFatPartition.h.
 {return m_fatStartSector;}
Referenced by FsVolume::fatStartSector().
fatType()
uint8_t ExFatPartition::fatType () const inline inherited
Returns
Type FAT_TYPE_EXFAT for exFAT partition or zero for error.
Definition at line 147 of file ExFatPartition.h.
 {return m_fatType;}
freeClusterCount()
uint32_t ExFatPartition::freeClusterCount () inherited
Returns
the free cluster count.
Definition at line 344 of file ExFatPartition.cpp.
{
   uint32_t nc = 0;
   uint32_t sector = m_clusterHeapStartSector;
   uint32_t usedCount = 0;
   uint8_t* cache;
   while (true) {
     cache = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
     if (!cache) {
       return 0;
     }
     for (size_t i = 0; i < m_bytesPerSector; i++) {
       if (cache[i] == 0XFF) {
         usedCount+= 8;
       } else if (cache[i]) {
         for (uint8_t mask = 1; mask ; mask <<=1) {
           if ((mask & cache[i])) {
             usedCount++;
           }
         }
       }
       nc += 8;
       if (nc >= m_clusterCount) {
         return m_clusterCount - usedCount;
       }
     }
   }
 }
References FsCache::CACHE_FOR_READ.
Referenced by FsVolume::freeClusterCount().
init()
bool ExFatPartition::init (BlockDevice * dev, uint8_t part) inherited
Initialize a exFAT partition.
Parameters
[in] dev The blockDevice for the partition.
[in] part The partition to be used. Legal values for part are 1-4 to use the corresponding partition on a device formatted with a MBR, Master Boot Record, or zero if the device is formatted as a super floppy with the FAT boot sector in sector zero.
Returns
true for success or false for failure.
Definition at line 75 of file ExFatPartition.cpp.
{
   uint32_t volStart = 0;
   uint8_t *cache;
   pbs_t* pbs;
   BpbExFat_t* bpb;
   MbrSector_t* mbr;
   MbrPart_t* mp;
   m_fatType = 0;
   m_blockDev = dev;
   cacheInit(m_blockDev);
   cache = dataCacheGet(0, FsCache::CACHE_FOR_READ);
   if (part > 4 || !cache) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (part >= 1) {
     mbr = reinterpret_cast<MbrSector_t*>(cache);
     mp = &mbr->part[part - 1];
     if ((mp->boot != 0 && mp->boot != 0X80) || mp->type == 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     volStart = getLe32(mp->relativeSectors);
     cache = dataCacheGet(volStart, FsCache::CACHE_FOR_READ);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   pbs = reinterpret_cast<pbs_t*>(cache);
   if (strncmp(pbs->oemName, "EXFAT", 5)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   bpb = reinterpret_cast<BpbExFat_t*>(pbs->bpb);
   if (bpb->bytesPerSectorShift != m_bytesPerSectorShift) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_fatStartSector = volStart + getLe32(bpb->fatOffset);
   m_fatLength = getLe32(bpb->fatLength);
   m_clusterHeapStartSector = volStart + getLe32(bpb->clusterHeapOffset);
   m_clusterCount = getLe32(bpb->clusterCount);
   m_rootDirectoryCluster = getLe32(bpb->rootDirectoryCluster);
   m_sectorsPerClusterShift = bpb->sectorsPerClusterShift;
   m_bytesPerCluster = 1UL << (m_bytesPerSectorShift + m_sectorsPerClusterShift);
   m_clusterMask = m_bytesPerCluster - 1;
   // Set m_bitmapStart to first free cluster.
   m_bitmapStart = 0;
   bitmapFind(0, 1);
   m_fatType = FAT_TYPE_EXFAT;
   return true;
  fail:
   return false;
 }
References mbrPartition::boot, partitionBootSector::bpb, biosParameterBlockExFat::bytesPerSectorShift, FsCache::CACHE_FOR_READ, biosParameterBlockExFat::clusterCount, biosParameterBlockExFat::clusterHeapOffset, DBG_FAIL_MACRO, FAT_TYPE_EXFAT, biosParameterBlockExFat::fatLength, biosParameterBlockExFat::fatOffset, getLe32(), partitionBootSector::oemName, masterBootRecordSector::part, mbrPartition::relativeSectors, biosParameterBlockExFat::rootDirectoryCluster, biosParameterBlockExFat::sectorsPerClusterShift, and mbrPartition::type.
Referenced by begin().
ls() [1/5]
bool ExFatVolume::ls () inline
List the directory contents of the root directory to Serial.
Returns
true for success or false for failure.
Definition at line 209 of file ExFatVolume.h.
             {
     return ls(&Serial);
   }
Referenced by ls().
ls() [2/5]
bool ExFatVolume::ls (const ExChar_t * path, uint8_t flags = 0) inline
List the directory contents of a directory to Serial.
Parameters
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 241 of file ExFatVolume.h.
{
     return ls(&Serial, path, flags);
   }
References ls().
ls() [3/5]
bool ExFatVolume::ls (print_t * pr, const ExChar_t * path, uint8_t flags) inline
List the contents of a directory.
Parameters
[in] pr Print stream for list.
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 122 of file ExFatVolume.h.
{
     ExFatFile dir;
     return dir.open(this, path, O_RDONLY) && dir.ls(pr, flags);
   }
References ExFatFile::ls(), O_RDONLY, and ExFatFile::open().
ls() [4/5]
bool ExFatVolume::ls (print_t * pr, uint8_t flags = 0) inline
List the directory contents of the root directory.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 103 of file ExFatVolume.h.
{
     return m_vwd.ls(pr, flags);
   }
References ExFatFile::ls().
ls() [5/5]
bool ExFatVolume::ls (uint8_t flags) inline
List the directory contents of the volume root to Serial.
Parameters
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 224 of file ExFatVolume.h.
{
     return ls(&Serial, flags);
   }
References ls().
mkdir() [1/2]
bool ExFatVolume::mkdir (const ExChar_t * path, bool pFlag = true) inline
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 134 of file ExFatVolume.h.
{
     ExFatFile sub;
     return sub.mkdir(vwd(), path, pFlag);
   }
References ExFatFile::mkdir().
Referenced by mkdir().
mkdir() [2/2]
bool ExFatVolume::mkdir (const String & path, bool pFlag = true) inline
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 271 of file ExFatVolume.h.
{
     return mkdir(path.c_str(), pFlag);
   }
References mkdir().
open() [1/2]
ExFile ExFatVolume::open (const ExChar_t * path, oflag_t oflag = O_RDONLY) inline
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a ExFile object.
Definition at line 144 of file ExFatVolume.h.
{
     ExFile tmpFile;
     tmpFile.open(this, path, oflag);
     return tmpFile;
   }
References ExFatFile::open().
Referenced by open().
open() [2/2]
ExFile ExFatVolume::open (const String & path, oflag_t oflag = O_RDONLY) inline
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open oflag flags.
Returns
a ExFile object.
Definition at line 280 of file ExFatVolume.h.
{
     return open(path.c_str(), oflag);
   }
References open().
printDir()
bool ExFatPartition::printDir (print_t * pr, ExFatFile * file) inherited
Definition at line 433 of file ExFatDbg.cpp.
{
   DirGeneric_t* dir = nullptr;
   DirFile_t* dirFile;
   DirStream_t* dirStream;
   DirName_t* dirName;
   uint16_t calcHash = 0;
   uint16_t nameHash = 0;
   uint16_t setChecksum = 0;
   uint16_t calcChecksum = 0;;
   uint8_t  nameLength = 0;
   uint8_t  setCount = 0;
   uint8_t  nUnicode;
 #define RAW_ROOT
 #ifndef RAW_ROOT
   while (1) {
     uint8_t buf[32];
     if (file->read(buf, 32) != 32) {
       break;
     }
     dir = reinterpret_cast<DirGeneric_t*>(buf);
 #else  // RAW_ROOT
   (void)file;
   uint32_t nDir = 1UL << (m_sectorsPerClusterShift + 4);
   uint32_t sector = clusterStartSector(m_rootDirectoryCluster);
   for (uint32_t iDir = 0; iDir < nDir; iDir++) {
     size_t i = iDir%16;
     if (i == 0) {
       uint8_t* cache = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
       if (!cache) {
         return false;
       }
       dir = reinterpret_cast<DirGeneric_t*>(cache);
     } else {
       dir++;
     }
 #endif  // RAW_ROOT
     if (dir->type == 0) {
       break;
     }
     pr->println();
     switch (dir->type) {
       case EXFAT_TYPE_BITMAP:
         printDirBitmap(pr, reinterpret_cast<DirBitmap_t*>(dir));
         break;
       case EXFAT_TYPE_UPCASE:
         printDirUpcase(pr, reinterpret_cast<DirUpcase_t*>(dir));
         break;
       case EXFAT_TYPE_LABEL:
         printDirLabel(pr, reinterpret_cast<DirLabel_t*>(dir));
         break;
       case EXFAT_TYPE_FILE:
         dirFile = reinterpret_cast<DirFile_t*>(dir);
         printDirFile(pr, dirFile);
         setCount = dirFile->setCount;
         setChecksum = getLe16(dirFile->setChecksum);
         calcChecksum = exFatDirChecksum(dir, 0);
         break;
       case EXFAT_TYPE_STREAM:
         dirStream = reinterpret_cast<DirStream_t*>(dir);
         printDirStream(pr, dirStream);
         nameLength = dirStream->nameLength;
         nameHash = getLe16(dirStream->nameHash);
         calcChecksum = exFatDirChecksum(dir, calcChecksum);
         setCount--;
         calcHash = 0;
         break;
        case EXFAT_TYPE_NAME:
         dirName = reinterpret_cast<DirName_t*>(dir);
         printDirName(pr, dirName);
         calcChecksum = exFatDirChecksum(dir, calcChecksum);
         nUnicode = nameLength > 15 ? 15 : nameLength;
         calcHash = exFatHashName(reinterpret_cast<ExChar16_t*>
                                 (dirName->unicode), nUnicode, calcHash);
         nameLength -= nUnicode;
         setCount--;
         if (nameLength == 0  || setCount == 0) {
           pr->print(F("setChecksum: 0x"));
           pr->print(setChecksum, HEX);
           if (setChecksum != calcChecksum) {
             pr->print(F(" != calcChecksum: 0x"));
           } else {
             pr->print(F(" == calcChecksum: 0x"));
           }
           pr->println(calcChecksum, HEX);
           pr->print(F("nameHash: 0x"));
           pr->print(nameHash, HEX);
           if (nameHash != calcHash) {
             pr->print(F(" != calcHash: 0x"));
           } else {
             pr->print(F(" == calcHash: 0x"));
           }
           pr->println(calcHash, HEX);
         }
         break;
       default:
         if (dir->type & 0x80) {
           pr->print(F("Unknown dirType: 0x"));
         } else {
           pr->print(F("Unused dirType: 0x"));
         }
         pr->println(dir->type, HEX);
         dmpDirData(pr, dir);
         break;
     }
   }
   pr->println(F("Done"));
   return true;
 }
References FsCache::CACHE_FOR_READ, EXFAT_TYPE_BITMAP, ExFatFile::read(), and DirGeneric_t::type.
printFat()
void ExFatPartition::printFat (print_t * pr) inherited
Definition at line 229 of file ExFatDbg.cpp.
{
   uint32_t next;
   int8_t status;
   pr->println(F("FAT:"));
   for (uint32_t cluster = 0; cluster < 16; cluster++) {
     status = fatGet(cluster, &next);
     pr->print(cluster, HEX);
     pr->write(' ');
     if (status == 0) {
       next = EXFAT_EOC;
     }
     pr->println(next, HEX);
   }
 }
References EXFAT_EOC, F, HEX, and status.
printUpcase()
void ExFatPartition::printUpcase (print_t * pr) inherited
Definition at line 550 of file ExFatDbg.cpp.
{
   uint8_t* upcase = nullptr;
   uint32_t sector;
   uint32_t size = 0;
   uint32_t checksum = 0;
   DirUpcase_t* dir;
   sector = clusterStartSector(m_rootDirectoryCluster);
   upcase = dataCacheGet(sector, FsCache::CACHE_FOR_READ);
   dir = reinterpret_cast<DirUpcase_t*>(upcase);
   if (!dir) {
     pr->println(F("read root dir failed"));
     return;
   }
   for (size_t i = 0; i < 16; i++) {
     if (dir[i].type == EXFAT_TYPE_UPCASE) {
       sector = clusterStartSector(getLe32(dir[i].firstCluster));
       size = getLe64(dir[i].size);
       break;
     }
   }
   if (!size) {
     pr->println(F("upcase not found"));
     return;
   }
   for (uint16_t i = 0; i < size/2; i++) {
     if ((i%256) == 0) {
       upcase = dataCacheGet(sector++, FsCache::CACHE_FOR_READ);
       if (!upcase) {
         pr->println(F("read upcase failed"));
         return;
       }
     }
     if (i%16 == 0) {
       pr->println();
       printHex(pr, i);
     }
     pr->write(' ');
     uint16_t uc = getLe16(&upcase[2*(i & 0XFF)]);
     printHex(pr, uc);
     checksum = upcaseChecksum(uc, checksum);
   }
   pr->println();
   pr->print(F("checksum: "));
   printHex(pr, checksum);
   pr->println();
 }
References FsCache::CACHE_FOR_READ, EXFAT_TYPE_UPCASE, F, getLe32(), and getLe64().
printVolInfo()
bool ExFatPartition::printVolInfo (print_t * pr) inherited
Definition at line 244 of file ExFatDbg.cpp.
{
   uint8_t* cache = dataCacheGet(0, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read mbr failed"));
     return false;
   }
   MbrSector_t* mbr = reinterpret_cast<MbrSector_t*>(cache);
   printMbr(pr, mbr);
   uint32_t volStart = getLe32(mbr->part->relativeSectors);
   uint32_t volSize = getLe32(mbr->part->totalSectors);
   if (volSize == 0) {
     pr->print(F("bad partition size"));
     return false;
   }
   cache = dataCacheGet(volStart, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read pbs failed"));
     return false;
   }
   printExFatBoot(pr, reinterpret_cast<pbs_t*>(cache));
   return true;
 }
References FsCache::CACHE_FOR_READ, and F.
remove() [1/2]
bool ExFatVolume::remove (const ExChar_t * path) inline
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
true for success or false for failure.
Definition at line 155 of file ExFatVolume.h.
{
     ExFatFile tmp;
     return tmp.open(this, path, O_WRONLY) && tmp.remove();
   }
References O_WRONLY, ExFatFile::open(), and ExFatFile::remove().
Referenced by remove().
remove() [2/2]
bool ExFatVolume::remove (const String & path) inline
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid name for the file.
Returns
true for success or false for failure.
Definition at line 289 of file ExFatVolume.h.
{
     return remove(path.c_str());
   }
References remove().
rename() [1/2]
bool ExFatVolume::rename (const ExChar_t * oldPath, const ExChar_t * newPath) inline
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 173 of file ExFatVolume.h.
{
     ExFatFile file;
     return file.open(vwd(), oldPath, O_RDONLY) && file.rename(vwd(), newPath);
   }
References O_RDONLY, ExFatFile::open(), and ExFatFile::rename().
Referenced by rename().
rename() [2/2]
bool ExFatVolume::rename (const String & oldPath, const String & newPath) inline
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 306 of file ExFatVolume.h.
{
     return rename(oldPath.c_str(), newPath.c_str());
   }
References rename().
rmdir() [1/2]
bool ExFatVolume::rmdir (const ExChar_t * path) inline
Remove a subdirectory from the volume's working directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 185 of file ExFatVolume.h.
{
     ExFatFile sub;
     return sub.open(this, path, O_RDONLY) && sub.rmdir();
   }
References O_RDONLY, ExFatFile::open(), and ExFatFile::rmdir().
Referenced by rmdir().
rmdir() [2/2]
bool ExFatVolume::rmdir (const String & path) inline
Remove a subdirectory from the volume's working directory.
Parameters
[in] path A path with a valid name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 317 of file ExFatVolume.h.
{
     return rmdir(path.c_str());
   }
References rmdir().
rootDirectoryCluster()
uint32_t ExFatPartition::rootDirectoryCluster () inline inherited
Returns
the root directory start cluster number.
Definition at line 161 of file ExFatPartition.h.
 {return m_rootDirectoryCluster;}
Referenced by ExFatFile::read(), and ExFatFile::seekSet().
rootLength()
uint32_t ExFatPartition::rootLength () inherited
Returns
the root directory length.
Definition at line 373 of file ExFatPartition.cpp.
{
   uint32_t nc = chainSize(m_rootDirectoryCluster);
   return nc << bytesPerClusterShift();
 }
References ExFatPartition::bytesPerClusterShift().
sectorsPerCluster()
uint32_t ExFatPartition::sectorsPerCluster () inline inherited
Returns
the number of sectors in a cluster.
Definition at line 165 of file ExFatPartition.h.
 {return 1UL << m_sectorsPerClusterShift;}
Referenced by ExFatPartition::blocksPerCluster(), ExFatFile::read(), FsVolume::sectorsPerCluster(), and ExFatFile::write().
sectorsPerClusterShift()
uint8_t ExFatPartition::sectorsPerClusterShift () inline inherited
Returns
the power of two for sectors per cluster.
Definition at line 171 of file ExFatPartition.h.
 {return m_sectorsPerClusterShift;}
truncate() [1/2]
bool ExFatVolume::truncate (const ExChar_t * path, uint64_t length) inline
Truncate a file to a specified length. The current file position will be at the new EOF.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 197 of file ExFatVolume.h.
{
     ExFatFile file;
     if (!file.open(this, path, O_WRONLY)) {
       return false;
     }
     return file.truncate(length);
   }
References O_WRONLY, ExFatFile::open(), and ExFatFile::truncate().
Referenced by truncate().
truncate() [2/2]
bool ExFatVolume::truncate (const String & path, uint64_t length) inline
Truncate a file to a specified length. The current file position will be at the new EOF.
Parameters
[in] path A path with a valid name for the file.
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 328 of file ExFatVolume.h.
{
     return truncate(path.c_str(), length);
   }
References truncate().
The documentation for this class was generated from the following files:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/ExFatVolume.h
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/ExFatLib/ExFatVolume.cpp