ERIS CORE: wren_value.h File Reference
wren_value.h File Reference
#include <stdbool.h>
#include <string.h>
#include "wren_common.h"
#include "wren_math.h"
#include "wren_utils.h"
Classes
struct CallFrame
struct FnDebug
struct MapEntry
struct Method
struct ObjClosure
struct ObjFn
struct ObjForeign
struct ObjInstance
struct ObjList
struct ObjMap
struct ObjModule
struct ObjRange
struct sObj
struct sObjClass
struct sObjFiber
struct sObjString
struct sObjUpvalue
Macros
#define AS_BOOL(value) ((value) == TRUE_VAL)
#define AS_CLASS(value) ((ObjClass*)AS_OBJ(value))
#define AS_CLOSURE(value) ((ObjClosure*)AS_OBJ(value))
#define AS_CSTRING(v) (AS_STRING(v)->value)
#define AS_FIBER(v) ((ObjFiber*)AS_OBJ(v))
#define AS_FN(value) ((ObjFn*)AS_OBJ(value))
#define AS_FOREIGN(v) ((ObjForeign*)AS_OBJ(v))
#define AS_INSTANCE(value) ((ObjInstance*)AS_OBJ(value))
#define AS_LIST(value) ((ObjList*)AS_OBJ(value))
#define AS_MAP(value) ((ObjMap*)AS_OBJ(value))
#define AS_MODULE(value) ((ObjModule*)AS_OBJ(value))
#define AS_NUM(value) (wrenValueToNum(value))
#define AS_OBJ(value) ((Obj*)(uintptr_t)((value) & ~(SIGN_BIT | QNAN)))
#define AS_RANGE(v) ((ObjRange*)AS_OBJ(v))
#define AS_STRING(v) ((ObjString*)AS_OBJ(v))
#define BOOL_VAL(boolean) ((boolean) ? TRUE_VAL : FALSE_VAL)
#define CONST_STRING(vm, text) wrenNewStringLength((vm), (text), sizeof(text) - 1)
#define FALSE_VAL ((Value)(uint64_t)(QNAN | TAG_FALSE))
#define GET_TAG(value) ((int)((value) & MASK_TAG))
#define IS_BOOL(value) (wrenIsBool(value))
#define IS_CLASS(value) (wrenIsObjType(value, OBJ_CLASS))
#define IS_CLOSURE(value) (wrenIsObjType(value, OBJ_CLOSURE))
#define IS_FALSE(value) ((value) == FALSE_VAL)
#define IS_FIBER(value) (wrenIsObjType(value, OBJ_FIBER))
#define IS_FN(value) (wrenIsObjType(value, OBJ_FN))
#define IS_FOREIGN(value) (wrenIsObjType(value, OBJ_FOREIGN))
#define IS_INSTANCE(value) (wrenIsObjType(value, OBJ_INSTANCE))
#define IS_LIST(value) (wrenIsObjType(value, OBJ_LIST))
#define IS_MAP(value) (wrenIsObjType(value, OBJ_MAP))
#define IS_NULL(value) ((value) == NULL_VAL)
#define IS_NUM(value) (((value) & QNAN) != QNAN)
#define IS_OBJ(value) (((value) & (QNAN | SIGN_BIT)) == (QNAN | SIGN_BIT))
#define IS_RANGE(value) (wrenIsObjType(value, OBJ_RANGE))
#define IS_STRING(value) (wrenIsObjType(value, OBJ_STRING))
#define IS_UNDEFINED(value) ((value) == UNDEFINED_VAL)
#define MASK_TAG (7)
#define NULL_VAL ((Value)(uint64_t)(QNAN | TAG_NULL))
#define NUM_VAL(num) (wrenNumToValue(num))
#define OBJ_VAL(obj) (wrenObjectToValue((Obj*)(obj)))
#define QNAN ((uint64_t)0x7ffc000000000000)
#define SIGN_BIT ((uint64_t)1 << 63)
#define TAG_FALSE (2)
#define TAG_NAN (0)
#define TAG_NULL (1)
#define TAG_TRUE (3)
#define TAG_UNDEFINED (4)
#define TAG_UNUSED2 (5)
#define TAG_UNUSED3 (6)
#define TAG_UNUSED4 (7)
#define TRUE_VAL ((Value)(uint64_t)(QNAN | TAG_TRUE))
#define UNDEFINED_VAL ((Value)(uint64_t)(QNAN | TAG_UNDEFINED))
Typedefs
typedef struct sObj Obj
typedef struct sObjClass ObjClass
typedef struct sObjFiber ObjFiber
typedef struct sObjUpvalue ObjUpvalue
typedef bool(* Primitive) (WrenVM *vm, Value *args)
typedef uint64_t Value
Enumerations
enum FiberState { FIBER_TRY , FIBER_ROOT , FIBER_OTHER }
enum MethodType {
METHOD_PRIMITIVE , METHOD_FUNCTION_CALL , METHOD_FOREIGN , METHOD_BLOCK ,
METHOD_NONE
}
enum ObjType {
OBJ_CLASS , OBJ_CLOSURE , OBJ_FIBER , OBJ_FN ,
OBJ_FOREIGN , OBJ_INSTANCE , OBJ_LIST , OBJ_MAP ,
OBJ_MODULE , OBJ_RANGE , OBJ_STRING , OBJ_UPVALUE
}
Functions
DECLARE_BUFFER (Method, Method)
DECLARE_BUFFER (Value, Value)
static void wrenAppendCallFrame (WrenVM *vm, ObjFiber *fiber, ObjClosure *closure, Value *stackStart)
void wrenBindMethod (WrenVM *vm, ObjClass *classObj, int symbol, Method method)
void wrenBindSuperclass (WrenVM *vm, ObjClass *subclass, ObjClass *superclass)
void wrenBlackenObjects (WrenVM *vm)
void wrenEnsureStack (WrenVM *vm, ObjFiber *fiber, int needed)
void wrenFreeObj (WrenVM *vm, Obj *obj)
void wrenFunctionBindName (WrenVM *vm, ObjFn *fn, const char *name, int length)
ObjClass * wrenGetClass (WrenVM *vm, Value value)
void wrenGrayBuffer (WrenVM *vm, ValueBuffer *buffer)
void wrenGrayObj (WrenVM *vm, Obj *obj)
void wrenGrayValue (WrenVM *vm, Value value)
static bool wrenHasError (const ObjFiber *fiber)
static bool wrenIsBool (Value value)
static bool wrenIsObjType (Value value, ObjType type)
int wrenListIndexOf (WrenVM *vm, ObjList *list, Value value)
void wrenListInsert (WrenVM *vm, ObjList *list, Value value, uint32_t index)
Value wrenListRemoveAt (WrenVM *vm, ObjList *list, uint32_t index)
void wrenMapClear (WrenVM *vm, ObjMap *map)
Value wrenMapGet (ObjMap *map, Value key)
static bool wrenMapIsValidKey (Value arg)
Value wrenMapRemoveKey (WrenVM *vm, ObjMap *map, Value key)
void wrenMapSet (WrenVM *vm, ObjMap *map, Value key, Value value)
ObjClass * wrenNewClass (WrenVM *vm, ObjClass *superclass, int numFields, ObjString *name)
ObjClosure * wrenNewClosure (WrenVM *vm, ObjFn *fn)
ObjFiber * wrenNewFiber (WrenVM *vm, ObjClosure *closure)
ObjForeign * wrenNewForeign (WrenVM *vm, ObjClass *classObj, size_t size)
ObjFn * wrenNewFunction (WrenVM *vm, ObjModule *module, int maxSlots)
Value wrenNewInstance (WrenVM *vm, ObjClass *classObj)
ObjList * wrenNewList (WrenVM *vm, uint32_t numElements)
ObjMap * wrenNewMap (WrenVM *vm)
ObjModule * wrenNewModule (WrenVM *vm, ObjString *name)
Value wrenNewRange (WrenVM *vm, double from, double to, bool isInclusive)
ObjClass * wrenNewSingleClass (WrenVM *vm, int numFields, ObjString *name)
Value wrenNewString (WrenVM *vm, const char *text)
Value wrenNewStringFromRange (WrenVM *vm, ObjString *source, int start, uint32_t count, int step)
Value wrenNewStringLength (WrenVM *vm, const char *text, size_t length)
ObjUpvalue * wrenNewUpvalue (WrenVM *vm, Value *value)
Value wrenNumToString (WrenVM *vm, double value)
static Value wrenNumToValue (double num)
static Value wrenObjectToValue (Obj *obj)
Value wrenStringCodePointAt (WrenVM *vm, ObjString *string, uint32_t index)
static bool wrenStringEqualsCString (const ObjString *a, const char *b, size_t length)
uint32_t wrenStringFind (ObjString *haystack, ObjString *needle, uint32_t startIndex)
Value wrenStringFormat (WrenVM *vm, const char *format,...)
Value wrenStringFromByte (WrenVM *vm, uint8_t value)
Value wrenStringFromCodePoint (WrenVM *vm, int value)
bool wrenValuesEqual (Value a, Value b)
static bool wrenValuesSame (Value a, Value b)
static double wrenValueToNum (Value value)
Macro Definition Documentation
AS_BOOL
#define AS_BOOL (value) ((value) == TRUE_VAL)
Definition at line 582 of file wren_value.h.
AS_CLASS
#define AS_CLASS (value) ((ObjClass*)AS_OBJ(value))
Definition at line 49 of file wren_value.h.
AS_CLOSURE
#define AS_CLOSURE (value) ((ObjClosure*)AS_OBJ(value))
Definition at line 50 of file wren_value.h.
AS_CSTRING
#define AS_CSTRING (v) (AS_STRING(v)->value)
Definition at line 61 of file wren_value.h.
AS_FIBER
#define AS_FIBER (v) ((ObjFiber*)AS_OBJ(v))
Definition at line 51 of file wren_value.h.
AS_FN
#define AS_FN (value) ((ObjFn*)AS_OBJ(value))
Definition at line 52 of file wren_value.h.
AS_FOREIGN
#define AS_FOREIGN (v) ((ObjForeign*)AS_OBJ(v))
Definition at line 53 of file wren_value.h.
AS_INSTANCE
#define AS_INSTANCE (value) ((ObjInstance*)AS_OBJ(value))
Definition at line 54 of file wren_value.h.
AS_LIST
#define AS_LIST (value) ((ObjList*)AS_OBJ(value))
Definition at line 55 of file wren_value.h.
AS_MAP
#define AS_MAP (value) ((ObjMap*)AS_OBJ(value))
Definition at line 56 of file wren_value.h.
AS_MODULE
#define AS_MODULE (value) ((ObjModule*)AS_OBJ(value))
Definition at line 57 of file wren_value.h.
AS_NUM
#define AS_NUM (value) (wrenValueToNum(value))
Definition at line 58 of file wren_value.h.
AS_OBJ
#define AS_OBJ (value) ((Obj*)(uintptr_t)((value) & ~(SIGN_BIT | QNAN)))
Definition at line 585 of file wren_value.h.
AS_RANGE
#define AS_RANGE (v) ((ObjRange*)AS_OBJ(v))
Definition at line 59 of file wren_value.h.
AS_STRING
#define AS_STRING (v) ((ObjString*)AS_OBJ(v))
Definition at line 60 of file wren_value.h.
BOOL_VAL
#define BOOL_VAL (boolean) ((boolean) ? TRUE_VAL : FALSE_VAL)
Definition at line 66 of file wren_value.h.
CONST_STRING
#define CONST_STRING (vm, text) wrenNewStringLength((vm), (text), sizeof(text) - 1)
Definition at line 87 of file wren_value.h.
FALSE_VAL
#define FALSE_VAL ((Value)(uint64_t)(QNAN | TAG_FALSE))
Definition at line 589 of file wren_value.h.
GET_TAG
#define GET_TAG (value) ((int)((value) & MASK_TAG))
Definition at line 594 of file wren_value.h.
IS_BOOL
#define IS_BOOL (value) (wrenIsBool(value))
Definition at line 72 of file wren_value.h.
IS_CLASS
#define IS_CLASS (value) (wrenIsObjType(value, OBJ_CLASS))
Definition at line 73 of file wren_value.h.
IS_CLOSURE
#define IS_CLOSURE (value) (wrenIsObjType(value, OBJ_CLOSURE))
Definition at line 74 of file wren_value.h.
IS_FALSE
#define IS_FALSE (value) ((value) == FALSE_VAL)
Definition at line 564 of file wren_value.h.
IS_FIBER
#define IS_FIBER (value) (wrenIsObjType(value, OBJ_FIBER))
Definition at line 75 of file wren_value.h.
IS_FN
#define IS_FN (value) (wrenIsObjType(value, OBJ_FN))
Definition at line 76 of file wren_value.h.
IS_FOREIGN
#define IS_FOREIGN (value) (wrenIsObjType(value, OBJ_FOREIGN))
Definition at line 77 of file wren_value.h.
IS_INSTANCE
#define IS_INSTANCE (value) (wrenIsObjType(value, OBJ_INSTANCE))
Definition at line 78 of file wren_value.h.
IS_LIST
#define IS_LIST (value) (wrenIsObjType(value, OBJ_LIST))
Definition at line 79 of file wren_value.h.
IS_MAP
#define IS_MAP (value) (wrenIsObjType(value, OBJ_MAP))
Definition at line 80 of file wren_value.h.
IS_NULL
#define IS_NULL (value) ((value) == NULL_VAL)
Definition at line 565 of file wren_value.h.
IS_NUM
#define IS_NUM (value) (((value) & QNAN) != QNAN)
Definition at line 559 of file wren_value.h.
IS_OBJ
#define IS_OBJ (value) (((value) & (QNAN | SIGN_BIT)) == (QNAN | SIGN_BIT))
Definition at line 562 of file wren_value.h.
IS_RANGE
#define IS_RANGE (value) (wrenIsObjType(value, OBJ_RANGE))
Definition at line 81 of file wren_value.h.
IS_STRING
#define IS_STRING (value) (wrenIsObjType(value, OBJ_STRING))
Definition at line 82 of file wren_value.h.
IS_UNDEFINED
#define IS_UNDEFINED (value) ((value) == UNDEFINED_VAL)
Definition at line 566 of file wren_value.h.
MASK_TAG
#define MASK_TAG (7)
Definition at line 569 of file wren_value.h.
NULL_VAL
#define NULL_VAL ((Value)(uint64_t)(QNAN | TAG_NULL))
Definition at line 588 of file wren_value.h.
NUM_VAL
#define NUM_VAL (num) (wrenNumToValue(num))
Definition at line 67 of file wren_value.h.
OBJ_VAL
#define OBJ_VAL (obj) (wrenObjectToValue((Obj*)(obj)))
Definition at line 68 of file wren_value.h.
QNAN
#define QNAN ((uint64_t)0x7ffc000000000000)
Definition at line 556 of file wren_value.h.
SIGN_BIT
#define SIGN_BIT ((uint64_t)1 << 63)
Definition at line 553 of file wren_value.h.
TAG_FALSE
#define TAG_FALSE (2)
Definition at line 574 of file wren_value.h.
TAG_NAN
#define TAG_NAN (0)
Definition at line 572 of file wren_value.h.
TAG_NULL
#define TAG_NULL (1)
Definition at line 573 of file wren_value.h.
TAG_TRUE
#define TAG_TRUE (3)
Definition at line 575 of file wren_value.h.
TAG_UNDEFINED
#define TAG_UNDEFINED (4)
Definition at line 576 of file wren_value.h.
TAG_UNUSED2
#define TAG_UNUSED2 (5)
Definition at line 577 of file wren_value.h.
TAG_UNUSED3
#define TAG_UNUSED3 (6)
Definition at line 578 of file wren_value.h.
TAG_UNUSED4
#define TAG_UNUSED4 (7)
Definition at line 579 of file wren_value.h.
TRUE_VAL
#define TRUE_VAL ((Value)(uint64_t)(QNAN | TAG_TRUE))
Definition at line 590 of file wren_value.h.
UNDEFINED_VAL
#define UNDEFINED_VAL ((Value)(uint64_t)(QNAN | TAG_UNDEFINED))
Definition at line 591 of file wren_value.h.
Typedef Documentation
Obj
typedef struct sObj Obj
Definition at line 1 of file wren_value.h.
ObjClass
typedef struct sObjClass ObjClass
Definition at line 1 of file wren_value.h.
ObjFiber
typedef struct sObjFiber ObjFiber
ObjUpvalue
typedef struct sObjUpvalue ObjUpvalue
Primitive
typedef bool(* Primitive) (WrenVM *vm, Value *args)
Definition at line 203 of file wren_value.h.
Value
typedef uint64_t Value
Definition at line 123 of file wren_value.h.
Enumeration Type Documentation
FiberState
enum FiberState
Enumerator
FIBER_TRY
FIBER_ROOT
FIBER_OTHER
Definition at line 300 of file wren_value.h.
 {
   // The fiber is being run from another fiber using a call to `try()`.
   FIBER_TRY,
   // The fiber was directly invoked by `runInterpreter()`. This means it's the
   // initial fiber used by a call to `wrenCall()` or `wrenInterpret()`.
   FIBER_ROOT,
   // The fiber is invoked some other way. If [caller] is `NULL` then the fiber
   // was invoked using `call()`. If [numFrames] is zero, then the fiber has
   // finished running and is done. If [numFrames] is one and that frame's `ip`
   // points to the first byte of code, the fiber has not been started yet.
   FIBER_OTHER,
 } FiberState;
MethodType
enum MethodType
Enumerator
METHOD_PRIMITIVE
METHOD_FUNCTION_CALL
METHOD_FOREIGN
METHOD_BLOCK
METHOD_NONE
Definition at line 357 of file wren_value.h.
 {
   // A primitive method implemented in C in the VM. Unlike foreign methods,
   // this can directly manipulate the fiber's stack.
   METHOD_PRIMITIVE,
   // A primitive that handles .call on Fn.
   METHOD_FUNCTION_CALL,
   // A externally-defined C method.
   METHOD_FOREIGN,
   // A normal user-defined method.
   METHOD_BLOCK,
   // No method for the given symbol.
   METHOD_NONE
 } MethodType;
ObjType
enum ObjType
Enumerator
OBJ_CLASS
OBJ_CLOSURE
OBJ_FIBER
OBJ_FN
OBJ_FOREIGN
OBJ_INSTANCE
OBJ_LIST
OBJ_MAP
OBJ_MODULE
OBJ_RANGE
OBJ_STRING
OBJ_UPVALUE
Definition at line 90 of file wren_value.h.
              {
   OBJ_CLASS,
   OBJ_CLOSURE,
   OBJ_FIBER,
   OBJ_FN,
   OBJ_FOREIGN,
   OBJ_INSTANCE,
   OBJ_LIST,
   OBJ_MAP,
   OBJ_MODULE,
   OBJ_RANGE,
   OBJ_STRING,
   OBJ_UPVALUE
 } ObjType;
Function Documentation
DECLARE_BUFFER() [1/2]
DECLARE_BUFFER (Method , Method)
DECLARE_BUFFER() [2/2]
DECLARE_BUFFER (Value , Value)
wrenAppendCallFrame()
static void wrenAppendCallFrame (WrenVM * vm, ObjFiber * fiber, ObjClosure * closure, Value * stackStart) inline static
Definition at line 645 of file wren_value.h.
 {
   // The caller should have ensured we already have enough capacity.
   ASSERT(fiber->frameCapacity > fiber->numFrames, "No memory for call frame.");
   CallFrame* frame = &fiber->frames[fiber->numFrames++];
   frame->stackStart = stackStart;
   frame->closure = closure;
   frame->ip = closure->fn->code.data;
 }
References ASSERT, CallFrame::closure, ObjFn::code, fiber, ObjClosure::fn, CallFrame::ip, and CallFrame::stackStart.
Referenced by wrenCallFunction(), and wrenNewFiber().
wrenBindMethod()
void wrenBindMethod (WrenVM * vm, ObjClass * classObj, int symbol, Method method)
Definition at line 120 of file wren_value.c.
 {
   // Make sure the buffer is big enough to contain the symbol's index.
   if (symbol >= classObj->methods.count)
   {
     Method noMethod;
     noMethod.type = METHOD_NONE;
     wrenMethodBufferFill(vm, &classObj->methods, noMethod,
                          symbol - classObj->methods.count + 1);
   }
   classObj->methods.data[symbol] = method;
 }
References method(), METHOD_NONE, sObjClass::methods, and Method::type.
Referenced by bindForeignClass(), bindMethod(), and wrenBindSuperclass().
wrenBindSuperclass()
void wrenBindSuperclass (WrenVM * vm, ObjClass * subclass, ObjClass * superclass)
Definition at line 62 of file wren_value.c.
 {
   ASSERT(superclass != NULL, "Must have superclass.");
   subclass->superclass = superclass;
   // Include the superclass in the total number of fields.
   if (subclass->numFields != -1)
   {
     subclass->numFields += superclass->numFields;
   }
   else
   {
     ASSERT(superclass->numFields == 0,
            "A foreign class cannot inherit from a class with fields.");
   }
   // Inherit methods from its superclass.
   for (int i = 0; i < superclass->methods.count; i++)
   {
     wrenBindMethod(vm, subclass, i, superclass->methods.data[i]);
   }
 }
References ASSERT, sObjClass::methods, NULL, sObjClass::numFields, sObjClass::superclass, and wrenBindMethod().
Referenced by wrenInitializeCore(), and wrenNewClass().
wrenBlackenObjects()
void wrenBlackenObjects (WrenVM * vm)
Definition at line 1216 of file wren_value.c.
 {
   while (vm->grayCount > 0)
   {
     // Pop an item from the gray stack.
     Obj* obj = vm->gray[--vm->grayCount];
     blackenObject(vm, obj);
   }
 }
References blackenObject(), WrenVM::gray, and WrenVM::grayCount.
Referenced by wrenCollectGarbage().
wrenEnsureStack()
void wrenEnsureStack (WrenVM * vm, ObjFiber * fiber, int needed)
Definition at line 190 of file wren_value.c.
 {
   if (fiber->stackCapacity >= needed) return;
   int capacity = wrenPowerOf2Ceil(needed);
   Value* oldStack = fiber->stack;
   fiber->stack = (Value*)wrenReallocate(vm, fiber->stack,
                                         sizeof(Value) * fiber->stackCapacity,
                                         sizeof(Value) * capacity);
   fiber->stackCapacity = capacity;
   // If the reallocation moves the stack, then we need to recalculate every
   // pointer that points into the old stack to into the same relative distance
   // in the new stack. We have to be a little careful about how these are
   // calculated because pointer subtraction is only well-defined within a
   // single array, hence the slightly redundant-looking arithmetic below.
   if (fiber->stack != oldStack)
   {
     // Top of the stack.
     if (vm->apiStack >= oldStack && vm->apiStack <= fiber->stackTop)
     {
       vm->apiStack = fiber->stack + (vm->apiStack - oldStack);
     }
     // Stack pointer for each call frame.
     for (int i = 0; i < fiber->numFrames; i++)
     {
       CallFrame* frame = &fiber->frames[i];
       frame->stackStart = fiber->stack + (frame->stackStart - oldStack);
     }
     // Open upvalues.
     for (ObjUpvalue* upvalue = fiber->openUpvalues;
          upvalue != NULL;
          upvalue = upvalue->next)
     {
       upvalue->value = fiber->stack + (upvalue->value - oldStack);
     }
     fiber->stackTop = fiber->stack + (fiber->stackTop - oldStack);
   }
 }
References WrenVM::apiStack, fiber, NULL, CallFrame::stackStart, wrenPowerOf2Ceil(), and wrenReallocate().
Referenced by wrenCallFunction(), and wrenEnsureSlots().
wrenFreeObj()
void wrenFreeObj (WrenVM * vm, Obj * obj)
Definition at line 1226 of file wren_value.c.
 {
 #if WREN_DEBUG_TRACE_MEMORY
   printf("free ");
   wrenDumpValue(OBJ_VAL(obj));
   printf(" @ %p\n", obj);
 #endif
   switch (obj->type)
   {
     case OBJ_CLASS:
       wrenMethodBufferClear(vm, &((ObjClass*)obj)->methods);
       break;
     case OBJ_FIBER:
     {
       ObjFiber* fiber = (ObjFiber*)obj;
       DEALLOCATE(vm, fiber->frames);
       DEALLOCATE(vm, fiber->stack);
       break;
     }
     case OBJ_FN:
     {
       ObjFn* fn = (ObjFn*)obj;
       wrenValueBufferClear(vm, &fn->constants);
       wrenByteBufferClear(vm, &fn->code);
       wrenIntBufferClear(vm, &fn->debug->sourceLines);
       DEALLOCATE(vm, fn->debug->name);
       DEALLOCATE(vm, fn->debug);
       break;
     }
     case OBJ_FOREIGN:
       wrenFinalizeForeign(vm, (ObjForeign*)obj);
       break;
     case OBJ_LIST:
       wrenValueBufferClear(vm, &((ObjList*)obj)->elements);
       break;
     case OBJ_MAP:
       DEALLOCATE(vm, ((ObjMap*)obj)->entries);
       break;
     case OBJ_MODULE:
       wrenSymbolTableClear(vm, &((ObjModule*)obj)->variableNames);
       wrenValueBufferClear(vm, &((ObjModule*)obj)->variables);
       break;
     case OBJ_CLOSURE:
     case OBJ_INSTANCE:
     case OBJ_RANGE:
     case OBJ_STRING:
     case OBJ_UPVALUE:
       break;
   }
   DEALLOCATE(vm, obj);
 }
References DEALLOCATE, fiber, fn, OBJ_CLASS, OBJ_CLOSURE, OBJ_FIBER, OBJ_FN, OBJ_FOREIGN, OBJ_INSTANCE, OBJ_LIST, OBJ_MAP, OBJ_MODULE, OBJ_RANGE, OBJ_STRING, OBJ_UPVALUE, OBJ_VAL, sObj::type, wrenDumpValue(), wrenFinalizeForeign(), and wrenSymbolTableClear().
Referenced by wrenCollectGarbage(), and wrenFreeVM().
wrenFunctionBindName()
void wrenFunctionBindName (WrenVM * vm, ObjFn * fn, const char * name, int length)
Definition at line 264 of file wren_value.c.
 {
   fn->debug->name = ALLOCATE_ARRAY(vm, char, length + 1);
   memcpy(fn->debug->name, name, length);
   fn->debug->name[length] = '\0';
 }
References ALLOCATE_ARRAY, fn, and name.
Referenced by endCompiler(), and wrenMakeCallHandle().
wrenGetClass()
ObjClass* wrenGetClass (WrenVM * vm, Value value)
Definition at line 1287 of file wren_value.c.
 {
   return wrenGetClassInline(vm, value);
 }
References wrenGetClassInline().
Referenced by DEF_PRIMITIVE().
wrenGrayBuffer()
void wrenGrayBuffer (WrenVM * vm, ValueBuffer * buffer)
Definition at line 1005 of file wren_value.c.
 {
   for (int i = 0; i < buffer->count; i++)
   {
     wrenGrayValue(vm, buffer->data[i]);
   }
 }
References wrenGrayValue().
Referenced by blackenFn(), and blackenList().
wrenGrayObj()
void wrenGrayObj (WrenVM * vm, Obj * obj)
Definition at line 976 of file wren_value.c.
 {
   if (obj == NULL) return;
   // Stop if the object is already darkened so we don't get stuck in a cycle.
   if (obj->isDark) return;
   // It's been reached.
   obj->isDark = true;
   // Add it to the gray list so it can be recursively explored for
   // more marks later.
   if (vm->grayCount >= vm->grayCapacity)
   {
     vm->grayCapacity = vm->grayCount * 2;
     vm->gray = (Obj**)vm->config.reallocateFn(vm->gray,
                                               vm->grayCapacity * sizeof(Obj*),
                                               vm->config.userData);
   }
   vm->gray[vm->grayCount++] = obj;
 }
References WrenVM::config, WrenVM::gray, WrenVM::grayCapacity, WrenVM::grayCount, sObj::isDark, NULL, WrenConfiguration::reallocateFn, and WrenConfiguration::userData.
Referenced by blackenClass(), blackenClosure(), blackenFiber(), blackenInstance(), blackenModule(), wrenBlackenSymbolTable(), wrenCollectGarbage(), wrenGrayValue(), and wrenMarkCompiler().
wrenGrayValue()
void wrenGrayValue (WrenVM * vm, Value value)
Definition at line 999 of file wren_value.c.
 {
   if (!IS_OBJ(value)) return;
   wrenGrayObj(vm, AS_OBJ(value));
 }
References AS_OBJ, IS_OBJ, and wrenGrayObj().
Referenced by blackenFiber(), blackenInstance(), blackenMap(), blackenModule(), blackenUpvalue(), wrenCollectGarbage(), wrenGrayBuffer(), and wrenMarkCompiler().
wrenHasError()
static bool wrenHasError (const ObjFiber * fiber) inline static
Definition at line 660 of file wren_value.h.
 {
   return !IS_NULL(fiber->error);
 }
References fiber, and IS_NULL.
Referenced by createClass(), DEF_PRIMITIVE(), runFiber(), runInterpreter(), and runtimeError().
wrenIsBool()
static bool wrenIsBool (Value value) inline static
Definition at line 823 of file wren_value.h.
 {
 #if WREN_NAN_TAGGING
   return value == TRUE_VAL || value == FALSE_VAL;
 #else
   return value.type == VAL_FALSE || value.type == VAL_TRUE;
 #endif
 }
References FALSE_VAL, and TRUE_VAL.
wrenIsObjType()
static bool wrenIsObjType (Value value, ObjType type) inline static
Definition at line 834 of file wren_value.h.
 {
   return IS_OBJ(value) && AS_OBJ(value)->type == type;
 }
References AS_OBJ, and IS_OBJ.
wrenListIndexOf()
int wrenListIndexOf (WrenVM * vm, ObjList * list, Value value)
Definition at line 323 of file wren_value.c.
 {
   int count = list->elements.count;
   for (int i = 0; i < count; i++)
   {
     Value item = list->elements.data[i];
     if(wrenValuesEqual(item, value)) {
       return i;
     }
   }
   return -1;
 }
References count, list(), and wrenValuesEqual().
Referenced by DEF_PRIMITIVE().
wrenListInsert()
void wrenListInsert (WrenVM * vm, ObjList * list, Value value, uint32_t index)
Definition at line 304 of file wren_value.c.
 {
   if (IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   // Add a slot at the end of the list.
   wrenValueBufferWrite(vm, &list->elements, NULL_VAL);
   if (IS_OBJ(value)) wrenPopRoot(vm);
   // Shift the existing elements down.
   for (uint32_t i = list->elements.count - 1; i > index; i--)
   {
     list->elements.data[i] = list->elements.data[i - 1];
   }
   // Store the new element.
   list->elements.data[index] = value;
 }
References AS_OBJ, IS_OBJ, list(), NULL_VAL, wrenPopRoot(), and wrenPushRoot().
Referenced by DEF_PRIMITIVE(), and wrenInsertInList().
wrenListRemoveAt()
Value wrenListRemoveAt (WrenVM * vm, ObjList * list, uint32_t index)
Definition at line 336 of file wren_value.c.
 {
   Value removed = list->elements.data[index];
   if (IS_OBJ(removed)) wrenPushRoot(vm, AS_OBJ(removed));
   // Shift items up.
   for (int i = index; i < list->elements.count - 1; i++)
   {
     list->elements.data[i] = list->elements.data[i + 1];
   }
   // If we have too much excess capacity, shrink it.
   if (list->elements.capacity / GROW_FACTOR >= list->elements.count)
   {
     list->elements.data = (Value*)wrenReallocate(vm, list->elements.data,
         sizeof(Value) * list->elements.capacity,
         sizeof(Value) * (list->elements.capacity / GROW_FACTOR));
     list->elements.capacity /= GROW_FACTOR;
   }
   if (IS_OBJ(removed)) wrenPopRoot(vm);
   list->elements.count--;
   return removed;
 }
References AS_OBJ, GROW_FACTOR, IS_OBJ, list(), wrenPopRoot(), wrenPushRoot(), and wrenReallocate().
Referenced by DEF_PRIMITIVE().
wrenMapClear()
void wrenMapClear (WrenVM * vm, ObjMap * map)
Definition at line 601 of file wren_value.c.
 {
   DEALLOCATE(vm, map->entries);
   map->entries = NULL;
   map->capacity = 0;
   map->count = 0;
 }
References DEALLOCATE, map(), and NULL.
Referenced by copyAttributes(), DEF_PRIMITIVE(), disallowAttributes(), and wrenMapRemoveKey().
wrenMapGet()
Value wrenMapGet (ObjMap * map, Value key)
Definition at line 574 of file wren_value.c.
 {
   MapEntry* entry;
   if (findEntry(map->entries, map->capacity, key, &entry)) return entry->value;
   return UNDEFINED_VAL;
 }
References findEntry(), map(), UNDEFINED_VAL, and MapEntry::value.
Referenced by addConstant(), addToAttributeGroup(), DEF_PRIMITIVE(), getModule(), importModule(), metaGetModuleVariables(), wrenGetMapContainsKey(), and wrenGetMapValue().
wrenMapIsValidKey()
static bool wrenMapIsValidKey (Value arg) inline static
Definition at line 880 of file wren_value.h.
 {
   return IS_BOOL(arg)
       || IS_CLASS(arg)
       || IS_NULL(arg)
       || IS_NUM(arg)
       || IS_RANGE(arg)
       || IS_STRING(arg);
 }
References IS_BOOL, IS_CLASS, IS_NULL, IS_NUM, IS_RANGE, and IS_STRING.
Referenced by validateKey(), wrenGetMapContainsKey(), and wrenSetMapValue().
wrenMapRemoveKey()
Value wrenMapRemoveKey (WrenVM * vm, ObjMap * map, Value key)
Definition at line 609 of file wren_value.c.
 {
   MapEntry* entry;
   if (!findEntry(map->entries, map->capacity, key, &entry)) return NULL_VAL;
   // Remove the entry from the map. Set this value to true, which marks it as a
   // deleted slot. When searching for a key, we will stop on empty slots, but
   // continue past deleted slots.
   Value value = entry->value;
   entry->key = UNDEFINED_VAL;
   entry->value = TRUE_VAL;
   if (IS_OBJ(value)) wrenPushRoot(vm, AS_OBJ(value));
   map->count--;
   if (map->count == 0)
   {
     // Removed the last item, so free the array.
     wrenMapClear(vm, map);
   }
   else if (map->capacity > MIN_CAPACITY &&
            map->count < map->capacity / GROW_FACTOR * MAP_LOAD_PERCENT / 100)
   {
     uint32_t capacity = map->capacity / GROW_FACTOR;
     if (capacity < MIN_CAPACITY) capacity = MIN_CAPACITY;
     // The map is getting empty, so shrink the entry array back down.
     // TODO: Should we do this less aggressively than we grow?
     resizeMap(vm, map, capacity);
   }
   if (IS_OBJ(value)) wrenPopRoot(vm);
   return value;
 }
References AS_OBJ, findEntry(), GROW_FACTOR, IS_OBJ, MapEntry::key, map(), MAP_LOAD_PERCENT, MIN_CAPACITY, NULL_VAL, resizeMap(), TRUE_VAL, UNDEFINED_VAL, MapEntry::value, wrenMapClear(), wrenPopRoot(), and wrenPushRoot().
Referenced by DEF_PRIMITIVE(), and wrenRemoveMapValue().
wrenMapSet()
void wrenMapSet (WrenVM * vm, ObjMap * map, Value key, Value value)
Definition at line 582 of file wren_value.c.
 {
   // If the map is getting too full, make room first.
   if (map->count + 1 > map->capacity * MAP_LOAD_PERCENT / 100)
   {
     // Figure out the new hash table size.
     uint32_t capacity = map->capacity * GROW_FACTOR;
     if (capacity < MIN_CAPACITY) capacity = MIN_CAPACITY;
     resizeMap(vm, map, capacity);
   }
   if (insertEntry(map->entries, map->capacity, key, value))
   {
     // A new key was added.
     map->count++;
   }
 }
References GROW_FACTOR, insertEntry(), map(), MAP_LOAD_PERCENT, MIN_CAPACITY, and resizeMap().
Referenced by addConstant(), addToAttributeGroup(), compileInModule(), copyAttributes(), copyMethodAttributes(), DEF_PRIMITIVE(), wrenInitializeCore(), and wrenSetMapValue().
wrenNewClass()
ObjClass* wrenNewClass (WrenVM * vm, ObjClass * superclass, int numFields, ObjString * name)
Definition at line 86 of file wren_value.c.
 {
   // Create the metaclass.
   Value metaclassName = wrenStringFormat(vm, "@ metaclass", OBJ_VAL(name));
   wrenPushRoot(vm, AS_OBJ(metaclassName));
   ObjClass* metaclass = wrenNewSingleClass(vm, 0, AS_STRING(metaclassName));
   metaclass->obj.classObj = vm->classClass;
   wrenPopRoot(vm);
   // Make sure the metaclass isn't collected when we allocate the class.
   wrenPushRoot(vm, (Obj*)metaclass);
   // Metaclasses always inherit Class and do not parallel the non-metaclass
   // hierarchy.
   wrenBindSuperclass(vm, metaclass, vm->classClass);
   ObjClass* classObj = wrenNewSingleClass(vm, numFields, name);
   // Make sure the class isn't collected while the inherited methods are being
   // bound.
   wrenPushRoot(vm, (Obj*)classObj);
   classObj->obj.classObj = metaclass;
   wrenBindSuperclass(vm, classObj, superclass);
   wrenPopRoot(vm);
   wrenPopRoot(vm);
   return classObj;
 }
References AS_OBJ, AS_STRING, WrenVM::classClass, sObj::classObj, name, sObjClass::obj, OBJ_VAL, wrenBindSuperclass(), wrenNewSingleClass(), wrenPopRoot(), wrenPushRoot(), and wrenStringFormat().
Referenced by createClass().
wrenNewClosure()
ObjClosure* wrenNewClosure (WrenVM * vm, ObjFn * fn)
Definition at line 134 of file wren_value.c.
 {
   ObjClosure* closure = ALLOCATE_FLEX(vm, ObjClosure,
                                       ObjUpvalue*, fn->numUpvalues);
   initObj(vm, &closure->obj, OBJ_CLOSURE, vm->fnClass);
   closure->fn = fn;
   // Clear the upvalue array. We need to do this in case a GC is triggered
   // after the closure is created but before the upvalue array is populated.
   for (int i = 0; i < fn->numUpvalues; i++) closure->upvalues[i] = NULL;
   return closure;
 }
References ALLOCATE_FLEX, fn, ObjClosure::fn, WrenVM::fnClass, initObj(), NULL, ObjClosure::obj, OBJ_CLOSURE, and ObjClosure::upvalues.
Referenced by compileInModule(), runInterpreter(), and wrenMakeCallHandle().
wrenNewFiber()
ObjFiber* wrenNewFiber (WrenVM * vm, ObjClosure * closure)
Definition at line 149 of file wren_value.c.
 {
   // Allocate the arrays before the fiber in case it triggers a GC.
   CallFrame* frames = ALLOCATE_ARRAY(vm, CallFrame, INITIAL_CALL_FRAMES);
   // Add one slot for the unused implicit receiver slot that the compiler
   // assumes all functions have.
   int stackCapacity = closure == NULL
       ? 1
       : wrenPowerOf2Ceil(closure->fn->maxSlots + 1);
   Value* stack = ALLOCATE_ARRAY(vm, Value, stackCapacity);
   ObjFiber* fiber = ALLOCATE(vm, ObjFiber);
   initObj(vm, &fiber->obj, OBJ_FIBER, vm->fiberClass);
   fiber->stack = stack;
   fiber->stackTop = fiber->stack;
   fiber->stackCapacity = stackCapacity;
   fiber->frames = frames;
   fiber->frameCapacity = INITIAL_CALL_FRAMES;
   fiber->numFrames = 0;
   fiber->openUpvalues = NULL;
   fiber->caller = NULL;
   fiber->error = NULL_VAL;
   fiber->state = FIBER_OTHER;
   if (closure != NULL)
   {
     // Initialize the first call frame.
     wrenAppendCallFrame(vm, fiber, closure, fiber->stack);
     // The first slot always holds the closure.
     fiber->stackTop[0] = OBJ_VAL(closure);
     fiber->stackTop++;
   }
   return fiber;
 }
References ALLOCATE, ALLOCATE_ARRAY, fiber, FIBER_OTHER, WrenVM::fiberClass, ObjClosure::fn, INITIAL_CALL_FRAMES, initObj(), ObjFn::maxSlots, NULL, NULL_VAL, OBJ_FIBER, OBJ_VAL, wrenAppendCallFrame(), and wrenPowerOf2Ceil().
Referenced by DEF_PRIMITIVE(), wrenEnsureSlots(), and wrenInterpret().
wrenNewForeign()
ObjForeign* wrenNewForeign (WrenVM * vm, ObjClass * classObj, size_t size)
Definition at line 234 of file wren_value.c.
 {
   ObjForeign* object = ALLOCATE_FLEX(vm, ObjForeign, uint8_t, size);
   initObj(vm, &object->obj, OBJ_FOREIGN, classObj);
   // Zero out the bytes.
   memset(object->data, 0, size);
   return object;
 }
References ALLOCATE_FLEX, ObjForeign::data, initObj(), ObjForeign::obj, and OBJ_FOREIGN.
Referenced by wrenSetSlotNewForeign().
wrenNewFunction()
ObjFn* wrenNewFunction (WrenVM * vm, ObjModule * module, int maxSlots)
Definition at line 244 of file wren_value.c.
 {
   FnDebug* debug = ALLOCATE(vm, FnDebug);
   debug->name = NULL;
   wrenIntBufferInit(&debug->sourceLines);
   ObjFn* fn = ALLOCATE(vm, ObjFn);
   initObj(vm, &fn->obj, OBJ_FN, vm->fnClass);
   wrenValueBufferInit(&fn->constants);
   wrenByteBufferInit(&fn->code);
   fn->module = module;
   fn->maxSlots = maxSlots;
   fn->numUpvalues = 0;
   fn->arity = 0;
   fn->debug = debug;
   return fn;
 }
References ALLOCATE, fn, WrenVM::fnClass, initObj(), FnDebug::name, NULL, OBJ_FN, and FnDebug::sourceLines.
Referenced by initCompiler(), and wrenMakeCallHandle().
wrenNewInstance()
Value wrenNewInstance (WrenVM * vm, ObjClass * classObj)
Definition at line 271 of file wren_value.c.
 {
   ObjInstance* instance = ALLOCATE_FLEX(vm, ObjInstance,
                                         Value, classObj->numFields);
   initObj(vm, &instance->obj, OBJ_INSTANCE, classObj);
   // Initialize fields to null.
   for (int i = 0; i < classObj->numFields; i++)
   {
     instance->fields[i] = NULL_VAL;
   }
   return OBJ_VAL(instance);
 }
References ALLOCATE_FLEX, ObjInstance::fields, initObj(), NULL_VAL, sObjClass::numFields, ObjInstance::obj, OBJ_INSTANCE, and OBJ_VAL.
Referenced by runInterpreter().
wrenNewList()
ObjList* wrenNewList (WrenVM * vm, uint32_t numElements)
Definition at line 286 of file wren_value.c.
 {
   // Allocate this before the list object in case it triggers a GC which would
   // free the list.
   Value* elements = NULL;
   if (numElements > 0)
   {
     elements = ALLOCATE_ARRAY(vm, Value, numElements);
   }
   ObjList* list = ALLOCATE(vm, ObjList);
   initObj(vm, &list->obj, OBJ_LIST, vm->listClass);
   list->elements.capacity = numElements;
   list->elements.count = numElements;
   list->elements.data = elements;
   return list;
 }
References ALLOCATE, ALLOCATE_ARRAY, initObj(), list(), WrenVM::listClass, NULL, and OBJ_LIST.
Referenced by addToAttributeGroup(), DEF_PRIMITIVE(), metaGetModuleVariables(), and wrenSetSlotNewList().
wrenNewMap()
ObjMap* wrenNewMap (WrenVM * vm)
Definition at line 363 of file wren_value.c.
 {
   ObjMap* map = ALLOCATE(vm, ObjMap);
   initObj(vm, &map->obj, OBJ_MAP, vm->mapClass);
   map->capacity = 0;
   map->count = 0;
   map->entries = NULL;
   return map;
 }
References ALLOCATE, initObj(), map(), WrenVM::mapClass, NULL, and OBJ_MAP.
Referenced by addConstant(), addToAttributeGroup(), classDefinition(), copyMethodAttributes(), DEF_PRIMITIVE(), initCompiler(), wrenNewVM(), and wrenSetSlotNewMap().
wrenNewModule()
ObjModule* wrenNewModule (WrenVM * vm, ObjString * name)
Definition at line 645 of file wren_value.c.
 {
   ObjModule* module = ALLOCATE(vm, ObjModule);
   // Modules are never used as first-class objects, so don't need a class.
   initObj(vm, (Obj*)module, OBJ_MODULE, NULL);
   wrenPushRoot(vm, (Obj*)module);
   wrenSymbolTableInit(&module->variableNames);
   wrenValueBufferInit(&module->variables);
   module->name = name;
   wrenPopRoot(vm);
   return module;
 }
References ALLOCATE, initObj(), name, ObjModule::name, NULL, OBJ_MODULE, ObjModule::variableNames, ObjModule::variables, wrenPopRoot(), wrenPushRoot(), and wrenSymbolTableInit().
Referenced by compileInModule(), and wrenInitializeCore().
wrenNewRange()
Value wrenNewRange (WrenVM * vm, double from, double to, bool isInclusive)
Definition at line 663 of file wren_value.c.
 {
   ObjRange* range = ALLOCATE(vm, ObjRange);
   initObj(vm, &range->obj, OBJ_RANGE, vm->rangeClass);
   range->from = from;
   range->to = to;
   range->isInclusive = isInclusive;
   return OBJ_VAL(range);
 }
References ALLOCATE, ObjRange::from, initObj(), ObjRange::isInclusive, ObjRange::obj, OBJ_RANGE, OBJ_VAL, WrenVM::rangeClass, and ObjRange::to.
Referenced by DEF_PRIMITIVE().
wrenNewSingleClass()
ObjClass* wrenNewSingleClass (WrenVM * vm, int numFields, ObjString * name)
Definition at line 46 of file wren_value.c.
 {
   ObjClass* classObj = ALLOCATE(vm, ObjClass);
   initObj(vm, &classObj->obj, OBJ_CLASS, NULL);
   classObj->superclass = NULL;
   classObj->numFields = numFields;
   classObj->name = name;
   classObj->attributes = NULL_VAL;
   wrenPushRoot(vm, (Obj*)classObj);
   wrenMethodBufferInit(&classObj->methods);
   wrenPopRoot(vm);
   return classObj;
 }
References ALLOCATE, sObjClass::attributes, initObj(), sObjClass::methods, name, sObjClass::name, NULL, NULL_VAL, sObjClass::numFields, sObjClass::obj, OBJ_CLASS, sObjClass::superclass, wrenPopRoot(), and wrenPushRoot().
Referenced by defineClass(), and wrenNewClass().
wrenNewString()
Value wrenNewString (WrenVM * vm, const char * text)
Definition at line 707 of file wren_value.c.
 {
   return wrenNewStringLength(vm, text, strlen(text));
 }
References wrenNewStringLength().
Referenced by defineClass(), resolveModule(), wrenCompileSource(), and wrenSetSlotString().
wrenNewStringFromRange()
Value wrenNewStringFromRange (WrenVM * vm, ObjString * source, int start, uint32_t count, int step)
Definition at line 728 of file wren_value.c.
 {
   uint8_t* from = (uint8_t*)source->value;
   int length = 0;
   for (uint32_t i = 0; i < count; i++)
   {
     length += wrenUtf8DecodeNumBytes(from[start + i * step]);
   }
   ObjString* result = allocateString(vm, length);
   result->value[length] = '\0';
   uint8_t* to = (uint8_t*)result->value;
   for (uint32_t i = 0; i < count; i++)
   {
     int index = start + i * step;
     int codePoint = wrenUtf8Decode(from + index, source->length - index);
     if (codePoint != -1)
     {
       to += wrenUtf8Encode(codePoint, to);
     }
   }
   hashString(result);
   return OBJ_VAL(result);
 }
References allocateString(), count, hashString(), OBJ_VAL, source, sObjString::value, wrenUtf8Decode(), wrenUtf8DecodeNumBytes(), and wrenUtf8Encode().
Referenced by DEF_PRIMITIVE().
wrenNewStringLength()
Value wrenNewStringLength (WrenVM * vm, const char * text, size_t length)
Definition at line 712 of file wren_value.c.
 {
   // Allow NULL if the string is empty since byte buffers don't allocate any
   // characters for a zero-length string.
   ASSERT(length == 0 || text != NULL, "Unexpected NULL string.");
   ObjString* string = allocateString(vm, length);
   // Copy the string (if given one).
   if (length > 0 && text != NULL) memcpy(string->value, text, length);
   hashString(string);
   return OBJ_VAL(string);
 }
References allocateString(), ASSERT, hashString(), NULL, OBJ_VAL, and sObjString::value.
Referenced by classDefinition(), copyMethodAttributes(), import(), method(), readName(), readRawString(), readString(), wrenNewString(), wrenNumToString(), wrenSetSlotBytes(), wrenStringCodePointAt(), and wrenSymbolTableAdd().
wrenNewUpvalue()
ObjUpvalue* wrenNewUpvalue (WrenVM * vm, Value * value)
Definition at line 963 of file wren_value.c.
 {
   ObjUpvalue* upvalue = ALLOCATE(vm, ObjUpvalue);
   // Upvalues are never used as first-class objects, so don't need a class.
   initObj(vm, &upvalue->obj, OBJ_UPVALUE, NULL);
   upvalue->value = value;
   upvalue->closed = NULL_VAL;
   upvalue->next = NULL;
   return upvalue;
 }
References ALLOCATE, sObjUpvalue::closed, initObj(), sObjUpvalue::next, NULL, NULL_VAL, sObjUpvalue::obj, OBJ_UPVALUE, and sObjUpvalue::value.
Referenced by captureUpvalue().
wrenNumToString()
Value wrenNumToString (WrenVM * vm, double value)
Definition at line 757 of file wren_value.c.
 {
   // Edge case: If the value is NaN or infinity, different versions of libc
   // produce different outputs (some will format it signed and some won't). To
   // get reliable output, handle it ourselves.
   if (isnan(value)) return CONST_STRING(vm, "nan");
   if (isinf(value))
   {
     if (value > 0.0)
     {
       return CONST_STRING(vm, "infinity");
     }
     else
     {
       return CONST_STRING(vm, "-infinity");
     }
   }
   // This is large enough to hold any double converted to a string using
   // "%.14g". Example:
   //
   //     -1.12345678901234e-1022
   //
   // So we have:
   //
   // + 1 char for sign
   // + 1 char for digit
   // + 1 char for "."
   // + 14 chars for decimal digits
   // + 1 char for "e"
   // + 1 char for "-" or "+"
   // + 4 chars for exponent
   // + 1 char for "\0"
   // = 24
   char buffer[24];
   int length = sprintf(buffer, "%.14g", value);
   return wrenNewStringLength(vm, buffer, length);
 }
References CONST_STRING, and wrenNewStringLength().
Referenced by DEF_PRIMITIVE().
wrenNumToValue()
static Value wrenNumToValue (double num) inline static
Definition at line 868 of file wren_value.h.
 {
 #if WREN_NAN_TAGGING
   return wrenDoubleToBits(num);
 #else
   Value value;
   value.type = VAL_NUM;
   value.as.num = num;
   return value;
 #endif
 }
References wrenDoubleToBits().
wrenObjectToValue()
static Value wrenObjectToValue (Obj * obj) inline static
Definition at line 840 of file wren_value.h.
 {
 #if WREN_NAN_TAGGING
   // The triple casting is necessary here to satisfy some compilers:
   // 1. (uintptr_t) Convert the pointer to a number of the right size.
   // 2. (uint64_t)  Pad it up to 64 bits in 32-bit builds.
   // 3. Or in the bits to make a tagged Nan.
   // 4. Cast to a typedef'd value.
   return (Value)(SIGN_BIT | QNAN | (uint64_t)(uintptr_t)(obj));
 #else
   Value value;
   value.type = VAL_OBJ;
   value.as.obj = obj;
   return value;
 #endif
 }
References QNAN, and SIGN_BIT.
wrenStringCodePointAt()
Value wrenStringCodePointAt (WrenVM * vm, ObjString * string, uint32_t index)
Definition at line 883 of file wren_value.c.
 {
   ASSERT(index < string->length, "Index out of bounds.");
   int codePoint = wrenUtf8Decode((uint8_t*)string->value + index,
                                  string->length - index);
   if (codePoint == -1)
   {
     // If it isn't a valid UTF-8 sequence, treat it as a single raw byte.
     char bytes[2];
     bytes[0] = string->value[index];
     bytes[1] = '\0';
     return wrenNewStringLength(vm, bytes, 1);
   }
   return wrenStringFromCodePoint(vm, codePoint);
 }
References ASSERT, sObjString::length, sObjString::value, wrenNewStringLength(), wrenStringFromCodePoint(), and wrenUtf8Decode().
Referenced by DEF_PRIMITIVE().
wrenStringEqualsCString()
static bool wrenStringEqualsCString (const ObjString * a, const char * b, size_t length) inline static
Definition at line 764 of file wren_value.h.
 {
   return a->length == length && memcmp(a->value, b, length) == 0;
 }
References sObjString::length, and sObjString::value.
Referenced by wrenSymbolTableFind(), and wrenValuesEqual().
wrenStringFind()
uint32_t wrenStringFind (ObjString * haystack, ObjString * needle, uint32_t startIndex)
Definition at line 902 of file wren_value.c.
 {
   // Edge case: An empty needle is always found.
   if (needle->length == 0) return start;
   // If the needle goes past the haystack it won't be found.
   if (start + needle->length > haystack->length) return UINT32_MAX;
   // If the startIndex is too far it also won't be found.
   if (start >= haystack->length) return UINT32_MAX;
   // Pre-calculate the shift table. For each character (8-bit value), we
   // determine how far the search window can be advanced if that character is
   // the last character in the haystack where we are searching for the needle
   // and the needle doesn't match there.
   uint32_t shift[UINT8_MAX];
   uint32_t needleEnd = needle->length - 1;
   // By default, we assume the character is not the needle at all. In that case
   // case, if a match fails on that character, we can advance one whole needle
   // width since.
   for (uint32_t index = 0; index < UINT8_MAX; index++)
   {
     shift[index] = needle->length;
   }
   // Then, for every character in the needle, determine how far it is from the
   // end. If a match fails on that character, we can advance the window such
   // that it the last character in it lines up with the last place we could
   // find it in the needle.
   for (uint32_t index = 0; index < needleEnd; index++)
   {
     char c = needle->value[index];
     shift[(uint8_t)c] = needleEnd - index;
   }
   // Slide the needle across the haystack, looking for the first match or
   // stopping if the needle goes off the end.
   char lastChar = needle->value[needleEnd];
   uint32_t range = haystack->length - needle->length;
   for (uint32_t index = start; index <= range; )
   {
     // Compare the last character in the haystack's window to the last character
     // in the needle. If it matches, see if the whole needle matches.
     char c = haystack->value[index + needleEnd];
     if (lastChar == c &&
         memcmp(haystack->value + index, needle->value, needleEnd) == 0)
     {
       // Found a match.
       return index;
     }
     // Otherwise, slide the needle forward.
     index += shift[(uint8_t)c];
   }
   // Not found.
   return UINT32_MAX;
 }
References sObjString::length, and sObjString::value.
Referenced by DEF_PRIMITIVE().
wrenStringFormat()
Value wrenStringFormat (WrenVM * vm, const char * format, ...)
Definition at line 818 of file wren_value.c.
 {
   va_list argList;
   // Calculate the length of the result string. Do this up front so we can
   // create the final string with a single allocation.
   va_start(argList, format);
   size_t totalLength = 0;
   for (const char* c = format; *c != '\0'; c++)
   {
     switch (*c)
     {
       case '$':
         totalLength += strlen(va_arg(argList, const char*));
         break;
       case '@':
         totalLength += AS_STRING(va_arg(argList, Value))->length;
         break;
       default:
         // Any other character is interpreted literally.
         totalLength++;
     }
   }
   va_end(argList);
   // Concatenate the string.
   ObjString* result = allocateString(vm, totalLength);
   va_start(argList, format);
   char* start = result->value;
   for (const char* c = format; *c != '\0'; c++)
   {
     switch (*c)
     {
       case '$':
       {
         const char* string = va_arg(argList, const char*);
         size_t length = strlen(string);
         memcpy(start, string, length);
         start += length;
         break;
       }
       case '@':
       {
         ObjString* string = AS_STRING(va_arg(argList, Value));
         memcpy(start, string->value, string->length);
         start += string->length;
         break;
       }
       default:
         // Any other character is interpreted literally.
         *start++ = *c;
     }
   }
   va_end(argList);
   hashString(result);
   return OBJ_VAL(result);
 }
References allocateString(), AS_STRING, hashString(), sObjString::length, OBJ_VAL, and sObjString::value.
Referenced by bindMethod(), DEF_PRIMITIVE(), getModuleVariable(), importModule(), methodNotFound(), resolveModule(), validateIndexValue(), validateSuperclass(), wrenGetModuleVariable(), wrenGetVariable(), wrenHasModule(), wrenHasVariable(), and wrenNewClass().
wrenStringFromByte()
Value wrenStringFromByte (WrenVM * vm, uint8_t value)
Definition at line 809 of file wren_value.c.
 {
   int length = 1;
   ObjString* string = allocateString(vm, length);
   string->value[0] = value;
   hashString(string);
   return OBJ_VAL(string);
 }
References allocateString(), hashString(), and OBJ_VAL.
Referenced by DEF_PRIMITIVE().
wrenStringFromCodePoint()
Value wrenStringFromCodePoint (WrenVM * vm, int value)
Definition at line 796 of file wren_value.c.
 {
   int length = wrenUtf8EncodeNumBytes(value);
   ASSERT(length != 0, "Value out of range.");
   ObjString* string = allocateString(vm, length);
   wrenUtf8Encode(value, (uint8_t*)string->value);
   hashString(string);
   return OBJ_VAL(string);
 }
References allocateString(), ASSERT, hashString(), OBJ_VAL, sObjString::value, wrenUtf8Encode(), and wrenUtf8EncodeNumBytes().
Referenced by DEF_PRIMITIVE(), and wrenStringCodePointAt().
wrenValuesEqual()
bool wrenValuesEqual (Value a, Value b)
Definition at line 1292 of file wren_value.c.
 {
   if (wrenValuesSame(a, b)) return true;
   // If we get here, it's only possible for two heap-allocated immutable objects
   // to be equal.
   if (!IS_OBJ(a) || !IS_OBJ(b)) return false;
   Obj* aObj = AS_OBJ(a);
   Obj* bObj = AS_OBJ(b);
   // Must be the same type.
   if (aObj->type != bObj->type) return false;
   switch (aObj->type)
   {
     case OBJ_RANGE:
     {
       ObjRange* aRange = (ObjRange*)aObj;
       ObjRange* bRange = (ObjRange*)bObj;
       return aRange->from == bRange->from &&
              aRange->to == bRange->to &&
              aRange->isInclusive == bRange->isInclusive;
     }
     case OBJ_STRING:
     {
       ObjString* aString = (ObjString*)aObj;
       ObjString* bString = (ObjString*)bObj;
       return aString->hash == bString->hash &&
       wrenStringEqualsCString(aString, bString->value, bString->length);
     }
     default:
       // All other types are only equal if they are same, which they aren't if
       // we get here.
       return false;
   }
 }
References AS_OBJ, ObjRange::from, sObjString::hash, IS_OBJ, ObjRange::isInclusive, sObjString::length, OBJ_RANGE, OBJ_STRING, ObjRange::to, sObj::type, sObjString::value, wrenStringEqualsCString(), and wrenValuesSame().
Referenced by DEF_PRIMITIVE(), findEntry(), and wrenListIndexOf().
wrenValuesSame()
static bool wrenValuesSame (Value a, Value b) inline static
Definition at line 803 of file wren_value.h.
 {
 #if WREN_NAN_TAGGING
   // Value types have unique bit representations and we compare object types
   // by identity (i.e. pointer), so all we need to do is compare the bits.
   return a == b;
 #else
   if (a.type != b.type) return false;
   if (a.type == VAL_NUM) return a.as.num == b.as.num;
   return a.as.obj == b.as.obj;
 #endif
 }
Referenced by wrenValuesEqual().
wrenValueToNum()
static double wrenValueToNum (Value value) inline static
Definition at line 858 of file wren_value.h.
 {
 #if WREN_NAN_TAGGING
   return wrenDoubleFromBits(value);
 #else
   return value.as.num;
 #endif
 }
References wrenDoubleFromBits().