ERIS CORE: Surface Class Reference
Surface Class Reference
#include <ILI9341_t3_ERIS.h>
Public Member Functions
Surface (Surface *SubSurfaceFrom, int16_t width, int16_t height)
Surface (Surface *SubSurfaceFrom, SdFs *pSD, const char *path, const char *fileName)
Surface (uint16_t *buffer, int16_t width, int16_t height)
Surface (uint16_t *buffer, uint32_t length)
int16_t getHeight ()
uint16_t * getSurfaceBufferP ()
int16_t getWidth ()
uint16_t * requestSubSurfaceBufferP (uint32_t size)
Protected Member Functions
void allocate ()
uint32_t hash (const char *s)
void revoke ()
Protected Attributes
uint32_t alloc_size
uint32_t guid
int16_t h
uint32_t head
uint16_t * pSB
int16_t w
Detailed Description
Definition at line 33 of file ILI9341_t3_ERIS.h.
Constructor & Destructor Documentation
Surface() [1/4]
Surface::Surface (Surface * SubSurfaceFrom, SdFs * pSD, const char * path, const char * fileName) inline
Definition at line 35 of file ILI9341_t3_ERIS.h.
{
         char str[16]; //char buffer
         char *c;     //char pointer
         FsFile file;
         guid = hash(path) * hash(fileName);
         w = 0;//init these in case of a bad path or file.
         c = 0;
         h = 0;
         alloc_size = 0;
         pSB = NULL;
         //open image, get size info, attempt to allocate a buffer then copy
         //and capture the dimensions
         if (!pSD->chdir(path)){ //change file path
             Serial.print(F("M ILI9341_t3_ERIS::bltSD Path not found: "));
             Serial.println(path);
             return;
         }
         file.open(fileName, O_READ);//open image to read
         if (file.available() == 0){ //file not found
             Serial.print(F("M ILI9341_t3_ERIS::bltSD File Not Found: "));
             Serial.println(fileName);
             //pSD->ls();
             return;
         }
         file.fgets(str,sizeof(str)); //read the header data
         file.fgets(str,sizeof(str)); //to get the image dimensions
         file.close();
         strtok(str," ");             //convert dimension text to numbers
         w = atol(str);
         c = strtok(NULL, " ");
         h = atol(c);
         alloc_size = w*h;
         if (alloc_size < SURFACE_MIN_ALLOC_SIZE) alloc_size = SURFACE_MIN_ALLOC_SIZE;
         pSB = SubSurfaceFrom->requestSubSurfaceBufferP(alloc_size);
     }
References alloc_size, StreamFile< BaseFile, PosType >::available(), FsVolume::chdir(), FsBaseFile::close(), F, FsBaseFile::fgets(), guid, h, hash(), NULL, O_READ, FsBaseFile::open(), pSB, requestSubSurfaceBufferP(), SURFACE_MIN_ALLOC_SIZE, and w.
Surface() [2/4]
Surface::Surface (Surface * SubSurfaceFrom, int16_t width, int16_t height) inline
Definition at line 71 of file ILI9341_t3_ERIS.h.
{
         guid =  ((uint32_t)SubSurfaceFrom<<4) * ((uint32_t)width + ((uint32_t)height<<8));
         w = width;
         h = height;
         alloc_size = w*h;
         if (alloc_size < SURFACE_MIN_ALLOC_SIZE) alloc_size = SURFACE_MIN_ALLOC_SIZE;
         pSB = SubSurfaceFrom->requestSubSurfaceBufferP(alloc_size);
         //attempt to allocate a sub surface buffer then clear it
         Serial.print(F("M SubSurface buffer allocated with a size of: "));
         Serial.println(alloc_size);
         Serial.print(F("M Surface GUID: "));
         Serial.println(guid);
     }
References alloc_size, F, guid, h, pSB, requestSubSurfaceBufferP(), SURFACE_MIN_ALLOC_SIZE, w, and width.
Surface() [3/4]
Surface::Surface (uint16_t * buffer, uint32_t length) inline
Definition at line 85 of file ILI9341_t3_ERIS.h.
{
         //take an existing buffer as the surface buffer
         guid =  (uint32_t)buffer<<2 * (uint32_t)length;
         pSB = buffer;
         w = 0;
         h = 0;
         alloc_size = length;
         head = 0; //used for sub surface allocation
         Serial.print(F("M Surface buffer attached with a size of: "));
         Serial.println(alloc_size);
         Serial.print(F("M Surface GUID: "));
         Serial.println(guid);
     }
References alloc_size, F, guid, h, head, pSB, and w.
Surface() [4/4]
Surface::Surface (uint16_t * buffer, int16_t width, int16_t height) inline
Definition at line 99 of file ILI9341_t3_ERIS.h.
{
         //take an existing buffer as the surface buffer
         guid =  (uint32_t)buffer * ((uint32_t)width<<11) / (1 + (uint32_t)height);
         pSB = buffer;
         w = width;
         h = height;
         alloc_size = w*h;
         head = 0; //used for sub surface allocation
         Serial.print(F("M Surface buffer attached with a size of: "));
         Serial.println(alloc_size);
         Serial.print(F("M Surface GUID: "));
         Serial.println(guid);
     }
References alloc_size, F, guid, h, head, pSB, w, and width.
Member Function Documentation
allocate()
void Surface::allocate () protected
getHeight()
int16_t Surface::getHeight () inline
Definition at line 141 of file ILI9341_t3_ERIS.h.
 {return h;}
References h.
Referenced by ILI9341_t3_ERIS::bltMem().
getSurfaceBufferP()
uint16_t* Surface::getSurfaceBufferP () inline
Definition at line 139 of file ILI9341_t3_ERIS.h.
 {return pSB;}
References pSB.
Referenced by ILI9341_t3_ERIS::bltMem(), and ControlButton::update().
getWidth()
int16_t Surface::getWidth () inline
Definition at line 140 of file ILI9341_t3_ERIS.h.
 {return w;}
References w.
Referenced by ILI9341_t3_ERIS::bltMem(), and ControlButton::update().
hash()
uint32_t Surface::hash (const char * s) inline protected
Definition at line 153 of file ILI9341_t3_ERIS.h.
{
         //uint32 djb2 string hash
         uint32_t h = 5381;
         int c;
         while ((c = *s++)){
             h = ((h << 5) + h) + c;
         }
         return h;
     }
References h, and s.
Referenced by Surface().
requestSubSurfaceBufferP()
uint16_t* Surface::requestSubSurfaceBufferP (uint32_t size) inline
Definition at line 113 of file ILI9341_t3_ERIS.h.
{
         /* provides an interface to enable childern subsurfaces
            to request a portion of the parents surface buffer
            function input is size of the surface array of N elements
            each element of the array being two bytes (uint16_t).
            so the allocation head will be moved size * 2
         */
         uint16_t* pSSB;
         if ((head + size) > alloc_size){
             //not enough space
             Serial.println(F("M ERROR: Surface out of MEM"));
             return NULL;
         }
         if (!pSB){
             Serial.println(F("M ERROR: Surface has no buffer"));
             return NULL;
         }
         pSSB = pSB + (head);
         head += size;
         Serial.println(F("M SubSurface allocated"));
         Serial.print(F("M Surface buffer remaining:"));
         Serial.println(alloc_size - head);
         return pSSB;
     }
References alloc_size, F, head, NULL, and pSB.
Referenced by Surface().
revoke()
void Surface::revoke () protected
Member Data Documentation
alloc_size
uint32_t Surface::alloc_size protected
Definition at line 147 of file ILI9341_t3_ERIS.h.
Referenced by Surface(), and requestSubSurfaceBufferP().
guid
uint32_t Surface::guid protected
Definition at line 148 of file ILI9341_t3_ERIS.h.
Referenced by Surface().
h
int16_t Surface::h protected
Definition at line 146 of file ILI9341_t3_ERIS.h.
Referenced by Surface(), getHeight(), and hash().
head
uint32_t Surface::head protected
Definition at line 149 of file ILI9341_t3_ERIS.h.
Referenced by Surface(), and requestSubSurfaceBufferP().
pSB
uint16_t* Surface::pSB protected
Definition at line 144 of file ILI9341_t3_ERIS.h.
Referenced by Surface(), getSurfaceBufferP(), and requestSubSurfaceBufferP().
w
int16_t Surface::w protected
Definition at line 145 of file ILI9341_t3_ERIS.h.
Referenced by Surface(), and getWidth().
The documentation for this class was generated from the following file:
ERISCore/include/ILI9341_t3_ERIS.h