ERIS CORE: Surface::Surface
Surface() [1/5]
Surface::Surface (Surface * SubSurfaceFrom, SdFs * pSD, const char * path, const char * fileName) inline
Definition at line 35 of file ILI9341_t3_ERIS.h.
{
         char str[16]; //char buffer
         char *c;     //char pointer
         FsFile file;
         guid = hash(path) * hash(fileName);
         w = 0;//init these in case of a bad path or file.
         c = 0;
         h = 0;
         alloc_size = 0;
         pSB = NULL;
         //open image, get size info, attempt to allocate a buffer then copy
         //and capture the dimensions
         if (!pSD->chdir(path)){ //change file path
             Serial.print(F("M ILI9341_t3_ERIS::bltSD Path not found: "));
             Serial.println(path);
             return;
         }
         file.open(fileName, O_READ);//open image to read
         if (file.available() == 0){ //file not found
             Serial.print(F("M ILI9341_t3_ERIS::bltSD File Not Found: "));
             Serial.println(fileName);
             //pSD->ls();
             return;
         }
         file.fgets(str,sizeof(str)); //read the header data
         file.fgets(str,sizeof(str)); //to get the image dimensions
         file.close();
         strtok(str," ");             //convert dimension text to numbers
         w = atol(str);
         c = strtok(NULL, " ");
         h = atol(c);
         alloc_size = w*h;
         if (alloc_size < SURFACE_MIN_ALLOC_SIZE) alloc_size = SURFACE_MIN_ALLOC_SIZE;
         pSB = SubSurfaceFrom->requestSubSurfaceBufferP(alloc_size);
     }
References alloc_size, guid, h, hash(), pSB, requestSubSurfaceBufferP(), SURFACE_MIN_ALLOC_SIZE, and w.
Referenced by Surface().