ERIS CORE: upcase.h File Reference
upcase.h File Reference
#include <stdint.h>
Functions
uint16_t toUpcase (uint16_t chr)
uint32_t upcaseChecksum (uint16_t unicode, uint32_t checksum)
Function Documentation
toUpcase()
uint16_t toUpcase (uint16_t chr)
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 202 of file upcase.cpp.
{
   uint16_t i, first;
   // Optimize for simple ASCII.
   if (chr < 127) {
     return chr - ('a' <= chr && chr <= 'z' ? 'a' - 'A' : 0);
   }
   i = searchPair16(reinterpret_cast<const pair16_t*>(mapTable), MAP_DIM, chr);
   first = readTable16(mapTable[i].base);
   if (first <= chr && (chr - first)  < readTable8(mapTable[i].count)) {
     int8_t off = readTable8(mapTable[i].off);
     if (off == 1) {
       return chr - ((chr - first) & 1);
     }
     return chr + (off ? off : -0x1C60);
   }
   i = searchPair16(lookupTable, LOOKUP_DIM, chr);
   if (readTable16(lookupTable[i].key) == chr) {
     return readTable16(lookupTable[i].val);
   }
   return chr;
 }
References count, LOOKUP_DIM, MAP_DIM, readTable16, readTable8, and searchPair16().
Referenced by ExFatPartition::checkUpcase(), ExFatFile::cmpName(), exFatHash(), hashDir(), and ExFatFormatter::writeUpcase().
upcaseChecksum()
uint32_t upcaseChecksum (uint16_t unicode, uint32_t checksum)
Definition at line 224 of file upcase.cpp.
{
   sum = (sum << 31) + (sum >> 1) + (uc & 0XFF);
   sum = (sum << 31) + (sum >> 1) + (uc >> 8);
   return sum;
 }
Referenced by ExFatPartition::printUpcase().