ERIS CORE: FatFormatter Class Reference
FatFormatter Class Reference
Format a FAT volume.
#include <FatFormatter.h>
Public Member Functions
bool format (BlockDevice *dev, uint8_t *secBuffer, print_t *pr=nullptr)
Private Member Functions
bool initFatDir (uint8_t fatType, uint32_t sectorCount)
void initPbs ()
bool makeFat16 ()
bool makeFat32 ()
bool writeMbr ()
Private Attributes
uint32_t m_capacityMB
uint32_t m_dataStart
BlockDevice * m_dev
uint32_t m_fatSize
uint32_t m_fatStart
uint8_t m_partType
print_t * m_pr
uint32_t m_relativeSectors
uint16_t m_reservedSectorCount
uint8_t * m_secBuf
uint32_t m_sectorCount
uint8_t m_sectorsPerCluster
uint32_t m_totalSectors
Detailed Description
Format a FAT volume.
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 33 of file FatFormatter.h.
Member Function Documentation
format()
bool FatFormatter::format (BlockDevice * dev, uint8_t * secBuffer, print_t * pr = nullptr)
Format a FAT volume.
Parameters
[in] dev Block device for volume.
[in] secBuffer buffer for writing to volume.
[in] pr Print device for progress output.
Returns
true for success or false for failure.
Definition at line 48 of file FatFormatter.cpp.
{
   bool rtn;
   m_dev = dev;
   m_secBuf = secBuf;
   m_pr = pr;
   m_sectorCount = m_dev->sectorCount();
   m_capacityMB = (m_sectorCount + SECTORS_PER_MB - 1)/SECTORS_PER_MB;
   if (m_capacityMB <= 6) {
     writeMsg("Card is too small.\r\n");
     return false;
   } else if (m_capacityMB <= 16) {
     m_sectorsPerCluster = 2;
   } else if (m_capacityMB <= 32) {
     m_sectorsPerCluster = 4;
   } else if (m_capacityMB <= 64) {
     m_sectorsPerCluster = 8;
   } else if (m_capacityMB <= 128) {
     m_sectorsPerCluster = 16;
   } else if (m_capacityMB <= 1024) {
     m_sectorsPerCluster = 32;
   } else if (m_capacityMB <= 32768) {
     m_sectorsPerCluster = 64;
   } else {
     // SDXC cards
     m_sectorsPerCluster = 128;
   }
   rtn = m_sectorCount < 0X400000 ? makeFat16() : makeFat32();
   if (rtn) {
     writeMsg("Format Done\r\n");
   } else {
     writeMsg("Format Failed\r\n");
   }
   return rtn;
 }
References m_capacityMB, m_dev, m_pr, m_secBuf, m_sectorCount, m_sectorsPerCluster, makeFat16(), makeFat32(), SharedSpiCard::sectorCount(), SECTORS_PER_MB, and writeMsg.
Referenced by SdFat32::format(), and SdFs::format().
initFatDir()
bool FatFormatter::initFatDir (uint8_t fatType, uint32_t sectorCount) private
Definition at line 84 of file FatFormatter.cpp.
{
   size_t n;
   memset(m_secBuf, 0, BYTES_PER_SECTOR);
   writeMsg("Writing FAT ");
   for (uint32_t i = 1; i < sectorCount; i++) {
     if (!m_dev->writeSector(m_fatStart + i, m_secBuf)) {
        return false;
     }
     if ((i%(sectorCount/32)) == 0) {
       writeMsg(".");
     }
   }
   writeMsg("\r\n");
   // Allocate reserved clusters and root for FAT32.
   m_secBuf[0] = 0XF8;
   n = fatType == 16 ? 4 : 12;
   for (size_t i = 1; i < n; i++) {
     m_secBuf[i] = 0XFF;
   }
   return m_dev->writeSector(m_fatStart, m_secBuf) &&
          m_dev->writeSector(m_fatStart + m_fatSize, m_secBuf);
 }
References BYTES_PER_SECTOR, m_dev, m_fatSize, m_fatStart, m_secBuf, writeMsg, and SharedSpiCard::writeSector().
Referenced by makeFat16(), and makeFat32().
initPbs()
void FatFormatter::initPbs () private
Definition at line 107 of file FatFormatter.cpp.
{
   PbsFat_t* pbs = reinterpret_cast<PbsFat_t*>(m_secBuf);
   memset(m_secBuf, 0, BYTES_PER_SECTOR);
   pbs->jmpInstruction[0] = 0XEB;
   pbs->jmpInstruction[1] = 0X76;
   pbs->jmpInstruction[2] = 0X90;
   for (uint8_t i = 0; i < sizeof(pbs->oemName); i++) {
     pbs->oemName[i] = ' ';
   }
   setLe16(pbs->bpb.bpb16.bytesPerSector, BYTES_PER_SECTOR);
   pbs->bpb.bpb16.sectorsPerCluster = m_sectorsPerCluster;
   setLe16(pbs->bpb.bpb16.reservedSectorCount, m_reservedSectorCount);
   pbs->bpb.bpb16.fatCount = 2;
   // skip rootDirEntryCount
   // skip totalSectors16
   pbs->bpb.bpb16.mediaType = 0XF8;
   // skip sectorsPerFat16
   // skip sectorsPerTrack
   // skip headCount
   setLe32(pbs->bpb.bpb16.hidddenSectors, m_relativeSectors);
   setLe32(pbs->bpb.bpb16.totalSectors32, m_totalSectors);
   // skip rest of bpb
   setLe16(pbs->signature, PBR_SIGNATURE);
 }
References partitionBootSectorFat::bpb, BYTES_PER_SECTOR, partitionBootSectorFat::jmpInstruction, m_relativeSectors, m_reservedSectorCount, m_secBuf, m_sectorsPerCluster, m_totalSectors, partitionBootSectorFat::oemName, PBR_SIGNATURE, setLe16(), setLe32(), and partitionBootSectorFat::signature.
Referenced by makeFat16(), and makeFat32().
makeFat16()
bool FatFormatter::makeFat16 () private
Definition at line 132 of file FatFormatter.cpp.
{
   uint32_t nc;
   uint32_t r;
   PbsFat_t* pbs = reinterpret_cast<PbsFat_t*>(m_secBuf);
   for (m_dataStart = 2*BU16; ; m_dataStart += BU16) {
     nc = (m_sectorCount - m_dataStart)/m_sectorsPerCluster;
     m_fatSize = (nc + 2 + (BYTES_PER_SECTOR/2) - 1)/(BYTES_PER_SECTOR/2);
     r = BU16 + 1 + 2*m_fatSize + FAT16_ROOT_SECTOR_COUNT;
     if (m_dataStart >= r) {
       m_relativeSectors = m_dataStart - r + BU16;
       break;
     }
   }
   // check valid cluster count for FAT16 volume
   if (nc < 4085 || nc >= 65525) {
     writeMsg("Bad cluster count\r\n");
     return false;
   }
   m_reservedSectorCount = 1;
   m_fatStart = m_relativeSectors + m_reservedSectorCount;
   m_totalSectors = nc*m_sectorsPerCluster
                    + 2*m_fatSize + m_reservedSectorCount + 32;
   if (m_totalSectors < 65536) {
     m_partType = 0X04;
   } else {
     m_partType = 0X06;
   }
   // write MBR
   if (!writeMbr()) {
     return false;
   }
   initPbs();
   setLe16(pbs->bpb.bpb16.rootDirEntryCount, FAT16_ROOT_ENTRY_COUNT);
   setLe16(pbs->bpb.bpb16.sectorsPerFat16, m_fatSize);
   pbs->bpb.bpb16.physicalDriveNumber = 0X80;
   pbs->bpb.bpb16.extSignature = EXTENDED_BOOT_SIGNATURE;
   setLe32(pbs->bpb.bpb16.volumeSerialNumber, 1234567);
   for (size_t i = 0; i < sizeof(pbs->bpb.bpb16.volumeLabel); i++) {
     pbs->bpb.bpb16.volumeLabel[i] = ' ';
   }
   pbs->bpb.bpb16.volumeType[0] = 'F';
   pbs->bpb.bpb16.volumeType[1] = 'A';
   pbs->bpb.bpb16.volumeType[2] = 'T';
   pbs->bpb.bpb16.volumeType[3] = '1';
   pbs->bpb.bpb16.volumeType[4] = '6';
   if (!m_dev->writeSector(m_relativeSectors, m_secBuf)) {
     return false;
   }
   return initFatDir(16, m_dataStart - m_fatStart);
 }
References partitionBootSectorFat::bpb, BU16, BYTES_PER_SECTOR, EXTENDED_BOOT_SIGNATURE, FAT16_ROOT_ENTRY_COUNT, FAT16_ROOT_SECTOR_COUNT, initFatDir(), initPbs(), m_dataStart, m_dev, m_fatSize, m_fatStart, m_partType, m_relativeSectors, m_reservedSectorCount, m_secBuf, m_sectorCount, m_sectorsPerCluster, m_totalSectors, setLe16(), setLe32(), writeMbr(), writeMsg, and SharedSpiCard::writeSector().
Referenced by format().
makeFat32()
bool FatFormatter::makeFat32 () private
Definition at line 184 of file FatFormatter.cpp.
{
   uint32_t nc;
   uint32_t r;
   PbsFat_t* pbs = reinterpret_cast<PbsFat_t*>(m_secBuf);
   FsInfo_t* fsi = reinterpret_cast<FsInfo_t*>(m_secBuf);
   m_relativeSectors = BU32;
   for (m_dataStart = 2*BU32; ; m_dataStart += BU32) {
     nc = (m_sectorCount - m_dataStart)/m_sectorsPerCluster;
     m_fatSize = (nc + 2 + (BYTES_PER_SECTOR/4) - 1)/(BYTES_PER_SECTOR/4);
     r = m_relativeSectors + 9 + 2*m_fatSize;
     if (m_dataStart >= r) {
       break;
     }
   }
   // error if too few clusters in FAT32 volume
   if (nc < 65525) {
     writeMsg("Bad cluster count\r\n");
     return false;
   }
   m_reservedSectorCount = m_dataStart - m_relativeSectors - 2*m_fatSize;
   m_fatStart = m_relativeSectors + m_reservedSectorCount;
   m_totalSectors = nc*m_sectorsPerCluster + m_dataStart - m_relativeSectors;
   // type depends on address of end sector
   // max CHS has lba = 16450560 = 1024*255*63
   if ((m_relativeSectors + m_totalSectors) <= 16450560) {
     // FAT32 with CHS and LBA
     m_partType = 0X0B;
   } else {
     // FAT32 with only LBA
     m_partType = 0X0C;
   }
   if (!writeMbr()) {
     return false;
   }
   initPbs();
   setLe32(pbs->bpb.bpb32.sectorsPerFat32, m_fatSize);
   setLe32(pbs->bpb.bpb32.fat32RootCluster, 2);
   setLe16(pbs->bpb.bpb32.fat32FSInfoSector, 1);
   setLe16(pbs->bpb.bpb32.fat32BackBootSector, 6);
   pbs->bpb.bpb32.physicalDriveNumber = 0X80;
   pbs->bpb.bpb32.extSignature = EXTENDED_BOOT_SIGNATURE;
   setLe32(pbs->bpb.bpb32.volumeSerialNumber, 1234567);
   for (size_t i = 0; i < sizeof(pbs->bpb.bpb32.volumeLabel); i++) {
     pbs->bpb.bpb32.volumeLabel[i] = ' ';
   }
   pbs->bpb.bpb32.volumeType[0] = 'F';
   pbs->bpb.bpb32.volumeType[1] = 'A';
   pbs->bpb.bpb32.volumeType[2] = 'T';
   pbs->bpb.bpb32.volumeType[3] = '3';
   pbs->bpb.bpb32.volumeType[4] = '2';
   if (!m_dev->writeSector(m_relativeSectors, m_secBuf)  ||
       !m_dev->writeSector(m_relativeSectors + 6, m_secBuf)) {
     return false;
   }
   // write extra boot area and backup
   memset(m_secBuf, 0 , BYTES_PER_SECTOR);
   setLe32(fsi->trailSignature, FSINFO_TRAIL_SIGNATURE);
   if (!m_dev->writeSector(m_relativeSectors + 2, m_secBuf)  ||
       !m_dev->writeSector(m_relativeSectors + 8, m_secBuf)) {
     return false;
   }
   // write FSINFO sector and backup
   setLe32(fsi->leadSignature, FSINFO_LEAD_SIGNATURE);
   setLe32(fsi->structSignature, FSINFO_STRUCT_SIGNATURE);
   setLe32(fsi->freeCount, 0XFFFFFFFF);
   setLe32(fsi->nextFree, 0XFFFFFFFF);
   if (!m_dev->writeSector(m_relativeSectors + 1, m_secBuf)  ||
       !m_dev->writeSector(m_relativeSectors + 7, m_secBuf)) {
     return false;
   }
   return initFatDir(32, 2*m_fatSize + m_sectorsPerCluster);
 }
References partitionBootSectorFat::bpb, BU32, BYTES_PER_SECTOR, EXTENDED_BOOT_SIGNATURE, FsInfoSector::freeCount, FSINFO_LEAD_SIGNATURE, FSINFO_STRUCT_SIGNATURE, FSINFO_TRAIL_SIGNATURE, initFatDir(), initPbs(), FsInfoSector::leadSignature, m_dataStart, m_dev, m_fatSize, m_fatStart, m_partType, m_relativeSectors, m_reservedSectorCount, m_secBuf, m_sectorCount, m_sectorsPerCluster, m_totalSectors, FsInfoSector::nextFree, setLe16(), setLe32(), FsInfoSector::structSignature, FsInfoSector::trailSignature, writeMbr(), writeMsg, and SharedSpiCard::writeSector().
Referenced by format().
writeMbr()
bool FatFormatter::writeMbr () private
Definition at line 258 of file FatFormatter.cpp.
{
   memset(m_secBuf, 0, BYTES_PER_SECTOR);
   MbrSector_t* mbr = reinterpret_cast<MbrSector_t*>(m_secBuf);
 #if USE_LBA_TO_CHS
   lbaToMbrChs(mbr->part->beginCHS, m_capacityMB, m_relativeSectors);
   lbaToMbrChs(mbr->part->endCHS, m_capacityMB,
               m_relativeSectors + m_totalSectors -1);
 #else  // USE_LBA_TO_CHS
   mbr->part->beginCHS[0] = 1;
   mbr->part->beginCHS[1] = 1;
   mbr->part->beginCHS[2] = 0;
   mbr->part->endCHS[0] = 0XFE;
   mbr->part->endCHS[1] = 0XFF;
   mbr->part->endCHS[2] = 0XFF;
 #endif  // USE_LBA_TO_CHS
   mbr->part->type = m_partType;
   setLe32(mbr->part->relativeSectors, m_relativeSectors);
   setLe32(mbr->part->totalSectors, m_totalSectors);
   setLe16(mbr->signature, MBR_SIGNATURE);
   return m_dev->writeSector(0, m_secBuf);
 }
References mbrPartition::beginCHS, BYTES_PER_SECTOR, mbrPartition::endCHS, lbaToMbrChs(), m_capacityMB, m_dev, m_partType, m_relativeSectors, m_secBuf, m_totalSectors, MBR_SIGNATURE, masterBootRecordSector::part, mbrPartition::relativeSectors, setLe16(), setLe32(), masterBootRecordSector::signature, mbrPartition::totalSectors, mbrPartition::type, and SharedSpiCard::writeSector().
Referenced by makeFat16(), and makeFat32().
Member Data Documentation
m_capacityMB
uint32_t FatFormatter::m_capacityMB private
Definition at line 52 of file FatFormatter.h.
Referenced by format(), and writeMbr().
m_dataStart
uint32_t FatFormatter::m_dataStart private
Definition at line 53 of file FatFormatter.h.
Referenced by makeFat16(), and makeFat32().
m_dev
BlockDevice* FatFormatter::m_dev private
Definition at line 59 of file FatFormatter.h.
Referenced by format(), initFatDir(), makeFat16(), makeFat32(), and writeMbr().
m_fatSize
uint32_t FatFormatter::m_fatSize private
Definition at line 54 of file FatFormatter.h.
Referenced by initFatDir(), makeFat16(), and makeFat32().
m_fatStart
uint32_t FatFormatter::m_fatStart private
Definition at line 55 of file FatFormatter.h.
Referenced by initFatDir(), makeFat16(), and makeFat32().
m_partType
uint8_t FatFormatter::m_partType private
Definition at line 63 of file FatFormatter.h.
Referenced by makeFat16(), makeFat32(), and writeMbr().
m_pr
print_t* FatFormatter::m_pr private
Definition at line 60 of file FatFormatter.h.
Referenced by format().
m_relativeSectors
uint32_t FatFormatter::m_relativeSectors private
Definition at line 56 of file FatFormatter.h.
Referenced by initPbs(), makeFat16(), makeFat32(), and writeMbr().
m_reservedSectorCount
uint16_t FatFormatter::m_reservedSectorCount private
Definition at line 62 of file FatFormatter.h.
Referenced by initPbs(), makeFat16(), and makeFat32().
m_secBuf
uint8_t* FatFormatter::m_secBuf private
Definition at line 61 of file FatFormatter.h.
Referenced by format(), initFatDir(), initPbs(), makeFat16(), makeFat32(), and writeMbr().
m_sectorCount
uint32_t FatFormatter::m_sectorCount private
Definition at line 57 of file FatFormatter.h.
Referenced by format(), makeFat16(), and makeFat32().
m_sectorsPerCluster
uint8_t FatFormatter::m_sectorsPerCluster private
Definition at line 64 of file FatFormatter.h.
Referenced by format(), initPbs(), makeFat16(), and makeFat32().
m_totalSectors
uint32_t FatFormatter::m_totalSectors private
Definition at line 58 of file FatFormatter.h.
Referenced by initPbs(), makeFat16(), makeFat32(), and writeMbr().
The documentation for this class was generated from the following files:
ERISCore/lib/SdFat-master/src/FatLib/FatFormatter.h
ERISCore/lib/SdFat-master/src/FatLib/FatFormatter.cpp