ERIS CORE: ios_base Class Reference
ios_base Class Reference
Base class for all streams.
#include <ios.h>
Public Types
typedef unsigned int fmtflags
typedef unsigned char iostate
typedef int64_t off_type
typedef uint8_t openmode
typedef uint64_t pos_type
enum seekdir { beg , cur , end }
typedef uint64_t streamsize
Public Member Functions
ios_base ()
char fill ()
char fill (char c)
fmtflags flags () const
fmtflags flags (fmtflags fl)
int precision () const
int precision (unsigned int n)
fmtflags setf (fmtflags fl)
fmtflags setf (fmtflags fl, fmtflags mask)
void unsetf (fmtflags fl)
unsigned width ()
unsigned width (unsigned n)
Static Public Attributes
static const fmtflags adjustfield = left | right | internal
static const openmode app = 0X4
static const openmode ate = 0X8
static const iostate badbit = 0X01
static const fmtflags basefield = dec | hex | oct
static const openmode binary = 0X10
static const fmtflags boolalpha = 0x0100
static const fmtflags dec = 0x0008
static const iostate eofbit = 0x02
static const iostate failbit = 0X04
static const iostate goodbit = 0x00
static const fmtflags hex = 0x0010
static const openmode in = 0X20
static const fmtflags internal = 0x0004
static const fmtflags left = 0x0001
static const fmtflags oct = 0x0020
static const openmode out = 0X40
static const fmtflags right = 0x0002
static const fmtflags showbase = 0x0200
static const fmtflags showpoint = 0x0400
static const fmtflags showpos = 0x0800
static const fmtflags skipws = 0x1000
static const openmode trunc = 0X80
static const fmtflags uppercase = 0x4000
Protected Member Functions
uint8_t flagsToBase ()
Private Attributes
char m_fill
fmtflags m_fmtflags
unsigned char m_precision
unsigned int m_width
Detailed Description
Base class for all streams.
Definition at line 50 of file ios.h.
Member Typedef Documentation
fmtflags
typedef unsigned int ios_base::fmtflags
type for format flags
Definition at line 94 of file ios.h.
iostate
typedef unsigned char ios_base::iostate
typedef for iostate bitmask
Definition at line 53 of file ios.h.
off_type
typedef int64_t ios_base::off_type
type for relative seek offset
Definition at line 82 of file ios.h.
openmode
typedef uint8_t ios_base::openmode
typedef for iostream open mode
Definition at line 129 of file ios.h.
pos_type
typedef uint64_t ios_base::pos_type
type for absolute seek position
Definition at line 80 of file ios.h.
streamsize
typedef uint64_t ios_base::streamsize
unsigned size that can represent maximum file size. (violates spec - should be signed)
Definition at line 78 of file ios.h.
Member Enumeration Documentation
seekdir
enum ios_base::seekdir
enumerated type for the direction of relative seeks
Enumerator
beg
seek relative to the beginning of the stream
cur
seek relative to the current stream position
end
seek relative to the end of the stream
Definition at line 85 of file ios.h.
                {
     beg,
     cur,
     end
   };
Constructor & Destructor Documentation
ios_base()
ios_base::ios_base () inline
Definition at line 145 of file ios.h.
              : m_fill(' '), m_fmtflags(dec | right | skipws)
     , m_precision(2), m_width(0) {}
Member Function Documentation
fill() [1/2]
char ios_base::fill () inline
Returns
fill character
Definition at line 148 of file ios.h.
               {
     return m_fill;
   }
Referenced by ostream::do_fill(), operator<<(), and operator>>().
fill() [2/2]
char ios_base::fill (char c) inline
Set fill character
Parameters
[in] c new fill character
Returns
old fill character
Definition at line 155 of file ios.h.
                     {
     char r = m_fill;
     m_fill = c;
     return r;
   }
flags() [1/2]
fmtflags ios_base::flags () const inline
Returns
format flags
Definition at line 161 of file ios.h.
{
     return m_fmtflags;
   }
Referenced by ostream::fill_not_left(), istream::getBool(), istream::getNumber(), ostream::putBool(), ostream::putDouble(), and istream::readSkip().
flags() [2/2]
fmtflags ios_base::flags (fmtflags fl) inline
set format flags
Parameters
[in] fl new flag
Returns
old flags
Definition at line 168 of file ios.h.
{
     fmtflags tmp = m_fmtflags;
     m_fmtflags = fl;
     return tmp;
   }
flagsToBase()
uint8_t ios_base::flagsToBase () inline protected
Returns
current number base
Definition at line 228 of file ios.h.
{
     uint8_t f = flags() & basefield;
     return f == oct ? 8 : f != hex ? 10 : 16;
   }
References hex(), and oct().
Referenced by ostream::putNum().
precision() [1/2]
int ios_base::precision () const inline
Returns
precision
Definition at line 174 of file ios.h.
{
     return m_precision;
   }
Referenced by operator<<(), and ostream::putDouble().
precision() [2/2]
int ios_base::precision (unsigned int n) inline
set precision
Parameters
[in] n new precision
Returns
old precision
Definition at line 181 of file ios.h.
{
     int r = m_precision;
     m_precision = n;
     return r;
   }
setf() [1/2]
fmtflags ios_base::setf (fmtflags fl) inline
set format flags
Parameters
[in] fl new flags to be or'ed in
Returns
old flags
Definition at line 190 of file ios.h.
{
     fmtflags r = m_fmtflags;
     m_fmtflags |= fl;
     return r;
   }
Referenced by boolalpha(), dec(), hex(), internal(), left(), oct(), right(), showbase(), showpoint(), showpos(), skipws(), and uppercase().
setf() [2/2]
fmtflags ios_base::setf (fmtflags fl, fmtflags mask) inline
modify format flags
Parameters
[in] mask flags to be removed
[in] fl flags to be set after mask bits have been cleared
Returns
old flags
Definition at line 200 of file ios.h.
{
     fmtflags r = m_fmtflags;
     m_fmtflags &= ~mask;
     m_fmtflags |= fl;
     return r;
   }
unsetf()
void ios_base::unsetf (fmtflags fl) inline
clear format flags
Parameters
[in] fl flags to be cleared
Definition at line 209 of file ios.h.
{
     m_fmtflags &= ~fl;
   }
Referenced by noboolalpha(), noshowbase(), noshowpoint(), noshowpos(), noskipws(), and nouppercase().
width() [1/2]
unsigned ios_base::width () inline
Returns
width
Definition at line 213 of file ios.h.
                    {
     return m_width;
   }
Referenced by ostream::do_fill(), istream::getStr(), and operator<<().
width() [2/2]
unsigned ios_base::width (unsigned n) inline
set width
Parameters
[in] n new width
Returns
old width
Definition at line 220 of file ios.h.
{
     unsigned r = m_width;
     m_width = n;
     return r;
   }
Member Data Documentation
adjustfield
const fmtflags ios_base::adjustfield = left | right | internal static
mask for adjustfield
Definition at line 123 of file ios.h.
Referenced by ostream::fill_not_left(), internal(), left(), ostream::putDouble(), and right().
app
const openmode ios_base::app = 0X4 static
seek to end before each write
Definition at line 133 of file ios.h.
Referenced by StreamBaseClass::open().
ate
const openmode ios_base::ate = 0X8 static
open and seek to end immediately after opening
Definition at line 135 of file ios.h.
Referenced by StreamBaseClass::open().
badbit
const iostate ios_base::badbit = 0X01 static
iostate bad bit for a nonrecoverable error.
Definition at line 58 of file ios.h.
Referenced by ios::bad(), ios::fail(), StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
basefield
const fmtflags ios_base::basefield = dec | hex | oct static
mask for basefield
Definition at line 125 of file ios.h.
Referenced by dec(), istream::getNumber(), hex(), and oct().
binary
const openmode ios_base::binary = 0X10 static
perform input and output in binary mode (as opposed to text mode)
Definition at line 137 of file ios.h.
Referenced by StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
boolalpha
const fmtflags ios_base::boolalpha = 0x0100 static
use strings true/false for bool
Definition at line 110 of file ios.h.
Referenced by boolalpha(), istream::getBool(), noboolalpha(), and ostream::putBool().
dec
const fmtflags ios_base::dec = 0x0008 static
base 10 flag
Definition at line 102 of file ios.h.
Referenced by dec().
eofbit
const iostate ios_base::eofbit = 0x02 static
iostate bit for end of file reached
Definition at line 60 of file ios.h.
Referenced by ios::eof(), StreamBaseClass::getch(), and istream::peek().
failbit
const iostate ios_base::failbit = 0X04 static
iostate fail bit for nonfatal error
Definition at line 62 of file ios.h.
Referenced by ios::fail(), istream::get(), istream::getBool(), istream::getChar(), istream::getDouble(), istream::getline(), istream::getStr(), StreamBaseClass::open(), ArduinoInStream::readline(), and istream::seekg().
goodbit
const iostate ios_base::goodbit = 0x00 static
iostate for no flags
Definition at line 56 of file ios.h.
Referenced by ios::good().
hex
const fmtflags ios_base::hex = 0x0010 static
base 16 flag
Definition at line 104 of file ios.h.
Referenced by istream::getNumber(), and hex().
in
const openmode ios_base::in = 0X20 static
open for input
Definition at line 139 of file ios.h.
Referenced by StreamBaseClass::open().
internal
const fmtflags ios_base::internal = 0x0004 static
fill between sign/base prefix and number
Definition at line 100 of file ios.h.
Referenced by internal().
left
const fmtflags ios_base::left = 0x0001 static
left adjust fields
Definition at line 96 of file ios.h.
Referenced by ostream::fill_not_left(), and left().
m_fill
char ios_base::m_fill private
Definition at line 234 of file ios.h.
m_fmtflags
fmtflags ios_base::m_fmtflags private
Definition at line 235 of file ios.h.
m_precision
unsigned char ios_base::m_precision private
Definition at line 236 of file ios.h.
m_width
unsigned int ios_base::m_width private
Definition at line 237 of file ios.h.
oct
const fmtflags ios_base::oct = 0x0020 static
base 8 flag
Definition at line 106 of file ios.h.
Referenced by istream::getNumber(), and oct().
out
const openmode ios_base::out = 0X40 static
open for output
Definition at line 141 of file ios.h.
Referenced by StreamBaseClass::open().
right
const fmtflags ios_base::right = 0x0002 static
right adjust fields
Definition at line 98 of file ios.h.
Referenced by right().
showbase
const fmtflags ios_base::showbase = 0x0200 static
use prefix 0X for hex and 0 for oct
Definition at line 112 of file ios.h.
Referenced by noshowbase(), and showbase().
showpoint
const fmtflags ios_base::showpoint = 0x0400 static
always show '.' for floating numbers
Definition at line 114 of file ios.h.
Referenced by noshowpoint(), ostream::putDouble(), and showpoint().
showpos
const fmtflags ios_base::showpos = 0x0800 static
show + sign for nonnegative numbers
Definition at line 116 of file ios.h.
Referenced by noshowpos(), ostream::putDouble(), and showpos().
skipws
const fmtflags ios_base::skipws = 0x1000 static
skip initial white space
Definition at line 118 of file ios.h.
Referenced by noskipws(), istream::readSkip(), and skipws().
trunc
const openmode ios_base::trunc = 0X80 static
truncate an existing stream when opening
Definition at line 143 of file ios.h.
Referenced by StreamBaseClass::open().
uppercase
const fmtflags ios_base::uppercase = 0x4000 static
use uppercase letters in number representations
Definition at line 121 of file ios.h.
Referenced by nouppercase(), and uppercase().
The documentation for this class was generated from the following file:
ios.h