ERIS CORE: AppManager::sendMessage
sendMessage()
bool AppManager::sendMessage (AppBaseClass * sender, const char * to_app, const char * message)
provides an interface for apps to send messages to other apps
Parameters
sender
to_app
message
Returns
true
false
Definition at line 447 of file AppManager.cpp.
{
   // sends a message to the requested app
   AppBaseClass *node = root;
   do{
     if (node->isName(to_app)){
       node->messageHandler(sender,message);
       return true;
     }
     node=node->next_app_node;//check next node
   }while(node !=NULL);
   return false;
 }
References AppBaseClass::isName(), AppBaseClass::messageHandler(), AppBaseClass::next_app_node, and root.
Referenced by SvcSerialCommandInterface::messageHandler_WREN_SCRIPT_COMPILE(), SvcSerialCommandInterface::messageHandler_WREN_SCRIPT_EXECUTE(), SvcSerialCommandInterface::messageHandler_WREN_SCRIPT_SAVE(), AppAudioToPolyphonic::onFocus(), sendMessageCallback(), and SvcSerialCommandInterface::update().