ERIS CORE: AppManager::getFocus
getFocus()
bool AppManager::getFocus (uint16_t id)
provides an interface for apps to request focus
Parameters
id
Returns
true
false
Definition at line 382 of file AppManager.cpp.
{
   if (appFocusStackIndex == 8) return false;
   appFocusStack[appFocusStackIndex++] = activeID;
   if (pActiveApp!=NULL){
     pActiveApp->onFocusLost();
   }
   pActiveApp = getApp(id);
   pActiveApp->onFocus();
   activeID=id;
   return true;
 }
References activeID, appFocusStack, appFocusStackIndex, getApp(), AppBaseClass::onFocus(), AppBaseClass::onFocusLost(), and pActiveApp.
Referenced by AppBaseClass::getFocus().