ERIS CORE: AppManager Class Reference
AppManager Class Reference
#include <AppManager.h>
Public Member Functions
bool chdir ()
bool chdir (const char *path)
AppBaseClass * getActiveApp ()
provides an interface for apps to request the active app object
AppBaseClass * getApp (uint16_t id)
provides an interface for apps to request another app object by id
bool getFocus (uint16_t id)
provides an interface for apps to request focus
SdFs * getSD ()
provides an interface for apps to request the SdFs object
bool ls ()
uint16_t peekAppFocus ()
provides an interface for apps to request the id of the active app
void printStats ()
prints out some stats in JSON format to the serial port
void RegisterApp (AppBaseClass *app)
provides an interface for apps to register themselves with the AppManager
bool releasePopUp ()
provides an interface for apps to release pop up focus
bool requestPopUp (uint16_t id, bool exclusive=false)
provides an interface for apps to request pop up focus with or without exclusive screen access
bool returnFocus ()
provides an interface for apps to release focus
bool sendMessage (AppBaseClass *sender, const char *to_app, const char *message)
provides an interface for apps to send messages to other apps
void update ()
AppManager update executes single update of the state machine.
Static Public Member Functions
static AppManager * getInstance ()
Public Attributes
SvcDataDictionary * data
Surface * displaySurfaceP
Surface * fastImgCacheSurfaceP
SdFs sd
Private Member Functions
AppManager ()
Construct a new App Manager:: App Manager object using a private constuctor (lazy singleton pattern)
Private Attributes
uint16_t activeID
AnalogInputs analog
Animation animated_wallpaper
uint16_t appFocusStack [8]
uint8_t appFocusStackIndex
uint16_t appPopUpStack [8]
uint8_t appPopUpStackIndex
elapsedMicros cycle_time
uint16_t cycle_time_max
elapsedMillis display_refresh_time
bool exclusive_app_render
elapsedMillis monitor_dd_update_timer
uint16_t nextIDAssignment
TS_Point p
AppBaseClass * pActiveApp
AppBaseClass * root
loopState state
bool touch_state
Static Private Attributes
static AppManager * obj = 0
Detailed Description
Definition at line 33 of file AppManager.h.
Constructor & Destructor Documentation
AppManager()
AppManager::AppManager () private
Construct a new App Manager:: App Manager object using a private constuctor (lazy singleton pattern)
Definition at line 33 of file AppManager.cpp.
{
   data = &_data;
   root = 0;
   activeID = 0;
   pActiveApp = 0;
   nextIDAssignment = 1; //id 0 is reserved
   monitor_dd_update_timer = 0;
   state = redraw_objects;
   //attach the global imgCache buffer to a surface
   memset(imgCache,0,sizeof(imgCache));
   fastImgCacheSurfaceP = new Surface(&imgCache[0],AM_IMG_CACHE_SIZE);
   displaySurfaceP = new Surface(&FB1[0],320,240);
   //init the app focus and app stacks
   memset(&appFocusStack,0,sizeof(appFocusStack));
   memset(&appPopUpStack,0,sizeof(appPopUpStack));
   appFocusStackIndex = 0;
   appPopUpStackIndex = 0;
   exclusive_app_render = false;
   cycle_time_max = 0;
   //init the sd card
   if (!sd.begin(SdioConfig(FIFO_SDIO))){
     Serial.println(F("M AppManager: FATAL! SD Card Not Found "));
     sd.initErrorHalt(&Serial);
   } else {Serial.println(F("AppManager: SD Card FOUND"));}
   //init the display
   Serial.println(F("M AppManager: Config display"));
   draw.setPWMPin(TFT_LED_PWM); //library will control the backlight
   draw.setSD(&sd); //provide a cd pointer to the sd class
   draw.setFrameBuffer(FB1);
   draw.useFrameBuffer(true);
   //render.setPWMPin(TFT_LED_PWM); //library will control the backlight
   //render.setSD(&sd); //provide a cd pointer to the sd class
   //render.setFrameBuffer(FB1);
   //render.useFrameBuffer(true);
   animated_wallpaper.setSD(&sd);
   animated_wallpaper.setPath(UI_ANIMATED_WALLPAPER_PATH);
   Serial.println(F("M AppManager: Init display"));
   draw.begin();
   //render.begin();
   Serial.println(F("M AppManager: Init touch controller"));
   //init the touch screen
   touch.setCalibrationInputs(452,374,3830,3800); //inital cal values; app manager will monitor and update
   touch.setRotation(3);
   touch.begin();
   touch_state = 0;
   //enable cpu temp monitoring
   tempmon_init();
   //set the default template colors for the gui
   data->create(UI_BUTTON_FILL_COLOR,(int32_t)76);
   data->create(UI_BUTTON_SHADE_COLOR,(int32_t)37);
   data->create(UI_BUTTON_ACTIVE_BORDER_COLOR,(int32_t)23254);
   data->create(UI_BUTTON_INACTIVE_BORDER_COLOR,(int32_t)23244);
   data->create(UI_BUTTON_TEXT_COLOR,(int32_t)50713);
   data->create(UI_SLIDER_BORDER_COLOR,(int32_t)44374);
   data->create(UI_SLIDER_SHADE_COLOR,(int32_t)44344);
   data->create(UI_SLIDER_FILL_COLOR,(int32_t)1530);
   data->create(UI_SLIDER_TEXT_COLOR,(int32_t)39222);
   Serial.println(F("M AppManager: Contructor complete"));
   #ifdef ENABLE_ASYNC_SCREEN_UPDATES
   //render.updateScreenAsync(true);
   display_refresh_time = 0;
   #endif
 };
References _data, activeID, AM_IMG_CACHE_SIZE, animated_wallpaper, appFocusStack, appFocusStackIndex, appPopUpStack, appPopUpStackIndex, ILI9341_t3_ERIS::begin(), Touch::begin(), SdBase< Vol >::begin(), SvcDataDictionary::create(), cycle_time_max, data, display_refresh_time, displaySurfaceP, draw(), exclusive_app_render, F, fastImgCacheSurfaceP, FIFO_SDIO, SdBase< Vol >::initErrorHalt(), monitor_dd_update_timer, nextIDAssignment, pActiveApp, redraw_objects, root, sd, Touch::setCalibrationInputs(), Animation::setPath(), ILI9341_t3_ERIS::setPWMPin(), Animation::setSD(), ILI9341_t3_ERIS::setSD(), state, TFT_LED_PWM, touch, and touch_state.
Referenced by getInstance().
Member Function Documentation
chdir() [1/2]
bool AppManager::chdir () inline
Definition at line 72 of file AppManager.h.
 {return sd.chdir();};
References FsVolume::chdir(), and sd.
chdir() [2/2]
bool AppManager::chdir (const char * path) inline
Definition at line 73 of file AppManager.h.
 {return sd.chdir(path);};
References FsVolume::chdir(), and sd.
getActiveApp()
AppBaseClass * AppManager::getActiveApp ()
provides an interface for apps to request the active app object
Returns
AppBaseClass*
Definition at line 393 of file AppManager.cpp.
 { return pActiveApp;}
References pActiveApp.
Referenced by AppSerialCommandInterface::updateRT().
getApp()
AppBaseClass * AppManager::getApp (uint16_t id)
provides an interface for apps to request another app object by id
Parameters
id
Returns
AppBaseClass*
Definition at line 319 of file AppManager.cpp.
{
     AppBaseClass *node = root;
     do{
       if (node->id == id){
         return node;
       }
       node=node->nextAppicationNode;
     }while(node !=NULL);
     return NULL;
 }
References AppBaseClass::id, AppBaseClass::nextAppicationNode, NULL, and root.
Referenced by update().
getFocus()
bool AppManager::getFocus (uint16_t id)
provides an interface for apps to request focus
Parameters
id
Returns
true
false
Definition at line 364 of file AppManager.cpp.
{
   if (appPopUpStackIndex == 8) return false;
   appFocusStack[appFocusStackIndex++] = activeID;
   activeID=id;
   return true;
 }
References activeID, appFocusStack, appFocusStackIndex, and appPopUpStackIndex.
Referenced by AppBaseClass::getFocus().
getInstance()
static AppManager* AppManager::getInstance () inline static
Definition at line 63 of file AppManager.h.
     {
       if (NULL==obj) {
         obj = new AppManager(); //create the object instance if not yet available
       }
       return obj;
     }
References AppManager(), NULL, and obj.
Referenced by AppSerialCommandInterface::AppSerialCommandInterface(), AppBaseClass::getFocus(), loop(), AppBaseClass::releasePopUp(), AppBaseClass::requestPopUp(), AppBaseClass::returnFocus(), AppBaseClass::selfRegister(), and AppSerialCommandInterface::updateRT().
getSD()
SdFs * AppManager::getSD ()
provides an interface for apps to request the SdFs object
Returns
SdFs*
Definition at line 309 of file AppManager.cpp.
{
   return &sd;
 }
References sd.
Referenced by AppSerialCommandInterface::AppSerialCommandInterface().
ls()
bool AppManager::ls () inline
Definition at line 74 of file AppManager.h.
 {return sd.ls();};
References FsVolume::ls(), and sd.
peekAppFocus()
uint16_t AppManager::peekAppFocus ()
provides an interface for apps to request the id of the active app
Returns
uint16_t
Definition at line 387 of file AppManager.cpp.
 {return activeID;}
References activeID.
printStats()
void AppManager::printStats ()
prints out some stats in JSON format to the serial port
Definition at line 419 of file AppManager.cpp.
{
   AppBaseClass *node = root;
   if (node == NULL) return;
   Serial.print(F("STATS {\"APPS\":{"));
   do{
     Serial.print(F("\""));
     Serial.print(node->name);
     Serial.print(F("\":{"));
     //Serial.print("\tupdate_loop_time: ");Serial.print(node->update_loop_time);
     Serial.print(F("\"update_loop_time_max\":"));Serial.print(node->update_loop_time_max);Serial.print(F(","));
     //Serial.print("\tupdateRT_loop_time: ");Serial.print(node->updateRT_loop_time);
     Serial.print(F("\"updateRT_loop_time_max\":"));Serial.print(node->updateRT_loop_time_max);Serial.print(F(","));
     //Serial.print("\tcycle_time: ");Serial.print(node->cycle_time);
     Serial.print(F("\"cycle_time_max\":"));Serial.print(node->cycle_time_max);Serial.print(F(","));
     //Serial.print("\tupdate_call_period: ");Serial.print(node->update_call_period);
     Serial.print(F("\"update_call_period_max\":"));Serial.print(node->update_call_period_max);Serial.print(F(","));
     Serial.print(F("\"updateRT_call_period_max\":"));Serial.print(node->updateRT_call_period_max);
     Serial.print(F("},"));
     //clear the stats
     node->update_loop_time_max = 0;
     node->updateRT_loop_time_max = 0;
     node->cycle_time_max = 0;
     node->update_call_period_max = 0;
     node->updateRT_call_period_max = 0;
     node=node->nextAppicationNode;//check next node
   }while(node !=NULL);
   if (root != 0){
     Serial.print(F("\"root\":\""));Serial.print(root->name);Serial.print(F("\""));
   }else{
     Serial.print(F("\"root\":"));Serial.print(F("\"NULL\""));
   }
   Serial.println(F("}}"));
   //print app manager stats
   Serial.print(F("STATS {\"APPMANAGER\":{"));
   Serial.print(F("\"cycle_time\":"));Serial.print(cycle_time);Serial.print(F(","));
   Serial.print(F("\"cycle_time_max\":"));Serial.print(cycle_time_max);Serial.print(F(","));
   Serial.print(F("\"touch_state\":"));Serial.print(touch_state);Serial.print(F(","));
   Serial.print(F("\"active_app_id\":"));Serial.print(activeID);Serial.print(F(","));
   Serial.print(F("\"exclusive_app_render\":"));Serial.print(exclusive_app_render);
   Serial.println(F("}}"));
   //clear the app manager stats
   cycle_time_max = 0;
   return;
 }
References activeID, cycle_time, AppBaseClass::cycle_time_max, cycle_time_max, exclusive_app_render, F, AppBaseClass::name, AppBaseClass::nextAppicationNode, NULL, root, touch_state, AppBaseClass::update_call_period_max, AppBaseClass::update_loop_time_max, AppBaseClass::updateRT_call_period_max, and AppBaseClass::updateRT_loop_time_max.
Referenced by AppSerialCommandInterface::updateRT().
RegisterApp()
void AppManager::RegisterApp (AppBaseClass * app)
provides an interface for apps to register themselves with the AppManager
Parameters
app
Definition at line 468 of file AppManager.cpp.
{
   //assign a unique id to the object
   app->id = nextIDAssignment++;
   app->draw = &draw;
   app->am = this;
   app->sd = &sd;
   if (root == 0) {root = app; return;}
   else{
     AppBaseClass *endNode = root;
     //add to the linked list
     while(endNode->nextAppicationNode !=0){endNode=endNode->nextAppicationNode;}
     endNode->nextAppicationNode = app;
     app->previousAppicationNode = endNode;
   }
 };
References AppBaseClass::am, AppBaseClass::draw, draw(), AppBaseClass::id, AppBaseClass::nextAppicationNode, nextIDAssignment, AppBaseClass::previousAppicationNode, root, AppBaseClass::sd, and sd.
Referenced by AppBaseClass::selfRegister().
releasePopUp()
bool AppManager::releasePopUp ()
provides an interface for apps to release pop up focus
Returns
true
false
Definition at line 350 of file AppManager.cpp.
{
   if (appFocusStackIndex == 0)return false;
   appPopUpStackIndex-=1;
   appPopUpStack[appPopUpStackIndex] = 0;
   exclusive_app_render = false;
   return true;
 }
References appFocusStackIndex, appPopUpStack, appPopUpStackIndex, and exclusive_app_render.
Referenced by AppBaseClass::releasePopUp().
requestPopUp()
bool AppManager::requestPopUp (uint16_t id, bool exclusive = false)
provides an interface for apps to request pop up focus with or without exclusive screen access
Parameters
id
exclusive
Returns
true
false
Definition at line 337 of file AppManager.cpp.
{
   if (appPopUpStackIndex == 8) return false;
   appPopUpStack[appPopUpStackIndex] = id;
   appPopUpStackIndex+=1;
   exclusive_app_render = exclusive;
   return true;
 }
References appPopUpStack, appPopUpStackIndex, and exclusive_app_render.
Referenced by AppBaseClass::requestPopUp().
returnFocus()
bool AppManager::returnFocus ()
provides an interface for apps to release focus
Returns
true
false
Definition at line 376 of file AppManager.cpp.
{
   if (appFocusStackIndex == 0) return false;
   activeID = appFocusStack[--appFocusStackIndex];//load from the stack
   appFocusStack[appFocusStackIndex] = 0;
   return true;
 }
References activeID, appFocusStack, and appFocusStackIndex.
Referenced by AppBaseClass::returnFocus().
sendMessage()
bool AppManager::sendMessage (AppBaseClass * sender, const char * to_app, const char * message)
provides an interface for apps to send messages to other apps
Parameters
sender
to_app
message
Returns
true
false
Definition at line 403 of file AppManager.cpp.
{
   // sends a message to the requested app
   AppBaseClass *node = root;
   do{
     if (node->isName(to_app)){
       node->MessageHandler(sender,message);
       return true;
     }
     node=node->nextAppicationNode;//check next node
   }while(node !=NULL);
   return false;
 }
References AppBaseClass::isName(), AppBaseClass::MessageHandler(), AppBaseClass::nextAppicationNode, NULL, and root.
Referenced by AppAudioToPolyphonic::onFocus(), and AppSerialCommandInterface::updateRT().
update()
void AppManager::update ()
AppManager update executes single update of the state machine.
Definition at line 105 of file AppManager.cpp.
{
     elapsedMicros app_time;
     uint32_t heapTop;
     uint32_t drt;
     bool touch_updated;
     bool update_analog;
     AppBaseClass *node;
     bool monitor_update;
     monitor_update = (monitor_dd_update_timer > APPMANAGER_MONITOR_DD_UPDATE_RATE_MSEC);
     cycle_time=0;
     drt = display_refresh_time;
     touch_updated = false;
     node = root;
     if (node == 0){
       Serial.println(F("AppManager::update called without an application initalized"));
       return;
     }
     //update analog inputs
     update_analog = analog.update();
     //update loop is directed by the state variable
     switch(state){
       case redraw_background:
         app_time=0;
         if (!draw.busy()){
             data->update(RENDER,(int32_t)0);
           if (animated_wallpaper.getNextFrameChunk()){
               draw.bltSDAnimationFullScreen(&animated_wallpaper);
               data->update(AM_REDRAW_BG,(int32_t)app_time);
           } else Serial.println(F("M bad chunk"));
         } else Serial.println(F("M draw busy"));
         if ((data->read(RENDER) == 0) && animated_wallpaper.isFrameComplete()){
           data->update(RENDER,(int32_t)1);
           state = redraw_objects;
         }
         break;
       case redraw_wait://idle render time to give the screen refresh a head start
         if (drt > 22){ //magic number is to tune the delay between frame buffer writes
                        //as the data is simutaniously being written out to SPI.
                        //This ensures we are not overwritting the current frame
                        //with the next frame.
           if(exclusive_app_render) state = redraw_objects;
           else state = redraw_background;
         };
         //note: this is  a good place for application manager housekeeping tasks where screen access is not required
         data->update(AM_AUDIO_CPU_MAX,(float32_t)AudioProcessorUsageMax());
         float32_t cpu;
         cpu = AudioProcessorUsage();
         data->update(AM_AUDIO_CPU,(float32_t)cpu);
         data->update(AM_AUDIO_MEM_MAX,(int32_t)AudioMemoryUsageMax());
         data->update(AM_AUDIO_MEM,(int32_t)AudioMemoryUsage());
         break;
       case redraw_render:
         app_time=0;
         data->update(RENDER_PERIOD,(int32_t)drt);
         data->update(RENDER,(int32_t)4);
         data->increment(RENDER_FRAME);
         draw.updateScreenAsync(false);//updateScreenAsyncFrom(&draw,false);
         state = redraw_wait;
         display_refresh_time = 0;
         break;
       case redraw_objects:
         node = root;
         if (exclusive_app_render == false){
           do{
               app_time=0;
               if (node->update_call_period > node->update_call_period_max) node->update_call_period_max = node->update_call_period;
               node->update(); //update active window
               node->update_loop_time = app_time;
               if (node->update_loop_time > node->update_loop_time_max){
                   node->update_loop_time_max = node->update_loop_time;
               }
               //update the data dictionary
               node->update_call_period =0;
               node=node->nextAppicationNode;//check next node
             }while(node !=NULL);
         };
         data->update(RENDER,(int32_t)2);
         data->increment(UPDATE_CALLS);
         state = redraw_popup;
         break;
       case redraw_popup:
         app_time=0;
         //draw any popups
         if (!appPopUpStackIndex==0 && appPopUpStack[appPopUpStackIndex-1] != 0){
           node = getApp(appPopUpStack[appPopUpStackIndex-1]);
           if (node != 0){
             //Serial.println(F("AppManager::redraw_popup"));
             node->update();
           }
         }
         data->update(RENDER,(int32_t)3);
         state = redraw_render;
         break;
     }
     //always call the apps updateRT function on every loop
     touch.update();
     touch_updated = true;
     data->increment(RT_CALLS);
     node = root;
     bool isactive_child;
     do{
       app_time=0;
       if (node->updateRT_priority > 0){
         node->updateRT_priority--;
       }else{
         if (node->updateRT_call_period > node->updateRT_call_period_max) node->updateRT_call_period_max = node->updateRT_call_period;
         node->updateRT(); //real time update (always called)
         node->updateRT_loop_time = app_time;
         if (node->updateRT_loop_time > node->updateRT_loop_time_max) node->updateRT_loop_time_max = node->updateRT_loop_time;
         node->updateRT_call_period =0;
       }
       isactive_child = false;
       if (node->id == activeID && !draw.busy()) {
           if (pActiveApp != node){
             if (pActiveApp != 0) pActiveApp->onFocusLost();
             node->onFocus();
             pActiveApp = node;
           }
       }
       if (node->parentNode!=NULL){if(node->parentNode->id == activeID){isactive_child = true;}}; //send event triggers to any child apps
       if (node->id == activeID || isactive_child) {
           //Serial.print("AppManager::updating active application");Serial.println(activeID);
           //trigger any events and then call the update function for this 'active' app or child node
           if (update_analog){
             data->update(AM_AN1,(int32_t)analog.readAN1());
             data->update(AM_AN2,(int32_t)analog.readAN2());
             data->update(AM_AN3,(int32_t)analog.readAN3());
             data->update(AM_AN4,(int32_t)analog.readAN4());
             node->onAnalog1(analog.readAN1(),analog.freadAN1());
             node->onAnalog2(analog.readAN2(),analog.freadAN2());
             node->onAnalog3(analog.readAN3(),analog.freadAN3());
             node->onAnalog4(analog.readAN4(),analog.freadAN4());
           }
           if (touch_updated == true && touch.touched()) {
             p = touch.getPoint();
             //data->update("TOUCH_X",(int32_t)p.x);
             //data->update("TOUCH_Y",(int32_t)p.y);
             data->update("TOUCH_Z",(int32_t)p.z);
             if (node->touch_state == 0){
                 node->onTouch(p.x, p.y);
                 node->touch_state=1;
             } else{
                 node->onTouchDrag(p.x, p.y);
             }
           } else if (node->touch_state==1){
             node->touch_state=0;
             node->onTouchRelease(p.x, p.y);
           }
       }
       node->cycle_time = cycle_time;
       if (node->cycle_time > node->cycle_time_max){
           node->cycle_time_max = node->cycle_time;
       }
       node=node->nextAppicationNode;//check next node
     }while(node !=NULL);
     if (cycle_time > cycle_time_max){
       cycle_time_max = cycle_time;
     } else{
       //delayMicroseconds((cycle_time_max - cycle_time)/100);
     }
     if(monitor_update){
       monitor_dd_update_timer = 0;
       data->update(AM_LOOP_TIME,(int32_t)cycle_time_max);
       data->update(AM_SERIAL_AVAIL,(int32_t)Serial.availableForWrite());
       //data->update("FRAME_PTR1",(int32_t)draw.getFrameAddress());
       //data->update("FRAME_PTR2",(int32_t)render.getFrameAddress());
       int32_t free_mem;
       void* htop;
       free_mem = 1000;
       cycle_time_max*=0.999;
       htop = malloc(1000);
       while (htop){
         memset(htop,0x5A,1000);
         heapTop = (uint32_t) htop;
         free(htop);
         free_mem += 1000;
         htop = malloc(free_mem);
       }
       data->update(FREE_MEM,(int32_t)(free_mem - 1000));
       data->update(HEAP_FREE,(int32_t)(0x20280000 - heapTop));
       data->update(LOCAL_MEM,(int32_t)(0x2007F000 - (uint32_t)(&heapTop)));
       heapTop = 0;
       data->update(CPU_TEMP,(float32_t)tempmonGetTemp());
       AudioProcessorUsageMaxReset();
       AudioMemoryUsageMaxReset();
     }
 };
References activeID, analog, animated_wallpaper, APPMANAGER_MONITOR_DD_UPDATE_RATE_MSEC, appPopUpStack, appPopUpStackIndex, AudioMemoryUsage, AudioMemoryUsageMax, AudioMemoryUsageMaxReset, AudioProcessorUsage, AudioProcessorUsageMax, AudioProcessorUsageMaxReset, ILI9341_t3_ERIS::bltSDAnimationFullScreen(), ILI9341_t3_ERIS::busy(), AppBaseClass::cycle_time, cycle_time, AppBaseClass::cycle_time_max, cycle_time_max, data, display_refresh_time, draw(), exclusive_app_render, F, AnalogInputs::freadAN1(), AnalogInputs::freadAN2(), AnalogInputs::freadAN3(), AnalogInputs::freadAN4(), getApp(), Animation::getNextFrameChunk(), Touch::getPoint(), AppBaseClass::id, SvcDataDictionary::increment(), Animation::isFrameComplete(), monitor_dd_update_timer, AppBaseClass::nextAppicationNode, NULL, AppBaseClass::onAnalog1(), AppBaseClass::onAnalog2(), AppBaseClass::onAnalog3(), AppBaseClass::onAnalog4(), AppBaseClass::onFocus(), AppBaseClass::onFocusLost(), AppBaseClass::onTouch(), AppBaseClass::onTouchDrag(), AppBaseClass::onTouchRelease(), p, pActiveApp, AppBaseClass::parentNode, SvcDataDictionary::read(), AnalogInputs::readAN1(), AnalogInputs::readAN2(), AnalogInputs::readAN3(), AnalogInputs::readAN4(), redraw_background, redraw_objects, redraw_popup, redraw_render, redraw_wait, root, state, touch, AppBaseClass::touch_state, Touch::touched(), AnalogInputs::update(), AppBaseClass::update(), Touch::update(), SvcDataDictionary::update(), AppBaseClass::update_call_period, AppBaseClass::update_call_period_max, AppBaseClass::update_loop_time, AppBaseClass::update_loop_time_max, AppBaseClass::updateRT(), AppBaseClass::updateRT_call_period, AppBaseClass::updateRT_call_period_max, AppBaseClass::updateRT_loop_time, AppBaseClass::updateRT_loop_time_max, and AppBaseClass::updateRT_priority.
Referenced by loop().
Member Data Documentation
activeID
uint16_t AppManager::activeID private
Definition at line 40 of file AppManager.h.
Referenced by AppManager(), getFocus(), peekAppFocus(), printStats(), returnFocus(), and update().
analog
AnalogInputs AppManager::analog private
Definition at line 36 of file AppManager.h.
Referenced by update().
animated_wallpaper
Animation AppManager::animated_wallpaper private
Definition at line 45 of file AppManager.h.
Referenced by AppManager(), and update().
appFocusStack
uint16_t AppManager::appFocusStack[8] private
Definition at line 49 of file AppManager.h.
Referenced by AppManager(), getFocus(), and returnFocus().
appFocusStackIndex
uint8_t AppManager::appFocusStackIndex private
Definition at line 51 of file AppManager.h.
Referenced by AppManager(), getFocus(), releasePopUp(), and returnFocus().
appPopUpStack
uint16_t AppManager::appPopUpStack[8] private
Definition at line 50 of file AppManager.h.
Referenced by AppManager(), releasePopUp(), requestPopUp(), and update().
appPopUpStackIndex
uint8_t AppManager::appPopUpStackIndex private
Definition at line 52 of file AppManager.h.
Referenced by AppManager(), getFocus(), releasePopUp(), requestPopUp(), and update().
cycle_time
elapsedMicros AppManager::cycle_time private
Definition at line 43 of file AppManager.h.
Referenced by printStats(), and update().
cycle_time_max
uint16_t AppManager::cycle_time_max private
Definition at line 41 of file AppManager.h.
Referenced by AppManager(), printStats(), and update().
data
SvcDataDictionary* AppManager::data
Definition at line 60 of file AppManager.h.
Referenced by AppManager(), AppCQT::init(), AppAudioToPolyphonic::initMyAppExample(), AppAudioToPolyphonic::update(), update(), AppScope::update(), ControlButton::update(), ControlSlider::update(), AppCQT::updateOscillatorBank(), AppCQT::updateRT(), AppScope::updateRT(), and AppSerialCommandInterface::updateRT().
display_refresh_time
elapsedMillis AppManager::display_refresh_time private
Definition at line 42 of file AppManager.h.
Referenced by AppManager(), and update().
displaySurfaceP
Surface* AppManager::displaySurfaceP
Definition at line 62 of file AppManager.h.
Referenced by AppManager(), and ControlButton::update().
exclusive_app_render
bool AppManager::exclusive_app_render private
Definition at line 53 of file AppManager.h.
Referenced by AppManager(), printStats(), releasePopUp(), requestPopUp(), and update().
fastImgCacheSurfaceP
Surface* AppManager::fastImgCacheSurfaceP
Definition at line 61 of file AppManager.h.
Referenced by AppManager(), and ControlButton::update().
monitor_dd_update_timer
elapsedMillis AppManager::monitor_dd_update_timer private
Definition at line 44 of file AppManager.h.
Referenced by AppManager(), and update().
nextIDAssignment
uint16_t AppManager::nextIDAssignment private
Definition at line 39 of file AppManager.h.
Referenced by AppManager(), and RegisterApp().
obj
AppManager * AppManager::obj = 0 static private
Definition at line 35 of file AppManager.h.
Referenced by getInstance().
p
TS_Point AppManager::p private
Definition at line 47 of file AppManager.h.
Referenced by update().
pActiveApp
AppBaseClass* AppManager::pActiveApp private
Definition at line 38 of file AppManager.h.
Referenced by AppManager(), getActiveApp(), and update().
root
AppBaseClass* AppManager::root private
Definition at line 37 of file AppManager.h.
Referenced by AppManager(), getApp(), printStats(), RegisterApp(), sendMessage(), and update().
sd
SdFs AppManager::sd
Definition at line 59 of file AppManager.h.
Referenced by AppManager(), chdir(), getSD(), ls(), RegisterApp(), and ControlButton::update().
state
loopState AppManager::state private
Definition at line 46 of file AppManager.h.
Referenced by AppManager(), and update().
touch_state
bool AppManager::touch_state private
Definition at line 48 of file AppManager.h.
Referenced by AppManager(), and printStats().
The documentation for this class was generated from the following files:
ERISCore/include/AppManager.h
ERISCore/src/AppManager.cpp