ERIS CORE: AppManager::returnFocus
returnFocus()
bool AppManager::returnFocus ()
provides an interface for apps to release focus
Returns
true
false
Definition at line 438 of file AppManager.cpp.
{
   if (app_focus_stack_index == 0) return false;
   getApp(active_app_id)->onFocusLost();
   active_app_id = app_focus_stack[--app_focus_stack_index];//load from the stack
   p_active_app = getApp(active_app_id);
   if(p_active_app!=NULL) p_active_app->onFocus();
   app_focus_stack[app_focus_stack_index] = 0;
   return true;
 }
References active_app_id, app_focus_stack, app_focus_stack_index, getApp(), AppBaseClass::onFocus(), AppBaseClass::onFocusLost(), and p_active_app.
Referenced by AppBaseClass::returnFocus().