ERIS CORE: AppManager::getInstance
getInstance()
static AppManager* AppManager::getInstance () inline static
Definition at line 65 of file AppManager.h.
     {
       if (NULL==obj) {
         obj = new AppManager(); //create the object instance if not yet available
       }
       return obj;
     }
References AppManager(), and obj.
Referenced by SvcSerialCommandInterface::SvcSerialCommandInterface(), audioDirectorConnectCallback(), audioDirectorDisconnectAllCallback(), audioDirectorDisconnectCallback(), audioDirectorGetFunctionListCallback(), audioDirectorGetTypeInstanceCountCallback(), audioDirectorGetTypeListCallback(), bltCallback(), dataDictReadCallback(), dataDictReadFloatCallback(), dataDictUpdateCallback(), dataDictUpdateFloatCallback(), drawDisablePixelOp(), drawEnablePixelOp(), drawFillCallback(), drawLineCallback(), drawUseSDFileSystem(), drawUseWrenFileSystem(), fileAvailableCallback(), fileCloseCallback(), fileFlushCallback(), fileIsDirectoryCallback(), fileIsOpenCallback(), fileNameCallback(), fileOpenNextCallback(), filePeekCallback(), filePositionCallback(), fileReadBytesCallback(), fileReadCallback(), fileRewindDirectoryCallback(), fileSeekCallback(), fileSizeCallback(), fileTruncateCallback(), fileWriteCallback(), fsExistsCallback(), fsFormat(), fsimportFromSD(), fsMkdirCallback(), fsOpenCallback(), fsRemoveCallback(), fsRenameCallback(), fsRmdirCallback(), fsTotalSizeCallback(), fsUsedSizeCallback(), AppBaseClass::getFocus(), getFocusCallback(), getImageSizeCallback(), getPixelCallback(), getSourceForModule(), handleClockCallback(), handleControlChangeCallback(), handleNoteOffCallback(), handleNoteOnCallback(), handleProgramChangeCallback(), loadImageCallback(), loadImageSurfaceCallback(), loadModuleComplete(), loop(), printCallback(), printWithFontCallback(), AppBaseClass::releasePopUp(), releasePopUpCallback(), AppBaseClass::requestPopUp(), requestPopUpCallback(), restartVMCallback(), AppBaseClass::returnFocus(), returnFocusCallback(), AppBaseClass::selfRegister(), sendMessageCallback(), setClockSpeedCallback(), setCursorCallback(), setDimensionCallback(), setPixelCallback(), setPositionCallback(), setTextColorCallback(), setWidgetDimensionCallback(), setWidgetPositionCallback(), SvcSerialCommandInterface::update(), and writeFn().