ERIS CORE: AppManager::requestArmSetClock
requestArmSetClock()
bool AppManager::requestArmSetClock (uint32_t requested_cpu_frequency)
provides an interface for apps to request cpu freq change note: this is only a request. the actual frequency will vary based on the allowed freq range and current cpu temp
Parameters
requested_cpu_frequency
Returns
true
false
Definition at line 574 of file AppManager.cpp.
{
     //set cpu freq based on thermal performance
     if(tempmonGetTemp() > CPU_THERMAL_THROTTLE_TEMP){
       set_arm_clock(CPU_LOW_POWER_MODE_FREQ);//thermal guard (safer but not failsafe)
       data->update("F_CPU_ACTUAL",(int32_t)F_CPU_ACTUAL);
       return false;
     } else {
       //silently cap the requested freq
       if(requested_cpu_frequency > CPU_BOOST_MAX_FREQ) requested_cpu_frequency = CPU_BOOST_MAX_FREQ;
       set_arm_clock(requested_cpu_frequency);
       data->update("F_CPU_ACTUAL",(int32_t)F_CPU_ACTUAL);
       return true;
     }
 }
References data, set_arm_clock(), and SvcDataDictionary::update().
Referenced by AppCQT::render(), setClockSpeedCallback(), and update().