ERIS CORE: AppManager::getAppByName
getAppByName()
AppBaseClass * AppManager::getAppByName (const char * appName)
Get the App pointer By Name. Returns NULL if not found.
Parameters
appName
Returns
AppBaseClass*
Definition at line 489 of file AppManager.cpp.
{
   AppBaseClass *node = root;
   do{
     if (node->isName(appName)){
       return node;
     }
     node=node->next_app_node;//check next node
   }while(node !=NULL);
   return NULL;
 }
References AppBaseClass::isName(), AppBaseClass::next_app_node, and root.
Referenced by AppAudioToPolyphonic::~AppAudioToPolyphonic(), audioDirectorConnectCallback(), audioDirectorDisconnectAllCallback(), audioDirectorDisconnectCallback(), audioDirectorGetArbWaveFormCallback(), audioDirectorGetFunctionListCallback(), audioDirectorGetTypeInstanceCountCallback(), audioDirectorGetTypeListCallback(), bltCallback(), bltFBCallback(), bltInPlaceCallback(), bltInPlaceFBCallback(), drawDisablePixelOp(), drawEnablePixelOp(), drawFillCallback(), drawLineCallback(), drawUseSDFileSystem(), drawUseWrenFileSystem(), fileAvailableCallback(), fileCloseCallback(), fileFlushCallback(), fileIsDirectoryCallback(), fileIsOpenCallback(), fileNameCallback(), fileOpenNextCallback(), filePeekCallback(), filePositionCallback(), fileReadBytesCallback(), fileReadCallback(), fileRewindDirectoryCallback(), fileSeekCallback(), fileSizeCallback(), fileTruncateCallback(), fileWriteCallback(), fsExistsCallback(), fsFormat(), fsimportFromSD(), fsMkdirCallback(), fsOpenCallback(), fsRemoveCallback(), fsRenameCallback(), fsRmdirCallback(), fsTotalSizeCallback(), fsUsedSizeCallback(), getFocusCallback(), getImageSizeCallback(), getPixelCallback(), getSourceForModule(), handleControlChangeCallback(), handleNoteOffCallback(), handleNoteOnCallback(), handleProgramChangeCallback(), loadImageCallback(), loadImageSurfaceCallback(), loadModuleComplete(), printCallback(), printStats(), printWithFontCallback(), releasePopUpCallback(), AppAudioToPolyphonic::render(), requestPopUpCallback(), restartVMCallback(), returnFocusCallback(), sendMessageCallback(), setCursorCallback(), setDimensionCallback(), setPixelCallback(), setPositionCallback(), setTextColorCallback(), setWidgetDimensionCallback(), setWidgetPositionCallback(), SvcSerialCommandInterface::update(), and writeFn().