ERIS CORE: AppManager::printStats
printStats()
void FASTRUN AppManager::printStats ()
prints out some stats in JSON format to the serial port
Definition at line 504 of file AppManager.cpp.
{
   SvcSerialCommandInterface* sci;
   sci = (SvcSerialCommandInterface*)getAppByName("SCI"); //request the serial command interface
   if(sci!=NULL){
     AppBaseClass *node = root;
     if (node == NULL) return;
     do{
       if(sci->requestStartLZ4Message()==true){
         sci->print(F("STATS {\"APPS\":{\""));
         sci->print(node->name);
         sci->print(F("\":{"));
         sci->print(F("\"render_period_max\":"));sci->print(node->render_period_max);sci->print(",");
         sci->print(F("\"render_cpu_time_max\":"));sci->print(node->render_cpu_time_max);sci->print(",");
         sci->print(F("\"update_period_max\":"));sci->print(node->update_period_max);sci->print(",");
         sci->print(F("\"update_cpu_time_max\":"));sci->print(node->update_cpu_time_max);
         sci->println("}}}");
         sci->sendLZ4Message();
       }
       //clear the stats
       node->render_cpu_time_max = 0;
       node->update_cpu_time_max = 0;
       node->cycle_time_max = 0;
       node->render_period_max = 0;
       node->update_period_max = 0;
       node=node->next_app_node;//check next node
     }while(node !=NULL);
     if(sci->requestStartLZ4Message()==true){
       sci->print(F("STATS {\"APPMANAGER\":{"));
       sci->print(F("\"cycle_time\":"));sci->print(cycle_time);sci->print(F(","));
       sci->print(F("\"cycle_time_max\":"));sci->print(cycle_time_max);sci->print(F(","));
       sci->print(F("\"touch_state\":"));sci->print(touch_state);sci->print(F(","));
       sci->print(F("\"active_app_id\":"));sci->print(active_app_id);sci->print(F(","));
       sci->print(F("\"exclusive_app_render\":"));sci->print(exclusive_app_render);
       sci->println(F("}}"));
       sci->sendLZ4Message();
     }
     //clear the app manager stats
     cycle_time_max = 0;
   }
   return;
 }
References active_app_id, cycle_time, AppBaseClass::cycle_time_max, cycle_time_max, exclusive_app_render, getAppByName(), AppBaseClass::name, AppBaseClass::next_app_node, AppBaseClass::render_cpu_time_max, AppBaseClass::render_period_max, SvcSerialCommandInterface::requestStartLZ4Message(), root, sci, SvcSerialCommandInterface::sendLZ4Message(), touch_state, AppBaseClass::update_cpu_time_max, and AppBaseClass::update_period_max.
Referenced by SvcSerialCommandInterface::update().