ERIS CORE: AppManager::AppManager
AppManager()
FLASHMEM AppManager::AppManager () private
Construct a new App Manager:: App Manager object using a private constuctor (lazy singleton pattern)
Definition at line 45 of file AppManager.cpp.
{
   ad = 0;
   data = &_data;
   root = 0;
   active_app_id = 0;
   p_active_app = 0;
   next_id_assignment = 1; //id 0 is reserved
   monitor_dd_update_timer = 0;
   state = redraw_objects;
   //attach the global imgCache buffer to a surface
   memset(imgCache,0,sizeof(imgCache));
   p_fast_img_cache_surface = new Surface(&imgCache[0],AM_IMG_CACHE_SIZE);
   p_display_surface = new Surface(&FB1[0],320,240);
   //init the app focus and app stacks
   memset(&app_focus_stack,0,sizeof(app_focus_stack));
   memset(&app_popup_stack,0,sizeof(app_popup_stack));
   app_focus_stack_index = 0;
   app_popup_stack_index = 0;
   exclusive_app_render = false;
   cycle_time_max = 0;
   //init the sd card
   if (!sd.begin(SdioConfig(FIFO_SDIO))){
     Serial.println(F("M AppManager: FATAL! SD Card Not Found "));
     sd.initErrorHalt(&Serial);
   } else {Serial.println(F("AppManager: SD Card FOUND"));}
   //init the display
   Serial.println(F("M AppManager: Config display"));
   draw.setPWMPin(TFT_LED_PWM); //library will control the backlight
   draw.setSD(&sd); //provide a cd pointer to the sd class
   draw.setFrameBuffer(FB1);
   draw.useFrameBuffer(true);
   //render.setPWMPin(TFT_LED_PWM); //library will control the backlight
   //render.setSD(&sd); //provide a cd pointer to the sd class
   //render.setFrameBuffer(FB1);
   //render.useFrameBuffer(true);
   animated_wallpaper.setSD(&sd);
   animated_wallpaper.setPath(UI_ANIMATED_WALLPAPER_PATH);
   Serial.println(F("M AppManager: Init display"));
   draw.begin();
   //render.begin();
   Serial.println(F("M AppManager: Init touch controller"));
   //init the touch screen
   touch.setCalibrationInputs(452,374,3830,3800); //inital cal values; app manager will monitor and update
   touch.setRotation(3);
   touch.begin();
   touch_state = 0;
   //enable cpu temp monitoring
   tempmon_init();
   //set the default template colors for the gui
   data->create(UI_BUTTON_FILL_COLOR,(int32_t)76);
   data->create(UI_BUTTON_SHADE_COLOR,(int32_t)37);
   data->create(UI_BUTTON_ACTIVE_BORDER_COLOR,(int32_t)23254);
   data->create(UI_BUTTON_INACTIVE_BORDER_COLOR,(int32_t)23244);
   data->create(UI_BUTTON_TEXT_COLOR,(int32_t)50713);
   data->create(UI_SLIDER_BORDER_COLOR,(int32_t)44374);
   data->create(UI_SLIDER_SHADE_COLOR,(int32_t)44344);
   data->create(UI_SLIDER_FILL_COLOR,(int32_t)1530);
   data->create(UI_SLIDER_TEXT_COLOR,(int32_t)39222);
   Serial.println(F("M AppManager: Contructor complete"));
   #ifdef ENABLE_ASYNC_SCREEN_UPDATES
   //render.updateScreenAsync(true);
   display_refresh_time = 0;
   #endif
 };
References _data, active_app_id, ad, animated_wallpaper, app_focus_stack, app_focus_stack_index, app_popup_stack, app_popup_stack_index, ILI9341_t3_ERIS::begin(), Touch::begin(), SvcDataDictionary::create(), cycle_time_max, data, display_refresh_time, draw(), exclusive_app_render, monitor_dd_update_timer, next_id_assignment, p_active_app, p_display_surface, p_fast_img_cache_surface, redraw_objects, root, sd, Touch::setCalibrationInputs(), Animation::setPath(), ILI9341_t3_ERIS::setPWMPin(), Animation::setSD(), ILI9341_t3_ERIS::setSD(), state, touch, and touch_state.
Referenced by getInstance().