ERIS CORE: AppManager::getApp
getApp()
AppBaseClass * AppManager::getApp (uint16_t id)
provides an interface for apps to request another app object by id
Parameters
id
Returns
AppBaseClass*
Definition at line 369 of file AppManager.cpp.
{
     AppBaseClass *node = root;
     do{
       if (node->id == id){
         return node;
       }
       node=node->next_app_node;
     }while(node !=NULL);
     return NULL;
 }
References AppBaseClass::id, AppBaseClass::next_app_node, and root.
Referenced by getFocus(), SvcMIDI::publish(), returnFocus(), and update().