ERIS CORE: SdBase< Vol > Class Template Reference
SdBase< Vol > Class Template Reference
base SD file system template class.
#include <SdFat-beta.h>
Public Member Functions
bool begin (SdCsPin_t csPin, uint32_t maxSck)
bool begin (SdCsPin_t csPin=SS)
bool begin (SdioConfig sdioConfig)
bool begin (SdSpiConfig spiConfig)
SdCard * card ()
bool cardBegin (SdioConfig sdioConfig)
bool cardBegin (SdSpiConfig spiConfig)
void errorHalt ()
void errorHalt (const __FlashStringHelper *msg)
void errorHalt (const char *msg)
void errorHalt (print_t *pr)
void errorHalt (print_t *pr, const __FlashStringHelper *msg)
void errorHalt (print_t *pr, const char *msg)
void errorPrint (const __FlashStringHelper *msg)
void errorPrint (const char *msg)
void errorPrint (Print *pr, const __FlashStringHelper *msg)
void errorPrint (print_t *pr)
void errorPrint (print_t *pr, char const *msg)
void initErrorHalt ()
void initErrorHalt (const __FlashStringHelper *msg)
void initErrorHalt (const char *msg)
void initErrorHalt (Print *pr, const __FlashStringHelper *msg)
void initErrorHalt (print_t *pr)
void initErrorHalt (print_t *pr, const char *msg)
void initErrorPrint ()
void initErrorPrint (Print *pr)
void printFatType (print_t *pr)
void printSdError (print_t *pr)
uint8_t sdErrorCode ()
uint8_t sdErrorData ()
Vol * vol ()
bool volumeBegin ()
Detailed Description
template<class Vol>
class SdBase< Vol >
base SD file system template class.
Definition at line 49 of file SdFat-beta.h.
Member Function Documentation
begin() [1/4]
template<class Vol > bool SdBase< Vol >::begin (SdCsPin_t csPin, uint32_t maxSck) inline
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
[in] maxSck Maximum SCK frequency.
Returns
true for success or false for failure.
Definition at line 72 of file SdFat-beta.h.
{
     return begin(SdSpiConfig(csPin, SHARED_SPI, maxSck));
   }
References SdBase< Vol >::begin(), and SHARED_SPI.
begin() [2/4]
template<class Vol > bool SdBase< Vol >::begin (SdCsPin_t csPin = SS) inline
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
Returns
true for success or false for failure.
Definition at line 57 of file SdFat-beta.h.
{
 #ifdef BUILTIN_SDCARD
     if (csPin == BUILTIN_SDCARD) {
       return begin(SdioConfig(FIFO_SDIO));
     }
 #endif  // BUILTIN_SDCARD
     return begin(SdSpiConfig(csPin, SHARED_SPI));
   }
References BUILTIN_SDCARD, FIFO_SDIO, and SHARED_SPI.
Referenced by SdBase< Vol >::begin().
begin() [3/4]
template<class Vol > bool SdBase< Vol >::begin (SdioConfig sdioConfig) inline
Initialize SD card and file system for SDIO mode.
Parameters
[in] sdioConfig SDIO configuration.
Returns
true for success or false for failure.
Definition at line 90 of file SdFat-beta.h.
{
     return cardBegin(sdioConfig) && Vol::begin(m_card);
   }
References SdBase< Vol >::cardBegin().
begin() [4/4]
template<class Vol > bool SdBase< Vol >::begin (SdSpiConfig spiConfig) inline
Initialize SD card and file system for SPI mode.
Parameters
[in] spiConfig SPI configuration.
Returns
true for success or false for failure.
Definition at line 81 of file SdFat-beta.h.
{
     return cardBegin(spiConfig) && Vol::begin(m_card);
   }
References SdBase< Vol >::cardBegin().
card()
template<class Vol > SdCard* SdBase< Vol >::card () inline
Returns
Pointer to SD card object.
Definition at line 95 of file SdFat-beta.h.
 {return m_card;}
cardBegin() [1/2]
template<class Vol > bool SdBase< Vol >::cardBegin (SdioConfig sdioConfig) inline
Initialize SD card in SDIO mode.
Parameters
[in] sdioConfig SDIO configuration.
Returns
true for success or false for failure.
Definition at line 112 of file SdFat-beta.h.
{
     m_card = m_cardFactory.newCard(sdioConfig);
     return m_card && !m_card->errorCode();
   }
References SdSpiCard::errorCode(), and SdCardFactory::newCard().
cardBegin() [2/2]
template<class Vol > bool SdBase< Vol >::cardBegin (SdSpiConfig spiConfig) inline
Initialize SD card in SPI mode.
Parameters
[in] spiConfig SPI configuration.
Returns
true for success or false for failure.
Definition at line 102 of file SdFat-beta.h.
{
     m_card = m_cardFactory.newCard(spiConfig);
     return m_card && !m_card->errorCode();
   }
References SdSpiCard::errorCode(), and SdCardFactory::newCard().
Referenced by SdBase< Vol >::begin().
errorHalt() [1/6]
template<class Vol > void SdBase< Vol >::errorHalt () inline
Print error info to Serial and halt.
Definition at line 305 of file SdFat-beta.h.
 {errorHalt(&Serial);}
References SdBase< Vol >::errorHalt().
Referenced by SdBase< Vol >::errorHalt().
errorHalt() [2/6]
template<class Vol > void SdBase< Vol >::errorHalt (const __FlashStringHelper * msg) inline
Print msg to Serial and halt.
Parameters
[in] msg Message to print.
Definition at line 300 of file SdFat-beta.h.
{
     errorHalt(&Serial, msg);
   }
References SdBase< Vol >::errorHalt().
errorHalt() [3/6]
template<class Vol > void SdBase< Vol >::errorHalt (const char * msg) inline
Print error info and halt.
Parameters
[in] msg Message to print.
Definition at line 311 of file SdFat-beta.h.
 {errorHalt(&Serial, msg);}
References SdBase< Vol >::errorHalt().
Referenced by SdBase< Vol >::errorHalt().
errorHalt() [4/6]
template<class Vol > void SdBase< Vol >::errorHalt (print_t * pr) inline
Print error info and halt.
Parameters
[in] pr Print destination.
Definition at line 121 of file SdFat-beta.h.
{
     if (sdErrorCode()) {
       pr->print(F("SdError: 0X"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0X"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
     SysCall::halt();
   }
References F, SysCall::halt(), HEX, SdBase< Vol >::sdErrorCode(), and SdBase< Vol >::sdErrorData().
errorHalt() [5/6]
template<class Vol > void SdBase< Vol >::errorHalt (print_t * pr, const __FlashStringHelper * msg) inline
Print msg and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 149 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorHalt(pr);
   }
References SdBase< Vol >::errorHalt(), and F.
errorHalt() [6/6]
template<class Vol > void SdBase< Vol >::errorHalt (print_t * pr, const char * msg) inline
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 138 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorHalt(pr);
   }
References SdBase< Vol >::errorHalt(), and F.
errorPrint() [1/5]
template<class Vol > void SdBase< Vol >::errorPrint (const __FlashStringHelper * msg) inline
Print msg, any SD error code.
Parameters
[in] msg Message to print.
Definition at line 325 of file SdFat-beta.h.
 {errorPrint(&Serial, msg);}
References SdBase< Vol >::errorPrint().
Referenced by SdBase< Vol >::errorPrint().
errorPrint() [2/5]
template<class Vol > void SdBase< Vol >::errorPrint (const char * msg) inline
Print msg, any SD error code.
Parameters
[in] msg Message to print.
Definition at line 320 of file SdFat-beta.h.
 {errorPrint(&Serial, msg);}
References SdBase< Vol >::errorPrint().
Referenced by SdBase< Vol >::errorPrint().
errorPrint() [3/5]
template<class Vol > void SdBase< Vol >::errorPrint (Print * pr, const __FlashStringHelper * msg) inline
Print msg, any SD error code.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 243 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorPrint(pr);
   }
References SdBase< Vol >::errorPrint(), and F.
errorPrint() [4/5]
template<class Vol > void SdBase< Vol >::errorPrint (print_t * pr) inline
Print SD errorCode and errorData.
Parameters
[in] pr Print destination.
Definition at line 216 of file SdFat-beta.h.
{
     if (sdErrorCode()) {
       pr->print(F("SdError: 0X"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0X"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
   }
References F, HEX, SdBase< Vol >::sdErrorCode(), and SdBase< Vol >::sdErrorData().
Referenced by SdBase< Vol >::errorPrint(), and SdBase< Vol >::initErrorPrint().
errorPrint() [5/5]
template<class Vol > void SdBase< Vol >::errorPrint (print_t * pr, char const * msg) inline
Print msg, any SD error code.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 232 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorPrint(pr);
   }
References SdBase< Vol >::errorPrint(), and F.
initErrorHalt() [1/6]
template<class Vol > void SdBase< Vol >::initErrorHalt () inline
Print error info and halt.
Definition at line 314 of file SdFat-beta.h.
 {initErrorHalt(&Serial);}
References SdBase< Vol >::initErrorHalt().
Referenced by SdBase< Vol >::initErrorHalt().
initErrorHalt() [2/6]
template<class Vol > void SdBase< Vol >::initErrorHalt (const __FlashStringHelper * msg) inline
Print error info and halt.
Parameters
[in] msg Message to print.
Definition at line 337 of file SdFat-beta.h.
{
     initErrorHalt(&Serial, msg);
   }
References SdBase< Vol >::initErrorHalt().
initErrorHalt() [3/6]
template<class Vol > void SdBase< Vol >::initErrorHalt (const char * msg) inline
Print error info and halt.
Parameters
[in] msg Message to print.
Definition at line 331 of file SdFat-beta.h.
 {initErrorHalt(&Serial, msg);}
References SdBase< Vol >::initErrorHalt().
Referenced by SdBase< Vol >::initErrorHalt().
initErrorHalt() [4/6]
template<class Vol > void SdBase< Vol >::initErrorHalt (Print * pr, const __FlashStringHelper * msg) inline
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 179 of file SdFat-beta.h.
{
     pr->println(msg);
     initErrorHalt(pr);
   }
References SdBase< Vol >::initErrorHalt().
initErrorHalt() [5/6]
template<class Vol > void SdBase< Vol >::initErrorHalt (print_t * pr) inline
Print error info and halt.
Parameters
[in] pr Print destination.
Definition at line 159 of file SdFat-beta.h.
{
     initErrorPrint(pr);
     SysCall::halt();
   }
References SysCall::halt(), and SdBase< Vol >::initErrorPrint().
initErrorHalt() [6/6]
template<class Vol > void SdBase< Vol >::initErrorHalt (print_t * pr, const char * msg) inline
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 169 of file SdFat-beta.h.
{
     pr->println(msg);
     initErrorHalt(pr);
   }
References SdBase< Vol >::initErrorHalt().
initErrorPrint() [1/2]
template<class Vol > void SdBase< Vol >::initErrorPrint () inline
Print error details after begin() fails.
Definition at line 292 of file SdFat-beta.h.
{
     initErrorPrint(&Serial);
   }
Referenced by SdBase< Vol >::initErrorHalt().
initErrorPrint() [2/2]
template<class Vol > void SdBase< Vol >::initErrorPrint (Print * pr) inline
Print error details after begin() fails.
Parameters
[in] pr Print destination.
Definition at line 188 of file SdFat-beta.h.
{
     pr->println(F("begin() failed"));
     if (sdErrorCode()) {
       pr->println(F("Do not reformat the SD."));
       if (sdErrorCode() == SD_CARD_ERROR_CMD0) {
         pr->println(F("No card, wrong chip select pin, or wiring error?"));
       }
     }
     errorPrint(pr);
   }
References SdBase< Vol >::errorPrint(), F, and SdBase< Vol >::sdErrorCode().
printFatType()
template<class Vol > void SdBase< Vol >::printFatType (print_t * pr) inline
Print volume FAT/exFAT type.
Parameters
[in] pr Print destination.
Definition at line 203 of file SdFat-beta.h.
{
     if (Vol::fatType() == FAT_TYPE_EXFAT) {
       pr->print(F("exFAT"));
     } else {
       pr->print(F("FAT"));
       pr->print(Vol::fatType());
     }
   }
References F, and FAT_TYPE_EXFAT.
printSdError()
template<class Vol > void SdBase< Vol >::printSdError (print_t * pr) inline
Print error info and return.
Parameters
[in] pr Print destination.
Definition at line 253 of file SdFat-beta.h.
{
     if (sdErrorCode()) {
       if (sdErrorCode() == SD_CARD_ERROR_CMD0) {
         pr->println(F("No card, wrong chip select pin, or wiring error?"));
       }
       pr->print(F("SD error: "));
       printSdErrorSymbol(pr, sdErrorCode());
       pr->print(F(" = 0x"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0x"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::cwv()) {
       pr->println(F("Check SD format."));
     }
   }
References F, HEX, printSdErrorSymbol(), SdBase< Vol >::sdErrorCode(), and SdBase< Vol >::sdErrorData().
sdErrorCode()
template<class Vol > uint8_t SdBase< Vol >::sdErrorCode () inline
Returns
SD card error code.
Definition at line 270 of file SdFat-beta.h.
{
     if (m_card) {
       return m_card->errorCode();
     }
     return SD_CARD_ERROR_INVALID_CARD_CONFIG;
   }
References SdSpiCard::errorCode().
Referenced by SdBase< Vol >::errorHalt(), SdBase< Vol >::errorPrint(), SdBase< Vol >::initErrorPrint(), and SdBase< Vol >::printSdError().
sdErrorData()
template<class Vol > uint8_t SdBase< Vol >::sdErrorData () inline
Returns
SD card error data.
Definition at line 278 of file SdFat-beta.h.
 {return m_card ? m_card->errorData() : 0;}
References SdSpiCard::errorData().
Referenced by SdBase< Vol >::errorHalt(), SdBase< Vol >::errorPrint(), and SdBase< Vol >::printSdError().
vol()
template<class Vol > Vol* SdBase< Vol >::vol () inline
Returns
pointer to base volume
Definition at line 281 of file SdFat-beta.h.
 {return reinterpret_cast<Vol*>(this);}
volumeBegin()
template<class Vol > bool SdBase< Vol >::volumeBegin () inline
Initialize file system after call to cardBegin.
Returns
true for success or false for failure.
Definition at line 287 of file SdFat-beta.h.
                      {
      return Vol::begin(m_card);
   }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/SdFat-beta.h