ERIS CORE: wren_opt_random.c File Reference
wren_opt_random.c File Reference
#include "wren_opt_random.h"
#include <string.h>
#include <time.h>
#include "wren.h"
#include "wren_vm.h"
#include "wren_opt_random.wren.inc"
Functions
static uint32_t advanceState (Well512 *well)
static void randomAllocate (WrenVM *vm)
static void randomFloat (WrenVM *vm)
static void randomInt0 (WrenVM *vm)
static void randomSeed0 (WrenVM *vm)
static void randomSeed1 (WrenVM *vm)
static void randomSeed16 (WrenVM *vm)
WrenForeignClassMethods wrenRandomBindForeignClass (WrenVM *vm, const char *module, const char *className)
WrenForeignMethodFn wrenRandomBindForeignMethod (WrenVM *vm, const char *className, bool isStatic, const char *signature)
const char * wrenRandomSource ()
Function Documentation
advanceState()
static uint32_t advanceState (Well512 * well) static
Definition at line 23 of file wren_opt_random.c.
 {
   uint32_t a, b, c, d;
   a = well->state[well->index];
   c = well->state[(well->index + 13) & 15];
   b =  a ^ c ^ (a << 16) ^ (c << 15);
   c = well->state[(well->index + 9) & 15];
   c ^= (c >> 11);
   a = well->state[well->index] = b ^ c;
   d = a ^ ((a << 5) & 0xda442d24U);
   well->index = (well->index + 15) & 15;
   a = well->state[well->index];
   well->state[well->index] = a ^ b ^ d ^ (a << 2) ^ (b << 18) ^ (c << 28);
   return well->state[well->index];
 }
Referenced by randomFloat(), and randomInt0().
randomAllocate()
static void randomAllocate (WrenVM * vm) static
Definition at line 40 of file wren_opt_random.c.
 {
   Well512* well = (Well512*)wrenSetSlotNewForeign(vm, 0, 0, sizeof(Well512));
   well->index = 0;
 }
References wrenSetSlotNewForeign().
Referenced by wrenRandomBindForeignClass(), and wrenRandomBindForeignMethod().
randomFloat()
static void randomFloat (WrenVM * vm) static
Definition at line 78 of file wren_opt_random.c.
 {
   Well512* well = (Well512*)wrenGetSlotForeign(vm, 0);
   // A double has 53 bits of precision in its mantissa, and we'd like to take
   // full advantage of that, so we need 53 bits of random source data.
   // First, start with 32 random bits, shifted to the left 21 bits.
   double result = (double)advanceState(well) * (1 << 21);
   // Then add another 21 random bits.
   result += (double)(advanceState(well) & ((1 << 21) - 1));
   // Now we have a number from 0 - (2^53). Divide be the range to get a double
   // from 0 to 1.0 (half-inclusive).
   result /= 9007199254740992.0;
   wrenSetSlotDouble(vm, 0, result);
 }
References advanceState(), wrenGetSlotForeign(), and wrenSetSlotDouble().
Referenced by wrenRandomBindForeignMethod().
randomInt0()
static void randomInt0 (WrenVM * vm) static
Definition at line 98 of file wren_opt_random.c.
 {
   Well512* well = (Well512*)wrenGetSlotForeign(vm, 0);
   wrenSetSlotDouble(vm, 0, (double)advanceState(well));
 }
References advanceState(), wrenGetSlotForeign(), and wrenSetSlotDouble().
Referenced by wrenRandomBindForeignMethod().
randomSeed0()
static void randomSeed0 (WrenVM * vm) static
Definition at line 46 of file wren_opt_random.c.
 {
   Well512* well = (Well512*)wrenGetSlotForeign(vm, 0);
   srand((uint32_t)time(NULL));
   for (int i = 0; i < 16; i++)
   {
     well->state[i] = rand();
   }
 }
References NULL, and wrenGetSlotForeign().
Referenced by wrenRandomBindForeignMethod().
randomSeed1()
static void randomSeed1 (WrenVM * vm) static
Definition at line 57 of file wren_opt_random.c.
 {
   Well512* well = (Well512*)wrenGetSlotForeign(vm, 0);
   srand((uint32_t)wrenGetSlotDouble(vm, 1));
   for (int i = 0; i < 16; i++)
   {
     well->state[i] = rand();
   }
 }
References wrenGetSlotDouble(), and wrenGetSlotForeign().
Referenced by wrenRandomBindForeignMethod().
randomSeed16()
static void randomSeed16 (WrenVM * vm) static
Definition at line 68 of file wren_opt_random.c.
 {
   Well512* well = (Well512*)wrenGetSlotForeign(vm, 0);
   for (int i = 0; i < 16; i++)
   {
     well->state[i] = (uint32_t)wrenGetSlotDouble(vm, i + 1);
   }
 }
References wrenGetSlotDouble(), and wrenGetSlotForeign().
Referenced by wrenRandomBindForeignMethod().
wrenRandomBindForeignClass()
WrenForeignClassMethods wrenRandomBindForeignClass (WrenVM * vm, const char * module, const char * className)
Definition at line 110 of file wren_opt_random.c.
 {
   ASSERT(strcmp(className, "Random") == 0, "Should be in Random class.");
   WrenForeignClassMethods methods;
   methods.allocate = randomAllocate;
   methods.finalize = NULL;
   return methods;
 }
References WrenForeignClassMethods::allocate, ASSERT, WrenForeignClassMethods::finalize, NULL, and randomAllocate().
Referenced by bindForeignClass().
wrenRandomBindForeignMethod()
WrenForeignMethodFn wrenRandomBindForeignMethod (WrenVM * vm, const char * className, bool isStatic, const char * signature)
Definition at line 121 of file wren_opt_random.c.
 {
   ASSERT(strcmp(className, "Random") == 0, "Should be in Random class.");
   if (strcmp(signature, "<allocate>") == 0) return randomAllocate;
   if (strcmp(signature, "seed_()") == 0) return randomSeed0;
   if (strcmp(signature, "seed_(_)") == 0) return randomSeed1;
   if (strcmp(signature, "seed_(_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_)") == 0)
   {
     return randomSeed16;
   }
   if (strcmp(signature, "float()") == 0) return randomFloat;
   if (strcmp(signature, "int()") == 0) return randomInt0;
   ASSERT(false, "Unknown method.");
   return NULL;
 }
References ASSERT, NULL, randomAllocate(), randomFloat(), randomInt0(), randomSeed0(), randomSeed1(), and randomSeed16().
Referenced by findForeignMethod().
wrenRandomSource()
const char* wrenRandomSource ()
Definition at line 105 of file wren_opt_random.c.
 {
   return randomModuleSource;
 }
Referenced by importModule().