ERIS CORE: FatFile Class Reference
FatFile Class Reference
Basic file class.
#include <FatFile.h>
Public Member Functions
FatFile ()
FatFile (const char *path, oflag_t oflag)
const char * __attribute__ ((error("use getName(name, size)"))) name()
size_t __attribute__ ((error("use getSFN(name, size)"))) getSFN(char *name)
int available () const
uint32_t available32 () const
void clearError ()
void clearWriteError ()
bool close ()
bool contiguousRange (uint32_t *bgnSector, uint32_t *endSector)
bool createContiguous (const char *path, uint32_t size)
bool createContiguous (FatFile *dirFile, const char *path, uint32_t size)
uint32_t curCluster () const
uint32_t curPosition () const
bool dirEntry (DirFat_t *dir)
uint16_t dirIndex () const
uint32_t dirSize ()
void dmpFile (print_t *pr, uint32_t pos, size_t n)
bool exists (const char *path)
void fgetpos (fspos_t *pos) const
int fgets (char *str, int num, char *delim=nullptr)
uint32_t fileSize () const
uint32_t firstBlock () const
uint32_t firstSector () const
void flush ()
void fsetpos (const fspos_t *pos)
bool getAccessDate (uint16_t *pdate)
bool getAccessDateTime (uint16_t *pdate, uint16_t *ptime)
bool getCreateDateTime (uint16_t *pdate, uint16_t *ptime)
uint8_t getError () const
bool getModifyDateTime (uint16_t *pdate, uint16_t *ptime)
size_t getName (char *name, size_t size)
size_t getName7 (char *name, size_t size)
size_t getName8 (char *name, size_t size)
size_t getSFN (char *name, size_t size)
bool getWriteError () const
bool isBusy ()
bool isDir () const
bool isFile () const
bool isHidden () const
bool isLFN () const
bool isOpen () const
bool isReadable () const
bool isReadOnly () const
bool isRoot () const
bool isRoot32 () const
bool isRootFixed () const
bool isSubDir () const
bool isSystem () const
bool isWritable () const
bool ls (print_t *pr, uint8_t flags=0, uint8_t indent=0)
bool mkdir (FatFile *dir, const char *path, bool pFlag=true)
bool open (const char *path, oflag_t oflag=O_RDONLY)
bool open (FatFile *dirFile, const char *path, oflag_t oflag)
bool open (FatFile *dirFile, uint16_t index, oflag_t oflag)
bool open (FatVolume *vol, const char *path, oflag_t oflag)
bool openExistingSFN (const char *path)
bool openNext (FatFile *dirFile, oflag_t oflag=O_RDONLY)
bool openRoot (FatVolume *vol)
operator bool () const
int peek ()
bool preAllocate (uint32_t length)
size_t printAccessDate (print_t *pr)
size_t printAccessDateTime (print_t *pr)
size_t printCreateDateTime (print_t *pr)
size_t printField (double value, char term, uint8_t prec=2)
size_t printField (float value, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type value, char term)
size_t printFileSize (print_t *pr)
size_t printModifyDateTime (print_t *pr)
size_t printName (print_t *pr)
size_t printName7 (print_t *pr)
size_t printName8 (print_t *pr)
size_t printSFN (print_t *pr)
int read ()
int read (void *buf, size_t count)
int8_t readDir (DirFat_t *dir)
bool remove ()
bool remove (const char *path)
bool rename (const char *newPath)
bool rename (FatFile *dirFile, const char *newPath)
void rewind ()
bool rmdir ()
bool rmRfStar ()
bool seekCur (int32_t offset)
bool seekEnd (int32_t offset=0)
bool seekSet (uint32_t pos)
bool sync ()
bool timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
bool truncate ()
bool truncate (uint32_t length)
size_t write (const char *str)
size_t write (const void *buf, size_t count)
size_t write (uint8_t b)
Static Public Member Functions
static void printFatDate (print_t *pr, uint16_t fatDate)
static void printFatTime (print_t *pr, uint16_t fatTime)
Private Member Functions
bool addCluster ()
bool addDirCluster ()
DirFat_t * cacheDir (uint16_t index)
DirFat_t * cacheDirEntry (uint8_t action)
bool cmpName (uint16_t index, FatLfn_t *fname, uint8_t lfnOrd)
bool createLFN (uint16_t index, FatLfn_t *fname, uint8_t lfnOrd)
uint16_t getLfnChar (DirLfn_t *ldir, uint8_t i)
uint8_t lfnChecksum (uint8_t *name)
bool makeUniqueSfn (FatLfn_t *fname)
bool mkdir (FatFile *parent, FatName_t *fname)
bool open (FatFile *dirFile, FatLfn_t *fname, oflag_t oflag)
bool open (FatFile *dirFile, FatSfn_t *fname, oflag_t oflag)
bool openCachedEntry (FatFile *dirFile, uint16_t cacheIndex, oflag_t oflag, uint8_t lfnOrd)
bool openCluster (FatFile *file)
bool openSFN (FatSfn_t *fname)
bool parsePathName (const char *str, FatLfn_t *fname, const char **ptr)
bool parsePathName (const char *str, FatSfn_t *fname, const char **ptr)
DirFat_t * readDirCache (bool skipReadOk=false)
Static Private Member Functions
static bool makeSFN (FatLfn_t *fname)
Private Attributes
uint8_t m_attributes = FILE_ATTR_CLOSED
uint32_t m_curCluster
uint32_t m_curPosition
uint32_t m_dirCluster
uint16_t m_dirIndex
uint32_t m_dirSector
uint8_t m_error = 0
uint32_t m_fileSize
uint32_t m_firstCluster
uint8_t m_flags = 0
uint8_t m_lfnOrd
FatVolume * m_vol
Static Private Attributes
static const uint8_t FILE_ATTR_CLOSED = 0
static const uint8_t FILE_ATTR_COPY
static const uint8_t FILE_ATTR_DIR = FILE_ATTR_SUBDIR | FILE_ATTR_ROOT
static const uint8_t FILE_ATTR_FILE = 0X08
static const uint8_t FILE_ATTR_HIDDEN = FAT_ATTRIB_HIDDEN
static const uint8_t FILE_ATTR_READ_ONLY = FAT_ATTRIB_READ_ONLY
static const uint8_t FILE_ATTR_ROOT
static const uint8_t FILE_ATTR_ROOT32 = 0X40
static const uint8_t FILE_ATTR_ROOT_FIXED = 0X20
static const uint8_t FILE_ATTR_SUBDIR = FAT_ATTRIB_DIRECTORY
static const uint8_t FILE_ATTR_SYSTEM = FAT_ATTRIB_SYSTEM
static const uint8_t FILE_FLAG_APPEND = 0X08
static const uint8_t FILE_FLAG_CONTIGUOUS = 0X40
static const uint8_t FILE_FLAG_DIR_DIRTY = 0X80
static const uint8_t FILE_FLAG_PREALLOCATE = 0X20
static const uint8_t FILE_FLAG_READ = 0X01
static const uint8_t FILE_FLAG_WRITE = 0X02
static const uint8_t READ_ERROR = 0X2
static const uint8_t WRITE_ERROR = 0X1
Friends
class FatVolume
Detailed Description
Basic file class.
Definition at line 132 of file FatFile.h.
Constructor & Destructor Documentation
FatFile() [1/2]
FatFile::FatFile () inline
Create an instance.
Definition at line 135 of file FatFile.h.
 {}
FatFile() [2/2]
FatFile::FatFile (const char * path, oflag_t oflag) inline
Create a file object and open it in the current working directory.
Parameters
[in] path A path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of open flags. see FatFile::open(FatFile*, const char*, uint8_t).
Definition at line 143 of file FatFile.h.
{
     open(path, oflag);
   }
References open().
Member Function Documentation
__attribute__() [1/2]
const char* FatFile::__attribute__ ((error("use getName(name, size)")))
No longer implemented due to Long File Names.
Use getName(char* name, size_t size).
Returns
a pointer to replacement suggestion.
__attribute__() [2/2]
size_t FatFile::__attribute__ ((error("use getSFN(name, size)")))
addCluster()
bool FatFile::addCluster () private
Definition at line 30 of file FatFile.cpp.
{
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
   uint32_t cc = m_curCluster;
   if (!m_vol->allocateCluster(m_curCluster, &m_curCluster)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (cc == 0) {
     m_flags |= FILE_FLAG_CONTIGUOUS;
   } else if (m_curCluster != (cc + 1)) {
     m_flags &= ~FILE_FLAG_CONTIGUOUS;
   }
   m_flags |= FILE_FLAG_DIR_DIRTY;
   return true;
  fail:
   return false;
 #else  // USE_FAT_FILE_FLAG_CONTIGUOUS
   m_flags |= FILE_FLAG_DIR_DIRTY;
   return m_vol->allocateCluster(m_curCluster, &m_curCluster);
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
 }
References FatPartition::allocateCluster(), DBG_FAIL_MACRO, FILE_FLAG_CONTIGUOUS, FILE_FLAG_DIR_DIRTY, m_curCluster, m_flags, and m_vol.
Referenced by addDirCluster(), and write().
addDirCluster()
bool FatFile::addDirCluster () private
Definition at line 55 of file FatFile.cpp.
{
   uint32_t sector;
   uint8_t* pc;
   if (isRootFixed()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // max folder size
   if (m_curPosition >= 512UL*4095) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!addCluster()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   sector = m_vol->clusterStartSector(m_curCluster);
   for (uint8_t i = 0; i < m_vol->sectorsPerCluster(); i++) {
     pc = m_vol->dataCachePrepare(sector + i, FsCache::CACHE_RESERVE_FOR_WRITE);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     memset(pc, 0, m_vol->bytesPerSector());
   }
   // Set position to EOF to avoid inconsistent curCluster/curPosition.
   m_curPosition += m_vol->bytesPerCluster();
   return true;
  fail:
   return false;
 }
References addCluster(), FatPartition::bytesPerCluster(), FatPartition::bytesPerSector(), FsCache::CACHE_RESERVE_FOR_WRITE, FatPartition::clusterStartSector(), FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, isRootFixed(), m_curCluster, m_curPosition, m_vol, and FatPartition::sectorsPerCluster().
Referenced by mkdir(), and open().
available()
int FatFile::available (void) const inline
Returns
The number of bytes available from the current position to EOF for normal files. INT_MAX is returned for very large files.
available32() is recomended for very large files.
Zero is returned for directory files.
Definition at line 167 of file FatFile.h.
{
     uint32_t n = available32();
     return n > INT_MAX ? INT_MAX : n;
   }
References available32().
Referenced by FsBaseFile::available().
available32()
uint32_t FatFile::available32 () const inline
Returns
The number of bytes available from the current position to EOF for normal files. Zero is returned for directory files.
Definition at line 174 of file FatFile.h.
{
     return isFile() ? fileSize() - curPosition() : 0;
   }
References curPosition(), fileSize(), and isFile().
Referenced by available(), and FsBaseFile::available64().
cacheDir()
DirFat_t* FatFile::cacheDir (uint16_t index) inline private
Definition at line 996 of file FatFile.h.
{
     return seekSet(32UL*index) ? readDirCache() : nullptr;
   }
References readDirCache(), and seekSet().
Referenced by getName7(), getName8(), open(), printName7(), and printName8().
cacheDirEntry()
DirFat_t * FatFile::cacheDirEntry (uint8_t action) private
Definition at line 91 of file FatFile.cpp.
{
   uint8_t* pc = m_vol->dataCachePrepare(m_dirSector, action);
   DirFat_t* dir = reinterpret_cast<DirFat_t*>(pc);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return dir + (m_dirIndex & 0XF);
  fail:
   return nullptr;
 }
References FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, m_dirIndex, m_dirSector, and m_vol.
Referenced by dirEntry(), getSFN(), mkdir(), remove(), rename(), sync(), and timestamp().
clearError()
void FatFile::clearError () inline
Clear all error bits.
Definition at line 178 of file FatFile.h.
                     {
     m_error = 0;
   }
References m_error.
clearWriteError()
void FatFile::clearWriteError () inline
Set writeError to zero
Definition at line 182 of file FatFile.h.
{
     m_error &= ~WRITE_ERROR;
   }
References m_error, and WRITE_ERROR.
Referenced by FsBaseFile::clearWriteError().
close()
bool FatFile::close ()
Close a file and force cached data and directory information to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 104 of file FatFile.cpp.
                     {
   bool rtn = sync();
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   return rtn;
 }
References FILE_ATTR_CLOSED, m_attributes, m_flags, and sync().
Referenced by FatVolume::chdir(), FsBaseFile::close(), createContiguous(), ls(), mkdir(), and open().
cmpName()
bool FatFile::cmpName (uint16_t index, FatLfn_t * fname, uint8_t lfnOrd) private
contiguousRange()
bool FatFile::contiguousRange (uint32_t * bgnSector, uint32_t * endSector)
Check for contiguous file and return its raw sector range.
Parameters
[out] bgnSector the first sector address for the file.
[out] endSector the last sector address for the file.
Set the contiguous flag if the file is contiguous. The parameters may be nullptr to only set the flag.
Returns
true for success or false for failure.
Definition at line 111 of file FatFile.cpp.
{
   // error if no clusters
   if (!isFile() || m_firstCluster == 0) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   for (uint32_t c = m_firstCluster; ; c++) {
     uint32_t next;
     int8_t fg = m_vol->fatGet(c, &next);
     if (fg < 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // check for contiguous
     if (fg == 0 || next != (c + 1)) {
       // error if not end of chain
       if (fg) {
         DBG_FAIL_MACRO;
         goto fail;
       }
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
       m_flags |= FILE_FLAG_CONTIGUOUS;
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
       if (bgnSector) {
         *bgnSector = m_vol->clusterStartSector(m_firstCluster);
       }
       if (endSector) {
         *endSector = m_vol->clusterStartSector(c)
                      + m_vol->sectorsPerCluster() - 1;
       }
       return true;
     }
   }
  fail:
   return false;
 }
References FatPartition::clusterStartSector(), DBG_FAIL_MACRO, FatPartition::fatGet(), FILE_FLAG_CONTIGUOUS, isFile(), m_firstCluster, m_flags, m_vol, and FatPartition::sectorsPerCluster().
Referenced by FsBaseFile::contiguousRange().
createContiguous() [1/2]
bool FatFile::createContiguous (const char * path, uint32_t size)
Create and open a new contiguous file of a specified size.
Parameters
[in] path A path with a valid file name.
[in] size The desired file size.
Returns
true for success or false for failure.
Definition at line 149 of file FatFile.cpp.
{
   if (!open(FatVolume::cwv(), path, O_CREAT | O_EXCL | O_RDWR)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (preAllocate(size)) {
     return true;
   }
   close();
  fail:
   return false;
 }
References close(), FatVolume::cwv(), DBG_FAIL_MACRO, O_CREAT, O_EXCL, O_RDWR, open(), and preAllocate().
createContiguous() [2/2]
bool FatFile::createContiguous (FatFile * dirFile, const char * path, uint32_t size)
Create and open a new contiguous file of a specified size.
Parameters
[in] dirFile The directory where the file will be created.
[in] path A path with a valid file name.
[in] size The desired file size.
Returns
true for success or false for failure.
Definition at line 162 of file FatFile.cpp.
{
   if (!open(dirFile, path, O_CREAT | O_EXCL | O_RDWR)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (preAllocate(size)) {
     return true;
   }
   close();
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, O_CREAT, O_EXCL, O_RDWR, open(), and preAllocate().
createLFN()
bool FatFile::createLFN (uint16_t index, FatLfn_t * fname, uint8_t lfnOrd) private
curCluster()
uint32_t FatFile::curCluster () const inline
Returns
The current cluster number for a file or directory.
Definition at line 220 of file FatFile.h.
 {return m_curCluster;}
References m_curCluster.
Referenced by peek().
curPosition()
uint32_t FatFile::curPosition () const inline
Returns
The current position for a file or directory.
Definition at line 223 of file FatFile.h.
 {return m_curPosition;}
References m_curPosition.
Referenced by available32(), FsBaseFile::curPosition(), openNext(), and peek().
dirEntry()
bool FatFile::dirEntry (DirFat_t * dir)
Return a file's directory entry.
Parameters
[out] dir Location for return of the file's directory entry.
Returns
true for success or false for failure.
Definition at line 176 of file FatFile.cpp.
{
   DirFat_t* dir;
   // Make sure fields on device are correct.
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // read entry
   dir = cacheDirEntry(FsCache::CACHE_FOR_READ);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // copy to caller's struct
   memcpy(dst, dir, sizeof(DirFat_t));
   return true;
  fail:
   return false;
 }
References FsCache::CACHE_FOR_READ, cacheDirEntry(), DBG_FAIL_MACRO, and sync().
Referenced by getAccessDate(), getCreateDateTime(), and getModifyDateTime().
dirIndex()
uint16_t FatFile::dirIndex () const inline
Returns
Directory entry index.
Definition at line 232 of file FatFile.h.
 {return m_dirIndex;}
References m_dirIndex.
Referenced by FsBaseFile::dirIndex(), open(), openCachedEntry(), and openSFN().
dirSize()
uint32_t FatFile::dirSize ()
Returns
The number of bytes allocated to a directory or zero if an error occurs.
Definition at line 197 of file FatFile.cpp.
{
   int8_t fg;
   if (!isDir()) {
     return 0;
   }
   if (isRootFixed()) {
     return FS_DIR_SIZE*m_vol->rootDirEntryCount();
   }
   uint16_t n = 0;
   uint32_t c = isRoot32() ? m_vol->rootDirStart() : m_firstCluster;
   do {
     fg = m_vol->fatGet(c, &c);
     if (fg < 0 || n > 4095) {
       return 0;
     }
     n += m_vol->sectorsPerCluster();
   } while (fg);
   return 512UL*n;
 }
References FatPartition::fatGet(), FS_DIR_SIZE, isDir(), isRoot32(), isRootFixed(), m_firstCluster, m_vol, FatPartition::rootDirEntryCount(), FatPartition::rootDirStart(), and FatPartition::sectorsPerCluster().
dmpFile()
void FatFile::dmpFile (print_t * pr, uint32_t pos, size_t n)
Dump file in Hex
Parameters
[in] pr Print stream for list.
[in] pos Start position in file.
[in] n number of locations to dump.
Definition at line 146 of file FatDbg.cpp.
{
   char text[17];
   text[16] = 0;
   if (n >= 0XFFF0) {
     n = 0XFFF0;
   }
   if (!seekSet(pos)) {
     return;
   }
   for (size_t i = 0; i <= n; i++) {
     if ((i & 15) == 0) {
       if (i) {
         pr->write(' ');
         pr->write(text);
         if (i == n) {
           break;
         }
       }
       pr->write('\r');
       pr->write('\n');
       if (i >= n) {
         break;
       }
       printHex(pr, 4, i);
       pr->write(' ');
     }
     int16_t h = read();
     if (h < 0) {
       break;
     }
     pr->write(' ');
     printHex(pr, 2, h);
     text[i&15] = ' ' <= h && h < 0X7F ? h : '.';
   }
   pr->write('\r');
   pr->write('\n');
 }
References printHex(), read(), seekSet(), and PrintBasic::write().
exists()
bool FatFile::exists (const char * path) inline
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
The calling instance must be an open directory file.
dirFile.exists("TOFIND.TXT") searches for "TOFIND.TXT" in the directory dirFile.
Returns
True if the file exists.
Definition at line 254 of file FatFile.h.
{
     FatFile file;
     return file.open(this, path, O_RDONLY);
   }
References O_RDONLY, and open().
Referenced by FsBaseFile::exists().
fgetpos()
void FatFile::fgetpos (fspos_t * pos) const
get position for streams
Parameters
[out] pos struct to receive position
Definition at line 245 of file FatFile.cpp.
{
   pos->position = m_curPosition;
   pos->cluster = m_curCluster;
 }
References fspos_t::cluster, m_curCluster, m_curPosition, and fspos_t::position.
Referenced by FsBaseFile::fgetpos().
fgets()
int FatFile::fgets (char * str, int num, char * delim = nullptr)
Get a string from a file.
fgets() reads bytes from a file into the array pointed to by str, until num - 1 bytes are read, or a delimiter is read and transferred to str, or end-of-file is encountered. The string is then terminated with a null byte.
fgets() deletes CR, '\r', from the string. This insures only a '\n' terminates the string for Windows text files which use CRLF for newline.
Parameters
[out] str Pointer to the array where the string is stored.
[in] num Maximum number of characters to be read (including the final null byte). Usually the length of the array str is used.
[in] delim Optional set of delimiters. The default is "\n".
Returns
For success fgets() returns the length of the string in str. If no data is read, fgets() returns zero for EOF or -1 if an error occurred.
Definition at line 217 of file FatFile.cpp.
{
   char ch;
   int n = 0;
   int r = -1;
   while ((n + 1) < num && (r = read(&ch, 1)) == 1) {
     // delete CR
     if (ch == '\r') {
       continue;
     }
     str[n++] = ch;
     if (!delim) {
       if (ch == '\n') {
         break;
       }
     } else {
       if (strchr(delim, ch)) {
         break;
       }
     }
   }
   if (r < 0) {
     // read error
     return -1;
   }
   str[n] = '\0';
   return n;
 }
References read().
Referenced by FsBaseFile::fgets().
fileSize()
uint32_t FatFile::fileSize () const inline
Returns
The total number of bytes in a file.
Definition at line 285 of file FatFile.h.
 {return m_fileSize;}
References m_fileSize.
Referenced by available32(), FsBaseFile::fileSize(), and printFileSize().
firstBlock()
uint32_t FatFile::firstBlock () const inline
Returns
first sector of file or zero for empty file.
Definition at line 287 of file FatFile.h.
 {return firstSector();}
References firstSector().
firstSector()
uint32_t FatFile::firstSector () const
Returns
Address of first sector or zero for empty file.
Definition at line 250 of file FatFile.cpp.
{
   return m_firstCluster ? m_vol->clusterStartSector(m_firstCluster) : 0;
 }
References FatPartition::clusterStartSector(), m_firstCluster, and m_vol.
Referenced by firstBlock(), and FsBaseFile::firstSector().
flush()
void FatFile::flush () inline
Arduino name for sync()
Definition at line 291 of file FatFile.h.
 {sync();}
References sync().
fsetpos()
void FatFile::fsetpos (const fspos_t * pos)
set position for streams
Parameters
[in] pos struct with value for new position
Definition at line 254 of file FatFile.cpp.
{
   m_curPosition = pos->position;
   m_curCluster = pos->cluster;
 }
References fspos_t::cluster, m_curCluster, m_curPosition, and fspos_t::position.
Referenced by FsBaseFile::fsetpos().
getAccessDate()
bool FatFile::getAccessDate (uint16_t * pdate)
Get a file's access date.
Parameters
[out] pdate Packed date for directory entry.
Returns
true for success or false for failure.
Definition at line 259 of file FatFile.cpp.
{
   DirFat_t dir;
   if (!dirEntry(&dir)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   *pdate = getLe16(dir.accessDate);
   return true;
  fail:
   return false;
 }
References DirFat_t::accessDate, DBG_FAIL_MACRO, dirEntry(), and getLe16().
Referenced by getAccessDateTime(), and printAccessDate().
getAccessDateTime()
bool FatFile::getAccessDateTime (uint16_t * pdate, uint16_t * ptime) inline
Get a file's access date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime return zero since FAT has no time.
This function is for comparability in FsFile.
Returns
true for success or false for failure.
Definition at line 312 of file FatFile.h.
{
     if (!getAccessDate(pdate)) {
       return false;
     }
     *ptime = 0;
     return true;
   }
References getAccessDate().
Referenced by FsBaseFile::getAccessDateTime().
getCreateDateTime()
bool FatFile::getCreateDateTime (uint16_t * pdate, uint16_t * ptime)
Get a file's create date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 272 of file FatFile.cpp.
{
   DirFat_t dir;
   if (!dirEntry(&dir)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   *pdate = getLe16(dir.createDate);
   *ptime = getLe16(dir.createTime);
   return true;
  fail:
   return false;
 }
References DirFat_t::createDate, DirFat_t::createTime, DBG_FAIL_MACRO, dirEntry(), and getLe16().
Referenced by FsBaseFile::getCreateDateTime(), and printCreateDateTime().
getError()
uint8_t FatFile::getError () const inline
Returns
All error bits.
Definition at line 328 of file FatFile.h.
 {return m_error;}
References m_error.
Referenced by FsBaseFile::getError(), ls(), open(), openNext(), rmdir(), and rmRfStar().
getLfnChar()
uint16_t FatFile::getLfnChar (DirLfn_t * ldir, uint8_t i) private
Definition at line 30 of file FatName.cpp.
{
   if (i < 5) {
     return getLe16(ldir->unicode1 + 2*i);
   } else if (i < 11) {
     return getLe16(ldir->unicode2 + 2*i - 10);
   } else if (i < 13) {
     return getLe16(ldir->unicode3 + 2*i - 22);
   }
   DBG_HALT_IF(i >= 13);
   return 0;
 }
References DBG_HALT_IF, getLe16(), DirLfn_t::unicode1, DirLfn_t::unicode2, and DirLfn_t::unicode3.
Referenced by getName7(), getName8(), printName7(), and printName8().
getModifyDateTime()
bool FatFile::getModifyDateTime (uint16_t * pdate, uint16_t * ptime)
Get a file's modify date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 286 of file FatFile.cpp.
{
   DirFat_t dir;
   if (!dirEntry(&dir)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   *pdate = getLe16(dir.modifyDate);
   *ptime = getLe16(dir.modifyTime);
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, dirEntry(), getLe16(), DirFat_t::modifyDate, and DirFat_t::modifyTime.
Referenced by FsBaseFile::getModifyDateTime(), and printModifyDateTime().
getName()
size_t FatFile::getName (char * name, size_t size)
Get a file's name followed by a zero byte.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in bytes. The array must be at least 13 bytes long. The file's name will be truncated if the file's name is too long.
Returns
length for success or zero for failure.
Definition at line 42 of file FatName.cpp.
{
 #if !USE_LONG_FILE_NAMES
   return getSFN(name, size);
 #elif USE_UTF8_LONG_NAMES
   return getName8(name, size);
 #else
   return getName7(name, size);
 #endif  // !USE_LONG_FILE_NAMES
 }
References getName7(), getName8(), and getSFN().
Referenced by FsBaseFile::getName().
getName7()
size_t FatFile::getName7 (char * name, size_t size)
Get a file's ASCII name followed by a zero.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in characters.
Returns
the name length.
Definition at line 52 of file FatName.cpp.
{
   FatFile dir;
   DirLfn_t* ldir;
   char* ptr = name;
   char* end = ptr + size;
   if (!isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!isLFN()) {
     return getSFN(name, size);
   }
   if (!dir.openCluster(this)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   for (uint8_t order = 1; order <= m_lfnOrd; order++) {
     ldir = reinterpret_cast<DirLfn_t*>(dir.cacheDir(m_dirIndex - order));
     if (!ldir) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (ldir->attributes != FAT_ATTRIB_LONG_NAME ||
         order != (ldir->order & 0X1F)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (uint8_t i = 0; i < 13; i++) {
       uint16_t c = getLfnChar(ldir, i);
       if (c == 0 || (ptr + 1) == end) {
         goto done;
       }
       *ptr++ = c >= 0X7F ? '?' : c;
     }
   }
  done:
   *ptr = '\0';
   return ptr - name;
  fail:
   name[0] = '\0';
   return 0;
 }
References DirLfn_t::attributes, cacheDir(), DBG_FAIL_MACRO, FAT_ATTRIB_LONG_NAME, getLfnChar(), getSFN(), isLFN(), isOpen(), m_dirIndex, m_lfnOrd, openCluster(), and DirLfn_t::order.
Referenced by getName().
getName8()
size_t FatFile::getName8 (char * name, size_t size)
Get a file's UTF-8 name followed by a zero.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in characters.
Returns
the name length.
Definition at line 96 of file FatName.cpp.
{
   char* end = name + size;
   char* str = name;
   char* ptr;
   FatFile dir;
   DirLfn_t* ldir;
   uint16_t hs = 0;
   uint32_t cp;
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   if (!isLFN()) {
     return getSFN(name, size);
   }
   if (!dir.openCluster(this)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   for (uint8_t order = 1; order <= m_lfnOrd; order++) {
     ldir = reinterpret_cast<DirLfn_t*>(dir.cacheDir(m_dirIndex - order));
     if (!ldir) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (ldir->attributes != FAT_ATTRIB_LONG_NAME ||
         order != (ldir->order & 0X1F)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (uint8_t i = 0; i < 13; i++) {
       uint16_t c = getLfnChar(ldir, i);
       if (hs) {
         if (!FsUtf::isLowSurrogate(c)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         cp = FsUtf::u16ToCp(hs, c);
         hs = 0;
       } else if (!FsUtf::isSurrogate(c)) {
         if (c == 0) {
           goto done;
         }
         cp = c;
       } else if (FsUtf::isHighSurrogate(c)) {
         hs = c;
         continue;
       } else {
         DBG_FAIL_MACRO;
         goto fail;
       }
       // Save space for zero byte.
       ptr = FsUtf::cpToMb(cp, str, end - 1);
       if (!ptr) {
         // Truncate name.  Could goto fail.
         goto done;
       }
       str = ptr;
     }
   }
  done:
   *str = '\0';
   return str - name;
  fail:
   *name = 0;
   return 0;
 }
References DirLfn_t::attributes, cacheDir(), FsUtf::cpToMb(), DBG_FAIL_MACRO, FAT_ATTRIB_LONG_NAME, getLfnChar(), getSFN(), FsUtf::isHighSurrogate(), isLFN(), FsUtf::isLowSurrogate(), isOpen(), FsUtf::isSurrogate(), m_dirIndex, m_lfnOrd, openCluster(), DirLfn_t::order, and FsUtf::u16ToCp().
Referenced by getName().
getSFN()
size_t FatFile::getSFN (char * name, size_t size)
Get a file's Short File Name followed by a zero byte.
Parameters
[out] name An array of characters for the file's name. The array should be at least 13 bytes long.
[in] size size of name array.
Returns
true for success or false for failure.
Definition at line 165 of file FatName.cpp.
{
   char c;
   uint8_t j = 0;
   uint8_t lcBit = FAT_CASE_LC_BASE;
   uint8_t* ptr;
   DirFat_t* dir;
   if (!isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isRoot()) {
     if (size < 2) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     name[0] = '/';
     name[1] = '\0';
     return 1;
   }
   // cache entry
   dir = cacheDirEntry(FsCache::CACHE_FOR_READ);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   ptr = dir->name;
   // format name
   for (uint8_t i = 0; i < 12; i++) {
     if (i == 8) {
       if (*ptr == ' ') {
         break;
       }
       lcBit = FAT_CASE_LC_EXT;
       c = '.';
     } else {
       c = *ptr++;
       if ('A' <= c && c <= 'Z' && (lcBit & dir->caseFlags)) {
         c += 'a' - 'A';
       }
       if (c == ' ') {
         continue;
       }
     }
     if ((j + 1u) == size) {
       break;
     }
     name[j++] = c;
   }
   name[j] = '\0';
   return j;
  fail:
   name[0] = '\0';
   return 0;
 }
References FsCache::CACHE_FOR_READ, cacheDirEntry(), DirFat_t::caseFlags, DBG_FAIL_MACRO, FAT_CASE_LC_BASE, FAT_CASE_LC_EXT, isOpen(), isRoot(), and DirFat_t::name.
Referenced by getName(), getName7(), getName8(), and printSFN().
getWriteError()
bool FatFile::getWriteError () const inline
Returns
value of writeError
Definition at line 376 of file FatFile.h.
{
     return isOpen() ? m_error & WRITE_ERROR : true;
   }
References isOpen(), m_error, and WRITE_ERROR.
Referenced by FsBaseFile::getWriteError().
isBusy()
bool FatFile::isBusy ()
Check for BlockDevice busy.
Returns
true if busy else false.
Definition at line 300 of file FatFile.cpp.
                      {
   return m_vol->isBusy();
 }
References FatPartition::isBusy(), and m_vol.
Referenced by FsBaseFile::isBusy().
isDir()
bool FatFile::isDir () const inline
Returns
True if this is a directory.
Definition at line 390 of file FatFile.h.
 {return m_attributes & FILE_ATTR_DIR;}
Referenced by FatVolume::chdir(), dirSize(), FsBaseFile::isDir(), ls(), mkdir(), open(), openNext(), openSFN(), read(), readDir(), and rmRfStar().
isFile()
bool FatFile::isFile () const inline
Returns
True if this is a normal file.
Definition at line 392 of file FatFile.h.
 {return m_attributes & FILE_ATTR_FILE;}
References FILE_ATTR_FILE, and m_attributes.
Referenced by available32(), contiguousRange(), FsBaseFile::isFile(), openSFN(), read(), rename(), seekEnd(), seekSet(), sync(), and timestamp().
isHidden()
bool FatFile::isHidden () const inline
Returns
True if this is a hidden file.
Definition at line 394 of file FatFile.h.
 {return m_attributes & FILE_ATTR_HIDDEN;}
References FILE_ATTR_HIDDEN, and m_attributes.
Referenced by FsBaseFile::isHidden(), and ls().
isLFN()
bool FatFile::isLFN () const inline
Returns
true if this file has a Long File Name.
Definition at line 396 of file FatFile.h.
 {return m_lfnOrd;}
References m_lfnOrd.
Referenced by getName7(), getName8(), printName7(), printName8(), remove(), rename(), and rmdir().
isOpen()
bool FatFile::isOpen () const inline
Returns
True if this is an open file/directory.
Definition at line 398 of file FatFile.h.
 {return m_attributes;}
References m_attributes.
Referenced by getName7(), getName8(), getSFN(), getWriteError(), mkdir(), open(), openNext(), openRoot(), printName7(), printName8(), seekSet(), and sync().
isReadable()
bool FatFile::isReadable () const inline
Returns
True file is readable.
Definition at line 400 of file FatFile.h.
 {return m_flags & FILE_FLAG_READ;}
References FILE_FLAG_READ, and m_flags.
Referenced by FsBaseFile::isReadable(), and read().
isReadOnly()
bool FatFile::isReadOnly () const inline
Returns
True if file is read-only
Definition at line 402 of file FatFile.h.
 {return m_attributes & FILE_ATTR_READ_ONLY;}
References FILE_ATTR_READ_ONLY, and m_attributes.
Referenced by FsBaseFile::isReadOnly(), and openCachedEntry().
isRoot()
bool FatFile::isRoot () const inline
Returns
True if this is the root directory.
Definition at line 404 of file FatFile.h.
 {return m_attributes & FILE_ATTR_ROOT;}
References FILE_ATTR_ROOT, and m_attributes.
Referenced by getSFN(), and rmRfStar().
isRoot32()
bool FatFile::isRoot32 () const inline
Returns
True if this is the FAT32 root directory.
Definition at line 406 of file FatFile.h.
 {return m_attributes & FILE_ATTR_ROOT32;}
References FILE_ATTR_ROOT32, and m_attributes.
Referenced by dirSize(), read(), and seekSet().
isRootFixed()
bool FatFile::isRootFixed () const inline
Returns
True if this is the FAT12 of FAT16 root directory.
Definition at line 408 of file FatFile.h.
 {return m_attributes & FILE_ATTR_ROOT_FIXED;}
References FILE_ATTR_ROOT_FIXED, and m_attributes.
Referenced by addDirCluster(), dirSize(), read(), and seekSet().
isSubDir()
bool FatFile::isSubDir () const inline
Returns
True if this is a subdirectory.
Definition at line 410 of file FatFile.h.
 {return m_attributes & FILE_ATTR_SUBDIR;}
References FILE_ATTR_SUBDIR, and m_attributes.
Referenced by FsBaseFile::isSubDir(), openCachedEntry(), rename(), rmdir(), and rmRfStar().
isSystem()
bool FatFile::isSystem () const inline
Returns
True if this is a system file.
Definition at line 412 of file FatFile.h.
 {return m_attributes & FILE_ATTR_SYSTEM;}
References FILE_ATTR_SYSTEM, and m_attributes.
isWritable()
bool FatFile::isWritable () const inline
Returns
True file is writable.
Definition at line 414 of file FatFile.h.
 {return m_flags & FILE_FLAG_WRITE;}
References FILE_FLAG_WRITE, and m_flags.
Referenced by FsBaseFile::isWritable(), preAllocate(), remove(), truncate(), and write().
lfnChecksum()
uint8_t FatFile::lfnChecksum (uint8_t * name) inline private
Definition at line 1003 of file FatFile.h.
{
     uint8_t sum = 0;
     for (uint8_t i = 0; i < 11; i++) {
         sum = (((sum & 1) << 7) | (sum >> 1)) + name[i];
     }
     return sum;
   }
Referenced by open(), and openNext().
ls()
bool FatFile::ls (print_t * pr, uint8_t flags = 0, uint8_t indent = 0)
List directory contents.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Parameters
[in] indent Amount of space before file name. Used for recursive list to indicate subdirectory level.
Returns
true for success or false for failure.
Definition at line 31 of file FatFilePrint.cpp.
{
   FatFile file;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   while (file.openNext(this, O_RDONLY)) {
     // indent for dir level
     if (!file.isHidden() || (flags & LS_A)) {
       for (uint8_t i = 0; i < indent; i++) {
         pr->write(' ');
       }
       if (flags & LS_DATE) {
         file.printModifyDateTime(pr);
         pr->write(' ');
       }
       if (flags & LS_SIZE) {
         file.printFileSize(pr);
         pr->write(' ');
       }
       file.printName(pr);
       if (file.isDir()) {
         pr->write('/');
       }
       pr->write('\r');
       pr->write('\n');
       if ((flags & LS_R) && file.isDir()) {
         file.ls(pr, flags, indent + 2);
       }
     }
     file.close();
   }
   if (getError()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, getError(), isDir(), isHidden(), ls(), LS_A, LS_DATE, LS_R, LS_SIZE, O_RDONLY, openNext(), printFileSize(), printModifyDateTime(), printName(), rewind(), and PrintBasic::write().
Referenced by FatVolume::ls(), and ls().
makeSFN()
static bool FatFile::makeSFN (FatLfn_t * fname) static private
makeUniqueSfn()
bool FatFile::makeUniqueSfn (FatLfn_t * fname) private
mkdir() [1/2]
bool FatFile::mkdir (FatFile * dir, const char * path, bool pFlag = true)
Make a new directory.
Parameters
[in] dir An open FatFile instance for the directory that will contain the new directory.
[in] path A path with a valid name for the new directory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 304 of file FatFile.cpp.
{
   FatName_t fname;
   FatFile tmpDir;
   if (isOpen() || !parent->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isDirSeparator(*path)) {
     while (isDirSeparator(*path)) {
       path++;
     }
     if (!tmpDir.openRoot(parent->m_vol)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     parent = &tmpDir;
   }
   while (1) {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!*path) {
       break;
     }
     if (!open(parent, &fname, O_RDONLY)) {
       if (!pFlag || !mkdir(parent, &fname)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     tmpDir = *this;
     parent = &tmpDir;
     close();
   }
   return mkdir(parent, &fname);
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, isDir(), isDirSeparator, isOpen(), m_vol, O_RDONLY, open(), openRoot(), and parsePathName().
Referenced by FatVolume::mkdir(), FsBaseFile::mkdir(), and rename().
mkdir() [2/2]
bool FatFile::mkdir (FatFile * parent, FatName_t * fname) private
Definition at line 346 of file FatFile.cpp.
{
   uint32_t sector;
   DirFat_t dot;
   DirFat_t* dir;
   uint8_t* pc;
   if (!parent->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // create a normal file
   if (!open(parent, fname, O_CREAT | O_EXCL | O_RDWR)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // convert file to directory
   m_flags = FILE_FLAG_READ;
   m_attributes = FILE_ATTR_SUBDIR;
   // allocate and zero first cluster
   if (!addDirCluster()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_firstCluster = m_curCluster;
   // Set to start of dir
   rewind();
   // force entry to device
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // cache entry - should already be in cache due to sync() call
   dir = cacheDirEntry(FsCache::CACHE_FOR_WRITE);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // change directory entry attribute
   dir->attributes = FAT_ATTRIB_DIRECTORY;
   // make entry for '.'
   memcpy(&dot, dir, sizeof(dot));
   dot.name[0] = '.';
   for (uint8_t i = 1; i < 11; i++) {
     dot.name[i] = ' ';
   }
   // cache sector for '.'  and '..'
   sector = m_vol->clusterStartSector(m_firstCluster);
   pc = m_vol->dataCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
   dir = reinterpret_cast<DirFat_t*>(pc);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // copy '.' to sector
   memcpy(&dir[0], &dot, sizeof(dot));
   // make entry for '..'
   dot.name[1] = '.';
   setLe16(dot.firstClusterLow, parent->m_firstCluster & 0XFFFF);
   setLe16(dot.firstClusterHigh, parent->m_firstCluster >> 16);
   // copy '..' to sector
   memcpy(&dir[1], &dot, sizeof(dot));
   // write first sector
   return m_vol->cacheSync();
  fail:
   return false;
 }
References addDirCluster(), DirFat_t::attributes, FsCache::CACHE_FOR_WRITE, cacheDirEntry(), FatPartition::cacheSync(), FatPartition::clusterStartSector(), FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FAT_ATTRIB_DIRECTORY, FILE_ATTR_SUBDIR, FILE_FLAG_READ, DirFat_t::firstClusterHigh, DirFat_t::firstClusterLow, isDir(), m_attributes, m_curCluster, m_firstCluster, m_flags, m_vol, DirFat_t::name, O_CREAT, O_EXCL, O_RDWR, open(), rewind(), setLe16(), and sync().
open() [1/6]
bool FatFile::open (const char * path, oflag_t oflag = O_RDONLY)
Open a file in the current working volume.
Parameters
[in] path A path with a valid name for a file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see FatFile::open(FatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 417 of file FatFile.cpp.
{
   return open(FatVolume::cwv(), path, oflag);
 }
References FatVolume::cwv(), and open().
open() [2/6]
bool FatFile::open (FatFile * dirFile, const char * path, oflag_t oflag)
Open a file or directory by name.
Parameters
[in] dirFile An open FatFile instance for the directory containing the file to be opened.
[in] path A path with a valid name for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list. Only one of O_RDONLY, O_READ, O_WRONLY, O_WRITE, or O_RDWR is allowed.
O_RDONLY - Open for reading.
O_READ - Same as O_RDONLY.
O_WRONLY - Open for writing.
O_WRITE - Same as O_WRONLY.
O_RDWR - Open for reading and writing.
O_APPEND - If set, the file offset shall be set to the end of the file prior to each write.
O_AT_END - Set the initial position at the end of the file.
O_CREAT - If the file exists, this flag has no effect except as noted under O_EXCL below. Otherwise, the file shall be created
O_EXCL - If O_CREAT and O_EXCL are set, open() shall fail if the file exists.
O_TRUNC - If the file exists and is a regular file, and the file is successfully opened and is not read only, its length shall be truncated to 0.
WARNING: A given file must not be opened by more than one FatFile object or file corruption may occur.
Note
Directory files must be opened read only. Write and truncation is not allowed for directory files.
Returns
true for success or false for failure.
Definition at line 425 of file FatFile.cpp.
{
   FatFile tmpDir;
   FatName_t fname;
   // error if already open
   if (isOpen() || !dirFile->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isDirSeparator(*path)) {
     while (isDirSeparator(*path)) {
       path++;
     }
     if (*path == 0) {
       return openRoot(dirFile->m_vol);
     }
     if (!tmpDir.openRoot(dirFile->m_vol)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     dirFile = &tmpDir;
   }
   while (1) {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (*path == 0) {
       break;
     }
     if (!open(dirFile, &fname, O_RDONLY)) {
       DBG_WARN_MACRO;
       goto fail;
     }
     tmpDir = *this;
     dirFile = &tmpDir;
     close();
   }
   return open(dirFile, &fname, oflag);
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, DBG_WARN_MACRO, isDir(), isDirSeparator, isOpen(), m_vol, O_RDONLY, open(), openRoot(), and parsePathName().
open() [3/6]
bool FatFile::open (FatFile * dirFile, FatLfn_t * fname, oflag_t oflag) private
open() [4/6]
bool FatFile::open (FatFile * dirFile, FatSfn_t * fname, oflag_t oflag) private
Definition at line 31 of file FatFileSFN.cpp.
{
   uint16_t date;
   uint16_t time;
   uint8_t ms10;
   bool emptyFound = false;
 #if SFN_OPEN_USES_CHKSUM
   uint8_t checksum;
 #endif  // SFN_OPEN_USES_CHKSUM
   uint8_t lfnOrd = 0;
   uint16_t emptyIndex;
   uint16_t index = 0;
   DirFat_t* dir;
   DirLfn_t* ldir;
   dirFile->rewind();
   while (true) {
     dir = dirFile->readDirCache(true);
     if (!dir) {
       if (dirFile->getError())  {
         DBG_FAIL_MACRO;
         goto fail;
       }
       // At EOF if no error.
       break;
     }
     if (dir->name[0] == FAT_NAME_FREE || dir->name[0] == FAT_NAME_FREE) {
       if (!emptyFound) {
         emptyIndex = index;
         emptyFound = true;
       }
       if (dir->name[0] == FAT_NAME_FREE) {
         break;
       }
       lfnOrd = 0;
     } else if (isFileOrSubdir(dir)) {
       if (!memcmp(fname->sfn, dir->name, 11)) {
         // don't open existing file if O_EXCL
         if (oflag & O_EXCL) {
           DBG_FAIL_MACRO;
           goto fail;
         }
 #if SFN_OPEN_USES_CHKSUM
         if (lfnOrd && checksum != lfnChecksum(dir->name)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
 #endif  // SFN_OPEN_USES_CHKSUM
         if (!openCachedEntry(dirFile, index, oflag, lfnOrd)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         return true;
       } else {
         lfnOrd = 0;
       }
     } else if (isLongName(dir)) {
       ldir = reinterpret_cast<DirLfn_t*>(dir);
       if (ldir->order & FAT_ORDER_LAST_LONG_ENTRY) {
         lfnOrd = ldir->order & 0X1F;
 #if SFN_OPEN_USES_CHKSUM
         checksum = ldir->checksum;
 #endif  // SFN_OPEN_USES_CHKSUM
       }
     } else {
       lfnOrd = 0;
     }
     index++;
   }
   // don't create unless O_CREAT and write mode
   if (!(oflag & O_CREAT) || !isWriteMode(oflag)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (emptyFound) {
     index = emptyIndex;
   } else {
     if (!dirFile->addDirCluster()) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   dir = reinterpret_cast<DirFat_t*>(dirFile->cacheDir(index));
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // initialize as empty file
   memset(dir, 0, sizeof(DirFat_t));
   memcpy(dir->name, fname->sfn, 11);
   // Set base-name and extension lower case bits.
   dir->caseFlags = (FAT_CASE_LC_BASE | FAT_CASE_LC_EXT) & fname->flags;
   // Set timestamps.
   if (FsDateTime::callback) {
     // call user date/time function
     FsDateTime::callback(&date, &time, &ms10);
     setLe16(dir->createDate, date);
     setLe16(dir->createTime, time);
     dir->createTimeMs = ms10;
   } else {
     setLe16(dir->createDate, FS_DEFAULT_DATE);
     setLe16(dir->modifyDate, FS_DEFAULT_DATE);
     setLe16(dir->accessDate, FS_DEFAULT_DATE);
     if (FS_DEFAULT_TIME) {
       setLe16(dir->createTime, FS_DEFAULT_TIME);
       setLe16(dir->modifyTime, FS_DEFAULT_TIME);
     }
   }
   // Force write of entry to device.
   dirFile->m_vol->cacheDirty();
   // open entry in cache.
   return openCachedEntry(dirFile, index, oflag, 0);
  fail:
   return false;
 }
References DirFat_t::accessDate, addDirCluster(), cacheDir(), FatPartition::cacheDirty(), FsDateTime::callback, DirFat_t::caseFlags, DirLfn_t::checksum, DirFat_t::createDate, DirFat_t::createTime, DirFat_t::createTimeMs, DBG_FAIL_MACRO, FAT_CASE_LC_BASE, FAT_CASE_LC_EXT, FAT_NAME_FREE, FAT_ORDER_LAST_LONG_ENTRY, FatSfn_t::flags, FS_DEFAULT_DATE, FS_DEFAULT_TIME, getError(), if(), isFileOrSubdir(), isLongName(), isWriteMode(), lfnChecksum(), m_vol, DirFat_t::modifyDate, DirFat_t::modifyTime, DirFat_t::name, O_CREAT, O_EXCL, openCachedEntry(), DirLfn_t::order, readDirCache(), rewind(), setLe16(), and FatSfn_t::sfn.
open() [5/6]
bool FatFile::open (FatFile * dirFile, uint16_t index, oflag_t oflag)
Open a file by index.
Parameters
[in] dirFile An open FatFile instance for the directory.
[in] index The index of the directory entry for the file to be opened. The value for index is (directory file position)/32.
[in] oflag bitwise-inclusive OR of open flags. See see FatFile::open(FatFile*, const char*, uint8_t).
See open() by path for definition of flags.
Returns
true for success or false for failure.
Definition at line 469 of file FatFile.cpp.
{
   if (index) {
     // Find start of LFN.
     DirLfn_t* ldir;
     uint8_t n = index < 20 ? index : 20;
     for (uint8_t i = 1; i <= n; i++) {
       ldir = reinterpret_cast<DirLfn_t*>(dirFile->cacheDir(index - i));
       if (!ldir) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       if (ldir->attributes != FAT_ATTRIB_LONG_NAME) {
         break;
       }
       if (ldir->order & FAT_ORDER_LAST_LONG_ENTRY) {
         if (!dirFile->seekSet(32UL*(index - i))) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         break;
       }
     }
   } else {
     dirFile->rewind();
   }
   if (!openNext(dirFile, oflag)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (dirIndex() != index) {
     close();
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References DirLfn_t::attributes, cacheDir(), close(), DBG_FAIL_MACRO, dirIndex(), FAT_ATTRIB_LONG_NAME, FAT_ORDER_LAST_LONG_ENTRY, openNext(), DirLfn_t::order, rewind(), and seekSet().
open() [6/6]
bool FatFile::open (FatVolume * vol, const char * path, oflag_t oflag)
Open a file in the volume root directory.
Parameters
[in] vol Volume where the file is located.
[in] path with a valid name for a file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see FatFile::open(FatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 421 of file FatFile.cpp.
{
   return vol && open(vol->vwd(), path, oflag);
 }
References FatVolume::vwd().
Referenced by FatFile(), FatVolume::chdir(), createContiguous(), exists(), FatVolume::exists(), FatVolume::ls(), mkdir(), open(), FatVolume::open(), FsBaseFile::open(), remove(), FatVolume::remove(), FatVolume::rename(), rename(), FatVolume::rmdir(), rmRfStar(), and FatVolume::truncate().
openCachedEntry()
bool FatFile::openCachedEntry (FatFile * dirFile, uint16_t cacheIndex, oflag_t oflag, uint8_t lfnOrd) private
Definition at line 510 of file FatFile.cpp.
{
   uint32_t firstCluster;
   memset(this, 0, sizeof(FatFile));
   // location of entry in cache
   m_vol = dirFile->m_vol;
   m_dirIndex = dirIndex;
   m_dirCluster = dirFile->m_firstCluster;
   DirFat_t* dir = reinterpret_cast<DirFat_t*>(m_vol->cacheAddress());
   dir += 0XF & dirIndex;
   // Must be file or subdirectory.
   if (!isFileOrSubdir(dir)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_attributes = dir->attributes & FILE_ATTR_COPY;
   if (isFileDir(dir)) {
     m_attributes |= FILE_ATTR_FILE;
   }
   m_lfnOrd = lfnOrd;
   switch (oflag & O_ACCMODE) {
     case O_RDONLY:
       if (oflag & O_TRUNC) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       m_flags = FILE_FLAG_READ;
       break;
     case O_RDWR:
       m_flags = FILE_FLAG_READ | FILE_FLAG_WRITE;
       break;
     case O_WRONLY:
       m_flags = FILE_FLAG_WRITE;
       break;
     default:
       DBG_FAIL_MACRO;
       goto fail;
   }
   if (m_flags & FILE_FLAG_WRITE) {
     if (isSubDir() || isReadOnly()) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   m_flags |= (oflag & O_APPEND ? FILE_FLAG_APPEND : 0);
   m_dirSector = m_vol->cacheSectorNumber();
   // copy first cluster number for directory fields
   firstCluster = ((uint32_t)getLe16(dir->firstClusterHigh) << 16)
                  | getLe16(dir->firstClusterLow);
   if (oflag & O_TRUNC) {
     if (firstCluster && !m_vol->freeChain(firstCluster)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // need to update directory entry
     m_flags |= FILE_FLAG_DIR_DIRTY;
   } else {
     m_firstCluster = firstCluster;
     m_fileSize = getLe32(dir->fileSize);
   }
   if ((oflag & O_AT_END) && !seekSet(m_fileSize)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   return false;
 }
References DirFat_t::attributes, FatPartition::cacheAddress(), FatPartition::cacheSectorNumber(), DBG_FAIL_MACRO, dirIndex(), FILE_ATTR_CLOSED, FILE_ATTR_COPY, FILE_ATTR_FILE, FILE_FLAG_APPEND, FILE_FLAG_DIR_DIRTY, FILE_FLAG_READ, FILE_FLAG_WRITE, DirFat_t::fileSize, DirFat_t::firstClusterHigh, DirFat_t::firstClusterLow, FatPartition::freeChain(), getLe16(), getLe32(), isFileDir(), isFileOrSubdir(), isReadOnly(), isSubDir(), m_attributes, m_dirCluster, m_dirIndex, m_dirSector, m_fileSize, m_firstCluster, m_flags, m_lfnOrd, m_vol, O_ACCMODE, O_APPEND, O_AT_END, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, and seekSet().
Referenced by open(), and openNext().
openCluster()
bool FatFile::openCluster (FatFile * file) private
Definition at line 592 of file FatFile.cpp.
{
   if (file->m_dirCluster == 0) {
     return openRoot(file->m_vol);
   }
   memset(this, 0, sizeof(FatFile));
   m_attributes = FILE_ATTR_SUBDIR;
   m_flags = FILE_FLAG_READ;
   m_vol = file->m_vol;
   m_firstCluster = file->m_dirCluster;
   return true;
 }
References FILE_ATTR_SUBDIR, FILE_FLAG_READ, m_attributes, m_dirCluster, m_firstCluster, m_flags, m_vol, and openRoot().
Referenced by getName7(), getName8(), printName7(), and printName8().
openExistingSFN()
bool FatFile::openExistingSFN (const char * path)
Open existing file wih Short 8.3 names.
Parameters
[in] path with short 8.3 names.
the purpose of this function is to save flash on Uno and other small boards.
Directories will be opened O_RDONLY, files O_RDWR.
Returns
true for success or false for failure.
Definition at line 150 of file FatFileSFN.cpp.
{
   FatSfn_t fname;
   auto vol = FatVolume::cwv();
   while (*path == '/') {
     path++;
   }
   if (*path == 0) {
     return openRoot(vol);
   }
   *this = *vol->vwd();
   do {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!openSFN(&fname)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } while (*path);
   return true;
  fail:
   return false;
 }
References FatVolume::cwv(), DBG_FAIL_MACRO, openRoot(), openSFN(), and parsePathName().
openNext()
bool FatFile::openNext (FatFile * dirFile, oflag_t oflag = O_RDONLY)
Open the next file or subdirectory in a directory.
Parameters
[in] dirFile An open FatFile instance for the directory containing the file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see FatFile::open(FatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 604 of file FatFile.cpp.
{
   uint8_t checksum = 0;
   DirLfn_t* ldir;
   uint8_t lfnOrd = 0;
   uint16_t index;
   // Check for not open and valid directory..
   if (isOpen() || !dirFile->isDir() || (dirFile->curPosition() & 0X1F)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   while (1) {
     // read entry into cache
     index = dirFile->curPosition()/FS_DIR_SIZE;
     DirFat_t* dir = dirFile->readDirCache();
     if (!dir) {
       if (dirFile->getError()) {
         DBG_FAIL_MACRO;
       }
       goto fail;
     }
     // done if last entry
     if (dir->name[0] == FAT_NAME_FREE) {
       goto fail;
     }
     // skip empty slot or '.' or '..'
     if (dir->name[0] == '.' || dir->name[0] == FAT_NAME_DELETED) {
       lfnOrd = 0;
     } else if (isFileOrSubdir(dir)) {
       if (lfnOrd && checksum != lfnChecksum(dir->name)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       if (!openCachedEntry(dirFile, index, oflag, lfnOrd)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       return true;
     } else if (isLongName(dir)) {
       ldir = reinterpret_cast<DirLfn_t*>(dir);
       if (ldir->order & FAT_ORDER_LAST_LONG_ENTRY) {
         lfnOrd = ldir->order & 0X1F;
         checksum = ldir->checksum;
       }
     } else {
       lfnOrd = 0;
     }
   }
  fail:
   return false;
 }
References DirLfn_t::checksum, curPosition(), DBG_FAIL_MACRO, FAT_NAME_DELETED, FAT_NAME_FREE, FAT_ORDER_LAST_LONG_ENTRY, FS_DIR_SIZE, getError(), isDir(), isFileOrSubdir(), isLongName(), isOpen(), lfnChecksum(), DirFat_t::name, openCachedEntry(), DirLfn_t::order, and readDirCache().
Referenced by ls(), open(), FsBaseFile::openNext(), and File32::openNextFile().
openRoot()
bool FatFile::openRoot (FatVolume * vol)
Open a volume's root directory.
Parameters
[in] vol The FAT volume containing the root directory to be opened.
Returns
true for success or false for failure.
Definition at line 657 of file FatFile.cpp.
{
   // error if file is already open
   if (isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   memset(this, 0, sizeof(FatFile));
   m_vol = vol;
   switch (vol->fatType()) {
 #if FAT12_SUPPORT
   case 12:
 #endif  // FAT12_SUPPORT
   case 16:
     m_attributes = FILE_ATTR_ROOT_FIXED;
     break;
   case 32:
     m_attributes = FILE_ATTR_ROOT32;
     break;
   default:
     DBG_FAIL_MACRO;
     goto fail;
   }
   // read only
   m_flags = FILE_FLAG_READ;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FatPartition::fatType(), FILE_ATTR_ROOT32, FILE_ATTR_ROOT_FIXED, FILE_FLAG_READ, isOpen(), m_attributes, m_flags, and m_vol.
Referenced by FatVolume::chdir(), mkdir(), open(), openCluster(), openExistingSFN(), and FsBaseFile::openRoot().
openSFN()
bool FatFile::openSFN (FatSfn_t * fname) private
Definition at line 176 of file FatFileSFN.cpp.
{
   DirFat_t dir;
   DirLfn_t* ldir;
   auto vol = m_vol;
   uint8_t lfnOrd = 0;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   while (true) {
     if (read(&dir, 32) != 32) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (dir.name[0] == 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (isFileOrSubdir(&dir) && memcmp(fname->sfn, dir.name, 11) == 0) {
       uint16_t dirIndex = (m_curPosition - 32) >> 5;
       uint32_t dirCluster = m_firstCluster;
       memset(this, 0 , sizeof(FatFile));
       m_attributes = dir.attributes & FILE_ATTR_COPY;
       if (isFileDir(&dir)) {
         m_attributes |= FILE_ATTR_FILE;
       }
       m_lfnOrd = lfnOrd;
       m_firstCluster = (uint32_t)getLe16(dir.firstClusterHigh) << 16;
       m_firstCluster |= getLe16(dir.firstClusterLow);
       m_fileSize = getLe32(dir.fileSize);
       m_flags = isFile() ? FILE_FLAG_READ | FILE_FLAG_WRITE : FILE_FLAG_READ;
       m_vol = vol;
       m_dirCluster = dirCluster;
       m_dirSector = m_vol->cacheSectorNumber();
       m_dirIndex = dirIndex;
       return true;
     } else if (isLongName(&dir)) {
       ldir = reinterpret_cast<DirLfn_t*>(&dir);
       if (ldir->order & FAT_ORDER_LAST_LONG_ENTRY) {
         lfnOrd = ldir->order & 0X1F;
       }
     } else {
       lfnOrd = 0;
     }
   }
  fail:
   return false;
 }
References DirFat_t::attributes, FatPartition::cacheSectorNumber(), DBG_FAIL_MACRO, dirIndex(), FAT_ORDER_LAST_LONG_ENTRY, FILE_ATTR_COPY, FILE_ATTR_FILE, FILE_FLAG_READ, FILE_FLAG_WRITE, DirFat_t::fileSize, DirFat_t::firstClusterHigh, DirFat_t::firstClusterLow, getLe16(), getLe32(), isDir(), isFile(), isFileDir(), isFileOrSubdir(), isLongName(), m_attributes, m_curPosition, m_dirCluster, m_dirIndex, m_dirSector, m_fileSize, m_firstCluster, m_flags, m_lfnOrd, m_vol, DirFat_t::name, DirLfn_t::order, read(), and FatSfn_t::sfn.
Referenced by openExistingSFN().
operator bool()
FatFile::operator bool () const inline
The parenthesis operator.
Returns
true if a file is open.
Definition at line 158 of file FatFile.h.
 {return isOpen();}
parsePathName() [1/2]
bool FatFile::parsePathName (const char * str, FatLfn_t * fname, const char ** ptr) private
Referenced by mkdir(), open(), and openExistingSFN().
parsePathName() [2/2]
bool FatFile::parsePathName (const char * str, FatSfn_t * fname, const char ** ptr) private
Definition at line 227 of file FatFileSFN.cpp.
{
   uint8_t uc = 0;
   uint8_t lc = 0;
   uint8_t bit = FNAME_FLAG_LC_BASE;
   // blank fill name and extension
   for (uint8_t i = 0; i < 11; i++) {
     fname->sfn[i] = ' ';
   }
   for (uint8_t i = 0, n = 7;; path++) {
     uint8_t c = *path;
     if (c == 0 || isDirSeparator(c)) {
       // Done.
       break;
     }
     if (c == '.' && n == 7) {
       n = 10;  // max index for full 8.3 name
       i = 8;   // place for extension
       // bit for extension.
       bit = FNAME_FLAG_LC_EXT;
     } else {
       if (sfnReservedChar(c) || i > n) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       if ('a' <= c && c <= 'z') {
         c += 'A' - 'a';
         lc |= bit;
       } else if ('A' <= c && c <= 'Z') {
         uc |= bit;
       }
       fname->sfn[i++] = c;
     }
   }
   // must have a file name, extension is optional
   if (fname->sfn[0] == ' ') {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Set base-name and extension bits.
   fname->flags = lc & uc ? 0 : lc;
   while (isDirSeparator(*path)) {
     path++;
   }
   *ptr = path;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FatSfn_t::flags, FNAME_FLAG_LC_BASE, FNAME_FLAG_LC_EXT, isDirSeparator, FatSfn_t::sfn, and sfnReservedChar().
peek()
int FatFile::peek ()
Return the next available byte without consuming it.
Returns
The byte if no error and not at eof else -1;
Definition at line 690 of file FatFile.cpp.
                   {
   uint32_t curPosition = m_curPosition;
   uint32_t curCluster = m_curCluster;
   int c = read();
   m_curPosition = curPosition;
   m_curCluster = curCluster;
   return c;
 }
References curCluster(), curPosition(), m_curCluster, m_curPosition, and read().
preAllocate()
bool FatFile::preAllocate (uint32_t length)
Allocate contiguous clusters to an empty file.
The file must be empty with no clusters allocated.
The file will contain uninitialized data.
Parameters
[in] length size of the file in bytes.
Returns
true for success or false for failure.
Definition at line 699 of file FatFile.cpp.
{
   uint32_t need;
   if (!length || !isWritable() || m_firstCluster) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   need = 1 + ((length - 1) >> m_vol->bytesPerClusterShift());
   // allocate clusters
   if (!m_vol->allocContiguous(need, &m_firstCluster)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_fileSize = length;
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
   // Mark contiguous and insure sync() will update dir entry
   m_flags |= FILE_FLAG_PREALLOCATE | FILE_FLAG_CONTIGUOUS | FILE_FLAG_DIR_DIRTY;
 #else  // USE_FAT_FILE_FLAG_CONTIGUOUS
   // insure sync() will update dir entry
   m_flags |= FILE_FLAG_DIR_DIRTY;
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
   return sync();
  fail:
   return false;
 }
References FatPartition::allocContiguous(), FatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, FILE_FLAG_CONTIGUOUS, FILE_FLAG_DIR_DIRTY, FILE_FLAG_PREALLOCATE, isWritable(), m_fileSize, m_firstCluster, m_flags, m_vol, and sync().
Referenced by createContiguous().
printAccessDate()
size_t FatFile::printAccessDate (print_t * pr)
Print a file's access date
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed.
Definition at line 74 of file FatFilePrint.cpp.
{
   uint16_t date;
   if (getAccessDate(&date)) {
     return fsPrintDate(pr, date);
   }
   return 0;
 }
References fsPrintDate(), and getAccessDate().
Referenced by printAccessDateTime().
printAccessDateTime()
size_t FatFile::printAccessDateTime (print_t * pr) inline
Print a file's access date
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed.
Definition at line 592 of file FatFile.h.
{
     return printAccessDate(pr);
   }
References printAccessDate().
printCreateDateTime()
size_t FatFile::printCreateDateTime (print_t * pr)
Print a file's creation date and time
Parameters
[in] pr Print stream for output.
Returns
The number of bytes printed.
Definition at line 82 of file FatFilePrint.cpp.
{
   uint16_t date;
   uint16_t time;
   if (getCreateDateTime(&date, &time)) {
     return fsPrintDateTime(pr, date, time);
   }
   return 0;
 }
References fsPrintDateTime(), and getCreateDateTime().
printFatDate()
static void FatFile::printFatDate (print_t * pr, uint16_t fatDate) static
Print a directory date field.
Format is yyyy-mm-dd.
Parameters
[in] pr Print stream for output.
[in] fatDate The date field from a directory entry.
printFatTime()
static void FatFile::printFatTime (print_t * pr, uint16_t fatTime) static
Print a directory time field.
Format is hh:mm:ss.
Parameters
[in] pr Print stream for output.
[in] fatTime The time field from a directory entry.
printField() [1/3]
size_t FatFile::printField (double value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 624 of file FatFile.h.
{
     char buf[24];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     str = fmtDouble(str, value, prec, false);
     return write(str, buf + sizeof(buf) - str);
   }
References buf, fmtDouble(), and write().
Referenced by printField().
printField() [2/3]
size_t FatFile::printField (float value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 642 of file FatFile.h.
{
     return printField(static_cast<double>(value), term, prec);
   }
References printField().
printField() [3/3]
template<typename Type > size_t FatFile::printField (Type value, char term) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 651 of file FatFile.h.
{
     char sign = 0;
     char buf[3*sizeof(Type) + 3];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     if (value < 0) {
       value = -value;
       sign = '-';
     }
     if (sizeof(Type) < 4) {
       str = fmtBase10(str, (uint16_t)value);
     } else {
       str = fmtBase10(str, (uint32_t)value);
     }
     if (sign) {
       *--str = sign;
     }
     return write(str, &buf[sizeof(buf)] - str);
   }
References buf, fmtBase10(), and write().
printFileSize()
size_t FatFile::printFileSize (print_t * pr)
Print a file's size.
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed is returned for success and zero is returned for failure.
Definition at line 100 of file FatFilePrint.cpp.
{
   char buf[11];
   char *ptr = buf + sizeof(buf);
   *--ptr = 0;
   ptr = fmtBase10(ptr, fileSize());
   while (ptr > buf) {
     *--ptr = ' ';
   }
   return pr->write(buf);
 }
References buf, fileSize(), fmtBase10(), and PrintBasic::write().
Referenced by ls().
printModifyDateTime()
size_t FatFile::printModifyDateTime (print_t * pr)
Print a file's modify date and time
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed.
Definition at line 91 of file FatFilePrint.cpp.
{
   uint16_t date;
   uint16_t time;
   if (getModifyDateTime(&date, &time)) {
     return fsPrintDateTime(pr, date, time);
   }
   return 0;
 }
References fsPrintDateTime(), and getModifyDateTime().
Referenced by ls().
printName()
size_t FatFile::printName (print_t * pr)
Print a file's name
Parameters
[in] pr Print stream for output.
Returns
length for success or zero for failure.
Definition at line 221 of file FatName.cpp.
{
 #if !USE_LONG_FILE_NAMES
   return printSFN(pr);
 #elif USE_UTF8_LONG_NAMES
   return printName8(pr);
 # else  // USE_LONG_FILE_NAMES
   return printName7(pr);
 #endif  // !USE_LONG_FILE_NAMES
   }
References printName7(), printName8(), and printSFN().
Referenced by ls().
printName7()
size_t FatFile::printName7 (print_t * pr)
Print a file's ASCII name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 231 of file FatName.cpp.
{
   FatFile dir;
   DirLfn_t* ldir;
   size_t n = 0;
   uint8_t buf[13];
   uint8_t i;
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   if (!isLFN()) {
     return printSFN(pr);
   }
   if (!dir.openCluster(this)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   for (uint8_t order = 1; order <= m_lfnOrd; order++) {
     ldir = reinterpret_cast<DirLfn_t*>(dir.cacheDir(m_dirIndex - order));
     if (!ldir) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (ldir->attributes != FAT_ATTRIB_LONG_NAME ||
         order != (ldir->order & 0X1F)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (i = 0; i < 13; i++) {
       uint16_t u = getLfnChar(ldir, i);
       if (u == 0) {
         // End of name.
         break;
       }
       buf[i] = u < 0X7F ? u : '?';
       n++;
     }
     pr->write(buf, i);
   }
   return n;
  fail:
   return 0;
 }
References DirLfn_t::attributes, buf, cacheDir(), DBG_FAIL_MACRO, FAT_ATTRIB_LONG_NAME, getLfnChar(), isLFN(), isOpen(), m_dirIndex, m_lfnOrd, openCluster(), DirLfn_t::order, printSFN(), and PrintBasic::write().
Referenced by printName().
printName8()
size_t FatFile::printName8 (print_t * pr)
Print a file's UTF-8 name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 277 of file FatName.cpp.
{
   FatFile dir;
   DirLfn_t* ldir;
   uint16_t hs = 0;
   uint32_t cp;
   size_t n = 0;
   char buf[5];
   char* end = buf + sizeof(buf);
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   if (!isLFN()) {
     return printSFN(pr);
   }
   if (!dir.openCluster(this)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   for (uint8_t order = 1; order <= m_lfnOrd; order++) {
     ldir = reinterpret_cast<DirLfn_t*>(dir.cacheDir(m_dirIndex - order));
     if (!ldir) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (ldir->attributes != FAT_ATTRIB_LONG_NAME ||
         order != (ldir->order & 0X1F)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (uint8_t i = 0; i < 13; i++) {
       uint16_t c = getLfnChar(ldir, i);;
       if (hs) {
         if (!FsUtf::isLowSurrogate(c)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         cp = FsUtf::u16ToCp(hs, c);
         hs = 0;
       } else if (!FsUtf::isSurrogate(c)) {
         if (c == 0) {
           break;
         }
         cp = c;
       } else if (FsUtf::isHighSurrogate(c)) {
         hs = c;
         continue;
       } else {
         DBG_FAIL_MACRO;
         goto fail;
       }
       char* str = FsUtf::cpToMb(cp, buf, end);
       if (!str) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       n += pr->write(buf, str - buf);
     }
   }
   return n;
  fail:
   return 0;
 }
References DirLfn_t::attributes, buf, cacheDir(), FsUtf::cpToMb(), DBG_FAIL_MACRO, FAT_ATTRIB_LONG_NAME, getLfnChar(), FsUtf::isHighSurrogate(), isLFN(), FsUtf::isLowSurrogate(), isOpen(), FsUtf::isSurrogate(), m_dirIndex, m_lfnOrd, openCluster(), DirLfn_t::order, printSFN(), FsUtf::u16ToCp(), and PrintBasic::write().
Referenced by printName().
printSFN()
size_t FatFile::printSFN (print_t * pr)
Print a file's Short File Name.
Parameters
[in] pr Print stream for output.
Returns
The number of characters printed is returned for success and zero is returned for failure.
Definition at line 342 of file FatName.cpp.
{
   char name[13];
   if (!getSFN(name, sizeof(name))) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return pr->write(name);
  fail:
   return 0;
 }
References DBG_FAIL_MACRO, getSFN(), and PrintBasic::write().
Referenced by printName(), printName7(), and printName8().
read() [1/2]
int FatFile::read () inline
Read the next byte from a file.
Returns
For success read returns the next byte in the file as an int. If an error occurs or end of file is reached -1 is returned.
Definition at line 725 of file FatFile.h.
              {
     uint8_t b;
     return read(&b, 1) == 1 ? b : -1;
   }
Referenced by dmpFile(), fgets(), openSFN(), peek(), readDir(), and readDirCache().
read() [2/2]
int FatFile::read (void * buf, size_t count)
Read data from a file starting at the current position.
Parameters
[out] buf Pointer to the location that will receive the data.
[in] count Maximum number of bytes to read.
Returns
For success read() returns the number of bytes read. A value less than nbyte, including zero, will be returned if end of file is reached. If an error occurs, read() returns -1.
Definition at line 726 of file FatFile.cpp.
{
   int8_t fg;
   uint8_t sectorOfCluster = 0;
   uint8_t* dst = reinterpret_cast<uint8_t*>(buf);
   uint16_t offset;
   size_t toRead;
   uint32_t sector;  // raw device sector number
   uint8_t* pc;
   // error if not open for read
   if (!isReadable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isFile()) {
     uint32_t tmp32 = m_fileSize - m_curPosition;
     if (nbyte >= tmp32) {
       nbyte = tmp32;
     }
   } else if (isRootFixed()) {
     uint16_t tmp16 =
       FS_DIR_SIZE*m_vol->m_rootDirEntryCount - (uint16_t)m_curPosition;
     if (nbyte > tmp16) {
       nbyte = tmp16;
     }
   }
   toRead = nbyte;
   while (toRead) {
     size_t n;
     offset = m_curPosition & m_vol->sectorMask();  // offset in sector
     if (isRootFixed()) {
       sector = m_vol->rootDirStart()
                + (m_curPosition >> m_vol->bytesPerSectorShift());
     } else {
       sectorOfCluster = m_vol->sectorOfCluster(m_curPosition);
       if (offset == 0 && sectorOfCluster == 0) {
         // start of new cluster
         if (m_curPosition == 0) {
           // use first cluster in file
           m_curCluster = isRoot32() ? m_vol->rootDirStart() : m_firstCluster;
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
         } else if (isFile() && isContiguous()) {
           m_curCluster++;
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
         } else {
           // get next cluster from FAT
           fg = m_vol->fatGet(m_curCluster, &m_curCluster);
           if (fg < 0) {
             DBG_FAIL_MACRO;
             goto fail;
           }
           if (fg == 0) {
             if (isDir()) {
               break;
             }
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
       }
       sector = m_vol->clusterStartSector(m_curCluster) + sectorOfCluster;
     }
     if (offset != 0 || toRead < m_vol->bytesPerSector()
         || sector == m_vol->cacheSectorNumber()) {
       // amount to be read from current sector
       n = m_vol->bytesPerSector() - offset;
       if (n > toRead) {
         n = toRead;
       }
       // read sector to cache and copy data to caller
       pc = m_vol->dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
       if (!pc) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       uint8_t* src = pc + offset;
       memcpy(dst, src, n);
 #if USE_MULTI_SECTOR_IO
     } else if (toRead >= 2*m_vol->bytesPerSector()) {
       uint32_t ns = toRead >> m_vol->bytesPerSectorShift();
       if (!isRootFixed()) {
         uint32_t mb = m_vol->sectorsPerCluster() - sectorOfCluster;
         if (mb < ns) {
           ns = mb;
         }
       }
       n = ns << m_vol->bytesPerSectorShift();
       if (!m_vol->cacheSafeRead(sector, dst, ns)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
 #endif  // USE_MULTI_SECTOR_IO
     } else {
       // read single sector
       n = m_vol->bytesPerSector();
       if (!m_vol->cacheSafeRead(sector, dst)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     dst += n;
     m_curPosition += n;
     toRead -= n;
   }
   return nbyte - toRead;
  fail:
   m_error |= READ_ERROR;
   return -1;
 }
References buf, FatPartition::bytesPerSector(), FatPartition::bytesPerSectorShift(), FsCache::CACHE_FOR_READ, FatPartition::cacheSafeRead(), FatPartition::cacheSectorNumber(), FatPartition::clusterStartSector(), FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FatPartition::fatGet(), FS_DIR_SIZE, isDir(), isFile(), isReadable(), isRoot32(), isRootFixed(), m_curCluster, m_curPosition, m_error, m_fileSize, m_firstCluster, FatPartition::m_rootDirEntryCount, m_vol, READ_ERROR, FatPartition::rootDirStart(), FatPartition::sectorMask(), FatPartition::sectorOfCluster(), and FatPartition::sectorsPerCluster().
readDir()
int8_t FatFile::readDir (DirFat_t * dir)
Read the next directory entry from a directory file.
Parameters
[out] dir The DirFat_t struct that will receive the data.
Returns
For success readDir() returns the number of bytes read. A value of zero will be returned if end of file is reached. If an error occurs, readDir() returns -1. Possible errors include readDir() called before a directory has been opened, this is not a directory file or an I/O error occurred.
Definition at line 837 of file FatFile.cpp.
{
   int16_t n;
   // if not a directory file or miss-positioned return an error
   if (!isDir() || (0X1F & m_curPosition)) {
     return -1;
   }
   while (1) {
     n = read(dir, sizeof(DirFat_t));
     if (n != sizeof(DirFat_t)) {
       return n == 0 ? 0 : -1;
     }
     // last entry if FAT_NAME_FREE
     if (dir->name[0] == FAT_NAME_FREE) {
       return 0;
     }
     // skip empty entries and entry for .  and ..
     if (dir->name[0] == FAT_NAME_DELETED || dir->name[0] == '.') {
       continue;
     }
     // return if normal file or subdirectory
     if (isFileOrSubdir(dir)) {
       return n;
     }
   }
 }
References FAT_NAME_DELETED, FAT_NAME_FREE, isDir(), isFileOrSubdir(), m_curPosition, DirFat_t::name, and read().
readDirCache()
DirFat_t * FatFile::readDirCache (bool skipReadOk = false) private
Definition at line 866 of file FatFile.cpp.
{
   DBG_HALT_IF(m_curPosition & 0X1F);
   uint8_t i = (m_curPosition >> 5) & 0XF;
   if (i == 0 || !skipReadOk) {
     int8_t n = read(&n, 1);
     if  (n != 1) {
       if (n != 0) {
         DBG_FAIL_MACRO;
       }
       goto fail;
     }
     m_curPosition += FS_DIR_SIZE - 1;
   } else {
     m_curPosition += FS_DIR_SIZE;
   }
   // return pointer to entry
   return reinterpret_cast<DirFat_t*>(m_vol->cacheAddress()) + i;
  fail:
   return nullptr;
 }
References FatPartition::cacheAddress(), DBG_FAIL_MACRO, DBG_HALT_IF, FS_DIR_SIZE, m_curPosition, m_vol, and read().
Referenced by cacheDir(), open(), openNext(), rmdir(), and rmRfStar().
remove() [1/2]
bool FatFile::remove ()
Remove a file.
The directory entry and all data for the file are deleted.
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 280 of file FatFileSFN.cpp.
                      {
   DirFat_t* dir;
   // Can't remove if LFN or not open for write.
   if (!isWritable() || isLFN()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Free any clusters.
   if (m_firstCluster && !m_vol->freeChain(m_firstCluster)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Cache directory entry.
   dir = cacheDirEntry(FsCache::CACHE_FOR_WRITE);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Mark entry deleted.
   dir->name[0] = FAT_NAME_DELETED;
   // Set this file closed.
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   // Write entry to device.
   return m_vol->cacheSync();
  fail:
   return false;
 }
References FsCache::CACHE_FOR_WRITE, cacheDirEntry(), FatPartition::cacheSync(), DBG_FAIL_MACRO, FAT_NAME_DELETED, FILE_ATTR_CLOSED, FatPartition::freeChain(), isLFN(), isWritable(), m_attributes, m_firstCluster, m_flags, m_vol, and DirFat_t::name.
Referenced by FsBaseFile::remove(), remove(), FatVolume::remove(), rename(), rmdir(), and rmRfStar().
remove() [2/2]
bool FatFile::remove (const char * path)
Remove a file.
The directory entry and all data for the file are deleted.
Parameters
[in] path Path for the file to be removed.
Example use: dirFile.remove(filenameToRemove);
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 889 of file FatFile.cpp.
{
   FatFile file;
   if (!file.open(this, path, O_WRONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return file.remove();
  fail:
   return false;
 }
References DBG_FAIL_MACRO, O_WRONLY, open(), and remove().
rename() [1/2]
bool FatFile::rename (const char * newPath)
Rename a file or subdirectory.
Note
the renamed file will be moved to the current volume working directory.
Parameters
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 901 of file FatFile.cpp.
{
   return rename(m_vol->vwd(), newPath);
 }
References m_vol, and FatVolume::vwd().
Referenced by FatVolume::rename().
rename() [2/2]
bool FatFile::rename (FatFile * dirFile, const char * newPath)
Rename a file or subdirectory.
Parameters
[in] dirFile Directory for the new path.
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 905 of file FatFile.cpp.
{
   DirFat_t entry;
   uint32_t dirCluster = 0;
   FatFile file;
   FatFile oldFile;
   uint8_t* pc;
   DirFat_t* dir;
   // Must be an open file or subdirectory.
   if (!(isFile() || isSubDir())) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Can't rename LFN in 8.3 mode.
   if (!USE_LONG_FILE_NAMES && isLFN()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Can't move file to new volume.
   if (m_vol != dirFile->m_vol) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // sync() and cache directory entry
   sync();
   oldFile = *this;
   dir = cacheDirEntry(FsCache::CACHE_FOR_READ);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // save directory entry
   memcpy(&entry, dir, sizeof(entry));
   // make directory entry for new path
   if (isFile()) {
     if (!file.open(dirFile, newPath, O_CREAT | O_EXCL | O_WRONLY)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } else {
     // don't create missing path prefix components
     if (!file.mkdir(dirFile, newPath, false)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // save cluster containing new dot dot
     dirCluster = file.m_firstCluster;
   }
   // change to new directory entry
   m_dirSector = file.m_dirSector;
   m_dirIndex = file.m_dirIndex;
   m_lfnOrd = file.m_lfnOrd;
   m_dirCluster = file.m_dirCluster;
   // mark closed to avoid possible destructor close call
   file.m_attributes = FILE_ATTR_CLOSED;
   file.m_flags = 0;
   // cache new directory entry
   dir = cacheDirEntry(FsCache::CACHE_FOR_WRITE);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // copy all but name and name flags to new directory entry
   memcpy(&dir->createTimeMs, &entry.createTimeMs,
          sizeof(entry) - sizeof(dir->name) - 2);
   dir->attributes = entry.attributes;
   // update dot dot if directory
   if (dirCluster) {
     // get new dot dot
     uint32_t sector = m_vol->clusterStartSector(dirCluster);
     pc = m_vol->dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
     dir = reinterpret_cast<DirFat_t*>(pc);
     if (!dir) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     memcpy(&entry, &dir[1], sizeof(entry));
     // free unused cluster
     if (!m_vol->freeChain(dirCluster)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // store new dot dot
     sector = m_vol->clusterStartSector(m_firstCluster);
     uint8_t* pc = m_vol->dataCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
     dir = reinterpret_cast<DirFat_t*>(pc);
     if (!dir) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     memcpy(&dir[1], &entry, sizeof(entry));
   }
   // Remove old directory entry;
   oldFile.m_firstCluster = 0;
   oldFile.m_flags = FILE_FLAG_WRITE;
   oldFile.m_attributes = FILE_ATTR_FILE;
   if (!oldFile.remove()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return m_vol->cacheSync();
  fail:
   return false;
 }
References DirFat_t::attributes, FsCache::CACHE_FOR_READ, FsCache::CACHE_FOR_WRITE, cacheDirEntry(), FatPartition::cacheSync(), FatPartition::clusterStartSector(), DirFat_t::createTimeMs, FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FILE_ATTR_CLOSED, FILE_ATTR_FILE, FILE_FLAG_WRITE, FatPartition::freeChain(), isFile(), isLFN(), isSubDir(), m_attributes, m_dirCluster, m_dirIndex, m_dirSector, m_firstCluster, m_flags, m_lfnOrd, m_vol, mkdir(), DirFat_t::name, O_CREAT, O_EXCL, O_WRONLY, open(), remove(), sync(), and USE_LONG_FILE_NAMES.
rewind()
void FatFile::rewind () inline
Set the file's current position to zero.
Definition at line 796 of file FatFile.h.
                 {
     seekSet(0);
   }
References seekSet().
Referenced by ls(), mkdir(), open(), rmdir(), and rmRfStar().
rmdir()
bool FatFile::rmdir ()
Remove a directory file.
The directory file will be removed only if it is empty and is not the root directory. rmdir() follows DOS and Windows and ignores the read-only attribute for the directory.
Note
This function should not be used to delete the 8.3 version of a directory that has a long name. For example if a directory has the long name "New folder" you should not delete the 8.3 name "NEWFOL~1".
Returns
true for success or false for failure.
Definition at line 1015 of file FatFile.cpp.
                     {
   // must be open subdirectory
   if (!isSubDir() || (!USE_LONG_FILE_NAMES && isLFN())) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   // make sure directory is empty
   while (1) {
     DirFat_t* dir = readDirCache(true);
     if (!dir) {
       // EOF if no error.
       if (!getError()) {
         break;
       }
       DBG_FAIL_MACRO;
       goto fail;
     }
     // done if past last used entry
     if (dir->name[0] == FAT_NAME_FREE) {
       break;
     }
     // skip empty slot, '.' or '..'
     if (dir->name[0] == FAT_NAME_DELETED || dir->name[0] == '.') {
       continue;
     }
     // error not empty
     if (isFileOrSubdir(dir)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   // convert empty directory to normal file for remove
   m_attributes = FILE_ATTR_FILE;
   m_flags |= FILE_FLAG_WRITE;
   return remove();
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FAT_NAME_DELETED, FAT_NAME_FREE, FILE_ATTR_FILE, FILE_FLAG_WRITE, getError(), isFileOrSubdir(), isLFN(), isSubDir(), m_attributes, m_flags, DirFat_t::name, readDirCache(), remove(), rewind(), and USE_LONG_FILE_NAMES.
Referenced by FsBaseFile::rmdir(), FatVolume::rmdir(), and rmRfStar().
rmRfStar()
bool FatFile::rmRfStar ()
Recursively delete a directory and all contained files.
This is like the Unix/Linux 'rm -rf *' if called with the root directory hence the name.
Warning - This will remove all contents of the directory including subdirectories. The directory will then be removed if it is not root. The read-only attribute for files will be ignored.
Note
This function should not be used to delete the 8.3 version of a directory that has a long name. See remove() and rmdir().
Returns
true for success or false for failure.
Definition at line 1057 of file FatFile.cpp.
{
   uint16_t index;
   FatFile f;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   while (1) {
     // remember position
     index = m_curPosition/FS_DIR_SIZE;
     DirFat_t* dir = readDirCache();
     if (!dir) {
       // At EOF if no error.
       if (!getError()) {
         break;
       }
       DBG_FAIL_MACRO;
       goto fail;
     }
     // done if past last entry
     if (dir->name[0] == FAT_NAME_FREE) {
       break;
     }
     // skip empty slot or '.' or '..'
     if (dir->name[0] == FAT_NAME_DELETED || dir->name[0] == '.') {
       continue;
     }
     // skip if part of long file name or volume label in root
     if (!isFileOrSubdir(dir)) {
       continue;
     }
     if (!f.open(this, index, O_RDONLY)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (f.isSubDir()) {
       // recursively delete
       if (!f.rmRfStar()) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     } else {
       // ignore read-only
       f.m_flags |= FILE_FLAG_WRITE;
       if (!f.remove()) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     // position to next entry if required
     if (m_curPosition != (32UL*(index + 1))) {
       if (!seekSet(32UL*(index + 1))) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   }
   // don't try to delete root
   if (!isRoot()) {
     if (!rmdir()) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FAT_NAME_DELETED, FAT_NAME_FREE, FILE_FLAG_WRITE, FS_DIR_SIZE, getError(), isDir(), isFileOrSubdir(), isRoot(), isSubDir(), m_curPosition, m_flags, DirFat_t::name, O_RDONLY, open(), readDirCache(), remove(), rewind(), rmdir(), rmRfStar(), and seekSet().
Referenced by rmRfStar().
seekCur()
bool FatFile::seekCur (int32_t offset) inline
Set the files position to current position + pos. See seekSet().
Parameters
[in] offset The new position in bytes from the current position.
Returns
true for success or false for failure.
Definition at line 831 of file FatFile.h.
{
     return seekSet(m_curPosition + offset);
   }
References m_curPosition, and seekSet().
seekEnd()
bool FatFile::seekEnd (int32_t offset = 0) inline
Set the files position to end-of-file + offset. See seekSet(). Can't be used for directory files since file size is not defined.
Parameters
[in] offset The new position in bytes from end-of-file.
Returns
true for success or false for failure.
Definition at line 839 of file FatFile.h.
{
     return isFile() ? seekSet(m_fileSize + offset) : false;
   }
References isFile(), m_fileSize, and seekSet().
seekSet()
bool FatFile::seekSet (uint32_t pos)
Sets a file's position.
Parameters
[in] pos The new position in bytes from the beginning of the file.
Returns
true for success or false for failure.
Definition at line 1132 of file FatFile.cpp.
{
   uint32_t nCur;
   uint32_t nNew;
   uint32_t tmp = m_curCluster;
   // error if file not open
   if (!isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Optimize O_APPEND writes.
   if (pos == m_curPosition) {
     return true;
   }
   if (pos == 0) {
     // set position to start of file
     m_curCluster = 0;
     goto done;
   }
   if (isFile()) {
     if (pos > m_fileSize) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } else if (isRootFixed()) {
     if (pos <= FS_DIR_SIZE*m_vol->rootDirEntryCount()) {
       goto done;
     }
     DBG_FAIL_MACRO;
     goto fail;
   }
   // calculate cluster index for new position
   nNew = (pos - 1) >> (m_vol->bytesPerClusterShift());
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
   if (isContiguous()) {
     m_curCluster = m_firstCluster + nNew;
     goto done;
   }
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
   // calculate cluster index for current position
   nCur = (m_curPosition - 1) >> (m_vol->bytesPerClusterShift());
   if (nNew < nCur || m_curPosition == 0) {
     // must follow chain from first cluster
     m_curCluster = isRoot32() ? m_vol->rootDirStart() : m_firstCluster;
   } else {
     // advance from curPosition
     nNew -= nCur;
   }
   while (nNew--) {
     if (m_vol->fatGet(m_curCluster, &m_curCluster) <= 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
  done:
   m_curPosition = pos;
   m_flags &= ~FILE_FLAG_PREALLOCATE;
   return true;
  fail:
   m_curCluster = tmp;
   return false;
 }
References FatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, FatPartition::fatGet(), FILE_FLAG_PREALLOCATE, isFile(), isOpen(), isRoot32(), isRootFixed(), m_curCluster, m_curPosition, m_fileSize, m_firstCluster, m_flags, m_vol, and FatPartition::rootDirStart().
Referenced by cacheDir(), dmpFile(), open(), openCachedEntry(), rewind(), rmRfStar(), seekCur(), seekEnd(), truncate(), and write().
sync()
bool FatFile::sync ()
The sync() call causes all modified data and directory fields to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 1197 of file FatFile.cpp.
                    {
   uint16_t date, time;
   uint8_t ms10;
   if (!isOpen()) {
     return true;
   }
   if (m_flags & FILE_FLAG_DIR_DIRTY) {
     DirFat_t* dir = cacheDirEntry(FsCache::CACHE_FOR_WRITE);
     // check for deleted by another open file object
     if (!dir || dir->name[0] == FAT_NAME_DELETED) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // do not set filesize for dir files
     if (isFile()) {
       setLe32(dir->fileSize, m_fileSize);
     }
     // update first cluster fields
     setLe16(dir->firstClusterLow, m_firstCluster & 0XFFFF);
     setLe16(dir->firstClusterHigh, m_firstCluster >> 16);
     // set modify time if user supplied a callback date/time function
     if (FsDateTime::callback) {
       FsDateTime::callback(&date, &time, &ms10);
       setLe16(dir->modifyDate, date);
       setLe16(dir->accessDate, date);
       setLe16(dir->modifyTime, time);
     }
     // clear directory dirty
     m_flags &= ~FILE_FLAG_DIR_DIRTY;
   }
   if (m_vol->cacheSync()) {
     return true;
   }
   DBG_FAIL_MACRO;
  fail:
   m_error |= WRITE_ERROR;
   return false;
 }
References DirFat_t::accessDate, FsCache::CACHE_FOR_WRITE, cacheDirEntry(), FatPartition::cacheSync(), FsDateTime::callback, DBG_FAIL_MACRO, FAT_NAME_DELETED, FILE_FLAG_DIR_DIRTY, DirFat_t::fileSize, DirFat_t::firstClusterHigh, DirFat_t::firstClusterLow, isFile(), isOpen(), m_error, m_fileSize, m_firstCluster, m_flags, m_vol, DirFat_t::modifyDate, DirFat_t::modifyTime, DirFat_t::name, setLe16(), setLe32(), and WRITE_ERROR.
Referenced by close(), dirEntry(), flush(), mkdir(), preAllocate(), rename(), timestamp(), and truncate().
timestamp()
bool FatFile::timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
Set a file's timestamps in its directory entry.
Parameters
[in] flags Values for flags are constructed by a bitwise-inclusive OR of flags from the following list
T_ACCESS - Set the file's last access date.
T_CREATE - Set the file's creation date and time.
T_WRITE - Set the file's last write/modification date and time.
Parameters
[in] year Valid range 1980 - 2107 inclusive.
[in] month Valid range 1 - 12 inclusive.
[in] day Valid range 1 - 31 inclusive.
[in] hour Valid range 0 - 23 inclusive.
[in] minute Valid range 0 - 59 inclusive.
[in] second Valid range 0 - 59 inclusive
Note
It is possible to set an invalid date since there is no check for the number of days in a month.
Modify and access timestamps may be overwritten if a date time callback function has been set by dateTimeCallback().
Returns
true for success or false for failure.
Definition at line 1238 of file FatFile.cpp.
{
   uint16_t dirDate;
   uint16_t dirTime;
   DirFat_t* dir;
   if (!isFile()
       || year < 1980
       || year > 2107
       || month < 1
       || month > 12
       || day < 1
       || day > 31
       || hour > 23
       || minute > 59
       || second > 59) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // update directory entry
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   dir = cacheDirEntry(FsCache::CACHE_FOR_WRITE);
   if (!dir) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   dirDate = FS_DATE(year, month, day);
   dirTime = FS_TIME(hour, minute, second);
   if (flags & T_ACCESS) {
     setLe16(dir->accessDate, dirDate);
   }
   if (flags & T_CREATE) {
     setLe16(dir->createDate, dirDate);
     setLe16(dir->createTime, dirTime);
     // units of 10 ms
     dir->createTimeMs = second & 1 ? 100 : 0;
   }
   if (flags & T_WRITE) {
     setLe16(dir->modifyDate, dirDate);
     setLe16(dir->modifyTime, dirTime);
   }
   return m_vol->cacheSync();
  fail:
   return false;
 }
References DirFat_t::accessDate, FsCache::CACHE_FOR_WRITE, cacheDirEntry(), FatPartition::cacheSync(), DirFat_t::createDate, DirFat_t::createTime, DirFat_t::createTimeMs, DBG_FAIL_MACRO, FS_DATE(), FS_TIME(), isFile(), m_vol, DirFat_t::modifyDate, DirFat_t::modifyTime, setLe16(), sync(), T_ACCESS, T_CREATE, and T_WRITE.
truncate() [1/2]
bool FatFile::truncate ()
Truncate a file at the current file position. will be maintained if it is less than or equal to length otherwise it will be set to end of file.
Returns
true for success or false for failure.
Definition at line 1288 of file FatFile.cpp.
{
   uint32_t toFree;
   // error if not a normal file or read-only
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (m_firstCluster == 0) {
       return true;
   }
   if (m_curCluster) {
     toFree = 0;
     int8_t fg = m_vol->fatGet(m_curCluster, &toFree);
     if (fg < 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (fg) {
       // current cluster is end of chain
       if (!m_vol->fatPutEOC(m_curCluster)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   } else {
     toFree = m_firstCluster;
     m_firstCluster = 0;
   }
   if (toFree) {
     if (!m_vol->freeChain(toFree)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   m_fileSize = m_curPosition;
   // need to update directory entry
   m_flags |= FILE_FLAG_DIR_DIRTY;
   return sync();
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FatPartition::fatGet(), FatPartition::fatPutEOC(), FILE_FLAG_DIR_DIRTY, FatPartition::freeChain(), isWritable(), m_curCluster, m_curPosition, m_fileSize, m_firstCluster, m_flags, m_vol, and sync().
Referenced by FatVolume::truncate(), and truncate().
truncate() [2/2]
bool FatFile::truncate (uint32_t length) inline
Truncate a file to a specified length. The current file position will be set to end of file.
Parameters
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 904 of file FatFile.h.
{
     return seekSet(length) && truncate();
   }
References seekSet(), and truncate().
write() [1/3]
size_t FatFile::write (const char * str) inline
Write a string to a file. Used by the Arduino Print class.
Parameters
[in] str Pointer to the string. Use getWriteError to check for errors.
Returns
count of characters written for success or -1 for failure.
Definition at line 912 of file FatFile.h.
{
     return write(str, strlen(str));
   }
Referenced by printField(), and write().
write() [2/3]
size_t FatFile::write (const void * buf, size_t count)
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buf Pointer to the location of the data to be written.
[in] count Number of bytes to write.
Returns
For success write() returns the number of bytes written, always count. If an error occurs, write() returns zero and writeError is set.
Definition at line 1332 of file FatFile.cpp.
{
   // convert void* to uint8_t*  -  must be before goto statements
   const uint8_t* src = reinterpret_cast<const uint8_t*>(buf);
   uint8_t* pc;
   uint8_t cacheOption;
   // number of bytes left to write  -  must be before goto statements
   size_t nToWrite = nbyte;
   size_t n;
   // error if not a normal file or is read-only
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // seek to end of file if append flag
   if ((m_flags & FILE_FLAG_APPEND)) {
     if (!seekSet(m_fileSize)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   // Don't exceed max fileSize.
   if (nbyte > (0XFFFFFFFF - m_curPosition)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   while (nToWrite) {
     uint8_t sectorOfCluster = m_vol->sectorOfCluster(m_curPosition);
     uint16_t sectorOffset = m_curPosition & m_vol->sectorMask();
     if (sectorOfCluster == 0 && sectorOffset == 0) {
       // start of new cluster
       if (m_curCluster != 0) {
 #if USE_FAT_FILE_FLAG_CONTIGUOUS
         int8_t fg;
         if (isContiguous() && m_fileSize > m_curPosition) {
           m_curCluster++;
           fg = 1;
         } else {
           fg = m_vol->fatGet(m_curCluster, &m_curCluster);
           if (fg < 0) {
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
 #else  // USE_FAT_FILE_FLAG_CONTIGUOUS
         int8_t fg = m_vol->fatGet(m_curCluster, &m_curCluster);
         if (fg < 0) {
           DBG_FAIL_MACRO;
           goto fail;
         }
 #endif  // USE_FAT_FILE_FLAG_CONTIGUOUS
         if (fg == 0) {
           // add cluster if at end of chain
           if (!addCluster()) {
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
       } else {
         if (m_firstCluster == 0) {
           // allocate first cluster of file
           if (!addCluster()) {
             DBG_FAIL_MACRO;
             goto fail;
           }
           m_firstCluster = m_curCluster;
         } else {
           m_curCluster = m_firstCluster;
         }
       }
     }
     // sector for data write
     uint32_t sector = m_vol->clusterStartSector(m_curCluster)
                       + sectorOfCluster;
     if (sectorOffset != 0 || nToWrite < m_vol->bytesPerSector()) {
       // partial sector - must use cache
       // max space in sector
       n = m_vol->bytesPerSector() - sectorOffset;
       // lesser of space and amount to write
       if (n > nToWrite) {
         n = nToWrite;
       }
       if (sectorOffset == 0 &&
          (m_curPosition >= m_fileSize || m_flags & FILE_FLAG_PREALLOCATE)) {
         // start of new sector don't need to read into cache
         cacheOption = FsCache::CACHE_RESERVE_FOR_WRITE;
       } else {
         // rewrite part of sector
         cacheOption = FsCache::CACHE_FOR_WRITE;
       }
       pc = m_vol->dataCachePrepare(sector, cacheOption);
       if (!pc) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       uint8_t* dst = pc + sectorOffset;
       memcpy(dst, src, n);
       if (m_vol->bytesPerSector() == (n + sectorOffset)) {
         // Force write if sector is full - improves large writes.
         if (!m_vol->cacheSyncData()) {
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
 #if USE_MULTI_SECTOR_IO
     } else if (nToWrite >= 2*m_vol->bytesPerSector()) {
       // use multiple sector write command
       uint32_t maxSectors = m_vol->sectorsPerCluster() - sectorOfCluster;
       uint32_t nSector = nToWrite >> m_vol->bytesPerSectorShift();
       if (nSector > maxSectors) {
         nSector = maxSectors;
       }
       n = nSector << m_vol->bytesPerSectorShift();
       if (!m_vol->cacheSafeWrite(sector, src, nSector)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
 #endif  // USE_MULTI_SECTOR_IO
     } else {
       // use single sector write command
       n = m_vol->bytesPerSector();
       if (!m_vol->cacheSafeWrite(sector, src)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_curPosition += n;
     src += n;
     nToWrite -= n;
   }
   if (m_curPosition > m_fileSize) {
     // update fileSize and insure sync will update dir entry
     m_fileSize = m_curPosition;
     m_flags |= FILE_FLAG_DIR_DIRTY;
   } else if (FsDateTime::callback) {
     // insure sync will update modified date and time
     m_flags |= FILE_FLAG_DIR_DIRTY;
   }
   return nbyte;
  fail:
   // return for write error
   m_error |= WRITE_ERROR;
   return 0;
 }
References addCluster(), buf, FatPartition::bytesPerSector(), FatPartition::bytesPerSectorShift(), FsCache::CACHE_FOR_WRITE, FsCache::CACHE_RESERVE_FOR_WRITE, FatPartition::cacheSafeWrite(), FatPartition::cacheSyncData(), FsDateTime::callback, FatPartition::clusterStartSector(), FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FatPartition::fatGet(), FILE_FLAG_APPEND, FILE_FLAG_DIR_DIRTY, FILE_FLAG_PREALLOCATE, isWritable(), m_curCluster, m_curPosition, m_error, m_fileSize, m_firstCluster, m_flags, m_vol, FatPartition::sectorMask(), FatPartition::sectorOfCluster(), FatPartition::sectorsPerCluster(), seekSet(), and WRITE_ERROR.
write() [3/3]
size_t FatFile::write (uint8_t b) inline
Write a single byte.
Parameters
[in] b The byte to be written.
Returns
+1 for success or -1 for failure.
Definition at line 919 of file FatFile.h.
{
     return write(&b, 1);
   }
References write().
Friends And Related Function Documentation
FatVolume
friend class FatVolume friend
FatVolume allowed access to private members.
Definition at line 964 of file FatFile.h.
Member Data Documentation
FILE_ATTR_CLOSED
const uint8_t FatFile::FILE_ATTR_CLOSED = 0 static private
This file has not been opened.
Definition at line 967 of file FatFile.h.
Referenced by close(), openCachedEntry(), remove(), and rename().
FILE_ATTR_COPY
const uint8_t FatFile::FILE_ATTR_COPY static private
Initial value:
=
                       FAT_ATTRIB_READ_ONLY | FAT_ATTRIB_HIDDEN |
                       FAT_ATTRIB_SYSTEM | FAT_ATTRIB_DIRECTORY
Attributes to copy from directory entry
Definition at line 988 of file FatFile.h.
Referenced by openCachedEntry(), and openSFN().
FILE_ATTR_DIR
const uint8_t FatFile::FILE_ATTR_DIR = FILE_ATTR_SUBDIR | FILE_ATTR_ROOT static private
Directory type bits
Definition at line 986 of file FatFile.h.
FILE_ATTR_FILE
const uint8_t FatFile::FILE_ATTR_FILE = 0X08 static private
Entry for normal data file
Definition at line 975 of file FatFile.h.
Referenced by isFile(), openCachedEntry(), openSFN(), rename(), and rmdir().
FILE_ATTR_HIDDEN
const uint8_t FatFile::FILE_ATTR_HIDDEN = FAT_ATTRIB_HIDDEN static private
File should be hidden in directory listings.
Definition at line 971 of file FatFile.h.
Referenced by isHidden().
FILE_ATTR_READ_ONLY
const uint8_t FatFile::FILE_ATTR_READ_ONLY = FAT_ATTRIB_READ_ONLY static private
File is read-only.
Definition at line 969 of file FatFile.h.
Referenced by isReadOnly().
FILE_ATTR_ROOT
const uint8_t FatFile::FILE_ATTR_ROOT static private
Initial value:
=
                       FILE_ATTR_ROOT_FIXED | FILE_ATTR_ROOT32
Entry is for root.
Definition at line 983 of file FatFile.h.
Referenced by isRoot().
FILE_ATTR_ROOT32
const uint8_t FatFile::FILE_ATTR_ROOT32 = 0X40 static private
A FAT32 root directory
Definition at line 981 of file FatFile.h.
Referenced by isRoot32(), and openRoot().
FILE_ATTR_ROOT_FIXED
const uint8_t FatFile::FILE_ATTR_ROOT_FIXED = 0X20 static private
A FAT12 or FAT16 root directory
Definition at line 979 of file FatFile.h.
Referenced by isRootFixed(), and openRoot().
FILE_ATTR_SUBDIR
const uint8_t FatFile::FILE_ATTR_SUBDIR = FAT_ATTRIB_DIRECTORY static private
Entry is for a subdirectory
Definition at line 977 of file FatFile.h.
Referenced by isSubDir(), mkdir(), and openCluster().
FILE_ATTR_SYSTEM
const uint8_t FatFile::FILE_ATTR_SYSTEM = FAT_ATTRIB_SYSTEM static private
Entry is for a system file.
Definition at line 973 of file FatFile.h.
Referenced by isSystem().
FILE_FLAG_APPEND
const uint8_t FatFile::FILE_FLAG_APPEND = 0X08 static private
Definition at line 1026 of file FatFile.h.
Referenced by openCachedEntry(), and write().
FILE_FLAG_CONTIGUOUS
const uint8_t FatFile::FILE_FLAG_CONTIGUOUS = 0X40 static private
Definition at line 1030 of file FatFile.h.
Referenced by addCluster(), contiguousRange(), and preAllocate().
FILE_FLAG_DIR_DIRTY
const uint8_t FatFile::FILE_FLAG_DIR_DIRTY = 0X80 static private
Definition at line 1032 of file FatFile.h.
Referenced by addCluster(), openCachedEntry(), preAllocate(), sync(), truncate(), and write().
FILE_FLAG_PREALLOCATE
const uint8_t FatFile::FILE_FLAG_PREALLOCATE = 0X20 static private
Definition at line 1028 of file FatFile.h.
Referenced by preAllocate(), seekSet(), and write().
FILE_FLAG_READ
const uint8_t FatFile::FILE_FLAG_READ = 0X01 static private
Definition at line 1024 of file FatFile.h.
Referenced by isReadable(), mkdir(), openCachedEntry(), openCluster(), openRoot(), and openSFN().
FILE_FLAG_WRITE
const uint8_t FatFile::FILE_FLAG_WRITE = 0X02 static private
Definition at line 1025 of file FatFile.h.
Referenced by isWritable(), openCachedEntry(), openSFN(), rename(), rmdir(), and rmRfStar().
m_attributes
uint8_t FatFile::m_attributes = FILE_ATTR_CLOSED private
Definition at line 1038 of file FatFile.h.
Referenced by close(), isFile(), isHidden(), isOpen(), isReadOnly(), isRoot(), isRoot32(), isRootFixed(), isSubDir(), isSystem(), mkdir(), openCachedEntry(), openCluster(), openRoot(), openSFN(), remove(), rename(), and rmdir().
m_curCluster
uint32_t FatFile::m_curCluster private
Definition at line 1045 of file FatFile.h.
Referenced by addCluster(), addDirCluster(), curCluster(), fgetpos(), fsetpos(), mkdir(), peek(), read(), seekSet(), truncate(), and write().
m_curPosition
uint32_t FatFile::m_curPosition private
Definition at line 1046 of file FatFile.h.
Referenced by addDirCluster(), curPosition(), fgetpos(), fsetpos(), openSFN(), peek(), read(), readDir(), readDirCache(), rmRfStar(), seekCur(), seekSet(), truncate(), and write().
m_dirCluster
uint32_t FatFile::m_dirCluster private
Definition at line 1044 of file FatFile.h.
Referenced by openCachedEntry(), openCluster(), openSFN(), and rename().
m_dirIndex
uint16_t FatFile::m_dirIndex private
Definition at line 1042 of file FatFile.h.
Referenced by cacheDirEntry(), dirIndex(), getName7(), getName8(), openCachedEntry(), openSFN(), printName7(), printName8(), and rename().
m_dirSector
uint32_t FatFile::m_dirSector private
Definition at line 1047 of file FatFile.h.
Referenced by cacheDirEntry(), openCachedEntry(), openSFN(), and rename().
m_error
uint8_t FatFile::m_error = 0 private
Definition at line 1039 of file FatFile.h.
Referenced by clearError(), clearWriteError(), getError(), getWriteError(), read(), sync(), and write().
m_fileSize
uint32_t FatFile::m_fileSize private
Definition at line 1048 of file FatFile.h.
Referenced by fileSize(), openCachedEntry(), openSFN(), preAllocate(), read(), seekEnd(), seekSet(), sync(), truncate(), and write().
m_firstCluster
uint32_t FatFile::m_firstCluster private
Definition at line 1049 of file FatFile.h.
Referenced by contiguousRange(), dirSize(), firstSector(), mkdir(), openCachedEntry(), openCluster(), openSFN(), preAllocate(), read(), remove(), rename(), seekSet(), sync(), truncate(), and write().
m_flags
uint8_t FatFile::m_flags = 0 private
Definition at line 1040 of file FatFile.h.
Referenced by addCluster(), close(), contiguousRange(), isReadable(), isWritable(), mkdir(), openCachedEntry(), openCluster(), openRoot(), openSFN(), preAllocate(), remove(), rename(), rmdir(), rmRfStar(), seekSet(), sync(), truncate(), and write().
m_lfnOrd
uint8_t FatFile::m_lfnOrd private
Definition at line 1041 of file FatFile.h.
Referenced by getName7(), getName8(), isLFN(), openCachedEntry(), openSFN(), printName7(), printName8(), and rename().
m_vol
FatVolume* FatFile::m_vol private
Definition at line 1043 of file FatFile.h.
Referenced by addCluster(), addDirCluster(), cacheDirEntry(), contiguousRange(), dirSize(), firstSector(), isBusy(), mkdir(), open(), openCachedEntry(), openCluster(), openRoot(), openSFN(), preAllocate(), read(), readDirCache(), remove(), rename(), seekSet(), sync(), timestamp(), truncate(), and write().
READ_ERROR
const uint8_t FatFile::READ_ERROR = 0X2 static private
Definition at line 1036 of file FatFile.h.
Referenced by read().
WRITE_ERROR
const uint8_t FatFile::WRITE_ERROR = 0X1 static private
Definition at line 1035 of file FatFile.h.
Referenced by clearWriteError(), getWriteError(), sync(), and write().
The documentation for this class was generated from the following files:
ERISCore/lib/SdFat-master/src/FatLib/FatFile.h
ERISCore/lib/SdFat-master/src/FatLib/FatDbg.cpp
ERISCore/lib/SdFat-master/src/FatLib/FatFile.cpp
ERISCore/lib/SdFat-master/src/FatLib/FatFilePrint.cpp
ERISCore/lib/SdFat-master/src/FatLib/FatFileSFN.cpp
ERISCore/lib/SdFat-master/src/FatLib/FatName.cpp