ERIS CORE: ifstream Class Reference
ifstream Class Reference
file input stream.
#include <fstream.h>
Public Types
typedef unsigned int fmtflags
typedef unsigned char iostate
typedef int64_t off_type
typedef uint8_t openmode
typedef uint64_t pos_type
enum seekdir { beg , cur , end }
typedef uint64_t streamsize
Public Member Functions
ifstream ()
ifstream (const char *path, openmode mode=in)
bool bad () const
void clear (iostate state=goodbit)
void close ()
bool eof () const
bool fail () const
char fill ()
char fill (char c)
fmtflags flags () const
fmtflags flags (fmtflags fl)
streamsize gcount () const
int get ()
istream & get (char &ch)
istream & get (char *str, streamsize n, char delim='\n')
istream & getline (char *str, streamsize n, char delim='\n')
bool good () const
istream & ignore (streamsize n=1, int delim=-1)
bool is_open ()
void open (const char *path, openmode mode=in)
operator bool () const
operator const void * () const
bool operator! () const
istream & operator>> (bool &arg)
istream & operator>> (char &ch)
istream & operator>> (char *str)
istream & operator>> (double &arg)
istream & operator>> (float &arg)
istream & operator>> (int &arg)
istream & operator>> (ios &(*pf)(ios &str))
istream & operator>> (ios_base &(*pf)(ios_base &str))
istream & operator>> (istream &(*pf)(istream &str))
istream & operator>> (long &arg)
istream & operator>> (short &arg)
istream & operator>> (signed char &ch)
istream & operator>> (signed char *str)
istream & operator>> (unsigned char &ch)
istream & operator>> (unsigned char *str)
istream & operator>> (unsigned int &arg)
istream & operator>> (unsigned long &arg)
istream & operator>> (unsigned short &arg)
istream & operator>> (void *&arg)
int peek ()
int precision () const
int precision (unsigned int n)
iostate rdstate () const
istream & seekg (off_type off, seekdir way)
istream & seekg (pos_type pos)
fmtflags setf (fmtflags fl)
fmtflags setf (fmtflags fl, fmtflags mask)
void setstate (iostate state)
void skipWhite ()
pos_type tellg ()
void unsetf (fmtflags fl)
unsigned width ()
unsigned width (unsigned n)
Static Public Attributes
static const fmtflags adjustfield = left | right | internal
static const openmode app = 0X4
static const openmode ate = 0X8
static const iostate badbit = 0X01
static const fmtflags basefield = dec | hex | oct
static const openmode binary = 0X10
static const fmtflags boolalpha = 0x0100
static const fmtflags dec = 0x0008
static const iostate eofbit = 0x02
static const iostate failbit = 0X04
static const iostate goodbit = 0x00
static const fmtflags hex = 0x0010
static const openmode in = 0X20
static const fmtflags internal = 0x0004
static const fmtflags left = 0x0001
static const fmtflags oct = 0x0020
static const openmode out = 0X40
static const fmtflags right = 0x0002
static const fmtflags showbase = 0x0200
static const fmtflags showpoint = 0x0400
static const fmtflags showpos = 0x0800
static const fmtflags skipws = 0x1000
static const openmode trunc = 0X80
static const fmtflags uppercase = 0x4000
Protected Member Functions
uint8_t flagsToBase ()
Private Member Functions
void clearWriteError ()
void getBool (bool *b)
int16_t getch ()
void getChar (char *ch)
bool getDouble (double *value)
ios::openmode getmode ()
template<typename T >
void getNumber (T *value)
bool getNumber (uint32_t posMax, uint32_t negMax, uint32_t *num)
void getStr (char *str)
bool getWriteError ()
void putch (char c)
void putstr (const char *str)
int16_t readSkip ()
bool seekoff (off_type off, seekdir way)
bool seekpos (pos_type pos)
void setmode (ios::openmode mode)
void write (char c)
int write (const void *buf, size_t n)
Private Attributes
char m_fill
fmtflags m_fmtflags
size_t m_gcount
iostate m_iostate = 0
ios::openmode m_mode
unsigned char m_precision
unsigned int m_width
Detailed Description
file input stream.
Definition at line 190 of file fstream.h.
Member Typedef Documentation
fmtflags
typedef unsigned int ios_base::fmtflags inherited
type for format flags
Definition at line 94 of file ios.h.
iostate
typedef unsigned char ios_base::iostate inherited
typedef for iostate bitmask
Definition at line 53 of file ios.h.
off_type
typedef int64_t ios_base::off_type inherited
type for relative seek offset
Definition at line 82 of file ios.h.
openmode
typedef uint8_t ios_base::openmode inherited
typedef for iostream open mode
Definition at line 129 of file ios.h.
pos_type
typedef uint64_t ios_base::pos_type inherited
type for absolute seek position
Definition at line 80 of file ios.h.
streamsize
typedef uint64_t ios_base::streamsize inherited
unsigned size that can represent maximum file size. (violates spec - should be signed)
Definition at line 78 of file ios.h.
Member Enumeration Documentation
seekdir
enum ios_base::seekdir inherited
enumerated type for the direction of relative seeks
Enumerator
beg
seek relative to the beginning of the stream
cur
seek relative to the current stream position
end
seek relative to the end of the stream
Definition at line 85 of file ios.h.
                {
     beg,
     cur,
     end
   };
Constructor & Destructor Documentation
ifstream() [1/2]
ifstream::ifstream () inline
Definition at line 193 of file fstream.h.
 {}
ifstream() [2/2]
ifstream::ifstream (const char * path, openmode mode = in) inline explicit
Constructor with open
Parameters
[in] path file to open
[in] mode open mode
Definition at line 198 of file fstream.h.
{
     open(path, mode);
   }
References mode, and open().
Member Function Documentation
bad()
bool ios::bad () const inline inherited
Returns
true if bad bit is set else false.
Definition at line 427 of file ios.h.
                    {
     return m_iostate & badbit;
   }
References ios_base::badbit, and ios::m_iostate.
Referenced by istream::peek().
clear()
void ios::clear (iostate state = goodbit) inline inherited
Clear iostate bits.
Parameters
[in] state The flags you want to set after clearing all flags.
Definition at line 434 of file ios.h.
{
     m_iostate = state;
   }
References ios::m_iostate.
Referenced by ibufstream::init(), and StreamBaseClass::open().
clearWriteError()
void StreamBaseClass::clearWriteError () inline protected inherited
Definition at line 39 of file fstream.h.
{
     StreamBaseFile::clearWriteError();
   }
Referenced by StreamBaseClass::open().
close()
void ifstream::close () inline
Close a file and force cached data and directory information to be written to the storage device.
Definition at line 207 of file fstream.h.
                {
     StreamBaseClass::close();
   }
eof()
bool ios::eof () const inline inherited
Returns
true if end of file has been reached else false.
Warning: An empty file returns false before the first read.
Moral: eof() is only useful in combination with fail(), to find out whether EOF was the cause for failure
Definition at line 419 of file ios.h.
                    {
     return m_iostate & eofbit;
   }
References ios_base::eofbit, and ios::m_iostate.
fail()
bool ios::fail () const inline inherited
Returns
true if any iostate bit other than eof are set else false.
Definition at line 423 of file ios.h.
                     {
     return m_iostate & (failbit | badbit);
   }
References ios_base::badbit, ios_base::failbit, and ios::m_iostate.
Referenced by istream::getDouble(), StreamBaseClass::open(), ios::operator bool(), ios::operator const void *(), and ios::operator!().
fill() [1/2]
char ios_base::fill () inline inherited
Returns
fill character
Definition at line 148 of file ios.h.
               {
     return m_fill;
   }
Referenced by ostream::do_fill(), operator<<(), and operator>>().
fill() [2/2]
char ios_base::fill (char c) inline inherited
Set fill character
Parameters
[in] c new fill character
Returns
old fill character
Definition at line 155 of file ios.h.
                     {
     char r = m_fill;
     m_fill = c;
     return r;
   }
flags() [1/2]
fmtflags ios_base::flags () const inline inherited
Returns
format flags
Definition at line 161 of file ios.h.
{
     return m_fmtflags;
   }
Referenced by ostream::fill_not_left(), istream::getBool(), istream::getNumber(), ostream::putBool(), ostream::putDouble(), and istream::readSkip().
flags() [2/2]
fmtflags ios_base::flags (fmtflags fl) inline inherited
set format flags
Parameters
[in] fl new flag
Returns
old flags
Definition at line 168 of file ios.h.
{
     fmtflags tmp = m_fmtflags;
     m_fmtflags = fl;
     return tmp;
   }
flagsToBase()
uint8_t ios_base::flagsToBase () inline protected inherited
Returns
current number base
Definition at line 228 of file ios.h.
{
     uint8_t f = flags() & basefield;
     return f == oct ? 8 : f != hex ? 10 : 16;
   }
References hex(), and oct().
Referenced by ostream::putNum().
gcount()
streamsize istream::gcount () const inline inherited
Returns
The number of characters extracted by the last unformatted input function.
Definition at line 215 of file istream.h.
{
     return m_gcount;
   }
References istream::m_gcount.
get() [1/3]
int istream::get () inherited
Extract a character if one is available.
Returns
The character or -1 if a failure occurs. A failure is indicated by the stream state.
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 29 of file istream.cpp.
                  {
   int c;
   m_gcount = 0;
   c = getch();
   if (c < 0) {
     setstate(failbit);
   } else {
     m_gcount = 1;
   }
   return c;
 }
References ios_base::failbit, istream::m_gcount, and ios::setstate().
Referenced by istream::get().
get() [2/3]
istream & istream::get (char & ch) inherited
Extract a character if one is available.
Parameters
[out] ch location to receive the extracted character.
Returns
always returns *this. A failure is indicated by the stream state.
Definition at line 41 of file istream.cpp.
{
   int tmp = get();
   if (tmp >= 0) {
     c = tmp;
   }
   return *this;
 }
References istream::get().
get() [3/3]
istream & istream::get (char * str, streamsize n, char delim = '\n') inherited
Extract characters.
Parameters
[out] str Location to receive extracted characters.
[in] n Size of str.
[in] delim Delimiter
Characters are extracted until extraction fails, n is less than 1, n-1 characters are extracted, or the next character equals delim (delim is not extracted). If no characters are extracted failbit is set. If end-of-file occurs the eofbit is set.
Returns
always returns *this. A failure is indicated by the stream state.
Definition at line 49 of file istream.cpp.
{
   int c;
   pos_t pos;
   m_gcount = 0;
   while ((m_gcount + 1)  < n) {
     c = getch(&pos);
     if (c < 0) {
       break;
     }
     if (c == delim) {
       setpos(&pos);
       break;
     }
     str[m_gcount++] = c;
   }
   if (n > 0) {
     str[m_gcount] = '\0';
   }
   if (m_gcount == 0) {
     setstate(failbit);
   }
   return *this;
 }
References ios_base::failbit, istream::m_gcount, and ios::setstate().
getBool()
void istream::getBool (bool * b) private inherited
Definition at line 73 of file istream.cpp.
{
   if ((flags() & boolalpha) == 0) {
     getNumber(b);
     return;
   }
 #ifdef __AVR__
   PGM_P truePtr = PSTR("true");
   PGM_P falsePtr = PSTR("false");
 #else  // __AVR__
   const char* truePtr = "true";
   const char* falsePtr = "false";
 #endif  // __AVR
   const uint8_t true_len = 4;
   const uint8_t false_len = 5;
   bool trueOk = true;
   bool falseOk = true;
   uint8_t i = 0;
   int c = readSkip();
   while (1) {
 #ifdef __AVR__
     falseOk = falseOk && c == pgm_read_byte(falsePtr + i);
     trueOk = trueOk && c == pgm_read_byte(truePtr + i);
 #else  // __AVR__
     falseOk = falseOk && c == falsePtr[i];
     trueOk = trueOk && c == truePtr[i];
 #endif  // __AVR__
     if (trueOk == false && falseOk == false) {
       break;
     }
     i++;
     if (trueOk && i == true_len) {
       *b = true;
       return;
     }
     if (falseOk && i == false_len) {
       *b = false;
       return;
     }
     c = getch();
   }
   setstate(failbit);
 }
References ios_base::boolalpha, ios_base::failbit, ios_base::flags(), istream::getNumber(), pgm_read_byte, PSTR, istream::readSkip(), and ios::setstate().
Referenced by istream::operator>>().
getch()
int16_t StreamBaseClass::getch () protected inherited
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 27 of file StreamBaseClass.cpp.
{
   uint8_t c;
   int8_t s = StreamBaseFile::read(&c, 1);
   if (s != 1) {
     if (s < 0) {
       setstate(badbit);
     } else {
       setstate(eofbit);
     }
     return -1;
   }
   if (c != '\r' || (getmode() & ios::binary)) {
     return c;
   }
   s = StreamBaseFile::read(&c, 1);
   if (s == 1 && c == '\n') {
     return c;
   }
   if (s == 1) {
     StreamBaseFile::seekCur(-1);
   }
   return '\r';
 }
References ios_base::badbit, ios_base::binary, ios_base::eofbit, StreamBaseClass::getmode(), read, s, and ios::setstate().
getChar()
void istream::getChar (char * ch) private inherited
Definition at line 116 of file istream.cpp.
{
   int16_t c = readSkip();
   if (c < 0) {
     setstate(failbit);
   } else {
     *ch = c;
   }
 }
References ios_base::failbit, istream::readSkip(), and ios::setstate().
Referenced by istream::operator>>().
getDouble()
bool istream::getDouble (double * value) private inherited
Definition at line 130 of file istream.cpp.
{
   bool got_digit = false;
   bool got_dot = false;
   bool neg;
   int16_t c;
   bool expNeg = false;
   int16_t exp = 0;
   int16_t fracExp = 0;
   uint32_t frac = 0;
   pos_t endPos;
   double pow10;
   double v;
   getpos(&endPos);
   c = readSkip();
   neg = c == '-';
   if (c == '-' || c == '+') {
     c = getch();
   }
   while (1) {
     if (isdigit(c)) {
       got_digit = true;
       if (frac < uint32_max/10) {
         frac = frac * 10 + (c  - '0');
         if (got_dot) {
           fracExp--;
         }
       } else {
         if (!got_dot) {
           fracExp++;
         }
       }
     } else if (!got_dot && c == '.') {
       got_dot = true;
     } else {
       break;
     }
     if (fracExp < -EXP_LIMIT || fracExp > EXP_LIMIT) {
       goto fail;
     }
     c = getch(&endPos);
   }
   if (!got_digit) {
     goto fail;
   }
   if (c == 'e' || c == 'E') {
     c = getch();
     expNeg = c == '-';
     if (c == '-' || c == '+') {
       c = getch();
     }
     while (isdigit(c)) {
       if (exp > EXP_LIMIT) {
         goto fail;
       }
       exp = exp * 10 + (c - '0');
       c = getch(&endPos);
     }
   }
   v = static_cast<double>(frac);
   exp = expNeg ? fracExp - exp : fracExp + exp;
   expNeg = exp < 0;
   if (expNeg) {
     exp = -exp;
   }
   pow10 = 10.0;
   while (exp) {
     if (exp & 1) {
       if (expNeg) {
         // check for underflow
         if (v < DBL_MIN * pow10  && frac != 0) {
           goto fail;
         }
         v /= pow10;
       } else {
         // check for overflow
         if (v > DBL_MAX / pow10) {
           goto fail;
         }
         v *= pow10;
       }
     }
     pow10 *= pow10;
     exp >>= 1;
   }
   setpos(&endPos);
   *value = neg ? -v : v;
   return true;
  fail:
   // error restore position to last good place
   setpos(&endPos);
   setstate(failbit);
   return false;
 }
References EXP_LIMIT, ios::fail(), ios_base::failbit, istream::readSkip(), ios::setstate(), and uint32_max.
Referenced by istream::operator>>().
getline()
istream & istream::getline (char * str, streamsize n, char delim = '\n') inherited
Extract characters
Parameters
[out] str Location to receive extracted characters.
[in] n Size of str.
[in] delim Delimiter
Characters are extracted until extraction fails, the next character equals delim (delim is extracted), or n-1 characters are extracted.
The failbit is set if no characters are extracted or n-1 characters are extracted. If end-of-file occurs the eofbit is set.
Returns
always returns *this. A failure is indicated by the stream state.
Definition at line 227 of file istream.cpp.
{
   pos_t pos;
   int c;
   m_gcount = 0;
   if (n > 0) {
     str[0] = '\0';
   }
   while (1) {
     c = getch(&pos);
     if (c < 0) {
       break;
     }
     if (c == delim) {
       m_gcount++;
       break;
     }
     if ((m_gcount + 1)  >=  n) {
       setpos(&pos);
       setstate(failbit);
       break;
     }
     str[m_gcount++] = c;
     str[m_gcount] = '\0';
   }
   if (m_gcount == 0) {
     setstate(failbit);
   }
   return *this;
 }
References ios_base::failbit, istream::m_gcount, and ios::setstate().
getmode()
ios::openmode StreamBaseClass::getmode () inline protected inherited
Internal do not use
Returns
mode
Definition at line 53 of file fstream.h.
{
     return m_mode;
   }
References StreamBaseClass::m_mode.
Referenced by StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
getNumber() [1/2]
template<typename T > void istream::getNumber (T * value) private inherited
Definition at line 367 of file istream.h.
{
   uint32_t tmp;
   if ((T)-1 < 0) {
     // number is signed, max positive value
     uint32_t const m = ((uint32_t)-1) >> (33 - sizeof(T) * 8);
     // max absolute value of negative number is m + 1.
     if (getNumber(m, m + 1, &tmp)) {
       *value = (T)tmp;
     }
   } else {
     // max unsigned value for T
     uint32_t const m = (T)-1;
     if (getNumber(m, m, &tmp)) {
       *value = (T)tmp;
     }
   }
 }
References m.
Referenced by istream::getBool(), and istream::operator>>().
getNumber() [2/2]
bool istream::getNumber (uint32_t posMax, uint32_t negMax, uint32_t * num) private inherited
Definition at line 257 of file istream.cpp.
{
   int16_t c;
   int8_t any = 0;
   int8_t have_zero = 0;
   uint8_t neg;
   uint32_t val = 0;
   uint32_t cutoff;
   uint8_t cutlim;
   pos_t endPos;
   uint8_t f = flags() & basefield;
   uint8_t base = f == oct ? 8 : f != hex ? 10 : 16;
   getpos(&endPos);
   c = readSkip();
   neg = c == '-' ? 1 : 0;
   if (c == '-' || c == '+') {
     c = getch();
   }
   if (base == 16 && c == '0') {  // TESTSUITE
     c = getch(&endPos);
     if (c == 'X' || c == 'x') {
       c = getch();
       // remember zero in case no hex digits follow x/X
       have_zero = 1;
     } else {
       any = 1;
     }
   }
   // set values for overflow test
   cutoff = neg ? negMax : posMax;
   cutlim = cutoff % base;
   cutoff /= base;
   while (1) {
     if (isdigit(c)) {
       c -= '0';
     } else if (isalpha(c)) {
       c -= isupper(c) ? 'A' - 10 : 'a' - 10;
     } else {
       break;
     }
     if (c >= base) {
       break;
     }
     if (val > cutoff || (val == cutoff && c > cutlim)) {
       // indicate overflow error
       any = -1;
       break;
     }
     val = val * base + c;
     c = getch(&endPos);
     any = 1;
   }
   setpos(&endPos);
   if (any > 0 || (have_zero && any >= 0)) {
     *num =  neg ? -val : val;
     return true;
   }
   setstate(failbit);
   return false;
 }
References ios_base::basefield, ios_base::flags(), ios_base::hex, ios_base::oct, and istream::readSkip().
getStr()
void istream::getStr (char * str) private inherited
Definition at line 320 of file istream.cpp.
{
   pos_t pos;
   uint16_t i = 0;
   uint16_t m = width() ? width() - 1 : 0XFFFE;
   if (m != 0) {
     getpos(&pos);
     int c = readSkip();
     while (i < m) {
       if (c < 0) {
         break;
       }
       if (isspace(c)) {
         setpos(&pos);
         break;
       }
       str[i++] = c;
       c = getch(&pos);
     }
   }
   str[i] = '\0';
   if (i == 0) {
     setstate(failbit);
   }
   width(0);
 }
References ios_base::failbit, m, istream::readSkip(), ios::setstate(), and ios_base::width().
Referenced by istream::operator>>().
getWriteError()
bool StreamBaseClass::getWriteError () inline protected inherited
Definition at line 46 of file fstream.h.
{
     return StreamBaseFile::getWriteError();
   }
Referenced by StreamBaseClass::putch(), and StreamBaseClass::putstr().
good()
bool ios::good () const inline inherited
Returns
True if no iostate flags are set else false.
Definition at line 409 of file ios.h.
                     {
     return m_iostate == goodbit;
   }
References ios_base::goodbit, and ios::m_iostate.
ignore()
istream & istream::ignore (streamsize n = 1, int delim = -1) inherited
Extract characters and discard them.
Parameters
[in] n maximum number of characters to ignore.
[in] delim Delimiter.
Characters are extracted until extraction fails, n characters are extracted, or the next input character equals delim (the delimiter is extracted). If end-of-file occurs the eofbit is set.
Failures are indicated by the state of the stream.
Returns
*this
Definition at line 347 of file istream.cpp.
{
   int c;
   m_gcount = 0;
   while (m_gcount < n) {
     c = getch();
     if (c < 0) {
       break;
     }
     m_gcount++;
     if (c == delim) {
       break;
     }
   }
   return *this;
 }
References istream::m_gcount.
is_open()
bool ifstream::is_open () inline
Returns
True if stream is open else false.
Definition at line 211 of file fstream.h.
                  {
     return StreamBaseFile::isOpen();
   }
open()
void ifstream::open (const char * path, openmode mode = in) inline
Open an ifstream
Parameters
[in] path file to open
[in] mode open mode
mode See fstream::open() for valid modes.
Definition at line 220 of file fstream.h.
{
     StreamBaseClass::open(path, mode | in);
   }
References mode, and StreamBaseClass::open().
Referenced by ifstream().
operator bool()
ios::operator bool () const inline explicit inherited
Returns
false if fail() else true.
Definition at line 403 of file ios.h.
 {return !fail();}
References ios::fail().
operator const void *()
ios::operator const void * () const inline inherited
Returns
null pointer if fail() is true.
Definition at line 395 of file ios.h.
{
     return !fail() ? reinterpret_cast<const void*>(this) : nullptr;
   }
References ios::fail().
operator!()
bool ios::operator! () const inline inherited
Returns
true if fail() else false.
Definition at line 399 of file ios.h.
{
     return fail();
   }
References ios::fail().
operator>>() [1/19]
istream& istream::operator>> (bool & arg) inline inherited
Extract a value of type bool.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 122 of file istream.h.
{
     getBool(&arg);
     return *this;
   }
References istream::getBool().
operator>>() [2/19]
istream& istream::operator>> (char & ch) inline inherited
Extract a character
Parameters
[out] ch location to store the character.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 77 of file istream.h.
{
     getChar(&ch);
     return *this;
   }
References istream::getChar().
operator>>() [3/19]
istream& istream::operator>> (char * str) inline inherited
Extract a character string
Parameters
[out] str location to store the string.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 68 of file istream.h.
{
     getStr(str);
     return *this;
   }
References istream::getStr().
operator>>() [4/19]
istream& istream::operator>> (double & arg) inline inherited
Extract a value of type double.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 185 of file istream.h.
{
     getDouble(&arg);
     return *this;
   }
References istream::getDouble().
operator>>() [5/19]
istream& istream::operator>> (float & arg) inline inherited
Extract a value of type float.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 194 of file istream.h.
{
     double v;
     getDouble(&v);
     arg = v;
     return *this;
   }
References istream::getDouble().
operator>>() [6/19]
istream& istream::operator>> (int & arg) inline inherited
Extract a value of type int.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 149 of file istream.h.
{
     getNumber(&arg);
     return *this;
   }
References istream::getNumber().
operator>>() [7/19]
istream& istream::operator>> (ios &(*)(ios &str) pf) inline inherited
call manipulator
Parameters
[in] pf function to call
Returns
the stream
Definition at line 59 of file istream.h.
{
     pf(*this);
     return *this;
   }
operator>>() [8/19]
istream& istream::operator>> (ios_base &(*)(ios_base &str) pf) inline inherited
call manipulator
Parameters
[in] pf function to call
Returns
the stream
Definition at line 51 of file istream.h.
{
     pf(*this);
     return *this;
   }
operator>>() [9/19]
istream& istream::operator>> (istream &(*)(istream &str) pf) inline inherited
call manipulator
Parameters
[in] pf function to call
Returns
the stream
Definition at line 44 of file istream.h.
{
     return pf(*this);
   }
operator>>() [10/19]
istream& istream::operator>> (long & arg) inline inherited
Extract a value of type long.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 167 of file istream.h.
                                  {  // NOLINT
     getNumber(&arg);
     return *this;
   }
References istream::getNumber().
operator>>() [11/19]
istream& istream::operator>> (short & arg) inline inherited
Extract a value of type short.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 131 of file istream.h.
                                   {  // NOLINT
     getNumber(&arg);
     return *this;
   }
References istream::getNumber().
operator>>() [12/19]
istream& istream::operator>> (signed char & ch) inline inherited
Extract a character
Parameters
[out] ch location to store the character.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 95 of file istream.h.
{
     getChar(reinterpret_cast<char*>(&ch));
     return *this;
   }
References istream::getChar().
operator>>() [13/19]
istream& istream::operator>> (signed char * str) inline inherited
Extract a character string
Parameters
[out] str location to store the string.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 86 of file istream.h.
{
     getStr(reinterpret_cast<char*>(str));
     return *this;
   }
References istream::getStr().
operator>>() [14/19]
istream& istream::operator>> (unsigned char & ch) inline inherited
Extract a character
Parameters
[out] ch location to store the character.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 113 of file istream.h.
{
     getChar(reinterpret_cast<char*>(&ch));
     return *this;
   }
References istream::getChar().
operator>>() [15/19]
istream& istream::operator>> (unsigned char * str) inline inherited
Extract a character string
Parameters
[out] str location to store the string.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 104 of file istream.h.
{
     getStr(reinterpret_cast<char*>(str));
     return *this;
   }
References istream::getStr().
operator>>() [16/19]
istream& istream::operator>> (unsigned int & arg) inline inherited
Extract a value of type unsigned int.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 158 of file istream.h.
{
     getNumber(&arg);
     return *this;
   }
References istream::getNumber().
operator>>() [17/19]
istream& istream::operator>> (unsigned long & arg) inline inherited
Extract a value of type unsigned long.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 176 of file istream.h.
                                           {  // NOLINT
     getNumber(&arg);
     return *this;
   }
References istream::getNumber().
operator>>() [18/19]
istream& istream::operator>> (unsigned short & arg) inline inherited
Extract a value of type unsigned short.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 140 of file istream.h.
                                            {  // NOLINT
     getNumber(&arg);
     return *this;
   }
References istream::getNumber().
operator>>() [19/19]
istream& istream::operator>> (void *& arg) inline inherited
Extract a value of type void*.
Parameters
[out] arg location to store the value.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 205 of file istream.h.
{
     uint32_t val;
     getNumber(&val);
     arg = reinterpret_cast<void*>(val);
     return *this;
   }
References istream::getNumber().
peek()
int istream::peek
Return the next available character without consuming it.
Returns
The character if the stream state is good else -1;
Definition at line 287 of file istream.cpp.
                   {
   int16_t c;
   pos_t pos;
   m_gcount = 0;
   getpos(&pos);
   c = getch();
   if (c < 0) {
     if (!bad()) {
       setstate(eofbit);
     }
   } else {
     setpos(&pos);
   }
   return c;
 }
precision() [1/2]
int ios_base::precision () const inline inherited
Returns
precision
Definition at line 174 of file ios.h.
{
     return m_precision;
   }
Referenced by operator<<(), and ostream::putDouble().
precision() [2/2]
int ios_base::precision (unsigned int n) inline inherited
set precision
Parameters
[in] n new precision
Returns
old precision
Definition at line 181 of file ios.h.
{
     int r = m_precision;
     m_precision = n;
     return r;
   }
putch()
void StreamBaseClass::putch (char c) protected inherited
Definition at line 101 of file StreamBaseClass.cpp.
{
   if (c == '\n' && !(getmode() & ios::binary)) {
     write('\r');
   }
   write(c);
   if (getWriteError()) {
     setstate(badbit);
   }
 }
References ios_base::badbit, ios_base::binary, StreamBaseClass::getmode(), StreamBaseClass::getWriteError(), ios::setstate(), and StreamBaseClass::write().
putstr()
void StreamBaseClass::putstr (const char * str) protected inherited
Definition at line 111 of file StreamBaseClass.cpp.
{
   size_t n = 0;
   while (1) {
     char c = str[n];
     if (c == '\0' || (c == '\n' && !(getmode() & ios::binary))) {
       if (n > 0) {
         write(str, n);
       }
       if (c == '\0') {
         break;
       }
       write('\r');
       str += n;
       n = 0;
     }
     n++;
   }
   if (getWriteError()) {
     setstate(badbit);
   }
 }
References ios_base::badbit, ios_base::binary, StreamBaseClass::getmode(), StreamBaseClass::getWriteError(), ios::setstate(), and StreamBaseClass::write().
rdstate()
iostate ios::rdstate () const inline inherited
Returns
The iostate flags for this file.
Definition at line 405 of file ios.h.
{
     return m_iostate;
   }
References ios::m_iostate.
readSkip()
int16_t istream::readSkip () private inherited
Definition at line 379 of file istream.cpp.
{
   int16_t c;
   do {
     c = getch();
   } while (isspace(c) && (flags() & skipws));
   return c;
 }
References ios_base::flags(), and ios_base::skipws.
Referenced by istream::getBool(), istream::getChar(), istream::getDouble(), istream::getNumber(), and istream::getStr().
seekg() [1/2]
istream& istream::seekg (off_type off, seekdir way) inline inherited
Set the stream position.
Parameters
[in] off An offset to move the read pointer relative to way. off is a signed 32-bit int so the offset is limited to +- 2GB.
[in] way One of ios::beg, ios::cur, or ios::end.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 315 of file istream.h.
{
     if (!seekoff(off, way)) {
       setstate(failbit);
     }
     return *this;
   }
References ios_base::failbit, and ios::setstate().
seekg() [2/2]
istream& istream::seekg (pos_type pos) inline inherited
Set the stream position
Parameters
[in] pos The absolute position in which to move the read pointer.
Returns
Is always *this. Failure is indicated by the state of *this.
Definition at line 301 of file istream.h.
{
     if (!seekpos(pos)) {
       setstate(failbit);
     }
     return *this;
   }
References ios_base::failbit, and ios::setstate().
seekoff()
bool StreamBaseClass::seekoff (off_type off, seekdir way) protected inherited
Definition at line 133 of file StreamBaseClass.cpp.
{
   pos_type pos;
   switch (way) {
   case beg:
     pos = off;
     break;
   case cur:
     pos = StreamBaseFile::curPosition() + off;
     break;
   case end:
     pos = StreamBaseFile::fileSize() + off;
     break;
   default:
     return false;
   }
   return seekpos(pos);
 }
References ios_base::beg, ios_base::cur, ios_base::end, and StreamBaseClass::seekpos().
seekpos()
bool StreamBaseClass::seekpos (pos_type pos) inline protected inherited
Internal do not use
Parameters
[in] pos
Definition at line 62 of file fstream.h.
{
     return StreamBaseFile::seekSet(pos);
   }
Referenced by StreamBaseClass::seekoff().
setf() [1/2]
fmtflags ios_base::setf (fmtflags fl) inline inherited
set format flags
Parameters
[in] fl new flags to be or'ed in
Returns
old flags
Definition at line 190 of file ios.h.
{
     fmtflags r = m_fmtflags;
     m_fmtflags |= fl;
     return r;
   }
Referenced by boolalpha(), dec(), hex(), internal(), left(), oct(), right(), showbase(), showpoint(), showpos(), skipws(), and uppercase().
setf() [2/2]
fmtflags ios_base::setf (fmtflags fl, fmtflags mask) inline inherited
modify format flags
Parameters
[in] mask flags to be removed
[in] fl flags to be set after mask bits have been cleared
Returns
old flags
Definition at line 200 of file ios.h.
{
     fmtflags r = m_fmtflags;
     m_fmtflags &= ~mask;
     m_fmtflags |= fl;
     return r;
   }
setmode()
void StreamBaseClass::setmode (ios::openmode mode) inline protected inherited
Internal do not use
Parameters
[in] mode
Definition at line 68 of file fstream.h.
{
     m_mode = mode;
   }
References StreamBaseClass::m_mode, and mode.
Referenced by StreamBaseClass::open().
setstate()
void ios::setstate (iostate state) inline inherited
Set iostate bits.
Parameters
[in] state Bitts to set.
Definition at line 441 of file ios.h.
{
     m_iostate |= state;
   }
References ios::m_iostate.
Referenced by istream::get(), istream::getBool(), StreamBaseClass::getch(), istream::getChar(), istream::getDouble(), istream::getline(), istream::getStr(), StreamBaseClass::open(), istream::peek(), StreamBaseClass::putch(), StreamBaseClass::putstr(), ArduinoInStream::readline(), and istream::seekg().
skipWhite()
void istream::skipWhite () inherited
used to implement ws()
Definition at line 388 of file istream.cpp.
{
   int c;
   pos_t pos;
   do {
     c = getch(&pos);
   } while (isspace(c));
   setpos(&pos);
 }
tellg()
pos_type istream::tellg () inline inherited
Returns
the stream position
Definition at line 293 of file istream.h.
                    {
     return tellpos();
   }
unsetf()
void ios_base::unsetf (fmtflags fl) inline inherited
clear format flags
Parameters
[in] fl flags to be cleared
Definition at line 209 of file ios.h.
{
     m_fmtflags &= ~fl;
   }
Referenced by noboolalpha(), noshowbase(), noshowpoint(), noshowpos(), noskipws(), and nouppercase().
width() [1/2]
unsigned ios_base::width () inline inherited
Returns
width
Definition at line 213 of file ios.h.
                    {
     return m_width;
   }
Referenced by ostream::do_fill(), istream::getStr(), and operator<<().
width() [2/2]
unsigned ios_base::width (unsigned n) inline inherited
set width
Parameters
[in] n new width
Returns
old width
Definition at line 220 of file ios.h.
{
     unsigned r = m_width;
     m_width = n;
     return r;
   }
write() [1/2]
void StreamBaseClass::write (char c) protected inherited
Definition at line 158 of file StreamBaseClass.cpp.
{
   StreamBaseFile::write(&c, 1);
 }
write() [2/2]
int StreamBaseClass::write (const void * buf, size_t n) protected inherited
Definition at line 154 of file StreamBaseClass.cpp.
{
   return StreamBaseFile::write(buf, n);
 }
References buf.
Referenced by StreamBaseClass::putch(), and StreamBaseClass::putstr().
Member Data Documentation
adjustfield
const fmtflags ios_base::adjustfield = left | right | internal static inherited
mask for adjustfield
Definition at line 123 of file ios.h.
Referenced by ostream::fill_not_left(), internal(), left(), ostream::putDouble(), and right().
app
const openmode ios_base::app = 0X4 static inherited
seek to end before each write
Definition at line 133 of file ios.h.
Referenced by StreamBaseClass::open().
ate
const openmode ios_base::ate = 0X8 static inherited
open and seek to end immediately after opening
Definition at line 135 of file ios.h.
Referenced by StreamBaseClass::open().
badbit
const iostate ios_base::badbit = 0X01 static inherited
iostate bad bit for a nonrecoverable error.
Definition at line 58 of file ios.h.
Referenced by ios::bad(), ios::fail(), StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
basefield
const fmtflags ios_base::basefield = dec | hex | oct static inherited
mask for basefield
Definition at line 125 of file ios.h.
Referenced by dec(), istream::getNumber(), hex(), and oct().
binary
const openmode ios_base::binary = 0X10 static inherited
perform input and output in binary mode (as opposed to text mode)
Definition at line 137 of file ios.h.
Referenced by StreamBaseClass::getch(), StreamBaseClass::putch(), and StreamBaseClass::putstr().
boolalpha
const fmtflags ios_base::boolalpha = 0x0100 static inherited
use strings true/false for bool
Definition at line 110 of file ios.h.
Referenced by boolalpha(), istream::getBool(), noboolalpha(), and ostream::putBool().
dec
const fmtflags ios_base::dec = 0x0008 static inherited
base 10 flag
Definition at line 102 of file ios.h.
Referenced by dec().
eofbit
const iostate ios_base::eofbit = 0x02 static inherited
iostate bit for end of file reached
Definition at line 60 of file ios.h.
Referenced by ios::eof(), StreamBaseClass::getch(), and istream::peek().
failbit
const iostate ios_base::failbit = 0X04 static inherited
iostate fail bit for nonfatal error
Definition at line 62 of file ios.h.
Referenced by ios::fail(), istream::get(), istream::getBool(), istream::getChar(), istream::getDouble(), istream::getline(), istream::getStr(), StreamBaseClass::open(), ArduinoInStream::readline(), and istream::seekg().
goodbit
const iostate ios_base::goodbit = 0x00 static inherited
iostate for no flags
Definition at line 56 of file ios.h.
Referenced by ios::good().
hex
const fmtflags ios_base::hex = 0x0010 static inherited
base 16 flag
Definition at line 104 of file ios.h.
Referenced by istream::getNumber(), and hex().
in
const openmode ios_base::in = 0X20 static inherited
open for input
Definition at line 139 of file ios.h.
Referenced by StreamBaseClass::open().
internal
const fmtflags ios_base::internal = 0x0004 static inherited
fill between sign/base prefix and number
Definition at line 100 of file ios.h.
Referenced by internal().
left
const fmtflags ios_base::left = 0x0001 static inherited
left adjust fields
Definition at line 96 of file ios.h.
Referenced by ostream::fill_not_left(), and left().
m_fill
char ios_base::m_fill private inherited
Definition at line 234 of file ios.h.
m_fmtflags
fmtflags ios_base::m_fmtflags private inherited
Definition at line 235 of file ios.h.
m_gcount
size_t istream::m_gcount private inherited
Definition at line 363 of file istream.h.
Referenced by istream::gcount(), istream::get(), istream::getline(), istream::ignore(), and istream::peek().
m_iostate
iostate ios::m_iostate = 0 private inherited
Definition at line 446 of file ios.h.
Referenced by ios::bad(), ios::clear(), ios::eof(), ios::fail(), ios::good(), ios::rdstate(), and ios::setstate().
m_mode
ios::openmode StreamBaseClass::m_mode private inherited
Definition at line 75 of file fstream.h.
Referenced by StreamBaseClass::getmode(), and StreamBaseClass::setmode().
m_precision
unsigned char ios_base::m_precision private inherited
Definition at line 236 of file ios.h.
m_width
unsigned int ios_base::m_width private inherited
Definition at line 237 of file ios.h.
oct
const fmtflags ios_base::oct = 0x0020 static inherited
base 8 flag
Definition at line 106 of file ios.h.
Referenced by istream::getNumber(), and oct().
out
const openmode ios_base::out = 0X40 static inherited
open for output
Definition at line 141 of file ios.h.
Referenced by StreamBaseClass::open().
right
const fmtflags ios_base::right = 0x0002 static inherited
right adjust fields
Definition at line 98 of file ios.h.
Referenced by right().
showbase
const fmtflags ios_base::showbase = 0x0200 static inherited
use prefix 0X for hex and 0 for oct
Definition at line 112 of file ios.h.
Referenced by noshowbase(), and showbase().
showpoint
const fmtflags ios_base::showpoint = 0x0400 static inherited
always show '.' for floating numbers
Definition at line 114 of file ios.h.
Referenced by noshowpoint(), ostream::putDouble(), and showpoint().
showpos
const fmtflags ios_base::showpos = 0x0800 static inherited
show + sign for nonnegative numbers
Definition at line 116 of file ios.h.
Referenced by noshowpos(), ostream::putDouble(), and showpos().
skipws
const fmtflags ios_base::skipws = 0x1000 static inherited
skip initial white space
Definition at line 118 of file ios.h.
Referenced by noskipws(), istream::readSkip(), and skipws().
trunc
const openmode ios_base::trunc = 0X80 static inherited
truncate an existing stream when opening
Definition at line 143 of file ios.h.
Referenced by StreamBaseClass::open().
uppercase
const fmtflags ios_base::uppercase = 0x4000 static inherited
use uppercase letters in number representations
Definition at line 121 of file ios.h.
Referenced by nouppercase(), and uppercase().
The documentation for this class was generated from the following file:
fstream.h