ERIS CORE: SoftSPI< MisoPin, MosiPin, SckPin, Mode > Class Template Reference
SoftSPI< MisoPin, MosiPin, SckPin, Mode > Class Template Reference
Software SPI
Fast software SPI.
#include <SoftSPI.h>
Public Member Functions
__attribute__ ((always_inline)) uint8_t receive()
__attribute__ ((always_inline)) uint8_t transfer(uint8_t txData)
__attribute__ ((always_inline)) void send(uint8_t data)
void begin ()
Private Member Functions
__attribute__ ((always_inline)) bool MODE_CPHA(uint8_t mode)
__attribute__ ((always_inline)) bool MODE_CPOL(uint8_t mode)
__attribute__ ((always_inline)) void receiveBit(uint8_t bit
__attribute__ ((always_inline)) void sendBit(uint8_t bit
__attribute__ ((always_inline)) void transferBit(uint8_t bit
fastDigitalWrite (SckPin, MODE_CPHA(Mode) ? MODE_CPOL(Mode) :!MODE_CPOL(Mode))
fastDigitalWrite (SckPin, MODE_CPHA(Mode) ? MODE_CPOL(Mode) :!MODE_CPOL(Mode))
fastDigitalWrite (SckPin, MODE_CPHA(Mode) ? MODE_CPOL(Mode) :!MODE_CPOL(Mode))
if (!MODE_CPHA(Mode))
if (!MODE_CPHA(Mode))
if (!MODE_CPHA(Mode))
if (fastDigitalRead(MisoPin)) *data|
if (fastDigitalRead(MisoPin)) *rxData|
Private Attributes
uint8_t * data
uint8_t data
nop
uint8_t * rxData
uint8_t uint8_t txData
Detailed Description
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0>
class SoftSPI< MisoPin, MosiPin, SckPin, Mode >
Fast software SPI.
Definition at line 49 of file SoftSPI.h.
Member Function Documentation
__attribute__() [1/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline private
Definition at line 111 of file SoftSPI.h.
                                {return (mode & 1) != 0;}
References mode.
__attribute__() [2/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline private
Definition at line 113 of file SoftSPI.h.
                                {return (mode & 2) != 0;}
References mode.
__attribute__() [3/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline
Soft SPI receive byte.
Returns
Data byte received.
Definition at line 62 of file SoftSPI.h.
                     {
     uint8_t data = 0;
     receiveBit(7, &data);
     receiveBit(6, &data);
     receiveBit(5, &data);
     receiveBit(4, &data);
     receiveBit(3, &data);
     receiveBit(2, &data);
     receiveBit(1, &data);
     receiveBit(0, &data);
     return data;
   }
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::data.
__attribute__() [4/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline
Soft SPI transfer byte.
Parameters
[in] txData Data byte to send.
Returns
Data byte received.
Definition at line 95 of file SoftSPI.h.
{
     uint8_t rxData = 0;
     transferBit(7, &rxData, txData);
     transferBit(6, &rxData, txData);
     transferBit(5, &rxData, txData);
     transferBit(4, &rxData, txData);
     transferBit(3, &rxData, txData);
     transferBit(2, &rxData, txData);
     transferBit(1, &rxData, txData);
     transferBit(0, &rxData, txData);
     return rxData;
   }
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::rxData, and SoftSPI< MisoPin, MosiPin, SckPin, Mode >::txData.
__attribute__() [5/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline private
__attribute__() [6/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline
Soft SPI send byte.
Parameters
[in] data Data byte to send.
Definition at line 79 of file SoftSPI.h.
{
     sendBit(7, data);
     sendBit(6, data);
     sendBit(5, data);
     sendBit(4, data);
     sendBit(3, data);
     sendBit(2, data);
     sendBit(1, data);
     sendBit(0, data);
   }
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::data.
__attribute__() [7/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline private
__attribute__() [8/8]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__ ((always_inline)) inline private
begin()
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> void SoftSPI< MisoPin, MosiPin, SckPin, Mode >::begin () inline
Initialize SoftSPI pins.
Definition at line 53 of file SoftSPI.h.
                {
     fastPinConfig(MisoPin, MISO_MODE, MISO_LEVEL);
     fastPinConfig(MosiPin, MOSI_MODE, !MODE_CPHA(Mode));
     fastPinConfig(SckPin, SCK_MODE, MODE_CPOL(Mode));
   }
References fastPinConfig, MISO_LEVEL, MISO_MODE, MOSI_MODE, and SCK_MODE.
Referenced by SoftSpiDriver< MisoPin, MosiPin, SckPin >::begin().
fastDigitalWrite() [1/3]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::fastDigitalWrite (SckPin , MODE_CPHA(Mode) ? MODE_CPOL(Mode) :!MODE_CPOL(Mode)) private
Referenced by SoftSPI< MisoPin, MosiPin, SckPin, Mode >::if().
fastDigitalWrite() [2/3]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::fastDigitalWrite (SckPin , MODE_CPHA(Mode) ? MODE_CPOL(Mode) :!MODE_CPOL(Mode)) private
fastDigitalWrite() [3/3]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::fastDigitalWrite (SckPin , MODE_CPHA(Mode) ? MODE_CPOL(Mode) :!MODE_CPOL(Mode)) private
if() [1/5]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::if (! MODE_CPHAMode) inline private
Definition at line 125 of file SoftSPI.h.
{
       fastDigitalWrite(SckPin, MODE_CPOL(Mode));
     }
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::fastDigitalWrite().
if() [2/5]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::if (! MODE_CPHAMode) inline private
Definition at line 140 of file SoftSPI.h.
{
       fastDigitalWrite(SckPin, MODE_CPOL(Mode));
     }
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::fastDigitalWrite().
if() [3/5]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::if (! MODE_CPHAMode) inline private
Definition at line 154 of file SoftSPI.h.
{
       fastDigitalWrite(SckPin, MODE_CPOL(Mode));
     }
References SoftSPI< MisoPin, MosiPin, SckPin, Mode >::fastDigitalWrite().
if() [4/5]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::if (fastDigitalRead(MisoPin)) private
if() [5/5]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::if (fastDigitalRead(MisoPin)) private
Member Data Documentation
data [1/2]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> uint8_t* SoftSPI< MisoPin, MosiPin, SckPin, Mode >::data private
Initial value:
{
    if (MODE_CPHA(Mode)) {
      fastDigitalWrite(SckPin, !MODE_CPOL(Mode));
    }
    nop
Definition at line 116 of file SoftSPI.h.
Referenced by SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__().
data [2/2]
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> uint8_t SoftSPI< MisoPin, MosiPin, SckPin, Mode >::data private
Initial value:
{
    if (MODE_CPHA(Mode)) {
      fastDigitalWrite(SckPin, !MODE_CPOL(Mode));
    }
    fastDigitalWrite(MosiPin, data & (1 << bit))
Definition at line 131 of file SoftSPI.h.
nop
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> SoftSPI< MisoPin, MosiPin, SckPin, Mode >::nop private
Definition at line 121 of file SoftSPI.h.
rxData
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> uint8_t* SoftSPI< MisoPin, MosiPin, SckPin, Mode >::rxData private
Definition at line 146 of file SoftSPI.h.
Referenced by SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__().
txData
template<uint8_t MisoPin, uint8_t MosiPin, uint8_t SckPin, uint8_t Mode = 0> uint8_t uint8_t SoftSPI< MisoPin, MosiPin, SckPin, Mode >::txData private
Initial value:
{
    if (MODE_CPHA(Mode)) {
      fastDigitalWrite(SckPin, !MODE_CPOL(Mode));
    }
    fastDigitalWrite(MosiPin, txData & (1 << bit))
Definition at line 146 of file SoftSPI.h.
Referenced by SoftSPI< MisoPin, MosiPin, SckPin, Mode >::__attribute__().
The documentation for this class was generated from the following file:
SoftSPI.h