ERIS CORE: FsName Class Reference
FsName Class Reference
Handle UTF-8 file names.
#include <FsName.h>
Public Member Functions
bool atEnd ()
uint16_t get16 ()
char getch ()
void reset ()
Public Attributes
const char * begin
const char * end
const char * next
Detailed Description
Handle UTF-8 file names.
Definition at line 37 of file FsName.h.
Member Function Documentation
atEnd()
bool FsName::atEnd () inline
Returns
true if at end.
Definition at line 47 of file FsName.h.
 {return next == end;}
References end, and next.
Referenced by ExFatFile::cmpName(), get16(), getch(), ExFatFile::hashName(), and ExFatFile::openPrivate().
get16()
uint16_t FsName::get16 () inline
Returns
next UTF-16 unit of LFN.
Definition at line 53 of file FsName.h.
 {return atEnd() ? 0 : *next++;}
References atEnd(), and next.
Referenced by ExFatFile::cmpName(), ExFatFile::hashName(), and ExFatFile::openPrivate().
getch()
char FsName::getch () inline
Returns
next char of LFN.
Definition at line 51 of file FsName.h.
 {return atEnd() ? 0 : *next++;}
References atEnd(), and next.
Referenced by ExFatFile::cmpName(), and ExFatFile::hashName().
reset()
void FsName::reset () inline
Reset to start of LFN.
Definition at line 49 of file FsName.h.
 {next = begin;}
References begin, and next.
Referenced by ExFatFile::hashName(), and ExFatFile::openPrivate().
Member Data Documentation
begin
const char* FsName::begin
Beginning of LFN.
Definition at line 40 of file FsName.h.
Referenced by ExFatFile::hashName(), ExFatFile::parsePathName(), and reset().
end
const char* FsName::end
Position one beyond last LFN character.
Definition at line 44 of file FsName.h.
Referenced by atEnd(), ExFatFile::hashName(), and ExFatFile::parsePathName().
next
const char* FsName::next
Next LFN character of end.
Definition at line 42 of file FsName.h.
Referenced by atEnd(), get16(), getch(), and reset().
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/src/common/FsName.h