ERIS CORE: TriangleWeb Class Reference
TriangleWeb Class Reference
#include <TriangleWeb.h>
Public Member Functions
TriangleWeb ()
uint_fast16_t bgColor (void)
virtual boolean forceTransitionNow (void)
void init (ILI9341_t3n tft)
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
virtual void reset (ILI9341_t3n tft)
String title ()
virtual boolean willForceTransition (void)
Detailed Description
Definition at line 14 of file TriangleWeb.h.
Constructor & Destructor Documentation
TriangleWeb()
TriangleWeb::TriangleWeb () inline
Definition at line 16 of file TriangleWeb.h.
 : BaseAnimation() {};
Member Function Documentation
bgColor()
uint_fast16_t TriangleWeb::bgColor (void) virtual
Reimplemented from BaseAnimation.
Definition at line 43 of file TriangleWeb.h.
{
     return _bgColor;
 }
forceTransitionNow()
boolean BaseAnimation::forceTransitionNow (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 44 of file BaseAnimation.h.
{
     // Extend me
     return false;   // Default: SuperTFT will transition animations automatically
 }
init()
void TriangleWeb::init (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
Definition at line 32 of file TriangleWeb.h.
{
   uint_fast16_t w = tft.width();
   uint_fast16_t h = tft.height();
   //tft.fillRect( 0, 0, w, h, 0x0 );
   _ptsAcross = w / WEB_POINT_SPACING + 1;
   _ptsDown = h / WEB_POINT_SPACING + 1;
   _bgColor = tft.color565( 0x22, 0x22, 0x22 );
 }
References tft(), and WEB_POINT_SPACING.
perFrame()
void TriangleWeb::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseAnimation.
Definition at line 61 of file TriangleWeb.h.
{
   //uint_fast16_t w = tft.width();
   //uint_fast16_t h = tft.height();
   // fillRect: flickers pretty bad
   //tft.fillRect( 0, 0, w, h, LV_RED );
   _phase += frameParams.timeMult * 0.0005 * (frameParams.audioMean*3.0f + 1.0f);
   // Prepare web color
   uint_fast8_t bright = (frameParams.audioPeak >> 1); // 0..512 -> 0..255
     // Weight brighter
     uint_fast16_t invBrightSquared = (0xff-bright)*(0xff-bright);
     bright = lerp8( bright, 0xff - (invBrightSquared>>8), 0.55f );
   uint_fast16_t color = tft.color565( bright, bright, bright );
   // When dark: Always illuminate one "lucky" line at random
   uint_fast16_t luckyLine = random( _ptsAcross * _ptsDown * 3 );
   uint_fast8_t luckyBright = random( 0x11, 0x55 );
   uint_fast16_t luckyColor = tft.color565( luckyBright, luckyBright, luckyBright );
   // It is possible to re-use some Point's here. TODO?
   Point nw, ne, sw;
   uint_fast16_t luckyIdx = 0;
   for( uint_fast8_t i=0; i<_ptsAcross; i++ ) {
     nw = getWebPoint( i, 0, _phase );
     for( uint_fast8_t j=0; j<_ptsDown; j++ ) {
       ne = getWebPoint( i+1, j, _phase );
       sw = getWebPoint( i, j+1, _phase );
       uint_fast16_t useColor;
       useColor = (luckyIdx==luckyLine) ? luckyColor : color;
       tft.drawLine( nw.x, nw.y, ne.x, ne.y, useColor );
       luckyIdx++;
       useColor = (luckyIdx==luckyLine) ? luckyColor : color;
       tft.drawLine( nw.x, nw.y, sw.x, sw.y, useColor );
       luckyIdx++;
       useColor = (luckyIdx==luckyLine) ? luckyColor : color;
       tft.drawLine( ne.x, ne.y, sw.x, sw.y, useColor );
       luckyIdx++;
       // Re-use sw point as new nw
       nw = sw;
     }
   }
 }
References FrameParams::audioMean, FrameParams::audioPeak, lerp8(), tft(), FrameParams::timeMult, Point::x, and Point::y.
reset()
void BaseAnimation::reset (ILI9341_t3n tft) virtual inherited
Reimplemented in TwistyText.
Definition at line 32 of file BaseAnimation.h.
{
     // Extend me
 }
title()
String TriangleWeb::title () virtual
Reimplemented from BaseAnimation.
Definition at line 47 of file TriangleWeb.h.
{
     return "TriangleWeb";
 }
willForceTransition()
boolean BaseAnimation::willForceTransition (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 40 of file BaseAnimation.h.
{
     return false;   // Default: SuperTFT will transition animations automatically
 }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/TriangleWeb.h