ERIS CORE: AnalogInputs Class Reference
AnalogInputs Class Reference
Used for filtering the analog inputs and change detection.
#include <AnalogInputs.h>
Public Member Functions
AnalogInputs ()
float freadAN1 ()
float freadAN2 ()
float freadAN3 ()
float freadAN4 ()
uint16_t readAN1 ()
uint16_t readAN2 ()
uint16_t readAN3 ()
uint16_t readAN4 ()
bool update ()
update returns true if a change is detected; false otherwise update is rate limited. additional calls will always return false
Private Attributes
int16_t ai [4]
elapsedMillis lastTrigger
elapsedMillis lastUpdate
Detailed Description
Used for filtering the analog inputs and change detection.
Definition at line 25 of file AnalogInputs.h.
Constructor & Destructor Documentation
AnalogInputs()
AnalogInputs::AnalogInputs () inline
Definition at line 31 of file AnalogInputs.h.
                       {
             analogReadAveraging(32);
             analogReadResolution(10);
             ai[0]=0;
             ai[1]=0;
             ai[2]=0;
             ai[3]=0;
         };
References ai.
Member Function Documentation
freadAN1()
float AnalogInputs::freadAN1 () inline
Definition at line 81 of file AnalogInputs.h.
 {return ai[0]/1024.0;};
References ai.
Referenced by AppManager::update().
freadAN2()
float AnalogInputs::freadAN2 () inline
Definition at line 82 of file AnalogInputs.h.
 {return ai[1]/1024.0;};
References ai.
Referenced by AppManager::update().
freadAN3()
float AnalogInputs::freadAN3 () inline
Definition at line 83 of file AnalogInputs.h.
 {return ai[2]/1024.0;};
References ai.
Referenced by AppManager::update().
freadAN4()
float AnalogInputs::freadAN4 () inline
Definition at line 84 of file AnalogInputs.h.
 {return ai[3]/1024.0;};
References ai.
Referenced by AppManager::update().
readAN1()
uint16_t AnalogInputs::readAN1 () inline
Definition at line 75 of file AnalogInputs.h.
 {return (uint16_t )ai[0];};
References ai.
Referenced by AppManager::update().
readAN2()
uint16_t AnalogInputs::readAN2 () inline
Definition at line 76 of file AnalogInputs.h.
 {return (uint16_t )ai[1];};
References ai.
Referenced by AppManager::update().
readAN3()
uint16_t AnalogInputs::readAN3 () inline
Definition at line 77 of file AnalogInputs.h.
 {return (uint16_t )ai[2];};
References ai.
Referenced by AppManager::update().
readAN4()
uint16_t AnalogInputs::readAN4 () inline
Definition at line 78 of file AnalogInputs.h.
 {return (uint16_t )ai[3];};
References ai.
Referenced by AppManager::update().
update()
bool AnalogInputs::update () inline
update returns true if a change is detected; false otherwise update is rate limited. additional calls will always return false
Returns
true
false
Definition at line 49 of file AnalogInputs.h.
                      {
             bool trigger;
             trigger=false;
             //rate limit the updates
             if (lastUpdate < MAX_POLLING_RATE) return false;
             lastUpdate = 0;
             int16_t old_ai[4] = {ai[0],ai[1],ai[2],ai[3]};
             //AudioNoInterrupts();
             ai[0] = (ai[0] * 0.85) + (analogRead(AN1) * 0.15);
             ai[1] = (ai[1] * 0.85) + (analogRead(AN2) * 0.15);
             ai[2] = (ai[2] * 0.85) + (analogRead(AN3) * 0.15);
             ai[3] = (ai[3] * 0.85) + (analogRead(AN4) * 0.15);
             //AudioInterrupts();
             if (abs(ai[0] - old_ai[0])>TRIGGER_DELTA) trigger = true;
             if (abs(ai[1] - old_ai[1])>TRIGGER_DELTA) trigger = true;
             if (abs(ai[2] - old_ai[2])>TRIGGER_DELTA) trigger = true;
             if (abs(ai[3] - old_ai[3])>TRIGGER_DELTA) trigger = true;
             if (lastTrigger > ANALOG_INPUTS_PERIODIC_UPDATE) trigger = true;
             if (trigger == true){
                 lastTrigger = 0;
                 return true;
             }
             return false;
         }
References ai, AN1, AN2, AN3, AN4, ANALOG_INPUTS_PERIODIC_UPDATE, lastTrigger, lastUpdate, MAX_POLLING_RATE, and TRIGGER_DELTA.
Referenced by AppManager::update().
Member Data Documentation
ai
int16_t AnalogInputs::ai[4] private
Definition at line 27 of file AnalogInputs.h.
Referenced by AnalogInputs(), freadAN1(), freadAN2(), freadAN3(), freadAN4(), readAN1(), readAN2(), readAN3(), readAN4(), and update().
lastTrigger
elapsedMillis AnalogInputs::lastTrigger private
Definition at line 29 of file AnalogInputs.h.
Referenced by update().
lastUpdate
elapsedMillis AnalogInputs::lastUpdate private
Definition at line 28 of file AnalogInputs.h.
Referenced by update().
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/include/AnalogInputs.h