ERIS CORE: wren_math.h File Reference
wren_math.h File Reference
#include <math.h>
#include <stdint.h>
Classes
union WrenDoubleBits
Macros
#define WREN_DOUBLE_NAN (wrenDoubleFromBits(WREN_DOUBLE_QNAN_POS_MIN_BITS))
#define WREN_DOUBLE_QNAN_POS_MAX_BITS (UINT64_C(0x7FFFFFFFFFFFFFFF))
#define WREN_DOUBLE_QNAN_POS_MIN_BITS (UINT64_C(0x7FF8000000000000))
Functions
static double wrenDoubleFromBits (uint64_t bits)
static uint64_t wrenDoubleToBits (double num)
Macro Definition Documentation
WREN_DOUBLE_NAN
#define WREN_DOUBLE_NAN (wrenDoubleFromBits(WREN_DOUBLE_QNAN_POS_MIN_BITS))
Definition at line 18 of file wren_math.h.
WREN_DOUBLE_QNAN_POS_MAX_BITS
#define WREN_DOUBLE_QNAN_POS_MAX_BITS (UINT64_C(0x7FFFFFFFFFFFFFFF))
Definition at line 16 of file wren_math.h.
WREN_DOUBLE_QNAN_POS_MIN_BITS
#define WREN_DOUBLE_QNAN_POS_MIN_BITS (UINT64_C(0x7FF8000000000000))
Definition at line 15 of file wren_math.h.
Function Documentation
wrenDoubleFromBits()
static double wrenDoubleFromBits (uint64_t bits) inline static
Definition at line 20 of file wren_math.h.
 {
   WrenDoubleBits data;
   data.bits64 = bits;
   return data.num;
 }
References data.
Referenced by wrenValueToNum().
wrenDoubleToBits()
static uint64_t wrenDoubleToBits (double num) inline static
Definition at line 27 of file wren_math.h.
 {
   WrenDoubleBits data;
   data.num = num;
   return data.bits64;
 }
References data.
Referenced by hashNumber(), and wrenNumToValue().