ERIS CORE: FsVolume Class Reference
FsVolume Class Reference
FsVolume class.
#include <FsVolume.h>
Public Member Functions
FsVolume ()
~FsVolume ()
bool begin (BlockDevice *blockDev)
uint32_t blocksPerCluster () __attribute__((deprecated))
uint32_t bytesPerCluster ()
bool chdir ()
bool chdir (const char *path)
bool chdir (const String &path)
void chvol ()
uint32_t clusterCount ()
uint32_t dataStartSector () const
void end ()
bool exists (const char *path)
bool exists (const String &path)
uint32_t fatStartSector () const
uint8_t fatType () const
uint32_t freeClusterCount ()
bool ls ()
bool ls (const char *path, uint8_t flags=0)
bool ls (print_t *pr)
bool ls (print_t *pr, const char *path, uint8_t flags)
bool ls (print_t *pr, uint8_t flags)
bool ls (uint8_t flags)
bool mkdir (const char *path, bool pFlag=true)
bool mkdir (const String &path, bool pFlag=true)
FsFile open (const char *path, oflag_t oflag=O_RDONLY)
FsFile open (const String &path, oflag_t oflag=O_RDONLY)
bool remove (const char *path)
bool remove (const String &path)
bool rename (const char *oldPath, const char *newPath)
bool rename (const String &oldPath, const String &newPath)
bool rmdir (const char *path)
bool rmdir (const String &path)
uint32_t sectorsPerCluster () const
Static Public Member Functions
static FsVolume * cwv ()
Friends
class FsBaseFile
Detailed Description
FsVolume class.
Definition at line 40 of file FsVolume.h.
Constructor & Destructor Documentation
FsVolume()
FsVolume::FsVolume () inline
Definition at line 42 of file FsVolume.h.
 : m_fVol(nullptr), m_xVol(nullptr) {}
~FsVolume()
FsVolume::~FsVolume () inline
Definition at line 44 of file FsVolume.h.
 {end();}
References end().
Member Function Documentation
begin()
bool FsVolume::begin (BlockDevice * blockDev)
Initialize an FatVolume object.
Parameters
[in] blockDev Device block driver.
Returns
true for success or false for failure.
Definition at line 28 of file FsVolume.cpp.
{
   m_blockDev = blockDev;
   m_fVol = nullptr;
   m_xVol = new (m_volMem) ExFatVolume;
   if (m_xVol && m_xVol->begin(m_blockDev, false)) {
     goto done;
   }
   m_xVol = nullptr;
   m_fVol = new (m_volMem) FatVolume;
   if (m_fVol && m_fVol->begin(m_blockDev, false)) {
     goto done;
   }
   m_cwv = nullptr;
   m_fVol = nullptr;
   return false;
  done:
   m_cwv = this;
   return true;
 }
References ExFatVolume::begin(), and FatVolume::begin().
blocksPerCluster()
uint32_t FsVolume::blocksPerCluster () inline
Definition at line 88 of file FsVolume.h.
 {return sectorsPerCluster();} //NOLINT
References sectorsPerCluster().
bytesPerCluster()
uint32_t FsVolume::bytesPerCluster () inline
Returns
the number of bytes in a cluster.
Definition at line 53 of file FsVolume.h.
{
     return m_fVol ? m_fVol->bytesPerCluster() :
            m_xVol ? m_xVol->bytesPerCluster() : 0;
   }
References ExFatPartition::bytesPerCluster(), and FatPartition::bytesPerCluster().
chdir() [1/3]
bool FsVolume::chdir () inline
Set volume working directory to root.
Returns
true for success or false for failure.
Definition at line 94 of file FsVolume.h.
                {
     return m_fVol ? m_fVol->chdir() :
            m_xVol ? m_xVol->chdir() : false;
   }
Referenced by ILI9341_t3_ERIS::begin(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), AppSerialCommandInterface::streamHandler(), and AppSerialCommandInterface::updateRT().
chdir() [2/3]
bool FsVolume::chdir (const char * path) inline
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 103 of file FsVolume.h.
{
     return m_fVol ? m_fVol->chdir(path) :
            m_xVol ? m_xVol->chdir(path) : false;
   }
chdir() [3/3]
bool FsVolume::chdir (const String & path) inline
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 280 of file FsVolume.h.
{
     return chdir(path.c_str());
   }
chvol()
void FsVolume::chvol () inline
Change global working volume to this volume.
Definition at line 60 of file FsVolume.h.
 {m_cwv = this;}
clusterCount()
uint32_t FsVolume::clusterCount () inline
Returns
The total number of clusters in the volume.
Definition at line 62 of file FsVolume.h.
{
     return m_fVol ? m_fVol->clusterCount() :
            m_xVol ? m_xVol->clusterCount() : 0;
   }
References ExFatPartition::clusterCount(), and FatPartition::clusterCount().
cwv()
static FsVolume* FsVolume::cwv () inline static
Returns
current working volume.
Definition at line 58 of file FsVolume.h.
 {return m_cwv;}
dataStartSector()
uint32_t FsVolume::dataStartSector () const inline
Returns
The logical sector number for the start of file data.
Definition at line 67 of file FsVolume.h.
{
     return m_fVol ? m_fVol->dataStartSector() :
            m_xVol ? m_xVol->clusterHeapStartSector() : 0;
   }
References ExFatPartition::clusterHeapStartSector(), and FatPartition::dataStartSector().
end()
void FsVolume::end () inline
free dynamic memory and end access to volume
Definition at line 108 of file FsVolume.h.
              {
     m_fVol = nullptr;
     m_xVol = nullptr;
   }
Referenced by ~FsVolume().
exists() [1/2]
bool FsVolume::exists (const char * path) inline
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 118 of file FsVolume.h.
{
     return m_fVol ? m_fVol->exists(path) :
            m_xVol ? m_xVol->exists(path) : false;
   }
Referenced by ILI9341_t3_ERIS::begin(), and AppSerialCommandInterface::streamHandler().
exists() [2/2]
bool FsVolume::exists (const String & path) inline
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 289 of file FsVolume.h.
{
     return exists(path.c_str());
   }
fatStartSector()
uint32_t FsVolume::fatStartSector () const inline
Returns
The logical sector number for the start of the first FAT.
Definition at line 72 of file FsVolume.h.
{
     return m_fVol ? m_fVol->fatStartSector() :
            m_xVol ? m_xVol->fatStartSector() : 0;
   }
References ExFatPartition::fatStartSector(), and FatPartition::fatStartSector().
fatType()
uint8_t FsVolume::fatType () const inline
Returns
Partition type, FAT_TYPE_EXFAT, FAT_TYPE_FAT32, FAT_TYPE_FAT16, or zero for error.
Definition at line 125 of file FsVolume.h.
{
     return m_fVol ? m_fVol->fatType() :
            m_xVol ? m_xVol->fatType() : 0;
   }
freeClusterCount()
uint32_t FsVolume::freeClusterCount () inline
Returns
the free cluster count.
Definition at line 77 of file FsVolume.h.
{
     return m_fVol ? m_fVol->freeClusterCount() :
            m_xVol ? m_xVol->freeClusterCount() : 0;
   }
References ExFatPartition::freeClusterCount(), and FatPartition::freeClusterCount().
ls() [1/6]
bool FsVolume::ls () inline
List directory contents.
Returns
true for success or false for failure.
Definition at line 236 of file FsVolume.h.
             {
     return ls(&Serial);
   }
ls() [2/6]
bool FsVolume::ls (const char * path, uint8_t flags = 0) inline
List the directory contents of a directory to Serial.
Parameters
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
true for success or false for failure.
Definition at line 270 of file FsVolume.h.
{
     return ls(&Serial, path, flags);
   }
ls() [3/6]
bool FsVolume::ls (print_t * pr) inline
List directory contents.
Parameters
[in] pr Print object.
Returns
true for success or false for failure.
Definition at line 135 of file FsVolume.h.
{
     return m_fVol ? m_fVol->ls(pr) :
            m_xVol ? m_xVol->ls(pr) : false;
   }
Referenced by ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), and AppSerialCommandInterface::updateRT().
ls() [4/6]
bool FsVolume::ls (print_t * pr, const char * path, uint8_t flags)
List the directory contents of a directory.
Parameters
[in] pr Print stream for list.
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 49 of file FsVolume.cpp.
{
   FsBaseFile dir;
   return dir.open(this, path, O_RDONLY) && dir.ls(pr, flags);
 }
References FsBaseFile::ls(), O_RDONLY, and FsBaseFile::open().
ls() [5/6]
bool FsVolume::ls (print_t * pr, uint8_t flags) inline
List directory contents.
Parameters
[in] pr Print object.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 152 of file FsVolume.h.
{
     return  m_fVol ? m_fVol->ls(pr, flags) :
             m_xVol ? m_xVol->ls(pr, flags) : false;
   }
ls() [6/6]
bool FsVolume::ls (uint8_t flags) inline
List directory contents.
Parameters
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 251 of file FsVolume.h.
{
     return ls(&Serial, flags);
   }
mkdir() [1/2]
bool FsVolume::mkdir (const char * path, bool pFlag = true) inline
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 181 of file FsVolume.h.
{
     return m_fVol ? m_fVol->mkdir(path, pFlag) :
            m_xVol ? m_xVol->mkdir(path, pFlag) : false;
   }
mkdir() [2/2]
bool FsVolume::mkdir (const String & path, bool pFlag = true) inline
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 300 of file FsVolume.h.
{
     return mkdir(path.c_str(), pFlag);
   }
open() [1/2]
FsFile FsVolume::open (const char * path, oflag_t oflag = O_RDONLY)
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a FsBaseFile object.
Definition at line 54 of file FsVolume.cpp.
{
   FsFile tmpFile;
   tmpFile.open(this, path, oflag);
   return tmpFile;
 }
References FsBaseFile::open().
Referenced by open().
open() [2/2]
FsFile FsVolume::open (const String & path, oflag_t oflag = O_RDONLY)
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a FsBaseFile object.
Definition at line 61 of file FsVolume.cpp.
{
   return open(path.c_str(), oflag );
 }
References open().
remove() [1/2]
bool FsVolume::remove (const char * path) inline
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
true for success or false for failure.
Definition at line 198 of file FsVolume.h.
{
     return m_fVol ? m_fVol->remove(path) :
            m_xVol ? m_xVol->remove(path) : false;
   }
remove() [2/2]
bool FsVolume::remove (const String & path) inline
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
true for success or false for failure.
Definition at line 316 of file FsVolume.h.
{
     return remove(path.c_str());
   }
rename() [1/2]
bool FsVolume::rename (const char * oldPath, const char * newPath) inline
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 216 of file FsVolume.h.
{
     return m_fVol ? m_fVol->rename(oldPath, newPath) :
            m_xVol ? m_xVol->rename(oldPath, newPath) : false;
   }
rename() [2/2]
bool FsVolume::rename (const String & oldPath, const String & newPath) inline
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 333 of file FsVolume.h.
{
     return rename(oldPath.c_str(), newPath.c_str());
   }
rmdir() [1/2]
bool FsVolume::rmdir (const char * path) inline
Remove a subdirectory from the volume's root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 228 of file FsVolume.h.
{
     return m_fVol ? m_fVol->rmdir(path) :
            m_xVol ? m_xVol->rmdir(path) : false;
   }
rmdir() [2/2]
bool FsVolume::rmdir (const String & path) inline
Remove a subdirectory from the volume's root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 344 of file FsVolume.h.
{
     return rmdir(path.c_str());
   }
sectorsPerCluster()
uint32_t FsVolume::sectorsPerCluster () const inline
Returns
The volume's cluster size in sectors.
Definition at line 82 of file FsVolume.h.
{
     return m_fVol ? m_fVol->sectorsPerCluster() :
            m_xVol ? m_xVol->sectorsPerCluster() : 0;
   }
References ExFatPartition::sectorsPerCluster(), and FatPartition::sectorsPerCluster().
Referenced by blocksPerCluster().
Friends And Related Function Documentation
FsBaseFile
friend class FsBaseFile friend
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure. FsBaseFile allowed access to private members.
Definition at line 365 of file FsVolume.h.
The documentation for this class was generated from the following files:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/FsLib/FsVolume.h
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/FsLib/FsVolume.cpp