ERIS CORE: D:/brian/Dev/Eris/ERISCore/src/AppManager.cpp File Reference
AppManager.cpp File Reference
#include <Arduino.h>
#include "HSI.h"
#include "touch.h"
#include "AnalogInputs.h"
#include "ILI9341_t3_ERIS.h"
#include "ili9341_t3n_font_Arial.h"
#include "AppManager.h"
Functions
uint16_t DMAMEM FB1[320 *240] __attribute__ ((aligned(32)))
Variables
ILI9341_t3_ERIS draw (TFT_CS, TFT_DC, TFT_RESET, TFT_MOSI, TFT_SCLK, TFT_MISO)
Touch touch (CS_TOUCH)
Detailed Description
Author
Brian Monkaba (brian.nosp@m..mon.nosp@m.kaba@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2021-08-20
Copyright
Copyright (c) 2021
Definition in file AppManager.cpp.
Function Documentation
__attribute__()
uint16_t DMAMEM FB1 [320 * 240] __attribute__ ((aligned(32)))
Variable Documentation
draw
ILI9341_t3_ERIS draw(TFT_CS, TFT_DC, TFT_RESET, TFT_MOSI, TFT_SCLK, TFT_MISO) (TFT_CS , TFT_DC , TFT_RESET , TFT_MOSI , TFT_SCLK , TFT_MISO)
Referenced by AppManager::AppManager(), AppManager::RegisterApp(), and AppManager::update().
touch
Touch touch(CS_TOUCH) (CS_TOUCH)
Referenced by AppManager::AppManager(), and AppManager::update().