ERIS CORE: SdSpiDriverBareUno Class Reference
SdSpiDriverBareUno Class Reference
Optimized SPI class for access to SD and SDHC flash memory cards.
#include <SdSpiBareUnoDriver.h>
Public Member Functions
void activate ()
void begin (SdSpiConfig spiConfig)
void deactivate ()
void end ()
uint8_t receive ()
uint8_t receive (uint8_t *buf, size_t count)
void select ()
void send (const uint8_t *buf, size_t count)
void send (uint8_t data)
void setSckSpeed (uint32_t maxSck)
void unselect ()
Static Public Member Functions
static uint8_t transfer (uint8_t data)
Private Attributes
SdCsPin_t m_csPin
Detailed Description
Optimized SPI class for access to SD and SDHC flash memory cards.
Definition at line 91 of file SdSpiBareUnoDriver.h.
Member Function Documentation
activate()
void SdSpiDriverBareUno::activate () inline
Activate SPI hardware.
Definition at line 94 of file SdSpiBareUnoDriver.h.
 {}
begin()
void SdSpiDriverBareUno::begin (SdSpiConfig spiConfig) inline
Initialize the SPI bus.
Parameters
[in] spiConfig SD card configuration.
Definition at line 103 of file SdSpiBareUnoDriver.h.
{
     m_csPin = spiConfig.csPin;
     unoPinMode(m_csPin, OUTPUT);
     unoDigitalWrite(m_csPin, HIGH);
     unoDigitalWrite(UNO_SS, HIGH);
     unoPinMode(UNO_SS, OUTPUT);
     SPCR |= _BV(MSTR);
     SPCR |= _BV(SPE);
     SPSR = 0;
     unoPinMode(UNO_SCK, OUTPUT);
     unoPinMode(UNO_MOSI, OUTPUT);
   }
References SdSpiConfig::csPin, HIGH, m_csPin, OUTPUT, UNO_MOSI, UNO_SCK, UNO_SS, unoDigitalWrite(), and unoPinMode().
deactivate()
void SdSpiDriverBareUno::deactivate () inline
Deactivate SPI hardware.
Definition at line 98 of file SdSpiBareUnoDriver.h.
 {}
end()
void SdSpiDriverBareUno::end () inline
deactivate SPI driver.
Definition at line 96 of file SdSpiBareUnoDriver.h.
 {}
receive() [1/2]
uint8_t SdSpiDriverBareUno::receive () inline
Receive a byte.
Returns
The byte.
Definition at line 119 of file SdSpiBareUnoDriver.h.
                     {
     return transfer(0XFF);
   }
References transfer().
receive() [2/2]
uint8_t SdSpiDriverBareUno::receive (uint8_t * buf, size_t count) inline
Receive multiple bytes.
Parameters
[out] buf Buffer to receive the data.
[in] count Number of bytes to receive.
Returns
Zero for no error or nonzero error code.
Definition at line 129 of file SdSpiBareUnoDriver.h.
{
     if (count == 0) {
       return 0;
     }
     uint8_t* pr = buf;
     SPDR = 0XFF;
     while (--count > 0) {
       while (!(SPSR & _BV(SPIF))) {}
       uint8_t in = SPDR;
       SPDR = 0XFF;
       *pr++ = in;
       // nops to optimize loop for 16MHz CPU 8 MHz SPI
       nop;
       nop;
     }
     while (!(SPSR & _BV(SPIF))) {}
     *pr = SPDR;
     return 0;
   }
References buf, count, and nop.
select()
void SdSpiDriverBareUno::select () inline
Set CS low.
Definition at line 176 of file SdSpiBareUnoDriver.h.
                 {
      unoDigitalWrite(m_csPin, LOW);
   }
References LOW, m_csPin, and unoDigitalWrite().
send() [1/2]
void SdSpiDriverBareUno::send (const uint8_t * buf, size_t count) inline
Send multiple bytes.
Parameters
[in] buf Buffer for data to be sent.
[in] count Number of bytes to send.
Definition at line 160 of file SdSpiBareUnoDriver.h.
{
     if (count == 0) {
       return;
     }
     SPDR = *buf++;
     while (--count > 0) {
       uint8_t b = *buf++;
       while (!(SPSR & (1 << SPIF))) {}
       SPDR = b;
       // nops to optimize loop for 16MHz CPU 8 MHz SPI
       nop;
       nop;
     }
     while (!(SPSR & (1 << SPIF))) {}
   }
References buf, count, and nop.
send() [2/2]
void SdSpiDriverBareUno::send (uint8_t data) inline
Send a byte.
Parameters
[in] data Byte to send
Definition at line 152 of file SdSpiBareUnoDriver.h.
{
     transfer(data);
   }
References data, and transfer().
setSckSpeed()
void SdSpiDriverBareUno::setSckSpeed (uint32_t maxSck) inline
Save high speed SPISettings after SD initialization.
Parameters
[in] spiConfig SPI options.
Definition at line 183 of file SdSpiBareUnoDriver.h.
{
     (void)maxSck;
     SPSR |= 1 << SPI2X;
   }
transfer()
static uint8_t SdSpiDriverBareUno::transfer (uint8_t data) inline static
Definition at line 187 of file SdSpiBareUnoDriver.h.
{
     SPDR = data;
     while (!(SPSR & _BV(SPIF))) {}  // wait
     return SPDR;
   }
References data.
Referenced by receive(), and send().
unselect()
void SdSpiDriverBareUno::unselect () inline
Set CS high.
Definition at line 193 of file SdSpiBareUnoDriver.h.
                   {
     unoDigitalWrite(m_csPin, HIGH);
   }
References HIGH, m_csPin, and unoDigitalWrite().
Member Data Documentation
m_csPin
SdCsPin_t SdSpiDriverBareUno::m_csPin private
Definition at line 198 of file SdSpiBareUnoDriver.h.
Referenced by begin(), select(), and unselect().
The documentation for this class was generated from the following file:
SdSpiBareUnoDriver.h