ERIS CORE: SvcDataDictionary::printDictionary
printDictionary()
void FLASHMEM SvcDataDictionary::printDictionary (SvcSerialCommandInterface * sci)
prints the dictionary to the SvcSerialCommandInterface
Parameters
sci
Definition at line 213 of file svcDataDictionary.cpp.
{
     //todo: print out in JSON format
     //Serial.flush();
     if(sci->requestStartLZ4Message()){
         sci->print(F("DD {"));
         uint16_t from, to;
         from = dd_transmitt_block++ * 16; //block size
         to = dd_transmitt_block * 16;
         if (to >= next){
             to = next;
             dd_transmitt_block = 0;
         }
         for(int i=from;i<to;i++){
             if (record[i].data_type == DDDT_INT32){
                 sci->printf("\"%s\":%d",record[i].key,record[i].val.int32_val);
             }else if (record[i].data_type == DDDT_FLOAT32){
                 sci->printf("\"%s\":%f",record[i].key,record[i].val.float32_val);
             }
             if (i != to-1) sci->print(",");
         }
         sci->println("}");
         sci->sendLZ4Message();
     }
 }
References dd_transmitt_block, DDDT_FLOAT32, DDDT_INT32, next, record, SvcSerialCommandInterface::requestStartLZ4Message(), sci, and SvcSerialCommandInterface::sendLZ4Message().
Referenced by SvcSerialCommandInterface::update().