ERIS CORE: SvcDataDictionary::readf
readf()
float32_t FASTRUN SvcDataDictionary::readf (const char * key)
returns the float32_t value of the record
Parameters
key
Returns
float32_t
Definition at line 96 of file svcDataDictionary.cpp.
{
     uint32_t h;
     h = hash(key);
     for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
         //key found
         if (record[i].key_hash == h) return record[i].val.float32_val;
     }
     //key not found
     return 0;
 }
References value_container::float32_val, hash(), record, and svcDataDictionaryRecord::val.
Referenced by dataDictReadFloatCallback(), and AppAudioToPolyphonic::initialize().