ERIS CORE: SvcDataDictionary::create
create() [3/3]
bool SvcDataDictionary::create (const char * key, int32_t val, uint32_t * owner)
Definition at line 50 of file svcDataDictionary.cpp.
{
     if (!copyKey(key)) return false;
     record[next].val.int32_val = val;
     record[next].owner = owner;
     record[next].record_type = DDRT_READ;
     record[next].key_hash = hash(key);
     next++;
     return true;
 }
References copyKey(), DDRT_READ, hash(), value_container::int32_val, svcDataDictionaryRecord::key_hash, next, svcDataDictionaryRecord::owner, record, svcDataDictionaryRecord::record_type, and svcDataDictionaryRecord::val.
Referenced by increment(), and update().