ERIS CORE: SvcDataDictionary::printDictionary
printDictionary()
void SvcDataDictionary::printDictionary (SvcSerialCommandInterface * sci)
prints the dictionary to the SvcSerialCommandInterface
Parameters
sci
Definition at line 226 of file SvcDataDictionary.cpp.
{
     //todo: print out in JSON format
     //Serial.flush();
     if(sci->requestStartLZ4Message()){
         sci->print(F("DD {"));
         for(int i=0;i<next;i++){
             if (record[i].data_type == DDDT_INT32){
                 sci->printf("\"%s\":%d",record[i].key,record[i].val.int32_val);
             }else if (record[i].data_type == DDDT_FLOAT32){
                 sci->printf("\"%s\":%f",record[i].key,record[i].val.float32_val);
             }
             if (i != next-1) sci->print(",");
         }
         sci->println("}");
         sci->sendLZ4Message();
     }
 }
References data_type, DDDT_FLOAT32, DDDT_INT32, value_container::float32_val, value_container::int32_val, key, next, record, SvcSerialCommandInterface::requestStartLZ4Message(), sci, SvcSerialCommandInterface::sendLZ4Message(), and val.
Referenced by SvcSerialCommandInterface::update().