ERIS CORE: SvcDataDictionary::update
update() [4/4]
bool SvcDataDictionary::update (const char * key, int32_t val, uint32_t * owner)
update the value of an owned record
creates a new record if one does not exist and
initalizes its value to zero
Parameters
key
val
owner
Returns
true
false
Definition at line 120 of file SvcDataDictionary.cpp.
{
     uint32_t h;
     h = hash(key);
     for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
         //key found
         if (record[i].key_hash == h){
         //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
             if (record[next].owner == owner && record[next].data_type == DDDT_INT32){
                 record[i].val.int32_val = val;
                 //arm_dcache_flush_delete(&record[i], sizeof(record[i]));
                 return true;
             } else return false;
         }
     }
     //key not found - try to create a new record
     return create(key, val, owner);
 }
References create(), data_type, DDDT_INT32, hash(), value_container::int32_val, key, key_hash, next, owner, record, val, and svcDataDictionaryRecord::val.
Referenced by dataDictUpdateCallback(), dataDictUpdateFloatCallback(), AppScope::render(), AppWren::render(), AppManager::requestArmSetClock(), AppManager::update(), AppScope::update(), and SvcSerialCommandInterface::update().