ERIS CORE: SvcDataDictionary::increment
increment()
bool SvcDataDictionary::increment (const char * key)
increments the value of a global record
creates a new record if one does not exist and
initalizes its value to zero
Parameters
key
Returns
true
false
Definition at line 196 of file SvcDataDictionary.cpp.
{
     uint32_t h;
     h = hash(key);
     int index = -1;
     for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
         //key found
         if (record[i].key_hash == h){
         //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
             index = i;
             break;
         }
     }
     if (index == -1){
         if (!create(key,(int32_t)0)) return false;
         index = next -1;
     }
     if (record[index].data_type == DDDT_INT32){
         record[index].val.int32_val++;
     }else if (record[index].data_type == DDDT_FLOAT32){
         record[index].val.float32_val++;
     }
     return true;
 }
References create(), data_type, DDDT_FLOAT32, DDDT_INT32, value_container::float32_val, hash(), value_container::int32_val, key, key_hash, next, record, and svcDataDictionaryRecord::val.
Referenced by SvcSerialCommandInterface::throttle(), AppCQT::update(), and AppManager::update().