ERIS CORE: SvcDataDictionary::hash
hash()
uint32_t SvcDataDictionary::hash (const char * s)
Definition at line 43 of file svcDataDictionary.cpp.
{
     //uint32 djb2 string hash
     uint32_t h = 5381;
     int c;
     while (c = (*s++)){h = ((h << 5) + h) + c;}
     return h;
 }
References s.
Referenced by create(), increment(), read(), readf(), and update().