ERIS CORE: SvcDataDictionary Class Reference
SvcDataDictionary Class Reference
#include <svcDataDictionary.h>
Public Member Functions
SvcDataDictionary ()
bool create (const char *key, float32_t val)
bool create (const char *key, int32_t val)
bool create (const char *key, int32_t val, uint32_t *owner)
bool increment (const char *key)
void printDictionary ()
void printStats ()
int32_t read (const char *key)
float32_t readf (const char *key)
bool update (const char *key, float32_t val)
bool update (const char *key, float32_t val, uint32_t *owner)
bool update (const char *key, int32_t val)
bool update (const char *key, int32_t val, uint32_t *owner)
Private Member Functions
uint32_t hash (const char *s)
Private Attributes
uint16_t next
svcDataDictionaryRecord record [DATADICT_KEYVALUE_PAIRS]
Detailed Description
Definition at line 86 of file svcDataDictionary.h.
Constructor & Destructor Documentation
SvcDataDictionary()
SvcDataDictionary::SvcDataDictionary () inline
Definition at line 100 of file svcDataDictionary.h.
{
             next=0;
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 record[i].owner = 0;
                 record[i].val.int32_val = 0;
                 record[i].pval = 0;
                 record[i].record_type = DDRT_READWRITE;
                 record[i].data_type = DDDT_INT32;
                 record[i].key_hash = 48879; //0xBEEF
                 #ifdef DATADICT_USE_MALLOC
                 record[i].key = NULL;
                 #else
                 memset(record[i].key,0,sizeof(record[i].key));
                 #endif
             }
         }
References svcDataDictionaryRecord::data_type, DATADICT_KEYVALUE_PAIRS, DDDT_INT32, DDRT_READWRITE, value_container::int32_val, svcDataDictionaryRecord::key, svcDataDictionaryRecord::key_hash, next, NULL, svcDataDictionaryRecord::owner, svcDataDictionaryRecord::pval, record, svcDataDictionaryRecord::record_type, and svcDataDictionaryRecord::val.
Member Function Documentation
create() [1/3]
bool SvcDataDictionary::create (const char * key, float32_t val) inline
Definition at line 169 of file svcDataDictionary.h.
{
             //if dictionary full
             if (next == DATADICT_KEYVALUE_PAIRS) return false;
             //TODO: ensure key doesn't already exist before creating a new record
             //else
             if(strlen(key) < DATADICT_MAX_KEY_LEN){
                 #ifdef DATADICT_USE_MALLOC
                 record[next].key = (char*)malloc(strlen(key)+1);
                 if (record[next].key != NULL){
                     strcpy(record[next].key,key);
                 } else return false; //if malloc failed
                 #else
                 strcpy(record[next].key,key);
                 #endif
                 record[next].val.float32_val = val;
                 record[next].pval = 0;
                 record[next].owner = 0;
                 record[next].record_type = DDRT_READWRITE;
                 record[next].data_type = DDDT_FLOAT32;
                 record[next].key_hash = hash(key);
                 next++;
                 return true;
             }
             return false;//bad key
         }
References svcDataDictionaryRecord::data_type, DATADICT_KEYVALUE_PAIRS, DATADICT_MAX_KEY_LEN, DDDT_FLOAT32, DDRT_READWRITE, value_container::float32_val, hash(), svcDataDictionaryRecord::key, svcDataDictionaryRecord::key_hash, next, NULL, svcDataDictionaryRecord::owner, svcDataDictionaryRecord::pval, record, svcDataDictionaryRecord::record_type, and svcDataDictionaryRecord::val.
create() [2/3]
bool SvcDataDictionary::create (const char * key, int32_t val) inline
Definition at line 143 of file svcDataDictionary.h.
{
             //if dictionary full
             if (next == DATADICT_KEYVALUE_PAIRS) return false;
             //TODO: ensure key doesn't already exist before creating a new record
             //else
             if(strlen(key) < DATADICT_MAX_KEY_LEN){
                 #ifdef DATADICT_USE_MALLOC
                 record[next].key = (char*)malloc(strlen(key)+1);
                 if (record[next].key != NULL){
                     strcpy(record[next].key,key);
                 } else return false; //if malloc failed
                 #else
                 strcpy(record[next].key,key);
                 #endif
                 record[next].val.int32_val = val;
                 record[next].pval = 0;
                 record[next].owner = 0;
                 record[next].record_type = DDRT_READWRITE;
                 record[next].data_type = DDDT_INT32;
                 record[next].key_hash = hash(key);
                 next++;
                 return true;
             }
             return false;//bad key
         }
References svcDataDictionaryRecord::data_type, DATADICT_KEYVALUE_PAIRS, DATADICT_MAX_KEY_LEN, DDDT_INT32, DDRT_READWRITE, hash(), value_container::int32_val, svcDataDictionaryRecord::key, svcDataDictionaryRecord::key_hash, next, NULL, svcDataDictionaryRecord::owner, svcDataDictionaryRecord::pval, record, svcDataDictionaryRecord::record_type, and svcDataDictionaryRecord::val.
create() [3/3]
bool SvcDataDictionary::create (const char * key, int32_t val, uint32_t * owner) inline
Definition at line 117 of file svcDataDictionary.h.
{
             //if dictionary full
             if (next == DATADICT_KEYVALUE_PAIRS) return false;
             //TODO: ensure key doesn't already exist before creating a new record
             //else
             if(strlen(key) < DATADICT_MAX_KEY_LEN){
                 #ifdef DATADICT_USE_MALLOC
                 record[next].key = strdup(key);
                 //record[next].key = (char*)malloc(strlen(key)+1);
                 //if (record[next].key != NULL){
                 //strcpy(record[next].key,key);
                 //} else return false; //if malloc failed
                 #else
                 strcpy(record[next].key,key);
                 #endif
                 record[next].val.int32_val = val;
                 record[next].pval = 0;
                 record[next].owner = owner;
                 record[next].record_type = DDRT_READ;
                 record[next].key_hash = hash(key);
                 next++;
                 return true;
             }
             return false;//bad key
         }
References DATADICT_KEYVALUE_PAIRS, DATADICT_MAX_KEY_LEN, DDRT_READ, hash(), value_container::int32_val, svcDataDictionaryRecord::key, svcDataDictionaryRecord::key_hash, next, svcDataDictionaryRecord::owner, svcDataDictionaryRecord::pval, record, svcDataDictionaryRecord::record_type, and svcDataDictionaryRecord::val.
Referenced by AppCQT::AppCQT(), AppManager::AppManager(), MyAppExample::MyAppExample(), increment(), and update().
hash()
uint32_t SvcDataDictionary::hash (const char * s) inline private
Definition at line 91 of file svcDataDictionary.h.
{
         //uint32 djb2 string hash
         uint32_t h = 5381;
         int c;
         while (c = *s++){h = ((h << 5) + h) + c;}
         return h;
     }
Referenced by create(), increment(), read(), readf(), and update().
increment()
bool SvcDataDictionary::increment (const char * key) inline
Definition at line 293 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             int index = -1;
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h){
                 //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
                     index = i;
                     break;
                 }
             }
             if (index == -1){
                 if (!create(key,(int32_t)0)) return false;
                 index = next -1;
             }
             if (record[index].data_type == DDDT_INT32){
                 record[index].val.int32_val++;
             }else if (record[index].data_type == DDDT_FLOAT32){
                 record[index].val.float32_val++;
             }
             return true;
         }
References create(), DATADICT_KEYVALUE_PAIRS, DDDT_FLOAT32, DDDT_INT32, value_container::float32_val, hash(), value_container::int32_val, next, record, and svcDataDictionaryRecord::val.
Referenced by AppManager::update().
printDictionary()
void SvcDataDictionary::printDictionary () inline
Definition at line 323 of file svcDataDictionary.h.
{
             //todo: print out in JSON format
             //Serial.flush();
             Serial.print("DD {");
             for(int i=0;i<next;i++){
                 if (record[i].data_type == DDDT_INT32){
                     Serial.printf("\"%s\":%d",record[i].key,record[i].val.int32_val);
                 }else if (record[i].data_type == DDDT_FLOAT32){
                     Serial.printf("\"%s\":%f",record[i].key,record[i].val.float32_val);
                 }
                 if (i != next-1) Serial.print(",");
             }
             Serial.println("}");
             //Serial.flush();
         }
References DDDT_FLOAT32, DDDT_INT32, next, and record.
Referenced by AppSerialCommandInterface::updateRT().
printStats()
void SvcDataDictionary::printStats () inline
Definition at line 319 of file svcDataDictionary.h.
{
         }
read()
int32_t SvcDataDictionary::read (const char * key) inline
Definition at line 195 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h) return record[i].val.int32_val;
             }
             //key not found
             return 0;
         }
References DATADICT_KEYVALUE_PAIRS, hash(), value_container::int32_val, record, and svcDataDictionaryRecord::val.
Referenced by MyAppExample::update(), AppManager::update(), ControlButton::update(), ControlSlider::update(), and AppCQT::updateOscillatorBank().
readf()
float32_t SvcDataDictionary::readf (const char * key) inline
Definition at line 206 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h) return record[i].val.float32_val;
             }
             //key not found
             return 0;
         }
References DATADICT_KEYVALUE_PAIRS, value_container::float32_val, hash(), record, and svcDataDictionaryRecord::val.
Referenced by MyAppExample::MyAppExample(), and MyAppExample::update().
update() [1/4]
bool SvcDataDictionary::update (const char * key, float32_t val) inline
Definition at line 274 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h){
                 //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
                     if (record[i].record_type == DDRT_READWRITE && record[i].data_type == DDDT_FLOAT32){
                         record[i].val.float32_val = val;
                         //arm_dcache_flush_delete(&record[i], sizeof(record[i]));
                         return true;
                     } else return false;
                 }
             }
             //key not found - try to create a new record
             return create(key, val);
         }
References create(), DATADICT_KEYVALUE_PAIRS, DDDT_FLOAT32, DDRT_READWRITE, value_container::float32_val, hash(), record, and svcDataDictionaryRecord::val.
update() [2/4]
bool SvcDataDictionary::update (const char * key, float32_t val, uint32_t * owner) inline
Definition at line 236 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h){
                 //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
                     if (record[next].owner == owner && record[next].data_type == DDDT_FLOAT32){
                         record[i].val.float32_val = val;
                         //arm_dcache_flush_delete(&record[i], sizeof(record[i]));
                         return true;
                     } else return false;
                 }
             }
             //key not found - try to create a new record
             return create(key, val, owner);
         }
References create(), DATADICT_KEYVALUE_PAIRS, DDDT_FLOAT32, value_container::float32_val, hash(), next, record, and svcDataDictionaryRecord::val.
update() [3/4]
bool SvcDataDictionary::update (const char * key, int32_t val) inline
Definition at line 255 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h){
                 //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
                     if (record[i].record_type == DDRT_READWRITE && record[i].data_type == DDDT_INT32){
                         record[i].val.int32_val = val;
                         //arm_dcache_flush_delete(&record[i], sizeof(record[i]));
                         return true;
                     } else return false;
                 }
             }
             //key not found - try to create a new record
             return create(key, val);
         }
References create(), DATADICT_KEYVALUE_PAIRS, DDDT_INT32, DDRT_READWRITE, hash(), value_container::int32_val, record, and svcDataDictionaryRecord::val.
update() [4/4]
bool SvcDataDictionary::update (const char * key, int32_t val, uint32_t * owner) inline
Definition at line 217 of file svcDataDictionary.h.
{
             uint32_t h;
             h = hash(key);
             for(int i=0;i<DATADICT_KEYVALUE_PAIRS;i++){
                 //key found
                 if (record[i].key_hash == h){
                 //if ((0==strncmp(record[i].key,key,DATADICT_MAX_KEY_LEN))){
                     if (record[next].owner == owner && record[next].data_type == DDDT_INT32){
                         record[i].val.int32_val = val;
                         //arm_dcache_flush_delete(&record[i], sizeof(record[i]));
                         return true;
                     } else return false;
                 }
             }
             //key not found - try to create a new record
             return create(key, val, owner);
         }
References create(), DATADICT_KEYVALUE_PAIRS, DDDT_INT32, hash(), value_container::int32_val, next, record, and svcDataDictionaryRecord::val.
Referenced by AppManager::update(), AppScope::update(), AppScope::updateRT(), and AppSerialCommandInterface::updateRT().
Member Data Documentation
next
uint16_t SvcDataDictionary::next private
Definition at line 89 of file svcDataDictionary.h.
Referenced by SvcDataDictionary(), create(), increment(), printDictionary(), and update().
record
svcDataDictionaryRecord SvcDataDictionary::record[DATADICT_KEYVALUE_PAIRS] private
Definition at line 88 of file svcDataDictionary.h.
Referenced by SvcDataDictionary(), create(), increment(), printDictionary(), read(), readf(), and update().
The documentation for this class was generated from the following file:
ERISCore/include/svcDataDictionary.h