ERIS CORE: ERISCore/lib/SdFat-master/src/common/FsDateTime.cpp File Reference
FsDateTime.cpp File Reference
#include "SysCall.h"
#include "FsDateTime.h"
#include "FmtNumber.h"
Namespaces
FsDateTime
Functions
void FsDateTime::clearCallback ()
static void dateTimeMs10 (uint16_t *date, uint16_t *time, uint8_t *ms10)
char * fsFmtDate (char *str, uint16_t date)
static char * fsFmtField (char *str, uint16_t n, char sep)
char * fsFmtTime (char *str, uint16_t time)
char * fsFmtTime (char *str, uint16_t time, uint8_t sec100)
char * fsFmtTimeZone (char *str, int8_t tz)
size_t fsPrintDate (print_t *pr, uint16_t date)
size_t fsPrintDateTime (print_t *pr, uint16_t date, uint16_t time)
size_t fsPrintDateTime (print_t *pr, uint32_t dateTime)
size_t fsPrintDateTime (print_t *pr, uint32_t dateTime, uint8_t s100, int8_t tz)
size_t fsPrintTime (print_t *pr, uint16_t time)
size_t fsPrintTime (print_t *pr, uint16_t time, uint8_t sec100)
size_t fsPrintTimeZone (print_t *pr, int8_t tz)
void FsDateTime::setCallback (void(*dateTime)(uint16_t *date, uint16_t *time))
void FsDateTime::setCallback (void(*dateTime)(uint16_t *date, uint16_t *time, uint8_t *ms10))
Variables
void(* FsDateTime::callback)(uint16_t *date, uint16_t *time, uint8_t *ms10) = nullptr
void(* FsDateTime::callback2)(uint16_t *date, uint16_t *time) = nullptr
Function Documentation
dateTimeMs10()
static void dateTimeMs10 (uint16_t * date, uint16_t * time, uint8_t * ms10) static
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 29 of file FsDateTime.cpp.
{
   *ms10 = 0;
   FsDateTime::callback2(date, time);
 }
References FsDateTime::callback2.
Referenced by FsDateTime::setCallback().
fsFmtDate()
char* fsFmtDate (char * str, uint16_t date)
Definition at line 62 of file FsDateTime.cpp.
{
   str = fsFmtField(str, date & 31, 0);
   date >>= 5;
   str = fsFmtField(str, date & 15, '-');
   date >>= 4;
   return fsFmtField(str, 1980 + date, '-');
 }
References fsFmtField().
Referenced by fsPrintDate(), and fsPrintDateTime().
fsFmtField()
static char* fsFmtField (char * str, uint16_t n, char sep) static
Definition at line 51 of file FsDateTime.cpp.
{
   if (sep) {
     *--str = sep;
   }
   str = fmtBase10(str, n);
   if (n < 10) {
     *--str = '0';
   }
   return str;
 }
References fmtBase10().
Referenced by fsFmtDate(), fsFmtTime(), and fsFmtTimeZone().
fsFmtTime() [1/2]
char* fsFmtTime (char * str, uint16_t time)
Definition at line 70 of file FsDateTime.cpp.
{
   time >>= 5;
   str = fsFmtField(str, time & 63, 0);
   return fsFmtField(str, time >> 6, ':');
 }
References fsFmtField().
Referenced by fsFmtTime(), fsPrintDateTime(), and fsPrintTime().
fsFmtTime() [2/2]
char* fsFmtTime (char * str, uint16_t time, uint8_t sec100)
Definition at line 76 of file FsDateTime.cpp.
{
   str = fsFmtField(str, 2*(time & 31) + (sec100 < 100 ? 0 : 1), 0);
   *--str = ':';
   return fsFmtTime(str, time);
 }
References fsFmtField(), and fsFmtTime().
fsFmtTimeZone()
char* fsFmtTimeZone (char * str, int8_t tz)
Definition at line 82 of file FsDateTime.cpp.
{
   char sign;
   if (tz & 0X80) {
     if (tz & 0X40) {
       sign = '-';
       tz = -tz;
     } else {
       sign = '+';
       tz &= 0X7F;
     }
     if (tz) {
       str = fsFmtField(str, 15*(tz%4), 0);
       str = fsFmtField(str, tz/4, ':');
       *--str = sign;
     }
     *--str = 'C';
     *--str = 'T';
     *--str = 'U';
   }
   return str;
 }
References fsFmtField().
Referenced by fsPrintDateTime(), and fsPrintTimeZone().
fsPrintDate()
size_t fsPrintDate (print_t * pr, uint16_t date)
Definition at line 104 of file FsDateTime.cpp.
{
   // Allow YYYY-MM-DD
   char buf[sizeof("YYYY-MM-DD") -1];
   char* str = buf + sizeof(buf);
   if (date) {
     str = fsFmtDate(str, date);
   } else {
      do {
       *--str = ' ';
     } while (str > buf);
   }
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtDate(), and PrintBasic::write().
Referenced by FatFile::printAccessDate().
fsPrintDateTime() [1/3]
size_t fsPrintDateTime (print_t * pr, uint16_t date, uint16_t time)
Definition at line 118 of file FsDateTime.cpp.
{
   // Allow YYYY-MM-DD hh:mm
   char buf[sizeof("YYYY-MM-DD hh:mm") -1];
   char* str = buf + sizeof(buf);
   if (date) {
     str = fsFmtTime(str, time);
     *--str = ' ';
     str = fsFmtDate(str, date);
   } else {
     do {
       *--str = ' ';
     } while (str > buf);
   }
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtDate(), fsFmtTime(), and PrintBasic::write().
Referenced by fsPrintDateTime(), ExFatFile::printAccessDateTime(), ExFatFile::printCreateDateTime(), FatFile::printCreateDateTime(), printDateTime(), ExFatFile::printModifyDateTime(), and FatFile::printModifyDateTime().
fsPrintDateTime() [2/3]
size_t fsPrintDateTime (print_t * pr, uint32_t dateTime)
Definition at line 134 of file FsDateTime.cpp.
{
   return fsPrintDateTime(pr, dateTime >> 16, dateTime & 0XFFFF);
 }
References fsPrintDateTime().
fsPrintDateTime() [3/3]
size_t fsPrintDateTime (print_t * pr, uint32_t dateTime, uint8_t s100, int8_t tz)
Definition at line 138 of file FsDateTime.cpp.
{
   // Allow YYYY-MM-DD hh:mm:ss UTC+hh:mm
   char buf[sizeof("YYYY-MM-DD hh:mm:ss UTC+hh:mm") -1];
   char* str = buf + sizeof(buf);
   if (tz) {
     str = fsFmtTimeZone(str, tz);
     *--str = ' ';
   }
   str = fsFmtTime(str, (uint16_t)dateTime, s100);
   *--str = ' ';
   str = fsFmtDate(str, (uint16_t)(dateTime >> 16));
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtDate(), fsFmtTime(), fsFmtTimeZone(), and PrintBasic::write().
fsPrintTime() [1/2]
size_t fsPrintTime (print_t * pr, uint16_t time)
Definition at line 153 of file FsDateTime.cpp.
{
   // Allow hh:mm
   char buf[sizeof("hh:mm") -1];
   char* str = buf + sizeof(buf);
   str = fsFmtTime(str, time);
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtTime(), and PrintBasic::write().
fsPrintTime() [2/2]
size_t fsPrintTime (print_t * pr, uint16_t time, uint8_t sec100)
Definition at line 161 of file FsDateTime.cpp.
{
   // Allow hh:mm:ss
   char buf[sizeof("hh:mm:ss") -1];
   char* str = buf + sizeof(buf);
   str = fsFmtTime(str, time, sec100);
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtTime(), and PrintBasic::write().
fsPrintTimeZone()
size_t fsPrintTimeZone (print_t * pr, int8_t tz)
Definition at line 169 of file FsDateTime.cpp.
{
   // Allow UTC+hh:mm
   char buf[sizeof("UTC+hh:mm") -1];
   char* str = buf + sizeof(buf);
   str = fsFmtTimeZone(str, tz);
   return pr->write(reinterpret_cast<uint8_t*>(str), buf + sizeof(buf) - str);
 }
References buf, fsFmtTimeZone(), and PrintBasic::write().