ERIS CORE: Checkerboard Class Reference
Checkerboard Class Reference
#include <Checkerboard.h>
Public Member Functions
Checkerboard ()
uint_fast16_t bgColor (void)
virtual boolean forceTransitionNow (void)
void init (ILI9341_t3n tft)
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
virtual void reset (ILI9341_t3n tft)
String title ()
virtual boolean willForceTransition (void)
Detailed Description
Definition at line 20 of file Checkerboard.h.
Constructor & Destructor Documentation
Checkerboard()
Checkerboard::Checkerboard () inline
Definition at line 22 of file Checkerboard.h.
 : BaseAnimation() {};
Member Function Documentation
bgColor()
uint_fast16_t Checkerboard::bgColor (void) virtual
Reimplemented from BaseAnimation.
Definition at line 38 of file Checkerboard.h.
{
     return _bgColor;
 }
forceTransitionNow()
boolean BaseAnimation::forceTransitionNow (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 44 of file BaseAnimation.h.
{
     // Extend me
     return false;   // Default: SuperTFT will transition animations automatically
 }
init()
void Checkerboard::init (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
Definition at line 34 of file Checkerboard.h.
{
   _bgColor = tft.color565( 0xff, 0xbb, 0xbb );
 }
References tft().
perFrame()
void Checkerboard::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseAnimation.
Definition at line 46 of file Checkerboard.h.
{
   int_fast16_t w = (int_fast16_t)tft.width();
   int_fast16_t h = (int_fast16_t)tft.height();
   _phase += frameParams.timeMult;
   float sizer = (cos(_phase*CHECKERBOARD_ZOOM_SPEED) + 1.0) * 0.5; // Range 0..1
   float size = lerp8( CHECKERBOARD_SIZE_MIN, CHECKERBOARD_SIZE_MAX, sizer );
   // Zoom in & out from center
   int_fast16_t strafeX = sin(_phase*CHECKERBOARD_STRAFE_SPEED_X) * CHECKERBOARD_STRAFE_DISTANCE * size;
   uint_fast8_t sqLeftOfCenter = ceil( (w/2 + strafeX) / (float)size );
   float startX = (w/2) - sqLeftOfCenter * size + strafeX;
   int_fast16_t strafeY = sin(_phase*CHECKERBOARD_STRAFE_SPEED_Y) * CHECKERBOARD_STRAFE_DISTANCE * size;
   uint_fast8_t sqAboveCenter = ceil( (h/2 + strafeY) / (float)size );
   float startY = (h/2) - sqAboveCenter * size + strafeY;
   // First square is light or 8dark?
   boolean startLight = (sqLeftOfCenter%2) ^ (sqAboveCenter%2);
     // Modulate colors based on audio input
     float ease = (1.0f-frameParams.audioMean);
     ease *= ease;   // Stronger reactions, please
     uint_fast8_t bright = (1.0f-ease) * 0xff;
     uint_fast16_t audioColor = tft.color565( bright, bright>>1, 0 );
   int_fast8_t sqX = -sqLeftOfCenter;
   for( float x=startX; x<w; x+=size ) {
     boolean isLight = startLight;
     int16_t drawX = max( x, 0 );
     int16_t drawW = (x >= 0) ? size : (size+x);
     int_fast8_t sqY = -sqAboveCenter;
     for( float y=startY; y<h; y+=size ) {
       int16_t drawY = max( y, 0 );
       int16_t drawH = (y >= 0) ? size : (size+y);
       uint_fast16_t color = tft.color565( (sqX * sqY * 57), (isLight ? 0xff : 0), (isLight ? 0xff : 0) );
             color ^= audioColor;
       tft.fillRect( drawX, drawY, drawW, drawH, color );
       isLight = !isLight;
       sqY++;
     }
     startLight = !startLight;
     sqX++;
   }
 }
References FrameParams::audioMean, CHECKERBOARD_SIZE_MAX, CHECKERBOARD_SIZE_MIN, CHECKERBOARD_STRAFE_DISTANCE, CHECKERBOARD_STRAFE_SPEED_X, CHECKERBOARD_STRAFE_SPEED_Y, CHECKERBOARD_ZOOM_SPEED, lerp8(), tft(), FrameParams::timeMult, x, and y.
reset()
void BaseAnimation::reset (ILI9341_t3n tft) virtual inherited
Reimplemented in TwistyText.
Definition at line 32 of file BaseAnimation.h.
{
     // Extend me
 }
title()
String Checkerboard::title () virtual
Reimplemented from BaseAnimation.
Definition at line 42 of file Checkerboard.h.
{
     return "Checkerboard";
 }
willForceTransition()
boolean BaseAnimation::willForceTransition (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 40 of file BaseAnimation.h.
{
     return false;   // Default: SuperTFT will transition animations automatically
 }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/Checkerboard.h