ERIS CORE: SdSpiBareUnoDriver.h File Reference
SdSpiBareUnoDriver.h File Reference
Driver to test with no Arduino includes.
#include <avr/interrupt.h>
#include "../common/SysCall.h"
Classes
class SdSpiDriverBareUno
Optimized SPI class for access to SD and SDHC flash memory cards.
Macros
#define HIGH 1
#define INPUT 0
#define LOW 0
#define nop asm volatile ("nop\n\t")
#define OUTPUT 1
#define UNO_MISO 12
#define UNO_MOSI 11
#define UNO_SCK 13
#define UNO_SS 10
Functions
uint8_t unoBit (uint8_t pin)
uint8_t unoDigitalRead (uint8_t pin)
void unoDigitalWrite (uint8_t pin, uint8_t value)
void unoPinMode (uint8_t pin, uint8_t mode)
Detailed Description
Driver to test with no Arduino includes.
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file SdSpiBareUnoDriver.h.
Macro Definition Documentation
HIGH
#define HIGH 1
Definition at line 36 of file SdSpiBareUnoDriver.h.
INPUT
#define INPUT 0
Definition at line 42 of file SdSpiBareUnoDriver.h.
LOW
#define LOW 0
Definition at line 39 of file SdSpiBareUnoDriver.h.
nop
#define nop asm volatile ("nop\n\t")
Definition at line 34 of file SdSpiBareUnoDriver.h.
OUTPUT
#define OUTPUT 1
Definition at line 45 of file SdSpiBareUnoDriver.h.
UNO_MISO
#define UNO_MISO 12
Definition at line 84 of file SdSpiBareUnoDriver.h.
UNO_MOSI
#define UNO_MOSI 11
Definition at line 83 of file SdSpiBareUnoDriver.h.
UNO_SCK
#define UNO_SCK 13
Definition at line 85 of file SdSpiBareUnoDriver.h.
UNO_SS
#define UNO_SS 10
Definition at line 82 of file SdSpiBareUnoDriver.h.
Function Documentation
unoBit()
uint8_t unoBit (uint8_t pin) inline
Definition at line 48 of file SdSpiBareUnoDriver.h.
{
   return 1 << (pin < 8 ? pin : pin < 14 ? pin - 8 : pin - 14);
 }
Referenced by unoDigitalRead(), unoDigitalWrite(), and unoPinMode().
unoDigitalRead()
uint8_t unoDigitalRead (uint8_t pin) inline
Definition at line 51 of file SdSpiBareUnoDriver.h.
{
   volatile uint8_t* reg = pin < 8 ? &PIND : pin < 14 ? &PINB : &PINC;
   return *reg & unoBit(pin);
 }
References unoBit().
unoDigitalWrite()
void unoDigitalWrite (uint8_t pin, uint8_t value) inline
Definition at line 55 of file SdSpiBareUnoDriver.h.
{
   volatile uint8_t* port = pin < 8 ? &PORTD : pin < 14 ? &PORTB : &PORTC;
   uint8_t bit = unoBit(pin);
   cli();
   if (value) {
     *port |= bit;
   } else {
     *port &= ~bit;
   }
   sei();
 }
References unoBit().
Referenced by SdSpiDriverBareUno::begin(), SdSpiDriverBareUno::select(), unoPinMode(), and SdSpiDriverBareUno::unselect().
unoPinMode()
void unoPinMode (uint8_t pin, uint8_t mode) inline
Definition at line 67 of file SdSpiBareUnoDriver.h.
{
   uint8_t bit = unoBit(pin);
   volatile uint8_t* reg = pin < 8 ? &DDRD : pin < 14 ? &DDRB : &DDRC;
   cli();
   if (mode == OUTPUT) {
     *reg |= bit;
   } else {
     *reg &= ~bit;
     // handle INPUT pull-up
     unoDigitalWrite(pin, mode != INPUT);
   }
   sei();
 }
References INPUT, mode, OUTPUT, unoBit(), and unoDigitalWrite().
Referenced by SdSpiDriverBareUno::begin().