ERIS CORE: SdFs Class Reference
SdFs Class Reference
SD file system class for FAT16, FAT32, and exFAT volumes.
#include <SdFat-beta.h>
Public Member Functions
bool begin (BlockDevice *blockDev)
bool begin (SdCsPin_t csPin, uint32_t maxSck)
bool begin (SdCsPin_t csPin=SS)
bool begin (SdioConfig sdioConfig)
bool begin (SdSpiConfig spiConfig)
uint32_t blocksPerCluster () __attribute__((deprecated))
uint32_t bytesPerCluster ()
SdCard * card ()
bool cardBegin (SdioConfig sdioConfig)
bool cardBegin (SdSpiConfig spiConfig)
bool chdir ()
bool chdir (const char *path)
bool chdir (const String &path)
void chvol ()
uint32_t clusterCount ()
uint32_t dataStartSector () const
void end ()
void errorHalt ()
void errorHalt (const __FlashStringHelper *msg)
void errorHalt (const char *msg)
void errorHalt (print_t *pr)
void errorHalt (print_t *pr, const __FlashStringHelper *msg)
void errorHalt (print_t *pr, const char *msg)
void errorPrint (const __FlashStringHelper *msg)
void errorPrint (const char *msg)
void errorPrint (Print *pr, const __FlashStringHelper *msg)
void errorPrint (print_t *pr)
void errorPrint (print_t *pr, char const *msg)
bool exists (const char *path)
bool exists (const String &path)
uint32_t fatStartSector () const
uint8_t fatType () const
uint32_t freeClusterCount ()
void initErrorHalt ()
void initErrorHalt (const __FlashStringHelper *msg)
void initErrorHalt (const char *msg)
void initErrorHalt (Print *pr, const __FlashStringHelper *msg)
void initErrorHalt (print_t *pr)
void initErrorHalt (print_t *pr, const char *msg)
void initErrorPrint ()
void initErrorPrint (Print *pr)
bool ls ()
bool ls (const char *path, uint8_t flags=0)
bool ls (print_t *pr)
bool ls (print_t *pr, const char *path, uint8_t flags)
bool ls (print_t *pr, uint8_t flags)
bool ls (uint8_t flags)
bool mkdir (const char *path, bool pFlag=true)
bool mkdir (const String &path, bool pFlag=true)
FsFile open (const char *path, oflag_t oflag=O_RDONLY)
FsFile open (const String &path, oflag_t oflag=O_RDONLY)
void printFatType (print_t *pr)
void printSdError (print_t *pr)
bool remove (const char *path)
bool remove (const String &path)
bool rename (const char *oldPath, const char *newPath)
bool rename (const String &oldPath, const String &newPath)
bool rmdir (const char *path)
bool rmdir (const String &path)
uint8_t sdErrorCode ()
uint8_t sdErrorData ()
uint32_t sectorsPerCluster () const
FsVolume * vol ()
bool volumeBegin ()
Static Public Member Functions
static FsVolume * cwv ()
Detailed Description
SD file system class for FAT16, FAT32, and exFAT volumes.
Definition at line 393 of file SdFat-beta.h.
Member Function Documentation
begin() [1/5]
bool FsVolume::begin (BlockDevice * blockDev) inherited
Initialize an FatVolume object.
Parameters
[in] blockDev Device block driver.
Returns
true for success or false for failure.
Definition at line 28 of file FsVolume.cpp.
{
   m_blockDev = blockDev;
   m_fVol = nullptr;
   m_xVol = new (m_volMem) ExFatVolume;
   if (m_xVol && m_xVol->begin(m_blockDev, false)) {
     goto done;
   }
   m_xVol = nullptr;
   m_fVol = new (m_volMem) FatVolume;
   if (m_fVol && m_fVol->begin(m_blockDev, false)) {
     goto done;
   }
   m_cwv = nullptr;
   m_fVol = nullptr;
   return false;
  done:
   m_cwv = this;
   return true;
 }
References ExFatVolume::begin(), and FatVolume::begin().
begin() [2/5]
bool SdBase< FsVolume >::begin (SdCsPin_t csPin, uint32_t maxSck) inline inherited
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
[in] maxSck Maximum SCK frequency.
Returns
true for success or false for failure.
Definition at line 72 of file SdFat-beta.h.
{
     return begin(SdSpiConfig(csPin, SHARED_SPI, maxSck));
   }
begin() [3/5]
bool SdBase< FsVolume >::begin (SdCsPin_t csPin = SS) inline inherited
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
Returns
true for success or false for failure.
Definition at line 57 of file SdFat-beta.h.
{
 #ifdef BUILTIN_SDCARD
     if (csPin == BUILTIN_SDCARD) {
       return begin(SdioConfig(FIFO_SDIO));
     }
 #endif  // BUILTIN_SDCARD
     return begin(SdSpiConfig(csPin, SHARED_SPI));
   }
begin() [4/5]
bool SdBase< FsVolume >::begin (SdioConfig sdioConfig) inline inherited
Initialize SD card and file system for SDIO mode.
Parameters
[in] sdioConfig SDIO configuration.
Returns
true for success or false for failure.
Definition at line 90 of file SdFat-beta.h.
{
     return cardBegin(sdioConfig) && Vol::begin(m_card);
   }
begin() [5/5]
bool SdBase< FsVolume >::begin (SdSpiConfig spiConfig) inline inherited
Initialize SD card and file system for SPI mode.
Parameters
[in] spiConfig SPI configuration.
Returns
true for success or false for failure.
Definition at line 81 of file SdFat-beta.h.
{
     return cardBegin(spiConfig) && Vol::begin(m_card);
   }
blocksPerCluster()
uint32_t FsVolume::blocksPerCluster () inline inherited
Definition at line 88 of file FsVolume.h.
 {return sectorsPerCluster();} //NOLINT
References FsVolume::sectorsPerCluster().
bytesPerCluster()
uint32_t FsVolume::bytesPerCluster () inline inherited
Returns
the number of bytes in a cluster.
Definition at line 53 of file FsVolume.h.
{
     return m_fVol ? m_fVol->bytesPerCluster() :
            m_xVol ? m_xVol->bytesPerCluster() : 0;
   }
References ExFatPartition::bytesPerCluster(), and FatPartition::bytesPerCluster().
card()
SdCard* SdBase< FsVolume >::card () inline inherited
Returns
Pointer to SD card object.
Definition at line 95 of file SdFat-beta.h.
 {return m_card;}
cardBegin() [1/2]
bool SdBase< FsVolume >::cardBegin (SdioConfig sdioConfig) inline inherited
Initialize SD card in SDIO mode.
Parameters
[in] sdioConfig SDIO configuration.
Returns
true for success or false for failure.
Definition at line 112 of file SdFat-beta.h.
{
     m_card = m_cardFactory.newCard(sdioConfig);
     return m_card && !m_card->errorCode();
   }
cardBegin() [2/2]
bool SdBase< FsVolume >::cardBegin (SdSpiConfig spiConfig) inline inherited
Initialize SD card in SPI mode.
Parameters
[in] spiConfig SPI configuration.
Returns
true for success or false for failure.
Definition at line 102 of file SdFat-beta.h.
{
     m_card = m_cardFactory.newCard(spiConfig);
     return m_card && !m_card->errorCode();
   }
chdir() [1/3]
bool FsVolume::chdir () inline inherited
Set volume working directory to root.
Returns
true for success or false for failure.
Definition at line 94 of file FsVolume.h.
                {
     return m_fVol ? m_fVol->chdir() :
            m_xVol ? m_xVol->chdir() : false;
   }
Referenced by ILI9341_t3_ERIS::begin(), ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), AppSerialCommandInterface::streamHandler(), and AppSerialCommandInterface::updateRT().
chdir() [2/3]
bool FsVolume::chdir (const char * path) inline inherited
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 103 of file FsVolume.h.
{
     return m_fVol ? m_fVol->chdir(path) :
            m_xVol ? m_xVol->chdir(path) : false;
   }
chdir() [3/3]
bool FsVolume::chdir (const String & path) inline inherited
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 280 of file FsVolume.h.
{
     return chdir(path.c_str());
   }
chvol()
void FsVolume::chvol () inline inherited
Change global working volume to this volume.
Definition at line 60 of file FsVolume.h.
 {m_cwv = this;}
clusterCount()
uint32_t FsVolume::clusterCount () inline inherited
Returns
The total number of clusters in the volume.
Definition at line 62 of file FsVolume.h.
{
     return m_fVol ? m_fVol->clusterCount() :
            m_xVol ? m_xVol->clusterCount() : 0;
   }
References ExFatPartition::clusterCount(), and FatPartition::clusterCount().
cwv()
static FsVolume* FsVolume::cwv () inline static inherited
Returns
current working volume.
Definition at line 58 of file FsVolume.h.
 {return m_cwv;}
dataStartSector()
uint32_t FsVolume::dataStartSector () const inline inherited
Returns
The logical sector number for the start of file data.
Definition at line 67 of file FsVolume.h.
{
     return m_fVol ? m_fVol->dataStartSector() :
            m_xVol ? m_xVol->clusterHeapStartSector() : 0;
   }
References ExFatPartition::clusterHeapStartSector(), and FatPartition::dataStartSector().
end()
void FsVolume::end () inline inherited
free dynamic memory and end access to volume
Definition at line 108 of file FsVolume.h.
              {
     m_fVol = nullptr;
     m_xVol = nullptr;
   }
Referenced by FsVolume::~FsVolume().
errorHalt() [1/6]
void SdBase< FsVolume >::errorHalt () inline inherited
Print error info to Serial and halt.
Definition at line 305 of file SdFat-beta.h.
 {errorHalt(&Serial);}
errorHalt() [2/6]
void SdBase< FsVolume >::errorHalt (const __FlashStringHelper * msg) inline inherited
Print msg to Serial and halt.
Parameters
[in] msg Message to print.
Definition at line 300 of file SdFat-beta.h.
{
     errorHalt(&Serial, msg);
   }
errorHalt() [3/6]
void SdBase< FsVolume >::errorHalt (const char * msg) inline inherited
Print error info and halt.
Parameters
[in] msg Message to print.
Definition at line 311 of file SdFat-beta.h.
 {errorHalt(&Serial, msg);}
errorHalt() [4/6]
void SdBase< FsVolume >::errorHalt (print_t * pr) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
Definition at line 121 of file SdFat-beta.h.
{
     if (sdErrorCode()) {
       pr->print(F("SdError: 0X"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0X"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
     SysCall::halt();
   }
errorHalt() [5/6]
void SdBase< FsVolume >::errorHalt (print_t * pr, const __FlashStringHelper * msg) inline inherited
Print msg and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 149 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorHalt(pr);
   }
errorHalt() [6/6]
void SdBase< FsVolume >::errorHalt (print_t * pr, const char * msg) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 138 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorHalt(pr);
   }
errorPrint() [1/5]
void SdBase< FsVolume >::errorPrint (const __FlashStringHelper * msg) inline inherited
Print msg, any SD error code.
Parameters
[in] msg Message to print.
Definition at line 325 of file SdFat-beta.h.
 {errorPrint(&Serial, msg);}
errorPrint() [2/5]
void SdBase< FsVolume >::errorPrint (const char * msg) inline inherited
Print msg, any SD error code.
Parameters
[in] msg Message to print.
Definition at line 320 of file SdFat-beta.h.
 {errorPrint(&Serial, msg);}
errorPrint() [3/5]
void SdBase< FsVolume >::errorPrint (Print * pr, const __FlashStringHelper * msg) inline inherited
Print msg, any SD error code.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 243 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorPrint(pr);
   }
errorPrint() [4/5]
void SdBase< FsVolume >::errorPrint (print_t * pr) inline inherited
Print SD errorCode and errorData.
Parameters
[in] pr Print destination.
Definition at line 216 of file SdFat-beta.h.
{
     if (sdErrorCode()) {
       pr->print(F("SdError: 0X"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0X"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
   }
errorPrint() [5/5]
void SdBase< FsVolume >::errorPrint (print_t * pr, char const * msg) inline inherited
Print msg, any SD error code.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 232 of file SdFat-beta.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorPrint(pr);
   }
exists() [1/2]
bool FsVolume::exists (const char * path) inline inherited
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 118 of file FsVolume.h.
{
     return m_fVol ? m_fVol->exists(path) :
            m_xVol ? m_xVol->exists(path) : false;
   }
Referenced by ILI9341_t3_ERIS::begin(), and AppSerialCommandInterface::streamHandler().
exists() [2/2]
bool FsVolume::exists (const String & path) inline inherited
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 289 of file FsVolume.h.
{
     return exists(path.c_str());
   }
fatStartSector()
uint32_t FsVolume::fatStartSector () const inline inherited
Returns
The logical sector number for the start of the first FAT.
Definition at line 72 of file FsVolume.h.
{
     return m_fVol ? m_fVol->fatStartSector() :
            m_xVol ? m_xVol->fatStartSector() : 0;
   }
References ExFatPartition::fatStartSector(), and FatPartition::fatStartSector().
fatType()
uint8_t FsVolume::fatType () const inline inherited
Returns
Partition type, FAT_TYPE_EXFAT, FAT_TYPE_FAT32, FAT_TYPE_FAT16, or zero for error.
Definition at line 125 of file FsVolume.h.
{
     return m_fVol ? m_fVol->fatType() :
            m_xVol ? m_xVol->fatType() : 0;
   }
freeClusterCount()
uint32_t FsVolume::freeClusterCount () inline inherited
Returns
the free cluster count.
Definition at line 77 of file FsVolume.h.
{
     return m_fVol ? m_fVol->freeClusterCount() :
            m_xVol ? m_xVol->freeClusterCount() : 0;
   }
References ExFatPartition::freeClusterCount(), and FatPartition::freeClusterCount().
initErrorHalt() [1/6]
void SdBase< FsVolume >::initErrorHalt () inline inherited
Print error info and halt.
Definition at line 314 of file SdFat-beta.h.
 {initErrorHalt(&Serial);}
initErrorHalt() [2/6]
void SdBase< FsVolume >::initErrorHalt (const __FlashStringHelper * msg) inline inherited
Print error info and halt.
Parameters
[in] msg Message to print.
Definition at line 337 of file SdFat-beta.h.
{
     initErrorHalt(&Serial, msg);
   }
initErrorHalt() [3/6]
void SdBase< FsVolume >::initErrorHalt (const char * msg) inline inherited
Print error info and halt.
Parameters
[in] msg Message to print.
Definition at line 331 of file SdFat-beta.h.
 {initErrorHalt(&Serial, msg);}
initErrorHalt() [4/6]
void SdBase< FsVolume >::initErrorHalt (Print * pr, const __FlashStringHelper * msg) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 179 of file SdFat-beta.h.
{
     pr->println(msg);
     initErrorHalt(pr);
   }
initErrorHalt() [5/6]
void SdBase< FsVolume >::initErrorHalt (print_t * pr) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
Definition at line 159 of file SdFat-beta.h.
{
     initErrorPrint(pr);
     SysCall::halt();
   }
initErrorHalt() [6/6]
void SdBase< FsVolume >::initErrorHalt (print_t * pr, const char * msg) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 169 of file SdFat-beta.h.
{
     pr->println(msg);
     initErrorHalt(pr);
   }
initErrorPrint() [1/2]
void SdBase< FsVolume >::initErrorPrint () inline inherited
Print error details after begin() fails.
Definition at line 292 of file SdFat-beta.h.
{
     initErrorPrint(&Serial);
   }
initErrorPrint() [2/2]
void SdBase< FsVolume >::initErrorPrint (Print * pr) inline inherited
Print error details after begin() fails.
Parameters
[in] pr Print destination.
Definition at line 188 of file SdFat-beta.h.
{
     pr->println(F("begin() failed"));
     if (sdErrorCode()) {
       pr->println(F("Do not reformat the SD."));
       if (sdErrorCode() == SD_CARD_ERROR_CMD0) {
         pr->println(F("No card, wrong chip select pin, or wiring error?"));
       }
     }
     errorPrint(pr);
   }
ls() [1/6]
bool FsVolume::ls () inline inherited
List directory contents.
Returns
true for success or false for failure.
Definition at line 236 of file FsVolume.h.
             {
     return ls(&Serial);
   }
ls() [2/6]
bool FsVolume::ls (const char * path, uint8_t flags = 0) inline inherited
List the directory contents of a directory to Serial.
Parameters
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
true for success or false for failure.
Definition at line 270 of file FsVolume.h.
{
     return ls(&Serial, path, flags);
   }
ls() [3/6]
bool FsVolume::ls (print_t * pr) inline inherited
List directory contents.
Parameters
[in] pr Print object.
Returns
true for success or false for failure.
Definition at line 135 of file FsVolume.h.
{
     return m_fVol ? m_fVol->ls(pr) :
            m_xVol ? m_xVol->ls(pr) : false;
   }
Referenced by ILI9341_t3_ERIS::bltSD(), ILI9341_t3_ERIS::bltSDFullScreen(), and AppSerialCommandInterface::updateRT().
ls() [4/6]
bool FsVolume::ls (print_t * pr, const char * path, uint8_t flags) inherited
List the directory contents of a directory.
Parameters
[in] pr Print stream for list.
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 49 of file FsVolume.cpp.
{
   FsBaseFile dir;
   return dir.open(this, path, O_RDONLY) && dir.ls(pr, flags);
 }
References FsBaseFile::ls(), O_RDONLY, and FsBaseFile::open().
ls() [5/6]
bool FsVolume::ls (print_t * pr, uint8_t flags) inline inherited
List directory contents.
Parameters
[in] pr Print object.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 152 of file FsVolume.h.
{
     return  m_fVol ? m_fVol->ls(pr, flags) :
             m_xVol ? m_xVol->ls(pr, flags) : false;
   }
ls() [6/6]
bool FsVolume::ls (uint8_t flags) inline inherited
List directory contents.
Parameters
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 251 of file FsVolume.h.
{
     return ls(&Serial, flags);
   }
mkdir() [1/2]
bool FsVolume::mkdir (const char * path, bool pFlag = true) inline inherited
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 181 of file FsVolume.h.
{
     return m_fVol ? m_fVol->mkdir(path, pFlag) :
            m_xVol ? m_xVol->mkdir(path, pFlag) : false;
   }
mkdir() [2/2]
bool FsVolume::mkdir (const String & path, bool pFlag = true) inline inherited
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 300 of file FsVolume.h.
{
     return mkdir(path.c_str(), pFlag);
   }
open() [1/2]
FsFile FsVolume::open (const char * path, oflag_t oflag = O_RDONLY) inherited
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a FsBaseFile object.
Definition at line 54 of file FsVolume.cpp.
{
   FsFile tmpFile;
   tmpFile.open(this, path, oflag);
   return tmpFile;
 }
References FsBaseFile::open().
Referenced by FsVolume::open().
open() [2/2]
FsFile FsVolume::open (const String & path, oflag_t oflag = O_RDONLY) inherited
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a FsBaseFile object.
Definition at line 61 of file FsVolume.cpp.
{
   return open(path.c_str(), oflag );
 }
References FsVolume::open().
printFatType()
void SdBase< FsVolume >::printFatType (print_t * pr) inline inherited
Print volume FAT/exFAT type.
Parameters
[in] pr Print destination.
Definition at line 203 of file SdFat-beta.h.
{
     if (Vol::fatType() == FAT_TYPE_EXFAT) {
       pr->print(F("exFAT"));
     } else {
       pr->print(F("FAT"));
       pr->print(Vol::fatType());
     }
   }
printSdError()
void SdBase< FsVolume >::printSdError (print_t * pr) inline inherited
Print error info and return.
Parameters
[in] pr Print destination.
Definition at line 253 of file SdFat-beta.h.
{
     if (sdErrorCode()) {
       if (sdErrorCode() == SD_CARD_ERROR_CMD0) {
         pr->println(F("No card, wrong chip select pin, or wiring error?"));
       }
       pr->print(F("SD error: "));
       printSdErrorSymbol(pr, sdErrorCode());
       pr->print(F(" = 0x"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0x"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::cwv()) {
       pr->println(F("Check SD format."));
     }
   }
remove() [1/2]
bool FsVolume::remove (const char * path) inline inherited
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
true for success or false for failure.
Definition at line 198 of file FsVolume.h.
{
     return m_fVol ? m_fVol->remove(path) :
            m_xVol ? m_xVol->remove(path) : false;
   }
remove() [2/2]
bool FsVolume::remove (const String & path) inline inherited
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
true for success or false for failure.
Definition at line 316 of file FsVolume.h.
{
     return remove(path.c_str());
   }
rename() [1/2]
bool FsVolume::rename (const char * oldPath, const char * newPath) inline inherited
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 216 of file FsVolume.h.
{
     return m_fVol ? m_fVol->rename(oldPath, newPath) :
            m_xVol ? m_xVol->rename(oldPath, newPath) : false;
   }
rename() [2/2]
bool FsVolume::rename (const String & oldPath, const String & newPath) inline inherited
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 333 of file FsVolume.h.
{
     return rename(oldPath.c_str(), newPath.c_str());
   }
rmdir() [1/2]
bool FsVolume::rmdir (const char * path) inline inherited
Remove a subdirectory from the volume's root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 228 of file FsVolume.h.
{
     return m_fVol ? m_fVol->rmdir(path) :
            m_xVol ? m_xVol->rmdir(path) : false;
   }
rmdir() [2/2]
bool FsVolume::rmdir (const String & path) inline inherited
Remove a subdirectory from the volume's root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 344 of file FsVolume.h.
{
     return rmdir(path.c_str());
   }
sdErrorCode()
uint8_t SdBase< FsVolume >::sdErrorCode () inline inherited
Returns
SD card error code.
Definition at line 270 of file SdFat-beta.h.
{
     if (m_card) {
       return m_card->errorCode();
     }
     return SD_CARD_ERROR_INVALID_CARD_CONFIG;
   }
sdErrorData()
uint8_t SdBase< FsVolume >::sdErrorData () inline inherited
Returns
SD card error data.
Definition at line 278 of file SdFat-beta.h.
 {return m_card ? m_card->errorData() : 0;}
sectorsPerCluster()
uint32_t FsVolume::sectorsPerCluster () const inline inherited
Returns
The volume's cluster size in sectors.
Definition at line 82 of file FsVolume.h.
{
     return m_fVol ? m_fVol->sectorsPerCluster() :
            m_xVol ? m_xVol->sectorsPerCluster() : 0;
   }
References ExFatPartition::sectorsPerCluster(), and FatPartition::sectorsPerCluster().
Referenced by FsVolume::blocksPerCluster().
vol()
FsVolume * SdBase< FsVolume >::vol () inline inherited
Returns
pointer to base volume
Definition at line 281 of file SdFat-beta.h.
 {return reinterpret_cast<Vol*>(this);}
volumeBegin()
bool SdBase< FsVolume >::volumeBegin () inline inherited
Initialize file system after call to cardBegin.
Returns
true for success or false for failure.
Definition at line 287 of file SdFat-beta.h.
                      {
      return Vol::begin(m_card);
   }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/SdFat-beta.h