ERIS CORE: wren_utils.c File Reference
wren_utils.c File Reference
#include <string.h>
#include "wren_utils.h"
#include "wren_vm.h"
Functions
DEFINE_BUFFER (Byte, uint8_t)
DEFINE_BUFFER (Int, int)
DEFINE_BUFFER (String, ObjString *)
void wrenBlackenSymbolTable (WrenVM *vm, SymbolTable *symbolTable)
int wrenPowerOf2Ceil (int n)
int wrenSymbolTableAdd (WrenVM *vm, SymbolTable *symbols, const char *name, size_t length)
void wrenSymbolTableClear (WrenVM *vm, SymbolTable *symbols)
int wrenSymbolTableEnsure (WrenVM *vm, SymbolTable *symbols, const char *name, size_t length)
int wrenSymbolTableFind (const SymbolTable *symbols, const char *name, size_t length)
void wrenSymbolTableInit (SymbolTable *symbols)
int wrenUtf8Decode (const uint8_t *bytes, uint32_t length)
int wrenUtf8DecodeNumBytes (uint8_t byte)
int wrenUtf8Encode (int value, uint8_t *bytes)
int wrenUtf8EncodeNumBytes (int value)
uint32_t wrenValidateIndex (uint32_t count, int64_t value)
Function Documentation
DEFINE_BUFFER() [1/3]
DEFINE_BUFFER (Byte , uint8_t)
DEFINE_BUFFER() [2/3]
DEFINE_BUFFER (Int , int)
DEFINE_BUFFER() [3/3]
DEFINE_BUFFER (String , ObjString *)
wrenBlackenSymbolTable()
void wrenBlackenSymbolTable (WrenVM * vm, SymbolTable * symbolTable)
Definition at line 56 of file wren_utils.c.
 {
   for (int i = 0; i < symbolTable->count; i++)
   {
     wrenGrayObj(vm, &symbolTable->data[i]->obj);
   }
   // Keep track of how much memory is still in use.
   vm->bytesAllocated += symbolTable->capacity * sizeof(*symbolTable->data);
 }
References WrenVM::bytesAllocated, and wrenGrayObj().
Referenced by blackenModule(), wrenCollectGarbage(), and wrenMarkCompiler().
wrenPowerOf2Ceil()
int wrenPowerOf2Ceil (int n)
Definition at line 185 of file wren_utils.c.
 {
   n--;
   n |= n >> 1;
   n |= n >> 2;
   n |= n >> 4;
   n |= n >> 8;
   n |= n >> 16;
   n++;
   return n;
 }
Referenced by wrenEnsureStack(), and wrenNewFiber().
wrenSymbolTableAdd()
int wrenSymbolTableAdd (WrenVM * vm, SymbolTable * symbols, const char * name, size_t length)
Definition at line 20 of file wren_utils.c.
 {
   ObjString* symbol = AS_STRING(wrenNewStringLength(vm, name, length));
   wrenPushRoot(vm, &symbol->obj);
   wrenStringBufferWrite(vm, symbols, symbol);
   wrenPopRoot(vm);
   return symbols->count - 1;
 }
References AS_STRING, name, sObjString::obj, wrenNewStringLength(), wrenPopRoot(), and wrenPushRoot().
Referenced by wrenDeclareVariable(), wrenDefineVariable(), and wrenSymbolTableEnsure().
wrenSymbolTableClear()
void wrenSymbolTableClear (WrenVM * vm, SymbolTable * symbols)
Definition at line 15 of file wren_utils.c.
 {
   wrenStringBufferClear(vm, symbols);
 }
Referenced by classDefinition(), wrenFreeObj(), and wrenFreeVM().
wrenSymbolTableEnsure()
int wrenSymbolTableEnsure (WrenVM * vm, SymbolTable * symbols, const char * name, size_t length)
Definition at line 32 of file wren_utils.c.
 {
   // See if the symbol is already defined.
   int existing = wrenSymbolTableFind(symbols, name, length);
   if (existing != -1) return existing;
   // New symbol, so add it.
   return wrenSymbolTableAdd(vm, symbols, name, length);
 }
References name, wrenSymbolTableAdd(), and wrenSymbolTableFind().
Referenced by bindForeignClass(), field(), methodSymbol(), and wrenMakeCallHandle().
wrenSymbolTableFind()
int wrenSymbolTableFind (const SymbolTable * symbols, const char * name, size_t length)
Definition at line 43 of file wren_utils.c.
 {
   // See if the symbol is already defined.
   // TODO: O(n). Do something better.
   for (int i = 0; i < symbols->count; i++)
   {
     if (wrenStringEqualsCString(symbols->data[i], name, length)) return i;
   }
   return -1;
 }
References name, and wrenStringEqualsCString().
Referenced by createForeign(), getModuleVariable(), loadCoreVariable(), name(), resolveName(), wrenDefineVariable(), wrenFinalizeForeign(), wrenFindVariable(), wrenGetVariable(), wrenHasVariable(), and wrenSymbolTableEnsure().
wrenSymbolTableInit()
void wrenSymbolTableInit (SymbolTable * symbols)
Definition at line 10 of file wren_utils.c.
 {
   wrenStringBufferInit(symbols);
 }
Referenced by classDefinition(), wrenNewModule(), and wrenNewVM().
wrenUtf8Decode()
int wrenUtf8Decode (const uint8_t * bytes, uint32_t length)
Definition at line 122 of file wren_utils.c.
 {
   // Single byte (i.e. fits in ASCII).
   if (*bytes <= 0x7f) return *bytes;
   int value;
   uint32_t remainingBytes;
   if ((*bytes & 0xe0) == 0xc0)
   {
     // Two byte sequence: 110xxxxx 10xxxxxx.
     value = *bytes & 0x1f;
     remainingBytes = 1;
   }
   else if ((*bytes & 0xf0) == 0xe0)
   {
     // Three byte sequence: 1110xxxx     10xxxxxx 10xxxxxx.
     value = *bytes & 0x0f;
     remainingBytes = 2;
   }
   else if ((*bytes & 0xf8) == 0xf0)
   {
     // Four byte sequence: 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx.
     value = *bytes & 0x07;
     remainingBytes = 3;
   }
   else
   {
     // Invalid UTF-8 sequence.
     return -1;
   }
   // Don't read past the end of the buffer on truncated UTF-8.
   if (remainingBytes > length - 1) return -1;
   while (remainingBytes > 0)
   {
     bytes++;
     remainingBytes--;
     // Remaining bytes must be of form 10xxxxxx.
     if ((*bytes & 0xc0) != 0x80) return -1;
     value = value << 6 | (*bytes & 0x3f);
   }
   return value;
 }
Referenced by DEF_PRIMITIVE(), wrenNewStringFromRange(), and wrenStringCodePointAt().
wrenUtf8DecodeNumBytes()
int wrenUtf8DecodeNumBytes (uint8_t byte)
Definition at line 170 of file wren_utils.c.
 {
   // If the byte starts with 10xxxxx, it's the middle of a UTF-8 sequence, so
   // don't count it at all.
   if ((byte & 0xc0) == 0x80) return 0;
   // The first byte's high bits tell us how many bytes are in the UTF-8
   // sequence.
   if ((byte & 0xf8) == 0xf0) return 4;
   if ((byte & 0xf0) == 0xe0) return 3;
   if ((byte & 0xe0) == 0xc0) return 2;
   return 1;
 }
Referenced by wrenNewStringFromRange().
wrenUtf8Encode()
int wrenUtf8Encode (int value, uint8_t * bytes)
Definition at line 78 of file wren_utils.c.
 {
   if (value <= 0x7f)
   {
     // Single byte (i.e. fits in ASCII).
     *bytes = value & 0x7f;
     return 1;
   }
   else if (value <= 0x7ff)
   {
     // Two byte sequence: 110xxxxx 10xxxxxx.
     *bytes = 0xc0 | ((value & 0x7c0) >> 6);
     bytes++;
     *bytes = 0x80 | (value & 0x3f);
     return 2;
   }
   else if (value <= 0xffff)
   {
     // Three byte sequence: 1110xxxx 10xxxxxx 10xxxxxx.
     *bytes = 0xe0 | ((value & 0xf000) >> 12);
     bytes++;
     *bytes = 0x80 | ((value & 0xfc0) >> 6);
     bytes++;
     *bytes = 0x80 | (value & 0x3f);
     return 3;
   }
   else if (value <= 0x10ffff)
   {
     // Four byte sequence: 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx.
     *bytes = 0xf0 | ((value & 0x1c0000) >> 18);
     bytes++;
     *bytes = 0x80 | ((value & 0x3f000) >> 12);
     bytes++;
     *bytes = 0x80 | ((value & 0xfc0) >> 6);
     bytes++;
     *bytes = 0x80 | (value & 0x3f);
     return 4;
   }
   // Invalid Unicode value. See: http://tools.ietf.org/html/rfc3629
   UNREACHABLE();
   return 0;
 }
References UNREACHABLE.
Referenced by readUnicodeEscape(), wrenNewStringFromRange(), and wrenStringFromCodePoint().
wrenUtf8EncodeNumBytes()
int wrenUtf8EncodeNumBytes (int value)
Definition at line 67 of file wren_utils.c.
 {
   ASSERT(value >= 0, "Cannot encode a negative value.");
   if (value <= 0x7f) return 1;
   if (value <= 0x7ff) return 2;
   if (value <= 0xffff) return 3;
   if (value <= 0x10ffff) return 4;
   return 0;
 }
References ASSERT.
Referenced by readUnicodeEscape(), and wrenStringFromCodePoint().
wrenValidateIndex()
uint32_t wrenValidateIndex (uint32_t count, int64_t value)
Definition at line 198 of file wren_utils.c.
 {
   // Negative indices count from the end.
   if (value < 0) value = count + value;
   // Check bounds.
   if (value >= 0 && value < count) return (uint32_t)value;
   return UINT32_MAX;
 }
References count.
Referenced by wrenGetListElement(), and wrenSetListElement().