ERIS CORE: AudioSynthWaveform2k::update
update()
void AudioSynthWaveform2k::update (void) virtual
Implements AudioStream.
Reimplemented in erisAudioSynthWaveform2k, and erisAudioSynthWaveform.
Definition at line 47 of file eris_synth_waveform.cpp.
 {
     audio_block_t *block;
     int16_t *bp, *end;
     int32_t val1, val2;
     int16_t magnitude15;
     uint32_t i, ph, index, index2, scale;
     const uint32_t inc = phase_increment;
     ph = phase_accumulator + phase_offset;
     if (magnitude == 0) {
         phase_accumulator += inc * AUDIO_BLOCK_SAMPLES;
         return;
     }
     block = allocate();
     if (!block) {
         phase_accumulator += inc * AUDIO_BLOCK_SAMPLES;
         return;
     }
     bp = block->data;
     switch(tone_type) {
     case WAVEFORM_SINE:
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             index = ph >> 21;
             val1 = AudioWaveformSine[index];
             val2 = AudioWaveformSine[index+1];
             scale = (ph >> 8) & 0xFFFF;
             val2 *= scale;
             val1 *= 0x10000 - scale;
             *bp++ = multiply_32x32_rshift32(val1 + val2, magnitude);
             ph += inc;
         }
         break;
     case WAVEFORM_ARBITRARY:
         if (!arbdata) {
             release(block);
             phase_accumulator += inc * AUDIO_BLOCK_SAMPLES;
             return;
         }
         // len = 256
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             index = ph >> 21;
             index2 = index + 1;
             if (index2 >= 256) index2 = 0;
             val1 = *(arbdata + index);
             val2 = *(arbdata + index2);
             scale = (ph >> 8) & 0xFFFF;
             val2 *= scale;
             val1 *= 0x10000 - scale;
             *bp++ = multiply_32x32_rshift32(val1 + val2, magnitude);
             ph += inc;
         }
         break;
     case WAVEFORM_SQUARE:
         magnitude15 = signed_saturate_rshift(magnitude, 16, 1);
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             if (ph & 0x80000000) {
                 *bp++ = -magnitude15;
             } else {
                 *bp++ = magnitude15;
             }
             ph += inc;
         }
         break;
     case WAVEFORM_BANDLIMIT_SQUARE:
         for (int i = 0 ; i < AUDIO_BLOCK_SAMPLES ; i++)
         {
           uint32_t new_ph = ph + inc ;
           int16_t val = band_limit_waveform.generate_square (new_ph, i) ;
           *bp++ = (val * magnitude) >> 16 ;
           ph = new_ph ;
         }
         break;
     case WAVEFORM_SAWTOOTH:
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             *bp++ = signed_multiply_32x16t(magnitude, ph);
             ph += inc;
         }
         break;
     case WAVEFORM_SAWTOOTH_REVERSE:
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             *bp++ = signed_multiply_32x16t(0xFFFFFFFFu - magnitude, ph);
             ph += inc;
         }
         break;
     case WAVEFORM_BANDLIMIT_SAWTOOTH:
     case WAVEFORM_BANDLIMIT_SAWTOOTH_REVERSE:
         for (i = 0 ; i < AUDIO_BLOCK_SAMPLES; i++)
         {
           uint32_t new_ph = ph + inc ;
           int16_t val = band_limit_waveform.generate_sawtooth (new_ph, i) ;
           if (tone_type == WAVEFORM_BANDLIMIT_SAWTOOTH_REVERSE)
             *bp++ = (val * -magnitude) >> 16 ;
           else
             *bp++ = (val * magnitude) >> 16 ;
           ph = new_ph ;
         }
         break;
     case WAVEFORM_TRIANGLE:
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             uint32_t phtop = ph >> 30;
             if (phtop == 1 || phtop == 2) {
                 *bp++ = ((0xFFFF - (ph >> 15)) * magnitude) >> 16;
             } else {
                 *bp++ = (((int32_t)ph >> 15) * magnitude) >> 16;
             }
             ph += inc;
         }
         break;
     case WAVEFORM_TRIANGLE_VARIABLE:
         do {
         uint32_t rise = 0xFFFFFFFF / (pulse_width >> 16);
         uint32_t fall = 0xFFFFFFFF / (0xFFFF - (pulse_width >> 16));
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             if (ph < pulse_width/2) {
                 uint32_t n = (ph >> 16) * rise;
                 *bp++ = ((n >> 16) * magnitude) >> 16;
             } else if (ph < 0xFFFFFFFF - pulse_width/2) {
                 uint32_t n = 0x7FFFFFFF - (((ph - pulse_width/2) >> 16) * fall);
                 *bp++ = (((int32_t)n >> 16) * magnitude) >> 16;
             } else {
                 uint32_t n = ((ph + pulse_width/2) >> 16) * rise + 0x80000000;
                 *bp++ = (((int32_t)n >> 16) * magnitude) >> 16;
             }
             ph += inc;
         }
         } while (0);
         break;
     case WAVEFORM_PULSE:
         magnitude15 = signed_saturate_rshift(magnitude, 16, 1);
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             if (ph < pulse_width) {
                 *bp++ = magnitude15;
             } else {
                 *bp++ = -magnitude15;
             }
             ph += inc;
         }
         break;
     case WAVEFORM_BANDLIMIT_PULSE:
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++)
         {
           int32_t new_ph = ph + inc ;
           int32_t val = band_limit_waveform.generate_pulse (new_ph, pulse_width, i) ;
           *bp++ = (int16_t) ((val * magnitude) >> 16) ;
           ph = new_ph ;
         }
         break;
     case WAVEFORM_SAMPLE_HOLD:
         for (i=0; i < AUDIO_BLOCK_SAMPLES; i++) {
             *bp++ = sample;
             uint32_t newph = ph + inc;
             if (newph < ph) {
                 sample = random(magnitude) - (magnitude >> 1);
             }
             ph = newph;
         }
         break;
     }
     phase_accumulator = ph - phase_offset;
     if (tone_offset) {
         bp = block->data;
         end = bp + AUDIO_BLOCK_SAMPLES;
         do {
             val1 = *bp;
             *bp++ = signed_saturate_rshift(val1 + tone_offset, 16, 0);
         } while (bp < end);
     }
     transmit(block, 0);
     release(block);
 }
References AudioStream::allocate(), arbdata, AudioWaveformSine, band_limit_waveform, audio_block_struct::data, magnitude, phase_accumulator, phase_increment, phase_offset, pulse_width, AudioStream::release(), sample, tone_offset, tone_type, AudioStream::transmit(), and val.
Referenced by erisAudioSynthWaveform::update(), and erisAudioSynthWaveform2k::update().