ERIS CORE: AudioSynthWaveform2k::begin
begin() [2/2]
void AudioSynthWaveform2k::begin (short t_type) inline inherited
Definition at line 95 of file eris_synth_waveform.h.
{
         phase_offset = 0;
         tone_type = t_type;
         if (t_type == WAVEFORM_BANDLIMIT_SQUARE)
           band_limit_waveform.init_square (phase_increment) ;
         else if (t_type == WAVEFORM_BANDLIMIT_PULSE)
           band_limit_waveform.init_pulse (phase_increment, pulse_width) ;
         else if (t_type == WAVEFORM_BANDLIMIT_SAWTOOTH || t_type == WAVEFORM_BANDLIMIT_SAWTOOTH_REVERSE)
           band_limit_waveform.init_sawtooth (phase_increment) ;
     }
References AudioSynthWaveform2k::band_limit_waveform, AudioSynthWaveform2k::phase_increment, AudioSynthWaveform2k::phase_offset, AudioSynthWaveform2k::pulse_width, and AudioSynthWaveform2k::tone_type.
Referenced by AudioSynthWaveform2k::begin(), AppCQT::init(), and SvcErisAudioParameterController::messageHandler().