ERIS CORE: AudioSynthWaveform2k::frequency
frequency()
void AudioSynthWaveform2k::frequency (float freq) inline inherited
Definition at line 49 of file eris_synth_waveform.h.
{
         if (freq < 0.0f) {
             freq = 0.0;
         } else if (freq > AUDIO_SAMPLE_RATE_EXACT / 2.0f) {
             freq = AUDIO_SAMPLE_RATE_EXACT / 2.0f;
         }
         phase_increment = freq * (4294967296.0f / AUDIO_SAMPLE_RATE_EXACT);
         if (phase_increment > 0x7FFE0000u) phase_increment = 0x7FFE0000;
     }
References AudioSynthWaveform2k::phase_increment.
Referenced by AudioSynthWaveform2k::begin(), AppAudioToPolyphonic::messageHandler(), SvcErisAudioParameterController::messageHandler(), and AppCQT::updateOscillatorBank().