ERIS CORE: ERISCore/lib/SdFat-master/src/common/FsStructs.h File Reference
FsStructs.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct biosParameterBlockExFat
struct biosParameterBlockFat16
struct biosParameterBlockFat32
struct DirBitmap_t
struct DirFat_t
struct DirFile_t
struct DirGeneric_t
struct DirLabel_t
struct DirLfn_t
struct DirName_t
struct DirStream_t
struct DirUpcase_t
struct ExFatBootSector
struct FsInfoSector
struct fspos_t
struct masterBootRecordSector
struct mbrPartition
struct partitionBootSector
struct partitionBootSectorFat
Typedefs
typedef struct biosParameterBlockExFat BpbExFat_t
typedef struct biosParameterBlockFat16 BpbFat16_t
typedef struct biosParameterBlockFat32 BpbFat32_t
typedef struct ExFatBootSector ExFatPbs_t
typedef struct FsInfoSector FsInfo_t
typedef struct mbrPartition MbrPart_t
typedef struct masterBootRecordSector MbrSector_t
typedef struct partitionBootSector pbs_t
typedef struct partitionBootSectorFat PbsFat_t
Functions
uint32_t exFatChecksum (uint32_t sum, uint8_t data)
uint16_t getLe16 (const uint8_t *src)
uint32_t getLe32 (const uint8_t *src)
uint64_t getLe64 (const uint8_t *src)
static bool isFileDir (const DirFat_t *dir)
static bool isFileOrSubdir (const DirFat_t *dir)
static uint8_t isLongName (const DirFat_t *dir)
static bool isSubdir (const DirFat_t *dir)
void lbaToMbrChs (uint8_t *chs, uint32_t capacityMB, uint32_t lba)
bool lfnReservedChar (uint8_t c)
void setLe16 (uint8_t *dst, uint16_t src)
void setLe32 (uint8_t *dst, uint32_t src)
void setLe64 (uint8_t *dst, uint64_t src)
bool sfnReservedChar (uint8_t c)
Variables
const uint8_t EXFAT_ATTRIB_ARCHIVE = 0x20
const uint8_t EXFAT_ATTRIB_DIRECTORY = 0x10
const uint8_t EXFAT_ATTRIB_HIDDEN = 0x02
const uint8_t EXFAT_ATTRIB_READ_ONLY = 0x01
const uint8_t EXFAT_ATTRIB_RESERVED = 0x08
const uint8_t EXFAT_ATTRIB_SYSTEM = 0x04
const uint32_t EXFAT_EOC = 0XFFFFFFFF
const uint8_t EXFAT_FLAG_ALWAYS1 = 0x01
const uint8_t EXFAT_FLAG_CONTIGUOUS = 0x02
const uint8_t EXFAT_MAX_NAME_LENGTH = 255
const uint8_t EXFAT_TYPE_BITMAP = 0X81
const uint8_t EXFAT_TYPE_FILE = 0X85
const uint8_t EXFAT_TYPE_LABEL = 0X83
const uint8_t EXFAT_TYPE_NAME = 0XC1
const uint8_t EXFAT_TYPE_STREAM = 0XC0
const uint8_t EXFAT_TYPE_UPCASE = 0X82
const uint8_t EXTENDED_BOOT_SIGNATURE = 0X29
const uint8_t FAT_ATTRIB_ARCHIVE = 0x20
const uint8_t FAT_ATTRIB_DIRECTORY = 0x10
const uint8_t FAT_ATTRIB_HIDDEN = 0x02
const uint8_t FAT_ATTRIB_LABEL = 0x08
const uint8_t FAT_ATTRIB_LONG_NAME = 0X0F
const uint8_t FAT_ATTRIB_READ_ONLY = 0x01
const uint8_t FAT_ATTRIB_SYSTEM = 0x04
const uint8_t FAT_CASE_LC_BASE = 0X08
const uint8_t FAT_CASE_LC_EXT = 0X10
const uint8_t FAT_MAX_LFN_LENGTH = 255
const uint8_t FAT_NAME_DELETED = 0XE5
const uint8_t FAT_NAME_FREE = 0X00
const uint8_t FAT_ORDER_LAST_LONG_ENTRY = 0X40
const size_t FS_DIR_SIZE = 32
const uint32_t FSINFO_LEAD_SIGNATURE = 0X41615252
const uint32_t FSINFO_STRUCT_SIGNATURE = 0x61417272
const uint32_t FSINFO_TRAIL_SIGNATURE = 0xAA550000
const uint16_t MBR_SIGNATURE = 0xAA55
const uint16_t PBR_SIGNATURE = 0xAA55
Typedef Documentation
BpbExFat_t
typedef struct biosParameterBlockExFat BpbExFat_t
BpbFat16_t
typedef struct biosParameterBlockFat16 BpbFat16_t
BpbFat32_t
typedef struct biosParameterBlockFat32 BpbFat32_t
ExFatPbs_t
typedef struct ExFatBootSector ExFatPbs_t
FsInfo_t
typedef struct FsInfoSector FsInfo_t
MbrPart_t
typedef struct mbrPartition MbrPart_t
MbrSector_t
typedef struct masterBootRecordSector MbrSector_t
pbs_t
typedef struct partitionBootSector pbs_t
PbsFat_t
typedef struct partitionBootSectorFat PbsFat_t
Function Documentation
exFatChecksum()
uint32_t exFatChecksum (uint32_t sum, uint8_t data) inline
Definition at line 296 of file FsStructs.h.
{
   return (sum << 31) + (sum >> 1) + data;
 }
References data.
Referenced by ExFatFormatter::format(), and ExFatFormatter::writeUpcaseByte().
getLe16()
uint16_t getLe16 (const uint8_t * src) inline
Definition at line 34 of file FsStructs.h.
{
   return *reinterpret_cast<const uint16_t*>(src);
 }
Referenced by ExFatPartition::checkUpcase(), ExFatFile::cmpName(), FatPartition::dmpFat(), FatPartition::fatGet(), FatFile::getAccessDate(), ExFatFile::getAccessDateTime(), ExFatFile::getCreateDateTime(), FatFile::getCreateDateTime(), getLfnChar(), FatFile::getLfnChar(), ExFatFile::getModifyDateTime(), FatFile::getModifyDateTime(), ExFatFile::getName7(), ExFatFile::getName8(), hashDir(), FatPartition::init(), FatFile::openCachedEntry(), ExFatFile::openPrivate(), FatFile::openSFN(), ExFatPartition::printDir(), printDirFile(), printDirName(), printDirStream(), printExFatBoot(), printFatDir(), printMbr(), ExFatFile::printName7(), ExFatFile::printName8(), and ExFatPartition::printUpcase().
getLe32()
uint32_t getLe32 (const uint8_t * src) inline
Definition at line 37 of file FsStructs.h.
{
   return *reinterpret_cast<const uint32_t*>(src);
 }
Referenced by ExFatPartition::checkUpcase(), FatPartition::dmpFat(), ExFatPartition::fatGet(), FatPartition::fatGet(), ExFatPartition::init(), FatPartition::init(), FatFile::openCachedEntry(), ExFatFile::openPrivate(), FatFile::openSFN(), printDirBitmap(), printDirFile(), printDirStream(), printDirUpcase(), printExFatBoot(), printFatDir(), printMbr(), ExFatPartition::printUpcase(), and ExFatPartition::printVolInfo().
getLe64()
uint64_t getLe64 (const uint8_t * src) inline
Definition at line 40 of file FsStructs.h.
{
   return *reinterpret_cast<const uint64_t*>(src);
 }
Referenced by ExFatPartition::checkUpcase(), ExFatFile::openPrivate(), printDirBitmap(), printDirStream(), printDirUpcase(), printExFatBoot(), and ExFatPartition::printUpcase().
isFileDir()
static bool isFileDir (const DirFat_t * dir) inline static
Definition at line 262 of file FsStructs.h.
{
   return (dir->attributes & (FAT_ATTRIB_DIRECTORY | FAT_ATTRIB_LABEL)) == 0;
 }
References DirFat_t::attributes, FAT_ATTRIB_DIRECTORY, and FAT_ATTRIB_LABEL.
Referenced by FatFile::openCachedEntry(), and FatFile::openSFN().
isFileOrSubdir()
static bool isFileOrSubdir (const DirFat_t * dir) inline static
Definition at line 265 of file FsStructs.h.
{
   return (dir->attributes & FAT_ATTRIB_LABEL) == 0;
 }
References DirFat_t::attributes, and FAT_ATTRIB_LABEL.
Referenced by FatFile::open(), FatFile::openCachedEntry(), FatFile::openNext(), FatFile::openSFN(), printFatDir(), FatFile::readDir(), FatFile::rmdir(), and FatFile::rmRfStar().
isLongName()
static uint8_t isLongName (const DirFat_t * dir) inline static
Definition at line 268 of file FsStructs.h.
{
   return dir->attributes == FAT_ATTRIB_LONG_NAME;
 }
References DirFat_t::attributes, and FAT_ATTRIB_LONG_NAME.
Referenced by FatFile::open(), FatFile::openNext(), FatFile::openSFN(), and printFatDir().
isSubdir()
static bool isSubdir (const DirFat_t * dir) inline static
Definition at line 271 of file FsStructs.h.
{
   return (dir->attributes & (FAT_ATTRIB_DIRECTORY | FAT_ATTRIB_LABEL))
           == FAT_ATTRIB_DIRECTORY;
 }
References DirFat_t::attributes, FAT_ATTRIB_DIRECTORY, and FAT_ATTRIB_LABEL.
lbaToMbrChs()
void lbaToMbrChs (uint8_t * chs, uint32_t capacityMB, uint32_t lba)
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 28 of file FsStructs.cpp.
{
   uint32_t c;
   uint8_t h;
   uint8_t s;
   uint8_t numberOfHeads;
   uint8_t sectorsPerTrack = capacityMB <= 256 ? 32 : 63;
   if (capacityMB <= 16) {
     numberOfHeads = 2;
   } else if (capacityMB <= 32) {
     numberOfHeads = 4;
   } else if (capacityMB <= 128) {
     numberOfHeads = 8;
   } else if (capacityMB <= 504) {
     numberOfHeads = 16;
   } else if (capacityMB <= 1008) {
     numberOfHeads = 32;
   } else if (capacityMB <= 2016) {
     numberOfHeads = 64;
   } else if (capacityMB <= 4032) {
     numberOfHeads = 128;
   } else {
     numberOfHeads = 255;
   }
   c = lba / (numberOfHeads * sectorsPerTrack);
   if (c <= 1023) {
     h = (lba % (numberOfHeads * sectorsPerTrack)) / sectorsPerTrack;
     s = (lba % sectorsPerTrack) + 1;
   } else {
     c = 1023;
     h = 254;
     s = 63;
   }
   chs[0] = h;
   chs[1] = ((c >> 2) & 0XC0) | s;
   chs[2] = c;
 }
References s.
Referenced by FatFormatter::writeMbr().
lfnReservedChar()
bool lfnReservedChar (uint8_t c) inline
Definition at line 99 of file FsStructs.h.
{
   return c < 0X20 || c == '"' || c == '*' || c == '/' || c == ':'
     || c == '<' || c == '>' || c == '?' || c == '\\'|| c == '|';
 }
Referenced by lfnLegalChar().
setLe16()
void setLe16 (uint8_t * dst, uint16_t src) inline
Definition at line 43 of file FsStructs.h.
{
   *reinterpret_cast<uint16_t*>(dst) = src;
 }
Referenced by FatPartition::fatPut(), ExFatFormatter::format(), FatFormatter::initPbs(), FatFormatter::makeFat16(), FatFormatter::makeFat32(), FatFile::mkdir(), FatFile::open(), ExFatFile::openPrivate(), FatFile::sync(), ExFatFile::syncDir(), ExFatFile::timestamp(), FatFile::timestamp(), and FatFormatter::writeMbr().
setLe32()
void setLe32 (uint8_t * dst, uint32_t src) inline
Definition at line 46 of file FsStructs.h.
{
   *reinterpret_cast<uint32_t*>(dst) = src;
 }
Referenced by ExFatPartition::fatPut(), FatPartition::fatPut(), ExFatFormatter::format(), FatFormatter::initPbs(), FatFormatter::makeFat16(), FatFormatter::makeFat32(), FatFile::sync(), ExFatFile::syncDir(), and FatFormatter::writeMbr().
setLe64()
void setLe64 (uint8_t * dst, uint64_t src) inline
Definition at line 49 of file FsStructs.h.
{
   *reinterpret_cast<uint64_t*>(dst) = src;
 }
Referenced by ExFatFormatter::format(), and ExFatFile::syncDir().
sfnReservedChar()
bool sfnReservedChar (uint8_t c) inline
Definition at line 105 of file FsStructs.h.
{
   if (c == '"' || c == '|' || c == '[' || c == '\\' || c == ']') {
     return true;
   }
   //  *+,./ or :;<=>?
   if ((0X2A <= c && c <= 0X2F && c != 0X2D) || (0X3A <= c && c <= 0X3F)) {
     return true;
   }
   // Reserved if not in range (0X20, 0X7F).
   return !(0X20 < c && c < 0X7F);
 }
Referenced by FatFile::parsePathName().
Variable Documentation
EXFAT_ATTRIB_ARCHIVE
const uint8_t EXFAT_ATTRIB_ARCHIVE = 0x20
Definition at line 363 of file FsStructs.h.
EXFAT_ATTRIB_DIRECTORY
const uint8_t EXFAT_ATTRIB_DIRECTORY = 0x10
Definition at line 362 of file FsStructs.h.
Referenced by ExFatFile::openPrivate().
EXFAT_ATTRIB_HIDDEN
const uint8_t EXFAT_ATTRIB_HIDDEN = 0x02
Definition at line 359 of file FsStructs.h.
EXFAT_ATTRIB_READ_ONLY
const uint8_t EXFAT_ATTRIB_READ_ONLY = 0x01
Definition at line 358 of file FsStructs.h.
EXFAT_ATTRIB_RESERVED
const uint8_t EXFAT_ATTRIB_RESERVED = 0x08
Definition at line 361 of file FsStructs.h.
EXFAT_ATTRIB_SYSTEM
const uint8_t EXFAT_ATTRIB_SYSTEM = 0x04
Definition at line 360 of file FsStructs.h.
EXFAT_EOC
const uint32_t EXFAT_EOC = 0XFFFFFFFF
Definition at line 328 of file FsStructs.h.
Referenced by ExFatFile::addCluster(), ExFatPartition::fatGet(), ExFatPartition::printFat(), and ExFatFile::truncate().
EXFAT_FLAG_ALWAYS1
const uint8_t EXFAT_FLAG_ALWAYS1 = 0x01
Definition at line 386 of file FsStructs.h.
Referenced by ExFatFile::openPrivate().
EXFAT_FLAG_CONTIGUOUS
const uint8_t EXFAT_FLAG_CONTIGUOUS = 0x02
Definition at line 387 of file FsStructs.h.
Referenced by ExFatFile::openPrivate(), and ExFatFile::syncDir().
EXFAT_MAX_NAME_LENGTH
const uint8_t EXFAT_MAX_NAME_LENGTH = 255
Definition at line 402 of file FsStructs.h.
Referenced by ExFatFile::hashName().
EXFAT_TYPE_BITMAP
const uint8_t EXFAT_TYPE_BITMAP = 0X81
Definition at line 330 of file FsStructs.h.
Referenced by ExFatFormatter::format(), and ExFatPartition::printDir().
EXFAT_TYPE_FILE
const uint8_t EXFAT_TYPE_FILE = 0X85
Definition at line 357 of file FsStructs.h.
Referenced by exFatDirChecksum(), ExFatFile::openPrivate(), ExFatPartition::printDir(), ExFatFile::syncDir(), and ExFatFile::timestamp().
EXFAT_TYPE_LABEL
const uint8_t EXFAT_TYPE_LABEL = 0X83
Definition at line 349 of file FsStructs.h.
Referenced by ExFatFormatter::format(), and ExFatPartition::printDir().
EXFAT_TYPE_NAME
const uint8_t EXFAT_TYPE_NAME = 0XC1
Definition at line 401 of file FsStructs.h.
Referenced by ExFatFile::getName7(), ExFatFile::getName8(), ExFatFile::openPrivate(), ExFatPartition::printDir(), ExFatFile::printName7(), ExFatFile::printName8(), ExFatFile::syncDir(), and ExFatFile::timestamp().
EXFAT_TYPE_STREAM
const uint8_t EXFAT_TYPE_STREAM = 0XC0
Definition at line 385 of file FsStructs.h.
Referenced by ExFatFile::openPrivate(), ExFatPartition::printDir(), ExFatFile::syncDir(), and ExFatFile::timestamp().
EXFAT_TYPE_UPCASE
const uint8_t EXFAT_TYPE_UPCASE = 0X82
Definition at line 339 of file FsStructs.h.
Referenced by ExFatPartition::checkUpcase(), ExFatFormatter::format(), ExFatPartition::printDir(), and ExFatPartition::printUpcase().
EXTENDED_BOOT_SIGNATURE
const uint8_t EXTENDED_BOOT_SIGNATURE = 0X29
Definition at line 153 of file FsStructs.h.
Referenced by FatFormatter::makeFat16(), and FatFormatter::makeFat32().
FAT_ATTRIB_ARCHIVE
const uint8_t FAT_ATTRIB_ARCHIVE = 0x20
Definition at line 240 of file FsStructs.h.
FAT_ATTRIB_DIRECTORY
const uint8_t FAT_ATTRIB_DIRECTORY = 0x10
Definition at line 239 of file FsStructs.h.
Referenced by isFileDir(), isSubdir(), and FatFile::mkdir().
FAT_ATTRIB_HIDDEN
const uint8_t FAT_ATTRIB_HIDDEN = 0x02
Definition at line 236 of file FsStructs.h.
FAT_ATTRIB_LABEL
const uint8_t FAT_ATTRIB_LABEL = 0x08
Definition at line 238 of file FsStructs.h.
Referenced by isFileDir(), isFileOrSubdir(), and isSubdir().
FAT_ATTRIB_LONG_NAME
const uint8_t FAT_ATTRIB_LONG_NAME = 0X0F
Definition at line 241 of file FsStructs.h.
Referenced by FatFile::getName7(), FatFile::getName8(), isLongName(), FatFile::open(), FatFile::printName7(), and FatFile::printName8().
FAT_ATTRIB_READ_ONLY
const uint8_t FAT_ATTRIB_READ_ONLY = 0x01
Definition at line 235 of file FsStructs.h.
FAT_ATTRIB_SYSTEM
const uint8_t FAT_ATTRIB_SYSTEM = 0x04
Definition at line 237 of file FsStructs.h.
FAT_CASE_LC_BASE
const uint8_t FAT_CASE_LC_BASE = 0X08
Filename base-name is all lower case
Definition at line 243 of file FsStructs.h.
Referenced by FatFile::getSFN(), and FatFile::open().
FAT_CASE_LC_EXT
const uint8_t FAT_CASE_LC_EXT = 0X10
Filename extension is all lower case.
Definition at line 245 of file FsStructs.h.
Referenced by FatFile::getSFN(), and FatFile::open().
FAT_MAX_LFN_LENGTH
const uint8_t FAT_MAX_LFN_LENGTH = 255
Max long file name length
Definition at line 284 of file FsStructs.h.
FAT_NAME_DELETED
const uint8_t FAT_NAME_DELETED = 0XE5
name[0] value for entry that is free after being "deleted"
Definition at line 232 of file FsStructs.h.
Referenced by FatFile::openNext(), printFatDir(), FatFile::readDir(), FatFile::remove(), FatFile::rmdir(), FatFile::rmRfStar(), and FatFile::sync().
FAT_NAME_FREE
const uint8_t FAT_NAME_FREE = 0X00
name[0] value for entry that is free and no allocated entries follow
Definition at line 234 of file FsStructs.h.
Referenced by FatFile::open(), FatFile::openNext(), FatFile::readDir(), FatFile::rmdir(), and FatFile::rmRfStar().
FAT_ORDER_LAST_LONG_ENTRY
const uint8_t FAT_ORDER_LAST_LONG_ENTRY = 0X40
Order mask that indicates the entry is the last long dir entry in a set of long dir entries. All valid sets of long dir entries must begin with an entry having this mask.
Definition at line 281 of file FsStructs.h.
Referenced by FatFile::open(), FatFile::openNext(), and FatFile::openSFN().
FS_DIR_SIZE
const size_t FS_DIR_SIZE = 32
Definition at line 96 of file FsStructs.h.
Referenced by ExFatFile::dirCache(), FatPartition::dirEntriesPerCluster(), ExFatFile::dirIndex(), FatFile::dirSize(), FatPartition::init(), ExFatFile::open(), FatFile::openNext(), ExFatFile::openPrivate(), ExFatPartition::printDir(), FatFile::read(), FatFile::readDirCache(), ExFatFile::rmdir(), and FatFile::rmRfStar().
FSINFO_LEAD_SIGNATURE
const uint32_t FSINFO_LEAD_SIGNATURE = 0X41615252
Definition at line 218 of file FsStructs.h.
Referenced by FatFormatter::makeFat32().
FSINFO_STRUCT_SIGNATURE
const uint32_t FSINFO_STRUCT_SIGNATURE = 0x61417272
Definition at line 219 of file FsStructs.h.
Referenced by FatFormatter::makeFat32().
FSINFO_TRAIL_SIGNATURE
const uint32_t FSINFO_TRAIL_SIGNATURE = 0xAA550000
Definition at line 220 of file FsStructs.h.
Referenced by FatFormatter::makeFat32().
MBR_SIGNATURE
const uint16_t MBR_SIGNATURE = 0xAA55
Definition at line 117 of file FsStructs.h.
Referenced by ExFatFormatter::format(), and FatFormatter::writeMbr().
PBR_SIGNATURE
const uint16_t PBR_SIGNATURE = 0xAA55
Definition at line 118 of file FsStructs.h.
Referenced by ExFatFormatter::format(), and FatFormatter::initPbs().