ERIS CORE: wren_primitive.h File Reference
wren_primitive.h File Reference
#include "wren_vm.h"
Macros
#define DEF_PRIMITIVE(name) static bool prim_##name(WrenVM* vm, Value* args)
#define FUNCTION_CALL(cls, name, function)
#define PRIMITIVE(cls, name, function)
#define RETURN_BOOL(value) RETURN_VAL(BOOL_VAL(value))
#define RETURN_ERROR(msg)
#define RETURN_ERROR_FMT(...)
#define RETURN_FALSE RETURN_VAL(FALSE_VAL)
#define RETURN_NULL RETURN_VAL(NULL_VAL)
#define RETURN_NUM(value) RETURN_VAL(NUM_VAL(value))
#define RETURN_OBJ(obj) RETURN_VAL(OBJ_VAL(obj))
#define RETURN_TRUE RETURN_VAL(TRUE_VAL)
#define RETURN_VAL(value)
Functions
uint32_t calculateRange (WrenVM *vm, ObjRange *range, uint32_t *length, int *step)
bool validateFn (WrenVM *vm, Value arg, const char *argName)
uint32_t validateIndex (WrenVM *vm, Value arg, uint32_t count, const char *argName)
bool validateInt (WrenVM *vm, Value arg, const char *argName)
bool validateIntValue (WrenVM *vm, double value, const char *argName)
bool validateKey (WrenVM *vm, Value arg)
bool validateNum (WrenVM *vm, Value arg, const char *argName)
bool validateString (WrenVM *vm, Value arg, const char *argName)
Macro Definition Documentation
DEF_PRIMITIVE
#define DEF_PRIMITIVE (name) static bool prim_##name(WrenVM* vm, Value* args)
Definition at line 35 of file wren_primitive.h.
FUNCTION_CALL
#define FUNCTION_CALL (cls, name, function)
Value:
    do                                                                         \
    {                                                                          \
      int symbol = wrenSymbolTableEnsure(vm,                                   \
          &vm->methodNames, name, strlen(name));                               \
      Method method;                                                           \
      method.type = METHOD_FUNCTION_CALL;                                      \
      method.as.primitive = prim_##function;                                   \
      wrenBindMethod(vm, cls, symbol, method);                                 \
    } while (false)
Definition at line 21 of file wren_primitive.h.
PRIMITIVE
#define PRIMITIVE (cls, name, function)
Value:
    do                                                                         \
    {                                                                          \
      int symbol = wrenSymbolTableEnsure(vm,                                   \
          &vm->methodNames, name, strlen(name));                               \
      Method method;                                                           \
      method.type = METHOD_PRIMITIVE;                                          \
      method.as.primitive = prim_##function;                                   \
      wrenBindMethod(vm, cls, symbol, method);                                 \
    } while (false)
Definition at line 8 of file wren_primitive.h.
RETURN_BOOL
#define RETURN_BOOL (value) RETURN_VAL(BOOL_VAL(value))
Definition at line 46 of file wren_primitive.h.
RETURN_ERROR
#define RETURN_ERROR (msg)
Value:
    do                                                                         \
    {                                                                          \
      vm->fiber->error = wrenNewStringLength(vm, msg, sizeof(msg) - 1);        \
      return false;                                                            \
    } while (false)
Definition at line 52 of file wren_primitive.h.
RETURN_ERROR_FMT
#define RETURN_ERROR_FMT (...)
Value:
    do                                                                         \
    {                                                                          \
      vm->fiber->error = wrenStringFormat(vm, __VA_ARGS__);                    \
      return false;                                                            \
    } while (false)
Definition at line 59 of file wren_primitive.h.
RETURN_FALSE
#define RETURN_FALSE RETURN_VAL(FALSE_VAL)
Definition at line 47 of file wren_primitive.h.
RETURN_NULL
#define RETURN_NULL RETURN_VAL(NULL_VAL)
Definition at line 48 of file wren_primitive.h.
RETURN_NUM
#define RETURN_NUM (value) RETURN_VAL(NUM_VAL(value))
Definition at line 49 of file wren_primitive.h.
RETURN_OBJ
#define RETURN_OBJ (obj) RETURN_VAL(OBJ_VAL(obj))
Definition at line 45 of file wren_primitive.h.
RETURN_TRUE
#define RETURN_TRUE RETURN_VAL(TRUE_VAL)
Definition at line 50 of file wren_primitive.h.
RETURN_VAL
#define RETURN_VAL (value)
Value:
    do                                                                         \
    {                                                                          \
      args[0] = value;                                                         \
      return true;                                                             \
    } while (false)
Definition at line 38 of file wren_primitive.h.
Function Documentation
calculateRange()
uint32_t calculateRange (WrenVM * vm, ObjRange * range, uint32_t * length, int * step)
Definition at line 68 of file wren_primitive.c.
 {
   *step = 0;
   // Edge case: an empty range is allowed at the end of a sequence. This way,
   // list[0..-1] and list[0...list.count] can be used to copy a list even when
   // empty.
   if (range->from == *length &&
       range->to == (range->isInclusive ? -1.0 : (double)*length))
   {
     *length = 0;
     return 0;
   }
   uint32_t from = validateIndexValue(vm, *length, range->from, "Range start");
   if (from == UINT32_MAX) return UINT32_MAX;
   // Bounds check the end manually to handle exclusive ranges.
   double value = range->to;
   if (!validateIntValue(vm, value, "Range end")) return UINT32_MAX;
   // Negative indices count from the end.
   if (value < 0) value = *length + value;
   // Convert the exclusive range to an inclusive one.
   if (!range->isInclusive)
   {
     // An exclusive range with the same start and end points is empty.
     if (value == from)
     {
       *length = 0;
       return from;
     }
     // Shift the endpoint to make it inclusive, handling both increasing and
     // decreasing ranges.
     value += value >= from ? -1 : 1;
   }
   // Check bounds.
   if (value < 0 || value >= *length)
   {
     vm->fiber->error = CONST_STRING(vm, "Range end out of bounds.");
     return UINT32_MAX;
   }
   uint32_t to = (uint32_t)value;
   *length = abs((int)(from - to)) + 1;
   *step = from < to ? 1 : -1;
   return from;
 }
References CONST_STRING, sObjFiber::error, WrenVM::fiber, ObjRange::from, ObjRange::isInclusive, ObjRange::to, validateIndexValue(), and validateIntValue().
Referenced by DEF_PRIMITIVE().
validateFn()
bool validateFn (WrenVM * vm, Value arg, const char * argName)
Definition at line 23 of file wren_primitive.c.
 {
   if (IS_CLOSURE(arg)) return true;
   RETURN_ERROR_FMT("$ must be a function.", argName);
 }
References IS_CLOSURE, and RETURN_ERROR_FMT.
Referenced by DEF_PRIMITIVE().
validateIndex()
uint32_t validateIndex (WrenVM * vm, Value arg, uint32_t count, const char * argName)
Definition at line 55 of file wren_primitive.c.
 {
   if (!validateNum(vm, arg, argName)) return UINT32_MAX;
   return validateIndexValue(vm, count, AS_NUM(arg), argName);
 }
References AS_NUM, count, validateIndexValue(), and validateNum().
Referenced by DEF_PRIMITIVE().
validateInt()
bool validateInt (WrenVM * vm, Value arg, const char * argName)
Definition at line 41 of file wren_primitive.c.
 {
   // Make sure it's a number first.
   if (!validateNum(vm, arg, argName)) return false;
   return validateIntValue(vm, AS_NUM(arg), argName);
 }
References AS_NUM, validateIntValue(), and validateNum().
Referenced by DEF_PRIMITIVE().
validateIntValue()
bool validateIntValue (WrenVM * vm, double value, const char * argName)
Definition at line 35 of file wren_primitive.c.
 {
   if (trunc(value) == value) return true;
   RETURN_ERROR_FMT("$ must be an integer.", argName);
 }
References RETURN_ERROR_FMT.
Referenced by calculateRange(), validateIndexValue(), and validateInt().
validateKey()
bool validateKey (WrenVM * vm, Value arg)
Definition at line 48 of file wren_primitive.c.
 {
   if (wrenMapIsValidKey(arg)) return true;
   RETURN_ERROR("Key must be a value type.");
 }
References RETURN_ERROR, and wrenMapIsValidKey().
Referenced by DEF_PRIMITIVE(), wrenGetMapContainsKey(), wrenRemoveMapValue(), and wrenSetMapValue().
validateNum()
bool validateNum (WrenVM * vm, Value arg, const char * argName)
Definition at line 29 of file wren_primitive.c.
 {
   if (IS_NUM(arg)) return true;
   RETURN_ERROR_FMT("$ must be a number.", argName);
 }
References IS_NUM, and RETURN_ERROR_FMT.
Referenced by DEF_PRIMITIVE(), validateIndex(), and validateInt().
validateString()
bool validateString (WrenVM * vm, Value arg, const char * argName)
Definition at line 62 of file wren_primitive.c.
 {
   if (IS_STRING(arg)) return true;
   RETURN_ERROR_FMT("$ must be a string.", argName);
 }
References IS_STRING, and RETURN_ERROR_FMT.
Referenced by DEF_PRIMITIVE().