ERIS CORE: D:/brian/Dev/Eris/ERISCore/include/AppManager.h File Reference
AppManager.h File Reference
#include <Arduino.h>
#include "HSI.h"
#include "touch.h"
#include "ILI9341_t3_ERIS.h"
#include "AudioDirector.h"
Classes
class AppBaseClass
class AppManager
Macros
#define ENABLE_ASYNC_SCREEN_UPDATES
#define MAX_NAME_LENGTH 24
Functions
ILI9341_t3_ERIS tft (TFT_CS, TFT_DC, TFT_RESET, TFT_MOSI, TFT_SCLK, TFT_MISO)
Touch touch (CS_TOUCH)
Variables
AudioDirector ad
const ILI9341_t3_font_t Arial_9
Macro Definition Documentation
ENABLE_ASYNC_SCREEN_UPDATES
#define ENABLE_ASYNC_SCREEN_UPDATES
Definition at line 5 of file AppManager.h.
MAX_NAME_LENGTH
#define MAX_NAME_LENGTH 24
Definition at line 4 of file AppManager.h.
Function Documentation
tft()
ILI9341_t3_ERIS tft (TFT_CS , TFT_DC , TFT_RESET , TFT_MOSI , TFT_SCLK , TFT_MISO)
Referenced by Checkerboard::init(), Cube3D::init(), MagentaSquares::init(), PlasmaCloud::init(), PlasmaYellow::init(), Sphere3D::init(), TransitionScroll::init(), TriangleWeb::init(), TwistyText::init(), Waveform::init(), MyAppExample::onTouch(), MyAppExample::onTouchDrag(), MyAppExample::onTouchRelease(), Checkerboard::perFrame(), Cube3D::perFrame(), Leaves::perFrame(), MagentaSquares::perFrame(), PlasmaCloud::perFrame(), PlasmaYellow::perFrame(), Sphere3D::perFrame(), TransitionDither::perFrame(), TransitionHalftone::perFrame(), TransitionScroll::perFrame(), TransitionSquares::perFrame(), TriangleWeb::perFrame(), TwistyText::perFrame(), Waveform::perFrame(), TransitionScroll::restart(), AppButton::update(), AppCQT::update(), MyAppExample::update(), AppManager::update(), AppScope::update(), and AppSlider::update().
touch()
Touch touch (CS_TOUCH)
Referenced by setup(), and AppManager::update().
Variable Documentation
ad
AudioDirector ad
Definition at line 21 of file AppManager.h.
Referenced by AppCQT::AppCQT(), AppScope::AppScope(), MyAppExample::MyAppExample(), MyAppExample::MessageHandler(), setup(), and AppSerialCommandInterface::updateRT().
Arial_9
const ILI9341_t3_font_t Arial_9 extern
Definition at line 208 of file ili9341_t3n_font_Arial.c.
Referenced by AppButton::update().