ERIS CORE: erisAudioAnalyzeScope::trigger
trigger() [2/2]
void erisAudioAnalyzeScope::trigger (void)
Definition at line 248 of file eris_analyze_scope.cpp.
 {
     h_div = auto_h_div;
     if (count ==0){ //ignore external trigger requests if already capturing
         if (delay_length > 0) {
             count = delay_length;
             state = STATE_DELAY;
         } else {
             count = mem_length;
             state = STATE_PRINTING;
         }
     }
 }
References auto_h_div, count, delay_length, h_div, mem_length, and state.
Referenced by AppScope::AppScope(), available(), and update().