ERIS CORE: SdCardFactory Class Reference
SdCardFactory Class Reference
Setup a SPI card or SDIO card.
#include <SdCard.h>
Public Member Functions
SdCard * newCard (SdioConfig config)
SdCard * newCard (SdSpiConfig config)
Detailed Description
Setup a SPI card or SDIO card.
Definition at line 50 of file SdCard.h.
Member Function Documentation
newCard() [1/2]
SdCard* SdCardFactory::newCard (SdioConfig config) inline
Initialize SDIO card.
Parameters
[in] config SDIO configuration.
Returns
generic card pointer or nullptr if SDIO is not supported.
Definition at line 66 of file SdCard.h.
{
 #if HAS_SDIO_CLASS
     m_sdioCard.begin(config);
     return &m_sdioCard;
 #else  // HAS_SDIO_CLASS
     (void)config;
     return nullptr;
 #endif  // HAS_SDIO_CLASS
   }
References SdSpiCard::begin(), and config.
newCard() [2/2]
SdCard* SdCardFactory::newCard (SdSpiConfig config) inline
Initialize SPI card.
Parameters
[in] config SPI configuration.
Returns
generic card pointer.
Definition at line 57 of file SdCard.h.
{
     m_spiCard.begin(config);
     return &m_spiCard;
   }
References SdSpiCard::begin(), and config.
Referenced by SdBase< Vol >::cardBegin().
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/SdCard/SdCard.h