ErisCore: UI Class Reference
UI Class Reference
#include <UI.h>
Public Member Functions
UI ()
void Setup (SdFatSdioEX *sdfat)
void Update ()
void LoadPreset ()
void setDisplayMessageWithValue (char *message, uint16_t value)
void setDisplayMessage (char *message)
float getControlValueFloat (const char *control_name)
uint16_t getControlValue (const char *control_name)
void setCCValue (uint8_t cc_id, uint8_t value)
void setControlValue (const char *control_name, uint16_t value)
void setControlModSource (const char *control_name, uint16_t value)
void setControlModInvert (const char *control_name, uint16_t value)
void setControlModGain (const char *control_name, uint16_t value)
void setModulatorInput (uint8_t modulator_index, float modulator_value)
uint8_t getMenuIndex (uint8_t menu_index_id)
const char * getActiveMenuName ()
uint8_t getUpdateStep ()
void setpFFT (uint16_t *fft_bin_array)
void setpCQT (CQT *p_cqt)
void setpScope (int16_t *oscope_array)
void setTapLED (bool state)
Public Attributes
uint16_t knob1_pos
uint16_t knob2_pos
uint16_t knob3_pos
uint16_t knob4_pos
uint16_t expin_pos
float level_in_r
float level_in_l
float level_out_r
float level_out_l
Constructor & Destructor Documentation
UI()
UI::UI ()
References EDITMODE_VALUE, ENC1_A_SW, ENC2_A_SW, ENC2_B_SW, initUICData(), INPUT, isr_enc1_change(), isr_enc2_change(), level_in_l, level_in_r, level_out_l, level_out_r, MENU_TITLE_SHOW_TIME, NULL, OUTPUT, RIBBON_SHOW_TIME, TFT_LED_PWM, ui_menus, uic_ribbon_image, uic_ribbon_image_folder, uic_ribbon_image_select, and uic_ribbon_image_select_folder.
Member Function Documentation
getActiveMenuName()
const char * UI::getActiveMenuName ()
References getMenuIndex(), and UIMenuType::menu_name.
getControlValue()
uint16_t UI::getControlValue (const char * control_name)
References UICType::mod_source, UICType::mod_value, NULL, and UICType::value.
getControlValueFloat()
float UI::getControlValueFloat (const char * control_name)
References UICType::max_value, UICType::mod_source, UICType::mod_value, NULL, and UICType::value.
getMenuIndex()
uint8_t UI::getMenuIndex (uint8_t menu_index_id)
References raw2c::i, and index.
getUpdateStep()
uint8_t UI::getUpdateStep ()
LoadPreset()
void UI::LoadPreset ()
References FatFile::close(), FatFile::fgets(), getControlValue(), index, NULL, O_READ, FatFile::open(), setControlModGain(), setControlModInvert(), setControlModSource(), setControlValue(), setDisplayMessageWithValue(), and value.
setCCValue()
void UI::setCCValue (uint8_t cc_id, uint8_t value)
References UICType::max_value, min_value, UICType::min_value, NULL, value, and UICType::value.
setControlModGain()
void UI::setControlModGain (const char * control_name, uint16_t value)
References UICType::mod_gain, NULL, and value.
setControlModInvert()
void UI::setControlModInvert (const char * control_name, uint16_t value)
References UICType::mod_invert, NULL, and value.
setControlModSource()
void UI::setControlModSource (const char * control_name, uint16_t value)
References UICType::mod_source, NULL, and value.
setControlValue()
void UI::setControlValue (const char * control_name, uint16_t value)
References UICType::max_value, min_value, UICType::min_value, NULL, value, and UICType::value.
setDisplayMessage()
void UI::setDisplayMessage (char * message)
References MESSAGE_SHOW_TIME.
setDisplayMessageWithValue()
void UI::setDisplayMessageWithValue (char * message, uint16_t value)
References MESSAGE_SHOW_TIME, and value.
setModulatorInput()
void UI::setModulatorInput (uint8_t modulator_index, float modulator_value)
References controls, UIMenuType::controls, UIMenuType::controls_count, raw2c::i, max_value, UICType::max_value, min_value, UICType::min_value, mod_gain, mod_invert, mod_source, UICType::mod_value, and value.
setpCQT()
void UI::setpCQT (CQT * p_cqt)
setpFFT()
void UI::setpFFT (uint16_t * fft_bin_array)
setpScope()
void UI::setpScope (int16_t * oscope_array)
setTapLED()
void UI::setTapLED (bool state)
Setup()
void UI::Setup (SdFatSdioEX * sdfat)
References FatFile::close(), FB, FatFile::fgets(), raw2c::i, ILI9341_BLACK, ILI9341_YELLOW, O_READ, FatFile::open(), FatFile::read(), tft, TFT_LED_PWM, uic_ribbon_icon_height, uic_ribbon_icon_width, and uic_tab.
Update()
void UI::Update ()
References controls, UIMenuType::controls, controls_count, EDITMODE_MODGAIN, EDITMODE_MODINVERT, EDITMODE_REALTIMEMONITOR, EDITMODE_VALUE, FPS_FONT, getMenuIndex(), index, LoadPreset(), max_value, UICType::max_value, menu_name, MENU_TITLE_SHOW_TIME, MESSAGE_FONT, min_value, UICType::min_value, UICType::mod_gain, mod_invert, UICType::mod_invert, mod_source, UICType::mod_source, UICType::mod_value, NUM_MOD_SOURCES, RIBBON_SHOW_TIME, SCREEN_SLEEP_TIME, setDisplayMessage(), tft, TFT_LED_PWM, value, and UICType::value.
Member Data Documentation
expin_pos
uint16_t UI::expin_pos
knob1_pos
uint16_t UI::knob1_pos
knob2_pos
uint16_t UI::knob2_pos
knob3_pos
uint16_t UI::knob3_pos
knob4_pos
uint16_t UI::knob4_pos
level_in_l
float UI::level_in_l
level_in_r
float UI::level_in_r
level_out_l
float UI::level_out_l
level_out_r
float UI::level_out_r
The documentation for this class was generated from the following files:
UI.h
UI.txt