ErisCore: PrintBasic Class Reference
PrintBasic Class Reference abstract
#include <PrintBasic.h>
Public Member Functions
PrintBasic ()
void clearWriteError ()
int getWriteError ()
size_t print (char c)
size_t print (const char *str)
size_t print (const __FlashStringHelper *str)
size_t println (const __FlashStringHelper *str)
size_t print (double n, uint8_t prec=2)
size_t print (signed char n, uint8_t base=10)
size_t print (unsigned char n, uint8_t base=10)
size_t print (int n, uint8_t base=10)
size_t print (unsigned int n, uint8_t base=10)
size_t print (long n, uint8_t base=10)
size_t print (unsigned long n, uint8_t base=10)
size_t println ()
size_t println (char c)
size_t println (const char *str)
size_t println (double n, uint8_t prec=2)
size_t println (signed char n, uint8_t base=10)
size_t println (unsigned char n, uint8_t base=10)
size_t println (int n, uint8_t base=10)
size_t println (unsigned int n, uint8_t base=10)
size_t println (long n, uint8_t base=10)
size_t println (unsigned long n, uint8_t base=10)
size_t write (const char *str)
virtual size_t write (uint8_t b)=0
virtual size_t write (const uint8_t *buffer, size_t size)
size_t write (const char *buffer, size_t size)
Protected Member Functions
void setWriteError (int err=1)
Constructor & Destructor Documentation
PrintBasic()
PrintBasic::PrintBasic () inline
Member Function Documentation
clearWriteError()
void PrintBasic::clearWriteError () inline
References setWriteError().
getWriteError()
int PrintBasic::getWriteError () inline
print() [1/10]
size_t PrintBasic::print (char c) inline
References write().
print() [2/10]
size_t PrintBasic::print (const __FlashStringHelper * str) inline
print() [3/10]
size_t PrintBasic::print (const char * str) inline
References write().
print() [4/10]
size_t PrintBasic::print (double n, uint8_t prec = 2) inline
print() [5/10]
size_t PrintBasic::print (int n, uint8_t base = 10) inline
References print().
print() [6/10]
size_t PrintBasic::print (long n, uint8_t base = 10)
Copyright (c) 2011-2019 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
References print().
print() [7/10]
size_t PrintBasic::print (signed char n, uint8_t base = 10) inline
References print().
print() [8/10]
size_t PrintBasic::print (unsigned char n, uint8_t base = 10) inline
References print().
print() [9/10]
size_t PrintBasic::print (unsigned int n, uint8_t base = 10) inline
References print().
print() [10/10]
size_t PrintBasic::print (unsigned long n, uint8_t base = 10) inline
println() [1/11]
size_t PrintBasic::println () inline
References write().
println() [2/11]
size_t PrintBasic::println (char c) inline
References println(), and write().
println() [3/11]
size_t PrintBasic::println (const __FlashStringHelper * str) inline
References print(), and println().
println() [4/11]
size_t PrintBasic::println (const char * str) inline
References print(), and println().
println() [5/11]
size_t PrintBasic::println (double n, uint8_t prec = 2) inline
References print(), and println().
println() [6/11]
size_t PrintBasic::println (int n, uint8_t base = 10) inline
References print(), and println().
println() [7/11]
size_t PrintBasic::println (long n, uint8_t base = 10) inline
References print(), and println().
println() [8/11]
size_t PrintBasic::println (signed char n, uint8_t base = 10) inline
References print(), and println().
println() [9/11]
size_t PrintBasic::println (unsigned char n, uint8_t base = 10) inline
References print(), and println().
println() [10/11]
size_t PrintBasic::println (unsigned int n, uint8_t base = 10) inline
References print(), and println().
println() [11/11]
size_t PrintBasic::println (unsigned long n, uint8_t base = 10) inline
References print(), and println().
setWriteError()
void PrintBasic::setWriteError (int err = 1) inline protected
write() [1/4]
size_t PrintBasic::write (const char * buffer, size_t size) inline
References write().
write() [2/4]
size_t PrintBasic::write (const char * str) inline
write() [3/4]
virtual size_t PrintBasic::write (const uint8_t * buffer, size_t size) inline virtual
References raw2c::i, and write().
write() [4/4]
virtual size_t PrintBasic::write (uint8_t b) pure virtual
The documentation for this class was generated from the following files:
PrintBasic.h
PrintBasic.cpp