ErisCore: ofstream Class Reference
ofstream Class Reference
file output stream.
#include <fstream.h>
Public Member Functions
ofstream ()
ofstream (const char *path, openmode mode=out)
void clear (iostate state=goodbit)
void close ()
void open (const char *path, openmode mode=out)
bool is_open ()
Public Member Functions inherited from ostream
ostream ()
ostream & operator<< (ostream &(*pf)(ostream &str))
ostream & operator<< (ios_base &(*pf)(ios_base &str))
ostream & operator<< (bool arg)
ostream & operator<< (const char *arg)
ostream & operator<< (const signed char *arg)
ostream & operator<< (const unsigned char *arg)
ostream & operator<< (const String &arg)
ostream & operator<< (char arg)
ostream & operator<< (signed char arg)
ostream & operator<< (unsigned char arg)
ostream & operator<< (double arg)
ostream & operator<< (float arg)
ostream & operator<< (short arg)
ostream & operator<< (unsigned short arg)
ostream & operator<< (int arg)
ostream & operator<< (unsigned int arg)
ostream & operator<< (long arg)
ostream & operator<< (unsigned long arg)
ostream & operator<< (const void *arg)
ostream & operator<< (const __FlashStringHelper *arg)
ostream & put (char ch)
ostream & flush ()
pos_type tellp ()
ostream & seekp (pos_type pos)
ostream & seekp (off_type off, seekdir way)
Public Member Functions inherited from ios
ios ()
operator const void * () const
bool operator! () const
operator bool () const
iostate rdstate () const
bool good () const
bool eof () const
bool fail () const
bool bad () const
void clear (iostate state=goodbit)
void setstate (iostate state)
Public Member Functions inherited from ios_base
ios_base ()
char fill ()
char fill (char c)
fmtflags flags () const
fmtflags flags (fmtflags fl)
int precision () const
int precision (unsigned int n)
fmtflags setf (fmtflags fl)
fmtflags setf (fmtflags fl, fmtflags mask)
void unsetf (fmtflags fl)
unsigned width ()
unsigned width (unsigned n)
Additional Inherited Members
Public Types inherited from ios_base
enum seekdir { beg, cur, end }
typedef unsigned char iostate
typedef uint32_t streamsize
typedef uint32_t pos_type
typedef int32_t off_type
typedef unsigned int fmtflags
typedef uint8_t openmode
Static Public Attributes inherited from ios_base
static const iostate goodbit = 0x00
static const iostate badbit = 0X01
static const iostate eofbit = 0x02
static const iostate failbit = 0X04
static const fmtflags left = 0x0001
static const fmtflags right = 0x0002
static const fmtflags internal = 0x0004
static const fmtflags dec = 0x0008
static const fmtflags hex = 0x0010
static const fmtflags oct = 0x0020
static const fmtflags boolalpha = 0x0100
static const fmtflags showbase = 0x0200
static const fmtflags showpoint = 0x0400
static const fmtflags showpos = 0x0800
static const fmtflags skipws = 0x1000
static const fmtflags uppercase = 0x4000
static const fmtflags adjustfield = left | right | internal
static const fmtflags basefield = dec | hex | oct
static const openmode app = 0X4
static const openmode ate = 0X8
static const openmode binary = 0X10
static const openmode in = 0X20
static const openmode out = 0X40
static const openmode trunc = 0X80
Protected Member Functions inherited from ios_base
uint8_t flagsToBase ()
Detailed Description
file output stream.
Constructor & Destructor Documentation
ofstream() [1/2]
ofstream::ofstream () inline
ofstream() [2/2]
ofstream::ofstream (const char * path, openmode mode = out) inline explicit
Constructor with open
Parameters
[in] path file to open
[in] mode open mode
References mode, and open().
Member Function Documentation
clear()
void ofstream::clear (iostate state = goodbit) inline
Clear state and writeError
Parameters
[in] state new state for stream
References ios::clear(), and StreamBaseClass::clearWriteError().
close()
void ofstream::close () inline
Close a file and force cached data and directory information to be written to the storage device.
References FatFile::close().
is_open()
bool ofstream::is_open () inline
Returns
True if stream is open else false.
References FatFile::isOpen().
open()
void ofstream::open (const char * path, openmode mode = out) inline
Open an ofstream
Parameters
[in] path file to open
[in] mode open mode
mode See fstream::open() for valid modes.
References mode, StreamBaseClass::open(), and ios_base::out.
The documentation for this class was generated from the following file:
fstream.h