ErisCore: TwistyText Class Reference
TwistyText Class Reference
#include <TwistyText.h>
Public Member Functions
TwistyText ()
void init (ILI9341_t3n tft)
uint_fast16_t bgColor (void)
String title ()
void reset (ILI9341_t3n tft)
boolean willForceTransition (void)
boolean forceTransitionNow (void)
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
Public Member Functions inherited from BaseAnimation
BaseAnimation ()
Constructor & Destructor Documentation
TwistyText()
TwistyText::TwistyText () inline
Member Function Documentation
bgColor()
uint_fast16_t TwistyText::bgColor (void) virtual
Reimplemented from BaseAnimation.
forceTransitionNow()
boolean TwistyText::forceTransitionNow (void) virtual
Reimplemented from BaseAnimation.
References LINE_COUNT.
init()
void TwistyText::init (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
References tft.
perFrame()
void TwistyText::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseAnimation.
References FrameParams::audioPeak, bit, CHARS_PER_LINE, raw2c::f, FONT_TABLE, FONT_TABLE_LENGTH, left(), lerp(), lerp8(), LINE_COUNT, LINE_SCROLL_SPEED, LINES, pgm_read_byte, TEXT_3D_THICKNESS_MULT, TEXT_PIXEL_HEIGHT, TEXT_PIXEL_WIDTH, tft, FrameParams::timeMult, TWIST_AMOUNT, raw2c::w, WOBBLE_AMOUNT, WOBBLE_FREQ, and WOBBLE_TORQUE.
reset()
void TwistyText::reset (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
References LINE_COUNT.
title()
String TwistyText::title () virtual
Reimplemented from BaseAnimation.
willForceTransition()
boolean TwistyText::willForceTransition (void) virtual
Reimplemented from BaseAnimation.
The documentation for this class was generated from the following file:
TwistyText.h