ErisCore: MyAppExample Class Reference
MyAppExample Class Reference
#include <appExample.h>
Public Member Functions
MyAppExample ()
void update ()
void onTouch (uint16_t x, uint16_t y)
void onTouchRelease (uint16_t x, uint16_t y)
void onTouchDrag (uint16_t x, uint16_t y)
void MessageHandler (AppBaseClass *sender, const char *message)
Public Member Functions inherited from AppBaseClass
AppBaseClass ()
uint16_t getId ()
bool isName (const char *name_string)
void setName (const char *name_string)
void setParent (AppBaseClass *parent)
void setPosition (int16_t newOriginX, int16_t newOriginY)
void setDimension (int16_t new_width, int16_t new_height)
virtual void updateRT ()
virtual void onFocus ()
virtual void onFocusLost ()
Public Attributes
AppButton * button
AppSlider * slider
int16_t x_end
int16_t x_start
int16_t y_end
int16_t y_start
int16_t x_last
int16_t y_last
int16_t y_last_scope
unsigned long t_lastupdate
erisAudioAnalyzeFFT1024 * fft
erisAudioAnalyzeFFT1024 * fft2
erisAudioAnalyzeScope * scope
Public Attributes inherited from AppBaseClass
int16_t origin_x
int16_t origin_y
int16_t width
int16_t height
char name [16]
Additional Inherited Members
Protected Attributes inherited from AppBaseClass
AppBaseClass * parentNode
AppBaseClass * previousAppicationNode
AppBaseClass * nextAppicationNode
ILI9341_t3_ERIS * _tft
bool touch_state
uint16_t id
Constructor & Destructor Documentation
MyAppExample()
MyAppExample::MyAppExample () inline
References ad, AudioMemoryUsageMaxReset, AudioProcessorUsageMaxReset, button, erisAudioAnalyzeFFT1024::enableFFT(), fft, fft2, AudioDirector::getAudioStreamObjByName(), AppBaseClass::height, AppBaseClass::origin_x, AppBaseClass::origin_y, scope, AppBaseClass::setDimension(), AppBaseClass::setName(), AppBaseClass::setParent(), AppBaseClass::setPosition(), slider, t_lastupdate, AppButton::text, AppSlider::text, erisAudioAnalyzeFFT1024::toggleActiveRange(), erisAudioAnalyzeScope::trigger(), AppSlider::value, AppBaseClass::width, x, and y.
Member Function Documentation
MessageHandler()
void MyAppExample::MessageHandler (AppBaseClass * sender, const char * message) inline virtual
Reimplemented from AppBaseClass.
References ad, AudioDirector::connect(), AudioDirector::disconnect(), fft, AudioDirector::getAudioStreamObjByName(), AppBaseClass::isName(), slider, and AppSlider::value.
onTouch()
void MyAppExample::onTouch (uint16_t x, uint16_t y) inline virtual
Reimplemented from AppBaseClass.
References tft, x, x_last, x_start, y, y_last, and y_start.
onTouchDrag()
void MyAppExample::onTouchDrag (uint16_t x, uint16_t y) inline virtual
Reimplemented from AppBaseClass.
References ILI9341_BLUE, ILI9341_ORANGE, ILI9341_RED, ILI9341_WHITE, ILI9341_YELLOW, tft, x, x_last, y, and y_last.
onTouchRelease()
void MyAppExample::onTouchRelease (uint16_t x, uint16_t y) inline virtual
Reimplemented from AppBaseClass.
References ILI9341_ORANGE, tft, x, x_end, x_last, x_start, y, y_end, y_last, and y_start.
update()
void MyAppExample::update () inline virtual
Reimplemented from AppBaseClass.
References x, and y.
Member Data Documentation
button
AppButton* MyAppExample::button
fft
erisAudioAnalyzeFFT1024* MyAppExample::fft
fft2
erisAudioAnalyzeFFT1024* MyAppExample::fft2
scope
erisAudioAnalyzeScope* MyAppExample::scope
slider
AppSlider* MyAppExample::slider
t_lastupdate
unsigned long MyAppExample::t_lastupdate
x_end
int16_t MyAppExample::x_end
x_last
int16_t MyAppExample::x_last
x_start
int16_t MyAppExample::x_start
y_end
int16_t MyAppExample::y_end
y_last
int16_t MyAppExample::y_last
y_last_scope
int16_t MyAppExample::y_last_scope
y_start
int16_t MyAppExample::y_start
The documentation for this class was generated from the following file:
appExample.h