ErisCore: SdFat32 Class Reference
SdFat32 Class Reference
SD file system class for FAT volumes.
#include <SdFat-beta.h>
Public Member Functions
bool format (print_t *pr=nullptr)
Public Member Functions inherited from SdBase< FatVolume >
bool begin (SdCsPin_t csPin=SS)
bool begin (SdCsPin_t csPin, uint32_t maxSck)
bool begin (SdSpiConfig spiConfig)
bool begin (SdioConfig sdioConfig)
SdCard * card ()
bool cardBegin (SdSpiConfig spiConfig)
bool cardBegin (SdioConfig sdioConfig)
void errorHalt (print_t *pr)
void errorHalt (print_t *pr, const char *msg)
void errorHalt (print_t *pr, const __FlashStringHelper *msg)
void errorHalt (const __FlashStringHelper *msg)
void errorHalt ()
void errorHalt (const char *msg)
void initErrorHalt (print_t *pr)
void initErrorHalt (print_t *pr, const char *msg)
void initErrorHalt (Print *pr, const __FlashStringHelper *msg)
void initErrorHalt ()
void initErrorHalt (const char *msg)
void initErrorHalt (const __FlashStringHelper *msg)
void initErrorPrint (Print *pr)
void initErrorPrint ()
void printFatType (print_t *pr)
void errorPrint (print_t *pr)
void errorPrint (print_t *pr, char const *msg)
void errorPrint (Print *pr, const __FlashStringHelper *msg)
void errorPrint (const char *msg)
void errorPrint (const __FlashStringHelper *msg)
void printSdError (print_t *pr)
uint8_t sdErrorCode ()
uint8_t sdErrorData ()
FatVolume * vol ()
bool volumeBegin ()
Public Member Functions inherited from FatVolume
bool begin (BlockDevice *dev, bool setCwv=true, uint8_t part=1)
void chvol ()
bool chdir ()
bool chdir (const char *path)
bool exists (const char *path)
bool ls (print_t *pr, uint8_t flags=0)
bool ls (print_t *pr, const char *path, uint8_t flags)
bool mkdir (const char *path, bool pFlag=true)
File32 open (const char *path, oflag_t oflag=O_RDONLY)
bool remove (const char *path)
bool rename (const char *oldPath, const char *newPath)
bool rmdir (const char *path)
bool truncate (const char *path, uint32_t length)
bool ls (uint8_t flags=0)
bool ls (const char *path, uint8_t flags=0)
bool chdir (const String &path)
bool exists (const String &path)
bool mkdir (const String &path, bool pFlag=true)
File32 open (const String &path, oflag_t oflag=O_RDONLY)
bool remove (const String &path)
bool rename (const String &oldPath, const String &newPath)
bool rmdir (const String &path)
bool truncate (const String &path, uint32_t length)
Public Member Functions inherited from FatPartition
FatPartition ()
uint8_t bytesPerClusterShift ()
uint16_t bytesPerCluster ()
uint16_t bytesPerSector ()
uint8_t bytesPerSectorShift ()
uint16_t sectorMask ()
uint8_t sectorsPerCluster () const
uint8_t blocksPerCluster () __attribute__((deprecated))
uint32_t sectorsPerFat () const
cache_t * cacheClear ()
uint32_t clusterCount () const
uint8_t sectorsPerClusterShift () const
uint32_t dataStartSector () const
uint8_t fatCount ()
uint32_t fatStartSector () const
uint8_t fatType () const
int32_t freeClusterCount ()
bool init (BlockDevice *dev, uint8_t part=1)
uint16_t rootDirEntryCount () const
uint32_t rootDirStart () const
uint32_t volumeSectorCount () const
int8_t dbgFat (uint32_t n, uint32_t *v)
void dmpDirSector (print_t *pr, uint32_t sector)
void dmpFat (print_t *pr, uint32_t start, uint32_t count)
void dmpRootDir (print_t *pr)
void dmpSector (print_t *pr, uint32_t sector, uint8_t bits=8)
Additional Inherited Members
Static Public Member Functions inherited from FatVolume
static FatVolume * cwv ()
Detailed Description
SD file system class for FAT volumes.
Member Function Documentation
format()
bool SdFat32::format (print_t * pr = nullptr) inline
Format a SD card FAT32/FAT16.
Parameters
[in] pr Optional Print information.
Returns
true for success or false for failure.
References FatPartition::cacheClear(), SdBase< FatVolume >::card(), and FatFormatter::format().
The documentation for this class was generated from the following file:
SdFat-beta.h