ErisCore: fstream Class Reference
fstream Class Reference
file input/output stream.
#include <fstream.h>
Public Member Functions
fstream ()
fstream (const char *path, openmode mode=in|out)
void clear (iostate state=goodbit)
void close ()
void open (const char *path, openmode mode=in|out)
bool is_open ()
Public Member Functions inherited from istream
istream ()
istream & operator>> (istream &(*pf)(istream &str))
istream & operator>> (ios_base &(*pf)(ios_base &str))
istream & operator>> (ios &(*pf)(ios &str))
istream & operator>> (char *str)
istream & operator>> (char &ch)
istream & operator>> (signed char *str)
istream & operator>> (signed char &ch)
istream & operator>> (unsigned char *str)
istream & operator>> (unsigned char &ch)
istream & operator>> (bool &arg)
istream & operator>> (short &arg)
istream & operator>> (unsigned short &arg)
istream & operator>> (int &arg)
istream & operator>> (unsigned int &arg)
istream & operator>> (long &arg)
istream & operator>> (unsigned long &arg)
istream & operator>> (double &arg)
istream & operator>> (float &arg)
istream & operator>> (void *&arg)
streamsize gcount () const
int get ()
istream & get (char &ch)
istream & get (char *str, streamsize n, char delim='\n')
istream & getline (char *str, streamsize n, char delim='\n')
istream & ignore (streamsize n=1, int delim=-1)
int peek ()
pos_type tellg ()
istream & seekg (pos_type pos)
istream & seekg (off_type off, seekdir way)
void skipWhite ()
Public Member Functions inherited from ios
ios ()
operator const void * () const
bool operator! () const
operator bool () const
iostate rdstate () const
bool good () const
bool eof () const
bool fail () const
bool bad () const
void clear (iostate state=goodbit)
void setstate (iostate state)
Public Member Functions inherited from ios_base
ios_base ()
char fill ()
char fill (char c)
fmtflags flags () const
fmtflags flags (fmtflags fl)
int precision () const
int precision (unsigned int n)
fmtflags setf (fmtflags fl)
fmtflags setf (fmtflags fl, fmtflags mask)
void unsetf (fmtflags fl)
unsigned width ()
unsigned width (unsigned n)
Public Member Functions inherited from ostream
ostream ()
ostream & operator<< (ostream &(*pf)(ostream &str))
ostream & operator<< (ios_base &(*pf)(ios_base &str))
ostream & operator<< (bool arg)
ostream & operator<< (const char *arg)
ostream & operator<< (const signed char *arg)
ostream & operator<< (const unsigned char *arg)
ostream & operator<< (const String &arg)
ostream & operator<< (char arg)
ostream & operator<< (signed char arg)
ostream & operator<< (unsigned char arg)
ostream & operator<< (double arg)
ostream & operator<< (float arg)
ostream & operator<< (short arg)
ostream & operator<< (unsigned short arg)
ostream & operator<< (int arg)
ostream & operator<< (unsigned int arg)
ostream & operator<< (long arg)
ostream & operator<< (unsigned long arg)
ostream & operator<< (const void *arg)
ostream & operator<< (const __FlashStringHelper *arg)
ostream & put (char ch)
ostream & flush ()
pos_type tellp ()
ostream & seekp (pos_type pos)
ostream & seekp (off_type off, seekdir way)
Additional Inherited Members
Public Types inherited from ios_base
enum seekdir { beg, cur, end }
typedef unsigned char iostate
typedef uint32_t streamsize
typedef uint32_t pos_type
typedef int32_t off_type
typedef unsigned int fmtflags
typedef uint8_t openmode
Static Public Attributes inherited from ios_base
static const iostate goodbit = 0x00
static const iostate badbit = 0X01
static const iostate eofbit = 0x02
static const iostate failbit = 0X04
static const fmtflags left = 0x0001
static const fmtflags right = 0x0002
static const fmtflags internal = 0x0004
static const fmtflags dec = 0x0008
static const fmtflags hex = 0x0010
static const fmtflags oct = 0x0020
static const fmtflags boolalpha = 0x0100
static const fmtflags showbase = 0x0200
static const fmtflags showpoint = 0x0400
static const fmtflags showpos = 0x0800
static const fmtflags skipws = 0x1000
static const fmtflags uppercase = 0x4000
static const fmtflags adjustfield = left | right | internal
static const fmtflags basefield = dec | hex | oct
static const openmode app = 0X4
static const openmode ate = 0X8
static const openmode binary = 0X10
static const openmode in = 0X20
static const openmode out = 0X40
static const openmode trunc = 0X80
Protected Member Functions inherited from ios_base
uint8_t flagsToBase ()
Detailed Description
file input/output stream.
Constructor & Destructor Documentation
fstream() [1/2]
fstream::fstream () inline
fstream() [2/2]
fstream::fstream (const char * path, openmode mode = in | out) inline explicit
Constructor with open
Parameters
[in] path file to open
[in] mode open mode
References mode, and open().
Member Function Documentation
clear()
void fstream::clear (iostate state = goodbit) inline
Clear state and writeError
Parameters
[in] state new state for stream
References ios::clear(), and StreamBaseClass::clearWriteError().
close()
void fstream::close () inline
Close a file and force cached data and directory information to be written to the storage device.
References FatFile::close().
is_open()
bool fstream::is_open () inline
Returns
True if stream is open else false.
References FatFile::isOpen().
open()
void fstream::open (const char * path, openmode mode = in | out) inline
Open a fstream
Parameters
[in] path path to open
[in] mode open mode
Valid open modes are (at end, ios::ate, and/or ios::binary may be added):
ios::in - Open file for reading.
ios::out or ios::out | ios::trunc - Truncate to 0 length, if existent, or create a file for writing only.
ios::app or ios::out | ios::app - Append; open or create file for writing at end-of-file.
ios::in | ios::out - Open file for update (reading and writing).
ios::in | ios::out | ios::trunc - Truncate to zero length, if existent, or create file for update.
ios::in | ios::app or ios::in | ios::out | ios::app - Append; open or create text file for update, writing at end of file.
References mode, and StreamBaseClass::open().
The documentation for this class was generated from the following file:
fstream.h