ERIS CORE: wren_debug.h File Reference
wren_debug.h File Reference
#include "wren_value.h"
#include "wren_vm.h"
Functions
void wrenDebugPrintStackTrace (WrenVM *vm)
void wrenDumpCode (WrenVM *vm, ObjFn *fn)
int wrenDumpInstruction (WrenVM *vm, ObjFn *fn, int i)
void wrenDumpStack (ObjFiber *fiber)
void wrenDumpValue (Value value)
Function Documentation
wrenDebugPrintStackTrace()
void wrenDebugPrintStackTrace (WrenVM * vm)
Definition at line 5 of file wren_debug.c.
 {
   // Bail if the host doesn't enable printing errors.
   if (vm->config.errorFn == NULL) return;
   ObjFiber* fiber = vm->fiber;
   if (IS_STRING(fiber->error))
   {
     vm->config.errorFn(vm, WREN_ERROR_RUNTIME,
                        NULL, -1, AS_CSTRING(fiber->error));
   }
   else
   {
     // TODO: Print something a little useful here. Maybe the name of the error's
     // class?
     vm->config.errorFn(vm, WREN_ERROR_RUNTIME,
                        NULL, -1, "[error object]");
   }
   for (int i = fiber->numFrames - 1; i >= 0; i--)
   {
     CallFrame* frame = &fiber->frames[i];
     ObjFn* fn = frame->closure->fn;
     // Skip over stub functions for calling methods from the C API.
     if (fn->module == NULL) continue;
     // The built-in core module has no name. We explicitly omit it from stack
     // traces since we don't want to highlight to a user the implementation
     // detail of what part of the core module is written in C and what is Wren.
     if (fn->module->name == NULL) continue;
     // -1 because IP has advanced past the instruction that it just executed.
     int line = fn->debug->sourceLines.data[frame->ip - fn->code.data - 1];
     vm->config.errorFn(vm, WREN_ERROR_STACK_TRACE,
                        fn->module->name->value, line,
                        fn->debug->name);
   }
 }
References AS_CSTRING, CallFrame::closure, WrenVM::config, WrenConfiguration::errorFn, fiber, WrenVM::fiber, fn, ObjClosure::fn, CallFrame::ip, IS_STRING, NULL, WREN_ERROR_RUNTIME, and WREN_ERROR_STACK_TRACE.
Referenced by runtimeError().
wrenDumpCode()
void wrenDumpCode (WrenVM * vm, ObjFn * fn)
Definition at line 361 of file wren_debug.c.
 {
   printf("%s: %s\n",
          fn->module->name == NULL ? "<core>" : fn->module->name->value,
          fn->debug->name);
   int i = 0;
   int lastLine = -1;
   for (;;)
   {
     int offset = dumpInstruction(vm, fn, i, &lastLine);
     if (offset == -1) break;
     i += offset;
   }
   printf("\n");
 }
References dumpInstruction(), fn, and NULL.
Referenced by endCompiler().
wrenDumpInstruction()
int wrenDumpInstruction (WrenVM * vm, ObjFn * fn, int i)
Definition at line 356 of file wren_debug.c.
 {
   return dumpInstruction(vm, fn, i, NULL);
 }
References dumpInstruction(), fn, and NULL.
wrenDumpStack()
void wrenDumpStack (ObjFiber * fiber)
Definition at line 379 of file wren_debug.c.
 {
   printf("(fiber %p) ", fiber);
   for (Value* slot = fiber->stack; slot < fiber->stackTop; slot++)
   {
     wrenDumpValue(*slot);
     printf(" | ");
   }
   printf("\n");
 }
References fiber, and wrenDumpValue().
wrenDumpValue()
void wrenDumpValue (Value value)
Definition at line 67 of file wren_debug.c.
 {
 #if WREN_NAN_TAGGING
   if (IS_NUM(value))
   {
     printf("%.14g", AS_NUM(value));
   }
   else if (IS_OBJ(value))
   {
     dumpObject(AS_OBJ(value));
   }
   else
   {
     switch (GET_TAG(value))
     {
       case TAG_FALSE:     printf("false"); break;
       case TAG_NAN:       printf("NaN"); break;
       case TAG_NULL:      printf("null"); break;
       case TAG_TRUE:      printf("true"); break;
       case TAG_UNDEFINED: UNREACHABLE();
     }
   }
 #else
   switch (value.type)
   {
     case VAL_FALSE:     printf("false"); break;
     case VAL_NULL:      printf("null"); break;
     case VAL_NUM:       printf("%.14g", AS_NUM(value)); break;
     case VAL_TRUE:      printf("true"); break;
     case VAL_OBJ:       dumpObject(AS_OBJ(value)); break;
     case VAL_UNDEFINED: UNREACHABLE();
   }
 #endif
 }
References AS_NUM, AS_OBJ, dumpObject(), GET_TAG, IS_NUM, IS_OBJ, TAG_FALSE, TAG_NAN, TAG_NULL, TAG_TRUE, TAG_UNDEFINED, and UNREACHABLE.
Referenced by blackenObject(), dumpInstruction(), wrenDumpStack(), and wrenFreeObj().