ERIS CORE: D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/MathUtil.h File Reference
MathUtil.h File Reference
Classes
struct Point16
struct PointF
struct PointU16
struct PointU8
Functions
float lerp (float a, float b, float progress)
uint_fast8_t lerp8 (uint_fast8_t a, uint_fast8_t b, float progress)
Point16 xyz2screen (float x, float y, float z, uint_fast16_t screenW_2, uint_fast16_t screenH_2)
Function Documentation
lerp()
float lerp (float a, float b, float progress)
Definition at line 29 of file MathUtil.h.
{
     return a + (b-a)*progress;
 }
Referenced by MagentaSquares::perFrame(), and TwistyText::perFrame().
lerp8()
uint_fast8_t lerp8 (uint_fast8_t a, uint_fast8_t b, float progress)
Definition at line 24 of file MathUtil.h.
{
     // Cast to int, avoid horrible values when b-a is less than zero
     return a + (int_fast8_t)((int_fast8_t)b-(int_fast8_t)a)*progress;
 }
Referenced by Checkerboard::perFrame(), Cube3D::perFrame(), PlasmaYellow::perFrame(), TriangleWeb::perFrame(), and TwistyText::perFrame().
xyz2screen()
Point16 xyz2screen (float x, float y, float z, uint_fast16_t screenW_2, uint_fast16_t screenH_2)
Definition at line 38 of file MathUtil.h.
{
     float invZ = 1.0f / z;
     return (Point16){
         (int_fast16_t)(screenW_2 + x*invZ*screenW_2),
         (int_fast16_t)(screenH_2 + y*invZ*screenW_2)
     };
 }
References x, and y.
Referenced by Sphere3D::init(), and Cube3D::perFrame().