ERIS CORE: cpplint.FileInfo Class Reference
cpplint.FileInfo Class Reference
Public Member Functions
def __init__ (self, filename)
def BaseName (self)
def Extension (self)
def FullName (self)
def IsSource (self)
def NoExtension (self)
def RepositoryName (self)
def Split (self)
Private Attributes
_filename
Detailed Description
Provides utility functions for filenames.
FileInfo provides easy access to the components of a file's path
relative to the project root.
Definition at line 1097 of file cpplint.py.
Constructor & Destructor Documentation
__init__()
def cpplint.FileInfo.__init__ (self, filename)
Definition at line 1104 of file cpplint.py.
   def __init__(self, filename):
     self._filename = filename
Member Function Documentation
BaseName()
def cpplint.FileInfo.BaseName (self)
File base name - text after the final slash, before the final period.
Definition at line 1171 of file cpplint.py.
   def BaseName(self):
     """File base name - text after the final slash, before the final period."""
     return self.Split()[1]
References cpplint.FileInfo.Split().
Extension()
def cpplint.FileInfo.Extension (self)
File extension - text following the final period.
Definition at line 1175 of file cpplint.py.
   def Extension(self):
     """File extension - text following the final period."""
     return self.Split()[2]
References cpplint.FileInfo.Split().
Referenced by cpplint.FileInfo.IsSource().
FullName()
def cpplint.FileInfo.FullName (self)
Make Windows paths like Unix.
Definition at line 1107 of file cpplint.py.
   def FullName(self):
     """Make Windows paths like Unix."""
     return os.path.abspath(self._filename).replace('\\', '/')
References cpplint.FileInfo._filename.
Referenced by cpplint.FileInfo.RepositoryName().
IsSource()
def cpplint.FileInfo.IsSource (self)
File has a source file extension.
Definition at line 1183 of file cpplint.py.
   def IsSource(self):
     """File has a source file extension."""
     return _IsSourceExtension(self.Extension()[1:])
References cpplint._IsSourceExtension(), and cpplint.FileInfo.Extension().
NoExtension()
def cpplint.FileInfo.NoExtension (self)
File has no source file extension.
Definition at line 1179 of file cpplint.py.
   def NoExtension(self):
     """File has no source file extension."""
     return '/'.join(self.Split()[0:2])
References cpplint.FileInfo.Split().
RepositoryName()
def cpplint.FileInfo.RepositoryName (self)
FullName after removing the local path to the repository.
If we have a real absolute path name here we can try to do something smart:
detecting the root of the checkout and truncating /path/to/checkout from
the name so that we get header guards that don't include things like
"C:\Documents and Settings\..." or "/home/username/..." in them and thus
people on different computers who have checked the source out to different
locations won't see bogus errors.
Definition at line 1111 of file cpplint.py.
   def RepositoryName(self):
     """FullName after removing the local path to the repository.
     If we have a real absolute path name here we can try to do something smart:
     detecting the root of the checkout and truncating /path/to/checkout from
     the name so that we get header guards that don't include things like
     "C:\Documents and Settings\..." or "/home/username/..." in them and thus
     people on different computers who have checked the source out to different
     locations won't see bogus errors.
     """
     fullname = self.FullName()
     if os.path.exists(fullname):
       project_dir = os.path.dirname(fullname)
       if os.path.exists(os.path.join(project_dir, ".svn")):
         # If there's a .svn file in the current directory, we recursively look
         # up the directory tree for the top of the SVN checkout
         root_dir = project_dir
         one_up_dir = os.path.dirname(root_dir)
         while os.path.exists(os.path.join(one_up_dir, ".svn")):
           root_dir = os.path.dirname(root_dir)
           one_up_dir = os.path.dirname(one_up_dir)
         prefix = os.path.commonprefix([root_dir, project_dir])
         return fullname[len(prefix) + 1:]
       # Not SVN <= 1.6? Try to find a git, hg, or svn top level directory by
       # searching up from the current path.
       root_dir = current_dir = os.path.dirname(fullname)
       while current_dir != os.path.dirname(current_dir):
         if (os.path.exists(os.path.join(current_dir, ".git")) or
             os.path.exists(os.path.join(current_dir, ".hg")) or
             os.path.exists(os.path.join(current_dir, ".svn"))):
           root_dir = current_dir
         current_dir = os.path.dirname(current_dir)
       if (os.path.exists(os.path.join(root_dir, ".git")) or
           os.path.exists(os.path.join(root_dir, ".hg")) or
           os.path.exists(os.path.join(root_dir, ".svn"))):
         prefix = os.path.commonprefix([root_dir, project_dir])
         return fullname[len(prefix) + 1:]
     # Don't know what to do; header guard warnings may be wrong...
     return fullname
References cpplint.FileInfo.FullName().
Referenced by cpplint.FileInfo.Split().
Split()
def cpplint.FileInfo.Split (self)
Splits the file into the directory, basename, and extension.
For 'chrome/browser/browser.cc', Split() would
return ('chrome/browser', 'browser', '.cc')
Returns:
  A tuple of (directory, basename, extension).
Definition at line 1157 of file cpplint.py.
   def Split(self):
     """Splits the file into the directory, basename, and extension.
     For 'chrome/browser/browser.cc', Split() would
     return ('chrome/browser', 'browser', '.cc')
     Returns:
       A tuple of (directory, basename, extension).
     """
     googlename = self.RepositoryName()
     project, rest = os.path.split(googlename)
     return (project,) + os.path.splitext(rest)
References cpplint.FileInfo.RepositoryName().
Referenced by cpplint.FileInfo.BaseName(), cpplint.FileInfo.Extension(), and cpplint.FileInfo.NoExtension().
Member Data Documentation
_filename
cpplint.FileInfo._filename private
Definition at line 1105 of file cpplint.py.
Referenced by cpplint.FileInfo.FullName().
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/extras/cpplint.py