ERIS CORE: ExFatFile Class Reference
ExFatFile Class Reference
Basic file class.
#include <ExFatFile.h>
Public Member Functions
ExFatFile ()
ExFatFile (const char *path, oflag_t oflag)
int available ()
uint64_t available64 ()
void clearError ()
void clearWriteError ()
bool close ()
bool contiguousRange (uint32_t *bgnSector, uint32_t *endSector)
uint64_t curPosition () const
uint64_t dataLength () const
uint32_t dirIndex () const
bool exists (const char *path)
void fgetpos (fspos_t *pos) const
int fgets (char *str, int num, char *delim=nullptr)
uint64_t fileSize () const
uint32_t firstSector () const
void flush ()
void fsetpos (const fspos_t *pos)
bool getAccessDateTime (uint16_t *pdate, uint16_t *ptime)
bool getCreateDateTime (uint16_t *pdate, uint16_t *ptime)
uint8_t getError () const
bool getModifyDateTime (uint16_t *pdate, uint16_t *ptime)
size_t getName (char *name, size_t size)
size_t getName7 (char *name, size_t size)
size_t getName8 (char *name, size_t size)
bool getWriteError () const
bool isBusy ()
bool isContiguous () const
bool isDir () const
bool isFile () const
bool isHidden () const
bool isOpen () const
bool isReadable () const
bool isReadOnly () const
bool isRoot () const
bool isSubDir () const
bool isWritable () const
bool ls (print_t *pr)
bool ls (print_t *pr, uint8_t flags, uint8_t indent=0)
bool mkdir (ExFatFile *parent, const char *path, bool pFlag=true)
bool open (const char *path, oflag_t oflag=O_RDONLY)
bool open (ExFatFile *dirFile, const char *path, oflag_t oflag)
bool open (ExFatFile *dirFile, uint32_t index, oflag_t oflag)
bool open (ExFatVolume *vol, const char *path, oflag_t oflag)
bool openNext (ExFatFile *dirFile, oflag_t oflag=O_RDONLY)
bool openRoot (ExFatVolume *vol)
operator bool ()
int peek ()
bool preAllocate (uint64_t length)
size_t printAccessDateTime (print_t *pr)
size_t printCreateDateTime (print_t *pr)
size_t printField (double value, char term, uint8_t prec=2)
size_t printField (float value, char term, uint8_t prec=2)
template<typename Type >
size_t printField (Type value, char term)
size_t printFileSize (print_t *pr)
size_t printModifyDateTime (print_t *pr)
size_t printName (print_t *pr)
size_t printName7 (print_t *pr)
size_t printName8 (print_t *pr)
int read ()
int read (void *buf, size_t count)
bool remove ()
bool remove (const char *path)
bool rename (const char *newPath)
bool rename (ExFatFile *dirFile, const char *newPath)
void rewind ()
bool rmdir ()
bool seekCur (int64_t offset)
bool seekEnd (int64_t offset=0)
bool seekSet (uint64_t pos)
uint8_t setCount () const
bool sync ()
bool timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
bool truncate ()
bool truncate (uint64_t length)
uint64_t validLength () const
size_t write (const char *str)
size_t write (const void *buf, size_t count)
size_t write (uint8_t b)
Private Member Functions
bool addCluster ()
bool addDirCluster ()
bool cmpName (const DirName_t *dirName, ExName_t *fname)
uint32_t curCluster () const
uint8_t * dirCache (uint8_t set, uint8_t options)
bool hashName (ExName_t *fname)
bool mkdir (ExFatFile *parent, ExName_t *fname)
bool openPrivate (ExFatFile *dir, ExName_t *fname, oflag_t oflag)
bool parsePathName (const char *path, ExName_t *fname, const char **ptr)
bool syncDir ()
ExFatVolume * volume () const
Private Attributes
uint8_t m_attributes = FILE_ATTR_CLOSED
uint32_t m_curCluster
uint64_t m_curPosition
uint64_t m_dataLength
DirPos_t m_dirPos
uint8_t m_error = 0
uint32_t m_firstCluster
uint8_t m_flags = 0
uint8_t m_setCount
uint64_t m_validLength
ExFatVolume * m_vol
Static Private Attributes
static const uint8_t FILE_ATTR_ARCHIVE = EXFAT_ATTRIB_ARCHIVE
static const uint8_t FILE_ATTR_CLOSED = 0
static const uint8_t FILE_ATTR_COPY
static const uint8_t FILE_ATTR_DIR = FILE_ATTR_SUBDIR | FILE_ATTR_ROOT
static const uint8_t FILE_ATTR_FILE = 0X08
static const uint8_t FILE_ATTR_HIDDEN = EXFAT_ATTRIB_HIDDEN
static const uint8_t FILE_ATTR_READ_ONLY = EXFAT_ATTRIB_READ_ONLY
static const uint8_t FILE_ATTR_ROOT = 0X40
static const uint8_t FILE_ATTR_SUBDIR = EXFAT_ATTRIB_DIRECTORY
static const uint8_t FILE_ATTR_SYSTEM = EXFAT_ATTRIB_SYSTEM
static const uint8_t FILE_FLAG_APPEND = 0X08
static const uint8_t FILE_FLAG_CONTIGUOUS = 0X40
static const uint8_t FILE_FLAG_DIR_DIRTY = 0X80
static const uint8_t FILE_FLAG_READ = 0X01
static const uint8_t FILE_FLAG_WRITE = 0X02
static const uint8_t READ_ERROR = 0X2
static const uint8_t WRITE_ERROR = 0X1
Friends
class ExFatVolume
Detailed Description
Basic file class.
Definition at line 60 of file ExFatFile.h.
Constructor & Destructor Documentation
ExFatFile() [1/2]
ExFatFile::ExFatFile () inline
Create an instance.
Definition at line 63 of file ExFatFile.h.
 {}
ExFatFile() [2/2]
ExFatFile::ExFatFile (const char * path, oflag_t oflag) inline
Create a file object and open it in the current working directory.
Parameters
[in] path A path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of open flags. see FatFile::open(FatFile*, const char*, uint8_t).
Definition at line 71 of file ExFatFile.h.
{
     open(path, oflag);
   }
References open().
Member Function Documentation
addCluster()
bool ExFatFile::addCluster () private
Definition at line 71 of file ExFatFileWrite.cpp.
{
   uint32_t find = m_vol->bitmapFind(m_curCluster ?  m_curCluster + 1 : 0, 1);
   if (find < 2) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!m_vol->bitmapModify(find, 1, 1)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (m_curCluster == 0) {
     m_flags |= FILE_FLAG_CONTIGUOUS;
     goto done;
   }
   if (isContiguous()) {
     if (find == (m_curCluster + 1)) {
       goto done;
     }
     // No longer contiguous so make FAT chain.
     m_flags &= ~FILE_FLAG_CONTIGUOUS;
     for (uint32_t c = m_firstCluster; c < m_curCluster; c++) {
       if (!m_vol->fatPut(c, c + 1)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   }
   // New cluster is EOC.
   if (!m_vol->fatPut(find, EXFAT_EOC)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Connect new cluster to existing chain.
   if (m_curCluster) {
     if (!m_vol->fatPut(m_curCluster, find)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
  done:
   m_curCluster = find;
   return true;
  fail:
   return false;
 }
References ExFatPartition::bitmapFind(), ExFatPartition::bitmapModify(), DBG_FAIL_MACRO, EXFAT_EOC, ExFatPartition::fatPut(), FILE_FLAG_CONTIGUOUS, isContiguous(), m_curCluster, m_firstCluster, m_flags, and m_vol.
Referenced by addDirCluster(), and write().
addDirCluster()
bool ExFatFile::addDirCluster () private
Definition at line 120 of file ExFatFileWrite.cpp.
{
   uint32_t sector;
   uint32_t dl = isRoot() ? m_vol->rootLength() : m_dataLength;
   uint8_t* cache;
   dl += m_vol->bytesPerCluster();
   if (dl >= 0X4000000) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!addCluster()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   sector = m_vol->clusterStartSector(m_curCluster);
   for (uint32_t i = 0; i  < m_vol->sectorsPerCluster(); i++) {
     cache = m_vol->dataCachePrepare(sector + i,
                                     FsCache::CACHE_RESERVE_FOR_WRITE);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     memset(cache, 0, m_vol->bytesPerSector());
   }
   if (!isRoot()) {
     m_flags |= FILE_FLAG_DIR_DIRTY;
     m_dataLength  += m_vol->bytesPerCluster();
     m_validLength += m_vol->bytesPerCluster();
   }
   return sync();
  fail:
   return false;
 }
References addCluster(), ExFatPartition::bytesPerCluster(), ExFatPartition::bytesPerSector(), FsCache::CACHE_RESERVE_FOR_WRITE, ExFatPartition::clusterStartSector(), ExFatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FILE_FLAG_DIR_DIRTY, isRoot(), m_curCluster, m_dataLength, m_flags, m_validLength, m_vol, ExFatPartition::rootLength(), ExFatPartition::sectorsPerCluster(), and sync().
Referenced by mkdir(), and openPrivate().
available()
int ExFatFile::available (void) inline
Returns
The number of bytes available from the current position to EOF for normal files. INT_MAX is returned for very large files.
available64() is recommended for very large files.
Zero is returned for directory files.
Definition at line 98 of file ExFatFile.h.
                   {
     uint64_t n = available64();
     return n > INT_MAX ? INT_MAX : n;
   }
References available64().
Referenced by FsBaseFile::available().
available64()
uint64_t ExFatFile::available64 () inline
Returns
The number of bytes available from the current position to EOF for normal files. Zero is returned for directory files.
Definition at line 105 of file ExFatFile.h.
{
     return isFile() ? fileSize() - curPosition() : 0;
   }
References curPosition(), fileSize(), and isFile().
Referenced by available(), and FsBaseFile::available64().
clearError()
void ExFatFile::clearError () inline
Clear all error bits.
Definition at line 109 of file ExFatFile.h.
                     {
     m_error = 0;
   }
References m_error.
clearWriteError()
void ExFatFile::clearWriteError () inline
Clear writeError.
Definition at line 113 of file ExFatFile.h.
{
     m_error &= ~WRITE_ERROR;
   }
References m_error, and WRITE_ERROR.
Referenced by FsBaseFile::clearWriteError().
close()
bool ExFatFile::close ()
Close a file and force cached data and directory information to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 52 of file ExFatFile.cpp.
                       {
   bool rtn = sync();
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   return rtn;
 }
References FILE_ATTR_CLOSED, m_attributes, m_flags, and sync().
Referenced by ExFatVolume::chdir(), FsBaseFile::close(), ls(), mkdir(), and open().
cmpName()
bool ExFatFile::cmpName (const DirName_t * dirName, ExName_t * fname) private
Definition at line 49 of file ExFatName.cpp.
{
   for (uint8_t i = 0; i < 15; i++) {
     uint16_t u = getLe16(dirName->unicode + 2*i);
     if (fname->atEnd()) {
       return u == 0;
     }
 #if USE_UTF8_LONG_NAMES
     uint16_t cp = fname->get16();
     if (toUpcase(cp) != toUpcase(u)) {
        return false;
     }
 #else  // USE_UTF8_LONG_NAMES
     char c = fname->getch();
     if (u >= 0x7F || toUpper(c) != toUpper(u)) {
       return false;
     }
 #endif  // USE_UTF8_LONG_NAMES
   }
   return true;
 }
References FsName::atEnd(), FsName::get16(), FsName::getch(), getLe16(), toUpcase(), toUpper(), and DirName_t::unicode.
Referenced by openPrivate().
contiguousRange()
bool ExFatFile::contiguousRange (uint32_t * bgnSector, uint32_t * endSector)
Check for contiguous file and return its raw sector range.
Parameters
[out] bgnSector the first sector address for the file.
[out] endSector the last sector address for the file.
Parameters may be nullptr.
Returns
true for success or false for failure.
Definition at line 59 of file ExFatFile.cpp.
{
   if (!isContiguous()) {
     return false;
   }
   if (bgnSector) {
     *bgnSector = firstSector();
   }
   if (endSector) {
     *endSector = firstSector() +
                  ((m_validLength - 1) >> m_vol->bytesPerSectorShift());
   }
   return true;
 }
References ExFatPartition::bytesPerSectorShift(), firstSector(), isContiguous(), m_validLength, and m_vol.
Referenced by FsBaseFile::contiguousRange().
curCluster()
uint32_t ExFatFile::curCluster () const inline private
Definition at line 772 of file ExFatFile.h.
 {return m_curCluster;}
References m_curCluster.
Referenced by openPrivate(), and peek().
curPosition()
uint64_t ExFatFile::curPosition () const inline
Returns
The current position for a file or directory.
Definition at line 133 of file ExFatFile.h.
 {return m_curPosition;}
References m_curPosition.
Referenced by available64(), FsBaseFile::curPosition(), openNext(), openPrivate(), and peek().
dataLength()
uint64_t ExFatFile::dataLength () const inline
Returns
Total data length for file.
Definition at line 136 of file ExFatFile.h.
 {return m_dataLength;}
References m_dataLength.
dirCache()
uint8_t * ExFatFile::dirCache (uint8_t set, uint8_t options) private
Definition at line 44 of file ExFatFile.cpp.
{
   DirPos_t pos = m_dirPos;
   if (m_vol->dirSeek(&pos, FS_DIR_SIZE*set) != 1) {
     return nullptr;
   }
   return m_vol->dirCache(&pos, options);
 }
References ExFatPartition::dirCache(), ExFatPartition::dirSeek(), FS_DIR_SIZE, m_dirPos, and m_vol.
Referenced by getName7(), getName8(), openPrivate(), printName7(), printName8(), remove(), syncDir(), and timestamp().
dirIndex()
uint32_t ExFatFile::dirIndex () const inline
Returns
Directory entry index.
Definition at line 138 of file ExFatFile.h.
 {return m_dirPos.position/FS_DIR_SIZE;}
References FS_DIR_SIZE, m_dirPos, and DirPos_t::position.
Referenced by FsBaseFile::dirIndex(), and open().
exists()
bool ExFatFile::exists (const char * path) inline
Test for the existence of a file in a directory
Parameters
[in] path Path of the file to be tested for.
The calling instance must be an open directory file.
dirFile.exists("TOFIND.TXT") searches for "TOFIND.TXT" in the directory dirFile.
Returns
true if the file exists else false.
Definition at line 150 of file ExFatFile.h.
{
       ExFatFile file;
       return file.open(this, path, O_RDONLY);
     }
References O_RDONLY, and open().
Referenced by FsBaseFile::exists().
fgetpos()
void ExFatFile::fgetpos (fspos_t * pos) const
get position for streams
Parameters
[out] pos struct to receive position
Definition at line 73 of file ExFatFile.cpp.
{
   pos->position = m_curPosition;
   pos->cluster = m_curCluster;
 }
References fspos_t::cluster, m_curCluster, m_curPosition, and fspos_t::position.
Referenced by FsBaseFile::fgetpos().
fgets()
int ExFatFile::fgets (char * str, int num, char * delim = nullptr)
Get a string from a file.
fgets() reads bytes from a file into the array pointed to by str, until num - 1 bytes are read, or a delimiter is read and transferred to str, or end-of-file is encountered. The string is then terminated with a null byte.
fgets() deletes CR, '\r', from the string. This insures only a '\n' terminates the string for Windows text files which use CRLF for newline.
Parameters
[out] str Pointer to the array where the string is stored.
[in] num Maximum number of characters to be read (including the final null byte). Usually the length of the array str is used.
[in] delim Optional set of delimiters. The default is "\n".
Returns
For success fgets() returns the length of the string in str. If no data is read, fgets() returns zero for EOF or -1 if an error occurred.
Definition at line 78 of file ExFatFile.cpp.
{
   char ch;
   int n = 0;
   int r = -1;
   while ((n + 1) < num && (r = read(&ch, 1)) == 1) {
     // delete CR
     if (ch == '\r') {
       continue;
     }
     str[n++] = ch;
     if (!delim) {
       if (ch == '\n') {
         break;
       }
     } else {
       if (strchr(delim, ch)) {
         break;
       }
     }
   }
   if (r < 0) {
     // read error
     return -1;
   }
   str[n] = '\0';
   return n;
 }
References read().
Referenced by FsBaseFile::fgets().
fileSize()
uint64_t ExFatFile::fileSize () const inline
Returns
The total number of bytes in a file.
Definition at line 181 of file ExFatFile.h.
 {return m_validLength;}
References m_validLength.
Referenced by available64(), FsBaseFile::fileSize(), and openPrivate().
firstSector()
uint32_t ExFatFile::firstSector () const
Returns
Address of first sector or zero for empty file.
Definition at line 106 of file ExFatFile.cpp.
{
   return m_firstCluster ? m_vol->clusterStartSector(m_firstCluster) : 0;
 }
References ExFatPartition::clusterStartSector(), m_firstCluster, and m_vol.
Referenced by contiguousRange(), and FsBaseFile::firstSector().
flush()
void ExFatFile::flush () inline
Arduino name for sync()
Definition at line 189 of file ExFatFile.h.
 {sync();}
References sync().
fsetpos()
void ExFatFile::fsetpos (const fspos_t * pos)
Set position for streams
Parameters
[in] pos struct with value for new position
Definition at line 110 of file ExFatFile.cpp.
{
   m_curPosition = pos->position;
   m_curCluster = pos->cluster;
 }
References fspos_t::cluster, m_curCluster, m_curPosition, and fspos_t::position.
Referenced by FsBaseFile::fsetpos().
getAccessDateTime()
bool ExFatFile::getAccessDateTime (uint16_t * pdate, uint16_t * ptime)
Get a file's access date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 115 of file ExFatFile.cpp.
{
   DirFile_t* df = reinterpret_cast<DirFile_t*>
                  (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_READ));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   *pdate = getLe16(df->accessDate);
   *ptime = getLe16(df->accessTime);
   return true;
  fail:
   return false;
 }
References DirFile_t::accessDate, DirFile_t::accessTime, FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, ExFatPartition::dirCache(), getLe16(), m_dirPos, and m_vol.
Referenced by FsBaseFile::getAccessDateTime(), and printAccessDateTime().
getCreateDateTime()
bool ExFatFile::getCreateDateTime (uint16_t * pdate, uint16_t * ptime)
Get a file's create date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 130 of file ExFatFile.cpp.
{
   DirFile_t* df = reinterpret_cast<DirFile_t*>
                  (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_READ));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   *pdate = getLe16(df->createDate);
   *ptime = getLe16(df->createTime);
   return true;
  fail:
   return false;
 }
References FsCache::CACHE_FOR_READ, DirFile_t::createDate, DirFile_t::createTime, DBG_FAIL_MACRO, ExFatPartition::dirCache(), getLe16(), m_dirPos, and m_vol.
Referenced by FsBaseFile::getCreateDateTime(), and printCreateDateTime().
getError()
uint8_t ExFatFile::getError () const inline
Returns
All error bits.
Definition at line 207 of file ExFatFile.h.
{
     return isOpen() ? m_error : 0XFF;
   }
References isOpen(), and m_error.
Referenced by FsBaseFile::getError(), and ls().
getModifyDateTime()
bool ExFatFile::getModifyDateTime (uint16_t * pdate, uint16_t * ptime)
Get a file's modify date and time.
Parameters
[out] pdate Packed date for directory entry.
[out] ptime Packed time for directory entry.
Returns
true for success or false for failure.
Definition at line 145 of file ExFatFile.cpp.
{
   DirFile_t* df = reinterpret_cast<DirFile_t*>
                  (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_READ));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   *pdate = getLe16(df->modifyDate);
   *ptime = getLe16(df->modifyTime);
   return true;
  fail:
   return false;
 }
References FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, ExFatPartition::dirCache(), getLe16(), m_dirPos, m_vol, DirFile_t::modifyDate, and DirFile_t::modifyTime.
Referenced by FsBaseFile::getModifyDateTime(), and printModifyDateTime().
getName()
size_t ExFatFile::getName (char * name, size_t size) inline
Get a file's name followed by a zero.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in characters.
Returns
the name length.
Definition at line 225 of file ExFatFile.h.
{
 #if USE_UTF8_LONG_NAMES
     return getName8(name, size);
 #else  // USE_UTF8_LONG_NAMES
     return getName7(name, size);
 #endif  // USE_UTF8_LONG_NAMES
   }
References getName7(), and getName8().
Referenced by FsBaseFile::getName().
getName7()
size_t ExFatFile::getName7 (char * name, size_t size)
Get a file's ASCII name followed by a zero.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in characters.
Returns
the name length.
Definition at line 70 of file ExFatName.cpp.
{
   DirName_t* dn;
   size_t n = 0;
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   for (uint8_t is = 2; is <= m_setCount; is++) {
     dn = reinterpret_cast<DirName_t*>
          (dirCache(is, FsCache::CACHE_FOR_READ));
     if (!dn || dn->type != EXFAT_TYPE_NAME) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (uint8_t in = 0; in < 15; in++) {
       uint16_t c = getLe16(dn->unicode + 2*in);
       if (c == 0 || (n + 1) >= count) {
         goto done;
       }
       name[n++] = c < 0X7F ? c : '?';
     }
   }
  done:
   name[n] = 0;
   return n;
  fail:
   *name = 0;
   return 0;
 }
References FsCache::CACHE_FOR_READ, count, DBG_FAIL_MACRO, dirCache(), EXFAT_TYPE_NAME, getLe16(), isOpen(), m_setCount, DirName_t::type, and DirName_t::unicode.
Referenced by getName().
getName8()
size_t ExFatFile::getName8 (char * name, size_t size)
Get a file's UTF-8 name followed by a zero.
Parameters
[out] name An array of characters for the file's name.
[in] size The size of the array in characters.
Returns
the name length.
Definition at line 101 of file ExFatName.cpp.
{
   char* end = name + count;
   char* str = name;
   char* ptr;
   DirName_t* dn;
   uint16_t hs = 0;
   uint32_t cp;
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   for (uint8_t is = 2; is <= m_setCount; is++) {
     dn = reinterpret_cast<DirName_t*>
          (dirCache(is, FsCache::CACHE_FOR_READ));
     if (!dn || dn->type != EXFAT_TYPE_NAME) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (uint8_t in = 0; in < 15; in++) {
       uint16_t c = getLe16(dn->unicode + 2*in);
       if (hs) {
         if (!FsUtf::isLowSurrogate(c)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         cp = FsUtf::u16ToCp(hs, c);
         hs = 0;
       } else if (!FsUtf::isSurrogate(c)) {
         if (c == 0) {
           goto done;
         }
         cp = c;
       } else if (FsUtf::isHighSurrogate(c)) {
         hs = c;
         continue;
       } else {
         DBG_FAIL_MACRO;
         goto fail;
       }
       // Save space for zero byte.
       ptr = FsUtf::cpToMb(cp, str, end - 1);
       if (!ptr) {
         // Truncate name.  Could goto fail.
         goto done;
       }
       str = ptr;
     }
   }
  done:
   *str = '\0';
   return str - name;
  fail:
   *name = 0;
   return 0;
 }
References FsCache::CACHE_FOR_READ, count, FsUtf::cpToMb(), DBG_FAIL_MACRO, dirCache(), EXFAT_TYPE_NAME, getLe16(), FsUtf::isHighSurrogate(), FsUtf::isLowSurrogate(), isOpen(), FsUtf::isSurrogate(), m_setCount, DirName_t::type, FsUtf::u16ToCp(), and DirName_t::unicode.
Referenced by getName().
getWriteError()
bool ExFatFile::getWriteError () const inline
Returns
value of writeError
Definition at line 249 of file ExFatFile.h.
{
     return isOpen() ? m_error & WRITE_ERROR : true;
   }
References isOpen(), m_error, and WRITE_ERROR.
Referenced by FsBaseFile::getWriteError().
hashName()
bool ExFatFile::hashName (ExName_t * fname) private
Definition at line 158 of file ExFatName.cpp.
{
   uint16_t hash = 0;
   fname->reset();
 #if USE_UTF8_LONG_NAMES
   fname->nameLength = 0;
   while (!fname->atEnd()) {
     uint16_t u = fname->get16();
     if (u == 0XFFFF) {
     DBG_FAIL_MACRO;
       goto fail;
     }
     hash = exFatHash(u, hash);
     fname->nameLength++;
   }
 #else  // USE_UTF8_LONG_NAMES
   while (!fname->atEnd()) {
     // Convert to byte for smaller exFatHash.
     char c = fname->getch();
     hash = exFatHash(c, hash);
   }
   fname->nameLength = fname->end - fname->begin;
 #endif  // USE_UTF8_LONG_NAMES
   fname->nameHash = hash;
   if (!fname->nameLength || fname->nameLength > EXFAT_MAX_NAME_LENGTH) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References FsName::atEnd(), FsName::begin, DBG_FAIL_MACRO, FsName::end, EXFAT_MAX_NAME_LENGTH, exFatHash(), FsName::get16(), FsName::getch(), ExName_t::nameHash, ExName_t::nameLength, and FsName::reset().
Referenced by parsePathName().
isBusy()
bool ExFatFile::isBusy ()
Check for BlockDevice busy.
Returns
true if busy else false.
Definition at line 160 of file ExFatFile.cpp.
{
   return m_vol->isBusy();
 }
References ExFatPartition::isBusy(), and m_vol.
Referenced by FsBaseFile::isBusy().
isContiguous()
bool ExFatFile::isContiguous () const inline
Returns
True if the file is contiguous.
Definition at line 259 of file ExFatFile.h.
 {return m_flags & FILE_FLAG_CONTIGUOUS;}
References FILE_FLAG_CONTIGUOUS, and m_flags.
Referenced by addCluster(), contiguousRange(), FsBaseFile::isContiguous(), openPrivate(), read(), remove(), seekSet(), syncDir(), truncate(), and write().
isDir()
bool ExFatFile::isDir () const inline
Returns
True if this is a directory.
Definition at line 261 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_DIR;}
References FILE_ATTR_DIR, and m_attributes.
Referenced by ExFatVolume::chdir(), FsBaseFile::isDir(), ls(), mkdir(), open(), openNext(), openPrivate(), and read().
isFile()
bool ExFatFile::isFile () const inline
Returns
True if this is a normal file.
Definition at line 263 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_FILE;}
References FILE_ATTR_FILE, and m_attributes.
Referenced by available64(), FsBaseFile::isFile(), read(), rename(), seekEnd(), seekSet(), and timestamp().
isHidden()
bool ExFatFile::isHidden () const inline
Returns
True if this is a hidden.
Definition at line 265 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_HIDDEN;}
References FILE_ATTR_HIDDEN, and m_attributes.
Referenced by FsBaseFile::isHidden(), and ls().
isOpen()
bool ExFatFile::isOpen () const inline
Returns
true if the file is open.
Definition at line 267 of file ExFatFile.h.
 {return m_attributes;}
References m_attributes.
Referenced by getError(), getName7(), getName8(), getWriteError(), mkdir(), open(), openNext(), openPrivate(), openRoot(), operator bool(), printName7(), printName8(), seekSet(), and sync().
isReadable()
bool ExFatFile::isReadable () const inline
Returns
True file is readable.
Definition at line 273 of file ExFatFile.h.
 {return m_flags & FILE_FLAG_READ;}
References FILE_FLAG_READ, and m_flags.
Referenced by FsBaseFile::isReadable(), and read().
isReadOnly()
bool ExFatFile::isReadOnly () const inline
Returns
True if file is read-only
Definition at line 269 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_READ_ONLY;}
References FILE_ATTR_READ_ONLY, and m_attributes.
Referenced by FsBaseFile::isReadOnly(), and openPrivate().
isRoot()
bool ExFatFile::isRoot () const inline
Returns
True if this is the root directory.
Definition at line 271 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_ROOT;}
References FILE_ATTR_ROOT, and m_attributes.
Referenced by addDirCluster(), read(), and seekSet().
isSubDir()
bool ExFatFile::isSubDir () const inline
Returns
True if this is a subdirectory.
Definition at line 275 of file ExFatFile.h.
 {return m_attributes & FILE_ATTR_SUBDIR;}
References FILE_ATTR_SUBDIR, and m_attributes.
Referenced by FsBaseFile::isSubDir(), openPrivate(), rename(), and rmdir().
isWritable()
bool ExFatFile::isWritable () const inline
Returns
True file is writable.
Definition at line 277 of file ExFatFile.h.
 {return m_flags & FILE_FLAG_WRITE;}
References FILE_FLAG_WRITE, and m_flags.
Referenced by FsBaseFile::isWritable(), preAllocate(), remove(), truncate(), and write().
ls() [1/2]
bool ExFatFile::ls (print_t * pr)
List directory contents.
Parameters
[in] pr Print stream for list.
Returns
true for success or false for failure.
Definition at line 30 of file ExFatFilePrint.cpp.
{
   ExFatFile file;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   while (file.openNext(this, O_RDONLY)) {
     if (!file.isHidden()) {
       file.printName(pr);
       if (file.isDir()) {
         pr->write('/');
       }
       pr->write('\r');
       pr->write('\n');
     }
     file.close();
   }
   if (getError()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, getError(), isDir(), isHidden(), O_RDONLY, openNext(), printName(), rewind(), and PrintBasic::write().
Referenced by ls(), and ExFatVolume::ls().
ls() [2/2]
bool ExFatFile::ls (print_t * pr, uint8_t flags, uint8_t indent = 0)
List directory contents.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Parameters
[in] indent Amount of space before file name. Used for recursive list to indicate subdirectory level.
Returns
true for success or false for failure.
Definition at line 58 of file ExFatFilePrint.cpp.
{
   ExFatFile file;
   if (!isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   while (file.openNext(this, O_RDONLY)) {
     // indent for dir level
     if (!file.isHidden() || (flags & LS_A)) {
       for (uint8_t i = 0; i < indent; i++) {
         pr->write(' ');
       }
       if (flags & LS_DATE) {
         file.printModifyDateTime(pr);
         pr->write(' ');
       }
       if (flags & LS_SIZE) {
         file.printFileSize(pr);
         pr->write(' ');
       }
       file.printName(pr);
       if (file.isDir()) {
         pr->write('/');
       }
       pr->write('\r');
       pr->write('\n');
       if ((flags & LS_R) && file.isDir()) {
         file.ls(pr, flags, indent + 2);
       }
     }
     file.close();
   }
   if (getError()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, getError(), isDir(), isHidden(), ls(), LS_A, LS_DATE, LS_R, LS_SIZE, O_RDONLY, openNext(), printFileSize(), printModifyDateTime(), printName(), rewind(), and PrintBasic::write().
mkdir() [1/2]
bool ExFatFile::mkdir (ExFatFile * parent, const char * path, bool pFlag = true)
Make a new directory.
Parameters
[in] parent An open directory file that will contain the new directory.
[in] path A path with a valid name for the new directory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 154 of file ExFatFileWrite.cpp.
{
   ExName_t fname;
   ExFatFile tmpDir;
   if (isOpen() || !parent->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isDirSeparator(*path)) {
     while (isDirSeparator(*path)) {
       path++;
     }
     if (!tmpDir.openRoot(parent->m_vol)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     parent = &tmpDir;
   }
   while (1) {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!*path) {
       break;
     }
     if (!openPrivate(parent, &fname, O_RDONLY)) {
       if (!pFlag || !mkdir(parent, &fname)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     tmpDir = *this;
     parent = &tmpDir;
     close();
   }
   return mkdir(parent, &fname);
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, isDir(), isDirSeparator, isOpen(), m_vol, O_RDONLY, openPrivate(), openRoot(), and parsePathName().
Referenced by ExFatVolume::mkdir(), and FsBaseFile::mkdir().
mkdir() [2/2]
bool ExFatFile::mkdir (ExFatFile * parent, ExName_t * fname) private
Definition at line 196 of file ExFatFileWrite.cpp.
{
   if (!parent->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // create a normal file
   if (!openPrivate(parent, fname, O_CREAT | O_EXCL | O_RDWR)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // convert file to directory
   m_attributes = FILE_ATTR_SUBDIR;
   // allocate and zero first cluster
   if (!addDirCluster()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_firstCluster = m_curCluster;
   // Set to start of dir
   rewind();
   m_flags = FILE_FLAG_READ | FILE_FLAG_CONTIGUOUS | FILE_FLAG_DIR_DIRTY;
   return sync();
  fail:
   return false;
 }
References addDirCluster(), DBG_FAIL_MACRO, FILE_ATTR_SUBDIR, FILE_FLAG_CONTIGUOUS, FILE_FLAG_DIR_DIRTY, FILE_FLAG_READ, isDir(), m_attributes, m_curCluster, m_firstCluster, m_flags, O_CREAT, O_EXCL, O_RDWR, openPrivate(), rewind(), and sync().
open() [1/4]
bool ExFatFile::open (const char * path, oflag_t oflag = O_RDONLY)
Open a file in the current working directory.
Parameters
[in] path A path with a valid name for a file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see ExFatFile::open(ExFatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 164 of file ExFatFile.cpp.
{
   return open(ExFatVolume::cwv(), path, oflag);
 }
References ExFatVolume::cwv(), and open().
open() [2/4]
bool ExFatFile::open (ExFatFile * dirFile, const char * path, oflag_t oflag)
Open a file or directory by name.
Parameters
[in] dirFile An open directory containing the file to be opened.
[in] path The path for a file to be opened.
[in] oflag Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list. Only one of O_RDONLY, O_READ, O_WRONLY, O_WRITE, or O_RDWR is allowed.
O_RDONLY - Open for reading.
O_READ - Same as O_RDONLY.
O_WRONLY - Open for writing.
O_WRITE - Same as O_WRONLY.
O_RDWR - Open for reading and writing.
O_APPEND - If set, the file offset shall be set to the end of the file prior to each write.
O_AT_END - Set the initial position at the end of the file.
O_CREAT - If the file exists, this flag has no effect except as noted under O_EXCL below. Otherwise, the file shall be created
O_EXCL - If O_CREAT and O_EXCL are set, open() shall fail if the file exists.
O_TRUNC - If the file exists and is a regular file, and the file is successfully opened and is not read only, its length shall be truncated to 0.
WARNING: A given file must not be opened by more than one file object or file corruption may occur.
Note
Directory files must be opened read only. Write and truncation is not allowed for directory files.
Returns
true for success or false for failure.
Definition at line 172 of file ExFatFile.cpp.
{
   ExFatFile tmpDir;
   ExName_t fname;
   // error if already open
   if (isOpen() || !dirFile->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isDirSeparator(*path)) {
     while (isDirSeparator(*path)) {
       path++;
     }
     if (*path == 0) {
       return openRoot(dirFile->m_vol);
     }
     if (!tmpDir.openRoot(dirFile->m_vol)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     dirFile = &tmpDir;
   }
   while (1) {
     if (!parsePathName(path, &fname, &path)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (*path == 0) {
       break;
     }
     if (!openPrivate(dirFile, &fname, O_RDONLY)) {
       DBG_WARN_MACRO;
       goto fail;
     }
     tmpDir = *this;
     dirFile = &tmpDir;
     close();
   }
   return openPrivate(dirFile, &fname, oflag);
  fail:
   return false;
 }
References close(), DBG_FAIL_MACRO, DBG_WARN_MACRO, isDir(), isDirSeparator, isOpen(), m_vol, O_RDONLY, openPrivate(), openRoot(), and parsePathName().
Referenced by ExFatFile(), ExFatVolume::chdir(), exists(), ExFatVolume::exists(), ExFatVolume::ls(), open(), ExFatVolume::open(), FsBaseFile::open(), remove(), ExFatVolume::remove(), ExFatVolume::rename(), rename(), ExFatVolume::rmdir(), and ExFatVolume::truncate().
open() [3/4]
bool ExFatFile::open (ExFatFile * dirFile, uint32_t index, oflag_t oflag)
Open a file by index.
Parameters
[in] dirFile An open ExFatFile instance for the directory.
[in] index The index of the directory entry for the file to be opened. The value for index is (directory file position)/32.
[in] oflag bitwise-inclusive OR of open flags. See see ExFatFile::open(ExFatFile*, const char*, uint8_t).
See open() by path for definition of flags.
Returns
true for success or false for failure.
Definition at line 215 of file ExFatFile.cpp.
{
   if (dirFile->seekSet(FS_DIR_SIZE*index) && openNext(dirFile, oflag)) {
     if (dirIndex() == index) {
       return true;
     }
     close();
     DBG_FAIL_MACRO;
   }
   return false;
 }
References close(), DBG_FAIL_MACRO, dirIndex(), FS_DIR_SIZE, openNext(), and seekSet().
open() [4/4]
bool ExFatFile::open (ExFatVolume * vol, const char * path, oflag_t oflag)
Open a file in the volume working directory.
Parameters
[in] vol Volume where the file is located.
[in] path with a valid name for a file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see open(ExFatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 168 of file ExFatFile.cpp.
{
   return vol && open(vol->vwd(), path, oflag);
 }
References open(), and ExFatVolume::vwd().
openNext()
bool ExFatFile::openNext (ExFatFile * dirFile, oflag_t oflag = O_RDONLY)
Open the next file or subdirectory in a directory.
Parameters
[in] dirFile An open instance for the directory containing the file to be opened.
[in] oflag bitwise-inclusive OR of open flags. See see open(ExFatFile*, const char*, uint8_t).
Returns
true for success or false for failure.
Definition at line 226 of file ExFatFile.cpp.
{
   if (isOpen() || !dir->isDir() || (dir->curPosition() & 0X1F)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return openPrivate(dir, nullptr, oflag);
  fail:
   return false;
 }
References curPosition(), DBG_FAIL_MACRO, isDir(), isOpen(), and openPrivate().
Referenced by ls(), open(), FsBaseFile::openNext(), and ExFile::openNextFile().
openPrivate()
bool ExFatFile::openPrivate (ExFatFile * dir, ExName_t * fname, oflag_t oflag) private
Definition at line 237 of file ExFatFile.cpp.
{
   int n;
   uint8_t modeFlags;
   uint32_t curCluster __attribute__((unused));
   uint8_t* cache __attribute__((unused));
   DirPos_t freePos __attribute__((unused));
   DirFile_t*   dirFile;
   DirStream_t* dirStream;
   DirName_t*   dirName;
   uint8_t buf[FS_DIR_SIZE];
   uint8_t freeCount = 0;
   uint8_t freeNeed = 3;
   bool inSet = false;
   // error if already open, no access mode, or no directory.
   if (isOpen() || !dir->isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   switch (oflag & O_ACCMODE) {
     case O_RDONLY:
       modeFlags = FILE_FLAG_READ;
       break;
     case O_WRONLY:
       modeFlags = FILE_FLAG_WRITE;
       break;
     case O_RDWR:
       modeFlags = FILE_FLAG_READ | FILE_FLAG_WRITE;
       break;
     default:
       DBG_FAIL_MACRO;
       goto fail;
   }
   modeFlags |= oflag & O_APPEND ? FILE_FLAG_APPEND : 0;
   if (fname) {
     freeNeed = 2 + (fname->nameLength + 14)/15;
     dir->rewind();
   }
   while (1) {
     n = dir->read(buf, FS_DIR_SIZE);
     if (n == 0) {
       goto create;
     }
     if (n != FS_DIR_SIZE) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!(buf[0] & 0x80)) {
       // Unused entry.
       if (freeCount == 0) {
         freePos.position = dir->curPosition() - FS_DIR_SIZE;
         freePos.cluster = dir->curCluster();
       }
       if (freeCount < freeNeed) {
         freeCount++;
       }
       if (!buf[0]) {
         if (fname) {
           goto create;
         }
         // Likely openNext call.
         DBG_WARN_MACRO;
         goto fail;
       }
       inSet = false;
     } else if (!inSet) {
       if (freeCount < freeNeed) {
         freeCount = 0;
       }
       if (buf[0] != EXFAT_TYPE_FILE) {
         continue;
       }
       inSet = true;
       memset(this, 0, sizeof(ExFatFile));
       dirFile = reinterpret_cast<DirFile_t*>(buf);
       m_setCount = dirFile->setCount;
       m_attributes = getLe16(dirFile->attributes) & FILE_ATTR_COPY;
       if (!(m_attributes & EXFAT_ATTRIB_DIRECTORY)) {
         m_attributes |= FILE_ATTR_FILE;
       }
       m_vol = dir->volume();
       m_dirPos.cluster = dir->curCluster();
       m_dirPos.position = dir->curPosition() - FS_DIR_SIZE;
       m_dirPos.isContiguous = dir->isContiguous();
     } else if (buf[0] == EXFAT_TYPE_STREAM) {
       dirStream = reinterpret_cast<DirStream_t*>(buf);
       m_flags = modeFlags;
       if (dirStream->flags & EXFAT_FLAG_CONTIGUOUS) {
         m_flags |= FILE_FLAG_CONTIGUOUS;
       }
       m_validLength = getLe64(dirStream->validLength);
       m_firstCluster = getLe32(dirStream->firstCluster);
       m_dataLength = getLe64(dirStream->dataLength);
       if (!fname) {
         goto found;
       }
       fname->reset();
       if (fname->nameLength != dirStream->nameLength ||
           fname->nameHash != getLe16(dirStream->nameHash)) {
         inSet = false;
       }
     } else if (buf[0] == EXFAT_TYPE_NAME) {
       dirName = reinterpret_cast<DirName_t*>(buf);
       if (!cmpName(dirName, fname)) {
         inSet = false;
         continue;
       }
       if (fname->atEnd()) {
         goto found;
       }
     } else {
       inSet = false;
     }
   }
  found:
   // Don't open if create only.
   if (oflag & O_EXCL) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Write, truncate, or at end is an error for a directory or read-only file.
   if ((oflag & (O_TRUNC | O_AT_END)) || (m_flags & FILE_FLAG_WRITE)) {
     if (isSubDir() || isReadOnly() || READ_ONLY) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
 #if !READ_ONLY
   if (oflag & O_TRUNC) {
     if (!(m_flags & FILE_FLAG_WRITE)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!truncate(0)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } else if ((oflag & O_AT_END) && !seekSet(fileSize())) {
     DBG_FAIL_MACRO;
     goto fail;
   }
 #endif  // !READ_ONLY
   return true;
  create:
 #if READ_ONLY
   DBG_FAIL_MACRO;
   goto fail;
 #else  // READ_ONLY
   // don't create unless O_CREAT and write
   if (!(oflag & O_CREAT) || !(modeFlags & FILE_FLAG_WRITE) || !fname) {
     DBG_WARN_MACRO;
     goto fail;
   }
   while (freeCount < freeNeed) {
     n = dir->read(buf, FS_DIR_SIZE);
     if (n == 0) {
       curCluster = dir->m_curCluster;
       if (!dir->addDirCluster()) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       dir->m_curCluster = curCluster;
       continue;
     }
     if (n != FS_DIR_SIZE) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (freeCount == 0) {
       freePos.position = dir->curPosition() - FS_DIR_SIZE;
       freePos.cluster = dir->curCluster();
     }
     freeCount++;
   }
   freePos.isContiguous = dir->isContiguous();
   memset(this, 0, sizeof(ExFatFile));
   m_vol = dir->volume();
   m_attributes = FILE_ATTR_FILE;
   m_dirPos = freePos;
   fname->reset();
   for (uint8_t i = 0; i < freeNeed; i++) {
     cache = dirCache(i, FsCache::CACHE_FOR_WRITE);
     if (!cache || (cache[0] & 0x80)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     memset(cache, 0 , FS_DIR_SIZE);
     if (i == 0) {
       dirFile = reinterpret_cast<DirFile_t*>(cache);
       dirFile->type = EXFAT_TYPE_FILE;
       m_setCount = freeNeed - 1;
       dirFile->setCount = m_setCount;
       if (FsDateTime::callback) {
         uint16_t date, time;
         uint8_t ms10;
         FsDateTime::callback(&date, &time, &ms10);
         setLe16(dirFile->createDate, date);
         setLe16(dirFile->createTime, time);
         dirFile->createTimeMs = ms10;
       } else {
         setLe16(dirFile->createDate, FS_DEFAULT_DATE);
         setLe16(dirFile->modifyDate, FS_DEFAULT_DATE);
         setLe16(dirFile->accessDate, FS_DEFAULT_DATE);
        if (FS_DEFAULT_TIME) {
          setLe16(dirFile->createTime, FS_DEFAULT_TIME);
          setLe16(dirFile->modifyTime, FS_DEFAULT_TIME);
          setLe16(dirFile->accessTime, FS_DEFAULT_TIME);
        }
       }
     } else if (i == 1) {
       dirStream = reinterpret_cast<DirStream_t*>(cache);
       dirStream->type = EXFAT_TYPE_STREAM;
       dirStream->flags = EXFAT_FLAG_ALWAYS1;
       m_flags = modeFlags | FILE_FLAG_DIR_DIRTY;
       dirStream->nameLength = fname->nameLength;
       setLe16(dirStream->nameHash, fname->nameHash);
     } else {
       dirName = reinterpret_cast<DirName_t*>(cache);
       dirName->type = EXFAT_TYPE_NAME;
       for (size_t k = 0; k < 15; k++) {
         if (fname->atEnd()) {
           break;
         }
         uint16_t u = fname->get16();
         setLe16(dirName->unicode + 2*k, u);
       }
     }
   }
   return sync();
 #endif  // READ_ONLY
  fail:
   // close file
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   return false;
 }
References __attribute__, DirFile_t::accessDate, DirFile_t::accessTime, addDirCluster(), FsName::atEnd(), DirFile_t::attributes, buf, FsCache::CACHE_FOR_WRITE, FsDateTime::callback, DirPos_t::cluster, cmpName(), DirFile_t::createDate, DirFile_t::createTime, DirFile_t::createTimeMs, curCluster(), curPosition(), DirStream_t::dataLength, DBG_FAIL_MACRO, DBG_WARN_MACRO, dirCache(), EXFAT_ATTRIB_DIRECTORY, EXFAT_FLAG_ALWAYS1, EXFAT_FLAG_CONTIGUOUS, EXFAT_TYPE_FILE, EXFAT_TYPE_NAME, EXFAT_TYPE_STREAM, FILE_ATTR_CLOSED, FILE_ATTR_COPY, FILE_ATTR_FILE, FILE_FLAG_APPEND, FILE_FLAG_CONTIGUOUS, FILE_FLAG_DIR_DIRTY, FILE_FLAG_READ, FILE_FLAG_WRITE, fileSize(), DirStream_t::firstCluster, DirStream_t::flags, FS_DEFAULT_DATE, FS_DEFAULT_TIME, FS_DIR_SIZE, FsName::get16(), getLe16(), getLe32(), getLe64(), isContiguous(), DirPos_t::isContiguous, isDir(), isOpen(), isReadOnly(), isSubDir(), m_attributes, m_curCluster, m_dataLength, m_dirPos, m_firstCluster, m_flags, m_setCount, m_validLength, m_vol, DirFile_t::modifyDate, DirFile_t::modifyTime, DirStream_t::nameHash, ExName_t::nameHash, DirStream_t::nameLength, ExName_t::nameLength, O_ACCMODE, O_APPEND, O_AT_END, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, DirPos_t::position, read(), READ_ONLY, FsName::reset(), rewind(), seekSet(), DirFile_t::setCount, setLe16(), sync(), truncate(), DirFile_t::type, DirStream_t::type, DirName_t::type, DirName_t::unicode, DirStream_t::validLength, and volume().
Referenced by mkdir(), open(), and openNext().
openRoot()
bool ExFatFile::openRoot (ExFatVolume * vol)
Open a volume's root directory.
Parameters
[in] vol The FAT volume containing the root directory to be opened.
Returns
true for success or false for failure.
Definition at line 483 of file ExFatFile.cpp.
{
   if (isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   memset(this, 0, sizeof(ExFatFile));
   m_attributes = FILE_ATTR_ROOT;
   m_vol = vol;
   m_flags = FILE_FLAG_READ;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FILE_ATTR_ROOT, FILE_FLAG_READ, isOpen(), m_attributes, m_flags, and m_vol.
Referenced by ExFatVolume::chdir(), mkdir(), open(), and FsBaseFile::openRoot().
operator bool()
ExFatFile::operator bool () inline
The parenthesis operator.
Returns
true if a file is open.
Definition at line 87 of file ExFatFile.h.
                   {
     return isOpen();
   }
References isOpen().
parsePathName()
bool ExFatFile::parsePathName (const char * path, ExName_t * fname, const char ** ptr) private
Definition at line 498 of file ExFatFile.cpp.
{
   // Skip leading spaces.
   while (*path == ' ') {
     path++;
   }
   fname->begin = path;
   fname->end = path;
   while (*path && !isDirSeparator(*path)) {
     uint8_t c = *path++;
     if (!lfnLegalChar(c)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (c != '.' && c != ' ') {
       // Need to trim trailing dots spaces.
       fname->end = path;
     }
   }
   // Advance to next path component.
   for (; *path == ' ' || isDirSeparator(*path); path++) {}
   *ptr = path;
   return hashName(fname);
  fail:
   return false;
 }
References FsName::begin, DBG_FAIL_MACRO, FsName::end, hashName(), isDirSeparator, and lfnLegalChar().
Referenced by mkdir(), and open().
peek()
int ExFatFile::peek ()
Return the next available byte without consuming it.
Returns
The byte if no error and not at eof else -1;
Definition at line 526 of file ExFatFile.cpp.
                     {
   uint64_t curPosition = m_curPosition;
   uint32_t curCluster = m_curCluster;
   int c = read();
   m_curPosition = curPosition;
   m_curCluster = curCluster;
   return c;
 }
References curCluster(), curPosition(), m_curCluster, m_curPosition, and read().
preAllocate()
bool ExFatFile::preAllocate (uint64_t length)
Allocate contiguous clusters to an empty file.
The file must be empty with no clusters allocated.
The file will have zero validLength and dataLength will equal the requested length.
Parameters
[in] length size of allocated space in bytes.
Returns
true for success or false for failure.
Definition at line 225 of file ExFatFileWrite.cpp.
{
   uint32_t find;
   uint32_t need;
   if (!length || !isWritable() || m_firstCluster) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   need = 1 + ((length - 1) >> m_vol->bytesPerClusterShift());
   find = m_vol->bitmapFind(0, need);
   if (find < 2) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!m_vol->bitmapModify(find, need, 1)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_dataLength = length;
   m_firstCluster = find;
   m_flags |= FILE_FLAG_DIR_DIRTY | FILE_FLAG_CONTIGUOUS;
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References ExFatPartition::bitmapFind(), ExFatPartition::bitmapModify(), ExFatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, FILE_FLAG_CONTIGUOUS, FILE_FLAG_DIR_DIRTY, isWritable(), m_dataLength, m_firstCluster, m_flags, m_vol, and sync().
printAccessDateTime()
size_t ExFatFile::printAccessDateTime (print_t * pr)
Print a file's access date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 101 of file ExFatFilePrint.cpp.
{
   uint16_t date;
   uint16_t time;
   if (getAccessDateTime(&date, &time)) {
     return fsPrintDateTime(pr, date, time);
   }
   return 0;
 }
References fsPrintDateTime(), and getAccessDateTime().
printCreateDateTime()
size_t ExFatFile::printCreateDateTime (print_t * pr)
Print a file's creation date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 110 of file ExFatFilePrint.cpp.
{
   uint16_t date;
   uint16_t time;
   if (getCreateDateTime(&date, &time)) {
     return fsPrintDateTime(pr, date, time);
   }
   return 0;
 }
References fsPrintDateTime(), and getCreateDateTime().
printField() [1/3]
size_t ExFatFile::printField (double value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 449 of file ExFatFile.h.
{
     char buf[24];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     str = fmtDouble(str, value, prec, false);
     return write(str, buf + sizeof(buf) - str);
   }
References buf, fmtDouble(), and write().
Referenced by printField().
printField() [2/3]
size_t ExFatFile::printField (float value, char term, uint8_t prec = 2) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
[in] prec Number of digits after decimal point.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 467 of file ExFatFile.h.
{
     return printField(static_cast<double>(value), term, prec);
   }
References printField().
printField() [3/3]
template<typename Type > size_t ExFatFile::printField (Type value, char term) inline
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] term The field terminator. Use '\n' for CR LF.
Returns
The number of bytes written or -1 if an error occurs.
Definition at line 476 of file ExFatFile.h.
{
     char sign = 0;
     char buf[3*sizeof(Type) + 3];
     char* str = buf + sizeof(buf);
     if (term) {
       *--str = term;
       if (term == '\n') {
         *--str = '\r';
       }
     }
     if (value < 0) {
       value = -value;
       sign = '-';
     }
     if (sizeof(Type) < 4) {
       str = fmtBase10(str, (uint16_t)value);
     } else {
       str = fmtBase10(str, (uint32_t)value);
     }
     if (sign) {
       *--str = sign;
     }
     return write(str, &buf[sizeof(buf)] - str);
   }
References buf, fmtBase10(), and write().
printFileSize()
size_t ExFatFile::printFileSize (print_t * pr)
Print a file's size in bytes.
Parameters
[in] pr Prtin stream for the output.
Returns
The number of bytes printed.
Definition at line 119 of file ExFatFilePrint.cpp.
{
   uint64_t n = m_validLength;
   char buf[21];
   char *str = &buf[sizeof(buf) - 1];
   char *bgn = str - 12;
   *str = '\0';
   do {
     uint64_t m = n;
     n /= 10;
     *--str = m - 10*n + '0';
   } while (n);
   while (str > bgn) {
     *--str = ' ';
   }
   return pr->write(str);
 }
References buf, m, m_validLength, and PrintBasic::write().
Referenced by ls().
printModifyDateTime()
size_t ExFatFile::printModifyDateTime (print_t * pr)
Print a file's modify date and time
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 136 of file ExFatFilePrint.cpp.
{
   uint16_t date;
   uint16_t time;
   if (getModifyDateTime(&date, &time)) {
     return fsPrintDateTime(pr, date, time);
   }
   return 0;
 }
References fsPrintDateTime(), and getModifyDateTime().
Referenced by ls().
printName()
size_t ExFatFile::printName (print_t * pr) inline
Print a file's name
Parameters
[in] pr Print stream for output.
Returns
length for success or zero for failure.
Definition at line 519 of file ExFatFile.h.
{
 #if USE_UTF8_LONG_NAMES
     return printName8(pr);
 #else  // USE_UTF8_LONG_NAMES
     return printName7(pr);
 #endif  // USE_UTF8_LONG_NAMES
   }
References printName7(), and printName8().
Referenced by ls().
printName7()
size_t ExFatFile::printName7 (print_t * pr)
Print a file's ASCII name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 145 of file ExFatFilePrint.cpp.
{
   DirName_t* dn;
   size_t n = 0;
   uint8_t in;
   uint8_t buf[15];
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   for (uint8_t is = 2; is <= m_setCount; is++) {
     dn = reinterpret_cast<DirName_t*>
          (dirCache(is, FsCache::CACHE_FOR_READ));
     if (!dn || dn->type != EXFAT_TYPE_NAME) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (in = 0; in < 15; in++) {
       uint16_t c = getLe16(dn->unicode + 2*in);
       if (!c) {
         break;
       }
       buf[in] = c < 0X7F ? c : '?';
       n++;
     }
     pr->write(buf, in);
   }
   return n;
  fail:
   return 0;
 }
References buf, FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, dirCache(), EXFAT_TYPE_NAME, getLe16(), isOpen(), m_setCount, DirName_t::type, DirName_t::unicode, and PrintBasic::write().
Referenced by printName().
printName8()
size_t ExFatFile::printName8 (print_t * pr)
Print a file's UTF-8 name
Parameters
[in] pr Print stream for output.
Returns
true for success or false for failure.
Definition at line 177 of file ExFatFilePrint.cpp.
{
   DirName_t* dn;
   uint16_t hs = 0;
   uint32_t cp;
   size_t n = 0;
   uint8_t in;
   char buf[5];
   if (!isOpen()) {
       DBG_FAIL_MACRO;
       goto fail;
   }
   for (uint8_t is = 2; is <= m_setCount; is++) {
     dn = reinterpret_cast<DirName_t*>
          (dirCache(is, FsCache::CACHE_FOR_READ));
     if (!dn || dn->type != EXFAT_TYPE_NAME) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (in = 0; in < 15; in++) {
       uint16_t c = getLe16(dn->unicode + 2*in);
       if (hs) {
         if (!FsUtf::isLowSurrogate(c)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         cp = FsUtf::u16ToCp(hs, c);
         hs = 0;
       } else if (!FsUtf::isSurrogate(c)) {
         if (c == 0) {
           break;
         }
         cp = c;
       } else if (FsUtf::isHighSurrogate(c)) {
         hs = c;
         continue;
       } else {
         DBG_FAIL_MACRO;
         goto fail;
       }
       char* str = FsUtf::cpToMb(cp, buf, buf + sizeof(buf));
       if (!str) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       n += pr->write(buf, str - buf);
     }
   }
   return n;
  fail:
   return 0;
 }
References buf, FsCache::CACHE_FOR_READ, FsUtf::cpToMb(), DBG_FAIL_MACRO, dirCache(), EXFAT_TYPE_NAME, getLe16(), FsUtf::isHighSurrogate(), FsUtf::isLowSurrogate(), isOpen(), FsUtf::isSurrogate(), m_setCount, DirName_t::type, FsUtf::u16ToCp(), DirName_t::unicode, and PrintBasic::write().
Referenced by printName().
read() [1/2]
int ExFatFile::read () inline
Read the next byte from a file.
Returns
For success read returns the next byte in the file as an int. If an error occurs or end of file is reached -1 is returned.
Definition at line 545 of file ExFatFile.h.
              {
     uint8_t b;
     return read(&b, 1) == 1 ? b : -1;
   }
Referenced by fgets(), openPrivate(), peek(), ExFatPartition::printDir(), and rmdir().
read() [2/2]
int ExFatFile::read (void * buf, size_t count)
Read data from a file starting at the current position.
Parameters
[out] buf Pointer to the location that will receive the data.
[in] count Maximum number of bytes to read.
Returns
For success read() returns the number of bytes read. A value less than nbyte, including zero, will be returned if end of file is reached. If an error occurs, read() returns -1.
Definition at line 535 of file ExFatFile.cpp.
{
   uint8_t* dst = reinterpret_cast<uint8_t*>(buf);
   int8_t fg;
   size_t toRead = count;
   size_t n;
   uint8_t* cache;
   uint16_t sectorOffset;
   uint32_t sector;
   uint32_t clusterOffset;
   if (!isReadable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isContiguous() || isFile()) {
     if ((m_curPosition + count) > m_validLength) {
       count = toRead = m_validLength - m_curPosition;
     }
   }
   while (toRead) {
     clusterOffset = m_curPosition & m_vol->clusterMask();
     sectorOffset = clusterOffset & m_vol->sectorMask();
     if (clusterOffset == 0) {
       if (m_curPosition == 0) {
         m_curCluster = isRoot()
                        ? m_vol->rootDirectoryCluster() : m_firstCluster;
       } else if (isContiguous()) {
         m_curCluster++;
       } else {
         fg = m_vol->fatGet(m_curCluster, &m_curCluster);
         if (fg < 0) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         if (fg == 0) {
           // EOF if directory.
           if (isDir()) {
             break;
           }
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
     }
     sector = m_vol->clusterStartSector(m_curCluster) +
              (clusterOffset >> m_vol->bytesPerSectorShift());
     if (sectorOffset != 0 || toRead < m_vol->bytesPerSector()
                           || sector == m_vol->dataCacheSector()) {
       n = m_vol->bytesPerSector() - sectorOffset;
       if (n > toRead) {
         n = toRead;
       }
       // read sector to cache and copy data to caller
       cache = m_vol->dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
       if (!cache) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       uint8_t* src = cache + sectorOffset;
       memcpy(dst, src, n);
 #if USE_MULTI_SECTOR_IO
     } else if (toRead >= 2*m_vol->bytesPerSector()) {
       uint32_t ns = toRead >> m_vol->bytesPerSectorShift();
       // Limit reads to current cluster.
       uint32_t maxNs = m_vol->sectorsPerCluster()
                        - (clusterOffset >> m_vol->bytesPerSectorShift());
       if (ns > maxNs) {
         ns = maxNs;
       }
       n = ns << m_vol->bytesPerSectorShift();
      if (!m_vol->cacheSafeRead(sector, dst, ns)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
 #endif  // USE_MULTI_SECTOR_IO
     } else {
       // read single sector
       n = m_vol->bytesPerSector();
       if (!m_vol->cacheSafeRead(sector, dst)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     dst += n;
     m_curPosition += n;
     toRead -= n;
   }
   return count - toRead;
  fail:
   m_error |= READ_ERROR;
   return -1;
 }
References buf, ExFatPartition::bytesPerSector(), ExFatPartition::bytesPerSectorShift(), FsCache::CACHE_FOR_READ, ExFatPartition::cacheSafeRead(), ExFatPartition::clusterMask(), ExFatPartition::clusterStartSector(), count, ExFatPartition::dataCachePrepare(), ExFatPartition::dataCacheSector(), DBG_FAIL_MACRO, dst, ExFatPartition::fatGet(), isContiguous(), isDir(), isFile(), isReadable(), isRoot(), m_curCluster, m_curPosition, m_error, m_firstCluster, m_validLength, m_vol, READ_ERROR, ExFatPartition::rootDirectoryCluster(), ExFatPartition::sectorMask(), and ExFatPartition::sectorsPerCluster().
remove() [1/2]
bool ExFatFile::remove ()
Remove a file.
The directory entry and all data for the file are deleted.
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 255 of file ExFatFileWrite.cpp.
{
   uint8_t* cache;
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Free any clusters.
   if (m_firstCluster) {
     if (isContiguous()) {
       uint32_t nc = 1 + ((m_dataLength - 1) >> m_vol->bytesPerClusterShift());
       if (!m_vol->bitmapModify(m_firstCluster, nc, 0)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     } else {
       if (!m_vol->freeChain(m_firstCluster)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   }
   for (uint8_t is = 0; is <= m_setCount; is++) {
     cache = dirCache(is, FsCache::CACHE_FOR_WRITE);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // Mark entry not used.
     cache[0] &= 0x7F;
   }
   // Set this file closed.
   m_attributes = FILE_ATTR_CLOSED;
   m_flags = 0;
   // Write entry to device.
   return m_vol->cacheSync();
  fail:
   return false;
 }
References ExFatPartition::bitmapModify(), ExFatPartition::bytesPerClusterShift(), FsCache::CACHE_FOR_WRITE, ExFatPartition::cacheSync(), DBG_FAIL_MACRO, dirCache(), FILE_ATTR_CLOSED, ExFatPartition::freeChain(), isContiguous(), isWritable(), m_attributes, m_dataLength, m_firstCluster, m_flags, m_setCount, and m_vol.
Referenced by FsBaseFile::remove(), remove(), ExFatVolume::remove(), rename(), and rmdir().
remove() [2/2]
bool ExFatFile::remove (const char * path)
Remove a file.
The directory entry and all data for the file are deleted.
Parameters
[in] path Path for the file to be removed.
Example use: dirFile.remove(filenameToRemove);
Note
This function should not be used to delete the 8.3 version of a file that has a long name. For example if a file has the long name "New Text Document.txt" you should not delete the 8.3 name "NEWTEX~1.TXT".
Returns
true for success or false for failure.
Definition at line 629 of file ExFatFile.cpp.
{
   ExFatFile file;
   if (!file.open(this, path, O_WRONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return file.remove();
  fail:
   return false;
 }
References DBG_FAIL_MACRO, O_WRONLY, open(), and remove().
rename() [1/2]
bool ExFatFile::rename (const char * newPath)
Rename a file or subdirectory.
Parameters
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 297 of file ExFatFileWrite.cpp.
{
   return rename(m_vol->vwd(), newPath);
 }
References m_vol, and ExFatVolume::vwd().
Referenced by ExFatVolume::rename().
rename() [2/2]
bool ExFatFile::rename (ExFatFile * dirFile, const char * newPath)
Rename a file or subdirectory.
Parameters
[in] dirFile Directory for the new path.
[in] newPath New path name for the file/directory.
Returns
true for success or false for failure.
Definition at line 301 of file ExFatFileWrite.cpp.
{
   ExFatFile file;
   ExFatFile oldFile;
   // Must be an open file or subdirectory.
   if (!(isFile() || isSubDir())) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Can't move file to new volume.
   if (m_vol != dirFile->m_vol) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!file.open(dirFile, newPath, O_CREAT | O_EXCL | O_WRONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   oldFile = *this;
   m_dirPos = file.m_dirPos;
   m_setCount = file.m_setCount;
   m_flags |= FILE_FLAG_DIR_DIRTY;
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Remove old directory entry;
   oldFile.m_firstCluster = 0;
   oldFile.m_flags = FILE_FLAG_WRITE;
   oldFile.m_attributes = FILE_ATTR_FILE;
   return oldFile.remove();
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FILE_ATTR_FILE, FILE_FLAG_DIR_DIRTY, FILE_FLAG_WRITE, isFile(), isSubDir(), m_attributes, m_dirPos, m_firstCluster, m_flags, m_setCount, m_vol, O_CREAT, O_EXCL, O_WRONLY, open(), remove(), and sync().
rewind()
void ExFatFile::rewind () inline
Set the file's current position to zero.
Definition at line 603 of file ExFatFile.h.
                 {
     seekSet(0);
   }
References seekSet().
Referenced by ls(), mkdir(), openPrivate(), and rmdir().
rmdir()
bool ExFatFile::rmdir ()
Remove a directory file.
The directory file will be removed only if it is empty and is not the root directory. rmdir() follows DOS and Windows and ignores the read-only attribute for the directory.
Note
This function should not be used to delete the 8.3 version of a directory that has a long name. For example if a directory has the long name "New folder" you should not delete the 8.3 name "NEWFOL~1".
Returns
true for success or false for failure.
Definition at line 337 of file ExFatFileWrite.cpp.
                       {
   int n;
   uint8_t dir[FS_DIR_SIZE];
   // must be open subdirectory
   if (!isSubDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   rewind();
   // make sure directory is empty
   while (1) {
     n = read(dir, FS_DIR_SIZE);
     if (n == 0) {
       break;
     }
     if (n != FS_DIR_SIZE || dir[0] & 0X80) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (dir[0] == 0) {
       break;
     }
   }
   // convert empty directory to normal file for remove
   m_attributes = FILE_ATTR_FILE;
   m_flags |= FILE_FLAG_WRITE;
   return remove();
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FILE_ATTR_FILE, FILE_FLAG_WRITE, FS_DIR_SIZE, isSubDir(), m_attributes, m_flags, read(), remove(), and rewind().
Referenced by FsBaseFile::rmdir(), and ExFatVolume::rmdir().
seekCur()
bool ExFatFile::seekCur (int64_t offset) inline
Set the files position to current position + pos. See seekSet().
Parameters
[in] offset The new position in bytes from the current position.
Returns
true for success or false for failure.
Definition at line 623 of file ExFatFile.h.
{
     return seekSet(m_curPosition + offset);
   }
References m_curPosition, and seekSet().
seekEnd()
bool ExFatFile::seekEnd (int64_t offset = 0) inline
Set the files position to end-of-file + offset. See seekSet(). Can't be used for directory files since file size is not defined.
Parameters
[in] offset The new position in bytes from end-of-file.
Returns
true for success or false for failure.
Definition at line 631 of file ExFatFile.h.
{
     return isFile() ? seekSet(m_validLength + offset) : false;
   }
References isFile(), m_validLength, and seekSet().
seekSet()
bool ExFatFile::seekSet (uint64_t pos)
Sets a file's position.
Parameters
[in] pos The new position in bytes from the beginning of the file.
Returns
true for success or false for failure.
Definition at line 641 of file ExFatFile.cpp.
{
   uint32_t nCur;
   uint32_t nNew;
   uint32_t tmp = m_curCluster;
   // error if file not open
   if (!isOpen()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // Optimize O_APPEND writes.
   if (pos == m_curPosition) {
     return true;
   }
   if (pos == 0) {
     // set position to start of file
     m_curCluster = 0;
     goto done;
   }
   if (isFile()) {
     if (pos > m_validLength) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   // calculate cluster index for new position
   nNew = (pos - 1) >> m_vol->bytesPerClusterShift();
   if (isContiguous()) {
     m_curCluster = m_firstCluster + nNew;
     goto done;
   }
   // calculate cluster index for current position
   nCur = (m_curPosition - 1) >> m_vol->bytesPerClusterShift();
   if (nNew < nCur || m_curPosition == 0) {
     // must follow chain from first cluster
     m_curCluster = isRoot() ? m_vol->rootDirectoryCluster() : m_firstCluster;
   } else {
     // advance from curPosition
     nNew -= nCur;
   }
   while (nNew--) {
     if (m_vol->fatGet(m_curCluster, &m_curCluster) <= 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
  done:
   m_curPosition = pos;
   return true;
  fail:
   m_curCluster = tmp;
   return false;
 }
References ExFatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, ExFatPartition::fatGet(), isContiguous(), isFile(), isOpen(), isRoot(), m_curCluster, m_curPosition, m_firstCluster, m_validLength, m_vol, and ExFatPartition::rootDirectoryCluster().
Referenced by open(), openPrivate(), rewind(), seekCur(), seekEnd(), truncate(), and write().
setCount()
uint8_t ExFatFile::setCount () const inline
Returns
directory set count
Definition at line 642 of file ExFatFile.h.
 {return m_setCount;}
References m_setCount.
sync()
bool ExFatFile::sync ()
The sync() call causes all modified data and directory fields to be written to the storage device.
Returns
true for success or false for failure.
Definition at line 370 of file ExFatFileWrite.cpp.
                      {
   if (!isOpen()) {
     return true;
   }
   if (m_flags & FILE_FLAG_DIR_DIRTY) {
     // clear directory dirty
     m_flags &= ~FILE_FLAG_DIR_DIRTY;
     return syncDir();
   }
   if (!m_vol->cacheSync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   m_error |= WRITE_ERROR;
   return false;
 }
References ExFatPartition::cacheSync(), DBG_FAIL_MACRO, FILE_FLAG_DIR_DIRTY, isOpen(), m_error, m_flags, m_vol, syncDir(), and WRITE_ERROR.
Referenced by addDirCluster(), close(), flush(), mkdir(), openPrivate(), preAllocate(), rename(), timestamp(), and truncate().
syncDir()
bool ExFatFile::syncDir () private
Definition at line 390 of file ExFatFileWrite.cpp.
{
   DirFile_t* df;
   DirStream_t* ds;
   uint8_t* cache;
   uint16_t checksum = 0;
   for (uint8_t is = 0; is <= m_setCount ; is++) {
     cache = dirCache(is, FsCache::CACHE_FOR_READ);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     switch (cache[0]) {
       case EXFAT_TYPE_FILE:
         df = reinterpret_cast<DirFile_t*>(cache);
         setLe16(df->attributes, m_attributes & FILE_ATTR_COPY);
         if (FsDateTime::callback) {
           uint16_t date, time;
           uint8_t ms10;
           FsDateTime::callback(&date, &time, &ms10);
           df->modifyTimeMs = ms10;
           setLe16(df->modifyTime, time);
           setLe16(df->modifyDate, date);
           setLe16(df->accessTime, time);
           setLe16(df->accessDate, date);
         }
         m_vol->dataCacheDirty();
         break;
       case EXFAT_TYPE_STREAM:
         ds = reinterpret_cast<DirStream_t*>(cache);
         if (isContiguous()) {
           ds->flags |= EXFAT_FLAG_CONTIGUOUS;
         } else {
           ds->flags &= ~EXFAT_FLAG_CONTIGUOUS;
         }
         setLe64(ds->validLength, m_validLength);
         setLe32(ds->firstCluster, m_firstCluster);
         setLe64(ds->dataLength, m_dataLength);
         m_vol->dataCacheDirty();
         break;
       case EXFAT_TYPE_NAME:
         break;
       default:
         DBG_FAIL_MACRO;
         goto fail;
         break;
     }
     checksum = exFatDirChecksum(cache, checksum);
   }
   df = reinterpret_cast<DirFile_t*>
        (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_WRITE));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   setLe16(df->setChecksum, checksum);
   if (!m_vol->cacheSync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   m_error |= WRITE_ERROR;
   return false;
 }
References DirFile_t::accessDate, DirFile_t::accessTime, DirFile_t::attributes, FsCache::CACHE_FOR_READ, FsCache::CACHE_FOR_WRITE, ExFatPartition::cacheSync(), FsDateTime::callback, ExFatPartition::dataCacheDirty(), DirStream_t::dataLength, DBG_FAIL_MACRO, ExFatPartition::dirCache(), dirCache(), EXFAT_FLAG_CONTIGUOUS, EXFAT_TYPE_FILE, EXFAT_TYPE_NAME, EXFAT_TYPE_STREAM, exFatDirChecksum(), FILE_ATTR_COPY, DirStream_t::firstCluster, DirStream_t::flags, isContiguous(), m_attributes, m_dataLength, m_dirPos, m_error, m_firstCluster, m_setCount, m_validLength, m_vol, DirFile_t::modifyDate, DirFile_t::modifyTime, DirFile_t::modifyTimeMs, DirFile_t::setChecksum, setLe16(), setLe32(), setLe64(), DirStream_t::validLength, and WRITE_ERROR.
Referenced by sync().
timestamp()
bool ExFatFile::timestamp (uint8_t flags, uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)
Truncate a file at the current file position.
Returns
true for success or false for failure. Set a file's timestamps in its directory entry.
Parameters
[in] flags Values for flags are constructed by a bitwise-inclusive OR of flags from the following list
T_ACCESS - Set the file's last access date and time.
T_CREATE - Set the file's creation date and time.
T_WRITE - Set the file's last write/modification date and time.
Parameters
[in] year Valid range 1980 - 2107 inclusive.
[in] month Valid range 1 - 12 inclusive.
[in] day Valid range 1 - 31 inclusive.
[in] hour Valid range 0 - 23 inclusive.
[in] minute Valid range 0 - 59 inclusive.
[in] second Valid range 0 - 59 inclusive
Note
It is possible to set an invalid date since there is no check for the number of days in a month.
Modify and access timestamps may be overwritten if a date time callback function has been set by dateTimeCallback().
Returns
true for success or false for failure.
Definition at line 460 of file ExFatFileWrite.cpp.
{
   DirFile_t* df;
   uint8_t* cache;
   uint16_t checksum = 0;
   uint16_t date;
   uint16_t time;
   uint8_t ms10;
   if (!isFile()
       || year < 1980
       || year > 2107
       || month < 1
       || month > 12
       || day < 1
       || day > 31
       || hour > 23
       || minute > 59
       || second > 59) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // update directory entry
   if (!sync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   date = FS_DATE(year, month, day);
   time = FS_TIME(hour, minute, second);
   ms10 = second & 1 ? 100 : 0;
   for (uint8_t is = 0; is <= m_setCount; is++) {
     cache = dirCache(is, FsCache::CACHE_FOR_READ);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     switch (cache[0]) {
       case EXFAT_TYPE_FILE:
         df = reinterpret_cast<DirFile_t*>(cache);
         setLe16(df->attributes, m_attributes & FILE_ATTR_COPY);
         m_vol->dataCacheDirty();
         if (flags & T_ACCESS) {
           setLe16(df->accessTime, time);
           setLe16(df->accessDate, date);
         }
         if (flags & T_CREATE) {
           df->createTimeMs = ms10;
           setLe16(df->createTime, time);
           setLe16(df->createDate, date);
         }
         if (flags & T_WRITE) {
           df->modifyTimeMs = ms10;
           setLe16(df->modifyTime, time);
           setLe16(df->modifyDate, date);
         }
         break;
       case EXFAT_TYPE_STREAM:
         break;
       case EXFAT_TYPE_NAME:
         break;
       default:
         DBG_FAIL_MACRO;
         goto fail;
         break;
     }
     checksum = exFatDirChecksum(cache, checksum);
   }
   df = reinterpret_cast<DirFile_t*>
        (m_vol->dirCache(&m_dirPos, FsCache::CACHE_FOR_WRITE));
   if (!df) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   setLe16(df->setChecksum, checksum);
   if (!m_vol->cacheSync()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   return true;
  fail:
   return false;
 }
References DirFile_t::accessDate, DirFile_t::accessTime, DirFile_t::attributes, FsCache::CACHE_FOR_READ, FsCache::CACHE_FOR_WRITE, ExFatPartition::cacheSync(), DirFile_t::createDate, DirFile_t::createTime, DirFile_t::createTimeMs, ExFatPartition::dataCacheDirty(), DBG_FAIL_MACRO, ExFatPartition::dirCache(), dirCache(), EXFAT_TYPE_FILE, EXFAT_TYPE_NAME, EXFAT_TYPE_STREAM, exFatDirChecksum(), FILE_ATTR_COPY, FS_DATE(), FS_TIME(), isFile(), m_attributes, m_dirPos, m_setCount, m_vol, DirFile_t::modifyDate, DirFile_t::modifyTime, DirFile_t::modifyTimeMs, DirFile_t::setChecksum, setLe16(), sync(), T_ACCESS, T_CREATE, and T_WRITE.
truncate() [1/2]
bool ExFatFile::truncate ()
Truncate a file at the current file position. will be maintained if it is less than or equal to length otherwise it will be set to end of file.
Returns
true for success or false for failure.
Definition at line 549 of file ExFatFileWrite.cpp.
{
   uint32_t toFree;
   // error if not a normal file or read-only
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (m_firstCluster == 0) {
       return true;
   }
   if (isContiguous()) {
     uint32_t nc = 1 + ((m_dataLength - 1) >> m_vol->bytesPerClusterShift());
     if (m_curCluster) {
       toFree = m_curCluster + 1;
       nc -= 1 + m_curCluster - m_firstCluster;
     } else {
       toFree = m_firstCluster;
       m_firstCluster = 0;
     }
     if (nc && !m_vol->bitmapModify(toFree, nc, 0)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } else {
     // need to free chain
     if (m_curCluster) {
       toFree = 0;
       int8_t fg = m_vol->fatGet(m_curCluster, &toFree);
       if (fg < 0) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       if (fg) {
         // current cluster is end of chain
         if (!m_vol->fatPut(m_curCluster, EXFAT_EOC)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
     } else {
       toFree = m_firstCluster;
       m_firstCluster = 0;
     }
     if (toFree) {
       if (!m_vol->freeChain(toFree)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
   }
   m_dataLength = m_curPosition;
   m_validLength = m_curPosition;
   m_flags |= FILE_FLAG_DIR_DIRTY;
   return sync();
  fail:
   return false;
 }
References ExFatPartition::bitmapModify(), ExFatPartition::bytesPerClusterShift(), DBG_FAIL_MACRO, EXFAT_EOC, ExFatPartition::fatGet(), ExFatPartition::fatPut(), FILE_FLAG_DIR_DIRTY, ExFatPartition::freeChain(), isContiguous(), isWritable(), m_curCluster, m_curPosition, m_dataLength, m_firstCluster, m_flags, m_validLength, m_vol, and sync().
Referenced by openPrivate(), ExFatVolume::truncate(), and truncate().
truncate() [2/2]
bool ExFatFile::truncate (uint64_t length) inline
Truncate a file to a specified length. The current file position will be set to end of file.
Parameters
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 701 of file ExFatFile.h.
{
     return seekSet(length) && truncate();
   }
References seekSet(), and truncate().
validLength()
uint64_t ExFatFile::validLength () const inline
Returns
The valid number of bytes in a file.
Definition at line 706 of file ExFatFile.h.
 {return m_validLength;}
References m_validLength.
volume()
ExFatVolume* ExFatFile::volume () const inline private
Definition at line 773 of file ExFatFile.h.
 {return m_vol;}
References m_vol.
Referenced by openPrivate().
write() [1/3]
size_t ExFatFile::write (const char * str) inline
Write a string to a file. Used by the Arduino Print class.
Parameters
[in] str Pointer to the string. Use getWriteError to check for errors.
Returns
count of characters written for success or -1 for failure.
Definition at line 712 of file ExFatFile.h.
{
     return write(str, strlen(str));
   }
Referenced by printField().
write() [2/3]
size_t ExFatFile::write (const void * buf, size_t count)
Write data to an open file.
Note
Data is moved to the cache but may not be written to the storage device until sync() is called.
Parameters
[in] buf Pointer to the location of the data to be written.
[in] count Number of bytes to write.
Returns
For success write() returns the number of bytes written, always count. If an error occurs, write() returns zero and writeError is set.
Definition at line 608 of file ExFatFileWrite.cpp.
{
   // convert void* to uint8_t*  -  must be before goto statements
   const uint8_t* src = reinterpret_cast<const uint8_t*>(buf);
   uint8_t* cache;
   uint8_t cacheOption;
   uint16_t sectorOffset;
   uint32_t sector;
   uint32_t clusterOffset;
   // number of bytes left to write  -  must be before goto statements
   size_t toWrite = nbyte;
   size_t n;
   // error if not an open file or is read-only
   if (!isWritable()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // seek to end of file if append flag
   if ((m_flags & FILE_FLAG_APPEND)) {
     if (!seekSet(m_validLength)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   while (toWrite) {
     clusterOffset = m_curPosition & m_vol->clusterMask();
     sectorOffset = clusterOffset & m_vol->sectorMask();
     if (clusterOffset == 0) {
       // start of new cluster
       if (m_curCluster != 0) {
         int fg;
         if (isContiguous()) {
           uint32_t lc = m_firstCluster;
           lc += (m_dataLength - 1) >> m_vol->bytesPerClusterShift();
           if (m_curCluster < lc) {
             m_curCluster++;
             fg = 1;
           } else {
             fg = 0;
           }
         } else {
           fg = m_vol->fatGet(m_curCluster, &m_curCluster);
           if (fg < 0) {
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
         if (fg == 0) {
           // add cluster if at end of chain
           if (!addCluster()) {
             DBG_FAIL_MACRO;
             goto fail;
           }
         }
       } else {
         if (m_firstCluster == 0) {
           // allocate first cluster of file
           if (!addCluster()) {
             DBG_FAIL_MACRO;
             goto fail;
           }
           m_firstCluster = m_curCluster;
         } else {
           m_curCluster = m_firstCluster;
         }
       }
     }
     // sector for data write
     sector = m_vol->clusterStartSector(m_curCluster) +
              (clusterOffset >> m_vol->bytesPerSectorShift());
     if (sectorOffset != 0 || toWrite < m_vol->bytesPerSector()) {
       // partial sector - must use cache
       // max space in sector
       n = m_vol->bytesPerSector() - sectorOffset;
       // lesser of space and amount to write
       if (n > toWrite) {
         n = toWrite;
       }
       if (sectorOffset == 0 && m_curPosition >= m_validLength) {
         // start of new sector don't need to read into cache
         cacheOption = FsCache::CACHE_RESERVE_FOR_WRITE;
       } else {
         // rewrite part of sector
         cacheOption = FsCache::CACHE_FOR_WRITE;
       }
       cache = m_vol->dataCachePrepare(sector, cacheOption);
       if (!cache) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       uint8_t* dst = cache + sectorOffset;
       memcpy(dst, src, n);
       if (m_vol->bytesPerSector() == (n + sectorOffset)) {
         // Force write if sector is full - improves large writes.
         if (!m_vol->dataCacheSync()) {
           DBG_FAIL_MACRO;
           goto fail;
         }
       }
 #if USE_MULTI_SECTOR_IO
     } else if (toWrite >= 2*m_vol->bytesPerSector()) {
       // use multiple sector write command
       uint32_t ns = toWrite >> m_vol->bytesPerSectorShift();
       // Limit writes to current cluster.
       uint32_t maxNs = m_vol->sectorsPerCluster()
                        - (clusterOffset >> m_vol->bytesPerSectorShift());
       if (ns > maxNs) {
         ns = maxNs;
       }
       n = ns << m_vol->bytesPerSectorShift();
       if (!m_vol->cacheSafeWrite(sector, src, ns)) {
          DBG_FAIL_MACRO;
         goto fail;
       }
 #endif  // USE_MULTI_SECTOR_IO
     } else {
       n = m_vol->bytesPerSector();
       if (!m_vol->cacheSafeWrite(sector, src)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     m_curPosition += n;
     src += n;
     toWrite -= n;
     if (m_curPosition > m_validLength) {
       m_flags |= FILE_FLAG_DIR_DIRTY;
       m_validLength = m_curPosition;
     }
   }
   if (m_curPosition > m_dataLength) {
     m_dataLength = m_curPosition;
     // update fileSize and insure sync will update dir entry
     m_flags |= FILE_FLAG_DIR_DIRTY;
   } else if (FsDateTime::callback) {
     // insure sync will update modified date and time
     m_flags |= FILE_FLAG_DIR_DIRTY;
   }
   return nbyte;
  fail:
   // return for write error
   m_error |= WRITE_ERROR;
   return 0;
 }
References addCluster(), buf, ExFatPartition::bytesPerClusterShift(), ExFatPartition::bytesPerSector(), ExFatPartition::bytesPerSectorShift(), FsCache::CACHE_FOR_WRITE, FsCache::CACHE_RESERVE_FOR_WRITE, ExFatPartition::cacheSafeWrite(), FsDateTime::callback, ExFatPartition::clusterMask(), ExFatPartition::clusterStartSector(), ExFatPartition::dataCachePrepare(), ExFatPartition::dataCacheSync(), DBG_FAIL_MACRO, dst, ExFatPartition::fatGet(), FILE_FLAG_APPEND, FILE_FLAG_DIR_DIRTY, isContiguous(), isWritable(), m_curCluster, m_curPosition, m_dataLength, m_error, m_firstCluster, m_flags, m_validLength, m_vol, ExFatPartition::sectorMask(), ExFatPartition::sectorsPerCluster(), seekSet(), and WRITE_ERROR.
write() [3/3]
size_t ExFatFile::write (uint8_t b) inline
Write a single byte.
Parameters
[in] b The byte to be written.
Returns
+1 for success or zero for failure.
Definition at line 719 of file ExFatFile.h.
 {return write(&b, 1);}
References write().
Referenced by write().
Friends And Related Function Documentation
ExFatVolume
friend class ExFatVolume friend
ExFatVolume allowed access to private members.
Definition at line 761 of file ExFatFile.h.
Member Data Documentation
FILE_ATTR_ARCHIVE
const uint8_t ExFatFile::FILE_ATTR_ARCHIVE = EXFAT_ATTRIB_ARCHIVE static private
Definition at line 791 of file ExFatFile.h.
FILE_ATTR_CLOSED
const uint8_t ExFatFile::FILE_ATTR_CLOSED = 0 static private
This file has not been opened.
Definition at line 780 of file ExFatFile.h.
Referenced by close(), openPrivate(), and remove().
FILE_ATTR_COPY
const uint8_t ExFatFile::FILE_ATTR_COPY static private
Initial value:
= EXFAT_ATTRIB_READ_ONLY |
                       EXFAT_ATTRIB_HIDDEN | EXFAT_ATTRIB_SYSTEM |
                       EXFAT_ATTRIB_DIRECTORY | EXFAT_ATTRIB_ARCHIVE
Attributes to copy from directory entry
Definition at line 797 of file ExFatFile.h.
Referenced by openPrivate(), syncDir(), and timestamp().
FILE_ATTR_DIR
const uint8_t ExFatFile::FILE_ATTR_DIR = FILE_ATTR_SUBDIR | FILE_ATTR_ROOT static private
Directory type bits
Definition at line 795 of file ExFatFile.h.
Referenced by isDir().
FILE_ATTR_FILE
const uint8_t ExFatFile::FILE_ATTR_FILE = 0X08 static private
Entry for normal data file
Definition at line 788 of file ExFatFile.h.
Referenced by isFile(), openPrivate(), rename(), and rmdir().
FILE_ATTR_HIDDEN
const uint8_t ExFatFile::FILE_ATTR_HIDDEN = EXFAT_ATTRIB_HIDDEN static private
File should be hidden in directory listings.
Definition at line 784 of file ExFatFile.h.
Referenced by isHidden().
FILE_ATTR_READ_ONLY
const uint8_t ExFatFile::FILE_ATTR_READ_ONLY = EXFAT_ATTRIB_READ_ONLY static private
File is read-only.
Definition at line 782 of file ExFatFile.h.
Referenced by isReadOnly().
FILE_ATTR_ROOT
const uint8_t ExFatFile::FILE_ATTR_ROOT = 0X40 static private
Root directory
Definition at line 793 of file ExFatFile.h.
Referenced by isRoot(), and openRoot().
FILE_ATTR_SUBDIR
const uint8_t ExFatFile::FILE_ATTR_SUBDIR = EXFAT_ATTRIB_DIRECTORY static private
Entry is for a subdirectory
Definition at line 790 of file ExFatFile.h.
Referenced by isSubDir(), and mkdir().
FILE_ATTR_SYSTEM
const uint8_t ExFatFile::FILE_ATTR_SYSTEM = EXFAT_ATTRIB_SYSTEM static private
Entry is for a system file.
Definition at line 786 of file ExFatFile.h.
FILE_FLAG_APPEND
const uint8_t ExFatFile::FILE_FLAG_APPEND = 0X08 static private
Definition at line 803 of file ExFatFile.h.
Referenced by openPrivate(), and write().
FILE_FLAG_CONTIGUOUS
const uint8_t ExFatFile::FILE_FLAG_CONTIGUOUS = 0X40 static private
Definition at line 804 of file ExFatFile.h.
Referenced by addCluster(), isContiguous(), mkdir(), openPrivate(), and preAllocate().
FILE_FLAG_DIR_DIRTY
const uint8_t ExFatFile::FILE_FLAG_DIR_DIRTY = 0X80 static private
Definition at line 805 of file ExFatFile.h.
Referenced by addDirCluster(), mkdir(), openPrivate(), preAllocate(), rename(), sync(), truncate(), and write().
FILE_FLAG_READ
const uint8_t ExFatFile::FILE_FLAG_READ = 0X01 static private
Definition at line 801 of file ExFatFile.h.
Referenced by isReadable(), mkdir(), openPrivate(), and openRoot().
FILE_FLAG_WRITE
const uint8_t ExFatFile::FILE_FLAG_WRITE = 0X02 static private
Definition at line 802 of file ExFatFile.h.
Referenced by isWritable(), openPrivate(), rename(), and rmdir().
m_attributes
uint8_t ExFatFile::m_attributes = FILE_ATTR_CLOSED private
Definition at line 816 of file ExFatFile.h.
Referenced by close(), isDir(), isFile(), isHidden(), isOpen(), isReadOnly(), isRoot(), isSubDir(), mkdir(), openPrivate(), openRoot(), remove(), rename(), rmdir(), syncDir(), and timestamp().
m_curCluster
uint32_t ExFatFile::m_curCluster private
Definition at line 811 of file ExFatFile.h.
Referenced by addCluster(), addDirCluster(), curCluster(), fgetpos(), fsetpos(), mkdir(), openPrivate(), peek(), read(), seekSet(), truncate(), and write().
m_curPosition
uint64_t ExFatFile::m_curPosition private
Definition at line 808 of file ExFatFile.h.
Referenced by curPosition(), fgetpos(), fsetpos(), peek(), read(), seekCur(), seekSet(), truncate(), and write().
m_dataLength
uint64_t ExFatFile::m_dataLength private
Definition at line 809 of file ExFatFile.h.
Referenced by addDirCluster(), dataLength(), openPrivate(), preAllocate(), remove(), syncDir(), truncate(), and write().
m_dirPos
DirPos_t ExFatFile::m_dirPos private
Definition at line 814 of file ExFatFile.h.
Referenced by dirCache(), dirIndex(), getAccessDateTime(), getCreateDateTime(), getModifyDateTime(), openPrivate(), rename(), syncDir(), and timestamp().
m_error
uint8_t ExFatFile::m_error = 0 private
Definition at line 817 of file ExFatFile.h.
Referenced by clearError(), clearWriteError(), getError(), getWriteError(), read(), sync(), syncDir(), and write().
m_firstCluster
uint32_t ExFatFile::m_firstCluster private
Definition at line 812 of file ExFatFile.h.
Referenced by addCluster(), firstSector(), mkdir(), openPrivate(), preAllocate(), read(), remove(), rename(), seekSet(), syncDir(), truncate(), and write().
m_flags
uint8_t ExFatFile::m_flags = 0 private
Definition at line 818 of file ExFatFile.h.
Referenced by addCluster(), addDirCluster(), close(), isContiguous(), isReadable(), isWritable(), mkdir(), openPrivate(), openRoot(), preAllocate(), remove(), rename(), rmdir(), sync(), truncate(), and write().
m_setCount
uint8_t ExFatFile::m_setCount private
Definition at line 815 of file ExFatFile.h.
Referenced by getName7(), getName8(), openPrivate(), printName7(), printName8(), remove(), rename(), setCount(), syncDir(), and timestamp().
m_validLength
uint64_t ExFatFile::m_validLength private
Definition at line 810 of file ExFatFile.h.
Referenced by addDirCluster(), contiguousRange(), fileSize(), openPrivate(), printFileSize(), read(), seekEnd(), seekSet(), syncDir(), truncate(), validLength(), and write().
m_vol
ExFatVolume* ExFatFile::m_vol private
Definition at line 813 of file ExFatFile.h.
Referenced by addCluster(), addDirCluster(), contiguousRange(), dirCache(), firstSector(), getAccessDateTime(), getCreateDateTime(), getModifyDateTime(), isBusy(), mkdir(), open(), openPrivate(), openRoot(), preAllocate(), read(), remove(), rename(), seekSet(), sync(), syncDir(), timestamp(), truncate(), volume(), and write().
READ_ERROR
const uint8_t ExFatFile::READ_ERROR = 0X2 static private
Definition at line 777 of file ExFatFile.h.
Referenced by read().
WRITE_ERROR
const uint8_t ExFatFile::WRITE_ERROR = 0X1 static private
Definition at line 776 of file ExFatFile.h.
Referenced by clearWriteError(), getWriteError(), sync(), syncDir(), and write().
The documentation for this class was generated from the following files:
ExFatFile.h
ExFatFile.cpp
ExFatFilePrint.cpp
ExFatFileWrite.cpp
ExFatName.cpp