ERIS CORE: FatVolume Class Reference
FatVolume Class Reference
Integration class for the FatLib library.
#include <FatVolume.h>
Public Member Functions
uint8_t __attribute__ ((error("use sectorsPerCluster()"))) blocksPerCluster()
bool begin (BlockDevice *dev, bool setCwv=true, uint8_t part=1)
uint16_t bytesPerCluster () const
uint8_t bytesPerClusterShift () const
uint16_t bytesPerSector () const
uint8_t bytesPerSectorShift () const
uint8_t * cacheClear ()
bool chdir ()
bool chdir (const char *path)
void chvol ()
uint32_t clusterCount () const
uint32_t dataStartSector () const
int8_t dbgFat (uint32_t n, uint32_t *v)
uint16_t dirEntriesPerCluster () const
bool dmpDirSector (print_t *pr, uint32_t sector)
void dmpFat (print_t *pr, uint32_t start, uint32_t count)
bool dmpRootDir (print_t *pr, uint32_t n=0)
void dmpSector (print_t *pr, uint32_t sector, uint8_t bits=8)
bool exists (const char *path)
uint8_t fatCount () const
uint32_t fatStartSector () const
uint8_t fatType () const
int32_t freeClusterCount ()
bool init (BlockDevice *dev, uint8_t part=1)
bool isBusy ()
bool ls (print_t *pr, const char *path, uint8_t flags)
bool ls (print_t *pr, uint8_t flags=0)
bool mkdir (const char *path, bool pFlag=true)
File32 open (const char *path, oflag_t oflag=O_RDONLY)
bool remove (const char *path)
bool rename (const char *oldPath, const char *newPath)
bool rmdir (const char *path)
uint16_t rootDirEntryCount () const
uint32_t rootDirStart () const
uint16_t sectorMask () const
uint8_t sectorsPerCluster () const
uint8_t sectorsPerClusterShift () const
uint32_t sectorsPerFat () const
bool truncate (const char *path, uint32_t length)
uint32_t volumeSectorCount () const
Private Member Functions
bool allocateCluster (uint32_t current, uint32_t *next)
bool allocContiguous (uint32_t count, uint32_t *firstCluster)
uint8_t * cacheAddress ()
void cacheDirty ()
void cacheInvalidate ()
bool cachePrepare (uint32_t sector, uint8_t option)
bool cacheSafeRead (uint32_t sector, uint8_t *dst)
bool cacheSafeRead (uint32_t sector, uint8_t *dst, size_t count)
bool cacheSafeWrite (uint32_t sector, const uint8_t *dst)
bool cacheSafeWrite (uint32_t sector, const uint8_t *dst, size_t count)
uint32_t cacheSectorNumber ()
bool cacheSync ()
bool cacheSyncData ()
uint32_t clusterStartSector (uint32_t cluster) const
FsCache * dataCache ()
uint8_t * dataCachePrepare (uint32_t sector, uint8_t options)
uint8_t * fatCachePrepare (uint32_t sector, uint8_t options)
int8_t fatGet (uint32_t cluster, uint32_t *value)
bool fatPut (uint32_t cluster, uint32_t value)
bool fatPutEOC (uint32_t cluster)
bool freeChain (uint32_t cluster)
bool isEOC (uint32_t cluster) const
uint8_t sectorOfCluster (uint32_t position) const
void setFreeClusterCount (int32_t value)
bool syncDevice ()
void updateFreeClusterCount (int32_t change)
FatFile * vwd ()
Static Private Member Functions
static FatVolume * cwv ()
Private Attributes
friend FatFile
uint32_t m_allocSearchStart
BlockDevice * m_blockDev
FsCache m_cache
uint8_t m_clusterSectorMask
uint32_t m_dataStartSector
uint32_t m_fatStartSector
uint8_t m_fatType = 0
uint32_t m_lastCluster
uint16_t m_rootDirEntryCount
uint32_t m_rootDirStart
uint8_t m_sectorsPerCluster
uint8_t m_sectorsPerClusterShift
uint32_t m_sectorsPerFat
FatFile m_vwd
Static Private Attributes
static const uint16_t m_bytesPerSector = 1 << m_bytesPerSectorShift
static const uint8_t m_bytesPerSectorShift = 9
static FatVolume * m_cwv = nullptr
static const uint16_t m_sectorMask = m_bytesPerSector - 1
Detailed Description
Integration class for the FatLib library.
Definition at line 37 of file FatVolume.h.
Member Function Documentation
__attribute__()
uint8_t FatPartition::__attribute__ ((error("use sectorsPerCluster()"))) inherited
allocateCluster()
bool FatPartition::allocateCluster (uint32_t current, uint32_t * next) private inherited
Definition at line 30 of file FatPartition.cpp.
{
   uint32_t find;
   bool setStart;
   if (m_allocSearchStart < current) {
     // Try to keep file contiguous. Start just after current cluster.
     find = current;
     setStart = false;
   } else {
     find = m_allocSearchStart;
     setStart = true;
   }
   while (1) {
     find++;
     if (find > m_lastCluster) {
       if (setStart) {
         // Can't find space, checked all clusters.
         DBG_FAIL_MACRO;
         goto fail;
       }
       find = m_allocSearchStart;
       setStart = true;
       continue;
     }
     if (find == current) {
       // Can't find space, already searched clusters after current.
       DBG_FAIL_MACRO;
       goto fail;
     }
     uint32_t f;
     int8_t fg = fatGet(find, &f);
     if (fg < 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (fg && f == 0) {
       break;
     }
   }
   if (setStart) {
     m_allocSearchStart = find;
   }
   // Mark end of chain.
   if (!fatPutEOC(find)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (current) {
     // Link clusters.
     if (!fatPut(current, find)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   updateFreeClusterCount(-1);
   *next = find;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::fatPutEOC(), FatPartition::m_allocSearchStart, FatPartition::m_lastCluster, and FatPartition::updateFreeClusterCount().
Referenced by FatFile::addCluster().
allocContiguous()
bool FatPartition::allocContiguous (uint32_t count, uint32_t * firstCluster) private inherited
Definition at line 92 of file FatPartition.cpp.
{
   // flag to save place to start next search
   bool setStart = true;
   // start of group
   uint32_t bgnCluster;
   // end of group
   uint32_t endCluster;
   // Start at cluster after last allocated cluster.
   endCluster = bgnCluster = m_allocSearchStart + 1;
   // search the FAT for free clusters
   while (1) {
     if (endCluster > m_lastCluster) {
       // Can't find space.
       DBG_FAIL_MACRO;
       goto fail;
     }
     uint32_t f;
     int8_t fg = fatGet(endCluster, &f);
     if (fg < 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (f || fg == 0) {
       // don't update search start if unallocated clusters before endCluster.
       if (bgnCluster != endCluster) {
         setStart = false;
       }
       // cluster in use try next cluster as bgnCluster
       bgnCluster = endCluster + 1;
     } else if ((endCluster - bgnCluster + 1) == count) {
       // done - found space
       break;
     }
     endCluster++;
   }
   // Remember possible next free cluster.
   if (setStart) {
     m_allocSearchStart = endCluster;
   }
   // mark end of chain
   if (!fatPutEOC(endCluster)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   // link clusters
   while (endCluster > bgnCluster) {
     if (!fatPut(endCluster - 1, endCluster)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     endCluster--;
   }
   // Maintain count of free clusters.
   updateFreeClusterCount(-count);
   // return first cluster number to caller
   *firstCluster = bgnCluster;
   return true;
  fail:
   return false;
 }
References count, DBG_FAIL_MACRO, FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::fatPutEOC(), FatPartition::m_allocSearchStart, FatPartition::m_lastCluster, and FatPartition::updateFreeClusterCount().
Referenced by FatFile::preAllocate().
begin()
bool FatVolume::begin (BlockDevice * dev, bool setCwv = true, uint8_t part = 1) inline
Initialize an FatVolume object.
Parameters
[in] dev Device block driver.
[in] setCwv Set current working volume if true.
[in] part partition to initialize.
Returns
true for success or false for failure.
Definition at line 46 of file FatVolume.h.
{
     if (!init(dev, part)) {
       return false;
     }
     if (!chdir()) {
       return false;
     }
     if (setCwv || !m_cwv) {
       m_cwv = this;
     }
     return true;
   }
References chdir(), FatPartition::init(), and m_cwv.
Referenced by FsVolume::begin().
bytesPerCluster()
uint16_t FatPartition::bytesPerCluster () const inline inherited
Returns
Number of bytes in a cluster.
Definition at line 62 of file FatPartition.h.
{
     return m_bytesPerSector << m_sectorsPerClusterShift;
   }
References FatPartition::m_bytesPerSector, and FatPartition::m_sectorsPerClusterShift.
Referenced by FatFile::addDirCluster().
bytesPerClusterShift()
uint8_t FatPartition::bytesPerClusterShift () const inline inherited
Returns
The shift count required to multiply by bytesPerCluster.
Definition at line 58 of file FatPartition.h.
{
     return m_sectorsPerClusterShift + m_bytesPerSectorShift;
   }
References FatPartition::m_bytesPerSectorShift, and FatPartition::m_sectorsPerClusterShift.
Referenced by FatFile::preAllocate(), and FatFile::seekSet().
bytesPerSector()
uint16_t FatPartition::bytesPerSector () const inline inherited
Returns
Number of bytes per sector.
Definition at line 66 of file FatPartition.h.
{
     return m_bytesPerSector;
   }
References FatPartition::m_bytesPerSector.
Referenced by FatFile::addDirCluster(), FatFile::read(), and FatFile::write().
bytesPerSectorShift()
uint8_t FatPartition::bytesPerSectorShift () const inline inherited
Returns
The shift count required to multiply by bytesPerCluster.
Definition at line 70 of file FatPartition.h.
{
     return m_bytesPerSectorShift;
   }
References FatPartition::m_bytesPerSectorShift.
Referenced by FatFile::read(), and FatFile::write().
cacheAddress()
uint8_t* FatPartition::cacheAddress () inline private inherited
Definition at line 262 of file FatPartition.h.
{
     return m_cache.cacheBuffer();
   }
References FsCache::cacheBuffer().
Referenced by FatFile::openCachedEntry(), and FatFile::readDirCache().
cacheClear()
uint8_t* FatPartition::cacheClear () inline inherited
Clear the cache and returns a pointer to the cache. Not for normal apps.
Returns
A pointer to the cache buffer or zero if an error occurs.
Definition at line 95 of file FatPartition.h.
{
     return m_cache.clear();
   }
Referenced by SdFat32::format().
cacheDirty()
void FatPartition::cacheDirty () inline private inherited
Definition at line 268 of file FatPartition.h.
                     {
     m_cache.dirty();
   }
References FsCache::dirty().
Referenced by FatFile::open().
cacheInvalidate()
void FatPartition::cacheInvalidate () inline private inherited
Definition at line 256 of file FatPartition.h.
{
     m_cache.invalidate();
   }
References FsCache::invalidate().
cachePrepare()
bool FatPartition::cachePrepare (uint32_t sector, uint8_t option) inline private inherited
Definition at line 231 of file FatPartition.h.
{
     return m_cache.prepare(sector, option);
   }
References FsCache::prepare().
cacheSafeRead() [1/2]
bool FatPartition::cacheSafeRead (uint32_t sector, uint8_t * dst) inline private inherited
Definition at line 196 of file FatPartition.h.
{
     return m_cache.cacheSafeRead(sector, dst);
   }
References dst.
Referenced by FatPartition::dmpDirSector(), FatPartition::dmpSector(), and FatFile::read().
cacheSafeRead() [2/2]
bool FatPartition::cacheSafeRead (uint32_t sector, uint8_t * dst, size_t count) inline private inherited
Definition at line 199 of file FatPartition.h.
{
     return m_cache.cacheSafeRead(sector, dst, count);
   }
References count, and dst.
cacheSafeWrite() [1/2]
bool FatPartition::cacheSafeWrite (uint32_t sector, const uint8_t * dst) inline private inherited
Definition at line 202 of file FatPartition.h.
{
     return m_cache.cacheSafeWrite(sector, dst);
   }
References dst.
Referenced by FatFile::write().
cacheSafeWrite() [2/2]
bool FatPartition::cacheSafeWrite (uint32_t sector, const uint8_t * dst, size_t count) inline private inherited
Definition at line 205 of file FatPartition.h.
{
     return m_cache.cacheSafeWrite(sector, dst, count);
   }
References count, and dst.
cacheSectorNumber()
uint32_t FatPartition::cacheSectorNumber () inline private inherited
Definition at line 265 of file FatPartition.h.
{
     return m_cache.sector();
   }
References FsCache::sector().
Referenced by FatFile::openCachedEntry(), FatFile::openSFN(), and FatFile::read().
cacheSync()
bool FatPartition::cacheSync () inline private inherited
Definition at line 249 of file FatPartition.h.
                    {
     return m_cache.sync() && syncDevice();
   }
References FsCache::sync().
Referenced by FatFile::mkdir(), FatFile::remove(), FatFile::rename(), FatFile::sync(), and FatFile::timestamp().
cacheSyncData()
bool FatPartition::cacheSyncData () inline private inherited
Definition at line 259 of file FatPartition.h.
{
     return m_cache.sync();
   }
References FsCache::sync().
Referenced by FatFile::write().
chdir() [1/2]
bool FatVolume::chdir () inline
Set volume working directory to root.
Returns
true for success or false for failure.
Definition at line 65 of file FatVolume.h.
                {
     m_vwd.close();
     return m_vwd.openRoot(this);
   }
References FatFile::close(), m_vwd, and FatFile::openRoot().
Referenced by begin().
chdir() [2/2]
bool FatVolume::chdir (const char * path)
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 30 of file FatVolume.cpp.
{
   FatFile dir;
   if (!dir.open(vwd(), path, O_RDONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!dir.isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_vwd = dir;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FatFile::isDir(), m_vwd, O_RDONLY, FatFile::open(), and vwd().
chvol()
void FatVolume::chvol () inline
Change global current working volume to this volume.
Definition at line 59 of file FatVolume.h.
 {m_cwv = this;}
References m_cwv.
clusterCount()
uint32_t FatPartition::clusterCount () const inline inherited
Returns
The total number of clusters in the volume.
Definition at line 99 of file FatPartition.h.
{
     return m_lastCluster - 1;
   }
Referenced by FatPartition::init().
clusterStartSector()
uint32_t FatPartition::clusterStartSector (uint32_t cluster) const inline private inherited
Definition at line 277 of file FatPartition.h.
{
     return m_dataStartSector + ((cluster - 2) << m_sectorsPerClusterShift);
   }
Referenced by FatFile::addDirCluster(), FatFile::contiguousRange(), FatPartition::dmpRootDir(), FatFile::firstSector(), FatFile::mkdir(), FatFile::read(), FatFile::rename(), and FatFile::write().
cwv()
static FatVolume* FatVolume::cwv () inline static private
Definition at line 334 of file FatVolume.h.
 {return m_cwv;}
References m_cwv.
Referenced by FatFile::createContiguous(), FatFile::open(), and FatFile::openExistingSFN().
dataCache()
FsCache* FatPartition::dataCache () inline private inherited
Definition at line 234 of file FatPartition.h.
 {return &m_cache;}
dataCachePrepare()
uint8_t* FatPartition::dataCachePrepare (uint32_t sector, uint8_t options) inline private inherited
Definition at line 253 of file FatPartition.h.
{
     return m_cache.prepare(sector, options);
   }
References FsCache::prepare().
Referenced by FatFile::addDirCluster(), FatFile::cacheDirEntry(), FatPartition::init(), FatFile::mkdir(), FatFile::read(), FatFile::rename(), and FatFile::write().
dataStartSector()
uint32_t FatPartition::dataStartSector () const inline inherited
Returns
The logical sector number for the start of file data.
Definition at line 107 of file FatPartition.h.
{
     return m_dataStartSector;
   }
dbgFat()
int8_t FatPartition::dbgFat (uint32_t n, uint32_t * v) inline inherited
Debug access to FAT table
Parameters
[in] n cluster number.
[out] v value of entry
Returns
-1 error, 0 EOC, else 1.
Definition at line 157 of file FatPartition.h.
{
     return fatGet(n, v);
   }
dirEntriesPerCluster()
uint16_t FatPartition::dirEntriesPerCluster () const inline inherited
Returns
Number of directory entries per sector.
Definition at line 74 of file FatPartition.h.
{
     return m_sectorsPerCluster*(m_bytesPerSector/FS_DIR_SIZE);
   }
References FS_DIR_SIZE, FatPartition::m_bytesPerSector, and FatPartition::m_sectorsPerCluster.
dmpDirSector()
bool FatPartition::dmpDirSector (print_t * pr, uint32_t sector) inherited
Definition at line 184 of file FatDbg.cpp.
{
   DirFat_t dir[16];
   if (!cacheSafeRead(sector, reinterpret_cast<uint8_t*>(dir))) {
     pr->println(F("dmpDir failed"));
     return false;
   }
   for (uint8_t i = 0; i < 16; i++) {
     if (!printFatDir(pr, dir + i)) {
       return false;
     }
   }
   return true;
 }
References FatPartition::cacheSafeRead(), F, printFatDir(), and PrintBasic::println().
Referenced by FatPartition::dmpRootDir().
dmpFat()
void FatPartition::dmpFat (print_t * pr, uint32_t start, uint32_t count) inherited
Definition at line 238 of file FatDbg.cpp.
{
   uint16_t nf = fatType() == 16 ? 256 : fatType() == 32 ? 128 : 0;
   if (nf == 0) {
     pr->println(F("Invalid fatType"));
     return;
   }
   pr->println(F("FAT:"));
   uint32_t sector = m_fatStartSector + start;
   uint32_t cluster = nf*start;
   for (uint32_t i = 0; i < count; i++) {
     uint8_t* pc = fatCachePrepare(sector + i, FsCache::CACHE_FOR_READ);
     if (!pc) {
       pr->println(F("cache read failed"));
       return;
     }
     for (size_t k = 0; k < nf; k++) {
       if (0 == cluster%8) {
         if (k) {
           pr->println();
         }
         printHex(pr, cluster);
       }
       cluster++;
       pr->write(' ');
       uint32_t v = fatType() == 32 ? getLe32(pc + 4*k) : getLe16(pc + 2*k);
       printHex(pr, v);
     }
     pr->println();
   }
 }
References FsCache::CACHE_FOR_READ, count, F, FatPartition::fatCachePrepare(), FatPartition::fatType(), getLe16(), getLe32(), FatPartition::m_fatStartSector, nf(), printHex(), PrintBasic::println(), and PrintBasic::write().
dmpRootDir()
bool FatPartition::dmpRootDir (print_t * pr, uint32_t n = 0) inherited
Definition at line 198 of file FatDbg.cpp.
{
   uint32_t sector;
   if (fatType() == 16) {
     sector = rootDirStart();
   } else if (fatType() == 32) {
     sector = clusterStartSector(rootDirStart());
   } else {
     pr->println(F("dmpRootDir failed"));
     return false;
   }
   return dmpDirSector(pr, sector + n);
 }
References FatPartition::clusterStartSector(), FatPartition::dmpDirSector(), F, FatPartition::fatType(), PrintBasic::println(), and FatPartition::rootDirStart().
dmpSector()
void FatPartition::dmpSector (print_t * pr, uint32_t sector, uint8_t bits = 8) inherited
Definition at line 211 of file FatDbg.cpp.
{
   uint8_t data[FatPartition::m_bytesPerSector];
   if (!cacheSafeRead(sector, data)) {
     pr->println(F("dmpSector failed"));
     return;
   }
   for (uint16_t i = 0; i < m_bytesPerSector;) {
     if (i%32 == 0) {
       if (i) {
         pr->println();
       }
       printHex(pr, i);
     }
     pr->write(' ');
     if (bits == 32) {
       printHex(pr, *reinterpret_cast<uint32_t*>(data + i));
       i += 4;
     } else if (bits == 16) {
       printHex(pr, *reinterpret_cast<uint16_t*>(data + i));
       i += 2;
     } else {
       printHex(pr, data[i++]);
     }
   }
   pr->println();
 }
References FatPartition::cacheSafeRead(), data, F, FatPartition::m_bytesPerSector, printHex(), PrintBasic::println(), and PrintBasic::write().
exists()
bool FatVolume::exists (const char * path) inline
Test for the existence of a file.
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 84 of file FatVolume.h.
{
     FatFile tmp;
     return tmp.open(this, path, O_RDONLY);
   }
References O_RDONLY, and FatFile::open().
fatCachePrepare()
uint8_t* FatPartition::fatCachePrepare (uint32_t sector, uint8_t options) inline private inherited
Definition at line 245 of file FatPartition.h.
{
     options |= FsCache::CACHE_STATUS_MIRROR_FAT;
     return dataCachePrepare(sector, options);
   }
References FsCache::CACHE_STATUS_MIRROR_FAT.
Referenced by FatPartition::dmpFat(), FatPartition::fatGet(), FatPartition::fatPut(), and FatPartition::freeClusterCount().
fatCount()
uint8_t FatPartition::fatCount () const inline inherited
Returns
The number of File Allocation Tables.
Definition at line 111 of file FatPartition.h.
{
     return 2;
   }
fatGet()
int8_t FatPartition::fatGet (uint32_t cluster, uint32_t * value) private inherited
Definition at line 157 of file FatPartition.cpp.
{
   uint32_t sector;
   uint32_t next;
   uint8_t* pc;
   // error if reserved cluster of beyond FAT
   if (cluster < 2 || cluster > m_lastCluster) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (fatType() == 32) {
     sector = m_fatStartSector + (cluster >> (m_bytesPerSectorShift - 2));
     pc = fatCachePrepare(sector, FsCache::CACHE_FOR_READ);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     uint16_t offset = (cluster << 2) & m_sectorMask;
     next = getLe32(pc + offset);
   } else if (fatType() == 16) {
     cluster &= 0XFFFF;
     sector = m_fatStartSector + (cluster >> (m_bytesPerSectorShift - 1) );
     pc = fatCachePrepare(sector, FsCache::CACHE_FOR_READ);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     uint16_t offset = (cluster << 1) & m_sectorMask;
     next = getLe16(pc + offset);
   } else if (FAT12_SUPPORT && fatType() == 12) {
     uint16_t index = cluster;
     index += index >> 1;
     sector = m_fatStartSector + (index >> m_bytesPerSectorShift);
     pc = fatCachePrepare(sector, FsCache::CACHE_FOR_READ);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     index &= m_sectorMask;
     uint16_t tmp = pc[index];
     index++;
     if (index == m_bytesPerSector) {
       pc = fatCachePrepare(sector + 1, FsCache::CACHE_FOR_READ);
       if (!pc) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       index = 0;
     }
     tmp |= pc[index] << 8;
     next = cluster & 1 ? tmp >> 4 : tmp & 0XFFF;
   } else {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (isEOC(next)) {
     return 0;
   }
   *value = next;
   return 1;
  fail:
   return -1;
 }
References FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, FAT12_SUPPORT, FatPartition::fatCachePrepare(), FatPartition::fatType(), getLe16(), getLe32(), FatPartition::isEOC(), FatPartition::m_bytesPerSector, FatPartition::m_bytesPerSectorShift, FatPartition::m_fatStartSector, FatPartition::m_lastCluster, and FatPartition::m_sectorMask.
Referenced by FatPartition::allocateCluster(), FatPartition::allocContiguous(), FatFile::contiguousRange(), FatFile::dirSize(), FatPartition::freeChain(), FatPartition::freeClusterCount(), FatFile::read(), FatFile::seekSet(), FatFile::truncate(), and FatFile::write().
fatPut()
bool FatPartition::fatPut (uint32_t cluster, uint32_t value) private inherited
Definition at line 224 of file FatPartition.cpp.
{
   uint32_t sector;
   uint8_t* pc;
   // error if reserved cluster of beyond FAT
   if (cluster < 2 || cluster > m_lastCluster) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (fatType() == 32) {
     sector = m_fatStartSector + (cluster >> (m_bytesPerSectorShift - 2));
     pc = fatCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     uint16_t offset = (cluster << 2) & m_sectorMask;
     setLe32(pc + offset, value);
     return true;
   }
   if (fatType() == 16) {
     cluster &= 0XFFFF;
     sector = m_fatStartSector + (cluster >> (m_bytesPerSectorShift - 1) );
     pc = fatCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     uint16_t offset = (cluster << 1) & m_sectorMask;
     setLe16(pc + offset, value);
     return true;
   }
   if (FAT12_SUPPORT && fatType() == 12) {
     uint16_t index = cluster;
     index += index >> 1;
     sector = m_fatStartSector + (index >> m_bytesPerSectorShift);
     pc = fatCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
     if (!pc) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     index &= m_sectorMask;
     uint8_t tmp = value;
     if (cluster & 1) {
       tmp = (pc[index] & 0XF) | tmp << 4;
     }
     pc[index] = tmp;
     index++;
     if (index == m_bytesPerSector) {
       sector++;
       index = 0;
       pc = fatCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
       if (!pc) {
         DBG_FAIL_MACRO;
         goto fail;
       }
     }
     tmp = value >> 4;
     if (!(cluster & 1)) {
       tmp = ((pc[index] & 0XF0)) | tmp >> 4;
     }
     pc[index] = tmp;
     return true;
   } else {
     DBG_FAIL_MACRO;
     goto fail;
   }
  fail:
   return false;
 }
References FsCache::CACHE_FOR_WRITE, DBG_FAIL_MACRO, FAT12_SUPPORT, FatPartition::fatCachePrepare(), FatPartition::fatType(), FatPartition::m_bytesPerSector, FatPartition::m_bytesPerSectorShift, FatPartition::m_fatStartSector, FatPartition::m_lastCluster, FatPartition::m_sectorMask, setLe16(), and setLe32().
Referenced by FatPartition::allocateCluster(), FatPartition::allocContiguous(), and FatPartition::freeChain().
fatPutEOC()
bool FatPartition::fatPutEOC (uint32_t cluster) inline private inherited
Definition at line 282 of file FatPartition.h.
{
     return fatPut(cluster, 0x0FFFFFFF);
   }
Referenced by FatPartition::allocateCluster(), FatPartition::allocContiguous(), and FatFile::truncate().
fatStartSector()
uint32_t FatPartition::fatStartSector () const inline inherited
Returns
The logical sector number for the start of the first FAT.
Definition at line 115 of file FatPartition.h.
{
     return m_fatStartSector;
   }
fatType()
uint8_t FatPartition::fatType () const inline inherited
Returns
The FAT type of the volume. Values are 12, 16 or 32.
Definition at line 119 of file FatPartition.h.
{
     return m_fatType;
   }
Referenced by FatPartition::dmpFat(), FatPartition::dmpRootDir(), FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::freeClusterCount(), and FatFile::openRoot().
freeChain()
bool FatPartition::freeChain (uint32_t cluster) private inherited
Definition at line 301 of file FatPartition.cpp.
{
   uint32_t next;
   int8_t fg;
   do {
     fg = fatGet(cluster, &next);
     if (fg < 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // free cluster
     if (!fatPut(cluster, 0)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     // Add one to count of free clusters.
     updateFreeClusterCount(1);
     if (cluster < m_allocSearchStart) {
       m_allocSearchStart = cluster - 1;
     }
     cluster = next;
   } while (fg);
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::m_allocSearchStart, and FatPartition::updateFreeClusterCount().
Referenced by FatFile::openCachedEntry(), FatFile::remove(), FatFile::rename(), and FatFile::truncate().
freeClusterCount()
int32_t FatPartition::freeClusterCount () inherited
Volume free space in clusters.
Returns
Count of free clusters for success or -1 if an error occurs.
Definition at line 329 of file FatPartition.cpp.
{
 #if MAINTAIN_FREE_CLUSTER_COUNT
   if (m_freeClusterCount >= 0) {
     return m_freeClusterCount;
   }
 #endif  // MAINTAIN_FREE_CLUSTER_COUNT
   uint32_t free = 0;
   uint32_t sector;
   uint32_t todo = m_lastCluster + 1;
   uint16_t n;
   if (FAT12_SUPPORT && fatType() == 12) {
     for (unsigned i = 2; i < todo; i++) {
       uint32_t c;
       int8_t fg = fatGet(i, &c);
       if (fg < 0) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       if (fg && c == 0) {
         free++;
       }
     }
   } else if (fatType() == 16 || fatType() == 32) {
     sector = m_fatStartSector;
     while (todo) {
       uint8_t* pc = fatCachePrepare(sector++, FsCache::CACHE_FOR_READ);
       if (!pc) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       n =  fatType() == 16 ? m_bytesPerSector/2 : m_bytesPerSector/4;
       if (todo < n) {
         n = todo;
       }
       if (fatType() == 16) {
         uint16_t* p16 = reinterpret_cast<uint16_t*>(pc);
         for (uint16_t i = 0; i < n; i++) {
           if (p16[i] == 0) {
             free++;
           }
         }
       } else {
         uint32_t* p32 = reinterpret_cast<uint32_t*>(pc);
         for (uint16_t i = 0; i < n; i++) {
           if (p32[i] == 0) {
             free++;
           }
         }
       }
       todo -= n;
     }
   } else {
     // invalid FAT type
     DBG_FAIL_MACRO;
     goto fail;
   }
   setFreeClusterCount(free);
   return free;
  fail:
   return -1;
 }
References FsCache::CACHE_FOR_READ, DBG_FAIL_MACRO, FAT12_SUPPORT, FatPartition::fatCachePrepare(), FatPartition::fatGet(), FatPartition::fatType(), FatPartition::m_bytesPerSector, FatPartition::m_fatStartSector, FatPartition::m_lastCluster, and FatPartition::setFreeClusterCount().
init()
bool FatPartition::init (BlockDevice * dev, uint8_t part = 1) inherited
Initialize a FAT partition.
Parameters
[in] dev BlockDevice for this partition.
[in] part The partition to be used. Legal values for part are 1-4 to use the corresponding partition on a device formatted with a MBR, Master Boot Record, or zero if the device is formatted as a super floppy with the FAT boot sector in sector zero.
Returns
true for success or false for failure.
Definition at line 393 of file FatPartition.cpp.
{
   uint32_t clusterCount;
   uint32_t totalSectors;
   uint32_t volumeStartSector = 0;
   m_blockDev = dev;
   pbs_t* pbs;
   BpbFat32_t* bpb;
   MbrSector_t* mbr;
   uint8_t tmp;
   m_fatType = 0;
   m_allocSearchStart = 1;
   m_cache.init(dev);
 #if USE_SEPARATE_FAT_CACHE
   m_fatCache.init(dev);
 #endif  // USE_SEPARATE_FAT_CACHE
   // if part == 0 assume super floppy with FAT boot sector in sector zero
   // if part > 0 assume mbr volume with partition table
   if (part) {
     if (part > 4) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     mbr = reinterpret_cast<MbrSector_t*>
           (dataCachePrepare(0, FsCache::CACHE_FOR_READ));
     MbrPart_t* mp = mbr->part + part - 1;
     if (!mbr || mp->type == 0 || (mp->boot != 0 && mp->boot != 0X80)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     volumeStartSector = getLe32(mp->relativeSectors);
   }
   pbs = reinterpret_cast<pbs_t*>
         (dataCachePrepare(volumeStartSector, FsCache::CACHE_FOR_READ));
   bpb = reinterpret_cast<BpbFat32_t*>(pbs->bpb);
   if (!pbs || bpb->fatCount != 2 ||
     getLe16(bpb->bytesPerSector) != m_bytesPerSector) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_sectorsPerCluster = bpb->sectorsPerCluster;
   m_clusterSectorMask = m_sectorsPerCluster - 1;
   // determine shift that is same as multiply by m_sectorsPerCluster
   m_sectorsPerClusterShift = 0;
   for (tmp = 1; m_sectorsPerCluster != tmp; tmp <<= 1) {
     if (tmp == 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     m_sectorsPerClusterShift++;
   }
   m_sectorsPerFat = getLe16(bpb->sectorsPerFat16);
   if (m_sectorsPerFat == 0) {
     m_sectorsPerFat = getLe32(bpb->sectorsPerFat32);
   }
   m_fatStartSector = volumeStartSector + getLe16(bpb->reservedSectorCount);
   // count for FAT16 zero for FAT32
   m_rootDirEntryCount = getLe16(bpb->rootDirEntryCount);
   // directory start for FAT16 dataStart for FAT32
   m_rootDirStart = m_fatStartSector + 2 * m_sectorsPerFat;
   // data start for FAT16 and FAT32
   m_dataStartSector = m_rootDirStart +
     ((FS_DIR_SIZE*m_rootDirEntryCount + m_bytesPerSector - 1)/m_bytesPerSector);
   // total sectors for FAT16 or FAT32
   totalSectors = getLe16(bpb->totalSectors16);
   if (totalSectors == 0) {
     totalSectors = getLe32(bpb->totalSectors32);
   }
   // total data sectors
   clusterCount = totalSectors - (m_dataStartSector - volumeStartSector);
   // divide by cluster size to get cluster count
   clusterCount >>= m_sectorsPerClusterShift;
   m_lastCluster = clusterCount + 1;
   // Indicate unknown number of free clusters.
   setFreeClusterCount(-1);
   // FAT type is determined by cluster count
   if (clusterCount < 4085) {
     m_fatType = 12;
     if (!FAT12_SUPPORT) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   } else if (clusterCount < 65525) {
     m_fatType = 16;
   } else {
     m_rootDirStart = getLe32(bpb->fat32RootCluster);
     m_fatType = 32;
   }
   m_cache.setMirrorOffset(m_sectorsPerFat);
 #if USE_SEPARATE_FAT_CACHE
   m_fatCache.setMirrorOffset(m_sectorsPerFat);
 #endif  // USE_SEPARATE_FAT_CACHE
   return true;
  fail:
   return false;
 }
References mbrPartition::boot, partitionBootSector::bpb, biosParameterBlockFat32::bytesPerSector, FsCache::CACHE_FOR_READ, FatPartition::clusterCount(), FatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FAT12_SUPPORT, biosParameterBlockFat32::fat32RootCluster, biosParameterBlockFat32::fatCount, FS_DIR_SIZE, getLe16(), getLe32(), FsCache::init(), FatPartition::m_allocSearchStart, FatPartition::m_blockDev, FatPartition::m_bytesPerSector, FatPartition::m_cache, FatPartition::m_clusterSectorMask, FatPartition::m_dataStartSector, FatPartition::m_fatStartSector, FatPartition::m_fatType, FatPartition::m_lastCluster, FatPartition::m_rootDirEntryCount, FatPartition::m_rootDirStart, FatPartition::m_sectorsPerCluster, FatPartition::m_sectorsPerClusterShift, FatPartition::m_sectorsPerFat, masterBootRecordSector::part, mbrPartition::relativeSectors, biosParameterBlockFat32::reservedSectorCount, biosParameterBlockFat32::rootDirEntryCount, biosParameterBlockFat32::sectorsPerCluster, biosParameterBlockFat32::sectorsPerFat16, biosParameterBlockFat32::sectorsPerFat32, FatPartition::setFreeClusterCount(), FsCache::setMirrorOffset(), biosParameterBlockFat32::totalSectors16, biosParameterBlockFat32::totalSectors32, and mbrPartition::type.
Referenced by begin().
isBusy()
bool FatPartition::isBusy () inline inherited
Check for BlockDevice busy.
Returns
true if busy else false.
Definition at line 165 of file FatPartition.h.
 {return m_blockDev->isBusy();}
Referenced by FatFile::isBusy().
isEOC()
bool FatPartition::isEOC (uint32_t cluster) const inline private inherited
Definition at line 286 of file FatPartition.h.
{
     return cluster > m_lastCluster;
   }
Referenced by FatPartition::fatGet().
ls() [1/2]
bool FatVolume::ls (print_t * pr, const char * path, uint8_t flags) inline
List the contents of a directory.
Parameters
[in] pr Print stream for list.
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 123 of file FatVolume.h.
{
     FatFile dir;
     return dir.open(this, path, O_RDONLY) && dir.ls(pr, flags);
   }
References FatFile::ls(), O_RDONLY, and FatFile::open().
ls() [2/2]
bool FatVolume::ls (print_t * pr, uint8_t flags = 0) inline
List the directory contents of the volume root directory.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 103 of file FatVolume.h.
{
     return m_vwd.ls(pr, flags);
   }
References FatFile::ls(), and m_vwd.
mkdir()
bool FatVolume::mkdir (const char * path, bool pFlag = true) inline
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 136 of file FatVolume.h.
{
     FatFile sub;
     return sub.mkdir(vwd(), path, pFlag);
   }
References FatFile::mkdir(), and vwd().
open()
File32 FatVolume::open (const char * path, oflag_t oflag = O_RDONLY) inline
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a File32 object.
Definition at line 147 of file FatVolume.h.
{
     File32 tmpFile;
     tmpFile.open(this, path, oflag);
     return tmpFile;
   }
References FatFile::open().
remove()
bool FatVolume::remove (const char * path) inline
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid name for the file.
Returns
true for success or false for failure.
Definition at line 159 of file FatVolume.h.
{
     FatFile tmp;
     return tmp.open(this, path, O_WRONLY) && tmp.remove();
   }
References O_WRONLY, FatFile::open(), and FatFile::remove().
rename()
bool FatVolume::rename (const char * oldPath, const char * newPath) inline
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 178 of file FatVolume.h.
{
     FatFile file;
     return file.open(vwd(), oldPath, O_RDONLY) && file.rename(vwd(), newPath);
   }
References O_RDONLY, FatFile::open(), FatFile::rename(), and vwd().
rmdir()
bool FatVolume::rmdir (const char * path) inline
Remove a subdirectory from the volume's working directory.
Parameters
[in] path A path with a valid name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 191 of file FatVolume.h.
{
     FatFile sub;
     return sub.open(this, path, O_RDONLY) && sub.rmdir();
   }
References O_RDONLY, FatFile::open(), and FatFile::rmdir().
rootDirEntryCount()
uint16_t FatPartition::rootDirEntryCount () const inline inherited
Returns
The number of entries in the root directory for FAT16 volumes.
Definition at line 139 of file FatPartition.h.
{
     return m_rootDirEntryCount;
   }
Referenced by FatFile::dirSize().
rootDirStart()
uint32_t FatPartition::rootDirStart () const inline inherited
Returns
The logical sector number for the start of the root directory on FAT16 volumes or the first cluster number on FAT32 volumes.
Definition at line 144 of file FatPartition.h.
{
     return m_rootDirStart;
   }
Referenced by FatFile::dirSize(), FatPartition::dmpRootDir(), FatFile::read(), and FatFile::seekSet().
sectorMask()
uint16_t FatPartition::sectorMask () const inline inherited
Returns
Mask for sector offset.
Definition at line 78 of file FatPartition.h.
{
     return m_sectorMask;
   }
References FatPartition::m_sectorMask.
Referenced by FatFile::read(), and FatFile::write().
sectorOfCluster()
uint8_t FatPartition::sectorOfCluster (uint32_t position) const inline private inherited
Definition at line 274 of file FatPartition.h.
{
     return (position >> 9) & m_clusterSectorMask;
   }
Referenced by FatFile::read(), and FatFile::write().
sectorsPerCluster()
uint8_t FatPartition::sectorsPerCluster () const inline inherited
Returns
The volume's cluster size in sectors.
Definition at line 82 of file FatPartition.h.
{
     return m_sectorsPerCluster;
   }
References FatPartition::m_sectorsPerCluster.
Referenced by FatFile::addDirCluster(), FatFile::contiguousRange(), FatFile::dirSize(), FatFile::read(), and FatFile::write().
sectorsPerClusterShift()
uint8_t FatPartition::sectorsPerClusterShift () const inline inherited
Returns
The shift count required to multiply by sectorsPerCluster.
Definition at line 103 of file FatPartition.h.
{
     return m_sectorsPerClusterShift;
   }
sectorsPerFat()
uint32_t FatPartition::sectorsPerFat () const inline inherited
Returns
The number of sectors in one FAT.
Definition at line 89 of file FatPartition.h.
{
     return m_sectorsPerFat;
   }
setFreeClusterCount()
void FatPartition::setFreeClusterCount (int32_t value) inline private inherited
Definition at line 222 of file FatPartition.h.
{
     (void)value;
   }
Referenced by FatPartition::freeClusterCount(), and FatPartition::init().
syncDevice()
bool FatPartition::syncDevice () inline private inherited
Definition at line 208 of file FatPartition.h.
                     {
     return m_blockDev->syncDevice();
   }
References SharedSpiCard::syncDevice().
truncate()
bool FatVolume::truncate (const char * path, uint32_t length) inline
Truncate a file to a specified length. The current file position will be at the new EOF.
Parameters
[in] path A path with a valid name for the file.
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 204 of file FatVolume.h.
{
     FatFile file;
     return file.open(this, path, O_WRONLY) && file.truncate(length);
   }
References O_WRONLY, FatFile::open(), and FatFile::truncate().
updateFreeClusterCount()
void FatPartition::updateFreeClusterCount (int32_t change) inline private inherited
Definition at line 225 of file FatPartition.h.
{
     (void)change;
   }
Referenced by FatPartition::allocateCluster(), FatPartition::allocContiguous(), and FatPartition::freeChain().
volumeSectorCount()
uint32_t FatPartition::volumeSectorCount () const inline inherited
Returns
The number of sectors in the volume
Definition at line 148 of file FatPartition.h.
{
     return sectorsPerCluster()*clusterCount();
   }
vwd()
FatFile* FatVolume::vwd () inline private
Definition at line 335 of file FatVolume.h.
 {return &m_vwd;}
References m_vwd.
Referenced by chdir(), mkdir(), FatFile::open(), FatFile::rename(), and rename().
Member Data Documentation
FatFile
friend FatVolume::FatFile private
Definition at line 333 of file FatVolume.h.
m_allocSearchStart
uint32_t FatPartition::m_allocSearchStart private inherited
Definition at line 188 of file FatPartition.h.
Referenced by FatPartition::allocateCluster(), FatPartition::allocContiguous(), FatPartition::freeChain(), and FatPartition::init().
m_blockDev
BlockDevice* FatPartition::m_blockDev private inherited
Definition at line 182 of file FatPartition.h.
Referenced by FatPartition::init().
m_bytesPerSector
const uint16_t FatPartition::m_bytesPerSector = 1 << m_bytesPerSectorShift static private inherited
Definition at line 179 of file FatPartition.h.
Referenced by FatPartition::bytesPerCluster(), FatPartition::bytesPerSector(), FatPartition::dirEntriesPerCluster(), FatPartition::dmpSector(), FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::freeClusterCount(), and FatPartition::init().
m_bytesPerSectorShift
const uint8_t FatPartition::m_bytesPerSectorShift = 9 static private inherited
Definition at line 178 of file FatPartition.h.
Referenced by FatPartition::bytesPerClusterShift(), FatPartition::bytesPerSectorShift(), FatPartition::fatGet(), and FatPartition::fatPut().
m_cache
FsCache FatPartition::m_cache private inherited
Definition at line 230 of file FatPartition.h.
Referenced by FatPartition::init().
m_clusterSectorMask
uint8_t FatPartition::m_clusterSectorMask private inherited
Definition at line 184 of file FatPartition.h.
Referenced by FatPartition::init().
m_cwv
FatVolume * FatVolume::m_cwv = nullptr static private
Definition at line 336 of file FatVolume.h.
Referenced by begin(), chvol(), and cwv().
m_dataStartSector
uint32_t FatPartition::m_dataStartSector private inherited
Definition at line 190 of file FatPartition.h.
Referenced by FatPartition::init().
m_fatStartSector
uint32_t FatPartition::m_fatStartSector private inherited
Definition at line 191 of file FatPartition.h.
Referenced by FatPartition::dmpFat(), FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::freeClusterCount(), and FatPartition::init().
m_fatType
uint8_t FatPartition::m_fatType = 0 private inherited
Definition at line 186 of file FatPartition.h.
Referenced by FatPartition::init().
m_lastCluster
uint32_t FatPartition::m_lastCluster private inherited
Definition at line 192 of file FatPartition.h.
Referenced by FatPartition::allocateCluster(), FatPartition::allocContiguous(), FatPartition::fatGet(), FatPartition::fatPut(), FatPartition::freeClusterCount(), and FatPartition::init().
m_rootDirEntryCount
uint16_t FatPartition::m_rootDirEntryCount private inherited
Definition at line 187 of file FatPartition.h.
Referenced by FatPartition::init(), and FatFile::read().
m_rootDirStart
uint32_t FatPartition::m_rootDirStart private inherited
Definition at line 193 of file FatPartition.h.
Referenced by FatPartition::init().
m_sectorMask
const uint16_t FatPartition::m_sectorMask = m_bytesPerSector - 1 static private inherited
Definition at line 180 of file FatPartition.h.
Referenced by FatPartition::fatGet(), FatPartition::fatPut(), and FatPartition::sectorMask().
m_sectorsPerCluster
uint8_t FatPartition::m_sectorsPerCluster private inherited
Definition at line 183 of file FatPartition.h.
Referenced by FatPartition::dirEntriesPerCluster(), FatPartition::init(), and FatPartition::sectorsPerCluster().
m_sectorsPerClusterShift
uint8_t FatPartition::m_sectorsPerClusterShift private inherited
Definition at line 185 of file FatPartition.h.
Referenced by FatPartition::bytesPerCluster(), FatPartition::bytesPerClusterShift(), and FatPartition::init().
m_sectorsPerFat
uint32_t FatPartition::m_sectorsPerFat private inherited
Definition at line 189 of file FatPartition.h.
Referenced by FatPartition::init().
m_vwd
FatFile FatVolume::m_vwd private
Definition at line 337 of file FatVolume.h.
Referenced by chdir(), ls(), and vwd().
The documentation for this class was generated from the following files:
FatVolume.h
FatVolume.cpp