ERIS CORE: ErisCore.cpp File Reference
ErisCore.cpp File Reference
#include <Arduino.h>
#include <SdCard/SdioCard.h>
#include <SdFatConfig.h>
#include <SdFat.h>
#include "HSI.h"
#include "SPI.h"
#include "appTemplate.h"
#include "appAudioToPolyphonic.h"
#include "appReprogram.h"
#include "svcSerialCommandInterface.h"
#include "PCM1863.h"
Macros
#define BUILTIN_SDCARD 254
Functions
void loop (void)
void setup ()
Variables
AudioDirector _ad
AppAudioToPolyphonic appPoly
AppReprogram appReprogram
SvcSerialCommandInterface sci
Macro Definition Documentation
BUILTIN_SDCARD
#define BUILTIN_SDCARD 254
Definition at line 2 of file ErisCore.cpp.
Function Documentation
loop()
void loop (void)
Definition at line 67 of file ErisCore.cpp.
                 {
   //The appManager will...
   //call the handlers of the active app for any triggered events,
   //calls update for the active app
   //calls updateRT for all apps
   AppManager::getInstance()->update();
 }
setup()
void setup ()
Definition at line 24 of file ErisCore.cpp.
              {
   //always run this first to ensure programming mode can be entered through the hmi
   //as access to the physical reset button may be restricted in an integrated application.
   //
   //power on/reset bootrequest check
   pinMode(TAP_INPUT, INPUT);
   pinMode(SW_D, INPUT);
   delay(500);
   Serial.begin(3000000);//baud rate is ignored by the library as it's fixed at max USB speed
   if (digitalRead(TAP_INPUT) == LOW && digitalRead(SW_D) == LOW){
             Serial.println(F("setup: Power on reset request to enter programming mode in 5 seconds."));
             delay(1000);
             __asm__ volatile ("bkpt #251"); //enter the bootloader
             while(1);
   }
   //while(!Serial); //DEBUG - wait for serial connection
   //delay(500);
   //reset the i2c bus and config the external ADC
   Serial.println(F("M Setup: Initalizing"));
   Serial.println(F("M Setup: Configuring Audio Hardware"));
   I2CReset();
   ExtADCConfig();
   ExtADCPrintStatus();
   //I2CBusScan();
   Serial.println(F("M Setup: Loading Applications"));
   //app = new MyAppExample();    //note: The AppBaseClass constructor self registers with the app manager
   //appReprogram = new AppReprogram();
   //appSCI = new AppSerialCommandInterface();
   //AppManager::getInstance()->getFocus(app->getId()); //focus is requested by obj id
   //give the audio director a pointer to the sci class
   _ad.setSCI(&sci);
   Serial.println(F("M Setup: Setting App Focus"));
   appPoly.getFocus();
   Serial.println(F("M Setup: Init Complete"));
   //delay(5000);
   if (CrashReport){
       Serial.print(CrashReport);
   }
 }
References _ad, appPoly, ExtADCConfig(), ExtADCPrintStatus(), F, AppBaseClass::getFocus(), I2CReset(), INPUT, LOW, sci, AudioDirector::setSCI(), SW_D, and TAP_INPUT.
Referenced by userSetup().
Variable Documentation
_ad
AudioDirector _ad
Definition at line 15 of file ErisCore.cpp.
Referenced by setup().
appPoly
AppAudioToPolyphonic appPoly
Definition at line 16 of file ErisCore.cpp.
Referenced by setup().
appReprogram
AppReprogram appReprogram
Definition at line 18 of file ErisCore.cpp.
sci
SvcSerialCommandInterface sci
Definition at line 17 of file ErisCore.cpp.
Referenced by SvcDataDictionary::printDictionary(), and setup().