ERIS CORE: SharedSpiCard Class Reference
SharedSpiCard Class Reference
Raw access to SD and SDHC flash memory cards via shared SPI port.
#include <SdSpiCard.h>
Public Member Functions
SharedSpiCard ()
uint32_t __attribute__ ((error("use sectorCount()"))) cardSize()
bool begin (SdSpiConfig spiConfig)
bool erase (uint32_t firstSector, uint32_t lastSector)
bool eraseSingleSectorEnable ()
void error (uint8_t code)
uint8_t errorCode () const
uint32_t errorData () const
bool isBusy ()
bool readCID (cid_t *cid)
bool readCSD (csd_t *csd)
bool readData (uint8_t *dst)
bool readOCR (uint32_t *ocr)
bool readSector (uint32_t sector, uint8_t *dst)
bool readSectors (uint32_t sector, uint8_t *dst, size_t ns)
bool readStart (uint32_t sector)
bool readStatus (uint8_t *status)
bool readStop ()
uint8_t sdState ()
uint32_t sectorCount ()
bool stopTransfer ()
bool syncDevice ()
uint8_t type () const
bool writeData (const uint8_t *src)
bool writeSector (uint32_t sector, const uint8_t *src)
bool writeSectors (uint32_t sector, const uint8_t *src, size_t ns)
bool writeStart (uint32_t sector)
bool writeStop ()
Static Public Attributes
static const uint8_t IDLE_STATE = 0
static const uint8_t READ_STATE = 1
static const uint8_t WRITE_STATE = 2
Private Member Functions
uint8_t cardAcmd (uint8_t cmd, uint32_t arg)
uint8_t cardCommand (uint8_t cmd, uint32_t arg)
bool readData (uint8_t *dst, size_t count)
bool readRegister (uint8_t cmd, void *buf)
void spiActivate ()
void spiBegin (SdSpiConfig spiConfig)
void spiDeactivate ()
uint8_t spiReceive ()
uint8_t spiReceive (uint8_t *buf, size_t n)
void spiSelect ()
void spiSend (const uint8_t *buf, size_t n)
void spiSend (uint8_t data)
void spiSetSckSpeed (uint32_t maxSck)
void spiStart ()
void spiStop ()
void spiUnselect ()
void type (uint8_t value)
bool waitReady (uint16_t ms)
bool writeData (uint8_t token, const uint8_t *src)
Private Attributes
SdCsPin_t m_csPin
uint8_t m_errorCode = SD_CARD_ERROR_INIT_NOT_CALLED
bool m_spiActive
SdSpiDriver m_spiDriver
uint8_t m_state
uint8_t m_status
uint8_t m_type = 0
Detailed Description
Raw access to SD and SDHC flash memory cards via shared SPI port.
Definition at line 46 of file SdSpiCard.h.
Constructor & Destructor Documentation
SharedSpiCard()
SharedSpiCard::SharedSpiCard () inline
Construct an instance of SharedSpiCard.
Definition at line 56 of file SdSpiCard.h.
 {}
Member Function Documentation
__attribute__()
uint32_t SharedSpiCard::__attribute__ ((error("use sectorCount()")))
begin()
bool SharedSpiCard::begin (SdSpiConfig spiConfig)
Initialize the SD card.
Parameters
[in] spiConfig SPI card configuration.
Returns
true for success or false for failure.
Definition at line 132 of file SdSpiCard.cpp.
{
   Timeout timeout;
   m_spiActive = false;
   m_errorCode = SD_CARD_ERROR_NONE;
   m_type = 0;
   m_csPin = spiConfig.csPin;
 #if SPI_DRIVER_SELECT >= 2
   m_spiDriverPtr = spiConfig.spiPort;
   if (!m_spiDriverPtr) {
     error(SD_CARD_ERROR_INVALID_CARD_CONFIG);
     goto fail;
   }
 #endif  // SPI_DRIVER_SELECT
   sdCsInit(m_csPin);
   spiUnselect();
   spiSetSckSpeed(1000UL*SD_MAX_INIT_RATE_KHZ);
   spiBegin(spiConfig);
   uint32_t arg;
   m_state = IDLE_STATE;
   spiStart();
   // must supply min of 74 clock cycles with CS high.
   spiUnselect();
   for (uint8_t i = 0; i < 10; i++) {
     spiSend(0XFF);
   }
   spiSelect();
   // command to go idle in SPI mode
   for (uint8_t i = 1;; i++) {
     if (cardCommand(CMD0, 0) == R1_IDLE_STATE) {
       break;
     }
     if (i == SD_CMD0_RETRY) {
       error(SD_CARD_ERROR_CMD0);
       goto fail;
     }
   }
 #if USE_SD_CRC
   if (cardCommand(CMD59, 1) != R1_IDLE_STATE) {
     error(SD_CARD_ERROR_CMD59);
     goto fail;
   }
 #endif  // USE_SD_CRC
   // check SD version
   if (!(cardCommand(CMD8, 0x1AA) & R1_ILLEGAL_COMMAND)) {
     type(SD_CARD_TYPE_SD2);
     for (uint8_t i = 0; i < 4; i++) {
       m_status = spiReceive();
     }
     if (m_status != 0XAA) {
       error(SD_CARD_ERROR_CMD8);
       goto fail;
     }
   } else {
     type(SD_CARD_TYPE_SD1);
   }
   // initialize card and send host supports SDHC if SD2
   arg = type() == SD_CARD_TYPE_SD2 ? 0X40000000 : 0;
   timeout.set(SD_INIT_TIMEOUT);
   while (cardAcmd(ACMD41, arg) != R1_READY_STATE) {
     // check for timeout
     if (timeout.timedOut()) {
       error(SD_CARD_ERROR_ACMD41);
       goto fail;
     }
   }
   // if SD2 read OCR register to check for SDHC card
   if (type() == SD_CARD_TYPE_SD2) {
     if (cardCommand(CMD58, 0)) {
       error(SD_CARD_ERROR_CMD58);
       goto fail;
     }
     if ((spiReceive() & 0XC0) == 0XC0) {
       type(SD_CARD_TYPE_SDHC);
     }
     // Discard rest of ocr - contains allowed voltage range.
     for (uint8_t i = 0; i < 3; i++) {
       spiReceive();
     }
   }
   spiStop();
   spiSetSckSpeed(spiConfig.maxSck);
   return true;
  fail:
   spiStop();
   return false;
 }
References ACMD41, cardAcmd(), cardCommand(), CMD0, CMD58, CMD59, CMD8, SdSpiConfig::csPin, error(), IDLE_STATE, m_csPin, m_errorCode, m_spiActive, m_state, m_status, m_type, SdSpiConfig::maxSck, R1_IDLE_STATE, R1_ILLEGAL_COMMAND, R1_READY_STATE, SD_CARD_TYPE_SD1, SD_CARD_TYPE_SD2, SD_CARD_TYPE_SDHC, SD_CMD0_RETRY, SD_INIT_TIMEOUT, SD_MAX_INIT_RATE_KHZ, sdCsInit(), spiBegin(), SdSpiConfig::spiPort, spiReceive(), spiSelect(), spiSend(), spiSetSckSpeed(), spiStart(), spiStop(), spiUnselect(), timeout, and type().
Referenced by DedicatedSpiCard::begin(), and SdCardFactory::newCard().
cardAcmd()
uint8_t SharedSpiCard::cardAcmd (uint8_t cmd, uint32_t arg) inline private
Definition at line 246 of file SdSpiCard.h.
{
     cardCommand(CMD55, 0);
     return cardCommand(cmd, arg);
   }
References cardCommand(), and CMD55.
Referenced by begin(), and readStatus().
cardCommand()
uint8_t SharedSpiCard::cardCommand (uint8_t cmd, uint32_t arg) private
Definition at line 224 of file SdSpiCard.cpp.
{
   if (!syncDevice()) {
     return 0XFF;
   }
   // select card
   if (!m_spiActive) {
     spiStart();
   }
   if (cmd != CMD12) {
     if (!waitReady(SD_CMD_TIMEOUT) && cmd != CMD0) {
       return 0XFF;
     }
   }
 #if USE_SD_CRC
   // form message
   uint8_t buf[6];
   buf[0] = (uint8_t)0x40U | cmd;
   buf[1] = (uint8_t)(arg >> 24U);
   buf[2] = (uint8_t)(arg >> 16U);
   buf[3] = (uint8_t)(arg >> 8U);
   buf[4] = (uint8_t)arg;
   // add CRC
   buf[5] = CRC7(buf, 5);
   // send message
   spiSend(buf, 6);
 #else  // USE_SD_CRC
   // send command
   spiSend(cmd | 0x40);
   // send argument
   uint8_t* pa = reinterpret_cast<uint8_t*>(&arg);
   for (int8_t i = 3; i >= 0; i--) {
     spiSend(pa[i]);
   }
   // send CRC - correct for CMD0 with arg zero or CMD8 with arg 0X1AA
   spiSend(cmd == CMD0 ? 0X95 : 0X87);
 #endif  // USE_SD_CRC
   // discard first fill byte to avoid MISO pull-up problem.
   spiReceive();
   // there are 1-8 fill bytes before response.  fill bytes should be 0XFF.
   uint16_t n = 0;
   do {
     m_status = spiReceive();
   } while (m_status & 0X80 && ++n < 10);
   return m_status;
 }
References buf, CMD0, CMD12, m_spiActive, m_status, SD_CMD_TIMEOUT, spiReceive(), spiSend(), spiStart(), syncDevice(), and waitReady().
Referenced by begin(), cardAcmd(), erase(), readOCR(), readRegister(), readSector(), readStart(), readStop(), writeSector(), and writeStart().
erase()
bool SharedSpiCard::erase (uint32_t firstSector, uint32_t lastSector)
Erase a range of sectors.
Parameters
[in] firstSector The address of the first sector in the range.
[in] lastSector The address of the last sector in the range.
Note
This function requests the SD card to do a flash erase for a range of sectors. The data on the card after an erase operation is either 0 or 1, depends on the card vendor. The card must support single sector erase.
Returns
true for success or false for failure.
Definition at line 277 of file SdSpiCard.cpp.
{
   csd_t csd;
   if (!readCSD(&csd)) {
     goto fail;
   }
   // check for single sector erase
   if (!csd.v1.erase_blk_en) {
     // erase size mask
     uint8_t m = (csd.v1.sector_size_high << 1) | csd.v1.sector_size_low;
     if ((firstSector & m) != 0 || ((lastSector + 1) & m) != 0) {
       // error card can't erase specified area
       error(SD_CARD_ERROR_ERASE_SINGLE_SECTOR);
       goto fail;
     }
   }
   if (m_type != SD_CARD_TYPE_SDHC) {
     firstSector <<= 9;
     lastSector <<= 9;
   }
   if (cardCommand(CMD32, firstSector)
       || cardCommand(CMD33, lastSector)
       || cardCommand(CMD38, 0)) {
     error(SD_CARD_ERROR_ERASE);
     goto fail;
   }
   if (!waitReady(SD_ERASE_TIMEOUT)) {
     error(SD_CARD_ERROR_ERASE_TIMEOUT);
     goto fail;
   }
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD32, CMD33, CMD38, error(), if(), m, m_type, readCSD(), SD_CARD_TYPE_SDHC, SD_ERASE_TIMEOUT, spiStop(), csd_t::v1, and waitReady().
eraseSingleSectorEnable()
bool SharedSpiCard::eraseSingleSectorEnable ()
Determine if card supports single sector erase.
Returns
true is returned if single sector erase is supported. false is returned if single sector erase is not supported.
Definition at line 314 of file SdSpiCard.cpp.
{
   csd_t csd;
   return readCSD(&csd) ? csd.v1.erase_blk_en : false;
 }
References readCSD(), and csd_t::v1.
error()
void SharedSpiCard::error (uint8_t code) inline
Set SD error code.
Parameters
[in] code value for error code.
Definition at line 85 of file SdSpiCard.h.
{
 //    (void)code;
     m_errorCode = code;
   }
References m_errorCode.
Referenced by begin(), erase(), readData(), readOCR(), readRegister(), readSector(), readStart(), readStatus(), readStop(), writeData(), writeSector(), writeStart(), and writeStop().
errorCode()
uint8_t SharedSpiCard::errorCode () const inline
Returns
code for the last error. See SdCardInfo.h for a list of error codes.
Definition at line 92 of file SdSpiCard.h.
{
     return m_errorCode;
   }
References m_errorCode.
Referenced by SdBase< Vol >::cardBegin(), and SdBase< Vol >::sdErrorCode().
errorData()
uint32_t SharedSpiCard::errorData () const inline
Returns
error data for last error.
Definition at line 96 of file SdSpiCard.h.
{
     return m_status;
   }
References m_status.
Referenced by SdBase< Vol >::sdErrorData().
isBusy()
bool SharedSpiCard::isBusy ()
Check for busy. MISO low indicates the card is busy.
Returns
true if busy else false.
Definition at line 319 of file SdSpiCard.cpp.
{
   if (m_state == READ_STATE) {
     return false;
   }
   bool spiActive = m_spiActive;
   if (!spiActive) {
     spiStart();
   }
   bool rtn = 0XFF != spiReceive();
   if (!spiActive) {
     spiStop();
   }
   return rtn;
 }
References m_spiActive, m_state, READ_STATE, spiReceive(), spiStart(), and spiStop().
Referenced by ExFatPartition::isBusy().
readCID()
bool SharedSpiCard::readCID (cid_t * cid) inline
Read a card's CID register. The CID contains card identification information such as Manufacturer ID, Product name, Product serial number and Manufacturing date.
Parameters
[out] cid pointer to area for returned data.
Returns
true for success or false for failure.
Definition at line 114 of file SdSpiCard.h.
{
     return readRegister(CMD10, cid);
   }
References CMD10, and readRegister().
readCSD()
bool SharedSpiCard::readCSD (csd_t * csd) inline
Read a card's CSD register. The CSD contains Card-Specific Data that provides information regarding access to the card's contents.
Parameters
[out] csd pointer to area for returned data.
Returns
true for success or false for failure.
Definition at line 125 of file SdSpiCard.h.
{
     return readRegister(CMD9, csd);
   }
References CMD9, and readRegister().
Referenced by erase(), eraseSingleSectorEnable(), and sectorCount().
readData() [1/2]
bool SharedSpiCard::readData (uint8_t * dst)
Read one data sector in a multiple sector read sequence
Parameters
[out] dst Pointer to the location for the data to be read.
Returns
true for success or false for failure.
Definition at line 334 of file SdSpiCard.cpp.
{
   return readData(dst, 512);
 }
Referenced by readRegister(), readSector(), readSectors(), DedicatedSpiCard::readSectors(), and readStatus().
readData() [2/2]
bool SharedSpiCard::readData (uint8_t * dst, size_t count) private
Definition at line 338 of file SdSpiCard.cpp.
{
 #if USE_SD_CRC
   uint16_t crc;
 #endif  // USE_SD_CRC
   // wait for start sector token
   Timeout timeout(SD_READ_TIMEOUT);
   while ((m_status = spiReceive()) == 0XFF) {
     if (timeout.timedOut()) {
       error(SD_CARD_ERROR_READ_TIMEOUT);
       goto fail;
     }
   }
   if (m_status != DATA_START_SECTOR) {
     error(SD_CARD_ERROR_READ_TOKEN);
     goto fail;
   }
   // transfer data
   if ((m_status = spiReceive(dst, count))) {
     error(SD_CARD_ERROR_DMA);
     goto fail;
   }
 #if USE_SD_CRC
   // get crc
   crc = (spiReceive() << 8) | spiReceive();
   if (crc != CRC_CCITT(dst, count)) {
     error(SD_CARD_ERROR_READ_CRC);
     goto fail;
   }
 #else  // USE_SD_CRC
   // discard crc
   spiReceive();
   spiReceive();
 #endif  // USE_SD_CRC
   return true;
  fail:
   spiStop();
   return false;
 }
References count, crc, DATA_START_SECTOR, error(), m_status, SD_READ_TIMEOUT, spiReceive(), spiStop(), and timeout.
readOCR()
bool SharedSpiCard::readOCR (uint32_t * ocr)
Read OCR register.
Parameters
[out] ocr Value of OCR register.
Returns
true for success or false for failure.
Definition at line 380 of file SdSpiCard.cpp.
{
   uint8_t* p = reinterpret_cast<uint8_t*>(ocr);
   if (cardCommand(CMD58, 0)) {
     error(SD_CARD_ERROR_CMD58);
     goto fail;
   }
   for (uint8_t i = 0; i < 4; i++) {
     p[3 - i] = spiReceive();
   }
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD58, error(), p, spiReceive(), and spiStop().
readRegister()
bool SharedSpiCard::readRegister (uint8_t cmd, void * buf) private
read CID or CSR register
Definition at line 398 of file SdSpiCard.cpp.
{
   uint8_t* dst = reinterpret_cast<uint8_t*>(buf);
   if (cardCommand(cmd, 0)) {
     error(SD_CARD_ERROR_READ_REG);
     goto fail;
   }
   if (!readData(dst, 16)) {
     goto fail;
   }
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References buf, cardCommand(), error(), readData(), and spiStop().
Referenced by readCID(), and readCSD().
readSector()
bool SharedSpiCard::readSector (uint32_t sector, uint8_t * dst)
Read a 512 byte sector from an SD card.
Parameters
[in] sector Logical sector to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 415 of file SdSpiCard.cpp.
{
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD17, sector)) {
     error(SD_CARD_ERROR_CMD17);
     goto fail;
   }
   if (!readData(dst, 512)) {
     goto fail;
   }
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD17, error(), readData(), SD_CARD_TYPE_SDHC, spiStop(), and type().
Referenced by FsCache::cacheSafeRead(), FsCache::prepare(), and ExFatPartition::readSector().
readSectors()
bool SharedSpiCard::readSectors (uint32_t sector, uint8_t * dst, size_t ns)
Read multiple 512 byte sectors from an SD card.
Parameters
[in] sector Logical sector to be read.
[in] ns Number of sectors to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 435 of file SdSpiCard.cpp.
{
   if (!readStart(sector)) {
     goto fail;
   }
   for (size_t i = 0; i < ns; i++, dst += 512) {
     if (!readData(dst, 512)) {
       goto fail;
     }
   }
   return readStop();
  fail:
   return false;
 }
References readData(), readStart(), and readStop().
Referenced by FsCache::cacheSafeRead().
readStart()
bool SharedSpiCard::readStart (uint32_t sector)
Start a read multiple sector sequence.
Parameters
[in] sector Address of first sector in sequence.
Note
This function is used with readData() and readStop() for optimized multiple sector reads. SPI chipSelect must be low for the entire sequence.
Returns
true for success or false for failure.
Definition at line 449 of file SdSpiCard.cpp.
{
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD18, sector)) {
     error(SD_CARD_ERROR_CMD18);
     goto fail;
   }
   m_state = READ_STATE;
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD18, error(), m_state, READ_STATE, SD_CARD_TYPE_SDHC, spiStop(), and type().
Referenced by readSectors(), and DedicatedSpiCard::readSectors().
readStatus()
bool SharedSpiCard::readStatus (uint8_t * status)
Return the 64 byte card status
Parameters
[out] status location for 64 status bytes.
Returns
true for success or false for failure.
Definition at line 465 of file SdSpiCard.cpp.
{
   // retrun is R2 so read extra status byte.
   if (cardAcmd(ACMD13, 0) || spiReceive()) {
     error(SD_CARD_ERROR_ACMD13);
     goto fail;
   }
   if (!readData(status, 64)) {
     goto fail;
   }
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References ACMD13, cardAcmd(), error(), readData(), spiReceive(), spiStop(), and status.
readStop()
bool SharedSpiCard::readStop ()
End a read multiple sectors sequence.
Returns
true for success or false for failure.
Definition at line 482 of file SdSpiCard.cpp.
{
   m_state = IDLE_STATE;
   if (cardCommand(CMD12, 0)) {
     error(SD_CARD_ERROR_CMD12);
     goto fail;
   }
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD12, error(), IDLE_STATE, m_state, and spiStop().
Referenced by readSectors(), DedicatedSpiCard::readSectors(), and syncDevice().
sdState()
uint8_t SharedSpiCard::sdState () inline
Returns
SD multi-sector read/write state
Definition at line 180 of file SdSpiCard.h.
 {return m_state;}
References m_state.
Referenced by DedicatedSpiCard::readSectors(), and DedicatedSpiCard::writeSectors().
sectorCount()
uint32_t SharedSpiCard::sectorCount ()
Determine the size of an SD flash memory card.
Returns
The number of 512 byte data sectors in the card or zero if an error occurs.
Definition at line 496 of file SdSpiCard.cpp.
{
   csd_t csd;
   return readCSD(&csd) ? sdCardCapacity(&csd) : 0;
 }
References readCSD(), and sdCardCapacity().
Referenced by ExFatFormatter::format(), FatFormatter::format(), and SdFs::format().
spiActivate()
void SharedSpiCard::spiActivate () inline private
Definition at line 268 of file SdSpiCard.h.
                      {
     m_spiDriver.activate();
   }
References SdSpiArduinoDriver::activate(), and m_spiDriver.
Referenced by spiStart().
spiBegin()
void SharedSpiCard::spiBegin (SdSpiConfig spiConfig) inline private
Definition at line 271 of file SdSpiCard.h.
{
     m_spiDriver.begin(spiConfig);
   }
References SdSpiArduinoDriver::begin(), and m_spiDriver.
Referenced by begin().
spiDeactivate()
void SharedSpiCard::spiDeactivate () inline private
Definition at line 274 of file SdSpiCard.h.
{
     m_spiDriver.deactivate();
   }
References SdSpiArduinoDriver::deactivate(), and m_spiDriver.
Referenced by spiStop().
spiReceive() [1/2]
uint8_t SharedSpiCard::spiReceive () inline private
Definition at line 277 of file SdSpiCard.h.
{
     return m_spiDriver.receive();
   }
References m_spiDriver, and SdSpiArduinoDriver::receive().
Referenced by begin(), cardCommand(), isBusy(), readData(), readOCR(), readStatus(), waitReady(), writeData(), and writeSector().
spiReceive() [2/2]
uint8_t SharedSpiCard::spiReceive (uint8_t * buf, size_t n) inline private
Definition at line 280 of file SdSpiCard.h.
{
     return m_spiDriver.receive(buf, n);
   }
References buf, m_spiDriver, and SdSpiArduinoDriver::receive().
spiSelect()
void SharedSpiCard::spiSelect () inline private
Definition at line 253 of file SdSpiCard.h.
                    {
     sdCsWrite(m_csPin, false);
   }
References m_csPin, and sdCsWrite().
Referenced by begin(), and spiStart().
spiSend() [1/2]
void SharedSpiCard::spiSend (const uint8_t * buf, size_t n) inline private
Definition at line 286 of file SdSpiCard.h.
{
     m_spiDriver.send(buf, n);
   }
References buf, m_spiDriver, and SdSpiArduinoDriver::send().
spiSend() [2/2]
void SharedSpiCard::spiSend (uint8_t data) inline private
Definition at line 283 of file SdSpiCard.h.
{
     m_spiDriver.send(data);
   }
References data, m_spiDriver, and SdSpiArduinoDriver::send().
Referenced by begin(), cardCommand(), spiStart(), spiStop(), writeData(), and writeStop().
spiSetSckSpeed()
void SharedSpiCard::spiSetSckSpeed (uint32_t maxSck) inline private
Definition at line 289 of file SdSpiCard.h.
{
     m_spiDriver.setSckSpeed(maxSck);
   }
References m_spiDriver, and SdSpiArduinoDriver::setSckSpeed().
Referenced by begin().
spiStart()
void SharedSpiCard::spiStart () private
Definition at line 501 of file SdSpiCard.cpp.
{
   if (!m_spiActive) {
     spiActivate();
     spiSelect();
     // Dummy byte to drive MISO busy status.
     spiSend(0XFF);
     m_spiActive = true;
   }
 }
References m_spiActive, spiActivate(), spiSelect(), and spiSend().
Referenced by begin(), cardCommand(), and isBusy().
spiStop()
void SharedSpiCard::spiStop () private
Definition at line 511 of file SdSpiCard.cpp.
{
   if (m_spiActive) {
     spiUnselect();
     // Insure MISO goes to low Z.
     spiSend(0XFF);
     spiDeactivate();
     m_spiActive = false;
   }
 }
References m_spiActive, spiDeactivate(), spiSend(), and spiUnselect().
Referenced by begin(), erase(), isBusy(), readData(), readOCR(), readRegister(), readSector(), readStart(), readStatus(), readStop(), writeData(), writeSector(), writeSectors(), writeStart(), and writeStop().
spiUnselect()
void SharedSpiCard::spiUnselect () inline private
Definition at line 258 of file SdSpiCard.h.
                      {
     sdCsWrite(m_csPin, true);
   }
References m_csPin, and sdCsWrite().
Referenced by begin(), and spiStop().
stopTransfer()
bool SharedSpiCard::stopTransfer ()
end a mult-sector transfer.
Returns
true for success or false for failure.
syncDevice()
bool SharedSpiCard::syncDevice ()
Returns
success if sync successful. Not for user apps.
Definition at line 521 of file SdSpiCard.cpp.
{
   if (m_state == WRITE_STATE) {
     return writeStop();
   }
   if (m_state == READ_STATE) {
     return readStop();
   }
   return true;
 }
References m_state, READ_STATE, readStop(), WRITE_STATE, and writeStop().
Referenced by cardCommand(), ExFatPartition::syncDevice(), and FatPartition::syncDevice().
type() [1/2]
uint8_t SharedSpiCard::type () const inline
Return the card type: SD V1, SD V2 or SDHC/SDXC
Returns
0 - SD V1, 1 - SD V2, or 3 - SDHC/SDXC.
Definition at line 202 of file SdSpiCard.h.
{
     return m_type;
   }
References m_type.
Referenced by begin(), readSector(), readStart(), writeSector(), and writeStart().
type() [2/2]
void SharedSpiCard::type (uint8_t value) inline private
Definition at line 261 of file SdSpiCard.h.
{
     m_type = value;
   }
References m_type.
waitReady()
bool SharedSpiCard::waitReady (uint16_t ms) private
Definition at line 531 of file SdSpiCard.cpp.
{
   Timeout timeout(ms);
   while (spiReceive() != 0XFF) {
     if (timeout.timedOut()) {
       return false;
     }
   }
   return true;
 }
References spiReceive(), and timeout.
Referenced by cardCommand(), erase(), writeData(), writeSector(), and writeStop().
writeData() [1/2]
bool SharedSpiCard::writeData (const uint8_t * src)
Write one data sector in a multiple sector write sequence.
Parameters
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 541 of file SdSpiCard.cpp.
{
   // wait for previous write to finish
   if (!waitReady(SD_WRITE_TIMEOUT)) {
     error(SD_CARD_ERROR_WRITE_TIMEOUT);
     goto fail;
   }
   if (!writeData(WRITE_MULTIPLE_TOKEN, src)) {
     goto fail;
   }
   return true;
  fail:
   spiStop();
   return false;
 }
References error(), SD_WRITE_TIMEOUT, spiStop(), waitReady(), and WRITE_MULTIPLE_TOKEN.
Referenced by writeSector(), writeSectors(), and DedicatedSpiCard::writeSectors().
writeData() [2/2]
bool SharedSpiCard::writeData (uint8_t token, const uint8_t * src) private
Definition at line 558 of file SdSpiCard.cpp.
{
 #if USE_SD_CRC
   uint16_t crc = CRC_CCITT(src, 512);
 #else  // USE_SD_CRC
   uint16_t crc = 0XFFFF;
 #endif  // USE_SD_CRC
   spiSend(token);
   spiSend(src, 512);
   spiSend(crc >> 8);
   spiSend(crc & 0XFF);
   m_status = spiReceive();
   if ((m_status & DATA_RES_MASK) != DATA_RES_ACCEPTED) {
     error(SD_CARD_ERROR_WRITE_DATA);
     goto fail;
   }
   return true;
  fail:
   spiStop();
   return false;
 }
References crc, DATA_RES_ACCEPTED, DATA_RES_MASK, error(), m_status, spiReceive(), spiSend(), spiStop(), and token.
writeSector()
bool SharedSpiCard::writeSector (uint32_t sector, const uint8_t * src)
Write a 512 byte sector to an SD card.
Parameters
[in] sector Logical sector to be written.
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 581 of file SdSpiCard.cpp.
{
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD24, sector)) {
     error(SD_CARD_ERROR_CMD24);
     goto fail;
   }
   if (!writeData(DATA_START_SECTOR, src)) {
     goto fail;
   }
 #if CHECK_FLASH_PROGRAMMING
   // wait for flash programming to complete
   if (!waitReady(SD_WRITE_TIMEOUT)) {
     error(SD_CARD_ERROR_WRITE_PROGRAMMING);
     goto fail;
   }
   // response is r2 so get and check two bytes for nonzero
   if (cardCommand(CMD13, 0) || spiReceive()) {
     error(SD_CARD_ERROR_CMD13);
     goto fail;
   }
 #endif  // CHECK_FLASH_PROGRAMMING
   spiStop();
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD13, CMD24, DATA_START_SECTOR, error(), SD_CARD_TYPE_SDHC, SD_WRITE_TIMEOUT, spiReceive(), spiStop(), type(), waitReady(), and writeData().
Referenced by FsCache::cacheSafeWrite(), ExFatFormatter::format(), FatFormatter::initFatDir(), FatFormatter::makeFat16(), FatFormatter::makeFat32(), FsCache::sync(), ExFatFormatter::syncUpcase(), FatFormatter::writeMbr(), ExFatPartition::writeSector(), DedicatedSpiCard::writeSector(), and ExFatFormatter::writeUpcaseByte().
writeSectors()
bool SharedSpiCard::writeSectors (uint32_t sector, const uint8_t * src, size_t ns)
Write multiple 512 byte sectors to an SD card.
Parameters
[in] sector Logical sector to be written.
[in] ns Number of sectors to be written.
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 615 of file SdSpiCard.cpp.
{
   if (!writeStart(sector)) {
     goto fail;
   }
   for (size_t i = 0; i < ns; i++, src += 512) {
     if (!writeData(src)) {
       goto fail;
     }
   }
   return writeStop();
  fail:
   spiStop();
   return false;
 }
References spiStop(), writeData(), writeStart(), and writeStop().
Referenced by FsCache::cacheSafeWrite().
writeStart()
bool SharedSpiCard::writeStart (uint32_t sector)
Start a write multiple sectors sequence.
Parameters
[in] sector Address of first sector in sequence.
Note
This function is used with writeData() and writeStop() for optimized multiple sector writes.
Returns
true for success or false for failure.
Definition at line 632 of file SdSpiCard.cpp.
{
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD25, sector)) {
     error(SD_CARD_ERROR_CMD25);
     goto fail;
   }
   m_state = WRITE_STATE;
   return true;
  fail:
   spiStop();
   return false;
 }
References cardCommand(), CMD25, error(), m_state, SD_CARD_TYPE_SDHC, spiStop(), type(), and WRITE_STATE.
Referenced by writeSectors(), and DedicatedSpiCard::writeSectors().
writeStop()
bool SharedSpiCard::writeStop ()
End a write multiple sectors sequence.
Returns
true for success or false for failure.
Definition at line 649 of file SdSpiCard.cpp.
{
   if (!waitReady(SD_WRITE_TIMEOUT)) {
     goto fail;
   }
   spiSend(STOP_TRAN_TOKEN);
   spiStop();
   m_state = IDLE_STATE;
   return true;
  fail:
   error(SD_CARD_ERROR_STOP_TRAN);
   spiStop();
   return false;
 }
References error(), IDLE_STATE, m_state, SD_WRITE_TIMEOUT, spiSend(), spiStop(), STOP_TRAN_TOKEN, and waitReady().
Referenced by syncDevice(), writeSectors(), and DedicatedSpiCard::writeSectors().
Member Data Documentation
IDLE_STATE
const uint8_t SharedSpiCard::IDLE_STATE = 0 static
SD is in idle state
Definition at line 50 of file SdSpiCard.h.
Referenced by begin(), readStop(), and writeStop().
m_csPin
SdCsPin_t SharedSpiCard::m_csPin private
Definition at line 321 of file SdSpiCard.h.
Referenced by begin(), spiSelect(), and spiUnselect().
m_errorCode
uint8_t SharedSpiCard::m_errorCode = SD_CARD_ERROR_INIT_NOT_CALLED private
Definition at line 322 of file SdSpiCard.h.
Referenced by begin(), error(), and errorCode().
m_spiActive
bool SharedSpiCard::m_spiActive private
Definition at line 323 of file SdSpiCard.h.
Referenced by begin(), cardCommand(), isBusy(), spiStart(), and spiStop().
m_spiDriver
SdSpiDriver SharedSpiCard::m_spiDriver private
Definition at line 292 of file SdSpiCard.h.
Referenced by spiActivate(), spiBegin(), spiDeactivate(), spiReceive(), spiSend(), and spiSetSckSpeed().
m_state
uint8_t SharedSpiCard::m_state private
Definition at line 324 of file SdSpiCard.h.
Referenced by begin(), isBusy(), readStart(), readStop(), sdState(), syncDevice(), writeStart(), and writeStop().
m_status
uint8_t SharedSpiCard::m_status private
Definition at line 325 of file SdSpiCard.h.
Referenced by begin(), cardCommand(), errorData(), readData(), and writeData().
m_type
uint8_t SharedSpiCard::m_type = 0 private
Definition at line 326 of file SdSpiCard.h.
Referenced by begin(), erase(), and type().
READ_STATE
const uint8_t SharedSpiCard::READ_STATE = 1 static
SD is in multi-sector read state.
Definition at line 52 of file SdSpiCard.h.
Referenced by isBusy(), DedicatedSpiCard::readSectors(), readStart(), and syncDevice().
WRITE_STATE
const uint8_t SharedSpiCard::WRITE_STATE = 2 static
SD is in multi-sector write state.
Definition at line 54 of file SdSpiCard.h.
Referenced by syncDevice(), DedicatedSpiCard::writeSectors(), and writeStart().
The documentation for this class was generated from the following files:
ERISCore/lib/SdFat-master/src/SdCard/SdSpiCard.h
ERISCore/lib/SdFat-master/src/SdCard/SdSpiCard.cpp