ERIS CORE: AudioStream::release
release()
void AudioStream::release (audio_block_t * block) static protected
Definition at line 135 of file AudioStream.cpp.
 {
     //if (block == NULL) return;
     uint32_t mask = (0x80000000 >> (31 - (block->memory_pool_index & 0x1F)));
     uint32_t index = block->memory_pool_index >> 5;
     //__disable_irq();
     if (block->ref_count > 1) {
         block->ref_count--;
     } else {
         //Serial.print("reles:");
         //Serial.println((uint32_t)block, HEX);
         memory_pool_available_mask[index] |= mask;
         if (index < memory_pool_first_mask) memory_pool_first_mask = index;
         memory_used--;
     }
     //__enable_irq();
 }
References memory_pool_available_mask, memory_pool_first_mask, audio_block_struct::memory_pool_index, memory_used, and audio_block_struct::ref_count.
Referenced by AudioConnection::disconnect(), erisAudioAnalyzeFFT1024::update(), and erisAudioAnalyzeScope::update().