ERIS CORE: main.c File Reference
main.c File Reference
#include <stdio.h>
#include "wren.h"
Functions
void errorFn (WrenVM *vm, WrenErrorType errorType, const char *module, const int line, const char *msg)
int main ()
static void writeFn (WrenVM *vm, const char *text)
Function Documentation
errorFn()
void errorFn (WrenVM * vm, WrenErrorType errorType, const char * module, const int line, const char * msg)
Definition at line 11 of file main.c.
 {
   switch (errorType)
   {
     case WREN_ERROR_COMPILE:
     {
       printf("[%s line %d] [Error] %s\n", module, line, msg);
     } break;
     case WREN_ERROR_STACK_TRACE:
     {
       printf("[%s line %d] in %s\n", module, line, msg);
     } break;
     case WREN_ERROR_RUNTIME:
     {
       printf("[Runtime Error] %s\n", msg);
     } break;
   }
 }
References WREN_ERROR_COMPILE, WREN_ERROR_RUNTIME, and WREN_ERROR_STACK_TRACE.
Referenced by main().
main()
int main ()
Definition at line 32 of file main.c.
 {
   WrenConfiguration config;
   wrenInitConfiguration(&config);
     config.writeFn = &writeFn;
     config.errorFn = &errorFn;
   WrenVM* vm = wrenNewVM(&config);
   const char* module = "main";
   const char* script = "System.print(\"I am running in a VM!\")";
   WrenInterpretResult result = wrenInterpret(vm, module, script);
   switch (result)
   {
     case WREN_RESULT_COMPILE_ERROR:
       { printf("Compile Error!\n"); } break;
     case WREN_RESULT_RUNTIME_ERROR:
       { printf("Runtime Error!\n"); } break;
     case WREN_RESULT_SUCCESS:
       { printf("Success!\n"); } break;
   }
   wrenFreeVM(vm);
 }
References config, errorFn(), WREN_RESULT_COMPILE_ERROR, WREN_RESULT_RUNTIME_ERROR, WREN_RESULT_SUCCESS, wrenFreeVM(), wrenInitConfiguration(), wrenInterpret(), wrenNewVM(), and writeFn().
writeFn()
static void writeFn (WrenVM * vm, const char * text) static
Definition at line 6 of file main.c.
 {
   printf("%s", text);
 }
Referenced by main().