ERIS CORE: DigitalPin< PinNumber > Class Template Reference
DigitalPin< PinNumber > Class Template Reference
Fast Pin I/O
Fast digital port I/O.
#include <DigitalPin.h>
Public Member Functions
DigitalPin ()
__attribute__ ((always_inline)) bool read() const
__attribute__ ((always_inline)) void config(uint8_t mode
__attribute__ ((always_inline)) void high()
__attribute__ ((always_inline)) void low()
__attribute__ ((always_inline)) void mode(uint8_t mode)
__attribute__ ((always_inline)) void toggle()
__attribute__ ((always_inline)) void write(bool value)
operator bool () const __attribute__((always_inline))
DigitalPin & operator= (bool value) __attribute__((always_inline))
Public Attributes
bool level
Detailed Description
template<uint8_t PinNumber>
class DigitalPin< PinNumber >
Fast digital port I/O.
Definition at line 297 of file DigitalPin.h.
Constructor & Destructor Documentation
DigitalPin()
template<uint8_t PinNumber> DigitalPin< PinNumber >::DigitalPin () inline
Constructor
Definition at line 301 of file DigitalPin.h.
 {}
Member Function Documentation
__attribute__() [1/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) const inline
Returns
Pin's level.
Definition at line 356 of file DigitalPin.h.
                     {
     return fastDigitalRead(PinNumber);
   }
References fastDigitalRead().
__attribute__() [2/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) inline
Set pin configuration.
Parameters
[in] mode INPUT or OUTPUT.
[in] level If mode is OUTPUT, set level high/low. If mode is INPUT, enable or disable the pin's 20K pullup.
__attribute__() [3/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) inline
Set pin level high if output mode or enable 20K pullup if input mode.
Definition at line 334 of file DigitalPin.h.
               {write(true);}
__attribute__() [4/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) inline
Set pin level low if output mode or disable 20K pullup if input mode.
Definition at line 340 of file DigitalPin.h.
              {write(false);}
__attribute__() [5/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) inline
Set pin mode.
Parameters
[in] mode INPUT, OUTPUT, or INPUT_PULLUP.
The internal pullup resistors will be enabled if mode is INPUT_PULLUP and disabled if the mode is INPUT.
Definition at line 350 of file DigitalPin.h.
{
     fastPinMode(PinNumber, mode);
   }
References fastPinMode(), and mode.
__attribute__() [6/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) inline
Toggle a pin.
If the pin is in output mode toggle the pin's level. If the pin is in input mode toggle the state of the 20K pullup.
Definition at line 366 of file DigitalPin.h.
                 {
     fastDigitalToggle(PinNumber);
   }
References fastDigitalToggle().
__attribute__() [7/7]
template<uint8_t PinNumber> DigitalPin< PinNumber >::__attribute__ ((always_inline)) inline
Write the pin's level.
Parameters
[in] value If true set the pin's level high else set the pin's level low.
Definition at line 375 of file DigitalPin.h.
{
     fastDigitalWrite(PinNumber, value);
   }
References fastDigitalWrite().
operator bool()
template<uint8_t PinNumber> DigitalPin< PinNumber >::operator bool () const inline
Parenthesis operator.
Returns
Pin's level
Definition at line 317 of file DigitalPin.h.
{
     return read();
   }
References read.
operator=()
template<uint8_t PinNumber> DigitalPin& DigitalPin< PinNumber >::operator= (bool value) inline
Asignment operator.
Parameters
[in] value If true set the pin's level high else set the pin's level low.
Returns
This DigitalPin instance.
Definition at line 309 of file DigitalPin.h.
{
     write(value);
     return *this;
   }
Member Data Documentation
level
template<uint8_t PinNumber> bool DigitalPin< PinNumber >::level
Initial value:
{
    fastPinConfig(PinNumber, mode, level)
Definition at line 327 of file DigitalPin.h.
The documentation for this class was generated from the following file:
ERISCore/lib/SdFat-master/src/DigitalIO/DigitalPin.h