ERIS CORE: TransitionScroll Class Reference
TransitionScroll Class Reference
#include <TransitionScroll.h>
Public Member Functions
TransitionScroll ()
void init (ILI9341_t3n tft)
boolean isComplete ()
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
void restart (ILI9341_t3n tft, uint_fast16_t color)
Detailed Description
Definition at line 18 of file TransitionScroll.h.
Constructor & Destructor Documentation
TransitionScroll()
TransitionScroll::TransitionScroll () inline
Definition at line 20 of file TransitionScroll.h.
 : BaseTransition() {};
Member Function Documentation
init()
void TransitionScroll::init (ILI9341_t3n tft) virtual
Reimplemented from BaseTransition.
Definition at line 35 of file TransitionScroll.h.
{
     _pixels = (uint16_t*)malloc( sizeof(uint_fast16_t) * tft.width() );
 }
References tft().
isComplete()
boolean TransitionScroll::isComplete () virtual
Reimplemented from BaseTransition.
Definition at line 117 of file TransitionScroll.h.
{
   return _phase >= 1.0f;
 }
perFrame()
void TransitionScroll::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseTransition.
Definition at line 68 of file TransitionScroll.h.
{
   uint_fast16_t w = (uint_fast16_t)tft.width();
   uint_fast16_t h = (uint_fast16_t)tft.height();
     _phase += frameParams.timeMult * TRANSITION_SCROLL_SPEED * SCROLL_WRAPS;
     // Apply some easing. Linear speed feels dull
     float ease = min( easeInOutCubic( _phase ), 1.0f );
     float unwrapped = SCROLL_WRAPS * ease;
     float wrap = unwrapped - floor(unwrapped);
     // scroll values fall from 1 to 0, so the image appears to move left.
     float scroll_f = w * (1.0f - wrap);
     uint_fast16_t scroll = floor(scroll_f);
     tft.setScroll( scroll );
     // Final frame: Fill with destination color
     if( unwrapped >= (SCROLL_WRAPS-1.0f) ) {
         if( scroll < _lastScroll ) {
             tft.fillRect( w - _lastScroll, 0, _lastScroll - scroll, h, _color );
             _lastScroll = scroll;
         }
         // Fill part of a random line
         uint_fast16_t x = random((uint_fast16_t)(w*0.9f),w);
         uint_fast16_t y = random(h);
         tft.drawFastHLine( x, y, w-x, _color );
     } else {
         // Let's noise this thing up
         uint_fast16_t staggerX = 1 + constrain( (ease-_lastEase) * STAGGER_X_STRENGTH, 0.0f, 1.0f ) * MAX_STAGGER_X;
         uint_fast8_t staggerHeight = random(1,MAX_STAGGER_HEIGHT+1);
         uint_fast16_t startY = random(h-(staggerHeight-1));
         for( uint_fast8_t line=0; line<staggerHeight; line++ ) {
             uint_fast16_t y = startY + line;
             tft.readRect( 0, y, w, 1, _pixels );
             tft.writeRect( staggerX, y, w-staggerX, 1, _pixels );
         }
     }
     _lastEase = ease;
 }
References easeInOutCubic(), MAX_STAGGER_HEIGHT, MAX_STAGGER_X, SCROLL_WRAPS, STAGGER_X_STRENGTH, tft(), FrameParams::timeMult, TRANSITION_SCROLL_SPEED, x, and y.
restart()
void TransitionScroll::restart (ILI9341_t3n tft, uint_fast16_t color) virtual
Reimplemented from BaseTransition.
Definition at line 39 of file TransitionScroll.h.
{
   //uint_fast16_t w = tft.width();
   //uint_fast16_t h = tft.height();
     _phase = 0;
     _color = inColor;
     _lastEase = 0;
     _lastScroll = tft.width();
 }
References tft().
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/TransitionScroll.h