ERIS CORE: SdExFat Class Reference
SdExFat Class Reference
SD file system class for exFAT volumes.
#include <SdFat.h>
Public Member Functions
uint32_t __attribute__ ((error("use sectorsPerCluster()"))) blocksPerCluster()
bool begin (BlockDevice *dev, bool setCwv=true, uint8_t part=1)
bool begin (SdCsPin_t csPin, uint32_t maxSck)
bool begin (SdCsPin_t csPin=SS)
bool begin (SdioConfig sdioConfig)
bool begin (SdSpiConfig spiConfig)
uint32_t bytesPerCluster () const
uint8_t bytesPerClusterShift () const
uint16_t bytesPerSector () const
uint8_t bytesPerSectorShift () const
uint8_t * cacheClear ()
SdCard * card ()
bool cardBegin (SdioConfig sdioConfig)
bool cardBegin (SdSpiConfig spiConfig)
bool chdir ()
bool chdir (const char *path)
void checkUpcase (print_t *pr)
void chvol ()
uint32_t clusterCount () const
uint32_t clusterHeapStartSector () const
void dmpBitmap (print_t *pr)
void dmpCluster (print_t *pr, uint32_t cluster, uint32_t offset, uint32_t count)
void dmpFat (print_t *pr, uint32_t start, uint32_t count)
void dmpSector (print_t *pr, uint32_t sector)
void errorHalt (print_t *pr)
void errorHalt (print_t *pr, const __FlashStringHelper *msg)
void errorHalt (print_t *pr, const char *msg)
void errorPrint (Print *pr, const __FlashStringHelper *msg)
void errorPrint (print_t *pr)
void errorPrint (print_t *pr, char const *msg)
bool exists (const char *path)
uint32_t fatLength () const
uint32_t fatStartSector () const
uint8_t fatType () const
bool format (print_t *pr=nullptr)
uint32_t freeClusterCount ()
bool init (BlockDevice *dev, uint8_t part)
void initErrorHalt (Print *pr, const __FlashStringHelper *msg)
void initErrorHalt (print_t *pr)
void initErrorHalt (print_t *pr, const char *msg)
void initErrorPrint (Print *pr)
bool isBusy ()
bool ls (print_t *pr, const char *path, uint8_t flags)
bool ls (print_t *pr, uint8_t flags=0)
bool mkdir (const char *path, bool pFlag=true)
ExFile open (const char *path, oflag_t oflag=O_RDONLY)
bool printDir (print_t *pr, ExFatFile *file)
void printFat (print_t *pr)
void printFatType (print_t *pr)
void printSdError (print_t *pr)
void printUpcase (print_t *pr)
bool printVolInfo (print_t *pr)
bool remove (const char *path)
bool rename (const char *oldPath, const char *newPath)
bool rmdir (const char *path)
uint32_t rootDirectoryCluster () const
uint32_t rootLength ()
uint8_t sdErrorCode ()
uint8_t sdErrorData ()
uint32_t sectorsPerCluster () const
uint8_t sectorsPerClusterShift () const
bool truncate (const char *path, uint64_t length)
ExFatVolume * vol ()
bool volumeBegin ()
Private Member Functions
uint8_t * bitmapCachePrepare (uint32_t sector, uint8_t option)
uint32_t bitmapFind (uint32_t cluster, uint32_t count)
bool bitmapModify (uint32_t cluster, uint32_t count, bool value)
void cacheInit (BlockDevice *dev)
bool cacheSafeRead (uint32_t sector, uint8_t *dst)
bool cacheSafeRead (uint32_t sector, uint8_t *dst, size_t count)
bool cacheSafeWrite (uint32_t sector, const uint8_t *src)
bool cacheSafeWrite (uint32_t sector, const uint8_t *src, size_t count)
bool cacheSync ()
uint32_t chainSize (uint32_t cluster)
uint32_t clusterMask () const
uint32_t clusterStartSector (uint32_t cluster)
void dataCacheDirty ()
void dataCacheInvalidate ()
uint8_t * dataCachePrepare (uint32_t sector, uint8_t option)
uint32_t dataCacheSector ()
bool dataCacheSync ()
uint8_t * dirCache (DirPos_t *pos, uint8_t options)
int8_t dirSeek (DirPos_t *pos, uint32_t offset)
int8_t fatGet (uint32_t cluster, uint32_t *value)
bool fatPut (uint32_t cluster, uint32_t value)
bool freeChain (uint32_t cluster)
bool readSector (uint32_t sector, uint8_t *dst)
uint16_t sectorMask () const
bool syncDevice ()
ExFatFile * vwd ()
bool writeSector (uint32_t sector, const uint8_t *src)
Static Private Member Functions
static ExFatVolume * cwv ()
Private Attributes
friend ExFatFile
uint32_t m_bitmapStart
BlockDevice * m_blockDev
uint32_t m_bytesPerCluster
SdCard * m_card
SdCardFactory m_cardFactory
uint32_t m_clusterCount
uint32_t m_clusterHeapStartSector
uint32_t m_clusterMask
FsCache m_dataCache
uint32_t m_fatLength
uint32_t m_fatStartSector
uint8_t m_fatType = 0
uint32_t m_rootDirectoryCluster
uint8_t m_sectorsPerClusterShift
ExFatFile m_vwd
Static Private Attributes
static const uint16_t m_bytesPerSector = 1 << m_bytesPerSectorShift
static const uint8_t m_bytesPerSectorShift = 9
static ExFatVolume * m_cwv = nullptr
static const uint16_t m_sectorMask = m_bytesPerSector - 1
Detailed Description
SD file system class for exFAT volumes.
Definition at line 373 of file SdFat.h.
Member Function Documentation
__attribute__()
uint32_t ExFatPartition::__attribute__ ((error("use sectorsPerCluster()"))) inherited
begin() [1/5]
bool ExFatVolume::begin (BlockDevice * dev, bool setCwv = true, uint8_t part = 1) inline inherited
Initialize an FatVolume object.
Parameters
[in] dev Device block driver.
[in] setCwv Set current working volume if true.
[in] part partition to initialize.
Returns
true for success or false for failure.
Definition at line 43 of file ExFatVolume.h.
{
     if (!init(dev, part)) {
       return false;
     }
     if (!chdir()) {
       return false;
     }
     if (setCwv || !m_cwv) {
       m_cwv = this;
     }
     return true;
   }
References ExFatVolume::chdir(), ExFatPartition::init(), and ExFatVolume::m_cwv.
Referenced by FsVolume::begin().
begin() [2/5]
bool SdBase< ExFatVolume >::begin (SdCsPin_t csPin, uint32_t maxSck) inline inherited
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
[in] maxSck Maximum SCK frequency.
Returns
true for success or false for failure.
Definition at line 73 of file SdFat.h.
{
     return begin(SdSpiConfig(csPin, SHARED_SPI, maxSck));
   }
begin() [3/5]
bool SdBase< ExFatVolume >::begin (SdCsPin_t csPin = SS) inline inherited
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
Returns
true for success or false for failure.
Definition at line 58 of file SdFat.h.
{
 #ifdef BUILTIN_SDCARD
     if (csPin == BUILTIN_SDCARD) {
       return begin(SdioConfig(FIFO_SDIO));
     }
 #endif  // BUILTIN_SDCARD
     return begin(SdSpiConfig(csPin, SHARED_SPI));
   }
begin() [4/5]
bool SdBase< ExFatVolume >::begin (SdioConfig sdioConfig) inline inherited
Initialize SD card and file system for SDIO mode.
Parameters
[in] sdioConfig SDIO configuration.
Returns
true for success or false for failure.
Definition at line 91 of file SdFat.h.
{
     return cardBegin(sdioConfig) && Vol::begin(m_card);
   }
begin() [5/5]
bool SdBase< ExFatVolume >::begin (SdSpiConfig spiConfig) inline inherited
Initialize SD card and file system for SPI mode.
Parameters
[in] spiConfig SPI configuration.
Returns
true for success or false for failure.
Definition at line 82 of file SdFat.h.
{
     return cardBegin(spiConfig) && Vol::begin(m_card);
   }
bitmapCachePrepare()
uint8_t* ExFatPartition::bitmapCachePrepare (uint32_t sector, uint8_t option) inline private inherited
Definition at line 138 of file ExFatPartition.h.
{
 #if USE_EXFAT_BITMAP_CACHE
     return m_bitmapCache.prepare(sector, option);
 #else  // USE_EXFAT_BITMAP_CACHE
     return m_dataCache.prepare(sector, option);
 #endif  // USE_EXFAT_BITMAP_CACHE
   }
References ExFatPartition::m_dataCache, and FsCache::prepare().
Referenced by ExFatPartition::bitmapFind(), and ExFatPartition::bitmapModify().
bitmapFind()
uint32_t ExFatPartition::bitmapFind (uint32_t cluster, uint32_t count) private inherited
Definition at line 30 of file ExFatPartition.cpp.
{
   uint32_t start = cluster ? cluster - 2 : m_bitmapStart;
   if (start >= m_clusterCount) {
     start = 0;
   }
   uint32_t endAlloc = start;
   uint32_t bgnAlloc = start;
   uint16_t sectorSize = 1 << m_bytesPerSectorShift;
   size_t i = (start >> 3) & (sectorSize - 1);
   uint8_t* cache;
   uint8_t mask = 1 << (start & 7);
   while (true) {
     uint32_t sector = m_clusterHeapStartSector +
                      (endAlloc >> (m_bytesPerSectorShift + 3));
     cache = bitmapCachePrepare(sector, FsCache::CACHE_FOR_READ);
     if (!cache) {
       return 0;
     }
     for (; i < sectorSize; i++) {
       for (; mask; mask <<= 1) {
         endAlloc++;
         if (!(mask & cache[i])) {
           if ((endAlloc - bgnAlloc) == count) {
             if (cluster == 0 && count == 1) {
               // Start at found sector.  bitmapModify may increase this.
               m_bitmapStart = bgnAlloc;
             }
             return bgnAlloc + 2;
           }
         } else {
           bgnAlloc = endAlloc;
         }
         if (endAlloc == start) {
           return 1;
         }
         if (endAlloc >= m_clusterCount) {
           endAlloc = bgnAlloc = 0;
           i = sectorSize;
           break;
         }
       }
       mask = 1;
     }
     i = 0;
   }
   return 0;
 }
References ExFatPartition::bitmapCachePrepare(), FsCache::CACHE_FOR_READ, count, ExFatPartition::m_bitmapStart, ExFatPartition::m_bytesPerSectorShift, ExFatPartition::m_clusterCount, and ExFatPartition::m_clusterHeapStartSector.
Referenced by ExFatFile::addCluster(), ExFatPartition::init(), and ExFatFile::preAllocate().
bitmapModify()
bool ExFatPartition::bitmapModify (uint32_t cluster, uint32_t count, bool value) private inherited
Definition at line 78 of file ExFatPartition.cpp.
{
   uint32_t sector;
   uint32_t start = cluster - 2;
   size_t i;
   uint8_t* cache;
   uint8_t mask;
   cluster -= 2;
   if ((start + count) > m_clusterCount) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (value) {
     if (start  <= m_bitmapStart && m_bitmapStart < (start + count)) {
       m_bitmapStart = (start + count) < m_clusterCount ? start + count : 0;
     }
   } else {
     if (start < m_bitmapStart) {
       m_bitmapStart = start;
     }
   }
   mask = 1 << (start & 7);
   sector = m_clusterHeapStartSector +
                    (start >> (m_bytesPerSectorShift + 3));
   i = (start >> 3) & m_sectorMask;
   while (true) {
     cache = bitmapCachePrepare(sector++, FsCache::CACHE_FOR_WRITE);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     for (; i < m_bytesPerSector; i++) {
       for (; mask; mask <<= 1) {
         if (value == static_cast<bool>(cache[i] & mask)) {
           DBG_FAIL_MACRO;
           goto fail;
         }
         cache[i] ^= mask;
         if (--count == 0) {
           return true;
         }
       }
       mask = 1;
     }
     i = 0;
   }
  fail:
   return false;
 }
References ExFatPartition::bitmapCachePrepare(), FsCache::CACHE_FOR_WRITE, count, DBG_FAIL_MACRO, ExFatPartition::m_bitmapStart, ExFatPartition::m_bytesPerSector, ExFatPartition::m_bytesPerSectorShift, ExFatPartition::m_clusterCount, ExFatPartition::m_clusterHeapStartSector, and ExFatPartition::m_sectorMask.
Referenced by ExFatFile::addCluster(), ExFatPartition::freeChain(), ExFatFile::preAllocate(), ExFatFile::remove(), and ExFatFile::truncate().
bytesPerCluster()
uint32_t ExFatPartition::bytesPerCluster () const inline inherited
Returns
the number of bytes in a cluster.
Definition at line 62 of file ExFatPartition.h.
 {return m_bytesPerCluster;}
References ExFatPartition::m_bytesPerCluster.
Referenced by ExFatFile::addDirCluster().
bytesPerClusterShift()
uint8_t ExFatPartition::bytesPerClusterShift () const inline inherited
Returns
the power of two for bytesPerCluster.
Definition at line 64 of file ExFatPartition.h.
{
     return m_bytesPerSectorShift + m_sectorsPerClusterShift;
   }
References ExFatPartition::m_bytesPerSectorShift, and ExFatPartition::m_sectorsPerClusterShift.
Referenced by ExFatPartition::dirSeek(), ExFatFile::preAllocate(), ExFatFile::remove(), ExFatPartition::rootLength(), ExFatFile::seekSet(), ExFatFile::truncate(), and ExFatFile::write().
bytesPerSector()
uint16_t ExFatPartition::bytesPerSector () const inline inherited
Returns
the number of bytes in a sector.
Definition at line 68 of file ExFatPartition.h.
 {return m_bytesPerSector;}
References ExFatPartition::m_bytesPerSector.
Referenced by ExFatFile::addDirCluster(), ExFatFile::read(), and ExFatFile::write().
bytesPerSectorShift()
uint8_t ExFatPartition::bytesPerSectorShift () const inline inherited
Returns
the power of two for bytesPerSector.
Definition at line 70 of file ExFatPartition.h.
 {return m_bytesPerSectorShift;}
References ExFatPartition::m_bytesPerSectorShift.
Referenced by ExFatFile::contiguousRange(), ExFatFile::read(), and ExFatFile::write().
cacheClear()
uint8_t* ExFatPartition::cacheClear () inline inherited
Clear the cache and returns a pointer to the cache. Not for normal apps.
Returns
A pointer to the cache buffer or zero if an error occurs.
Definition at line 75 of file ExFatPartition.h.
{
     return m_dataCache.clear();
   }
References FsCache::clear(), and ExFatPartition::m_dataCache.
Referenced by format().
cacheInit()
void ExFatPartition::cacheInit (BlockDevice * dev) inline private inherited
Definition at line 145 of file ExFatPartition.h.
{
 #if USE_EXFAT_BITMAP_CACHE
     m_bitmapCache.init(dev);
 #endif  // USE_EXFAT_BITMAP_CACHE
     m_dataCache.init(dev);
   }
References FsCache::init(), and ExFatPartition::m_dataCache.
Referenced by ExFatPartition::init().
cacheSafeRead() [1/2]
bool ExFatPartition::cacheSafeRead (uint32_t sector, uint8_t * dst) inline private inherited
Definition at line 181 of file ExFatPartition.h.
{
     return m_dataCache.cacheSafeRead(sector, dst);
   }
References FsCache::cacheSafeRead(), dst, and ExFatPartition::m_dataCache.
Referenced by ExFatFile::read().
cacheSafeRead() [2/2]
bool ExFatPartition::cacheSafeRead (uint32_t sector, uint8_t * dst, size_t count) inline private inherited
Definition at line 187 of file ExFatPartition.h.
{
     return m_dataCache.cacheSafeRead(sector, dst, count);
   }
References FsCache::cacheSafeRead(), count, dst, and ExFatPartition::m_dataCache.
cacheSafeWrite() [1/2]
bool ExFatPartition::cacheSafeWrite (uint32_t sector, const uint8_t * src) inline private inherited
Definition at line 184 of file ExFatPartition.h.
{
     return m_dataCache.cacheSafeWrite(sector, src);
   }
References FsCache::cacheSafeWrite(), and ExFatPartition::m_dataCache.
Referenced by ExFatFile::write().
cacheSafeWrite() [2/2]
bool ExFatPartition::cacheSafeWrite (uint32_t sector, const uint8_t * src, size_t count) inline private inherited
Definition at line 190 of file ExFatPartition.h.
{
      return m_dataCache.cacheSafeWrite(sector, src, count);
   }
References FsCache::cacheSafeWrite(), count, and ExFatPartition::m_dataCache.
cacheSync()
bool ExFatPartition::cacheSync () inline private inherited
Definition at line 151 of file ExFatPartition.h.
                    {
 #if USE_EXFAT_BITMAP_CACHE
     return m_bitmapCache.sync() && m_dataCache.sync() && syncDevice();
 #else  // USE_EXFAT_BITMAP_CACHE
     return m_dataCache.sync() && syncDevice();
 #endif  // USE_EXFAT_BITMAP_CACHE
   }
References ExFatPartition::m_dataCache, FsCache::sync(), and ExFatPartition::syncDevice().
Referenced by ExFatFile::remove(), ExFatFile::sync(), ExFatFile::syncDir(), and ExFatFile::timestamp().
card()
SdCard* SdBase< ExFatVolume >::card () inline inherited
Returns
Pointer to SD card object.
Definition at line 96 of file SdFat.h.
 {return m_card;}
cardBegin() [1/2]
bool SdBase< ExFatVolume >::cardBegin (SdioConfig sdioConfig) inline inherited
Initialize SD card in SDIO mode.
Parameters
[in] sdioConfig SDIO configuration.
Returns
true for success or false for failure.
Definition at line 113 of file SdFat.h.
{
     m_card = m_cardFactory.newCard(sdioConfig);
     return m_card && !m_card->errorCode();
   }
cardBegin() [2/2]
bool SdBase< ExFatVolume >::cardBegin (SdSpiConfig spiConfig) inline inherited
Initialize SD card in SPI mode.
Parameters
[in] spiConfig SPI configuration.
Returns
true for success or false for failure.
Definition at line 103 of file SdFat.h.
{
     m_card = m_cardFactory.newCard(spiConfig);
     return m_card && !m_card->errorCode();
   }
chainSize()
uint32_t ExFatPartition::chainSize (uint32_t cluster) private inherited
Definition at line 129 of file ExFatPartition.cpp.
{
   uint32_t n = 0;
   int8_t status;
   do {
     status = fatGet(cluster, & cluster);
     if (status < 0) return 0;
     n++;
   } while (status);
   return n;
 }
References ExFatPartition::fatGet(), and status.
Referenced by ExFatPartition::rootLength().
chdir() [1/2]
bool ExFatVolume::chdir () inline inherited
Set volume working directory to root.
Returns
true for success or false for failure.
Definition at line 59 of file ExFatVolume.h.
                {
     m_vwd.close();
     return m_vwd.openRoot(this);
   }
References ExFatFile::close(), ExFatVolume::m_vwd, and ExFatFile::openRoot().
Referenced by ExFatVolume::begin().
chdir() [2/2]
bool ExFatVolume::chdir (const char * path) inherited
Set volume working directory.
Parameters
[in] path Path for volume working directory.
Returns
true for success or false for failure.
Definition at line 30 of file ExFatVolume.cpp.
{
   ExFatFile dir;
   if (!dir.open(vwd(), path, O_RDONLY)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (!dir.isDir()) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_vwd = dir;
   return true;
  fail:
   return false;
 }
References DBG_FAIL_MACRO, ExFatFile::isDir(), ExFatVolume::m_vwd, O_RDONLY, ExFatFile::open(), and ExFatVolume::vwd().
checkUpcase()
void ExFatPartition::checkUpcase (print_t * pr) inherited
Definition at line 291 of file ExFatDbg.cpp.
{
   bool skip = false;
   uint16_t u = 0;
   uint8_t* upcase = nullptr;
   uint32_t size = 0;
   uint32_t sector = clusterStartSector(m_rootDirectoryCluster);
   uint8_t* cache = dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read root failed"));
     return;
   }
   DirUpcase_t* dir = reinterpret_cast<DirUpcase_t*>(cache);
   pr->println(F("\nChecking upcase table"));
   for (size_t i = 0; i < 16; i++) {
     if (dir[i].type == EXFAT_TYPE_UPCASE) {
       sector = clusterStartSector(getLe32(dir[i].firstCluster));
       size = getLe64(dir[i].size);
       break;
     }
   }
   if (!size) {
     pr->println(F("upcase not found"));
     return;
   }
   for (size_t i = 0; i < size/2; i++) {
     if ((i%256) == 0) {
       upcase = dataCachePrepare(sector++, FsCache::CACHE_FOR_READ);
       if (!upcase) {
         pr->println(F("read upcase failed"));
         return;
       }
     }
     uint16_t v = getLe16(&upcase[2*(i & 0XFF)]);
     if (skip) {
       pr->print("skip ");
       pr->print(u);
       pr->write(' ');
       pr->println(v);
     }
     if (v == 0XFFFF) {
       skip = true;
     } else if (skip) {
       for (uint16_t k = 0; k < v; k++) {
         uint16_t x = toUpcase(u + k);
         if (x != (u + k)) {
           printHex(pr, (uint16_t)(u+k));
           pr->write(',');
           printHex(pr, x);
           pr->println("<<<<<<<<<<<<<<<<<<<<");
         }
       }
       u += v;
       skip = false;
     } else {
       uint16_t x = toUpcase(u);
       if (v != x) {
         printHex(pr, u);
         pr->write(',');
         printHex(pr, x);
         pr->write(',');
         printHex(pr, v);
         pr->println();
       }
       u++;
     }
   }
   pr->println(F("Done checkUpcase"));
 }
References FsCache::CACHE_FOR_READ, ExFatPartition::clusterStartSector(), ExFatPartition::dataCachePrepare(), EXFAT_TYPE_UPCASE, F, getLe16(), getLe32(), getLe64(), ExFatPartition::m_rootDirectoryCluster, PrintBasic::print(), printHex(), PrintBasic::println(), toUpcase(), and PrintBasic::write().
chvol()
void ExFatVolume::chvol () inline inherited
Change global working volume to this volume.
Definition at line 71 of file ExFatVolume.h.
 {m_cwv = this;}
References ExFatVolume::m_cwv.
clusterCount()
uint32_t ExFatPartition::clusterCount () const inline inherited
Returns
the cluster count for the partition.
Definition at line 79 of file ExFatPartition.h.
 {return m_clusterCount;}
References ExFatPartition::m_clusterCount.
clusterHeapStartSector()
uint32_t ExFatPartition::clusterHeapStartSector () const inline inherited
Returns
the cluster heap start sector.
Definition at line 81 of file ExFatPartition.h.
 {return m_clusterHeapStartSector;}
References ExFatPartition::m_clusterHeapStartSector.
clusterMask()
uint32_t ExFatPartition::clusterMask () const inline private inherited
Definition at line 166 of file ExFatPartition.h.
 {return m_clusterMask;}
References ExFatPartition::m_clusterMask.
Referenced by ExFatFile::read(), and ExFatFile::write().
clusterStartSector()
uint32_t ExFatPartition::clusterStartSector (uint32_t cluster) inline private inherited
Definition at line 167 of file ExFatPartition.h.
{
     return m_clusterHeapStartSector +
            ((cluster - 2) << m_sectorsPerClusterShift);
   }
References ExFatPartition::m_clusterHeapStartSector, and ExFatPartition::m_sectorsPerClusterShift.
Referenced by ExFatFile::addDirCluster(), ExFatPartition::checkUpcase(), ExFatPartition::dirCache(), ExFatPartition::dmpCluster(), ExFatFile::firstSector(), ExFatPartition::printDir(), ExFatPartition::printUpcase(), ExFatFile::read(), and ExFatFile::write().
cwv()
static ExFatVolume* ExFatVolume::cwv () inline static private inherited
Definition at line 331 of file ExFatVolume.h.
 {return m_cwv;}
References ExFatVolume::m_cwv.
Referenced by ExFatFile::open().
dataCacheDirty()
void ExFatPartition::dataCacheDirty () inline private inherited
Definition at line 158 of file ExFatPartition.h.
 {m_dataCache.dirty();}
References FsCache::dirty(), and ExFatPartition::m_dataCache.
Referenced by ExFatFile::syncDir(), and ExFatFile::timestamp().
dataCacheInvalidate()
void ExFatPartition::dataCacheInvalidate () inline private inherited
Definition at line 159 of file ExFatPartition.h.
 {m_dataCache.invalidate();}
References FsCache::invalidate(), and ExFatPartition::m_dataCache.
dataCachePrepare()
uint8_t* ExFatPartition::dataCachePrepare (uint32_t sector, uint8_t option) inline private inherited
Definition at line 160 of file ExFatPartition.h.
{
     return m_dataCache.prepare(sector, option);
   }
References ExFatPartition::m_dataCache, and FsCache::prepare().
Referenced by ExFatFile::addDirCluster(), ExFatPartition::checkUpcase(), ExFatPartition::dirCache(), ExFatPartition::dmpFat(), ExFatPartition::dmpSector(), ExFatPartition::fatGet(), ExFatPartition::fatPut(), ExFatPartition::freeClusterCount(), ExFatPartition::init(), ExFatPartition::printDir(), ExFatPartition::printUpcase(), ExFatPartition::printVolInfo(), ExFatFile::read(), and ExFatFile::write().
dataCacheSector()
uint32_t ExFatPartition::dataCacheSector () inline private inherited
Definition at line 163 of file ExFatPartition.h.
 {return m_dataCache.sector();}
References ExFatPartition::m_dataCache, and FsCache::sector().
Referenced by ExFatFile::read().
dataCacheSync()
bool ExFatPartition::dataCacheSync () inline private inherited
Definition at line 164 of file ExFatPartition.h.
 {return m_dataCache.sync();}
References ExFatPartition::m_dataCache, and FsCache::sync().
Referenced by ExFatFile::write().
dirCache()
uint8_t * ExFatPartition::dirCache (DirPos_t * pos, uint8_t options) private inherited
Definition at line 140 of file ExFatPartition.cpp.
{
   uint32_t sector = clusterStartSector(pos->cluster);
   sector += (m_clusterMask & pos->position) >> m_bytesPerSectorShift;
   uint8_t* cache = dataCachePrepare(sector, options);
   return cache ? cache + (pos->position & m_sectorMask) : nullptr;
 }
References DirPos_t::cluster, ExFatPartition::clusterStartSector(), ExFatPartition::dataCachePrepare(), ExFatPartition::m_bytesPerSectorShift, ExFatPartition::m_clusterMask, ExFatPartition::m_sectorMask, and DirPos_t::position.
Referenced by ExFatFile::dirCache(), ExFatFile::getAccessDateTime(), ExFatFile::getCreateDateTime(), ExFatFile::getModifyDateTime(), ExFatFile::syncDir(), and ExFatFile::timestamp().
dirSeek()
int8_t ExFatPartition::dirSeek (DirPos_t * pos, uint32_t offset) private inherited
Definition at line 148 of file ExFatPartition.cpp.
{
   int8_t status;
   uint32_t tmp = (m_clusterMask & pos->position) + offset;
   pos->position += offset;
   tmp >>= bytesPerClusterShift();
   while (tmp--) {
     if (pos->isContiguous) {
       pos->cluster++;
     } else {
       status = fatGet(pos->cluster, &pos->cluster);
       if (status != 1) {
         return status;
       }
     }
   }
   return 1;
 }
References ExFatPartition::bytesPerClusterShift(), DirPos_t::cluster, ExFatPartition::fatGet(), DirPos_t::isContiguous, ExFatPartition::m_clusterMask, DirPos_t::position, and status.
Referenced by ExFatFile::dirCache().
dmpBitmap()
void ExFatPartition::dmpBitmap (print_t * pr) inherited
Definition at line 361 of file ExFatDbg.cpp.
{
   pr->println(F("bitmap:"));
   dmpSector(pr, m_clusterHeapStartSector);
 }
References ExFatPartition::dmpSector(), F, ExFatPartition::m_clusterHeapStartSector, and PrintBasic::println().
dmpCluster()
void ExFatPartition::dmpCluster (print_t * pr, uint32_t cluster, uint32_t offset, uint32_t count) inherited
Definition at line 366 of file ExFatDbg.cpp.
{
   uint32_t sector = clusterStartSector(cluster) + offset;
   for (uint32_t i = 0; i < count; i++) {
     pr->print(F("\nSector: "));
     pr->println(sector + i, HEX);
     dmpSector(pr, sector + i);
   }
 }
References ExFatPartition::clusterStartSector(), count, ExFatPartition::dmpSector(), F, HEX, PrintBasic::print(), and PrintBasic::println().
dmpFat()
void ExFatPartition::dmpFat (print_t * pr, uint32_t start, uint32_t count) inherited
Definition at line 376 of file ExFatDbg.cpp.
{
   uint32_t sector = m_fatStartSector + start;
   uint32_t cluster = 128*start;
   pr->println(F("FAT:"));
   for (uint32_t i = 0; i < count; i++) {
     uint8_t* cache = dataCachePrepare(sector + i, FsCache::CACHE_FOR_READ);
     if (!cache) {
       pr->println(F("cache read failed"));
       return;
     }
     uint32_t* fat = reinterpret_cast<uint32_t*>(cache);
     for (size_t k = 0; k < 128; k++) {
       if (0 == cluster%8) {
         if (k) {
           pr->println();
         }
         printHex(pr, cluster);
       }
       cluster++;
       pr->write(' ');
       printHex(pr, fat[k]);
     }
     pr->println();
   }
 }
References FsCache::CACHE_FOR_READ, count, ExFatPartition::dataCachePrepare(), F, ExFatPartition::m_fatStartSector, printHex(), PrintBasic::println(), and PrintBasic::write().
dmpSector()
void ExFatPartition::dmpSector (print_t * pr, uint32_t sector) inherited
Definition at line 402 of file ExFatDbg.cpp.
{
   uint8_t* cache = dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("dmpSector failed"));
     return;
   }
   for (uint16_t i = 0; i < m_bytesPerSector; i++) {
     if (i%32 == 0) {
       if (i) {
         pr->println();
       }
       printHex(pr, i);
     }
     pr->write(' ');
     printHex(pr, cache[i]);
   }
   pr->println();
 }
References FsCache::CACHE_FOR_READ, ExFatPartition::dataCachePrepare(), F, ExFatPartition::m_bytesPerSector, printHex(), PrintBasic::println(), and PrintBasic::write().
Referenced by ExFatPartition::dmpBitmap(), and ExFatPartition::dmpCluster().
errorHalt() [1/3]
void SdBase< ExFatVolume >::errorHalt (print_t * pr) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
Definition at line 122 of file SdFat.h.
{
     if (sdErrorCode()) {
       pr->print(F("SdError: 0X"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0X"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
     SysCall::halt();
   }
errorHalt() [2/3]
void SdBase< ExFatVolume >::errorHalt (print_t * pr, const __FlashStringHelper * msg) inline inherited
Print msg and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 150 of file SdFat.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorHalt(pr);
   }
errorHalt() [3/3]
void SdBase< ExFatVolume >::errorHalt (print_t * pr, const char * msg) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 139 of file SdFat.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorHalt(pr);
   }
errorPrint() [1/3]
void SdBase< ExFatVolume >::errorPrint (Print * pr, const __FlashStringHelper * msg) inline inherited
Print msg, any SD error code.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 244 of file SdFat.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorPrint(pr);
   }
errorPrint() [2/3]
void SdBase< ExFatVolume >::errorPrint (print_t * pr) inline inherited
Print SD errorCode and errorData.
Parameters
[in] pr Print destination.
Definition at line 217 of file SdFat.h.
{
     if (sdErrorCode()) {
       pr->print(F("SdError: 0X"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0X"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
   }
errorPrint() [3/3]
void SdBase< ExFatVolume >::errorPrint (print_t * pr, char const * msg) inline inherited
Print msg, any SD error code.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 233 of file SdFat.h.
{
     pr->print(F("error: "));
     pr->println(msg);
     errorPrint(pr);
   }
exists()
bool ExFatVolume::exists (const char * path) inline inherited
Test for the existence of a file.
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 80 of file ExFatVolume.h.
{
     ExFatFile tmp;
     return tmp.open(this, path, O_RDONLY);
   }
References O_RDONLY, and ExFatFile::open().
fatGet()
int8_t ExFatPartition::fatGet (uint32_t cluster, uint32_t * value) private inherited
Definition at line 167 of file ExFatPartition.cpp.
{
   uint8_t* cache;
   uint32_t next;
   uint32_t sector;
   if (cluster > (m_clusterCount + 1)) {
     DBG_FAIL_MACRO;
     return -1;
   }
   sector = m_fatStartSector + (cluster >> (m_bytesPerSectorShift - 2));
   cache = dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
   if (!cache) {
     return -1;
   }
   next = getLe32(cache + ((cluster << 2) & m_sectorMask));
   if (next == EXFAT_EOC) {
     return 0;
   }
   *value = next;
   return 1;
 }
References FsCache::CACHE_FOR_READ, ExFatPartition::dataCachePrepare(), DBG_FAIL_MACRO, EXFAT_EOC, getLe32(), ExFatPartition::m_bytesPerSectorShift, ExFatPartition::m_clusterCount, ExFatPartition::m_fatStartSector, and ExFatPartition::m_sectorMask.
Referenced by ExFatPartition::chainSize(), ExFatPartition::dirSeek(), ExFatPartition::freeChain(), ExFatPartition::printFat(), ExFatFile::read(), ExFatFile::seekSet(), ExFatFile::truncate(), and ExFatFile::write().
fatLength()
uint32_t ExFatPartition::fatLength () const inline inherited
Returns
the FAT length in sectors
Definition at line 83 of file ExFatPartition.h.
 {return m_fatLength;}
References ExFatPartition::m_fatLength.
fatPut()
bool ExFatPartition::fatPut (uint32_t cluster, uint32_t value) private inherited
Definition at line 190 of file ExFatPartition.cpp.
{
   uint32_t sector;
   uint8_t* cache;
   if (cluster < 2 || cluster > (m_clusterCount + 1)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   sector = m_fatStartSector + (cluster >> (m_bytesPerSectorShift - 2));
   cache = dataCachePrepare(sector, FsCache::CACHE_FOR_WRITE);
   if (!cache) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   setLe32(cache + ((cluster << 2) & m_sectorMask), value);
   return true;
  fail:
   return false;
 }
References FsCache::CACHE_FOR_WRITE, ExFatPartition::dataCachePrepare(), DBG_FAIL_MACRO, ExFatPartition::m_bytesPerSectorShift, ExFatPartition::m_clusterCount, ExFatPartition::m_fatStartSector, ExFatPartition::m_sectorMask, and setLe32().
Referenced by ExFatFile::addCluster(), ExFatPartition::freeChain(), and ExFatFile::truncate().
fatStartSector()
uint32_t ExFatPartition::fatStartSector () const inline inherited
Returns
the FAT start sector number.
Definition at line 85 of file ExFatPartition.h.
 {return m_fatStartSector;}
References ExFatPartition::m_fatStartSector.
fatType()
uint8_t ExFatPartition::fatType () const inline inherited
Returns
Type FAT_TYPE_EXFAT for exFAT partition or zero for error.
Definition at line 87 of file ExFatPartition.h.
 {return m_fatType;}
References ExFatPartition::m_fatType.
format()
bool SdExFat::format (print_t * pr = nullptr) inline
Format a SD card exFAT.
Parameters
[in] pr Optional Print information.
Returns
true for success or false for failure.
Definition at line 380 of file SdFat.h.
{
     ExFatFormatter fmt;
     uint8_t* cache = cacheClear();
     if (!cache) {
       return false;
     }
     return fmt.format(card(), cache, pr);
   }
References ExFatPartition::cacheClear(), SdBase< ExFatVolume >::card(), and ExFatFormatter::format().
freeChain()
bool ExFatPartition::freeChain (uint32_t cluster) private inherited
Definition at line 210 of file ExFatPartition.cpp.
{
   uint32_t next;
   uint32_t start = cluster;
   int8_t status;
   do {
     status = fatGet(cluster, &next);
     if (status < 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (!fatPut(cluster, 0)) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     if (status == 0 || (cluster + 1) != next) {
       if (!bitmapModify(start, cluster - start + 1, 0)) {
         DBG_FAIL_MACRO;
         goto fail;
       }
       start = next;
     }
     cluster = next;
   } while (status);
   return true;
  fail:
   return false;
 }
References ExFatPartition::bitmapModify(), DBG_FAIL_MACRO, ExFatPartition::fatGet(), ExFatPartition::fatPut(), and status.
Referenced by ExFatFile::remove(), and ExFatFile::truncate().
freeClusterCount()
uint32_t ExFatPartition::freeClusterCount () inherited
Returns
the free cluster count.
Definition at line 240 of file ExFatPartition.cpp.
{
   uint32_t nc = 0;
   uint32_t sector = m_clusterHeapStartSector;
   uint32_t usedCount = 0;
   uint8_t* cache;
   while (true) {
     cache = dataCachePrepare(sector++, FsCache::CACHE_FOR_READ);
     if (!cache) {
       return 0;
     }
     for (size_t i = 0; i < m_bytesPerSector; i++) {
       if (cache[i] == 0XFF) {
         usedCount+= 8;
       } else if (cache[i]) {
         for (uint8_t mask = 1; mask ; mask <<=1) {
           if ((mask & cache[i])) {
             usedCount++;
           }
         }
       }
       nc += 8;
       if (nc >= m_clusterCount) {
         return m_clusterCount - usedCount;
       }
     }
   }
 }
References FsCache::CACHE_FOR_READ, ExFatPartition::dataCachePrepare(), ExFatPartition::m_bytesPerSector, ExFatPartition::m_clusterCount, and ExFatPartition::m_clusterHeapStartSector.
init()
bool ExFatPartition::init (BlockDevice * dev, uint8_t part) inherited
Initialize a exFAT partition.
Parameters
[in] dev The blockDevice for the partition.
[in] part The partition to be used. Legal values for part are 1-4 to use the corresponding partition on a device formatted with a MBR, Master Boot Record, or zero if the device is formatted as a super floppy with the FAT boot sector in sector zero.
Returns
true for success or false for failure.
Definition at line 269 of file ExFatPartition.cpp.
{
   uint32_t volStart = 0;
   uint8_t* cache;
   pbs_t* pbs;
   BpbExFat_t* bpb;
   MbrSector_t* mbr;
   MbrPart_t* mp;
   m_fatType = 0;
   m_blockDev = dev;
   cacheInit(m_blockDev);
   cache = dataCachePrepare(0, FsCache::CACHE_FOR_READ);
   if (part > 4 || !cache) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   if (part >= 1) {
     mbr = reinterpret_cast<MbrSector_t*>(cache);
     mp = &mbr->part[part - 1];
     if ((mp->boot != 0 && mp->boot != 0X80) || mp->type == 0) {
       DBG_FAIL_MACRO;
       goto fail;
     }
     volStart = getLe32(mp->relativeSectors);
     cache = dataCachePrepare(volStart, FsCache::CACHE_FOR_READ);
     if (!cache) {
       DBG_FAIL_MACRO;
       goto fail;
     }
   }
   pbs = reinterpret_cast<pbs_t*>(cache);
   if (strncmp(pbs->oemName, "EXFAT", 5)) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   bpb = reinterpret_cast<BpbExFat_t*>(pbs->bpb);
   if (bpb->bytesPerSectorShift != m_bytesPerSectorShift) {
     DBG_FAIL_MACRO;
     goto fail;
   }
   m_fatStartSector = volStart + getLe32(bpb->fatOffset);
   m_fatLength = getLe32(bpb->fatLength);
   m_clusterHeapStartSector = volStart + getLe32(bpb->clusterHeapOffset);
   m_clusterCount = getLe32(bpb->clusterCount);
   m_rootDirectoryCluster = getLe32(bpb->rootDirectoryCluster);
   m_sectorsPerClusterShift = bpb->sectorsPerClusterShift;
   m_bytesPerCluster = 1UL << (m_bytesPerSectorShift + m_sectorsPerClusterShift);
   m_clusterMask = m_bytesPerCluster - 1;
   // Set m_bitmapStart to first free cluster.
   m_bitmapStart = 0;
   bitmapFind(0, 1);
   m_fatType = FAT_TYPE_EXFAT;
   return true;
  fail:
   return false;
 }
References ExFatPartition::bitmapFind(), mbrPartition::boot, partitionBootSector::bpb, biosParameterBlockExFat::bytesPerSectorShift, FsCache::CACHE_FOR_READ, ExFatPartition::cacheInit(), biosParameterBlockExFat::clusterCount, biosParameterBlockExFat::clusterHeapOffset, ExFatPartition::dataCachePrepare(), DBG_FAIL_MACRO, FAT_TYPE_EXFAT, biosParameterBlockExFat::fatLength, biosParameterBlockExFat::fatOffset, getLe32(), ExFatPartition::m_bitmapStart, ExFatPartition::m_blockDev, ExFatPartition::m_bytesPerCluster, ExFatPartition::m_bytesPerSectorShift, ExFatPartition::m_clusterCount, ExFatPartition::m_clusterHeapStartSector, ExFatPartition::m_clusterMask, ExFatPartition::m_fatLength, ExFatPartition::m_fatStartSector, ExFatPartition::m_fatType, ExFatPartition::m_rootDirectoryCluster, ExFatPartition::m_sectorsPerClusterShift, partitionBootSector::oemName, masterBootRecordSector::part, mbrPartition::relativeSectors, biosParameterBlockExFat::rootDirectoryCluster, biosParameterBlockExFat::sectorsPerClusterShift, and mbrPartition::type.
Referenced by ExFatVolume::begin().
initErrorHalt() [1/3]
void SdBase< ExFatVolume >::initErrorHalt (Print * pr, const __FlashStringHelper * msg) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 180 of file SdFat.h.
{
     pr->println(msg);
     initErrorHalt(pr);
   }
initErrorHalt() [2/3]
void SdBase< ExFatVolume >::initErrorHalt (print_t * pr) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
Definition at line 160 of file SdFat.h.
{
     initErrorPrint(pr);
     SysCall::halt();
   }
initErrorHalt() [3/3]
void SdBase< ExFatVolume >::initErrorHalt (print_t * pr, const char * msg) inline inherited
Print error info and halt.
Parameters
[in] pr Print destination.
[in] msg Message to print.
Definition at line 170 of file SdFat.h.
{
     pr->println(msg);
     initErrorHalt(pr);
   }
initErrorPrint()
void SdBase< ExFatVolume >::initErrorPrint (Print * pr) inline inherited
Print error details after begin() fails.
Parameters
[in] pr Print destination.
Definition at line 189 of file SdFat.h.
{
     pr->println(F("begin() failed"));
     if (sdErrorCode()) {
       pr->println(F("Do not reformat the SD."));
       if (sdErrorCode() == SD_CARD_ERROR_CMD0) {
         pr->println(F("No card, wrong chip select pin, or wiring error?"));
       }
     }
     errorPrint(pr);
   }
isBusy()
bool ExFatPartition::isBusy () inline inherited
Check for BlockDevice busy.
Returns
true if busy else false.
Definition at line 105 of file ExFatPartition.h.
 {return m_blockDev->isBusy();}
References SharedSpiCard::isBusy(), and ExFatPartition::m_blockDev.
Referenced by ExFatFile::isBusy().
ls() [1/2]
bool ExFatVolume::ls (print_t * pr, const char * path, uint8_t flags) inline inherited
List the contents of a directory.
Parameters
[in] pr Print stream for list.
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 118 of file ExFatVolume.h.
{
     ExFatFile dir;
     return dir.open(this, path, O_RDONLY) && dir.ls(pr, flags);
   }
References ExFatFile::ls(), O_RDONLY, and ExFatFile::open().
ls() [2/2]
bool ExFatVolume::ls (print_t * pr, uint8_t flags = 0) inline inherited
List the directory contents of the root directory.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Returns
true for success or false for failure.
Definition at line 99 of file ExFatVolume.h.
{
     return m_vwd.ls(pr, flags);
   }
References ExFatFile::ls(), and ExFatVolume::m_vwd.
mkdir()
bool ExFatVolume::mkdir (const char * path, bool pFlag = true) inline inherited
Make a subdirectory in the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
true for success or false for failure.
Definition at line 130 of file ExFatVolume.h.
{
     ExFatFile sub;
     return sub.mkdir(vwd(), path, pFlag);
   }
References ExFatFile::mkdir(), and ExFatVolume::vwd().
open()
ExFile ExFatVolume::open (const char * path, oflag_t oflag = O_RDONLY) inline inherited
open a file
Parameters
[in] path location of file to be opened.
[in] oflag open flags.
Returns
a ExFile object.
Definition at line 140 of file ExFatVolume.h.
{
     ExFile tmpFile;
     tmpFile.open(this, path, oflag);
     return tmpFile;
   }
References ExFatFile::open().
printDir()
bool ExFatPartition::printDir (print_t * pr, ExFatFile * file) inherited
Definition at line 421 of file ExFatDbg.cpp.
{
   DirGeneric_t* dir = nullptr;
   DirFile_t* dirFile;
   DirStream_t* dirStream;
   DirName_t* dirName;
   uint16_t calcHash = 0;
   uint16_t nameHash = 0;
   uint16_t setChecksum = 0;
   uint16_t calcChecksum = 0;
   uint8_t  nameLength = 0;
   uint8_t  setCount = 0;
   uint8_t  nUnicode;
 #define RAW_ROOT
 #ifndef RAW_ROOT
   while (1) {
     uint8_t buf[FS_DIR_SIZE];
     if (file->read(buf, FS_DIR_SIZE) != FS_DIR_SIZE) {
       break;
     }
     dir = reinterpret_cast<DirGeneric_t*>(buf);
 #else  // RAW_ROOT
   (void)file;
   uint32_t nDir = 1UL << (m_sectorsPerClusterShift + 4);
   uint32_t sector = clusterStartSector(m_rootDirectoryCluster);
   for (uint32_t iDir = 0; iDir < nDir; iDir++) {
     size_t i = iDir%16;
     if (i == 0) {
       uint8_t* cache = dataCachePrepare(sector++, FsCache::CACHE_FOR_READ);
       if (!cache) {
         return false;
       }
       dir = reinterpret_cast<DirGeneric_t*>(cache);
     } else {
       dir++;
     }
 #endif  // RAW_ROOT
     if (dir->type == 0) {
       break;
     }
     pr->println();
     switch (dir->type) {
       case EXFAT_TYPE_BITMAP:
         printDirBitmap(pr, reinterpret_cast<DirBitmap_t*>(dir));
         break;
       case EXFAT_TYPE_UPCASE:
         printDirUpcase(pr, reinterpret_cast<DirUpcase_t*>(dir));
         break;
       case EXFAT_TYPE_LABEL:
         printDirLabel(pr, reinterpret_cast<DirLabel_t*>(dir));
         break;
       case EXFAT_TYPE_FILE:
         dirFile = reinterpret_cast<DirFile_t*>(dir);
         printDirFile(pr, dirFile);
         setCount = dirFile->setCount;
         setChecksum = getLe16(dirFile->setChecksum);
         calcChecksum = exFatDirChecksum(dir, 0);
         break;
       case EXFAT_TYPE_STREAM:
         dirStream = reinterpret_cast<DirStream_t*>(dir);
         printDirStream(pr, dirStream);
         nameLength = dirStream->nameLength;
         nameHash = getLe16(dirStream->nameHash);
         calcChecksum = exFatDirChecksum(dir, calcChecksum);
         setCount--;
         calcHash = 0;
         break;
        case EXFAT_TYPE_NAME:
         dirName = reinterpret_cast<DirName_t*>(dir);
         printDirName(pr, dirName);
         calcChecksum = exFatDirChecksum(dir, calcChecksum);
         nUnicode = nameLength > 15 ? 15 : nameLength;
         calcHash = hashDir(dirName, calcHash);
         nameLength -= nUnicode;
         setCount--;
         if (nameLength == 0  || setCount == 0) {
           pr->print(F("setChecksum: 0x"));
           pr->print(setChecksum, HEX);
           if (setChecksum != calcChecksum) {
             pr->print(F(" != calcChecksum: 0x"));
           } else {
             pr->print(F(" == calcChecksum: 0x"));
           }
           pr->println(calcChecksum, HEX);
           pr->print(F("nameHash: 0x"));
           pr->print(nameHash, HEX);
           if (nameHash != calcHash) {
             pr->print(F(" != calcHash: 0x"));
           } else {
             pr->print(F(" == calcHash: 0x"));
           }
           pr->println(calcHash, HEX);
         }
         break;
       default:
         if (dir->type & 0x80) {
           pr->print(F("Unknown dirType: 0x"));
         } else {
           pr->print(F("Unused dirType: 0x"));
         }
         pr->println(dir->type, HEX);
         dmpDirData(pr, dir);
         break;
     }
   }
   pr->println(F("Done"));
   return true;
 }
References buf, FsCache::CACHE_FOR_READ, ExFatPartition::clusterStartSector(), ExFatPartition::dataCachePrepare(), dmpDirData(), EXFAT_TYPE_BITMAP, EXFAT_TYPE_FILE, EXFAT_TYPE_LABEL, EXFAT_TYPE_NAME, EXFAT_TYPE_STREAM, EXFAT_TYPE_UPCASE, exFatDirChecksum(), F, FS_DIR_SIZE, getLe16(), hashDir(), HEX, ExFatPartition::m_rootDirectoryCluster, ExFatPartition::m_sectorsPerClusterShift, DirStream_t::nameHash, DirStream_t::nameLength, PrintBasic::print(), printDirBitmap(), printDirFile(), printDirLabel(), printDirName(), printDirStream(), printDirUpcase(), PrintBasic::println(), ExFatFile::read(), DirFile_t::setChecksum, DirFile_t::setCount, and DirGeneric_t::type.
printFat()
void ExFatPartition::printFat (print_t * pr) inherited
Definition at line 537 of file ExFatDbg.cpp.
{
   uint32_t next;
   int8_t status;
   pr->println(F("FAT:"));
   for (uint32_t cluster = 0; cluster < 16; cluster++) {
     status = fatGet(cluster, &next);
     pr->print(cluster, HEX);
     pr->write(' ');
     if (status == 0) {
       next = EXFAT_EOC;
     }
     pr->println(next, HEX);
   }
 }
References EXFAT_EOC, F, ExFatPartition::fatGet(), HEX, PrintBasic::print(), PrintBasic::println(), status, and PrintBasic::write().
printFatType()
void SdBase< ExFatVolume >::printFatType (print_t * pr) inline inherited
Print volume FAT/exFAT type.
Parameters
[in] pr Print destination.
Definition at line 204 of file SdFat.h.
{
     if (Vol::fatType() == FAT_TYPE_EXFAT) {
       pr->print(F("exFAT"));
     } else {
       pr->print(F("FAT"));
       pr->print(Vol::fatType());
     }
   }
printSdError()
void SdBase< ExFatVolume >::printSdError (print_t * pr) inline inherited
Print error info and return.
Parameters
[in] pr Print destination.
Definition at line 254 of file SdFat.h.
{
     if (sdErrorCode()) {
       if (sdErrorCode() == SD_CARD_ERROR_CMD0) {
         pr->println(F("No card, wrong chip select pin, or wiring error?"));
       }
       pr->print(F("SD error: "));
       printSdErrorSymbol(pr, sdErrorCode());
       pr->print(F(" = 0x"));
       pr->print(sdErrorCode(), HEX);
       pr->print(F(",0x"));
       pr->println(sdErrorData(), HEX);
     } else if (!Vol::fatType()) {
       pr->println(F("Check SD format."));
     }
   }
printUpcase()
void ExFatPartition::printUpcase (print_t * pr) inherited
Definition at line 552 of file ExFatDbg.cpp.
{
   uint8_t* upcase = nullptr;
   uint32_t sector;
   uint32_t size = 0;
   uint32_t checksum = 0;
   DirUpcase_t* dir;
   sector = clusterStartSector(m_rootDirectoryCluster);
   upcase = dataCachePrepare(sector, FsCache::CACHE_FOR_READ);
   dir = reinterpret_cast<DirUpcase_t*>(upcase);
   if (!dir) {
     pr->println(F("read root dir failed"));
     return;
   }
   for (size_t i = 0; i < 16; i++) {
     if (dir[i].type == EXFAT_TYPE_UPCASE) {
       sector = clusterStartSector(getLe32(dir[i].firstCluster));
       size = getLe64(dir[i].size);
       break;
     }
   }
   if (!size) {
     pr->println(F("upcase not found"));
     return;
   }
   for (uint16_t i = 0; i < size/2; i++) {
     if ((i%256) == 0) {
       upcase = dataCachePrepare(sector++, FsCache::CACHE_FOR_READ);
       if (!upcase) {
         pr->println(F("read upcase failed"));
         return;
       }
     }
     if (i%16 == 0) {
       pr->println();
       printHex(pr, i);
     }
     pr->write(' ');
     uint16_t uc = getLe16(&upcase[2*(i & 0XFF)]);
     printHex(pr, uc);
     checksum = upcaseChecksum(uc, checksum);
   }
   pr->println();
   pr->print(F("checksum: "));
   printHex(pr, checksum);
   pr->println();
 }
References FsCache::CACHE_FOR_READ, ExFatPartition::clusterStartSector(), ExFatPartition::dataCachePrepare(), EXFAT_TYPE_UPCASE, F, getLe16(), getLe32(), getLe64(), ExFatPartition::m_rootDirectoryCluster, PrintBasic::print(), printHex(), PrintBasic::println(), upcaseChecksum(), and PrintBasic::write().
printVolInfo()
bool ExFatPartition::printVolInfo (print_t * pr) inherited
Definition at line 599 of file ExFatDbg.cpp.
{
   uint8_t* cache = dataCachePrepare(0, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read mbr failed"));
     return false;
   }
   MbrSector_t* mbr = reinterpret_cast<MbrSector_t*>(cache);
   printMbr(pr, mbr);
   uint32_t volStart = getLe32(mbr->part->relativeSectors);
   uint32_t volSize = getLe32(mbr->part->totalSectors);
   if (volSize == 0) {
     pr->print(F("bad partition size"));
     return false;
   }
   cache = dataCachePrepare(volStart, FsCache::CACHE_FOR_READ);
   if (!cache) {
     pr->println(F("read pbs failed"));
     return false;
   }
   printExFatBoot(pr, reinterpret_cast<pbs_t*>(cache));
   return true;
 }
References FsCache::CACHE_FOR_READ, ExFatPartition::dataCachePrepare(), F, getLe32(), masterBootRecordSector::part, PrintBasic::print(), printExFatBoot(), PrintBasic::println(), printMbr(), mbrPartition::relativeSectors, and mbrPartition::totalSectors.
readSector()
bool ExFatPartition::readSector (uint32_t sector, uint8_t * dst) inline private inherited
Definition at line 193 of file ExFatPartition.h.
{
     return m_blockDev->readSector(sector, dst);
   }
References dst, ExFatPartition::m_blockDev, and SharedSpiCard::readSector().
remove()
bool ExFatVolume::remove (const char * path) inline inherited
Remove a file from the volume root directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
true for success or false for failure.
Definition at line 151 of file ExFatVolume.h.
{
     ExFatFile tmp;
     return tmp.open(this, path, O_WRONLY) && tmp.remove();
   }
References O_WRONLY, ExFatFile::open(), and ExFatFile::remove().
rename()
bool ExFatVolume::rename (const char * oldPath, const char * newPath) inline inherited
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
true for success or false for failure.
Definition at line 169 of file ExFatVolume.h.
{
     ExFatFile file;
     return file.open(vwd(), oldPath, O_RDONLY) && file.rename(vwd(), newPath);
   }
References O_RDONLY, ExFatFile::open(), ExFatFile::rename(), and ExFatVolume::vwd().
rmdir()
bool ExFatVolume::rmdir (const char * path) inline inherited
Remove a subdirectory from the volume's working directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
true for success or false for failure.
Definition at line 181 of file ExFatVolume.h.
{
     ExFatFile sub;
     return sub.open(this, path, O_RDONLY) && sub.rmdir();
   }
References O_RDONLY, ExFatFile::open(), and ExFatFile::rmdir().
rootDirectoryCluster()
uint32_t ExFatPartition::rootDirectoryCluster () const inline inherited
Returns
the root directory start cluster number.
Definition at line 107 of file ExFatPartition.h.
 {return m_rootDirectoryCluster;}
References ExFatPartition::m_rootDirectoryCluster.
Referenced by ExFatFile::read(), and ExFatFile::seekSet().
rootLength()
uint32_t ExFatPartition::rootLength () inherited
Returns
the root directory length.
Definition at line 327 of file ExFatPartition.cpp.
{
   uint32_t nc = chainSize(m_rootDirectoryCluster);
   return nc << bytesPerClusterShift();
 }
References ExFatPartition::bytesPerClusterShift(), ExFatPartition::chainSize(), and ExFatPartition::m_rootDirectoryCluster.
Referenced by ExFatFile::addDirCluster().
sdErrorCode()
uint8_t SdBase< ExFatVolume >::sdErrorCode () inline inherited
Returns
SD card error code.
Definition at line 271 of file SdFat.h.
{
     if (m_card) {
       return m_card->errorCode();
     }
     return SD_CARD_ERROR_INVALID_CARD_CONFIG;
   }
sdErrorData()
uint8_t SdBase< ExFatVolume >::sdErrorData () inline inherited
Returns
SD card error data.
Definition at line 279 of file SdFat.h.
 {return m_card ? m_card->errorData() : 0;}
sectorMask()
uint16_t ExFatPartition::sectorMask () const inline private inherited
Definition at line 177 of file ExFatPartition.h.
 {return m_sectorMask;}
References ExFatPartition::m_sectorMask.
Referenced by ExFatFile::read(), and ExFatFile::write().
sectorsPerCluster()
uint32_t ExFatPartition::sectorsPerCluster () const inline inherited
Returns
the number of sectors in a cluster.
Definition at line 111 of file ExFatPartition.h.
 {return 1UL << m_sectorsPerClusterShift;}
References ExFatPartition::m_sectorsPerClusterShift.
Referenced by ExFatFile::addDirCluster(), ExFatFile::read(), and ExFatFile::write().
sectorsPerClusterShift()
uint8_t ExFatPartition::sectorsPerClusterShift () const inline inherited
Returns
the power of two for sectors per cluster.
Definition at line 116 of file ExFatPartition.h.
 {return m_sectorsPerClusterShift;}
syncDevice()
bool ExFatPartition::syncDevice () inline private inherited
Definition at line 178 of file ExFatPartition.h.
                     {
     return m_blockDev->syncDevice();
   }
References ExFatPartition::m_blockDev, and SharedSpiCard::syncDevice().
Referenced by ExFatPartition::cacheSync().
truncate()
bool ExFatVolume::truncate (const char * path, uint64_t length) inline inherited
Truncate a file to a specified length. The current file position will be at the new EOF.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
[in] length The desired length for the file.
Returns
true for success or false for failure.
Definition at line 193 of file ExFatVolume.h.
{
     ExFatFile file;
     if (!file.open(this, path, O_WRONLY)) {
       return false;
     }
     return file.truncate(length);
   }
References O_WRONLY, ExFatFile::open(), and ExFatFile::truncate().
vol()
ExFatVolume * SdBase< ExFatVolume >::vol () inline inherited
Returns
pointer to base volume
Definition at line 282 of file SdFat.h.
 {return reinterpret_cast<Vol*>(this);}
volumeBegin()
bool SdBase< ExFatVolume >::volumeBegin () inline inherited
Initialize file system after call to cardBegin.
Returns
true for success or false for failure.
Definition at line 288 of file SdFat.h.
                      {
      return Vol::begin(m_card);
   }
vwd()
ExFatFile* ExFatVolume::vwd () inline private inherited
Definition at line 332 of file ExFatVolume.h.
 {return &m_vwd;}
References ExFatVolume::m_vwd.
Referenced by ExFatVolume::chdir(), ExFatVolume::mkdir(), ExFatFile::open(), ExFatFile::rename(), and ExFatVolume::rename().
writeSector()
bool ExFatPartition::writeSector (uint32_t sector, const uint8_t * src) inline private inherited
Definition at line 196 of file ExFatPartition.h.
{
     return m_blockDev->writeSector(sector, src);
   }
References ExFatPartition::m_blockDev, and SharedSpiCard::writeSector().
Member Data Documentation
ExFatFile
friend ExFatVolume::ExFatFile private inherited
Definition at line 330 of file ExFatVolume.h.
m_bitmapStart
uint32_t ExFatPartition::m_bitmapStart private inherited
Definition at line 208 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapFind(), ExFatPartition::bitmapModify(), and ExFatPartition::init().
m_blockDev
BlockDevice* ExFatPartition::m_blockDev private inherited
Definition at line 216 of file ExFatPartition.h.
Referenced by ExFatPartition::init(), ExFatPartition::isBusy(), ExFatPartition::readSector(), ExFatPartition::syncDevice(), and ExFatPartition::writeSector().
m_bytesPerCluster
uint32_t ExFatPartition::m_bytesPerCluster private inherited
Definition at line 215 of file ExFatPartition.h.
Referenced by ExFatPartition::bytesPerCluster(), and ExFatPartition::init().
m_bytesPerSector
const uint16_t ExFatPartition::m_bytesPerSector = 1 << m_bytesPerSectorShift static private inherited
Definition at line 201 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapModify(), ExFatPartition::bytesPerSector(), ExFatPartition::dmpSector(), and ExFatPartition::freeClusterCount().
m_bytesPerSectorShift
const uint8_t ExFatPartition::m_bytesPerSectorShift = 9 static private inherited
Definition at line 200 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapFind(), ExFatPartition::bitmapModify(), ExFatPartition::bytesPerClusterShift(), ExFatPartition::bytesPerSectorShift(), ExFatPartition::dirCache(), ExFatPartition::fatGet(), ExFatPartition::fatPut(), and ExFatPartition::init().
m_card
SdCard* SdBase< ExFatVolume >::m_card private inherited
Definition at line 344 of file SdFat.h.
m_cardFactory
SdCardFactory SdBase< ExFatVolume >::m_cardFactory private inherited
Definition at line 345 of file SdFat.h.
m_clusterCount
uint32_t ExFatPartition::m_clusterCount private inherited
Definition at line 212 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapFind(), ExFatPartition::bitmapModify(), ExFatPartition::clusterCount(), ExFatPartition::fatGet(), ExFatPartition::fatPut(), ExFatPartition::freeClusterCount(), and ExFatPartition::init().
m_clusterHeapStartSector
uint32_t ExFatPartition::m_clusterHeapStartSector private inherited
Definition at line 211 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapFind(), ExFatPartition::bitmapModify(), ExFatPartition::clusterHeapStartSector(), ExFatPartition::clusterStartSector(), ExFatPartition::dmpBitmap(), ExFatPartition::freeClusterCount(), and ExFatPartition::init().
m_clusterMask
uint32_t ExFatPartition::m_clusterMask private inherited
Definition at line 214 of file ExFatPartition.h.
Referenced by ExFatPartition::clusterMask(), ExFatPartition::dirCache(), ExFatPartition::dirSeek(), and ExFatPartition::init().
m_cwv
ExFatVolume * ExFatVolume::m_cwv = nullptr static private inherited
Definition at line 333 of file ExFatVolume.h.
Referenced by ExFatVolume::begin(), ExFatVolume::chvol(), and ExFatVolume::cwv().
m_dataCache
FsCache ExFatPartition::m_dataCache private inherited
Definition at line 207 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapCachePrepare(), ExFatPartition::cacheClear(), ExFatPartition::cacheInit(), ExFatPartition::cacheSafeRead(), ExFatPartition::cacheSafeWrite(), ExFatPartition::cacheSync(), ExFatPartition::dataCacheDirty(), ExFatPartition::dataCacheInvalidate(), ExFatPartition::dataCachePrepare(), ExFatPartition::dataCacheSector(), and ExFatPartition::dataCacheSync().
m_fatLength
uint32_t ExFatPartition::m_fatLength private inherited
Definition at line 210 of file ExFatPartition.h.
Referenced by ExFatPartition::fatLength(), and ExFatPartition::init().
m_fatStartSector
uint32_t ExFatPartition::m_fatStartSector private inherited
Definition at line 209 of file ExFatPartition.h.
Referenced by ExFatPartition::dmpFat(), ExFatPartition::fatGet(), ExFatPartition::fatPut(), ExFatPartition::fatStartSector(), and ExFatPartition::init().
m_fatType
uint8_t ExFatPartition::m_fatType = 0 private inherited
Definition at line 217 of file ExFatPartition.h.
Referenced by ExFatPartition::fatType(), and ExFatPartition::init().
m_rootDirectoryCluster
uint32_t ExFatPartition::m_rootDirectoryCluster private inherited
Definition at line 213 of file ExFatPartition.h.
Referenced by ExFatPartition::checkUpcase(), ExFatPartition::init(), ExFatPartition::printDir(), ExFatPartition::printUpcase(), ExFatPartition::rootDirectoryCluster(), and ExFatPartition::rootLength().
m_sectorMask
const uint16_t ExFatPartition::m_sectorMask = m_bytesPerSector - 1 static private inherited
Definition at line 202 of file ExFatPartition.h.
Referenced by ExFatPartition::bitmapModify(), ExFatPartition::dirCache(), ExFatPartition::fatGet(), ExFatPartition::fatPut(), and ExFatPartition::sectorMask().
m_sectorsPerClusterShift
uint8_t ExFatPartition::m_sectorsPerClusterShift private inherited
Definition at line 218 of file ExFatPartition.h.
Referenced by ExFatPartition::bytesPerClusterShift(), ExFatPartition::clusterStartSector(), ExFatPartition::init(), ExFatPartition::printDir(), and ExFatPartition::sectorsPerCluster().
m_vwd
ExFatFile ExFatVolume::m_vwd private inherited
Definition at line 334 of file ExFatVolume.h.
Referenced by ExFatVolume::chdir(), ExFatVolume::ls(), and ExFatVolume::vwd().
The documentation for this class was generated from the following file:
SdFat.h