ERIS CORE: SdSpiCard Class Reference
SdSpiCard Class Reference
Raw access to SD and SDHC flash memory cards via SPI protocol.
#include <SdSpiCard.h>
Public Member Functions
SdSpiCard ()
bool begin (SdSpiConfig spiConfig)
uint32_t cardSize () __attribute__((deprecated))
void dbgClearStats ()
void dbgPrintStats ()
bool erase (uint32_t firstSector, uint32_t lastSector)
bool eraseSingleSectorEnable ()
void error (uint8_t code)
uint8_t errorCode () const
uint32_t errorData () const
bool isBusy ()
bool readCID (cid_t *cid)
bool readCSD (csd_t *csd)
bool readData (uint8_t *dst)
bool readOCR (uint32_t *ocr)
bool readSector (uint32_t sector, uint8_t *dst)
bool readSectors (uint32_t sector, uint8_t *dst, size_t ns)
bool readSingle (uint32_t sector, uint8_t *dst)
bool readStart (uint32_t sector)
bool readStatus (uint8_t *status)
bool readStop ()
uint32_t sectorCount ()
void spiStart ()
void spiStop ()
bool syncDevice ()
uint8_t type () const
bool writeData (const uint8_t *src)
bool writeSector (uint32_t sector, const uint8_t *src)
bool writeSectors (uint32_t sector, const uint8_t *src, size_t ns)
bool writeSingle (uint32_t sector, const uint8_t *src)
bool writeStart (uint32_t sector)
bool writeStart (uint32_t sector, uint32_t eraseCount)
bool writeStop ()
Detailed Description
Raw access to SD and SDHC flash memory cards via SPI protocol.
Definition at line 46 of file SdSpiCard.h.
Constructor & Destructor Documentation
SdSpiCard()
SdSpiCard::SdSpiCard () inline
Construct an instance of SdSpiCard.
Definition at line 50 of file SdSpiCard.h.
 : m_errorCode(SD_CARD_ERROR_INIT_NOT_CALLED), m_type(0) {}
Member Function Documentation
begin()
bool SdSpiCard::begin (SdSpiConfig spiConfig)
Initialize the SD card.
Parameters
[in] spi SPI driver for card.
[in] spiConfig SPI card configuration.
Returns
true for success or false for failure.
Definition at line 223 of file SdSpiCard.cpp.
{
   SdMillis_t t0 = SysCall::curTimeMS();
   m_errorCode = SD_CARD_ERROR_NONE;
   m_type = 0;
   m_csPin = spiConfig.csPin;
 #if SPI_DRIVER_SELECT >= 2
   m_spiDriverPtr = spiConfig.spiPort;
   if (!m_spiDriverPtr) {
     error(SD_CARD_ERROR_INVALID_CARD_CONFIG);
     goto fail;
   }
 #endif  // SPI_DRIVER_SELECT
   sdCsInit(m_csPin);
   spiUnselect();
   spiSetSckSpeed(1000UL*SD_MAX_INIT_RATE_KHZ);
   spiBegin(spiConfig);
   uint32_t arg;
 #if ENABLE_DEDICATED_SPI
   m_sharedSpi = !(spiConfig.options & DEDICATED_SPI);
   m_spiActive = false;
   m_curState = IDLE_STATE;
 #else  // ENABLE_DEDICATED_SPI
   if (spiConfig.options & DEDICATED_SPI) {
     error(SD_CARD_ERROR_INVALID_CARD_CONFIG);
     goto fail;
   }
 #endif  // ENABLE_DEDICATED_SPI
   spiStart();
   // must supply min of 74 clock cycles with CS high.
   spiUnselect();
   for (uint8_t i = 0; i < 10; i++) {
     spiSend(0XFF);
   }
   spiSelect();
   DBG_BEGIN_TIME(DBG_CMD0_TIME);
   // command to go idle in SPI mode
   for (uint8_t i = 1;; i++) {
     DBG_EVENT_COUNT(DBG_CMD0_COUNT);
     if (cardCommand(CMD0, 0) == R1_IDLE_STATE) {
       break;
     }
     if (i == SD_CMD0_RETRY) {
       error(SD_CARD_ERROR_CMD0);
       goto fail;
     }
     // stop multi-block write
     spiSend(STOP_TRAN_TOKEN);
     // finish block transfer
     for (int i = 0; i < 520; i++) {
       spiReceive();
     }
   }
   DBG_END_TIME(DBG_CMD0_TIME);
 #if USE_SD_CRC
   if (cardCommand(CMD59, 1) != R1_IDLE_STATE) {
     error(SD_CARD_ERROR_CMD59);
     goto fail;
   }
 #endif  // USE_SD_CRC
   // check SD version
   if (!(cardCommand(CMD8, 0x1AA) & R1_ILLEGAL_COMMAND)) {
     type(SD_CARD_TYPE_SD2);
     for (uint8_t i = 0; i < 4; i++) {
       m_status = spiReceive();
     }
     if (m_status != 0XAA) {
       error(SD_CARD_ERROR_CMD8);
       goto fail;
     }
   } else {
     type(SD_CARD_TYPE_SD1);
   }
   // initialize card and send host supports SDHC if SD2
   arg = type() == SD_CARD_TYPE_SD2 ? 0X40000000 : 0;
   DBG_BEGIN_TIME(DBG_ACMD41_TIME);
   while (cardAcmd(ACMD41, arg) != R1_READY_STATE) {
     DBG_EVENT_COUNT(DBG_ACMD41_COUNT);
     // check for timeout
     if (isTimedOut(t0, SD_INIT_TIMEOUT)) {
       error(SD_CARD_ERROR_ACMD41);
       goto fail;
     }
   }
   DBG_END_TIME(DBG_ACMD41_TIME);
   // if SD2 read OCR register to check for SDHC card
   if (type() == SD_CARD_TYPE_SD2) {
     if (cardCommand(CMD58, 0)) {
       error(SD_CARD_ERROR_CMD58);
       goto fail;
     }
     if ((spiReceive() & 0XC0) == 0XC0) {
       type(SD_CARD_TYPE_SDHC);
     }
     // Discard rest of ocr - contains allowed voltage range.
     for (uint8_t i = 0; i < 3; i++) {
       spiReceive();
     }
   }
   spiStop();
   spiSetSckSpeed(spiConfig.maxSck);
   return true;
 fail:
   spiStop();
   return false;
 }
References ACMD41, CMD0, CMD58, CMD59, CMD8, SdSpiConfig::csPin, SysCall::curTimeMS(), DBG_BEGIN_TIME, DBG_END_TIME, DBG_EVENT_COUNT, DEDICATED_SPI, error(), SdSpiConfig::maxSck, SdSpiConfig::options, R1_IDLE_STATE, R1_ILLEGAL_COMMAND, R1_READY_STATE, SD_CARD_TYPE_SD1, SD_CARD_TYPE_SD2, SD_CARD_TYPE_SDHC, SD_CMD0_RETRY, SD_INIT_TIMEOUT, SD_MAX_INIT_RATE_KHZ, sdCsInit(), SdSpiConfig::spiPort, spiStart(), spiStop(), STOP_TRAN_TOKEN, and type().
Referenced by SdCardFactory::newCard().
cardSize()
uint32_t SdSpiCard::cardSize () inline
Definition at line 70 of file SdSpiCard.h.
 {return sectorCount();}
References sectorCount().
dbgClearStats()
void SdSpiCard::dbgClearStats ()
Clear debug stats.
Definition at line 384 of file SdSpiCard.cpp.
 {::dbgClearStats();}
dbgPrintStats()
void SdSpiCard::dbgPrintStats ()
Print debug stats.
Definition at line 386 of file SdSpiCard.cpp.
 {::dbgPrintStats();}
erase()
bool SdSpiCard::erase (uint32_t firstSector, uint32_t lastSector)
Erase a range of sectors.
Parameters
[in] firstSector The address of the first sector in the range.
[in] lastSector The address of the last sector in the range.
Note
This function requests the SD card to do a flash erase for a range of sectors. The data on the card after an erase operation is either 0 or 1, depends on the card vendor. The card must support single sector erase.
Returns
true for success or false for failure.
Definition at line 388 of file SdSpiCard.cpp.
{
   csd_t csd;
   if (!readCSD(&csd)) {
     goto fail;
   }
   // check for single sector erase
   if (!csd.v1.erase_blk_en) {
     // erase size mask
     uint8_t m = (csd.v1.sector_size_high << 1) | csd.v1.sector_size_low;
     if ((firstSector & m) != 0 || ((lastSector + 1) & m) != 0) {
       // error card can't erase specified area
       error(SD_CARD_ERROR_ERASE_SINGLE_SECTOR);
       goto fail;
     }
   }
   if (m_type != SD_CARD_TYPE_SDHC) {
     firstSector <<= 9;
     lastSector <<= 9;
   }
   if (cardCommand(CMD32, firstSector)
       || cardCommand(CMD33, lastSector)
       || cardCommand(CMD38, 0)) {
     error(SD_CARD_ERROR_ERASE);
     goto fail;
   }
   DBG_BEGIN_TIME(DBG_ERASE_BUSY);
   if (!waitNotBusy(SD_ERASE_TIMEOUT)) {
     error(SD_CARD_ERROR_ERASE_TIMEOUT);
     goto fail;
   }
   DBG_END_TIME(DBG_ERASE_BUSY);
   spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
References readCSD(), and csd_t::v1.
eraseSingleSectorEnable()
bool SdSpiCard::eraseSingleSectorEnable ()
Determine if card supports single sector erase.
Returns
true is returned if single sector erase is supported. false is returned if single sector erase is not supported.
Definition at line 427 of file SdSpiCard.cpp.
{
   csd_t csd;
   return readCSD(&csd) ? csd.v1.erase_blk_en : false;
 }
References readCSD(), and csd_t::v1.
error()
void SdSpiCard::error (uint8_t code) inline
Set SD error code.
Parameters
[in] code value for error code.
Definition at line 95 of file SdSpiCard.h.
{
     m_errorCode = code;
   }
Referenced by begin(), readSingle(), readStart(), readStatus(), readStop(), writeData(), writeSingle(), writeStart(), and writeStop().
errorCode()
uint8_t SdSpiCard::errorCode () const inline
Returns
code for the last error. See SdCardInfo.h for a list of error codes.
Definition at line 101 of file SdSpiCard.h.
{
     return m_errorCode;
   }
Referenced by SdBase< Vol >::cardBegin(), and SdBase< Vol >::sdErrorCode().
errorData()
uint32_t SdSpiCard::errorData () const inline
Returns
error data for last error.
Definition at line 105 of file SdSpiCard.h.
{
     return m_status;
   }
Referenced by SdBase< Vol >::sdErrorData().
isBusy()
bool SdSpiCard::isBusy ()
Check for busy. MISO low indicates the card is busy.
Returns
true if busy else false.
Definition at line 432 of file SdSpiCard.cpp.
{
   bool rtn = true;
   bool spiActive = m_spiActive;
   if (!spiActive) {
     spiStart();
   }
   for (uint8_t i = 0; i < 8; i++) {
     if (0XFF == spiReceive()) {
       rtn = false;
       break;
     }
   }
   if (!spiActive) {
     spiStop();
   }
   return rtn;
 }
References spiStart(), and spiStop().
readCID()
bool SdSpiCard::readCID (cid_t * cid) inline
Read a card's CID register. The CID contains card identification information such as Manufacturer ID, Product name, Product serial number and Manufacturing date.
Parameters
[out] cid pointer to area for returned data.
Returns
true for success or false for failure.
Definition at line 155 of file SdSpiCard.h.
{
     return readRegister(CMD10, cid);
   }
References CMD10.
readCSD()
bool SdSpiCard::readCSD (csd_t * csd) inline
Read a card's CSD register. The CSD contains Card-Specific Data that provides information regarding access to the card's contents.
Parameters
[out] csd pointer to area for returned data.
Returns
true for success or false for failure.
Definition at line 166 of file SdSpiCard.h.
{
     return readRegister(CMD9, csd);
   }
References CMD9.
Referenced by erase(), eraseSingleSectorEnable(), and sectorCount().
readData()
bool SdSpiCard::readData (uint8_t * dst)
Read one data sector in a multiple sector read sequence
Parameters
[out] dst Pointer to the location for the data to be read.
Returns
true for success or false for failure.
Definition at line 461 of file SdSpiCard.cpp.
{
   return readData(dst, 512);
 }
Referenced by readSectors(), readSingle(), and readStatus().
readOCR()
bool SdSpiCard::readOCR (uint32_t * ocr)
Read OCR register.
Parameters
[out] ocr Value of OCR register.
Returns
true for success or false for failure.
Definition at line 509 of file SdSpiCard.cpp.
{
   uint8_t *p = reinterpret_cast<uint8_t*>(ocr);
   syncDevice();
   if (cardCommand(CMD58, 0)) {
     error(SD_CARD_ERROR_CMD58);
     goto fail;
   }
   for (uint8_t i = 0; i < 4; i++) {
     p[3 - i] = spiReceive();
   }
   spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
readSector()
bool SdSpiCard::readSector (uint32_t sector, uint8_t * dst) inline
Read a 512 byte sector from an SD card.
Parameters
[in] sector Logical sector to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 122 of file SdSpiCard.h.
{
 #if ENABLE_DEDICATED_SPI
     return readSectors(sector, dst, 1);
 #else  // ENABLE_DEDICATED_SPI
     return readSingle(sector, dst);
 #endif  // ENABLE_DEDICATED_SPI
   }
References readSectors(), and readSingle().
Referenced by FsCache::get().
readSectors()
bool SdSpiCard::readSectors (uint32_t sector, uint8_t * dst, size_t ns)
Read multiple 512 byte sectors from an SD card.
Parameters
[in] sector Logical sector to be read.
[in] ns Number of sectors to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 693 of file SdSpiCard.cpp.
{
 #if ENABLE_DEDICATED_SPI
   if (m_curState != READ_STATE || sector != m_curSector) {
     if (!syncDevice()) {
       return false;
     }
     if (!SdSpiCard::readStart(sector)) {
       return false;
     }
     m_curSector = sector;
     m_curState = READ_STATE;
   }
   for (size_t i = 0; i < ns; i++, dst += 512) {
     if (!readData(dst, 512)) {
       return false;
     }
   }
   m_curSector += ns;
   return m_sharedSpi ? syncDevice() : true;
 #else  // ENABLE_DEDICATED_SPI
   if (!readStart(sector)) {
     return false;
   }
   for (size_t i = 0; i < ns; i++, dst += 512) {
     if (!readData(dst, 512)) {
       return false;
     }
   }
   return readStop();
 #endif  // ENABLE_DEDICATED_SPI
 }
References readData(), readStart(), readStop(), and syncDevice().
Referenced by readSector().
readSingle()
bool SdSpiCard::readSingle (uint32_t sector, uint8_t * dst)
Read a 512 byte sector from an SD card.
Parameters
[in] sector Logical sector to be read.
[out] dst Pointer to the location that will receive the data.
Returns
true for success or false for failure.
Definition at line 546 of file SdSpiCard.cpp.
{
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD17, sector)) {
     error(SD_CARD_ERROR_CMD17);
     goto fail;
   }
   if (!readData(dst, 512)) {
     goto fail;
   }
   spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
References CMD17, error(), readData(), SD_CARD_TYPE_SDHC, spiStop(), and type().
Referenced by readSector().
readStart()
bool SdSpiCard::readStart (uint32_t sector)
Start a read multiple sector sequence.
Parameters
[in] sector Address of first sector in sequence.
Note
This function is used with readData() and readStop() for optimized multiple sector reads. SPI chipSelect must be low for the entire sequence.
Returns
true for success or false for failure.
Definition at line 566 of file SdSpiCard.cpp.
{
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD18, sector)) {
     error(SD_CARD_ERROR_CMD18);
     goto fail;
   }
 //  spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
References CMD18, error(), SD_CARD_TYPE_SDHC, spiStop(), and type().
Referenced by readSectors().
readStatus()
bool SdSpiCard::readStatus (uint8_t * status)
Return the 64 byte card status
Parameters
[out] status location for 64 status bytes.
Returns
true for success or false for failure.
Definition at line 582 of file SdSpiCard.cpp.
{
   // retrun is R2 so read extra status byte.
   if (cardAcmd(ACMD13, 0) || spiReceive()) {
     error(SD_CARD_ERROR_ACMD13);
     goto fail;
   }
   if (!readData(status, 64)) {
     goto fail;
   }
   spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
References ACMD13, error(), readData(), spiStop(), and status.
readStop()
bool SdSpiCard::readStop ()
End a read multiple sectors sequence.
Returns
true for success or false for failure.
Definition at line 605 of file SdSpiCard.cpp.
{
   if (cardCommand(CMD12, 0)) {
     error(SD_CARD_ERROR_CMD12);
     goto fail;
   }
   spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
References CMD12, error(), and spiStop().
Referenced by readSectors(), and syncDevice().
sectorCount()
uint32_t SdSpiCard::sectorCount ()
Determine the size of an SD flash memory card.
Returns
The number of 512 byte data sectors in the card or zero if an error occurs.
Definition at line 599 of file SdSpiCard.cpp.
{
   csd_t csd;
   return readCSD(&csd) ? sdCardCapacity(&csd) : 0;
 }
References readCSD(), and sdCardCapacity().
Referenced by cardSize(), and FatFormatter::format().
spiStart()
void SdSpiCard::spiStart ()
Set CS low and activate the card.
Definition at line 618 of file SdSpiCard.cpp.
{
   if (!m_spiActive) {
     spiActivate();
     spiSelect();
     m_spiActive = true;
   }
 }
Referenced by begin(), and isBusy().
spiStop()
void SdSpiCard::spiStop ()
Set CS high and deactivate the card.
Definition at line 626 of file SdSpiCard.cpp.
{
   if (m_spiActive) {
     spiUnselect();
     spiSend(0XFF);
     spiDeactivate();
     m_spiActive = false;
   }
 }
Referenced by begin(), isBusy(), readSingle(), readStart(), readStatus(), readStop(), writeData(), writeSectors(), writeSingle(), writeStart(), and writeStop().
syncDevice()
bool SdSpiCard::syncDevice ()
Returns
success if sync successful. Not for user apps.
Definition at line 725 of file SdSpiCard.cpp.
{
 #if ENABLE_DEDICATED_SPI
   if (m_curState == READ_STATE) {
     if (!SdSpiCard::readStop()) {
       return false;
     }
   } else if (m_curState == WRITE_STATE) {
     if (!SdSpiCard::writeStop()) {
       return false;
     }
   }
   m_curState = IDLE_STATE;
 #endif  // ENABLE_DEDICATED_SPI
   return true;
 }
References readStop(), and writeStop().
Referenced by readSectors(), and writeSectors().
type()
uint8_t SdSpiCard::type () const inline
Return the card type: SD V1, SD V2 or SDHC/SDXC
Returns
0 - SD V1, 1 - SD V2, or 3 - SDHC/SDXC.
Definition at line 207 of file SdSpiCard.h.
{
     return m_type;
   }
Referenced by begin(), readSingle(), readStart(), writeSingle(), and writeStart().
writeData()
bool SdSpiCard::writeData (const uint8_t * src)
Write one data sector in a multiple sector write sequence.
Parameters
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 777 of file SdSpiCard.cpp.
{
   // wait for previous write to finish
   DBG_BEGIN_TIME(DBG_WRITE_BUSY);
   if (!waitNotBusy(SD_WRITE_TIMEOUT)) {
     error(SD_CARD_ERROR_WRITE_TIMEOUT);
     goto fail;
   }
   DBG_END_TIME(DBG_WRITE_BUSY);
   if (!writeData(WRITE_MULTIPLE_TOKEN, src)) {
     goto fail;
   }
   return true;
 fail:
   spiStop();
   return false;
 }
References DBG_BEGIN_TIME, DBG_END_TIME, error(), SD_WRITE_TIMEOUT, spiStop(), and WRITE_MULTIPLE_TOKEN.
Referenced by writeSectors(), and writeSingle().
writeSector()
bool SdSpiCard::writeSector (uint32_t sector, const uint8_t * src) inline
Writes a 512 byte sector to an SD card.
Parameters
[in] sector Logical sector to be written.
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 217 of file SdSpiCard.h.
{
 #if ENABLE_DEDICATED_SPI
     return writeSectors(sector, src, 1);
 #else  // ENABLE_DEDICATED_SPI
     return writeSingle(sector, src);
 #endif  // ENABLE_DEDICATED_SPI
   }
References writeSectors(), and writeSingle().
Referenced by FsCache::sync().
writeSectors()
bool SdSpiCard::writeSectors (uint32_t sector, const uint8_t * src, size_t ns)
Write multiple 512 byte sectors to an SD card.
Parameters
[in] sector Logical sector to be written.
[in] ns Number of sectors to be written.
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 741 of file SdSpiCard.cpp.
{
   #if ENABLE_DEDICATED_SPI
   if (m_curState != WRITE_STATE || m_curSector != sector) {
     if (!syncDevice()) {
       return false;
     }
     if (!writeStart(sector)) {
       return false;
     }
     m_curSector = sector;
     m_curState = WRITE_STATE;
   }
   for (size_t i = 0; i < ns; i++, src += 512) {
     if (!writeData(src)) {
       return false;
     }
   }
   m_curSector += ns;
   return m_sharedSpi ? syncDevice() : true;
 #else  // ENABLE_DEDICATED_SPI
   if (!writeStart(sector)) {
     goto fail;
   }
   for (size_t i = 0; i < ns; i++, src += 512) {
     if (!writeData(src)) {
       goto fail;
     }
   }
   return writeStop();
  fail:
   spiStop();
   return false;
 #endif  // ENABLE_DEDICATED_SPI
 }
References spiStop(), syncDevice(), writeData(), writeStart(), and writeStop().
Referenced by writeSector().
writeSingle()
bool SdSpiCard::writeSingle (uint32_t sector, const uint8_t * src)
Writes a 512 byte sector to an SD card.
Parameters
[in] sector Logical sector to be written.
[in] src Pointer to the location of the data to be written.
Returns
true for success or false for failure.
Definition at line 657 of file SdSpiCard.cpp.
{
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD24, sector)) {
     error(SD_CARD_ERROR_CMD24);
     goto fail;
   }
   if (!writeData(DATA_START_SECTOR, src)) {
     goto fail;
   }
 #if CHECK_FLASH_PROGRAMMING
   // wait for flash programming to complete
   DBG_BEGIN_TIME(DBG_WRITE_FLASH);
   if (!waitNotBusy(SD_WRITE_TIMEOUT)) {
     error(SD_CARD_ERROR_WRITE_PROGRAMMING);
     goto fail;
   }
   DBG_END_TIME(DBG_WRITE_FLASH);
   // response is r2 so get and check two bytes for nonzero
   if (cardCommand(CMD13, 0) || spiReceive()) {
     error(SD_CARD_ERROR_CMD13);
     goto fail;
   }
 #endif  // CHECK_FLASH_PROGRAMMING
   spiStop();
   return true;
 fail:
   spiStop();
   return false;
 }
References CMD13, CMD24, DATA_START_SECTOR, DBG_BEGIN_TIME, DBG_END_TIME, error(), SD_CARD_TYPE_SDHC, SD_WRITE_TIMEOUT, spiStop(), type(), and writeData().
Referenced by writeSector().
writeStart() [1/2]
bool SdSpiCard::writeStart (uint32_t sector)
Start a write multiple sectors sequence.
Parameters
[in] sector Address of first sector in sequence.
Note
This function is used with writeData() and writeStop() for optimized multiple sector writes.
Returns
true for success or false for failure.
Definition at line 819 of file SdSpiCard.cpp.
{
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     sector <<= 9;
   }
   if (cardCommand(CMD25, sector)) {
     error(SD_CARD_ERROR_CMD25);
     goto fail;
   }
   return true;
 fail:
   spiStop();
   return false;
 }
References CMD25, error(), SD_CARD_TYPE_SDHC, spiStop(), and type().
Referenced by writeSectors().
writeStart() [2/2]
bool SdSpiCard::writeStart (uint32_t sector, uint32_t eraseCount)
Start a write multiple sector sequence with pre-erase.
Parameters
[in] sector Address of first sector in sequence.
[in] eraseCount The number of sectors to be pre-erased.
Note
This function is used with writeData() and writeStop() for optimized multiple sector writes.
Returns
true for success or false for failure.
Definition at line 835 of file SdSpiCard.cpp.
{
   // send pre-erase count
   if (cardAcmd(ACMD23, eraseCount)) {
     error(SD_CARD_ERROR_ACMD23);
     goto fail;
   }
   // use address if not SDHC card
   if (type() != SD_CARD_TYPE_SDHC) {
     blockNumber <<= 9;
   }
   if (cardCommand(CMD25, blockNumber)) {
     error(SD_CARD_ERROR_CMD25);
     goto fail;
   }
   return true;
 fail:
   spiStop();
   return false;
 }
References ACMD23, CMD25, error(), SD_CARD_TYPE_SDHC, spiStop(), and type().
writeStop()
bool SdSpiCard::writeStop ()
End a write multiple sectors sequence.
Returns
true for success or false for failure.
Definition at line 856 of file SdSpiCard.cpp.
{
   DBG_BEGIN_TIME(DBG_WRITE_STOP);
   if (!waitNotBusy(SD_WRITE_TIMEOUT)) {
     goto fail;
   }
   DBG_END_TIME(DBG_WRITE_STOP);
   spiSend(STOP_TRAN_TOKEN);
   spiStop();
   return true;
 fail:
   error(SD_CARD_ERROR_STOP_TRAN);
   spiStop();
   return false;
 }
References DBG_BEGIN_TIME, DBG_END_TIME, error(), SD_WRITE_TIMEOUT, spiStop(), and STOP_TRAN_TOKEN.
Referenced by syncDevice(), and writeSectors().
The documentation for this class was generated from the following files:
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/SdCard/SdSpiCard.h
D:/brian/Dev/Eris/ERISCore/lib/SdFat-beta-master/src/SdCard/SdSpiCard.cpp