ERIS CORE: bltCallback
bltCallback()
void bltCallback (WrenVM * vm)
VM callback for extention method.
Parameters
vm
Definition at line 619 of file AppWren.cpp.
{
   //(int16_t from_x, int16_t from_y, int16_t width, int16_t height, int16_t dest_x, int16_t dest_y)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   bltMode bm;
   int32_t blt_mode_request = wrenGetSlotDouble(vm, 7);
   if (blt_mode_request == 0){ bm = BLT_COPY;
   }else if (blt_mode_request == 1){ bm = BLT_BLK_COLOR_KEY;
   }else if (blt_mode_request == 2){ bm = BLT_HATCH_BLK;
   }else if (blt_mode_request == 3){ bm = BLT_HATCH_XOR;
   }else if (blt_mode_request == 4){ bm = BLT_ADD;
   }else if (blt_mode_request == 5){ bm = BLT_SUB;
   }else if (blt_mode_request == 6){ bm = BLT_MULT;
   }else if (blt_mode_request == 7){ bm = BLT_DIV;
   }else if (blt_mode_request == 8){ bm = BLT_AND;
   }else if (blt_mode_request == 9){ bm = BLT_OR;
   }else if (blt_mode_request == 10){bm = BLT_XOR;
   }else if (blt_mode_request == 11){bm = BLT_MEAN;
   }else return;
   app->bltSurface2FrameBuffer(wrenGetSlotDouble(vm, 1), wrenGetSlotDouble(vm, 2),wrenGetSlotDouble(vm, 3),wrenGetSlotDouble(vm, 4),wrenGetSlotDouble(vm, 5), wrenGetSlotDouble(vm, 6),bm);
 }
References BLT_ADD, BLT_AND, BLT_BLK_COLOR_KEY, BLT_COPY, BLT_DIV, BLT_HATCH_BLK, BLT_HATCH_XOR, BLT_MEAN, BLT_MULT, BLT_OR, BLT_SUB, BLT_XOR, AppWren::bltSurface2FrameBuffer(), AppManager::getAppByName(), and AppManager::getInstance().
Referenced by bindForeignMethod().