ERIS CORE: getImageSizeCallback
getImageSizeCallback()
void getImageSizeCallback (WrenVM * vm)
Definition at line 534 of file AppWren.cpp.
{
   //(char* path,char* filename,int16_t x, int16_t y)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   int32_t width, height;
   if(app->useNativeFS == true){
     app->getDraw()->getImageSize(wrenGetSlotString(vm,1),wrenGetSlotString(vm,2),&width,&height,0);
   }else{
     app->getDraw()->getImageSize(wrenGetSlotString(vm,1),wrenGetSlotString(vm,2),&width,&height,&app->wren_file_system);
   }
   wrenEnsureSlots(vm, 3);
   wrenSetSlotNewList(vm, 0);
   wrenSetSlotDouble(vm,1,width);
   wrenInsertInList(vm, 0, -1, 1);//insert the width from slot 1
   wrenSetSlotDouble(vm,2,height);
   wrenInsertInList(vm, 0, -1, 2);//insert the height from slot 1
 }
References AppManager::getAppByName(), AppWren::getDraw(), ILI9341_t3_ERIS::getImageSize(), AppManager::getInstance(), AppWren::useNativeFS, and AppWren::wren_file_system.
Referenced by bindForeignMethod().