ERIS CORE: audioDirectorGetTypeListCallback
audioDirectorGetTypeListCallback()
void audioDirectorGetTypeListCallback (WrenVM * vm)
AudioDirector callback for wren.
Parameters
vm
Definition at line 366 of file AppWren.cpp.
{
   //(char* function)
   int num_slots;
     int slot = 0;
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   AudioDirector* ad = app->getAudioDirector();
   const char * function = wrenGetSlotString(vm, 1);
   num_slots = ad->getTypeCountByFunction(function)+1;
   wrenEnsureSlots(vm, num_slots);
   wrenSetSlotNewList(vm, slot);
   while(++slot < num_slots) {
     char* cat_list;
     cat_list = ad->getTypeListItem(function,slot-1);
         wrenSetSlotString(vm, slot, cat_list);
         wrenInsertInList(vm, 0, -1, slot);
     }
 }
References AppManager::getAppByName(), AppWren::getAudioDirector(), AppManager::getInstance(), AudioDirector::getTypeCountByFunction(), and AudioDirector::getTypeListItem().
Referenced by bindForeignMethod().