ERIS CORE: fsimportFromSD
fsimportFromSD()
void FLASHMEM fsimportFromSD (WrenVM * vm)
imports a file from the SD card to the RAM drive returns the file size if ok, else returns -1 to indicate an error
Parameters
vm
Definition at line 972 of file AppWren.cpp.
{
   //(src_path,src_file,dest_path,dst_file)
   char c[64];
   int32_t file_size;
   FsFile source; //The source is the SD card
   File dest; //The destination is the VM file system located in ext_ram
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   const char* src_path;
   const char* src_filename;
   const char* dst_path;
   const char* dst_filename;
   src_path = wrenGetSlotString(vm,1);
   src_filename = wrenGetSlotString(vm,2);
   dst_path = wrenGetSlotString(vm,3);
   dst_filename = wrenGetSlotString(vm,4);
   am->getSD()->chdir(src_path);
   source = am->getSD()->open(src_filename,O_RDONLY);
   //make sure the destination drive has enough space
   file_size = source.available();
   if (file_size > (WREN_VM_FILE_SYSTEM_SIZE - app->wren_file_system.usedSize())){
     //if not return -1 to wren to indicate a destination size error
     source.close();
     wrenSetSlotDouble(vm,0,-1);
     return;
   }else if (file_size == 0){
      //if not return -2 to wren to indicate a source file error or empty file
     source.close();
     wrenSetSlotDouble(vm,0,-2);
     return;
   }
   //file exists and the destination has enough space, continue..
   strcpy(c,dst_path);
   strcat(c,dst_filename);
   dest = app->wren_file_system.open(c,O_RDWR);
   //c[2]=0; //null termination
   for(int32_t i = file_size; i > 0; i--){
     source.readBytes(c,1);//read char
     dest.write(c,1);
   }
   source.close();
   dest.close();
   wrenSetSlotDouble(vm,0,file_size);
 }
References AppManager::getAppByName(), AppManager::getInstance(), AppManager::getSD(), and AppWren::wren_file_system.
Referenced by bindForeignMethod().