ERIS CORE: getSourceForModule
getSourceForModule()
const char* getSourceForModule (const char * name)
Get the Source For Module object requested by the Wren VM.
Parameters
name
Returns
const char*
Definition at line 99 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   return app->loadModuleSource(name);
 }
References AppManager::getAppByName(), AppManager::getInstance(), and AppWren::loadModuleSource().
Referenced by loadModule().