ERIS CORE: setClockSpeedCallback
setClockSpeedCallback()
void setClockSpeedCallback (WrenVM * vm)
Set the CPU Clock Speed Callback object.
Parameters
vm
Definition at line 255 of file AppWren.cpp.
{
   //(uint16_t cpu_speed)
   AppManager* am = AppManager::getInstance();
   am->requestArmSetClock(wrenGetSlotDouble(vm, 1));
 }
References AppManager::getInstance(), and AppManager::requestArmSetClock().
Referenced by bindForeignMethod().