ERIS CORE: bindForeignMethod
bindForeignMethod()
WrenForeignMethodFn FLASHMEM bindForeignMethod (WrenVM * vm, const char * module, const char * className, bool isStatic, const char * signature)
callback function for Wren to request an exported function bindings
Parameters
vm
module
className
isStatic
signature
Returns
WrenForeignMethodFn
Definition at line 1258 of file AppWren.cpp.
 {
   //callback for the VM to request a pointer to the c function.
   if (strcmp(module, "main") == 0)
   {
     if (strcmp(className, "App") == 0) //these are static methods... attach them to the class, not an instance
     {
       if (strcmp(signature, "sendMessage(_,_)") == 0){
         return sendMessageCallback;
       }else if (strcmp(signature, "setPosition(_,_)") == 0){
         return setPositionCallback;
       }else if (strcmp(signature, "setDimension(_,_)") == 0){
         return setDimensionCallback;
       }else if (strcmp(signature, "setWidgetPosition(_,_)") == 0){
         return setWidgetPositionCallback;
       }else if (strcmp(signature, "setWidgetDimension(_,_)") == 0){
         return setWidgetDimensionCallback;
       }else if (strcmp(signature, "requestPopUp(_)") == 0){
         return requestPopUpCallback;
       }else if (strcmp(signature, "releasePopUp()") == 0){
         return releasePopUpCallback;
       }else if (strcmp(signature, "getFocus()") == 0){
         return getFocusCallback;
       }else if (strcmp(signature, "returnFocus()") == 0){
         return returnFocusCallback;
       }else if (strcmp(signature, "setClockSpeed(_)") == 0){
         return setClockSpeedCallback;
       }else if (strcmp(signature, "random(_)") == 0){
         return setRandomCallback;
       }else if (strcmp(signature, "restartVM(_)") == 0){
         return restartVMCallback;
       }
     }else if (strcmp(className, "Data") == 0){ //these are static methods... attach them to the class, not an instance
       if (strcmp(signature, "update(_,_)") == 0){
         return dataDictUpdateCallback;
       }else if (strcmp(signature, "read(_)") == 0){
         return dataDictReadCallback;
       }
       if (strcmp(signature, "updatef(_,_)") == 0){
         return dataDictUpdateFloatCallback;
       }else if (strcmp(signature, "readf(_)") == 0){
         return dataDictReadFloatCallback;
       }
     }else if (strcmp(className, "AudioDirector") == 0){ //these are static methods... attach them to the class, not an instance
       if (strcmp(signature, "connect(_,_,_,_)") == 0){
         return audioDirectorConnectCallback;
       } else if (strcmp(signature, "disconnect(_,_)") == 0){
         return audioDirectorDisconnectCallback;
       }else if (strcmp(signature, "disconnectAll()") == 0){
         return audioDirectorDisconnectAllCallback;
       }else if (strcmp(signature, "getFunctionList()") == 0){
         return audioDirectorGetFunctionListCallback;
       }else if (strcmp(signature, "getTypeList(_)") == 0){
         return audioDirectorGetTypeListCallback;
       }else if (strcmp(signature, "getTypeInstanceCount(_)") == 0){
         return audioDirectorGetTypeInstanceCountCallback;
       }else if (strcmp(signature, "enableInterrupts()") == 0){
         return audioDirectorEnableAudioInterrupts;
       }else if (strcmp(signature, "disableInterrupts()") == 0){
         return audioDirectorDisableAudioInterrupts;
       }else if (strcmp(signature, "getArbSample(_,_)") == 0){
         return audioDirectorGetArbWaveFormCallback;
       }
     }else if (strcmp(className, "Draw") == 0){ //these are static methods... attach them to the class, not an instance
       if (strcmp(signature, "setPixel(_,_,_,_,_)") == 0){
         return setPixelCallback;
       }else if (strcmp(signature, "getPixel(_,_)") == 0){
         return getPixelCallback;
       }else if (strcmp(signature, "setTextColor(_,_,_)") == 0){
         return setTextColorCallback;
       }else if (strcmp(signature, "setCursor(_,_)") == 0){
         return setCursorCallback;
       }else if (strcmp(signature, "print(_)") == 0){
         return printCallback;
       }else if (strcmp(signature, "print(_,_,_,_,_)") == 0){
         return printWithFontCallback;
       }else if (strcmp(signature, "setFontSize(_)") == 0){
         return setFontSizeCallback;
       }else if (strcmp(signature, "getImageSize(_,_)") == 0){
         return getImageSizeCallback;
       }else if (strcmp(signature, "loadImage(_,_,_,_,_)") == 0){
         return loadImageCallback;
       }else if (strcmp(signature, "loadImageToSurface(_,_,_,_,_)") == 0){
         return loadImageSurfaceCallback;
       }else if (strcmp(signature, "blt(_,_,_,_,_,_,_)") == 0){
         return bltCallback;
       }else if (strcmp(signature, "bltFB(_,_,_,_,_,_,_)") == 0){
         return bltFBCallback;
       }else if (strcmp(signature, "bltInPlace(_,_,_,_,_,_,_)") == 0){
         return bltInPlaceCallback;
       }else if (strcmp(signature, "bltInPlaceFB(_,_,_,_,_,_,_)") == 0){
         return bltInPlaceFBCallback;
       }else if (strcmp(signature, "line(_,_,_,_,_,_,_)") == 0){
         return drawLineCallback;
       }else if (strcmp(signature, "fill(_,_,_)") == 0){
         return drawFillCallback;
       }else if (strcmp(signature, "useWrenFileSystem()") == 0){
         return drawUseWrenFileSystem;
       }else if (strcmp(signature, "useSDFileSystem()") == 0){
         return drawUseSDFileSystem;
       }else if (strcmp(signature, "enablePixelOP(_,_)") == 0){
         return drawEnablePixelOp;
       }else if (strcmp(signature, "disablePixelOP()") == 0){
         return drawDisablePixelOp;
       }
     }else if (strcmp(className, "FileSystem") == 0){
       if (strcmp(signature, "open(_,_)") == 0){
         return fsOpenCallback;
       }else if (strcmp(signature, "exists(_)") == 0){
         return fsExistsCallback;
       }else if (strcmp(signature, "mkdir(_)") == 0){
         return fsMkdirCallback;
       }else if (strcmp(signature, "rename(_,_)") == 0){
         return fsRenameCallback;
       }else if (strcmp(signature, "remove(_)") == 0){
         return fsRemoveCallback;
       }else if (strcmp(signature, "rmdir(_)") == 0){
         return fsRmdirCallback;
       }else if (strcmp(signature, "usedSize()") == 0){
         return fsUsedSizeCallback;
       }else if (strcmp(signature, "totalSize()") == 0){
         return fsTotalSizeCallback;
       }else if (strcmp(signature, "importFromSD(_,_,_,_)") == 0){
         return fsimportFromSD;
       }else if (strcmp(signature, "format()") == 0){
         return fsFormat;
       }
     }else if (strcmp(className, "File") == 0){
       if (strcmp(signature, "read(_)") == 0){
         return fileReadCallback;
       }else if (strcmp(signature, "readBytes(_)") == 0){
         return fileReadBytesCallback;
       }else if (strcmp(signature, "write(_)") == 0){
         return fileWriteCallback;
       }else if (strcmp(signature, "available()") == 0){
         return fileAvailableCallback;
       }else if (strcmp(signature, "peek()") == 0){
         return filePeekCallback;
       }else if (strcmp(signature, "flush()") == 0){
         return fileFlushCallback;
       }else if (strcmp(signature, "truncate(_)") == 0){
         return fileTruncateCallback;
       }else if (strcmp(signature, "seek(_,_)") == 0){
         return fileSeekCallback;
       }else if (strcmp(signature, "position()") == 0){
         return filePositionCallback;
       }else if (strcmp(signature, "size()") == 0){
         return fileSizeCallback;
       }else if (strcmp(signature, "close()") == 0){
         return fileCloseCallback;
       }else if (strcmp(signature, "isOpen()") == 0){
         return fileIsOpenCallback;
       }else if (strcmp(signature, "name()") == 0){
         return fileNameCallback;
       }else if (strcmp(signature, "isDirectory()") == 0){
         return fileIsDirectoryCallback;
       }else if (strcmp(signature, "openNextFile(_)") == 0){
         return fileOpenNextCallback;
       }else if (strcmp(signature, "rewindDirectory()") == 0){
         return fileRewindDirectoryCallback;
       }
     }
     // Other classes in main...
   }
   // Other modules...
   //else return NULL?
   return NULL;
 }
References audioDirectorConnectCallback(), audioDirectorDisableAudioInterrupts(), audioDirectorDisconnectAllCallback(), audioDirectorDisconnectCallback(), audioDirectorEnableAudioInterrupts(), audioDirectorGetArbWaveFormCallback(), audioDirectorGetFunctionListCallback(), audioDirectorGetTypeInstanceCountCallback(), audioDirectorGetTypeListCallback(), bltCallback(), bltFBCallback(), bltInPlaceCallback(), bltInPlaceFBCallback(), dataDictReadCallback(), dataDictReadFloatCallback(), dataDictUpdateCallback(), dataDictUpdateFloatCallback(), drawDisablePixelOp(), drawEnablePixelOp(), drawFillCallback(), drawLineCallback(), drawUseSDFileSystem(), drawUseWrenFileSystem(), fileAvailableCallback(), fileCloseCallback(), fileFlushCallback(), fileIsDirectoryCallback(), fileIsOpenCallback(), fileNameCallback(), fileOpenNextCallback(), filePeekCallback(), filePositionCallback(), fileReadBytesCallback(), fileReadCallback(), fileRewindDirectoryCallback(), fileSeekCallback(), fileSizeCallback(), fileTruncateCallback(), fileWriteCallback(), fsExistsCallback(), fsFormat(), fsimportFromSD(), fsMkdirCallback(), fsOpenCallback(), fsRemoveCallback(), fsRenameCallback(), fsRmdirCallback(), fsTotalSizeCallback(), fsUsedSizeCallback(), getFocusCallback(), getImageSizeCallback(), getPixelCallback(), loadImageCallback(), loadImageSurfaceCallback(), printCallback(), printWithFontCallback(), releasePopUpCallback(), requestPopUpCallback(), restartVMCallback(), returnFocusCallback(), sendMessageCallback(), setClockSpeedCallback(), setCursorCallback(), setDimensionCallback(), setFontSizeCallback(), setPixelCallback(), setPositionCallback(), setRandomCallback(), setTextColorCallback(), setWidgetDimensionCallback(), and setWidgetPositionCallback().
Referenced by AppWren::startVM().