ERIS CORE: audioDirectorDisconnectAllCallback
audioDirectorDisconnectAllCallback()
void audioDirectorDisconnectAllCallback (WrenVM * vm)
AudioDirector callback for wren.
Parameters
vm
Definition at line 322 of file AppWren.cpp.
{
   //()
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   bool b = app->getAudioDirector()->disconnectAll();
   wrenSetSlotBool(vm, 0,b);
 }
References AudioDirector::disconnectAll(), AppManager::getAppByName(), AppWren::getAudioDirector(), and AppManager::getInstance().
Referenced by bindForeignMethod().