ERIS CORE: AppWren.cpp File Reference
AppWren.cpp File Reference
#include "AppWren.h"
#include "globaldefs.h"
#include <Arduino.h>
#include <AppManager.h>
#include <boarddefs.h>
Functions
pid_t _getpid (void)
int _gettimeofday (struct timeval *tv, struct timezone *tz)
int _kill (pid_t pid, int signum)
Wren system interface.
int _times (void)
void audioDirectorConnectCallback (WrenVM *vm)
AudioDirector callback for wren.
void audioDirectorDisconnectAllCallback (WrenVM *vm)
AudioDirector callback for wren.
void audioDirectorDisconnectCallback (WrenVM *vm)
AudioDirector callback for wren.
WrenForeignMethodFn bindForeignMethod (WrenVM *vm, const char *module, const char *className, bool isStatic, const char *signature)
callback function for Wren to request an exported function bindings
void dataDictReadCallback (WrenVM *vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
void dataDictReadFloatCallback (WrenVM *vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
void dataDictUpdateCallback (WrenVM *vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
void dataDictUpdateFloatCallback (WrenVM *vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
void errorFn (WrenVM *vm, WrenErrorType errorType, const char *module, const int line, const char *msg)
error function system callback for the Wren VM. Stdout/Stderr is SerialUSB1
void getFocusCallback (WrenVM *vm)
Get the Focus Callback object.AppWren exported method which can be called from within a Wren VM instance.
const char * getSourceForModule (const char *name)
Get the Source For Module object requested by the Wren VM.
WrenLoadModuleResult loadModule (WrenVM *vm, const char *name)
callback for the VM to request a module be loaded from the filesystem
static void loadModuleComplete (WrenVM *vm, const char *module, WrenLoadModuleResult result)
callback function for the VM to indicate to the system that it's ok to release any memory allocated during the module load request
void releasePopUpCallback (WrenVM *vm)
AppWren exported method which can be called from within a Wren VM instance.
void requestPopUpCallback (WrenVM *vm)
AppWren exported method which can be called from within a Wren VM instance.
void returnFocusCallback (WrenVM *vm)
AppWren exported method which can be called from within a Wren VM instance.
void sendMessageCallback (WrenVM *vm)
AppWren exported method which can be called from within a Wren VM instance.
uint32_t set_arm_clock (uint32_t frequency)
void setClockSpeedCallback (WrenVM *vm)
Set the CPU Clock Speed Callback object.
void setDimensionCallback (WrenVM *vm)
Set the Dimension Callback object. AppWren exported method which can be called from within a Wren VM instance.
void setPixelCallback (WrenVM *vm)
Set the Pixel Callback object. AppWren exported method which can be called from within a Wren VM instance.
void setPositionCallback (WrenVM *vm)
AppWren exported method which can be called from within a Wren VM instance.
void setWidgetDimensionCallback (WrenVM *vm)
Set the Widget Dimension Callback object. AppWren exported method which can be called from within a Wren VM instance.
void setWidgetPositionCallback (WrenVM *vm)
Set the Widget Position Callback object. AppWren exported method which can be called from within a Wren VM instance.
static void writeFn (WrenVM *vm, const char *text)
write function system callback for the Wren VM. Stdout/Stderr is SerialUSB1
Detailed Description
Author
Brian Monkaba (brian.nosp@m..mon.nosp@m.kaba@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2021-12-14
Copyright
Copyright (c) 2021
Definition in file AppWren.cpp.
Function Documentation
_getpid()
pid_t _getpid (void)
Definition at line 27 of file AppWren.cpp.
 {return 1;}
_gettimeofday()
int _gettimeofday (struct timeval * tv, struct timezone * tz)
Definition at line 29 of file AppWren.cpp.
 {return 0;}
_kill()
int _kill (pid_t pid, int signum)
Wren system interface.
Definition at line 26 of file AppWren.cpp.
 {return 0;}
_times()
int _times (void)
Definition at line 28 of file AppWren.cpp.
 {return 0;}
audioDirectorConnectCallback()
void audioDirectorConnectCallback (WrenVM * vm)
AudioDirector callback for wren.
Parameters
vm
Definition at line 255 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   bool b = am->ad->connect(wrenGetSlotString(vm, 1));
   wrenSetSlotBool(vm, 0,b);
 }
Referenced by bindForeignMethod().
audioDirectorDisconnectAllCallback()
void audioDirectorDisconnectAllCallback (WrenVM * vm)
AudioDirector callback for wren.
Parameters
vm
Definition at line 276 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   bool b = am->ad->disconnectAll();
   wrenSetSlotBool(vm, 0,b);
 }
Referenced by bindForeignMethod().
audioDirectorDisconnectCallback()
void audioDirectorDisconnectCallback (WrenVM * vm)
AudioDirector callback for wren.
Parameters
vm
Definition at line 266 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   bool b = am->ad->disconnect(wrenGetSlotString(vm, 1));
   wrenSetSlotBool(vm, 0,b);
 }
Referenced by bindForeignMethod().
bindForeignMethod()
WrenForeignMethodFn bindForeignMethod (WrenVM * vm, const char * module, const char * className, bool isStatic, const char * signature)
callback function for Wren to request an exported function bindings
Parameters
vm
module
className
isStatic
signature
Returns
WrenForeignMethodFn
Definition at line 338 of file AppWren.cpp.
 {
   //callback for the VM to request a pointer to the c function.
   if (strcmp(module, "main") == 0)
   {
     if (strcmp(className, "App") == 0) //these are static methods... attach them to the class, not an instance
     {
       if (strcmp(signature, "sendMessage(_,_)") == 0){
         return sendMessageCallback;
       }else if (strcmp(signature, "setPosition(_,_)") == 0){
         return setPositionCallback;
       }else if (strcmp(signature, "setDimension(_,_)") == 0){
         return setDimensionCallback;
       }else if (strcmp(signature, "setWidgetPosition(_,_)") == 0){
         return setWidgetPositionCallback;
       }else if (strcmp(signature, "setWidgetDimension(_,_)") == 0){
         return setWidgetDimensionCallback;
       }else if (strcmp(signature, "requestPopUp(_)") == 0){
         return requestPopUpCallback;
       }else if (strcmp(signature, "releasePopUp()") == 0){
         return releasePopUpCallback;
       }else if (strcmp(signature, "getFocus()") == 0){
         return getFocusCallback;
       }else if (strcmp(signature, "returnFocus()") == 0){
         return returnFocusCallback;
       }else if (strcmp(signature, "setPixel(_,_,_,_,_)") == 0){
         return setPixelCallback;
       }else if (strcmp(signature, "setClockSpeed(_)") == 0){
         return setClockSpeedCallback;
       }
       // Other foreign methods on Math...
     }else if (strcmp(className, "Data") == 0){ //these are static methods... attach them to the class, not an instance
       if (strcmp(signature, "update(_,_)") == 0){
         return dataDictUpdateCallback;
       }else if (strcmp(signature, "read(_)") == 0){
         return dataDictReadCallback;
       }
       if (strcmp(signature, "updatef(_,_)") == 0){
         return dataDictUpdateFloatCallback;
       }else if (strcmp(signature, "readf(_)") == 0){
         return dataDictReadFloatCallback;
       }
     }else if (strcmp(className, "AudioDirector") == 0){ //these are static methods... attach them to the class, not an instance
       if (strcmp(signature, "connect(_)") == 0){
         return audioDirectorConnectCallback;
       } else if (strcmp(signature, "disconnect(_)") == 0){
         return audioDirectorDisconnectCallback;
       }else if (strcmp(signature, "disconnectAll()") == 0){
         return audioDirectorDisconnectAllCallback;
       }
     }
     // Other classes in main...
   }
   // Other modules...
   //else return NULL?
   return NULL;
 }
References audioDirectorConnectCallback(), audioDirectorDisconnectAllCallback(), audioDirectorDisconnectCallback(), dataDictReadCallback(), dataDictReadFloatCallback(), dataDictUpdateCallback(), dataDictUpdateFloatCallback(), getFocusCallback(), releasePopUpCallback(), requestPopUpCallback(), returnFocusCallback(), sendMessageCallback(), setClockSpeedCallback(), setDimensionCallback(), setPixelCallback(), setPositionCallback(), setWidgetDimensionCallback(), and setWidgetPositionCallback().
Referenced by AppWren::startVM().
dataDictReadCallback()
void dataDictReadCallback (WrenVM * vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 299 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   int32_t d = am->data->read(wrenGetSlotString(vm, 1));
   wrenSetSlotDouble(vm, 0,d);
 }
Referenced by bindForeignMethod().
dataDictReadFloatCallback()
void dataDictReadFloatCallback (WrenVM * vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 320 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   float32_t f = am->data->readf(wrenGetSlotString(vm, 1));
   wrenSetSlotDouble(vm, 0,f);
 }
Referenced by bindForeignMethod().
dataDictUpdateCallback()
void dataDictUpdateCallback (WrenVM * vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 289 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   bool b = am->data->update(wrenGetSlotString(vm, 1),(int32_t)wrenGetSlotDouble(vm, 2));
   wrenSetSlotBool(vm, 0,b);
 }
Referenced by bindForeignMethod().
dataDictUpdateFloatCallback()
void dataDictUpdateFloatCallback (WrenVM * vm)
SvcDataDictionary exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 310 of file AppWren.cpp.
{
   AppManager* am = AppManager::getInstance();
   bool b = am->data->update(wrenGetSlotString(vm, 1),(float)wrenGetSlotDouble(vm, 2));
   wrenSetSlotBool(vm, 0,b);
 }
Referenced by bindForeignMethod().
errorFn()
void errorFn (WrenVM * vm, WrenErrorType errorType, const char * module, const int line, const char * msg)
error function system callback for the Wren VM. Stdout/Stderr is SerialUSB1
Parameters
vm
errorType
module
line
msg
Definition at line 51 of file AppWren.cpp.
 {
   switch (errorType)
   {
     case WREN_ERROR_COMPILE:
     {
      SerialUSB1.printf("VM WREN_ERR [%s line %d] [Error] %s\n", module, line, msg);
     } break;
     case WREN_ERROR_STACK_TRACE:
     {
       SerialUSB1.printf("VM WREN_ERR [%s line %d] in %s\n", module, line, msg);
     } break;
     case WREN_ERROR_RUNTIME:
     {
       //Serial.printf("VM M WREN_ERR [Runtime Error] %s\n", msg);
     } break;
   }
 }
Referenced by AppWren::startVM().
getFocusCallback()
void getFocusCallback (WrenVM * vm)
Get the Focus Callback object.AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 206 of file AppWren.cpp.
{
   //(void)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->getFocus();
 }
References AppWren::getFocus().
Referenced by bindForeignMethod().
getSourceForModule()
const char* getSourceForModule (const char * name)
Get the Source For Module object requested by the Wren VM.
Parameters
name
Returns
const char*
Definition at line 78 of file AppWren.cpp.
{
   return g_math_wren;
 }
Referenced by loadModule().
loadModule()
WrenLoadModuleResult loadModule (WrenVM * vm, const char * name)
callback for the VM to request a module be loaded from the filesystem
Parameters
vm
name
Returns
WrenLoadModuleResult
Definition at line 108 of file AppWren.cpp.
{
   //callback for the VM to request a module be loaded from the filesystem
   Serial.printf("M VM: loadModule %s\n", name);
   WrenLoadModuleResult result = {0};
     result.onComplete = loadModuleComplete;
     result.source = getSourceForModule(name);
   return result;
 }
References getSourceForModule(), and loadModuleComplete().
Referenced by AppWren::startVM().
loadModuleComplete()
static void loadModuleComplete (WrenVM * vm, const char * module, WrenLoadModuleResult result) static
callback function for the VM to indicate to the system that it's ok to release any memory allocated during the module load request
Parameters
vm
module
result
Definition at line 89 of file AppWren.cpp.
 {
   if(result.source) {
     //for example, if we used malloc to allocate
     //our source string, we use free to release it.
     //free((void*)result.source);
   }
 }
Referenced by loadModule().
releasePopUpCallback()
void releasePopUpCallback (WrenVM * vm)
AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 195 of file AppWren.cpp.
{
   //(void)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->releasePopUp();
 }
References AppWren::releasePopUp().
Referenced by bindForeignMethod().
requestPopUpCallback()
void requestPopUpCallback (WrenVM * vm)
AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 184 of file AppWren.cpp.
{
   //(void)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->requestPopUp(wrenGetSlotBool(vm, 1));
 }
References AppWren::requestPopUp().
Referenced by bindForeignMethod().
returnFocusCallback()
void returnFocusCallback (WrenVM * vm)
AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 217 of file AppWren.cpp.
{
   //(void)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->setWidgetDimension(wrenGetSlotDouble(vm, 1),wrenGetSlotDouble(vm, 2));
 }
References AppWren::setWidgetDimension().
Referenced by bindForeignMethod().
sendMessageCallback()
void sendMessageCallback (WrenVM * vm)
AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 125 of file AppWren.cpp.
{
 //callback params can be found in the slots
 //return value goes into slot 0
   AppManager* am = AppManager::getInstance();
   wrenSetSlotBool(vm, 0, am->sendMessage(am->getAppByName("AppWren"),wrenGetSlotString(vm, 1),wrenGetSlotString(vm, 2)));
 }
Referenced by bindForeignMethod().
set_arm_clock()
uint32_t set_arm_clock (uint32_t frequency)
Referenced by setClockSpeedCallback().
setClockSpeedCallback()
void setClockSpeedCallback (WrenVM * vm)
Set the CPU Clock Speed Callback object.
Parameters
vm
Definition at line 243 of file AppWren.cpp.
{
   //(uint16_t cpu_speed)
   set_arm_clock(wrenGetSlotDouble(vm, 1));
 }
References set_arm_clock().
Referenced by bindForeignMethod().
setDimensionCallback()
void setDimensionCallback (WrenVM * vm)
Set the Dimension Callback object. AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 149 of file AppWren.cpp.
{
   //(int16_t new_width, int16_t new_height)
   AppManager* am = AppManager::getInstance();
   AppBaseClass* app = am->getAppByName("AppWren");
   app->setDimension(wrenGetSlotDouble(vm, 1),wrenGetSlotDouble(vm, 2));
 }
References AppBaseClass::setDimension().
Referenced by bindForeignMethod().
setPixelCallback()
void setPixelCallback (WrenVM * vm)
Set the Pixel Callback object. AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 228 of file AppWren.cpp.
{
   //(int16_t x, int16_t y, int16_t r, int16_t g, int16_t b)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->setPixel(wrenGetSlotDouble(vm, 1),wrenGetSlotDouble(vm, 2),wrenGetSlotDouble(vm, 3),wrenGetSlotDouble(vm, 4),wrenGetSlotDouble(vm, 5));
 }
References AppWren::setPixel().
Referenced by bindForeignMethod().
setPositionCallback()
void setPositionCallback (WrenVM * vm)
AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 137 of file AppWren.cpp.
{
   //(int16_t newOriginX, int16_t newOriginY)
   AppManager* am = AppManager::getInstance();
   AppBaseClass* app = am->getAppByName("AppWren");
   app->setPosition(wrenGetSlotDouble(vm, 1),wrenGetSlotDouble(vm, 2));
 };
References AppBaseClass::setPosition().
Referenced by bindForeignMethod().
setWidgetDimensionCallback()
void setWidgetDimensionCallback (WrenVM * vm)
Set the Widget Dimension Callback object. AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 173 of file AppWren.cpp.
{
   //(int16_t new_width, int16_t new_height)
   AppManager* am = AppManager::getInstance();
   AppBaseClass* app = am->getAppByName("AppWren");
   app->setWidgetDimension(wrenGetSlotDouble(vm, 1),wrenGetSlotDouble(vm, 2));
 }
References AppBaseClass::setWidgetDimension().
Referenced by bindForeignMethod().
setWidgetPositionCallback()
void setWidgetPositionCallback (WrenVM * vm)
Set the Widget Position Callback object. AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 161 of file AppWren.cpp.
{
   //(int16_t newOriginX, int16_t newOriginY)
   AppManager* am = AppManager::getInstance();
   AppBaseClass* app = am->getAppByName("AppWren");
   app->setWidgetPosition(wrenGetSlotDouble(vm, 1),wrenGetSlotDouble(vm, 2));
 }
References AppBaseClass::setWidgetPosition().
Referenced by bindForeignMethod().
writeFn()
static void writeFn (WrenVM * vm, const char * text) static
write function system callback for the Wren VM. Stdout/Stderr is SerialUSB1
Parameters
vm
text
Definition at line 38 of file AppWren.cpp.
{
   SerialUSB1.printf("VM %s", text);
 }
Referenced by AppWren::startVM().