ERIS CORE: writeFn
writeFn()
static void writeFn (WrenVM * vm, const char * text) static
write function system callback for the Wren VM. Stdout/Stderr is Serial
Parameters
vm
text
Definition at line 45 of file AppWren.cpp.
{
   //Serial.printf("VM %s", text);
   AppManager* am = AppManager::getInstance();
   SvcSerialCommandInterface* sci = (SvcSerialCommandInterface*)am->getAppByName("SCI");
   if(sci->requestStartLZ4Message()){
     sci->printf("VM %s", text);
     sci->sendLZ4Message();
   };
 }
References AppManager::getAppByName(), AppManager::getInstance(), SvcSerialCommandInterface::requestStartLZ4Message(), sci, and SvcSerialCommandInterface::sendLZ4Message().
Referenced by AppWren::startVM().