ERIS CORE: drawEnablePixelOp
drawEnablePixelOp()
void drawEnablePixelOp (WrenVM * vm)
Definition at line 795 of file AppWren.cpp.
{
   //(int16_t start_x, int16_t start_y, int16_t end_x, int16_t end_y, int16_t r, int16_t g, int16_t b)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   pixelOPMode pom;
   int32_t pixel_mode_request = wrenGetSlotDouble(vm, 2);
   pom = PXOP_COPY; //default
   if(pixel_mode_request==0) pom = PXOP_COPY;
   else if(pixel_mode_request==1) pom =  PXOP_BLK_COLOR_KEY;
   else if(pixel_mode_request==2) pom = PXOP_HATCH_BLK;
   else if(pixel_mode_request==3) pom = PXOP_HATCH_XOR;
   else if(pixel_mode_request==4) pom = PXOP_ADD;
   else if(pixel_mode_request==5) pom = PXOP_SUB;
   else if(pixel_mode_request==6) pom = PXOP_MULT;
   else if(pixel_mode_request==7) pom = PXOP_DIV;
   else if(pixel_mode_request==8) pom = PXOP_AND;
   else if(pixel_mode_request==9) pom = PXOP_OR;
   else if(pixel_mode_request==10) pom = PXOP_XOR;
   else if(pixel_mode_request==11) pom = PXOP_MEAN;
   else if(pixel_mode_request==12) pom = PXOP_1ST_PIXEL_COLOR_KEY;
   else if(pixel_mode_request==13) pom = PXOP_NOT_BLK_COLOR_KEY;
   else if(pixel_mode_request==14) pom = PXOP_NOT_1ST_PIXEL_COLOR_KEY;
   app->enablePixelOP(wrenGetSlotDouble(vm, 1),pom);
 }
References AppWren::enablePixelOP(), AppManager::getAppByName(), AppManager::getInstance(), PXOP_1ST_PIXEL_COLOR_KEY, PXOP_ADD, PXOP_AND, PXOP_BLK_COLOR_KEY, PXOP_COPY, PXOP_DIV, PXOP_HATCH_BLK, PXOP_HATCH_XOR, PXOP_MEAN, PXOP_MULT, PXOP_NOT_1ST_PIXEL_COLOR_KEY, PXOP_NOT_BLK_COLOR_KEY, PXOP_OR, PXOP_SUB, and PXOP_XOR.
Referenced by bindForeignMethod().