ERIS CORE: loadImageSurfaceCallback
loadImageSurfaceCallback()
void loadImageSurfaceCallback (WrenVM * vm)
VM callback for extention method.
Parameters
vm
Definition at line 579 of file AppWren.cpp.
{
   //(char* path,char* filename,int16_t x, int16_t y)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   bltMode bm;
   int32_t blt_mode_request = wrenGetSlotDouble(vm, 5);
   if (blt_mode_request == 0){ bm = BLT_COPY;
   }else if (blt_mode_request == 1){ bm = BLT_BLK_COLOR_KEY;
   }else if (blt_mode_request == 2){ bm = BLT_HATCH_BLK;
   }else if (blt_mode_request == 3){ bm = BLT_HATCH_XOR;
   }else if (blt_mode_request == 4){ bm = BLT_ADD;
   }else if (blt_mode_request == 5){ bm = BLT_SUB;
   }else if (blt_mode_request == 6){ bm = BLT_MULT;
   }else if (blt_mode_request == 7){ bm = BLT_DIV;
   }else if (blt_mode_request == 8){ bm = BLT_AND;
   }else if (blt_mode_request == 9){ bm = BLT_OR;
   }else if (blt_mode_request == 10){bm = BLT_XOR;
   }else return;
   if(app->useNativeFS){
     app->bltSD2Surface(wrenGetSlotString(vm,1),wrenGetSlotString(vm,2),wrenGetSlotDouble(vm, 3),wrenGetSlotDouble(vm, 4),bm);
   }else{
     app->bltRAMDrive2Surface(wrenGetSlotString(vm,1),wrenGetSlotString(vm,2),wrenGetSlotDouble(vm, 3),wrenGetSlotDouble(vm, 4),bm);
   }
 }
References BLT_ADD, BLT_AND, BLT_BLK_COLOR_KEY, BLT_COPY, BLT_DIV, BLT_HATCH_BLK, BLT_HATCH_XOR, BLT_MULT, BLT_OR, BLT_SUB, BLT_XOR, AppWren::bltRAMDrive2Surface(), AppWren::bltSD2Surface(), AppManager::getAppByName(), AppManager::getInstance(), and AppWren::useNativeFS.
Referenced by bindForeignMethod().