ERIS CORE: loadModule
loadModule()
WrenLoadModuleResult loadModule (WrenVM * vm, const char * name)
callback for the VM to request a module be loaded from the filesystem
Parameters
vm
name
Returns
WrenLoadModuleResult
Definition at line 124 of file AppWren.cpp.
{
   //callback for the VM to request a module be loaded from the filesystem
   Serial.printf("M VM: loadModule %s\n", name);
   WrenLoadModuleResult result = {0};
     result.onComplete = loadModuleComplete;
     result.source = getSourceForModule(name);
   return result;
 }
References getSourceForModule(), and loadModuleComplete().
Referenced by AppWren::startVM().