ERIS CORE: loadModuleComplete
loadModuleComplete()
static void loadModuleComplete (WrenVM * vm, const char * module, WrenLoadModuleResult result) static
callback function for the VM to indicate to the system that it's ok to release any memory allocated during the module load request
Parameters
vm
module
result
Definition at line 111 of file AppWren.cpp.
 {
   if(result.source) {
     //for example, if we used malloc to allocate
     //our source string, we use free to release it.
     //free((void*)result.source);
     AppManager* am = AppManager::getInstance();
     AppWren* app = (AppWren*)am->getAppByName("AppWren");
     return app->freeModuleSource();
   }
 }
References AppWren::freeModuleSource(), AppManager::getAppByName(), and AppManager::getInstance().
Referenced by loadModule().