ERIS CORE: fsimportFromSD
fsimportFromSD()
void fsimportFromSD (WrenVM * vm)
VM callback for extention method.
Parameters
vm
Definition at line 834 of file AppWren.cpp.
{
   //(src_path,src_file,dest_path,dst_file)
   char c[64];
   FsFile source; //The source is the SD card
   File dest; //The destination is the VM file system located in ext_ram
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   const char* src_path;
   const char* src_filename;
   const char* dst_path;
   const char* dst_filename;
   src_path = wrenGetSlotString(vm,1);
   src_filename = wrenGetSlotString(vm,2);
   dst_path = wrenGetSlotString(vm,3);
   dst_filename = wrenGetSlotString(vm,4);
   am->requestArmSetClock(600000000);
   am->getSD()->chdir(src_path);
   source = am->getSD()->open(src_filename,O_RDONLY);
   strcpy(c,dst_path);
   strcat(c,dst_filename);
   dest = app->wren_file_system.open(c,O_RDWR);
   //c[2]=0; //null termination
   for(int32_t i= source.available(); i > 0; i--){
     source.readBytes(c,1);//read char
     dest.write(c,1);
   }
   source.close();
   dest.close();
   wrenSetSlotDouble(vm,0,app->wren_file_system.totalSize());
 }
References AppManager::getAppByName(), AppManager::getInstance(), AppManager::getSD(), AppManager::requestArmSetClock(), and AppWren::wren_file_system.
Referenced by bindForeignMethod().