ERIS CORE: drawLineCallback
drawLineCallback()
void drawLineCallback (WrenVM * vm)
VM callback for extention method.
Parameters
vm
Definition at line 485 of file AppWren.cpp.
{
   //(int16_t start_x, int16_t start_y, int16_t end_x, int16_t end_y, int16_t r, int16_t g, int16_t b)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->drawLine(wrenGetSlotDouble(vm,1),wrenGetSlotDouble(vm,2),wrenGetSlotDouble(vm, 3),wrenGetSlotDouble(vm, 4),wrenGetSlotDouble(vm, 5), wrenGetSlotDouble(vm, 6), wrenGetSlotDouble(vm, 7));
 }
References AppWren::drawLine(), AppManager::getAppByName(), and AppManager::getInstance().
Referenced by bindForeignMethod().