ERIS CORE: getFocusCallback
getFocusCallback()
void getFocusCallback (WrenVM * vm)
Get the Focus Callback object.AppWren exported method which can be called from within a Wren VM instance.
Parameters
vm
Definition at line 232 of file AppWren.cpp.
{
   //(void)
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   app->getFocus();
 }
References AppManager::getAppByName(), AppWren::getFocus(), and AppManager::getInstance().
Referenced by bindForeignMethod().