ERIS CORE: audioDirectorGetFunctionListCallback
audioDirectorGetFunctionListCallback()
void audioDirectorGetFunctionListCallback (WrenVM * vm)
AudioDirector callback for wren.
Parameters
vm
Definition at line 335 of file AppWren.cpp.
{
   //()
   int num_slots;
     int slot = 0;
   AppManager* am = AppManager::getInstance();
   AppWren* app = (AppWren*)am->getAppByName("AppWren");
   AudioDirector* ad = app->getAudioDirector();
   num_slots = ad->getFunctionCount()+1;
   wrenEnsureSlots(vm, num_slots);
   wrenSetSlotNewList(vm, slot);
   while(++slot < num_slots) {
     char* cat_list;
     cat_list = ad->getFunctionListItem(slot-1);
         wrenSetSlotString(vm, slot, cat_list);
         wrenInsertInList(vm, 0, -1, slot);
     }
 }
References AppManager::getAppByName(), AppWren::getAudioDirector(), AudioDirector::getFunctionCount(), AudioDirector::getFunctionListItem(), and AppManager::getInstance().
Referenced by bindForeignMethod().