ERIS CORE: ControlButton::update
update()
void ControlButton::update () inline override protected virtual
Reimplemented from AppBaseClass.
Definition at line 73 of file controlButton.h.
{
         isDirty = true;
         if(isPressed==false && show_active == true && time_active > SHOW_ACTIVE_TIME_MILLISEC){
                 show_active = false;
                 isDirty = true;
                 time_active = 0;
         }
         if (!isDirty) return;
         if(usingImage){
             if(!imgloaded){
                 //allocate space
                 imgcache = new Surface(am->fastImgCacheSurfaceP, &am->sd, img_path, img_filename);
                 if(!imgcache){
                     Serial.println(F("M ERROR imgcache out of mem"));
                     Serial.flush();
                     delete(imgcache);
                     return;
                 }else{
                     draw->bltSD(imgcache->getSurfaceBufferP(), imgcache->getWidth(),img_path, img_filename,0,0,AT_NONE); //load img into cache
                     imgloaded = true;
                     return;
                 }
             } else{
                 draw->bltMem(am->displaySurfaceP,imgcache,x,y,AT_NONE);
             }
         }else{
             draw->fillRoundRect(x,y,w,h/2+3,3,am->data->read("UI_BUTTON_FILL_COLOR"));
             draw->fillRoundRect(x,y+h/2,w,h/2,3,am->data->read("UI_BUTTON_SHADE_COLOR"));
         }
         if (show_active){
             draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_ACTIVE_BORDER_COLOR")); //ILI9341_GREENYELLOW
         } else{
             draw->drawRoundRect(x,y,w,h,4,am->data->read("UI_BUTTON_INACTIVE_BORDER_COLOR"));//ILI9341_MAGENTA
         }
         if(!usingImage){
             draw->setTextColor(am->data->read("UI_BUTTON_TEXT_COLOR"));
             draw->setCursor(x+(w/2),y+(h/2),true);
             draw->setFont(Arial_9);
             draw->print(text);
         }
         isDirty = false;
     };
References AppBaseClass::am, Arial_9, AT_NONE, ILI9341_t3_ERIS::bltMem(), ILI9341_t3_ERIS::bltSD(), AppBaseClass::draw, Surface::getSurfaceBufferP(), Surface::getWidth(), AppBaseClass::h, img_filename, img_path, imgcache, imgloaded, isDirty, isPressed, show_active, SHOW_ACTIVE_TIME_MILLISEC, text, time_active, usingImage, AppBaseClass::w, AppBaseClass::x, and AppBaseClass::y.