ERIS CORE: AppAudioToPolyphonic::messageHandler
messageHandler()
void FASTRUN AppAudioToPolyphonic::messageHandler (AppBaseClass * sender, const char * message) inline virtual
receiver method for inter-app string based communication
Parameters
uval
fval
Reimplemented from AppBaseClass.
Definition at line 237 of file AppAudioToPolyphonic.h.
{
         if (am == NULL) return;
         if (sender->isName("SLIDER")){
           //erisAudioFilterBiquad* filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:3"));
           //filter->setLowpass(0,100.0 + (8000.0 * (slider->value/100.0)));
         }
         else if(sender->isName("SIN")){ //...or, can detect sender by name
           changeVoice(WAVEFORM_SINE);
         }
         else if(sender->isName("TRI")){
           changeVoice(WAVEFORM_TRIANGLE);
         }
         else if(sender->isName("SAW")){
           changeVoice(WAVEFORM_SAWTOOTH);
         }
         else if(sender->isName("REVSAW")){
           changeVoice(WAVEFORM_SAWTOOTH_REVERSE);
         }
         else if(sender->isName("SQUARE")){
           changeVoice(WAVEFORM_SQUARE);
         }
         else if(sender->isName("SCI")){
           erisAudioSynthWaveform* wav = (erisAudioSynthWaveform*) (ad->getAudioStreamObjByName("waveform:17"));
           if (wav!=NULL){
             wav->frequency(atoi(message));
             wav->amplitude(0.01);
           }
         }
         else if(sender->isName("BACK")){
            am->sendMessage(this,"AppWren","demo");
         }
     }
References AppBaseClass::ad, AppBaseClass::am, AudioSynthWaveformhd::amplitude(), changeVoice(), AudioSynthWaveformhd::frequency(), AudioDirector::getAudioStreamObjByName(), AppBaseClass::isName(), and AppManager::sendMessage().