ERIS CORE: AppAudioToPolyphonic::render
render()
void FLASHMEM AppAudioToPolyphonic::render () inline virtual
render loop
Reimplemented from AppBaseClass.
Definition at line 163 of file AppAudioToPolyphonic.h.
{
       if(ad!=NULL && am!= NULL){
         /*
         erisAudioEffectFreeverb* reverb = (erisAudioEffectFreeverb*)(ad->getAudioStreamObjByName("freeverb:1"));
         if (reverb != NULL){
           reverb->roomsize(am->data->readf(REVERB_ROOM_SIZE));
           reverb->damping(am->data->readf(REVERB_DAMPING));
         }
         erisAudioMixer4* mixer = (erisAudioMixer4*)(ad->getAudioStreamObjByName("mixer:2"));
         if (mixer != NULL){
           if(am->data->read(INPUT_PEAK) < 200){
             mixer->gain(0,0.1);
             mixer->gain(1,0.2);
             mixer->gain(2,0.2);
             mixer->gain(3,0.2);
           }else{
             mixer->gain(0,0.1);
             mixer->gain(1,0.2);
             mixer->gain(2,0.2);
             mixer->gain(3,0.3);
           }
         }
         erisAudioMixer4* mixer = (erisAudioMixer4*)(ad->getAudioStreamObjByName("mixer:6"));
         if (mixer != NULL){
           if(am->data->read(INPUT_PEAK) < 300){
             mixer->gain(0,0.3);
             mixer->gain(1,0.3);
             mixer->gain(2,0.0);
             mixer->gain(3,0.3);
           }else{
             mixer->gain(0,0.3);
             mixer->gain(1,0.3);
             mixer->gain(2,0.0);
             mixer->gain(3,0.3);
           }
         }
         */
         ControlSlider* cs = (ControlSlider*)am->getAppByName("SLIDER");
         if(cs!=NULL) cs->setValue((int16_t)(100 * ((float)am->data->read(INPUT_PEAK))/16384.0));
       }
     }
References AppBaseClass::ad, AppBaseClass::am, AppManager::data, AppManager::getAppByName(), SvcDataDictionary::read(), and ControlSlider::setValue().