ERIS CORE: AppAudioToPolyphonic::messageHandler
messageHandler()
void FLASHMEM AppAudioToPolyphonic::messageHandler (AppBaseClass * sender, const char * message) inline virtual
receiver method for inter-app string based communication
Parameters
uval
fval
Reimplemented from AppBaseClass.
Definition at line 198 of file AppAudioToPolyphonic.h.
{
         if (sender == slider){ //can detect message sender by ptr...
           //erisAudioFilterBiquad* filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:3"));
           //filter->setLowpass(0,100.0 + (8000.0 * (slider->value/100.0)));
         }
         else if(sender->isName("SIN")){ //...or, can detect sender by name
           changeVoice(WAVEFORM_SINE);
         }
         else if(sender->isName("TRI")){
           changeVoice(WAVEFORM_TRIANGLE);
         }
         else if(sender->isName("SAW")){
           changeVoice(WAVEFORM_SAWTOOTH);
         }
         else if(sender->isName("REVSAW")){
           changeVoice(WAVEFORM_SAWTOOTH_REVERSE);
         }
         else if(sender->isName("SQUARE")){
           changeVoice(WAVEFORM_SQUARE);
         }
         else if(sender->isName("SCI")){
           //Serial.print(F("M appExample::MessageHandler SCI param: "));
           //Serial.println(message);
           //Serial.flush();
           erisAudioSynthWaveform* wav = (erisAudioSynthWaveform*) (ad->getAudioStreamObjByName("waveform:17"));
           //AudioNoInterrupts();
           wav->frequency(atoi(message));
           wav->amplitude(0.01);
           //AudioNoInterrupts();
         }
         else if(sender->isName("TEST")){
           AudioNoInterrupts();
           ad->disconnect("fft1024:1 0");
           ad->disconnect("fft1024:2 0");
           ad->connect("waveform:17 0 fft1024:1 0");
           ad->connect("waveform:17 0 fft1024:2 0");
           AudioInterrupts();
         }
     }
References AppBaseClass::ad, AudioSynthWaveform::amplitude(), changeVoice(), AudioDirector::connect(), AudioDirector::disconnect(), AudioSynthWaveform::frequency(), AudioDirector::getAudioStreamObjByName(), AppBaseClass::isName(), and slider.