ERIS CORE: AppAudioToPolyphonic::initalize
initalize()
void FLASHMEM AppAudioToPolyphonic::initalize () inline
Definition at line 47 of file AppAudioToPolyphonic.h.
{
       sprintf(name, APPNAME);
       update_priority = 10; //set to higher priority
       id = 1;
       t_lastupdate = micros();
       x_end = 0;
       x_start = 0;
       y_end = 0;
       y_start = 0;
       x_last = 0;
       y_last = 0;
       y_last_scope = 0;
       erisAudioSynthNoisePink* pink = (erisAudioSynthNoisePink*) (ad->getAudioStreamObjByName("pink:1"));
       pink->amplitude(1.0);
       erisAudioFilterBiquad* filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:1"));
       filter->setLowpass(0, 1100);
       filter->setHighpass(1, 270);
       filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:2"));
       filter->setLowpass(0, 300);
       filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:3"));
       filter->setLowpass(0,8052);
       filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:4"));
       filter->setLowpass(0,18400);
       filter = (erisAudioFilterBiquad*) (ad->getAudioStreamObjByName("biquad:5"));
       filter->setNotch(0,475,2.0);
       erisAudioEffectFreeverb* reverb = (erisAudioEffectFreeverb*)(ad->getAudioStreamObjByName("freeverb:1"));
       am->data->create("REVERB_ROOM_SIZE",(float32_t)0.88);
       am->data->create("REVERB_DAMPING",(float32_t)0.37);
       reverb->roomsize(am->data->readf("REVERB_ROOM_SIZE"));
       reverb->damping(am->data->readf("REVERB_DAMPING"));
       erisAudioMixer4* mix = (erisAudioMixer4*)(ad->getAudioStreamObjByName("mixer:1"));
       mix->gain(0,1.0);
       mix->gain(1,0.40);
       mix->gain(3,0.40);
       output_gate = 1.0;
       erisAudioEffectDelay* delay = (erisAudioEffectDelay*)(ad->getAudioStreamObjByName("delay:1"));
       delay->delay(0,30);
       delay->delay(1,0);
       delay->delay(2,0);
       delay->delay(3,100);
       mix = (erisAudioMixer4*)(ad->getAudioStreamObjByName("mixer:2"));
       mix->gain(0,0.3);
       mix->gain(1,0.001);
       mix->gain(2,0.0001);
       mix->gain(3,0.7);
       //oscope = new AppScope;
       oscope.setWidgetPosition(5,5);
       oscope.setWidgetDimension(110,50);
       oscope.setPosition(5,20);
       oscope.setDimension(315,100);
       oscope.setParent(this);
       //cqt = new AppCQT;
       cqt.setWidgetPosition(125,5);
       cqt.setWidgetDimension(SCREEN_WIDTH-10-125,50);
       cqt.setParent(this);
       slider = new ControlSlider(this);
       slider->setWidgetPosition(0,65);
       slider->setWidgetDimension(SCREEN_WIDTH,10);
       slider->setName("SLIDER");
       slider->setText("");
       slider->setValue(0);
       uint8_t si = 0;
       uint16_t bx = 5;
       uint16_t by = 90;
       for (uint16_t i=0;i<sizeof(s)/16;i+=1){
         button = new ControlButton(this); //reuse the button var to create many instances
         if(bx>(SCREEN_WIDTH-78)){
           bx=5;by+=78;
         }
         button->setWidgetPosition(bx,by);
         button->setWidgetDimension(66,66);
         button->setName(s[si]);
         button->setText(s[si]);
         button->setImage("/I/U/I",p[si++]);
         bx+=78;
       }
     }
References AppBaseClass::ad, AppBaseClass::am, button, cqt, SvcDataDictionary::create(), AppManager::data, AudioDirector::getAudioStreamObjByName(), AppBaseClass::name, oscope, output_gate, p, SvcDataDictionary::readf(), s, AppBaseClass::setDimension(), ControlButton::setImage(), AppBaseClass::setName(), AppBaseClass::setParent(), AppBaseClass::setPosition(), ControlButton::setText(), ControlSlider::setText(), ControlSlider::setValue(), AppBaseClass::setWidgetDimension(), AppBaseClass::setWidgetPosition(), slider, t_lastupdate, AppBaseClass::update_priority, x_end, x_last, x_start, y_end, y_last, y_last_scope, and y_start.
Referenced by AppAudioToPolyphonic().