ERIS CORE: AppAudioToPolyphonic::makeAudioConnections
makeAudioConnections()
void FLASHMEM AppAudioToPolyphonic::makeAudioConnections () inline
Definition at line 317 of file AppAudioToPolyphonic.h.
{
       if (ad == NULL) return;
       AudioNoInterrupts();
       ad->disconnectAll();
       //input to input amplifier
       ad->connect("i2s-in:1 1 amp:2 0");
       //amplified input -> filter -> master mixer
       ad->connect("amp:2 0 biquad:4 0");
       //ad->connect("amp:2 0 mixer:1 1");
       ad->connect("biquad:4 0 mixer:1 2");
       //master mixer -> output amp
       ad->connect("mixer:1 0 amp:1 0");
       ad->connect("amp:1 0 i2s-out:1 0");
       //16 input bank bus mixer structure (4in x 4blocks)
       ad->connect("console:1 0 mixer:6 0");
       ad->connect("console:2 0 mixer:6 1");
       //bus output to filter -> reverb -> master mixer
       //ad->connect("mixer:6 0 amp:1 0");
       ad->connect("mixer:6 0 biquad:3 0");
       ad->connect("biquad:3 0 freeverb:1 0");
       ad->connect("freeverb:1 0 mixer:1 4");
       ad->connect("freeverb:1 0 delay:1 0");
       //filtered bus mixer -> master mixer
       ad->connect("biquad:3 0 mixer:1 0");
       //connect the oscillators to console 1
       ad->connect("waveform:1 0 console:1 0");
       ad->connect("waveform:2 0 console:1 1");
       ad->connect("waveform:3 0 console:1 2");
       ad->connect("waveform:4 0 console:1 3");
       ad->connect("waveform:5 0 console:1 4");
       ad->connect("waveform:6 0 console:1 5");
       ad->connect("waveform:7 0 console:1 6");
       ad->connect("waveform:8 0 console:1 7");
       ad->connect("waveform:9 0 console:2 0");
       ad->connect("waveform:10 0 console:2 1");
       ad->connect("waveform:11 0 console:2 2");
       ad->connect("waveform:12 0 console:2 3");
       ad->connect("waveform:13 0 console:2 4");
       ad->connect("waveform:14 0 console:2 5");
       ad->connect("waveform:15 0 console:2 6");
       ad->connect("waveform:16 0 console:2 7");
       //fft connections
       ad->connect("amp:2 0 biquad:2 0");
       ad->connect("biquad:1 0 fft1024:1 0"); //lp filter
       ad->connect("amp:2 0 biquad:1 0");
       ad->connect("biquad:2 0 fft1024:2 0"); //lp filter
       //input amp-> scope ch1
       ad->connect("amp:2 0 scope:1 0");
       //filtered bus mixer output -> scope ch2
       ad->connect("biquad:3 0 scope:1 1");
       //delay connections
       ad->connect("delay:1 0 mixer:2 0");
       ad->connect("delay:1 1 mixer:2 1");
       ad->connect("delay:1 2 mixer:2 2");
       ad->connect("delay:1 3 mixer:2 3");
       ad->connect("mixer:2 0 biquad:5 0");
       ad->connect("biquad:5 0 mixer:1 3");
       AudioInterrupts();
     }
References AppBaseClass::ad, AudioDirector::connect(), and AudioDirector::disconnectAll().
Referenced by onFocus().