ERIS CORE: LZ4_compressBound
LZ4_compressBound()
LZ4LIB_API int LZ4_compressBound (int inputSize)
LZ4_compressBound() : Provides the maximum size that LZ4 compression may output in a "worst case" scenario (input data not compressible) This function is primarily useful for memory allocation purposes (destination buffer size). Macro LZ4_COMPRESSBOUND() is also provided for compilation-time evaluation (stack memory allocation for example). Note that LZ4_compress_default() compresses faster when dstCapacity is >= LZ4_compressBound(srcSize) inputSize : max supported value is LZ4_MAX_INPUT_SIZE return : maximum output size in a "worst case" scenario or 0, if input size is incorrect (too large or negative)
Definition at line 682 of file lz4.c.
 { return LZ4_COMPRESSBOUND(isize); }
References isize, and LZ4_COMPRESSBOUND.
Referenced by LZ4_compress(), LZ4_compress_continue(), LZ4_compress_destSize_extState(), LZ4_compress_fast_extState(), LZ4_compress_fast_extState_fastReset(), and LZ4_compress_withState().