ERIS CORE: LZ4_compress_fast
LZ4_compress_fast()
LZ4LIB_API int LZ4_compress_fast (const char * src, char * dst, int srcSize, int dstCapacity, int acceleration)
LZ4_compress_fast() : Same as LZ4_compress_default(), but allows selection of "acceleration" factor. The larger the acceleration value, the faster the algorithm, but also the lesser the compression. It's a trade-off. It can be fine tuned, with each successive value providing roughly +~3% to speed. An acceleration value of "1" is the same as regular LZ4_compress_default() Values <= 0 will be replaced by LZ4_ACCELERATION_DEFAULT (currently == 1, see lz4.c). Values > LZ4_ACCELERATION_MAX will be replaced by LZ4_ACCELERATION_MAX (currently == 65537, see lz4.c).
Definition at line 1366 of file lz4.c.
 {
     int result;
 #if (LZ4_HEAPMODE)
     LZ4_stream_t* ctxPtr = (LZ4_stream_t*)ALLOC(sizeof(LZ4_stream_t));   /* malloc-calloc always properly aligned */
     if (ctxPtr == NULL) return 0;
 #else
     LZ4_stream_t ctx;
     LZ4_stream_t* const ctxPtr = &ctx;
 #endif
     result = LZ4_compress_fast_extState(ctxPtr, source, dest, inputSize, maxOutputSize, acceleration);
 #if (LZ4_HEAPMODE)
     FREEMEM(ctxPtr);
 #endif
     return result;
 }
References ALLOC, dest, FREEMEM, inputSize, LZ4_compress_fast_extState(), maxOutputSize, and source.
Referenced by SvcSerialCommandInterface::endLZ4Message(), LZ4_compress_default(), and SvcSerialCommandInterface::streamHandler().