ERIS CORE: LZ4_compress_fast_extState
LZ4_compress_fast_extState()
LZ4LIB_API int LZ4_compress_fast_extState (void * state, const char * src, char * dst, int srcSize, int dstCapacity, int acceleration)
Definition at line 1296 of file lz4.c.
 {
     LZ4_stream_t_internal* const ctx = & LZ4_initStream(state, sizeof(LZ4_stream_t)) -> internal_donotuse;
     assert(ctx != NULL);
     if (acceleration < 1) acceleration = LZ4_ACCELERATION_DEFAULT;
     if (acceleration > LZ4_ACCELERATION_MAX) acceleration = LZ4_ACCELERATION_MAX;
     if (maxOutputSize >= LZ4_compressBound(inputSize)) {
         if (inputSize < LZ4_64Klimit) {
             return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, 0, notLimited, byU16, noDict, noDictIssue, acceleration);
         } else {
             const tableType_t tableType = ((sizeof(void*)==4) && ((uptrval)source > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
             return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, 0, notLimited, tableType, noDict, noDictIssue, acceleration);
         }
     } else {
         if (inputSize < LZ4_64Klimit) {
             return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, maxOutputSize, limitedOutput, byU16, noDict, noDictIssue, acceleration);
         } else {
             const tableType_t tableType = ((sizeof(void*)==4) && ((uptrval)source > LZ4_DISTANCE_MAX)) ? byPtr : byU32;
             return LZ4_compress_generic(ctx, source, dest, inputSize, NULL, maxOutputSize, limitedOutput, tableType, noDict, noDictIssue, acceleration);
         }
     }
 }
References assert, byPtr, byU16, byU32, dest, inputSize, limitedOutput, LZ4_64Klimit, LZ4_ACCELERATION_DEFAULT, LZ4_ACCELERATION_MAX, LZ4_compress_generic(), LZ4_compressBound(), LZ4_initStream(), maxOutputSize, noDict, noDictIssue, notLimited, and source.
Referenced by LZ4_compress_destSize_extState(), LZ4_compress_fast(), LZ4_compress_limitedOutput_withState(), and LZ4_compress_withState().