ERIS CORE: LZ4_decompress_safe_usingDict
LZ4_decompress_safe_usingDict()
LZ4LIB_API int LZ4_decompress_safe_usingDict (const char * src, char * dst, int srcSize, int dstCapcity, const char * dictStart, int dictSize)
LZ4_decompress_*_usingDict() : These decoding functions work the same as a combination of LZ4_setStreamDecode() followed by LZ4_decompress_*_continue() They are stand-alone, and don't need an LZ4_streamDecode_t structure. Dictionary is presumed stable : it must remain accessible and unmodified during decompression. Performance tip : Decompression speed can be substantially increased when dst == dictStart + dictSize.
Definition at line 2430 of file lz4.c.
 {
     if (dictSize==0)
         return LZ4_decompress_safe(source, dest, compressedSize, maxOutputSize);
     if (dictStart+dictSize == dest) {
         if (dictSize >= 64 KB - 1) {
             return LZ4_decompress_safe_withPrefix64k(source, dest, compressedSize, maxOutputSize);
         }
         assert(dictSize >= 0);
         return LZ4_decompress_safe_withSmallPrefix(source, dest, compressedSize, maxOutputSize, (size_t)dictSize);
     }
     assert(dictSize >= 0);
     return LZ4_decompress_safe_forceExtDict(source, dest, compressedSize, maxOutputSize, dictStart, (size_t)dictSize);
 }
References assert, compressedSize, dest, KB, LZ4_decompress_safe(), LZ4_decompress_safe_forceExtDict(), LZ4_decompress_safe_withPrefix64k(), LZ4_decompress_safe_withSmallPrefix(), maxOutputSize, and source.