ERIS CORE: ILI9341_t3_ERIS::drawPixel
drawPixel()
void ILI9341_t3_ERIS::drawPixel (Surface * dest, int16_t x, int16_t y, uint16_t color)
Definition at line 149 of file ILI9341_t3_ERIS.cpp.
{
   uint16_t *dstBuffer;
   dstBuffer = dest->getSurfaceBufferP();
   dstBuffer[(y * dest->getWidth()) + x] = color;
 }
References Surface::getSurfaceBufferP(), and Surface::getWidth().
Referenced by AppWren::drawLine(), and AppWren::setPixel().