ERIS CORE: ILI9341_t3_ERIS::bltSDAnimationFullScreen
bltSDAnimationFullScreen()
void ILI9341_t3_ERIS::bltSDAnimationFullScreen (Animation * an)
renders an image chunk using the information provided by Animation parameter This function is used to render the animated backgrounds
Parameters
an
Definition at line 574 of file ILI9341_t3_ERIS.cpp.
{
   p_SD->chdir(an->getPath());
   file.open(an->getFileName(), O_READ);
   if (file.available() == 0){ //file not found
     Serial.print(F("M ILI9341_t3_ERIS::bltSDFullScreen File Not Found:"));
     Serial.println(an->getFileName());
     return;
   }
   //for (unsigned long i = (SCREEN_WIDTH * 64) ; i < (SCREEN_WIDTH * SCREEN_HEIGHT); i += 32){
   uint32_t chunk_size = (_width * _height)/ANIMATION_CHUNKS_PER_FRAME;
   uint32_t i = an->chunk * chunk_size;
   file.seekSet(15 + (i*2)); //skip the header - header will always be 15 bytes for full screen wallpaper
   file.read(&_pfbtft[i],chunk_size*2);
   //Serial.println()
   file.close();
 }
References Animation::chunk, file, Animation::getFileName(), Animation::getPath(), and p_SD.
Referenced by AppManager::update().