ERIS CORE: ILI9341_t3_ERIS::bltSDB
bltSDB()
void FLASHMEM ILI9341_t3_ERIS::bltSDB (uint16_t * dest_buffer, uint16_t dest_buffer_width, uint16_t dest_buffer_height, const char * path, const char * filename, int16_t x, int16_t y, bltMode blt_mode)
image block transfer from the SD card to a buffer at the given x,y coords
blt from the SD card to a memory buffer x,y destination
Parameters
dest_buffer
dest_buffer_width
dest_buffer_height
path
filename
x
y
blt_mode
Definition at line 1108 of file ILI9341_t3_ERIS.cpp.
{
   int16_t iy; // x & y index
   int16_t w;int16_t h; //width & height
   int16_t mx;        //left clip x offset
   int16_t nx;        //right clip x offset
   unsigned long ifb; //frame buffer index
   //uint16_t dwbf[SCREEN_WIDTH];//file read pixel row input buffer
   uint16_t dw;       //pixel data
   uint16_t first_pixel;
   char str[16];      //char buffer
   char *c;           //char pointer
   bool toggle = false;
   //pSD->chdir();
   if (!p_SD->chdir(path)){ //change file path
     Serial.print(F("M ILI9341_t3_ERIS::bltSD Path not found: "));
     Serial.println(path);
     return;
   }
   file.open(filename, O_READ);        //open image to read
   if (file.available() == 0){ //file not found
     Serial.print(F("M ILI9341_t3_ERIS::bltSD File Not Found: "));
     Serial.println(filename);
     //pSD->ls();
     return;
   }
   file.fgets(str,sizeof(str)); //read the header data
   file.fgets(str,sizeof(str)); //to get the image dimensions
   strtok(str," ");             //convert dimension text to numbers
   w = atol(str);
   c = strtok(NULL, " ");
   h = atol(c);
   //get first pixel value in case of color key by pixel
   file.readBytes((char*)&first_pixel,2);
   file.seek(file.position()-2L); //rewind the read pointer
   //clip in y dimension (top)
   if (y<0) { //throw away rows which are off screen
     for (iy = 0; iy < -1L * y; iy += 1L){ //for each off screen row
       file.seekCur(w*2L);
       h -= 1; //reduce bitmap hight by 1 row
     }
     y = 0; //set y pos to 0 for the remaining portion of the bitmap
   }
   for (iy = y; iy < y + h; iy += 1){ //for each row
     toggle ^= true;
     if (iy < dest_buffer_height) //clip in y dimension (bottom) - simply don't draw anything
     {
       int16_t r,g,b;
       mx = 0; nx = 0;
       if (x < 0L){file.seekCur(x * -2L);mx = -1L * x;} //clip in x dimension (left) - skip offscreen data
       ifb = (iy * dest_buffer_width) + x + mx; //32bit index
       if (x + w > dest_buffer_width){nx = x + w - dest_buffer_width;}//clip in x dimension (right) - truncate copy to screen bounds
       for (uint16_t z = 0; z < (w - mx - nx); z += 1){
         file.read(&dw,2);
         toggle ^= true;
       //
       //pixel operation section
       //
       if (pixel_op_enable){
         int16_t src_r,src_g,src_b;
         bool is_not_color_keyed;
         //#define CL(_r, _g, _b) ((((_r)&0xF8) << 8) | (((_g)&0xFC) << 3) | ((_b) >> 3))
         //unpack the color channels from the 565 RGB format
         src_r = 0xFF & (dw >> 8);
         if (src_r > 255) src_r = 255; //clip the max value for each channel
         src_g = 0xFF & (dw >> 3);
         if (src_g > 255) src_g = 255;
         src_b = 0xFF & (dw << 3);
         if ( (blt_mode == BLT_BLK_COLOR_KEY) && ((dw & 0xE79C) == 0) ) is_not_color_keyed = false;
         else if ( (blt_mode == BLT_1ST_PIXEL_COLOR_KEY) && (dw == first_pixel) ) is_not_color_keyed = false;
         else is_not_color_keyed = true;
         switch(pixel_op){
           case PXOP_1ST_PIXEL_COLOR_KEY:
             if (is_not_color_keyed) dw = pixel_op_param;
             break;
           case PXOP_BLK_COLOR_KEY:
             if (is_not_color_keyed) dw = pixel_op_param;
             break;
           case PXOP_HATCH_BLK:
             if (toggle && is_not_color_keyed) dw = 0;
             break;
           case PXOP_HATCH_XOR:
               if (toggle && is_not_color_keyed) dw = pixel_op_param^dw;
             break;
           case PXOP_COPY:
             if (is_not_color_keyed) dw = pixel_op_param; //note: same result as a fill function - could be used for benchmarking
             break;
           case PXOP_ADD:
             if (is_not_color_keyed) dw = CL(src_r + pixel_op_param_r,src_g + pixel_op_param_g, src_b + pixel_op_param_b);
             break;
           case PXOP_AND:
             if (is_not_color_keyed) dw = CL(src_r & pixel_op_param_r,src_g & pixel_op_param_g, src_b & pixel_op_param_b);
             break;
           case PXOP_DIV:
             if (is_not_color_keyed) dw = CL(src_r / pixel_op_param_r,src_g / pixel_op_param_g, src_b / pixel_op_param_b);
             break;
           case PXOP_MEAN:
             if (is_not_color_keyed) dw = CL((src_r + pixel_op_param_r)/2,(src_g + pixel_op_param_g)/2, (src_b + pixel_op_param_b)/2);
             break;
           case PXOP_MULT:
             if (is_not_color_keyed) dw = CL(src_r * pixel_op_param_r,src_g * pixel_op_param_g, src_b * pixel_op_param_b);
             break;
           case PXOP_OR:
             if (is_not_color_keyed) dw = CL(src_r | pixel_op_param_r,src_g | pixel_op_param_g, src_b | pixel_op_param_b);
             break;
           case PXOP_SUB:
             if (is_not_color_keyed) dw = CL(src_r - pixel_op_param_r,src_g - pixel_op_param_g, src_b - pixel_op_param_b);
             break;
           case PXOP_XOR:
             if (is_not_color_keyed) dw = CL(src_r ^ pixel_op_param_r,src_g ^ pixel_op_param_g, src_b ^ pixel_op_param_b);
             break;
           case PXOP_NOT_1ST_PIXEL_COLOR_KEY:
             if (!is_not_color_keyed) dw = pixel_op_param;
             break;
           case PXOP_NOT_BLK_COLOR_KEY:
             if (!is_not_color_keyed) dw = pixel_op_param;
             break;
           //default:
             //dw = dw;//unknown op - just read the pixel
         };
       }//else dw = dw; //pixel op disabled so simply read the source pixel
         //bit transfer operation
         uint32_t write_index;
         write_index = ifb + z;
         if (blt_mode == BLT_COPY){
           dest_buffer[write_index] = dw;
         }else if (blt_mode == BLT_BLK_COLOR_KEY && ((dw & 0xE79C) != 0)){dest_buffer[write_index] = dw;
         }else if (blt_mode == BLT_HATCH_BLK){
           if ((dw & 0xE79C) != 0){ dest_buffer[write_index] = dw;
           } else if (toggle) dest_buffer[write_index] = 0; //pFB[i] ^= pFB[i];
         }else if (blt_mode == BLT_HATCH_XOR){
           if ((dw & 0xE79C) != 0) dest_buffer[write_index] = dw^dest_buffer[write_index];
           else if (toggle) dest_buffer[write_index] = dest_buffer[write_index];
         }else if (blt_mode == BLT_ADD){
           r = (dest_buffer[write_index] >> 8) + (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) + (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) + (0xFF & (dw << 3));
           if(r>0xFF) r = 0xFF; //clip the result to 8bit
           if(g>0xFF) g = 0xFF;
           if(b>0xFF) b = 0xFF;
           dest_buffer[write_index] = CL(r,g,b); //convert back to 565 format and write the result
         }else if (blt_mode == BLT_SUB){
           r = (dest_buffer[write_index] >> 8) - (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) - (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) - (0xFF & (dw << 3));
           if (r < 0) r = 0; //clamp the result to zero
           if (g < 0) g = 0;
           if (b < 0) b = 0;
           dest_buffer[write_index] = CL(r,g,b);
         }else if (blt_mode == BLT_MULT){
           r = (dest_buffer[write_index] >> 8) * (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) * (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) * (0xFF & (dw << 3));
           if (r > 255) r = 255; //clip the max value for each channel
           if (g > 255) g = 255;
           if (b > 255) b = 255;
           dest_buffer[write_index] = CL(r,g,b);
         }else if (blt_mode == BLT_DIV){
           r = (dest_buffer[write_index] >> 8) / (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) / (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) / (0xFF & (dw << 3));
           if (r > 255) r = 255; //clip the max value for each channel
           if (g > 255) g = 255;
           if (b > 255) b = 255;
           dest_buffer[write_index] = CL(r,g,b);
         }else if (blt_mode == BLT_AND){
           r = (dest_buffer[write_index] >> 8) & (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) & (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) & (0xFF & (dw << 3));
           dest_buffer[write_index] = CL(r,g,b);
         }else if (blt_mode == BLT_OR){
           r = (dest_buffer[write_index] >> 8) | (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) | (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) | (0xFF & (dw << 3));
           dest_buffer[write_index] = CL(r,g,b);
         }else if (blt_mode == BLT_XOR){
           r = (dest_buffer[write_index] >> 8) ^ (0xFF & (dw >> 8));
           g = (dest_buffer[write_index] >> 3) ^ (0xFF & (dw >> 3));
           b = (dest_buffer[write_index] << 3) ^ (0xFF & (dw << 3));
           dest_buffer[write_index] = CL(r,g,b);
         }else if (blt_mode == BLT_MEAN){
           q7_t res[3];
           q7_t a[2];
           a[0] = (0x7F & (dest_buffer[write_index] >> 8));
           a[1] = (0x7F & (dw >> 8));
           arm_mean_q7(a,2,&res[0]);
           a[0] = (0x7F & (dest_buffer[write_index] >> 3));
           a[1] = (0x7F & (dw >> 3));
           arm_mean_q7(a,2,&res[1]);
           a[0] = (0x7F & (dest_buffer[write_index] << 3));
           a[1] = (0x7F & (dw << 3));
           arm_mean_q7(a,2,&res[2]);
           dest_buffer[write_index] = CL(res[0],res[1],res[2]);
         }else if (blt_mode == BLT_1ST_PIXEL_COLOR_KEY){
           if (dw != first_pixel) dest_buffer[write_index] = dw;
         }
       }
       if (x + w > dest_buffer_width){file.seekCur( (x + w - dest_buffer_width) * 2);} //clip in x dimension (right) - skip unused data
     }
     else{
       //since y index is now off screen close the file and return
       file.close();
       return;
     }
   }
   file.close();
 }
References BLT_1ST_PIXEL_COLOR_KEY, BLT_ADD, BLT_AND, BLT_BLK_COLOR_KEY, BLT_COPY, BLT_DIV, BLT_HATCH_BLK, BLT_HATCH_XOR, BLT_MEAN, BLT_MULT, BLT_OR, BLT_SUB, BLT_XOR, file, p_SD, pixel_op, pixel_op_enable, pixel_op_param, pixel_op_param_b, pixel_op_param_g, pixel_op_param_r, PXOP_1ST_PIXEL_COLOR_KEY, PXOP_ADD, PXOP_AND, PXOP_BLK_COLOR_KEY, PXOP_COPY, PXOP_DIV, PXOP_HATCH_BLK, PXOP_HATCH_XOR, PXOP_MEAN, PXOP_MULT, PXOP_NOT_1ST_PIXEL_COLOR_KEY, PXOP_NOT_BLK_COLOR_KEY, PXOP_OR, PXOP_SUB, and PXOP_XOR.
Referenced by bltSD(), AppWren::bltSD2Surface(), and ControlButton::render().