ERIS CORE: ILI9341_t3_ERIS Class Reference
ILI9341_t3_ERIS Class Reference
#include <ILI9341_t3_ERIS.h>
Public Member Functions
ILI9341_t3_ERIS (uint8_t cs, uint8_t dc, uint8_t rst=255, uint8_t mosi=11, uint8_t sclk=13, uint8_t miso=12)
void begin ()
void bltMem (Surface *dest, Surface *source, int16_t x, int16_t y, bltAlphaType alpha_type)
void bltSD (const char *path, const char *filename, int16_t x, int16_t y, bltAlphaType alpha_type)
void bltSD (uint16_t *dest_buffer, uint16_t dest_buffer_width, const char *path, const char *filename, int16_t x, int16_t y, bltAlphaType alpha_type)
void bltSDAnimationFullScreen (Animation *an)
void bltSDFullScreen (const char *filename)
bool busy ()
void drawFastHLine (Surface *dest, int16_t x, int16_t y, int16_t w, uint16_t color)
void drawFastVLine (Surface *dest, int16_t x, int16_t y, int16_t h, uint16_t color)
void drawPixel (Surface *dest, int16_t x, int16_t y, uint16_t color)
void fillRect (Surface *dest, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void fillRectHGradient (Surface *dest, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color1, uint16_t color2)
void fillRectVGradient (Surface *dest, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color1, uint16_t color2)
void fillScreenHGradient (Surface *dest, uint16_t color1, uint16_t color2)
void fillScreenVGradient (Surface *dest, uint16_t color1, uint16_t color2)
void fillSurface (Surface *dest, uint16_t color)
uint32_t getFrameAddress ()
uint16_t readPixel (Surface *dest, int16_t x, int16_t y)
void setPWMPin (uint8_t pin)
void setSD (SdFs *ptr)
bool updateScreenAsyncFrom (ILI9341_t3_ERIS *draw, bool update_cont)
Protected Attributes
uint8_t backlight
FsFile file
uint16_t * pFB
SdFs * pSD
uint32_t tft_read_speed
uint32_t tft_write_speed
Detailed Description
Definition at line 207 of file ILI9341_t3_ERIS.h.
Constructor & Destructor Documentation
ILI9341_t3_ERIS()
ILI9341_t3_ERIS::ILI9341_t3_ERIS (uint8_t cs, uint8_t dc, uint8_t rst = 255, uint8_t mosi = 11, uint8_t sclk = 13, uint8_t miso = 12) inline
Definition at line 210 of file ILI9341_t3_ERIS.h.
                                                                                                                      : ILI9341_t3n(cs,dc,rst,mosi,sclk,miso){
             //_SPI_CLOCK = 1000000;
             tft_write_speed = 72000000;
             tft_read_speed = 20000000;
             pSD = NULL;
             backlight = 0;
             pFB = NULL;
         };
References backlight, pFB, pSD, tft_read_speed, and tft_write_speed.
Member Function Documentation
begin()
void FLASHMEM ILI9341_t3_ERIS::begin ()
Definition at line 65 of file ILI9341_t3_ERIS.cpp.
{
     ILI9341_t3n::begin(tft_write_speed,tft_read_speed);
     //setFrameBuffer(FB1);
     //useFrameBuffer(true);
     fillScreen(ILI9341_BLACK);
     //pFB = 0;//FB1;
     //try and force a second buffer
     //setFrameBuffer(FB2);
     //useFrameBuffer(true);
     //fillScreen(ILI9341_PURPLE);
     //pFB2 = 0;//FB2;
     //setClock(30000000); //110000000
     setClipRect();
     setOrigin();
     //fillScreen(ILI9341_RED);
     setTextColor(CL(174, 143, 255));
     setTextSize(1);
     setRotation(1);
     println("Online...");
     updateScreen();
     dmabusy=false;
 }
References dmabusy, tft_read_speed, and tft_write_speed.
bltMem()
void FLASHMEM ILI9341_t3_ERIS::bltMem (Surface * dest, Surface * source, int16_t x, int16_t y, bltAlphaType alpha_type)
Definition at line 99 of file ILI9341_t3_ERIS.cpp.
{
   bool toggle = false;
   int16_t source_x,source_y, dest_x,dest_y;
   uint32_t read_index,write_index;
   uint16_t *srcBuffer;
   uint16_t *dstBuffer;
   srcBuffer = source->getSurfaceBufferP();
   dstBuffer = dest->getSurfaceBufferP();
   //check for null
   if (!srcBuffer) return;
   if (!dstBuffer) return;
   //check for off surface blt attempt
   if ((pos_x > dest->getWidth()) || (0 > (dest->getWidth() + pos_x))) return;
   if ((pos_y > dest->getHeight()) || (0 > (dest->getHeight() + pos_y))) return;
   //for each pixel in the source buffer, write to the dest buffer if the x,y coords are within bounds
   for (source_y=0; source_y < source->getHeight();source_y +=1){
     for (source_x=0; source_x < source->getWidth();source_x +=1){
       //translate the source coords to the destination coords
       dest_x = pos_x + source_x;
       dest_y = pos_y + source_y;
       write_index = (dest_y * dest->getWidth()) + dest_x;
       read_index = (source_y * source->getWidth()) + source_x;
       if(dest_x < 320 && dest_x >= 0 && dest_y < 240 && dest_y >= 0){
         //if in bounds then ok to write
         if (AT_NONE == alpha_type){
           dstBuffer[write_index] = srcBuffer[read_index];
         }else if(AT_HATCHXOR){
           if (toggle) dstBuffer[write_index] = srcBuffer[read_index];
           toggle ^= true;
         }else if(AT_TRANS){
           //TODO: unpack both source and dest, average the rgb values, repack and store in dest
         }
       }
     }
   }
 }
References AT_HATCHXOR, AT_NONE, AT_TRANS, dest, and source.
Referenced by AppWren::update(), and ControlButton::update().
bltSD() [1/2]
void FLASHMEM ILI9341_t3_ERIS::bltSD (const char * path, const char * filename, int16_t x, int16_t y, bltAlphaType alpha_type)
Definition at line 156 of file ILI9341_t3_ERIS.cpp.
{
   bltSD(_pfbtft, 320, path, filename,x,y,alpha_type);
   return;
 }
References bltSD().
bltSD() [2/2]
void FLASHMEM ILI9341_t3_ERIS::bltSD (uint16_t * dest_buffer, uint16_t dest_buffer_width, const char * path, const char * filename, int16_t x, int16_t y, bltAlphaType alpha_type)
Definition at line 161 of file ILI9341_t3_ERIS.cpp.
{
   int16_t iy; // x & y index
   int16_t w;int16_t h; //width & height
   int16_t mx;        //left clip x offset
   int16_t nx;        //right clip x offset
   unsigned long ifb; //frame buffer index
   //uint16_t dwbf[320];//file read pixel row input buffer
   uint16_t dw;       //pixel data
   char str[16];      //char buffer
   char *c;           //char pointer
   bool toggle = false;
   //pSD->chdir();
   if (!pSD->chdir(path)){ //change file path
     Serial.print(F("M ILI9341_t3_ERIS::bltSD Path not found: "));
     Serial.println(path);
     return;
   }
   file.open(filename, O_READ);        //open image to read
   if (file.available() == 0){ //file not found
     Serial.print(F("M ILI9341_t3_ERIS::bltSD File Not Found: "));
     Serial.println(filename);
     //pSD->ls();
     return;
   }
   file.fgets(str,sizeof(str)); //read the header data
   file.fgets(str,sizeof(str)); //to get the image dimensions
   strtok(str," ");             //convert dimension text to numbers
   w = atol(str);
   c = strtok(NULL, " ");
   h = atol(c);
   //clip in y dimension (top)
   if (y<0) { //throw away rows which are off screen
     for (iy = 0; iy < -1L * y; iy += 1L){ //for each off screen row
       file.seekCur(w*2L);
       h -= 1; //reduce bitmap hight by 1 row
     }
     y = 0; //set y pos to 0 for the remaining portion of the bitmap
   }
   for (iy = y; iy < y + h; iy += 1){ //for each row
     toggle ^= true;
     if (iy < 240L) //clip in y dimension (bottom) - simply don't draw anything
     {
       mx = 0; nx = 0;
       if (x < 0L){file.seekCur(x * -2L);mx = -1L * x;} //clip in x dimension (left) - skip offscreen data
       ifb = (iy * dest_buffer_width) + x + mx; //32bit index
       if (x + w > dest_buffer_width){nx = x + w - dest_buffer_width;}//clip in x dimension (right) - truncate copy to screen bounds
       for (uint16_t z = 0; z < (w - mx - nx); z += 1){
         file.read(&dw,2);
         toggle ^= true;
         //if alpha is enabled mask any colors close to black
         if (alpha_type == AT_NONE){dest_buffer[ifb + z] = dw;}
         else if (alpha_type == AT_TRANS && (dw & 0xE79C) != 0){dest_buffer[ifb + z] = dw;}
         else if (alpha_type == AT_HATCHBLK){
           if ((dw & 0xE79C) != 0) dest_buffer[ifb + z] = dw;
           else if (toggle) dest_buffer[ifb + z] = 0; //pFB[i] ^= pFB[i];
         }
         else if (alpha_type == AT_HATCHXOR){
           if ((dw & 0xE79C) != 0) dest_buffer[ifb + z] = dw;
           else if (toggle) dest_buffer[ifb + z] = dest_buffer[ifb + z]^dest_buffer[ifb + z];
         }
       }
       if (x + w > dest_buffer_width){file.seekCur( (x + w - dest_buffer_width) * 2);} //clip in x dimension (right) - skip unused data
     }
     else{
       //since y index is now off screen close the file and return
       file.close();
       return;
     }
   }
   file.close();
 }
References AT_HATCHBLK, AT_HATCHXOR, AT_NONE, AT_TRANS, file, and pSD.
Referenced by bltSD(), and ControlButton::update().
bltSDAnimationFullScreen()
void ILI9341_t3_ERIS::bltSDAnimationFullScreen (Animation * an)
Definition at line 235 of file ILI9341_t3_ERIS.cpp.
{
   //full screen block transfer with no clipping - used for full screen images matching the screen resolution
   pSD->chdir(an->getPath());
   file.open(an->getFileName(), O_READ);
   if (file.available() == 0){ //file not found
     Serial.print(F("M ILI9341_t3_ERIS::bltSDFullScreen File Not Found:"));
     Serial.println(an->getFileName());
     return;
   }
   //for (unsigned long i = (320 * 64) ; i < (320 * 240); i += 32){
   uint32_t chunk_size = (320 * 240)/ANIMATION_CHUNKS_PER_FRAME;
   uint32_t i = an->chunk * chunk_size;
   file.seekSet(15 + (i*2)); //skip the header - header will always be 15 bytes for full screen wallpaper
   file.read(&_pfbtft[i],chunk_size*2);
   //Serial.println()
   file.close();
 }
References ANIMATION_CHUNKS_PER_FRAME, Animation::chunk, file, Animation::getFileName(), Animation::getPath(), and pSD.
bltSDFullScreen()
void ILI9341_t3_ERIS::bltSDFullScreen (const char * filename)
Definition at line 253 of file ILI9341_t3_ERIS.cpp.
{
   //full screen block transfer with no clipping - used for full screen images matching the screen resolution
   pSD->chdir("/I/U/W");
   file.open(filename, O_READ);
   if (file.available() == 0){ //file not found
     Serial.print(F("M ILI9341_t3_ERIS::bltSDFullScreen File Not Found:"));
     Serial.println(filename);
     pSD->ls();
     return;
   }
   file.seekSet(15); //skip the header - header will always be 15 bytes for full screen wallpaper
   //for (unsigned long i = (320 * 64) ; i < (320 * 240); i += 32){
   for (uint32_t i = 0; i < (320 * 240); i += 32){ //32,64
     file.read(&_pfbtft[i],64);
   }
   file.close();
 }
References file, and pSD.
busy()
bool ILI9341_t3_ERIS::busy () inline
Definition at line 229 of file ILI9341_t3_ERIS.h.
 {return _busy();} //(_dma_state & ILI9341_DMA_ACTIVE);}
References _busy().
drawFastHLine()
void ILI9341_t3_ERIS::drawFastHLine (Surface * dest, int16_t x, int16_t y, int16_t w, uint16_t color)
drawFastVLine()
void ILI9341_t3_ERIS::drawFastVLine (Surface * dest, int16_t x, int16_t y, int16_t h, uint16_t color)
drawPixel()
void ILI9341_t3_ERIS::drawPixel (Surface * dest, int16_t x, int16_t y, uint16_t color)
Definition at line 149 of file ILI9341_t3_ERIS.cpp.
{
   uint16_t *dstBuffer;
   dstBuffer = dest->getSurfaceBufferP();
   dstBuffer[(y * dest->getWidth()) + x] = color;
 }
References dest.
Referenced by AppWren::setPixel().
fillRect()
void ILI9341_t3_ERIS::fillRect (Surface * dest, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
fillRectHGradient()
void ILI9341_t3_ERIS::fillRectHGradient (Surface * dest, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color1, uint16_t color2)
fillRectVGradient()
void ILI9341_t3_ERIS::fillRectVGradient (Surface * dest, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color1, uint16_t color2)
fillScreenHGradient()
void ILI9341_t3_ERIS::fillScreenHGradient (Surface * dest, uint16_t color1, uint16_t color2)
fillScreenVGradient()
void ILI9341_t3_ERIS::fillScreenVGradient (Surface * dest, uint16_t color1, uint16_t color2)
fillSurface()
void ILI9341_t3_ERIS::fillSurface (Surface * dest, uint16_t color)
Definition at line 136 of file ILI9341_t3_ERIS.cpp.
{
   int16_t dest_x,dest_y;
   uint16_t *dstBuffer;
   uint32_t write_index;
   dstBuffer = dest->getSurfaceBufferP();
   for (dest_y=0; dest_y < dest->getHeight();dest_y +=1){
     for (dest_x=0; dest_x < dest->getWidth();dest_x +=1){
       write_index = (dest_y * dest->getWidth()) + dest_x;
       dstBuffer[write_index] = color;
     }
   }
 };
References dest.
getFrameAddress()
uint32_t ILI9341_t3_ERIS::getFrameAddress () inline
Definition at line 223 of file ILI9341_t3_ERIS.h.
 {return (uint32_t)(void *)_pfbtft;}
readPixel()
uint16_t ILI9341_t3_ERIS::readPixel (Surface * dest, int16_t x, int16_t y)
setPWMPin()
void ILI9341_t3_ERIS::setPWMPin (uint8_t pin)
Definition at line 58 of file ILI9341_t3_ERIS.cpp.
{
     backlight = pin;
     //pinMode(backlight, OUTPUT);
     analogWriteFrequency(backlight, 30000);
     analogWrite(backlight, 220);
 }
References backlight.
setSD()
void ILI9341_t3_ERIS::setSD (SdFs * ptr)
Definition at line 56 of file ILI9341_t3_ERIS.cpp.
 {pSD = ptr;}
References pSD.
updateScreenAsyncFrom()
bool ILI9341_t3_ERIS::updateScreenAsyncFrom (ILI9341_t3_ERIS * draw, bool update_cont)
Definition at line 16 of file ILI9341_t3_ERIS.cpp.
{
   bool rval;
   //Serial.printf("%u\n",(uint32_t)(void*)draw->_pfbtft);
   //Serial.flush();
   dmabusy=true;
   setFrameCompleteCB(&renderCompleteCB);
   rval= updateScreenAsync(false);
   return rval;
 }
References dmabusy, and renderCompleteCB().
Member Data Documentation
backlight
uint8_t ILI9341_t3_ERIS::backlight protected
Definition at line 252 of file ILI9341_t3_ERIS.h.
Referenced by ILI9341_t3_ERIS(), and setPWMPin().
file
FsFile ILI9341_t3_ERIS::file protected
Definition at line 250 of file ILI9341_t3_ERIS.h.
Referenced by bltSD(), bltSDAnimationFullScreen(), and bltSDFullScreen().
pFB
uint16_t* ILI9341_t3_ERIS::pFB protected
Definition at line 251 of file ILI9341_t3_ERIS.h.
Referenced by ILI9341_t3_ERIS().
pSD
SdFs* ILI9341_t3_ERIS::pSD protected
Definition at line 249 of file ILI9341_t3_ERIS.h.
Referenced by ILI9341_t3_ERIS(), bltSD(), bltSDAnimationFullScreen(), bltSDFullScreen(), and setSD().
tft_read_speed
uint32_t ILI9341_t3_ERIS::tft_read_speed protected
Definition at line 248 of file ILI9341_t3_ERIS.h.
Referenced by ILI9341_t3_ERIS(), and begin().
tft_write_speed
uint32_t ILI9341_t3_ERIS::tft_write_speed protected
Definition at line 247 of file ILI9341_t3_ERIS.h.
Referenced by ILI9341_t3_ERIS(), and begin().
The documentation for this class was generated from the following files:
ILI9341_t3_ERIS.h
ILI9341_t3_ERIS.cpp