ERIS CORE: ILI9341_t3_ERIS::printWithFont
printWithFont()
void FASTRUN ILI9341_t3_ERIS::printWithFont (const char * string_buffer, uint16_t x, uint16_t y, const char * font, uint16_t pt, LittleFS_RAM * file_system = NULL)
prints the string buffer using the provided sprite library name and pt size
Parameters
string_buffer
x
y
font
pt
useKernFile apply kerning using the font .krn file; default is disable (false)
file_system optional pointer to a LittleFS file system, otherwise the SD card is used
Definition at line 517 of file ILI9341_t3_ERIS.cpp.
{
   uint64_t position;
   const String end_of_index = "KEARNING\n";
   float fx;
   int32_t width,height;
   int16_t j;
   int16_t count;
   int16_t startx[128];
   int16_t stopx[128];
   int16_t kern_value;
   char wildcard[2];
   char terminator = '\n';
   char font_file_path[64];
   char font_file_path_only[64];
   char font_file_name[64];
   char font_kerning_file_path[64];
   char tmp[8];//tmp buffer to build the file name
   char *character;//[102];//storage for the loaded start stop x indexes from the kerning file
   String line;
   FsFile kern;
   File lfs_kern;
   //make sure the font exists
   if(file_system == NULL){
     strcpy(font_file_path,"/I/U/F/");
     strcat(font_file_path,font);
     strcat(font_file_path,"/");
     if (!p_SD->exists(font_file_path)){
       setCursor(0,10);
       print("FONT PATH NOT FOUND! ");
       return;
     }
   }else{
     strcpy(font_file_path,"/");
     strcat(font_file_path,font);
     strcat(font_file_path,"/");
     if (!file_system->exists(font_file_path)){
       setCursor(0,10);
       print("FONT PATH NOT FOUND!\n");
       print(font_file_path);
       return;
     }
   }
   strcpy(font_file_path_only,font_file_path);//capture the font file path only; used later to get the image size
   sprintf(tmp,"%2hu",pt);//build the kerning and font filenames; file name is just the pt number to two digits
   strcpy(font_file_name,tmp);//build the filename used to get the image size later
   strcat(font_file_name,".ile");
   strcat(font_file_path,tmp);//build the full paths with the filename included for both the kerning and image file
   strcpy(font_kerning_file_path,font_file_path);//copy
   strcat(font_file_path,".ile");//add the file name sufixes
   strcat(font_kerning_file_path,".krn");
   setTextSize(pt);
   //open the kerning file
   if(file_system == NULL){
     kern = p_SD->open(font_kerning_file_path,O_RDONLY);
     if (!kern) return;
   }else{
     lfs_kern = file_system->open(font_kerning_file_path,O_RDONLY);
     if (!lfs_kern){
       setCursor(0,10);
       println("kerning file not found.");
       print(font_kerning_file_path);
       return;
     }
   }
   //load the x start and stop indexes one time
   if(file_system == NULL){
     line = kern.readStringUntil(terminator,64);//throw away the header line
     line = kern.readStringUntil(terminator,64); //get the first record
   }else{
     line = lfs_kern.readStringUntil(terminator,64);//throw away the header line
     line = lfs_kern.readStringUntil(terminator,64); //get the first record
   }
   j = 0;
   character = (char*)extmem_malloc(256);
   do{
     count = sscanf(line.c_str(),"%c %hu %hu\n",&character[j],&startx[j],&stopx[j]); //load the coords
     j+=1;
     if(file_system == NULL){
       line = kern.readStringUntil(terminator,256);
     }else{
       line = lfs_kern.readStringUntil(terminator,256);
     }
   }while(count == 3);//j < 102 end of index reached
   //throw away the next line and save the file positions
   if(file_system == NULL){
     line = kern.readStringUntil(terminator,256);
     line = kern.readStringUntil(terminator,256);
     position = kern.position(); //save the position
   }else{
     line = lfs_kern.readStringUntil(terminator,256);
     line = lfs_kern.readStringUntil(terminator,256);
     position = lfs_kern.position(); //save the position
   }
   //get the font image size
   if(file_system == NULL){
     getImageSize(font_file_path_only,font_file_name, &width, &height);
   }else{
     getImageSize(font_file_path_only,font_file_name, &width, &height,file_system);
   }
   //now walk the string buffer and 'print'
   strcpy(wildcard,"*");
   fx = x;
   char last_c;
   last_c = ' ';
   for(int16_t i = 0; i < (int16_t)strlen(string_buffer);i++){
     char string_c;
     string_c = string_buffer[i]; //for each char
     kern_value = 0;
     //search for a kerning pair
     if(0){
       if(file_system == NULL){
           kern.seek(position);
           while(kern.available() > 0){
             line = kern.readStringUntil(terminator,256);
             if( (line.c_str()[0]==wildcard[0] && line.c_str()[1]==string_c) || (line.c_str()[0]==last_c && line.c_str()[1]==string_c)){
               char dummy[16];
               count = sscanf(line.c_str(),"%s %hu\n",&dummy,&kern_value); //load the kern value
               break;
             }
           }
       }else{
           lfs_kern.seek(position,SeekSet);
           while(lfs_kern.available() > 0){
             line = lfs_kern.readStringUntil(terminator,256);
             if( (line.c_str()[0]==wildcard[0] && line.c_str()[1]==string_c) | (line.c_str()[0]==last_c && line.c_str()[1]==string_c) ){
               char dummy[16];
               count = sscanf(line.c_str(),"%s %hu\n",&dummy,&kern_value); //load the kern value
               break;
             }
           }
       }
     }
     last_c = string_buffer[i];
     j = -1;
     do{
       //search the character to find the index for loading the start/stop x values
       j++;
       if (j>102) break;
     }while(string_c!=character[j]);
     //check stop_x it should be greater than zero.. if not the char was not found
     //else blt the font char
     if(j < 102 && string_c != ' '){
       fx -= kern_value/pt/6.0;
       if(file_system == NULL){
         bltArea2Buffer(_pfbtft,fx,y,SCREEN_WIDTH,SCREEN_HEIGHT,font_file_path,startx[j],0,stopx[j]-startx[j],height,BLT_BLK_COLOR_KEY,NULL);
       }else{
         bltArea2Buffer(_pfbtft,fx,y,SCREEN_WIDTH,SCREEN_HEIGHT,font_file_path,startx[j],0,stopx[j]-startx[j],height,BLT_BLK_COLOR_KEY,file_system);
       }
       fx += (stopx[j]-startx[j])+1;
     } else{
       fx += pt/2.0;
     }
   }
   extmem_free(character);
   if(file_system == NULL){
     kern.close();
   }else{
     lfs_kern.close();
   }
 }
References BLT_BLK_COLOR_KEY, bltArea2Buffer(), getImageSize(), and p_SD.
Referenced by printWithFontCallback().