ERIS CORE: ILI9341_t3_ERIS::fillSurface
fillSurface()
void FLASHMEM ILI9341_t3_ERIS::fillSurface (Surface * dest, uint16_t color, bltMode blt_mode = BLT_COPY)
Parameters
dest
color
Definition at line 300 of file ILI9341_t3_ERIS.cpp.
{
   int16_t dest_x,dest_y;
   uint16_t *dest_buffer;
   bool toggle, is_not_color_keyed;
   uint16_t dw, first_pixel,w;
   toggle = false;
   dest_buffer = dest->getSurfaceBufferP();
   first_pixel = dest_buffer[0];
   int16_t r,g,b;
   //#define CL(_r, _g, _b) ((((_r)&0xF8) << 8) | (((_g)&0xFC) << 3) | ((_b) >> 3))
   //unpack the color channels from the 565 RGB format
   r = 0xFF & (color >> 8);
   if (r > 255) r = 255; //clip the max value for each channel
   g = 0xFF & (color >> 3);
   if (g > 255) g = 255;
   b = 0xFF & (color << 3);
   dw = color;
   if ( (blt_mode == BLT_BLK_COLOR_KEY) && ((dw & 0xE79C) == 0) ) is_not_color_keyed = false;
       else is_not_color_keyed = true;
   w =  dest->getWidth();
   for (dest_y=0; dest_y < dest->getHeight();dest_y +=1){
     for (dest_x=0; dest_x < dest->getWidth();dest_x +=1){
       uint32_t write_index;
       toggle ^= toggle;
       write_index = (dest_y * w) + dest_x;
       if (blt_mode == BLT_COPY){
         dest_buffer[write_index] = dw;
       }else if (blt_mode == BLT_BLK_COLOR_KEY && ((dw & 0xE79C) != 0)){dest_buffer[write_index] = dw;
       }else if (blt_mode == BLT_HATCH_BLK){
         if ((dw & 0xE79C) != 0){ dest_buffer[write_index] = dw;
         } else if (toggle) dest_buffer[write_index] = 0; //pFB[i] ^= pFB[i];
       }else if (blt_mode == BLT_HATCH_XOR){
         if ((dw & 0xE79C) != 0) dest_buffer[write_index] = dw^dest_buffer[write_index];
         else if (toggle) dest_buffer[write_index] = dest_buffer[write_index];
       }else if (blt_mode == BLT_ADD){
         r = (dest_buffer[write_index] >> 8) + (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) + (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) + (0xFF & (dw << 3));
         if(r>0xFF) r = 0xFF; //clip the result to 8bit
         if(g>0xFF) g = 0xFF;
         if(b>0xFF) b = 0xFF;
         dest_buffer[write_index] = CL(r,g,b); //convert back to 565 format and write the result
       }else if (blt_mode == BLT_SUB){
         r = (dest_buffer[write_index] >> 8) - (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) - (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) - (0xFF & (dw << 3));
         if (r < 0) r = 0; //clamp the result to zero
         if (g < 0) g = 0;
         if (b < 0) b = 0;
         dest_buffer[write_index] = CL(r,g,b);
       }else if (blt_mode == BLT_MULT){
         r = (dest_buffer[write_index] >> 8) * (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) * (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) * (0xFF & (dw << 3));
         if (r > 255) r = 255; //clip the max value for each channel
         if (g > 255) g = 255;
         if (b > 255) b = 255;
         dest_buffer[write_index] = CL(r,g,b);
       }else if (blt_mode == BLT_DIV){
         r = (dest_buffer[write_index] >> 8) / (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) / (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) / (0xFF & (dw << 3));
         if (r > 255) r = 255; //clip the max value for each channel
         if (g > 255) g = 255;
         if (b > 255) b = 255;
         dest_buffer[write_index] = CL(r,g,b);
       }else if (blt_mode == BLT_AND){
         r = (dest_buffer[write_index] >> 8) & (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) & (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) & (0xFF & (dw << 3));
         dest_buffer[write_index] = CL(r,g,b);
       }else if (blt_mode == BLT_OR){
         r = (dest_buffer[write_index] >> 8) | (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) | (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) | (0xFF & (dw << 3));
         dest_buffer[write_index] = CL(r,g,b);
       }else if (blt_mode == BLT_XOR){
         r = (dest_buffer[write_index] >> 8) ^ (0xFF & (dw >> 8));
         g = (dest_buffer[write_index] >> 3) ^ (0xFF & (dw >> 3));
         b = (dest_buffer[write_index] << 3) ^ (0xFF & (dw << 3));
         dest_buffer[write_index] = CL(r,g,b);
       }else if (blt_mode == BLT_MEAN){
         q7_t res[3];
         q7_t a[2];
         a[0] = (0x7F & (dest_buffer[write_index] >> 8));
         a[1] = (0x7F & (dw >> 8));
         arm_mean_q7(a,2,&res[0]);
         a[0] = (0x7F & (dest_buffer[write_index] >> 3));
         a[1] = (0x7F & (dw >> 3));
         arm_mean_q7(a,2,&res[1]);
         a[0] = (0x7F & (dest_buffer[write_index] << 3));
         a[1] = (0x7F & (dw << 3));
         arm_mean_q7(a,2,&res[2]);
         dest_buffer[write_index] = CL(res[0],res[1],res[2]);
       }else if (blt_mode == BLT_1ST_PIXEL_COLOR_KEY){
         if (dw != first_pixel) dest_buffer[write_index] = dw;
       }else{
         dest_buffer[write_index] = dw;
       }
     }
   }
 };
References BLT_1ST_PIXEL_COLOR_KEY, BLT_ADD, BLT_AND, BLT_BLK_COLOR_KEY, BLT_COPY, BLT_DIV, BLT_HATCH_BLK, BLT_HATCH_XOR, BLT_MEAN, BLT_MULT, BLT_OR, BLT_SUB, BLT_XOR, Surface::getHeight(), Surface::getSurfaceBufferP(), and Surface::getWidth().
Referenced by AppWren::drawFill().