ERIS CORE: ILI9341_t3_ERIS::drawSurfaceLine
drawSurfaceLine()
void ILI9341_t3_ERIS::drawSurfaceLine (Surface * dest, int16_t start_x, int16_t start_y, int16_t end_x, int16_t end_y, uint16_t color)
Definition at line 167 of file ILI9341_t3_ERIS.cpp.
{
   uint16_t *dstBuffer;
   dstBuffer = dest->getSurfaceBufferP();
   uint16_t* save = _pfbtft;
   _pfbtft = dstBuffer;
   _width = dest->getWidth();
   _height = dest->getHeight();
   drawLine(start_x, start_y, end_x, end_y, color);
   _pfbtft = save;
   _width = 320;
   _height = 240;
 }
References Surface::getHeight(), Surface::getSurfaceBufferP(), and Surface::getWidth().
Referenced by AppWren::drawLine().