ERIS CORE: ILI9341_t3_ERIS::bltSurface2Surface
bltSurface2Surface()
void FASTRUN ILI9341_t3_ERIS::bltSurface2Surface (Surface * dest, int16_t dest_x, int16_t dest_y, Surface * source, int16_t from_x, int16_t from_y, int16_t from_width, int16_t from_height, bltMode blt_mode)
block transfer from source to dest with the given parameters
Parameters
dest
dest_x
dest_y
source
from_x
from_y
from_width
from_height
blt_mode
Definition at line 90 of file ILI9341_t3_ERIS.cpp.
{
   bool toggle = false;
   int16_t source_x,source_y, d_x,d_y;
   uint32_t read_index,write_index;
   uint16_t *srcBuffer;
   uint16_t *dest_buffer;
   uint16_t first_pixel;
   srcBuffer = source->getSurfaceBufferP();
   dest_buffer = dest->getSurfaceBufferP();
   //check for null
   if (!srcBuffer) return;
   if (!dest_buffer) return;
   //check for off surface blt attempt
   if ((dest_x > dest->getWidth()) || (0 > (dest->getWidth() + dest_x))) return;
   if ((dest_y > dest->getHeight()) || (0 > (dest->getHeight() + dest_y))) return;
   first_pixel = srcBuffer[0];//for first pixel mask
   if(0 && blt_mode == BLT_COPY){ //TODO WIP - PXP currently disabled
     //PXP TEST
     uint16_t dw,dh,first_pixel;
     dw = dest_x + from_width;
     if(dw>SCREEN_WIDTH) dw=SCREEN_WIDTH;
     dh = dest_y + from_height;
     if(dh>SCREEN_HEIGHT) dh=SCREEN_HEIGHT;
     PXP_input_buffer(srcBuffer, 2, source->getWidth(), source->getHeight());
     PXP_input_format(PXP_RGB565,0,0,0);
     PXP_input_position(dest_x, dest_y, dw, dh);
     PXP_input_background_color(0,0,0);
     PXP_overlay_buffer(srcBuffer, 2, source->getWidth()-1, source->getHeight()-1);
     PXP_overlay_format(PXP_RGB565,0,true,0,PXP_MERGEAS,false);
     PXP_overlay_color_key_low(0);
     PXP_overlay_color_key_high(20,20,20);
     PXP_overlay_position(dest_x, dest_y, dw, dh);
     PXP_output_buffer(dest_buffer, 2, dest->getWidth(), dest->getHeight());
     PXP_output_format();
     PXP_output_clip(SCREEN_WIDTH, SCREEN_HEIGHT);
     //PXP_flip_horizontally(true); //testing - for visual confirmation
     PXP_process();
     return;
   }else{
     //for each pixel by x,y coords...
     for (source_y=0; source_y < source->getHeight();source_y +=1){
       for (source_x=0; source_x < source->getWidth();source_x +=1){
         //translate the source coords to the destination coords and calculate the indexes
         d_x = dest_x + source_x;
         d_y = dest_y + source_y;
         write_index = (d_y * dest->getWidth()) + d_x;
         read_index = (source_y * source->getWidth()) + source_x;
         if(d_x < dest->getWidth() && d_x >= 0 && d_y < dest->getHeight() && d_y >= 0){ //bounds check
           uint16_t dw;
           int16_t r,g,b;
           toggle ^= true;//toggle for hatch operations
           //
           //pixel operation section
           //
           if (pixel_op_enable){
             int16_t src_r,src_g,src_b;
              //#define CL(_r, _g, _b) ((((_r)&0xF8) << 8) | (((_g)&0xFC) << 3) | ((_b) >> 3))
             //unpack the color channels from the 565 RGB format
             src_r = 0xFF & (srcBuffer[read_index] >> 8);
             if (src_r > 255) src_r = 255; //clip the max value for each channel
             src_g = 0xFF & (srcBuffer[read_index] >> 3);
             if (src_g > 255) src_g = 255;
             src_b = 0xFF & (srcBuffer[read_index] << 3);
             switch(pixel_op){
               case PXOP_1ST_PIXEL_COLOR_KEY:
                 if (first_pixel != srcBuffer[read_index]){
                   dw = srcBuffer[read_index];
                 } else dw = pixel_op_param;
                 break;
               case PXOP_BLK_COLOR_KEY:
                 if ((srcBuffer[read_index] & 0xE79C) == 0){
                   dw = srcBuffer[read_index];
                 } else dw = pixel_op_param;
                 break;
               case PXOP_HATCH_BLK:
                 if (toggle){
                    if ((srcBuffer[read_index] & 0xE79C) == 0){
                     dw = pixel_op_param;
                   }else dw = srcBuffer[read_index];
                 }else dw = 0;
                 break;
               case PXOP_HATCH_XOR:
                 if (toggle){
                    if ((srcBuffer[read_index] & 0xE79C) == 0){
                     dw = pixel_op_param;
                   }else dw = srcBuffer[read_index];
                 }else dw = pixel_op_param ^ srcBuffer[read_index];
                 break;
               case PXOP_COPY:
                 dw = pixel_op_param; //note: same result as a fill function - could be used for benchmarking
                 break;
               case PXOP_ADD:
                 dw = CL(src_r + pixel_op_param_r,src_g + pixel_op_param_g, src_b + pixel_op_param_b);
                 break;
               case PXOP_AND:
                 dw = CL(src_r & pixel_op_param_r,src_g & pixel_op_param_g, src_b & pixel_op_param_b);
                 break;
               case PXOP_DIV:
                 dw = CL(src_r / pixel_op_param_r,src_g / pixel_op_param_g, src_b / pixel_op_param_b);
                 break;
               case PXOP_MEAN:
                 dw = CL((src_r + pixel_op_param_r)/2,(src_g + pixel_op_param_g)/2, (src_b + pixel_op_param_b)/2);
                 break;
               case PXOP_MULT:
                 dw = CL(src_r * pixel_op_param_r,src_g * pixel_op_param_g, src_b * pixel_op_param_b);
                 break;
               case PXOP_OR:
                 dw = CL(src_r | pixel_op_param_r,src_g | pixel_op_param_g, src_b | pixel_op_param_b);
                 break;
               case PXOP_SUB:
                 dw = CL(src_r - pixel_op_param_r,src_g - pixel_op_param_g, src_b - pixel_op_param_b);
                 break;
               case PXOP_XOR:
                 dw = CL(src_r ^ pixel_op_param_r,src_g ^ pixel_op_param_g, src_b ^ pixel_op_param_b);
                 break;
               default:
                 dw = srcBuffer[read_index];//unknown op - just read the pixel
                 break;
             };
           }else dw = srcBuffer[read_index]; //pixel op disabled so simply read the source pixel
           //bit transfer operation
           if (blt_mode == BLT_COPY){
             dest_buffer[write_index] = dw;
           }else if (blt_mode == BLT_BLK_COLOR_KEY && ((dw & 0xE79C) != 0)){dest_buffer[write_index] = dw;
           }else if (blt_mode == BLT_HATCH_BLK){
             if ((dw & 0xE79C) != 0){ dest_buffer[write_index] = dw;
             } else if (toggle) dest_buffer[write_index] = 0; //pFB[i] ^= pFB[i];
           }else if (blt_mode == BLT_HATCH_XOR){
             if ((dw & 0xE79C) != 0) dest_buffer[write_index] = dw^dest_buffer[write_index];
             else if (toggle) dest_buffer[write_index] = dest_buffer[write_index];
           }else if (blt_mode == BLT_ADD){
             r = (dest_buffer[write_index] >> 8) + (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) + (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) + (0xFF & (dw << 3));
             if(r>0xFF) r = 0xFF; //clip the result to 8bit
             if(g>0xFF) g = 0xFF;
             if(b>0xFF) b = 0xFF;
             dest_buffer[write_index] = CL(r,g,b); //convert back to 565 format and write the result
           }else if (blt_mode == BLT_SUB){
             r = (dest_buffer[write_index] >> 8) - (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) - (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) - (0xFF & (dw << 3));
             if (r < 0) r = 0; //clamp the result to zero
             if (g < 0) g = 0;
             if (b < 0) b = 0;
             dest_buffer[write_index] = CL(r,g,b);
           }else if (blt_mode == BLT_MULT){
             r = (dest_buffer[write_index] >> 8) * (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) * (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) * (0xFF & (dw << 3));
             if (r > 255) r = 255; //clip the max value for each channel
             if (g > 255) g = 255;
             if (b > 255) b = 255;
             dest_buffer[write_index] = CL(r,g,b);
           }else if (blt_mode == BLT_DIV){
             r = (dest_buffer[write_index] >> 8) / (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) / (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) / (0xFF & (dw << 3));
             if (r > 255) r = 255; //clip the max value for each channel
             if (g > 255) g = 255;
             if (b > 255) b = 255;
             dest_buffer[write_index] = CL(r,g,b);
           }else if (blt_mode == BLT_AND){
             r = (dest_buffer[write_index] >> 8) & (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) & (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) & (0xFF & (dw << 3));
             dest_buffer[write_index] = CL(r,g,b);
           }else if (blt_mode == BLT_OR){
             r = (dest_buffer[write_index] >> 8) | (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) | (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) | (0xFF & (dw << 3));
             dest_buffer[write_index] = CL(r,g,b);
           }else if (blt_mode == BLT_XOR){
             r = (dest_buffer[write_index] >> 8) ^ (0xFF & (dw >> 8));
             g = (dest_buffer[write_index] >> 3) ^ (0xFF & (dw >> 3));
             b = (dest_buffer[write_index] << 3) ^ (0xFF & (dw << 3));
             dest_buffer[write_index] = CL(r,g,b);
           }else if (blt_mode == BLT_MEAN){
             q7_t res[3];
             q7_t a[2];
             a[0] = (0x7F & (dest_buffer[write_index] >> 8));
             a[1] = (0x7F & (dw >> 8));
             arm_mean_q7(a,2,&res[0]);
             a[0] = (0x7F & (dest_buffer[write_index] >> 3));
             a[1] = (0x7F & (dw >> 3));
             arm_mean_q7(a,2,&res[1]);
             a[0] = (0x7F & (dest_buffer[write_index] << 3));
             a[1] = (0x7F & (dw << 3));
             arm_mean_q7(a,2,&res[2]);
             dest_buffer[write_index] = CL(res[0],res[1],res[2]);
           }else if (blt_mode == BLT_1ST_PIXEL_COLOR_KEY){
             if (dw != first_pixel) dest_buffer[write_index] = dw;
           }
         }
       }
     }
   }
 }
References BLT_1ST_PIXEL_COLOR_KEY, BLT_ADD, BLT_AND, BLT_BLK_COLOR_KEY, BLT_COPY, BLT_DIV, BLT_HATCH_BLK, BLT_HATCH_XOR, BLT_MEAN, BLT_MULT, BLT_OR, BLT_SUB, BLT_XOR, Surface::getHeight(), Surface::getSurfaceBufferP(), Surface::getWidth(), pixel_op, pixel_op_enable, pixel_op_param, pixel_op_param_b, pixel_op_param_g, pixel_op_param_r, PXOP_1ST_PIXEL_COLOR_KEY, PXOP_ADD, PXOP_AND, PXOP_BLK_COLOR_KEY, PXOP_COPY, PXOP_DIV, PXOP_HATCH_BLK, PXOP_HATCH_XOR, PXOP_MEAN, PXOP_MULT, PXOP_OR, PXOP_SUB, PXOP_XOR, PXP_input_background_color(), PXP_input_buffer(), PXP_input_format(), PXP_input_position(), PXP_output_buffer(), PXP_output_clip(), PXP_output_format(), PXP_overlay_buffer(), PXP_overlay_color_key_high(), PXP_overlay_color_key_low(), PXP_overlay_format(), PXP_overlay_position(), and PXP_process().
Referenced by AppWren::bltSurface2FrameBuffer(), AppWren::render(), and ControlButton::render().