ERIS CORE: ILI9341_t3_ERIS::drawSurfaceFill
drawSurfaceFill()
void ILI9341_t3_ERIS::drawSurfaceFill (Surface * dest, uint16_t color)
Definition at line 179 of file ILI9341_t3_ERIS.cpp.
{
   uint16_t *dstBuffer;
   dstBuffer = dest->getSurfaceBufferP();
   uint16_t* save = _pfbtft;
   _pfbtft = dstBuffer;
   _width = dest->getWidth();
   _height = dest->getHeight();
   fillScreen(color);
   _pfbtft = save;
   _width = SCREEN_WIDTH;
   _height = SCREEN_HEIGHT;
 }
References Surface::getHeight(), Surface::getSurfaceBufferP(), and Surface::getWidth().