ERIS CORE: ILI9341_t3_ERIS::fillSurface
fillSurface()
void FASTRUN ILI9341_t3_ERIS::fillSurface (Surface * dest, uint16_t color)
Parameters
dest
color
Definition at line 300 of file ILI9341_t3_ERIS.cpp.
{
   int16_t dest_x,dest_y;
   uint16_t *dstBuffer;
   uint32_t write_index;
   dstBuffer = dest->getSurfaceBufferP();
   for (dest_y=0; dest_y < dest->getHeight();dest_y +=1){
     for (dest_x=0; dest_x < dest->getWidth();dest_x +=1){
       write_index = (dest_y * dest->getWidth()) + dest_x;
       dstBuffer[write_index] = color;
     }
   }
 };
References Surface::getHeight(), Surface::getSurfaceBufferP(), and Surface::getWidth().
Referenced by AppWren::drawFill().