ERIS CORE: iostream.h File Reference
iostream.h File Reference
iostream class
#include "istream.h"
#include "ostream.h"
Classes
class iostream
Input/Output stream.
struct setfill
type for setfill manipulator
struct setprecision
type for setprecision manipulator
struct setw
type for setw manipulator
Functions
ostream & endl (ostream &os)
ostream & flush (ostream &os)
ostream & operator<< (ostream &os, const setfill &arg)
ostream & operator<< (ostream &os, const setprecision &arg)
ostream & operator<< (ostream &os, const setw &arg)
istream & operator>> (istream &is, const setprecision &arg)
istream & operator>> (istream &is, const setw &arg)
istream & operator>> (istream &obj, const setfill &arg)
istream & ws (istream &is)
Detailed Description
iostream class
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file iostream.h.
Function Documentation
endl()
ostream& endl (ostream & os) inline
insert endline
Parameters
[in] os The Stream
Returns
The stream
Definition at line 45 of file iostream.h.
{
   os.put('\n');
 #if ENDL_CALLS_FLUSH
   os.flush();
 #endif  // ENDL_CALLS_FLUSH
   return os;
 }
References ostream::flush(), and ostream::put().
flush()
ostream& flush (ostream & os) inline
flush manipulator
Parameters
[in] os The stream
Returns
The stream
Definition at line 56 of file iostream.h.
{
   os.flush();
   return os;
 }
References ostream::flush().
operator<<() [1/3]
ostream& operator<< (ostream & os, const setfill & arg) inline
setfill manipulator
Parameters
[in] os the stream
[in] arg set setfill object
Returns
the stream
Definition at line 78 of file iostream.h.
{
   os.fill(arg.c);
   return os;
 }
References setfill::c, and ios_base::fill().
operator<<() [2/3]
ostream& operator<< (ostream & os, const setprecision & arg) inline
setprecision manipulator
Parameters
[in] os the stream
[in] arg set setprecision object
Returns
the stream
Definition at line 108 of file iostream.h.
{
   os.precision(arg.p);
   return os;
 }
References setprecision::p, and ios_base::precision().
operator<<() [3/3]
ostream& operator<< (ostream & os, const setw & arg) inline
setw manipulator
Parameters
[in] os the stream
[in] arg set setw object
Returns
the stream
Definition at line 138 of file iostream.h.
{
   os.width(arg.w);
   return os;
 }
References setw::w, and ios_base::width().
operator>>() [1/3]
istream& operator>> (istream & is, const setprecision & arg) inline
setprecision manipulator
Parameters
[in] is the stream
[in] arg set setprecision object
Returns
the stream
Definition at line 117 of file iostream.h.
{
   is.precision(arg.p);
   return is;
 }
References is, and setprecision::p.
operator>>() [2/3]
istream& operator>> (istream & is, const setw & arg) inline
setw manipulator
Parameters
[in] is the stream
[in] arg set setw object
Returns
the stream
Definition at line 147 of file iostream.h.
{
   is.width(arg.w);
   return is;
 }
References is, and setw::w.
operator>>() [3/3]
istream& operator>> (istream & obj, const setfill & arg) inline
setfill manipulator
Parameters
[in] obj the stream
[in] arg set setfill object
Returns
the stream
Definition at line 87 of file iostream.h.
{
   obj.fill(arg.c);
   return obj;
 }
References setfill::c, and ios_base::fill().
ws()
istream& ws (istream & is) inline
Skip white space
Parameters
[in] is the Stream
Returns
The stream
Definition at line 37 of file iostream.h.
{
   is.skipWhite();
   return is;
 }
References is.