ERIS CORE: wren_opt_meta.h File Reference
wren_opt_meta.h File Reference
#include "wren_common.h"
#include "wren.h"
Functions
WrenForeignMethodFn wrenMetaBindForeignMethod (WrenVM *vm, const char *className, bool isStatic, const char *signature)
const char * wrenMetaSource ()
Function Documentation
wrenMetaBindForeignMethod()
WrenForeignMethodFn wrenMetaBindForeignMethod (WrenVM * vm, const char * className, bool isStatic, const char * signature)
Definition at line 73 of file wren_opt_meta.c.
 {
   // There is only one foreign method in the meta module.
   ASSERT(strcmp(className, "Meta") == 0, "Should be in Meta class.");
   ASSERT(isStatic, "Should be static.");
   if (strcmp(signature, "compile_(_,_,_)") == 0)
   {
     return metaCompile;
   }
   if (strcmp(signature, "getModuleVariables_(_)") == 0)
   {
     return metaGetModuleVariables;
   }
   ASSERT(false, "Unknown method.");
   return NULL;
 }
References ASSERT, metaCompile(), metaGetModuleVariables(), and NULL.
Referenced by findForeignMethod().
wrenMetaSource()
const char* wrenMetaSource ()
Definition at line 68 of file wren_opt_meta.c.
 {
   return metaModuleSource;
 }
Referenced by importModule().