ERIS CORE: ERISCore/lib/SdFat-master/src/SdCard/SdCardInfo.cpp File Reference
SdCardInfo.cpp File Reference
#include "SdCardInfo.h"
Macros
#define SD_CARD_ERROR(e, m) case SD_CARD_ERROR_##e: pr->print(F(#e)); break;
#define SD_CARD_ERROR(e, m) case SD_CARD_ERROR_##e: pr->print(F(m)); break;
Functions
void printSdErrorSymbol (print_t *pr, uint8_t code)
void printSdErrorText (print_t *pr, uint8_t code)
Macro Definition Documentation
SD_CARD_ERROR [1/2]
#define SD_CARD_ERROR (e, m) case SD_CARD_ERROR_##e: pr->print(F(#e)); break;
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 38 of file SdCardInfo.cpp.
SD_CARD_ERROR [2/2]
#define SD_CARD_ERROR (e, m) case SD_CARD_ERROR_##e: pr->print(F(m)); break;
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 38 of file SdCardInfo.cpp.
Function Documentation
printSdErrorSymbol()
void printSdErrorSymbol (print_t * pr, uint8_t code)
Definition at line 29 of file SdCardInfo.cpp.
{
   pr->print(F("SD_CARD_ERROR_"));
   switch (code) {
     SD_ERROR_CODE_LIST
     default: pr->print(F("UNKNOWN"));
   }
 }
References F, PrintBasic::print(), and SD_ERROR_CODE_LIST.
Referenced by SdBase< Vol >::printSdError().
printSdErrorText()
void printSdErrorText (print_t * pr, uint8_t code)
Definition at line 39 of file SdCardInfo.cpp.
{
   switch
   (code) {
     SD_ERROR_CODE_LIST
     default: pr->print(F("Unknown error"));
   }
 }
References F, PrintBasic::print(), and SD_ERROR_CODE_LIST.