ERIS CORE: a
a() [2/2]
technical modifications allowed The Licensor authorizes You to exercise the Licensed Rights in all media and formats whether now known or hereafter and to make technical modifications necessary to do so The Licensor waives and or agrees not to assert any right or authority to forbid You from making technical modifications necessary to exercise the Licensed including technical modifications necessary to circumvent Effective Technological Measures For purposes of this Public simply making modifications authorized by this Section() a (4)
Referenced by erisAudioAnalyzeFFT1024::sort_fftrr_by_cqt_bin(), erisAudioAnalyzeFFT1024::sort_fftrr_by_value(), and AppCQT::updateOscillatorBank().