ERIS CORE: AppScope::render
render()
void AppScope::render () inline protected virtual
render loop
Reimplemented from AppBaseClass.
Definition at line 30 of file AppScope.h.
                  {
         uint16_t y_last_scope;
         uint16_t y_last_scope_ch2;
         y_last_scope=h/2;
         y_last_scope_ch2=h/2;
         scale = 30000.0 / ((float)scope->getPeakValue() + 0.0001);
         if (scale > 10.0) scale = 10.0;
         am->data->update("OSCOPE_SCALE",scale);
         draw->fillRoundRect(x,y,w,h,3,CL(0,0,0));
         for (int16_t i=0;i<w;i++){
             int16_t v;
             float f;
             uint16_t ch1,ch2;
             v = scope->read(0,i) * scale;
             f = ((v * 0.000030517578125) + 1.0) * 0.5; // 1/32768 = 0.000030517578125
             ch1 = y + (uint16_t)(f * h);
             if (i > 0) draw->drawLine(x + i-1,y_last_scope,x + i,ch1,ILI9341_ORANGE);
             //draw the second channel
             v = scope->read(1,i) * scale;
             f = ((v * 0.000030517578125) + 1.0) * 0.5;
             ch2 = y + (uint16_t)(f * h);
             if (i > 0) draw->drawLine(x + i-1,y_last_scope_ch2,x + i,ch2,ILI9341_CYAN);
             //draw x-y plot
             if (i > 0) draw->drawLine(y_last_scope_ch2,y_last_scope,ch2,ch1,ILI9341_GREENYELLOW);
             y_last_scope = ch1;
             y_last_scope_ch2 = ch2;
         }
         if (w>120 && h>60){
             draw->setCursor(x+w - 100,y+5);
             draw->print("scale: ");
             draw->print(scale);
             draw->setCursor(x+w - 100,y+20);
             draw->print("hdiv: ");
             draw->print(scope->getHDiv());
         }
         draw->drawRoundRect(x,y,w,h,4,ILI9341_MAGENTA);
     };    //called only when the app is active
References AppBaseClass::am, AppManager::data, AppBaseClass::draw, erisAudioAnalyzeScope::getHDiv(), erisAudioAnalyzeScope::getPeakValue(), AppBaseClass::h, erisAudioAnalyzeScope::read(), scale, scope, SvcDataDictionary::update(), AppBaseClass::w, AppBaseClass::x, and AppBaseClass::y.