ERIS CORE: wren.h File Reference
wren.h File Reference
#include <stdarg.h>
#include <stdlib.h>
#include <stdbool.h>
Classes
struct WrenConfiguration
struct WrenForeignClassMethods
struct WrenLoadModuleResult
Macros
#define WREN_API
#define WREN_VERSION_MAJOR 0
#define WREN_VERSION_MINOR 4
#define WREN_VERSION_NUMBER
#define WREN_VERSION_PATCH 0
#define WREN_VERSION_STRING "0.4.0"
Typedefs
typedef WrenForeignClassMethods(* WrenBindForeignClassFn) (WrenVM *vm, const char *module, const char *className)
typedef WrenForeignMethodFn(* WrenBindForeignMethodFn) (WrenVM *vm, const char *module, const char *className, bool isStatic, const char *signature)
typedef void(* WrenErrorFn) (WrenVM *vm, WrenErrorType type, const char *module, int line, const char *message)
typedef void(* WrenFinalizerFn) (void *data)
typedef void(* WrenForeignMethodFn) (WrenVM *vm)
typedef struct WrenHandle WrenHandle
typedef void(* WrenLoadModuleCompleteFn) (WrenVM *vm, const char *name, struct WrenLoadModuleResult result)
typedef WrenLoadModuleResult(* WrenLoadModuleFn) (WrenVM *vm, const char *name)
typedef struct WrenLoadModuleResult WrenLoadModuleResult
typedef void *(* WrenReallocateFn) (void *memory, size_t newSize, void *userData)
typedef const char *(* WrenResolveModuleFn) (WrenVM *vm, const char *importer, const char *name)
typedef struct WrenVM WrenVM
typedef void(* WrenWriteFn) (WrenVM *vm, const char *text)
Enumerations
enum WrenErrorType { WREN_ERROR_COMPILE , WREN_ERROR_RUNTIME , WREN_ERROR_STACK_TRACE }
enum WrenInterpretResult { WREN_RESULT_SUCCESS , WREN_RESULT_COMPILE_ERROR , WREN_RESULT_RUNTIME_ERROR }
enum WrenType {
WREN_TYPE_BOOL , WREN_TYPE_NUM , WREN_TYPE_FOREIGN , WREN_TYPE_LIST ,
WREN_TYPE_MAP , WREN_TYPE_NULL , WREN_TYPE_STRING , WREN_TYPE_UNKNOWN
}
Functions
WREN_API void wrenAbortFiber (WrenVM *vm, int slot)
WREN_API WrenInterpretResult wrenCall (WrenVM *vm, WrenHandle *method)
WREN_API void wrenCollectGarbage (WrenVM *vm)
WREN_API void wrenEnsureSlots (WrenVM *vm, int numSlots)
WREN_API void wrenFreeVM (WrenVM *vm)
WREN_API int wrenGetListCount (WrenVM *vm, int slot)
WREN_API void wrenGetListElement (WrenVM *vm, int listSlot, int index, int elementSlot)
WREN_API bool wrenGetMapContainsKey (WrenVM *vm, int mapSlot, int keySlot)
WREN_API int wrenGetMapCount (WrenVM *vm, int slot)
WREN_API void wrenGetMapValue (WrenVM *vm, int mapSlot, int keySlot, int valueSlot)
WREN_API bool wrenGetSlotBool (WrenVM *vm, int slot)
WREN_API const char * wrenGetSlotBytes (WrenVM *vm, int slot, int *length)
WREN_API int wrenGetSlotCount (WrenVM *vm)
WREN_API double wrenGetSlotDouble (WrenVM *vm, int slot)
WREN_API void * wrenGetSlotForeign (WrenVM *vm, int slot)
WREN_API WrenHandle * wrenGetSlotHandle (WrenVM *vm, int slot)
WREN_API const char * wrenGetSlotString (WrenVM *vm, int slot)
WREN_API WrenType wrenGetSlotType (WrenVM *vm, int slot)
WREN_API void * wrenGetUserData (WrenVM *vm)
WREN_API void wrenGetVariable (WrenVM *vm, const char *module, const char *name, int slot)
WREN_API int wrenGetVersionNumber ()
WREN_API bool wrenHasModule (WrenVM *vm, const char *module)
WREN_API bool wrenHasVariable (WrenVM *vm, const char *module, const char *name)
WREN_API void wrenInitConfiguration (WrenConfiguration *configuration)
WREN_API void wrenInsertInList (WrenVM *vm, int listSlot, int index, int elementSlot)
WREN_API WrenInterpretResult wrenInterpret (WrenVM *vm, const char *module, const char *source)
WREN_API WrenHandle * wrenMakeCallHandle (WrenVM *vm, const char *signature)
WREN_API WrenVM * wrenNewVM (WrenConfiguration *configuration)
WREN_API void wrenReleaseHandle (WrenVM *vm, WrenHandle *handle)
WREN_API void wrenRemoveMapValue (WrenVM *vm, int mapSlot, int keySlot, int removedValueSlot)
WREN_API void wrenSetListElement (WrenVM *vm, int listSlot, int index, int elementSlot)
WREN_API void wrenSetMapValue (WrenVM *vm, int mapSlot, int keySlot, int valueSlot)
WREN_API void wrenSetSlotBool (WrenVM *vm, int slot, bool value)
WREN_API void wrenSetSlotBytes (WrenVM *vm, int slot, const char *bytes, size_t length)
WREN_API void wrenSetSlotDouble (WrenVM *vm, int slot, double value)
WREN_API void wrenSetSlotHandle (WrenVM *vm, int slot, WrenHandle *handle)
WREN_API void * wrenSetSlotNewForeign (WrenVM *vm, int slot, int classSlot, size_t size)
WREN_API void wrenSetSlotNewList (WrenVM *vm, int slot)
WREN_API void wrenSetSlotNewMap (WrenVM *vm, int slot)
WREN_API void wrenSetSlotNull (WrenVM *vm, int slot)
WREN_API void wrenSetSlotString (WrenVM *vm, int slot, const char *text)
WREN_API void wrenSetUserData (WrenVM *vm, void *userData)
Macro Definition Documentation
WREN_API
#define WREN_API
Definition at line 26 of file wren.h.
WREN_VERSION_MAJOR
#define WREN_VERSION_MAJOR 0
Definition at line 9 of file wren.h.
WREN_VERSION_MINOR
#define WREN_VERSION_MINOR 4
Definition at line 10 of file wren.h.
WREN_VERSION_NUMBER
#define WREN_VERSION_NUMBER
Value:
                             (WREN_VERSION_MAJOR * 1000000 +                    \
                             WREN_VERSION_MINOR * 1000 +                       \
                             WREN_VERSION_PATCH)
Definition at line 18 of file wren.h.
WREN_VERSION_PATCH
#define WREN_VERSION_PATCH 0
Definition at line 11 of file wren.h.
WREN_VERSION_STRING
#define WREN_VERSION_STRING "0.4.0"
Definition at line 14 of file wren.h.
Typedef Documentation
WrenBindForeignClassFn
typedef WrenForeignClassMethods(* WrenBindForeignClassFn) (WrenVM *vm, const char *module, const char *className)
Definition at line 150 of file wren.h.
WrenBindForeignMethodFn
typedef WrenForeignMethodFn(* WrenBindForeignMethodFn) (WrenVM *vm, const char *module, const char *className, bool isStatic, const char *signature)
Definition at line 98 of file wren.h.
WrenErrorFn
typedef void(* WrenErrorFn) (WrenVM *vm, WrenErrorType type, const char *module, int line, const char *message)
Definition at line 129 of file wren.h.
WrenFinalizerFn
typedef void(* WrenFinalizerFn) (void *data)
Definition at line 67 of file wren.h.
WrenForeignMethodFn
typedef void(* WrenForeignMethodFn) (WrenVM *vm)
Definition at line 61 of file wren.h.
WrenHandle
typedef struct WrenHandle WrenHandle
Definition at line 1 of file wren.h.
WrenLoadModuleCompleteFn
typedef void(* WrenLoadModuleCompleteFn) (WrenVM *vm, const char *name, struct WrenLoadModuleResult result)
Definition at line 81 of file wren.h.
WrenLoadModuleFn
typedef WrenLoadModuleResult(* WrenLoadModuleFn) (WrenVM *vm, const char *name)
Definition at line 94 of file wren.h.
WrenLoadModuleResult
typedef struct WrenLoadModuleResult WrenLoadModuleResult
WrenReallocateFn
typedef void*(* WrenReallocateFn) (void *memory, size_t newSize, void *userData)
Definition at line 58 of file wren.h.
WrenResolveModuleFn
typedef const char*(* WrenResolveModuleFn) (WrenVM *vm, const char *importer, const char *name)
Definition at line 73 of file wren.h.
WrenVM
typedef struct WrenVM WrenVM
Definition at line 1 of file wren.h.
WrenWriteFn
typedef void(* WrenWriteFn) (WrenVM *vm, const char *text)
Definition at line 103 of file wren.h.
Enumeration Type Documentation
WrenErrorType
enum WrenErrorType
Enumerator
WREN_ERROR_COMPILE
WREN_ERROR_RUNTIME
WREN_ERROR_STACK_TRACE
Definition at line 105 of file wren.h.
 {
   // A syntax or resolution error detected at compile time.
   WREN_ERROR_COMPILE,
   // The error message for a runtime error.
   WREN_ERROR_RUNTIME,
   // One entry of a runtime error's stack trace.
   WREN_ERROR_STACK_TRACE
 } WrenErrorType;
WrenInterpretResult
enum WrenInterpretResult
Enumerator
WREN_RESULT_SUCCESS
WREN_RESULT_COMPILE_ERROR
WREN_RESULT_RUNTIME_ERROR
Definition at line 274 of file wren.h.
 {
   WREN_RESULT_SUCCESS,
   WREN_RESULT_COMPILE_ERROR,
   WREN_RESULT_RUNTIME_ERROR
 } WrenInterpretResult;
WrenType
enum WrenType
Enumerator
WREN_TYPE_BOOL
WREN_TYPE_NUM
WREN_TYPE_FOREIGN
WREN_TYPE_LIST
WREN_TYPE_MAP
WREN_TYPE_NULL
WREN_TYPE_STRING
WREN_TYPE_UNKNOWN
Definition at line 285 of file wren.h.
 {
   WREN_TYPE_BOOL,
   WREN_TYPE_NUM,
   WREN_TYPE_FOREIGN,
   WREN_TYPE_LIST,
   WREN_TYPE_MAP,
   WREN_TYPE_NULL,
   WREN_TYPE_STRING,
   // The object is of a type that isn't accessible by the C API.
   WREN_TYPE_UNKNOWN
 } WrenType;
Function Documentation
wrenAbortFiber()
WREN_API void wrenAbortFiber (WrenVM * vm, int slot)
Definition at line 1979 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   vm->fiber->error = vm->apiStack[slot];
 }
References WrenVM::apiStack, sObjFiber::error, WrenVM::fiber, and validateApiSlot().
wrenCall()
WREN_API WrenInterpretResult wrenCall (WrenVM * vm, WrenHandle * method)
Definition at line 1442 of file wren_vm.c.
 {
   ASSERT(method != NULL, "Method cannot be NULL.");
   ASSERT(IS_CLOSURE(method->value), "Method must be a method handle.");
   ASSERT(vm->fiber != NULL, "Must set up arguments for call first.");
   ASSERT(vm->apiStack != NULL, "Must set up arguments for call first.");
   ASSERT(vm->fiber->numFrames == 0, "Can not call from a foreign method.");
   ObjClosure* closure = AS_CLOSURE(method->value);
   ASSERT(vm->fiber->stackTop - vm->fiber->stack >= closure->fn->arity,
          "Stack must have enough arguments for method.");
   // Clear the API stack. Now that wrenCall() has control, we no longer need
   // it. We use this being non-null to tell if re-entrant calls to foreign
   // methods are happening, so it's important to clear it out now so that you
   // can call foreign methods from within calls to wrenCall().
   vm->apiStack = NULL;
   // Discard any extra temporary slots. We take for granted that the stub
   // function has exactly one slot for each argument.
   vm->fiber->stackTop = &vm->fiber->stack[closure->fn->maxSlots];
   wrenCallFunction(vm, vm->fiber, closure, 0);
   WrenInterpretResult result = runInterpreter(vm, vm->fiber);
   // If the call didn't abort, then set up the API stack to point to the
   // beginning of the stack so the host can access the call's return value.
   if (vm->fiber != NULL) vm->apiStack = vm->fiber->stack;
   return result;
 }
References WrenVM::apiStack, ObjFn::arity, AS_CLOSURE, ASSERT, WrenVM::fiber, ObjClosure::fn, IS_CLOSURE, ObjFn::maxSlots, method(), NULL, sObjFiber::numFrames, runInterpreter(), sObjFiber::stack, sObjFiber::stackTop, and wrenCallFunction().
Referenced by AppWren::onAnalog1(), AppWren::onAnalog2(), AppWren::onAnalog3(), AppWren::onAnalog4(), AppWren::onFocus(), AppWren::onFocusLost(), AppWren::onTouch(), AppWren::onTouchDrag(), AppWren::onTouchRelease(), AppWren::update(), AppWren::updateRT(), and AppWren::vmConstructor().
wrenCollectGarbage()
WREN_API void wrenCollectGarbage (WrenVM * vm)
Definition at line 125 of file wren_vm.c.
 {
 #if WREN_DEBUG_TRACE_MEMORY || WREN_DEBUG_TRACE_GC
   printf("-- gc --\n");
   size_t before = vm->bytesAllocated;
   double startTime = (double)clock() / CLOCKS_PER_SEC;
 #endif
   // Mark all reachable objects.
   // Reset this. As we mark objects, their size will be counted again so that
   // we can track how much memory is in use without needing to know the size
   // of each *freed* object.
   //
   // This is important because when freeing an unmarked object, we don't always
   // know how much memory it is using. For example, when freeing an instance,
   // we need to know its class to know how big it is, but its class may have
   // already been freed.
   vm->bytesAllocated = 0;
   wrenGrayObj(vm, (Obj*)vm->modules);
   // Temporary roots.
   for (int i = 0; i < vm->numTempRoots; i++)
   {
     wrenGrayObj(vm, vm->tempRoots[i]);
   }
   // The current fiber.
   wrenGrayObj(vm, (Obj*)vm->fiber);
   // The handles.
   for (WrenHandle* handle = vm->handles;
        handle != NULL;
        handle = handle->next)
   {
     wrenGrayValue(vm, handle->value);
   }
   // Any object the compiler is using (if there is one).
   if (vm->compiler != NULL) wrenMarkCompiler(vm, vm->compiler);
   // Method names.
   wrenBlackenSymbolTable(vm, &vm->methodNames);
   // Now that we have grayed the roots, do a depth-first search over all of the
   // reachable objects.
   wrenBlackenObjects(vm);
   // Collect the white objects.
   Obj** obj = &vm->first;
   while (*obj != NULL)
   {
     if (!((*obj)->isDark))
     {
       // This object wasn't reached, so remove it from the list and free it.
       Obj* unreached = *obj;
       *obj = unreached->next;
       wrenFreeObj(vm, unreached);
     }
     else
     {
       // This object was reached, so unmark it (for the next GC) and move on to
       // the next.
       (*obj)->isDark = false;
       obj = &(*obj)->next;
     }
   }
   // Calculate the next gc point, this is the current allocation plus
   // a configured percentage of the current allocation.
   vm->nextGC = vm->bytesAllocated + ((vm->bytesAllocated * vm->config.heapGrowthPercent) / 100);
   if (vm->nextGC < vm->config.minHeapSize) vm->nextGC = vm->config.minHeapSize;
 #if WREN_DEBUG_TRACE_MEMORY || WREN_DEBUG_TRACE_GC
   double elapsed = ((double)clock() / CLOCKS_PER_SEC) - startTime;
   // Explicit cast because size_t has different sizes on 32-bit and 64-bit and
   // we need a consistent type for the format string.
   printf("GC %lu before, %lu after (%lu collected), next at %lu. Took %.3fms.\n",
          (unsigned long)before,
          (unsigned long)vm->bytesAllocated,
          (unsigned long)(before - vm->bytesAllocated),
          (unsigned long)vm->nextGC,
          elapsed*1000.0);
 #endif
 }
References WrenVM::bytesAllocated, WrenVM::compiler, WrenVM::config, WrenVM::fiber, WrenVM::first, WrenVM::handles, WrenConfiguration::heapGrowthPercent, WrenVM::methodNames, WrenConfiguration::minHeapSize, WrenVM::modules, sObj::next, WrenVM::nextGC, NULL, WrenVM::numTempRoots, WrenVM::tempRoots, wrenBlackenObjects(), wrenBlackenSymbolTable(), wrenFreeObj(), wrenGrayObj(), wrenGrayValue(), and wrenMarkCompiler().
Referenced by DEF_PRIMITIVE(), AppWren::update(), and wrenReallocate().
wrenEnsureSlots()
WREN_API void wrenEnsureSlots (WrenVM * vm, int numSlots)
Definition at line 1635 of file wren_vm.c.
 {
   // If we don't have a fiber accessible, create one for the API to use.
   if (vm->apiStack == NULL)
   {
     vm->fiber = wrenNewFiber(vm, NULL);
     vm->apiStack = vm->fiber->stack;
   }
   int currentSize = (int)(vm->fiber->stackTop - vm->apiStack);
   if (currentSize >= numSlots) return;
   // Grow the stack if needed.
   int needed = (int)(vm->apiStack - vm->fiber->stack) + numSlots;
   wrenEnsureStack(vm, vm->fiber, needed);
   vm->fiber->stackTop = vm->apiStack + numSlots;
 }
References WrenVM::apiStack, WrenVM::fiber, NULL, sObjFiber::stack, sObjFiber::stackTop, wrenEnsureStack(), and wrenNewFiber().
Referenced by AppWren::getWrenHandles(), metaGetModuleVariables(), AppWren::onAnalog1(), AppWren::onAnalog2(), AppWren::onAnalog3(), AppWren::onAnalog4(), AppWren::onFocus(), AppWren::onFocusLost(), AppWren::onTouch(), AppWren::onTouchDrag(), AppWren::onTouchRelease(), AppWren::update(), AppWren::updateRT(), and AppWren::vmConstructor().
wrenFreeVM()
WREN_API void wrenFreeVM (WrenVM * vm)
Definition at line 99 of file wren_vm.c.
 {
   ASSERT(vm->methodNames.count > 0, "VM appears to have already been freed.");
   // Free all of the GC objects.
   Obj* obj = vm->first;
   while (obj != NULL)
   {
     Obj* next = obj->next;
     wrenFreeObj(vm, obj);
     obj = next;
   }
   // Free up the GC gray set.
   vm->gray = (Obj**)vm->config.reallocateFn(vm->gray, 0, vm->config.userData);
   // Tell the user if they didn't free any handles. We don't want to just free
   // them here because the host app may still have pointers to them that they
   // may try to use. Better to tell them about the bug early.
   ASSERT(vm->handles == NULL, "All handles have not been released.");
   wrenSymbolTableClear(vm, &vm->methodNames);
   DEALLOCATE(vm, vm);
 }
References ASSERT, WrenVM::config, DEALLOCATE, WrenVM::first, WrenVM::gray, WrenVM::handles, WrenVM::methodNames, sObj::next, NULL, WrenConfiguration::reallocateFn, WrenConfiguration::userData, wrenFreeObj(), and wrenSymbolTableClear().
Referenced by AppWren::~AppWren(), main(), and AppWren::restartVM().
wrenGetListCount()
WREN_API int wrenGetListCount (WrenVM * vm, int slot)
Definition at line 1792 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_LIST(vm->apiStack[slot]), "Slot must hold a list.");
   ValueBuffer elements = AS_LIST(vm->apiStack[slot])->elements;
   return elements.count;
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, and validateApiSlot().
wrenGetListElement()
WREN_API void wrenGetListElement (WrenVM * vm, int listSlot, int index, int elementSlot)
Definition at line 1801 of file wren_vm.c.
 {
   validateApiSlot(vm, listSlot);
   validateApiSlot(vm, elementSlot);
   ASSERT(IS_LIST(vm->apiStack[listSlot]), "Slot must hold a list.");
   ValueBuffer elements = AS_LIST(vm->apiStack[listSlot])->elements;
   uint32_t usedIndex = wrenValidateIndex(elements.count, index);
   ASSERT(usedIndex != UINT32_MAX, "Index out of bounds.");
   vm->apiStack[elementSlot] = elements.data[usedIndex];
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, validateApiSlot(), and wrenValidateIndex().
wrenGetMapContainsKey()
WREN_API bool wrenGetMapContainsKey (WrenVM * vm, int mapSlot, int keySlot)
Definition at line 1855 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Slot must hold a map.");
   Value key = vm->apiStack[keySlot];
   ASSERT(wrenMapIsValidKey(key), "Key must be a value type");
   if (!validateKey(vm, key)) return false;
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   Value value = wrenMapGet(map, key);
   return !IS_UNDEFINED(value);
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, IS_UNDEFINED, map(), validateApiSlot(), validateKey(), wrenMapGet(), and wrenMapIsValidKey().
wrenGetMapCount()
WREN_API int wrenGetMapCount (WrenVM * vm, int slot)
Definition at line 1846 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_MAP(vm->apiStack[slot]), "Slot must hold a map.");
   ObjMap* map = AS_MAP(vm->apiStack[slot]);
   return map->count;
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, map(), and validateApiSlot().
wrenGetMapValue()
WREN_API void wrenGetMapValue (WrenVM * vm, int mapSlot, int keySlot, int valueSlot)
Definition at line 1871 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   validateApiSlot(vm, valueSlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Slot must hold a map.");
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   Value value = wrenMapGet(map, vm->apiStack[keySlot]);
   if (IS_UNDEFINED(value)) {
     value = NULL_VAL;
   }
   vm->apiStack[valueSlot] = value;
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, IS_UNDEFINED, map(), NULL_VAL, validateApiSlot(), and wrenMapGet().
wrenGetSlotBool()
WREN_API bool wrenGetSlotBool (WrenVM * vm, int slot)
Definition at line 1676 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_BOOL(vm->apiStack[slot]), "Slot must hold a bool.");
   return AS_BOOL(vm->apiStack[slot]);
 }
References WrenVM::apiStack, AS_BOOL, ASSERT, IS_BOOL, and validateApiSlot().
Referenced by metaCompile().
wrenGetSlotBytes()
WREN_API const char* wrenGetSlotBytes (WrenVM * vm, int slot, int * length)
Definition at line 1684 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_STRING(vm->apiStack[slot]), "Slot must hold a string.");
   ObjString* string = AS_STRING(vm->apiStack[slot]);
   *length = string->length;
   return string->value;
 }
References WrenVM::apiStack, AS_STRING, ASSERT, IS_STRING, and validateApiSlot().
wrenGetSlotCount()
WREN_API int wrenGetSlotCount (WrenVM * vm)
Definition at line 1628 of file wren_vm.c.
 {
   if (vm->apiStack == NULL) return 0;
   return (int)(vm->fiber->stackTop - vm->apiStack);
 }
References WrenVM::apiStack, WrenVM::fiber, NULL, and sObjFiber::stackTop.
Referenced by validateApiSlot().
wrenGetSlotDouble()
WREN_API double wrenGetSlotDouble (WrenVM * vm, int slot)
Definition at line 1694 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_NUM(vm->apiStack[slot]), "Slot must hold a number.");
   return AS_NUM(vm->apiStack[slot]);
 }
References WrenVM::apiStack, AS_NUM, ASSERT, IS_NUM, and validateApiSlot().
Referenced by randomSeed1(), and randomSeed16().
wrenGetSlotForeign()
WREN_API void* wrenGetSlotForeign (WrenVM * vm, int slot)
Definition at line 1702 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_FOREIGN(vm->apiStack[slot]),
          "Slot must hold a foreign instance.");
   return AS_FOREIGN(vm->apiStack[slot])->data;
 }
References WrenVM::apiStack, AS_FOREIGN, ASSERT, IS_FOREIGN, and validateApiSlot().
Referenced by randomFloat(), randomInt0(), randomSeed0(), randomSeed1(), and randomSeed16().
wrenGetSlotHandle()
WREN_API WrenHandle* wrenGetSlotHandle (WrenVM * vm, int slot)
Definition at line 1719 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   return wrenMakeHandle(vm, vm->apiStack[slot]);
 }
References WrenVM::apiStack, validateApiSlot(), and wrenMakeHandle().
Referenced by AppWren::getWrenHandles().
wrenGetSlotString()
WREN_API const char* wrenGetSlotString (WrenVM * vm, int slot)
Definition at line 1711 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   ASSERT(IS_STRING(vm->apiStack[slot]), "Slot must hold a string.");
   return AS_CSTRING(vm->apiStack[slot]);
 }
References WrenVM::apiStack, AS_CSTRING, ASSERT, IS_STRING, and validateApiSlot().
Referenced by metaCompile().
wrenGetSlotType()
WREN_API WrenType wrenGetSlotType (WrenVM * vm, int slot)
Definition at line 1662 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   if (IS_BOOL(vm->apiStack[slot])) return WREN_TYPE_BOOL;
   if (IS_NUM(vm->apiStack[slot])) return WREN_TYPE_NUM;
   if (IS_FOREIGN(vm->apiStack[slot])) return WREN_TYPE_FOREIGN;
   if (IS_LIST(vm->apiStack[slot])) return WREN_TYPE_LIST;
   if (IS_MAP(vm->apiStack[slot])) return WREN_TYPE_MAP;
   if (IS_NULL(vm->apiStack[slot])) return WREN_TYPE_NULL;
   if (IS_STRING(vm->apiStack[slot])) return WREN_TYPE_STRING;
   return WREN_TYPE_UNKNOWN;
 }
References WrenVM::apiStack, IS_BOOL, IS_FOREIGN, IS_LIST, IS_MAP, IS_NULL, IS_NUM, IS_STRING, validateApiSlot(), WREN_TYPE_BOOL, WREN_TYPE_FOREIGN, WREN_TYPE_LIST, WREN_TYPE_MAP, WREN_TYPE_NULL, WREN_TYPE_NUM, WREN_TYPE_STRING, and WREN_TYPE_UNKNOWN.
wrenGetUserData()
WREN_API void* wrenGetUserData (WrenVM * vm)
Definition at line 1985 of file wren_vm.c.
 {
     return vm->config.userData;
 }
References WrenVM::config, and WrenConfiguration::userData.
wrenGetVariable()
WREN_API void wrenGetVariable (WrenVM * vm, const char * module, const char * name, int slot)
Definition at line 1924 of file wren_vm.c.
 {
   ASSERT(module != NULL, "Module cannot be NULL.");
   ASSERT(name != NULL, "Variable name cannot be NULL.");
   Value moduleName = wrenStringFormat(vm, "$", module);
   wrenPushRoot(vm, AS_OBJ(moduleName));
   ObjModule* moduleObj = getModule(vm, moduleName);
   ASSERT(moduleObj != NULL, "Could not find module.");
   wrenPopRoot(vm); // moduleName.
   int variableSlot = wrenSymbolTableFind(&moduleObj->variableNames,
                                          name, strlen(name));
   ASSERT(variableSlot != -1, "Could not find variable.");
   setSlot(vm, slot, moduleObj->variables.data[variableSlot]);
 }
References AS_OBJ, ASSERT, getModule(), name, NULL, setSlot(), ObjModule::variableNames, ObjModule::variables, wrenPopRoot(), wrenPushRoot(), wrenStringFormat(), and wrenSymbolTableFind().
Referenced by AppWren::getWrenHandles().
wrenGetVersionNumber()
WREN_API int wrenGetVersionNumber ()
Definition at line 39 of file wren_vm.c.
 {
   return WREN_VERSION_NUMBER;
 }
References WREN_VERSION_NUMBER.
wrenHasModule()
WREN_API bool wrenHasModule (WrenVM * vm, const char * module)
Definition at line 1965 of file wren_vm.c.
 {
   ASSERT(module != NULL, "Module cannot be NULL.");
   Value moduleName = wrenStringFormat(vm, "$", module);
   wrenPushRoot(vm, AS_OBJ(moduleName));
   ObjModule* moduleObj = getModule(vm, moduleName);
   wrenPopRoot(vm); // moduleName.
   return moduleObj != NULL;
 }
References AS_OBJ, ASSERT, getModule(), NULL, wrenPopRoot(), wrenPushRoot(), and wrenStringFormat().
wrenHasVariable()
WREN_API bool wrenHasVariable (WrenVM * vm, const char * module, const char * name)
Definition at line 1945 of file wren_vm.c.
 {
   ASSERT(module != NULL, "Module cannot be NULL.");
   ASSERT(name != NULL, "Variable name cannot be NULL.");
   Value moduleName = wrenStringFormat(vm, "$", module);
   wrenPushRoot(vm, AS_OBJ(moduleName));
   //We don't use wrenHasModule since we want to use the module object.
   ObjModule* moduleObj = getModule(vm, moduleName);
   ASSERT(moduleObj != NULL, "Could not find module.");
   wrenPopRoot(vm); // moduleName.
   int variableSlot = wrenSymbolTableFind(&moduleObj->variableNames,
     name, strlen(name));
   return variableSlot != -1;
 }
References AS_OBJ, ASSERT, getModule(), name, NULL, ObjModule::variableNames, wrenPopRoot(), wrenPushRoot(), wrenStringFormat(), and wrenSymbolTableFind().
wrenInitConfiguration()
WREN_API void wrenInitConfiguration (WrenConfiguration * configuration)
Definition at line 44 of file wren_vm.c.
 {
   config->reallocateFn = defaultReallocate;
   config->resolveModuleFn = NULL;
   config->loadModuleFn = NULL;
   config->bindForeignMethodFn = NULL;
   config->bindForeignClassFn = NULL;
   config->writeFn = NULL;
   config->errorFn = NULL;
   config->initialHeapSize = 1024 * 1024 * 10;
   config->minHeapSize = 1024 * 1024;
   config->heapGrowthPercent = 50;
   config->userData = NULL;
 }
References config, defaultReallocate(), and NULL.
Referenced by main(), AppWren::startVM(), and wrenNewVM().
wrenInsertInList()
WREN_API void wrenInsertInList (WrenVM * vm, int listSlot, int index, int elementSlot)
Definition at line 1829 of file wren_vm.c.
 {
   validateApiSlot(vm, listSlot);
   validateApiSlot(vm, elementSlot);
   ASSERT(IS_LIST(vm->apiStack[listSlot]), "Must insert into a list.");
   ObjList* list = AS_LIST(vm->apiStack[listSlot]);
   // Negative indices count from the end.
   // We don't use wrenValidateIndex here because insert allows 1 past the end.
   if (index < 0) index = list->elements.count + 1 + index;
   ASSERT(index <= list->elements.count, "Index out of bounds.");
   wrenListInsert(vm, list, vm->apiStack[elementSlot], index);
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, list(), validateApiSlot(), and wrenListInsert().
wrenInterpret()
WREN_API WrenInterpretResult wrenInterpret (WrenVM * vm, const char * module, const char * source)
Definition at line 1513 of file wren_vm.c.
 {
   ObjClosure* closure = wrenCompileSource(vm, module, source, false, true);
   if (closure == NULL) return WREN_RESULT_COMPILE_ERROR;
   wrenPushRoot(vm, (Obj*)closure);
   ObjFiber* fiber = wrenNewFiber(vm, closure);
   wrenPopRoot(vm); // closure.
   vm->apiStack = NULL;
   return runInterpreter(vm, fiber);
 }
References WrenVM::apiStack, fiber, NULL, runInterpreter(), source, WREN_RESULT_COMPILE_ERROR, wrenCompileSource(), wrenNewFiber(), wrenPopRoot(), and wrenPushRoot().
Referenced by AppWren::loadScript(), main(), and wrenInitializeCore().
wrenMakeCallHandle()
WREN_API WrenHandle* wrenMakeCallHandle (WrenVM * vm, const char * signature)
Definition at line 1392 of file wren_vm.c.
 {
   ASSERT(signature != NULL, "Signature cannot be NULL.");
   int signatureLength = (int)strlen(signature);
   ASSERT(signatureLength > 0, "Signature cannot be empty.");
   // Count the number parameters the method expects.
   int numParams = 0;
   if (signature[signatureLength - 1] == ')')
   {
     for (int i = signatureLength - 1; i > 0 && signature[i] != '('; i--)
     {
       if (signature[i] == '_') numParams++;
     }
   }
   // Count subscript arguments.
   if (signature[0] == '[')
   {
     for (int i = 0; i < signatureLength && signature[i] != ']'; i++)
     {
       if (signature[i] == '_') numParams++;
     }
   }
   // Add the signatue to the method table.
   int method =  wrenSymbolTableEnsure(vm, &vm->methodNames,
                                       signature, signatureLength);
   // Create a little stub function that assumes the arguments are on the stack
   // and calls the method.
   ObjFn* fn = wrenNewFunction(vm, NULL, numParams + 1);
   // Wrap the function in a closure and then in a handle. Do this here so it
   // doesn't get collected as we fill it in.
   WrenHandle* value = wrenMakeHandle(vm, OBJ_VAL(fn));
   value->value = OBJ_VAL(wrenNewClosure(vm, fn));
   wrenByteBufferWrite(vm, &fn->code, (uint8_t)(CODE_CALL_0 + numParams));
   wrenByteBufferWrite(vm, &fn->code, (method >> 8) & 0xff);
   wrenByteBufferWrite(vm, &fn->code, method & 0xff);
   wrenByteBufferWrite(vm, &fn->code, CODE_RETURN);
   wrenByteBufferWrite(vm, &fn->code, CODE_END);
   wrenIntBufferFill(vm, &fn->debug->sourceLines, 0, 5);
   wrenFunctionBindName(vm, fn, signature, signatureLength);
   return value;
 }
References ASSERT, fn, method(), WrenVM::methodNames, NULL, OBJ_VAL, WrenHandle::value, wrenFunctionBindName(), wrenMakeHandle(), wrenNewClosure(), wrenNewFunction(), and wrenSymbolTableEnsure().
Referenced by AppWren::getWrenHandles().
wrenNewVM()
WREN_API WrenVM* wrenNewVM (WrenConfiguration * configuration)
Definition at line 59 of file wren_vm.c.
 {
   WrenReallocateFn reallocate = defaultReallocate;
   void* userData = NULL;
   if (config != NULL) {
     userData = config->userData;
     reallocate = config->reallocateFn ? config->reallocateFn : defaultReallocate;
   }
   WrenVM* vm = (WrenVM*)reallocate(NULL, sizeof(*vm), userData);
   memset(vm, 0, sizeof(WrenVM));
   // Copy the configuration if given one.
   if (config != NULL)
   {
     memcpy(&vm->config, config, sizeof(WrenConfiguration));
     // We choose to set this after copying,
     // rather than modifying the user config pointer
     vm->config.reallocateFn = reallocate;
   }
   else
   {
     wrenInitConfiguration(&vm->config);
   }
   // TODO: Should we allocate and free this during a GC?
   vm->grayCount = 0;
   // TODO: Tune this.
   vm->grayCapacity = 4;
   vm->gray = (Obj**)reallocate(NULL, vm->grayCapacity * sizeof(Obj*), userData);
   vm->nextGC = vm->config.initialHeapSize;
   wrenSymbolTableInit(&vm->methodNames);
   vm->modules = wrenNewMap(vm);
   wrenInitializeCore(vm);
   return vm;
 }
References config, WrenVM::config, defaultReallocate(), WrenVM::gray, WrenVM::grayCapacity, WrenVM::grayCount, WrenConfiguration::initialHeapSize, WrenVM::methodNames, WrenVM::modules, WrenVM::nextGC, NULL, WrenConfiguration::reallocateFn, wrenInitConfiguration(), wrenInitializeCore(), wrenNewMap(), and wrenSymbolTableInit().
Referenced by main(), and AppWren::startVM().
wrenReleaseHandle()
WREN_API void wrenReleaseHandle (WrenVM * vm, WrenHandle * handle)
Definition at line 1494 of file wren_vm.c.
 {
   ASSERT(handle != NULL, "Handle cannot be NULL.");
   // Update the VM's head pointer if we're releasing the first handle.
   if (vm->handles == handle) vm->handles = handle->next;
   // Unlink it from the list.
   if (handle->prev != NULL) handle->prev->next = handle->next;
   if (handle->next != NULL) handle->next->prev = handle->prev;
   // Clear it out. This isn't strictly necessary since we're going to free it,
   // but it makes for easier debugging.
   handle->prev = NULL;
   handle->next = NULL;
   handle->value = NULL_VAL;
   DEALLOCATE(vm, handle);
 }
References ASSERT, DEALLOCATE, WrenVM::handles, WrenHandle::next, NULL, NULL_VAL, WrenHandle::prev, and WrenHandle::value.
Referenced by AppWren::releaseWrenHandles().
wrenRemoveMapValue()
WREN_API void wrenRemoveMapValue (WrenVM * vm, int mapSlot, int keySlot, int removedValueSlot)
Definition at line 1907 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Slot must hold a map.");
   Value key = vm->apiStack[keySlot];
   if (!validateKey(vm, key)) {
     return;
   }
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   Value removed = wrenMapRemoveKey(vm, map, key);
   setSlot(vm, removedValueSlot, removed);
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, map(), setSlot(), validateApiSlot(), validateKey(), and wrenMapRemoveKey().
wrenSetListElement()
WREN_API void wrenSetListElement (WrenVM * vm, int listSlot, int index, int elementSlot)
Definition at line 1815 of file wren_vm.c.
 {
   validateApiSlot(vm, listSlot);
   validateApiSlot(vm, elementSlot);
   ASSERT(IS_LIST(vm->apiStack[listSlot]), "Slot must hold a list.");
   ObjList* list = AS_LIST(vm->apiStack[listSlot]);
   uint32_t usedIndex = wrenValidateIndex(list->elements.count, index);
   ASSERT(usedIndex != UINT32_MAX, "Index out of bounds.");
   list->elements.data[usedIndex] = vm->apiStack[elementSlot];
 }
References WrenVM::apiStack, AS_LIST, ASSERT, IS_LIST, list(), validateApiSlot(), and wrenValidateIndex().
wrenSetMapValue()
WREN_API void wrenSetMapValue (WrenVM * vm, int mapSlot, int keySlot, int valueSlot)
Definition at line 1887 of file wren_vm.c.
 {
   validateApiSlot(vm, mapSlot);
   validateApiSlot(vm, keySlot);
   validateApiSlot(vm, valueSlot);
   ASSERT(IS_MAP(vm->apiStack[mapSlot]), "Must insert into a map.");
   Value key = vm->apiStack[keySlot];
   ASSERT(wrenMapIsValidKey(key), "Key must be a value type");
   if (!validateKey(vm, key)) {
     return;
   }
   Value value = vm->apiStack[valueSlot];
   ObjMap* map = AS_MAP(vm->apiStack[mapSlot]);
   wrenMapSet(vm, map, key, value);
 }
References WrenVM::apiStack, AS_MAP, ASSERT, IS_MAP, map(), validateApiSlot(), validateKey(), wrenMapIsValidKey(), and wrenMapSet().
wrenSetSlotBool()
WREN_API void wrenSetSlotBool (WrenVM * vm, int slot, bool value)
Definition at line 1732 of file wren_vm.c.
 {
   setSlot(vm, slot, BOOL_VAL(value));
 }
References BOOL_VAL, and setSlot().
wrenSetSlotBytes()
WREN_API void wrenSetSlotBytes (WrenVM * vm, int slot, const char * bytes, size_t length)
Definition at line 1737 of file wren_vm.c.
 {
   ASSERT(bytes != NULL, "Byte array cannot be NULL.");
   setSlot(vm, slot, wrenNewStringLength(vm, bytes, length));
 }
References ASSERT, NULL, setSlot(), and wrenNewStringLength().
wrenSetSlotDouble()
WREN_API void wrenSetSlotDouble (WrenVM * vm, int slot, double value)
Definition at line 1743 of file wren_vm.c.
 {
   setSlot(vm, slot, NUM_VAL(value));
 }
References NUM_VAL, and setSlot().
Referenced by randomFloat(), and randomInt0().
wrenSetSlotHandle()
WREN_API void wrenSetSlotHandle (WrenVM * vm, int slot, WrenHandle * handle)
Definition at line 1785 of file wren_vm.c.
 {
   ASSERT(handle != NULL, "Handle cannot be NULL.");
   setSlot(vm, slot, handle->value);
 }
References ASSERT, NULL, setSlot(), and WrenHandle::value.
Referenced by AppWren::onAnalog1(), AppWren::onAnalog2(), AppWren::onAnalog3(), AppWren::onAnalog4(), AppWren::onFocus(), AppWren::onFocusLost(), AppWren::onTouch(), AppWren::onTouchDrag(), AppWren::onTouchRelease(), AppWren::update(), AppWren::updateRT(), and AppWren::vmConstructor().
wrenSetSlotNewForeign()
WREN_API void* wrenSetSlotNewForeign (WrenVM * vm, int slot, int classSlot, size_t size)
Definition at line 1748 of file wren_vm.c.
 {
   validateApiSlot(vm, slot);
   validateApiSlot(vm, classSlot);
   ASSERT(IS_CLASS(vm->apiStack[classSlot]), "Slot must hold a class.");
   ObjClass* classObj = AS_CLASS(vm->apiStack[classSlot]);
   ASSERT(classObj->numFields == -1, "Class must be a foreign class.");
   ObjForeign* foreign = wrenNewForeign(vm, classObj, size);
   vm->apiStack[slot] = OBJ_VAL(foreign);
   return (void*)foreign->data;
 }
References WrenVM::apiStack, AS_CLASS, ASSERT, ObjForeign::data, IS_CLASS, sObjClass::numFields, OBJ_VAL, validateApiSlot(), and wrenNewForeign().
Referenced by randomAllocate().
wrenSetSlotNewList()
WREN_API void wrenSetSlotNewList (WrenVM * vm, int slot)
Definition at line 1763 of file wren_vm.c.
 {
   setSlot(vm, slot, OBJ_VAL(wrenNewList(vm, 0)));
 }
References OBJ_VAL, setSlot(), and wrenNewList().
wrenSetSlotNewMap()
WREN_API void wrenSetSlotNewMap (WrenVM * vm, int slot)
Definition at line 1768 of file wren_vm.c.
 {
   setSlot(vm, slot, OBJ_VAL(wrenNewMap(vm)));
 }
References OBJ_VAL, setSlot(), and wrenNewMap().
wrenSetSlotNull()
WREN_API void wrenSetSlotNull (WrenVM * vm, int slot)
Definition at line 1773 of file wren_vm.c.
 {
   setSlot(vm, slot, NULL_VAL);
 }
References NULL_VAL, and setSlot().
wrenSetSlotString()
WREN_API void wrenSetSlotString (WrenVM * vm, int slot, const char * text)
Definition at line 1778 of file wren_vm.c.
 {
   ASSERT(text != NULL, "String cannot be NULL.");
   setSlot(vm, slot, wrenNewString(vm, text));
 }
References ASSERT, NULL, setSlot(), and wrenNewString().
wrenSetUserData()
WREN_API void wrenSetUserData (WrenVM * vm, void * userData)
Definition at line 1990 of file wren_vm.c.
 {
     vm->config.userData = userData;
 }
References WrenVM::config, and WrenConfiguration::userData.