ERIS CORE: wren_core.c File Reference
wren_core.c File Reference
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include "wren_common.h"
#include "wren_core.h"
#include "wren_math.h"
#include "wren_primitive.h"
#include "wren_value.h"
#include "wren_core.wren.inc"
Macros
#define DEF_FN_CALL(numArgs)
#define DEF_NUM_BITWISE(name, op)
#define DEF_NUM_CONSTANT(name, value)
#define DEF_NUM_FN(name, fn)
#define DEF_NUM_INFIX(name, op, type)
Functions
static void call_fn (WrenVM *vm, Value *args, int numArgs)
DEF_PRIMITIVE (bool_not)
DEF_PRIMITIVE (bool_toString)
DEF_PRIMITIVE (class_attributes)
DEF_PRIMITIVE (class_name)
DEF_PRIMITIVE (class_supertype)
DEF_PRIMITIVE (class_toString)
DEF_PRIMITIVE (fiber_abort)
DEF_PRIMITIVE (fiber_call)
DEF_PRIMITIVE (fiber_call1)
DEF_PRIMITIVE (fiber_current)
DEF_PRIMITIVE (fiber_error)
DEF_PRIMITIVE (fiber_isDone)
DEF_PRIMITIVE (fiber_new)
DEF_PRIMITIVE (fiber_suspend)
DEF_PRIMITIVE (fiber_transfer)
DEF_PRIMITIVE (fiber_transfer1)
DEF_PRIMITIVE (fiber_transferError)
DEF_PRIMITIVE (fiber_try)
DEF_PRIMITIVE (fiber_try1)
DEF_PRIMITIVE (fiber_yield)
DEF_PRIMITIVE (fiber_yield1)
DEF_PRIMITIVE (fn_arity)
DEF_PRIMITIVE (fn_new)
DEF_PRIMITIVE (fn_toString)
DEF_PRIMITIVE (list_add)
DEF_PRIMITIVE (list_addCore)
DEF_PRIMITIVE (list_clear)
DEF_PRIMITIVE (list_count)
DEF_PRIMITIVE (list_filled)
DEF_PRIMITIVE (list_indexOf)
DEF_PRIMITIVE (list_insert)
DEF_PRIMITIVE (list_iterate)
DEF_PRIMITIVE (list_iteratorValue)
DEF_PRIMITIVE (list_new)
DEF_PRIMITIVE (list_removeAt)
DEF_PRIMITIVE (list_removeValue)
DEF_PRIMITIVE (list_subscript)
DEF_PRIMITIVE (list_subscriptSetter)
DEF_PRIMITIVE (list_swap)
DEF_PRIMITIVE (map_addCore)
DEF_PRIMITIVE (map_clear)
DEF_PRIMITIVE (map_containsKey)
DEF_PRIMITIVE (map_count)
DEF_PRIMITIVE (map_iterate)
DEF_PRIMITIVE (map_keyIteratorValue)
DEF_PRIMITIVE (map_new)
DEF_PRIMITIVE (map_remove)
DEF_PRIMITIVE (map_subscript)
DEF_PRIMITIVE (map_subscriptSetter)
DEF_PRIMITIVE (map_valueIteratorValue)
DEF_PRIMITIVE (null_not)
DEF_PRIMITIVE (null_toString)
DEF_PRIMITIVE (num_atan2)
DEF_PRIMITIVE (num_bangeq)
DEF_PRIMITIVE (num_bitwiseNot)
DEF_PRIMITIVE (num_clamp)
DEF_PRIMITIVE (num_dotDot)
DEF_PRIMITIVE (num_dotDotDot)
DEF_PRIMITIVE (num_eqeq)
DEF_PRIMITIVE (num_fraction)
DEF_PRIMITIVE (num_fromString)
DEF_PRIMITIVE (num_isInfinity)
DEF_PRIMITIVE (num_isInteger)
DEF_PRIMITIVE (num_isNan)
DEF_PRIMITIVE (num_max)
DEF_PRIMITIVE (num_min)
DEF_PRIMITIVE (num_mod)
DEF_PRIMITIVE (num_pow)
DEF_PRIMITIVE (num_sign)
DEF_PRIMITIVE (num_toString)
DEF_PRIMITIVE (num_truncate)
DEF_PRIMITIVE (object_bangeq)
DEF_PRIMITIVE (object_eqeq)
DEF_PRIMITIVE (object_is)
DEF_PRIMITIVE (object_not)
DEF_PRIMITIVE (object_same)
DEF_PRIMITIVE (object_toString)
DEF_PRIMITIVE (object_type)
DEF_PRIMITIVE (range_from)
DEF_PRIMITIVE (range_isInclusive)
DEF_PRIMITIVE (range_iterate)
DEF_PRIMITIVE (range_iteratorValue)
DEF_PRIMITIVE (range_max)
DEF_PRIMITIVE (range_min)
DEF_PRIMITIVE (range_to)
DEF_PRIMITIVE (range_toString)
DEF_PRIMITIVE (string_byteAt)
DEF_PRIMITIVE (string_byteCount)
DEF_PRIMITIVE (string_codePointAt)
DEF_PRIMITIVE (string_contains)
DEF_PRIMITIVE (string_endsWith)
DEF_PRIMITIVE (string_fromByte)
DEF_PRIMITIVE (string_fromCodePoint)
DEF_PRIMITIVE (string_indexOf1)
DEF_PRIMITIVE (string_indexOf2)
DEF_PRIMITIVE (string_iterate)
DEF_PRIMITIVE (string_iterateByte)
DEF_PRIMITIVE (string_iteratorValue)
DEF_PRIMITIVE (string_plus)
DEF_PRIMITIVE (string_startsWith)
DEF_PRIMITIVE (string_subscript)
DEF_PRIMITIVE (string_toString)
DEF_PRIMITIVE (system_clock)
DEF_PRIMITIVE (system_gc)
DEF_PRIMITIVE (system_writeString)
static ObjClass * defineClass (WrenVM *vm, ObjModule *module, const char *name)
static bool runFiber (WrenVM *vm, ObjFiber *fiber, Value *args, bool isCall, bool hasValue, const char *verb)
void wrenInitializeCore (WrenVM *vm)
Macro Definition Documentation
DEF_FN_CALL
#define DEF_FN_CALL (numArgs)
Value:
    DEF_PRIMITIVE(fn_call##numArgs)                                            \
    {                                                                          \
      call_fn(vm, args, numArgs);                                              \
      return false;                                                            \
    }
Definition at line 270 of file wren_core.c.
DEF_NUM_BITWISE
#define DEF_NUM_BITWISE (name, op)
Value:
    DEF_PRIMITIVE(num_bitwise##name)                                           \
    {                                                                          \
      if (!validateNum(vm, args[1], "Right operand")) return false;            \
      uint32_t left = (uint32_t)AS_NUM(args[0]);                               \
      uint32_t right = (uint32_t)AS_NUM(args[1]);                              \
      RETURN_NUM(left op right);                                               \
    }
Definition at line 669 of file wren_core.c.
DEF_NUM_CONSTANT
#define DEF_NUM_CONSTANT (name, value)
Value:
    DEF_PRIMITIVE(num_##name)                                                  \
    {                                                                          \
      RETURN_NUM(value);                                                       \
    }
Definition at line 634 of file wren_core.c.
DEF_NUM_FN
#define DEF_NUM_FN (name, fn)
Value:
    DEF_PRIMITIVE(num_##name)                                                  \
    {                                                                          \
      RETURN_NUM(fn(AS_NUM(args[0])));                                         \
    }
Definition at line 685 of file wren_core.c.
DEF_NUM_INFIX
#define DEF_NUM_INFIX (name, op, type)
Value:
    DEF_PRIMITIVE(num_##name)                                                  \
    {                                                                          \
      if (!validateNum(vm, args[1], "Right operand")) return false;            \
      RETURN_##type(AS_NUM(args[0]) op AS_NUM(args[1]));                       \
    }
Definition at line 652 of file wren_core.c.
Function Documentation
call_fn()
static void call_fn (WrenVM * vm, Value * args, int numArgs) static
Definition at line 264 of file wren_core.c.
 {
   // +1 to include the function itself.
   wrenCallFunction(vm, vm->fiber, AS_CLOSURE(args[0]), numArgs + 1);
 }
References AS_CLOSURE, WrenVM::fiber, and wrenCallFunction().
DEF_PRIMITIVE() [1/105]
DEF_PRIMITIVE (bool_not)
Definition at line 16 of file wren_core.c.
 {
   RETURN_BOOL(!AS_BOOL(args[0]));
 }
References AS_BOOL, and RETURN_BOOL.
DEF_PRIMITIVE() [2/105]
DEF_PRIMITIVE (bool_toString)
Definition at line 21 of file wren_core.c.
 {
   if (AS_BOOL(args[0]))
   {
     RETURN_VAL(CONST_STRING(vm, "true"));
   }
   else
   {
     RETURN_VAL(CONST_STRING(vm, "false"));
   }
 }
References AS_BOOL, CONST_STRING, and RETURN_VAL.
DEF_PRIMITIVE() [3/105]
DEF_PRIMITIVE (class_attributes)
Definition at line 53 of file wren_core.c.
 {
   RETURN_VAL(AS_CLASS(args[0])->attributes);
 }
References AS_CLASS, and RETURN_VAL.
DEF_PRIMITIVE() [4/105]
DEF_PRIMITIVE (class_name)
Definition at line 33 of file wren_core.c.
 {
   RETURN_OBJ(AS_CLASS(args[0])->name);
 }
References AS_CLASS, name, and RETURN_OBJ.
DEF_PRIMITIVE() [5/105]
DEF_PRIMITIVE (class_supertype)
Definition at line 38 of file wren_core.c.
 {
   ObjClass* classObj = AS_CLASS(args[0]);
   // Object has no superclass.
   if (classObj->superclass == NULL) RETURN_NULL;
   RETURN_OBJ(classObj->superclass);
 }
References AS_CLASS, NULL, RETURN_NULL, RETURN_OBJ, and sObjClass::superclass.
DEF_PRIMITIVE() [6/105]
DEF_PRIMITIVE (class_toString)
Definition at line 48 of file wren_core.c.
 {
   RETURN_OBJ(AS_CLASS(args[0])->name);
 }
References AS_CLASS, name, and RETURN_OBJ.
DEF_PRIMITIVE() [7/105]
DEF_PRIMITIVE (fiber_abort)
Definition at line 71 of file wren_core.c.
 {
   vm->fiber->error = args[1];
   // If the error is explicitly null, it's not really an abort.
   return IS_NULL(args[1]);
 }
References IS_NULL.
DEF_PRIMITIVE() [8/105]
DEF_PRIMITIVE (fiber_call)
Definition at line 140 of file wren_core.c.
 {
   return runFiber(vm, AS_FIBER(args[0]), args, true, false, "call");
 }
References AS_FIBER, and runFiber().
DEF_PRIMITIVE() [9/105]
DEF_PRIMITIVE (fiber_call1)
Definition at line 145 of file wren_core.c.
 {
   return runFiber(vm, AS_FIBER(args[0]), args, true, true, "call");
 }
References AS_FIBER, and runFiber().
DEF_PRIMITIVE() [10/105]
DEF_PRIMITIVE (fiber_current)
Definition at line 150 of file wren_core.c.
 {
   RETURN_OBJ(vm->fiber);
 }
References RETURN_OBJ.
DEF_PRIMITIVE() [11/105]
DEF_PRIMITIVE (fiber_error)
Definition at line 155 of file wren_core.c.
 {
   RETURN_VAL(AS_FIBER(args[0])->error);
 }
References AS_FIBER, error, and RETURN_VAL.
DEF_PRIMITIVE() [12/105]
DEF_PRIMITIVE (fiber_isDone)
Definition at line 160 of file wren_core.c.
 {
   ObjFiber* runFiber = AS_FIBER(args[0]);
   RETURN_BOOL(runFiber->numFrames == 0 || wrenHasError(runFiber));
 }
References AS_FIBER, RETURN_BOOL, runFiber(), and wrenHasError().
DEF_PRIMITIVE() [13/105]
DEF_PRIMITIVE (fiber_new)
Definition at line 58 of file wren_core.c.
 {
   if (!validateFn(vm, args[1], "Argument")) return false;
   ObjClosure* closure = AS_CLOSURE(args[1]);
   if (closure->fn->arity > 1)
   {
     RETURN_ERROR("Function cannot take more than one parameter.");
   }
   RETURN_OBJ(wrenNewFiber(vm, closure));
 }
References ObjFn::arity, AS_CLOSURE, ObjClosure::fn, RETURN_ERROR, RETURN_OBJ, validateFn(), and wrenNewFiber().
DEF_PRIMITIVE() [14/105]
DEF_PRIMITIVE (fiber_suspend)
Definition at line 166 of file wren_core.c.
 {
   // Switching to a null fiber tells the interpreter to stop and exit.
   vm->fiber = NULL;
   vm->apiStack = NULL;
   return false;
 }
References NULL.
DEF_PRIMITIVE() [15/105]
DEF_PRIMITIVE (fiber_transfer)
Definition at line 174 of file wren_core.c.
 {
   return runFiber(vm, AS_FIBER(args[0]), args, false, false, "transfer to");
 }
References AS_FIBER, and runFiber().
DEF_PRIMITIVE() [16/105]
DEF_PRIMITIVE (fiber_transfer1)
Definition at line 179 of file wren_core.c.
 {
   return runFiber(vm, AS_FIBER(args[0]), args, false, true, "transfer to");
 }
References AS_FIBER, and runFiber().
DEF_PRIMITIVE() [17/105]
DEF_PRIMITIVE (fiber_transferError)
Definition at line 184 of file wren_core.c.
 {
   runFiber(vm, AS_FIBER(args[0]), args, false, true, "transfer to");
   vm->fiber->error = args[1];
   return false;
 }
References AS_FIBER, and runFiber().
DEF_PRIMITIVE() [18/105]
DEF_PRIMITIVE (fiber_try)
Definition at line 191 of file wren_core.c.
 {
   runFiber(vm, AS_FIBER(args[0]), args, true, false, "try");
   // If we're switching to a valid fiber to try, remember that we're trying it.
   if (!wrenHasError(vm->fiber)) vm->fiber->state = FIBER_TRY;
   return false;
 }
References AS_FIBER, FIBER_TRY, runFiber(), and wrenHasError().
DEF_PRIMITIVE() [19/105]
DEF_PRIMITIVE (fiber_try1)
Definition at line 200 of file wren_core.c.
 {
   runFiber(vm, AS_FIBER(args[0]), args, true, true, "try");
   // If we're switching to a valid fiber to try, remember that we're trying it.
   if (!wrenHasError(vm->fiber)) vm->fiber->state = FIBER_TRY;
   return false;
 }
References AS_FIBER, FIBER_TRY, runFiber(), and wrenHasError().
DEF_PRIMITIVE() [20/105]
DEF_PRIMITIVE (fiber_yield)
Definition at line 209 of file wren_core.c.
 {
   ObjFiber* current = vm->fiber;
   vm->fiber = current->caller;
   // Unhook this fiber from the one that called it.
   current->caller = NULL;
   current->state = FIBER_OTHER;
   if (vm->fiber != NULL)
   {
     // Make the caller's run method return null.
     vm->fiber->stackTop[-1] = NULL_VAL;
   }
   return false;
 }
References sObjFiber::caller, FIBER_OTHER, NULL, NULL_VAL, and sObjFiber::state.
DEF_PRIMITIVE() [21/105]
DEF_PRIMITIVE (fiber_yield1)
Definition at line 227 of file wren_core.c.
 {
   ObjFiber* current = vm->fiber;
   vm->fiber = current->caller;
   // Unhook this fiber from the one that called it.
   current->caller = NULL;
   current->state = FIBER_OTHER;
   if (vm->fiber != NULL)
   {
     // Make the caller's run method return the argument passed to yield.
     vm->fiber->stackTop[-1] = args[1];
     // When the yielding fiber resumes, we'll store the result of the yield
     // call in its stack. Since Fiber.yield(value) has two arguments (the Fiber
     // class and the value) and we only need one slot for the result, discard
     // the other slot now.
     current->stackTop--;
   }
   return false;
 }
References sObjFiber::caller, FIBER_OTHER, NULL, sObjFiber::stackTop, and sObjFiber::state.
DEF_PRIMITIVE() [22/105]
DEF_PRIMITIVE (fn_arity)
Definition at line 259 of file wren_core.c.
 {
   RETURN_NUM(AS_CLOSURE(args[0])->fn->arity);
 }
References AS_CLOSURE, fn, and RETURN_NUM.
DEF_PRIMITIVE() [23/105]
DEF_PRIMITIVE (fn_new)
Definition at line 251 of file wren_core.c.
 {
   if (!validateFn(vm, args[1], "Argument")) return false;
   // The block argument is already a function, so just return it.
   RETURN_VAL(args[1]);
 }
References RETURN_VAL, and validateFn().
DEF_PRIMITIVE() [24/105]
DEF_PRIMITIVE (fn_toString)
Definition at line 295 of file wren_core.c.
 {
   RETURN_VAL(CONST_STRING(vm, "<fn>"));
 }
References CONST_STRING, and RETURN_VAL.
DEF_PRIMITIVE() [25/105]
DEF_PRIMITIVE (list_add)
Definition at line 322 of file wren_core.c.
 {
   wrenValueBufferWrite(vm, &AS_LIST(args[0])->elements, args[1]);
   RETURN_VAL(args[1]);
 }
References AS_LIST, and RETURN_VAL.
DEF_PRIMITIVE() [26/105]
DEF_PRIMITIVE (list_addCore)
Definition at line 331 of file wren_core.c.
 {
   wrenValueBufferWrite(vm, &AS_LIST(args[0])->elements, args[1]);
   // Return the list.
   RETURN_VAL(args[0]);
 }
References AS_LIST, and RETURN_VAL.
DEF_PRIMITIVE() [27/105]
DEF_PRIMITIVE (list_clear)
Definition at line 339 of file wren_core.c.
 {
   wrenValueBufferClear(vm, &AS_LIST(args[0])->elements);
   RETURN_NULL;
 }
References AS_LIST, and RETURN_NULL.
DEF_PRIMITIVE() [28/105]
DEF_PRIMITIVE (list_count)
Definition at line 345 of file wren_core.c.
 {
   RETURN_NUM(AS_LIST(args[0])->elements.count);
 }
References AS_LIST, and RETURN_NUM.
DEF_PRIMITIVE() [29/105]
DEF_PRIMITIVE (list_filled)
Definition at line 301 of file wren_core.c.
 {
   if (!validateInt(vm, args[1], "Size")) return false;
   if (AS_NUM(args[1]) < 0) RETURN_ERROR("Size cannot be negative.");
   uint32_t size = (uint32_t)AS_NUM(args[1]);
   ObjList* list = wrenNewList(vm, size);
   for (uint32_t i = 0; i < size; i++)
   {
     list->elements.data[i] = args[2];
   }
   RETURN_OBJ(list);
 }
References AS_NUM, list(), RETURN_ERROR, RETURN_OBJ, validateInt(), and wrenNewList().
DEF_PRIMITIVE() [30/105]
DEF_PRIMITIVE (list_indexOf)
Definition at line 409 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   RETURN_NUM(wrenListIndexOf(vm, list, args[1]));
 }
References AS_LIST, list(), RETURN_NUM, and wrenListIndexOf().
DEF_PRIMITIVE() [31/105]
DEF_PRIMITIVE (list_insert)
Definition at line 350 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   // count + 1 here so you can "insert" at the very end.
   uint32_t index = validateIndex(vm, args[1], list->elements.count + 1,
                                  "Index");
   if (index == UINT32_MAX) return false;
   wrenListInsert(vm, list, args[2], index);
   RETURN_VAL(args[2]);
 }
References AS_LIST, list(), RETURN_VAL, validateIndex(), and wrenListInsert().
DEF_PRIMITIVE() [32/105]
DEF_PRIMITIVE (list_iterate)
Definition at line 363 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   // If we're starting the iteration, return the first index.
   if (IS_NULL(args[1]))
   {
     if (list->elements.count == 0) RETURN_FALSE;
     RETURN_NUM(0);
   }
   if (!validateInt(vm, args[1], "Iterator")) return false;
   // Stop if we're out of bounds.
   double index = AS_NUM(args[1]);
   if (index < 0 || index >= list->elements.count - 1) RETURN_FALSE;
   // Otherwise, move to the next index.
   RETURN_NUM(index + 1);
 }
References AS_LIST, AS_NUM, IS_NULL, list(), RETURN_FALSE, RETURN_NUM, and validateInt().
DEF_PRIMITIVE() [33/105]
DEF_PRIMITIVE (list_iteratorValue)
Definition at line 384 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   uint32_t index = validateIndex(vm, args[1], list->elements.count, "Iterator");
   if (index == UINT32_MAX) return false;
   RETURN_VAL(list->elements.data[index]);
 }
References AS_LIST, list(), RETURN_VAL, and validateIndex().
DEF_PRIMITIVE() [34/105]
DEF_PRIMITIVE (list_new)
Definition at line 317 of file wren_core.c.
 {
   RETURN_OBJ(wrenNewList(vm, 0));
 }
References RETURN_OBJ, and wrenNewList().
DEF_PRIMITIVE() [35/105]
DEF_PRIMITIVE (list_removeAt)
Definition at line 393 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   uint32_t index = validateIndex(vm, args[1], list->elements.count, "Index");
   if (index == UINT32_MAX) return false;
   RETURN_VAL(wrenListRemoveAt(vm, list, index));
 }
References AS_LIST, list(), RETURN_VAL, validateIndex(), and wrenListRemoveAt().
DEF_PRIMITIVE() [36/105]
DEF_PRIMITIVE (list_removeValue)
Definition at line 402 of file wren_core.c.
{
   ObjList* list = AS_LIST(args[0]);
   int index = wrenListIndexOf(vm, list, args[1]);
   if(index == -1) RETURN_NULL;
   RETURN_VAL(wrenListRemoveAt(vm, list, index));
 }
References AS_LIST, list(), RETURN_NULL, RETURN_VAL, wrenListIndexOf(), and wrenListRemoveAt().
DEF_PRIMITIVE() [37/105]
DEF_PRIMITIVE (list_subscript)
Definition at line 430 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   if (IS_NUM(args[1]))
   {
     uint32_t index = validateIndex(vm, args[1], list->elements.count,
                                    "Subscript");
     if (index == UINT32_MAX) return false;
     RETURN_VAL(list->elements.data[index]);
   }
   if (!IS_RANGE(args[1]))
   {
     RETURN_ERROR("Subscript must be a number or a range.");
   }
   int step;
   uint32_t count = list->elements.count;
   uint32_t start = calculateRange(vm, AS_RANGE(args[1]), &count, &step);
   if (start == UINT32_MAX) return false;
   ObjList* result = wrenNewList(vm, count);
   for (uint32_t i = 0; i < count; i++)
   {
     result->elements.data[i] = list->elements.data[start + i * step];
   }
   RETURN_OBJ(result);
 }
References AS_LIST, AS_RANGE, calculateRange(), count, ObjList::elements, IS_NUM, IS_RANGE, list(), RETURN_ERROR, RETURN_OBJ, RETURN_VAL, validateIndex(), and wrenNewList().
DEF_PRIMITIVE() [38/105]
DEF_PRIMITIVE (list_subscriptSetter)
Definition at line 462 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   uint32_t index = validateIndex(vm, args[1], list->elements.count,
                                  "Subscript");
   if (index == UINT32_MAX) return false;
   list->elements.data[index] = args[2];
   RETURN_VAL(args[2]);
 }
References AS_LIST, list(), RETURN_VAL, and validateIndex().
DEF_PRIMITIVE() [39/105]
DEF_PRIMITIVE (list_swap)
Definition at line 415 of file wren_core.c.
 {
   ObjList* list = AS_LIST(args[0]);
   uint32_t indexA = validateIndex(vm, args[1], list->elements.count, "Index 0");
   if (indexA == UINT32_MAX) return false;
   uint32_t indexB = validateIndex(vm, args[2], list->elements.count, "Index 1");
   if (indexB == UINT32_MAX) return false;
   Value a = list->elements.data[indexA];
   list->elements.data[indexA] = list->elements.data[indexB];
   list->elements.data[indexB] = a;
   RETURN_NULL;
 }
References AS_LIST, list(), RETURN_NULL, and validateIndex().
DEF_PRIMITIVE() [40/105]
DEF_PRIMITIVE (map_addCore)
Definition at line 500 of file wren_core.c.
 {
   if (!validateKey(vm, args[1])) return false;
   wrenMapSet(vm, AS_MAP(args[0]), args[1], args[2]);
   // Return the map itself.
   RETURN_VAL(args[0]);
 }
References AS_MAP, RETURN_VAL, validateKey(), and wrenMapSet().
DEF_PRIMITIVE() [41/105]
DEF_PRIMITIVE (map_clear)
Definition at line 510 of file wren_core.c.
 {
   wrenMapClear(vm, AS_MAP(args[0]));
   RETURN_NULL;
 }
References AS_MAP, RETURN_NULL, and wrenMapClear().
DEF_PRIMITIVE() [42/105]
DEF_PRIMITIVE (map_containsKey)
Definition at line 516 of file wren_core.c.
 {
   if (!validateKey(vm, args[1])) return false;
   RETURN_BOOL(!IS_UNDEFINED(wrenMapGet(AS_MAP(args[0]), args[1])));
 }
References AS_MAP, IS_UNDEFINED, RETURN_BOOL, validateKey(), and wrenMapGet().
DEF_PRIMITIVE() [43/105]
DEF_PRIMITIVE (map_count)
Definition at line 523 of file wren_core.c.
 {
   RETURN_NUM(AS_MAP(args[0])->count);
 }
References AS_MAP, count, and RETURN_NUM.
DEF_PRIMITIVE() [44/105]
DEF_PRIMITIVE (map_iterate)
Definition at line 528 of file wren_core.c.
 {
   ObjMap* map = AS_MAP(args[0]);
   if (map->count == 0) RETURN_FALSE;
   // If we're starting the iteration, start at the first used entry.
   uint32_t index = 0;
   // Otherwise, start one past the last entry we stopped at.
   if (!IS_NULL(args[1]))
   {
     if (!validateInt(vm, args[1], "Iterator")) return false;
     if (AS_NUM(args[1]) < 0) RETURN_FALSE;
     index = (uint32_t)AS_NUM(args[1]);
     if (index >= map->capacity) RETURN_FALSE;
     // Advance the iterator.
     index++;
   }
   // Find a used entry, if any.
   for (; index < map->capacity; index++)
   {
     if (!IS_UNDEFINED(map->entries[index].key)) RETURN_NUM(index);
   }
   // If we get here, walked all of the entries.
   RETURN_FALSE;
 }
References AS_MAP, AS_NUM, IS_NULL, IS_UNDEFINED, map(), RETURN_FALSE, RETURN_NUM, and validateInt().
DEF_PRIMITIVE() [45/105]
DEF_PRIMITIVE (map_keyIteratorValue)
Definition at line 568 of file wren_core.c.
 {
   ObjMap* map = AS_MAP(args[0]);
   uint32_t index = validateIndex(vm, args[1], map->capacity, "Iterator");
   if (index == UINT32_MAX) return false;
   MapEntry* entry = &map->entries[index];
   if (IS_UNDEFINED(entry->key))
   {
     RETURN_ERROR("Invalid map iterator.");
   }
   RETURN_VAL(entry->key);
 }
References AS_MAP, IS_UNDEFINED, MapEntry::key, map(), RETURN_ERROR, RETURN_VAL, and validateIndex().
DEF_PRIMITIVE() [46/105]
DEF_PRIMITIVE (map_new)
Definition at line 473 of file wren_core.c.
 {
   RETURN_OBJ(wrenNewMap(vm));
 }
References RETURN_OBJ, and wrenNewMap().
DEF_PRIMITIVE() [47/105]
DEF_PRIMITIVE (map_remove)
Definition at line 561 of file wren_core.c.
 {
   if (!validateKey(vm, args[1])) return false;
   RETURN_VAL(wrenMapRemoveKey(vm, AS_MAP(args[0]), args[1]));
 }
References AS_MAP, RETURN_VAL, validateKey(), and wrenMapRemoveKey().
DEF_PRIMITIVE() [48/105]
DEF_PRIMITIVE (map_subscript)
Definition at line 478 of file wren_core.c.
 {
   if (!validateKey(vm, args[1])) return false;
   ObjMap* map = AS_MAP(args[0]);
   Value value = wrenMapGet(map, args[1]);
   if (IS_UNDEFINED(value)) RETURN_NULL;
   RETURN_VAL(value);
 }
References AS_MAP, IS_UNDEFINED, map(), RETURN_NULL, RETURN_VAL, validateKey(), and wrenMapGet().
DEF_PRIMITIVE() [49/105]
DEF_PRIMITIVE (map_subscriptSetter)
Definition at line 489 of file wren_core.c.
 {
   if (!validateKey(vm, args[1])) return false;
   wrenMapSet(vm, AS_MAP(args[0]), args[1], args[2]);
   RETURN_VAL(args[2]);
 }
References AS_MAP, RETURN_VAL, validateKey(), and wrenMapSet().
DEF_PRIMITIVE() [50/105]
DEF_PRIMITIVE (map_valueIteratorValue)
Definition at line 583 of file wren_core.c.
 {
   ObjMap* map = AS_MAP(args[0]);
   uint32_t index = validateIndex(vm, args[1], map->capacity, "Iterator");
   if (index == UINT32_MAX) return false;
   MapEntry* entry = &map->entries[index];
   if (IS_UNDEFINED(entry->key))
   {
     RETURN_ERROR("Invalid map iterator.");
   }
   RETURN_VAL(entry->value);
 }
References AS_MAP, IS_UNDEFINED, MapEntry::key, map(), RETURN_ERROR, RETURN_VAL, validateIndex(), and MapEntry::value.
DEF_PRIMITIVE() [51/105]
DEF_PRIMITIVE (null_not)
Definition at line 598 of file wren_core.c.
 {
   RETURN_VAL(TRUE_VAL);
 }
References RETURN_VAL, and TRUE_VAL.
DEF_PRIMITIVE() [52/105]
DEF_PRIMITIVE (null_toString)
Definition at line 603 of file wren_core.c.
 {
   RETURN_VAL(CONST_STRING(vm, "null"));
 }
References CONST_STRING, and RETURN_VAL.
DEF_PRIMITIVE() [53/105]
DEF_PRIMITIVE (num_atan2)
Definition at line 750 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "x value")) return false;
   RETURN_NUM(atan2(AS_NUM(args[0]), AS_NUM(args[1])));
 }
References AS_NUM, RETURN_NUM, and validateNum().
DEF_PRIMITIVE() [54/105]
DEF_PRIMITIVE (num_bangeq)
Definition at line 720 of file wren_core.c.
 {
   if (!IS_NUM(args[1])) RETURN_TRUE;
   RETURN_BOOL(AS_NUM(args[0]) != AS_NUM(args[1]));
 }
References AS_NUM, IS_NUM, RETURN_BOOL, and RETURN_TRUE.
DEF_PRIMITIVE() [55/105]
DEF_PRIMITIVE (num_bitwiseNot)
Definition at line 726 of file wren_core.c.
 {
   // Bitwise operators always work on 32-bit unsigned ints.
   RETURN_NUM(~(uint32_t)AS_NUM(args[0]));
 }
References AS_NUM, and RETURN_NUM.
DEF_PRIMITIVE() [56/105]
DEF_PRIMITIVE (num_clamp)
Definition at line 775 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Min value")) return false;
   if (!validateNum(vm, args[2], "Max value")) return false;
   double value = AS_NUM(args[0]);
   double min = AS_NUM(args[1]);
   double max = AS_NUM(args[2]);
   double result = (value < min) ? min : ((value > max) ? max : value);
   RETURN_NUM(result);
 }
References AS_NUM, RETURN_NUM, and validateNum().
DEF_PRIMITIVE() [57/105]
DEF_PRIMITIVE (num_dotDot)
Definition at line 732 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Right hand side of range")) return false;
   double from = AS_NUM(args[0]);
   double to = AS_NUM(args[1]);
   RETURN_VAL(wrenNewRange(vm, from, to, true));
 }
References AS_NUM, RETURN_VAL, validateNum(), and wrenNewRange().
DEF_PRIMITIVE() [58/105]
DEF_PRIMITIVE (num_dotDotDot)
Definition at line 741 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Right hand side of range")) return false;
   double from = AS_NUM(args[0]);
   double to = AS_NUM(args[1]);
   RETURN_VAL(wrenNewRange(vm, from, to, false));
 }
References AS_NUM, RETURN_VAL, validateNum(), and wrenNewRange().
DEF_PRIMITIVE() [59/105]
DEF_PRIMITIVE (num_eqeq)
Definition at line 714 of file wren_core.c.
 {
   if (!IS_NUM(args[1])) RETURN_FALSE;
   RETURN_BOOL(AS_NUM(args[0]) == AS_NUM(args[1]));
 }
References AS_NUM, IS_NUM, RETURN_BOOL, and RETURN_FALSE.
DEF_PRIMITIVE() [60/105]
DEF_PRIMITIVE (num_fraction)
Definition at line 794 of file wren_core.c.
 {
   double unused;
   RETURN_NUM(modf(AS_NUM(args[0]) , &unused));
 }
References AS_NUM, and RETURN_NUM.
DEF_PRIMITIVE() [61/105]
DEF_PRIMITIVE (num_fromString)
Definition at line 608 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Argument")) return false;
   ObjString* string = AS_STRING(args[1]);
   // Corner case: Can't parse an empty string.
   if (string->length == 0) RETURN_NULL;
   errno = 0;
   char* end;
   double number = strtod(string->value, &end);
   // Skip past any trailing whitespace.
   while (*end != '\0' && isspace((unsigned char)*end)) end++;
   if (errno == ERANGE) RETURN_ERROR("Number literal is too large.");
   // We must have consumed the entire string. Otherwise, it contains non-number
   // characters and we can't parse it.
   if (end < string->value + string->length) RETURN_NULL;
   RETURN_NUM(number);
 }
References AS_STRING, sObjString::length, RETURN_ERROR, RETURN_NULL, RETURN_NUM, validateString(), and sObjString::value.
DEF_PRIMITIVE() [62/105]
DEF_PRIMITIVE (num_isInfinity)
Definition at line 800 of file wren_core.c.
 {
   RETURN_BOOL(isinf(AS_NUM(args[0])));
 }
References AS_NUM, and RETURN_BOOL.
DEF_PRIMITIVE() [63/105]
DEF_PRIMITIVE (num_isInteger)
Definition at line 805 of file wren_core.c.
 {
   double value = AS_NUM(args[0]);
   if (isnan(value) || isinf(value)) RETURN_FALSE;
   RETURN_BOOL(trunc(value) == value);
 }
References AS_NUM, RETURN_BOOL, and RETURN_FALSE.
DEF_PRIMITIVE() [64/105]
DEF_PRIMITIVE (num_isNan)
Definition at line 812 of file wren_core.c.
 {
   RETURN_BOOL(isnan(AS_NUM(args[0])));
 }
References AS_NUM, and RETURN_BOOL.
DEF_PRIMITIVE() [65/105]
DEF_PRIMITIVE (num_max)
Definition at line 766 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Other value")) return false;
   double value = AS_NUM(args[0]);
   double other = AS_NUM(args[1]);
   RETURN_NUM(value > other ? value : other);
 }
References AS_NUM, RETURN_NUM, and validateNum().
DEF_PRIMITIVE() [66/105]
DEF_PRIMITIVE (num_min)
Definition at line 757 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Other value")) return false;
   double value = AS_NUM(args[0]);
   double other = AS_NUM(args[1]);
   RETURN_NUM(value <= other ? value : other);
 }
References AS_NUM, RETURN_NUM, and validateNum().
DEF_PRIMITIVE() [67/105]
DEF_PRIMITIVE (num_mod)
Definition at line 708 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Right operand")) return false;
   RETURN_NUM(fmod(AS_NUM(args[0]), AS_NUM(args[1])));
 }
References AS_NUM, RETURN_NUM, and validateNum().
DEF_PRIMITIVE() [68/105]
DEF_PRIMITIVE (num_pow)
Definition at line 787 of file wren_core.c.
 {
   if (!validateNum(vm, args[1], "Power value")) return false;
   RETURN_NUM(pow(AS_NUM(args[0]), AS_NUM(args[1])));
 }
References AS_NUM, RETURN_NUM, and validateNum().
DEF_PRIMITIVE() [69/105]
DEF_PRIMITIVE (num_sign)
Definition at line 817 of file wren_core.c.
 {
   double value = AS_NUM(args[0]);
   if (value > 0)
   {
     RETURN_NUM(1);
   }
   else if (value < 0)
   {
     RETURN_NUM(-1);
   }
   else
   {
     RETURN_NUM(0);
   }
 }
References AS_NUM, and RETURN_NUM.
DEF_PRIMITIVE() [70/105]
DEF_PRIMITIVE (num_toString)
Definition at line 834 of file wren_core.c.
 {
   RETURN_VAL(wrenNumToString(vm, AS_NUM(args[0])));
 }
References AS_NUM, RETURN_VAL, and wrenNumToString().
DEF_PRIMITIVE() [71/105]
DEF_PRIMITIVE (num_truncate)
Definition at line 839 of file wren_core.c.
 {
   double integer;
   modf(AS_NUM(args[0]) , &integer);
   RETURN_NUM(integer);
 }
References AS_NUM, and RETURN_NUM.
DEF_PRIMITIVE() [72/105]
DEF_PRIMITIVE (object_bangeq)
Definition at line 861 of file wren_core.c.
 {
   RETURN_BOOL(!wrenValuesEqual(args[0], args[1]));
 }
References RETURN_BOOL, and wrenValuesEqual().
DEF_PRIMITIVE() [73/105]
DEF_PRIMITIVE (object_eqeq)
Definition at line 856 of file wren_core.c.
 {
   RETURN_BOOL(wrenValuesEqual(args[0], args[1]));
 }
References RETURN_BOOL, and wrenValuesEqual().
DEF_PRIMITIVE() [74/105]
DEF_PRIMITIVE (object_is)
Definition at line 866 of file wren_core.c.
 {
   if (!IS_CLASS(args[1]))
   {
     RETURN_ERROR("Right operand must be a class.");
   }
   ObjClass *classObj = wrenGetClass(vm, args[0]);
   ObjClass *baseClassObj = AS_CLASS(args[1]);
   // Walk the superclass chain looking for the class.
   do
   {
     if (baseClassObj == classObj) RETURN_BOOL(true);
     classObj = classObj->superclass;
   }
   while (classObj != NULL);
   RETURN_BOOL(false);
 }
References AS_CLASS, IS_CLASS, NULL, RETURN_BOOL, RETURN_ERROR, sObjClass::superclass, and wrenGetClass().
DEF_PRIMITIVE() [75/105]
DEF_PRIMITIVE (object_not)
Definition at line 851 of file wren_core.c.
 {
   RETURN_VAL(FALSE_VAL);
 }
References FALSE_VAL, and RETURN_VAL.
DEF_PRIMITIVE() [76/105]
DEF_PRIMITIVE (object_same)
Definition at line 846 of file wren_core.c.
 {
   RETURN_BOOL(wrenValuesEqual(args[1], args[2]));
 }
References RETURN_BOOL, and wrenValuesEqual().
DEF_PRIMITIVE() [77/105]
DEF_PRIMITIVE (object_toString)
Definition at line 888 of file wren_core.c.
 {
   Obj* obj = AS_OBJ(args[0]);
   Value name = OBJ_VAL(obj->classObj->name);
   RETURN_VAL(wrenStringFormat(vm, "instance of @", name));
 }
References AS_OBJ, sObj::classObj, name, sObjClass::name, OBJ_VAL, RETURN_VAL, and wrenStringFormat().
DEF_PRIMITIVE() [78/105]
DEF_PRIMITIVE (object_type)
Definition at line 895 of file wren_core.c.
 {
   RETURN_OBJ(wrenGetClass(vm, args[0]));
 }
References RETURN_OBJ, and wrenGetClass().
DEF_PRIMITIVE() [79/105]
DEF_PRIMITIVE (range_from)
Definition at line 900 of file wren_core.c.
 {
   RETURN_NUM(AS_RANGE(args[0])->from);
 }
References AS_RANGE, and RETURN_NUM.
DEF_PRIMITIVE() [80/105]
DEF_PRIMITIVE (range_isInclusive)
Definition at line 922 of file wren_core.c.
 {
   RETURN_BOOL(AS_RANGE(args[0])->isInclusive);
 }
References AS_RANGE, and RETURN_BOOL.
DEF_PRIMITIVE() [81/105]
DEF_PRIMITIVE (range_iterate)
Definition at line 927 of file wren_core.c.
 {
   ObjRange* range = AS_RANGE(args[0]);
   // Special case: empty range.
   if (range->from == range->to && !range->isInclusive) RETURN_FALSE;
   // Start the iteration.
   if (IS_NULL(args[1])) RETURN_NUM(range->from);
   if (!validateNum(vm, args[1], "Iterator")) return false;
   double iterator = AS_NUM(args[1]);
   // Iterate towards [to] from [from].
   if (range->from < range->to)
   {
     iterator++;
     if (iterator > range->to) RETURN_FALSE;
   }
   else
   {
     iterator--;
     if (iterator < range->to) RETURN_FALSE;
   }
   if (!range->isInclusive && iterator == range->to) RETURN_FALSE;
   RETURN_NUM(iterator);
 }
References AS_NUM, AS_RANGE, ObjRange::from, IS_NULL, ObjRange::isInclusive, RETURN_FALSE, RETURN_NUM, ObjRange::to, and validateNum().
DEF_PRIMITIVE() [82/105]
DEF_PRIMITIVE (range_iteratorValue)
Definition at line 958 of file wren_core.c.
 {
   // Assume the iterator is a number so that is the value of the range.
   RETURN_VAL(args[1]);
 }
References RETURN_VAL.
DEF_PRIMITIVE() [83/105]
DEF_PRIMITIVE (range_max)
Definition at line 916 of file wren_core.c.
 {
   ObjRange* range = AS_RANGE(args[0]);
   RETURN_NUM(fmax(range->from, range->to));
 }
References AS_RANGE, ObjRange::from, RETURN_NUM, and ObjRange::to.
DEF_PRIMITIVE() [84/105]
DEF_PRIMITIVE (range_min)
Definition at line 910 of file wren_core.c.
 {
   ObjRange* range = AS_RANGE(args[0]);
   RETURN_NUM(fmin(range->from, range->to));
 }
References AS_RANGE, ObjRange::from, RETURN_NUM, and ObjRange::to.
DEF_PRIMITIVE() [85/105]
DEF_PRIMITIVE (range_to)
Definition at line 905 of file wren_core.c.
 {
   RETURN_NUM(AS_RANGE(args[0])->to);
 }
References AS_RANGE, and RETURN_NUM.
DEF_PRIMITIVE() [86/105]
DEF_PRIMITIVE (range_toString)
Definition at line 964 of file wren_core.c.
 {
   ObjRange* range = AS_RANGE(args[0]);
   Value from = wrenNumToString(vm, range->from);
   wrenPushRoot(vm, AS_OBJ(from));
   Value to = wrenNumToString(vm, range->to);
   wrenPushRoot(vm, AS_OBJ(to));
   Value result = wrenStringFormat(vm, "@$@", from,
                                   range->isInclusive ? ".." : "...", to);
   wrenPopRoot(vm);
   wrenPopRoot(vm);
   RETURN_VAL(result);
 }
References AS_OBJ, AS_RANGE, ObjRange::from, ObjRange::isInclusive, RETURN_VAL, ObjRange::to, wrenNumToString(), wrenPopRoot(), wrenPushRoot(), and wrenStringFormat().
DEF_PRIMITIVE() [87/105]
DEF_PRIMITIVE (string_byteAt)
Definition at line 1014 of file wren_core.c.
 {
   ObjString* string = AS_STRING(args[0]);
   uint32_t index = validateIndex(vm, args[1], string->length, "Index");
   if (index == UINT32_MAX) return false;
   RETURN_NUM((uint8_t)string->value[index]);
 }
References AS_STRING, sObjString::length, RETURN_NUM, validateIndex(), and sObjString::value.
DEF_PRIMITIVE() [88/105]
DEF_PRIMITIVE (string_byteCount)
Definition at line 1024 of file wren_core.c.
 {
   RETURN_NUM(AS_STRING(args[0])->length);
 }
References AS_STRING, and RETURN_NUM.
DEF_PRIMITIVE() [89/105]
DEF_PRIMITIVE (string_codePointAt)
Definition at line 1029 of file wren_core.c.
 {
   ObjString* string = AS_STRING(args[0]);
   uint32_t index = validateIndex(vm, args[1], string->length, "Index");
   if (index == UINT32_MAX) return false;
   // If we are in the middle of a UTF-8 sequence, indicate that.
   const uint8_t* bytes = (uint8_t*)string->value;
   if ((bytes[index] & 0xc0) == 0x80) RETURN_NUM(-1);
   // Decode the UTF-8 sequence.
   RETURN_NUM(wrenUtf8Decode((uint8_t*)string->value + index,
                             string->length - index));
 }
References AS_STRING, if(), sObjString::length, RETURN_NUM, validateIndex(), sObjString::value, and wrenUtf8Decode().
DEF_PRIMITIVE() [90/105]
DEF_PRIMITIVE (string_contains)
Definition at line 1045 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Argument")) return false;
   ObjString* string = AS_STRING(args[0]);
   ObjString* search = AS_STRING(args[1]);
   RETURN_BOOL(wrenStringFind(string, search, 0) != UINT32_MAX);
 }
References AS_STRING, RETURN_BOOL, validateString(), and wrenStringFind().
DEF_PRIMITIVE() [91/105]
DEF_PRIMITIVE (string_endsWith)
Definition at line 1055 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Argument")) return false;
   ObjString* string = AS_STRING(args[0]);
   ObjString* search = AS_STRING(args[1]);
   // Edge case: If the search string is longer then return false right away.
   if (search->length > string->length) RETURN_FALSE;
   RETURN_BOOL(memcmp(string->value + string->length - search->length,
                      search->value, search->length) == 0);
 }
References AS_STRING, sObjString::length, RETURN_BOOL, RETURN_FALSE, validateString(), and sObjString::value.
DEF_PRIMITIVE() [92/105]
DEF_PRIMITIVE (string_fromByte)
Definition at line 999 of file wren_core.c.
 {
   if (!validateInt(vm, args[1], "Byte")) return false;
   int byte = (int) AS_NUM(args[1]);
   if (byte < 0)
   {
     RETURN_ERROR("Byte cannot be negative.");
   }
   else if (byte > 0xff)
   {
     RETURN_ERROR("Byte cannot be greater than 0xff.");
   }
   RETURN_VAL(wrenStringFromByte(vm, (uint8_t) byte));
 }
References AS_NUM, RETURN_ERROR, RETURN_VAL, validateInt(), and wrenStringFromByte().
DEF_PRIMITIVE() [93/105]
DEF_PRIMITIVE (string_fromCodePoint)
Definition at line 982 of file wren_core.c.
 {
   if (!validateInt(vm, args[1], "Code point")) return false;
   int codePoint = (int)AS_NUM(args[1]);
   if (codePoint < 0)
   {
     RETURN_ERROR("Code point cannot be negative.");
   }
   else if (codePoint > 0x10ffff)
   {
     RETURN_ERROR("Code point cannot be greater than 0x10ffff.");
   }
   RETURN_VAL(wrenStringFromCodePoint(vm, codePoint));
 }
References AS_NUM, RETURN_ERROR, RETURN_VAL, validateInt(), and wrenStringFromCodePoint().
DEF_PRIMITIVE() [94/105]
DEF_PRIMITIVE (string_indexOf1)
Definition at line 1069 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Argument")) return false;
   ObjString* string = AS_STRING(args[0]);
   ObjString* search = AS_STRING(args[1]);
   uint32_t index = wrenStringFind(string, search, 0);
   RETURN_NUM(index == UINT32_MAX ? -1 : (int)index);
 }
References AS_STRING, RETURN_NUM, validateString(), and wrenStringFind().
DEF_PRIMITIVE() [95/105]
DEF_PRIMITIVE (string_indexOf2)
Definition at line 1080 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Argument")) return false;
   ObjString* string = AS_STRING(args[0]);
   ObjString* search = AS_STRING(args[1]);
   uint32_t start = validateIndex(vm, args[2], string->length, "Start");
   if (start == UINT32_MAX) return false;
   uint32_t index = wrenStringFind(string, search, start);
   RETURN_NUM(index == UINT32_MAX ? -1 : (int)index);
 }
References AS_STRING, sObjString::length, RETURN_NUM, validateIndex(), validateString(), and wrenStringFind().
DEF_PRIMITIVE() [96/105]
DEF_PRIMITIVE (string_iterate)
Definition at line 1093 of file wren_core.c.
 {
   ObjString* string = AS_STRING(args[0]);
   // If we're starting the iteration, return the first index.
   if (IS_NULL(args[1]))
   {
     if (string->length == 0) RETURN_FALSE;
     RETURN_NUM(0);
   }
   if (!validateInt(vm, args[1], "Iterator")) return false;
   if (AS_NUM(args[1]) < 0) RETURN_FALSE;
   uint32_t index = (uint32_t)AS_NUM(args[1]);
   // Advance to the beginning of the next UTF-8 sequence.
   do
   {
     index++;
     if (index >= string->length) RETURN_FALSE;
   } while ((string->value[index] & 0xc0) == 0x80);
   RETURN_NUM(index);
 }
References AS_NUM, AS_STRING, IS_NULL, sObjString::length, RETURN_FALSE, RETURN_NUM, validateInt(), and sObjString::value.
DEF_PRIMITIVE() [97/105]
DEF_PRIMITIVE (string_iterateByte)
Definition at line 1119 of file wren_core.c.
 {
   ObjString* string = AS_STRING(args[0]);
   // If we're starting the iteration, return the first index.
   if (IS_NULL(args[1]))
   {
     if (string->length == 0) RETURN_FALSE;
     RETURN_NUM(0);
   }
   if (!validateInt(vm, args[1], "Iterator")) return false;
   if (AS_NUM(args[1]) < 0) RETURN_FALSE;
   uint32_t index = (uint32_t)AS_NUM(args[1]);
   // Advance to the next byte.
   index++;
   if (index >= string->length) RETURN_FALSE;
   RETURN_NUM(index);
 }
References AS_NUM, AS_STRING, IS_NULL, sObjString::length, RETURN_FALSE, RETURN_NUM, and validateInt().
DEF_PRIMITIVE() [98/105]
DEF_PRIMITIVE (string_iteratorValue)
Definition at line 1142 of file wren_core.c.
 {
   ObjString* string = AS_STRING(args[0]);
   uint32_t index = validateIndex(vm, args[1], string->length, "Iterator");
   if (index == UINT32_MAX) return false;
   RETURN_VAL(wrenStringCodePointAt(vm, string, index));
 }
References AS_STRING, sObjString::length, RETURN_VAL, validateIndex(), and wrenStringCodePointAt().
DEF_PRIMITIVE() [99/105]
DEF_PRIMITIVE (string_plus)
Definition at line 1164 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Right operand")) return false;
   RETURN_VAL(wrenStringFormat(vm, "@@", args[0], args[1]));
 }
References RETURN_VAL, validateString(), and wrenStringFormat().
DEF_PRIMITIVE() [100/105]
DEF_PRIMITIVE (string_startsWith)
Definition at line 1151 of file wren_core.c.
 {
   if (!validateString(vm, args[1], "Argument")) return false;
   ObjString* string = AS_STRING(args[0]);
   ObjString* search = AS_STRING(args[1]);
   // Edge case: If the search string is longer then return false right away.
   if (search->length > string->length) RETURN_FALSE;
   RETURN_BOOL(memcmp(string->value, search->value, search->length) == 0);
 }
References AS_STRING, sObjString::length, RETURN_BOOL, RETURN_FALSE, validateString(), and sObjString::value.
DEF_PRIMITIVE() [101/105]
DEF_PRIMITIVE (string_subscript)
Definition at line 1170 of file wren_core.c.
 {
   ObjString* string = AS_STRING(args[0]);
   if (IS_NUM(args[1]))
   {
     int index = validateIndex(vm, args[1], string->length, "Subscript");
     if (index == -1) return false;
     RETURN_VAL(wrenStringCodePointAt(vm, string, index));
   }
   if (!IS_RANGE(args[1]))
   {
     RETURN_ERROR("Subscript must be a number or a range.");
   }
   int step;
   uint32_t count = string->length;
   int start = calculateRange(vm, AS_RANGE(args[1]), &count, &step);
   if (start == -1) return false;
   RETURN_VAL(wrenNewStringFromRange(vm, string, start, count, step));
 }
References AS_RANGE, AS_STRING, calculateRange(), count, IS_NUM, IS_RANGE, sObjString::length, RETURN_ERROR, RETURN_VAL, validateIndex(), wrenNewStringFromRange(), and wrenStringCodePointAt().
DEF_PRIMITIVE() [102/105]
DEF_PRIMITIVE (string_toString)
Definition at line 1195 of file wren_core.c.
 {
   RETURN_VAL(args[0]);
 }
References RETURN_VAL.
DEF_PRIMITIVE() [103/105]
DEF_PRIMITIVE (system_clock)
Definition at line 1200 of file wren_core.c.
 {
   RETURN_NUM((double)clock() / CLOCKS_PER_SEC);
 }
References RETURN_NUM.
DEF_PRIMITIVE() [104/105]
DEF_PRIMITIVE (system_gc)
Definition at line 1205 of file wren_core.c.
 {
   wrenCollectGarbage(vm);
   RETURN_NULL;
 }
References RETURN_NULL, and wrenCollectGarbage().
DEF_PRIMITIVE() [105/105]
DEF_PRIMITIVE (system_writeString)
Definition at line 1211 of file wren_core.c.
 {
   if (vm->config.writeFn != NULL)
   {
     vm->config.writeFn(vm, AS_CSTRING(args[1]));
   }
   RETURN_VAL(args[1]);
 }
References AS_CSTRING, NULL, and RETURN_VAL.
defineClass()
static ObjClass* defineClass (WrenVM * vm, ObjModule * module, const char * name) static
Definition at line 1222 of file wren_core.c.
 {
   ObjString* nameString = AS_STRING(wrenNewString(vm, name));
   wrenPushRoot(vm, (Obj*)nameString);
   ObjClass* classObj = wrenNewSingleClass(vm, 0, nameString);
   wrenDefineVariable(vm, module, name, nameString->length, OBJ_VAL(classObj), NULL);
   wrenPopRoot(vm);
   return classObj;
 }
References AS_STRING, sObjString::length, name, NULL, OBJ_VAL, wrenDefineVariable(), wrenNewSingleClass(), wrenNewString(), wrenPopRoot(), and wrenPushRoot().
Referenced by wrenInitializeCore().
runFiber()
static bool runFiber (WrenVM * vm, ObjFiber * fiber, Value * args, bool isCall, bool hasValue, const char * verb) static
Definition at line 86 of file wren_core.c.
 {
   if (wrenHasError(fiber))
   {
     RETURN_ERROR_FMT("Cannot $ an aborted fiber.", verb);
   }
   if (isCall)
   {
     // You can't call a called fiber, but you can transfer directly to it,
     // which is why this check is gated on `isCall`. This way, after resuming a
     // suspended fiber, it will run and then return to the fiber that called it
     // and so on.
     if (fiber->caller != NULL) RETURN_ERROR("Fiber has already been called.");
     if (fiber->state == FIBER_ROOT) RETURN_ERROR("Cannot call root fiber.");
     // Remember who ran it.
     fiber->caller = vm->fiber;
   }
   if (fiber->numFrames == 0)
   {
     RETURN_ERROR_FMT("Cannot $ a finished fiber.", verb);
   }
   // When the calling fiber resumes, we'll store the result of the call in its
   // stack. If the call has two arguments (the fiber and the value), we only
   // need one slot for the result, so discard the other slot now.
   if (hasValue) vm->fiber->stackTop--;
   if (fiber->numFrames == 1 &&
       fiber->frames[0].ip == fiber->frames[0].closure->fn->code.data)
   {
     // The fiber is being started for the first time. If its function takes a
     // parameter, bind an argument to it.
     if (fiber->frames[0].closure->fn->arity == 1)
     {
       fiber->stackTop[0] = hasValue ? args[1] : NULL_VAL;
       fiber->stackTop++;
     }
   }
   else
   {
     // The fiber is being resumed, make yield() or transfer() return the result.
     fiber->stackTop[-1] = hasValue ? args[1] : NULL_VAL;
   }
   vm->fiber = fiber;
   return false;
 }
References fiber, WrenVM::fiber, FIBER_ROOT, NULL, NULL_VAL, RETURN_ERROR, RETURN_ERROR_FMT, sObjFiber::stackTop, and wrenHasError().
Referenced by DEF_PRIMITIVE().
wrenInitializeCore()
void wrenInitializeCore (WrenVM * vm)
Definition at line 1235 of file wren_core.c.
 {
   ObjModule* coreModule = wrenNewModule(vm, NULL);
   wrenPushRoot(vm, (Obj*)coreModule);
   // The core module's key is null in the module map.
   wrenMapSet(vm, vm->modules, NULL_VAL, OBJ_VAL(coreModule));
   wrenPopRoot(vm); // coreModule.
   // Define the root Object class. This has to be done a little specially
   // because it has no superclass.
   vm->objectClass = defineClass(vm, coreModule, "Object");
   PRIMITIVE(vm->objectClass, "!", object_not);
   PRIMITIVE(vm->objectClass, "==(_)", object_eqeq);
   PRIMITIVE(vm->objectClass, "!=(_)", object_bangeq);
   PRIMITIVE(vm->objectClass, "is(_)", object_is);
   PRIMITIVE(vm->objectClass, "toString", object_toString);
   PRIMITIVE(vm->objectClass, "type", object_type);
   // Now we can define Class, which is a subclass of Object.
   vm->classClass = defineClass(vm, coreModule, "Class");
   wrenBindSuperclass(vm, vm->classClass, vm->objectClass);
   PRIMITIVE(vm->classClass, "name", class_name);
   PRIMITIVE(vm->classClass, "supertype", class_supertype);
   PRIMITIVE(vm->classClass, "toString", class_toString);
   PRIMITIVE(vm->classClass, "attributes", class_attributes);
   // Finally, we can define Object's metaclass which is a subclass of Class.
   ObjClass* objectMetaclass = defineClass(vm, coreModule, "Object metaclass");
   // Wire up the metaclass relationships now that all three classes are built.
   vm->objectClass->obj.classObj = objectMetaclass;
   objectMetaclass->obj.classObj = vm->classClass;
   vm->classClass->obj.classObj = vm->classClass;
   // Do this after wiring up the metaclasses so objectMetaclass doesn't get
   // collected.
   wrenBindSuperclass(vm, objectMetaclass, vm->classClass);
   PRIMITIVE(objectMetaclass, "same(_,_)", object_same);
   // The core class diagram ends up looking like this, where single lines point
   // to a class's superclass, and double lines point to its metaclass:
   //
   //        .------------------------------------. .====.
   //        |                  .---------------. | #    #
   //        v                  |               v | v    #
   //   .---------.   .-------------------.   .-------.  #
   //   | Object  |==>| Object metaclass  |==>| Class |=="
   //   '---------'   '-------------------'   '-------'
   //        ^                                 ^ ^ ^ ^
   //        |                  .--------------' # | #
   //        |                  |                # | #
   //   .---------.   .-------------------.      # | # -.
   //   |  Base   |==>|  Base metaclass   |======" | #  |
   //   '---------'   '-------------------'        | #  |
   //        ^                                     | #  |
   //        |                  .------------------' #  | Example classes
   //        |                  |                    #  |
   //   .---------.   .-------------------.          #  |
   //   | Derived |==>| Derived metaclass |=========="  |
   //   '---------'   '-------------------'            -'
   // The rest of the classes can now be defined normally.
   wrenInterpret(vm, NULL, coreModuleSource);
   vm->boolClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Bool"));
   PRIMITIVE(vm->boolClass, "toString", bool_toString);
   PRIMITIVE(vm->boolClass, "!", bool_not);
   vm->fiberClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Fiber"));
   PRIMITIVE(vm->fiberClass->obj.classObj, "new(_)", fiber_new);
   PRIMITIVE(vm->fiberClass->obj.classObj, "abort(_)", fiber_abort);
   PRIMITIVE(vm->fiberClass->obj.classObj, "current", fiber_current);
   PRIMITIVE(vm->fiberClass->obj.classObj, "suspend()", fiber_suspend);
   PRIMITIVE(vm->fiberClass->obj.classObj, "yield()", fiber_yield);
   PRIMITIVE(vm->fiberClass->obj.classObj, "yield(_)", fiber_yield1);
   PRIMITIVE(vm->fiberClass, "call()", fiber_call);
   PRIMITIVE(vm->fiberClass, "call(_)", fiber_call1);
   PRIMITIVE(vm->fiberClass, "error", fiber_error);
   PRIMITIVE(vm->fiberClass, "isDone", fiber_isDone);
   PRIMITIVE(vm->fiberClass, "transfer()", fiber_transfer);
   PRIMITIVE(vm->fiberClass, "transfer(_)", fiber_transfer1);
   PRIMITIVE(vm->fiberClass, "transferError(_)", fiber_transferError);
   PRIMITIVE(vm->fiberClass, "try()", fiber_try);
   PRIMITIVE(vm->fiberClass, "try(_)", fiber_try1);
   vm->fnClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Fn"));
   PRIMITIVE(vm->fnClass->obj.classObj, "new(_)", fn_new);
   PRIMITIVE(vm->fnClass, "arity", fn_arity);
   FUNCTION_CALL(vm->fnClass, "call()", fn_call0);
   FUNCTION_CALL(vm->fnClass, "call(_)", fn_call1);
   FUNCTION_CALL(vm->fnClass, "call(_,_)", fn_call2);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_)", fn_call3);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_)", fn_call4);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_)", fn_call5);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_)", fn_call6);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_)", fn_call7);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_)", fn_call8);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_)", fn_call9);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_)", fn_call10);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_,_)", fn_call11);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_,_,_)", fn_call12);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_,_,_,_)", fn_call13);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_,_,_,_,_)", fn_call14);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_,_,_,_,_,_)", fn_call15);
   FUNCTION_CALL(vm->fnClass, "call(_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_)", fn_call16);
   PRIMITIVE(vm->fnClass, "toString", fn_toString);
   vm->nullClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Null"));
   PRIMITIVE(vm->nullClass, "!", null_not);
   PRIMITIVE(vm->nullClass, "toString", null_toString);
   vm->numClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Num"));
   PRIMITIVE(vm->numClass->obj.classObj, "fromString(_)", num_fromString);
   PRIMITIVE(vm->numClass->obj.classObj, "infinity", num_infinity);
   PRIMITIVE(vm->numClass->obj.classObj, "nan", num_nan);
   PRIMITIVE(vm->numClass->obj.classObj, "pi", num_pi);
   PRIMITIVE(vm->numClass->obj.classObj, "tau", num_tau);
   PRIMITIVE(vm->numClass->obj.classObj, "largest", num_largest);
   PRIMITIVE(vm->numClass->obj.classObj, "smallest", num_smallest);
   PRIMITIVE(vm->numClass->obj.classObj, "maxSafeInteger", num_maxSafeInteger);
   PRIMITIVE(vm->numClass->obj.classObj, "minSafeInteger", num_minSafeInteger);
   PRIMITIVE(vm->numClass, "-(_)", num_minus);
   PRIMITIVE(vm->numClass, "+(_)", num_plus);
   PRIMITIVE(vm->numClass, "*(_)", num_multiply);
   PRIMITIVE(vm->numClass, "/(_)", num_divide);
   PRIMITIVE(vm->numClass, "<(_)", num_lt);
   PRIMITIVE(vm->numClass, ">(_)", num_gt);
   PRIMITIVE(vm->numClass, "<=(_)", num_lte);
   PRIMITIVE(vm->numClass, ">=(_)", num_gte);
   PRIMITIVE(vm->numClass, "&(_)", num_bitwiseAnd);
   PRIMITIVE(vm->numClass, "|(_)", num_bitwiseOr);
   PRIMITIVE(vm->numClass, "^(_)", num_bitwiseXor);
   PRIMITIVE(vm->numClass, "<<(_)", num_bitwiseLeftShift);
   PRIMITIVE(vm->numClass, ">>(_)", num_bitwiseRightShift);
   PRIMITIVE(vm->numClass, "abs", num_abs);
   PRIMITIVE(vm->numClass, "acos", num_acos);
   PRIMITIVE(vm->numClass, "asin", num_asin);
   PRIMITIVE(vm->numClass, "atan", num_atan);
   PRIMITIVE(vm->numClass, "cbrt", num_cbrt);
   PRIMITIVE(vm->numClass, "ceil", num_ceil);
   PRIMITIVE(vm->numClass, "cos", num_cos);
   PRIMITIVE(vm->numClass, "floor", num_floor);
   PRIMITIVE(vm->numClass, "-", num_negate);
   PRIMITIVE(vm->numClass, "round", num_round);
   PRIMITIVE(vm->numClass, "min(_)", num_min);
   PRIMITIVE(vm->numClass, "max(_)", num_max);
   PRIMITIVE(vm->numClass, "clamp(_,_)", num_clamp);
   PRIMITIVE(vm->numClass, "sin", num_sin);
   PRIMITIVE(vm->numClass, "sqrt", num_sqrt);
   PRIMITIVE(vm->numClass, "tan", num_tan);
   PRIMITIVE(vm->numClass, "log", num_log);
   PRIMITIVE(vm->numClass, "log2", num_log2);
   PRIMITIVE(vm->numClass, "exp", num_exp);
   PRIMITIVE(vm->numClass, "%(_)", num_mod);
   PRIMITIVE(vm->numClass, "~", num_bitwiseNot);
   PRIMITIVE(vm->numClass, "..(_)", num_dotDot);
   PRIMITIVE(vm->numClass, "...(_)", num_dotDotDot);
   PRIMITIVE(vm->numClass, "atan(_)", num_atan2);
   PRIMITIVE(vm->numClass, "pow(_)", num_pow);
   PRIMITIVE(vm->numClass, "fraction", num_fraction);
   PRIMITIVE(vm->numClass, "isInfinity", num_isInfinity);
   PRIMITIVE(vm->numClass, "isInteger", num_isInteger);
   PRIMITIVE(vm->numClass, "isNan", num_isNan);
   PRIMITIVE(vm->numClass, "sign", num_sign);
   PRIMITIVE(vm->numClass, "toString", num_toString);
   PRIMITIVE(vm->numClass, "truncate", num_truncate);
   // These are defined just so that 0 and -0 are equal, which is specified by
   // IEEE 754 even though they have different bit representations.
   PRIMITIVE(vm->numClass, "==(_)", num_eqeq);
   PRIMITIVE(vm->numClass, "!=(_)", num_bangeq);
   vm->stringClass = AS_CLASS(wrenFindVariable(vm, coreModule, "String"));
   PRIMITIVE(vm->stringClass->obj.classObj, "fromCodePoint(_)", string_fromCodePoint);
   PRIMITIVE(vm->stringClass->obj.classObj, "fromByte(_)", string_fromByte);
   PRIMITIVE(vm->stringClass, "+(_)", string_plus);
   PRIMITIVE(vm->stringClass, "[_]", string_subscript);
   PRIMITIVE(vm->stringClass, "byteAt_(_)", string_byteAt);
   PRIMITIVE(vm->stringClass, "byteCount_", string_byteCount);
   PRIMITIVE(vm->stringClass, "codePointAt_(_)", string_codePointAt);
   PRIMITIVE(vm->stringClass, "contains(_)", string_contains);
   PRIMITIVE(vm->stringClass, "endsWith(_)", string_endsWith);
   PRIMITIVE(vm->stringClass, "indexOf(_)", string_indexOf1);
   PRIMITIVE(vm->stringClass, "indexOf(_,_)", string_indexOf2);
   PRIMITIVE(vm->stringClass, "iterate(_)", string_iterate);
   PRIMITIVE(vm->stringClass, "iterateByte_(_)", string_iterateByte);
   PRIMITIVE(vm->stringClass, "iteratorValue(_)", string_iteratorValue);
   PRIMITIVE(vm->stringClass, "startsWith(_)", string_startsWith);
   PRIMITIVE(vm->stringClass, "toString", string_toString);
   vm->listClass = AS_CLASS(wrenFindVariable(vm, coreModule, "List"));
   PRIMITIVE(vm->listClass->obj.classObj, "filled(_,_)", list_filled);
   PRIMITIVE(vm->listClass->obj.classObj, "new()", list_new);
   PRIMITIVE(vm->listClass, "[_]", list_subscript);
   PRIMITIVE(vm->listClass, "[_]=(_)", list_subscriptSetter);
   PRIMITIVE(vm->listClass, "add(_)", list_add);
   PRIMITIVE(vm->listClass, "addCore_(_)", list_addCore);
   PRIMITIVE(vm->listClass, "clear()", list_clear);
   PRIMITIVE(vm->listClass, "count", list_count);
   PRIMITIVE(vm->listClass, "insert(_,_)", list_insert);
   PRIMITIVE(vm->listClass, "iterate(_)", list_iterate);
   PRIMITIVE(vm->listClass, "iteratorValue(_)", list_iteratorValue);
   PRIMITIVE(vm->listClass, "removeAt(_)", list_removeAt);
   PRIMITIVE(vm->listClass, "remove(_)", list_removeValue);
   PRIMITIVE(vm->listClass, "indexOf(_)", list_indexOf);
   PRIMITIVE(vm->listClass, "swap(_,_)", list_swap);
   vm->mapClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Map"));
   PRIMITIVE(vm->mapClass->obj.classObj, "new()", map_new);
   PRIMITIVE(vm->mapClass, "[_]", map_subscript);
   PRIMITIVE(vm->mapClass, "[_]=(_)", map_subscriptSetter);
   PRIMITIVE(vm->mapClass, "addCore_(_,_)", map_addCore);
   PRIMITIVE(vm->mapClass, "clear()", map_clear);
   PRIMITIVE(vm->mapClass, "containsKey(_)", map_containsKey);
   PRIMITIVE(vm->mapClass, "count", map_count);
   PRIMITIVE(vm->mapClass, "remove(_)", map_remove);
   PRIMITIVE(vm->mapClass, "iterate(_)", map_iterate);
   PRIMITIVE(vm->mapClass, "keyIteratorValue_(_)", map_keyIteratorValue);
   PRIMITIVE(vm->mapClass, "valueIteratorValue_(_)", map_valueIteratorValue);
   vm->rangeClass = AS_CLASS(wrenFindVariable(vm, coreModule, "Range"));
   PRIMITIVE(vm->rangeClass, "from", range_from);
   PRIMITIVE(vm->rangeClass, "to", range_to);
   PRIMITIVE(vm->rangeClass, "min", range_min);
   PRIMITIVE(vm->rangeClass, "max", range_max);
   PRIMITIVE(vm->rangeClass, "isInclusive", range_isInclusive);
   PRIMITIVE(vm->rangeClass, "iterate(_)", range_iterate);
   PRIMITIVE(vm->rangeClass, "iteratorValue(_)", range_iteratorValue);
   PRIMITIVE(vm->rangeClass, "toString", range_toString);
   ObjClass* systemClass = AS_CLASS(wrenFindVariable(vm, coreModule, "System"));
   PRIMITIVE(systemClass->obj.classObj, "clock", system_clock);
   PRIMITIVE(systemClass->obj.classObj, "gc()", system_gc);
   PRIMITIVE(systemClass->obj.classObj, "writeString_(_)", system_writeString);
   // While bootstrapping the core types and running the core module, a number
   // of string objects have been created, many of which were instantiated
   // before stringClass was stored in the VM. Some of them *must* be created
   // first -- the ObjClass for string itself has a reference to the ObjString
   // for its name.
   //
   // These all currently have a NULL classObj pointer, so go back and assign
   // them now that the string class is known.
   for (Obj* obj = vm->first; obj != NULL; obj = obj->next)
   {
     if (obj->type == OBJ_STRING) obj->classObj = vm->stringClass;
   }
 }
References AS_CLASS, WrenVM::boolClass, WrenVM::classClass, sObj::classObj, defineClass(), WrenVM::fiberClass, WrenVM::first, WrenVM::fnClass, FUNCTION_CALL, WrenVM::listClass, WrenVM::mapClass, WrenVM::modules, NULL, NULL_VAL, WrenVM::nullClass, WrenVM::numClass, sObjClass::obj, OBJ_STRING, OBJ_VAL, WrenVM::objectClass, PRIMITIVE, WrenVM::rangeClass, WrenVM::stringClass, wrenBindSuperclass(), wrenFindVariable(), wrenInterpret(), wrenMapSet(), wrenNewModule(), wrenPopRoot(), and wrenPushRoot().
Referenced by wrenNewVM().