ERIS CORE: Waveform Class Reference
Waveform Class Reference
#include <Waveform.h>
Public Member Functions
Waveform ()
uint_fast16_t bgColor (void)
virtual boolean forceTransitionNow (void)
void init (ILI9341_t3n tft)
void perFrame (ILI9341_t3n tft, FrameParams frameParams)
virtual void reset (ILI9341_t3n tft)
String title ()
virtual boolean willForceTransition (void)
Detailed Description
Definition at line 10 of file Waveform.h.
Constructor & Destructor Documentation
Waveform()
Waveform::Waveform () inline
Definition at line 12 of file Waveform.h.
 : BaseAnimation() {};
Member Function Documentation
bgColor()
uint_fast16_t Waveform::bgColor (void) virtual
Reimplemented from BaseAnimation.
Definition at line 29 of file Waveform.h.
{
     return _bgColor;
 }
Referenced by perFrame().
forceTransitionNow()
boolean BaseAnimation::forceTransitionNow (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 44 of file BaseAnimation.h.
{
     // Extend me
     return false;   // Default: SuperTFT will transition animations automatically
 }
init()
void Waveform::init (ILI9341_t3n tft) virtual
Reimplemented from BaseAnimation.
Definition at line 25 of file Waveform.h.
{
   _bgColor = tft.color565( 0, 0, 0x55 );
 }
References tft().
perFrame()
void Waveform::perFrame (ILI9341_t3n tft, FrameParams frameParams) virtual
Reimplemented from BaseAnimation.
Definition at line 37 of file Waveform.h.
{
   uint_fast16_t w = tft.width();
   uint_fast16_t h = tft.height();
   // fillRect: flickers pretty bad
   //tft.fillRect( 0, 0, w, h, LV_RED );
   // Prepare body color
   uint_fast8_t bright = (frameParams.audioPeak >> 1); // 0..512 -> 0..255
   uint_fast16_t bodyColor = tft.color565( bright, bright, 0 );  // yellow
   // Prepare body height
   uint_fast16_t h_2 = (h >> 1);
   uint_fast16_t bodyHeight = frameParams.audioMean * h;
   tft.drawFastVLine( _step, h_2-(bodyHeight>>1), bodyHeight, bodyColor );
   // Clear this column. Background should have a triangle wave effect
   uint_fast8_t bgBright = _colorPhase + _step;
   if( bgBright & 0x80 ) {
     bgBright = (0xff-bgBright) << 1;
   } else {
     bgBright <<= 1;
   }
   uint_fast16_t bgColor = tft.color565( 0, 0, bgBright );
   // Draw background color in the other pixels
   uint_fast16_t margin = (h - bodyHeight) >> 1;
   tft.drawFastVLine( _step, 0,          margin, bgColor );
   tft.drawFastVLine( _step, h - margin, margin, bgColor );
   // Advance to next line
   if( _step == 0 ) {
     _step = w - 1; // Restart drawing on right-hand size
     // After the screen is covered: Advance the background color
     _colorPhase += 3;
   } else {
     _step--;
   }
 }
References FrameParams::audioMean, FrameParams::audioPeak, bgColor(), and tft().
reset()
void BaseAnimation::reset (ILI9341_t3n tft) virtual inherited
Reimplemented in TwistyText.
Definition at line 32 of file BaseAnimation.h.
{
     // Extend me
 }
title()
String Waveform::title () virtual
Reimplemented from BaseAnimation.
Definition at line 33 of file Waveform.h.
{
     return "Waveform";
 }
willForceTransition()
boolean BaseAnimation::willForceTransition (void) virtual inherited
Reimplemented in TwistyText.
Definition at line 40 of file BaseAnimation.h.
{
     return false;   // Default: SuperTFT will transition animations automatically
 }
The documentation for this class was generated from the following file:
D:/brian/Dev/Eris/ERISCore/lib/ILI9341_t3n-master/examples/DemoSauce/Waveform.h