ERIS CORE: ERISCore/lib/SdFat-master/src/FatLib/FatDbg.cpp File Reference
FatDbg.cpp File Reference
#include "FatLib.h"
Functions
static uint16_t getLfnChar (DirLfn_t *ldir, uint8_t i)
static bool printFatDir (print_t *pr, DirFat_t *dir)
static void printHex (print_t *pr, uint16_t val)
static void printHex (print_t *pr, uint32_t val)
static void printHex (print_t *pr, uint8_t h)
static void printHex (print_t *pr, uint8_t w, uint16_t h)
template<typename Uint >
static void printHexLn (print_t *pr, Uint val)
Function Documentation
getLfnChar()
static uint16_t getLfnChar (DirLfn_t * ldir, uint8_t i) static
Copyright (c) 2011-2021 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 28 of file FatDbg.cpp.
{
   if (i < 5) {
     return getLe16(ldir->unicode1 + 2*i);
   } else if (i < 11) {
     return getLe16(ldir->unicode2 + 2*i - 10);
   } else if (i < 13) {
     return getLe16(ldir->unicode3 + 2*i - 22);
   }
   return 0;
 }
References getLe16(), DirLfn_t::unicode1, DirLfn_t::unicode2, and DirLfn_t::unicode3.
Referenced by printFatDir().
printFatDir()
static bool printFatDir (print_t * pr, DirFat_t * dir) static
Definition at line 94 of file FatDbg.cpp.
{
   DirLfn_t* ldir = reinterpret_cast<DirLfn_t*>(dir);
   if (!dir->name[0]) {
     pr->println(F("Unused"));
     return false;
   } else if (dir->name[0] == FAT_NAME_DELETED) {
     pr->println(F("Deleted"));
   } else if (isFileOrSubdir(dir)) {
     pr->print(F("SFN: "));
     for (uint8_t i = 0; i < 11; i++) {
       printHex(pr, dir->name[i]);
       pr->write(' ');
     }
     pr->write(' ');
     pr->write(dir->name, 11);
     pr->println();
     pr->print(F("attributes: 0X"));
     printHexLn(pr, dir->attributes);
     pr->print(F("caseFlags: 0X"));
     printHexLn(pr, dir->caseFlags);
     uint32_t fc = ((uint32_t)getLe16(dir->firstClusterHigh) << 16)
                  | getLe16(dir->firstClusterLow);
     pr->print(F("firstCluster: "));
     pr->println(fc, HEX);
     pr->print(F("fileSize: "));
     pr->println(getLe32(dir->fileSize));
   } else if (isLongName(dir)) {
     pr->print(F("LFN: "));
     for (uint8_t i = 0; i < 13; i++) {
       uint16_t c = getLfnChar(ldir, i);
       if (15 < c && c < 128) {
         pr->print(static_cast<char>(c));
       } else {
         pr->print("0X");
         pr->print(c, HEX);
       }
       pr->print(' ');
     }
     pr->println();
     pr->print(F("order: 0X"));
     pr->println(ldir->order, HEX);
     pr->print(F("attributes: 0X"));
     pr->println(ldir->attributes, HEX);
     pr->print(F("checksum: 0X"));
     pr->println(ldir->checksum, HEX);
   } else {
     pr->println(F("Other"));
   }
   pr->println();
   return true;
 }
References DirFat_t::attributes, DirLfn_t::attributes, DirFat_t::caseFlags, DirLfn_t::checksum, F, FAT_NAME_DELETED, DirFat_t::fileSize, DirFat_t::firstClusterHigh, DirFat_t::firstClusterLow, getLe16(), getLe32(), getLfnChar(), HEX, isFileOrSubdir(), isLongName(), DirFat_t::name, DirLfn_t::order, PrintBasic::print(), printHex(), printHexLn(), PrintBasic::println(), and PrintBasic::write().
Referenced by FatPartition::dmpDirSector().
printHex() [1/4]
static void printHex (print_t * pr, uint16_t val) static
Definition at line 58 of file FatDbg.cpp.
{
   bool space = true;
   for (uint8_t i = 0; i < 4; i++) {
     uint8_t h = (val >> (12 - 4*i)) & 15;
     if (h || i == 3) {
       space = false;
     }
     if (space) {
       pr->write(' ');
     } else {
       pr->print(h, HEX);
     }
   }
 }
References HEX, PrintBasic::print(), and PrintBasic::write().
printHex() [2/4]
static void printHex (print_t * pr, uint32_t val) static
Definition at line 73 of file FatDbg.cpp.
{
   bool space = true;
   for (uint8_t i = 0; i < 8; i++) {
     uint8_t h = (val >> (28 - 4*i)) & 15;
     if (h || i == 7) {
       space = false;
     }
     if (space) {
       pr->write(' ');
     } else {
       pr->print(h, HEX);
     }
   }
 }
References HEX, PrintBasic::print(), and PrintBasic::write().
printHex() [3/4]
static void printHex (print_t * pr, uint8_t h) static
Definition at line 39 of file FatDbg.cpp.
{
   if (h < 16) {
     pr->write('0');
   }
   pr->print(h, HEX);
 }
References HEX, PrintBasic::print(), and PrintBasic::write().
Referenced by FatPartition::dmpFat(), FatFile::dmpFile(), FatPartition::dmpSector(), printFatDir(), and printHexLn().
printHex() [4/4]
static void printHex (print_t * pr, uint8_t w, uint16_t h) static
Definition at line 46 of file FatDbg.cpp.
{
   char buf[5];
   char* ptr = buf + sizeof(buf);
   *--ptr = 0;
   for (uint8_t i = 0; i < w; i++) {
     char c = h & 0XF;
     *--ptr = c < 10 ? c + '0' : c + 'A' - 10;
     h >>= 4;
   }
   pr->write(ptr);
 }
References buf, and PrintBasic::write().
printHexLn()
template<typename Uint > static void printHexLn (print_t * pr, Uint val) static
Definition at line 89 of file FatDbg.cpp.
{
   printHex(pr, val);
   pr->println();
 }
References printHex(), and PrintBasic::println().
Referenced by printFatDir().