ERIS CORE: AudioSynthWaveformModulated2k::begin
begin() [1/2]
void AudioSynthWaveformModulated2k::begin (float t_amp, float t_freq, short t_type) inline inherited
Definition at line 177 of file eris_synth_waveform.h.
{
         amplitude(t_amp);
         frequency(t_freq);
         begin (t_type) ;
     }
References AudioSynthWaveformModulated2k::amplitude(), AudioSynthWaveformModulated2k::begin(), and AudioSynthWaveformModulated2k::frequency().