ERIS CORE: handleProgramChangeCallback
handleProgramChangeCallback()
void handleProgramChangeCallback (byte channel, byte program)
Definition at line 68 of file SvcMIDI.cpp.
{
     char msg[32];
     AppManager* am = AppManager::getInstance();
     SvcMIDI* m = (SvcMIDI*)am->getAppByName("MIDI");
     sprintf(msg,"PC %d %d",channel,program);
     m->publish(msg);
 }
References AppManager::getAppByName(), AppManager::getInstance(), m, and SvcMIDI::publish().
Referenced by SvcMIDI::midiInit().