ERIS CORE: handleControlChangeCallback
handleControlChangeCallback()
void handleControlChangeCallback (byte channel, byte control, byte value)
Definition at line 60 of file SvcMIDI.cpp.
{
     char msg[32];
     AppManager* am = AppManager::getInstance();
     SvcMIDI* m = (SvcMIDI*)am->getAppByName("MIDI");
     sprintf(msg,"CC %d %d %d",channel,control,value);
     m->publish(msg);
 }
References AppManager::getAppByName(), AppManager::getInstance(), m, and SvcMIDI::publish().
Referenced by SvcMIDI::midiInit().