ERIS CORE: handleClockCallback
handleClockCallback()
void handleClockCallback ()
Definition at line 83 of file SvcMIDI.cpp.
{
   unsigned long t = micros();
   last_midi_clock_rxtime = t;
   if(midi_clock_counter%2) usbMIDI.sendRealTime(midi::Clock);
   midi_clock_counter += 1;
   if(midi_clock_counter % 3 == 0) thirtysecond_note_count++;
   if(midi_clock_counter % 6 == 0) sixteenth_note_count++;
   if(midi_clock_counter % 12 == 0) {eighth_note_count++; last_eighth_note_time = t; eighth_note_tick ^= true;}
   if(midi_clock_counter % 24 == 0){
     quarter_note_tick ^= true;
     midi_clock_counter = 0;
     tempo = round(60.0 * (1.0 / ((float)(t - last_quarter_note_time) / 1000000.0)));
     if (tempo > 240.0) tempo = 240.0;
     AppManager* am = AppManager::getInstance();
     am->data->update("TEMPO",tempo);
     last_quarter_note_time = t;
     quarter_note_count += 1;
   }
 }
References AppManager::data, eighth_note_count, eighth_note_tick, AppManager::getInstance(), last_eighth_note_time, last_midi_clock_rxtime, last_quarter_note_time, midi_clock_counter, quarter_note_count, quarter_note_tick, sixteenth_note_count, tempo, thirtysecond_note_count, and SvcDataDictionary::update().
Referenced by SvcMIDI::midiInit().