ERIS CORE: MinimumSerial Class Reference
MinimumSerial Class Reference
mini serial class for the SdFat library.
#include <MinimumSerial.h>
Public Member Functions
int available ()
void begin (uint32_t baud)
void clearWriteError ()
void flush ()
int getWriteError ()
operator bool ()
size_t print (char c)
size_t print (const __FlashStringHelper *str)
size_t print (const char *str)
size_t print (double n, uint8_t prec=2)
size_t print (int n, uint8_t base=10)
size_t print (long n, uint8_t base=10)
size_t print (signed char n, uint8_t base=10)
size_t print (unsigned char n, uint8_t base=10)
size_t print (unsigned int n, uint8_t base=10)
size_t print (unsigned long n, uint8_t base=10)
size_t println ()
size_t println (char c)
size_t println (const __FlashStringHelper *str)
size_t println (const char *str)
size_t println (double n, uint8_t prec=2)
size_t println (int n, uint8_t base=10)
size_t println (long n, uint8_t base=10)
size_t println (signed char n, uint8_t base=10)
size_t println (unsigned char n, uint8_t base=10)
size_t println (unsigned int n, uint8_t base=10)
size_t println (unsigned long n, uint8_t base=10)
int read ()
size_t write (const char *buffer, size_t size)
size_t write (const char *buffer, size_t size)
size_t write (const char *str)
size_t write (const char *str)
virtual size_t write (const uint8_t *buffer, size_t size)
virtual size_t write (const uint8_t *buffer, size_t size)
size_t write (uint8_t b)
virtual size_t write (uint8_t b)=0
Protected Member Functions
void setWriteError (int err=1)
Private Member Functions
size_t printDouble (double n, uint8_t prec)
size_t printNum (unsigned long n, uint8_t base)
Private Attributes
int m_error
Detailed Description
mini serial class for the SdFat library.
Definition at line 37 of file MinimumSerial.h.
Member Function Documentation
available()
int MinimumSerial::available ()
Returns
one if data is available.
begin()
void MinimumSerial::begin (uint32_t baud)
Set baud rate for serial port zero and enable in non interrupt mode. Do not call this function if you use another serial library.
Parameters
[in] baud rate
clearWriteError()
void PrintBasic::clearWriteError () inline inherited
Definition at line 57 of file PrintBasic.h.
{
     setWriteError(0);
   }
References PrintBasic::setWriteError().
flush()
void MinimumSerial::flush ()
Wait for write done.
getWriteError()
int PrintBasic::getWriteError () inline inherited
Definition at line 60 of file PrintBasic.h.
                       {
     return m_error;
   }
References PrintBasic::m_error.
operator bool()
MinimumSerial::operator bool () inline
Returns
true for hardware serial
Definition at line 40 of file MinimumSerial.h.
 {return true;}
print() [1/10]
size_t PrintBasic::print (char c) inline inherited
Definition at line 63 of file PrintBasic.h.
{
     return write(c);
   }
References PrintBasic::write().
Referenced by ExFatPartition::checkUpcase(), ExFatPartition::dmpCluster(), SdBase< Vol >::errorHalt(), SdBase< Vol >::errorPrint(), PrintBasic::print(), ExFatPartition::printDir(), printDirBitmap(), printDirFile(), printDirLabel(), printDirName(), printDirStream(), printDirUpcase(), PrintBasic::printDouble(), printExFatBoot(), ExFatPartition::printFat(), printFatDir(), SdBase< Vol >::printFatType(), printHex(), PrintBasic::println(), printMbr(), SdBase< Vol >::printSdError(), printSdErrorSymbol(), printSdErrorText(), ExFatPartition::printUpcase(), and ExFatPartition::printVolInfo().
print() [2/10]
size_t PrintBasic::print (const __FlashStringHelper * str) inline inherited
Definition at line 69 of file PrintBasic.h.
{
 #ifdef __AVR__
   PGM_P p = reinterpret_cast<PGM_P>(str);
   size_t n = 0;
   for (uint8_t c; (c = pgm_read_byte(p + n)) && write(c); n++) {}
   return n;
 #else  // __AVR__
   return print(reinterpret_cast<const char *>(str));
 #endif  // __AVR__
   }
References p, pgm_read_byte, PrintBasic::print(), and PrintBasic::write().
print() [3/10]
size_t PrintBasic::print (const char * str) inline inherited
Definition at line 66 of file PrintBasic.h.
{
     return write(str);
   }
References PrintBasic::write().
print() [4/10]
size_t PrintBasic::print (double n, uint8_t prec = 2) inline inherited
Definition at line 86 of file PrintBasic.h.
{
     return printDouble(n, prec);
   }
References PrintBasic::printDouble().
print() [5/10]
size_t PrintBasic::print (int n, uint8_t base = 10) inline inherited
Definition at line 95 of file PrintBasic.h.
{
     return print((long)n, base);
   }
References PrintBasic::print().
print() [6/10]
size_t PrintBasic::print (long n, uint8_t base = 10) inherited
Copyright (c) 2011-2020 Bill Greiman This file is part of the SdFat library for SD memory cards.
MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 28 of file PrintBasic.cpp.
{
   if (n < 0 && base == 10) {
     return print('-') + printNum(-n, base);
   }
   return printNum(n, base);
 }
References PrintBasic::print(), and PrintBasic::printNum().
print() [7/10]
size_t PrintBasic::print (signed char n, uint8_t base = 10) inline inherited
Definition at line 89 of file PrintBasic.h.
{
     return print((long)n, base);
   }
References PrintBasic::print().
print() [8/10]
size_t PrintBasic::print (unsigned char n, uint8_t base = 10) inline inherited
Definition at line 92 of file PrintBasic.h.
{
     return print((unsigned long)n, base);
   }
References PrintBasic::print().
print() [9/10]
size_t PrintBasic::print (unsigned int n, uint8_t base = 10) inline inherited
Definition at line 98 of file PrintBasic.h.
{
     return print((unsigned long)n, base);
   }
References PrintBasic::print().
print() [10/10]
size_t PrintBasic::print (unsigned long n, uint8_t base = 10) inline inherited
Definition at line 102 of file PrintBasic.h.
{
     return printNum(n, base);
   }
References PrintBasic::printNum().
printDouble()
size_t PrintBasic::printDouble (double n, uint8_t prec) private inherited
Definition at line 49 of file PrintBasic.cpp.
{
   // Max printable 32-bit floating point number. AVR uses 32-bit double.
   const double maxfp = static_cast<double>(0XFFFFFF00UL);
   size_t rtn = 0;
   if (isnan(n)) {
     return write("NaN");
   }
   if (n < 0) {
     n = -n;
     rtn += print('-');
   }
   if (isinf(n)) {
     return rtn + write("Inf");
   }
   if (n > maxfp) {
     return rtn + write("Ovf");
   }
   double round = 0.5;
   for (uint8_t i  = 0; i < prec; ++i) {
     round *= 0.1;
   }
   n += round;
   uint32_t whole = (uint32_t)n;
   rtn += print(whole);
   if (prec) {
     rtn += print('.');
     double fraction = n - static_cast<double>(whole);
     for (uint8_t i = 0; i < prec; i++) {
       fraction *= 10.0;
       uint8_t digit = fraction;
       rtn += print(digit);
       fraction -= digit;
     }
   }
   return rtn;
 }
References PrintBasic::print(), and PrintBasic::write().
Referenced by PrintBasic::print().
println() [1/11]
size_t PrintBasic::println () inline inherited
Definition at line 105 of file PrintBasic.h.
                    {
     return write("\r\n");
   }
References PrintBasic::write().
Referenced by PrintBasic::println().
println() [2/11]
size_t PrintBasic::println (char c) inline inherited
Definition at line 108 of file PrintBasic.h.
{
     return write(c) + println();
   }
References PrintBasic::println(), and PrintBasic::write().
println() [3/11]
size_t PrintBasic::println (const __FlashStringHelper * str) inline inherited
Definition at line 79 of file PrintBasic.h.
{
 #ifdef __AVR__
     return print(str) + println();
 #else  // __AVR__
     return println(reinterpret_cast<const char *>(str));
 #endif  // __AVR__
   }
References PrintBasic::print(), and PrintBasic::println().
Referenced by ExFatPartition::checkUpcase(), ExFatPartition::dmpBitmap(), ExFatPartition::dmpCluster(), dmpDirData(), FatPartition::dmpDirSector(), ExFatPartition::dmpFat(), FatPartition::dmpFat(), FatPartition::dmpRootDir(), ExFatPartition::dmpSector(), FatPartition::dmpSector(), SdBase< Vol >::errorHalt(), SdBase< Vol >::errorPrint(), SdBase< Vol >::initErrorHalt(), printDateTime(), ExFatPartition::printDir(), printDirBitmap(), printDirFile(), printDirLabel(), printDirName(), printDirStream(), printDirUpcase(), printExFatBoot(), ExFatPartition::printFat(), printFatDir(), printHex64(), printHexLn(), println64(), printMbr(), SdBase< Vol >::printSdError(), ExFatPartition::printUpcase(), and ExFatPartition::printVolInfo().
println() [4/11]
size_t PrintBasic::println (const char * str) inline inherited
Definition at line 111 of file PrintBasic.h.
{
     return print(str) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [5/11]
size_t PrintBasic::println (double n, uint8_t prec = 2) inline inherited
Definition at line 114 of file PrintBasic.h.
{
     return print(n, prec) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [6/11]
size_t PrintBasic::println (int n, uint8_t base = 10) inline inherited
Definition at line 123 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [7/11]
size_t PrintBasic::println (long n, uint8_t base = 10) inline inherited
Definition at line 129 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [8/11]
size_t PrintBasic::println (signed char n, uint8_t base = 10) inline inherited
Definition at line 117 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [9/11]
size_t PrintBasic::println (unsigned char n, uint8_t base = 10) inline inherited
Definition at line 120 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [10/11]
size_t PrintBasic::println (unsigned int n, uint8_t base = 10) inline inherited
Definition at line 126 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
println() [11/11]
size_t PrintBasic::println (unsigned long n, uint8_t base = 10) inline inherited
Definition at line 132 of file PrintBasic.h.
{
     return print(n, base) + println();
   }
References PrintBasic::print(), and PrintBasic::println().
printNum()
size_t PrintBasic::printNum (unsigned long n, uint8_t base) private inherited
Definition at line 34 of file PrintBasic.cpp.
{
   const uint8_t DIM = 8*sizeof(long);
   char buf[DIM];
   char *str = &buf[DIM];
   if (base < 2) return 0;
   do {
     char c = n%base;
     n /= base;
     *--str = c + (c < 10 ? '0' : 'A' - 10);
   } while (n);
   return write(str, &buf[DIM] - str);
 }
References buf, and PrintBasic::write().
Referenced by PrintBasic::print().
read()
int MinimumSerial::read ()
Unbuffered read
Returns
-1 if no character is available or an available character.
setWriteError()
void PrintBasic::setWriteError (int err = 1) inline protected inherited
Definition at line 152 of file PrintBasic.h.
{
     m_error = err;
   }
References PrintBasic::m_error.
Referenced by PrintBasic::clearWriteError().
write() [1/8]
size_t PrintBasic::write (const char * buffer, size_t size) inline inherited
Definition at line 147 of file PrintBasic.h.
{
     return write((const uint8_t*)buffer, size);
   }
References PrintBasic::write().
write() [2/8]
size_t PrintBasic::write inline
Definition at line 147 of file PrintBasic.h.
{
     return write((const uint8_t*)buffer, size);
   }
write() [3/8]
size_t PrintBasic::write (const char * str) inline inherited
Definition at line 135 of file PrintBasic.h.
{
     return write(str, strlen(str));
   }
Referenced by ExFatPartition::checkUpcase(), dmpDirData(), ExFatPartition::dmpFat(), FatPartition::dmpFat(), FatFile::dmpFile(), ExFatPartition::dmpSector(), FatPartition::dmpSector(), fsPrintDate(), fsPrintDateTime(), fsPrintTime(), fsPrintTimeZone(), ExFatFile::ls(), FatFile::ls(), PrintBasic::print(), printDirLabel(), PrintBasic::printDouble(), printExFatBoot(), ExFatPartition::printFat(), printFatDir(), ExFatFile::printFileSize(), FatFile::printFileSize(), printHex(), PrintBasic::println(), printMbr(), ExFatFile::printName7(), FatFile::printName7(), ExFatFile::printName8(), FatFile::printName8(), PrintBasic::printNum(), FatFile::printSFN(), ExFatPartition::printUpcase(), and PrintBasic::write().
write() [4/8]
size_t PrintBasic::write inline
Definition at line 135 of file PrintBasic.h.
{
     return write(str, strlen(str));
   }
write() [5/8]
virtual size_t PrintBasic::write (const uint8_t * buffer, size_t size) inline virtual inherited
Reimplemented in StreamFile< BaseFile, PosType >, StreamFile< ExFatFile, uint64_t >, StreamFile< FsBaseFile, uint64_t >, and StreamFile< FatFile, uint32_t >.
Definition at line 140 of file PrintBasic.h.
{
     size_t i;
     for (i = 0; i < size; i++) {
       if (!write(buffer[i])) break;
     }
     return i;
   }
References PrintBasic::write().
write() [6/8]
virtual size_t PrintBasic::write inline
Definition at line 140 of file PrintBasic.h.
{
     size_t i;
     for (i = 0; i < size; i++) {
       if (!write(buffer[i])) break;
     }
     return i;
   }
write() [7/8]
size_t MinimumSerial::write (uint8_t b) virtual
Unbuffered write
Parameters
[in] b byte to write.
Returns
1
Implements PrintBasic.
write() [8/8]
virtual size_t PrintBasic::write
Member Data Documentation
m_error
int PrintBasic::m_error private inherited
Definition at line 159 of file PrintBasic.h.
Referenced by PrintBasic::getWriteError(), and PrintBasic::setWriteError().
The documentation for this class was generated from the following file:
MinimumSerial.h